### ISSUE TITLE
Consider making shaka.media.DrmEngine an optional component for ~13kb savings.

### ISSUE THREAD

**Issue by dalecurtis** [shaka-project/shaka-player#1017]
As titled, it's 50+kb of JS and many sites may not be using any DRM, so a 10% savings in unzipped package size seems kind of nice. Here are the numbers after a hacky removal:

HLS or DASH only: ~104kb, ~34kb gzipped
HLS or DASH w/o DrmEngine: 91kb, ~31kb gzipped

**Comment by vaage** [comment]
@joeyparrish This looks like a fair request. I feel it is enough work to be labeled as an enhancement. Can you schedule it? I would be happy to take this one on.

**Comment by joeyparrish** [comment]
Sounds good.  Tentatively scheduled for v2.3, but could easily slip as it is low priority compared to other features.

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
