### ISSUE TITLE
Detect encoder failures on live streams

### ISSUE THREAD

**Issue by kuznetcoff777** [shaka-project/shaka-player#1031]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate issues**:yes

**What version of Shaka Player are you using**:2.2.1

**Can you reproduce the issue with our latest release version**: yes

**Can you reproduce the issue with the latest code from `master`**: yes

**Are you using the demo app or your own custom app**: custom

**If custom app, can you reproduce the issue using our demo app**: have no ablility

**What browser and OS are you using**: chrome  60.0.3112.113

**What are the manifest and license server URIs**: sent to mail
*(you can send the URIs to <shaka-player-issues@google.com> instead, but please use GitHub and the template for the rest)*

**What did you do?** Live encoder stopped work as expected because of disk failure (disk remounted as read-only), so no new segments and no updates of mpd file, it freezed. I opened stream in player and nothing happened, only requests to mpd file and licenser server. I suppose it happens because of freezed publish time. I attempted to repeat situation, but encoder works normally and i just copied mpd file and attemped to play it, so situation was the same. I suppose there must be some validation or some error in console so we can find it and attempt to play backup stream. But at the moment all looks like it should play but nothing happens.

**Comment by kuznetcoff777** [comment]
Hi! Any success?

**Comment by joeyparrish** [comment]
@kuznetcoff777, if the encoder stops updating the live manifest, we have no way to detect that right now.  I would like to be able to detect this situation and issue an error, but I'm not sure how best to do that.

If there is any guidance in DASH or DASH IOP, I would be grateful for pointers.

**Comment by joeyparrish** [comment]
It seems that `publishTime` might be part of the solution, but a quick scan of the latest IOP did not turn up an obvious solution.

> MPD@publishTime provides versioning functionality: MPD with later publication times include all information that was included all MPDs with earlier publication times.

Perhaps if `publishTime` isn't changing for a significant amount of time, we could combine that with some other signal to guess that the encoder is offline.

**Comment by kuznetcoff777** [comment]
Maybe it is necessary to make some configurable parameter, some delta, for example if it = 60, then if now_date - piblishtime>60, then error

**Comment by kuznetcoff777** [comment]
M?

**Comment by kuznetcoff777** [comment]
Guys, it is pretty critical thing, cause now our player have main and backup playlist, and if main playlist stalls, player cannot turn to backup, because of it does not get that something wrong with main playlist.

**Comment by joeyparrish** [comment]
@kuznetcoff777, you are welcome to submit a pull request for this if you need a solution sooner than we can provide.

The best idea we have come up with in this thread so far is to fail when `publishTime` stops updating for some amount of time.  You would need to look into lib/dash/dash_parser.js to add the check and lib/util/error.js to create a new error code.  If you want the timeout to be configurable, you would also need to look at externs/shaka/player.js to add a field to shakaExtern.DashManifestConfiguration and lib/player.js to set the default.

**Comment by kuznetcoff777** [comment]
With great pleasure, but i do not know your code as well as you are. I just wanted to know if any thoughts appeared, last thing was your question. I think it must be configurable, because:
1-publish time is constant when it is VOD
2-i saw some encoders, which do not refresh publish time (or refreshes very seldom)

**Comment by joeyparrish** [comment]
Yes, I think some configurable parameter makes sense.

**Comment by avelad** [comment]
We are already detecting potential coding issues at https://github.com/shaka-project/shaka-player/blob/main/lib/media/media_source_engine.js#L869, I consider this issue resolved
