### ISSUE TITLE
Could Shaka inject MediaKeys polyfills as dependencies, instead of polyfilling the browser?

### ISSUE THREAD

**Issue by chrisfillmore** [shaka-project/shaka-player#1032]
The project I work on acts as middleware between client UI applications and two things: players, and DRM service providers. We support multiple players.

Additionally, one of the DRM services we integrate with requires a dummy license challenge in order to conduct "device activation". So I need to know what EME API's are available in the browser.

The sum of this is, I have my own version of this code:

```
if (navigator.requestMediaKeySystemAccess &&
      MediaKeySystemAccess.prototype.getConfiguration) {
  ...
} else if (HTMLMediaElement.prototype.webkitGenerateKeyRequest) {
  ...
} else if (HTMLMediaElement.prototype.generateKeyRequest) {
  ...
} else if (window.MSMediaKeys) {
  ...
} else {
  ...
}
```

The trouble is, my detection is complicated by the fact that Shaka polyfills the browser. Under most circumstances the polyfills are effective and I don't have a problem. But I need to be careful about the order of my feature-detection to be sure I am checking for older API's first. This is the case specifically in Safari 10+. If I checked for `requestMediaKeySystemAccess` first, I would see that it exists, but it would not work because Shaka has installed the no-op polyfill. (We make no restrictions on how many different players the client application uses. If they want to use our Safari player for HLS-FP, then use Shaka to play clear DASH, that's their prerogative.)

Tizen 2017 TV's support both legacy 0.1b EME and the modern spec, which means that when I'm doing my detection, I need to check for Tizen 2017 and say no, don't use 0.1b, use `requestMediaKeySystemAccess`.

I understand this is a broader architectural concern, but I thought I would plant the idea. If Shaka could inject its dependencies locally into drm_engine, it could spare its' users some tricky feature detection.

**Comment by joeyparrish** [comment]
This is a thing we could do, but I'm not prepared to make such a fundamental shift in our philosophy/architecture right now.  I'm tentatively adding this to the backlog, but I'm not certain if we will do this.  We need time to think through the ramifications.

In the mean time, have you considered waiting to install polyfills until right before you set up Shaka Player?  You could do your platform detection first, then choose a player, then install polyfills if it's Shaka, then instantiate a `shaka.Player` instance.  Would this help?

Another option would be to install polyfills individually instead of using `shaka.polyfill.installAll()`.  You can call each one when you wish, such as:

```js
shaka.polyfill.Fullscreen.install();
shaka.polyfill.IndexedDB.install();
shaka.polyfill.InputEvent.install();
shaka.polyfill.MathRound.install();

// ... wait ...

if (timeToChooseAPlayer) {
  shaka.polyfill.Promise.install();
  shaka.polyfill.MediaSource.install();
  shaka.polyfill.MediaKeys.install();

  if (shaka.Player.isBrowserSupported()) {
    var player = new shaka.Player();
  } else {
    // ...
  }
}
```

Do these suggestions help?

**Comment by chrisfillmore** [comment]
Our architecture is intentionally generic, so that the library can be reused across multiple projects. Players and DRM service integrations are decoupled and have no insight into each others' lifecycles. 

The primary culprit in this complex flow is the "device activation" requirement for one of our service integrations. This flow may be invoked in a variety of circumstances, both before and after playback has happened (and polyfills have been installed). It depends on user behaviour, the response from the activation server, etc etc.

Thanks for the suggestion.

**Comment by avelad** [comment]
Anyone interested in this? If no one responds to the thread in 7 days, it will be closed automatically. Thank you!
