### ISSUE TITLE
Add FAQ entry about DASH startNumber

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1097]
A question came up recently about the default value for startNumber (zero vs one) and whether or not zero is an acceptable value.  It might be useful to add a FAQ entry explaining our position and linking to previous discussions on the subject.

**Comment by devil-cyber** [comment]
hey can I work on this issue

**Comment by joeyparrish** [comment]
Sure thing!

**Comment by theodab** [comment]
I was going to write an FAQ entry about this.
However, on reflection, is something that was asked about once in 2017 really a "frequently" asked question?
I'm already worried that our FAQ might be getting long enough that people might not want to read it, so I think I'll just close this six-year-old issue.
