### ISSUE TITLE
Add a tutorial for developing for Chromecast

### ISSUE THREAD

**Issue by sergioavazquez** [shaka-project/shaka-player#1142]
I'm working on integrating Shaka with Chromecast in my own project. I wanted to start with your apps's receiver code and customize it.

I'm going to be using widevine, and I read I need to develop a custom receiver for that, since shaka's demo receiver is already working with it, I'm thinking on leveraging that. 

I noticed you have a demo receiver on the repository but I couldn't make it work. I already have everything set up for developing a Chromecast receiver. Meaning I accessed Google Cast SDK Developer Console and set it up so when I cast within my app, I see the custom receiver on the screen.

Is there a CDN for the compiled version: `../../dist/receiver.compiled.js` ? I couldn't find that file on the repository or the npm version. 
I added `receiver_app.js` as well as `controls.js` and demo_utils` instead but it doesn't work

I couldn't find any docs on how to set shaka's demo receiver up and running. I tried using Chromecast's default receiver instead (CC_APP_ID > CC1AD845) but it does not work either.

I also noticed there's a new receiver SDK: https://developers.google.com/cast/docs/caf_receiver_basic are you planing on migrating soon? What about the sender?

Thanks in advance,

**Comment by TheModMaker** [comment]
I am not that familiar with Chromecast development, but I will help as I can. You can get hosted versions of the library at CDNJS (https://cdnjs.com/libraries/shaka-player).  We don't provide hosted versions of the receiver, that is up to the app.  The compiled receiver is only in the `master` branch since it is not in a release yet.  You will have to compile it manually using `build/build.py` or `build/all.py`.  This will compile the source files for the receiver into that bundle file.

Or, alternatively you could load the receiver app without compiling.  It should only need the compiled library and then: `demo/common/assets.js`, `demo/common/controls.js`, `demo/common/demo_utils.js`, and `demo/cast_receiver/receiver_app.js`.  If you are just editing `demo/cast_receiver/index.html`, you can just load those files and remove the `load.js` file since that is just a bootstrapping script.

On the sender side, you should use an instance of [shaka.cast.CastProxy](https://shaka-player-demo.appspot.com/docs/api/shaka.cast.CastProxy.html).  This will handle connection to the receiver and will proxy any calls to the Player through to the receiver (e.g. calling `player.load()` on the sender will load the asset on the receiver).

We only support using a custom receiver, trying to use the default receiver won't work.

We should provide tutorials on how to setup Chromecast support.

**Comment by sergioavazquez** [comment]
Thanks @TheModMaker! I was able to make it work importing the non compiled scripts. Apparently `assets.js` is not needed. I tried switching contents and it works without it. I'd really appreciate info on how to further integrate Chromecast. I'd love to be able to send custom messages with content's name, logo, etc.
I got the player and video from the cast_proxy:
```
 const video_ = castProxy_.getVideo();
 const player_ = castProxy_.getPlayer();
```
Then I'm using that player's instance to load the asset and the video to play/pause. Is this what you were referring to?
 Is there a built in method for sending custom messages? if not, how can I integrate one with current's cast_proxy?

**Comment by TheModMaker** [comment]
> Then I'm using that player's instance to load the asset and the video to play/pause. Is this what you were referring to?

Correct.  Using that player and video instance will proxy to the remote object or will proxy to the local versions when not casting.

> Is there a built in method for sending custom messages? if not, how can I integrate one with current's cast_proxy?

We don't have any way to do it, but you should be able to use the normal [cast messaging](https://developers.google.com/cast/docs/custom_receiver#messages).  We use a special namespace for messaging, so it shouldn't conflict with your messages.

**Comment by legrengo** [comment]
sergioavazquez

> Merci @TheModMaker ! J'ai été capable de le faire fonctionner en important les scripts non compilés. Apparemment `assets.js`n'est pas nécessaire. J'ai essayé de changer de contenu et ça marche sans ça. J'aimerais vraiment savoir comment intégrer davantage Chromecast. J'aimerais pouvoir envoyer des messages personnalisés avec le nom du contenu, le logo, etc. 
> J'ai le lecteur et la vidéo de cast_proxy:
> 
> ```
>  const video_ = castProxy_.getVideo();
>  const player_ = castProxy_.getPlayer();
> ```
> Ensuite, j'utilise l'instance de ce joueur pour charger l'actif et la vidéo pour lire / mettre en pause. Est-ce ce que vous avez mentionné? 
> Existe-t-il une méthode intégrée pour envoyer des messages personnalisés? Si non, comment puis-je en intégrer un avec cast_proxy?

sergioavazquez

> I'm working on integrating Shaka with Chromecast in my own project. I wanted to start with your apps's receiver code and customize it.
> 
> I'm going to be using widevine, and I read I need to develop a custom receiver for that, since shaka's demo receiver is already working with it, I'm thinking on leveraging that.
> 
> I noticed you have a demo receiver on the repository but I couldn't make it work. I already have everything set up for developing a Chromecast receiver. Meaning I accessed Google Cast SDK Developer Console and set it up so when I cast within my app, I see the custom receiver on the screen.
> 
> Is there a CDN for the compiled version: `../../dist/receiver.compiled.js` ? I couldn't find that file on the repository or the npm version.
> I added `receiver_app.js` as well as `controls.js` and demo_utils` instead but it doesn't work
> 
> I couldn't find any docs on how to set shaka's demo receiver up and running. I tried using Chromecast's default receiver instead (CC_APP_ID > CC1AD845) but it does not work either.
> 
> I also noticed there's a new receiver SDK: https://developers.google.com/cast/docs/caf_receiver_basic are you planing on migrating soon? What about the sender?
> 
> Thanks in advance,


hello TheModMaker,
 I am a beginner in the circles

have you managed to make it work ??
I do not know what started

**Comment by garethgeorge** [comment]
Likewise have questions about this -- is there any clear guide at the moment on how to get chrome cast support working when using shaka player? 

The current top google result is this: https://github.com/google/shaka-player/blob/master/docs/design/chromecast.md but it appears to be out of date.

**Comment by davidloiret** [comment]
Hello!
Are you planning to make CastProxy & CastSender compatible with the new caf receiver (currently it seems to only work with the v2 receiver)?

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
