### ISSUE TITLE
CastReceiver integration tests

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1162]
We currently have unit tests on shaka.cast.CastReceiver, but no integration tests.  We should write integration tests that integrate CastReceiver with Player.  This could help catch bugs like #1128 (uncaught receiver-side exceptions) sooner by simulating the environment of a receiver app.

These tests could be run on a single device, which means better automation than we could get from actually casting from one device to another.

**Comment by joeyparrish** [comment]
We now have one integration test for CastReceiver, in which we delay various stages of load() to make sure the sender continues to get updates.  This helped catch and solve some runtime exceptions.

We will leave this open until we write some general integration tests for CastReceiver, unrelated to any known bug, along the lines of the playback tests we have in `player_integration.js`.  At that point, we will have reasonable general coverage, and can close this issue.  Regression tests can be added to `cast_receiver_integration.js` for future bugs.

**Comment by avelad** [comment]
@joeyparrish  I'm not sure we add it, since we want to do https://github.com/shaka-project/shaka-player/issues/4214 in the future

**Comment by joeyparrish** [comment]
Agreed.  Thanks!
