### ISSUE TITLE
CastUtils TimeRanges test sometimes times out

### ISSUE THREAD

**Issue by theodab** [shaka-project/shaka-player#1215]
`CastUtils TimeRanges deserialize into equivalent objects` sometimes times out when I run the full test suite. I've seen this happen a lot while testing other things, but annoyingly I am having a very hard time reproducing it on purpose. I ran the `CastUtils` tests 10k times in a row and eventually it was reproduced; notably, once it started happening (~5k runs in) it suddenly started happening multiple times in a row, which suggests it involves some kind of external state.
That particular test does not have any asynchronous parts, but the beforeEach and afterEach attached to it do. In particular, the beforeEach involves loading file assets and appending a buffer to media source engine, so it might be some file I/O problem.

**Comment by avelad** [comment]
@joeyparrish  I'm not sure we add it, since we want to do https://github.com/shaka-project/shaka-player/issues/4214 in the future

**Comment by joeyparrish** [comment]
Agreed.  Also this hasn't been an issue in recent momentary.
