### ISSUE TITLE
Enqueue emsg events and publish when the playhead advances past startTime

### ISSUE THREAD

**Issue by chrisfillmore** [shaka-project/shaka-player#1268]
Spun off of https://github.com/google/shaka-player/issues/1169#issuecomment-349384099. I can submit a PR for this.

This is behaviour we implement in our app so that emsg events are published to our ad SDK at the correct time. I think it makes sense to have it in Shaka.

Requirements:
- Instead of immediately publishing emsg events when emsg boxes are parsed, Shaka should put these events in a queue.
- Shaka should poll the video element for `currentTime` and publish any emsg events in the queue which have `startTime <= currentTime`.
- Reusing the existing polling behaviour from EventStream is desirable.

Should the polling interval be configurable? It probably doesn't need to be but I wonder if there are use cases where people need to have their emsg events immediately upon parsing. But then, would you also want the EventStream polling to be configurable? I assume not.

**Comment by TheModMaker** [comment]
I don't think it needs to be configurable.  I also think we should do both.  We can still fire the `emsg` event once we see a box and also be polling the time and fire the `timelineregionenter` and `timelineregionexit` events when the playhead reaches the time.  This allows the app to handle the `emsg` boxes themselves if they want to.
