### ISSUE TITLE
Add text style support to SimpleTextDisplayer

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1289]
We are not currently extracting style information from subtitle formats.  We also do not manipulate CSS from the default text displayer.

We could extract this information into `shaka.text.Cue` and pass it to the text displayer.  The default displayer could then programatically style `::cue` to set the appropriate properties.

**Comment by ismena** [comment]
We do extract some style info. Shaka Cue has background color, color, font weight, family, style and size properties as well as line height and wrap option.

Currently our default text displayer doesn't use this info, so we can certainly work on that.

**Comment by joeyparrish** [comment]
I stand corrected.  Thanks!

**Comment by toschlog** [comment]
Yes, yes, please add this!

**Comment by avelad** [comment]
We already support <b>, <I>, <u> tags and colors.

We are closing this issue, if anyone is interested in supporting more styles, please open an issue with the specific details.

Thanks!
