### ISSUE TITLE
Convert TTML extent height to VTTRegion lines?

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1290]
Is it possible to convert the extent height in TTML into the `lines` field in the [VTTRegion interface](https://www.w3.org/TR/webvtt1/#the-vttregion-interface)?

If not, should we discuss extending the VTTRegion API to allow more control over the height, perhaps in terms of percentage?

**Comment by avelad** [comment]
With UITextDisplayer this is no longer necessary I think. @joeyparrish can we close this issue?

**Comment by joeyparrish** [comment]
Agreed.  This predates UITextDisplayer.  We gave up on adding to the VTTCue API once we found out that even Chrome wasn't interested in fully implementing the existing VTTCue API.
