### ISSUE TITLE
Add support for EXT-X-GAP

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#1308]
Is it possible add support to EXT-X-GAP?

https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.4.7

The EXT-X-GAP tag indicates that the segment URL to which it applies  does not contain media data and SHOULD NOT be loaded by clients. It  applies only to the next Media Segment.

**Comment by ismena** [comment]
Hi, thanks for the request. Let's summon The Shaka Mastermind and hear his verdict :)
@joeyparrish 

In the meantime, could you please describe the use case for EXT-X-GAP in more detail. Do you have it in LIVE streams or VOD? When and why does this happen?

**Comment by joeyparrish** [comment]
Sounds reasonable.  Thanks!

**Comment by avelad** [comment]
You can find more info in:
https://devstreaming-cdn.apple.com/videos/wwdc/2017/504op4c3001w2f222/504/504_advances_in_http_live_streaming.pdf?dl=1

The use case of EXT-X-GAP in our case is skip some segment if the transponder is not enough powerful (in Live and Event playlist)

**Comment by meryacine** [comment]
@joeyparrish @michellezhuogg 
popping this issue back up.

**Comment by ningl2** [comment]
@joeyparrish what is the status of EXT-X-GAP support in Shaka? How does Shaka deal with mismatched discontinuities from audio/video tracks signaled by EXT-X-DISCONTINUITY otherwise?

**Comment by michellezhuogg** [comment]
Hello @ningl2 ,

It's not implemented in Shaka Player yet. We welcome contributions from the community! Thank you!

**Comment by meryacine** [comment]
@ningl2 Do you mean that an `EXT-X-DISCONTINUITY` might cause tracks miss-alignment.  If so, why would that happen, and how does an `EXT-X-GAP` fix this miss-alignment?

**Comment by ningl2** [comment]
Sorry I wasn't clear. Sometimes a contribution feed may be missing parts of audio or video at different times in the stream. HLS spec requires that all EXT-X-DISCONTINUITY tags are aligned across all renditions and variants. This means that we are forced to drop audio/video if the other track is missing data.  The fix for this, the suggestion from Apple is to use EXT-X-GAP in this situation, but looks like there's no good support for this tag in Shaka (or other players for that matter).

**Comment by CermakM** [comment]
Any progress with this?

**Comment by joeyparrish** [comment]
Not that I'm aware of.  None from the core team, and I haven't seen any PRs from the community, either.

We're short-staffed right now (one full-time engineer, two part-time), so I don't foresee the core team getting to this soon.  We apologize for the inconvenience.  In the meantime, PRs are always welcome.  Thanks!

**Comment by CermakM** [comment]
Understood, thanks for the prompt response. Is there any way you could estimate how long would the implementation take? (considering a core member that is familiar with the project). We might consider contributing, it'd be useful tho to have a rough idea about time requirements. Cheers!

**Comment by avelad** [comment]
It seems that Chromium is working on having a native HLS on the platform(https://bugs.chromium.org/p/chromium/issues/detail?id=1266991), and will also support this functionality (https://chromium-review.googlesource.com/c/chromium/src/+/3382254).
