### ISSUE TITLE
PWA tutorial

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1343]
In addition to the [offline tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html), we should have a PWA tutorial which provides a higher-level view of how the offline APIs relate to building a PWA.  It should also cover best practices for media PWA development and give a checklist of necessary PWA components.

Both the PWA and offline tutorials should reference one another.

**Comment by devil-cyber** [comment]
hey can I work on this issue?

**Comment by joeyparrish** [comment]
I don't see why not!  Feel free to send a PR.

**Comment by devil-cyber** [comment]
Thanks 😊

**Comment by avelad** [comment]
I think this is part of the application, not the player. Is anyone interested in this?
