### ISSUE TITLE
Handle manifest updates outside ManifestParser

### ISSUE THREAD

**Issue by TheModMaker** [shaka-project/shaka-player#1408]
Since both standard manifest parsers need to do manifest updates, it makes more sense to have a common class to handle updates.  This also allows us to have a common place to delay manifest updates if we need to (see #1399).

The new design will be to have the `ManifestParser` type only handle parsing the manifest.  It can still be stateful and the method may be called multiple times to handle updated manifests.  The manifest parser will still need to update the existing manifest object like we do now.

Manifest parsers may still need to make other network requests for things like segment indexes or HLS media playlists.

Sketch API:
- Remove `ManifestParser.start`, `ManifestParser.stop`, and `ManifestParser.update`
- Add `ManifestParser.parse` method, which will accept the URI, `PlayerInterface`, and return a Promise to the `Manifest` object.
- The `Manifest` type will get a `minimumUpdatePeriod` property, which can be null.

We will still support plugins defining the old methods for at least v2.6.

**Comment by avelad** [comment]
Is anyone interested in seeing this implemented? Otherwise the issue will be closed in 7 days.
