### ISSUE TITLE
Check support for ContentProtection value="cbcs" in DASH

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1419]
Currently, Chrome (66) only supports "cenc" encryption, not "cbcs".  There are clues in a DASH manifest when other encryption schemes are used.  For example:

```xml
<ContentProtection value="cbcs" schemeIdUri="urn:mpeg:dash:mp4protection:2011" />
```

We should check for this and reject content using an unsupported encryption scheme.

Here is an example of such content:

https://storage.googleapis.com/shaka-demo-assets/sintel-cbcs/dash.mpd

https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/sintel-cbcs/dash.mpd;license=https://cwip-shaka-proxy.appspot.com/no_auth;lang=en-US;build=uncompiled

This relates to the following proposed extension to EME: https://github.com/WICG/encrypted-media-encryption-scheme/blob/master/explainer.md

This information could some day be used to query the browser for support, rather than just rejecting any content not using "cenc".

**Comment by philhar** [comment]
As an aside, this stream stops after 10s in Chrome 68:

> Shaka Error MEDIA.VIDEO_ERROR (3,,PIPELINE_ERROR_DECODE: DecryptingDemuxerStream: decrypt error)

**Comment by joeyparrish** [comment]
Bumping priority so that we can detect encryption scheme support and properly reject content that can't be decrypted correctly.  The current situation of garbage decryptions and decoder errors is not good.
