### ISSUE TITLE
Stopping a live stream

### ISSUE THREAD

**Issue by ncahoon** [shaka-project/shaka-player#1440]
**Have you read the [FAQ](https://goo.gl/JE1Sy5) and checked for duplicate open issues?**: Yes

**What version of Shaka Player are you using?**: 2.4.0

**Can you reproduce the issue with our latest release version?**: Yes

**Can you reproduce the issue with the latest code from `master`?**: Yes

**Are you using the demo app or your own custom app?**: Demo app

**What browser and OS are you using?**: Mac Chrome 66.0.3359.139

**What are the manifest and license server URIs?**:
I can deploy the live stream if needed.

**What did you do?**

I recently asked in the DASH-IF slack #general channel about ending a DASH live stream.

Our use case is a customer wants to end a live event and play some duration of post event slate but not allow that to continue on indefinitely.

The DASH-IF group suggested ...

"Removing the minimumUpdatePeriod and adding the duration to the MPD"

Is this ability to stop a live stream a feature of the Shaka player? Am I following the correct method?

**What did you expect to happen?**

The live stream to stop without errors.

**What actually happened?**

The live stream stopped but the player continued to display the spinning circle icon.

"Assertion failed: Detected as IPR stream, but does not match our model of IPR!"

**Comment by TheModMaker** [comment]
Are you trying to convert the live stream to VOD?  Is the whole stream available or just a portion of it?  If a new person tries to play the manifest after the stream has ended, how do you want them to see it?  Do you know how long the stream will be when it starts?  Does it work if you keep the `minimumUpdatePeriod`?

Having live streams end and convert to VOD is complicated.  We have a bug on the backlog to handle a similar case, #1055.

**Comment by ncahoon** [comment]
It all depends on when a person joins the stream and what our customer has configured. If the event has not begun, and the event URL has been published, users will get a live stream of repeating "pre-event slate". If they join while the stream is "live" they will get the live linear stream. If they join the event after it's over and the customer has chosen VOD replayable on the event, they will get a VOD manifest. If they watch the event to the end, then customer can specify how long they want "post-event slate to play". We have been successfully doing this with HLS for some time. We are working on getting this same feature developed in DASH. I can setup a test stream for you where it "ends" after ~2 minutes if that would help. I believe it's a different use case than the bug you mentioned. I saw that one, and decided mine was different.

**Comment by ncahoon** [comment]
@TheModMaker would you like me to publish a sample stream for you to see?

**Comment by ncahoon** [comment]
@TheModMaker I've created the ability for you to create this scenario on a live stream on our platform. https://content.uplynk.com/channel/3ff06a21737f40bd9f0e3bc342a4ca6b.mpd?xtest=end30&prettydash=1 The first parameter on the URL tells the stream to end in 30 seconds, the second parameter formats the manifest XML to be easier on the eyes. We are removing the minimumUpdatePeriod and adding the mediaPresentationDuration for the stream to end. I'm working with the our internal player teams to support this and the folks at BitMovin. Let me know if this works for you.

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
