### ISSUE TITLE
Custom cast media control notifications 

### ISSUE THREAD

**Issue by sergioavazquez** [shaka-project/shaka-player#1491]
I'm customizing media controls for Android devices. When playing media locally, on an android device, I solved it using `MediaSession`: https://developers.google.com/web/updates/2017/02/media-session 
I even added `ActionHandlers` for previous and next tracks.

I have a very similar goal when casting. It'd look something like this: https://developers.google.com/cast/docs/design_checklist/sender

I believe I'd have to add a `chrome.cast.media.GenericMediaMetadata` to `chrome.cast.media.MediaInfo`.
Create a request, and load it: 
`var request = new chrome.cast.media.LoadRequest(mediaInfo);`
`castSession.loadMedia(request).then(...)`

Can I achieve this customization via `CastProxy`? I didn't find documents on how to extend its functionality either. Would this need to be a new feature or could I work around it myself?

Thanks in advance,

**Comment by joeyparrish** [comment]
I don't know the answer off-hand, but I'm looking into this now.

**Comment by sergioavazquez** [comment]
Awesome, Thanks @joeyparrish!

**Comment by sergioavazquez** [comment]
This should be a good example on how it's implemented: [Google CastVideos repo](https://github.com/googlecast/CastVideos-chrome/blob/master/CastVideos.js)

**Comment by sergioavazquez** [comment]
@vaage I understand how doing that could work, but wouldn't that be a problem when updating Shaka? I was looking forward to a solution that doesn't require me customizing Shaka's code, so I could still update from npm seamlessly. Am I missing something here? Can I add the customization to `shaka.cast.CastReceiver.prototype.sendMediaInfoMessage_` elsewhere? In my own code, I mean. 
Thanks!

**Comment by vaage** [comment]
We don't have support for that feature right now, nor do we have an official way in the library to inject it. If you were to add support for it, we are always welcoming to pull requests and would be happy to evaluate the pull request and add it to the project.

**Comment by joeyparrish** [comment]
@sergioavazquez, I've added the "help wanted" tag to indicate that we would be happy to review a pull request for this feature.  Please read [CONTRIBUTING.md](https://github.com/google/shaka-player/blob/master/CONTRIBUTING.md) for details.  Thanks!

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
