### ISSUE TITLE
Reconstruct moof boxes to support ssix

### ISSUE THREAD

**Issue by srstrong** [shaka-project/shaka-player#1503]
So the MPEG-DASH spec (I’m reading ISO/IEC 23009-1:2014(E)) details how sidx and ssix boxes alongside SubRepresentations with the @level attribute can be used to facilitate trick play, with the player having sufficient information from the index boxes to perform range requests against the ‘main’ segment to download, for example, just the iframes.

However, it doesn’t look like Shaka player (or the reference Dash player) has support for this yet - currently, Shaka is handling trick play by supporting an extra AdaptationSet with the EssentialProperty element pointing at the trickmode schema;  this is ok as far as it goes, but since it’s effectively being treated as a full segment it needs to be stored separately to the ‘main’ segments, or at least being muxed on-the-fly when requested.  This is a shame, since it is incurring either additional storage or additional cpu, which the specified sidx / ssix approach would, I believe, avoid.

So two questions:

a) have I misunderstood either the spec or the additional AdaptationSet approach?
b) if I’ve not misunderstood, then are there any plans for Shaka to support sidx / ssix in the future?

**Comment by vaage** [comment]
@srstrong Thanks for bringing this up. I am going to bring-in @kqyang as he is one of the resident experts on the Dash spec. @kqyang, would you be able to comment on @srstrong 's understanding of the spec and the additional AdaptationSet approach?

Once we know that everyone has the same understanding of what the spec allows, we can look into how best to approach this in the Shaka Player code.

**Comment by joeyparrish** [comment]
If this is a way to point just at the i-frames without having a separate container, I don't believe browsers are going to be able to support that.  It would be analogous to HLS's iframe-only playlists, which MediaSource in the browser can't accept.

**Comment by kqyang** [comment]
@srstrong Your understanding of the DASH spec is correct. TrickPlay implementation using Sub-Representations in combination with Index Segments and Subsegment Index boxes are more efficient, in terms of storage and cpu, than what we are doing now in Shaka Player and Packager.

Unfortunately, as @joeyparrish pointed out, that requires browser support, which I don't think it is supported in any browsers right now, except possibly Safari. To make it work, I think [MSE](https://www.w3.org/TR/media-source/) has to be updated first.

**Comment by vaage** [comment]
@srstrong Does that answer your question? If so, please feel free to close the issue.

**Comment by srstrong** [comment]
Thanks for the quick responses chaps, much appreciated.  I haven't been through the sidx / ssix boxes in alongside the mp4 moof definition in massive detail, but first glance suggested that there would be sufficient info in those boxes to allow the client-side javascript to construct an appropriate moof containing just the frames referenced by the selected level.  So essentially just moving the re-muxing from the server to the client - which will be a very minor hit on the client performance in exchange for improved scalability at the server

**Comment by srstrong** [comment]
That's possibly something we'd be interested in helping with.  I'm working on our server implementation at the moment, so will review the sidx and ssix boxes to see if there is indeed enough information to construct a sane moof.  If so, I'll let you know and we can discuss how that might happen

**Comment by avelad** [comment]
Anyone interested in this? If no one responds to the thread in 7 days, it will be closed automatically. Thank you!
