### ISSUE TITLE
Suspend MediaSourceEngine operations if video element is not in the DOM

### ISSUE THREAD

**Issue by chrisfillmore** [shaka-project/shaka-player#1538]
We have a use case on Tizen 2017 TV's where we remove the video element from the DOM in order to play some ads in another element. We have made a change to `MediaSourceEngine` to defer all operations (i.e. calls to `enqueueOperation_`) until the video element is back in the DOM. If we don't remove the video element from the DOM, or if we don't suspend calls to `enqueueOperation_`, we get 3016 VIDEO_ERROR.

Would Shaka be willing to accept such a change upstream? I believe this could be achieved cleanly by using a `MutationObserver` and watching the whole document. Performance would need to be investigated, and likely you would want the behaviour to be configurable behind a flag.

As an alternative, perhaps you could allow the client to set a callback which returns a Promise that resolves when `enqueueOperation_` can proceed. Then the client can deal with the `MutationObserver`.

2018 model Tizen TV's apparently have the same issue. We also have both 2017 and 2018 model LG WebOS TV's; I will check if it affects those platforms.

Thanks. Please let me know where this falls in terms of reasonableness.

**Comment by theodab** [comment]
Personally, I think the client-controlled option sounds better. That would allow for the client to just toggle it on or off at the same time as they modify the DOM, and not worry about the performance of a `MutationObserver` at all.

@joeyparrish, thoughts?

**Comment by chrisfillmore** [comment]
That's an even better idea. A simple synchronous call that allows the client to tell Shaka whether it should do MediaSource work or not.

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
