### ISSUE TITLE
Extract the current defaults config values (from source code) into the config documentation

### ISSUE THREAD

**Issue by leandromoreira** [shaka-project/shaka-player#1544]
While I was reading the shaka documentation to understand how the [network fallback works]( https://github.com/google/shaka-player/blob/master/docs/tutorials/network-and-buffering-config.md ) I saw that there is a configuration for that but then it wasn't clear for me which are the default values for these configs.

I think the [network default config value seems to be at the backoff.js](https://github.com/google/shaka-player/blob/bb646befca77a35ff781ea1f453b385d0ff73a89/lib/net/backoff.js#L144) file and I was wondering how can use the source code to generate or to improve the existent [config tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-config.html,) with the default values.

**Comment by leandromoreira** [comment]
@ismena I could not find a place where I can see all the default values for the shaka configuration. I think we can look at them by calling `player.getConfiguration();` but maybe to explicitly expose those values on a documentation would be helpful.

And maybe this default configuration adopted by shaka needs to be dynamically generated each shaka version, since the defaults are usually on the code itself.

> The concept of network fallback as a whole?

No, I understood.

**Comment by joeyparrish** [comment]
Ideally, we would have some way of extracting the defaults from the code into a generated doc.  We will have to build something new for that, though.  It's not provided by jsdoc.

I've bumped this to v2.6, our code health and cleanup milestone.  For now, we need to wrap up on v2.5 features.
