### ISSUE TITLE
Add error handling documentation

### ISSUE THREAD

**Issue by leandromoreira** [shaka-project/shaka-player#1545]
The error handling example [on the doc](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) is great but maybe it deserves its own page or expanded section with more examples, so users can learn from it. Things like: how to capture, [specify the errors](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html) to send metrics or how to recovery.

**Comment by ismena** [comment]
Thanks for giving us feedback on the tutorials! Let me schedule this for 2.5.

**Comment by leandromoreira** [comment]
One example I can think of is how a user can intercept and act on a given error? 

Shaka has its retry system but I don't want shaka to retry when my server replied with 403 or I want to extract a http header to send metrics about this error, maybe a filter where I can decide if I let the default network fallback system to work or stop the chain.

**Comment by mohamedfasil** [comment]
any update on this ?

**Comment by friday** [comment]
I think this can be closed? (fixed in #4983)

**Comment by avelad** [comment]
Yes, Thanks!
