### ISSUE TITLE
Dedupe emsg with identical "id" field.

### ISSUE THREAD

**Issue by damienlevin** [shaka-project/shaka-player#1549]
This might be WAI, curious to hear your thoughts on this.
 

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
Yes
**What version of Shaka Player are you using?**:
2.4.3
**Can you reproduce the issue with our latest release version?**:
Yes
**Can you reproduce the issue with the latest code from `master`?**:
Yes
**Are you using the demo app or your own custom app?**:
Yes
**If custom app, can you reproduce the issue using our demo app?**:
Yes
**What browser and OS are you using?**:
Chrome/Linux
**What are the manifest and license server URIs?**:
N/A
**What did you do?**
Played a stream with duplicated emsg (same id field value)
**What did you expect to happen?**
Only the first event should be provided to the callback. 
As per specification:
> id: a field identifying this instance of the message. Messages with equivalent semantics shall have the
> same value, i.e. processing of any one event message box with the same id is sufficient.
> 

FYI: This is the behavior in DashJS.

**What actually happened?**
All events were provided to the callback.
Tested URL:
https://storage.googleapis.com/dlevin/dash_id3/manifest_id3_v0.mpd

Note that here, despite having a same id, the events have a different presentation_time_delta, so in this case perhaps the current behavior makes sense. But assuming all event were the same, should Shaka dedupe them ?

**Comment by joeyparrish** [comment]
I'm okay with dedupe based on ID, since it's much simpler and supported by the spec.  ("Processing of any one event message box with the same id is sufficient.")

I'll put this in the backlog for now, but we'd be happy to accept a PR if you have time to work on it.  Thanks!

**Comment by damienlevin** [comment]
Great thanks. 
I'll try to TAL this week.
