### ISSUE TITLE
Document fullscreen advice

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1566]
Today, while debugging a UI-related issue with a partner, we discovered that fullscreening a video element in Chrome forces the use of browser-native video controls.  It took a long time to figure this out.

We should write a doc with fullscreen-related advice.  For example, to keep custom controls (or no controls at all), you must call requestFullscreen on an element that contains the video element and any controls you want.  You must also do so from a user interaction event handler.

If anyone has any other issues that have come up in their own apps, please feel free to comment and add to the list of things we should document in a fullscreen tutorial.

**Comment by chrisfillmore** [comment]
This is not related to fullscreen, but is related to custom controls. Some CSS properties such as `transition` and `opacity` can cause video rendering problems in IE11 and Edge. We saw this in our test application when the video element would stay completely black after playback had started, until we clicked on the browser window.

I believe this is related to behaviour of independent composition described here:
https://msdn.microsoft.com/en-us/library/jj680148(v=vs.85).aspx

I never got around to filing a bug with MS about it, but fyi in case it's useful to you.
