### ISSUE TITLE
Make replay smoother by buffering from the start

### ISSUE THREAD

**Issue by TheModMaker** [shaka-project/shaka-player#1605]
If we are nearing the end of the video, we should, optionally, start buffering from the start again.  This will make replay and loop smoother.  This will be controlled by a configuration option to avoid buffering when the app doesn't want to replay or loop.

We used to require exactly one buffered range, which is why we didn't do this in the past; however, I don't think much of our code assumes that anymore.  Things like buffering goal calculation will need to be adjusted to account for this and we'll need to ensure StreamingEngine doesn't remove it as part of removing behind the playhead.  But with gap jumping, we already allow multiple buffered ranges in general.

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
