### ISSUE TITLE
cannot playback widevine/playready drm link by web app on Tizen

### ISSUE THREAD

**Issue by kevinbol** [shaka-project/shaka-player#1663]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**:
yes
**What version of Shaka Player are you using?**:
v2.5.0 COMPILED_DEBUG_JS
**Can you reproduce the issue with our latest release version?**:
yes
**Can you reproduce the issue with the latest code from `master`?**:
yes
**Are you using the demo app or your own custom app?**:
demo app
**If custom app, can you reproduce the issue using our demo app?**:

**What browser and OS are you using?**:
I make shaka player into  a web app on Tizen 
**What are the manifest and license server URIs?**:

**What did you do?**
I select all the widevine/playready drm link in the default list, such as Tears of Steel (widevine), and click load button. no video or audio is output.
**What did you expect to happen?**
playback normally
**What actually happened?**
cannot playback, and no error happened.

Tears of Steel (clear) play well.
![clear](https://user-images.githubusercontent.com/41713907/48457879-1c2a2180-e7ff-11e8-9980-71615ee1e3af.jpg)

Tears of Steel (widevine) cannot play
![widevine](https://user-images.githubusercontent.com/41713907/48457883-23512f80-e7ff-11e8-975c-ae8a52ebf626.jpg)

**Comment by chrisfillmore** [comment]
I'm a bit confused. Your first image appears to show Tears of Steel playing. So, does it play?

Have you checked the debugger for any output to the console?

**Comment by kevinbol** [comment]
hi, chrisfillmore
thanks for your response.
the first image appears Tears of Steel (clear) playing well.
the second image appears Tears of Steel (widevine) cannot play.
there is nothing in the log output to console. 

Shaka declare to support wedevine and playready on Tizen. does it include web app on Tizen ?

**Comment by joeyparrish** [comment]
@kevinbol, I can see the same or similar issue on our 2017 Tizen TV.  I'm not sure what is causing it, but our automated playback tests for those assets fail inconsistently on our Tizen device.  I see MediaSource failures, so I expect either a bug in Tizen's media stack or some incompatibility between Tizen's decoders and the media content itself.  This is similar in spirit to #1610, but it's very difficult to debug these things.

If we can figure out the trigger, we may be able to produce a workaround.  But it might not be feasible, and we might have to rely on Samsung to fix the platform in some way.

I'll update this issue once we have something more concrete to go on.

**Comment by kevinbol** [comment]
> @kevinbol, I can see the same or similar issue on our 2017 Tizen TV. I'm not sure what is causing it, but our automated playback tests for those assets fail inconsistently on our Tizen device. I see MediaSource failures, so I expect either a bug in Tizen's media stack or some incompatibility between Tizen's decoders and the media content itself. This is similar in spirit to #1610, but it's very difficult to debug these things.
> 
> If we can figure out the trigger, we may be able to produce a workaround. But it might not be feasible, and we might have to rely on Samsung to fix the platform in some way.
> 
> I'll update this issue once we have something more concrete to go on.

thanks for your reply~

**Comment by leszek-syroka** [comment]
It looks like the issue is not related with the codec or DRM key system. 

Audio stream has negative PTS and DTS which affects buffering ranges and is not supported correctly on  2017 Tizen TVs. 

Audio content dumped from Tears of Steel is attached: https://user-images.githubusercontent.com/60613759/143867759-8450c3c5-748a-4932-a17c-abbd78bd4048.mp4

Please check the results from ffprobe.

```
$ ffprobe -show_packets audio.mp4 | grep "dts\|pts" | head

pts=-2048
pts_time=-0.042667
dts=-2048
dts_time=-0.042667
pts=-1024
pts_time=-0.021333
dts=-1024
dts_time=-0.021333
pts=0
pts_time=0.000000
```

The only workaround for this issue is not to use content with negative PTS/DTS for legacy Tizen TVs.
