### ISSUE TITLE
UI: Android a11y "select to speak" reads "video video"

### ISSUE THREAD

**Issue by ismena** [shaka-project/shaka-player#1678]
1. Turn on "select to speak" in Android a11y settings
2. Open the demo with the new UI
3. Touch the floating "select to speak" button
4. Touch an element of the video controls, such as the mute button

Result:
The screen reader says "video video", then reads the mute button.  It seems to be reading out all overlapping elements at that point on the screen.

Expected:
Only the touched element (such as mute button) would be read aloud.

**Comment by avelad** [comment]
I have used VoiceOver on macOS and I no longer experience this issue.
