### ISSUE TITLE
Investigate need for gap-jumping in external asset tests

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1702]
In our external asset playback tests in `test/player_external.js`, I have found that gap-jumping helps in certain cases.  This is unexpected, so we should investigate why this is and whether this represents a real bug somewhere in the library.

**Comment by avelad** [comment]
Since 4.0 we always jump gaps (see: https://github.com/shaka-project/shaka-player/pull/4125), so technically this issue is no longer necessary.
