### ISSUE TITLE
Decouple content from key systems

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1707]
Today, if a piece of content references PlayReady and Widevine, we'll try those key systems.  If the content doesn't reference any particular key systems, we will try a list of well-known key systems.

Instead, we should let `Player` configuration decide what key systems we try, regardless of what the content says.  We should also have a configuration in the demo app to allow the user to specify a particular key system to try, whether or not we know about it in advance.

**Comment by joeyparrish** [comment]
Thanks to @xhwang-chromium for the suggestion!

**Comment by avelad** [comment]
What we want already exists in the demos, and in the configuration with `preferredKeySystems`
