### ISSUE TITLE
Use HLS metadata to name track languages

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1762]
Spawned from discussion in #1747:

@gdub01 wrote:
> One more suggestion:
> in the m3u8 playlist a name is provide for the audio and text files like:
> LANGUAGE="arb",NAME="ARABIC"
>
> Not sure if it would be too annoying to grab this as it appears it's not in mpd files. But if that's doable I think it would be useful.

We could use the "name" information from HLS to help with naming the languages of audio and text tracks.  That assumes that this info in the HLS playlist is spec'd to specify a language name.  I have not verified this.

**Comment by fadomire** [comment]
from HLS spec it seems to be even required
> NAME: (Required) A string that describes the primary language used in the media selection.
source : https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/adding_alternate_media_to_a_playlist

**Comment by surajkumar-sk** [comment]
I didn't understand the issue, the `Name` in the `type=audio` tag can represent anything. In all the videos of HLS in Shaka-player Demo, the name tag has names like "stream_0 || stream1 || stream2", so, it's not a reliable source for naming language.

**Comment by avelad** [comment]
Is anyone interested in this? If not, the issue will be closed in 7 days.
