### ISSUE TITLE
Build TS caption metadata on-the-fly

### ISSUE THREAD

**Issue by bkodirov** [shaka-project/shaka-player#1826]
Can Shaka player parse CEA 608 and provide a text track list?
We have an HLS stream which doesn't have closed CLOSED-CAPTIONS metadata in it. Meantime our TS files do have CEA 608 closed caption. 
Currently, Exoplayer and AVPlayer are parsing TS and providing information about the CC. We can select that CC and player are rendering closed caption properly. Our chromecast app doesn't provide closed caption for the same stream. It is using
 [  4.815s] [cast.framework.common.libraryloader] library(//ajax.googleapis.com/ajax/libs/shaka-player/2.4.4/shaka-player.compiled.js) is loaded .

**Comment by joeyparrish** [comment]
I believe we are driving the tracks API from the metadata in the HLS playlist.  Can your playlist be fixed to signal the presence of the CC data?

**Comment by bkodirov** [comment]
Unfortunately, our encoder doesn't provide CLOSED-CAPTION metadata in the Manifest.

**Comment by joeyparrish** [comment]
Then I'll convert this into an "enhancement" issue to build CC metadata on-the-fly as captions are discovered in the content.  Note that this would only work for TS content, and only with mux.js installed for transmuxing.  In other cases, we would not have the opportunity to discover the captions.  In MP4 content, we would not be parsing the content unless the metadata was there to signal the presence of embedded captions.

**Comment by bkodirov** [comment]
Thank you. Since CAF(Chromecast) receiver uses shaka player, do you have any clue, whether it is gonna be available on the chromecast CAF?

**Comment by joeyparrish** [comment]
The CAF team have their own release schedule, which I can't predict.  But it would have to be in a Shaka Player release first, and this is not scheduled for a release yet.

**Comment by joeyparrish** [comment]
If anyone is interested in contributing a PR for this, please let us know!  (Tagging @arturparkhisenko based on discussions in #2466.)

**Comment by ashishTivo** [comment]
Hi, just checking if anyone working for  detecting embedded closed captions if manifest doesnt have closed captions data?

**Comment by joeyparrish** [comment]
I don't believe anyone is working on this at the moment.  Would you like me to assign it to you?

**Comment by avelad** [comment]
We already support this functionality for when loading a media playlist.
