### ISSUE TITLE
Official support for Amazon Echo Show

### ISSUE THREAD

**Issue by chrisfillmore** [shaka-project/shaka-player#1828]
Amazon Echo Show is a FireOS device which provides an html5, Chromium-based environment for video playback via a [WebView](https://developer.android.com/reference/android/webkit/WebView) (see additional comments below).

https://www.amazon.com/All-new-Echo-Show-2nd-Gen/dp/B077SXWSRP

I realize this is a request to support yet-another device platform. At any rate, I thought you should know, we are trying to deploy Shaka to such a device. (We're currently running into some trouble generating a license request, but we'll work with Amazon on that.)

**Comment by joeyparrish** [comment]
Thanks for the note.  We appreciate it.

For now, we have two other devices in queue to integrate with our lab testing environment (XBox One and LG WebOS), so we can't look into Amazon Echo Show right now.

But we'll keep it in mind.  I'm always interested in adding new platforms to the family.

In the mean time, let us know if you need help debugging or if you have any PRs to improve support for the device.  Thanks!

**Comment by chrisfillmore** [comment]
I learned something recently and have to clarify: the Echo Show device is actually Amazon FireOS-based. The html5 environment is provided by an Amazon WebView.

According to [this FAQ](https://developer.amazon.com/docs/fire-tv/web-hybrid-app-faq.html) the Amazon WebView is a re-implementation of [Android's WebView](https://developer.android.com/reference/android/webkit/WebView). Also, if you want to play protected content, you need to handle Android's [EVENT_PROVISION_REQUIRED](https://developer.android.com/reference/android/media/MediaDrm.html#EVENT_PROVISION_REQUIRED).

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
