### ISSUE TITLE
UI: A11y: Use the lang= attribute to help screen-readers recognize localized aria attributes

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1860]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
It is not clear that our translated aria attributes will be correctly read by screen readers.

**Describe the solution you'd like**
First, we should test this using the localized UI and a screen-reader that understands a language other than English.  For example, I find that [this W3 page about `lang` attributes](https://www.w3.org/International/questions/qa-html-language-declarations) (appropriately) renders in German for me (based on my browser preferences) and uses `lang="de"` in the HTML. 
 If a screen-reader can correctly pronounce a non-English version of this page, then we know how things *should* work.

Second, we should test our demo page with a non-English UI.  If the non-English aria labels are not correctly read, we should try adding `lang=` to the video controls container when the locale changes.  Alternately, we could add `lang=` to the individual divs and spans to handle the case where some translations are missing.  This *should* work, but hasn't been tested.

**Describe alternatives you've considered**
I don't know of any alternatives to `lang=`.

**Comment by joeyparrish** [comment]
The ChromeOS screen reader (ChromeVox) seems to read the whole page to me in German, including the English text.  So the UI's German aria labels are correctly read in German.  But since the demo app itself is not localized, it may make sense to tag the entire page with `<html lang="en">` for now and then change the `lang=` attribute on the video controls when we change locales in the video controls.

**Comment by joeyparrish** [comment]
We actually already have `<html lang="en">` on the demo app.  It doesn't seem to affect the pronunciation in ChromeVox, at least on ChromeOS.  It is probably still worth checking with other screen readers or on other platforms.  I've seen ChromeOS have unique behavior with regards to language in other areas.

**Comment by joeyparrish** [comment]
It looks like we can set lang= on individual elements based on which locale we used when we localized that string.

**Comment by absidue** [comment]
As most of the time shaka-player is aware of the language of text tracks, another good place to add the `lang` tag could be in UITextDisplayer. It could also explicitly add an empty `lang` attribute when the language is unknown (to quote the MDN page `If the attribute value is the empty string (lang=""), the language is set to unknown).
