### ISSUE TITLE
DASH-IF 4.2 AdaptationSet @SelectionPriority

### ISSUE THREAD

**Issue by jnorthrup** [shaka-project/shaka-player#1877]
i have observed that dash player seems to halt with DASH_INVALID_XML: 4001 when I add selectionPriority=100 to AdaptatoinSet declaration per DASH-IF 4.2 

the first adaptation set is opus+webm from ffmpeg DASH muxer, and the second adaptation set is AAC/mp4 audio-only.

without the selectionPriority attribute dash will play fine, but only the ISO mp4 aac audio.

for given quality and bandwidth prioritizing opus seems like a good thing, at the very least reasonable to test through the DASH-IF suggested means.

 ```XML
?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
        profiles="urn:mpeg:dash:profile:isoff-live:2011"
        type="static"
        mediaPresentationDuration="PT58M44.8S"
        minBufferTime="PT10.0S">
        <ProgramInformation>
        </ProgramInformation>
        <Period id="0" start="PT0.0S">
                <AdaptationSet id="0" selectionPriority=100  contentType="audio" segmentAlignment="true" bitstreamSwitching="true">
                        <Representation id="0" mimeType="audio/webm" codecs="opus" bandwidth="8000" audioSamplingRate="48000">
                                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
                                <BaseURL>stream-eps-5-kambing-hitam-di-sekitar-kita-0-8000.webm</BaseURL>
                                <SegmentList timescale="1000000" duration="5000000" startNumber="1">
                                        <Initialization range="0-512" />
                                        <SegmentURL mediaRange="513-6845" />
     ```

**Comment by jnorthrup** [comment]
https://github.com/google/shaka-player/issues/476  appears to satisfy the criterion to show how one can swing the preferences a certain way.

**Comment by jnorthrup** [comment]
i have tested out cherry picking the encoding bitrates between opus and aac to give opus an increment less bandwidth consumption per #476  

doing this has prioritized the webm adaptationset in shaka  player.

**Comment by TheModMaker** [comment]
You need to add quotes around the value: `selectionPriority="100"`.  DASH_INVALID_XML means the XML syntax is incorrect, it doesn't deal with the properties themselves.  If there is a new property we don't support, we will just ignore it.

We don't support `selectionPriority`, so we will just ignore it.  But this would be something we would like to add since it will avoid us having to use heuristics to guess which to choose initially.

Can you provide an example manifest URL?  Which Shaka Player version are you using?  We should pick the stream with the lowest bandwidth.

**Comment by jnorthrup** [comment]
i backed off using selectionPriority in the XML because the xml namespace validation also complains.  this was internal testing.

the idea i had was to use the highest and lowest bitrates with opus and throw iphone a bone with some optimal AAC HEV2 streams using ffmpeg and dual DASH/HLS manifest creation.  

on that note, master.m3u8 also plays no media... but that's a problem for a different day. the individual streams have a playlist each.

**Comment by jnorthrup** [comment]
https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/92 links to XSD with the updated syntax.

i filed a heads-up with ffmpeg.org  here https://trac.ffmpeg.org/ticket/7845#ticket

**Comment by avelad** [comment]
Can you provide a sample stream to implement it in Shaka? Thanks!
