### ISSUE TITLE
Validate StreamGenerator output is gapless

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1887]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Issue #1206, in which a problem with StreamGenerator resulted in gaps which went undetected for a long time.

**Describe the solution you'd like**

We should add tests to validate that StreamGenerator's output is gapless for all the test content we use in TestScheme.

**Comment by avelad** [comment]
I haven't seen any problems with StreamGenerator in 5 years, should we close this issue?
