### ISSUE TITLE
Inefficient buffering behavior with negative trick play rate

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1958]
When we are doing trick play with a negative rate, the player is still buffering forwards.  Either we should buffer backwards, or we should avoid buffering more than one segment at a time.

**Comment by floribon** [comment]
I am also affected by this, backward playback causes the player to constantly buffer and clear buffer. I minified the impact by setting `bufferingGoal: 1` and a `rebufferingGoal: 0` but it is still wasting a lot of bandwidth.

**Comment by ismena** [comment]
@joeyparrish you mentioned that you had thoughts on this might be addressed. Could you share? Depending on priority and complexity, the team can take it on or we could open this for external contributions.

**Comment by joeyparrish** [comment]
My gut feeling is that since today, StreamingEngine follows a SegmentIterator to decide what to fetch, what we need is something like a ReverseSegmentIterator.  Any time the play rate changes, StreamingEngine could check if it changed between negative and non-negative and re-init the iterator accordingly.  This would keep most of the complexity of the change in the implementation of ReverseSegmentIterator, which would be relatively easy to test in isolation.
