### ISSUE TITLE
Bad interactions between buffering observer and trick play

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#1961]
The buffering observer puts the player in a buffering state on an unbuffered seek, which makes sense.

The buffering observer resumes playback when rebuffering goal is met, which it observes by polling the SourceBuffers.  This polls every 250ms, but the timer is not guaranteed to fire on time.

Even with a small rebuffering goal, a fast network can result in multiple segments fetched before we exit the buffering state.  (Multiple segments fetched inside of 250ms.)

Combine fast networks with slow browsers, and this can mean that the buffering watchdog timer fires much later than 250ms, allowing even more opportunity for multiple segments to fetch between polling events.  Anecdotally, as much as 700+ms, according to a partner.

Combine all that with trick play, where we make repeated seeks, and we end up wasting a lot of bandwidth by fetching things that we don't need.

Polling for the buffering state is the root of the problem, and we have recently found other reasons to avoid it.  If possible, we should get rely on HTML5 video events to be informed of buffering state changes and inform the application UI.  The polling and manipulation of playbackRate should go away.

**Comment by avelad** [comment]
Since 4.5 we removed the poll and the playback rate change, now we use the browser events. So this issue is resolved now. Thanks!
