### ISSUE TITLE
Alternate NetworkingEngine url selection strategy on retry

### ISSUE THREAD

**Issue by chrisfillmore** [shaka-project/shaka-player#1997]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, this is sort of related to #1437, but a different approach.

**Is your feature request related to a problem? Please describe.**
I'd like to be able to provide a list of url's and the number of times each should be requested. Currently, `retryParameters.maxAttempts` is defined in one place, and Shaka cycles through `uris` on retry:
```
index = (index + 1) % request.uris.length;
```

**Describe the solution you'd like**
If we could configure a url selection strategy somehow, that would be nice. My initial thought was to add a new parameter on `retryParameters`, like `maxAttemptsPerUrl`, which would not be a breaking change. But the logic of whether to retry is handled in Backoff, whereas the url selection is handled in NetworkingEngine. I'm not sure what the best approach is.

**Describe alternatives you've considered**
Currently I provide a list of url's via network request filter. I can get NetworkingEngine to retry per-url by just providing each url multiple times, e.g:
```
request.uris = [
  'manifest1.mpd', 'manifest1.mpd', 'manifest1.mpd',
  'manifest2.mpd', 'maniest2.mpd', 'manifest2.mpd'
];
```
And I configure `retryParameters.maxAttempts` to 6. This works, but it's a bit of weird way to get what I want.

**Additional context**
Our manifest url's, even if they represent the same content, may have different business implications. The simplest example is a stream with ads versus one without. We make money from ads, so we'd always like to serve the ad stream. If there is a brief connection/server problem, we'd still like to retry the ad stream before falling back to the non-ad one. We also have some streams with longer `timeShiftBufferDepth`.

**Comment by theodab** [comment]
An optional value in `shaka.extern.RetryParameters` sounds reasonable to me. I think we could make the networking engine "translate" the retry parameters and uris list into the form you mentioned you are doing currently, if `maxAttemptsPerUrl` is present. That way, the backoff code (which is used elsewhere) doesn't have to change, and the internal networking engine architecture doesn't change significantly. I'll give it a shot.

**Comment by TheModMaker** [comment]
Are you talking about for the initial `load()` request or for manifest updates?  For the initial load you can just use normal retry parameters and use a "catch" for the final failure to switch to the next manifest option.

For Live, each manifest needs to represent the same exact content.  Having one URL have ads and one without will break things.  In every manifest option and every update there needs to be the same content.  You can't just remove an ad that existed in a previous update by switching to another manifest.

Also, changing `timeShiftBufferDepth` while playing may not be supported.  So if you switch to a different manifest that has a different value, we will probably ignore the change.

**Comment by chrisfillmore** [comment]
> Are you talking about for the initial `load()` request or for manifest updates? For the initial load you can just use normal retry parameters and use a "catch" for the final failure to switch to the next manifest option.
We'd like to support both initial manifest load and subsequent updates. Wouldn't catching a failed call to load() require reinitializing the media stack? I would expect this to have an impact on video start time.

> For Live, each manifest needs to represent the same exact content. Having one URL have ads and one without will break things. In every manifest option and every update there needs to be the same content. You can't just remove an ad that existed in a previous update by switching to another manifest.
Before we give it to the player, the ad manifest is passed off to an external service, which populates ad periods with ad content (i.e. server-side ad insertion), instead of filler content (e.g. "Your program will return shortly..."). I think this describes the "same content". The manifest and presentation timeline is the same as far as I can tell. Do you disagree?

> Also, changing `timeShiftBufferDepth` while playing may not be supported. So if you switch to a different manifest that has a different value, we will probably ignore the change.
I have only done limited testing and I also observed that playback stalled when switching between these types of manifests. But I was going to continue testing since Joey indicated (https://github.com/google/shaka-player/issues/1201#issuecomment-501353479) the player should support it.

**Comment by avelad** [comment]
Currently the standard has moved to using Content Steering for this purpose. I'm going to close the issue, please if you don't agree, write a comment and we can talk about it.
