### ISSUE TITLE
Add new error code for segment fetch errors.

### ISSUE THREAD

**Issue by OrenMe** [shaka-project/shaka-player#2118]
While investigating the request/response filters mechanism I saw you have different error propagation between license and other request/response types.
For license, no matter what error the underlying networking engine throws, the DRM engine will turn it to a `LICENSE_REQUEST_FAILED` error.
https://github.com/google/shaka-player/blob/e7a5bb9ecf07c5a0ac0d87d2a7a44e24d6a371f0/lib/media/drm_engine.js#L1122-L1140  
For other types of requests the streaming engine will re-throw the networking engine error(last else clause, lines 1607-1614):
https://github.com/google/shaka-player/blob/e7a5bb9ecf07c5a0ac0d87d2a7a44e24d6a371f0/lib/media/streaming_engine.js#L1579-L1615
So if there was a filter request or response error the application using the player can know if it is a filter error or an actual HTTP error.
(the streaming engine actually does have also different handling for all of if-else clauses - so maybe this is also valid for them - you will not know that they failed due to filter error, like the license).

Is there a reason for this inconsistency in behaviour? does it serve a purpose?

**Comment by OrenMe** [comment]
@joeyparrish this makes sense, but in this case shouldn’t the other way be aligned?
I mean, the streaming engine does emit the underlying network error as is i this case.
Should this be amended? And in this case is the request/response filter error should always be in the payload of their respective higher level engine/controller?
I’m wrapping shaka’s API with an abstraction later and also wondering if I should use the request/response filter error or report it as license/manifest/segment loading error.

**Comment by TheModMaker** [comment]
I guess that makes sense.  We can add a new error code for `SEGMENT_FETCH_ERROR` to differentiate the source of the network error.  This would be a breaking change since apps would no longer see errors like `HTTP_ERROR` anymore.  We should also update the display in the demo app to handle these nested errors better.

**Comment by OrenMe** [comment]
Thanks @avelad for coming back to this. As the original opener of this issue, even I have no vested interest in this anymore, so if no one else commented for so long this can be closed.
