### ISSUE TITLE
How to ignore a segment and buffer next segment?

### ISSUE THREAD

**Issue by thinhvnu** [shaka-project/shaka-player#2144]
Dear shaka team,
I want to play chunk 1.ts, ignore 2.ts if it has error and buffers 3.ts without seeking to 3.ts
Our case is chunk error 404 not found. Player retry 2 times and stuck. I want to ignore this and get next
![Screenshot from 2019-09-13 16-12-20](https://user-images.githubusercontent.com/30438937/64851409-8a1ebf80-d641-11e9-9177-9ae91dc9a332.png)

Pls help

**Comment by theodab** [comment]
Could you please fill out the [bug report template](https://github.com/google/shaka-player/issues/new?assignees=&labels=&template=bug_report.md&title=)? You have not provided enough information for us to do anything.

**Comment by ismena** [comment]
Oh, I don't think that's a bug report!

@thinhnv789 please correct me if I'm wrong, here's I thought the issue was about:
One of the segments in a stream fails to be downloaded and you want the player to try and go to the next one instead of stopping and throwing an error.
Is that right?

Is that for a live stream? I think I remember @joeyparrish telling me that this happened with live streams sometimes. Or was it you, Jacob? @TheModMaker 
Can we treat it as a gap or something?

**Comment by ismena** [comment]
Update: we don't have capability to skip failed segments at the moment, but this sounds like something we should be able to add without too much trouble since we already have gap-jumping capabilities.

I'll tag this an enhancement.

**Comment by thinhnv789** [comment]
@ismena thank for your support,
You understand what I mean,
**One of the segments in a stream fails to be downloaded and you want the player to try and go to the next one instead of stopping and throwing an error.**
please let do it if you can.
Thanks,

**Comment by caridley** [comment]
We see this situation fairly frequently in some or our live streams. We currently recover by restarting the player which isn't the best experience.

**Comment by ismena** [comment]
@caridley I hear you.
I think, we had some gap jumping work planned for v4, maybe this can be part of that. 
Let me bring it up with the team. If not, maybe we could accept a PR for this.
@joeyparrish thoughts?

**Comment by joeyparrish** [comment]
I think we could add a config option for it.  If set, StreamingEngine could move on to the next segment if a segment request fails.  I feel certain it should be used only for live streams, but I'm not sure if that would be best enforced or just documented for that option, and left to applications to decide.  I think I would lean toward giving app developers the choice.  It probably wouldn't actually hurt to turn it on for VOD.

**Comment by avelad** [comment]
In my opinion:
In Live streams we should always try to reproduce, skip gaps and even erroneous segments. What the user wants is to play the Live stream, in DVB this is always the case, so in adaptive streaming it should be the same.

Note: there is sometimes that there is the catchup/startover/retrogrid/... option that uses a circular buffer of N days and in the end the playlist is VoD, so here it would also make sense.

**Comment by ismena** [comment]
@joeyparrish Are we open on PRs on this with our current gap jumping logic or does it not make sense until that's changed?

**Comment by rahulkrish** [comment]
@joeyparrish @ismena Any updates on this issue? Are you open to PRs with the current gap jumping logic or is this going to be addressed as part of v4?

**Comment by joeyparrish** [comment]
We are open to PRs, with a preference to discuss the concept of your change here before reviewing a PR, to help make sure we're in agreement.  Any breaking change will be deferred to v4 (or accelerate our decision to bump the version number to v4, if it's really compelling).

**Comment by avelad** [comment]
Solved by https://github.com/shaka-project/shaka-player/pull/4189
