### ISSUE TITLE
Track time it takes to run tests

### ISSUE THREAD

**Issue by TheModMaker** [shaka-project/shaka-player#2145]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
I have made several changes (fa32335f6e496a98ac9dc11821690839f81224f7, 4fdf8f7a1c2c6c413ed2a86c140397abc0044e0b, e2fa4626b506cbc54c849ff3ed25e59cf428d60f) to make the tests run faster, especially the unit tests.  There are many cases where we used to have tests that took several seconds to run.  For integration tests, this may be unavoidable, but for unit tests, this is unacceptable.

The guideline we should follow it try to keep unit tests under 100ms and have integration tests take less than a few seconds if possible.  Playback tests can take longer since we want to simulate real playback, but other tests should run as fast as possible.

**Describe the solution you'd like**
We should have automated checks that test how long a test runs to ensure it is within guidelines.  We should get an error if a unit test takes longer than 200ms and maybe add an error for non-playback integration tests too (maybe 3-5 seconds).  We should also have a report of our test times so we can see which tests take a long time to prioritize making those faster.

When running locally you can install the [karma-time-stats-reporter](https://www.npmjs.com/package/karma-time-stats-reporter) and use that with the `--reporters` option.  This will report the slowest tests and how long they took.  The junit reporter includes the time in the XML report, so we may be able to show slow tests on the build bot.  It reports the time it took for tests, but it is difficult to see at a glance.

**Describe alternatives you've considered**

**Additional context**

**Comment by avelad** [comment]
Improvements addressed by Joey.
