### ISSUE TITLE
Add tests for key rotation

### ISSUE THREAD

**Issue by TheModMaker** [shaka-project/shaka-player#2162]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
We don't have any tests that verify key rotation in DrmEngine.  See #2160.

**Describe the solution you'd like**
We should add some tests that verify that we handle getting new `encrypted` events from future media segments and these events result in creating new sessions.

**Describe alternatives you've considered**

**Additional context**

**Comment by avelad** [comment]
Already done with https://github.com/shaka-project/shaka-player/commit/3846eeac3f3777c35e61f479958015062f4275af#diff-c6f582c00ff89fe4e56693512e2ff43920ff32bad9be8b37b7114a7b7d9f8640
