### ISSUE TITLE
Deleting stored demo content can break internal state

### ISSUE THREAD

**Issue by theodab** [shaka-project/shaka-player#2201]
I had this problem while testing #2156. I had happened to store the asset, and when I tried to delete it the delete operation messed up. Now the demo page is in a state where it thinks that asset is stored, but it is not actually, and if I can neither play nor delete the asset.
I'm not sure if this was the result of chance, or if it's specific to that asset. I did notice that there was an error when downloading the asset, though the asset was playing offline just fine even after the error... it's possible that one of the last segments failed to download or something, and that messed up the delete operation?
More testing will be required to know for sure.

**Comment by avelad** [comment]
I have tried this and I have not been able to reproduce the problem again, I have tried 10 times with different assets. I consider the problem solved.
Tested with the changes of https://github.com/shaka-project/shaka-player/pull/5936
