### ISSUE TITLE
Gesture support in mobile UI

### ISSUE THREAD

**Issue by jimist** [shaka-project/shaka-player#2239]
This feature request is for making the user experience better especially in full-screen mode. If you have experience using KMPlayer, you can see that hand gestures are pretty handy for backward, forward and turning the volume up and down. 

**Swiping left and right does the backward and forward respectively and swiping up and down, turns the volume up and down**. It must be noted that the speed of these swipes is important for how much change should be made.

These hand gestures should not be enabled until we are in the full-screen mode because they would overlap with other hand gestures that control the page, but they're pretty handy in the full-screen mode.

With the experience I have in developing the shaka-player, I guess that these should be handled in the **UI section** to be usable in the web player.

If any of the main developers see this, please set a guideline for the development if necessary, cause I'm more than happy to help. 

Furthermore, if any modification for the idea is necessary or there are any flaws in this idea, I'll be happy to hear it

**Comment by joeyparrish** [comment]
UI gesture support in fullscreen mode sounds reasonable.  Are you thinking just the four gestures you mentioned?  (Swipe up/down for volume, left/right to seek, with speed to indicate how much to seek/change volume.)

We'd be happy to discuss the design and review a pull request.  Thanks!

**Comment by jimist** [comment]
I am open to more ideas for the gestures. Currently, I have these 4 gestures in mind and I think it would be a good start for this path in the shaka-player.

I am also more than eager to develop this feature myself if it wouldn't be a problem.

I'll fork now and will work on this in the coming weeks. @joeyparrish 

As for the design, please just give me a headstart by where do you think it would be best to implement this feature; I'll read the code and follow the same structure for developing this.

I have the design below in mind:

1. In the '**ui**' section in '**controls.js**', we should have a method '**onHandGesture_**' and it will be called on any gesture
2. We will also have a '**shaka.ui.HandGestures**' which all the code regarding these sections's logic will be there.

If this design sounds good enough, I could start the development and further discussions could be made after some progress.

**Comment by ismena** [comment]
@jimist 
Sounds like a solid plan. Please feel free to start working on the PR (maybe, start with a single gesture first, so we can flash out the design in the process, if need be).

**Comment by avelad** [comment]
Is anyone in the community still interested in this? Otherwise the issue will be closed in 7 days.
