### ISSUE TITLE
Add plugin interface for storage mechanism

### ISSUE THREAD

**Issue by theodab** [shaka-project/shaka-player#2302]
We should make a plugin interface for offline storage mechanism; that is to say, to allow the user to optionally replace the IndexedDB implementation with their own custom storage mechanism, if they so wish. Now that we aren't changing the offline storage internals constantly, this should probably be doable.
Some demand has come up for this recently (see #2295).

**Comment by avelad** [comment]
Is anyone interested in this functionality? The issue will be closed in 7 days if no one answers.
