### ISSUE TITLE
Request for feedback: DASH-IF guidelines on timing model and DRM workflows

### ISSUE THREAD

**Issue by sandersaares** [shaka-project/shaka-player#2380]
DASH-IF is in the process of publishing (mid-2020) an update to the interoperability guidelines, which includes:

* [An interoperable view on the DASH timing model](https://dashif-documents.azurewebsites.net/Guidelines-TimingModel/master/Guidelines-TimingModel.html) - a constrained variant of the highly flexible DASH timing model, clearly defining that content authors should not be leaving any gaps in the timeline and focusing on what is actually implemented on common players, together with something of an illustrated guide to the various timing characteristics (inspired by [your awesome timing diagram](https://shaka-player-demo.appspot.com/docs/api/tutorial-architecture.html)).
* [Client workflows for content protection & security](https://dashif-documents.azurewebsites.net/Guidelines-Security/master/Guidelines-Security.html) - bridging the gap between DASH and EME by describing flexible workflows for how DASH clients should use the data in the MPD to activate and use DRM systems via an API such as EME.

Feedback from player developers is very valuable in ensuring these updates correspond to practical reality and avoid excessive ivory tower theorycrafting. If you can find the time, please give these documents a read and submit any questions or comments as issues in the GitHub repos referenced in the document headers.

While both documents are mostly new content in their entirety, I would draw your attention to the following aspects in particular:

* The timing model document makes some deviations from MPEG terminology and instead defines some (hopefully) easily understandable concepts like "sample timeline" and "MPD timeline". It also flips around some DASH concepts - instead of talking of "availability start/end times of segments", it defines an "availability window" that covers a range of time. Are these changes of viewpoint helpful? Or do they harm matters by deviating from MPEG standards?
* The client workflows for DRM system selection and activation are partly based on what we saw in existing players, partly pure theory added on top where we saw lack of required flexibility. There is a risk that we have not fully understood all the nuances of EME in defining this, so a review from actual daily EME-users would likely uncover something. Note that the document is designed in the spirit of EME but the guidelines are also intended to be applicable to non-EME platforms, so they intentionally do not use EME technical details like function names and such.
* There are differing views on whether encoders producing content with clock drift should be considered legal (and all clients required to compensate for the drift) or whether encoders should be responsible for correctly tracking real time (with clients allowed to assume content timing matches MPD). Your input into the discussion at https://github.com/Dash-Industry-Forum/Guidelines-TimingModel/issues/5 would be valuable.

**Comment by ismena** [comment]
Thanks for reaching out @sandersaares! Let me tag our overlord who rules over our time.
@joeyparrish, are we interested in participating? Would you like someone on the team to take a look at the docs? (probably @TheModMaker or @theodab, the rest of us haven't worked with DASH as closely)
