### ISSUE TITLE
Add a new method to storage to allow delete orphaned data

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#2420]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**Is your feature request related to a problem? Please describe.**

When a user clicks on download and before the download is finished it refreshes the page, the segments remain in the database but it is not possible to delete them without deleting the entire database (deleteAll).

**Describe the solution you'd like**

Add a new method to allow delete orphaned data in the shaka.offline.Storage class 

**Describe alternatives you've considered**

Allow to save the manifest while downloading the segments and update the indexes dynamically when new data is downloaded. The problem with this proposal is that IO operations are increased and cases of incomplete downloads would have to be managed, so a status would have to be added to the downloads.

**Comment by joeyparrish** [comment]
I agree that this is necessary.  A download status to flag in-progress downloads would also be a component of future work on background fetch, so adding that makes sense.

**Comment by avelad** [comment]
For me it's not longer necessary, so I'm going to close the issue.
