### ISSUE TITLE
Signalling the last segment number in Period

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#2430]
Add support to the feature described in DASH IOP 4.4.3.6. Signalling the last segment number in Period https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf

```
As indicated in clause 4.3.2.2, the content provider may not offer the last segment that is signaled in the MPD. If this is the case, the content provider should signal that the last segment is not the one indicated in the MPD.
At least the following three options may be considered:
 - Use the lmsg signalling as defined in clause 4.4.3.5.
 - Use the Segment Timeline with @r value greater or equal to 0.
Add a Supplemental Descriptor with @schemeIdUri set to http://dashif.org/guidelines/last-segment-number with the @value set to the last segment number.
```

This feature request is add support to `<SupplementalProperty schemeIdUri="http://dashif.org/guidelines/last-segment-number" value="368" />`

Sample stream: http://dash.akamaized.net/dash264/TestCasesIOP41/LastSegmentNumber/1/manifest_last_segment_num.mpd

**Comment by joeyparrish** [comment]
Sounds reasonable.  Thanks!

**Comment by joeyparrish** [comment]
This intersects with my work on #1339, which changes the way we generate segment references for DASH.  It will be relatively easy to integrate after that.
