### ISSUE TITLE
WebOS TV | After changing audio track or enabling text track the playback goes frame by frame (very slow)

### ISSUE THREAD

**Issue by SunDr17** [shaka-project/shaka-player#2431]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.7

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
no

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
WebOS 4.7.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG43UM7300PLB

**What are the manifest and license server URIs?**

http://video.beeline.tv/dash/channel026.isml/manifest.mpd

https://udrm.beeline.tv/cenc/widevine/license?custom_data=eyJjYV9zeXN0ZW0iOiJodHRwczovL3Jlc3QuYmVlbGluZS50di92NV8wXzIvYXBpX3YzL3NlcnZpY2UvYXNzZXRGaWxlL2FjdGlvbi9nZXRDb250ZXh0P2tzPWRqSjhORGM0ZklybmVSYjBxQjc4bEE1aFU0blVHTGN3ODZmR2NOaFhKMnk3ekpFV1RYTHZMazNJLUlwTUNCRTUyWWxGUlpROGo3dWdtcGtwT0dFWm9JX0tNTXFnc1I1ZzFCMDE1Vm80UFd3RkNhS211Z1Z6ZUh4Y0VxdTYxdmdjVXV3bWx0S3VpLWVoRXJ6VmVUanB1QzYtd1FRQkl4NEhfYXV1QVpnclFiSVhmcnRZTzZzQ05SUUphbXkwcHVUOXBpaEFPeC1yWjhGMFFZeDB6cWRHTlQtRm05a01YRVdkbkoxLXEzd1lHNjBiZlptUkJ2QTFBOWtfY2tDMTg1bXBPcWtqenBlZ01fZ09qVXAtd2g5am5HUEEzajRRZzNRPSZjb250ZXh0VHlwZT1ub25lJmlkPTEzMDIxNzEiLCJhY2NvdW50X2lkIjo0NzgsImNvbnRlbnRfaWQiOiJDaGFubmVsMDI2IiwiZmlsZXMiOiIiLCJ1c2VyX3Rva2VuIjoiZGpKOE5EYzRmSXJuZVJiMHFCNzhsQTVoVTRuVUdMY3c4NmZHY05oWEoyeTd6SkVXVFhMdkxrM0ktSXBNQ0JFNTJZbEZSWlE4ajd1Z21wa3BPR0Vab0lfS01NcWdzUjVnMUIwMTVWbzRQV3dGQ2FLbXVnVnplSHhjRXF1NjF2Z2NVdXdtbHRLdWktZWhFcnpWZVRqcHVDNi13UVFCSXg0SF9hdXVBWmdyUWJJWGZydFlPNnNDTlJRSmFteTBwdVQ5cGloQU94LXJaOEYwUVl4MHpxZEdOVC1GbTlrTVhFV2RuSjEtcTN3WUc2MGJmWm1SQnZBMUE5a19ja0MxODVtcE9xa2p6cGVnTV9nT2pVcC13aDlqbkdQQTNqNFFnM1E9IiwidWRpZCI6Ijk2NjRFMjE4MUUxNjc2MkMiLCJhZGRpdGlvbmFsX2Nhc19zeXN0ZW0iOjQ3OH0%3d&signature=kJ%2fkoNNST2fBwD5%2bgUKLy4JF9c0%3d&brandid=16&clientversion=7.0.0&udid=9664E2181E16762C&userid=2949598

**What did you do?**

1. Run playback
2. Select another audiotrack

**What did you expect to happen?**
Audio track changed, playback goes well

**What actually happened?**

After changing audio track or enabling text track the playback goes frame by frame (very slow), buffering is enabled and after each ~5seconds frame changes and audio doesn't play. No any errors in a console.

My code which select audio track:
`
    this.player.selectAudioLanguage(audioTrack.language);
    this.player.selectVariantTrack(audioTrack);
`

Checked with Playready and Widevine, for all playback goes slowly

**Comment by joeyparrish** [comment]
This sounds like it is probably a bug in the device firmware.  It will be difficult for us to figure out, though, because we don't have a WebOS device set up yet.

In the mean time, can you please try our demo app and some of the content in it?  We have both Widevine and PlayReady content available.  Please click the "search" tab at the top of the app and filter from there.

If this is a content-specific bug, this will help us figure that out and decide what the next steps could be.  If it **is** a firmware bug, it might be something you could work around with a change to your encoding & packaging.

**Comment by SunDr17** [comment]
@joeyparrish Please help me how to use your demo in TV and which one? What shall I load/build and run on TV?

**Comment by joeyparrish** [comment]
You could load https://shaka-player-demo.appspot.com/ on the TV's browser.

**Comment by SunDr17** [comment]
@joeyparrish I ran demo on WebOS and this problem is reproduced. On Tizen works well. But on WebOS video goes frame by frame. But it reproduced only on Live, on VOD all was correct. So the problem reproduces only on webos for live

**Comment by aluklon** [comment]
@SunDr17, very similar to this problem https://github.com/google/shaka-player/issues/2327. Try this solution https://github.com/google/shaka-player/issues/1610#issuecomment-440415869.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
