### ISSUE TITLE
UI language menu out of sync while casting

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#2486]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
nightly from 2020-04-07

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**What browser and OS are you using?**
ChromeOS 80

**What are the manifest and license server URIs?**
"Angel One" in the demo app

**What did you do?**
1. Load "Angel One"
2. Cast
3. Open the language menu
4. Change languages rapidly

**What did you expect to happen?**
The selected language should have the check mark next to it

**What actually happened?**
Sometimes, the selected language in the UI and the language being streamed on the TV get out of sync

I expect this is caused by the way CastProxy works.  It is possible that there's some timing issue between the events and getters being proxied to the device.

This is not a major issue, since it requires some aggressive user behavior and the impact of the bug is very low.

**Comment by multiplexer2** [comment]
This is still a quite annoying problem in 3.3.2, and applies to at least the Captions and Resolution selection as well. Just change state a couple of times while casting, and the menu will get out of sync with the actual player state. Aggressive clicking is not necessary to reproduce this problem. Sometimes it even happens on the first click on a menu item.

**Comment by joeyparrish** [comment]
Bumped priority to P2.
