### ISSUE TITLE
Suggest v3.4+ priorities here!

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#2505]
Given that the development of version 2.6 is coming to an end, I would like to be able to open the discussion of the things that are most priority for the integrators of the ShakaPlayer.

To limit the list each member should propose 3 things and in order of priority.

The items to pick should be the entries that appears in https://github.com/google/shaka-player/blob/master/roadmap.md

For me, the priority is:
1) Thumbnail tracks
2) Low-latency live (LHLS, equivalent for DASH)
3) Codec-switching

**Comment by joeyparrish** [comment]
I've pinned this to the top of the issues list and renamed it.  Please, everyone, let us know your top priorities for v2.7+.

**Comment by boredom2** [comment]
For us, the most important Functionality, we cant wait to use is any kind of Preload API. Far above anything else.

**Comment by riksagar** [comment]
I'd like to see a solution to #2179.  Then we could remove our workaround.

Not sure if that will be covered by your "Codec-switching" task

Regards,
Rik.

**Comment by Romain-Bernier** [comment]
For us, the most important functionality is the CMAF low latency.
Regards

**Comment by joeyparrish** [comment]
Please note that although our plans & timelines have not changed, we have decided to rename v2.6 to v3.0, and therefore v2.7 planning has become v3.1 planning.

**Comment by jakubriedl** [comment]
For us the most important values related to video playback are performance and stability. So if in future releases could be more effort spent on that we would welcome that. To highlight some ideas (not in order).
- data & drm preload API
- typescript support
- bundle size reduction
- some performance metrics API we could push to our analytics

**Comment by radiantmediaplayer** [comment]
100% Low-latency live (LHLS, equivalent for DASH) for us

**Comment by avelad** [comment]
@joeyparrish Are there already selected priorities?

**Comment by joeyparrish** [comment]
Thank you, everyone, for the feedback!

At this time, we are prioritizing LL-HLS, followed by MediaCapabilities + codec-switching.  We have a design for LL-HLS from @michellezhuogg, who will also work on the implementation.

**Comment by avelad** [comment]
Will low latency be supported in DASH?

**Comment by joeyparrish** [comment]
At a minimum, we will add support for the `availabilityTimeOffset` attribute for low-latency DASH.  We are debating the value of also using `ReadableStream` to pipeline data from the network into MediaSource for LL-DASH.  This would require major changes to `NetworkingEngine` and the scheme plugin API, so we want to make sure there is a measurable latency improvement before we commit to a breaking change like that.

**Comment by avelad** [comment]
There is a DASH-IF presentation where this topic is discussed. Really if chunks are not passed directly to the media source, there is really no low latency, because chunks would not be used at all.

https://dvb.org/wp-content/uploads/2020/03/Latest-on-DASH-low-latency.pdf

![image](https://user-images.githubusercontent.com/8983024/84235937-11c52c00-aaf7-11ea-83c3-6f55c2955d89.png)

According to the previous image, which case is the one you want to implement?

**Comment by adgllorente** [comment]
It would be great to have:

- Thumbnail tracks
- CMAF support
- Stream Preload

**Comment by jjtfsalgado** [comment]
For us would be the ability to play media playlists #2300

**Comment by joeyparrish** [comment]
@avelad, let's discuss details of DASH low-latency on #1525.

**Comment by Maxou44** [comment]
It would be awesome to have:

1) Codec-switching
2) Be clever and choose a stream resolution adapted to the player size  (to save bandwidth if the player is tiny) 
3) Bundle size reduction

**Comment by OrenMe** [comment]
1. prefetch/preload - ability to load additional medias in addition to current playing one #880
2. low level analytics for performance and advanced analytics - segment/manifest/license load times, processed data etc
3. additional offline support - https://github.com/google/shaka-player/issues/879, https://github.com/google/shaka-player/issues/1347, https://github.com/google/shaka-player/issues/1301

@avelad @joeyparrish would you be interested to maybe link to issues opened per item in the roadmap and we can then collect thumbs up on each to see community traction? I would really appreciate this and enjoy if we have this.

**Comment by enjikaka** [comment]
Would also love to see Preload API, with support for [seamless playback](https://developers.google.com/web/fundamentals/media/mse/seamless-playback) between two dash manifests.

**Comment by joeyparrish** [comment]
Hi everyone,

At this point, we are nearly done with v3.1, which will include LL-HLS and LL-DASH, plus our own CEA 608/708 parser to replace mux.js.  I will rename this issue to continue to collect feedback on priorities for v3.2, for which work has not yet started.

**Comment by j0hnlam** [comment]
Codec switching/preference would be great for 3.2 - https://github.com/google/shaka-player/issues/2179

**Comment by Forium777** [comment]
Smooth streaming support is a priority to be competitor with other players like dash.js #703

**Comment by Maximusya** [comment]
+1 for
- [Preload API #880](https://github.com/google/shaka-player/issues/880)
- [persistent license renewal #1347](https://github.com/google/shaka-player/issues/1347)
