### ISSUE TITLE
Use "this" in static methods

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#2532]
To solve #2528, we need to upgrade the compiler.  A side-benefit of the upgrade is that we will finally be able to use `this` in static methods.  The use of `this` in static methods has long been part of ES6 classes, but the compiler version we used did not support it.

We should clean up our many, many self-aliases in static methods.  For example, in `lib/util/string_utils.js`, we currently have this:

```js
  static fromBytesAutoDetect(data) {
    const StringUtils = shaka.util.StringUtils;
    // ...
      return StringUtils.fromUTF8(uint8);
```

The alias would be removed and the call site would use `this` instead:

```js
  static fromBytesAutoDetect(data) {
    // ...
      return this.fromUTF8(uint8);
```

**Comment by avelad** [comment]
Since our plan is to migrate to TypeScript, @joeyparrish, are you okay if we close this issue?

**Comment by joeyparrish** [comment]
Yes, fine with me.
