### ISSUE TITLE
Audio starts before video on 2020 Tizen TVs

### ISSUE THREAD

**Issue by rez** [shaka-project/shaka-player#2570]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.10

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
N/A / Tizen

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
 Model: `QN49Q80TAFXZA` Firmware: `T-NKMAKUC-1113.0, b1031200/B30101 ,BT -S`

**What are the manifest and license server URIs?**
I will send a link to the provided email with issue name, number and example video. 

**What did you do?**
To reproduce you can load a video, ideally at a point where there should be audio, and play. I also reproduced the behavior while seeking.

**What did you expect to happen?**
I expected that when the video starts playback the audio to match and be in sync.

**What actually happened?**
What actually happened is that the audio will start playback while the video is in some pause state. The video will start playback some time later.

From the look of it it appears that the video is actually ahead of the audio. The audio plays or catches up to the video and then when they are in sync the video will start.

------------

I am attaching a link to a video of the issue for more visibility. You can find it [here](https://drive.google.com/file/d/1A_SxnOAETjf7PKerVOQN9vNB8k3UofYG/view?usp=sharing)

**Comment by chrisfillmore** [comment]
Does this happen on any other model year Tizen TV?
Can you trivially reproduce this with any content? Like the sample content in the Shaka demo app?
Are you playing DASH or HLS?
Is your content protected by DRM? Is it Widevine or PlayReady?

**Comment by rez** [comment]
I have only experienced the issue on this model of 2020 Tizen TV.

This behavior has been reproduced across a variety of content(Shaka demo and our custom app), HLS, Dash and DRM(PlayReady) enabled.

**Comment by leszek-syroka** [comment]
I can confirm that the issue is still reproducible at Tizen 2020 TVs. There is a A/V desynchronization when playback rate is changed from 0 to 1. It's the platform side issue.

The only workaround I can suggest from Shaka player side it to use _play_/_pause_ instead of changing playback rate to 0/1.

**Comment by avelad** [comment]
In the latest versions we removed the playback rate change for the buffering control. Can you try it again with 4.6.X? Thank you!
