### ISSUE TITLE
HLS content playback on Safari does not use UITextDisplayer

### ISSUE THREAD

**Issue by Qingkui9** [shaka-project/shaka-player#2585]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
The one from master branch.

**Please ask your question**
It seems like the HLS content playback on Safari doesn't pick up the UITextDisplayer. It is alway using its own shadow dom text track container. Is this the correct behavior or did I miss anything?

**Comment by joeyparrish** [comment]
Native HLS playback on Safari includes native text rendering, I believe.  I don't think we have any control over that, as the subtitles/captions are fetched by Apple below the level of JavaScript.  We don't have any access to that data unless we are in control of playback, as we are when we use MediaSource on desktop Safari or other platforms.  But MediaSource isn't an option for us on iOS or when FairPlay is used on desktop.

Sorry for the confusion!

**Comment by avelad** [comment]
I think there is a way to implement this. Taking the cuechange event, you could map activeCues to a Cue understood by the ShakaPlayer and use the UITextDisplayer.

Note: for this you would also have to disable native rendering via css.
Note2: right now Safari supports PiP with subtitles and this would be lost.

**Comment by TheModMaker** [comment]
In my testing, native HLS doesn't populate the `activeCues` field.

**Comment by avelad** [comment]
I just tested again with Safari 13.1 in macOS 10.15.4 and activeCues only is available with showing mode

**Comment by TheModMaker** [comment]
I tested in Safari 13.0.5, so it may be a new feature.  So we can have this be an enhancement for the future.

**Comment by avelad** [comment]
I attach a screenshot with what I see and with the code that I have tried:
![Captura de pantalla 2020-05-27 a las 8 34 03](https://user-images.githubusercontent.com/8983024/82985751-defa3e80-9ff4-11ea-8557-1118f8de82c9.png)

@TheModMaker If you make the same change as me, do you see the same result?

In Safari you can modify the css cue style with 

```
video::-webkit-media-text-track-container {
    // Style the container
}

video::-webkit-media-text-track-background {
    // Style the text background
}

video::-webkit-media-text-track-display {
    // Style the text itself
}
```

With this you can disable CSS rendering and use activeCues as you like.

**Comment by TheModMaker** [comment]
Sorry, I naively just picked the first TextTrack element.  After finding the active one, I see the `activeCues` contains the correct cues.

**Comment by bidisha15hotstar** [comment]
Still exists for me.

**Comment by bidisha15hotstar** [comment]
@joeyparrish , the active cue is empty when we switch to english to arabic to english.

**Comment by avelad** [comment]
Is there anyone still interested in this? Thanks!

**Comment by avelad** [comment]
@tykus160 will work on it
