### ISSUE TITLE
Error reporting refactor

### ISSUE THREAD

**Issue by MilosRasic** [shaka-project/shaka-player#2617]
**Is your feature request related to a problem? Please describe.**
Current error reporting is very well documented at https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html

This implementation is fine when debugging an app that uses Shaka Player, but it's driving me nuts when working with a crash reporting tool. There's two major problems:

1. Error codes. Is there any obstacle to just using name strings? Currently, we have code like this:
```
const getErrorName = (code, shaka) => {
	if (!shaka) {
		return;
	}

	// eslint-disable-next-line consistent-return
	return Object.keys(shaka.util.Error.Code).find(
		errorName => shaka.util.Error.Code[errorName] === code
	);
};

const isNetworkFailure = code =>
	[
		1000, // UNSUPPORTED_SCHEME
		1001, // BAD_HTTP_STATUS
		1002, // HTTP_ERROR
		1003, // TIMEOUT
		1004, // MALFORMED_DATA_URI
		1005, // UNKNOWN_DATA_URI_ENCODING
	].includes(code);
```

It's not too much of a problem I guess, but is it really necessary? What do the numeric IDs give us that we wouldn't have with strings?

2. Error details in `error.data` array. This is fine when debugging, but for filtering and grouping errors in a crash reporting tool it's almost impossible to work with. Those tools usually only support simple operations like "equals" and "contains" in their query languages and we can't access a JSON blob to check elements of an array.

If trying to map this error detail format to something more usable for crash reporting, there's the problem of a "moving target". For example, "original error" is sometimes `error.data[0]`, sometimes `error.data[1]`, etc.

**Describe the solution you'd like**
1. Simply replace numeric error codes with strings. If an app sees value in exposing numeric codes to end users, they can come up with their own set.

2. Switch from an array to a simple key/value pair object. For example, this:
> error.data[0] is the URI.
> error.data[1] is the status code.
> error.data[2] is the response text, or null if the response could not be interpretted as text.
> error.data[3] is the map of response headers.
> error.data[4] is the NetworkingEngine.RequestType of the request, if one was provided.

would become something like this:
```
{
	uri,
	statusCode,
	responseText,
	responseHeaders,
	requestType,
}
```

This would be much easier to use. Some crash reporting tools would probably support it out of the box, for others, mapping by looking for a property of an object is much more straightforward than looking for an array element at an index which depends on error code.

**Describe alternatives you've considered**
Complex app code to transform shaka errors into something usable by crash reporting tools is the only alternative I can see, but not a great one.

Also, Shaka could provide helpers to extract specific error details, but the above solution seems cleaner to me. The only catch is the above would require a major version bump (changing library API) and helpers would be minor (new feature) according to semver.

**Additional context**
![shakaerrors](https://user-images.githubusercontent.com/533052/83748377-646b9780-a662-11ea-97f8-6a5f2754f57a.png)

**Comment by joeyparrish** [comment]
Thanks for the feedback!  This is really helpful.

We originally assumed that numeric codes would be preferable for logging in production, but perhaps we were mistaken.  The string name of the error is available and provided in debug builds.  It would not be difficult to offer that in all builds.  Here's the code I'm referring to:

https://github.com/google/shaka-player/blob/ec2674a4d891aeec6732b7500ad50faf858f7435/lib/util/error.js#L68-L108

We could also replace the `data` array with a dictionary.  So long as errors supplied both `data` and the dictionary for a while, this could be a minor version bump.  Later, we would remove `data` in a major release.

**Comment by chrisfillmore** [comment]
@joeyparrish In my (enterprise) organization, there is an army of folks (some engineering, some not) looking at analytics before the information makes it to actual developers. I believe that including error names in production would help these people, for the simple reason that a short, descriptive phrase like an error name is easier to remember than a number. Keep in mind that these people may be dealing with errors from multiple domains (different device clients, protocols, vendors, etc).

A requirement that my team has internally is that error codes must be attached to a domain. This allows us to resolve error code collisions. I work on a "video playback sdk" which itself has error codes like 1001, 1002, etc. Errors from Shaka get the domain `com.google.shakaplayer` and errors from my component get `com.myorg.mycomponent`. Though Shaka has few dependencies (I think muxjs may be the only one?), adding a "domain" attribute could be a non-breaking, useful enhancement for users of Shaka.

For what it's worth though, I don't think that it makes any different whether error data is provided as a dictionary or array. In either case, clients can (and should, IMO) normalize their error information to an interface particular to their domain.

I think the only advantage to adopting a dictionary would be if it became possible to inspect these errors, and their associated data, statically. Something like this is possible in TypeScript via indexed types and generics. I don't know Closure Compiler but I assume it does not support that.

**Comment by chrisfillmore** [comment]
One more thing to add: I do think numeric error codes are useful in general. Consider HTTP status codes and the implication of error ranges. This attribute is very useful.

**Comment by avelad** [comment]
Is anyone interested in this? If not in 7 days the issue will be closed.
