### ISSUE TITLE
Reduce polyfill requirements

### ISSUE THREAD

**Issue by marcelbeumer** [shaka-project/shaka-player#2625]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**Is your feature request related to a problem? Please describe.**

I need to explain customers which polyfills I'm shipping, and also worried about having to fix possible collisions (not happened yet)

**Describe the solution you'd like**

Shaka Player requires several polyfills for cross browser playback. 

I’m integrating Shaka in a custom video player solution that is integrated into several third party websites. The less polyfills the better: less risk for collision with other libraries, less pollution of the global namespace, less to explain and warn consumers of the video player for. 

I looked at the list of polyfills and these are my notes:

* Fullscreen: not needed to polyfill, can use an internal API instead
* InputEvent: not needed to polyfill, could use an internal API instead
* PiPWebkit: not needed to polyfill, could use an internal API instead
* Languages: not needed to polyfill, can take navigator.language as fallback if navigator.languages is not there
* MathRound: not needed to polyfill, internal helper function could do too
* VideoPlayPromise: not needed to polyfill, this could be done inside the player code itself (return the promise of the videoEl.play or your own Promise.resolve())
* VTTCue: not needed to polyfill, could use internal API instead
* VideoPlaybackQuality: not sure, haven’t looked into it. Can’t this be abstracted away inside the player itself?
* PatchedMediaKeysApple|Ms|Nop|WebKit: not sure, haven’t looked into it. Can’t this be abstracted away inside the player itself?
* MediaSource: not sure, haven’t looked into it
* indexedDB: not sure, haven’t looked into it, but hard to imagine why internal API would not be good enough
* EncryptionScheme: not sure, haven’t looked into it

What do you think? 

Thanks in advance and thanks for Shaka!

**Describe alternatives you've considered**

Alternatively for "internal API" suggestions above, maybe some could be passed as external dependancy too (similar to mux.js that's now used from window/global but could be passed to constructor)

**Additional context**

**Comment by chrisfillmore** [comment]
Fwiw I strongly support injecting these dependencies where they're needed, rather than polyfilling them.

**Comment by ismena** [comment]
@joeyparrish this seems like your department. Could you please comment on our direction for this?

**Comment by joeyparrish** [comment]
Changing direction on polyfills would be a breaking change, so if we did it, it would have to be done carefully and would require a bump to Shaka Player v4.

That said, we considered the tradeoffs between polyfills and abstraction layers very early in the project's history, and we chose polyfills.  I think everything we polyfill could have been done as an abstraction layer instead.  At the time, it seemed like the best choice.

To be honest, I don't really understand why abstraction layers would be preferable for either of you.  Could you elaborate on the down sides of these particular polyfills or the polyfill approach in general?

**Comment by chrisfillmore** [comment]
I previously had an issue (#1032) where Shaka's polyfills were colliding with some feature detection I was doing. Ultimately we resolved it on our end by adjusting our application's behaviour.

I don't have a current issue. However, I do believe external libs should avoid polyfilling the browser as it introduces the risk of collisions. I would flip the question and ask, what benefits do polyfills confer over standard dependency injection?

**Comment by joeyparrish** [comment]
Thanks for the link.  I had forgotten about the conversation in #1032.

> I would flip the question and ask, what benefits do polyfills confer over standard dependency injection?

When we can write code in the library assuming a browser that implements standard web APIs as spec'd, we can greatly simplify the process of writing and maintaining that code.  When we older browsers and platforms fall out of use and we stop supporting them, we just delete the polyfill.

**Comment by joeyparrish** [comment]
> I don't have a current issue. However, I do believe external libs should avoid polyfilling the browser as it introduces the risk of collisions.

Another alternative would be to require you to install your own polyfills at the application layer.  Which, effectively, we do by asking you to call shaka.polyfill.installAll().  If it's really about conflicts, and you want to be in complete control of polyfills, just don't call that method.

And when you need to support a Tizen TV, you can figure out what polyfills are needed for that platform (VTTCue, EME) and install them.  And when you need to support IE, you can figure out what polyfills are needed (VTTCue, EME, Promises, events, ...)

**Comment by chrisfillmore** [comment]
Putting the onus on the client to install any polyfills does not actually address the problem of collisions. I work on a component which essentially provides an abstraction over Shaka and other players. I am only one part of larger client applications, and **my** clients may be doing their own feature detection, using any other MSE players, and handling their own polyfills, at any time before or during playback. Sure, I may be able to coordinate with other teams within my org, but what if some component of my broader application is being handled by an external contractor? Now I have to coordinate with them too. Global polyfills make this very bad for clients. Dependency injection would avoid this problem entirely.

Shaka has a hard dependency on MSE/EME. This has benefits for Shaka: you can avoid an extra layer of abstraction, and make more assumptions about your environment. But it has downsides for Shaka too: the code base has many platform-checks in core components like DrmEngine. And the downside for Shaka's clients is what I described above: polyfills can make it difficult to do our own feature detection, etc.

**Comment by joeyparrish** [comment]
Okay, that makes sense.  Thanks for taking the time to explain it.

We still can't commit to this change yet, mainly because of backward compatibility.  But we will consider this in our planning and look for an opportunity to do better.

**Comment by chrisfillmore** [comment]
Ok thanks for listening!

**Comment by vodlogic** [comment]
We are also facing a similar challenge of wanting to selectively install polyfills.

I had a look at installing them individually, however each polyfill class and its corresponding `install()` function are not exported in the annotations so they are not available in the compiled player.

As a test I added the export annotations to the source code, recompiled the player and was able to use `shaka.polyfill.MediaCapabilities.install()` in our application.

Would it be possible to review whether exporting the install functions would be a reasonable and low effort interim step?

**Comment by joeyparrish** [comment]
I think it would be very reasonable to export the install methods of individual polyfills.  Please feel free to send a PR!

**Comment by avelad** [comment]
Is anyone interested in this? Otherwise the issue will be closed in 7 days. Thanks!
