### ISSUE TITLE
Document useful getters for various events

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#2657]
Many events have no extra properties, so we should document clearly for these events which getters or other methods an app may want to use on the event.  For example, on `adaptation` events, an app may want to look at `getStats()` or `getVariantTracks()` to see what happened.

**Comment by ismena** [comment]
I'm moving this to the backlog for now as it has lower priority than other 3.1 issues. 

It will stay assigned to me, so I have it on my radar, but it won't distract the rest of the team. 

If we can squeeze it in, we will, otherwise it'll go out in a later release.
