### ISSUE TITLE
Expose PresentationTimeline segment availability duration through Player

### ISSUE THREAD

**Issue by Stansbridge** [shaka-project/shaka-player#2711]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Mostly :-)

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I have done a solid search

**What version of Shaka Player are you using?**
2.5.5 - precompiled NPM package

**Please ask your question**
I'd like to access the MPD `timeShiftBufferDepth` value which is stored inside `PresentationTimeline.segmentAvailabilityDuration_`. 

There doesn't appear to me to be an idiomatic way to retrieve this value without either: 
a) re-implementing the current `DashParser` as a plugin with a custom escape-hatch or event emission
b) maintaining a fork of Shaka to expose this value as an external

I have figured I can actually almost retrieve this, if I was _really_ determined, by reversing the logic within Shaka source (please forgive me):
```javascript
const { presentationTimeline } = player.getManifest();
presentationTimeline.setUserSeekStart(-Infinity);
const start = presentationTimeline.getSegmentAvailabilityStart();
const end = presentationTimeline.getSegmentAvailabilityEnd();
const timeShiftBufferDepth = end - start
```

I'm hoping there is something nicer that isn't using `getManifest()` which has clearly begun a deprecation process. Thanks!

**Comment by TheModMaker** [comment]
Why would you need this value?  The main reason I would think you'd want this is to determine the seek range.  In this case, you can use `player.seekRange()` to get the seekable ranges and can use the difference to find the size.  This will approximately be that value, but accounts for things like recently started live streams.

**Comment by Stansbridge** [comment]
Thanks @TheModMaker 

>The main reason I would think you'd want this is to determine the seek range

Yes, correct. In most cases we are happily using `player.seekRange()`. 

We would like to access the value of `PresentationTimeline.segmentAvailabilityDuration_` to understand what the future expected duration of a stream will be. We maintain long DVR windows and it is valuable for us to know the manifest value in advance. Specifically for our particular use case, we need this value to ensure our UI is rendering correctly in certain edge cases.

**Comment by Stansbridge** [comment]
@joeyparrish 

>What do you mean about the "future duration" of a stream?

Sorry for the ambiguity - We would like to access the value of `PresentationTimeline.segmentAvailabilityDuration_` to estimate the future dvr window length.

>How does what you want differ from player.seekRange()?
This accounts only for the current range of time that seeking is allowed.

For example:

If a stream has been live for 10 minutes with a tsbd value set to PT3H we could expect `player.seekRange()` to provide a dvr window of 600 seconds but the internal value of `PresentationTimeline.segmentAvailabilityDuration_` to be 10800.

Access to this value is really useful to us. If the Shaka team disagrees then we will continue using our workaround. Thank you!

**Comment by joeyparrish** [comment]
Ah, I see.  You want to know the full DVR window, but there may not yet be enough content to fill it.  That's very reasonable.  I'll reopen this as a feature request.
