### ISSUE TITLE
Stop extending segment references to cover gaps

### ISSUE THREAD

**Issue by ctt828** [shaka-project/shaka-player#2729]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.0.1

**Please ask your question**

For my use case, there are 'static' medias which are composed of multiple periods, 
and there may be 'intended' gaps on the presentation timeline : 

1. in the front : period[0]`@start` is not zero
2. between periods : period[i+1].start_time > period[i].end_time
3. in the rear : mediaPresentationDuration > last_period.end_time

I need to get the start and duration info for each period so I can present the intended gaps on the seek bar.

1. I use SegmentTimeline in my MPDs so I start with `lib/dash/mpd_utils.js - createTimeline()`: 

    from :
    ``` javascript
    if ((timeline.length > 0) && (startTime != lastEndTime))
    ```

    to :
    ``` javascript
    if ((timeline.length > 0) && (startTime < lastEndTime))
    ```

2. `lib/media/segment_index.js - fit()`

    from :
    ``` javascript
    this.references[this.references.length - 1] =
        new shaka.media.SegmentReference(
            lastReference.startTime,
            /* endTime= */ windowEnd,
            .......
            );
    ```

    to :
    ``` javascript
    this.references[this.references.length - 1] =
        new shaka.media.SegmentReference(
            lastReference.startTime,
            lastReference.endTime,
            .......
            );
    ```

3. Now I can get the correct period end time from :
    ``` javascript
    myPlayer.getManifest().variants[i].video.segmentIndex.indexes_[i].references[#THE_LAST_SEGMENT].endTime
    ```

Q1. Is the above modification safe?

Q2. Is there a better way to get the period info (start & duration)?

Q3. I would be grateful if you could give me a hint about how to always get the playhead positioned at 00:00 instead of start of the first period, so the initial gap can be present on the seek bar.

Thank you!

**Comment by michellezhuogg** [comment]
Hello @ctt828 ,

Could you please help me to understand better the purpose of 'intended' gaps on the presentation?
Periods cannot overlap and should not have gaps between them (although Shaka Player supports gap jumping). 
https://github.com/google/shaka-player/blob/master/docs/design/dash-manifests.md

**Comment by joeyparrish** [comment]
Shaka Player is open source, and you're free to make whatever modifications you wish in your own fork.  But I don't believe those modifications are ones we would accept into the repo.

I could be wrong, but I would not expect content as you described to be permitted by DASH IOP (InterOp Points).  If there is a better way to achieve what you are trying to do, we may be able to recommend another approach that would be interoperable and would work in Shaka Player the way you would want.

**Comment by ctt828** [comment]
@michellezhuogg 
We are developing a video recording & playback service for our surveillance products,
for the continuous recording use case as an example, a gap on the media timeline should be presented 
to the user to indicate that a camera was offline so there is no media available for that period of time.

@joeyparrish 
In my opinion, the Period@start and Period@duration are open fields controlled by the media producer,
so if a gap is not allowed by DASH, it should be the media producer's responsibility, not the player's.
In other words, if the player received a MPD that does contain a gap, the "stretching the last segment to fill the gap" technique  
does not make the gap playable anyway.

It may be a good idea for the MPD parser to just provide original information carried in a MPD,
including start and duration info of each period in a presentation, and that's what I am trying to achieve
in my modifications. But I am not sure if the modifications are safe and still don't know how to present the initial gap on the seek bar. Appreciate for any advices, thank you!

**Comment by TheModMaker** [comment]
The DASH IOP doesn't say anything about gaps between Periods, but it does say that a Period is expected to continue until the next.  The IOP does say there are allowed to be gaps between `SegmentTimeline` elements.

We currently extend segments so the timeline is continuous, but I can see the use of having the UI show gaps in the content.  We  currently support both DASH and HLS and v3 has squashed the Periods into a single stream.  This means you can't explicitly get the different Period times, but we could remove the segment extending and allow an app to see the original segment times.  They then could use that to determine if there are gaps in the stream.

You would use `player.getManifest()` to get the manifest, then use `await stream.createSegmentIndex()` to ensure the index is available and use `Array.from(stream.segmentIndex)` to get the list of references.  You can do that now, but the references should be continuous.

**Comment by avelad** [comment]
Is there anyone still interested in this functionality? Otherwise the issue will be closed in 7 days.
