### ISSUE TITLE
CastReceiver does not work play/pause from the remote

### ISSUE THREAD

**Issue by alex2844** [shaka-project/shaka-player#2730]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.0.1

**Are you using the demo app or your own custom app?**
demo

**What browser and OS are you using?**
Chrome OS, Android TV

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Xiaomi mi box S, Android TV 9

**Comment by ismena** [comment]
Unfortunately, we don't have access to an Android TV for debugging or reproing at this time(
I'll leave the issue open in case anyone in the community faced a similar problem and might be able to help.

**Comment by alex2844** [comment]
The problem is not only on Android TV, but also on Chromecast - I checked the Chromecast ultra on the device

**Comment by theodab** [comment]
Well, if this also happens with Chromecast, then I can look into it.

**Comment by theodab** [comment]
Can confirm. I enabled HDMI-CEC, so that I could use my remote to control the Chromecast, and I was not able to pause or resume.
By comparison, when casting YouTube onto the Chromecast, I was able to pause with the remote... but not to resume?
Well, whatever, I'll see if I can figure out how to fix this.

**Comment by ismena** [comment]
@theodab I thought it might be a problem of us not using the lastest version of the Chromecast SDK (v2 vs CAF? I vaguely remember another issue mentioning this), but the fact that it also affects Android TVs make me doubtful.

**Comment by joeyparrish** [comment]
I checked in with the Cast team, and they suspect it has to do with our using an old SDK and not using the preferred method of creating a media receiver app.  See also #2635.

I'm working with the Cast team to find a migration path for Shaka's receiver apps to CAF.  We'll keep both issues updated as we make progress.

**Comment by SadiqaliZaveri** [comment]
@alex2844 Faced something similar and it was solved by adding a tax index attribute to the play button and then focusing it. Hope this helps.

Shaka V3.1.0
Android TV - MI

**Comment by avelad** [comment]
Our effort must go along the lines of implementing https://github.com/shaka-project/shaka-player/issues/4214 so I am going to close this issue. Sorry!
