### ISSUE TITLE
Attach compiled code to GitHub releases

### ISSUE THREAD

**Issue by thenewguy** [shaka-project/shaka-player#2738]
Please include compiled assets with the release

**Comment by TheModMaker** [comment]
Do you mean assets (i.e. the media content), or asserts (i.e. checks in the code to validate invariants)?

If you are talking about the media, I don't see why we should include the media.  We don't provide media, we provide a library.  Requiring people to download gigabytes of media to get a library is highly unusual.  Also, a lot of our demo assets are not managed by us, but are hosted by third-parties.  So we can't just include the segments.

If you mean *asserts*, then why would you want them?  They should never happen in production code since they are checking our internal assumptions about our code.  Having them increases the size of the release and shouldn't add much.

**Comment by thenewguy** [comment]
@TheModMaker Hey. Sorry I was so brief.

I meant the compiled js and css - preferably not minified.

I was trying out the player for the first time and it is convenient for first use to be able to drag a javascript folder from the github release download into the local webserver static folder.  Figured the feedback would be useful from the perspective of a new user.

If you're strongly against it I don't suppose I would argue for it.  But it is certainly more convenient the first time trying a new project if the boiler plate can run against a local copy without making me learn the compilation toolchain.  Using a CDN version is certainly one way to do it but local copies can be preferable

**Comment by joeyparrish** [comment]
Compiled code and CSS are included in our releases via NPM and various NPM-driven CDNs.  If you use any of these means, you have them in `dist/`.  If you want unminified, use the variants with `debug` in the file name.

The compiled code is never checked into the repository in github, even in release branches & tags.  I don't see why one would check in compiled binary code.  (Would we require it to be updated on every commit?)  Compiled releases of this project are generally consumed via NPM or some other distribution mechanism.  You won't get that through github download links.

If you want to compile it yourself (from git clone, a github download zip file, or even after npm install), it's pretty easy.  Compiling the code requires python (build scripts) and Java (compiler).  Just run `python build/all.py`.  That will generate both fully-compiled production builds and debug builds.

See also [the "Basic Usage" tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) and [the "Debugging" tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html).

Does this help?

**Comment by TheModMaker** [comment]
@thenewguy is suggesting we add a tarball with the compiled release when we make a release.  This is how we do it in [Shaka Player Embedded](https://github.com/google/shaka-player-embedded/releases).  When we make a release, we could zip up the NPM bundle and include that in the GitHub release page so people can download it directly from the release tab.

**Comment by joeyparrish** [comment]
Ah, I see.  That would be a change to our release process.  Jacob, can we automate that when we push the tag?

**Comment by thenewguy** [comment]
You should definitely be able to automate it. It shouldn't be a manual process as that would be a lot of trouble

**Comment by TheModMaker** [comment]
We should be able to automate it within our release script.  When we publish the NPM package, we can just also run `npm pack`, which creates a tarball of the NPM files (the same as the release itself).  We can then upload that with the GitHub release tag.

**Comment by thenewguy** [comment]
This might simplify things for you: https://github.com/actions/upload-release-asset

**Comment by joeyparrish** [comment]
We don't have time to augment our release tools yet, so I attached the tarballs manually to v2.5.14 and v3.0.2.  Hope this helps!

**Comment by avelad** [comment]
Is anyone interested in having this done? Thanks!

**Comment by joeyparrish** [comment]
This is already done since we revamped the release workflow.  Every release since 4.0.0 has this.
