### ISSUE TITLE
Tweak ABR estimator settings

### ISSUE THREAD

**Issue by naktinis** [shaka-project/shaka-player#2766]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**Is your feature request related to a problem? Please describe.**
I found that my bandwidth is underestimated by a factor of ~2-3x and that I can reliably fix it by increasing abrEstimator's minBytes_ to 32000.

**Describe the solution you'd like**
Make abrEstimator_ accessible (not private) or minBytes_ configurable in some different manner.

**Describe alternatives you've considered**
One alternative would be to ask you to set it to 32000 or some other higer value, but this may not work for everyone. Currently I have to manually change the minified source code, but it's ugly and I risk forgetting to change it after upgrading to a recent shaka-player version.

**Additional context**
I've seen this and other related estimator parameters discussed here:
https://github.com/google/shaka-player/issues/435
https://github.com/google/shaka-player/issues/1366

**Comment by joeyparrish** [comment]
We should experiment with bandwidth estimation on various browsers and confirm that our settings are correct for the scenarios we can test.  It is concerning that @naktinis got 10-20x lower bandwidth estimates on non-Chrome browsers.

One thing that could be causing this is the lack of the NetworkInformation API on non-Chrome browsers.  This API allows us to start closer to the ideal bandwidth early on.  If the lack of this in other browsers means lower estimates, it could be that it takes too long to converge on the best estimate without it, or that the default bandwidth estimate (used before we have any data) should be increased.

If the NetworkInformation API and default bandwidth estimate can't explain any observed difference, then we should evaluate modifying the constants in the estimator, as @naktinis suggested.

**Comment by naktinis** [comment]
Am I right to assume that this has been solved by #3422?

For example, this config is now possible as an equivalent of what's described above:
```
abr: {
    advanced: {
        minBytes: 32000
    }
}
```

**Comment by joeyparrish** [comment]
I don't know if it has been solved per se, but that setting should be a workaround at least.  I would consider this solved if we thoroughly tested and verified our defaults, and made any necessary updates to the defaults to ensure good performance out of the box.

**Comment by avelad** [comment]
The current values are correct, and for LL-HLS it is necessary not to increase minBytes because otherwise we would lose many samples. Since we already allow the configuration, I consider the issue resolved. Thanks!
