### ISSUE TITLE
Detach/re-attach to the video element on client-side ads for devices that don't support multiple media elements

### ISSUE THREAD

**Issue by ismena** [shaka-project/shaka-player#2792]
Some device types don't support multiple video elements on the page and CS IMA has to reuse the same video element to show ads. (Tizen, WebOS)
For this scenario, we need to detach from the `<video>` and re-attach after the ads has finished playing.
IMA has an [isCustomPlaybackUsed](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsManager#isCustomPlaybackUsed) method that we can call to check if the media element is gonna be reused (true if the method returns true :)).

We can call it when we get [a content pause is requested](https://github.com/google/shaka-player/blob/master/lib/ads/client_side_ad_manager.js#L194) by the SDK, and detach from the element if need be.

We'll need to save `video.currentTime` to be able to resume playback once [the ads are done playing](https://github.com/google/shaka-player/blob/master/lib/ads/client_side_ad_manager.js#L232).

**Comment by bruno-sartori** [comment]
Any updates on this?

**Comment by Boubalou** [comment]
While implementing this logic on our end while waiting for this to be provided within Shaka, we faced an issue where track IDs upon a detach/attach flow would change and get incremented, leading to our comparison to select a text track to be broken.

It would be nice to keep that in mind or allow a way to reset that state of IDs when re-attaching the player with the same manifest after an ad.

**Comment by avelad** [comment]
I plan to implement this as soon as the Preload API is working correctly for unload

**Comment by avelad** [comment]
With the following code implemented on the application side it is possible to support it:

Using `ads.customPlayheadTracker = true` and v.4.8 or above


```
this.eventManager_ = new shaka.util.EventManager();
const adManager = this.player_.getAdManager();
let loadTimeout;
let prevPreload;
this.eventManager_.listen(adManager, shaka.ads.AdManager.AD_STARTED, async (e) => {
  if (e?.originalEvent?.type !== google.ima.AdEvent.Type.CONTENT_PAUSE_REQUESTED) {
    return;
  }
  if (loadTimeout) {
    clearTimeout(loadTimeout);
  }

  if (!prevPreload) {
    prevPreload = await this.player_.unloadAndSavePreload(true, true);
    this.player_.detach(true);
  }
});
this.eventManager_.listen(adManager, shaka.ads.AdManager.AD_STOPPED, (e) => {
  if (e?.originalEvent?.type !== google.ima.AdEvent.Type.CONTENT_RESUME_REQUESTED) {
    return;
  }
  if (loadTimeout) {
    clearTimeout(loadTimeout);
  }
  loadTimeout = setTimeout(async () => {
    await this.player_.attach(this.video_, true);
    this.player_.load(prevPreload)
    prevPreload = undefined;
  }, 100);
});
```
