### ISSUE TITLE
Use MediaSession action handler in the demo

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#2812]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

The demo uses the MediaSession Metadata API to show information about the media that is playing.  But we are not yet demonstrating the proper use of the action handler part of the MediaSession API.

**Describe the solution you'd like**

Use setActionHandler to listen for play/pause/stop/seek/skipad events.  Without this, all we get for free is play/pause and a non-seekable timeline.

**Describe alternatives you've considered**

None come to mind, other than the status quo.

**Additional context**

https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/setActionHandler

**Comment by CodeDotJS** [comment]
I'm working on it @joeyparrish
