### ISSUE TITLE
Use shaka.text.Cue everywhere instead of shaka.extern.Cue

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#2818]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

shaka.text.Cue is a concrete implementation of the shaka.extern.Cue interface.  This implies flexibility in the types returned by plugins, but the reality is that we have mixed these types in several places already and made assumptions that we will always get shaka.text.Cue.

Also, we need consistency when fields are added, and increasingly we need to add useful methods to shaka.text.Cue that we could not expect to exist elsewhere (`clone()`, for example).

**Describe the solution you'd like**

I'd like to standardize on using the exported shaka.text.Cue type as the output of text parsers instead of shaka.extern.Cue.  We already use shaka.text.Cue as the input of the TextDisplayer interface.

There is a small risk to any applications with custom text parser plugins, but that seems unlikely in practice.  Custom TextDisplayer plugins should be unaffected.

**Describe alternatives you've considered**

We could make all new methods on shaka.text.Cue into static methods that take shaka.extern.Cue as arguments, we could refer to shaka.extern.Cue in all input params, and we could check for the existence of all fields that were added in the past.  But that sounds more difficult to keep up with.

**Comment by joeyparrish** [comment]
I should also add that I don't believe we can remove shaka.extern.Cue completely.  As an extern, it still serves the purpose of keeping the fields from being renamed by the compiler.  This is important for both custom TextParser plugins and custom TextDisplayer plugins.

**Comment by TheModMaker** [comment]
I do remember problems with internal tools about having the externs refer to library types.  So having the externs use `shaka.extern.Cue` allows us to have the externs only refer to other extern types and not to library types.  I think we are seeing a bunch of warnings from the internal compiler about our use of `shaka.media.PresentationTimeline` and other library types.

**Comment by joeyparrish** [comment]
We already have references to shaka.text.Cue in the externs, even in shaka.extern.Cue.  It's a little crazy.
