### ISSUE TITLE
Improve support for Japanese subtitles

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#2853]
Is it possible to add the following in TTML and WebVTT?
- Vertical text with tate-chū-yoko
- Rubies

WebVTT uses the vertical cue setting and HTML-style `<ruby>` & `<rt>` tags. The ruby position can be controlled using the ruby-position CSS property and tate-chū-yoko is enabled with the `text-combine-upright` CSS property.

```
WEBVTT

STYLE
::cue(.combine) { text-combine-upright: all; }

00:00:01.000 → 00:00:04.000 vertical:rl line:5%
グーグルは<c.combine>1998</c>年に<ruby>創業<rt>そうぎょう</rt></ruby>しました

00:00:05.000 → 00:00:08.000 line:90%,end
グーグルは1998年に<ruby>創業<rt>そうぎょう</rt></ruby>しました
```

TTML uses the `tts:writingMode` region attribute to control vertical text, and `tts:ruby` and `tts:rubyPosition` span attributes. Tate-chū-yoko is enabled with the `tts:textCombine` span attribute.

```
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
    xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
    xmlns:xml="http://www.w3.org/XML/1998/namespace">
<head>
  <layout>
    <region
      xml:id="vert_right" 
      tts:extent="100% 100%" tts:origin="2% 5%"
      tts:writingMode="tbrl"/>
    <region 
      xml:id="bottom"
      tts:extent="100% 100%" tts:origin="0% 40%"
      tts:displayAlign="center"/>
  </layout>
</head>
<body>
  <div>
    <p begin="00:00:01.000" end="00:00:04.000" region="vert_right">グーグルは<span tts:textCombine="all">1998</span>年に<span tts:ruby="container"><span tts:ruby="base">創業</span><span tts:ruby="text">そうぎょう</span></span>しました</p>
    <p begin="00:00:05.000" end="00:00:09.000" region="bottom">グーグルは1998年に<span tts:ruby="container"><span tts:ruby="base">創業</span><span tts:ruby="text">そうぎょう</span></span>しました</p>
  </div>
</body>
</tt>
```

Source and more examples:
- https://netflixtechblog.com/implementing-japanese-subtitles-on-netflix-c165fbe61989
- https://medium.com/google-exoplayer/improved-japanese-subtitle-support-7598fee12cf4

**Comment by avelad** [comment]
TTML example: https://github.com/google/ExoPlayer/pull/8677/files

**Comment by ismena** [comment]
Damn, Asian languages are cool!

This isn't a priority for the team at the moment, but we'd gladly accept a PR.

**Comment by avelad** [comment]
All functionality has been merged in following PRs:
https://github.com/shaka-project/shaka-player/pull/5633
https://github.com/shaka-project/shaka-player/pull/5642
https://github.com/shaka-project/shaka-player/pull/5644
https://github.com/shaka-project/shaka-player/pull/5645
