### ISSUE TITLE
Over-zealous error log on IPR with expiring segments

### ISSUE THREAD

**Issue by colde** [shaka-project/shaka-player#2854]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.1

**Please ask your question**
It seems lib/media/presentation_timeline.js contains logic to check that this.segmentAvailabilityDuration_ == Infinity
If that fails it logs: 'Detected as IPR stream, but does not match our model of IPR!' as an error.

However, in our case we use live stream buffers as a temporary measure, while we are creating actual VOD streams in the background. Therefore, the segments do actually expire, as they move out of the buffer window. Is there anything problematic with the playback of that? 

Our MPD header looks like:
`<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:ns1="http://www.w3.org/2001/XMLSchema-instance" ns1:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:dvb:dash:profile:dvb-dash:2014,urn:dvb:dash:profile:dvb-dash:isoff-ext-live:2014,http://dashif.org/guidelines/dash-if-simple" xmlns:cenc="urn:mpeg:cenc:2013" availabilityStartTime="2020-09-17T12:54:02Z" publishTime="2020-09-17T13:09:24Z" minimumUpdatePeriod="PT5S" timeShiftBufferDepth="PT2H39M49S" mediaPresentationDuration="PT2H39M49S" minBufferTime="PT5S" type="dynamic">`

It seems that the `timeShiftBufferDepth` is what causes the logging.

Should we just ignore this error, or is there logic that will cause problems?

**Comment by joeyparrish** [comment]
If you want segments to expire, then that doesn't match our understanding of IPR.  That is what we would call live.  If you remove mediaPresentationDuration, it will be seen as live.

Alternately, we could tweak the definition of IPR to allow for expiration of content.  Does your content play correctly if you ignore the error log?

**Comment by colde** [comment]
Yeah, it's not so much IPR, as it is essentially timeshifted live, but with start and end time (which might be in the future). Not sure if that is conceptually closer to IPR or Live, in my mind IPR is closer (as i don't really know of many commercial implementations og origins where the segments from a live stream hang around for ever). But it was mainly to check we weren't setting us self up for a problem later.

It looks like everything is working fine, at least, we haven't seen any problems in the test.

**Comment by joeyparrish** [comment]
Then I think you could just tweak the conditions for the log to silence it.  Would you like to send a PR?

**Comment by colde** [comment]
Yeah, I'm happy to give it a try at least.

**Comment by avelad** [comment]
Can you check if the error still occurs in the main branch? Thank you!
