### ISSUE TITLE
Tizen 5.5: starting live DASH takes too long

### ISSUE THREAD

**Issue by JakubRimal** [shaka-project/shaka-player#2862]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.4

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
yes but it's not accurate to measure the starting time as it loads the whole page again

**What browser and OS are you using?**
Tizen 5.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Full Model: UE32T5372AUXXH
Firmware: T-KTS2DEUC-1302.5

but it happens e.g. with premium QTQ7X as well – the important thing is that it has Tizen 5.5 (does not happen with Tizen 5 and older)

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-live-assets/player-source.mpd

**What did you do?**
Play live DASH

**What did you expect to happen?**
It should start to play reasonably fast.

**What actually happened?**
It takes around 5s before it starts to play. From the log I'm not able to say what actually takes so long – it looks "normal" but there are bigger gaps between starting phases than usually.

Another thing is that it freezes/buffers every few minutes (as you can see e. g. at 13:54:49.744 in the log).

Internet connection doesn't have an impact on this problem (happens even with very good cable connection).

**Our configuration for Shaka player instance:**
```
{
    streaming: {
        stallEnabled: false,
        bufferingGoal: 5,
        rebufferingGoal: 3,
        bufferBehind: 5,
    },
    abr: {
        switchInterval: 4, // segment length
        defaultBandwidthEstimate: 1500000,
        bandwidthDowngradeTarget: 0.90,
        bandwidthUpgradeTarget: 0.80,
        enabled: true,
    },
}
```

**Debug log of Shaka player:**
[shaka-starting-live-dash.log](https://github.com/google/shaka-player/files/5255459/shaka-starting-live-dash.log)

**Comment by TheModMaker** [comment]
Setting an small `bufferingGoal` like that will mean we only have one segment buffered at a time.  So even with a very fast internet connection, we'll need to download the file quickly as we near the end of the buffer.  I would suggest at least 20 seconds to buffer.

Secondly, IIRC, some smart TVs have very slow decoders and can't seek within a file.  Meaning if we ask to play at 3 seconds into a segment, it will take 3 seconds to decode up to that point.  You should try setting `streaming.startAtSegmentBoundary` to `true` and see if that helps.

**Comment by joeyparrish** [comment]
@JakubRimal, do the suggestions made by @TheModMaker help?  In particular, slow startup can be caused by mid-segment seek points on smart TVs, so I would strongly suggest trying `streaming.startAtSegmentBoundary` set to `true`.  But his other points about a small `bufferingGoal` also apply.

**Comment by JakubRimal** [comment]
No, I have tried the configuration recommended by @TheModMaker and the result is the same. I would say that the main point here is that it happens **only** with Tizen 5.5 – when I run completely the same application on Tizen 5 it starts to play as expected, so it looks like the issue is connected with the new Tizen 5.5 (Tizen versions table: https://developer.samsung.com/smarttv/develop/specifications/tv-model-groups.html).

**Comment by joeyparrish** [comment]
Usually, we can count on things to get somewhat better with newer firmware releases.  😢 

We don't have Tizen 5.5, so we can't test this ourselves.  We will try to come up with some other suggestions for you to try.

- Does this problem occur with this live stream with a default Shaka Player configuration?
- Does this problem occur with other live streams?
- Does this problem occur with VOD content?

**Comment by JakubRimal** [comment]
> * Does this problem occur with this live stream with a default Shaka Player configuration?

Yes, it is even reproducible wit Shaka Player Demo (https://shaka-player-demo.appspot.com/demo/) in the default web browser which is in TV.

> * Does this problem occur with other live streams?

Yes.

> * Does this problem occur with VOD content?

No.

**Comment by joeyparrish** [comment]
Thanks for the feedback.  The major difference between live and VOD is that live doesn't generally start at 0.  If it's the initial seek in a live stream which is taking too long, that time is not something that is in our direct control.  And we don't have Tizen 5.5 to debug with.

I note that you also mention that it freezes and buffers a lot.  If you configure it to force the use of the lowest resolution before you call load(), how does this impact the startup time and buffering?

```js
player.configure('abr.restrictions.maxHeight', 1);
player.load(...)
```

What is the lowest resolution/bitrate in your live streams?

What codecs are you using for audio & video in these live streams?

**Comment by JakubRimal** [comment]
I'm sorry but it requires some additional tests on the real device which is quite hard in these covid times... We'll come back when it will be possible.

**Comment by joeyparrish** [comment]
We understand that completely.  We have the same problem.  Take your time!

**Comment by cidevant** [comment]
Hi, I am colleague of @JakubRimal 

> If you configure it to force the use of the lowest resolution before you call load(), how does this impact the startup time and buffering?

Yes, it improved startup a lot, nearly instant play, no freezes. But abr is not working now, it plays in lowest resolution.

> What is the lowest resolution/bitrate in your live streams?
> What codecs are you using for audio & video in these live streams?

```
<Period start="PT0S" id="1">
    <AdaptationSet startWithSAP="1" segmentAlignment="true" id="101" mimeType="video/mp4" >
        <SegmentTemplate timescale="90000" duration="360000" media="$RepresentationID$/$Number%06d$.m4s" initialization="$RepresentationID$/IS.mp4" startNumber="49420800"/>
        <Representation id="101-365" codecs="avc1.640029" width="960" height="540" sar="1:1" bandwidth="2322000"/>
        <Representation id="101-366" codecs="avc1.4d4029" width="640" height="360" sar="1:1" bandwidth="1272000"/>
        <Representation id="101-367" codecs="avc1.640029" width="1280" height="720" sar="1:1" bandwidth="3972000"/>
        <Representation id="101-368" codecs="avc1.64002a" width="1920" height="1080" sar="1:1" bandwidth="5872000"/>
        <Representation id="101-360" codecs="avc1.4d4029" width="320" height="180" sar="1:1" bandwidth="672000"/>
    </AdaptationSet>
    <AdaptationSet startWithSAP="1" segmentAlignment="true" id="105" mimeType="audio/mp4" lang="cze" >
        <SegmentTemplate timescale="90000" duration="360000" media="$RepresentationID$/$Number%06d$.m4s" initialization="$RepresentationID$/IS.mp4" startNumber="49420800"/>
        <Representation id="105-365" codecs="mp4a.40.5" audioSamplingRate="24000" bandwidth="128000"/>
    </AdaptationSet>
</Period>
```

**Comment by joeyparrish** [comment]
Forcing the lowest res wasn't proposed as a solution, but just as a debugging step, to help us understand the device's behavior.

If forcing the player to use a lower resolution eliminates the freezing behavior, then it could be that the bitrate or resolution can't be handled by the device.  It could also be that some difference in the encoding profile in the higher resolutions can't be handled by the device (b-frames, etc.).  If the network connection can definitely handle the bandwidth requirements of the higher resolutions, then we can only blame the decoder.

Can you confirm the available bandwidth with a speed test from the device?

Can you also check what the player believes the bandwidth is during or after playback?  `player.getStats().estimatedBandwidth`

As for codecs, here's what I see in the representations:

| Height | Bitrate | Codec Params |
| --- | --- | --- |
| 180 | 672k | main profile, level 4.1 |
| 360 | 1.2M | main profile, level 4.1 |
| 540 | 2.3M | high profile, level 4.1 |
| 720 | 3.9M | high profile, level 4.1 |
| 1080 | 5.8M | high profile, level 4.2 |

Can you please check that the device's decoder is documented to be able to handle those bitrates and profiles?
