### ISSUE TITLE
Stall detector cause the error "The play() request was interrupted by a call to pause()" on SmartTV

### ISSUE THREAD

**Issue by Yuvalke** [shaka-project/shaka-player#2920]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
yes.

**Can you reproduce the issue with the latest code from `master`?**
yes.

**Are you using the demo app or your own custom app?**
custom app.

**If custom app, can you reproduce the issue using our demo app?**
Didn't try the demo app on the TV.

**What browser and OS are you using?**
SmartTV - LG and Samsung.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen 4.

**What are the manifest and license server URIs?**

**What did you do?**
call play() and before play promise resolved stall detector request for pause and cause the DOM exception. 

**What did you expect to happen?**
play promise will resolve.

**What actually happened?**
Getting error from play promise.

**Comment by OrenMe** [comment]
Hi, any update on this issue - this is causing streams to halt on start and require user to press play again.

**Comment by TheModMaker** [comment]
Is this an actual exception?  The log "a call to play was interrupted by a call to pause" isn't an error, it is just a rejected Promise from the `play` call.  We don't actually use the Promise, so it shouldn't cause any problems for us.  If you're app is seeing this error from your calls to `play`, then you can just catch and ignore it.  Waiting for the Promise from `play()` isn't really needed and you could use the `play` event instead.

**Comment by joeyparrish** [comment]
We also have a polyfill to silence these noisy, useless logs already: https://github.com/google/shaka-player/blob/e3c01d827b83567b35de808803251b90ae7dd1f4/lib/polyfill/video_play_promise.js#L27-L44

**Comment by OrenMe** [comment]
What seems to happen is that the pause command happens and then the play doesn't actually do anything.
Might be some timing issue with the underlying video implementation on TV.
The pause and then play are called one after the other in the stall detector.

**Comment by Yuvalke** [comment]
Hi, @joeyparrish and @TheModMaker thanks for your response.
The play promise has valuable info, we get info when the media couldn't play for example "user gesture" for autoplay on
few devices, in this case, the video tag paused property set to false but the media couldn't play so pause request is needed after that error to correlate the state.
The play promise AFAIK relevant for first play request and the specific scenario happens on smartTV and cast only on a stall detector.
I suggested checking if we're in a playing state or not before we're making the pause request, another possible solution could be listening to the `playing` event, only after that start the stall detector process for smartTV and cast, what do you think?

**Comment by TheModMaker** [comment]
The problem with waiting is we've seen stalls happen at the start before.  Sometimes the media pipeline gets stuck at the start.  There are a few configuration params you could change to make this better:

- `streaming.stallEnabled`: If set to `false`, never trigger the stall detector.
- `streaming.stallThreshold`: The amount of time to wait before detecting a stall.  Setting this to a larger value will cause us to wait longer and not trigger early at the start.
- `streaming.stallSkip`: Defines the amount of time to skip forward.  If 0, we'll play/pause, otherwise we'll skip this amount forward.  You could set this to 0.1 to cause a seek instead.

**Comment by Yuvalke** [comment]
@TheModMaker It gets stuck before `playing` event?
stall detector fixes some issues on smartTV with `pause` `play`, I don't want to miss this fix.

**Comment by Yuvalke** [comment]
@TheModMaker what do you think about the fix I suggested?

**Comment by joeyparrish** [comment]
@Yuvalke, I apologize for leaving this issue for so long without updates.  Is this still an issue for you?  Did you try your suggestions above with `stallSkip`?

**Comment by Yuvalke** [comment]
@joeyparrish  Actually, I implemented it on my side for a quick fix(stall skip default value is hardcoded) - I wonder if you can export your default config before Environment changes taking into account so I'll be able to apply your default config(to prevent issues when default value will change) before `playing` as I mentioned in my suggestion.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
