### ISSUE TITLE
Support alignment in CEA-608

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#2940]
According to https://github.com/google/shaka-player/pull/2731, positioning and alignment not supported.

This issue is to track additional support for this functionality.

Note: DASH-IF seems to have support for this functionality.

**Comment by TheModMaker** [comment]
Do you have any sample content that uses positioning?

**Comment by avelad** [comment]
@TheModMaker the streams of https://github.com/google/shaka-player/pull/2939 have positioning

**Comment by caridley** [comment]
We need this as well, to prevent captions from covering important content like scores in sports programming.

**Comment by caridley** [comment]
This is a high priority for us, and we can help with implementation. We can provide access to streams for development purposes, but won't be able to provide long term access to those streams for use in regression testing or demo content.

It would be much appreciated if a Shaka developer with some expertise in the Shaka caption code could sketch out how this might be done in a way that is consistent with the existing architecture.  Is this issue the appropriate place for that discussion?

**Comment by iskewedI** [comment]
Hi @avelad could you give me the status for this issue? I was about to open a new issue regarding CEA-608 captions that aren't being positioned correctly in the screen for TizenTV, and just found this. For the client the CC alignment is really important, so we need to confirm if you are going to support it. 
Thank you!

**Comment by avelad** [comment]
The issue is still open, so we haven't worked on it yet. If you are interested in doing a PR for it, let us know. Thank you!

**Comment by avelad** [comment]
I added support to vertical position in https://github.com/shaka-project/shaka-player/issues/2940
