### ISSUE TITLE
Play range end is expanded to segment boundary

### ISSUE THREAD

**Issue by interlark** [shaka-project/shaka-player#2955]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** v3.0.5

I wanna load HLS stream, for example: 10 seconds, 5 segments, 2 seconds each. And make available to user only a particular period of time, says, from 1.12 seconds till 9.2 seconds. Anything before 1.12 and past 9.2 are not welcome, so it would be sort of highlighted event from a stream. Is it doable in shaka-player?
Segments are aligned by 2 seconds, so I can not request already perfect cut [1.12, 9.2], only [0, 10], but I think I can do some little adjustments (start\end trimming) on the client side.

**Comment by TheModMaker** [comment]
You can use `playRangeStart` and `playRangeEnd` configuration parameters.

```js
player.configure('playRangeStart', 1.12);
player.configure('playRangeEnd', 9.2);
```

**Comment by interlark** [comment]
I've read about it, but it doesn't work. You still can play from the 0:00, and more else 'playRangeEnd' isn't worked properly: 9.2 turns into 11.59.
Demo: https://codepen.io/interlark/pen/pogrXjx
![image](https://user-images.githubusercontent.com/20641837/97930639-a9b90000-1d8d-11eb-9e29-ea0410e9b516.png)
![image](https://user-images.githubusercontent.com/20641837/97930678-c0f7ed80-1d8d-11eb-9541-651ddeac95f4.png)

**Comment by joeyparrish** [comment]
In that codepen, I initially see a 9-second range, then it jumps to 12 for some reason

**Comment by joeyparrish** [comment]
With this DASH content, it works correctly: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
With that content, I set the time range to something that made it more obvious that it was working:

```js
  player.configure('playRangeStart', 10);
  player.configure('playRangeEnd', 20);
```

**Comment by joeyparrish** [comment]
It's also working correctly with this MP4-based HLS content: https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8

But with this TS-based HLS content, it is only nearly correct: https://cf-sf-video.wmspanel.com/local/raw/BigBuckBunny_320x180.mp4/playlist.m3u8

On that, it extends the end of the range to 23 when I ask for 20.

**Comment by joeyparrish** [comment]
Ah, there's some segment-sized rounding going on.  If you ask for Angel One clipped to time 20, you get 20.  If you ask for 21, you get 24.  That clip uses 4-second segments.  This effect can be seen across DASH & HLS, MP4 & TS, and on both v2.5.17 and v3.0.5 of Shaka Player.

**Comment by joeyparrish** [comment]
This only seems to affect the end of the seek range, not the start.

**Comment by gldraphael** [comment]
I'd like to attempt working on this on Monday... which files would be a good place to start?

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!

**Comment by halws** [comment]
Hi, it seems not to be working with raw mp4 https://codepen.io/Halws/pen/oNPxJjN

@shaka-bot reopen
