### ISSUE TITLE
Exceptions should return the real/final URI 

### ISSUE THREAD

**Issue by mihaiav** [shaka-project/shaka-player#2969]
If a resource loaded (e.g example.com) redirects using http 302 status code to a different resource(example-two.com) that fails to load (i.e. returns http 401 status) the exception provides only the original URI (example.com).

This is problematic if the client manages multiple users (i.e. credential sets) based on the domain of the resource (i.e. example.com) because it doesn't know the domain name of the resource that fails. It sees only the original/initial URI. 

**Describe the solution you'd like**

The exceptions should provide an additional field with the real/actual URI that fails
For example shaka error 1001 provides 5 fields. The first one is the original URI that shaka tries to load.
In addition to these field we need one more:
```

An HTTP network request returned an HTTP status that indicated a failure.
error.data[0] is the URI.
error.data[1] is the status code.
error.data[2] is the response text, or null if the response could not be interpretted as text.
error.data[3] is the map of response headers.
error.data[4] is the NetworkingEngine.RequestType of the request, if one was provided.
```
 +

```
error.data[5] is the final URI. This may be different if the initial URI (error.data[0]) issued a redirect.
```

This is related to https://github.com/google/shaka-player/issues/2965

**Comment by zordrakk** [comment]
> 

Can I take up this issue?
