### ISSUE TITLE
Configurable stall detector

### ISSUE THREAD

**Issue by bcupac** [shaka-project/shaka-player#3008]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Own app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
WebOS4 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
WebOS4 05.20.15 75UK6500PLA WebOS4.2.0-8404

**What are the manifest and license server URIs?**

sent to email

**What did you do?**

played the dash stream

**What did you expect to happen?**
smooth playback

**What actually happened?**

We serve Server Side Ad Injection(SSAI) dash manifests that consist of many periods. Some periods are encrypted and contain actual content, other ones are Ads and they are unencrypted.
The problem that We encountered on many LG WebOS TVs is that, when playback switches from the first Ad to the second Ad (from one period to the other period) the video stalls and does not recover.
When testing in the browser, video plays smoothly.

Chrome:
In chrome it will detect a gap and skip it, or a stall and unstall it:

<img width="371" alt="chrome 2" src="https://user-images.githubusercontent.com/7647317/100286565-4e84c280-2f73-11eb-84f5-023c7ad8e6d3.png">
WebOS:

It will detect the stall, try to play/pause but video will remain stalled.

<img width="1216" alt="webos" src="https://user-images.githubusercontent.com/7647317/100286577-52b0e000-2f73-11eb-9247-52bf62feb6d7.png">

**Comment by bcupac** [comment]
Changing the threshold in time_ranges_utils.js  getGapIndex function, to something like 0.8s, and
lowering the timer in gap_jumping_controller.js to 0.125s

```
 this.gapJumpTimer_ = new shaka.util.Timer(() => {
      this.onPollGapJump_();
    }).tickEvery(/* seconds= */ 0.125);
```

will prevent LG tvs from stalling and they will jump gaps now by seeking through them.

**Comment by MilosRasic** [comment]
Can we extract these two values into config and keep the current hardcoded values as defaults?

**Comment by joeyparrish** [comment]
Renamed this and converted into an enhancement request for a configurable stall detector

**Comment by avelad** [comment]
> Changing the threshold in time_ranges_utils.js getGapIndex function, to something like 0.8s, and lowering the timer in gap_jumping_controller.js to 0.125s
> 
> ```
>  this.gapJumpTimer_ = new shaka.util.Timer(() => {
>       this.onPollGapJump_();
>     }).tickEvery(/* seconds= */ 0.125);
> ```
> 
> will prevent LG tvs from stalling and they will jump gaps now by seeking through them.

About the threshold is already configurable with `streaming.gapDetectionThreshold`. And  I created https://github.com/shaka-project/shaka-player/pull/5525
