### ISSUE TITLE
iOS 14 + iPhone 7/8 fullscreen video incorrectly positioned after playing IMA3 ads.

### ISSUE THREAD

**Issue by albinjohnson** [shaka-project/shaka-player#3090]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
In demo app we are not able to play the content on fullscreen

**What browser and OS are you using?**
Safari and iOS 14.2

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

```js
const manifestUri = 'https://storage.googleapis.com/gvabox/media/samples/stock.mp4';
const adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
```

**What did you do?**

Just click the play button and click on screen to enter full screen

**What did you expect to happen?**
 The main video and  ad to be correctly positioned on fullscreen

[Demo.zip](https://github.com/google/shaka-player/files/5800961/Demo.zip)

**What actually happened?**

We've found that on iPhone 7/8 and all versions of iOS 14, after playing HTML5 ads, the main content video is pushed to the top of the video window rather than centred. The ad itself is correctly positioned, as is the content when there's no ads (i.e. the IMA SDK isn't involved) or any other combination other  iPhone 7/8 and all versions of iOS 14.

demo video attached showing the issue on iPhone 8 and iPhone 11 with working  as expected. — it's consistently reproducible on both real 7/8 devices and the simulator.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
