### ISSUE TITLE
Wrong resolution labels - cropping black bars results in label suggesting that quality has dropped

### ISSUE THREAD

**Issue by ScripterYoda** [shaka-project/shaka-player#3141]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
N/A

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**
Used manifest with film in resolution 1920x800.

**What did you expect to happen?**
That the resolution label will read 1080p

**What actually happened?**
The resolution label read 800p.

As inspected in code, resolution label is based only on the height of video, but I think it depends also on the width.
After all, the business use is to change quality and eg. cropping black bars from video does not change its quality and should not change its label.

For me, quality stated as 'x p' assumes aspect ratio of 16:9 and if a video has different aspect ratio than it means:
if we put this video in the smallest possible frame 16:9 than that frame (not video!) will have height of x pixels.

Youtube labels their videos according to that logic - eg. https://www.youtube.com/watch?v=1VIZ89FEjYI.
Wikipedia states that 1080p means explicitly 1920x1080 and "term usually assumes a widescreen aspect ratio of 16:9" - https://en.wikipedia.org/wiki/1080p.

I think that label should always state the height of 16:9 frame - maybe it should be a configurable behaviour?

Video 1920x1080 -> label '1080p'
Video 1920x800 -> label '1080p', now is '800p'
Video 2160x1080 -> label '1215p' now is '1080p'

**Comment by TheModMaker** [comment]
I agree this should be configurable.  1080p comes from broadcast TV/Movies where it was always 1920x1080.  So how to handle non-16:9 content is a matter of preference (hence the configuration).  What may be better to to fix 1080p,720p,etc and pick the one that is closest instead of arbitrary values like 800p.
