### ISSUE TITLE
Make UI ad elements conditional on the presence of ad logic in the build

### ISSUE THREAD

**Issue by TheModMaker** [shaka-project/shaka-player#3179]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest `master`.

**Can you reproduce the issue with our latest release version?**
N/A

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
N/A

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
N/A

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What did you do?**
```sh
./build/build.py +@complete -@ads
```

**What did you expect to happen?**
To build successfully.

**What actually happened?**
A number of build errors.

We should either allow removing ads or move the files into `core`.

**Comment by joeyparrish** [comment]
The UI depends on ads, I'm pretty sure.  If you use `+@complete -@ui -@ads`, it should work, I think.  If not, then it's definitely a bug.

**Comment by TheModMaker** [comment]
Yes that does work.  Maybe we should move the ads files into the ui?  Do the ads files do anything without the UI?

**Comment by joeyparrish** [comment]
You can use ads APIs without the UI, yes.  We could make the UI function without them, though, by making the UI ads features conditional on the core library ads APIs being present in the build.  It would be similar, I think, to how we did this for the newer text format parsers referenced by Player.

**Comment by ismena** [comment]
*glaring* Excluding both UI and Ads, what's wrong with you, people!

Let me schedule this as in enhancement :/

**Comment by avelad** [comment]
Is anyone interested on it? If no response, in 7 days the issue will be closed automatically
