### ISSUE TITLE
Issues using WV key rotation on Tizen and WebOS

### ISSUE THREAD

**Issue by nextsux** [shaka-project/shaka-player#3193]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.5 (with 3.0.8 we have other problems like streams not playing at all - not part of this issue)

**Can you reproduce the issue with our latest release version?**
no, it has other problems

**Can you reproduce the issue with the latest code from `master`?**
no, it has other problems

**Are you using the demo app or your own custom app?**
own

**If custom app, can you reproduce the issue using our demo app?**
not available for WebOS/TIZEN

**What browser and OS are you using?**
AFAIK WebOS/TIZEN are webkit based

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
WebOS 4.x
Tizen 2/2016 3/2017

**What are the manifest and license server URIs?**
https://smoula.net/data/wv-enc-test/llama-clear.mpd
https://smoula.net/data/wv-enc-test/llama-wv-no-rotation.mpd https://cwip-shaka-proxy.appspot.com/no_auth
https://smoula.net/data/wv-enc-test/llama-wv-rotation.mpd https://cwip-shaka-proxy.appspot.com/no_auth

**What did you do?**
I've created DASH video without encryption, with encryption and with encryption + rotate keys every 5 secs using this:

```bash
$ ffmpeg -i llama_3_original.mp4 -c:a copy \
  -vf "scale=-2:480" \
  -c:v libx264 -profile:v main -level:v 3.1 \
  -x264-params scenecut=0:open_gop=0:min-keyint=120:keyint=120 \
  -minrate 1000k -maxrate 1000k -bufsize 1000k -b:v 1000k \
  -output_ts_offset 1s \
  -y llama_480p.mp4

$ packager \
  in='llama_480p.mp4,stream=audio,output=audio.mp4,init_segment=audio-wv-rotation/init.mp4,segment_template=audio-wv-rotation/$Number$.m4s' \
  in='llama_480p.mp4,stream=video,output=video.mp4,init_segment=video-wv-rotation/init.mp4,segment_template=video-wv-rotation/$Number$.m4s' \
  --generate_static_live_mpd \
  --enable_widevine_encryption \
  --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test \
  --content_id 6c6c616d615f6e657875735f32303231 \
  --signer widevine_test \
  --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9 \
  --aes_signing_iv d58ce954203b7c9a9a9d467f59839249 \
  --clear_lead 0 \
  --crypto_period_duration 5 \
  --protection_systems widevine \
  --generate_dash_if_iop_compliant_mpd \
  --mpd_output llama-wv-rotation.mpd

$ packager \
  in='llama_480p.mp4,stream=audio,output=audio.mp4,init_segment=audio-wv-no-rotation/init.mp4,segment_template=audio-wv-no-rotation/$Number$.m4s' \
  in='llama_480p.mp4,stream=video,output=video.mp4,init_segment=video-wv-no-rotation/init.mp4,segment_template=video-wv-no-rotation/$Number$.m4s' \
  --generate_static_live_mpd \
  --enable_widevine_encryption \
  --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test \
  --content_id 6c6c616d615f6e657875735f32303232 \
  --signer widevine_test \
  --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9 \
  --aes_signing_iv d58ce954203b7c9a9a9d467f59839249 \
  --clear_lead 0 \
  --crypto_period_duration 0 \
  --protection_systems widevine \
  --generate_dash_if_iop_compliant_mpd \
  --mpd_output llama-wv-no-rotation.mpd

$ packager \
  --generate_static_live_mpd \
  in='llama_480p.mp4,stream=audio,output=audio.mp4,init_segment=audio-clear/init.mp4,segment_template=audio-clear/$Number$.m4s' \
  in='llama_480p.mp4,stream=video,output=video.mp4,init_segment=video-clear/init.mp4,segment_template=video-clear/$Number$.m4s' \
  --generate_dash_if_iop_compliant_mpd \
  --mpd_output llama-clear.mpd
```

**What did you expect to happen?**
That all supplied video streams are going to work and play

**What actually happened?**
Using web player (Chrome/Firefox) all works.
Video without encryption works.
Video with static encryption key works on LG and on Tizen it crashes whole app.
Video with key rotation does not work at all.

According to "Tizen 2017 model is actively tested and supported by the Shaka Player team. Tizen 2016 model is community-supported and untested by us." I and "DRM support matrix" I would expect it to work at least on Tizen 2017. I found nothing about support of key rotation in Shaka on those platforms.

Am I doing something wrong in MPDs? Is it a Shaka's issue or key rotation is not supported at all on Tizen/LG?

**Comment by michellezhuogg** [comment]
Tested on Tizen with the manifests and got the same log:

INFO LOG: 'Starting attach...'
INFO LOG: 'Starting load of https://smoula.net/data/wv-enc-test/llama-clear.mpd...'
WARN LOG: 'No variants met the ABR restrictions. Choosing a variant by lowest bandwidth.'
WARN LOG: 'No preferred audio language set.  We have chosen an arbitrary language initially'
WARN LOG: 'No variants met the ABR restrictions. Choosing a variant by lowest bandwidth.'
INFO LOG: 'Jumping forward', 0.001, 'seconds because of gap before start time of', 0.001
WARN LOG: 'No variants met the ABR restrictions. Choosing a variant by lowest bandwidth.'
WARN LOG: 'No variants met the ABR restrictions. Choosing a variant by lowest bandwidth.'
WARN LOG: 'No variants met the ABR restrictions. Choosing a variant by lowest bandwidth.'
ERROR LOG: 'Timeout waiting for event ended', 'current time', 31.242, 'duration', 150.041, 'ready state', 4, 'playback rate', 1, 'paused', false, 'buffered', [Object{start: 0.001, end: 41.006}]
WARN LOG: 'No variants met the ABR restrictions. Choosing a variant by lowest bandwidth.'
INFO LOG: 'Preparing to destroy walker...'

**Comment by nextsux** [comment]
Do you mean you're not playing the clear non encrypted one? I had problems only with encrypted (particularly with key rotations)

**Comment by michellezhuogg** [comment]
Hello @nextsux , we tested with all three manifests with Shaka v3.0.8 on Tizen, and they all played smoothly. Could you please try with v3.0.8 when the other issues get fixed, and let us know if it's still happening? Thank you!

**Comment by nextsux** [comment]
We've finished tests with LG 4.3.0:

https://smoula.net/data/wv-enc-test/llama-clear.mpd - OK
https://smoula.net/data/wv-enc-test/llama-wv-no-rotation.mpd - OK
https://smoula.net/data/wv-enc-test/llama-wv-rotation.mpd - FAIL with specific configuration

When we set BUFFERING_GOAL to 40, player FAILs with Shaka Error 3016
When we set BUFFERING_GOAL to value from interval 10-14, playback is OK

our used config:
```
 const BUFFERING_GOAL = 40; // default 10
 player.configure({
        streaming: {
            bufferingGoal: BUFFERING_GOAL
        },
        drm: {
            servers: {
                'com.widevine.alpha': 'https://cwip-shaka-proxy.appspot.com/no_auth'
            },
        }
    });
    ```

**Comment by joeyparrish** [comment]
> https://smoula.net/data/wv-enc-test/llama-wv-rotation.mpd - FAIL with specific configuration
> When we set BUFFERING_GOAL to 40, player FAILs with Shaka Error 3016
> When we set BUFFERING_GOAL to value from interval 10-14, playback is OK

If you buffer ahead to a point where we don't have keys yet, what _should_ happen is that the browser should play happily unless the playhead reaches that spot before the keys are available.  If that happens, the browser _should_ stall playback until the keys are available.

What _might_ be happening on these TVs is that if we buffer to a point where we don't have keys yet, the TV tries to decrypt/decode that content anyway and throws a fatal error.  If this is true, this would be non-spec-compliant behavior from the platform.  This would also explain why a lower buffering goal works around it for you.

@nextsux, what is the key rotation interval for this content?  Is the 10-14 second buffering goal within ~2 key intervals?

**Comment by nextsux** [comment]
IIRC I've set key rotation for this demo to 5 seconds so key rollover can
be tested quickly. So yes, this explanation makes sense for me.

Dne pá 14. 5. 2021 20:20 uživatel Joey Parrish ***@***.***>
napsal:

**Comment by joeyparrish** [comment]
Thank you for confirming.  My best advice, then, is to consider your key rotation interval when you choose the buffering goal for these platforms.

If anyone can think of a workaround that we could apply automatically, I would be happy to discuss.  But I have no good ideas right now.

My first thought was to automatically constrain the buffering goal if `Platform.isWebOS()`, etc, based on the key interval.  But it seems like it would cause confusion to ignore and override the app's configuration in certain cases.  Besides this, we have no way to automatically discover the key interval.

**Comment by joeyparrish** [comment]
Nobody has had any ideas for a workaround in a year, so I'm closing this issue now.
