### ISSUE TITLE
Not all playlists start at the same time

### ISSUE THREAD

**Issue by jonasevcik** [shaka-project/shaka-player#3195]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Mac OS 10.15.7, Chrome 88.0.4324.192 (Official Build) (x86_64)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
-

**What are the manifest and license server URIs?**
[manifest](https://shaka.livesporttv.cloud/master.m3u8)

**What did you do?**
Load and play the URL.

**What did you expect to happen?**
It will play back.

**What actually happened?**
The player finishes with: `Ignoring large gap at 0 size 5.990334`. This can be solved by enabling `jumpLargeGaps` flag, but duration of the gap is highly inaccurate.
PTS time of the first audio packet is: 219636.010667
PTS time of the first video packet is: 219636.042422
which is 0.03 s apart, not 5.9. That's in fact duration of the whole audio segment. This is probably related to the fact, that the player assumes that all variants start at the same time. This can be seen in the logs too:
`First segment v-1614966902.mp4 starts at 219636.01066666667`
There's probably some implementation logic I'm missing, but shouldn't be the gap duration equal to 0.03 s?

**Comment by joeyparrish** [comment]
I think I see the issue.  The inaccuracy is not really in gap detection.  The gap really is that large, based on where the segments ended up in the presentation.  This is because we applied the wrong timestamp offset to the segments by assuming that all variants start at the same time.  So the root of the issue is the HLS parser and its assumptions.

I'll update the title and see if there is an easy fix to disable that bad assumption for content like yours.

**Comment by theodab** [comment]
Now that we use sequence mode for HLS, I don't think this is a problem anymore. I just tried it with [our nightly build](https://nightly-dot-shaka-player-demo.appspot.com/), and the content plays just fine.
