### ISSUE TITLE
Add option to ignore EME expiration times

### ISSUE THREAD

**Issue by asgvard** [shaka-project/shaka-player#3205]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.7

**Please ask your question**
Hi! I would like to follow up on the issue about the wrong key expiration times reported by the Tizen 5. This issue was discussed in this ticket (https://github.com/google/shaka-player/issues/2456), which is also referenced in this one (https://github.com/google/shaka-player/issues/2252) and meant to be fixed in this PR (https://github.com/google/shaka-player/pull/2579).
However we are still experiencing the same issue and I am not sure how the option for the custom polling time in that PR is supposed to solve this.
I am opening this as a Question because we are pretty sure it is not the issue with Shaka, but I would like to have a discussion about possible workarounds.

ISSUE:
We have found that the Tizen 5 and Tizen 5.5 EME implementation has a problem where the expiration times for the license keys are reported with ignoring the timezone (GMT +1 for us), and also the "offset" of this wrong expiration time is getting bigger and bigger for each minute when the TV is in the sleep mode. This issue is happening mostly on the Tizen models of 2019 and 2020 years in the Premium bracket.

Example:
We have a testing setup in the Castlabs DRM service (DRMToday), where we have the following configuration for the Customer Rights Token for Widevine:
```
{
     "relativeExpiration": "PT5M",
     "playDuration": 240000
}
```
There is no key rotation, only the expiration time setting affects this.
So the license expiration is 5 minutes, and the maximum play duration is 3 minutes. We can see that as soon as the license is fetched, it is already having the expiration time in the past (-1 hour for the time zone, plus 5 minutes for configured exp time, resulting into it being -55 min in the past). Then if the TV is put in the sleep mode for let's say 30 minutes, next time we try it - the license will have -1 hour, minus another 30 minutes for sleep, plus 5 minutes for the configured exp time.

Here is the cleaned up console log with the verbose logs from shaka:
```
Created MediaKeys object for key system com.widevine.alpha
Creating new temporary session
EME init data: type= cenc data= AAAAZ3Bzc2gAAAAA7e-LqXnWSs6jyCfc1R0h7QAAAEcIARIQ3By8R7uUTe6RX-wK08IxChoIY2FzdGxhYnMiHGV5SmhjM05sZEVsa0lqb2lkbTlrTFRRME5TSjkyB2RlZmF1bHQ4AA==
Sending license request for session ksidC979CA6B of type license-request
EME license request <encrypted body>
EME license response <encrypted body>
Updating session ksidC979CA6B
Key status changed for session ksidC979CA6B
Key status changed for session MediaKeySession {sessionId: "ksidC979CA6B", expiration: 1612757220000, closed: Promise, keyStatuses: MediaKeyStatusMap, onkeystatuseschange: null, …}
active session found {initData: Uint8Array(103), loaded: false, oldExpiration: Infinity, updatePromise: null}
Key statuses map MediaKeyStatusMap {size: 1}
session expiration 1612757220000
ms until session expiration -35029358 // This is already in the past despite being just fetched
Session has expired ksidC979CA6B
Key status changed for session ksidC979CA6B
Key status changed for session MediaKeySession {sessionId: "ksidC979CA6B", expiration: NaN, closed: Promise, keyStatuses: MediaKeyStatusMap, onkeystatuseschange: null, …}
active session found undefined
Key statuses map MediaKeyStatusMap {size: 0}
session expiration NaN
ms until session expiration NaN
Creating new temporary session
----REPEAT over and over----
```

Interesting thing is that after restarting the TV (by holding Power button for few seconds) it resets this "timer" and removes the offset accumulated by the time when the TV was in the sleep mode. For example in the case of the customer project when they had expiration time 24h, it was working fine after the TV restart. Then the problem appeared again when the "sleep time" has reached 23h. (Assuming there was 1 more hour offset for the wrong timezone calculation).

WORKAROUNDS:
The main logic for this is happening here (https://github.com/google/shaka-player/blob/master/lib/media/drm_engine.js#L1469).
The first portion of the condition checks only the expiration time, but ignores the expiration status, while second portion checks for both status and the time:
```
msUntilExpiration < 0 || (hasExpiredKeys && msUntilExpiration < 1000)
```
We have recently tried to just remove the first portion of this condition. It is still experimental as we are not sure what other edge cases it might affect, but so far it seems that for our testing configuration it works fine and the license is properly expired after 3 minutes of watching, or 5 minutes in total. The status changes to "expired" and the player requests the new license.
Another workaround is to simply make the license infinite in the DRM provider config, which also solves the issue and doesn't require changes from our side.

Another workaround we have tried is to add limited license fetching attempts, so if it fetches the license 3 times and in all 3 times it is expired - we are firing an error and showing the popup in the app saying that the user has to restart the TV. But of course this is not the best experience and we are moving away from this solution as it was a temporary one.

FOLLOW UP QUESTIONS:
1) How do you think, what is the main reason of having this condition as it is now? It seems like the first portion only cares about the exp time, while second portion cares for both time and status. Is there any edge case when the expiration status is not updated yet, but the time is already expired? Is it safe to do it like we are trying to do it, by always checking for both expiration status and expiration time? `hasExpiredKeys && msUntilExpiration < 1000`
2) In the PR mentioned above (https://github.com/google/shaka-player/pull/2579), there is a new option to customize the polling time of the expiration time, but I still can't fully understand how this can help with the issue we have, since polling less frequently would not change the result that the time is in the past and calculated in the wrong way. If anyone has an insight about how this option is supposed to help with our issue, please let us know :) Since the initial issue was closed (https://github.com/google/shaka-player/issues/2456) with the potential resolution in that PR.
3) @tvanlaerhoven @el-gringo I hope you don't mind me pinging you here. Could you guys please let us know how did you solve the issue in your case? (https://github.com/google/shaka-player/issues/2456) We would really appreciate any input on this. Were you able to contact Samsung about this?

Would appreciate any input on those questions! Thank you :)

**Comment by TheModMaker** [comment]
It seems like #2579 was created to specifically fix the issue on Xbox, not do what the title says.  I'll rename this issue and tag it an enhancement to actually do what it says in the title.

The `msUntilExpiration < 0` exists to handle platforms that don't set the key status to `expired`.  For example, if they don't support it or if it is set to `internal-error`.  I think this should still exist (when the new flag isn't set) to clean up sessions.  We could change the other part to something like `!hasUsableSession` to remove useless sessions.  So the condition would be something like:

```js
if (!hasUsableSessions || (!this.config_.ignoreExpirationTime && msUntilExpiration < 0)) {
  ...
}
```

@ismena Can we talk to Samsung about the incorrect expiration times?

**Comment by avelad** [comment]
@asgvard I have tested on a Tizen 5.5 (Q60T) and have not reproduced this problem. Could it be that Samsung has updated the firmware and solved this problem? can you try again on your devices?
