### ISSUE TITLE
Highlight current time when hovered on seek bar

### ISSUE THREAD

**Issue by Divyansh-P** [shaka-project/shaka-player#3236]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

No. Just a suggestion.

**Describe the solution you'd like**

![ss](https://user-images.githubusercontent.com/70144022/111318704-4fa93f00-868b-11eb-8896-bdabc388e4f3.jpg)
When we point the cursor on the seek bar, that point should be highlighted and the timestamp of that point should be visible above the seek bar (as shown in the provided image).

**Comment by avelad** [comment]
In recent times, Thumbnails have been added at the player level, but it has not been added to the UI, so it makes sense to address it together with this.

**Comment by nafees87n** [comment]
I want to give it a shot. Can I?

**Comment by michellezhuogg** [comment]
@nafees87n Sounds good! 
Please test with different browsers / screen sizes, and make sure they all work before you send the Pull Request.

**Comment by nafees87n** [comment]
> In recent times, Thumbnails have been added at the player level, but it has not been added to the UI, so it makes sense to address it together with this.

`Thumbnail added at player level but not UI`

 What is meant by this? Can I get some insight on this?

**Comment by avelad** [comment]
Here's what I say: https://github.com/google/shaka-player/pull/3145#issuecomment-788186044

If it won't let you open the drive file, you can use the DASH-IF link, otherwise ask me for permission by drive and I'll give you access.

**Comment by nafees87n** [comment]
I was just tinkering around, trying to understand the workflow. I was trying out some random codes related to tooltips when I added this line in `demo/close_button.js`

`shakaDemo.Tooltips.make(
        this.button_,
        shakaDemo.MessageIds.ALWAYS_STREAM_TEXT_WARNING
    );`

![Screenshot_20210320_014455](https://user-images.githubusercontent.com/56021937/111837452-e7be5700-891d-11eb-964a-8d153b5dc84d.png)

When I add this line in the constructor of `shakaDemo.CloseButton`, I get `Cannot read property 'resolve' of null` error in chrome and `this.localization_ is null` in firefox. I am not able to understand this error.

Attatching some screenshots for reference.
![Screenshot_20210320_014210](https://user-images.githubusercontent.com/56021937/111837261-a4fc7f00-891d-11eb-8520-8bcf056ba9e7.png)
![Screenshot_20210320_014125](https://user-images.githubusercontent.com/56021937/111837268-a7f76f80-891d-11eb-9956-62b209de2261.png)
![Screenshot_20210320_014109](https://user-images.githubusercontent.com/56021937/111837270-a8900600-891d-11eb-9d3a-c038b390dd50.png)

**Comment by theodab** [comment]
@nafees87n
The custom close button is added to the UI inside `shakaDemo.Main.configureUI_`. When you load a tooltip, it attempts to attach the associated localized string, but the localized strings aren't loaded until `shakaDemo.Main.setupLocalization_`, which happens a bit later in the load order.
So if you want that to work, you'll need to re-arrange the order of operations inside `shakaDemo.Main.setupPlayer_` slightly. Which is something we will probably end up having to do eventually anyway, once we get around to adding aria labels to the demo (currently, a low-priority task).

**Comment by nafees87n** [comment]
To calculate the timestamp on tooltip I am using the following formula 
`this.video.duration*(event.offsetX/this.seekbar_.getBoundingClientRect().width)`

Is this the correct way to approach this? The value is not being synced with the time displayed by the `presentation_time.js`

**Comment by joeyparrish** [comment]
It sounds like you want something similar to this: https://github.com/google/shaka-player/blob/0943c80ce8098ad04ae3546454bdb63c1fee560a/ui/range_element.js#L207-L241

You should try to refactor that method and reuse some of those calculations, rather than trying to recreate the formula.

**Comment by nafees87n** [comment]
@joeyparrish 
I used the same thing, but still there's a mismatch between presentation_time and tooltip timestamp.
Can you please help me?
**Attatchments for your reference:**
The `hoverTime_` function is called upon `mousedown` event on `this.bar` and `this.seek_` is the tippyjs instance of `this.bar`
![Screenshot_20210322_192828](https://user-images.githubusercontent.com/56021937/112003458-ef147900-8b46-11eb-8df0-3aae0a8bd890.png)


https://user-images.githubusercontent.com/56021937/112003738-2edb6080-8b47-11eb-9b64-faf7132fa137.mp4

**Comment by michellezhuogg** [comment]
Hello @nafees87n ,
If you're applying for GSoC, please kindly understand that we have limited capacity now and would not be able to provide close guidance until the GSoC officially starts in the summer. 
As a general contributor to Shaka Player, you are welcome to send us a PR once you have a complete, fully-tested, ready-for-review solution. Thank you!

**Comment by nafees87n** [comment]
Yes, I will be applying for GSoC. I took up this issue to understand the codebase and the workflow. I am aware of your limitations, but I reckon you can still tell if my understanding and approach regarding this particular issue are correct.  

The seek bar hover and presentation_time mismatch happens only towards the end of the seek bar, and when I adjust the scale to adjust that towards the end, then the mismatch happens in the initial part of the seek bar. I don't know if the problem can be with the gradient of the seek bar.

**Comment by surajkumar-sk** [comment]
Hello @nafees87n ,
 now that the members won't be guiding you are you still working on this?

**Comment by nafees87n** [comment]
@surajkumar-sk 
As you can see, I have been stuck with a problem that I am trying to solve. If I have a complete, ready to review solution, I'll definitely make the PR.

**Comment by surajkumar-sk** [comment]
@nafees87n will you be adding a thumbnail above the toolpit.

**Comment by nafees87n** [comment]
@surajkumar-sk 
If I have a solution for that then yes otherwise no.

**Comment by surajkumar-sk** [comment]
@nafees87n Can I give it a try or would you like to do this alone.

**Comment by nafees87n** [comment]
@surajkumar-sk 
You can try as well

**Comment by joeyparrish** [comment]
@nafees87n, it sounds like something is off, but I don't know what.

Two pieces of advice:
1. You shouldn't just copy that code.  You should refactor it instead.  Code duplication often leads to long-term problems.  Instead, consider moving the code to a more general utility method that both classes can use.
2. The code you're copying from may not be perfect.  When we use that calculation to seek based on a touch screen event, nobody would notice if it's off by a few pixels, so we probably have a small bug.  When you start using it for tooltips, it becomes obvious that there is something slightly off.

Since we're calculating sizes and positions, it's easy to make mistakes where you exclude a borders, margins, padding, etc, and it's not always clear what is included by the browser method we're using.  I found this on [MDN's article on getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect), which might be useful:

> The width and height properties of the DOMRect object returned by the method include the padding and border-width, not only the content width/height. In the standard box model, this would be equal to the width or height property of the element + padding + border-width. But if box-sizing: border-box is set for the element this would be directly equal to its width or height.

I don't know if that will help, but hopefully this will send you in the right direction.

If you don't use [MDN](https://developer.mozilla.org/) yet, you really should.  It is the only resource I trust for web development. 
 I've even started adding "MDN" to my searches to make sure I get to the right page quickly.

**Comment by ka95708** [comment]
Hello, @nafees87n

I found at middle of seek bar is accurate.
So i guess actual time is like this.

![螢幕擷取畫面 2023-09-14 204629](https://github.com/shaka-project/shaka-player/assets/12542531/c00db34e-e593-44a6-9f75-77f42dc9e608)

After calculate this seems more accurate.
Hope that can help.

![螢幕擷取畫面 2023-09-14 211331](https://github.com/shaka-project/shaka-player/assets/12542531/25a88f2b-15c3-4e1e-99df-a323948af927)
