### ISSUE TITLE
VTT cues relative segment start time is not getting applied

### ISSUE THREAD

**Issue by OrenMe** [shaka-project/shaka-player#3242]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Tes

**What version of Shaka Player are you using?**
3.0.8 and latest on master

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome on Mac OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**_Sent via email_**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default config, I can reproduce on the Shaka sample app with just applying the playback URL

**What did you do?**
1. load playback URL
2. choose subtitle from menu

**What did you expect to happen?**
See captions

**What actually happened?**
Captions do not appear

Additional input:

The offset is calculated only from period start time and not from segment start
https://github.com/google/shaka-player/blob/568321c2d147962dab29195466fc17756a2b452f/lib/text/vtt_text_parser.js#L53

I followed the discussion here https://github.com/google/shaka-player/issues/480, and change done here https://github.com/google/shaka-player/pull/542/, that has since been removed here: https://github.com/google/shaka-player/commit/9a86d0460ff53a22df253e0f1109be31f5598f0d and indeed in the past the offset was segmentStart and not periodStart.
It was lately changed here https://github.com/google/shaka-player/commit/4bf22e2359a840fe15c482de5e4671cfb72c14f0 to periodStart and there was an active discussion that got stopped around this exact line, that can be seen in link to the change.

I have a test stream provided

**Comment by OrenMe** [comment]
I read a bit more in the description of https://github.com/google/shaka-player/commit/4bf22e2359a840fe15c482de5e4671cfb72c14f0.
My two cents here is that there are packagers applying segmented VTT to live videos so this might break them, but if aim here is to conform to IOP then I can also understand why this change was applied.
Nevertheless, would you re-consider?
I can already tell you I saw players implementing their own VTT parser just to patch the parseMedia method.

**Comment by TheModMaker** [comment]
It seems this change is needed to play many HLS content, and Safari does it like we do now.  But we could probably add back the flag to select which mode to work in.

**Comment by philippe-elsass-deltatre** [comment]
Hello this is still a pretty major issue for Live DASH with in-band VTT. 
VTT times are relative to segment start and since upgrading to Shaka 3.x the subtitles are broken.

There should be a configuration option to define the behaviour...

**Comment by philippe-elsass-deltatre** [comment]
@avelad @joeyparrish @theodab sorry to @ you but this is in fact a bug. Live DASH subtitles are very broken right now.

**Comment by joeyparrish** [comment]
@OrenMe sent a test stream URL privately, but the manifest currently at that URL has no text streams at all.

@philippe-elsass-deltatre, can you provide us with a test stream to look into this?  If this can be done with public content, that is preferable, as it means more people could work on the issue.  If it must be private, you can send it to shaka-player-issues@google.com and it will not leave the team at Google.

**Comment by philippe-elsass-deltatre** [comment]
I'm chasing for a test stream (BTW how do I share one privately?) but essentially, it's really a tiny option that we need:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/82216401/160360501-c8586dd9-e3d2-440b-b61d-3e73632b99c4.png">

**Comment by joeyparrish** [comment]
> I'm chasing for a test stream (BTW how do I share one privately?)

Here:
> If it must be private, you can send it to [shaka-player-issues@google.com](mailto:shaka-player-issues@google.com) and it will not leave the team at Google.

There is some history on this.  Here are a few links and quotes from a previous debate:

https://github.com/shaka-project/shaka-player/issues/480#issuecomment-245833294
> **DASH-IF IOP v3.3, section 6.4.5 forbids the use of plaintext TTML/WebVTT text in multiple segments**, as quoted below.
>
> > Only one file for the full period is permitted, practically limiting this use case to non-live content.
> >
> > Such external files are assumed do have a timeline aligned with the Period, so that TTML time 00:00:00.000 corresponds to the start of the Period. [...]
> >
> > The same applies to side-loaded WebVTT files. In that case, the @MimeType is text/vtt. If segmented subtitles are needed, such as for live sources, ISOBMFF-packaged TTML or WebVTT segments are expected be used to provide proper timing.
>
> Therefore the use of such content is dubious at best. You should be using ISOBMFF encapsulation for text streams.

https://github.com/shaka-project/shaka-player/issues/480#issuecomment-259348711
> Specification-wise, media samples that exist in ISOBMFF containers exist on a separate timeline from the period, with presentationTimeOffset being the alignment factor. *[snip]*
>
> However, **media samples that exist in plain text (sidecar) files are assumed to have a timeline aligned with the period** (see DASH-IF IOP 6.4.5)!

So it seems to me that the current behavior is correct with regard to the DASH IOP.

However, since the change you want is trivial, I propose that you send a PR to introduce a new configuration. 
 By default, we will keep the current, IOP-inspired behavior.  If the new config is set, we will make VTT segment times segment-relative.  I propose that this config be available indefinitely, not as a temporary transition from one default to another.  It's easy enough to offer both interpretations.

The new config can be passed from Player to MediaSourceEngine to TextEngine.  We can add a new field to `shaka.extern.TextParser.TimeContext` (which is given by TextEngine to all parsers).  This new field will be equal to either `periodStart` or `segmentStart`, depending on the config.  The VTT parser can then use this field instead of `periodStart`, and all other parsers can use the fields they are already using (which are already correct in context).

Thoughts?
