### ISSUE TITLE
Fonts are loaded from fonts.gstatic.com

### ISSUE THREAD

**Issue by FireMasterK** [shaka-project/shaka-player#3257]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Shaka-Player UI library loads fonts from google's CDN.

**Describe the solution you'd like**

I would like to package these fonts/files myself.

**Describe alternatives you've considered**

I'm not sure

**Additional context**
![image](https://user-images.githubusercontent.com/20838718/111861804-1d435e80-8977-11eb-9036-298a0cdaebc2.png)

**Comment by FireMasterK** [comment]
The source for this is: https://github.com/google/shaka-player/blob/c5af2be27a2256e699763e0570235b30838ed2aa/ui/controls.less#L15-L17

**Comment by TheModMaker** [comment]
I think if you override these fonts in your CSS, then the browser will load yours instead of these.  Unfortunately since these are static CSS files, we can't set these at runtime based on configurations.  But we could add something to the build scripts to replace it.

**Comment by FireMasterK** [comment]
> But we could add something to the build scripts to replace it.

Would this reflect in the npm package too, or would I have to build it manually for this?

**Comment by joeyparrish** [comment]
What are we talking about replacing here?  The CSS URL?  Or the font URL from inside that CSS file?

**Comment by FireMasterK** [comment]
I'd like to be able to load the fonts from my servers, so that I don't need to use Google's cdn just for the fonts.

For this case, I think the css can be omitted (requiring them to be loaded externally), or the fonts could be distributed along with the package (without linking gstatic).

**Comment by demetrius-tech** [comment]
I also encounter this issue and would be nice to have it fixed soon. What "priority:P3" means?

**Comment by joeyparrish** [comment]
I don't know the distribution terms of Google's fonts offhand.  It's possible that they could be distributed with the player, but caching performance will be better if a common URL is used across sites.  A user who has used any other app with those fonts will have them in cache when they visit your app, and vice-versa.

May I ask why the fonts must be distributed from your server?

If you really insist on it, you can always choose to modify the font URL yourself.  This is, after all, open source.

**Comment by joeyparrish** [comment]
@demetrius-tech, the descriptions of each label can be seen in the project's labels list or by mousing over the label.  Our priority system goes from P0 (most urgent) to P4 (least urgent), with specific guidelines for each based on impact and severity.

**Comment by demetrius-tech** [comment]
@joeyparrish Thank you for your answer. We have firewalls that do not allow us to access the external resources. In case there is no solution to this, then I will look for an workaround.

**Comment by joeyparrish** [comment]
Have you tried overriding the font face rule with your own CSS?  You wouldn't even have to modify the existing CSS, I think.

**Comment by sunknudsen** [comment]
For privacy reasons, I self-host fonts in my React apps.

I installed [shaka-player](https://www.npmjs.com/package/shaka-player) and use custom version of `node_modules/shaka-player/dist/controls.css` removing `@font-face` declarations and replacing `font-family` attributes.

```css
.shaka-video-container .material-icons-round {
  font-family: "Material Icons Rounded";
  font-size: 24px;
}
.shaka-video-container * {
  font-family: "Roboto Mono", monospace;
}
```

I then installed [@fontsource/material-icons-rounded](https://www.npmjs.com/package/@fontsource/material-icons-rounded) and [@fontsource/roboto-mono](https://www.npmjs.com/package/@fontsource/roboto-mono) and import fonts.

Works flawlessly…

That said, feels like loading whole font (162.99 kB) only to use a handful of icons could be greatly optimized.

Would be great if this repo shipped with a custom version of font that only includes used icons.

**Comment by joeyparrish** [comment]
That's a great result!

But I think my preference would be if we stopped using the icon font entirely, and just used SVGs instead.  See #2467.  Any objections to closing this issue in favor of that solution?

If anyone feels motivated to make the change, SVG icons can be had from here: https://github.com/marella/material-design-icons/tree/main/svg#readme
