### ISSUE TITLE
Need better documentation for using  captions/subtitles when not using Shaka UI

### ISSUE THREAD

**Issue by hvgotcodes** [shaka-project/shaka-player#3315]
This is on latest chrome with shaka-player 3.0.10

I have some video streams with a single embedded CE-608 caption.  I can play the video stream but can't get the captions to display.  

From reading closed PRs I've pieced together that I need to have mux.js available, with `forceTransmuxTS: true` in the streaming config,  and tried code

```
player.addEventListener('streaming', e => {
      const track = this.shakaPlayer.getTextTracks()[0];
      this.shakaPlayer.setTextTrackVisibility(true);
      this.shakaPlayer.selectTextLanguage('en');
      this.shakaPlayer.selectTextTrack(track); 
});

```

I am unsure if that is all that is necessary to display captions, or if I need to do something else.  The track available on shaka has `active: true`, and there is a proper HTML TextTrack on the media element  with

`{kind: "subtitles", label: "Shaka Player TextTrack", language: "", id: "", mode: "showing", …}`

but it has no cues.  

Would be great if there was a guide that outlined how to do display captions/subtitles.

**Comment by michellezhuogg** [comment]
Hello @hvgotcodes , would you please share your manifest with us, so that we can reproduce?

**Comment by sonicd300** [comment]
@hvgotcodes by any chance are you using safari? I've had to create my own captions selector and filter out an automatically added track which is something that safari does in response to a really old issue, this track will exist in the DOM no matter what (in the safari case). 

@michellezhuogg Manifest aside it would be very helpful to have documentation related to how to side load text tracks that are not packaged in the manifest, I've been struggling for quite sometime specifically when casting, currently somewhere in the docs suggest that the best place to side load text tracks is after awaiting `player.load()` this will ensure player has triggered a `load` event, but something is odd and it's better to listen to `loaded` event from the player and do the side loading in there. A detailed guide would help big time.

**Comment by michellezhuogg** [comment]
@sonicd300 ,
We hear you! We'll add tutorial for displaying captions. If anyone wants to contribute, that's welcome as well!
Reference: https://github.com/google/shaka-player/issues/3241#issuecomment-801215127

**Comment by avelad** [comment]
Currently mux.js is no longer needed to support CEA-608 so it is not necessary to add this documentation.
