### ISSUE TITLE
List and play partially offline video

### ISSUE THREAD

**Issue by nimishsinghal** [shaka-project/shaka-player#3318]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.4

**Please ask your question**
I have a use case where I want to list and play partially downloaded offline video. If the user reaches the end of the downloaded content it should resume from the manifestUri.

I wanted to check if this use case is possible with the current shaka player implementation. Any possible ways to achieve this behavior.

**Comment by joeyparrish** [comment]
I don't believe that would work today, but that's something we could consider.

Today, the manifest object lands in storage last, after all segments.  To support background fetch (#879), we would need to create the manifest first, with an "incomplete" flag, then store the segments, then update the flag to mark it as "complete".

This work could be done independently of background fetch itself, which would allow you to list incomplete videos.  But they couldn't be played back.

Playback would mean also updating the stream records in the database as each segment was stored.

Perhaps we could change the system to build the entire database upfront, before fetching any segments, and to record the URL and byte range of each segment alongside the segment data itself.  Then, only the segment records need updating as we download, and the URL and byte range data could be used to resume an incomplete download.

**Comment by avelad** [comment]
It is currently supported.
