### ISSUE TITLE
Live DRM on Chrome buffers for an extended period of time on Chrome

### ISSUE THREAD

**Issue by pajong** [shaka-project/shaka-player#3322]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome Version 89.0.4389.114, Mac OS 10.15.7 (Can reproduce in other Mac/Chrome versions)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Sent to shaka-player-issues@google.com

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

None, just using the demo App

**What did you do?**

Start the playback on Chrome, left it for 5-10 minutes

**What did you expect to happen?**
The playback happens seamlessly without buffering

**What actually happened?**

The stream buffers for a long time periodically, sent a video recording on the email.
This DOES NOT happen on other browsers (e.g. Firefox)

**Comment by surajkumar-sk** [comment]
@pajong when hls Livestream video(shaka-player history video) is loaded in the demo page it plays the first 10 sec of video and then goes into buffering state for infinite time. This issue occurs in chrome, firefox, edge (all latest versions). I just wanted to confirm that is this issue and your issue same, or should I open a new issue for this. 

Thank you.

**Comment by pajong** [comment]
@surajkumar-sk Thank you for checking the issue. Can you please check why the stream is buffering infinitely after a few seconds?

**Comment by surajkumar-sk** [comment]
@pajong I checked the network log for knowing the cause of the error. I think that specific video(shaka-player history) is at fault here. First, the master playlist is fetched, then all the media playlists are fetched from the master playlist. It is live content so media segments should continuously be added at the end of the list of media playlists. But for that video media segments are not being added so the player tries to fetch the next media segment but the URI doesn't exist in the media playlist, the media playlist keeps updating but no new media segments get added so the video just keeps buffering.

**Comment by michellezhuogg** [comment]
Hello @pajong ,

Your manifest looks no longer valid. Could you please confirm that it's still available for testing?

**Comment by surajkumar-sk** [comment]
@michellezhuogg 

> It should be a different issue from the 'shaka-player history' video.
I didn't understand this, like do you mean the issue is not in the video, but it's something else.

Thank you

**Comment by joeyparrish** [comment]
> I think that specific video(shaka-player history) is at fault here. 

Looks like our live stream encoder is hung.  I'm looking into it now.

**Comment by joeyparrish** [comment]
For the sake of record-keeping, the live encoder hung after encoding ~1.43 million segments, which is a runtime of ~66 days.  From timestamps in the files, it appears to have been hung since March 27 without anyone noticing (about 19 days ago).

I tried to reboot it remotely, but something went wrong, and I will have to drive to the lab and power cycle it manually.  It might stay down for another day or so until I can manage that.

**Comment by surajkumar-sk** [comment]
>  it appears to have been hung since March 27 without anyone noticing (about 19 days ago)

😂😂 . The first few seconds play normally, and when the loading starts I usually leave the page because I got the files that I needed from the network log by that time. It's probably the same for anyone else who visited. I noticed it after reading this issue. 😂

**Comment by joeyparrish** [comment]
@surajkumar-sk, the history live stream is back up and running after the hung machine was rebooted.

@pajong, we can't reproduce the issue with the content you sent us private.  We get back an HTTP 404 error on the manifest.  Can you please double-check that the content is still available?

**Comment by pajong** [comment]
Hello, @joeyparrish 
It looks like the manifest url and the header value are generated dynamically. I sent a follow up email to get the updated url and header value. Please let me know if you need anything else. Thank you!

**Comment by joeyparrish** [comment]
Got it.  Thanks!

**Comment by joeyparrish** [comment]
The buffering appears to be because the server isn't responding quickly.  I'm seeing as much as 13 seconds TTFB (time to first byte) on some requests.  At one point in my playback session, a concurrent manifest and segment request were blocked for 13+ seconds.  Later requests were all sub-second.

Can you please look into metrics for your server/CDN to make sure it is healthy?  I don't see anything wrong with Shaka Player with this content.

**Comment by pajong** [comment]
Hello, @joeyparrish 
Thank you so much for looking into the issue.

We just confirmed that the issue does not happen on Shaka v2.5.21, but started happening since v3.0.0 (still happening on the latest version)
Why would the stream not have any issues with the response time in Shaka v2, but have issues in v3? Since the stream plays fine in earlier versions, wouldn't this be a Shaka player issue?

**Comment by joeyparrish** [comment]
What you're saying makes sense, but I honestly don't know.  I haven't spent any time debugging this issue with v2.5.

I'll put it back into the triage queue.  Whoever picks this up next should compare v2.5 with the master branch, and look to see if network response times are improved.  If all responses are faster in v2.5, we should compare to see if we're making different requests in v3.0, which might be a clue.

My instinct says that if the live edge calculations are different between v2.5 and v3.0, and the server blocks requests for segments that are not yet complete, that could explain the difference.

**Comment by surajkumar-sk** [comment]
I am actually free these days and I also read the code for the implementation of HLS in shaka-player. I could compare the two versions and diagnose the issue and find a possible cause. @pajong you could email me the manifest and license server URIs if you don't have an issue with it. 
sk10121815@gmail.com

**Comment by pajong** [comment]
Hello, @surajkumar-sk . I have already sent the manifest to shaka-player-issues@google.com. Do you still need me to send it to that gmail?

**Comment by surajkumar-sk** [comment]
I actually don't work at google on shaka-player . I am a student studying video streaming technology.

**Comment by pajong** [comment]
@surajkumar-sk Just sent out the information to the gmail - please let me know if you have issues with playing the stream. Thank you!

**Comment by surajkumar-sk** [comment]
@pajong I added the video manifest and license Uri and played the video in the latest shaka-player version. I didn't see any kind of lag. The Live content is playing pretty smoothly except for a few ms of buffers in between. The video below shows the streaming video.  I am using windows Chrome version 87.xx.x.


https://user-images.githubusercontent.com/71056993/115932150-368d6e00-a441-11eb-9210-107ce97ecab9.mp4


It worked properly in the current version so I didn't check it with v.2.5.x.
The problem might be a Mac thing or as @joeyparrish said, there might be a problem with the server. 
I am unable to reproduce the issue.

**Comment by pajong** [comment]
Since the Shaka team was able to reproduce and see the issue, I will wait for someone in the Shaka team to pick up and compare with v2. Thanks for looking @surajkumar-sk

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
