### ISSUE TITLE
Tizen 4 2018 encrypted playback got stuck. 

### ISSUE THREAD

**Issue by Yuvalke** [shaka-project/shaka-player#3344]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
v3.0.8 and v3.0.10

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Didn't try, reproduced on v3.0.x.

**Are you using the demo app or your own custom app?**
Custom app.

**What browser and OS are you using?**
Tizen TV.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen 4 2018, model number UE50NU7090. 

**What are the manifest and license server URIs?**
sent by email.

**What did you do?**
playing encrypted media.

**What did you expect to happen?**
The media will keep playing.

**What actually happened?**
There is a small gap jumping on the beginning of the media, stall handled by stallDetector, play-pause solution for smartTV happening and the playback got stuck on the same position.
Small seek solve the issue, seems like checking on stall detector if the current time has changed after trying to break the stall is needed because it sometimes breaks the stall and sometimes it doesn't, I added log file which show this behavior(pause-play solution is working much better than seeking in general)

[Log shows play pause stuck](https://github.com/google/shaka-player/files/6333988/tizen.logs.txt)

**Comment by Yuvalke** [comment]
The issue is when the stall happens on the beginning and then `pause` `play` doesn't help and I saw that multiple seeks until the media start again fix the issue(one seek by changing the stallSkip doesn't).
The stream I sent isn't valid any more, I'll provide a valid one if needed.

**Comment by david-hm-morgan** [comment]
I am seeing a similar sort of issue on a 2017 Tizen 3.  My way to reliably reprod it is to do big seek jumps:
1. play movie
2. seek to late in the movie and let play for a few seconds
3. seek back to near the beginning

It is possisble to recreate it on v3.0.6 and earlier, but from v3.0.7 it is seemingly 100% of seek backs as above will create it.  Same on 3.0.8, 3.0.9, 3.0.10 and today 3.0.11 too.

![image](https://user-images.githubusercontent.com/37144605/116558788-b743e280-a8f7-11eb-814b-97cfd49b2a07.png)
In this image, my seek back goes from the title rolling near the end to 0:00:05.

Am I seeing a different issue or the same as this ticket?

**Comment by Yuvalke** [comment]
Hi @david-hm-morgan, I guess it's the same issue but I didn't reproduce it in the exact same way, did you try on a later Tizen version? I saw in 2020 it works well.
Actually today I had some new findings, It reproduces on two scenarios:
1. the beginning after stall(small gap - `seeked`).
2. after multiple seeks in a row in the middle of the media. 
Also, I saw sometimes when the issue reproduced  `seeking` event dispatched but I don't see `seeked` event from the video element.

**Comment by david-hm-morgan** [comment]
@Yuvalke I have access to a 2019 (Tizen5) too and this does not exhibit this issue.

**Comment by david-hm-morgan** [comment]
I noticed this historical issue https://github.com/google/shaka-player/issues/2131 which again sounds similar.  Going to try to debug around stall detector

**Comment by Yuvalke** [comment]
Thank you @david-hm-morgan, there are many issues that could be related but they didn't resolve this issue.
It seems like we're facing the same issue with multiple seeks, new seek should reject the old one if it's still in process?

Thank you for your help.

**Comment by Yuvalke** [comment]
Hi @joeyparrish, I wrote in the ticket description the issue what the issue and where it's happening, do you need media to repro?
I solve the issue right now by checking while the media is in stall I make a small seeks until it breaks the stall.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
