### ISSUE TITLE
Stall occurs when transitioning from unencrypted DASH program content to Ads period

### ISSUE THREAD

**Issue by PaulPineda** [shaka-project/shaka-player#3345]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
There don't seem to be direct duplicates but there are similar issues of stalling that have been reported:
https://github.com/google/shaka-player/issues/2867
https://github.com/google/shaka-player/issues/3008
and _possibly_ https://github.com/google/shaka-player/issues/3191

**What version of Shaka Player are you using?**
Tested on Shaka Demo Player uncompiled v3.0.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
WebOS 4.x versions

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
* webOS 4.3.0 (43UK6470PLC)
* webOS 4.3.0 (32LK6100PLB)
* webOS 5.0.0 (50UN7500PLA)
* webOS 4.9.0 (43UM7600PLB)
* webOS 3.5 (608KCMR1V507)

**What are the manifest and license server URIs?**

The manifest URI has be send via email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Sent via email

**What did you do?**
1. Point an LG container app at https://shaka-player-demo.appspot.com/
1. Click “Custom content” to navigate to the view that allows you to add your own content
1. Click the “+” button at the bottom right hand corner of the window to add your content, add a name for this custom content and paste the manifest URI sent via email 
1. Play the content out and observe that the content stalls at around the 2:30 mark

NB The manifest URI point to an unencrypted DASH stream that has server side ads stitched in at certain point (also detailed in the email)

**What did you expect to happen?**
The content continues to play without issue through the 2:30 mark and beyond

**What actually happened?**

The player remains in a playing state but the content enters an indefinite stalling state

We have attempted to recover the stall in the following ways:
* Enable the stallDetection with Threshold set to 0 and 2. A stall was report around the expected time of 2:30 into the stream. Neither setup resolved the stall although the player state changed from being stalled in the Playing state to being stalled in the Seeking state.
* Remove B-frames from the Ad-content
* Checked for gaps in the buffer (no gaps were reported)

**Comment by joeyparrish** [comment]
We can't directly support or debug on WebOS.  This is currently considered a "community-supported" platform because we don't have the devices or test infrastructure set up for WebOS.

**Comment by joeyparrish** [comment]
We have purchased a WebOS device, and we intend to build out infrastructure to support it, but we have no timeline for that yet.  Other issues are currently higher priority.

**Comment by avelad** [comment]
@joeyparrish, May I ask what model of TV with WebOS you have bought?

**Comment by joeyparrish** [comment]
I think it was WebOS three-point-something, but I can't recall.  It is still in a box in the office.  It was something I intended to spend time on before the pandemic hit, and I haven't been able to get back to it since.

**Comment by PaulPineda** [comment]
> I think it was WebOS three-point-something, but I can't recall. It is still in a box in the office. It was something I intended to spend time on before the pandemic hit, and I haven't been able to get back to it since.

It'd be great to find out the specifics, we've found that neither the WebOS version nor age of the device to be a very reliable way of determining a device's capabilities and therefore the likelihood of being able to reproduce the issue

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
