### ISSUE TITLE
Add support for ID3 tags in mp4

### ISSUE THREAD

**Issue by ismena** [shaka-project/shaka-player#3351]
We use mux.js to parse ID3 tags in ts streams.
Mp4 also [supports](https://www.webcitation.org/6ACo4Nqy6?url=http://www.mp4ra.org/specs.html#id3v2) embedding ID3.
We should see if we can use mux.js to parse those or implement the parsing using our mp4 parser.

**Comment by avelad** [comment]
Please consider not using mux.js, because this adds an external dependency that might not be desired.

**Comment by avelad** [comment]
@joeyparrish already done with ID3 parsing in the Shaka.

**Comment by joeyparrish** [comment]
Fixed in PR #4409.
