### ISSUE TITLE
Create an Analytics component in Shaka for an integration with BigQuery

### ISSUE THREAD

**Issue by ismena** [shaka-project/shaka-player#3359]
We are planning an integration with Google Cloud Services and BigQuery to allow Shaka users to easily collect and understand the data related to how their media is being watched and interacted with.
(See the prototype presentation [here](https://youtu.be/0ZhKzS65EMo?list=PLIivdWyY5sqIl6CyJfr_cUFhxKikxrgYb)).

This is a tracker for the Shaka Analytics component. Design and concept paper docs are to follow.

**Comment by avelad** [comment]
I think it would be very nice to have a generic Analytics module, and that there is a specific module for integrating with BigQuery, but that applications can also add modules for integration with other services. What do you think?

**Comment by ismena** [comment]
Yeah, our design is in sync with that. The Shaka component is gonna listen to analytics-related events and send them to the endpoint, provided by the app.
As part of the BQ integration, we'll provide the code for the BQ-connected endpoint, but anyone's welcome to write their own backend for other services.

**Comment by avelad** [comment]
Is anyone interested in this? If not, the issue will be closed in 7 days.
