### ISSUE TITLE
HLS interstitial support

### ISSUE THREAD

**Issue by ismena** [shaka-project/shaka-player#3364]
Apple is working on a new spec for Client-side driven interstitials. Once they finalize it, we could
- provide guidance for apps for implementing the spec with 2 players (+add events that make it easier)
- provide implementation for platforms that can't support 2 players (depending on Apple's guidance on this)
- consider providing a built-in 2-player implementation in the future

**Comment by ronak2121** [comment]
Hey @joeyparrish do you know if this is also being considered for version 3.3? Do you have any idea on timelines when this would be supported?

**Comment by joeyparrish** [comment]
Nobody is working on it currently.  If someone in the community is interested to contribute, it may be possible to get it into our next release.  But right now, the core team is fully engaged on other features.
