### ISSUE TITLE
How to display a side loaded text track by default when using chromecast?

### ISSUE THREAD

**Issue by sonicd300** [shaka-project/shaka-player#3370]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.10

**Please ask your question**
I have side loaded text tracks which load/render properly during playback in a browser, but these aren't showing up by default when casting, instead it's turning the caption selector to its off state, if i manually select a track then gets displayed.

The text tracks are being loaded after the player had fired the loaded event, using `addTextTrackAsync` and awaiting that promise (side note: sometimes even if it's awaited it doesn't return the track), then selected and its visibility set to `true`.

Is there anything in particular that needs to happen to display side loaded text tracks by default when casting?

**Comment by avelad** [comment]
Since we want to do https://github.com/shaka-project/shaka-player/issues/4214 I'm going to close this issue.
