### ISSUE TITLE
Support playing multiple text tracks at once

### ISSUE THREAD

**Issue by Sweknas** [shaka-project/shaka-player#3436]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.1.0

**Please ask your question**
I am working on a project where i use Shaka player as a debug and quality verifier for dash files and have tried to figure out a way to show multiple textTracks of a dash manifest at once. I have looked trough the api documention and the code for some days but have not found a solution and understand that this maybe not something the player is built for but would like to get a tip if u think it should be possible to do in some way. It would be super nice if it could be done with your manifest parser and every thing to build uppon without to many own wierd tweeks and requests to sync it with the player. Thanks in advance :-)

**Comment by theodab** [comment]
We do not currently have any way to play multiple text tracks at the same time, no.
It's not too complex of a feature for us to add. It'd require some adjustments to the text engine, and probably a new method on the player to expose the behavior to developers, but not any huge architectural changes.
I'll mark this as an enhancement request for now, but I wouldn't necessarily count on us getting to it right away. I don't think anyone else has requested anything like this. In fact, a few weeks ago I had to solve a bug where this was happening by accident!

**Comment by avelad** [comment]
@joeyparrish can you review this request? Thanks!

**Comment by joeyparrish** [comment]
I don't have a solution for this, but I'm open to proposals.
