### ISSUE TITLE
Why does shaka sometimes convert CRITICAL errors thrown in a request filter to RECOVERABLE?

### ISSUE THREAD

**Issue by martinstark** [shaka-project/shaka-player#3455]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0

**Please ask your question**

Why does shaka sometimes convert a critical error thrown inside of a request filter to a recoverable error? Can I force the error to be fatal?

I discovered this while writing a custom filter for detecting when a manifest is fetched 10+ times with no segments being fetched. Since the particular case the filter is trying to detect is not that easy to reproduce I'm testing it on a regular live stream, which resulted in the filter throwing a recoverable error, despite severity being set to 2.

Testing some more, the behavior looks inconsistent, and I would like to try to understand why, so that I can write my filter accordingly.

If throwing on the first manifest request, the error shaka throws will immediately be critical.
If throwing on the second manifest request, the first error thrown will be recoverable, followed by a critical error on the next attempt.
If throwing on the third manifest request or later, the player will stall and infinitely throw recoverable errors.

The real filter resets the counter to 0 on segment requests. I've removed that part in order to test the filter on a regular stream, and make it easier to reproduce the shaka behavior I'm trying to understand.

```javascript
// This generates a non-fatal error, even though it explicitly throws a new shaka error with severity 2:

const getManifestStallFilter = () => {
  let counter = 0;

  return (type) => {
    if (type === shaka.net.NetworkingEngine.RequestType.MANIFEST) {
      counter += 1;
    }

    if (counter > 2) {
      throw new shaka.util.Error(2, 1, "MANIFEST_FETCH_LOOP", {
        reason: "Session closed due to manifest stuck in fetch loop.",
      });
    }
  };
};

// Results in an infinite amount of non-fatal errors while the player stalls. Segment requests stop, manifest requests keep happening, and each of them throw a non-fatal error:

{
  "severity": 1,
  "category": 1,
  "code": 1006,
  "data": [
    {
      "severity": 2,
      "category": 1,
      "code": "MANIFEST_FETCH_LOOP",
      "data": [
        {
          "reason": "Session closed due to manifest stuck in fetch loop."
        }
      ],
      "handled": false
    }
  ],
  "handled": false
}

```

```javascript
// This generates one non-fatal error, and then a fatal error on the next fetch:

const getManifestStallFilter = () => {
  let counter = 0;

  return (type) => {
    if (type === shaka.net.NetworkingEngine.RequestType.MANIFEST) {
      counter += 1;
    }

    if (counter > 1) {
      throw new shaka.util.Error(2, 1, "MANIFEST_FETCH_LOOP", {
        reason: "Session closed due to manifest stuck in fetch loop.",
      });
    }
  };
};

// Result

{
  "severity": 1,
  "category": 1,
  "code": 1006,
  "data": [
    {
      "severity": 2,
      "category": 1,
      "code": "MANIFEST_FETCH_LOOP",
      "data": [
        {
          "reason": "Session closed due to manifest stuck in fetch loop."
        }
      ],
      "handled": false
    }
  ],
  "handled": false
}

// Followed by

{
  "severity": 2,
  "category": 1,
  "code": 1006,
  "data": [
    {
      "severity": 2,
      "category": 1,
      "code": "MANIFEST_FETCH_LOOP",
      "data": [
        {
          "reason": "Session closed due to manifest stuck in fetch loop."
        }
      ],
      "handled": false
    }
  ],
  "handled": false
}

```

```javascript
// This generates a fatal error right away:

const getManifestStallFilter = () => {
  let counter = 0;

  return (type) => {
    if (type === shaka.net.NetworkingEngine.RequestType.MANIFEST) {
      counter += 1;
    }

    if (counter > 0) {
      throw new shaka.util.Error(2, 1, "MANIFEST_FETCH_LOOP", {
        reason: "Session closed due to manifest stuck in fetch loop.",
      });
    }
  };
};

// Result

{
  "severity": 2,
  "category": 1,
  "code": 1006,
  "data": [
    {
      "severity": 2,
      "category": 1,
      "code": "MANIFEST_FETCH_LOOP",
      "data": [
        {
          "reason": "Session closed due to manifest stuck in fetch loop."
        }
      ],
      "handled": false
    }
  ],
  "handled": false
}
```

**Comment by joeyparrish** [comment]
Sounds like it could be a bug or an oversight.  Happy to accept a PR if you feel like looking into it.  Otherwise, we will get to it eventually.  Thanks!

**Comment by avelad** [comment]
Can you check if the error occurs in the latest versions? The logic has changed a lot since the issue was opened. Thank you!

**Comment by fredrik-telia** [comment]
I'll see what I can do!

**Comment by avelad** [comment]
@fredrik-telia So, can we close the issue?

**Comment by fredrik-telia** [comment]
I believe so, yes, thank you!
