### ISSUE TITLE
Add specific doc on localization strategies

### ISSUE THREAD

**Issue by zisiskol** [shaka-project/shaka-player#3464]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ ](https://bit.ly/ShakaFAQ)and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0 Compiled (Release)

**Please ask your question**
I am using Shaka Player UI and i would like to change the overflow Menu Buttons language. 
Based on the documentation and on my research, i tried to use something like this to change the language  to Greek:

```
let localization_ = new shaka.ui.Localization('el');
localization_.changeLocale(["el"]);
```

Unfortunately the buttons language is not changing, no matter if i call it before or after initializing my player.

Is this the proper way to change the language ?
Am i missing any step ?

Thanks in advance

**Comment by TheModMaker** [comment]
I think you do `ui.getControls().getLocalization().changeLocale(['el'])`.  `ui` is either the `shaka.ui.Overlay` object you created, or you can get it using `video.ui` if using the DOM setup.

**Comment by zisiskol** [comment]
Hi @TheModMaker 

Thanks for the feedback.

I tried your proposals nevertheless it didn't work.

Below a part from my code:

```
var ui;
async function init() {
    var video = document.getElementById('video');
    ui = video['ui'];
    const config = {
        addSeekBar: true,
        seekBarColors: {
            base: 'rgba(226, 106, 106, 0.3)',
            buffered: 'rgba(226, 106, 106, 0.54)',
            played: 'rgb(226, 106, 106)',
        },
        controlPanelElements: ['skip', 'play_pause', 'time_and_duration', 'mute', 'volume', 'fullscreen', 'overflow_menu', 'spacer'],
        overflowMenuButtons: ['captions', 'cast', 'quality', 'language', 'picture_in_picture', 'loop', 'playback_rate']
    };

    ui.configure(config);
    ui.getControls().getLocalization().changeLocale(["el"]); // try to change menu language
    const controls = ui.getControls();
    const player = controls.getPlayer();

    // Listen for error events.
    player.addEventListener('error', onPlayerErrorEvent);
    controls.addEventListener('error', onUIErrorEvent);

    // Try to load a manifest.
    // This is an asynchronous process.
    try {
        await player.load(manifestUri);
        // This runs if the asynchronous load is successful.
        console.log('The video has now been loaded!');

    } catch (error) {
        onPlayerError(error);
    }
}
```

**Comment by joeyparrish** [comment]
You're doing it correctly, but Greek is not one of the 18 locales built in at compile time.  These are your options:

1. Select localizations to add to the build at compile-time:
```sh
./build/build.py --name custom +@complete --locales en el ar es zh
# This generates dist/shaka-player.custom.js
```

2. Load specific locale data at runtime (adjust the URL as needed):
```js
  const controls = ui.getControls();
  const localization = controls.getLocalization();
  const response = await fetch('ui/locales/el.json');     // <----- JSON translation URL here
  const translations = await response.json();
  const translation_map = new Map(Object.entries(translations));
  localization.insert('el', translation_map);
```

3. Lazy-load any requested locale data at runtime (adjust the URL as needed):
```js
  const controls = ui.getControls();
  const localization = controls.getLocalization();

  localization.addEventListener('unknown-locales', async (e) => {
    for (const locale of e.locales) {
      const response = await fetch('ui/locales/' + locale + '.json');     // <----- JSON translation URL here
      const translations = await response.json();
      const translation_map = new Map(Object.entries(translations));
      localization.insert(locale, translation_map);
    }
  });
```

4. Come up with a custom way to store and load translations.  As long as you can provide a `Map` to `localization.insert()`, you can get this data however you like.

Does this help?

**Comment by joeyparrish** [comment]
(I've renamed this as a "docs" issue to put the above advice into a specific doc.)

**Comment by zisiskol** [comment]
This solve my problem now i can change the language. Also i agree that this should be a part of the documentation to help other developers to handle similar cases.

Thanks for your help.

**Comment by joeyparrish** [comment]
Glad to hear that it helped!  I'm going to reopen this issue to track adding this information to the tutorials.

**Comment by optimm** [comment]
Hi , i am very new to open source and would like to work on this issue if you could please guide me a bit
