### ISSUE TITLE
rangeError: Malformed FairPlay init data ( only iphone devices both chrome & safari ( Working fine in macOS safari)

### ISSUE THREAD

**Issue by kailash-byjus** [shaka-project/shaka-player#3505]
Hi Everyone,

I'm facing "Malformed FairPlay init data" (Error Code: 6016) On iPhone device only 

**The player is working fine in chrome, Mozilla, firefox, edge on windows & macOS**

Shaka Player version  : **"2.5.10"**,

**On iPhone device (chrome & safari) the video is loading fine but it's not playing it's in the pause state**

Safari version on mac OS is **Version 14.0.3 (16610.4.3.1.7)**

 
 Player configuration 
 ` player.configure({
   drm : {
   servers : {
    'com.apple.fps.1_0': 'https://drm....../fairplay/license',
    'com.widevine.alpha': 'https://drm...../license/widevine'
   },
   
advanced: {
   'com.apple.fps.1_0': {
          serverCertificate:  new Uint8Array([......
        }
},
fairPlayTransform  : isIOS ? false : true;
   }
 })`
 
 network configuration 
 
 `player
      .getNetworkingEngine()
      .registerRequestFilter(function (type, request) {
       
        if (type === 2) {
          request.uris[0] += `/${srcKey}`;
          request.headers['Content-Type'] = 'application/octet-stream';
          request.headers.Authorization = `Bearer ${authToken}`;
        }
      });`

**Comment by kailash-byjus** [comment]
@TheModMaker @joeyparrish 
@shaka-bot 
Can I get any help here on this error?

**Comment by avelad** [comment]
@kailash-byjus  Can you test with 3.3.4 or 4.0.0? Thanks!
