### ISSUE TITLE
Delay observed in start of playback 

### ISSUE THREAD

**Issue by jeev1989** [shaka-project/shaka-player#3508]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Not tried

**What browser and OS are you using?**
Chrome Version 91.0.4472.114  - MAC OS Big Sur

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

streaming: {
                    rebufferingGoal: 1,
                    bufferBehind: 6,
                    bufferingGoal: 10,
                    durationBackoff: 1,
                    ignoreTextStreamFailures: true
}

**What did you do?**

** Load any playback url from the start and observe the time taken for the playback to start**
** Load any playback content from a specific location(Resume) functionality**

**What did you expect to happen?**
Playback to start without any delay/lag

**What actually happened?**

** There was a significant delay observed during the start of play in the above mentioned both scenarios.**

**Compared to Shaka 2.5.10 version  with the  latest Shaka 3.1.1, the delay observed between the start of playback is 1 second.**

**Comment by kumarashu123** [comment]
**We tried playing the same VOD content with Shaka v2.5.10 and v3.1.1, v3.1.2 and found that the video start time is higher in 3.1.1, 3.1.2 compared to 2.5.10.**
	
Same network speed, manifest url and buffering configuration was used for testing the two.
	
Url used: https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths/dash.mpd
	
Statistics:

1. Network bandwidth at the time of testing: 13Mbps	
2. 20 iterations were done		
3. Avg. video start time for 2.5.10 - 2697 ms
4. Avg. video start time for 3.1.1 - 3090 ms

**Comment by michellezhuogg** [comment]
Hello @jeev1989 , thank you for reporting the issue! Is the delay observed with multiple manifests, or only the sample manifest that you mentioned? Is the delay observed both Dash and HLS?

**Comment by jeev1989** [comment]
The delay is observed for all the manifests. Our current requirement uses only dash content. We have observed it on Dash as of now. We have not tested in on HLS.

**Comment by joeyparrish** [comment]
Performance should be much better in general with the latest releases.  It's possible that #4064 has solved this issue.  Can you please try your content again with the latest releases?  Currently, that would be v4.0.0, v3.3.4, or v3.2.6.
