### ISSUE TITLE
Hook / Plugin Access HLS Playlist Custom Tags

### ISSUE THREAD

**Issue by derekdowling** [shaka-project/shaka-player#3523]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes.

**Is your feature request related to a problem? Please describe.**

The HLS video backend that I am looking to use with Shaka encodes server side ad insertion metadata into HLS playlist files using [EXT-X-DATERANGE](https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.2.7) tags. This metadata is used to manage visibility of custom ad player UI elements while also supplying data to that element to display ad duration, count, remaining time, etc.

**Describe the solution you'd like**

Plugin hooks similar to that of Caption Parsing and Displaying but for SSAI metadata or even more generally for custom `EXT-X-*` or `EXT-X-DATERANGE` derived events, whatever level of abstraction seems the most useful or generally applicable for all Shaka consumers. Basically I want the ability to parse timed events from playlist tags, push them into a queue, have Shaka determine when the event should be emitted, and then have a "Displayer" for doing something interesting with them.

This issue covers a similar use case: https://github.com/google/shaka-player/issues/1983.

**Describe alternatives you've considered**
From looking at the [plugin/customization](https://shaka-player-demo.appspot.com/docs/api/tutorial-plugins.html) guide, it doesn't appear that there is an easy way to access this information. To accomplish this today, it appears I would have to override the default [HlsParser](https://shaka-player-demo.appspot.com/docs/api/lib_hls_hls_parser.js.html#line55), which is undesirable.

**Comment by dazilb** [comment]
Are there any updates on this issue?
