### ISSUE TITLE
Account for safeSeekOffset in seekRange()

### ISSUE THREAD

**Issue by OrenMe** [shaka-project/shaka-player#3526]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
latest and 3.0.10

**Please ask your question**
I'm trying to seek to beginning of a live stream for a start over scenario where a current show has started and hasn't finished and user wants to start over and watch it from 0 sec.
The stream is live with fixed start time and growing buffer.
What I'm trying to do is to seek to actual second 0 of video but what I see is that I can only seek to a few seconds from the start of the window.
I'm trying to set the currentTime to be the seekRange start value.
I can reproduce it on my streams and also on streams in the demo site, for example this: 
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/livesim/segtimeline_1/utc_head/testpic_6s/Manifest.mpd;panel=ALL_CONTENT;panelData=LIVE,DASH;build=uncompiled
And I use this code in the console.
```
document.querySelector("video").currentTime = shakaDemoMain.player_.seekRange().start;
```
This media has timeShiftBufferDepth of 5 minutes but I can only get it to seek back to ~(-4:52) and same happens with rest of live streams.

What we are trying to do is to correlate times with EPG data and show start over as a time slot with VOD like timings, so we for example show UI of a show and we can show that it is, for example, 22 minutes since it started and has 8 more till it ends.
And if user wants to start over he can see to 0, but when user seeks to 0 or clicks the "StartOver" button then stream will always start from a few seconds and not 0.

What am I'm missing here? is this a bug or limitation or just me not using the API correctly?

**Comment by OrenMe** [comment]
Hi @joeyparrish, sorry I was on vacation so took time to see it.
I linked also one of the test stream from Shaka demo site as it happens there as well.
```
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:ns2="urn:mobitv" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" availabilityStartTime="1970-01-01T00:00:00Z" id="Config part of url maybe?" minBufferTime="PT2S" minimumUpdatePeriod="PT0S" profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:com:dashif:dash264" publishTime="2021-07-19T08:59:15Z" timeShiftBufferDepth="PT5M" type="dynamic" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd">
   <ProgramInformation>
      <Title>Media Presentation Description by MobiTV. Powered by MDL Team@Sweden.</Title>
   </ProgramInformation>
   <BaseURL>https://livesim.dashif.org/livesim/sts_1626685058/sid_f42c5609/segtimeline_1/utc_head/testpic_6s/</BaseURL>
<Period id="p0" start="PT0S" ns2:publishTime="1970-01-01T00:00:00Z">
      <AdaptationSet contentType="audio" lang="eng" mimeType="audio/mp4" segmentAlignment="true" startWithSAP="1" ns2:qualityLevel="SD">
         <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main" />
         <SegmentTemplate initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/t$Time$.m4s" timescale="48000">
<SegmentTimeline>
```

Where can I find the 8 sec presentation delay?

You can repro it by following the steps in the description, are you able to see this by following them?

**Comment by OrenMe** [comment]
@joeyparrish is this related to `safeSeekOffset` which is set to 5 by default?
So it means that the actual `player.seekRange().start` should take into account the `safeSeekOffset`?
In our case the DVR window is for start over meaning the start time is fixed and only the live edge progresses so we do not have an issue with falling outside the start of the DVR window.

**Comment by OrenMe** [comment]
@joeyparrish any chance you can review my comment?
Do you think it might be a valid use case to include the safeSeekOffset in the seek range?

**Comment by joeyparrish** [comment]
There is a `suggestedPresentationDelay` attribute in DASH, and if it's missing, we have a configurable fallback.  It defaults to some multiple of the minBufferTime, if I recall correctly.

You can customize this with these configs:
  - `manifest.dash.ignoreSuggestedPresentationDelay`: if true, ignore the delay from the manifest and only use the fallback
  - `manifest.defaultPresentationDelay`: a specific delay in seconds, which defaults to "0".  "0" is interpreted differently for DASH & HLS.  For DASH, it's 1.5 * minBufferTime, and for HLS, it's 3 segment durations.  These are the historical defaults for these formats in Shaka Player.
  - `streaming.safeSeekOffset`: an offset applied to the start of the live range, to avoid a loop where we fall outside the window repeatedly.  Defaults to 5.

In your content snippet above, minBufferTime is 2, so the default delay would be 3.  This, plus safeSeekOffset of 5 would explain the 8-seconds you're seeing.  The presentation delay is taken out of the end of the range (it's bufferable, but considered past what we show to the user), and the safeSeekOffset is at the beginning of the range (it's not removed from the range, and we can fall back into that space during buffering, but it's a danger zone that we won't seek directly to).

Does this help explain?

**Comment by yuimbo** [comment]
Hi Joey,

Reading your comment above, it seems `PresentationDelay` and `safeSeekOffset` are parameters that affects how far towards the *end* of the bufferable range that is playable, correct?

Howeve,r the problem mentioned in the start of the issue (which I am also encountering) is that Shaka also seems to restrict how far into the *beginning* of the bufferable range that is reachable. I.e. while playing an ongoing livestream, seeking to 00:00  yields playback from a few seconds further forward in the stream instead.

**Comment by OrenMe** [comment]
thanks @joeyparrish, using the `safeSeekOffset` did the job for us.
@joeyparrish in regards to my comment here https://github.com/google/shaka-player/issues/3526#issuecomment-882539587 


> @joeyparrish is this related to `safeSeekOffset` which is set to 5 by default?
> So it means that the actual `player.seekRange().start` should take into account the `safeSeekOffset`?
> In our case the DVR window is for start over meaning the start time is fixed and only the live edge progresses so we do not have an issue with falling outside the start of the DVR window.

Specifically this:
>So it means that the actual player.seekRange().start should take into account the safeSeekOffset?

If I try to seek to start of DVR window maybe it is better to already take into account the `safeSeekOffset` in it cause in any case an app can only seek to `player.seekRange().start + safeSeekOffset`, so today an app will need to read both values to understand exactly what is the very first point in time it can seek to. WDYT?

**Comment by avelad** [comment]
@OrenMe Do you want submit a PR to improve it? Thanks!
