### ISSUE TITLE
Support `urn:mpeg:dash:event:callback:2015` Event schema

### ISSUE THREAD

**Issue by lundibundi** [shaka-project/shaka-player#3528]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.1.1 locally with `https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.1.1/shaka-player.compiled.debug.min.js`

**Please ask your question**
In the specification clause `5.10.4.5 DASH Callback Event` there is defined:

> DASH Callback events are indications in the content that it is expected by a DASH Client to issue an HTTP
GET request to a given URL and ignore the HTTP response. These event schemes are identified by the
URN "urn:mpeg:dash:event:callback:2015".
A content author may use such an event for tracking play-back of specific content on a server that is not
included in the media path.
...
An HTTP GET request is expected to be issued to a URL contained in message_data[].

Which IIUC is expected to make an http request upon reaching a specific presentation time of this period. And there is no expectation of any metadata needed in the media-segments themselves for this to work. (please correct me if this is not correct)

Therefore I tried to this MPD with different Event#presentationTime but couldn't get it to work in shaka-player.
(This is not a complete MPD file, just as an example here, if a full mpd would be required I'll try to provide one)

```
<?xml version="1.0" encoding="utf-8"?>
<MPD type="dynamic" profiles="urn:mpeg:dash:profile:isoff-live:2011" xmlns="urn:mpeg:dash:schema:mpd:2011"
     availabilityStartTime="1970-01-01T00:00:00.000Z" publishTime="2021-07-14T12:33:11.511Z"
     minimumUpdatePeriod="PT186.282S" minBufferTime="PT2.000S">
    <Period id="60dc63956db4d3548a810f15e-1626265991511" duration="PT300.000S" start="PT1626265991.511S">
        <EventStream schemeIdUri="urn:mpeg:dash:event:callback:2015" value="1" timescale="1">
            <Event id="0" presentationTime="0" messageData="http://localhost:8000/report-callback">1</Event>
            <Event id="1" presentationTime="5" messageData="http://localhost:8000/report-callback">1</Event>
            <Event id="2" presentationTime="10" messageData="http://localhost:8000/report-callback">1</Event>
            <Event id="3" presentationTime="15" messageData="http://localhost:8000/report-callback">1</Event>
            <Event id="4" presentationTime="20" messageData="http://localhost:8000/report-callback">1</Event>
            <Event id="5" presentationTime="25" messageData="http://localhost:8000/report-callback">1</Event>
        </EventStream>
        <AdaptationSet id="0" frameRate="15360/512" segmentAlignment="true" par="16:9" contentType="video"
                       maxWidth="1280" maxHeight="720">
            <Representation id="0" width="640" height="360" sar="1281:1280" mimeType="video/mp4" codecs="avc1.64001f"
                            bandwidth="756532">
                <SegmentTemplate timescale="15360" startNumber="1" media="video/360p-600-$Number$.m4s"
                                 initialization="video/360p-600-init.mp4" presentationTimeOffset="9216000">
                    <SegmentTimeline>
                        <S d="76800" r="418" t="0"/>
                        <S d="45056" t="32179200"/>
                    </SegmentTimeline>
                </SegmentTemplate>
            </Representation>
        </AdaptationSet>
    </Period>
    <UTCTiming schemeIdUri="urn:mpeg:dash:utc:direct:2014" value="2021-07-14T12:34:05.239Z"/>
</MPD>
```

I've found https://github.com/google/shaka-player/issues/1856#issuecomment-479124754 issue/comment but it doesn't consider the `urn:mpeg:dash:event:callback:2015` event "type" which is technically described in the spec.
I've also tried to look though the codebase but couldn't find anything connected with the `callback:2015` event.

Is there something possibly wrong with my MPDs (timings/values/etc) or does shaka-player not support `urn:mpeg:dash:event:callback:2015` at all?

**Comment by TheModMaker** [comment]
We don't support that.  We support `EventStream` elements, but by firing events for the app to do something.  We fire `timelineregionenter` and `timelineregionexit` events whenever the playhead enters or leaves a region defined by an event.  You could fire these yourself by listening for the enter event and sending the request yourself.  `event.detail` will be an [TimelineRegionInfo](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.TimelineRegionInfo) object.

**Comment by avelad** [comment]
Do you have a demo stream we can use to implement this? Thanks!
