### ISSUE TITLE
RESTRICTIONS_CANNOT_BE_MET error for multiple periods using different DRM keys

### ISSUE THREAD

**Issue by gscragg** [shaka-project/shaka-player#3529]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, there exists [this closed issue](https://github.com/google/shaka-player/issues/2503), where bad content was blamed. Perhaps we have the same problem, but our content is all generated in house and not an external ad service.

**What version of Shaka Player are you using?**
3.1.1

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes, but the content does not play at all.

**Are you using the demo app or your own custom app?**
Custom app, but its the most basic implementation of shaka in order to replicate the issue.

**If custom app, can you reproduce the issue using our demo app?**
No, because I need to customise the license requests.

**What browser and OS are you using?**
Chrome on MacOS.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
Demo player: [https://s3.ap-southeast-2.amazonaws.com/shift72.com/4012-demo.html](https://s3.ap-southeast-2.amazonaws.com/shift72.com/4012-demo.html)
Manifest: [https://s3.ap-southeast-2.amazonaws.com/shift72.com/4012-content.mpd](https://s3.ap-southeast-2.amazonaws.com/shift72.com/4012-content.mpd)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```js
{
        manifest: {
          dash: {
            ignoreMinBufferTime: true
          }
        },
        drm: {
          delayLicenseRequestUntilPlayed: false,
          servers: {
            'com.widevine.alpha': [redacted]
          }
        }
      }
```

**What did you do?**
Played multi period content, where the init data is not contained in the manifest.
I have not yet tried the same content with pssh datas in the manifest. 

**What did you expect to happen?**
Content to play and no errors generated. Our custom player, listens for shaka errors and shuts itself down if a critical one is encountered. These errors are reported as critical but playback can still happen (in current release).

**What actually happened?**
Content plays, but errors are thrown at every period boundary.
However in master, content does not play.

**Comment by gscragg** [comment]
The same issue occurs using the CAF receiver on a chromecast. The 4012 error is thrown and the receiver stops working.

**Comment by gscragg** [comment]
The issue is still present on 3.2.0.

**Comment by TheModMaker** [comment]
The license server is giving me a 401 `not authorized` error when I try.  I think the problem is around [here](https://github.com/google/shaka-player/blob/d5769eeda47524998a714a3d701604561d761b6d/lib/player.js#L5644), where we require all the keys to be available.  It is possible we don't load all the keys for future Periods, so it shouldn't be restricted yet.

**Comment by gscragg** [comment]
Apologies, content license had expired. I have fixed it now. You can see the 4012 error in the console, but the content is still playable.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
