### ISSUE TITLE
Support direct playback of HLS media playlists, without master playlist

### ISSUE THREAD

**Issue by CySlider** [shaka-project/shaka-player#3536]
The standard states:

[6.2.4.  Providing Variant Streams](https://datatracker.ietf.org/doc/html/rfc8216#section-6.2.4)

>    A server MAY offer multiple Media Playlist files to provide different
>    encodings of the same presentation.  If it does so, it SHOULD provide
>    a Master Playlist file that lists each Variant Stream to allow
>    clients to switch between encodings dynamically.

[6.3.1.  General Client Responsibilities](https://datatracker.ietf.org/doc/html/rfc8216#section-6.3.1)

>    The client obtains the Playlist file from the URI.  If the Playlist
>    file so obtained is a Master Playlist, the client can select a
>    Variant Stream to load from the Master Playlist.

Yet the Shaka player refuses the playback of a valid single variant HLS stream without a master playlist with 
`4022 HLS_MASTER_PLAYLIST_NOT_PROVIDED`

Also discussed here: https://github.com/google/shaka-player/issues/1580
Possible blocker for this is: https://github.com/google/shaka-player/issues/1431

**Comment by joeyparrish** [comment]
Renamed and marked as an enhancement.  We don't support this yet.

**Comment by CySlider** [comment]
IMHO enhancement is a mischaracterization.  

Only having one playlist is the default in this spec (Server **MAY** offer multiple play lists and only in that case it SHOULD provide a master playlist). And not supporting it, is a violation of the specs from as low as version 1. Also having handled at least dozen different HLS players every single one did support this.

I hope this gets more attention than P3/Enhancement.

**Comment by joeyparrish** [comment]
Can you explain the purpose of playing a media playlist without other variants?  If there's no adaptation, how is that meaningfully different than playing a single MP4?

**Comment by CySlider** [comment]
We also support multiple bitrates, but the implementation currently is, that in case there is only a single bitrate provided, we do not provide a master. Saves one - according to the specs unnecessary - roundtrip when starting playback. Playback delay and server load is a sensitive matter. Also we adhere to the specs, shaka not. Obviously it's your call, if you want to, but I still think this is rather a bug than an enhancement, at least if your goal is to be HLS standard compliant.

**Comment by soonwait** [comment]
we create a BlobPlugin to make a temporary master playlist, It's work now

**Comment by joeyparrish** [comment]
Upgraded to bug based on the argument made by @CySlider.  Thanks!
