### ISSUE TITLE
Playready + Microsoft Edge Seek Back Issue: Spamming seek back causes long buffer and video resumes from unexpected position

### ISSUE THREAD

**Issue by miguelriverarios** [shaka-project/shaka-player#3537]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.2.0 (via the Shaka Player Demo)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Microsoft Edge on Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

N/A

**What did you do?**

1) [Go to Shaka Demo Player on Microsoft Edge](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=ALL_CONTENT;build=uncompiled)
2) Set filters on DRM to Playready and Manifest to DASH
3) Play Big Buck Bunny (Azure)
4) Play the stream and seek to near the end of the stream (~ 10 min)
5) Spam seek back several times by clicking on earlier points in the timeline (refer to the gif below to see what I mean)
6) See the timeline jump back to the point where you originally seeked to (close to the end of the stream)
7) The stream will buffer for a while and eventually resume playback at the original point (close to the end of the stream), as opposed to the final point seeked to

**If you play the Big Buck Bunny video that only has Widevine support, this issue does not occur.

![shakaBuffering](https://user-images.githubusercontent.com/18443223/125993081-7013b282-8d26-487d-9a7e-3a6c20665572.gif)

**What did you expect to happen?**
Expected the stream to play from the final point that was seeked to

**What actually happened?**
The stream position jumps ahead and the stream buffers for a while and then starts playing from the first seeking point as opposed to the final seeking point. This issue was originally reported on our custom app, but we realized it was reproducible on the newest version of Shaka on the demo player. Issue only appears on Microsoft Edge with Playready (does not occur when you switch to Widevine).

**Comment by Wayne-Morgan** [comment]
I've noticed this also.
It looks as though the playback position is set according to the first seek, but the segment acquisition position is set according to the last. All of the segments from the position of the last seek, up to the position of the first seek are acquired and then discarded, before the segment acquisition finally catches up with the (incorrect) playback position.

**Comment by Wayne-Morgan** [comment]
I have a little more information on this issue.

I have an application playing DASH (playready) on Edge. I open the developer tools and paste in the following:
```javascript
const video = document.getElementById("video");
const intervalFn = () => console.log(">>> currentTime:" + video.currentTime)
let interval;
const seekListener = () => { console.log("seeking currentTime:" + video.currentTime); interval = interval || setInterval(intervalFn, 5); }
const seekedListener = () => { console.log("seeked currentTime:" + video.currentTime); clearInterval(interval); interval = 0; }
const otherListener = (e)=>console.log("Event " + e.type + " currentTime:" + video.currentTime);

video.addEventListener("seeking", seekListener)
video.addEventListener("seeked", seekedListener)

video.addEventListener("loadstart", otherListener);
video.addEventListener("sourceset", otherListener);
video.addEventListener("waiting", otherListener);
video.addEventListener("canplay", otherListener);
video.addEventListener("canplaythrough", otherListener);
video.addEventListener("playing", otherListener);
video.addEventListener("ended", otherListener);
//video.addEventListener("seeking", otherListener);
//video.addEventListener("seeked", otherListener);
video.addEventListener("play", otherListener);
video.addEventListener("firstplay", otherListener);
video.addEventListener("pause", otherListener);
video.addEventListener("durationchange", otherListener);
video.addEventListener("fullscreenchange", otherListener);
video.addEventListener("error", otherListener);
video.addEventListener("loadedmetadata", otherListener);
video.addEventListener("posterchange", otherListener);
video.addEventListener("textdata", otherListener);
video.addEventListener("ready", otherListener);
```
This will look at the value of `video.currentTime` as various video events are captured, and also monitor its value frequently between a `seeking` and `seeked` event.

With the video playing, I position the pointer on the seek bar at position t=6371s, and press the mouse button. I slide the mouse pointer to the left to position t=1536s before releasing the button.
I see the value of `video.currentTime` decreasing as I move the pointer to the left, but then it jumps up to 6371 again when the `seeked` event is received.
![image](https://user-images.githubusercontent.com/26894243/174094615-ec80aac5-86ed-4b53-9c1a-967384c614ce.png)

Now the StreamingEngine is busy acquiring segments from t=1536s, but the Playhead is waiting for t=6371s. Eventually the Streaming engine will catch up, and playback will restart at t=6371s.

While in this "catching-up" state, any seek to a position less than 6371 will position the StreamingEngine, but the Playhead will once again be reset to 6371 on the `seeked` event.
A seek to a point greater than 6371 will work correctly, and the player will recover.

@joeyparrish, @TheModMaker, if I have time I can take a look at this. Can you give me any hints at where to look?

**Comment by joeyparrish** [comment]
@Wayne-Morgan, thank you for the detailed work!

You should debug this in StreamingEngine to start.  It uses SegmentIterator to move sequentially through the segments, so once it has a segment to fetch, it will always continue in order from there.

This sequential movement gets reset on seek, but there may be a race or other bug in that logic.  Look for the seek listeners in StreamingEngine.

Also, on seek, StreamingEngine will generally clear the buffer and reset where it should stream from based on the current position of the playhead at that time.  This is where we might have a race.  There are private methods getSegmentReferenceNeeded_ and getTimeNeeded_ that could be relevant, but I can't recall why we have both.  Maybe they don't agree in some edge case, and that could be the cause of the issue.

Sorry I don't have more than guesses, and thank you for looking into it!  Let us know what else we can do to support you.

**Comment by Wayne-Morgan** [comment]
Someone just reminded me of this issue. I'm afraid I haven't had a chance to investigate. If anyone else wants to pick it up, please feel free.

**Comment by david-hm-morgan** [comment]
in conjunction with @Wayne-Morgan I've attempted to reproduce this with latest release v4.8.0 and cannot reproduce.  Please go ahead to dismiss this issue.
