### ISSUE TITLE
HLS parser does not offset presentation timeline for event type playlists

### ISSUE THREAD

**Issue by pcruiksh** [shaka-project/shaka-player#3557]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome+MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
Play HLS content with #EXT-X-PLAYLIST-TYPE:EVENT

**What did you expect to happen?**
Presentation timeline is offset toward 0 by the minimum segment start time

**What actually happened?**
The HLS parser treats event type streams as live streams for the purpose of offsetting (or not offsetting in this case) the presentation timeline. This is contrary to the stated intent in the comments regarding VOD/EVENT type streams (hls_parser.js line 516). Additionally, the condition at line 501 seems to indicate you are explicitly aware you may be handling event streams in that block, so the overall intent is confusing.

**Comment by avelad** [comment]
@pcruiksh Can you test with 4.3.0? Thanks!
