### ISSUE TITLE
Handling HLS Large Gap Between SSAI and Live Segment Discontinuity

### ISSUE THREAD

**Issue by derekdowling** [shaka-project/shaka-player#3560]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**

I am looking to integrate Shaka with a live stream HLS implementation that does SSAI with pre-roll ads (ad inserted at the very beginning of the HLS stream) and am running into a stall behavior. I am relatively new to the HLS standard and am continuing to trace through Shaka and try to debug if who's "fault" the stall is (Shaka needing a mechanism for an HLS compliant case, or our backend for not providing necessary HLS metadata for a large gap in times between a discontinuity) but was hoping to get some guidance in the interim.

Scenario:

- Shaka loads the initial Ad playlist. The first ad segment will always have a startTime of 60s (that does not accurately reflect the real live time of the stream)
- Shaka will successfully play through the ad playlist and segments
- When the discontinuity is encountered at the end of the ad, live stream segments will be downloaded with segment startTimes that are relative to the live stream
- Shaka ends up stalling because the last played ad segment "endTime" will be somewhere between 60 - 120s, and the next segment "startTime" can be 100's or 1000's of seconds later. (eg [{startTime: 68, endTime: 70}, {startTime:10343, endTime: 10345}]) Shaka begins to seek forward 3s at a time and obviously remains stalled indefinitely. 

Question:

Is there a way that Shaka can account for these types of scenarios and gracefully handle them? Or is there something our backend system should be doing to tell Shaka to handle a large gap like this that is already implemented? If this does appear to be a feature gap in Shaka and would be willing to aid in terms of suggesting a possible path forward, I would likely be able to implement the solution. Thanks!

Shaka Debug Logging For Context:

<img width="1412" alt="Screen Shot 2021-07-29 at 6 09 42 PM" src="https://user-images.githubusercontent.com/613964/127580780-eb17e617-a877-4d40-9c8e-fdaf7c2df237.png">

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
