### ISSUE TITLE
seekRange().start is going back and forth while start-over

### ISSUE THREAD

**Issue by yairans** [shaka-project/shaka-player#3571]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** Latest - v3.2.0

**Can you reproduce the issue with our latest release version?** Yes

**Are you using the demo app or your own custom app?** Demo app

**What browser and OS are you using?** Chrome/Mac OS

**What are the manifest and license server URIs?** Sent to mail

**What did you do?**
Load the start-over stream and observe the `seekRange().start`

**What did you expect to happen?**
`seekRange().start` is permanent

**What actually happened?**
`seekRange().start` is going back and forth between the manifest loadings. see the screenshot attached

![image](https://user-images.githubusercontent.com/17685520/128847910-8b7959a2-9851-4f34-809c-8cb26f86e0f4.png)

**Comment by OrenMe** [comment]
adding a bit more context, the stream is start over, meaning it has fixed point in past DVR that doesn't change and only the live edge progresses.
We have noticed that the way the seekRange is updated is tied to the live edge calculation as it is expected that the sliding window always progresses ahead and takes both the live edge ahead as well as the earliest start time of the window, but this is not the case with start over streams as explained above.
I think this is also the case with live event where initial stage the manifest is accumulating the DVR window.

**Comment by yairans** [comment]
Hi, any chance for someone to take a look?

**Comment by joeyparrish** [comment]
I see your point.  The start is based on the end, which is not correct in this case.  We would be happy to accept a PR if you want to attempt a fix.

**Comment by pulkit-30** [comment]
Please assign me this issue and please help me out with some code pointers/references from where I can start digging into it.

**Comment by joeyparrish** [comment]
@pulkit-30, you are welcome to work on this.  Please take a look in `lib/media/presentation_timeline.js`.

**Comment by pulkit-30** [comment]
Thank you for your response. I am starting working on this and I will create pull request soon.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
