### ISSUE TITLE
Changing manifest URI when initializating cast app

### ISSUE THREAD

**Issue by ScripterYoda** [shaka-project/shaka-player#3595]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**What did you do?**
I want to have possibility to change manifest URI inside receiver app (our manifest have one codec assets so I want to VP9 manifest if possible and H264 manifest otherwise). Now, there is a contentIdCallback that I can pass while initializating CastReceiver. 

**What did you expect to happen?**
I would expect that the contentIdCallback would always properly change url.

**What actually happened?**
contentIdCallback is only called with LOAD generic message but not with INIT shaka message or ASYNC CALL iwth load shaka message. Therefore, I have now no way to change my manifest URI.

**Comment by theodab** [comment]
If we did add something like this, `contentIdCallback` would not be the right place to put it. That is meant to turn `contentId` values into URIs, not URIs into other URIs. Changing it might break other peoples apps.
We could add a separate callback for this, I suppose?

In the meantime, though... you might be able to solve this problem with a [custom network scheme plugin](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shaka.net.NetworkingEngine.html#.registerScheme). Like, you could call `player.load` with a synthetic URI that contains the real URI, then have a custom scheme plugin redirect the request to the correct URI.
So the scheme plugin would look something like:

```js
shaka.net.NetworkingEngine.registerScheme('fake', (uri, request, requestType, progressUpdated, headersReceived) => {
  const realUri = uri.split('fake:')[1];
  const finalUri = realUri; // TODO: Determine which codec asset URI to load.
  return shaka.net.HttpXHRPlugin.parse(finalUri, request, requestType, progressUpdated, headersReceived);
});
```
Then you'd just append `fake:` to the start of the URI you want to load, and let this scheme plugin

**Comment by joeyparrish** [comment]
If you are happy manipulating the URI in a scheme plugin, I would make one tweak to @theodab's recommendation.  Instead of calling directly into `shaka.net.HttpXHRPlugin`, I would recommend modifying the request object's `uris` field and then calling `NetworkingEngine.request()`.  That way, you are not hard-coding the name of a plugin that may someday be deprecated.

If this solution doesn't work for you or it is too cumbersome, we could offer a new callback.

**Comment by avelad** [comment]
@joeyparrish I'm not sure we want to support this, since we want to do https://github.com/shaka-project/shaka-player/issues/4214 in the future

**Comment by joeyparrish** [comment]
Yes, obsolete now.  Thanks!
