### ISSUE TITLE
Add chapter marks in the seek bar

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#3597]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest

**Please ask your question**
I want to edit the `shaka-range-container` CSS is it possible to do so?

I tried to edit it but it picks the default CSS settings on progress update.

I want to make the input range circle in red color and the progress update of currentTime also in red and I have already created the overlay of my chapters on the timeline I just want to hide the `shaka-range-container` and display my chapters with just a progress update in red and the input circle in red.

Maybe Same as youtube!!

my Current UI
![shaka-ss](https://user-images.githubusercontent.com/59652404/130584150-09f2bbb0-d9b3-4dca-be1a-78017c94fcd3.png)

What I want to do
![image](https://user-images.githubusercontent.com/59652404/130584260-e35af249-525b-4c62-92f6-00696de1f402.png)

Is it possible? how?

Thank you advance for your answers : )

**Comment by hiren3897** [comment]
> @hiren3897 , how do you create chapters like that ? It isn't support by shaka-player by default right ? I'm interested!

Yes, you are right I created chapters my way ^^

> Back to the question, if I'm reading right - you already have your own chapter element, now you need the circle to be red and the default seek bar to be transparent? You can set seekBarColors to transparent ?

Yes, we can transparent the seek bar "base" and "buffered" and keep the "played" to red color.

I tried to append my chapters in the `shaka-seek-bar-container` but a good CSS is required to be overlayed on the seek-bar and also it should be capable to listen chapters click and a seek-bar (input) click event. In short same as youtube does ^^

But I am having a hard time doing so...

**Comment by kocoten1992** [comment]
I see your dilemma, either create from scratch seekbar with your functionality or a custom element and link it with current seekbar right ?

Since you already create your element, maybe just go with that, if I was doing it, my strategy would be:
1. Expose an api for the communication between them.
2. When user click on chapter it will notify seekbar (or the otherway around).

For example: there is a private method https://github.com/google/shaka-player/blob/d5769eeda47524998a714a3d701604561d761b6d/ui/controls.js#L1312, we can make that api public and use it for communication:

```js
// controls-extension.js
goog.require('shaka.ui.Controls');

/**
 * @override
 * @export
 */
shaka.ui.Controls.prototype.seek = function (currentTime) {
  this.seek_(currentTime);
}
```

Build with `python3 build/build.py +controls-extension.js`

And in your chapter element, we can do this:
```js
this.controls_.seek(currentTime);
```

None of the code was tested, this is just an idea, hope it help.

**Comment by hochhaus** [comment]
@hiren3897 Do you have any update on the status of your personal solution?

**Comment by hiren3897** [comment]
Hello @hochhaus 
I have a pretty good solution for the chapter's VOD that is in my application.

@joeyparrish @avelad 
Currently, I am struggling with Live chapter management because in shaka-player for example:
- If I `addChapterTrack() `for the first time 
    - URL: holds 10 chapter information
https://gist.githubusercontent.com/hiren3897/2ccfe08bb7f99892d28e7d91c2cb1293/raw/9f85cb7ea0b8ca35cd09528b2339f6c486d0e372/10BBB.vtt 
    - it returns an array of 10 chapters using` getChapters('en')`

- Then again I `addChapterTrack() `for the second time
  - URL: holds next 5 chapter information https://gist.githubusercontent.com/hiren3897/711508f42a3ad31105c64eb06bc8426c/raw/03a849d06f161046bfafbd9f5387369e0576565c/next5BBB.vtt
    - it returns the same array of 10 chapters using` getChapters('en')` added before
    - We don't have an update for an array with old + new chapters added to the player.
 
Do we have any kind of solution for this? Or it sounds more like a bug?
because the behavior should be when we add another chapter webvtt we should have an updated ARRAY of chapters.

A code for reference:

```javascript
const getChaptersData = async(chapterUrl, language, mimeType) => {
  await this.player_.addChaptersTrack(`${chapterUrl}`, `${language}`, `${mimeType}`);

  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(this.player_.getChapters(`${language}`));
    }, 1.5 * 1000); // it by defaults requires a delay of 1.5 seconds to get the chapters
  });
};

// 10 https://gist.githubusercontent.com/hiren3897/2ccfe08bb7f99892d28e7d91c2cb1293/raw/9f85cb7ea0b8ca35cd09528b2339f6c486d0e372/10BBB.vtt
// 5 https://gist.githubusercontent.com/hiren3897/711508f42a3ad31105c64eb06bc8426c/raw/03a849d06f161046bfafbd9f5387369e0576565c/next5BBB.vtt
// full https://gist.githubusercontent.com/hiren3897/b7d30a2505a1a8929175aaa7ded7c013/raw/0fce37ff8e389dcd86bdd4dc102ec4d23bf39b6d/BBB.vtt
setTimeout(async() => {
  console.log('first 10');
  const data = await getChaptersData('https://gist.githubusercontent.com/hiren3897/2ccfe08bb7f99892d28e7d91c2cb1293/raw/9f85cb7ea0b8ca35cd09528b2339f6c486d0e372/10BBB.vtt', 'en', 'text/vtt');
  console.log({ data }); // 10 chapters array in console
  console.log(this.player_.getChaptersTracks()); // have one track in console
}, 5000);

setTimeout(async() => {
  console.log('next 5 added');
  const data = await getChaptersData('https://gist.githubusercontent.com/hiren3897/b7d30a2505a1a8929175aaa7ded7c013/raw/0fce37ff8e389dcd86bdd4dc102ec4d23bf39b6d/BBB.vtt', 'en', 'text/vtt');
  console.log({ data });  // same 10 chapters array in console
  console.log(this.player_.getChaptersTracks()); // have 2 tracks in console
}, 10000);
```



Thank you for you help in advance :)

**Comment by avelad** [comment]
@hiren3897 I have a solution for this, throughout today I'll do a PR to solve it.

On the other hand, your second VTT file is wrong, the WEBVTT header is missing.

**Comment by hiren3897** [comment]
@avelad Thanks for the quick response
here is my second WEBVTT: https://gist.github.com/hiren3897/711508f42a3ad31105c64eb06bc8426c

Once you resolve the problem please update me on the solution.

I have a question
Once you do a PR on this and then it will be set to be released on the next launch date because for me it is urgent and I am dependent on npm release for my current project.

Do you have any idea how I can make it work for now? or when will be the release of 3.3.1 ?

**Comment by avelad** [comment]
About the dates, someone from the ShakaPlayer team has to answer...

**Comment by hiren3897** [comment]
Okay, thanks

@avelad 
And can you tell me is it possible to solve this problem with a temporary fix now? `I am using npm`
should we merge the array? 
how do we get both WEBVTT data from the player?

@joeyparrish can we know the date?

**Comment by joeyparrish** [comment]
I don't have time to do another release today, but I have been cherry-picking changes to the v3.3.x release branch.  I'll see if I have time tomorrow.

**Comment by hochhaus** [comment]
Thanks @hiren3897, @avelad and @joeyparrish.

@hiren3897 Are you able to share details (ideally code) about the solution in your application? Is it at the point where a PR to this repo makes sense?

**Comment by hiren3897** [comment]
> I don't have time to do another release today, but I have been cherry-picking changes to the v3.3.x release branch. I'll see if I have time tomorrow.

It will be really appreciated :partying_face: thanks

**Comment by hiren3897** [comment]
> Thanks @hiren3897, @avelad and @joeyparrish.
> 
> @hiren3897 Are you able to share details (ideally code) about the solution in your application? Is it at the point where a PR to this repo makes sense?

For now, I am quite busy with my application for VOD and live chapters. I will do this PR when I will have the best time of mine. :)

**Comment by hochhaus** [comment]
Thanks @hiren3897

**Comment by hochhaus** [comment]
@joeyparrish Thanks for the 4.0.0 release.

I see support for "multiple chapter tracks with same language" but I can't find support for the "chapter marks in the seek bar". Did a change making it easy to add such markers in the seek bar land and I'm just missing it?

**Comment by hiren3897** [comment]
I think @joeyparrish has by mistake closed this issue 

And the work is not yet done for the chapter markers

**Comment by joeyparrish** [comment]
Yes, looks like this issue was tagged in the release notes, which caused the release workflow to close this issue.  Sorry for the mistake!

**Comment by jcavalca** [comment]
Hey @joeyparrish, just wanted to check if there were any updates regarding plans of adding this feature. Thanks!

**Comment by Trail3lazer** [comment]
@joeyparrish hey Joey, I was curious about what it would take to create this feature. I was trying to figure it out but, I'm struggling to be able to manually test my seekbar additions in my solution. 

Do you know how I can run a local instance of the player without a server or hosted website?

This is my fork and branch https://github.com/Trail3lazer/shaka-player/tree/chapter-marks

The existing automated tests seem to be working and if this ends up being something that works I'd like to create some additional unit and integration tests.

**Comment by theodab** [comment]
We use Apache to host the demo page locally for testing. If you'd rather not set that up, you could also use a script, like the `SimpleHTTPServer` python script.

**Comment by avelad** [comment]
@Trail3lazer Please, create a PR in this repo. It seems that you create the PR in you own repo. Thanks.

**Comment by Trail3lazer** [comment]
@avelad Sorry, I didn't see this sooner. I created a PR a few days ago but realized I forgot to include language support. I am finishing some unit tests then I'll create another PR. I can create it sooner if that would be helpful.

**Comment by Trail3lazer** [comment]
I'm having a lot of trouble trying to access dom elements in the integration tests. Am I setting up this test incorrectly? UiUtils.getElementByClassName(videoContainer, 'shaka-seek-bar-container') is an empty object. [Link](https://github.com/shaka-project/shaka-player/pull/5771) to my PR with all my changes. My test I wrote is failing because I'm struggling with the setup.
[chapter_ui_integration.txt](https://github.com/shaka-project/shaka-player/files/12900617/chapter_ui_integration.txt)

**Comment by Trail3lazer** [comment]
Sorry, I have been working on schoolwork and was unavailable to look into the PR comments you left until today. It looks like my changes were copied and then merged with this PR https://github.com/shaka-project/shaka-player/pull/5863. Is there any way I could have my commits linked to improve my portfolio?

**Comment by avelad** [comment]
Since there are problems with the functionality, the changes will be reverted and the issue will be opened again in case someone wants to work on it
