### ISSUE TITLE
WebOS multiple Updating manifest... on player start

### ISSUE THREAD

**Issue by makisp** [shaka-project/shaka-player#3624]
[WebOS - First run.txt](https://github.com/google/shaka-player/files/7121998/WebOS.-.First.run.txt)
[Tizen - First run.txt](https://github.com/google/shaka-player/files/7121999/Tizen.-.First.run.txt)

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Shaka 3.2 debug

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Own custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
WebOS 4.1.4-5726

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG 49UK6400PLF (Seems like a general WebOS issue as it happens on every WebOS device tested)
WebOS 4.1.4-5726

**What are the manifest and license server URIs?**
https://tr.prem.cdn.cosmotetvott.gr/sport1hd/sport1hd.isml/.mpd?ts=1616496517&dvr_window_length=3600&hdnts=st=1631020045~exp=1631063275~acl=*~id=c4c5311b-a47f-4d11-b73b-a1872d90fb75~data=e7e7c000a7679ede3910ba63cce989d6f032717b8110daf8d00b50897ca1342e~hmac=0503ff179eb5e824daec462ccebdc5931827d53e

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
`{
  "drm": {
    "retryParameters": {
      "maxAttempts": 1,
      "baseDelay": 500,
      "backoffFactor": 1,
      "fuzzFactor": 0.1,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "servers": {
      "com.widevine.alpha": "https://widevine.entitlement.eu.theplatform.com/wv/web/ModularDrm/getRawWid…Hm9xc7g&account=http://access.auth.theplatform.com/data/Account/2703510745"
    },
    "clearKeys": {},
    "advanced": {
      "com.widevine.alpha": {
        "distinctiveIdentifierRequired": false,
        "persistentStateRequired": false,
        "videoRobustness": "SW_SECURE_CRYPTO",
        "audioRobustness": "SW_SECURE_CRYPTO",
        "sessionType": "",
        "serverCertificate": {},
        "serverCertificateUri": "",
        "individualizationServer": ""
      }
    },
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1,
    "preferredKeySystems": []
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 1,
      "baseDelay": 500,
      "backoffFactor": 1,
      "fuzzFactor": 0.1,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": false,
    "defaultPresentationDelay": 0,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
      }
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "ignoreImageStreamFailures": false,
      "useFullSegmentsForStartTime": false
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 1,
    "bufferingGoal": 10,
    "bufferBehind": 0,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.1,
    "smallGapLimit": 4,
    "jumpLargeGaps": true,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2,
    "lowLatencyMode": false,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 1
  },
  "offline": {
    "usePersistentLicense": true
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 5000000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    }
  },
  "preferredAudioLanguage": "el",
  "preferredTextLanguage": "el",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferredVideoCodecs": [],
  "preferredAudioCodecs": [],
  "preferForcedSubs": false,
  "preferredDecodingAttributes": [],
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 360,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null
}`

**What did you do?**
When we load our DASH manifest we have noticed that in a WebOS device the player has an extra delay in the start of the video playback in compare with a Tizen device.
We used the shaka debug player and we noticed that the WebOS device is calling the Updating manifest... process three times while in a Tizen device this procedure is called only one time.
The Updating manifest... process seems to be the main root cause of the delay in the WebOS.
Why this Updating manifest... process is called two extra times in a WebOS device ?
Is there any configuration or way to solve those extra process ?

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
