### ISSUE TITLE
live dash streams stopped working with shaka but continue to work for other dash players

### ISSUE THREAD

**Issue by caridley** [shaka-project/shaka-player#3632]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.22

**Can you reproduce the issue with our latest release version?**
yes 3.1.2, 3.2.0

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
chrome on MAC OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
samsung tizen TVs all models

**What are the manifest and license server URIs?**
We will provide a sample stream URL when needed via e-mail, assuming that we are able to reproduce the problem at that time. I think we will be able to leave a stream in this bad state through tomorrow Wed 9/14. It would be awesome if some can look at the problem in that time frame.

See player-manifest.xml in the attached zip file 
[LiveStreamNotStarting2.zip](https://github.com/google/shaka-player/files/7159022/LiveStreamNotStarting2.zip)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
See player-config.json in the attached zip file 
[LiveStreamNotStarting2.zip](https://github.com/google/shaka-player/files/7159022/LiveStreamNotStarting2.zip)

Player state information at time of failure is captured in the player-metrics.json file in the attached zip file
[LiveStreamNotStarting2.zip](https://github.com/google/shaka-player/files/7159022/LiveStreamNotStarting2.zip)

Debug player logging up to time of failure is in the log.txt file in the attached .zip file
[LiveStreamNotStarting2.zip](https://github.com/google/shaka-player/files/7159022/LiveStreamNotStarting2.zip)

Here is a Charles proxy capture of the network requests made when attempting to start the stream
[CharlesProxy2.chls.zip](https://github.com/google/shaka-player/files/7159024/CharlesProxy2.chls.zip)

**What did you do?**

I tried to play the live stream from our application.

**What did you expect to happen?**
I expected the stream to start playing

**What actually happened?**
I can see that the manifest, init segment, media segment and drm license requests were successful and segments are loaded up to the bufferingGoal of 20 seconds but playback never starts.

This stream had worked previously with Shaka and other DASH video players.
It suddenly stopped working for just Shaka player.

This has happened with two different streams in the last 3 days.

Attachements
[LiveStreamNotStarting2.zip](https://github.com/google/shaka-player/files/7159022/LiveStreamNotStarting2.zip)

[CharlesProxy2.chls.zip](https://github.com/google/shaka-player/files/7159024/CharlesProxy2.chls.zip)

**Comment by joeyparrish** [comment]
Can you please clarify what platforms are affected?  You mentioned both Tizen TV and Chrome on macOS.

**Comment by caridley** [comment]
We have observed the problem with both Chrome and Tizen TVs. We suspect that it happens on all platforms. 

Unfortunately the current incarnation of the problem has resolved, and we are unable to test on other platforms.

This information in the palyer-metrics.json file caught my attention. Notice that mediaElement.currentTime is near start of the buffered text, but the buffer audio and video ranges are far ahead of that

 "bufferedInfo": {
  "total": [
   {
    "start": 3711136.373811,
    "end": 3711154.385665
   }
  ],
  "audio": [
   {
    "start": 3711136.373811,
    "end": 3711154.392499
   }
  ],
  "video": [
   {
    "start": 3711136.367666,
    "end": 3711154.385665
   }
  ],
  "text": [
   {
    "start": 3533680.15,
    "end": 3533696.1659999997
   }
  ]
 },
 "keySystem": "com.widevine.alpha",
 "expiration": 1631681766000,
 "mediaElement": {
  "crossOrigin": null,
  "currentTime": 3533681.014999,

**Comment by caridley** [comment]
@joeyparrish  it looks like this problem was caused by a 50 hour discrepancy in the presentationTimeOffset. We are able to easily reproduce the problem by altering the presentationTimeOffset with a Charles proxy rewrite. Using that method we have found that shaka fails to start the stream when the presentiatonTimeOffset is off in the negative direction by more than about 2 seconds.

Some of our video engineers tell me that it is not unusual to have some drift in live stream presentation times, although 50 hr clearly indicates a more severe problem.

I think we could make the player more resilient by effectively ignoring the presentationTimeOffset when actual presentation times have drifted outside some threshold. This might be done in streaming_engine.fetchAndAppend_() with some code something like this.

const presentationTimeInSegment = parsePresentationTime(segment);
const presentationTimeDrift = (presentationTimeInSegment + segmentReference.timestampOffset)  - segmentReference.startTime;
if(presentationTimeDrift < conflg.lowerDriftLimit  || presentationTimeDrift > config.upperDriftLimit) {
	segmentRefrence.timstampOffset =  presentationTimeInSegment - segmentReference.startTime;
}

What do you think?

**Comment by caridley** [comment]
We are working on a fix for this in our fork of shaka. Is there any interest in an MR with this fix? Note that the underlying problem is bad content; live manifests with incorrect presentationTimeOffset.

**Comment by david-hm-morgan** [comment]
Hi @caridley yes please I know myself and @Wayne-Morgan would welcome a fix to this.

**Comment by avelad** [comment]
Since the PR associated is declined, see https://github.com/shaka-project/shaka-player/pull/4444#issuecomment-1381084727 I'm going yo close this issue.
