### ISSUE TITLE
Shaka doesn't recover when a feed is stopped and started in quick succession

### ISSUE THREAD

**Issue by donnierisk** [shaka-project/shaka-player#3647]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
Yes, we encounter this on the demo shaka player as well

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Using latest version of chrome on Mac/Windows and Android

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

We get the player from UI config
manifest: {
                    retryParameters: {
                        maxAttempts: 2,
                        baseDelay: 1000,
                        backoffFactor: 1,
                        fuzzFactor: 0.5,
                        timeout: 30000,
                        stallTimeout: 5000,
                        connectionTimeout: 10000,
                    },
                },
                streaming: {
                    retryParameters: {
                        maxAttempts: 1,
                        baseDelay: 2000,
                        backoffFactor: 1,
                        fuzzFactor: 0.5,
                        timeout: 30000,
                        stallTimeout: 5000,
                        connectionTimeout: 10000,
                    },
                    rebufferingGoal: 2,
                    bufferingGoal: 10,
                    bufferBehind: 0,
                    ignoreTextStreamFailures: false,
                    alwaysStreamText: false,
                    startAtSegmentBoundary: false,
                    gapDetectionThreshold: 0.1,
                    smallGapLimit: 0.5,
                    jumpLargeGaps: true,
                    durationBackoff: 1,
                    forceTransmuxTS: false,
                    safeSeekOffset: 5,
                    stallEnabled: true,
                    stallThreshold: 1,
                    stallSkip: 0,
                    useNativeHlsOnSafari: true,
                    inaccurateManifestTolerance: 2,
                    lowLatencyMode,
                    autoLowLatencyMode: false,
                    forceHTTPS: false,
                    preferNativeHls: false,
                    updateIntervalSeconds: 1,
}

**What did you do?**

Start a stream from a program like OBS. Watch it on the shaka player; Stop the stream then start it again within a few seconds. The player gets stuck buffering infinitely and doesn't recover.

**What did you expect to happen?**
The player should be able to recover after a few seconds

**What actually happened?**

When we stop a video stream and then start it up again after a second. It seems like the highest number .ts file in an .m3u8 file fails first as shown in the screenshot with the network tab and error, and it reattempts a few .ts files before that one, but keeps getting interrupted or something. We don't get any logs from our config options that detected this; it silently buffers without us being able to do anything about it.

Network tab when the video stays frozen and doesn't recover:
<img width="1398" alt="Network tab when it is stuck" src="https://user-images.githubusercontent.com/17927429/133808251-83b8c724-4636-44e9-90e3-8989e838ed21.png">

Network tab when it works as usual:
<img width="1175" alt="Network tab when it is working" src="https://user-images.githubusercontent.com/17927429/133808260-a9a7e88a-f1ac-4333-b839-921692acf584.png">

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
