### ISSUE TITLE
hls parser doesn't set the audio codec properly when playing MS PlayReady CMAF DRM hls test stream.

### ISSUE THREAD

**Issue by HugoSaintLaurent** [shaka-project/shaka-player#3663]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.1

**Can you reproduce the issue with our latest release version?**
I have also reproduce the issue with 3.2.0

**Can you reproduce the issue with the latest code from `master`?**
I have not tried.

**Are you using the demo app or your own custom app?**
Issue can be reproduced with both.

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Windows 10 and Edge

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
PS5

**What are the manifest and license server URIs?**

LA_URL: https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(persist:false,ck:W31bfVt9W31bfVt9W31bfQ==,ckt:aescbc)
HLS manifest: https://test.playready.microsoft.com/media/dash/APPLEENC_CBCS_BBB_1080p/1080p_alternate.m3u8
dash manifest: https://test.playready.microsoft.com/media/dash/APPLEENC_CBCS_BBB_1080p/1080p.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
player.configure({
				drm: {
					servers: {
						['com.microsoft.playready']: 'https://test.playready.microsoft.com/service/rightsmanager.asmx?cfg=(persist:false,ck:W31bfVt9W31bfVt9W31bfQ==,ckt:aescbc)',
					},
					advanced: {
						['com.microsoft.playready']: {
							'distinctiveIdentifierRequired': true,
							'persistentStateRequired': false,
							'videoRobustness': '',
							'audioRobustness': ''
						}
					}
				}})

**What did you do?**
Play the hls stream using the custom tab in the demo app.

**What did you expect to happen?**
I expect the stream to play fine.

**What actually happened?**
Playback failed. When looking at streamInfo.stream.codecs for audio, the codec is set to "avc1.64002a". This value is not supported and the variant will be dropped when shaka.util.StreamUtils.filterManifestByMediaSource(this.manifest_); is called in player.js onInitializeDrm_(has, wants).  Calling this.filterManifest_(this.manifest_) before exiting the function would also drops the variant. Ether call will leave the player with no variant to play. Forcing the codec value to 'ac3' fixes the issues. Note that playing the dash version of the stream provided by Microsoft yields the proper results i.e. the stream plays and the audio codec is set to ac3.

**Comment by HugoSaintLaurent** [comment]
In the current version of the HLS specification available here: https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.6.2.  There is no mention in the EXT-X-STREAM-INF's CODEC attribute's description that it must contains all the codec that appears for the stream.

**Comment by avelad** [comment]
Does it work correctly now?
