### ISSUE TITLE
UITextDisplayer should be independent of css styles.

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#3670]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**Is your feature request related to a problem? Please describe.**

UITextDisplayer right now depends on css styles (https://github.com/google/shaka-player/blob/master/ui/less/containers.less#L298-L309), so if it only depends on the player without UI, you need to include undocumented code in your app.

**Describe the solution you'd like**

Remove all css style and include a config file for configure all styles.

**Describe alternatives you've considered**

I am open to opinions.

**Comment by joeyparrish** [comment]
I think hard-coding styles in JS is not a good pattern, and making them configurable through JS instead of hard-coded is more complex than just using CSS.

What if we split the TextDisplayer default CSS out into a separate output that is easier to include without the full UI CSS?

**Comment by avelad** [comment]
Your idea seems good to me, separating it in a separate file and easy to import is enough.

**Comment by avelad** [comment]
For me it's not longer necessary, so I'm going to close the issue.
