### ISSUE TITLE
Use Shaka CEA parser for TS

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#3674]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** YES

**Is your feature request related to a problem? Please describe.**

Right now there is the forceTransmuxTS setting to parse CEA-608 on devices that natively support TS, but this involves using mux.js and transmuxing TS to MP4.

**Describe the solution you'd like**

Since we have a CEA-608 parser for MP4, the idea would be to extend it to support TS.

**Describe alternatives you've considered**

Leave current behavior

**Comment by theodab** [comment]
It sounds reasonable as a feature. I'm not sure if we could justify getting rid of mux.js support altogether, but extending the CEA-608 parser to not require the intermediary step of turning TS into MP4 would be nice performance-wise.

I don't think this is something the Google Cast team is interested in, though, so I wouldn't expect us to get around to it anytime soon. I'll mark this as seeking PRs for now.

**Comment by avelad** [comment]
@theodab Do you know if the Cast team wants only DASH or is also interested in migrating and using ShakaPlayer for HLS as well?

**Comment by joeyparrish** [comment]
Looking at this again, forceTransmuxTS isn't only useful for CEA.  It's also useful for working around broken platforms.

So long as we have transmuxing with mux.js, I think we should give apps the option to force us to transmux TS, even when the platform claims to support it.

But I'm still in favor of using our native CEA parser for TS as soon as we can.
