### ISSUE TITLE
Why are we configuring Controls two times?

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#3705]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**Please ask your question**
1. In [`shaka.ui.Overlay`](https://github.com/google/shaka-player/blob/master/ui/ui.js#L27) class we are first creating Controls for the overlay using [`shaka.ui.Controls`](https://github.com/google/shaka-player/blob/master/ui/ui.js#L51-L52) in the constructor of this class we are configuring the layout of Controls here https://github.com/google/shaka-player/blob/a09d8c9869d5246af540d562f36546a294c2d9e9/ui/controls.js#L171 which is actually responsible for the creating the main structure of Control Panel.

2. After controls have been created we then call a configure function on the overlay https://github.com/google/shaka-player/blob/a09d8c9869d5246af540d562f36546a294c2d9e9/ui/ui.js#L54-L56

And in the configure function after player configuration, we are again calling the same configure function on controls. https://github.com/google/shaka-player/blob/a09d8c9869d5246af540d562f36546a294c2d9e9/ui/ui.js#L141

We are calling the same function twice, Why so? Is that to configure layout as demanded by the user like in the first call we set up the default UI and in the second we modify it merging the two config objects in the overlay configure function.

**Comment by WINOFFRG** [comment]
Yes, the Overlay constructor when creates new controls - configures the UI controls itself and hence there is no need to configure the controls again. It is ultimately affecting the time complexity for UI configuration. So what do you propose Sir? **Should we remove this call?** Should I raise the PR for it? https://github.com/google/shaka-player/blob/b8b72a900d155ef085e72e62b5da697d67990c04/ui/ui.js#L141

**Comment by WINOFFRG** [comment]
Hello @joeyparrish ! Any updates on this issue?

**Comment by joeyparrish** [comment]
Yes, of course.  Feel free to send a PR.  Thanks!

**Comment by WINOFFRG** [comment]
Hello! I was just testing by removing the extra control configuration call https://github.com/google/shaka-player/blob/b8b72a900d155ef085e72e62b5da697d67990c04/ui/ui.js#L141 as we discussed above. 

But found that, Test seemed to failed. Controls were not configured in the test browser. Moreover, The local live server which I created for my testing was using uncompiled version and there seemed no issue at all. Controls were configured properly. Refer screenshots below.

![image](https://user-images.githubusercontent.com/61311751/141656760-b7e69d7c-c701-43c4-85a9-510bd9e6bcc4.png)

Player Demo on localhost serving the same properly.
![image](https://user-images.githubusercontent.com/61311751/141656772-5b8fdf63-c193-4469-a001-ddd9cdb36e7d.png)

Player demo on Test browser. With missing controls.
![image](https://user-images.githubusercontent.com/61311751/141656800-39884664-ba7e-4356-bce4-65dd5d9a43e6.png)


What could be the reason? Was that extra call actually required, If yes could you please explain?

**Comment by theodab** [comment]
I would try removing the call to configure within `shaka.ui.Controls` instead:

https://github.com/google/shaka-player/blob/bd7b384c662b04ca4d9d083cc210ac7776a138a4/ui/controls.js#L171

The one that you disabled is the line that is responsible for changing the controls if the UI is reconfigured after creation, which is something we still need. It's also something a lot of the UI tests use, so it makes sense that the tests would break if you disabled it.

**Comment by WINOFFRG** [comment]
Now understood why the test failed! Thanks. Yes, at first I also thought to remove that one, but later found that the many functions in the `controls.js` were dependedent on that property. So, got no move but ultimately I realised that we are still making some extra calls which is configuring UI multiple times. Not sure on this.

Please do share an update. Thanks

**Comment by joeyparrish** [comment]
Sorry, it's really difficult to advise you on making a change if we can't see what you're doing.  Feel free to open a PR if you'd like to discuss the change there.
