### ISSUE TITLE
Shaka 3.X.X causes video to stall every few seconds on some WebOS TVs

### ISSUE THREAD

**Issue by makisp** [shaka-project/shaka-player#3707]
**Have you read the FAQ and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Shaka 3.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from master?**
Yes

**Are you using the demo app or your own custom app?**
Own custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
WebOS 4.1.4-5726

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG 49UK6400PLF (From our tests the issue seems to appear on WebOS **4.1.4-4.4.0** and/or **UK64XX** models)
WebOS 4.1.4-5726

**What are the manifest and license server URIs?**
https://tr.prem.cdn.cosmotetvott.gr/sport1hd/sport1hd.isml/.mpd?ts=1616496517&dvr_window_length=3600&hdnts=st=1631020045~exp=1631063275~acl=*~id=c4c5311b-a47f-4d11-b73b-a1872d90fb75~data=e7e7c000a7679ede3910ba63cce989d6f032717b8110daf8d00b50897ca1342e~hmac=0503ff179eb5e824daec462ccebdc5931827d53e

**What configuration are you using? What is the output of player.getConfiguration()?**
{ "drm": { "retryParameters": { "maxAttempts": 1, "baseDelay": 500, "backoffFactor": 1, "fuzzFactor": 0.1, "timeout": 30000, "stallTimeout": 5000, "connectionTimeout": 10000 }, "servers": { "com.widevine.alpha": "https://widevine.entitlement.eu.theplatform.com/wv/web/ModularDrm/getRawWid…Hm9xc7g&account=http://access.auth.theplatform.com/data/Account/2703510745" }, "clearKeys": {}, "advanced": { "com.widevine.alpha": { "distinctiveIdentifierRequired": false, "persistentStateRequired": false, "videoRobustness": "SW_SECURE_CRYPTO", "audioRobustness": "SW_SECURE_CRYPTO", "sessionType": "", "serverCertificate": {}, "serverCertificateUri": "", "individualizationServer": "" } }, "delayLicenseRequestUntilPlayed": false, "logLicenseExchange": false, "updateExpirationTime": 1, "preferredKeySystems": [] }, "manifest": { "retryParameters": { "maxAttempts": 1, "baseDelay": 500, "backoffFactor": 1, "fuzzFactor": 0.1, "timeout": 30000, "stallTimeout": 5000, "connectionTimeout": 10000 }, "availabilityWindowOverride": null, "disableAudio": false, "disableVideo": false, "disableText": false, "disableThumbnails": false, "defaultPresentationDelay": 0, "dash": { "clockSyncUri": "", "ignoreDrmInfo": false, "disableXlinkProcessing": false, "xlinkFailGracefully": false, "ignoreMinBufferTime": false, "autoCorrectDrift": true, "initialSegmentLimit": 1000, "ignoreSuggestedPresentationDelay": false, "ignoreEmptyAdaptationSet": false, "ignoreMaxSegmentDuration": false, "keySystemsByURI": { "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey", "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha", "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready", "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready", "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime" } }, "hls": { "ignoreTextStreamFailures": false, "ignoreImageStreamFailures": false, "useFullSegmentsForStartTime": false } }, "streaming": { "retryParameters": { "maxAttempts": 2, "baseDelay": 1000, "backoffFactor": 2, "fuzzFactor": 0.5, "timeout": 30000, "stallTimeout": 5000, "connectionTimeout": 10000 }, "rebufferingGoal": 1, "bufferingGoal": 10, "bufferBehind": 0, "ignoreTextStreamFailures": false, "alwaysStreamText": false, "startAtSegmentBoundary": false, "gapDetectionThreshold": 0.1, "smallGapLimit": 4, "jumpLargeGaps": true, "durationBackoff": 1, "forceTransmuxTS": false, "safeSeekOffset": 5, "stallEnabled": true, "stallThreshold": 1, "stallSkip": 0, "useNativeHlsOnSafari": true, "inaccurateManifestTolerance": 2, "lowLatencyMode": false, "autoLowLatencyMode": false, "forceHTTPS": false, "preferNativeHls": false, "updateIntervalSeconds": 1 }, "offline": { "usePersistentLicense": true }, "abr": { "enabled": true, "useNetworkInformation": true, "defaultBandwidthEstimate": 5000000, "switchInterval": 8, "bandwidthUpgradeTarget": 0.85, "bandwidthDowngradeTarget": 0.95, "restrictions": { "minWidth": 0, "maxWidth": null, "minHeight": 0, "maxHeight": null, "minPixels": 0, "maxPixels": null, "minFrameRate": 0, "maxFrameRate": null, "minBandwidth": 0, "maxBandwidth": null } }, "preferredAudioLanguage": "el", "preferredTextLanguage": "el", "preferredVariantRole": "", "preferredTextRole": "", "preferredAudioChannelCount": 2, "preferredVideoCodecs": [], "preferredAudioCodecs": [], "preferForcedSubs": false, "preferredDecodingAttributes": [], "restrictions": { "minWidth": 0, "maxWidth": null, "minHeight": 360, "maxHeight": null, "minPixels": 0, "maxPixels": null, "minFrameRate": 0, "maxFrameRate": null, "minBandwidth": 0, "maxBandwidth": null }, "playRangeStart": 0, "playRangeEnd": null }

**What did you do?**
When playing a 1080p/50fps stream, it stalls roughly every 15-20 seconds. The stall duration is about 500ms. Altering some of the player params didn't lead to any success.
This issue started from version 3.0.0. 2.5.X versions worked fine with no stalls. I'm also attaching two screenshots with the logs during a stall.

![freeze-moment](https://user-images.githubusercontent.com/17730817/137884073-e0691575-9771-4c74-bcf2-5198a13b9829.png)
![freeze-moment-shaka-debug](https://user-images.githubusercontent.com/17730817/137884078-779041bc-f47c-4500-a9b6-8c0e03081b63.png)

**Comment by yasinex** [comment]
We are experiencing the same issue. Is there any updates regarding this?

**Comment by joeyparrish** [comment]
We don't have official support for WebOS yet.  At this time WebOS support is community-maintained.

Without WebOS testing integrated into our lab, there is nothing we can do to debug a WebOS issue right now.

**Comment by lemmykilmister34** [comment]
We had the same issue on Webos 4 and solved it by decreasing buffer time of the player. 

bufferingGoal: 3,
        rebufferingGoal: 3

**Comment by SergioFernandez-Mirada** [comment]
> We had the same issue on Webos 4 and solved it by decreasing buffer time of the player.
> 
> bufferingGoal: 3, rebufferingGoal: 3

Not working for us, still reproducing multiple Stalls on WebOS TVs.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
