### ISSUE TITLE
Feature Request: SRD Support

### ISSUE THREAD

**Issue by UeliDeSchwert** [shaka-project/shaka-player#3718]
In the second amendment to MPEG-DASH, an extension called "SRD" (Spatial Relationship Description) is described.

In more detail, the workings of this technology are described in the Proceedings of the 7th International Conference on Multimedia Systems' paper by Niamut, Thomas, D'Acunto, Concolato, Denoual and Lim: [MPEG DASH SRD - Spatial Relationship Description](https://2016.acmmmsys.org/papers/MMSYS/a5-niamut.pdf).

Are there currently any plans for the Shaka-Player to introduce support for SRD?

**Comment by avelad** [comment]
Is anyone interested in this? If not, the issue will be closed in 7 days.
