### ISSUE TITLE
Live multi period gets stuck

### ISSUE THREAD

**Issue by yairans** [shaka-project/shaka-player#3719]
**What version of Shaka Player are you using?** 3.2.1

**Can you reproduce the issue with our latest release version?** yes

**Are you using the demo app or your own custom app?** demo app

**What browser and OS are you using?** mac chrome

The manifest is multi period where the period base url alternates alternately from one period to another.
Let's call the working period "working" and the not working period "not working".
**Scenario 1**.  joining to the live while the "working" period, the playback is smooth, the player switches between the periods without any issue. 
**Scenario 2**. Joining to the live while the "not working" period, the player loads only a couple of segments, and then gets stuck and loads only the manifests.
indeed, when this "not working" period is done, the player progresses to the "working" period smoothly. 

please find [here](https://drive.google.com/drive/folders/17DuERfDABuzet_2BpCXKx6U-R8ZpWo-Y) the logs and har of these 2 scenarios (the base url of the "working" is "cnn", and the base url of the "not working" is "blackout")

**Comment by michellezhuogg** [comment]
Hello @yairans , 
Thank you for reaching out! Please help me to understand your bug better. What are you expecting the player to do with the "not working" period?
Btw, if you can shorten the logs and display only the relevant messages, it would be easier for us to read. Thank you!

**Comment by OrenMe** [comment]
Hi @michellezhuogg , I'll answer on behalf of my colleague as he is not working today.
What we saw is that playback fails when playing the manifest in the "bad" period. We want it to play successfully basically.

What we observed though is strange and there is some compound effect here.
Basically there is content periods and transition periods.
As @yairans mentioned, if when a user loads the stream he encounters the content period and then after some viewing time the content switches to the transition period and then also the transition period changes back to the content period everything plays fine.
If a user enters the stream while there is a transition period then playback is stuck, and shaka keeps loading the manifest over and over without loading new segments(it loads the first 2-3 segments immediately when first loaded actually) and if you wait long enough till a switch to content period happens then suddenly shaka is able to load the segments from there and main content plays.

I hope this helps with the observation and the logs.
They r quite verbose cause we tried to capture all the transitions and provide them with the har files for inspection.

Does this help in any way to pin point the issue?

We also tested on other players and it worked there so we assumed it is some unhandled edge case.

**Comment by OrenMe** [comment]
@michellezhuogg was my explanation helped to make the issue more clear?

**Comment by OrenMe** [comment]
Hi @michellezhuogg did you get a chance maybe to look?

**Comment by yairans** [comment]
@joeyparrish @michellezhuogg any update here please?

**Comment by joeyparrish** [comment]
Apologies, but Michelle has moved on from the Shaka team.

Is this still an issue with the latest source from `main`?

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!

**Comment by OrenMe** [comment]
Thanks @avelad. Alas, also Yair has moved from the specific project this issue was opened from. @giladna can you test?
