### ISSUE TITLE
Dash/Live HLS + IMA ads failing to play in Samsung Tizen browser or in iPhone simulation mode on Chrome Browser

### ISSUE THREAD

**Issue by krackjack234** [shaka-project/shaka-player#3720]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app. Below is the url

https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpreonlybumper&cmsid=496&vid=short_onecue&correlator=;panel=CUSTOM%20CONTENT;build=uncompiled

Both Dash url and HLS Live url is showing same error.

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
1. Chrome Browser in iPhone simulation mode
2. Tizen browser on Samsung Tizen tv

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Samsung Tizen TV all versions

**What are the manifest and license server URIs?**

**DASH Manifest**: https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths/dash.mpd

**HLS LIVE Manifest**: https://storage.googleapis.com/shaka-live-assets/player-source.m3u8

**Ad Tag**:  https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpreonlybumper&cmsid=496&vid=short_onecue&correlator=

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Using demo app out of the box

**What did you do?**

1.Go to https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled
2. Add a DASH  or HLS live content 
3. Add a IMA ad tag 
4. Play the content

**What did you expect to happen?**
Ads should play followed by content

**What actually happened?**
Ads and content fails to play

Below error is seen on console

```
failed to get buffered range for video DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at shaka.media.MediaSourceEngine.getBuffered_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:476:47)
    at shaka.media.MediaSourceEngine.bufferedAheadOf (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:435:29)
    at shaka.media.StreamingEngine.update_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:963:49)
    at shaka.media.StreamingEngine.onUpdate_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:885:26)
    at shaka.util.DelayedTick.onTick_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1850:20)
    at onTick (https://shaka-player-demo.appspot.com/lib/util/delayed_tick.js:56:14)
```

**NOTE**

**Actual issue is happening on Tizen app / browser on Samsung Tizen tv.**
Same issue can be reported with **Chrome browser in iPhone 6/7/8 simulation mode**

**Comment by avelad** [comment]
The Tizen part is likely related to https://github.com/google/shaka-player/issues/2792

**Comment by avelad** [comment]
This will be resolved with https://github.com/shaka-project/shaka-player/issues/2792
