### ISSUE TITLE
How to fork one request to two in the registerRequestFilter?

### ISSUE THREAD

**Issue by vaseala** [shaka-project/shaka-player#3723]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes!

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes!

**What version of Shaka Player are you using?**
3.2.1

**Please ask your question**
I convert a mp4 file to dash which have a video file with the size of 30,000KB, for example.
Then For some reason， I have to split the video file to 3 segments, each with 10,000KB.
when play the video, I use the mpd file,which point to the video file of 30,000KB.
I do some work in the `player.getNetworkingEngine().registerRequestFilter` through the request.headers.Range, for example, when the range is `bytes=12,000-18,000`, I point the request to the second segment, and set the headers.Range to `bytes=2,000-8,000`, then it works。 But there has some Ranges cross two segments ， for example `bytes=18,000-24,000`, in this case, I have to request two segments: point`bytes=8,000-10,000` to the second segment and point `bytes=0-4,000` to the third segment, the problem is: I do not know how to achieve this?

**Comment by joeyparrish** [comment]
I would suggest that you split the files on segment boundaries instead.  Then you can more easily modify the DASH manifest to refer to the correct URLs.

Or better yet, package the content into separate files per segment in the first place.  Then you won't have to modify anything in the manifest or player.  This is what most people seem to do.

If you are using Shaka Packager or Shaka Streamer, I can offer you guidance on how to achieve that.  Otherwise, please consult the manual for whatever software you are using to encode and package the content.

Does this help?

**Comment by vaseala** [comment]
@joeyparrish  Thanks！

The scheme I am using now is a proxy URL:
First, pass the fragments information to the header of the URL in the request filter.
Then load multiple segments in the response filter, and then concat them and assign them to response.data.
It's not too elegant, so I want to use a more elegant way to achieve.

I don't want to divide a file into too many segments, I want to divide the file into a range of sizes.
For example: I want to divide an 800M file into about 80-100 M  per segment. Can it be achieved with shaka packager? 
If so, can you help me provide with some release document or demo of shaka packager?

**Comment by avelad** [comment]
@joeyparrish , can you help @vaseala with his last question? Thanks!

**Comment by joeyparrish** [comment]
@vaseala, if processing the video is an option, I would recommend you use Shaka Packager (more powerful) or Shaka Streamer (easier) to create a segmented DASH or HLS stream.  Modifying it on-the-fly in the player is bound to be more work.

Shaka Packager will only package: segment the inputs you give it, and create the manifests.  Shaka Streamer is a front-end to Shaka Packager and FFmpeg to both transcode and package the content in one step.

Does this help?
