### ISSUE TITLE
Memory Leak / Unhandled Promise Rejection: AbortError: Fetch is aborted - Safari playing DASH

### ISSUE THREAD

**Issue by bcupac** [shaka-project/shaka-player#3731]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
archived https://github.com/google/shaka-player/issues/3020

**What version of Shaka Player are you using?**
3.1.2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Big Sur - Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths/dash.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default shaka player demo configuration

**What did you do?**

1. start playback of Big Buck Bunny: the Dark Truths of a Video Dev Cartoon (DASH) on shaka player demo
2. burst seek by randomly clicking on the progress bar

**What did you expect to happen?**
no error 

**What actually happened?**

a bunch of  Fetch is aborted errors appear and Memory footprint starts getting larger.
 [Error] Unhandled Promise Rejection: AbortError: Fetch is aborted
	promiseEmptyOnRejected (http_fetch_plugin.js:64)
	promiseReactionJob

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
