### ISSUE TITLE
Hardcoded color in UITextDisplayer

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#3740]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** Master

**Can you reproduce the issue with our latest release version?** N/A

**Can you reproduce the issue with the latest code from `master`?** Yes

**Are you using the demo app or your own custom app?** Both

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?**
Any

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Don't apply

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Don't apply

**What did you do?**

Load a subtitle

**What did you expect to happen?**
The text is rendered correctly

**What actually happened?**

The text show a background color

Regression introduced here: 
[https://github.com/google/shaka-player/commit/cdeffbb9e6afcc68cb2165bcc0c99be20c9cb153#diff-4da2bc433a18f3034f87d4e923005ff2e2e6589926c98cd166487674f1a84d23R438](url)

![image](https://user-images.githubusercontent.com/8983024/140269668-820f448d-fc9a-42a8-8f90-2959555047f5.png)

**Comment by avelad** [comment]
Related to https://github.com/google/shaka-player/issues/3670

Acoording to @joeyparrish https://github.com/google/shaka-player/issues/3670#issuecomment-929402477, `I think hard-coding styles in JS is not a good pattern`

**Comment by avelad** [comment]
@joeyparrish can you review it?

**Comment by joeyparrish** [comment]
Yes, you're right.  Thanks!

I added priority and component labels.

**Comment by avelad** [comment]
For me it's not longer necessary, so I'm going to close the issue.
