### ISSUE TITLE
Don't use cached timescale for embedded captions when timescale can be parsed from the media segment

### ISSUE THREAD

**Issue by pcruiksh** [shaka-project/shaka-player#3749]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome + Mac OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
N/A

**What did you do?**
Play a stream with embedded CEA608 captions and try to display those captions

**What did you expect to happen?**
Captions are aligned with the media and display correctly

**What actually happened?**
I'll preface by stating I'm not actually 100% sure this is a bug.

Shaka caches timescales for closed captions by parsing the timescale and track ID from init segments:
https://github.com/google/shaka-player/blob/c993fca5793200a7d4ba556d6ef150db52365f68/lib/cea/mp4_cea_parser.js#L73-L89

This is creating issues with our content where the media segments don't seem to contain matching track IDs, so the cached timescale values are never used:
https://github.com/google/shaka-player/blob/c993fca5793200a7d4ba556d6ef150db52365f68/lib/cea/mp4_cea_parser.js#L159-L164

As a result, cue times are off by several orders of magnitude. However, this content has segment index (SIDX) boxes which contain the timescale metadata. It seems it would be preferable to use the timescale from the media segment, if available, and fallback to the cached value only if needed, e.g.
```javascript
  .fullBox('sidx', (box) => {
    goog.asserts.assert(
      box.version != null,
      'SIDX is a full box and should have a valid version.');
  
    box.reader.skip(4)
    sidxTimescale = box.reader.readUint32();
  })
  
  .fullBox('tfhd', (box) => {
    goog.asserts.assert(
        box.flags != null,
        'TFHD is a full box and should have valid flags.');
  
    const parsedTFHD = shaka.util.Mp4BoxParsers.parseTFHD(
        box.reader, box.flags);
  
    // If specified, defaultSampleDuration and defaultSampleSize
    // override the ones specified in the TREX box
    defaultSampleDuration = parsedTFHD.defaultSampleDuration
      || this.defaultSampleDuration_;
  
    defaultSampleSize = parsedTFHD.defaultSampleSize
      || this.defaultSampleSize_;
  
    const trackId = parsedTFHD.trackId;
    // Get the timescale from the track Id
    const cachedTimescale = this.trackIdToTimescale_.get(trackId);
    timescale = sidxTimescale || cachedTimescale || timescale;
  })
```

**Comment by TheModMaker** [comment]
This would be technically bad content.  The timescale in the `sidx` box is only valid for the values in the `sidx` box.  It is recommended that this match the media timescale, but it doesn't have to.  Each track in the media must have an associated track header.

We can keep this as a low-priority enhancement, but you should fix your content.

**Comment by pcruiksh** [comment]
@TheModMaker Thanks for the feedback, I will bring this up with our content team. Feel free to close this if you feel it is not a worthwhile enhancement.
