### ISSUE TITLE
Sync translation updates into Google's internal translation system

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#3752]
We have updated translations in this project that need to be pushed back upstream into Google's internal translation system (which is the source of these strings).  This will ensure that our next dump from that system doesn't overwrite and undo these improvements.  (For example, see PR #3751)

**Comment by avelad** [comment]
@joeyparrish , is this still necessary?

**Comment by joeyparrish** [comment]
Yes.  I need to work on some internal automation for this.  The two sets of translations are out of sync, and some new strings remain untranslated.

**Comment by avelad** [comment]
According to our conversation on Friday, @joeyparrish is  going to be in charge of automating this.

**Comment by joeyparrish** [comment]
Internal tracking in b/361830865

**Comment by joeyparrish** [comment]
Chinese translation updates made on GitHub have been reviewed and accepted in the internal system.  Still waiting on review of 6 Russian translations.

**Comment by joeyparrish** [comment]
Russian translations have been accepted.  I will poll the community on further conflicts between the two sets.

**Comment by joeyparrish** [comment]
Conflicts resolved.  Further changes pushed back to Google's Translation Console for 1x German, 1x Spanish, 1x French, and 2x Polish messages.  The new translations have yet to be accepted there.

**Comment by joeyparrish** [comment]
Polish and German changes accepted.  Still waiting on review for Spanish and French.

**Comment by joeyparrish** [comment]
Spanish translation accepted.  Waiting on French.

**Comment by joeyparrish** [comment]
French suggestion accepted. Everything is now in sync.
