### ISSUE TITLE
LL HLS MANIFEST.HLS_INVALID_PLAYLIST_HIERARCHY

### ISSUE THREAD

**Issue by toninospiderman123** [shaka-project/shaka-player#3757]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0, 3.2.1

**Please ask your question**
I'm trying to play a Low Latency HLS manifest on shaka player but i receive this error MANIFEST.HLS_INVALID_PLAYLIST_HIERARCHY (also on demo page with Low Latency Settings Enable)

How can i fix this? I'm available to share the manifest in private.

**Comment by avelad** [comment]
@toninospiderman123 Can you share a stream with the error you see?
