### ISSUE TITLE
Ima sdk integration with Shaka in react

### ISSUE THREAD

**Issue by pooryak** [shaka-project/shaka-player#3759]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
https://shaka-player-demo.appspot.com/docs/api/tutorial-ad_monetization.html
I read the documentation on this page but I couldn't implement it in react, Is there any sample for that?

**Comment by avelad** [comment]
We have no experience with react, but in the README there is a section with examples. (https://github.com/shaka-project/shaka-player#framework-integrations)

Can you tell us if they help you?
