### ISSUE TITLE
Missing metadata event with timed ID3 data in HLS stream from Telos Z/IPStream X/2 encoder

### ISSUE THREAD

**Issue by pszemus** [shaka-project/shaka-player#3761]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.2.1 (uncompiled)

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
didn't try

**Are you using the demo app or your own custom app?**
demo app

**What browser and OS are you using?**
Google Chrome 96.0.4664.45

**What are the manifest and license server URIs?**
https://wptv-devel.wpcdn.pl/open.fm/S04-HLS1-httpLS.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default demo app configuration

**What did you do?**
In demo app: 

1. start playing https://wptv-devel.wpcdn.pl/open.fm/S04-HLS1-httpLS.m3u8
1. add `metadata` event listener: ```shakaDemoMain.player_.addEventListener('metadata', (e) => {console.log("[t: " + shakaDemoMain.player_.getMediaElement().currentTime + "] MetadataEvent event", e);});```

**What did you expect to happen?**

After about 1 minute of playing there should be 2 `metadata` events. 
Hls.js shows them correctly:
![image](https://user-images.githubusercontent.com/13220781/142412481-300e3527-58b1-49a0-9424-dc196c199ef8.png)

**What actually happened?**
No `metadata` event fired.

**Comment by TheModMaker** [comment]
I don't think we support the `metadata` event ourselves.  We technically do on Safari since the browser does it for us; but when playing ourselves, I don't think we handle the metadata events/data.  We'll keep this as an enhancement to add this.

**Comment by pszemus** [comment]
@TheModMaker I can send you a sample HLS stream (from Wowza Streaming Engine) where `metadata` event is published in Chrome.

**Comment by avelad** [comment]
Your stream uses TS, and it seems like mux.js says it has metadata with dispatchType = 15, but it doesn't return no data or frames. I suggest you look at the logic of mux.js to see what is happening (https://github.com/videojs/mux.js/blob/main/lib/m2ts/metadata-stream.js).

**Comment by avelad** [comment]
mux.js PR --> https://github.com/videojs/mux.js/pull/408
