### ISSUE TITLE
Start of playback failure handling

### ISSUE THREAD

**Issue by synologic** [shaka-project/shaka-player#3764]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.1

I am trying to perform some error handling for the initial play request.
My config looks as follows:

streaming: {
      bufferingGoal : 12,
      bufferBehind: 24,
      rebufferingGoal : 0.1,
      inaccurateManifestTolerance : 0
  },
  manifest : {
      defaultPresentationDelay : 20,
      dash : {
          autoCorrectDrift: true,
          initialSegmentLimit: 1000,
      }
  },
  streaming : {
      stallEnabled: true,
      stallThreshold: 1000,
      stallSkip : 0,
      failureCallback : function(e) {
          console.log("Streaming failure callback")
          console.log(e);
      },
      retryParameters : {
          maxAttempts: 2,
          stallTimeout : 1000,
          connectionTimeout : 2000,
          timeout : 2000
      }
  }

My, corner, case is that the DASH manifest exists, but the audio and video INIT segments are missing, therefore there's no way to init the player decoders.

The player is attempting to download various init segments for a time i could not determine how to set to make sure it's not spending 20+ seconds trying to get the init segments so the first question is how would this be set ?

The second question is that, after a while, the player gives up on trying to download the init segments however there's no event being fired.

I am currently listening for the following events:

error, buffering, onstateidle, unloading, streaming, onstatechange

but none gets fired when the player gives up trying to download the inits, however the debug version keeps logging:

Updating manifest...
Already got the variants' decodingInfo.

Short of looking at the playhead to see if it's actually moving, is there any better way to detect Shaka not being able to start playing in this case ?

I suspect the same may happen if it's unable to find acutal video segments while playing.
In this case, the server is reachable, manifest is being delivered and 404 is returned for the init segments which are missing.

Some help here would be appreciated.

Thanks

**Comment by avelad** [comment]
@synologic Yesterday version 4.0.0 was released, can you test if it is still happening there? Thanks!
