### ISSUE TITLE
Problem with playback not always starting on Safari 15

### ISSUE THREAD

**Issue by sobbe81** [shaka-project/shaka-player#3768]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
3.2.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
N/A due to DRM

**What browser and OS are you using?**
Safari 15

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
When we play content in Safari 15 the playback does not start every time. Sometimes playback does not start and we do not get any indication that something is wrong. The same code works on Safari 14. 

When playback does not start we can get it to start by setting video.src = null or call player.load() from the console.

If we manipulate timing, introducing a sleep before we call load the playback is more likely to start.

**What did you expect to happen?**
Playback should start every time or give us an error message

**What actually happened?**

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
