### ISSUE TITLE
deSync in video and audio playlists is breaking shaka-player

### ISSUE THREAD

**Issue by denissabramovs** [shaka-project/shaka-player#3775]
Using `shaka-player v3.2.1`

![image](https://user-images.githubusercontent.com/65600131/143598790-2fba76d1-5e76-4da1-8038-b6038028f5f6.png)

**Current behavior**:
We have found out, that when video playlist is falling behind or stuck for some reason and audio playlist is ahead of it, then it breaks whole timeline for shaka-player.
You can remove some of the entries from video playlist manually and try to play that via shaka-player.

**Expected behavior**:
Be able to play video until desync part or at least skip those parts, where no video with audio provided for some time range.

**Comment by denissabramovs** [comment]
HLS Playlists:
https://gist.github.com/denissabramovs/d18d72d929e07c820078b318d29595f6
https://gist.github.com/denissabramovs/6871b1346f7b8b1682a7afe12a0a0453
https://gist.github.com/denissabramovs/856b336b768147f1ba40aa41d99f3d82

**Comment by denissabramovs** [comment]
Video playlist part to look into:
```
#EXTINF:29.952000,
#EXT-X-PROGRAM-DATE-TIME:2021-11-26T15:00:11.379+0000
playlist_01800.m4s
#EXT-X-DISCONTINUITY
#EXTINF:30.080000,
#EXT-X-PROGRAM-DATE-TIME:2021-11-26T15:05:43.798+0000
playlist_01801.m4s
```
Audio playlist to look into:
```
#EXTINF:30.000000,
#EXT-X-PROGRAM-DATE-TIME:2021-11-26T13:13:41.275+0000
playlist_11587.m4s
#EXT-X-DISCONTINUITY
#EXTINF:30.000000,
#EXT-X-PROGRAM-DATE-TIME:2021-11-26T15:05:43.798+0000
playlist_11588.m4s
#EXTINF:30.000000,
```

**Comment by denissabramovs** [comment]
Even after restarting recording process/service and recovering/continue playlists, shaka-player couldn't play those playlists anymore.

**Comment by denissabramovs** [comment]
Here is a small presentation of what is happening:
https://share.vidyard.com/watch/qubXAaXcaiPPy6YNNyN8wa?

**Comment by denissabramovs** [comment]
Here is a small presentation of what is happening:
https://share.vidyard.com/watch/fWhognCn75Fh6S5RrHcSS2?

**Comment by avelad** [comment]
@denissabramovs Can you test with 4.3.0? Thanks!

**Comment by denissabramovs** [comment]
Sorry that code was deleted a year ago, can't help you.

**Comment by avelad** [comment]
So I'm going to close the ticket, if it happens again please don't hesitate to reopen it. Thanks!
