### ISSUE TITLE
Continue loading live stream manifest when paused

### ISSUE THREAD

**Issue by lansi951** [shaka-project/shaka-player#3781]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.2.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
Not tested. but this issue not in the commit log.

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Microsoft Edge 96.0.1054.34
Windows 11 22000.348

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-live-assets/player-source.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default configuration

**What did you do?**
`load` live stream manifest, play video and pause.
or just `load`, not play video.

**What did you expect to happen?**
Stop load manifest also.

**What actually happened?**
Player continue loading when paused.
Load all resolution manifests every time.
Waiting many time, but not stopped load same.

Can stop loading or make option?

**Comment by OrenMe** [comment]
Hi @TheModMaker, any update on this issue? 
Our use case, we sometimes want to pause playback and any processing of AV and do another operation and then resume playback, this is especially important on low end devices where memory is limited.
Specifically this gets more complicated if manifests are too big (live with long DVR and audio and video encoding doesn't have aligned segments) and refresh every X seconds causes big memory spikes.

**Comment by avelad** [comment]
I've started working on this, if anyone has a suggestion now is the time. The first question is, do we want it to be configurable or not? I vote no, but I would like to hear from the community.

Note: PR for this feature will be created this week.
