### ISSUE TITLE
Excessive buffering on live DASH stream (does not happen with dash.js)

### ISSUE THREAD

**Issue by radiantmediaplayer** [shaka-project/shaka-player#3786]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Y

**What version of Shaka Player are you using?**
3.2.1

**Can you reproduce the issue with our latest release version?**
Y

**Can you reproduce the issue with the latest code from `master`?**
Y

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Y

**What browser and OS are you using?**
Chrome 96 for Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://d3b0cunbtfs49l.cloudfront.net/out/v1/0d53cb06a90e4626ac7fd29051b154f0/index.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default config for custom content at https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=debug_compiled

**What did you do?**
Just try to play above DASH live stream

**What did you expect to happen?**
Shaka player should play the stream ASAP. 

**What actually happened?**
It took 10 seconds and more to play content. The same issue happens if I manually switch renditions, excessive buffering and stalling happen. The same stream plays without issue at http://reference.dashif.org/dash.js/v4.2.0/samples/dash-if-reference-player/index.html in the exact same network condition.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!

**Comment by radiantmediaplayer** [comment]
I no longer have access to the problematic live stream so I am not able to run more test. I will close this issue and re-open if we encounter this issue again. Thanks for your answer.
