### ISSUE TITLE
Multiple hlsfairplay live streams faliure on same time

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#3787]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
latest v3.2.1

**Please ask your question**
I have created a multiplayer feature that contains 1 main player(highest resolution) that plays the video with sound and 3 small players attached muted with the lowest quality resolution (using setVariantTracks) on switch the quality changes vise versa.
- The first problem I see is in the shaka player UI they are no option that displays the quality in the overflow menu even if we have configured it.
- Second, in macOS safari only it is able to load the only one main player and the other small players keep on loading
  - I have checked all the players are correctly configured with DRM and serverCertificate.

![WhatsApp Image 2021-12-02 at 11 40 30](https://user-images.githubusercontent.com/59652404/144406548-bacd0295-cd31-4863-bb48-79056937e66d.jpeg)

**Comment by avelad** [comment]
Fairplay is only supported in src=, so the video element takes care of all the ABR work, plus it doesn't allow you to select which video quality to play.

I remember that Safari (depends on the HW of the mac), only allows 1 instance of FairPlay in the browser at the same time, but it also depends on the version of Safari.

For example on a macbook pro m1, Safari 15.4 only supports 2 videos with FairPlay at the same time. But with an intel macbook pro (2018), it only supports 1 video.

Does answer your questions?

**Comment by hiren3897** [comment]
Yes, it perfectly answers my question 
Thanks :)
