### ISSUE TITLE
Xbox Playback fails when seeking contents with closed captions

### ISSUE THREAD

**Issue by Vasanthavanan-Devarajan** [shaka-project/shaka-player#3789]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.13

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
NA

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
**Console Name**: XBOX ONE 
**SandBox**: XDKS.1,
**OS Version**: 10.0.22000.2989

**What are the manifest and license server URIs?**
**Manifest**: https://livesim.dashif.org/livesim/testpic_2s/cea608.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
`{
      "drm": {
        "retryParameters": {
          "maxAttempts": 2,
          "baseDelay": 1000,
          "backoffFactor": 2,
          "fuzzFactor": 0.5,
          "timeout": 10000
        },
    "servers": {},
    "clearKeys": {},
    "advanced": {},
    "delayLicenseRequestUntilPlayed": false,
        "logLicenseExchange": false,
        "updateExpirationTime": 1
      },
  "manifest": {
        "retryParameters": {
          "maxAttempts": 2,
          "baseDelay": 1000,
          "backoffFactor": 2,
          "fuzzFactor": 0.5,
          "timeout": 10000
        },
    "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "defaultPresentationDelay": 0,
        "dash": {
          "clockSyncUri": "",
          "ignoreDrmInfo": false,
          "xlinkFailGracefully": false,
          "ignoreMinBufferTime": false,
          "autoCorrectDrift": true,
          "initialSegmentLimit": 1000,
          "ignoreSuggestedPresentationDelay": false,
          "ignoreEmptyAdaptationSet": false
        },
    "hls": {
          "ignoreTextStreamFailures": false,
          "useFullSegmentsForStartTime": false
    }
  },
  "streaming": {
        "retryParameters": {
          "maxAttempts": 2,
          "baseDelay": 1000,
          "backoffFactor": 2,
          "fuzzFactor": 0.5,
          "timeout": 10000
        },
    "rebufferingGoal": 2,
        "bufferingGoal": 10,
        "bufferBehind": 30,
        "ignoreTextStreamFailures": false,
        "alwaysStreamText": false,
        "startAtSegmentBoundary": false,
        "smallGapLimit": 0.5,
        "jumpLargeGaps": true,
        "durationBackoff": 1,
        "forceTransmuxTS": false,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsOnSafari": true,
        "inaccurateManifestTolerance": 2
      },
  "offline": {
        "usePersistentLicense": true
      },
  "abr": {
        "enabled": true,
        "defaultBandwidthEstimate": 10000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
          "minWidth": 0,
          "maxWidth": null,
          "minHeight": 0,
          "maxHeight": null,
          "minPixels": 0,
          "maxPixels": null,
          "minFrameRate": 0,
          "maxFrameRate": null,
          "minBandwidth": 0,
          "maxBandwidth": null
        }
  },
  "preferredAudioLanguage": "",
      "preferredTextLanguage": "",
      "preferredVariantRole": "",
      "preferredTextRole": "",
      "preferredAudioChannelCount": 2,
      "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null
      },
  "playRangeStart": 0,
  "playRangeEnd": null
}`

**What did you do?**

- Play any live stream with closed captions
- Enable closed captions
- Seek back (any duration) on the stream
- Playback fails consistently

Note: The stream does not fail unless we enable captions. But once the captions are enabled, the stream consistently fails regardless of whether the captions are disabled again.

**What did you expect to happen?**
Playback should not fail.

**What actually happened?**

![XBOX_LIVE_Streaming_CC_ISSUE](https://user-images.githubusercontent.com/84713132/144426577-f06f6c53-7156-41a8-8d57-50b581422594.jpg)

**Comment by avelad** [comment]
Can you test with main branch? Thanks!
