### ISSUE TITLE
Edge - PlayReady Error

### ISSUE THREAD

**Issue by deisenbacher01** [shaka-project/shaka-player#3790]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://admvta.cdn.mgmlcdn.com/encvod/_definst_/smil:2021-09-29/vidqAR7dOgDsV.smil/manifest_mpm4sav_mvlist.mpd;license=https://playready.ezdrm.com/cency/preauth.aspx?pX=CF62DE;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v3.2.1-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edge/96.0.1054.41
Microsoft Edge
Version 96.0.1054.41 (Official build) (64-bit)

**What did you do?**
Tired to play the media

**What did you expect to happen?**
Should Play

**What actually happened?**
Shaka Error DRM.LICENSE_RESPONSE_REJECTED (Failed to execute 'update' on 'MediaKeySession': Rejected with system code (13))
This media plays in an older edge and IE so we know it is not a PlayReady DRM issue persay

**Comment by deisenbacher01** [comment]
it looks like the player is trying to go a GET and not a POST as it normally should.

**Comment by deisenbacher01** [comment]
New content as the older content is expired
https://6183afedc795e.streamlock.net/vod/mp4:sample.mp4/manifest.mpd
https://playready.ezdrm.com/cency/preauth.aspx?pX=250E0F

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
