### ISSUE TITLE
recoverable error fired when moving to offline - SegmentTimeline manifest 

### ISSUE THREAD

**Issue by yairans** [shaka-project/shaka-player#3794]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/livesim/segtimeline_1/utc_head/testpic_6s/Manifest.mpd;panel=ALL_CONTENT;panelData=LIVE;build=uncompiled

**What version of Shaka Player are you using?**
v3.2.1-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

**What did you do?**
Play the manifest, after a few seconds move to offline

**What did you expect to happen?**
A critical error

**What actually happened?**
A recoverable error

The issue occurs in SegmentTimeline manifest only, but in SegmentTemplate I get a critical error as expected - https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/livesim/utc_head/testpic_2s/Manifest.mpd;panel=ALL_CONTENT;panelData=LIVE;build=uncompiled

After some investigation I found: 
1. shaka forces the error to be recoverable here - https://github.com/google/shaka-player/blob/9c65b6dc431791851f64d1d95db3e6cc08efa510/lib/dash/dash_parser.js#L1231
2. The HTTP_ERROR (1002) error caught by the streaming engine here - https://github.com/google/shaka-player/blob/9c65b6dc431791851f64d1d95db3e6cc08efa510/lib/media/streaming_engine.js#L1290 but only when playing SegmentTemplate manifest, and not when playing SegmentTimeline manifest.

As a workaround, I force, in my player, the error severity to be critical for any HTTP_ERROR (1002) error. 
do you think is it enough, or I should do the same for other errors?

**Comment by TheModMaker** [comment]
The error should be recoverable since you can call `player.retryStreaming()` to continue once you're back online.  Both cases should be the same, so we'll look into why they're different.

**Comment by yairans** [comment]
thanks @TheModMaker, whats about the workaround of listening to HTTP_ERROR (1002) error, should be enough?

**Comment by yairans** [comment]
@joeyparrish can someone take a look at this issue please? thanks

**Comment by yairans** [comment]
@TheModMaker @joeyparrish any update?

**Comment by joeyparrish** [comment]
The behavior looks correct to me.  The error is considered recoverable because playback can continue once the internet connection is restored, and the default behavior for live streams is to retry indefinitely.  You can override that behavior if you wish, though.

Does this help explain?

**Comment by yairans** [comment]
@joeyparrish So why in SegmentTemplate I do get a critical error? 
how can I override that behavior? I've tried by `failureCallback` config, and it doesn't work, seems because the error is not caught at all, as I wrote in the ticket description.

**Comment by joeyparrish** [comment]
I'm not sure why different DASH manifests would produce different error severity for the same condition.  That doesn't sound right.

We don't have time to look into this right now, and it seems like a fairly minor issue.  Feel free to investigate yourself and send a PR with a fix or a follow-up comment with your findings.

**Comment by avelad** [comment]
Can you check if the error occurs in the latest versions? The logic has changed a lot since the issue was opened. Thank you!
