### ISSUE TITLE
CEA608 closed caption doesn't show up with FMP4+DASH as of Shaka player v3.2.1

### ISSUE THREAD

**Issue by liuyang5832** [shaka-project/shaka-player#3804]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.2.1

**Please ask your question**
I was testing Cea608 closed caption with Fragmented mp4+DASH playback and I found it doesn't show up, I found v3.0.14 can work but latest v3.2.1 doesn't work. The closed caption data is encoded as H264 SEI into video stream track.

**Comment by caridley** [comment]
This sounds like the same issues as https://github.com/google/shaka-player/issues/3782 which has been fixed in the master branch

**Comment by liuyang5832** [comment]
I debugged a little bit and think the issue seems relating to channel selection button on the player UI. Even though I clicked on closed caption display, by probing the code in run time I think the channel is actually not picked up to display somehow.

**Comment by avelad** [comment]
@liuyang5832 can you test with the latest realese (3.3.4 for example)?
