### ISSUE TITLE
Dash live playback lags when seeked on edge or goTOLive()

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#3817]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**

3.2.1
**Please ask your question**
I am trying to play dash live streams in the player

What I observed is when the live stream is ongoing and I click on a button or seek it to the live. Certainly, the playback stops, and after a few seconds or when I do play/pause, it forces playback on 3to4x speed to reach the live edge.

Can you please explain why does this happens and what player configuration settings we can do to handle this behavior.

thanks in advance.

**Comment by hiren3897** [comment]
hello @joeyparrish @TheModMaker can you please answer my question :p

**Comment by avelad** [comment]
@hiren3897 can you share a stream with which you see the error?

Since this sounds more like a bug, could you share the browser, system, etc (bug template)?

Thanks!

**Comment by hiren3897** [comment]
I have already created the bug issue here https://github.com/shaka-project/shaka-player/issues/3911 

For the stream, maybe you can share your mail ID so I can send you a URL to test
