### ISSUE TITLE
ShakaPlayer queries MediaCapabilities about parameters inconsistent with HLS manifest

### ISSUE THREAD

**Issue by jtrelak-vewd** [shaka-project/shaka-player#3818]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes
**What version of Shaka Player are you using?** 3.2.1
**Can you reproduce the issue with our latest release version?** Yes
**Can you reproduce the issue with the latest code from `master`?** Yes
**Are you using the demo app or your own custom app?** custom app
**If custom app, can you reproduce the issue using our demo app?** Yes
**What browser and OS are you using?**
Reproducible on our builds, as well as on Google Chrome, linux, 96.0.4664.45 (Official Build) (64-bit)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
This issue causes no playback on many embedded devices

**What are the manifest and license server URIs?**
I will send URIs to email.
Here you have example manifest (this one is generaged by USP, however we have examples generated with Shaka Packager - produce same effect, also will be sent to email):
```
#EXTM3U
#EXT-X-VERSION:1
## Created with Unified Streaming Platform (version=1.10.18-20255)

# variants
#EXT-X-STREAM-INF:BANDWIDTH=655000,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=960x540
h264_aac-lc-audio_eng=128001-video_eng=489000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1490000,CODECS="mp4a.40.2,avc1.77.31",RESOLUTION=1280x720
h264_aac-lc-audio_eng=128001-video_eng=1277000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2893000,CODECS="mp4a.40.2,avc1.100.40",RESOLUTION=1920x1080
h264_aac-lc-audio_eng=128001-video_eng=2601000.m3u8

# variants
#EXT-X-STREAM-INF:BANDWIDTH=136000,CODECS="mp4a.40.2"
h264_aac-lc-audio_eng=128001.m3u8
```

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
Load the stream
Check, what decodingConfig is given into mediaCapabilities.decodingInfo(decodingConfig)

**What did you expect to happen?**
Reliable values of:
- fps in case of video
- bitrate in case of audio

**What actually happened?**
The values in decodingConfig (listed below) are inconsistent with data in manifest. The problem is, that for many SmartTV devices decodingInfo returns result supported:false (huge bitrate for audio, and 1 fps for video are not acceptable), and then shakaPlayer does not start playback, but rise an error instead. There was no such issues in previous version of ShakaPlayer we used: 3.0.6, therefore we treat this behaviour as a regression.

In case of manifest I listed above, ShakaPlayer produces the following decodingConfig:
```
{
  "type": "media-source",
  "audio": {
    "contentType": "audio/mp4; codecs=\\"mp4a.40.2\\"",
    "channels": 2,
    "bitrate": 655000,
    "samplerate": 1,
    "spatialRendering": false
  },
  "video": {
    "contentType": "video/mp4; codecs=\\"avc1.42001e\\"",
    "width": 960,
    "height": 540,
    "bitrate": 655000,
    "framerate": 1
  }
```
logs:
```
Dropping variant - not compatible with platform type=video codecs=avc1.66.30,mp4a.40.2 bandwidth=undefined frameRate=undefined width=960 height=540    stream_utils.js:444
Dropping variant - not compatible with platform type=video codecs=avc1.77.31,mp4a.40.2 bandwidth=undefined frameRate=undefined width=1280 height=720    stream_utils.js:444
Dropping variant - not compatible with platform type=video codecs=avc1.100.40,mp4a.40.2 bandwidth=undefined frameRate=undefined width=1920 height=1080    stream_utils.js:444
```
Error message reads:
```
    "severity": 2,
    "category": 4,
    "code": 4032,
    "data": [],
    "handled": false,
    "message": "Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()",
```

**Comment by avelad** [comment]
@jtrelak-vewd can you test again with 4.3.5? Thanks!
