### ISSUE TITLE
getAudioLanguagesAndRoles() in ShakaPlayer returns more than 1 combination for 1 track with accessibility tag

### ISSUE THREAD

**Issue by SeverynLutskiv** [shaka-project/shaka-player#3820]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** - Yes

**What version of Shaka Player are you using?** - shaka-player@3.0.7

**What browser and OS are you using?** - MacOS, Chrome Version 96.0.4664.110

**What did you do?**
- Received a manifest with an audio tract that contains 'Accessibility' tag and 'Role' tag. Then I've used a getAudioLanguagesAndRoles() method from ShakaPlayer class.

**What did you expect to happen?**
 - I've expected to receive one object per each track, which describes it.

**What actually happened?**
 - I've received 2 objects containing the same 'language' value and different 'role' values, one of it is a value of 'Role' tag in the audio track, other one is a value of 'Accessibility' tag. 

We use it to display audio tracks in UI as a picker, but it returns us 2 objects for 1 audio track, which requires us to make some filtering after the getAudioLanguagesAndRoles() method invocation.

Does shaka player have another API for this?

**Comment by avelad** [comment]
Can you share your stream to see what's happening? I want to see how you declare Accessibility and Role tag to see what we are doing wrong. Thanks!
