### ISSUE TITLE
How to add differnt audio tracks, subtitles in the Shaka player?

### ISSUE THREAD

**Issue by TymofieievVolodymyr** [shaka-project/shaka-player#3823]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.1

**Please ask your question**

A question for understanding the general concept

When working with Shaka player and HLS or DASH protocols, I need to be able to switch audio tracks

For HLS we have .m3u8 playlist file, for DASH we have MPD file

It is a simple file that can be opened by notepad

And as I understand information about additional audiotracks, subtitles are contained in these files

In a player, we use a URL called manifest to these files

HLS https://5b44cf20b0388.streamlock.net:8443/vod/smil:hls-maudios-prod.smil/playlist.m3u8

DASH https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd

Shaka players consume this information and give a chance to enable captions or switch tracks.

**Are those files (MPD, m3u8  ) created only on the back-end side?**

**Or it is possible to form it on the client?** 

**Or there is another possibility to add different audio tracks and subtitles?**

**Comment by avelad** [comment]
Any adaptive protocol you use has to be generated on the backend side.

It is not possible to add external audio tracks, but it is possible to add subtitle tracks with `addTextTrackAsync` (see https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html )

Does this solve your doubts?
