### ISSUE TITLE
HLS stream video 'twitches' while loading on Samsung Smart TV

### ISSUE THREAD

**Issue by TavenCFC** [shaka-project/shaka-player#3826]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Y

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Y

**What version of Shaka Player are you using?**
3.2.1

**Please ask your question**
Hi. I have a problem playing HLS Live stream. 
While content is loading, I get a short chunk of the stream that plays several times.
Then playback works fine, but the loading process looks ugly.
I've tried several configurations. 
The problem can be reproduced with a standard configuration and this [link](https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8)
I'm also using the latest version of the mux.js.

Device: Tizen 6.0, model: UE43AU7100

Could you help me with this issue?

Thank you.

**Comment by joeyparrish** [comment]
I'm not sure I understand the issue.  Could you share a short video of this effect?
