### ISSUE TITLE
PeriodCombiner deduplicating image streams too aggressively

### ISSUE THREAD

**Issue by dvoracek-slub** [shaka-project/shaka-player#3844]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
No (there I get a TypeError, see [#3840](https://github.com/google/shaka-player/issues/3840#issuecomment-1009772295))

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Linux Mint 20.1, Firefox 95.0.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
–

**What are the manifest and license server URIs?**
https://raw.githubusercontent.com/dvoracek-slub/shaka-player-issue/main/image-stream-dedup/video.mpd

(full example: https://raw.githubusercontent.com/dvoracek-slub/shaka-player-issue/main/image-stream-dedup/index.html)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default

**What did you do? What did you expect to happen? What actually happened?**
Using a DASH manifest that lists four image streams, I tried to access all of them using `getImageTracks()`. Only one was returned.

```js
await player.load(
  "https://raw.githubusercontent.com/dvoracek-slub/shaka-player-issue/main/image-stream-dedup/video.mpd"
);

const imageTracks = player.getImageTracks();

// Expected: 4
// Actual: 1
console.log(imageTracks.length);
```

**Notes**
The issue is that too many image streams are dropped in `PeriodCombiner::filterOutImageStreamDuplicates_`.

My use-cases for having multiple image streams are:
- Provide thumbnails in multiple resolutions. However, the total width/height of the grid may be the same (e.g., 10x10 with 80x45 images, and 5x5 with 160x90 images).
- Provide thumbnails for multiple video tracks. (I'm offering multiple video tracks by filtering the variants available to the player.)

The most robust solution would probably be to also check the media URLs if that's possible, though it may suffice to just add checks for bandwidth, height, tilesLayout, and the label (after providing that via `imageStreamToTrack`).

**Comment by avelad** [comment]
@joeyparrish / @theodab do we want to implement this?
