### ISSUE TITLE
Shakaplayer Issue with React 17.0.2 

### ISSUE THREAD

**Issue by sannjayy** [shaka-project/shaka-player#3848]
WARNING in ./node_modules/shaka-player/dist/controls.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/shaka-player/dist/controls.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Sanjay\Desktop\code test\react-video-player\node_modules\shaka-player\ui\https:\fonts.googleapis.com\icon?family=Material+Icons+Round' file: Error: ENOENT: no such file or directory, open 'C:\Users\Sanjay\Desktop\code test\react-video-player\node_modules\shaka-player\ui\https:\fonts.googleapis.com\icon?family=Material+Icons+Round'  
 @ ./node_modules/shaka-player/dist/controls.css 8:6-235 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-205 83:0-205 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ./src/App.js 7:0-40
 @ ./src/index.js 7:0-24 11:33-36

3 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.65.0 compiled with 3 warnings in 1517 m

**Comment by MadMods96** [comment]
Respected sir/Madam,

I am Madhusudan Pareek , a computer science undergraduate , I have just entered to my 4th semester at TC College affiliated with Savitri Bai Phule Pune University. I am new to open source but I am well aware of JavaScript , Nodejs, PostgreSQL, MySQL, HTML,CSS, bootstrap, React and also good knowledge of making rest api’s. I would love to contribute to your organization  and want to work on this issue.. Currently I had worked with an organization ‘IBKAAS’ as an intern and developed their backend with NodeJS ( express )and PostgreSQL and now I’m looking for open source..

Hoping to hear from you soon.

Regards

Madhusudan

**Comment by jonyahmed19** [comment]
I am facing same issue here.

**Comment by gautamkhatter** [comment]
Were you able to solve this issue with the shaka player in React?

**Comment by avelad** [comment]
We don't officially support React, but people have contributed here: https://github.com/shaka-project/shaka-player#framework-integrations

Does this help you?
