### ISSUE TITLE
Support for DASH-IF section 4.6. Provisioning of Live Content in On-Demand Mode

### ISSUE THREAD

**Issue by tafinho** [shaka-project/shaka-player#3854]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**Is your feature request related to a problem? Please describe.**
When bridging the gap between live and on-demand content based on that live content, seamlessly, there's the need to maintain SAST. As per DASH-IF section 4.6. that can be achieved by setting period@start set as the content's start time. This causes Shaka to freeze, as it cannot recognise period@start for static manifests.

**Describe the solution you'd like**
Support for DASH-IF section  4.6. , by supporting period@start on static manifests.

**Describe alternatives you've considered**

There are none. This is the recommended DASH-IF implementation.

**Additional context**
I can share reference content and workflow through email.

**Comment by avelad** [comment]
@tafinho are you interested on send a PR to implement it? Thanks!
