### ISSUE TITLE
(New) problem with the cookie auth step and the asynchronous credentials step in the tutorial

### ISSUE THREAD

**Issue by sinewave440hz** [shaka-project/shaka-player#3859]
(May I suggest adding a "tutorial" tag, as the old issue template mentioned the tutorial, which means that all old issues turn up when searching for "tutorial" issues...?)

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes
**What version of Shaka Player are you using?**
3.3.0
**Can you reproduce the issue with our latest release version?**
Yes!
**Can you reproduce the issue with the latest code from `master`?**
Haven't actually tried
**Are you using the demo app or your own custom app?**
Following the tutorial
**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome latest

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

From the license server auth tutorial page:
'https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd';
'https://cwip-shaka-proxy.appspot.com/cookie_auth';
and
'https://cwip-shaka-proxy.appspot.com/header_auth';

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

From the tutorial page:

`  player.configure({
    drm: {
      servers: { 'com.widevine.alpha': licenseServer }
    }
  });`

**What did you do?**
Followed the steps for trying out cookie auth, but still received 6007. Read through #3192 and set chrome to accept 3rd party cookies, no change.

For the asychronous credentials step, I followed the steps but received no response from the server in the auth request.

**What did you expect to happen?**

I expected the cookie auth tutorial step to work as described and play correctly. Same with the asynchronous credentials step.

**What actually happened?**

As I mentioned I still received 6007 when attempting to use the cookie auth step. For the asynchronous credentials step, I never received a response from the auth request.

**Comment by avelad** [comment]
I'm sorry it took so long to reply, were you able to resolve the problem?
