### ISSUE TITLE
Main video is not played after the Ad. 

### ISSUE THREAD

**Issue by ysadigurs** [shaka-project/shaka-player#3865]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
(https://shaka-player-demo.appspot.com/) online

**Please ask your question**
[ad4_xml.mpd.txt](https://github.com/google/shaka-player/files/7882915/ad4_xml.mpd.txt)
Player stops playback after the Ad without playing the main video.

**Comment by avelad** [comment]
@ysadigurs Since this sounds more like a bug, could you fill in the bug template and share it with us? 

In order to reproduce the error we will need a test stream.

Thanks!
