### ISSUE TITLE
Main video starts playing only several minutes after the Ad

### ISSUE THREAD

**Issue by ysadigurs** [shaka-project/shaka-player#3866]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
Not related to Shake Player, but a general MPD question

**Please ask your question**
Please advise what could be the issue in the attached MPD causing the Player to start the main video only 5-10 minutes after the ad.
[TVE001838863.txt](https://github.com/google/shaka-player/files/7883791/TVE001838863.txt)

**Comment by avelad** [comment]
This more than a question sounds like a bug, can you fill in the bug template and share the stream data to be able to do a deeper analysis? Thanks!
