### ISSUE TITLE
Time between fetching DRM certificate till drmsessionupdate is fired, is much longer on chrome than safari

### ISSUE THREAD

**Issue by amansieboatengkofi** [shaka-project/shaka-player#3872]
Have you read the FAQ and checked for duplicate open issues?

Yes
What version of Shaka Player are you using?
3.1.0

Can you reproduce the issue with our latest release version?
Yes

Can you reproduce the issue with the latest code from master?
Yes

Are you using the demo app or your own custom app?
the demo app

If custom app, can you reproduce the issue using our demo app?

What browser and OS are you using?
Chrome Version 97.0.4692.7 Mac OS

For embedded devices (smart TVs, etc.), what model and firmware version are you using?
N/A

What are the manifest and license server URIs?

What configuration are you using? What is the output of player.getConfiguration()?
abr:
       bandwidthDowngradeTarget: 0.95
       bandwidthUpgradeTarget: 0.85
       defaultBandwidthEstimate: 1000000
       enabled: true
       restrictions: {minWidth: 0, maxWidth: Infinity, minHeight: 0, maxHeight: Infinity, minPixels: 0, …}
       switchInterval: 8
       useNetworkInformation: true
manifest:
    availabilityWindowOverride: NaN
    dash: {clockSyncUri: '', ignoreDrmInfo: false, xlinkFailGracefully: false, ignoreMinBufferTime: false, autoCorrectDrift: true, …}
    defaultPresentationDelay: 0
    disableAudio: false
    disableText: false
    disableVideo: false
    hls: {ignoreTextStreamFailures: false, useFullSegmentsForStartTime: true}
    retryParameters: {maxAttempts: 2, baseDelay: 1000, backoffFactor: 2, fuzzFactor: 0.5, timeout: 30000}

drm:
      advanced: {com.widevine.alpha: {…}}
      clearKeys: {}
      delayLicenseRequestUntilPlayed: false
      initDataTransform: ƒ Zd(a,b,c)
      logLicenseExchange: false
      retryParameters: {maxAttempts: 2, baseDelay: 1000, backoffFactor: 2, fuzzFactor: 0.5, timeout: 30000}
      servers:
          com.widevine.alpha: "<redacted>"
      updateExpirationTime: 1

streaming:
       alwaysStreamText: false
       autoLowLatencyMode: false
       bufferBehind: 30
       bufferingGoal: 10
       durationBackoff: 1
       failureCallback: ƒ (c)
       forceHTTPS: false
       forceTransmuxTS: false
       ignoreTextStreamFailures: false
       inaccurateManifestTolerance: 2
       jumpLargeGaps: false
       lowLatencyMode: false
       preferNativeHls: false
       rebufferingGoal: 2
       retryParameters: {maxAttempts: 2, baseDelay: 1000, backoffFactor: 2, fuzzFactor: 0.5, timeout: 30000}
       safeSeekOffset: 5
       smallGapLimit: 0.5
       stallEnabled: true
       stallSkip: 0.1
       stallThreshold: 1
       startAtSegmentBoundary: false
       useNativeHlsOnSafari: true

What did you do?

We measured the time it takes in our drm flow. Let's call this time DRM_TIME_TO_INITIALIZE. It is measured from the time we make the certificate call , till drmsessionupdate is fired (signaling that encrypted content can now be played). 

We noticed that on chrome (widevine) DRM_TIME_TO_INITIALIZE is around 1.8 s, while on safari (fairplay) DRM_TIME_TO_INITIALIZE is around 0.9s.

The entire certificate call fetch happens in 0.3 s, and the entire license call fetch happens in 0.1 seconds.

We are wondering why on chrome DRM_TIME_TO_INITIALIZE is much higher than that of safari.
We are also looking for ideas on how to bring down DRM_TIME_TO_INITIALIZE on chrome.
What  processing is happening in shaka player while installing the license or generating a challenge?

What did you expect to happen?
We were expecting similar times for DRM_TIME_TO_INITIALIZE for fairplay and widevine.
We are wondering why on chrome DRM_TIME_TO_INITIALIZE is much higher than that of safari.
We are also looking for ideas on how to bring down DRM_TIME_TO_INITIALIZE on chrome.
What  processing is happening in shaka player while installing the license or generating a challenge?

**Comment by joeyparrish** [comment]
A few follow-up questions:

Are you setting a service certificate for Widevine through Shaka's DRM config?  If not, Widevine will make an extra license request and round-trip to get one from the server.

When you say "The entire certificate call fetch happens in 0.3 s, and the entire license call fetch happens in 0.1 seconds", are you referring to Widevine or Safari or both?  Are these the times for the network requests alone?
