### ISSUE TITLE
how to change player adaption manually

### ISSUE THREAD

**Issue by nargesghahremani** [shaka-project/shaka-player#3879]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.1.6
hi, In auto quality mode, the player always loads videos in 360p and 480p,While the bandwidth is high and can load video in 720p quality even 1080p properly!!
i can't find the solution,
how can set the quality configs manually?or is there a solution for this issue?
thanks in advance

**Comment by avelad** [comment]
@nargesghahremani What browser are you using? is it a DASH or HLS stream?
If you are using HLS in Safari, it is not possible to set the quality as the video element does.
If you are using other settings, see https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html and to select quality manually you should use `selectVariantTrack` function
