### ISSUE TITLE
Can't play the content in 3.3.0 but dashif 4.3.0 works

### ISSUE THREAD

**Issue by RalfHsiao** [shaka-project/shaka-player#3882]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

I find the similar issues (https://github.com/google/shaka-player/issues/3045 & https://github.com/google/shaka-player/issues/3139).

The #3045 is only audio warning but I get video and audio warning at the same time. 
In #3045 discussion, the issue's  root cause is the same as #3139. 
Based on #3139's discussion, it seem to be fixed in `3.1.0`.

It still happened in `3.3.0`

By the way, dashif (`4.3.0`) can play with this sources.

**What version of Shaka Player are you using?**

3.3.0

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `master`?**

No try

**Are you using the demo app or your own custom app?**

[demo app](https://shaka-player-demo.appspot.com/demo/#audiolang=zh-TW;textlang=zh-TW;uilang=zh-TW;asset=https://bitmovin-a.akamaihd.net/content/sintel/sintel.mpd;panel=CUSTOM%20CONTENT;build=uncompiled
)

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

I try testing two devices and both of them happened.

Browser: Chrome 96.0.4664.110
OS: MacOS 11.5.2

Browser: Chrome 97.0.4692.71
OS: MacOS 10.15.7

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

source from Bitmovin
https://bitmovin-a.akamaihd.net/content/sintel/sintel.mpd

No license

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Use online demo app.

**What did you do?**

Open the demo app link and play the content.

**What did you expect to happen?**

The source could be played well.

**What actually happened?**

Keep buffering.

The console show the uninterrupted warnings:
`(audio:1) cannot find segment lookupTime: 885 presentationTime: 887` 
`(video:15) cannot find segment lookupTime: 885 presentationTime: 887`

![image](https://user-images.githubusercontent.com/8230869/150251136-ead2d5d3-74b0-4a0e-9546-4ba87874f3a4.png)

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
