### ISSUE TITLE
sessionType = persistent-license is not considered

### ISSUE THREAD

**Issue by stefano24** [shaka-project/shaka-player#3885]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
mac os, chrome

**What are the manifest and license server URIs?**
A manifest /manifest(format=mpd-time-csf,encryption=cenc) 
with its license server

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
player.configure({
      drm: {
        preferredKeySystems: ['com.widevine.alpha'],
        servers: { 'com.widevine.alpha': this.licenseServer },
        advanced: {
          'com.widevine.alpha': {
            persistentStateRequired: true,
            sessionType: 'persistent-license'
          }
        }
      }
    });

**What did you do?**
Simply load the configuration and play the video.

**What did you expect to happen?**
That only on first time (first load) the license call is done, but then i expect that cdm not make again the license request. And that the same session is used.

**What actually happened?**
The server license call works, but the license is never stored and on refresh page the license request is always done.

**Comment by avelad** [comment]
The use case is not supported yet. See https://github.com/google/shaka-player/issues/1956

**Comment by stefano24** [comment]
Ok, and when is supported the license storage? Also on storage offline context is not working. Above a config:
player.configure({
      drm: {
        logLicenseExchange: true,
        preferredKeySystems: ['com.widevine.alpha'],
        servers: { 'com.widevine.alpha': this.licenseServer },
        advanced: {
          'com.widevine.alpha': {
            persistentStateRequired: true,
            sessionType: 'persistent-license'
          }
        }
      },
      offline: {
        usePersistentLicense: true
      }
    });

const storage = new shaka.offline.Storage(player);
    storage.store(this.manifestUrl).then((res) => {
      player
        .load(res.offlineUri)
        .then((response) => {
          // This runs if the asynchronous load is successful.
          console.log('The video has now been loaded!');
        })
        .catch(this.onError); // onError is executed if the asynchronous load fails.
    });

**Comment by avelad** [comment]
See: https://github.com/google/shaka-player/pull/3301
