### ISSUE TITLE
Shaka Player Webos loss of performance to a standstill

### ISSUE THREAD

**Issue by pedrosilvabos** [shaka-project/shaka-player#3890]
Have you read the Tutorials?
YES

Have you read the FAQ and checked for duplicate open issues?
YES

What version of Shaka Player are you using?
3.0.10

I have shaka working for Tizen and webos environents, with the same code.

The test team has a stress test that will open a stream let it play for 10 minutes, turn it off for 3 minutes and then play it again for another 10 minutes, this for at lest 50 cycles.

It is good to understand that when the turn off the stream, shaka player is infact destroyed and they go to a Full Info Page inside the app.

Tizen has no problem, and could play and stop all day.
Webos (all versions) after around 29 cycles will start to downgrade the bitrate (and will not pickup after) and increase the buffering, and around 10 cycles later it will simply not play, and produce eternal buffering.

This is does not happen on chrome either.

Using monitoring tools for webos and checking memory and network usage, there really isn't anything happening, all values look good both memory and cpu. 

I read that shaka does not keep buffering.
Does anyone have any idea what could be causing this?
I can provide the manifest, but since it is attached to a DRM please let me know ahead so I can provide fresh links.

Thank you in adavance!

**Comment by avelad** [comment]
Hi @pedrosilvabos. In version 4.0 we have resolved https://github.com/shaka-project/shaka-player/issues/4062 Can you try again with this version? Thanks!
