### ISSUE TITLE
A fragmented dash timeline using shaka-player

### ISSUE THREAD

**Issue by cpoutros** [shaka-project/shaka-player#3891]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0

**Please ask your question**
Hello,

I have a collection of dash packaged mp4 video files of varying time length. These video files can be anywhere from 30 seconds to 5 minute duration and each with its own mpd; the collection of files spawns one day period.  Can shaka-player be used to display one time line bar of 24 hour period but with gaps or chapters in it (much like youtube has on some timelines)? The goal is for the user to easily see what time segments during the 24 hour period there is video content available for playback. 

I started by manually creating one large mpd file by adding all the periods in and adjusting period id, start and duration.  This works if there are no gaps. Also, I don't know if there a way to control the timeline bar color to display gabs or periods where there isn't video.  

Looking forward to hearing some suggestions on how to accomplish such feature. 

Thank you

**Comment by joeyparrish** [comment]
I don't think this is something Shaka Player can do today, but there are some ideas out there that might get you closer.

We have had a low-priority feature request open for some time now (https://github.com/shaka-project/shaka-player/issues/764) to allow an app to append VOD clips together in the client.  It sounds like this would cover everything except the timeline UI, but nobody is working on this right now.  If you're interested, you could comment on that issue and start a PR.

As for the UI, the closest thing we have now is ad markers.  For ad-supported content, we mark the timeline to show where the ads are located.  You could do something similar for your various content regions, based on the ad marker support we already have.  (This would involve modifying or customizing our UI in some way.)

Does this help?
