### ISSUE TITLE
Questions about chapters API

### ISSUE THREAD

**Issue by hochhaus** [shaka-project/shaka-player#3895]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.3.0

**Please ask your question**
I'm experimenting with the chapters API referencing the code, tests and comments (https://github.com/google/shaka-player/issues/3538#issuecomment-895111300). Could you clarify my understanding of the following items?

  1. Why is the chapterURL provided via `player.addChaptersTrack()` instead of being included in the manifest? This isn't the end of the world but it seems unintuitive to me.
  2. Why does the `addChaptersTrack()` promise resolve before the chapters file has been downloaded and parsed by the browser? This seems to unnecessarily increase the complexity of correctly using chapters.
  3. Why does `shaka.extern.Chapter` not include the cue identifier (`shaka.extern.Cue.id`)? The calling code can pull this information directly out of the cue but it seems to unnecessarily complicate certain use cases.

**Comment by hochhaus** [comment]
> Why does the addChaptersTrack() promise resolve before the chapters file has been downloaded and parsed by the browser? This seems to unnecessarily increase the complexity of correctly using chapters.

To add a bit more context here, when shaka downloads a captions VTT file it appears to do so from a JS `fetch()`. However, when shaka downloads a chapters VTT file it appears to do so by appending a `<track>` element to the DOM. Possibly this is necessary for some reason. However, if it is not, possibly the API could be cleaned up by directly `fetch()`ing the chapters VTT as well?

**Comment by avelad** [comment]
Hi @hochhaus 

1. We would be happy to support it directly in HLS and DASH, but as far as I know it is not specified how they should be included, if you have the information, please open an enhancement issue so we can do it in the future.
2. This sounds like a bug, please open a bug and we'll fix it.
3. I think it can be easily fixed.

**Comment by hochhaus** [comment]
Thanks @avelad. I opened dedicated issues per your comments so I will close this issue.

**Comment by hochhaus** [comment]
> We would be happy to support it directly in HLS and DASH, but as far as I know it is not specified how they should be included, if you have the information, please open an enhancement issue so we can do it in the future.

I also am not able to find this documented and the current implementation is not problematic. Should I find HLS / DASH documentation in the future I will open a dedicated issue.
