### ISSUE TITLE
Duplicate player UI in a programatic setup

### ISSUE THREAD

**Issue by FireMasterK** [shaka-project/shaka-player#3896]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Not sure

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Brave on Linux

**What are the manifest and license server URIs?**
N/A - all

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
This shouldn't be affected by it.

**What did you do?**
Load shaka-player through an `import()` statement

**What did you expect to happen?**
Not have 2 UIs when using a programmatic setup.

**What actually happened?**
There are 2 sets of controls visible when seeking - also seen in https://github.com/TeamPiped/Piped/issues/755
This can be fixed/worked around by removing all div elements inside shaka's container like so: `this.$refs.container.querySelectorAll("div").forEach(node => node.remove());`
The bug is visible on https://7ff4d18c.piped.pages.dev/watch?v=zs9QpPKDw74

I feel that the reason this is happening is that shaka is being loaded when a video element is already present in the document, thus causing issues when initializing the UI again.

**Comment by joeyparrish** [comment]
@FireMasterK, we need more information.  Are you setting the `controls` attribute on the `<video>` element?  Are you using the `data-shaka-player` attributes and auto-setup, or are you creating `shaka.ui.Overlay` explicitly, or both?

Can you share the parts of your application that load Shaka and interact with the UI?
