### ISSUE TITLE
Crash: Shaka Player category: 2 code: 2007 "MP4 segment does not contain TTML"

### ISSUE THREAD

**Issue by ghost** [shaka-project/shaka-player#3908]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

3.0.13 (using CAF 3.0.0102)
3.0.10 (using CAF 3.0.0096)

**Can you reproduce the issue with our latest release version?**

Have to use CAF

**Can you reproduce the issue with the latest code from `master`?**

Have to use CAF

**Are you using the demo app or your own custom app?**

Own app

**If custom app, can you reproduce the issue using our demo app?**

Go to  

https://shaka-player-[demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://c[…]504bde94bf2;panel=CUSTOM%20CONTENT;build=uncompiled
](https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://csm-e-tv2dkdash-eb.tls1.yospace.com/csm/extlive/tv2dkdev01,vod2live_50_fps.mpd?yo.ac=false&ss_req=1&yo.d.mc=true&yo.pbr=true&ppid=c982e23f9cef4ad19b81a504bde94bf2;panel=CUSTOM%20CONTENT;build=uncompiled)

Enable danish subtitles/captions and watch the error when the ads are being shown:

<img width="750" alt="Screenshot 2022-01-27 at 13 19 20" src="https://user-images.githubusercontent.com/53769763/151357965-65d09b23-8ee7-4972-b997-bd35e4647712.png">

**What browser and OS are you using?**

Google Chrome Cast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

Google Chrome Cast gen 3

**What are the manifest and license server URIs?**

🤷‍♂️ - will have to get back to you on that if this is critical information?

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

🤷‍♂️ - will have to get back to you on that if this is critical information?

**What did you do?**

Started Google Chrome Cast with on a stream with linear ads replacement (LAR) and enabled subtitles.

When it reaches the ads it crash the player and I find the following in the console:

<img width="1266" alt="Screenshot 2022-01-26 at 11 27 05" src="https://user-images.githubusercontent.com/53769763/151171586-91ae6ab9-63d3-403a-a1bf-382cc091a977.png">

Googling hints me to that it’s because the LAR does not have subtitles (TTML).

<img width="713" alt="Screenshot 2022-01-26 at 11 30 17" src="https://user-images.githubusercontent.com/53769763/151171650-17c31fac-0add-4e2c-bf32-468afaad2aa2.png">

**What did you expect to happen?**

ignore that the ads does not contain subtitle files

**What actually happened?**

please see "What did you do?" section

**Comment by NorfeldtAbtion** [comment]
I updated the initial comment with demo player options

**Comment by avelad** [comment]
The video has several periods, if I'm not mistaken there are some with stpp and others with vtt. 
I think that it's related to https://github.com/google/shaka-player/issues/2237

**Comment by NorfeldtAbtion** [comment]
@mimse I noticed you are active in #2237 - do you also think it's related?

**Comment by avelad** [comment]
@NorfeldtAbtion I have seen that with the published stream it does not happen, can you share a stream with which to reproduce the problem?

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
