### ISSUE TITLE
Changes in Shaka

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#3909]
Hi everyone,

I want to share with you some changes that are coming to the Shaka family of projects.  This will be cross-posted to shaka-player-users, shaka-packager-users, and the GitHub Issues pages of all of our projects.

### Shaka is moving within Google

After 7.5 years of Shaka under Chrome/Widevine, the Shaka projects are moving.  The Cast team, who has been a primary user of Shaka Player within Google, will be taking over ownership of Shaka from Chrome/Widevine.  We look forward to a closer relationship with Cast!

### Seeking volunteer maintainers

We are now offering members of the Shaka community an opportunity to share in maintenance responsibilities, such as responding to issues, reviewing and merging PRs, and making releases.  We think this is long overdue, and will help all Shaka projects move forward more quickly.

If you would like to volunteer as a maintainer for one or more of the Shaka projects, please email me privately at joeyparrish@google.com.

### Infrastructure is moving to GitHub Actions

We are rewriting our internal tools and processes to make them more publicly accessible.  Having Google-only tools (and even some Google-only tests) has become a barrier for contributors and has slowed down our release timelines.  

We are migrating all testing, release, and deployment infrastructure to GitHub Actions, and improving access as much as possible.  All contributors will be able to run the same tests and get faster feedback, and all maintainers will be equally able to create releases and deploy demos and docs.

We will also start sending our own contributions through the public PR process, rather than using a private code review process for Googlers.

### Questions?

If you have any questions about these changes, please don't hesitate to ask!  You can email me privately at joeyparrish@google.com or ask publicly via the GitHub Issues pages for any of our projects.

https://github.com/google/shaka-packager
https://github.com/google/shaka-player
https://github.com/google/shaka-player-embedded
https://github.com/google/shaka-streamer

Joey, on behalf of the Shaka Team

**Comment by matvp91** [comment]
Hey Joey & the Shaka Team,

Glad to see you're moving towards a more community driven approach, I bet this will definitely benefit Shaka in the long run.

I do have a question regarding the items and prioritization of the roadmap. With CAF being an internal Google project and Cast taking ownership, will the roadmap mainly be prioritized according to the needs of CAF?

Best regards,
Mat

**Comment by joeyparrish** [comment]
With Cast taking ownership, the team at Google will be focusing our time on the priorities of CAF.

My current priority for all of our projects is test and release automation, publicly accessible infrastructure through GitHub Actions, selecting non-Googler maintainers, and documenting processes for those maintainers.  This is for the health of the projects and their communities, so that everyone can contribute more easily, so that we have a larger pool of reviewers and approvers for contributions, and so that every contributor can see their own needs and priorities met without Google being a bottleneck any longer.

(As a side-note, I just posted https://github.com/google/shaka-player/issues/3925 to gather feedback about our release strategy.  Let us know what you think, as this will influence the public maintenance processes and tools we're building.)

So right now, those are my top priorities, beyond any feature or fix.  Once these things are settled, we'll be turning our attention back toward features and bug fixes.

**Comment by avelad** [comment]
What are CAF's priorities going to be?

**Comment by joeyparrish** [comment]
Right now our top priorities are to close the feature gaps between CAF's current HLS player (closed source) and Shaka Player, so that Shaka can take over HLS playback in CAF.  So lots of HLS work in the next couple of quarters.
