### ISSUE TITLE
Dash and HLS live stream (with 3hours DVR mode) lags in player

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#3911]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
No.

**What version of Shaka Player are you using?**
3.2.1

**Can you reproduce the issue with our latest release version?**
No.

**Can you reproduce the issue with the latest code from `master`?**
Dependent on npm. 

**Are you using the demo app or your own custom app?**
Own custom app with overlay layout from shaka

**If custom app, can you reproduce the issue using our demo app?**
--

**What browser and OS are you using?**
We are targeting
Browsers: Chrome, Edge, Firefox, Safari, Chromium
OS: Windows, Linux, iOS, macOS, iPadOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
No 

**What are the manifest and license server URIs?**

I am going to send you a demo URL of my application with a secured password and mail where you will be able to test the player with the debug logs in the console and also the manifest URLs will be displayed while playing the content. 

Please this URLS and player are confidential so keep it as secure as possible.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

You will see the player.getConfiguration() On platform
You will see the player.getAssetUri() On platform
You will see the player.drmInfo() On platform

**What did you do?**

I tried to load the Dash live stream manifest on the player with the defaults configuration of the shaka-player but it lags many times while performing the playback. also, we tried to play with the parameters like `bufferingGoals`, `rebuffering Goal` but it was creating more latency and not giving an appropriate playback.

When we try to downscale the bandwidth of the internet using Network throttling to fast 3G or slow 3G we have a large latency gap and the player lags a lot.

Secondly and the main issue we are facing is when we put the shaka-player on the production it was causing a lot of load on our CDN servers since we put that on the production of our client and this is only because of playing the live content on the shaka-player.

**What did you expect to happen?**
We what a smooth behavior of our live content to be played on the edge with as low latency as possible
We would also happy to see if our DASH manifest and HLS playlist are coded correctly is coded perfectly to provide a smooth playback

**What actually happened?**

Since we started using the shaka-player to play our live content it was causing many lags on the live edge of the player.
it was always staying > -4 seconds back from the live and even more as it keeps lagging.
Also sometimes in between the good performing player, it gets stuck and after 1-2 mins or a few seconds, it goes very fast to reach the content left over to reach the live back and then normalize.

I think there is something we are missing in our manifest or in the shaka-player that is not able to give the playback of our dash or hls manifest/playlist contents.

[NOTE]
When you load the URL provided in the mail on mac or in chrome it will automatically play the supported contents.

**Comment by hiren3897** [comment]
Hello @joeyparrish did you have time to see my email? for this bug report?

**Comment by hiren3897** [comment]
Hello, Did you have time to check my email regarding this bug, can you please respond to it.

Thanks.

**Comment by TavenCFC** [comment]
Hello. I'm not sure if this is the same issue, but I'm getting some lag while the hls live stream is loading. It looks like 1 short video clip is played multiple times. The problem is on Samsung Smart TV. I posted the issue here #3826 but didn't get a response.

**Comment by hiren3897** [comment]
Hello, @joeyparrish can we have a look at this bug issue? I have sent a mail with all the manifest URLs for testings but I have not yet received any response can I have a status about it, please.

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!

**Comment by hiren3897** [comment]
Yes, I will test at let you know by the end of the day

Thanks for you work
