### ISSUE TITLE
Native iOS 15 player for Safari with fairplay in web app version

### ISSUE THREAD

**Issue by ilgianfra** [shaka-project/shaka-player#3918]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes
**What version of Shaka Player are you using?**
3.1.2
**Can you reproduce the issue with our latest release version?**
Last version got problem with safari and fairplay #3598

**What browser and OS are you using?**
Safari IOS 15 (iPhone) with fairplay

**What did you expect to happen?**
According to this https://github.com/google/shaka-player/issues/3565 I should be able to remove controls from native player in safari. We are using fairplay and as the doc says we got a native player in full screen (which is fine) but we would like to put our custom controls, is that possible?

**Comment by avelad** [comment]
Yes, it is possible to use custom controls with Fairplay, but only when not playing fullscreen on iOS. In iOS, the Fullscreen API is not enabled, so the native controls would be shown in Fullscreen.
