### ISSUE TITLE
Start live stream at preferred Resolution/Variant.

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#3919]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.2.1

**Please ask your question**
I am working on the two following tasks mentioned below.

1) Manage player resolution up to 720p on startup for the live stream
Answer: Is doable by ABR configuration from restrictions by setting `maxBandwidth`

2) start the live stream at 144p then upscale (if the bandwidth permits it) up to 720p maximum.
Is there any way to start the live stream at the lowest variant? by using config or manually doing it after the player is loaded?

My questions:
  - Is there any way to start the live stream at the lowest variant? by using config or manually doing it after the player is loaded?
  - is there any way to detect the device max supported bandwidth from shaka-player?
  - can we auto upscale it using ABR up to the supportable bandwidth of the client?

Can you give me a perfect explanation of what these properties do?
```
bandwidthDowngradeTarget: 0.85,
bandwidthUpgradeTarget: 0.15,
switchInterval: 5
```
Thanks

**Comment by martinstark** [comment]
> Is there any way to start the live stream at the lowest variant? by using config or manually doing it after the player is loaded?

You can configure `abr.defaultBandwidthEstimate` to give shaka a starting point for its bandwidth estimate. If you set it sufficiently low it should cause shaka to start at the lowest bandwidth.

> is there any way to detect the device max supported bandwidth from shaka-player?
Not that I'm aware. Shaka builds an internal bandwidth estimate for a playback session, which it uses to upgrade or downgrade tracks according to the sensitivity configured in the abr configuration. You can also override the AbrManager yourself for complete control of variant track selection.

> Can you give me a perfect explanation of what these properties do?

https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.AbrConfiguration

**Comment by avelad** [comment]
@hiren3897 With the previous comment have all your doubts been resolved?

**Comment by hiren3897** [comment]
Hello, yes it answers my question :) thanks
