### ISSUE TITLE
the video with drm appears on the black screen.

### ISSUE THREAD

**Issue by baehongjun0212** [shaka-project/shaka-player#3923]
Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
yes

What version of Shaka Player are you using?
3.0

Can you reproduce the issue with our latest release version?
yes

Can you reproduce the issue with the latest code from master?
yes

Are you using the demo app or your own custom app?
yes

If custom app, can you reproduce the issue using our demo app?
/

What browser and OS are you using?
Mac OS

Using the drawimage() method, the screen of the video is being drawn on the canvas.
However, the video with drm appears on the black screen.
I looked it up to solve it, and they said it was because of the **drm policy.**

Is there any way to solve this problem?

**Comment by avelad** [comment]
Due to the security policy applied by DRM, it is not possible to view a video with DRM on a canvas. So it is not possible to do what you need.

This is a non-ShakaPlayer issue, we can give you support, but it is a limitation of the browser-drm conjunction.
