### ISSUE TITLE
Shaka Player Release Process Survey

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#3925]
Please take a moment to give us some feedback on our release process.  One representative response per company, please.

https://forms.gle/phUUVPSo5CgpPNgB8

**Comment by avelad** [comment]
@joeyparrish Are there any results of the survey that can be shared here?

**Comment by joeyparrish** [comment]
It was an even split.  8 for change, 8 against change.

![image](https://user-images.githubusercontent.com/6843156/157521724-458cce0f-2f1a-42d2-8d05-ee3baa2966ca.png)

For now, we will keep the existing system, and re-evaluate in the future.

Thanks, everyone, for your feedback!
