### ISSUE TITLE
MPD Chaining support in Dash 

### ISSUE THREAD

**Issue by Gheri** [shaka-project/shaka-player#3926]
SO/IEC 23009-1:2014/ Amdendent 4 added definition for MPD Chaining. Chaining adds a new supplemental property to a manifest, instructing the player to load a new manifest once playback is complete. It is designed to allow simplified ad insertion capabilities, especially placing static ads as pre-rolls to live streams, which are otherwise complicated to achieve with multi-period manifests. It also allows for simplified player development, as manifests only ever contain a single period.

The DASH IF has created two test vectors which can be used for development

http://testassets.dashif.org/#feature/details/588a48c27459f8cb201b881b

**Comment by joeyparrish** [comment]
Great idea!  Let us know if you'd like to start working on this.

**Comment by joeyparrish** [comment]
In case it's helpful:

You can wait for a video's "end" event and call `player.load()` again.  If you want to implement chaining support in the player, that's effectively what you'd do with the supplemental property in the DASH manifest.

**Comment by Gheri** [comment]
Thanks Joey. I would try to work on this and if required I would ask you
any questions I might have.
Thanks for suggestions

**Comment by Gheri** [comment]
Hey Joey,
Any pointers as to where I can start If I have to implement the XLink
onRequest Feature in Shaka Player ??
Like If you have any design on top of the mind on how to start with.
Any Major Challenges that we could not implement on Request but only
implement on Load.
Dash Server Guided Ad Insertion Support - Patch Manifests & XLinks for VOD
· Issue #3238 · shaka-project/shaka-player (github.com)
<https://github.com/shaka-project/shaka-player/issues/3238>

I Think MPD Chaining or XLInk on Request is now the need for scalability

Thanks,
Gheri.

**Comment by joeyparrish** [comment]
Let's discuss xlink in the xlink issue for clarity.  As for chaining, as I mentioned before:

> You can wait for a video's "end" event and call player.load() again. If you want to implement chaining support in the player, that's effectively what you'd do with the supplemental property in the DASH manifest.

I think that's roughly the control flow you want.  The rest is a question of where to put the code, how to organize things, and how to plumb through the data you need to do it.

Since this is signaled in the manifest, you could always add a property to shaka.extern.Manifest, populated by shaka.dash.DashParser, then use that property in shaka.Player to react to the `ended` event on the media element and load new media.

**Comment by Gheri** [comment]
Thanks @joeyparrish . I am going with xlink for SGAI for now as some devices does not support MPD Chaining and I have no control over their implementation.
Just Like for MPD Chaining #3238  issue you roughly gave pointers for implementation. Can you help us with some pointers for this issue xlink implementation ??

**Comment by avelad** [comment]
I think this is feasible to implement in Shaka currently, is anyone interested in seeing this implemented?

**Comment by Gheri** [comment]
I m interested But might need help and some time also as I m busy with my office work

**Comment by avelad** [comment]
@Gheri I can implement it, but I want to know if there is interest in adding this functionality to Shaka, do you have more example sequences besides the dashif ones?

**Comment by Gheri** [comment]
Let me check I can revert early next week.
