### ISSUE TITLE
Not able to play non drm videos using shaka Player

### ISSUE THREAD

**Issue by anjuDigiMantra** [shaka-project/shaka-player#3932]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.10

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `master`?**
yes

**Are you using the demo app or your own custom app?**
yes

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

[Shaka Error NETWORK.BAD_HTTP_STATUS (https://video-staging.adda247.com/file?id=5270&pkgId=3724,400,{"success":false,"message":"Binding Exception. Parameters missing","response":null,"data":null},[object Object],0)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:1001)

**Comment by martinstark** [comment]
The `BAD_HTTP_STATUS` is not an internal shaka error, it's the server responding with an error when you try to access the URL.

Try visiting https://video-staging.adda247.com/file?id=5270&pkgId=3724,400 and you'll see the same error message. It does not look like a manifest URL.

**Comment by anjuDigiMantra** [comment]
> The `BAD_HTTP_STATUS` is not an internal shaka error, it's the server responding with an error when you try to access the URL.
> 
> Try visiting https://video-staging.adda247.com/file?id=5270&pkgId=3724,400 and you'll see the same error message. It does not look like a manifest URL.


Can we use shaka player for non-drm videos as we do not have any manifest url for non drm videos?

**Comment by martinstark** [comment]
Shaka is first and foremost a MSE/EME DASH and HLS player, which are both video formats using manifests (with or without drm). It is also possible to play .mp4 files directly through shaka, but for that you need a URL that points towards a .mp4 file.

**Comment by avelad** [comment]
We were able to solve your question? Is there anything else we can do?
