### ISSUE TITLE
Subtitles in PIP

### ISSUE THREAD

**Issue by jakubvojacek** [shaka-project/shaka-player#3966]
Hello

I would post in https://github.com/google/shaka-player/issues/1903 but its closed and I cannot post there - I believe chromium team made it already possible for shaka to insert any element into pip (https://groups.google.com/a/chromium.org/g/blink-dev/c/jr2fQUh6xEI?pli=1)

Do you think something like that would be possible?

Thanks

**Comment by avelad** [comment]
Duplicate of https://github.com/shaka-project/shaka-player/issues/4964
