### ISSUE TITLE
Const Multiple Audio Language Order

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#3978]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
NONE

**What version of Shaka Player are you using?**
v3.3.2

**Please ask your question**
I am playing an HLS live stream with 8 languages 

Every time I reload the page the list of audio changes its position in the Language list. 

What we want is it should have the exact same order of audio order as HLS live playlist has. Even if we reload the page.

**Comment by avelad** [comment]
This sounds more like a request for improvement than a question. Can you open an improvement issue?
Thanks!

**Comment by hiren3897** [comment]
#4178
