### ISSUE TITLE
useMediaCapabilities does not allow drm clearKeys on Firefox

### ISSUE THREAD

**Issue by naktinis** [shaka-project/shaka-player#3983]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
v.3.3.2
v.3.2.0

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `master`?**
Yes.

**Are you using the demo app or your own custom app?**
Custom.

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Firefox 97.0 / MacOS 12.2.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "servers": {},
    "clearKeys": {
      "deadbeefdeadbeefdeadbeefdeadbeef": "18675309186753091867530918675309"
    },
    "advanced": {},
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 1.5,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "defaultPresentationDelay": 0,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "useFullSegmentsForStartTime": false
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 30,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "smallGapLimit": 0.5,
    "jumpLargeGaps": false,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2
  },
  "offline": {
    "usePersistentLicense": true
  },
  "abr": {
    "enabled": true,
    "defaultBandwidthEstimate": 4500000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    }
  },
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null
}
```

**What did you do?**
Set up clearKey DRM as follows:
```
playerShaka.configure({
    drm: {
        clearKeys: {
            'deadbeefdeadbeefdeadbeefdeadbeef': '18675309186753091867530918675309'
        }
    },
});
```

**What did you expect to happen?**
Clear key to be used to decode the content and the content to play.

**What actually happened?**
Content failed to play.

If I set `useMediaCapabilities: false` then it starts working again. I did `git bisect` and traced it to `b63a64e4ba83f7db422853dc879d1068e5f6dcdb`. So I'm guessing the default logic assumes that Firefox does not support `"keySystem": "org.w3.clearkey"`.

Below I'll provide media capabilities decoding info on Firefox and Chrome for comparison.
```
navigator.mediaCapabilities.decodingInfo({
  "type": "media-source",
  "video": {
    "contentType": "video/mp4; codecs=\"avc1.64001f\"",
    "width": 1280,
    "height": 720,
    "bitrate": 1904407,
    "framerate": 23.976023976023978
  },
  "audio": {
    "contentType": "audio/mp4; codecs=\"mp4a.40.2\"",
    "channels": 2,
    "bitrate": 133733,
    "samplerate": 44100,
    "spatialRendering": false
  },
  "keySystemConfiguration": {
    "keySystem": "org.w3.clearkey",
    "initDataType": "keyids",
    "persistentState": "optional",
    "distinctiveIdentifier": "optional",
    "sessionTypes": [
      "temporary"
    ],
    "audio": {
      "robustness": ""
    },
    "video": {
      "robustness": ""
    }
  }
}).then(r => console.log(r))
```
On Firefox it returns:
```
MediaCapabilitiesInfo {
  supported: true,
  smooth: true,
  powerEfficient: false
}
```

On Chrome it returns:
```
{
  keySystemAccess: MediaKeySystemAccess {keySystem: 'org.w3.clearkey'}
  powerEfficient: true,
  smooth: true,
  supported: true
}
```

Is this just a bug or lack of functionality on Firefox?

**Comment by michellezhuogg** [comment]
Hello @naktinis ,

Thank you for reporting this issue! From the mediaCapabilities.decodingInfo API outputs on Firefox and Chrome that you provided, it seems Firefox cannot take the `keySystemConfiguration` input and return the `keySystemAccess` yet. That is directly from the browser. In Shaka Player, if we set `useMediaCapabilities` to `true`, we use the `keySystemAccess` value from the MediaCapabilitiesInfo for DRM info. With Firefox, the keySystemAccess is missing.
To fix this, we can polyfill the MediaCapabilities decodingInfo API for Firefox in Shaka Player and call 'requestMediaKeySystemAccess' to get the keySystemAccess, something like [this](https://github.com/shaka-project/shaka-player/blob/3a6daa1b1f86a77400fd85a534a4c83adf0c286f/lib/polyfill/media_capabilities.js#L174).  Would that work for you?

**Comment by naktinis** [comment]
Hi @michellezhuogg! Yes, I think that would work. Thanks!

**Comment by avelad** [comment]
I've been looking around the issue a bit and I see the following:
![Captura de pantalla 2022-04-18 a las 13 20 22](https://user-images.githubusercontent.com/8983024/163801174-84dc91a3-4adc-4039-a330-3774363bbb51.png)

So the response is populated by https://github.com/shaka-project/eme-encryption-scheme-polyfill/blob/main/index.js

If this polyfill is not installed, the browser does not fill in this information.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
