### ISSUE TITLE
Keyboard navigation of range elements on Firefox

### ISSUE THREAD

**Issue by dvoracek-slub** [shaka-project/shaka-player#3987]
Note: This is basically same as #2027. That issue concerns IE and is closed as "will not implement" because IE isn't supported anymore, but the issue also occurs in Firefox.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Linux Mint 20.1, Firefox 97.0

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
—

**What are the manifest and license server URIs?**
Any

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default

**What did you do?**
Focus on volume bar (or seek bar) and use the arrow keys to change the value.

**What did you expect to happen?**
Volume is adjusted in small steps.

**What actually happened?**
Volume jumps to 0 or 1.

**Comment by prakhar3062** [comment]
are you working on it
