### ISSUE TITLE
reducing delay while playing dash stream

### ISSUE THREAD

**Issue by MikolajMGT** [shaka-project/shaka-player#3988]
Hello There!

I was testing Shaka Player using following demo:

https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://livesim.dashif.org/livesim/chunkdur_4/ato_7/testpic4_8s/Manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

This stream is live dash stream that displays current time (minutes and seconds). There is some delay between playback and current time, something about 15-20s for me. I would like to know if is there any way to reduce it? It seems like player is not following stream edge but plays only buffered content - after buffering it is not seeking to latest point of time. I believe that there is a way to achieve that but I didn't find solution yet, so I would be grateful for some tips.

Refards

**Comment by joeyparrish** [comment]
The distance from the true live edge (what's on the server) and the playback live edge (what the user sees as the live edge) is called the "presentation delay".  Shaka Player may get hints about this from a DASH manifest, but it can be configured explicitly through the config:

```js
player.configure('manifest.defaultPresentationDelay', 30);  // 30s delay
player.configure('manifest.dash.ignoreSuggestedPresentationDelay', true);
```

It is possible to set too short a delay, which can lead to buffering at the edge and playback further from the edge.  How short this can be depends on the content and how you're serving it.

Does this help?

**Comment by joeyparrish** [comment]
Oh, and since you're using the demo, I should have mentioned that you can change these settings in the demo UI by clicking the "gear" icon in the top left and changing the settings there.

Does this help?
