### ISSUE TITLE
Text-tracks enabled when changing audio-tracks via selectAudioLanguage (HLS only)

### ISSUE THREAD

**Issue by saringer** [shaka-project/shaka-player#3989]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes

**What version of Shaka Player are you using?**

3.3.2

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `master`?**

yes

**Are you using the demo app or your own custom app?**

We are using a custom app

**If custom app, can you reproduce the issue using our demo app?**

yes

**What browser and OS are you using?**

Safari (v15.3) on MacOS Monterey (v12.2.1)

**What did you do?**

The following steps were executed via JS-Debugger on the [Shaka-Demo](https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=ALL_CONTENT;panelData=drm:CLEAR,VOD,HLS;build=uncompiled) for the Asset _Angel One (HLS, MP4, multilingual)_:

- Select a text track
- enable text track visibility
- disable text track visibility
- change audio language

`player = video.ui.getControls().getLocalPlayer()`
` player.selectTextLanguage('fr')`
`player.setTextTrackVisibility(true)`
`player.setTextTrackVisibility(false)`
`player.selectAudioLanguage('it')`
`player.isTextTrackVisible()`

**What did you expect to happen?**

I expected no text tracks to be displayed, due to previously setting _textTrackVisibility_ to _false_.

**What actually happened?**

The previously set Text-Tracks are now displayed

<img width="1533" alt="Screenshot 2022-02-22 at 16 33 39" src="https://user-images.githubusercontent.com/7473273/155166255-c95e7f5e-6bd1-47aa-9e4c-d26ced44ede4.png">

**Comment by saringer** [comment]
I noticed on my screenshot that actually not the previously selected subtitles are displayed, but the english subtitles. Which does not make sense to me either when I select italian audio. When checking for the current active text tracks right after the commands on my previous screenshot 

`player.getTextTracks()`

I noticed that two text-tracks are now shown as active
<img width="1540" alt="Screenshot 2022-02-22 at 16 46 43" src="https://user-images.githubusercontent.com/7473273/155168667-4a6004eb-2623-4829-998d-2e89e6e7a2ae.png">

**Comment by avelad** [comment]
In this case the video element controls the reproduction, what happens is something that the Safari player itself does.

If you want to reverse this behavior you can use:

```js
player.configure('streaming.preferNativeHls', false);
```

**Comment by saringer** [comment]
Our content is encrypted with Fairplay. Would that still be supported if we disable the native hls support?

**Comment by avelad** [comment]
Fairplay is compatible with MSE (mp4) in 4.0. If your content uses TS, you have to use src= (native)
