### ISSUE TITLE
How do you control abr control in safari?

### ISSUE THREAD

**Issue by baehongjun0212** [shaka-project/shaka-player#3998]
Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?
Yes

Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
Yes

What version of Shaka Player are you using?
3.0

Please ask your question
When playing HLS images using ShakaPlayer in Safari, they automatically switch from low-definition to high-definition images. (360p -> 1080p )

In Chrome, you could disable abr control with the command below, but in Safari, how do you disable abr?

chrome: 
`player1.configure({abr: {enabled: false}});`

`My Video track: 360p / 480p / 720p / 1080p`

Thanks !

**Comment by joeyparrish** [comment]
If you are using Safari's native HLS implementation, Shaka Player is not in control of ABR.  In that case, there is no API in Safari to disable ABR (as far as I know).

On iOS, you don't have any other choice.  On desktop Safari, you can disable native HLS (and use Shaka's implementation) with:

```js
player.configure('streaming.preferNativeHls', false);
```

**Comment by baehongjun0212** [comment]
Even if I set it up above, the video quality automatically changes :(

```
async function initPlayer() {
  const video1 = document.getElementById('video1'); 
  const player1 = new shaka.Player(video1); 
  window.player1 = player1;

  player1.addEventListener('error', onErrorEvent);
  player1.configure({abr: {enabled: false}}); 
  player1.configure('streaming.preferNativeHls', false);
}
```

**Comment by avelad** [comment]
@baehongjun0212 are you using macOS or iOS?

**Comment by joeyparrish** [comment]
On iOS, `preferNativeHls: false` can't work, because native HLS is all there is.  On desktop Safari, it's different.

Does this answer your question?
