### ISSUE TITLE
Chromecast button not acivated

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4005]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.3.0
**Please ask your question**
I have integrated shaka-player in the android app using a web view.

when I try to use Chromecast the button doesn't appear on the UI.

I have set the Chromecast ID in the config and also linked script cast_sender.js in the index.html? 

It works when I try from the browser but not from the android app web-view.

Can you please help me with this? thanks

**Comment by hiren3897** [comment]
Did you have time to see my question, please?

**Comment by joeyparrish** [comment]
This could be a deficiency of WebView.  The Cast SDK communicates through private APIs to Chrome, which does the actual UDP and/or HTTP communication with the Chromecast devices on the network.  It is possible that WebView doesn't expose those APIs, whatever they are.  I don't know for sure, but this seems like the most likely cause.

**Comment by joeyparrish** [comment]
Listing all Cast devices on the network would have to be a function of the Cast SDK.  We don't have any direct way to do that in the player.  Full Cast SDK docs are here: https://developers.google.com/cast/docs/reference/web_sender

@JulianDomingo, I haven't found a method to list receivers on the network, but I am still learning my way around the SDK.  Is there a method for that, or is that restricted to the browser UI for selecting a receiver?

**Comment by hiren3897** [comment]
Yes, it would be great to have this function.

I am also on my learning the SDK to have this possibility.

If we have something, we can discuss it here.

Thanks

**Comment by joeyparrish** [comment]
As far as I can tell, device discovery is all handled inside the browser in C++, and isn't surfaced through JavaScript.  Sorry!

Since we don't have control over either of your issues in the player (WebView support for cast APIs, JS API for device discovery), I think we should close this issue.

**Comment by hiren3897** [comment]
Can you provide me the source where you find that the `device discovery is all handled inside the browser in C++` please?

I found some sources that discover the Chromecast receiver
`Get the list of ChromeCast devices (there is a 10 second delay for finding the devices on the local network):
java -jar caster.jar -l`
https://github.com/NoRulesJustFeels/Caster

https://github.com/NoRulesJustFeels/DIAL

And

For the WebView will it be possible to add an external cast button in the android app and cast the video from the shaka player?
What do you think about it?

**Comment by joeyparrish** [comment]
> Can you provide me the source where you find that the `device discovery is all handled inside the browser in C++` please?

There is no API in the Cast SDK to expose that information in JS.  When you use the Cast SDK to start a session, the list of devices is shown in Chrome's native UI, so it must be handled internal to the browser in C++.

> I found some sources that discover the Chromecast receiver
> https://github.com/NoRulesJustFeels/Caster

Absolutely.  People have reverse-engineered the Cast protocol and can do mdns discovery from other environments.  Our [testing tools for Chromecast](https://github.com/shaka-project/generic-webdriver-server/tree/main/backends/chromecast#readme) rely on a [node module called castv2](https://www.npmjs.com/package/castv2) that can do this.  I meant that in a web app, the only way to do MDNS is through the browser, and the browser doesn't expose that capability to JavaScript.

> For the WebView will it be possible to add an external cast button in the android app and cast the video from the shaka player?

I have no idea.  My guess is yes, but I wouldn't know where to start.  There is probably some way to do this in Java, and to expose that capability to JavaScript in some custom way through your app's WebView.  I don't have any Android app development experience, so this is just a guess.

**Comment by hiren3897** [comment]
Okay, thanks for the explanations :)
