### ISSUE TITLE
TTML Subtitles (live) not showing

### ISSUE THREAD

**Issue by ShanePhelan** [shaka-project/shaka-player#4006]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.2

**Please ask your question**
We're testing live subtitles via an adaptation set of type 'text':

`<AdaptationSet
      id="2"
      group="3"
      contentType="text"
      mimeType="application/mp4"
      codecs="stpp.ttml.im1i"
      startWithSAP="1">
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="caption" />
      <SegmentTemplate
        timescale="1000"
        initialization="CTV01-$RepresentationID$.dash"
        media="CTV01-$RepresentationID$-$Time$.dash">
        
        <SegmentTimeline>
          <S t="1646238318680" d="3840" r="2" />
          <S d="560" />
          <S d="3280" />
          <S d="3840" r="3" />
          <S d="1360" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="caption_1=64000"
        bandwidth="64000">
      </Representation>
    </AdaptationSet>`

The codec is `stpp.ttml.im1i` so I've registered a parser against that codec:

`shaka.text.TextEngine.registerParser('application/mp4; codecs="stpp.ttml.im1i"', () => new shaka.text.Mp4TtmlParser());`

I'm also configuring to use the `UITextDisplayer`

`textDisplayFactory: function() { return new shaka.text.UITextDisplayer(videoElement, videoElement.parentNode); }`

Then doing the following to show:
`var tracks = player.getTextTracks();`
`player.selectTextTrack(tracks[0]);`
`player.setTextTrackVisibility(true);`

The track is definitely created but I can't see any requests for TTML files and nothing is displayed. Note, the same stream is showing the subtitles in the dashif reference player.

**Comment by ShanePhelan** [comment]
Update: If I show / hide / show then the subtitles are visible. Is this expected?

`var tracks = player.getTextTracks();`
`player.selectTextTrack(tracks[0]);`
`player.setTextTrackVisibility(true);`
`player.setTextTrackVisibility(false);`
`player.setTextTrackVisibility(true);`

**Comment by avelad** [comment]
@ShanePhelan I think this is more of a bug than a question, can you create an issue with the bug template and attach the url with which the bug is reproduced? Thank you!
