### ISSUE TITLE
 In the process of "MediaKeySession.update ()" Error: Failed to execute 'update' on 'MediaKeySession': Rejected with system code (38)

### ISSUE THREAD

**Issue by KazukiSugiyama107** [shaka-project/shaka-player#4010]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.6

**Please ask your question**

The license server returns the result of the request and there is an error when doing `MediaKeySession.update ()` on it.
We have confirmed that the license can be issued on the license server.

```
Error: Failed to execute 'update' on 'MediaKeySession': Rejected with system code (38)
```

I think the method in which the error is occurring is`update()`in `webkitmediakeys.js`, but since it is a js file that is externally referenced, I do not know what the error code means or the cause.
Do you know the cause of the error and the meaning of the error code?

**Comment by joeyparrish** [comment]
The error is that the browser API `update()` on `MediaKeySession` failed, and it reported "system code 38" as the reason, which is a Widevine-specific error code.  You'll need to refer to Widevine to determine what that means.  I don't believe the Widevine system codes are public, though I would be happy to be wrong about that.

In general, a failure in `update()` means that a license response was not accepted or understood by the Widevine CDM.  You should check to see:

1. if the license server URL was correct
2. if the format of the response is a raw Widevine license, and if not, visit [our license wrapping/unwrapping tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html)
3. if your server's license policies all make sense together and are a combination supported by Widevine

All of these things are out of the control of Shaka Player, but we can guide you a bit on solutions if you determine which was the cause.

**Comment by KazukiSugiyama107** [comment]
thank you for answering.
Contact Widevine for error codes.
This time, the error occurred only in the download, so I think that the application side that implements it is also involved.
Please check that part. If that doesn't work, comment again.

**Comment by KazukiSugiyama107** [comment]
This error has been resolved.
Thanks for your cooperation!
This issue will be closed.
