### ISSUE TITLE
currentTrack is undefined in Safari

### ISSUE THREAD

**Issue by vkryviak-magine** [shaka-project/shaka-player#4011]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.1

**Can you reproduce the issue with our latest release version?**
I assume yes as code is the same. Sorry cannot check this as reproduces selectively on production

**Can you reproduce the issue with the latest code from `main`?**
I assume yes as code is the same. Sorry cannot check this as reproduces selectively on production

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Not

**What browser and OS are you using?**
Safari 13-15 Only on MacOS 10.15

**What did you do?**
Bug appears after transition from v2.5.23 to v3.2.1 and only in Safari on MacOS 10.15
Error is fired when user start playing a video. Videos/users are different. 
Error may occur for the first video or after watching several videos.
We see the bug only in Bugsnag (happens selectively ±100 times per day).
Still cannot reproduce it. Trying as much as possible

**What actually happened?**
Error happens [here](https://github.com/shaka-project/shaka-player/blob/main/lib/player.js#L5459) 
Looks like sometimes currentTrack is undefined

**Stacktrace**
TypeError undefined is not an object (evaluating 'c.id') 
    node_modules/shaka-player/dist/shaka-player.compiled.js:428:369 Al
    node_modules/shaka-player/dist/shaka-player.compiled.js:397:160 
    node_modules/shaka-player/dist/shaka-player.compiled.js:374:63 
    node_modules/shaka-player/dist/shaka-player.compiled.js:372:345 
    node_modules/shaka-player/dist/shaka-player.compiled.js:22:41 Ca
    node_modules/shaka-player/dist/shaka-player.compiled.js:23:93 
    node_modules/shaka-player/dist/shaka-player.compiled.js:24:195 
    [native code] Promise
    node_modules/shaka-player/dist/shaka-player.compiled.js:24:92 
    node_modules/shaka-player/dist/shaka-player.compiled.js:24:229 I
    node_modules/shaka-player/dist/shaka-player.compiled.js:372:291 
    node_modules/shaka-player/dist/shaka-player.compiled.js:164:798 e
    node_modules/@bugsnag/browser/dist/bugsnag.js:2629:35 

shaka-player.compiled.js:428:369 -> { source: '../lib/player.js', line: 5264, column: 34, name: 'id' }

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
