### ISSUE TITLE
Getting 400 error code for widevine test server url

### ISSUE THREAD

**Issue by Dev3krishna** [shaka-project/shaka-player#4012]
Hi @joeyparrish or any folks who has been implementing DRM using shaka player, 

I am trying to implement DRM using widevine test server url provided on shaka packager documentation -
>Test server url - https://license.uat.widevine.com/cenc/getcontentkey/widevine_test

I am able to encrypt my video using this test-server key and serve the all the manifest and encrypted files using xampp on my local machine. I am using shaka-player on frontend to decrypt the content by changing the configuration as below - 

```
this.player.configure({
      drm: {
        servers: {
          "com.widevine.alpha":
            "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test"
        },
      },
});
```
On fetching the key the it is giving 400 error code , can someone plz guide me how exactly can I decrypt and play the video

For the first 6 seconds the video get's played irrespective of what we pass as license_server_url

**Comment by joeyparrish** [comment]
The URL you are using is only used for encryption, not licensing for playback.  They don't speak the same protocol.  If I recall correctly, the corresponding license server endpoint for Widevine UAT is https://proxy.uat.widevine.com/proxy

Does this help?

**Comment by Dev3krishna** [comment]
Thanks a lot @joeyparrish. It works
