### ISSUE TITLE
Subtitles show a background black

### ISSUE THREAD

**Issue by adgllorente** [shaka-project/shaka-player#4017]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Brave and Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Sended to the email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

1. Start playback
2. Choose spanish subtitles

**What did you expect to happen?**
Subtitles should be shown with a tight background black color.

**What actually happened?**

Subtitles show a big background black color

![Captura de pantalla 2022-03-08 a las 8 44 09](https://user-images.githubusercontent.com/1067480/157190529-b35845a2-1ce1-47c5-b277-eba0363f10ab.png)

**Comment by avelad** [comment]
@adgllorente can you share here the TTML that produces this error? I only need the ttml (if you prefer in raw format here (copy-paste)).
