### ISSUE TITLE
Google ad manager spliced HLS stream stops at discontinuity / ad break

### ISSUE THREAD

**Issue by jdeisenh** [shaka-project/shaka-player#4020]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.3.2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
not tried

**Are you using the demo app or your own custom app?**
checked both

**If custom app, can you reproduce the issue using our demo app?**
can be reproduced with demo app

**What browser and OS are you using?**
Chrome, Firefox, LG Web OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://fut.dev.wpstr.tv/tmp/shakahang/master2.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Defaults from demo app

**What did you do?**

Load URL in the demo app, press play

**What did you expect to happen?**
All 3 segments of the content play, not just the first

**What actually happened?**

Hang after the first segment

This very short 3 segment HLS stream is a minimized problem from a live stream that runs through google admanager DAI live stitcher. Only one of our test channels is affected with this problem, but there, it hangs every time on the first ad. 
Exoplayer plays it fine, apple HLS checker does not see a problem
The full pipeline is AWS Elemental Live Encoder -> Unified Streaming Packager -> google admanager 360 live stitcher.
This example has been manually built by dropping all but one profile and reducing the live manifest to a static one with only 3 segments.
A live manifest can be provided on request

**Comment by joeyparrish** [comment]
We have recently made some big changes to our HLS implementation.  Can you please try with the latest (unreleased) version here?  https://nightly-dot-shaka-player-demo.appspot.com/demo/

**Comment by jdeisenh** [comment]
The nightly of today plays as expected. 

Still the same assertions about 
Assertion failed: Metadata start time should be less or equal to the end time! player.js:2534:18

When transitioning into the ad, I see
Jumping forward 0.10253099999999904 seconds because of gap starting at 12.69335 and ending at 12.718385 gap_jumping_controller.js:240:19

**Comment by jdeisenh** [comment]
So, close this and wait for v3.3 ?

**Comment by joeyparrish** [comment]
Yes, except v3.3 is already out, and the next feature release will be v4.0.

Thanks for confirming that it works correctly in the upcoming release!
