### ISSUE TITLE
DRM key-Rotation fails when playback starts close to live edge

### ISSUE THREAD

**Issue by MoinPansare** [shaka-project/shaka-player#4021]
Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
yes

What version of Shaka Player are you using?
v3.3.2

Can you reproduce the issue with our latest release version?
yes

Can you reproduce the issue with the latest code from main?
not tried

Are you using the demo app or your own custom app?
checked both

If custom app, can you reproduce the issue using our demo app?
can be reproduced with demo app

What browser and OS are you using?
Chrome, Firefox

For embedded devices (smart TVs, etc.), what model and firmware version are you using?
N/A

What are the manifest and license server URIs?
https://pqi-ppe-cdn.enwd.co.sa.charterlab.com/LIVE/1022/dash-kr2/PAC12HD/manifest.mpd
i can provide Licence URL via mail or other methods that might be suitable 

What configuration are you using? What is the output of player.getConfiguration()?
Defaults from demo app

What did you do?
1. Load URL in the demo app
2. Load LicenceURL
3. Press Play

What did you expect to happen?
Once Keys are rotated, the playback should not stall

What actually happened?
The player requests for a license and that request is successfully completed, but if the segment is downloaded before the license request is triggered it results in a decode error resulting in stalling playback indefinitely.
I tried increasing the "DurationBackoff" parameter gradually and if the backoff is large enough so as to have segment download only after a successful manifest update with the correct Period info, the playback works.
This too being un-reliable and the playback eventually stalls with the below message
We also tried the "Delay License Request Untill Played" config but to no avail.
The error we get with the default config is 

{
    "severity": 2,
    "category": 3,
    "code": 3016,
    "data": [
        3,
        null,
        "PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: {timestamp=1646859001520188 duration=23211 size=285 is_key_frame=1 encrypted=0}"
    ],
    "handled": false,
    "message": "Shaka Error MEDIA.VIDEO_ERROR (3,,PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: {timestamp=1646859001520188 duration=23211 size=285 is_key_frame=1 encrypted=0})",
    "stack": "Error: Shaka Error MEDIA.VIDEO_ERROR (3,,PIPELINE_ERROR_DECODE: Failed to send audio packet for decoding: {timestamp=1646859001520188 duration=23211 size=285 is_key_frame=1 encrypted=0})\n    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:94:17)\n    at shaka.Player.videoErrorToShakaError_ (https://shaka-player-demo.appspot.com/lib/player.js:5766:12)\n    at shaka.Player.onVideoError_ (https://shaka-player-demo.appspot.com/lib/player.js:5778:24)\n    at HTMLVideoElement.onError (https://shaka-player-demo.appspot.com/lib/player.js:1318:39)"
}
(video:1) : failed to fetch and append code=3015
(audio:6) : failed to fetch and append code=3015
{
    "severity": 2,
    "category": 3,
    "code": 3015,
    "data": [
        {
            "stack": "Error: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.\n    at shaka.media.MediaSourceEngine.append_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:759:38)\n    at Object.start (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:559:22)\n    at shaka.media.MediaSourceEngine.startOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:1035:14)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:922:12)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:557:18)\n    at shaka.media.StreamingEngine.append_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1589:51)\n    at async shaka.media.StreamingEngine.fetchAndAppend_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1275:9)"
        }
    ],
    "handled": false,
    "message": "Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.)",
    "stack": "Error: Shaka Error MEDIA.MEDIA_SOURCE_OPERATION_THREW (InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.)\n    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:94:17)\n    at shaka.media.MediaSourceEngine.startOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:1044:25)\n    at shaka.media.MediaSourceEngine.enqueueOperation_ (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:922:12)\n    at shaka.media.MediaSourceEngine.appendBuffer (https://shaka-player-demo.appspot.com/lib/media/media_source_engine.js:557:18)\n    at shaka.media.StreamingEngine.append_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1589:51)\n    at async shaka.media.StreamingEngine.fetchAndAppend_ (https://shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1275:9)"
}

**Comment by joeyparrish** [comment]
@MoinPansare, can you please send license server URLs and authentication details to shaka-player-issues@google.com?  There's no way we could reproduce the issue without those details.  Anything sent to that email alias will be kept within the team at Google.

**Comment by joeyparrish** [comment]
That said, the error code appears to indicate a decoder error.  I think it should be possible to get that error if the content is decoded with the wrong key (and the output is effectively garbage), but that should not be an easy mistake to make.  The content should indicate the key ID for the segment, and you shouldn't have the wrong key unless the license server made a mistake.

This may require a pretty deep dive.

**Comment by MoinPansare** [comment]
@joeyparrish 
i only see this happening when the segment from period i+1 is downloaded before it is referenced in the manifest.
What i mean here is that lets say a segment 201.m4s is downloaded and is being pushed into decryption, and after this a manifest request is triggered stating that the segment 201.m4s was in a new period and has been encrypted using new keys.
Rather than using the new keys for this segment we end up using the old keys resulting in decode error.
If we have a mechanism to delay decryption of segments until required for playback we should be able to solve this.

**Comment by MoinPansare** [comment]
@joeyparrish, any comments on this issue. Awaiting a response

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
