### ISSUE TITLE
STPP Subtitles not rendered

### ISSUE THREAD

**Issue by david-hm-morgan** [shaka-project/shaka-player#4024]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://origin.vod.staging.salto.fr/benchmark/output/f/d/7/fd7db07dc85e6e2c94d8a45a56e65526cd976697de35394f4c200177f9ffd03d/static/c364010_web_clear_540p_dash_v10.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

(A recent [pull request](https://github.com/shaka-project/shaka-player/pull/3754) allowed the tracks to be discovered with this stream)

**What version of Shaka Player are you using?**
v3.3.2-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

**What did you do?**

1. Play the stream
2. Enable French captions (either of the two tracks)

**What did you expect to happen?**
Captions will be shown

**What actually happened?**

No subtitles rendered

**Comment by avelad** [comment]
I tested and the subtitle is rendered but is not visible for some reason. I think that the problem is in some CSS layer.

**Comment by joeyparrish** [comment]
There is a span container toward the top of the hierarchy (just inside `<div class="shaka-text-wrapper">` with `opacity: 0` set.  All its children are hidden.

It's because the TTML contains this:

```xml
  <style xml:id="defaultStyle"
         tts:backgroundColor="#00000000"
         tts:color="#ffffffff"
         tts:fontFamily="monospaceSansSerif"
         tts:fontSize="130%"
         tts:fontStyle="normal"
         tts:fontWeight="normal"
         tts:lineHeight="150%"
         tts:opacity="0"
         tts:textAlign="center"
         tts:textDecoration="none" />
```

If you drop `tts:opacity="0"`, it should show up correctly.
