### ISSUE TITLE
Play Range start and end settings

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4026]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.3.2

**Can you reproduce the issue with our latest release version?**
NO

**Can you reproduce the issue with the latest code from `main`?**
NO

**Are you using the demo app or your custom app?**
Demo APP

**If custom app, can you reproduce the issue using our demo app?**
__

**What browser and OS are you using?**
Chrome, Firefox, safari edge on iOS, iPadOS, macOS, Linux, windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://dash.akamaized.net/akamai/bbb_30fps/bbb_with_tiled_thumbnails.mpd
https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

playRangeStart: 10,
playRangeEnd: 100

**What did you do?**

I try to set the start and end range for a VOD

**What did you expect to happen?**
To have a timeline same as start and end range declared

**What happened?**

When I try to apply the play range start and end for DASH, I have a perfect timeline UI with the range declared, but the video is stuck and doesn't play further unless I click the timeline it plays than when I take back the seek to the start it Stops again.
![DASH](https://user-images.githubusercontent.com/59652404/158191712-053f6398-1f42-44aa-b641-16ef06d2c15d.png)

FOR HLS, 
When we declare the range the UI is not well set up and when the video ends we are not able to play the video again.

![HLS](https://user-images.githubusercontent.com/59652404/158192354-00476e5c-48f5-4c98-8d00-8d9d223ab344.png)

For mp4, the settings are not applied.

Thanks

**Comment by hiren3897** [comment]
Thanks :+1:

**Comment by hiren3897** [comment]
Hello, @joeyparrish Do we have any update on this bug?

**Comment by joeyparrish** [comment]
Looks like PresentationTimeline has a bug, and our unit test for seekRange() doesn't exercise this case.  When the manifest parser notifies the timeline of explicit segment times, rather than just a range, the playRangeEnd is ignored.

**Comment by hiren3897** [comment]
Thanks for the quick workaround on this issue.

I would also like to remind you that the UI build for DASH seems perfect but the video doesn't play at the start.
When I click ahead of the timeline then it starts playing because it fetches the segments to play but again when the I take back the timeline to zero the video is stopped.

For HLS,
The scenario is different, here the timeline is not built perfectly, and on the video ended we are not able to play the video again

These settings are also applied for mp4 VOD rather than DASH and HLS?

**Comment by hiren3897** [comment]
I created a playback issue #4091

the setting seems to be perfect for both HLS and VOD but it gives playback problem
