### ISSUE TITLE
Certain errors occur when downloading and playing videos

### ISSUE THREAD

**Issue by KazukiSugiyama107** [shaka-project/shaka-player#4032]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.6

**Please ask your question**
A video playback license will be issued at the time of download.
You can play it by downloading, but an error will occur after a certain number of seconds have passed during playback.

There are two types of error details, and I've checked the details, but I don't know the cause.
Do you know the cause of the error?

```
shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3016,
  "data": [
    3,
    null,
    "CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=17875.3"
  ],
  "handled": false
}
```

```
shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3016,
  "data": [
    3,
    null,
    "CHUNK_DEMUXER_ERROR_APPEND_FAILED: Failed to prepare video sample for decode"
  ],
  "handled": false
}
```

**Comment by joeyparrish** [comment]
That appears to be a decoder error.  The browser failed to decode one of the segments.  Does the same video resolution and audio language play correctly when streaming?  Or is this isolated to offline playback?

**Comment by KazukiSugiyama107** [comment]
Thank you for your investigation.
We have received reports from users about this error that reinstalling the app and reinstalling the video fixed the issue.
Because this problem has been resolved close the issue

**Comment by joeyparrish** [comment]
Thanks for the update!
