### ISSUE TITLE
When disconnecting from chromecast, subtitles are turned off

### ISSUE THREAD

**Issue by multiplexer2** [shaka-project/shaka-player#4036]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Probably

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome on Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Using Shaka demo

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Using Shaka demo

**What did you do?**
Navigate to the Shaka player demo site.
Play "Angel One"
Activate English (or any) subtitles
Start casting to an external device with Chromecast
The subtitles are correctly displayed on the external screen
Stop casting

**What did you expect to happen?**
After stopping the cast session the player continues to display the active subtitle track.

**What actually happened?**
The subtitles are now off

**Comment by avelad** [comment]
Can you check again against the main branch? Thanks!

**Comment by multiplexer2** [comment]
@shaka-bot reopen

This bug is still present in the latest code from main
