### ISSUE TITLE
Shaka player throws 3016 on LG 2016 and 2017 if server certificate is set.

### ISSUE THREAD

**Issue by shanmugapriyak1788** [shaka-project/shaka-player#4041]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
I haven't tested itt

**Are you using the demo app or your own custom app?**
Custom Application

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
LG 2016, LG 2017 OS 3.X

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Device ModelName: "49UJ632T-TA"
Device ModelNumber: "(Web0S; Linux/SmartTV)"
DeviceName: "lgwebostv"
Device User agent: "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 WebAppManager"

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
We could not retrieve as the player fails before this

**What did you do?**
1. Do the playback in LG 2016 with Widevine certificate options set.

**What did you expect to happen?**
Playback should happen. Playback should not if optimization is set.

**What actually happened?**
The Player threw the error 
Error Details: 
`
[{"errorCode":4194824,"errorMessage":"Errors parsing or processing audio or video streams.","internalError":{"errorCode":3016,"errorMessage":"{\"severity\":2,\"category\":3,\"code\":3016,\"data\":[4,null,null],\"handled\":false}","componentErrorCode":3016,"hexErrorCode":"BC8"},"contextDescription":"3016  undefined","componentErrorCode":520,"hexErrorCode":"400208"}] 
`

**Comment by joeyparrish** [comment]
Unfortunately:

 - We don't have an LG TV to reproduce this issue
 - It's a decoder or other platform-level error, which we usually can't do anything about anyway

I think your best recourse is either to work with someone at LG or to experiment with the source code to try to discover a workaround.  If you do discover a workaround for this, we'd be happy to have a PR for it.

Sorry we can't do more!

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
