### ISSUE TITLE
Chromecast not appearing when starting player programatically only.

### ISSUE THREAD

**Issue by Kla3mus** [shaka-project/shaka-player#4067]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.2.1

**Please ask your question**
My code to make ShakaPlayer play videos is like this (but I have the receiever ID set of course)

`
async function startPlayer(elementId, config, src) {

    window[elementId + "_shakaPlayer"] = function (elementId, config, src) {

        let player = null;
        let controls = null;
        let castProxy = null;
        let ui = null;

        let player1 = null;
        let video1 = null;

        browserSetup();
        initializePlayer();
        startVideo();

        function browserSetup() {
            shaka.polyfill.installAll();
            if (!shaka.Player.isBrowserSupported()) {
                alert('Browser is not supported');
            }
        }

        function initializePlayer() {

            const videoElement = document.getElementById(elementId);

            createPlayer(videoElement);
            createUi(videoElement);
            setWidevineRequestFilter(src.widevineLicenseUrl, src.playReadyUrl);
        }

        function createPlayer(videoElement)
        {
            let playerConfig = {
                'drm': {
                    'servers': {
                        'com.widevine.alpha': src.widevineLicenseUrl,
                        'com.microsoft.playready': src.playReadyUrl
                    }
                },
                'preferredAudioLanguage': config.defaultAudioLanguage,
                'preferredTextLanguage': config.defaultSubtitleLanguage
            }
            //shaka.util.Cast //changeReceiverId
            player = new shaka.Player(videoElement);
            castProxy = new shaka.cast.CastProxy(videoElement, player, "NumberIsHereInProductionButIHaveRemovedItForThisPost"); 
            player.configure(playerConfig);

        }

        function createUi(videoElement) {
            const uiConfig = {
                'controlPanelElements': [
                    'play_pause', 'time_and_duration', 'spacer', 'mute', 'volume', 'overflow_menu', 'cast', 'fullscreen'
                ],
                'overflowMenuButtons': ['captions', 'quality', 'language']
            };
            
            let container = videoElement.parentElement;

            ui = new shaka.ui.Overlay(player, container, videoElement);
            ui.configure(uiConfig);
            controls = ui.getControls();

            player1 = controls.getPlayer();
            video1 = controls.getVideo();

            controls.addEventListener('caststatuschanged', function (event) {
                const newCastStatus = event['newStatus'];
                // Handle cast status change
                console.log('The new cast status is: ' + newCastStatus, event);
            });

        }

        function setWidevineRequestFilter(wideVineLicenseUrl, playReadyLicenseUrl) {
            player.getNetworkingEngine().registerRequestFilter(function (type, request) {

                if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE)
                    return;

                const licUri = new URL(request.uris[0].toLowerCase());
                request.uris[0] = licUri.pathname.includes('widevine') ? wideVineLicenseUrl : playReadyLicenseUrl;
            });
        }
        
        async function startVideo() {
            try {
                await player.load(src.manifestUrl);
            } catch (error) {
                console.log(error);
            }
        }

        function dispose() {
            player.unload();
            player.destroy();
            player = null;
            controls = null;
            ui = null;
            window[elementId + "_shakaPlayer"] = null;
        }

        return {
            dispose: dispose,
            castProxy: castProxy,
            player1: player1,
            video1: video1
        }
    }(elementId, config, src);
}

function disposePlayer(elementId) {
    window[elementId + "_shakaPlayer"].dispose();
}
`

My problem is that the Chromecast button never appears in the player. I can cast by left clicking, no problem, it plays and all is well. And I can even control it from the player, but the button in the player is not visible. I thought this would be taken care of by the 'cast' field in the uiConfig?

**Comment by Kla3mus** [comment]
Thanks for the quick responses!

I thought that `NumberIsHereInProductionButIHaveRemovedItForThisPost` was supposed to be the castReceiverAppId? (this is the actual number receiverAppId in my JavaScript file, I have just removed it for this post)

`castProxy = new shaka.cast.CastProxy(videoElement, player, "NumberIsHereInProductionButIHaveRemovedItForThisPost"); `

At least according to this? -> 
https://shaka-player-demo.appspot.com/docs/api/shaka.cast.CastProxy.html

Or is receiverAppId different from castReceiverAppId?

Note again that I am able to cast by left clicking on the window, so the casting actually works...
![image](https://user-images.githubusercontent.com/6784123/160561043-5425f9ce-e833-417c-8807-89c4fd1ede17.png)
![image](https://user-images.githubusercontent.com/6784123/160561108-ad7eb4c8-e4c7-4252-8cf5-f83116d5ef12.png)

**Comment by Kla3mus** [comment]
A little extra.
![image](https://user-images.githubusercontent.com/6784123/160580670-6ea38460-8baa-4d50-ae3b-4e769516f9e3.png)
I'm getting these two CastSender things in the log when using the debug player... Not sure if it's good that there's two of each, or not...

**Comment by Kla3mus** [comment]
Alright!

I added it to 

          ```
const uiConfig = {
                'controlPanelElements': [
                    'play_pause', 'time_and_duration', 'spacer', 'mute', 'volume', 'overflow_menu', 'cast', 'fullscreen'
                ],
                'overflowMenuButtons': ['captions', 'quality', 'language'],
                'castReceiverAppId': 'NumberIsHereInProductionButIHaveRemovedItForThisPost'
            };
```

And it worked perfectly. I found this: https://shaka-player-demo.appspot.com/docs/api/ui_ui.js.html that helped me out a bit too...

Thanks guys! :)

**Comment by joeyparrish** [comment]
You shouldn't be creating your own CastProxy IIRC.  Just let the UI create one based on the configured receiver app ID.  If you need to access it, use `ui.getControls().getCastProxy()`

**Comment by Kla3mus** [comment]
Ah. Perfect :) Thanks joey! 👍
