### ISSUE TITLE
Error only when load HLS

### ISSUE THREAD

**Issue by bram-abe** [shaka-project/shaka-player#4070]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
windows, macOs, chrome, firefox & edge

**What did you do?**

Load HLS manifest

**What did you expect to happen?**
Shaka should load and play HLS manifest

**What actually happened?**
Error Code : 1002
Error message: "TypeError: Failed to fetch\n    at $jscomp.generator.Engine_.program_ (https://****/dist/shaka-player-***).

If I load HLS manifest directly from video player such as VLC it works fine but not worked when load from Shaka player.
DASH and CMAF not effected. the problem only happen on HLS.

**Comment by joeyparrish** [comment]
Looks like a CORS error.  Are you loading content from another domain/origin, other than where your web player is hosted?  If so, the server must explicitly allow access.  See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for details.

If it is in fact a CORS error, you will see logs in the JS console of the browser indicating this.  These are generated by the browser and aren't visible in JavaScript, so Shaka Player can't directly detect CORS issues and explicitly name them in an error code.

**Comment by bram-abe** [comment]
Thank you for response @joeyparrish . 

I've had fixing CORS problem and revalidate the caching and now have new `HEAD` failed request.
There is a console message : Unable to find byte-order-mark, making an educated guess.
error.code : 1001
error.data[1] : 404

I've also done HLS endpoint testing with VLC player and it's works

**Comment by joeyparrish** [comment]
Looks like an HTTP 404 error (not found).  Are you sure there isn't a typo?

Does your server support HEAD requests?

**Comment by bram-abe** [comment]
> Looks like an HTTP 404 error (not found). Are you sure there isn't a typo?
> 
> Does your server support HEAD requests?

Yes, the server support HEAD request. 

I've had test it with another player to confirm and it works.
also HLS endpoint located on same server where CMAF dan DASH endpoint reside so it's have an identical server configuration

**Comment by avelad** [comment]
@bram-abe Can you check with 4.0.0? I think the problem could have been solved.
