### ISSUE TITLE
CMCD tests failing on Xbox One

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#4072]
Test output on Xbox One:

```
Edge 18.22000 (Xbox One) CmcdManager Query serialization produces correctly serialized data FAILED
        Error: Expected 'br=52317,bs,cid="xyz",com.test-exists,com.test-hello="world",com.test-testing=1234,com.test-token=undefined,d=6067,mtp=10000,nor="..%2Ftesting%2F3.m4v",nrr="0-99",sid="c936730c-031e-4a73-976f-92bc34039c60"' to be 'br=52317,bs,cid="xyz",com.test-exists,com.test-hello="world",com.test-testing=1234,com.test-token=s,d=6067,mtp=10000,nor="..%2Ftesting%2F3.m4v",nrr="0-99",sid="c936730c-031e-4a73-976f-92bc34039c60"'.
            at <Jasmine>
           at Anonymous function (test/util/cmcd_manager_unit.js:41:7 <- test/util/cmcd_manager_unit.js:37:7)
            at <Jasmine>
```

It seems that the cause is the code to handle Symbols:

```js
      // Serialize the key/value pair
      const type = typeof value;
      let result;

      if (type === 'string' && key !== 'ot' && key !== 'sf' && key !== 'st') {
        result = `${key}=${JSON.stringify(value)}`;
      } else if (type === 'boolean') {
        result = key;
      } else if (type === 'symbol') {
        result = `${key}=${value.description}`;
      } else {
        result = `${key}=${value}`;
      }
```

On Xbox One, it seems that `description` is unimplemented somehow:

```js
const s = Symbol('s');
console.log(s.description);  // prints undefined
```

While that is clearly a bug in the platform's JavaScript environment, @littlespex, is it necessary or useful to have Symbol support here?  I don't understand when someone would use that.

**Comment by littlespex** [comment]
Symbols are used to define custom CMCD token values. That said, there is currently no way to define custom CMCD fields (that feature is mentioned in the [original ticket](https://github.com/shaka-project/shaka-player/issues/3619) but not yet implemented). The symbol `else if` could be removed for now, or a fallback could be added `result = `${key}=${value.description || value.toString()(7, -1)}`;.

**Comment by joeyparrish** [comment]
What are "custom CMCD token values", and why are Symbols the solution?
