### ISSUE TITLE
Mixing muxed audio+video with alternate audio segments

### ISSUE THREAD

**Issue by fred-gregorio** [shaka-project/shaka-player#4081]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
3.3.2  with  mux.js  6.0.1

**Please ask your question**
I currently use video.js with my player and am planing to change it to use shaka. Development and test are being made under Edge and Chrome.
All my streams are LIVE-HLS  and some have multiple audio tracks, mainly portuguese and english.
For instance, the following HLS manifest:
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="eng a1",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="eng"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="por a2",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="por",URI="tracks-a2/mono.m3u8"
#EXT-X-STREAM-INF:AUDIO="aac",CLOSED-CAPTIONS=NONE,RESOLUTION=1920x1080,FRAME-RATE=29.970,CODECS="avc1.4d0028,mp4a.40.2",AVERAGE-BANDWIDTH=6050000,BANDWIDTH=7570000
tracks-v1a1/mono.m3u8

returns, when I call getAudioLanguagesAndRoles():
0: {language: 'pt', role: '', label: 'por a2'}
length: 1
(Only one language track)

when I use video.js with the same stream/manifest, it returns both tracks when call audioTracks():
0:
loaded_: true
enabled: true
id: "eng a1"
kind: "main"
label: "eng a1"
language: (eng)

1:
enabled: (false)
id: "por a2"
kind: "alternative"
label: "por a2"
language: "por"
length: 2

The lines that create the player and load the manifest are:
   video.vid= document.getElementById('video-player');  // this is <video autoplay id='video-player' poster='img/loader.gif'></video>
   video.player= new shaka.Player(video.vid);
   video.player.addEventListener('error', function() {
       video.onerror= true;
   });
   video.player.load(<the-url>)
   .then( function() {
       callback( {status: 1} );
    })
   .catch( function(error_data) {
       callback( {status: -1} );
   });

I'm almost sure that I'm doing something wrong, but I can't find what.

Is getLanguagesAndRoles() the correct API to be used for this?

Thanks in advance.

**Comment by joeyparrish** [comment]
It looks like your English track has no URI attribute:

`#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="eng a1",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="eng"`

Does this help?

**Comment by fred-gregorio** [comment]
Hi Joey,

Thanks for the promptness in replying.

I noticed that the URI is not explicitly there and my first bet was on it. But then I looked at RFC 8216, section [4.3.4.2.1] - Alternative redentions, which states:

   The URI attribute of the EXT-X-MEDIA tag is REQUIRED if the media
   type is SUBTITLES, but OPTIONAL if the media type is VIDEO or AUDIO.
   If the media type is VIDEO or AUDIO, a missing URI attribute
   indicates that the media data for this Rendition is included in the
   Media Playlist of any EXT-X-STREAM-INF tag referencing this EXT-
   X-MEDIA tag.  **If the media TYPE is AUDIO and the URI attribute is
   missing, clients MUST assume that the audio data for this Rendition
   is present in every video Rendition specified by the EXT-X-STREAM-INF
   tag.**

This stream is being encoded by Flusonic and I'm not sure I can force it to include the URI in a variant that is described in the EXT-X-STREAM-INF tag.

Any chance that shaka will support this construction in the near future?

Best Regards
Fred

**Comment by joeyparrish** [comment]
If I understand correctly, you've got one playlist with audio+video in the same segments, and a second playlist with alternate audio segments containing no video.  Shaka Player doesn't demux or parse containers.  That is done by the browser in our model.  But in that model, you can either have separate audio and video streams, or you can have a stream with both, but you can't mix them.

Sorry we can't help with that!  I'm sure there are other players available that will demux and remux containers, and can therefore handle this scenario.  hls.js is very popular, and may meet your needs.

I hope this helps!

**Comment by fred-gregorio** [comment]
Helo Joey,

Unfortunately, you misinterpret it. Each alternative audio have a different set of segments with both video and audio.

For example:

main-playlist (manifest), URL= <base-url>/index.m3u8
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="por a1",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="por"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="eng a2",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="eng",URI="**tracks-a2/mono.m3u8**"
#EXT-X-STREAM-INF:AUDIO="aac",CLOSED-CAPTIONS=NONE,RESOLUTION=1920x1080,FRAME-RATE=29.970,CODECS="avc1.4d0028,mp4a.40.2",AVERAGE-BANDWIDTH=5910000,BANDWIDTH=7390000
**tracks-v1a1/mono.m3u8**

por a1, URL= <base-url>**/tracks-v1a1/mono.m3u8**
#EXTM3U
#EXT-X-TARGETDURATION:9
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:64503
#EXT-X-PROGRAM-DATE-TIME:2022-03-31T12:14:22Z
#EXTINF:8.008,
2022/03/31/12/14/22-08008.ts
#EXTINF:8.008,
2022/03/31/12/14/30-08008.ts
#EXTINF:8.008,
2022/03/31/12/14/38-08008.ts
#EXTINF:8.008,
2022/03/31/12/14/46-08008.ts

eng a2, URL= <base-url>**/tracks-a2/mono.m3u8**
#EXTM3U
#EXT-X-TARGETDURATION:9
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:64537
#EXT-X-PROGRAM-DATE-TIME:2022-03-31T12:18:54Z
#EXTINF:8.008,
2022/03/31/12/18/54-08008.ts
#EXTINF:8.008,
2022/03/31/12/19/02-08008.ts
#EXTINF:8.008,
2022/03/31/12/19/10-08008.ts
#EXTINF:8.008,
2022/03/31/12/19/18-08008.ts

The fact that the URI is not explicitly informed in the EXT-X-MEDIA tag just indicates to use the URI in the EXT-X-STREAM-INF to fetch the playlist for that variant.

This is defined since HLS-4. Prior to that (HLS-3) no different audio tracks were supported, unless, of course, the player would look for it in the the segments, in case more than one audio was available.

So, no, it's not expected for Shaka or any other MSE compatible player to demux, since this is up to the mediaplayer in the browser. What is expected from the player is to detect the existence of these alternative URIs, and provide a mechanism for the user to select them. The manifest in my example is a perfect valid HLS manifest.

If you decide to reopen this issue, I can provide you with an URL to play from our Flussonic encoder.

Best
Fred
