### ISSUE TITLE
Normalized volume

### ISSUE THREAD

**Issue by Ballevill** [shaka-project/shaka-player#4082]
Is there a normalized volume function in the shaka player as in youtube that will adjust the volume to e.g. 14 LUFS? 

Thx

**Comment by joeyparrish** [comment]
No, there is no such feature.  Volume is controlled purely through the video element: `videoElement.volume = 0.5`.  You can set the volume to any value between 0 and 1.  Normalizing could be done through [Web Audio APIs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API), but that's not part of Shaka Player.
