### ISSUE TITLE
Handling revoked widevine clients

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-player#4100]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest version

**Please ask your question**
We are using widevine/playready drm. Few users are getting the below error from our license server:
"Invalid license request. DRM client models with revoked certificates are not allowed to receive licenses"

Our license partner told us that there is some issue with the browser CDM. Can you please let me know how to handle these revoked certificate clients with shaka-player? Is there a way to update the certificates? Also can you pls tell me how this certificate is acquired? how it is installed in browser.

Thanks

**Comment by joeyparrish** [comment]
These are questions for Widevine as far as I can tell.  I'll give you some general information, but you'll need to follow up with Widevine support if you need any further assistance: https://www.widevine.com/contact

In general, each Widevine client has a certificate or "keybox" (for older devices).  For desktop browsers, this is a certificate that _I believe_ may be the same for all instances of that browser+OS combination.  For instance, all instances of Chrome on macOS on arm64 would have the same root of trust.  For Android or other CE devices, the device certificate may be the same for all devices of the same model, or may be different per individual devices (installed at the factory).

Devices can be further individualized with their own per-device certificates.

Revocations may be for individual devices, or they may target whole models of devices.  Only Widevine can give you more information on what was revoked or why.

These device certificates are never accessible to JavaScript libraries or applications, so there is nothing we can do about this in Shaka Player.

Widevine may be able to advise you further.  There _may_ be a way for you to set a policy in your license server that indicates that you are willing to deliver licenses to devices known to be compromised, but this risks attackers gaining access to your content keys, and is inadvisable from a security point of view.  You _may_ also have contractual obligations to content owners preventing you from using such a policy.

I hope that is a helpful primer, and I hope that Widevine is able to help you further: https://www.widevine.com/contact

Thanks!
