### ISSUE TITLE
Problem with IOS + FairPlay

### ISSUE THREAD

**Issue by qba86** [shaka-project/shaka-player#4107]
**Shaka player version: 2.5.15**

Fairplay on OSX works fine, but this same implementation on IOS doesn't work (ios 13.3, safari 13.0.4)
Console doesn't show any errors, player is still buffering.

```js
const fairPlayCertificate = convertObjectToArray(__FAIRPLAY_CERTIFICATE__);
config.drm.advanced['com.apple.fps.1_0'].serverCertificate = new Uint8Array(fairPlayCertificate);
config.drm.servers['com.apple.fps.1_0'] = fairplay.url; // in console I see request to fairplay.url

this.player.getNetworkingEngine().registerRequestFilter((type, request) => {
	// this filter isn't call on iOS but is call on OSX
})

this.player.getNetworkingEngine().registerResponseFilter((type, request) => {
	// this filter isn't call on iOS but is call on OSX is
})
```

Where did I go wrong?

**Comment by qba86** [comment]
Can anyone help me? :)

**Comment by joeyparrish** [comment]
Request and response filters for manifests and segments are not possible on iOS, because iOS does not permit Shaka Player to be in charge of network requests for media.  On iOS, all playback is through Apple's native HLS implementation.  The only requests we get to make on iOS are DRM license requests.

Does this help?

**Comment by qba86** [comment]
@joeyparrish thank You for Your request. "Request and response filters for manifests and segments are not possible on iOS" - I know It.
"The only requests we get to make on iOS are DRM license requests." - so how can I get license request?

**Comment by joeyparrish** [comment]
You can register a request or response filter, and on iOS, it will be called with `LICENSE`-type requests.  To make a license request, you need to configure the player for FairPlay.  See these two tutorials:

 - https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html
 - https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html

Does this answer your question?
