### ISSUE TITLE
The screen goes dark after a certain period of time in the full screen state.

### ISSUE THREAD

**Issue by KazukiSugiyama107** [shaka-project/shaka-player#4128]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.0.6

**Please ask your question**
This is an event that only happens to certain users, but when I play the video in full screen, the screen goes dark after a certain amount of time.
I asked the user to take a video, but the screen went dark when the cursor disappeared.

The video player implementation sets the data-shaka-player tag on the UI.
Hiding the cursor is done by `contolrs.js#onMouseStill_()`.
At the method call point, I couldn't confirm that the process of changing the brightness of the display was called, but I think it might be related.

Did you know the relevance of the screen dimming when the cursor disappears?

**Comment by joeyparrish** [comment]
I'm not aware of any way to control screen dimming features from a web browser.  If there's a web API for that, we would be happy to use it.

**Comment by KazukiSugiyama107** [comment]
Thank you for confirmation.
Close the ticket.
