### ISSUE TITLE
Is it possible to send `customData`?

### ISSUE THREAD

**Issue by AbeEstrada** [shaka-project/shaka-player#4133]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
^3.3.2

**Please ask your question**

I'm migrating from VideoJS to ShalaPlayer and VideoJS has a plugin to add the cast button [silvermine/videojs-chromecast](https://github.com/silvermine/videojs-chromecast), that plugin can send `customData` to the receiver as part of the `requestData.media` ([ChromecastTech.js#L172](https://github.com/silvermine/videojs-chromecast/blob/d885cc665739dcffb9d0f82aa0c23de03f5fa053/src/js/tech/ChromecastTech.js#L172)), I already tried with `controls.getCastProxy().setAppData({})` but it is different and **I do not control** the receiver web app. I see the receiver can handle it ([cast_receiver.js#L786](https://github.com/shaka-project/shaka-player/blob/d6bdf9a4c2ac1d8085bcc925492eb0526fe82c33/lib/cast/cast_receiver.js#L786))

My questions is: Is there a way to include `customData` as part of the request?

**Comment by joeyparrish** [comment]
The `shaka.cast` APIs are meant to be used on the sender side with `shaka.cast` used also on the receiver side.  For a receiver you don't control, you should probably use the Cast SDK directly.  In a future release, Shaka Player's `shaka.cast` API will be replaced with a cast button in our UI that talks directly to generic receivers.

See also #4214

Are you using the Shaka Player UI or a custom UI?  If your UI is custom, you can just choose not to use `shaka.cast` and talk directly to the Cast SDK.

If you _are_ using our UI, it will use `shaka.cast.CastProxy` no matter what.  You could choose not to configure it with an app ID, but you would still need to hook into or replace the various UI elements to make them communicate with your receiver.

Sorry for the inconvenience!
