### ISSUE TITLE
[PARAMOUNT GLOBAL] Samsung 2017 Video Start Failure

### ISSUE THREAD

**Issue by agajassi** [shaka-project/shaka-player#4143]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. I saw a similar open issue, but wanted to file this one with additional information/details and link the 2 tickets.
This is related to [issue/4142](https://github.com/shaka-project/shaka-player/issues/4142)

**What version of Shaka Player are you using?**
3.2.0

**Can you reproduce the issue with our latest release version?**
Yes. I can reproduce with 3.3.2

**Can you reproduce the issue with the latest code from `main`?**
Yes I can reproduce from `main` as well.

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Tizen

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
We were able to reproduce with couple different TVs. Here is information about both:

```
Model Code: UN50MU6070
Software Version: T-KTMAKUC-1300.3
Sub-micom Version: T-KTMINTV-1012
e-manual version: KTMATSCL-3.1.2
```
```
Model Code: UN32M5300
Software Version: T-KTSAKUC-1300.3
Sub-micom Version: T-KTSINTV-1003
e-manual version: KTSATSCL-1.2.1
```

**What are the manifest and license server URIs?**
We are able to reproduce the same issue both with encrypted and unencrypted. 
Here is the manifest URL for clear one:
```
https://entclips.cbsaavideo.com/2022/04/14/2023088195946/1284068_dash_ta/stream.mpd
```

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
For the sake of simplicity I am using default config values, but still the result of getConfig is attached to this ticket.
It is in a _pplus_config.txt_ file

**What did you do?**
Loaded a very simple test harness and called play().
Also tried with autoplay on <video>

**What did you expect to happen?**
I expected it to start playback, just like it does on other platforms.

**What actually happened?**
Nothing is rendered. Just a black screen. According to logs, player detects a stall at 0.042 and attempts to break stall by toggling Pause/Play. After that player changes to Playing state and that is it. Nothing else happens.

[pplus_config.txt](https://github.com/shaka-project/shaka-player/files/8526027/pplus_config.txt)
[Samsung_shaka_332_log.txt](https://github.com/shaka-project/shaka-player/files/8526047/Samsung_shaka_332_log.txt)
[tizen_debug_logs.txt](https://github.com/shaka-project/shaka-player/files/8526099/tizen_debug_logs.txt)

**Comment by agajassi** [comment]
Please let us know, if there is anything we can do to help. Test, debug, collect more info...etc.

**Comment by Vasanthavanan-Devarajan** [comment]
We also facing a similar issue with the X1 platform.  
[Issue 4014](https://github.com/shaka-project/shaka-player/issues/4014)

**Comment by agajassi** [comment]
<img width="1505" alt="Screen Shot 2022-05-11 at 6 03 51 PM" src="https://user-images.githubusercontent.com/12893220/167977978-8b5ea078-0637-44a7-a2be-83bf0af1f650.png">

In case if its helpful, here is the screenshot of 3015 error that gets fired when this issue is reproduced

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
