### ISSUE TITLE
Shaka Player goes blank on switching to landscape mode

### ISSUE THREAD

**Issue by ighosh98** [shaka-project/shaka-player#4145]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
We have tested with 3.3.2 using the demo app. We have also tested using these versions  of Shaka Player on a custom ReactJS demo app using NextJS framework:
- 3.2.1
- 3.2.0
- 3.0.1 
- 2.5.22
- 2.5.23

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
We were able to reproduce the issue both on the demo app and the custom app.

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
**Browser**: Chrome Browser
**OS**: Android
**Mobile Device Used**: OnePlus 7 Pro, Samsung M51(Android 11), One plus Nord 2
**Note**: We were able to reproduce this issue consistently on other Android devices too.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

Manifest file URL: https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

We have used the demo app and custom app with default configs. Attaching the configs in the file titled `defaultConfig.txt` 
[defaultConfig.txt](https://github.com/shaka-project/shaka-player/files/8527749/defaultConfig.txt)

**What did you do?**

1. Enable autorotate on the mobile device.
2. Continue rotating the phone to switch back and forth from a fullscreen mode to portrait mode. 
Attaching the video illustrating the steps mentioned for reference.

On the custom app, when user clicks on fullscreen icon, we force the player to render in landscape mode. So, there is another way to reproduce the issue on such an app:
1. Click on fullscreen icon multiple times. This forces the user to switch between portrait and landscape modes. 
There would be an instance during these steps when the player skin disappears and the video does not render but the audio continues playing in the background.  

**What did you expect to happen?**
We expected that the video would continue playing normally with audio and video. We expect the player skin controls and the video to render properly.

**What actually happened?**

1. The video player screen goes blank and the audio continues to play. The controls of the video player disappear as well. We can still click on where the controls were to play/pause and perform other actions on the video but the icons and the video do not render.
Rate of reproduction on Shaka Player demo app: ~30%(3 out of every 10 times)

https://user-images.githubusercontent.com/27827510/164386961-923fda3b-87e8-42cc-bbab-fe759e393ff2.mp4

**Comment by avelad** [comment]
Can you test if the main branch still has the problem? Thanks!
