### ISSUE TITLE
Playback problem on setting play range start and end

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4150]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v3.2.2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your custom app?**
DEMO APP

**If custom app, can you reproduce the issue using our demo app?**
--

**What browser and OS are you using?**
Chrome, Firefox, safari edge on iOS, iPadOS, macOS, Linux, windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
--

**What are the manifest and license server URIs?**

https://dash.akamaized.net/akamai/bbb_30fps/bbb_with_tiled_thumbnails.mpd
https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

playRangeStart: 10,
playRangeEnd: 100

**What did you do?**

I applied the start and end play range in the player.

and test if the player can give a playback between the given range

**What did you expect to happen?**
To have a player timeline and playback of VOD within the start and end play range configured 

**What actually happened?**

The configured settings are well applied on the player with the perfect timeline UI with #4068

But after setting the play range start and end there are many playback issues in the player.
- With DASH
  - the player is stopped at the start time of the play range start. if we seek ahead then the playback begins
  - if we click on the seek bar then the endTime of the player keeps on changing. for example, my endTime is 100 and after click, it was changed to 110+ 
  
- With HLS
  - it has the same problem as DASH has for seek-bar
  - if the video is ended the player is not able to play the video again.

**Comment by hiren3897** [comment]
Hello, am I explaining something wrong while reporting a bug because I am not getting a response from you?

I have created this bug report a second time and I am still not getting any updates or feedback on this bug.

Can you please reply to this? Many Thanks

**Comment by avelad** [comment]
@hiren3897 , @joeyparrish is in multiple projects and is busy, as soon as he has time he can help you.

**Comment by hiren3897** [comment]
@avelad thank you for your reply.

Noted!!

**Comment by hiren3897** [comment]
Hello, @joeyparrish can we have a point on this issue ?

**Comment by hiren3897** [comment]
Hello, @joeyparrish can we have a point on this issue ?

**Comment by hiren3897** [comment]
Hello, @joeyparrish can we have a point on this issue ?

**Comment by joeyparrish** [comment]
Sorry, I haven't had time to work on this.  Feel free to dig in to the source, though, and let us know what you find.  PRs are always welcome.  I suggest you look into the definitions of seekRange() and the methods that calls in PresentationTimeline.

**Comment by avelad** [comment]
Can you test if the main branch still has the problem? Thank you!
