### ISSUE TITLE
Issues with playing mp4 content on Tizen

### ISSUE THREAD

**Issue by MalgoBlock** [shaka-project/shaka-player#4161]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
There is a couple of open issues where video does not start at all on Tizen. (#4142 and #4143), they may be related however in my case the video does start playing but stalls shortly after (after about 1 minute) 

**What version of Shaka Player are you using?**
3.3.2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom app - the problem only happens on Tizen, the web version works without problems

**If custom app, can you reproduce the issue using our demo app?**
have not tried

**What browser and OS are you using?**
Tizen

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Model Code: UE43RU7179UXZG
Software Version:  T-MSLDEUC-1374.0

**What are the manifest and license server URIs?**
Have sent the URIs to [shaka-player-issues@google.com](mailto:shaka-player-issues@google.com)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```
abr:
advanced: {minTotalBytes: 128000, minBytes: 16000, fastHalfLife: 2, slowHalfLife: 5}
bandwidthDowngradeTarget: 0.95
bandwidthUpgradeTarget: 0.85
defaultBandwidthEstimate: 1000000
enabled: true
restrictions: {minWidth: 0, maxWidth: Infinity, minHeight: 0, maxHeight: Infinity, minPixels: 0, …}
switchInterval: 8
useNetworkInformation: true
__proto__: Object
abrFactory: ƒ ()
cmcd: {enabled: false, sessionId: "", contentId: "", useHeaders: false}
drm:
advanced: {}
clearKeys: {}
delayLicenseRequestUntilPlayed: false
initDataTransform: ƒ (a,b,c)
logLicenseExchange: false
preferredKeySystems: []
retryParameters:
backoffFactor: 2
baseDelay: 1000
connectionTimeout: 10000
fuzzFactor: 0.5
maxAttempts: 2
stallTimeout: 5000
timeout: 30000
__proto__: Object
servers:
com.apple.fps.1_0: *** 
com.microsoft.playready: ***
com.widevine.alpha: ***
__proto__: Object
updateExpirationTime: 1
__proto__: Object
manifest:
availabilityWindowOverride: NaN
dash: {clockSyncUri: "", ignoreDrmInfo: false, disableXlinkProcessing: false, xlinkFailGracefully: false, ignoreMinBufferTime: false, …}
defaultPresentationDelay: 0
disableAudio: false
disableText: false
disableThumbnails: false
disableVideo: false
hls: {ignoreTextStreamFailures: false, ignoreImageStreamFailures: false, useFullSegmentsForStartTime: false, defaultAudioCodec: "mp4a.40.2", defaultVideoCodec: "avc1.42E01E"}
retryParameters:
backoffFactor: 2
baseDelay: 1000
connectionTimeout: 10000
fuzzFactor: 0.5
maxAttempts: 2
stallTimeout: 5000
timeout: 30000
__proto__: Object
__proto__: Object
offline: {usePersistentLicense: true, trackSelectionCallback: ƒ, downloadSizeCallback: ƒ, progressCallback: ƒ}
playRangeEnd: Infinity
playRangeStart: 0
preferForcedSubs: false
preferredAudioChannelCount: 2
preferredAudioCodecs: []
preferredAudioLanguage: "de"
preferredDecodingAttributes: []
preferredTextLanguage: ""
preferredTextRole: ""
preferredVariantRole: "stereo_20"
preferredVideoCodecs: []
restrictions: {minWidth: 0, maxWidth: Infinity, minHeight: 0, maxHeight: Infinity, minPixels: 0, …}
streaming:
alwaysStreamText: false
autoLowLatencyMode: false
bufferBehind: 30
bufferingGoal: 10
dispatchAllEmsgBoxes: false
durationBackoff: 1
failureCallback: ƒ (c)
forceHTTPS: false
forceTransmuxTS: false
gapDetectionThreshold: 0.5
ignoreTextStreamFailures: false
inaccurateManifestTolerance: 2
jumpLargeGaps: false
lowLatencyMode: false
observeQualityChanges: false
preferNativeHls: false
rebufferingGoal: 2
retryParameters:
backoffFactor: 2
baseDelay: 1000
connectionTimeout: 10000
fuzzFactor: 0.5
maxAttempts: 2
stallTimeout: 5000
timeout: 30000
__proto__: Object
safeSeekOffset: 5
smallGapLimit: 0.5
stallEnabled: true
stallSkip: 0
stallThreshold: 1
startAtSegmentBoundary: false
updateIntervalSeconds: 1
useNativeHlsOnSafari: true
__proto__: Object
textDisplayFactory: ƒ ()
__proto__: Object
```

**What did you do?**
Try to play video

**What did you expect to happen?**
Video to play without stalling

**What actually happened?**
I am trying to play protected content and sometimes it also does not start but when it does in consistently stalls at around 1 - 2 minutes. There is no error when it happens, the underlying video element has networkState 1 (idle) and readyState 4 (have enough data) and paused = false
It is possible to seek and sometimes, but not always, after seeking the video plays again (and then stalls again)
When the video stalls, there is no error message, even with the Verbose 2 logs.
A very short mp4 file plays on Tizen without problems. (Up to about 2 minutes in length)

I am not sure if this may be related to drm configuration, on Tizen device I become a following errors:
```
PatchedMediaKeysNop.requestMediaKeySystemAccess
navigator.requestMediaKeySystemAccess failed.
PatchedMediaKeysNop.requestMediaKeySystemAccess
MediaCapabilities.decodingInfo() failed. {"type":"file","video":{"contentType":"video/mp4","width":1,"height":1,"bitrate":100,"framerate":1},"keySystemConfiguration":{"keySystem":"com.widevine.alpha","initDataType":"cenc","persistentState":"optional","distinctiveIdentifier":"optional","sessionTypes":["temporary"],"video":{"robustness":""}}} Error: The key system specified is not supported.
    at Navigator.../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.shaka.polyfill.PatchedMediaKeysNop.requestMediaKeySystemAccess (:8087/assets/bundle.js:154260)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Engine_.program_ (:8087/assets/bundle.js:154418)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Engine_.nextStep_ (:8087/assets/bundle.js:152448)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Engine_.next_ (:8087/assets/bundle.js:152444)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Generator_.next (:8087/assets/bundle.js:152449)
    at b (:8087/assets/bundle.js:152450)
    at <anonymous>
MediaCapabilities.decodingInfo() failed. {"type":"file","video":{"contentType":"video/mp4","width":1,"height":1,"bitrate":100,"framerate":1},"keySystemConfiguration":{"keySystem":"com.microsoft.playready","initDataType":"cenc","persistentState":"optional","distinctiveIdentifier":"optional","sessionTypes":["temporary"],"video":{"robustness":""}}} Error: The key system specified is not supported.
    at Navigator.../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.shaka.polyfill.PatchedMediaKeysNop.requestMediaKeySystemAccess (:8087/assets/bundle.js:154260)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Engine_.program_ (:8087/assets/bundle.js:154418)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Engine_.nextStep_ (:8087/assets/bundle.js:152448)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Engine_.next_ (:8087/assets/bundle.js:152444)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Generator_.next (:8087/assets/bundle.js:152449)
    at b (:8087/assets/bundle.js:152450)
    at <anonymous>
MediaCapabilities.decodingInfo() failed. {"type":"file","video":{"contentType":"video/mp4","width":1,"height":1,"bitrate":100,"framerate":1},"keySystemConfiguration":{"keySystem":"com.apple.fps.1_0","initDataType":"cenc","persistentState":"optional","distinctiveIdentifier":"optional","sessionTypes":["temporary"],"video":{"robustness":""}}} Error: The key system specified is not supported.
    at Navigator.../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.shaka.polyfill.PatchedMediaKeysNop.requestMediaKeySystemAccess (:8087/assets/bundle.js:154260)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Engine_.program_ (:8087/assets/bundle.js:154418)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Engine_.nextStep_ (:8087/assets/bundle.js:152448)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Engine_.next_ (:8087/assets/bundle.js:152444)
    at ../node_modules/shaka-player/dist/shaka-player.compiled.debug.js.$jscomp.generator.Generator_.next (:8087/assets/bundle.js:152449)
    at b (:8087/assets/bundle.js:152450)
    at <anonymous>
```

In the Browser Video plays but I receive an warning : `Failed to parse video contentType: video/mp4; codecs=`

I am not sure what can I try to get the video to play.

**Comment by MalgoBlock** [comment]
When the video stops this is the output of player.getStats():
```
bufferingTime: 21.296000003814697
completionPercent: 1
corruptedFrames: 0
decodedFrames: 0
drmTimeSeconds: NaN
droppedFrames: 0
estimatedBandwidth: NaN
height: NaN
licenseTime: NaN
liveLatency: NaN
loadLatency: 1.9860000610351562
manifestTimeSeconds: NaN
maxSegmentDuration: NaN
pauseTime: 0
playTime: 32.51600003242493
stateHistory: Array(3)
0: {timestamp: 1650967065.7, state: "buffering", duration: 13.428999900817871}
1: {timestamp: 1650967079.129, state: "playing", duration: 32.51600003242493}
2: {timestamp: 1650967111.645, state: "buffering", duration: 7.867000102996826}
length: 3
o: (...)
__proto__: Array(0)
streamBandwidth: NaN
switchHistory: []
width: NaN
```

**Comment by joeyparrish** [comment]
Playback of a single MP4 is up to the platform.  We don't control buffering in that scenario.  For a single MP4 (not DASH or HLS), Shaka Player is only responsible for the license exchange.

Do you have different results in any other player?  It could be that the MP4 is not encoded in a way that the platform decoder can handle.

**Comment by MalgoBlock** [comment]
I have replaced the Shaka Player with simple <video> tag with the same src and the movie plays without problem so it does not seem to be a decoder problem. The same mp4 starts playing with Shaka but gets stuck very quickly in the buffering state. After changing currentTime sometimes video plays a bit more and then gets stuck again.

Any idea what else could I try?

**Comment by joeyparrish** [comment]
I wonder if this has to do with the way we manage buffering states in the player.  It's not ideal.  We do everything ourselves, rather than trusting the browser.  It has been refactored a few times, but the general algorithm has been unchanged since we first launched Shaka Player, and browsers were notoriously unreliable with regards to buffering state.

If you can modify the player, please try this change in `lib/media/play_rate_controller.js`:

```js
  calculateCurrentRate_() {
    // return this.isBuffering_ ? 0 : this.rate_;
    return this.rate_;
  }
```

This will effectively stop the player from setting playbackRate to 0 when it thinks it's in a buffering state.  With this change, the UI may be incorrect, but if playback is able to progress, it will tell us that this system is to blame for the bug.

**Comment by MalgoBlock** [comment]
Thank you for the suggestion! I have tried it but unfortunately this does not seem to make any difference.
Is there anything that could be done to prevent the player going into buffering state? 
When I check the readyState of the video it is always 4 but the player enters buffering state and seems stuck in it.
I looked a bit through the Shaka Player code but couldn't see anything obvious.

**Comment by joeyparrish** [comment]
If that's not the issue, then I'm not sure what is.  I'll try debugging on our Tizen and see if I can figure it out.

**Comment by joeyparrish** [comment]
I'm unable to access the content you sent us privately.  I get HTTP 403 responses.  Is it geo-restricted?  I see that your company is in Germany.  Do I need to VPN through Germany to access it?  I'm also getting 404 responses when I post (empty payload, with curl) to the license server URLs you provided.  Vielen Dank!

**Comment by MalgoBlock** [comment]
@shaka-bot reopen

**Comment by MalgoBlock** [comment]
Sorry for the late response.. Yes, the content is geo blocked, maybe connecting through VPN would work. I will see if I could find another way to allow you access or find a different example file that is not blocked.

**Comment by MalgoBlock** [comment]
Hi, sorry for the delay in answering.
I am sending a couple of non geoblocked urls (one long and one short content) to your email address, please let me know if you are able to play those
@shaka-bot reopen

**Comment by MalgoBlock** [comment]
Hi, I just wanted to check if you manage to play the content I have sent? (Or do I need to look for another example?) Were you  able to replicate the issue I was having?

**Comment by MalgoBlock** [comment]
Hi, is there any progress on this issue? Do you maybe have a timescale for the v 4.2 release?

**Comment by theodab** [comment]
Me and @joeyparrish are both busy working on Chromecast issues at the moment. I have not had time to check out the content you said yet; I assume he hasn't either.

**Comment by MalgoBlock** [comment]
@theodab Am I correct to assume that your last comment is still the case?

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!

**Comment by MalgoBlock** [comment]
Hi, I have now tested this with v.4.3.3, unfortunately there does not seem to be much of a change. The video starts playing and plays consistently for about 1 minute and then stalls without recovering. If I then fast forward I can continue watching but also only for about 1 minute or less and it stalls again. Same if I start somewhere in the middle - always about a minute of play and then it stalls.
