### ISSUE TITLE
Shaka player skips some fragments causing the captions to flash (appear and disappear quickly)

### ISSUE THREAD

**Issue by vishnump-discovery** [shaka-project/shaka-player#4165]
We found that even though the fragmented mp4 caption files are in compliant with the standard, the Shaka player skips some fragments causing the captions to flash (appear and disappear quickly).

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://gtp-public-test-us-east-1.s3.amazonaws.com/flashing-captions-issue/fmp4-2sec/master.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v3.2.4-uncompiled

**What browser and OS are you using?**
Chrome/100.0.4896.127

**What did you do?**

1. Opened the shaka player demo page
2. We played the content using the manifest url - https://gtp-public-test-us-east-1.s3.amazonaws.com/flashing-captions-issue/fmp4-2sec/master.mpd
3. Opened the devtools 
4. After enabling the captions from settings icon, We can see the error message in console like "WVTT sample duration unknown, and no default found!",
"Aborting current segment request."

**What did you expect to happen?**

The shaka player should show all the captions properly

**What actually happened?**

During the playback if we enable captions from settings icon, We can't see the captions properly based on the window duration on the player. We see the following errors in the Shaka player web console output:
"WVTT sample duration unknown, and no default found!",
"Aborting current segment request. "

Based on our analysis, I see that this error is logged if there is no duration set in the samples in trun and also there is no default duration is set in tfhd box. 
But by analyzing the fragmented mp4s, I can see that, if trun has no sample duration, we have it set in the tfhd header. But some how Shaka player is not getting the default duration from the tfhd header.

<img width="1792" alt="Screenshot 2022-04-26 at 10 07 33 PM" src="https://user-images.githubusercontent.com/92804352/165354587-38b8fa85-b39f-4bfd-83d6-0e303a7c5dc5.png">

![image-20220318-165257](https://user-images.githubusercontent.com/92804352/165355303-f68f3382-52e9-4ce0-8562-74490f62a58a.png)

**Comment by avelad** [comment]
@vishnump-discovery can you review if the parser is correct? https://github.com/shaka-project/shaka-player/blob/main/lib/util/mp4_box_parsers.js#L18

**Comment by joeyparrish** [comment]
The flags field of your tfhd box is invalid.  The value is 0x020000.  The track ID is required, and your case, is then followed by another 4 bytes.  The flag bits are supposed to indicate which fields follow the track ID.  Clearly you mean those 4 bytes to be interpretted as a field, but 0x020000 is not a valid flag.  The valid values are 0x000001 (base_data_offset), 0x000002 (sample_description_index), 0x000008 (default_sample_duration), 0x000010 (default_sample_size), and 0x000020 (default_sample_flags - not read by Shaka).

This appears to be a bug in your content packaging.

**Comment by sriramhd** [comment]
@joeyparrish Apologies for the delayed response.  We'll follow up internally with our packaging folks and report back. Thanks for the pointers!
