### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by frankykubo** [shaka-project/shaka-player#4167]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.4

**Can you reproduce the issue with our latest release version?**
There is no need

**Can you reproduce the issue with the latest code from `main`?**
There is no need

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Probably, but there is no need.

**What browser and OS are you using?**
Chrome canary 103.0.5026.0, Windows 10

**What did you do?**
Updated from version 3.3.3 to version 3.3.4

**What did you expect to happen?**
No import errors.

**What actually happened?**
App is not able to import shaka anymore in this version, attaching picture below.

![shaka_err](https://user-images.githubusercontent.com/50501921/165461354-90c1baff-2a82-4464-b83e-44ca2bea66dc.png)

When I go back to v 3.3.3, it works as expected.
Thank you.

**Comment by joeyparrish** [comment]
v3.3.4 contained this PR: https://github.com/shaka-project/shaka-player/pull/4163

Do you think that could explain the issue?  What happens if you remove that added line from the d.ts file?

**Comment by joeyparrish** [comment]
There were not many other changes in v3.3.4 compared to v3.3.3: https://github.com/shaka-project/shaka-player/compare/v3.3.3...v3.3.4

The other changes were CSS, CI, and documentation changes.

**Comment by frankykubo** [comment]
@joeyparrish Yes, you are right. Removing `export default shaka;` from shaka-player.compiled.d.ts file fixes the error.

**Comment by joeyparrish** [comment]
Thank you for confirming.  I will revert the PR that caused this.
