### ISSUE TITLE
Const Multiple Audio Language Order

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4178]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**Is your feature request related to a problem? Please describe.**

I am trying to play a live and VOD  (HLS) playback with multiple audio.

1) When the player is loaded every time the default language selected is changed.
Also, 2) the sequence of the languages is changed when the player is loaded or a refresh is made each time.

**Describe the solution you'd like**

For the first, the problem I think we can set the default language from the configuration which is shorted.
But the second problem needs an improvement, the list of audio languages in the menu should appear in the same sequence as declared in the HLS playlist.

**Describe alternatives you've considered**

No alternatives just a quick and simple solution to make the appearance of the audio list const every time as configured in the HLS playlist.

**Additional context**

--

Thanks

**Comment by joeyparrish** [comment]
Is this using the Shaka Player UI?  Or is the issue the list of languages/tracks from the Shaka Player API (`getAudioLanguages()`)?

**Comment by joeyparrish** [comment]
Is the order of the languages in `player.getAudioLanguages()` self-consistent (same every time)?  Does the order there match the UI?  Does the order there match the HLS playlist?

**Comment by joeyparrish** [comment]
(Since you didn't provide any content for testing, we will need you to help us understand these details.)

**Comment by hiren3897** [comment]
Hello @joeyparrish 
Sorry for the delay I was so busy with other features.

So here is my info about the audio languages
The HLS playlist has 10 different languages as you can see in the image and also the order of the languages

![playlistORDER](https://user-images.githubusercontent.com/59652404/173024470-953d85a3-2017-4bad-8db9-4a1f19a33755.png)

1. eng
2. ger
3. rus
4. spa
5. fre
6. ita
7. jpn
8. pol
9. gre
10. cze

Every time I load the player or refresh the page the order of the audio languages changes 
You can observe the 3 images below where you can see the `player.getAudioLanguages()` changes.

![Player1Audio Images](https://user-images.githubusercontent.com/59652404/173025095-5391adcf-d03a-4b99-9c1e-a11133b81d0b.png)

![playerAudio2](https://user-images.githubusercontent.com/59652404/173025099-a43d0963-3acc-43ce-a906-e5320602f2d3.png)

![playerAudio3](https://user-images.githubusercontent.com/59652404/173025100-fa131a1e-4af8-482c-ad51-6f854519afec.png)

For the test I can send you the HLS playlist URL by email 
thanks

**Comment by hiren3897** [comment]
Hello, @joeyparrish did have time to see about this issue? thanks

**Comment by hiren3897** [comment]
Hello, @joeyparrish can we have a point on this issue ?

**Comment by hiren3897** [comment]
Hello, @joeyparrish can we have a point on this fix?

**Comment by hiren3897** [comment]
Hello, @joeyparrish can we have a point on this issue ?

**Comment by joeyparrish** [comment]
This is a low-priority issue for us, and we are not currently working on a fix.  PRs are always welcome, though.

I can't think of a good reason for the order to change unless the order changes in the playlist.  If there's some non-deterministic behavior in the HLS parser or Player, I'm all for fixing it.  Maybe see if the order of variant tracks in the manifest is stable, and if the order of languages in the parsed manifest corresponds to the order of getAudioLanguages().  It could be that the order of variant tracks coming of the HLS parser is the real root of the issue.

If you have to go cheap and quick, you could always add a .sort() somewhere in get*Languages().  But I think it would be preferable to understand why it changes in the first place.

I hope that helps!

**Comment by hiren3897** [comment]
Okay thanks for the quick response :)

I will have a look and let you know

**Comment by avelad** [comment]
I've been testing this issue with the demo streams, and it doesn't happen in the main branch. Thanks!
