### ISSUE TITLE
Preroll advertisement fails to start and disappears

### ISSUE THREAD

**Issue by salles-g** [shaka-project/shaka-player#4179]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
v3.3.4

**Are you using the demo app or your own custom app?**
I'm using the demo app.

**What browser and OS are you using?**
Google Chrome 100.0.4896.127 on Windows 10 Pro.

**What are the manifest and license server URIs?**
I'm using the [Sintel](https://shaka-player-demo.appspot.com/demo/#audiolang=pt-PT;textlang=pt-PT;uilang=pt-PT;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=uncompiled) asset.

**What did you do?**
I clicked directly on this [Sintel](https://shaka-player-demo.appspot.com/demo/#audiolang=pt-PT;textlang=pt-PT;uilang=pt-PT;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=uncompiled) asset URL. It also works when reloading the page in this exact URL.

**What did you expect to happen?**
I expected the Google Preroll to start.

**What actually happened?**
The ad fails to start and vanishes. I assume the demo doesn't use Shaka's debug version, but I'd expect something like **"IMA error 400 caused by IMA error 1205: The browser prevented playback without user interaction"** on the console.

**On a custom application:**
I was able to reproduce this exact behaviour on my application, even with **autoplay=false**. Setting **muted=true** on the video tag, the ad worked on my Chrome in Windows 10, but not on an iPhone SE's Safari.

I could get it to work by delaying the requestClientSideAds() call with a setTimeout of 10000ms, but that's on my custom application and I don't know if it'd work on the demo.

If this is really an issue with the autoplay, I'd love to know why it happens with autoplay=false. I've double checked and I'm not forcing a .play() anywhere in my code, and my workaround with "mute" does not work in all browsers.

**Comment by salles-g** [comment]
Digging more into it: on an iPhone 6S (Safari), the video refuses to load with the following error, and clicking on the play button does not start the playback.

![image](https://user-images.githubusercontent.com/82478213/166236324-162503cb-9e59-494c-b8f0-e6b75d1fa8e3.png)

_(edited this out from the issue as this was done on a platfrom different than the specified)_

**Comment by joeyparrish** [comment]
Thanks for the report.  I can't reproduce this in Chrome 100 on ChromeOS.  I haven't tried an iPhone yet.

Did I understand you correctly that it also fails for you in Chrome 100 on Windows?

**Comment by salles-g** [comment]
That's correct, it fails for me in Chrome 100 on Windows 10 Pro.

If I click on the play button, there is a user interaction, so the ad plays perfectly:
https://user-images.githubusercontent.com/82478213/166304095-e8ecfacb-4300-4b99-a91f-3c8d8a5a11ee.mp4

However, if I refresh the page and don't interact with it, the ad just vanishes:
https://user-images.githubusercontent.com/82478213/166304172-1fece2c0-ee3c-438a-bf65-edaa7ee33088.mp4

**Comment by joeyparrish** [comment]
I just tried again and this time I was able to reproduce it.  Nothing logged by IMA at all, nor any errors or warnings about it logged by Shaka.

We're loading the IMA SDK in the demo synchronously:

```html
<script type="text/javascript" src="https://imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
```

So there shouldn't be any issue with the timing of loading it.  I'm not sure what else it could be offhand, so we'll need to dig into this more deeply.

**Comment by salles-g** [comment]
Thanks for the quick response!

I don't know if this helps, but here's the error I get with the debug player in my custom application:
![image](https://user-images.githubusercontent.com/82478213/166306945-b5e99ca2-b106-4d7a-a104-0fa03582b9af.png)

**Comment by joeyparrish** [comment]
Autoplay restrictions are entirely up to the browser, and client-side ad insertion often involves a secondary video element that overlays ours.  So even if the browser allows you to autoplay the main element (because the user clicked something), it's conceivable that the browser might still reject autoplay from a secondary ad element in an iframe.

I would suggest you take this up with IMA instead.

**Comment by salles-g** [comment]
Thanks! I'll try and bring it to them.
Just one last question. My issue is: even if I have autoplay disabled, it tries to autoplay. Is that really up to IMA, considering Shaka creates the <video> tag?

**Comment by theodab** [comment]
The `video` element that a client-side IMA ad is playing in isn't created by Shaka, actually. We give the IMA SDK an empty `div`, and it makes a `video` element inside that `div`. We also give it a fallback `video` element that we do make, but I think that's for if it is unable to make new elements. See [their docs](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdDisplayContainer).

**Comment by salles-g** [comment]
Tysm! I'll close the issue in this case, then.

**Comment by salles-g** [comment]
Based on [this code sample](https://github.com/googleads/googleads-ima-html5/tree/main/attempt_to_autoplay) by IMA, I've managed to solve this.
I put try/catch around a random play() event before calling the start() method. If the promise rejects, I start the ads on any user interaction instead of simply calling the method:

```
        let autoplayAllowed;
        function autoplayChecksResolved() {
          shaka.log.debug('[autoplay]', 'autoplay checks resolved');
          const adsManager = a.getAdsManager(this.video_);
          if (autoplayAllowed) {
            shaka.log.debug('[autoplay]', 'autoplay allowed, starting adsManager');
            adsManager.start();
          } else {
            shaka.log.debug('[autoplay]', 'autoplay not allowed, fall back to click activation');
            // start ads on user interactions
            ['click', 'keydown'].forEach((event) => {
              window.addEventListener(event, () => {
                adsManager.start();
              }, { oince: true });
            });
          }
        }
        const videoContent = document.querySelector('video');
        const playPromise = videoContent.play();
        if (playPromise !== undefined) {
          playPromise.then(() => {
            shaka.log.debug('[autoplay]', 'unmuted autoplay works!');
            // If we make it here, unmuted autoplay works.
            videoContent.pause();
            autoplayAllowed = true;
            autoplayRequiresMuted = false;
            autoplayChecksResolved();
          }).catch(() => {
            shaka.log.warning('[autoplay]', 'unmuted autoplay does not work');
            // Unmuted autoplay failed. Now try muted autoplay.
            videoContent.volume = 1;
            videoContent.muted = false;
            autoplayAllowed = false;
            autoplayRequiresMuted = false;
            autoplayChecksResolved();
          });
        }
```

Of course this has some issues. This only works if I request the ads before a video's **canplay** event, otherwise the video won't play. So in my implementation I call it this way:
`video.addEventListener('canplay', requestClientSideAds, { once: true });`

The starting of the events is also binded to any window click (or key press), and not specifically a play button.

The IMA code sample accounts for a "muted" starting of the advertisement, which I've opted out of because it doesn't make sense for me to start a preroll muted. If this promise handling gets implemented in Shaka, it'd be nice to choose if it allows playing muted or not.

**Comment by joeyparrish** [comment]
Recategorized as a bug.  Someone needs to investigate your code snippet and decide if this or something like it should live in Shaka Player.  Thanks!
