### ISSUE TITLE
Exception in v4.0.0 with streaming.startAtSegmentBoundary

### ISSUE THREAD

**Issue by EinBaum** [shaka-project/shaka-player#4188]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.0.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
no

**What browser and OS are you using?**
Firefox 99

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

This issue will ONLY occur if you set "streaming.startAtSegmentBoundary" to true.

**What did you do?**

call "load()"

**What did you expect to happen?**
video plays

**What actually happened?**

`ERROR TypeError: k.segmentIndex[Symbol.iterator]().seek is not a function`

https://github.com/shaka-project/shaka-player/blob/20ddf6aa533222bde016ef3d6412e91fab03a5f9/lib/player.js#L5013
calls "seek()" but that function has been removed in version 4.0

**Comment by avelad** [comment]
I have checked and it happens. Seems like a regression when removing deprecated code in 4.0. @joeyparrish , can you take a look at it?

**Comment by joeyparrish** [comment]
There are no tests that activate that code path!  Fixing the code was easy.  I'm adding tests now.  PR coming soon.
