### ISSUE TITLE
Preload documentation

### ISSUE THREAD

**Issue by bknill** [shaka-project/shaka-player#4198]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
4.0.0

**Please ask your question**

Hi is the Preload documentation available yet (I realise you've only just released it!) Is it as described in [the proposal?  ](https://github.com/shaka-project/shaka-player/blob/main/docs/design/preload.md) ?

**Comment by joeyparrish** [comment]
Sorry for the confusion.  Preload (#880) has not been implemented yet.
