### ISSUE TITLE
PERIOD_FLATTENING_FAILED Error when playing mixed hvc1/hev1 or dvhe/dvh1 periods.

### ISSUE THREAD

**Issue by ghouet** [shaka-project/shaka-player#4202]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Sahak 4.0.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Chrome or Safari.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
https://storage.googleapis.com/trumantest-public/gh/shaka-bug.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
demo page config.

**What did you do?**
Attempt to play https://storage.googleapis.com/trumantest-public/gh/shaka-bug.mpd.

**What did you expect to happen?**
The stream should play properly.
It does actually play properly when I edit the mpd to only have dvh/hvc1 periods instead of a mix.

**What actually happened?**
The console shows the following error:
"Unused stream in period-flattening!"
... codecs: "dvh1.05.01" ....

**Comment by joeyparrish** [comment]
Thanks @ghouet!
