### ISSUE TITLE
Be able to play offline content on Safari on iPhone

### ISSUE THREAD

**Issue by oxixes** [shaka-project/shaka-player#4204]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Yes, currently offline content can be played on Safari for iPadOS, but not in iOS (which says it is not supported and gives an error).

**Describe the solution you'd like**

Be able to play offline content on Safari on iPhone.

**Describe alternatives you've considered**

A service worker may be a replacement, by redirecting requests to IndexedDB and using the player as if it was loading an online video, but I'd like the website I'm working on to be accessible and work in both http and https. 

**Additional context**

_None_

**Comment by joeyparrish** [comment]
I'm sorry, but this is not feasible.  On iOS, playback happens through Apple's native HLS implementation.  Applications can't fetch segments themselves, and service workers can't intercept the requests made by the HLS implementation (which is in C++).

If Apple were to make the MediaSource API available on iOS, Shaka's offline APIs would work.  But until then, there's isn't anything we can do.  If you feel strongly about this, please file an issue letting Apple know you want MediaSource on iOS, and why!
