### ISSUE TITLE
v4.0 Invalid config, unrecognized key .manifest.hls.useFullSegmentsForStartTime 

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4210]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v4.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**

Demo App
**If custom app, can you reproduce the issue using our demo app?**
---

**What browser and OS are you using?**
Chrome, Firefox, Safari
Linux, Windows, macOS, iOS, iPadOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

I will send the Playlist URL by mail once I get a response from you::)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

`.manifest.hls.useFullSegmentsForStartTime `

**What did you do?**

I tried to play the HLS stream and I got a blank playback in the player

**What did you expect to happen?**
To have an HLS playback of VOD and LIVE content

**What actually happened?**

IN the version v3,2,1 my HLS playback for LIVE and VOD was working perfectly by using the following settings `.manifest.hls.useFullSegmentsForStartTime`

In version 4.0.0 the setting has been removed and it throws me the same error in the console as before if I don't use those settings in v3.2.1

![errorShaka](https://user-images.githubusercontent.com/59652404/167862755-b777ef44-b4b7-45af-9614-d5ef52601ac3.jpeg)

The CONFIG
![theConfig](https://user-images.githubusercontent.com/59652404/167859161-49bc9ad5-556a-4663-8b14-f00eed7a4557.png)

**Comment by hiren3897** [comment]
hello thanks for the information

but when I try to play HLS VOD it throws errors in the console and I have no playback.

I will send the materials to test tomorrow with debug mode so you easily have a look.

can I send it to shaka-player-issues@google.com?

**Comment by hiren3897** [comment]
https://shaka-player-demo.appspot.com/demo/#audiolang=en-IN;textlang=en-IN;uilang=en-IN;asset=https://bhaktimarga-livestreaming-p30-cdn.hexaglobe.net/e01fee8f14cb7ea86e9b8bd5ac125676/627c0d93/bhaktimarga/bhaktimarga-website-web-1/bhaktimargalivestreaming_fre.smil/playlist.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by joeyparrish** [comment]
> Access to fetch at 'https://bhaktimarga-livestreaming-p30-cdn.hexaglobe.net/e01fee8f14cb7ea86e9b8bd5ac125676/627c0d93/bhaktimarga/bhaktimarga-website-web-1/bhaktimargalivestreaming_fre.smil/bhaktimargalivestreaming_video_1080_high_20220504133732_002161_03819784_0000006240000.ts' from origin 'https://shaka-player-demo.appspot.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

That's a CORS error.  It has nothing to do with the player.  It means the origin requesting the content (that's our demo) doesn't have permission to do so (that's controlled by the server hosting the content).  You can read more about Cross-Origin Resource Sharing on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by hiren3897** [comment]
So the player is making the request to 'https://bhaktimarga-livestreaming-p30-cdn.hexaglobe.net/e01fee8f14cb7ea86e9b8bd5ac125676/627c0d93/bhaktimarga/bhaktimarga-website-web-1/bhaktimargalivestreaming_fre.smil/bhaktimargalivestreaming_video_1080_high_20220504133732_002161_03819784_0000006240000.ts' ?

but before when we used manifest.hls.useFullSegmentsForStartTime the error was not coming 

the problem of Range Headers

**Comment by joeyparrish** [comment]
Range headers need special CORS configuration.  If your content uses byte ranges, then the server has to be configured to send the necessary CORS headers to allow `Range` in the request.  This may also trigger a "CORS preflight request", but I can't recall for sure.
