### ISSUE TITLE
HLS FAIRPLAY with DRM not working with v4.0.0

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4211]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v4.0

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `main`?**
YES

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
YES

**What browser and OS are you using?**
Safari iOS, iPad, MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

HLS FAIR PLAY with native as well as with MSE doesn't work

we have mp2t content type in HLS

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

drm.servers => drm_URL
drm.advanced.'com.apple.fps.1_0'.serverCertificate: cert

**What did you do?**

To play the HLS Fairplay live stream on the safari browser with DRM and ServerCertificate but it is not working in v4 :( I have a blank player playing nothing

**What did you expect to happen?**
To have an HLS LIVE playback on safari mac and iOS and iPad

**What actually happened?**

The HLS Fairplay used to work perfectly with v3.2.2 but it is not working in v4 :( 

I will send the screenshot and whole debug on mail

**Comment by hiren3897** [comment]
after changing it from `com.apple.fps.1_0` tp com.apple.fps' still it doesn't work for me.

**Comment by hiren3897** [comment]
I tested on the Shaka demo app and it says failed to decode media failed to decode

**Comment by hiren3897** [comment]
I have sent an email to shaka-player-issues@google.com with the template and the demo test URL. can you please test it on safari 

Thanks

**Comment by hiren3897** [comment]
Hello @avelad did you got time to test it? are you available?

**Comment by avelad** [comment]
@hiren3897 Sorry, I'm on holidays until tomorrow

**Comment by hiren3897** [comment]
Okay, once you are back on Wednesday please let me know.

**Comment by hiren3897** [comment]
@joeyparrish Yes!, you can forward it to him, I will send the new demo to test because the earlier URLs are expired

**Comment by avelad** [comment]
@hiren3897 One question, I haven't received Joey's email yet because he's sleeping, what is the DRM provider (company)?

**Comment by avelad** [comment]
Using: https://na-fps.ezdrm.com/demo/ezdrm/master.m3u8

and the next configuration: 
```json
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "servers": {
      "com.apple.fps": "https://fps.ezdrm.com/api/licenses/b99ed9e5-c641-49d1-bfa8-43692b686ddb"
    },
    "clearKeys": {},
    "advanced": {
      "com.apple.fps": {
        "distinctiveIdentifierRequired": false,
        "persistentStateRequired": false,
        "videoRobustness": "",
        "audioRobustness": "",
        "sessionType": "",
        "serverCertificate": {},
        "serverCertificateUri": "https://fps.ezdrm.com/demo/video/eleisure.cer",
        "individualizationServer": ""
      }
    },
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1,
    "preferredKeySystems": []
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 1,
      "fuzzFactor": 0.5,
      "timeout": 15000,
      "stallTimeout": 2000,
      "connectionTimeout": 3000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": true,
    "defaultPresentationDelay": 0,
    "segmentRelativeVttTiming": false,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": true,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": true,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 10000000000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
        "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
      }
    },
    "hls": {
      "ignoreTextStreamFailures": true,
      "ignoreImageStreamFailures": false,
      "defaultAudioCodec": "mp4a.40.2",
      "defaultVideoCodec": "avc1.42E01E",
      "ignoreManifestProgramDateTime": false,
      "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\""
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 15,
      "baseDelay": 1000,
      "backoffFactor": 1,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 30,
    "bufferBehind": 5,
    "ignoreTextStreamFailures": true,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.5,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 0,
    "lowLatencyMode": false,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 1,
    "dispatchAllEmsgBoxes": false,
    "observeQualityChanges": false,
    "maxDisabledTime": 30
  },
  "offline": {
    "usePersistentLicense": true,
    "numberOfParallelDownloads": 5
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 4,
    "bandwidthUpgradeTarget": 0.95,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    },
    "advanced": {
      "minTotalBytes": 64000,
      "minBytes": 20000,
      "fastHalfLife": 2,
      "slowHalfLife": 4
    }
  },
  "preferredAudioLanguage": "es",
  "preferredTextLanguage": "es",
  "preferredVariantRole": "main",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferredVideoCodecs": [
    "dvh1",
    "dvhe",
    "av01",
    "hvc1",
    "hev1",
    "vp09",
    "vp9",
    "avc1",
    "avc3"
  ],
  "preferredAudioCodecs": [],
  "preferForcedSubs": false,
  "preferredDecodingAttributes": [],
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null,
  "cmcd": {
    "enabled": false,
    "sessionId": "",
    "contentId": "",
    "useHeaders": false
  }
}
```

And the next request filter:
```js
function ezdrmFairPlayRequest (type, request) {
  if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) {
    return;
  }
  request.headers['Content-Type'] = 'application/octet-stream';
}
```

and the next response filter
`shaka.util.FairPlayUtils.commonFairPlayResponse`

With this it works correctly in 4.0.0.

EZDRM data has been recolected from https://www.ezdrm.com/demonstration-of-shaka-player-security-ezdrm?hsLang=en

**Comment by hiren3897** [comment]
@avelad if you play this on Safari you will see the error 3016
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://equidia-racing1-p29-cdn.hexaglobe.net/91e41779dec52e9e2d993b71da22b004/628390a4/equidia/equidia-website-web-1/eqdracing1pri_fre.smil/playlistfairplay.m3u8;license=https://fps.ezdrm.com/api/licenses/aac98b67-4987-49ad-b6b5-139522b134ee?m=6d9e5a7455041704e99bea9663b7686d&client=equidia&targetfile=racing1&t_hex=628390a4;certificate=https://equidia-racing1-p-api.hexaglobe.net/equidia/racing1/equidia-website-web-1/certificate/equidia.cer;panel=CUSTOM%20CONTENT;build=compiled

**Comment by avelad** [comment]
https://user-images.githubusercontent.com/8983024/168809753-3caffd83-e56a-4e20-b1a3-b2795d064049.mov

Note: there are no video and audio due DRM restrictions in the recording.

![IMG_4402](https://user-images.githubusercontent.com/8983024/168809707-c96ddc3d-f8c4-4378-a50f-51bb4fc124c2.jpg)

**Comment by hiren3897** [comment]
How did it appear in the second image?

It is only because of the DRM? so I have to ask the DRM about the problem we are facing?

**Comment by avelad** [comment]
I haven't done anything special, I just opened your link...

**Comment by avelad** [comment]
Note: I tested your url in iOS 15.5 (iPhone 13) and it works!

**Comment by hiren3897** [comment]
Yes, I saw that already, it is weird maybe it is because of DRM not sure

but if I see on safari networks I have a correct license request with `200 OK`

**Comment by joeyparrish** [comment]
@avelad, I just forwarded you the info from @hiren3897.

**Comment by avelad** [comment]
@hiren3897 I'm going to try it today, otherwise it will have to be tomorrow

**Comment by hiren3897** [comment]
I have received a mail from my DRM provider about this https://github.com/shaka-project/shaka-player/pull/4231

so when we have a fix in 4.1 I guess the problem for macOS safari will be fixed.

Thanks @avelad and @joeyparrish

**Comment by hiren3897** [comment]
```
{
    "keySystem": "com.widevine.alpha",
    "licenseServerUri": "https://widevine-dash.ezdrm.com/proxy?pX=4B6508&CustomDATA=equidia%23live2%b",
    "distinctiveIdentifierRequired": false,
    "persistentStateRequired": false,
    "sessionType": "temporary",
    "audioRobustness": "",
    "videoRobustness": "",
    "serverCertificateUri": "",
    "initData": [
        {
            "initDataType": "cenc",
            "initData": {
                "0": 0,
                "1": 0,
                "2": 0,
                "3": 82,
                "4": 112,
                "5": 115,
                "6": 115,
                "7": 104,
                "8": 0,
                "9": 0,
                "10": 0,
                "11": 0,
                "12": 237,
                "13": 239,
                "14": 139,
                "15": 169,
                "16": 121,
                "17": 214,
                "18": 74,
                "19": 206,
                "20": 163,
                "21": 200,
                "22": 39,
                "23": 220,
                "24": 213,
                "25": 29,
                "26": 33,
                "27": 237,
                "28": 0,
                "29": 0,
                "30": 0,
                "31": 50,
                "32": 8,
                "33": 1,
                "34": 18,
                "35": 16,
                "36": 2,
                "37": 207,
                "38": 14,
                "39": 4,
                "40": 250,
                "41": 182,
                "42": 89,
                "43": 96,
                "44": 132,
                "45": 73,
                "46": 232,
                "47": 120,
                "48": 186,
                "49": 86,
                "50": 230,
                "51": 254,
                "52": 26,
                "53": 8,
                "54": 109,
                "55": 111,
                "56": 118,
                "57": 105,
                "58": 100,
                "59": 111,
                "60": 110,
                "61": 101,
                "62": 34,
                "63": 16,
                "64": 233,
                "65": 78,
                "66": 38,
                "67": 137,
                "68": 174,
                "69": 54,
                "70": 11,
                "71": 78,
                "72": 138,
                "73": 127,
                "74": 201,
                "75": 50,
                "76": 252,
                "77": 117,
                "78": 155,
                "79": 194,
                "80": 50,
                "81": 0
            },
            "keyId": "~02cf0e04fab659608449e878ba56e6fe~"
        }
    ],
    "keyIds": {}
}
```

**Comment by hiren3897** [comment]
Hello, Do we have a fix in v4.0.1?

**Comment by avelad** [comment]
Yes, https://github.com/shaka-project/shaka-player/releases/tag/v4.0.1 `fairplay: Re-add initDataTransform config`

**Comment by hiren3897** [comment]
Thanks, I will test this and let you know!  :)

**Comment by hiren3897** [comment]
@avelad my HLS Fairplay stream still doesn't work with v4.0.1

**Comment by avelad** [comment]
There shouldn't be any difference, but you can always try.

**Comment by hiren3897** [comment]
![ima_6a7a7b5](https://user-images.githubusercontent.com/59652404/172413105-57285e0c-c1d9-454a-9159-ded919b984de.jpeg)

**Comment by hiren3897** [comment]
Hello @avelad greetings of the day,

can you please comment on the above response? Thanks

**Comment by avelad** [comment]
It seems that what fails in your capture is that some keysystems are being tested that are not supported in your browser. Widevine appears, PlayReady, Adobe?...

**Comment by hiren3897** [comment]
Okay, But it should mainly test for the `com.apple.fps` no? 
why does the player test other media capabilities?

Do we have any way to stop this test? 

because it works with 3.2.2 on the same platform and browser

**Comment by avelad** [comment]
The video that I have put in the comment above is with 4.1.0 and it works for me.

**Comment by hiren3897** [comment]
Thanks for your reply: can you please test this URL on your mac Safari with my HLS Fairplay stream 
https://test-drm.hexaglobe.net/hrathod/v4/newPluginTest-debug.php

The version is shaka v4.1.0

because I am still getting the error
![ima_d483109](https://user-images.githubusercontent.com/59652404/172638129-aa28fbea-0795-48d8-a1f4-aa5cb67ca5ab.jpeg)

**Comment by avelad** [comment]
![Captura de pantalla 2022-06-08 a las 16 15 16](https://user-images.githubusercontent.com/8983024/172639246-51512c0c-e1b2-4527-aee0-dca561b0db34.png)
It seems that it is geoblocked for Madrid (Spain)

**Comment by hiren3897** [comment]
I am sorry that I forgot to check that.
But for the success.
since v4.1.0
do we have changed any configuration for HLS Fairplay?

What do I do?
I give the .m3u8 URL to the load
I configure the DRM license to `drm.servers.com.apple.fps: "https://path/to/license"`
I configure the serverCertificateUri to `drm.advanced.com.apple.fps.serverCertificateUri: "https://path/to/cert"`

Am I missing something to do like ??
```js
function ezdrmFairPlayRequest (type, request) {
  if (type !== shaka.net.NetworkingEngine.RequestType.LICENSE) {
    return;
  }
  request.headers['Content-Type'] = 'application/octet-stream';
}
```

**Comment by hiren3897** [comment]
when I set `com.apple.fps` it doesn't work for me or on other machines
if I set `com.apple.fps.1_0` it is working but sometimes it gives me the same result of loading DRM restrictions 

I guess the DRM license request OR Fairplay cert is taking too long to be requested
@avelad can you please comment

**Comment by hiren3897** [comment]
hello, @avelad  can we come to a point do we have a fix in the newly released version?

and what are the steps to set up Fairplay live stream?

Thanks

**Comment by avelad** [comment]
It will be resolved with https://github.com/shaka-project/shaka-player/pull/4309
