### ISSUE TITLE
not working on IOS webview

### ISSUE THREAD

**Issue by espinojim2** [shaka-project/shaka-player#4221]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=uncompiled

**What version of Shaka Player are you using?**
v4.0.0-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by joeyparrish** [comment]
Since I'm not familiar with iOS WebView, what's the quickest way for me to bring up the demo in an iOS WebView?  Would I need to write and compile an application that uses WebView?  Or is there something trivial I can install on an iPhone?
