### ISSUE TITLE
LL-HLS: Preload hinted fragments is played twice sometimes

### ISSUE THREAD

**Issue by duggaraju** [shaka-project/shaka-player#4223]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.0.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome/Edge windwos

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Just play a live LL-HLS URL which has preload hint for the latest part.

**What did you expect to happen?**
Playback works fine.

**What actually happened?**

You will occasionally see audio/video repeat and if you see the network trace, the same part is downloaded twice.

Since the preload hinted part has no duration (start/end time are the same) and then when it becomes a regular part sometimes instea of merging the part looks like we are adding twice and downloading twice.

**Comment by duggaraju** [comment]
Sample live URL https://lldemo-usw22.streaming.media.azure.net/7c7bbf89-6a16-4b49-90d3-8bf15477b04f/93634f61-62c8-4f58-a500-ee2c9a6f40f4.ism/manifest(format=m3u8-cmaf).m3u8 but this may go down any time.

**Comment by joeyparrish** [comment]
Do you get the same behavior for v3.3?  Or was this introduced in v4.0?

**Comment by avelad** [comment]
I can reproduce it in 4.0.0 with https://shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;lowLatencyMode=true;uilang=es-ES;asset=https://lldemo-usw22.streaming.media.azure.net/7c7bbf89-6a16-4b49-90d3-8bf15477b04f/93634f61-62c8-4f58-a500-ee2c9a6f40f4.ism/manifest(format=m3u8-cmaf).m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by duggaraju** [comment]
Yes it repros with Shaka 3.3.0 as well.  You can clearly see the same video fragment being downloaded twice in the developer tools.  I can see it more often with audio parts (but I guess it is more of a timing issue and could happen with video too. But audio being smaller and quicker to download more easier to hit).

**Comment by joeyparrish** [comment]
Thank you for confirming!

**Comment by joeyparrish** [comment]
From what I see, the merge logic is actually sound.  The problem appears to be in how streaming and buffering operates on these segments.  I expect it is caused by the reference having a 0-duration, but I need to spend a little more time debugging to be certain.
