### ISSUE TITLE
How to use ui elements class in angular project. Is there any code example of it?

### ISSUE THREAD

**Issue by smvora4u** [shaka-project/shaka-player#4226]
I am very new to Shaka player. I am using shaka player with my angular project. I follow [this method ](https://betterprogramming.pub/the-best-open-source-media-player-to-integrate-with-your-angular-apps-39a80ff1aedb)explained by some one. That is working fine but now show thumbnail on seekbar hover like youtube, want to seek 10 seconds forward and backward, change the style of controls like vertical volume bar and seek bar in between all controls. Can I do this stuffs with shaka player, if yes, then how? Is there any simple example from which I can get this. I have gone through the documentations but can't get how to use shaka player ui elements class?

**Comment by joeyparrish** [comment]
We don't have thumbnail support in the UI yet, but we do have an open feature request for it already.

With the Shaka Player UI, you can:
 - Configure the UI to add or remove buttons or other UI elements
 - Configure the UI to change the order of elements in the UI
 - Style elements in CSS
 - Write plugins for additional elements we don't provide (custom buttons, etc)

See this page for details on customizing the UI: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html

Does this help?

**Comment by theodab** [comment]
See https://github.com/shaka-project/shaka-player/issues/3371 for progress on the UI thumbnails.

**Comment by smvora4u** [comment]
- How to make vertical volume bar?
- 10 seconds forward and backward, how to do that?
- want seekbar and all controls in one line, like currently seekbar is under all other controls by default. I want it in between other controls.  i.e. Play/pause - current time - seekbar - volume - settings - PIP - full screen. all should be in one line.

Is there any example or so for this? Please provide so I can refer it too.

By the way thank for your quick reply @joeyparrish. I appreciate this.

**Comment by joeyparrish** [comment]
> * How to make vertical volume bar?
> * 10 seconds forward and backward, how to do that?

We don't have that built-in, but you can find examples of how others have done it with custom UI elements.  For example: https://github.com/patricktran/shaka-player-ui-controls

> * want seekbar and all controls in one line, like currently seekbar is under all other controls by default. I want it in between other controls.  i.e. Play/pause - current time - seekbar - volume - settings - PIP - full screen. all should be in one line.

This could be changed with CSS if I'm not mistaken.  I believe there are examples of that in this third-party gallery of themes and styles: https://github.com/lucksy/shaka-player-themes
