### ISSUE TITLE
Incompatible codec is selected in Windows Edge for Widevine

### ISSUE THREAD

**Issue by wjywbs** [shaka-project/shaka-player#4242]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.0.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Windows 10 Edge 101, with PlayReady support and HEVC extension

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=compiled

Manifest url:
https://personal-data-2018.s3.amazonaws.com/bbb/b5.m3u8
https://personal-data-2018.s3.amazonaws.com/bbb/b5.mpd

Extra config:
```
{
  "drm": {
    "servers": {
      "com.widevine.alpha": "https://widevine-proxy.appspot.com/proxy"
    }
  }
}
```

**What did you expect to happen?**
Video (h264 format) plays using widevine.

**What actually happened?**
Shaka player tries to play h265 format with widevine and fails. Widevine license request went through.

This issue happens when both widevine and playready info exists in the manifest, and only widevine license server is provided.

**Comment by avelad** [comment]
The problem occurs when the manifest has H.264 and H.265, the browser supports Widevine and PlayReady, but with the following combination:
- Clear: H.264 and H.265
- Playready: H.264 and H.265
- Widevine: H.264

**Comment by avelad** [comment]
Verified that it is still happening in the main branch
