### ISSUE TITLE
com.microsoft.playready to com.microsoft.playready.recommendation mapping in HLS

### ISSUE THREAD

**Issue by wjywbs** [shaka-project/shaka-player#4243]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
`com.microsoft.playready.recommendation` is recommended in #818 for Windows Edge. But HLS manifest uses `com.microsoft.playready` as key format, and shaka uses `com.microsoft.playready` CDM and license server config instead of `com.microsoft.playready.recommendation`

`#EXT-X-KEY:METHOD=SAMPLE-AES,KEYFORMAT="com.microsoft.playready"`
https://docs.microsoft.com/en-us/playready/packaging/mp4-based-formats-supported-by-playready-clients?tabs=case4

**Describe the solution you'd like**

```
{
  "drm": {
    "servers": {
      "com.microsoft.playready.recommendation": "https://url"
    }
  }
}
```
Shaka can provide a way to map the key format in HLS, and remain compatible with DASH.

**Describe alternatives you've considered**

**Additional context**

DASH playback supports key system mapping.
https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html#choosing-a-key-system

```
player.configure({
  dash: {
    keySystemsByURI: {
      'urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95': 'com.microsoft.playready.recommendation',
    }
  }
});
```

**Comment by avelad** [comment]
@wjywbs Are you interested in sending a PR for it?

**Comment by wjywbs** [comment]
I haven't checked how to fix this yet.
