### ISSUE TITLE
Cannot set startTime on Safari-handled HLS content after loading it again

### ISSUE THREAD

**Issue by alexandercerutti** [shaka-project/shaka-player#4244]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes, none found

**What version of Shaka Player are you using?**

3.3.4, 3.3.5

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Not tested

**Are you using the demo app or your own custom app?**

Custom App

**If custom app, can you reproduce the issue using our demo app?**

I guess it cannot be tested (see below for the reason).

**What browser and OS are you using?**

Safari 15, iOS 15 and MacOS 12.2.1 (see differences below)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

-

**What are the manifest and license server URIs?**

I don't know yet if I can provide one (cause they are owned by our client). I'll provide via mail if needed

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

-

**What did you do?**

- load a (clean for sure) HLS content with startTime not specified or to 0 and leave it go for a few seconds.
- unload the content
- load the content back again with a startTime

**What did you expect to happen?**

The content should start from the specified point

**What actually happened?**

Content starts again from 0

___

I've investigated a bit what is happening under the hood and it seems like there's kind of race condition issue that happens on Safari iOS but not on Safari MacOS.

My use case is what follows: we load a content and at a certain point we might have an AD midroll. Hence, we unload the content and give Video node control to our AD Provider's SDK.

Then, we give back Video node control to Shaka, by passing to it the latest `currentTime` as `startTime` in `.load()`.

`.load` call is centralized such as:

```js
await this.player.load(content.src, content.startPosition, content.mimeType);
```

But when this is executed on Safari iOS, the `startTime` is ignored. Deep diving inside shaka, I've found there's an utility, that is being used, `shaka.media.SrcEqualsPlayhead`, which gets created everytime the content is loaded.

This class owns these notable things:
 - Instance variable `this.started_`
 - `onLoaded()`, which gets executed when the media is in ready state and sets `this.started_` to `true`.
 - `setStartTime(startTime)` method, which uses `this.started_` to update the startTime
 
In `player.js`, `onSrcEquals_` executes this:

```js
this.playhead_ = new shaka.media.SrcEqualsPlayhead(mediaElement);

...

if (has.startTime != null) {
  this.playhead_.setStartTime(has.startTime);
}
```

and expects that `onLoaded()` in `SrcEqualsPlayhead` will get called asynchronously but it may happen (especially on iOS, but it happened once also on Mac) that the function is called before `setStartTime` could get called. Therefore startTime setting is ignored.

I guess that `onLoaded()` could be moved into a Promise that will always resolve asynchronously but I'm not very into the codebase, so I don't know if it could be the right solution.

I'm available for any clarification if needed.
Thank you!

**Comment by joeyparrish** [comment]
Often you don't know if an event has already fired before you start listening for it.  With media lifecycle events, the `readyState` attribute tells you what stage you're in, so you can avoid this scenario.  To simplify that, we have the utility [`shaka.util.MediaReadyState.waitForReadyState()`](https://github.com/shaka-project/shaka-player/blob/4e4e92e98da357285547859a98e6b3fe75d1904f/lib/util/media_ready_state_utils.js#L20).  It calls a callback when a certain ready state is reached.  If it has already been reached, it calls the callback right away.  Otherwise, it waits for the corresponding event.

In the case where the state has already been reached, perhaps the utility should call the callback asynchronously (after a Promise) instead of synchronously before returning.  I think that would solve it by deferring that callback until the next interpreter cycle.

An alternate fix could be to change the `Playhead` interface.  We could add a separate method to "start" any async or other actions, instead of those being done in the constructor.  Then Player would call the constructor, then `setStartTime()`, then call "go", or whatever would be an actual good name for the method.  That new method would start timers, event listeners, etc., after all other setup methods had been called.  This way, the timing would be more explicit.

@alexandercerutti, would you be willing to test patches/branches for me to make sure these proposed fixes work?  I don't have an iPhone or Mac available at home to test this.

**Comment by joeyparrish** [comment]
Here are two possible fixes:

 - via Promise: https://github.com/joeyparrish/shaka-player/commit/c6d4ce915302f7eae779cf7be13adc650cec3bad
 - via new method: https://github.com/joeyparrish/shaka-player/commit/d9acbd58f8373b4423fa725443805e89f323626f

I expect both to work, but I think I prefer the addition of the new method.  If that fix works, I think that is the one I'd prefer to merge.

**Comment by alexandercerutti** [comment]
Hey @joeyparrish, thanks for your reply and your possible fixes!

I'm going to test them asap. I'm not quite sure if the best way to test them is by changing the compiled code or to recompile it from scratch and replace `compiled.debug.js` inside npm dependency in `node_modules`.

I'm not quite sure how to start in case of compilation. Is there any document I can refer to? I was looking in the repo but I wasn't able to find it. May I also propose to create a Github Wiki with documentation?

**Comment by joeyparrish** [comment]
Documentation is built from the /docs/ folder and lives in https://shaka-player-demo.appspot.com/docs/api/

Compilation is documented briefly in https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html

The short version is:

```sh
python build/all.py
```

Output goes to dist/

I hope that helps!

**Comment by alexandercerutti** [comment]
Thanks @joeyparrish!

I tried to compile both solutions (but yet I have to test them, I'll do as soon as my test iPhone will have enough charge 😝).

Promise solution built correctly, but the other one failed with this error:

<img width="1411" alt="immagine" src="https://user-images.githubusercontent.com/5442545/170222708-921ae65b-0388-4799-abaa-4747c6fcdebf.png">

**Comment by alexandercerutti** [comment]
I don't know, I was testing with my work custom application which compiles with Webpack 4. What's weird is that if I try to compile Promise fix, Webpack will output invalid characters:

```js
u
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! ./../../webpack/buildin/global.js */ "./node_modules/webpack/buildin/global.js")))ndefinedundefinedundefinedundefinedundefined
```

I don't actually know the reason.
I'll have to setup a custom project, hoping that this issue won't also happen in the next version with this fix (if you'll decide to use Promise version or if the issue will also happen with the other solution).

**Comment by avelad** [comment]
@joeyparrish can you review the last comment?

**Comment by alexandercerutti** [comment]
@joeyparrish do you have any news about this? This is blocking a more-than-actual production issue (and report) on our product. Should I open a Pull Request? I'd be happy to. If so, against which branch?

**Comment by avelad** [comment]
Any PR are welcome! Always against main branch! Thanks!

**Comment by alexandercerutti** [comment]
Oh, wait. Now I'm remembering: I wasn't able to test the second fix possibility. So I can open a PR for Promise fix only. I'm not sure this is actually okay as @joeyparrish expressed preference for the second solution.

**Comment by alexandercerutti** [comment]
@joeyparrish any news? What should be fixed on the second sample so it can be tested?

**Comment by alexandercerutti** [comment]
Hey @joeyparrish, were you able to give a look to this? We have a task open for this issue (even if I'll probably be able to test this again in September, when I'll get back from remote working). So, just to understand if it would be good to proceed with a PR with the promise solution. Just to remember you, I wasn't able to test the solution you preferred, maybe due to some kind of missing comment that I'm not quite sure how to fix.

**Comment by avelad** [comment]
@joeyparrish Can you review it again? if i remember correctly... you have two branches in your fork about this issue.

**Comment by alexandercerutti** [comment]
Hey @joeyparrish @avelad, I had the change to put again my hands on this and I tries to make things work. Now I'm of the idea that the "method way" @joeyparrish proposed is the best way.

I had to add a missing `.ready()` call in `onSrcEquals` method, but I'm not very sure this is the best place. I thing I'm going to open a PR with the fix to this (which includes what @joeyparrish did).
