### ISSUE TITLE
Drop usage of google closure compiler or better alternative ?

### ISSUE THREAD

**Issue by kocoten1992** [shaka-project/shaka-player#4251]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Not relevant

**Please ask your question**
Hello shaka team,

After sometime usage of shaka-player, I notice that google-closure-compiler is a PITA (slang), even a small change will require 30s recompiling the whole lib (which is extremely easy to made you open a youtube tab - which could cost way more than 30s).

I'm thinking of a `fast mode` for the compiler but it doesn't seem to be exists. I wish there is no compile step at all in development. How is your workflow everyday, how do you deal with it?

**Comment by theodab** [comment]
If you're worried about the time it takes to re-compile the app, you can load the uncompiled version (`shaka-player.uncompiled.js`, it's in the main folder). That will let you run the javascript files directly, without having to do a full compilation pass each time. You will have to load part of the Closure library for the files to work correctly, admittedly.
Here's the files the demo loads:

https://github.com/shaka-project/shaka-player/blob/60af9ad596e5c2cb31d1e7bb616e415cf46ca761/demo/index.html#L76-L86

Technically speaking, Closure Compiler does have a "fast mode" in the form of setting `compilation_level` to `WHITESPACE_ONLY` (see [the docs](https://developers.google.com/closure/compiler/docs/compilation_levels)). We leave the compilation level at its default value in our build scripts, though.

**Comment by kocoten1992** [comment]
Thanks @theodab, I've already try `WHITESPACE_ONLY`, it does not make a different (it does - but..).

The main issue (I think) is java run time slow start, my experience with java is very limited but having manage several java projects - it have an issue with `JVM warmup time`, unless we have a `watch mode` - which java process already warm up and keep running in background and doing compile, otherwise everytime running from cli - JVM gonna warm up, I think java is the worst fit for a cli project like that.

But thanks for the idea shaka demo, I'll try apply it and let you know.

**Comment by joeyparrish** [comment]
As @theodab says, normally we test in uncompiled mode in the demo, so after editing sources, we just reload the page without waiting for compilation.  In the demo, this is the default mode.  Doing this in your own app is covered briefly in the ["Debugging" tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html), in the section titled "Loading the uncompiled library".

Testing an issue that involves compiled mode is a pain, because compiling really is very slow.  I don't know that it will get much better so long as we are using Closure.  It could get slightly better with more modularization of the library and with a more intelligent build system that tracks dependencies and only rebuilds what is necessary.  (Like you'd expect from any build system used for C++ projects.)

In one possible future, we could drop Closure some day in favor of TypeScript, but this is a huge change, not only to the entire JavaScript codebase, but also requires a new tool for minification, a new docs system, etc.

Does the tip about the uncompiled library help alleviate some of the pain of development for now?

**Comment by kocoten1992** [comment]
Hi, thanks for the input and some insight for future change.

I'm on hold with uncompiled approach for now and just discorver https://github.com/closure-gun/closure-gun, I'll do a PR in docs if the experiment successful.

And thank for the insight again, I'm having a mix feeling about compiling anything in web development (coming from php world - where I have extremely tight development feedback loop - just a F5 reload).

I hope Typescript have an extreme mode for compiling, otherwise (maybe) we could use an opt in approach - just use a js static analyzer to report potential error and let user decide to fix it - and not compiling anything :smiley:

**Comment by joeyparrish** [comment]
It's possible for TypeScript to make it worse.  TypeScript **must** be compiled before reload.

I believe there's a background compiler for TS that is constantly recompiling your code as you edit, though I haven't really used TypeScript yet, so I don't have any experience with it.  I don't know how fast TS compilation is (probably it's fine), but with Closure in uncompiled mode, you literally don't have to compile at all.  Just F5 reload, as you mentioned with PHP.

If you have anything to contribute regarding closure-gun, I would be happy to review it.  But I do worry that requiring both a C++ compiler and Maven would be prohibitive.  People already complain about needing Java installed to run the compiler, so I don't know about adding C++ and Maven to the list of dev-dependencies.

**Comment by joeyparrish** [comment]
> I not confidence in uncompiled mode approach because I need to constantly swap in `google-closure-library/closure/goog/base.js` when push app into production mode

Just build the check into the app.  If you have your own build steps for production, you can strip out the check if you like, or just leave it in and don't deploy the uncompiled sources.

> writing environment check is also ugly

Your pseudo-code for it doesn't look too bad at all.  Our actual code for it is pretty long, but we're also managing a bunch of settings in the demo app's URL: https://github.com/shaka-project/shaka-player/blob/main/demo/load.js

In the end, it's just a loop around a list of scripts, and we load them dynamically:

```js
  var scripts = {
    'compiled': window['COMPILED_JS'],
    'debug_compiled': window['COMPILED_DEBUG_JS'],
    'uncompiled': window['UNCOMPILED_JS'],
  }[buildType];
  for (var j = 0; j < scripts.length; ++j) {
    loadRelativeScript(scripts[j]);
  }
```

Script loading is defined toward the top of the file:

```js
  // The URL of the page itself, without URL fragments or search strings.
  var pageUrl = location.href.split('#')[0].split('?')[0];
  // The URL of the page, up to and including the final '/'.
  var baseUrl = pageUrl.split('/').slice(0, -1).join('/') + '/';

  function loadRelativeScript(src) {
    importScript(baseUrl + src);
  }

  function importScript(src) {
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = src;
    script.defer = true;
    // Setting async = false is important to make sure the script is imported
    // before the 'load' event fires.
    script.async = false;  // eslint-disable-line id-denylist
    document.head.appendChild(script);

    // Signal success, or else the Closure Library's loader will not load the
    // next script.
    return true;
  }
```

I don't think there's much more we can do for you on this, but thanks for discussing it.  I hope you're able to find a workflow that works for you!

**Comment by kocoten1992** [comment]
Thank you, after some consideration, I think go with uncompiled approach still better than go through so much hassle.
