### ISSUE TITLE
Shaka 4.0.0 incorrectly generates SegmentReferences in Segment indexes

### ISSUE THREAD

**Issue by vishnump-discovery** [shaka-project/shaka-player#4256]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
[manifest copy.txt](https://github.com/shaka-project/shaka-player/files/8773216/manifest.copy.txt)

**What version of Shaka Player are you using?**
v4.0.0-uncompiled

**What browser and OS are you using?**
Chrome/101.0.4951.64 , All versions.

**What did you do?**
Start the playback based on the manifest file provided.
FF to the end of the content (more than 80% of the content)
Infinite buffering screen will come.(the same can be reproduced by updating the media element current time near to the end time of the total duration)
Based on our analysis  Shaka 4.0.0 incorrectly generates SegmentReferences in Segment indexes. For the manifest file can be found here - 

[manifest copy.txt](https://github.com/shaka-project/shaka-player/files/8773216/manifest.copy.txt)

The last SegmentIndex contains only one SegmentReference:

<img width="532" alt="Screenshot 2022-05-24 at 11 49 05 AM" src="https://user-images.githubusercontent.com/92804352/170316335-b8508422-b148-438d-9c85-8282c607f553.png">

So even the appendWindow is 2436-2778, there is only one reference which covers: 2436-2440.575999….

That is why it cannot find segment: 

(video:3) timeNeeded=2440.5759999999996
streaming_engine.js:987 (video:3) update_: presentationTime=2437.503999 bufferedAhead=3.0720000000001164

When SegmentIndexes for SegmentTemplate are generated the timeline is no updated. Hence, the  timeline getSegmentAvailabilityEnd contains from previous Period. That is why in last SegmentIndex we have only one SegmentReference.

**What did you expect to happen?**

The playback should work properly while Fast forwarding also.

**Comment by vishnump-discovery** [comment]
Hi Team 

Any update on this issue?

**Comment by joeyparrish** [comment]
We've just had a long holiday here, and this issue hasn't been investigated yet.  It's on our list, though.

**Comment by vishnump-discovery** [comment]
Hi @joeyparrish 

I have included the manifest file instead. Is that fine for you to replicate? The playback url will expire in short time. Thats why I have uploaded the manifest.

**Comment by vishnump-discovery** [comment]
Hi @joeyparrish 

Please find the playback url - https://qzg292fzej.execute-api.us-east-1.amazonaws.com/manifest/vod/vishnu_test.mpd

shaka demo app url - https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://qzg292fzej.execute-api.us-east-1.amazonaws.com/manifest/vod/vishnu_test.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by vishnump-discovery** [comment]
HI @joeyparrish 

Any update on this issue?

**Comment by joeyparrish** [comment]
We have not replicated the issue yet.  Is the issue still present in the latest release, v4.1.1?

**Comment by vishnump-discovery** [comment]
This issue is not there with v2.5.20. Regarding the version v4.1.1 I will check and update.

**Comment by joeyparrish** [comment]
I can't reproduce in v4.1.1.  I wasn't entirely sure what you meant by "FF".  Did you mean seek or the trick-play/fast-forward controls?

I tried seeking directly to a position close to the end, and saw no buffering problems.  I also tried enabling trick play controls and fast-forwarding at 8x from the beginning to the end, and saw no problems there, either.

**Comment by vishnump-discovery** [comment]
I am able to reproduce the issue with v4.1.1 also. I will share the playback url through email. I will attach the video for the evidence so that you can reproduce the issue easily.
Can you please share the email for sending the playback url?

**Comment by joeyparrish** [comment]
shaka-player-issues@google.com  Thanks!

**Comment by vishnump-discovery** [comment]
Hi @joeyparrish 

The issue can be reproducible with shaka 4.1.1. I have shared the playback url and evidence to the above mentioned mail. Please check the mail.

**Comment by vishnump-discovery** [comment]
HI @joeyparrish 

Any update on this issue?

The issue will occur when the manifest having both segmentTemplate and segmentlist in the periods.

**Comment by joeyparrish** [comment]
Please create a PR, and please compare with the contents of https://github.com/shaka-project/shaka-player/pull/4348, which makes some changes to PresentationTimeline in notifySegments.  I don't know if this relates to your problem, solves your problem, or conflicts with your fix, so please double-check.  Thanks!

**Comment by vishnump-discovery** [comment]
Hi @joeyparrish 

This is the problem on the "segment_template.js" file. if the segment info having the segment duration in "createStreamInfo" method instead of creating reference and notifying the segment end availability its returning the callback method "generateSegmentIndex".

<img width="1790" alt="Screenshot 2022-07-19 at 12 30 38 PM" src="https://user-images.githubusercontent.com/92804352/179687654-cc760a5d-f96b-4771-8396-d50855bac4c1.png">

I will create the PR and will past the link here.

**Comment by joeyparrish** [comment]
Thanks!

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
