### ISSUE TITLE
Remove IE 11 from default browsers list

### ISSUE THREAD

**Issue by RaymondCheng** [shaka-project/shaka-player#4271]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. The FAQ states up front that IE11 is no longer supported past version 3.1.

**What version of Shaka Player are you using?**
4.1.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
N/A, build issue

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Edge/Chrome/Firefox, Windows 11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

N/A

**What did you do?**

1. On a Windows 10 or 11 machine, follow the steps in Shaka's CONTRIBUTING.md. Will not repro on a non-Windows machine.
2. When you reach step 8, you run python build/test.py.

**What did you expect to happen?**
I expect IE 11 should not be in the default browser list because it is being retired on June 15, 2022, which is less than a fortnight from today. I expected that whichever default browsers are chosen to run the tests, that most tests should pass.

**What actually happened?**

On my machine, Edge/Chrome/Firefox have over 2000 tests pass, with some number of failures. IE is in fact in the default browser list, and IE fails to run at all, claiming a missing plugin. When I went to search for the plugin to install (WebDriver?), the Microsoft website states IE 11 is retiring on June 15, 2022, and the only WebDrivers on offer are for Windows 8.1. Although those might work, no builds are provided for Win 10/11. This makes me think IE 11 should be removed from the default browser list.

**Comment by joeyparrish** [comment]
Agreed!  Sorry we overlooked that when we removed other aspects of IE support from the project.

**Comment by RaymondCheng** [comment]
I can have a PR for this shortly.

**Comment by joeyparrish** [comment]
Thanks!
