### ISSUE TITLE
Bad rendering for non-zero textStrokeWidth cue property

### ISSUE THREAD

**Issue by toschlog** [shaka-project/shaka-player#4280]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.1.0

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Have not tried

**Are you using the demo app or your own custom app?**

Custom app

**If custom app, can you reproduce the issue using our demo app?**

Have not tried

**What browser and OS are you using?**

Castlabs ECS version of Electron v10.4.7 on Windows

**What are the manifest and license server URIs?**
 
See attached manifest (MPD) and subtitle (TTML) files.

The TTML file contains `tts:textOutline="#000000 2px"` in the style section that translates to `textStrokeWidth: '2px'` in the cues.

**What did you do?**

Played Billions S1E1 from Amazon in Hearo, using UITextDisplayer for subtitles.

**What did you expect to happen?**

The subtitles should be legible :)  Here's what they look like when viewing on Amazon.com:

![Billions S1E1 on the Amazon com web page](https://user-images.githubusercontent.com/25090868/172505307-868fb959-71cf-4506-8ca1-56cb5723fb44.PNG)

**What actually happened?**

Here's what the subtitles looked like in Hearo:

![Billions S1E1 in Hearo](https://user-images.githubusercontent.com/25090868/172505319-00ecf87a-63ef-43c1-97a8-77d9cca340f5.PNG)

I've hacked around this by deleting the textStrokeWidth property from every cue.

[billions.mpd.txt](https://github.com/shaka-project/shaka-player/files/8857301/billions.mpd.txt)
[billions.ttml.txt](https://github.com/shaka-project/shaka-player/files/8857513/billions.ttml.txt)

**Comment by avelad** [comment]
@theodab if I remember correctly, you implemented this property, can you take a look at it?

**Comment by toschlog** [comment]
Interestingly, the disneyplus.com web player has a subtitle options menu that can produce similarly ugly text:

![image](https://user-images.githubusercontent.com/25090868/173142499-3ae284c0-2147-4338-b7e7-1fcb21ed2585.png)

If you select a large enough font size, however, it looks ok.

**Comment by avelad** [comment]
According to previous comment, it's a configuration issue (font size), so I'm going to close the issue. Thanks!
