### ISSUE TITLE
How to use thumbnail generation with HLS 

### ISSUE THREAD

**Issue by ShivamJoker** [shaka-project/shaka-player#4281]
I saw some PRs for thumbnail generation while we seek through the timeline.
I was unable to find any docs which tells us how we can integrate it.

It would be great if someone could provide a demo with source code example

**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.1.0

**Comment by ShivamJoker** [comment]
@avelad I know about the `getThumbnails` API but I am not sure how can we display it on the timeline when someone scrubs through it. 

Do we need to manually implement our own logic?
Also I am not sure what would be the idea format for generating HLS format.

**Comment by avelad** [comment]
The API mainly returns a URL, you have to take care of rendering that image in the proper position and size.

The best format to use is jpeg.
For HLS, Roku has a very interesting guide that can help you: https://developer.roku.com/en-gb/docs/developer-program/media-playback/trick-mode/hls-and-dash.md# hls-considerations

**Comment by joeyparrish** [comment]
I would love to see thumbnail support for scrubbing added to our UI layer, but nobody is working on a PR for that as far as I know.  Volunteers are welcome!

**Comment by ShivamJoker** [comment]
@joeyparrish I can give it a shot later if you could give some pointers on where and how to start.

**Comment by avelad** [comment]
@ShivamJoker Please see: https://github.com/shaka-project/shaka-player/issues/3371 
If you want we can continue the discussion in that ticket. Thanks!
