### ISSUE TITLE
Subtitle text isn't centered using UITextDisplayer

### ISSUE THREAD

**Issue by toschlog** [shaka-project/shaka-player#4282]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.1.0

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Have not tried

**Are you using the demo app or your own custom app?**

Custom app

**If custom app, can you reproduce the issue using our demo app?**

Have not tied

**What browser and OS are you using?**

Castlabs ECS version of Electron v10.4.7 on Windows

**What are the manifest and license server URIs?**

See attached manifest (MPD).  The subtitle data is embedded in the segments and I'm not sure how to get to it.

**What did you do?**

Played "Star Trek: Strange New Worlds" S1E5 in Hearo.

**What did you expect to happen?**

The subtitles should be centered.  Here's a sequence as seen in the player on paramountplus.com.

![good1](https://user-images.githubusercontent.com/25090868/172675815-05502dbf-8c65-4b1d-a268-0f0683113807.PNG)
![good2](https://user-images.githubusercontent.com/25090868/172675822-89bd3803-ec8d-428d-a7f4-547a7b12c141.PNG)
![good3](https://user-images.githubusercontent.com/25090868/172675823-ef23894b-d6f0-4253-84c8-913c44b40713.PNG)
![good4](https://user-images.githubusercontent.com/25090868/172675826-c9c2c8bf-81a3-413f-bd68-bfb03d5b463e.PNG)
![good5](https://user-images.githubusercontent.com/25090868/172675828-f1d48714-b4e6-4046-90cd-4eeb654bc746.PNG)

**What actually happened?**

The subtitles jump around.  Here's the same sequence in Hearo.

![bad1](https://user-images.githubusercontent.com/25090868/172678893-688fcc0f-6c5e-4bb9-95d4-a7e582377b7e.PNG)
![bad2](https://user-images.githubusercontent.com/25090868/172678894-cf5bd89c-7074-46ce-80c3-eefd84fcfc63.PNG)
![bad3](https://user-images.githubusercontent.com/25090868/172678898-e78f3063-179d-491a-8495-18ff4f0cfe3e.PNG)
![bad4](https://user-images.githubusercontent.com/25090868/172678896-a8c2e31c-1133-401e-9316-ffc8ec34165f.PNG)
![bad5](https://user-images.githubusercontent.com/25090868/172678897-81380349-5034-4232-9f2f-14f44c79706e.PNG)

This sequence starts at 34:24.

What's going on is that the `size` value for each cue is different.  Here are the values for those five lines:

60 a way to blow off some steam
65  to do something risky...
48 to break the rules
58 only we make the rules
15 bingo

If I bash the size values to 100, the titles are centered.

It seems that paramountplus.com is changing the size of the text area according to the `size` value, but always drawing the area itself centered.  Shaka Player, on the other hand, is drawing the text area all the way to the left. (Not that they're not *all the way* to the left in the images because I set the shaka-text-container div to be 25px in from the edge of the video.)

It's possible that Shaka Player is doing the right thing here, but I don't think so.  I looked at "The Queen's Gambit" on Netflix and all its cues have a size value of 80.  That's resulting in the titles in Shaka Player being a bit to the left of center.  Again, bashing that value to 100 results in centered titles.

[star_trek.mpd.txt](https://github.com/shaka-project/shaka-player/files/8864364/star_trek.mpd.txt)

**Comment by avelad** [comment]
Please, provide the URL of the manifest (HTTPS) or provide the failing subtitle file (WebVTT or TTML). Thanks!

**Comment by toschlog** [comment]
@avelad I've attached one of the segment M4S file.  Is that helpful?  (Note that the file isn't really a text file, but Github won't accept an M4S file.)

[seg.m4s.txt](https://github.com/shaka-project/shaka-player/files/8892565/seg.m4s.txt)

**Comment by joeyparrish** [comment]
Is the stream self-initializing?  If not, we might also need an init segment to concatenate with that.

**Comment by joeyparrish** [comment]
I see that it's a VTT in MP4 segment.  The parser needs an init segment to get timescale information, which is necessary to interpret the timestamps in the MP4 text segment.  I did a hex dump of the m4s segment, and I see that the init segment boxes are missing from it, so we will also need the init segment in order to ingest the text segment.

**Comment by toschlog** [comment]
See attached.  Hopefully that's what you need.

[init.m4v (1).txt](https://github.com/shaka-project/shaka-player/files/8919899/init.m4v.1.txt)
[init.m4v (2).txt](https://github.com/shaka-project/shaka-player/files/8919900/init.m4v.2.txt)
[vtt_init.m4v.txt](https://github.com/shaka-project/shaka-player/files/8919905/vtt_init.m4v.txt)

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!

**Comment by toschlog** [comment]
The subtitles are centering correctly with 4.3.4.  Thanks!
