### ISSUE TITLE
Player stalls when playing multi-period live DASH with CDN failover

### ISSUE THREAD

**Issue by echoy-harmonicinc** [shaka-project/shaka-player#4283]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** v4.0.1

**Please ask your question**

I have setup two DASH streams, assuming:
- Stream A: example-01.com/manifest.mpd
- Stream B: example-02.com/manifest.mpd
- CDN: cdn-example.com/manifest.mpd

The CDN will automatically switch from A to B if A fails

Spec:
- Absolute timestamp enabled
- Multi-period live stream
- Both streams have same representation IDs

Scenarios:
- When I have period IDs from A and B in sync, playback is smooth after failover
  - In sync here means playing period 1 in A is same as playing period 1 in B
- When I have period IDs totally out of sync, playback is also smooth
  - Manifest A has periods [2,3,4,5,6], while B has [12,13,14]
  - Period 6 in A -> failover -> Period 14 in B -> still plays fine
 - When I have them "partially" in sync, player stalls
   - Manifest A has [1,2,3,4,5,6], while B has [1,2]
   - Period 6 in A -> failover -> Period 2 in B -> stalls

The only error I get is:
`Assertion failed: Should not see evicted segments after available segments`

I'm planning on fixing such issue but no idea yet

**Comment by echoy-harmonicinc** [comment]
Found that when there's same period ID with totally different segments, the segment indices will have mixed references from both old and new manifests. The index order is also wrong, causing get() to return the wrong segment reference.

I'm planning on adding checks before returning reference from the iterator (perhaps checking the time required against the startTime and endTime in the returned segment reference). Please leave a comment if you have any better idea.

Screenshot for reference: 
(Logged the segmentIndex when calling segmentIndex.get)
(note #0 and #1, where #0 is from same period ID but old manifest and #1 is from new)
![Screenshot 2022-06-09 at 14 18 25 copy](https://user-images.githubusercontent.com/88302346/172981046-beddf71f-887b-4a50-aa4c-ac5567a33ac0.png)

**Comment by joeyparrish** [comment]
> When I have them "partially" in sync, player stalls
> * Manifest A has [1,2,3,4,5,6], while B has [1,2]
> * Period 6 in A -> failover -> Period 2 in B -> stalls

I could be wrong, but I think this is outside of what's allowed in the DASH IOP.  Period IDs are meant to be unique and stable throughout the presentation.  So I believe your CDN failover needs to be fixed to account for that.

**Comment by echoy-harmonicinc** [comment]
@joeyparrish thanks for the feedback. I wonder if that's a good idea to check the time range from the returned segment reference from segment iterator against the presentation time required. Then if it's not within the range, I'll assume the segment iterator/indices/references are invalid, and do the followings:
- Clear the period combiner in dash_parser
- Period combiner variants will be updated by the new manifest
- Getting variants from the period combiner
- Replace the old variants with the new ones in ABR manager
- Get the suitable variant from ABR manager
- Call switchVariant in streaming engine

Although the playback works after the above actions, I'm not sure whether such fix is appropriate/considered good practice.

**Comment by echoy-harmonicinc** [comment]
![DASH Failover drawio (1) (1)](https://user-images.githubusercontent.com/88302346/175862109-b730fac1-a447-42ba-9722-ec266da55a85.png)
Maybe the figure will describe the issue better:

1. Assume period 1 has 2 segments and evicted
2. We are playing Period 3 Segment 6 (Index #5, 6th segment overall)
3. At t = 9, failover triggered
4. We want to get the next segment with index #6
5. There are only 2 segments in period 1, 4 segments in period 2
6. New index = (6 - 2 - 4) = period3[0] = 1st segment, period 3
7. Yields Segment 5'
8. We get incorrect segment 5', instead of segment D'
9. Player stalls, and also segment requests return 404 error

**Comment by joeyparrish** [comment]
I don't think that's something we want to do in mainline Shaka Player.  If your content is well outside of DASH IOP guidelines and the change to support it is non-trivial, our policy is generally to reject those changes.

You may choose to maintain your own fork of Shaka Player to do as you described, but I would recommend instead that your encoder should be fixed to comply with DASH IOP.  The key phrase in **IO**P is "**I**nter**o**p".  You can do a lot within the DASH spec, but if you want your encoder to interoperate with other off-the-shelf components like Shaka Player, you need to restrict your content in certain ways to make that more feasible.

We apologize for any inconvenience this may cause you.
