### ISSUE TITLE
How to manage quality in video HLS in iOS/Safari?

### ISSUE THREAD

**Issue by adrics97** [shaka-project/shaka-player#4285]
I have made a player with shaka in a webview in flutter but I have problems to handle the different qualities of the video in safari iOS, this is because safari use native Hls built. But when I do shaka.Player.isBrowserSupported() is true, and i can play the video with automatic quality. I want to manage the differents streams of my .m3u8 file. When I do some functions like getManifest() or getVariantsTracks() is null or incomplete. How is the way to manage my differents streams in iOS/safari ?, with the video tag? 

I tried with the straming.useNativeHlsOnSafari to false, but i have the same problem. There must be some way to handle such qualities in safari or iOS because youtube does allow it.

**Comment by avelad** [comment]
In Safari streaming is handled by Apple's player. It is not possible to do what you want.
