### ISSUE TITLE
UITextDisplayer isn't updating the vertical position for subtitles with line breaks

### ISSUE THREAD

**Issue by toschlog** [shaka-project/shaka-player#4288]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.1.0

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Have not tried

**Are you using the demo app or your own custom app?**

Custom

**If custom app, can you reproduce the issue using our demo app?**

Have not tried

**What browser and OS are you using?**

Castlabs ECS version of Electron v10.4.7 on Windows

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```config.textDisplayFactory = () => new shaka.text.UITextDisplayer(document.getElementById("shaka-video-element"), videoContainerRef.current)```

(Except that I'm actually creating my own displayer that calls down to UITextDisplayer.  This is so I can hack the cues in the `append` function.)

**What are the manifest and license server URIs?**

See the attached manifest and the VTT for the relevant segment.

**What did you do?**

Watched the Eternals on Disney+.

**What did you expect to happen?**

I expected the subtitles to be drawn on-screen.  Here's what I see using the default subtitles (that is, not specifying a `textDisplayFactor` in config ).

![good1](https://user-images.githubusercontent.com/25090868/173136522-abf8d606-4968-431a-ada7-bb6efe456a57.PNG)
![good2](https://user-images.githubusercontent.com/25090868/173136523-89ed2094-99bb-4e8b-ae51-541f73a0692b.PNG)

**What actually happened?**

For titles with an embedded newline, the second line is cut off.  Like this:

![bad1](https://user-images.githubusercontent.com/25090868/173137302-8cbaa2b5-38d4-41de-a446-c6da930c7410.PNG)
![bad2](https://user-images.githubusercontent.com/25090868/173137303-90c6f342-cc7e-426c-9cf3-d5a2b39bc7d2.PNG)

All the titles in this film have a `line` value of 95.  It appears that the default text displayer adjusts that when the cue payload has newlines in it.

I'm hacking around this by counting the number of newlines in the cur and doing `cue.line -= 8 * newlineCount`.  Note that I'm also doing `cue.lineAlign = "start"` to get around a different bug.

[manifest.mpd.txt](https://github.com/shaka-project/shaka-player/files/8881776/manifest.mpd.txt)
[seg_00018.vtt.txt](https://github.com/shaka-project/shaka-player/files/8881777/seg_00018.vtt.txt)

**Comment by toschlog** [comment]
I think this may not be a Shaka Player issue after all.  I looked at "Star Trek: Strange New Worlds" on Paramount+ and it has different values for `line` when there are line breaks in the text.  But "The Eternals" on Disney+ is using the same value for all lines.  So I think that the Disney+ web player is adjusting for this in a non-standard way.

If this is the case, then it's probably best if I continue using my hack and applying it only to Disney+.

**Comment by joeyparrish** [comment]
Okay.  If you think it's not a Shaka issue, we can close it.  If you need to open this issue again before it expires and gets locked, just put `@shaka-bot reopen` in a comment.  Thanks!

**Comment by toschlog** [comment]
Clarification:  It was my bashing the lineAlign value that was causing this problem.  So I believe that https://github.com/shaka-project/shaka-player/issues/4247 is still an issue, but this item is completely bogus.  Sorry about that.
