### ISSUE TITLE
Multiple TTML captions are being aggregated into a single line of text

### ISSUE THREAD

**Issue by littlespex** [shaka-project/shaka-player#4301]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.x, 4.0.x, 4.1.x

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
MacOS 11.6.6, all browsers. Tizen and webOS.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Available upon request

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

- Load a stream with segmented TTML
- Enable captions via `selectTextTrack(track)` and `setTextTrackVisibility(true)`

**What did you expect to happen?**
Captions appear one cue at a time according to the time values provided in the TTML.

**What actually happened?**

All captions for a given segment are concatenated into a single cue point, ignoring the `begin` and `end` time attributes provided in the TTML.

![Screen Shot 2022-06-14 at 11 46 19 AM](https://user-images.githubusercontent.com/1508707/173670914-44447015-a6b8-43c9-b0c8-72e7546c0297.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ebutts="urn:ebu:tt:style" ttp:timeBase="media" xml:lang="en" ttp:cellResolution="50 30">
	<head>
		<styling>
			<style xml:id="paragraphStyle" tts:fontStyle="normal" tts:fontSize="125%" tts:lineHeight="normal" ebutts:linePadding="0.5c" tts:fontFamily="monospace" tts:color="#ffffff" tts:textAlign="center" tts:wrapOption="noWrap" />
			<style xml:id="textStyle" tts:backgroundColor="#000000" tts:color="#ffffff" />
		</styling>
		<layout>
			<region xml:id="speaker" tts:origin="10% 10%" tts:extent="80% 80%" tts:overflow="visible" tts:displayAlign="after" />
		</layout>
	</head>
	<body style="paragraphStyle">
		<div>
			<!-- text-based TTML -->
			<p xml:id="s0" begin="666:45:05.991" end="666:45:07.926" region="speaker">
				<span style="textStyle">I was really worried</span>
			</p>
			<p xml:id="s1" begin="666:45:08.059" end="666:45:10.462" region="speaker">
				<span style="textStyle">
					that you were
					<br />
					gonna be, like, mad.
				</span>
			</p>
			<p xml:id="s2" begin="666:45:10.595" end="666:45:11.529" region="speaker">
				<span style="textStyle">
					Mad?
					<br />
					Oh, my God.
				</span>
				PPl
			</p>
			<p xml:id="s3" begin="666:45:11.663" end="666:45:11.995" region="speaker">
				<span style="textStyle">Are you kidding me?</span>
			</p>
		</div>
	</body>
</tt>
```

**Comment by joeyparrish** [comment]
It looks like line breaks are not starting a new line as they should.

**Comment by littlespex** [comment]
It seems like the times are incorrect as well. According to the video's `currentTime`, only the first caption should be rendered in the attached screenshot.

**Comment by littlespex** [comment]
I'm not sure. The stream we used to create the issue no longer exists. I have to track down a new one.

**Comment by avelad** [comment]
@littlespex I tested the TTML file included in the descripcion and now the text is rendered correctly.

**Comment by littlespex** [comment]
Great!  We can close this issue.
