### ISSUE TITLE
DownloadHeadersReceived EVENT doesn't fire on HLS live stream?

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4304]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v3.2.2

**Please ask your question**
I am using "DownloadHeadersReceived" event to get the information of what player is downloading for the analytics purpose.

I have observed that the event is only fired while playing DASH live streams and not when playing HLS live streams!!

For dash live stream it is continuously fired to fetch Manifest but...

The event is only fired when on Safari to request a DRM license.
How can I trace the fetch of playlist or TS segments with the event in the player? is it possible?

Can you give me an explanation for why it doesn't work? Or a solution to make it work on HLS Live streams?

**Comment by joeyparrish** [comment]
Are you using Safari?  Native HLS on Safari is the default, IIRC, and native HLS means the browser internals are making the requests.

**Comment by joeyparrish** [comment]
Correct.  When using native HLS, the browser makes all the requests below the level of JavaScript, and therefore Shaka would not be able to inform you about any details of those requests, nor let you view or modify them in filters.  The only requests Shaka makes in native HLS are DRM license requests.

Does this help?

**Comment by hiren3897** [comment]
Thanks it helps :)
