### ISSUE TITLE
Polyfill lib/polyfill/videoplaybackquality.js Not working on LG WebOS

### ISSUE THREAD

**Issue by samueleastdev** [shaka-project/shaka-player#4313]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

Shaka: 4.1.1

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Basic custom setup

**If custom app, can you reproduce the issue using our demo app?**

Just testing with this: https://shaka-version-test-latest.s3.amazonaws.com/test2.html

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

LG WebOs 3.5 to 3.9 TVs

**What did you do?**

Run the url above on an LG TV WebOS and it will give this error.

<img width="1212" alt="Screen Shot 2022-06-22 at 5 54 56 PM" src="https://user-images.githubusercontent.com/1894778/175252757-cb0c32e4-3cfc-456a-81e3-64f47e4c1f70.png">

Seems the Polyfill for https://developer.mozilla.org/en-US/docs/Web/API/VideoPlaybackQuality doesnt seem to work for this device.

Shaka Polyfill: https://shaka-player-demo.appspot.com/docs/api/lib_polyfill_videoplaybackquality.js.html

Was just wondering if there is a workaround the TV navigator.userAgent says 
```
Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 WebAppManager 
```

Thanks

**Comment by avelad** [comment]
I have been checking and it seems that in old versions of Chrome it is not included in the prototype but it is included in the video element itself, that's why it fails in WebOS 3.X.

**Comment by gitvids** [comment]
Thank you 👍🏻

**Comment by samueleastdev** [comment]
Thanks you 👍🏻
