### ISSUE TITLE
Getting 4012 and 5005 error code while running playback on Playstation 5

### ISSUE THREAD

**Issue by jaskarancodes** [shaka-project/shaka-player#4314]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
2.5.10

**Please ask your question**
Hey Team 
We are running multi-key and multi-period dash content with Playready DRM on PlayStation 5. When we are running 4K streams we get 4012 which leads to 5005 and then 3016 error codes giving InvalidStateError (the playback sometimes starts for 1-2s before giving the 3016). When we run the playback with FHD and HD content we get 4012 error but the stream starts playing. I can see that we are getting missing keys in 4012 error code detail block, is it due to some keys being missing in the license ? What are these missing keys ? 
We are running H265 content which is supported by Playstation 5 and using SL3000 for 4K and SL 2000 for generating licenses.

Please help us debug this issue. 
[Attached the errors]
![4K -PS-4012](https://user-images.githubusercontent.com/34194550/175320773-788e0932-cb57-44ea-b367-25f98b150a77.png)
![4K-PS-5005](https://user-images.githubusercontent.com/34194550/175320785-38cc2bea-85f1-430d-adc4-a6663e0e2270.png)
![4K-PS-Error](https://user-images.githubusercontent.com/34194550/175320791-5e5b26f2-b5cc-4d9d-9653-4b4c7f5d5b82.png)
![4K-PS-3016](https://user-images.githubusercontent.com/34194550/175320779-cdf2e45a-9d2e-49ac-84ee-836cc8e40bf1.png)

**Comment by joeyparrish** [comment]
> Please help us debug this issue.

We will try to support you via GitHub as much as we can, but we don't have a PS5 and PS5 is not an officially-supported platform.  That means we can't do any debugging directly, and it is up to the larger community to make and verify any changes necessary for PS5.

> I can see that we are getting missing keys in 4012 error code detail block, is it due to some keys being missing in the license ? What are these missing keys ?

Yes, that's exactly right.  Quoting [the docs on error 4012](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:4012):


> name | number | description
> --- | --- | ---
> RESTRICTIONS_CANNOT_BE_MET | 4012 | There exist some streams that could be decoded, but restrictions imposed by the application or the key system prevent us from playing. This may happen under the following conditions:<br><br> • The application has given restrictions to the Player that restrict at least one content type completely (e.g. no playable audio).<br> • **The manifest specifies different keys than were given to us from the license server.**<br> • The key system has imposed output restrictions that cannot be met (such as HDCP) and there are no unrestricted alternatives.<br><br>`error.data[0]` is a `shaka.extern.RestrictionInfo` object describing the kinds of restrictions that caused this error.

In this case, the restrictions object in `error.data[0]` contains the exact key IDs that are specified in the manifest, but missing from the license.  See `error.data[0].missingKeys`, specifically, and the docs for [`RestrictionInfo`](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.RestrictionInfo).

Here is a snippet of your screenshot showing where the missing key IDs appear:

![Screenshot snippet](https://user-images.githubusercontent.com/6843156/176016753-512f8ab0-4d05-4cf8-b321-bd46763c0f47.png)

Does this help?

**Comment by jaskarancodes** [comment]
@joeyparrish https://github.com/shaka-project/shaka-player/commit/92b9f25539dc9d754f29a75e7ab37a6e6d8ec656 change fixes the 4012 error but even after the change, I am getting 3016 error code for 4K streams. 

It seems to be that the player has issues running SL 3000 content. I am able to play FHD SDR content but not able to play FHD HDR/ 4K content.

**Comment by joeyparrish** [comment]
Error 3016 is a decoder error, and decoders are part of the platform rather than the JS player.  You'll need to check your content encoding against whatever the PS5 decoders support.  Often times a hardware decoder or hardware DRM can be limited in what profiles, framerates, bitrates, etc they support.  I have neither a PS5 nor any documentation for what they support, so I don't believe I'll be able to help you with that in any detail.

Is there anything else I can do for you?

**Comment by jaskarancodes** [comment]
What we have figured out so far is we are able to play SL2000 content on the PS5 but to run 4K we need SL3000. We are following up with Sony to get this rectified.
