### ISSUE TITLE
[PARAMOUNT GLOBAL] - PS4 - Unable to Parse VTT Cues Markup

### ISSUE THREAD

**Issue by agajassi** [shaka-project/shaka-player#4321]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, I have. I searched for duplicates and couldn't find any

**What version of Shaka Player are you using?**
3.2.1 and up

**Can you reproduce the issue with our latest release version?**
N/A

**Can you reproduce the issue with the latest code from `main`?**
Not directly from main but from this [PR](https://github.com/shaka-project/shaka-player/pull/4320), because without it I don't get playback. See [issue/4315](https://github.com/shaka-project/shaka-player/issues/4315) ticket.

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Recently released WebMAF 3.0.1 for Play Station 4

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
WebMAF/v3.0.1-rc-6-g6b785d8b
SDK Version: 9.5

**What are the manifest and license server URIs?**
I will need to email. It is not a clear asset. 

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default configuration. Using it as is.

**What did you do?**
1. Put together a simple html page with Shaka player 4.1.1 and autoplay attribute in
2. Packaged using WebMAF 3.0.1 packager provided to me by Sony
3. Loaded package onto PS4
4. Started playback
5. Enabled captions

**What did you expect to happen?**
I expected it render captions properly on the screen

**What actually happened?**

Captions were not properly displayed, because of parsing error.
```
VTT parser encountered an invalid VTT setting:
Decoded string contains an "unknown character" codepoint.  That probably means the UTF8 encoding was incorrect!
```
I wonder if this commit has anything to do with it:
https://github.com/shaka-project/shaka-player/commit/a72a1e91023a33c777a6001a64f818ea2e469914

![166094103-c132729e-f83c-4360-b02a-86ebf65f41d2](https://user-images.githubusercontent.com/12893220/176063570-7e90e776-7db2-4559-9b53-59154c2ebc03.png)

![166094069-3d7a7f77-c8fe-4bc6-95f5-3404dbcdb39b](https://user-images.githubusercontent.com/12893220/176063583-2679db6a-2a64-430b-8e59-3aaec6ba5ac6.jpeg)

**Comment by joeyparrish** [comment]
"stypmp4" is a clue for me that what you're seeing is actually an MP4 with VTT embedded, not a text-based VTT file.  Those are the bytes of a binary MP4 that happen to be UTF8.

I expect you'd see something similar on a desktop browser with the same content.  Is that the case?

**Comment by agajassi** [comment]
@joeyparrish On desktop or other devices same exact content (and other similar ones) don't exhibit the same issue. I just tried again to be absolutely sure.

**Comment by agajassi** [comment]
If I take the same page and swap out Shaka version from latest one to one of the older ones such as v3.0.1, then even on PS4 I cannot reproduce. Captions are properly rendered without any parsing errors

**Comment by avelad** [comment]
@agajassi Can you try to include? https://github.com/anonyco/FastestSmallestTextEncoderDecoder

**Comment by agajassi** [comment]
@avelad That is the first thing that came to my mind. I tried and it didn't work, like it does on Xbox unfortunately :( 

Not advocating for this change, but just out of curiosity I reverted back the changes in this commit https://github.com/shaka-project/shaka-player/commit/a72a1e91023a33c777a6001a64f818ea2e469914
and doing so corrected the issue described in this ticket. Maybe it needs a polyfil after all? 🤷🏼‍♂️

**Comment by avelad** [comment]
I've been thinking and maybe it would be good to include the commit https://github.com/shaka-project/shaka-player/commit/a72a1e91023a33c777a6001a64f818ea2e469914 as a fallback in case there is no TextDecoder, @joeyparrish , what do you think?

**Comment by agajassi** [comment]
@avelad 
Quick question. 
In that [PR](https://github.com/shaka-project/shaka-player/pull/4324), the one associated with this ticket, you are checking to see if `window.TextDecoder` is available. As Joey mentioned, you are doing this to eliminate the need for polyfil on some platforms such as Xbox. 

The problem with PS4/WebMAF is that `window.TextDecoder` is defined there, so it actually uses TextDecoder, but despite that it still unable to parse cues properly. 

To resolve this issue, we were thinking to exclude PS4 from that TextDecoder. Do you see any potential problems down the line with us doing that? 

`if (window.TextDecoder && !shaka.util.Platform.isPS4())`

I tested this above line, and it can confirm that it corrects the issue described in this ticket

cc: @dsparacio

**Comment by avelad** [comment]
@agajassi Since PS4 support is community based, if that solution is the right fit, please create a PR so we can review, comment, approve, and merge it. Thanks!

**Comment by agajassi** [comment]
@avelad sounds good. Thank you. Yes I will do it for both.
