### ISSUE TITLE
Apple Advanced HLS Streams from demo page do not work in Firefox

### ISSUE THREAD

**Issue by klipstein** [shaka-project/shaka-player#4325]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes

**What version of Shaka Player are you using?**

4.1.1

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `main`?**

I've used the following demo-page URLs:

- https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;forceTransmuxTS=true;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/apple-advanced-stream-ts/master.m3u8;panel=ALL_CONTENT;panelData=HLS,MP2TS;build=uncompiled;v
- https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;forceTransmuxTS=true;uilang=en-US;asset=https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8;panel=ALL_CONTENT;panelData=HLS,MP2TS;build=uncompiled;v

**Are you using the demo app or your own custom app?**

Demo app.

**If custom app, can you reproduce the issue using our demo app?**

Yes

**What browser and OS are you using?**

Mac OS X, Firefox Version 102. Also fails on Windows Firefox.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

not applicable

**What are the manifest and license server URIs?**

- https://storage.googleapis.com/shaka-demo-assets/apple-advanced-stream-ts/master.m3u8
- https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

No special configuration.

**What did you do?**

Opened:

- https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;forceTransmuxTS=true;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/apple-advanced-stream-ts/master.m3u8;panel=ALL_CONTENT;panelData=HLS,MP2TS;build=uncompiled;v
- https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;forceTransmuxTS=true;uilang=en-US;asset=https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8;panel=ALL_CONTENT;panelData=HLS,MP2TS;build=uncompiled;v

**What did you expect to happen?**

That no error 4032 appears in Firefox and playback is possible.

**What actually happened?**

I received the error 4032 and playback did not work.

**Comment by joeyparrish** [comment]
Firefox reports that it does not support raw AAC.  On Chrome, this returns `true`, but on Firefox, it returns `false`:

```js
MediaSource.isTypeSupported("audio/aac")
```

This is the root cause of the error, and unfortunately, the error is correct in this case.  Error 4032, `CONTENT_UNSUPPORTED_BY_BROWSER`, is accurate for Firefox.

**Comment by klipstein** [comment]
@joeyparrish thanks for your feedback. The background why I opened this issue was, that we switched from HLS.js to Shaka for our HLS streams, because we now also had to support DASH streams in our video player. And as we tried to play our standard HLS streams (AWS Elemental) within Shaka it worked well in all browsers other than Firefox. The example streams on the demo-page look very close to what we generate via AWS Elemental.

At the moment we stick to using HLS.js on Firefox and Shaka for all other browsers and it would be great if Shaka would also work with the mentioned manifests. I'm also asking myself what is HLS.js doing different to get them played back?

When you open the manifest URIs via HLS.js in Firefox they actually play:

- https://hls-js.netlify.app/demo/?src=https%3A%2F%2Fdevstreaming-cdn.apple.com%2Fvideos%2Fstreaming%2Fexamples%2Fimg_bipbop_adv_example_ts%2Fmaster.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==
- https://hls-js.netlify.app/demo/?src=https%3A%2F%2Fstorage.googleapis.com%2Fshaka-demo-assets%2Fapple-advanced-stream-ts%2Fmaster.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==

**Comment by joeyparrish** [comment]
I'll reopen to investigate.

My best guess is that hls.js will package the raw AAC into an MP4 container.  Firefox, like every other device/platform/browser, supports AAC in MP4.

Re-packaging content like that isn't something Shaka will do today, and I'm not convinced that it's something we _should_ do.  But I'll keep this open while we confirm whether that is the trick hls.js is using.  If so, and if that is an important feature for you, I will convert this into a feature request and would accept a PR to implement it.

Is raw AAC (not in an MP4 container) important for your application?

**Comment by joeyparrish** [comment]
I don't have any first-hand experience with Elemental, but I'll ask on [video-dev slack](https://video-dev.herokuapp.com/), as there are people there with a lot of experience I lack.

**Comment by joeyparrish** [comment]
Oh, also, we support TS transmuxing through mux.js already, so if you can switch to a TS container for audio, that should also work.

**Comment by joeyparrish** [comment]
Somebody on video-dev slack provided this screenshot of how to enable TS for audio:

![ts-audio](https://user-images.githubusercontent.com/6843156/180857686-f70653d3-7bcf-401d-b2d4-11ec5b5e1058.png)

They also said you can get MP4 by switching "HLS output" to "CMAF output".

Does this help?

**Comment by joeyparrish** [comment]
I think at this point, especially given that there is a setting in Elemental to produce a more modern HLS output (CMAF), we are uninterested in implementing repackaging of raw AAC to MP4 to work around what appears to be a bug in Firefox.  I'm going to relabel this issue accordingly.

**Comment by klipstein** [comment]
@joeyparrish thanks for the great help! Closing this ticket because the above details are sufficient in case someone else has the same issue.

**Comment by joeyparrish** [comment]
I'm glad we could help!  Or at least, that we could find people on Slack who could help.  :-)
