### ISSUE TITLE
Minimum Android OS version supported?

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4328]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.2.2

**Please ask your question**
Can you please tell us the minimum Android OS versions supported by Shaka-Player? 

Thanks

**Comment by joeyparrish** [comment]
I think it's more to do with the Chrome version than the OS version, since the player runs in the browser in JavaScript and doesn't touch the OS directly.

We test on the latest stable version of Chrome.  Any version of Android that is still updating Chrome should work.

**Comment by hiren3897** [comment]
Okay thanks for the info,
