### ISSUE TITLE
How to set Portrait videos using shaka player

### ISSUE THREAD

**Issue by krackjack234** [shaka-project/shaka-player#4331]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Please ask your question**
We want to use shaka player to play both landscape and portrait videos.
Wanted to check if there is any configuration in shaka player where we can set the correct aspect ratio.

**Comment by joeyparrish** [comment]
The player doesn't control the aspect ratio.  That is a feature of the content.

If your application sets size constraints on the video element in CSS, you might want to think about adjusting your CSS that to account for portrait mode.

And if you run into any specific issues in your implementation, please feel free to file another issue, and we'll be happy to help.

Thanks!

**Comment by krackjack234** [comment]
This can be closed. Thanks for your reply.
