### ISSUE TITLE
Dispatch a player event for client-side ad errors

### ISSUE THREAD

**Issue by sachaelkaim** [shaka-project/shaka-player#4335]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.3.5

**Please ask your question**
I would like to log google.ima.AdErrorEvent.Type.AD_ERROR on loading to my console and 
google.ima.AdErrorEvent.Type.AD_ERROR while playing ads, but I do not see any event listeners for this in the documentation.
Is there any way to call these event listeners to output messages on my console without using the Shaka debugger?

**Comment by joeyparrish** [comment]
It looks like we don't expose those events in any way today.  I'll convert this into a feature request.

If anyone is interested in adding that, please take a look at `onAdError_` in `lib/ads/client_side_ad_manager.js`.  This could dispatch events through the player via `this.onEvent_()`, and there are several examples of this in that file.

We recently started collecting event names into `shaka.util.FakeEvent.EventName`, and event types are documented at the top of `lib/player.js`.  So please use these when you add a new ad-error event to the player.

Does this help?
