### ISSUE TITLE
Sudden DRM fail after webos update

### ISSUE THREAD

**Issue by j-pedro-faria-alb** [shaka-project/shaka-player#4336]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
3.2.9

We have an app for LG Webos using the Shaka Player, it works like a charm. However a few days ago, after a webos update to a specific version 5.4.1-9 the player suddenly started to be unable to play content with DRM, throwing a severity 2, category6, code 6002 error 

The browser found one of the requested key systems, but it failed to create an instance of the CDM for some unknown reason.
error.data[0] is an error message string from the browser.

beeing data[0] = "data": [ Unable to create CDM ], "handled": false

We are a little at lost here, specially because on other versions of Webos and chrome, the player plays all the content without a problem.

The info we gathered so far was that this ill-fated Webos version uses chromium 68.

I will add more info in this ticket after the team does a bit more research on the topic.
If needed I can provide streams for testing purposes. 

Thank you in advance!

**Comment by joeyparrish** [comment]
I would recommend you ask LG or search LG docs for any information about changes in DRM.  Is it Widevine or something else?

**Comment by j-pedro-faria-alb** [comment]
Hi Joey, thanks for the quick reply.
Its just Widevine everything else works as it should. I will try to approach LG.
Thank you!

**Comment by kareldohnal** [comment]
@j-pedro-faria-alb Hi. If you have any thread open with LG or any response from them, could you share? We have the same problem at our company.

**Comment by j-pedro-faria-alb** [comment]
@kareldohnal we do have an open thread with LG. However they asked for our app and some other things so they could test on their end, since I am only a developer, i bubbled up the info to my superiors and am waiting for instructions.
I will keep this post alice tho
