### ISSUE TITLE
Freeze frame on media change

### ISSUE THREAD

**Issue by j-pedro-faria-alb** [shaka-project/shaka-player#4342]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
4

Is it possible to freeze a a frame when we change the source?
To better explain this, we are trying to minimize the sense of media switch. And working like the videoElement Poster, it would be interesting if we could use the exact same frame from the playing media to act as poster for the incoming media.

**Comment by theodab** [comment]
You could do something like this:

```js
const canvas = document.createElement('canvas');
canvas.width = video.offsetWidth;
canvas.height = video.offsetHeight;
const ctx = canvas.getContext('2d');
ctx.drawImage(video, 0, 0);
video.poster = canvas.toDataURL();
```

Some tweaking might be required to get the resultant poster to be the right resolution.

**Comment by j-pedro-faria-alb** [comment]
the solution I am searching is to have a snapshot from frame from a DRM secured content.

**Comment by joeyparrish** [comment]
DRM content often can't be read into a canvas.  There's nothing we could do about that.

**Comment by j-pedro-faria-alb** [comment]
thank you Joey.
Forgive me for insisting, but would there be a way to switch content avoiding the black loading screen? without a pre set poster image. Just hold pause up until the next stream starts.
Thank you

**Comment by joeyparrish** [comment]
If you have two video elements and players, and your application pauses one while it loads another, then yes, you could do this.  It would be up to your application to manage which video element is shown at any given time.

Does this help?

**Comment by j-pedro-faria-alb** [comment]
It is a valid idea for a browser. However we are developing for Webos and Tizen. These systems only allow for one player to work, being that, in the moment the second player starts to load data the system will kill the first player and originate a black screen "loading screen".

Thank you for the advice!

**Comment by joeyparrish** [comment]
Okay, well, I don't think there's anything else we can do.  Capturing a frame of a DRM video is restricted well below the level of the player.  Restrictions on multiple video elements are also out of our hands.

Sorry we couldn't do more!
