### ISSUE TITLE
Changes in Apple FairPlay integration in 4.1.1?

### ISSUE THREAD

**Issue by jakubkrolikowski** [shaka-project/shaka-player#4349]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.1.1

**Please ask your question**

I'm trying to upgrade from 3.3.7 to 4.1.1 and cannot make the player work with FairPlay DRM encrypted content.
I get this error message after video manifest is loaded:
```
  "message": "Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (The operation is not supported.,NotSupportedError: The operation is not supported.,)",
  "stack": "@https://ajax.googleapis.com/ajax/libs/shaka-player/4.1.1/shaka-player.ui.debug.js:181:806
@https://ajax.googleapis.com/ajax/libs/shaka-player/4.1.1/shaka-player.ui.debug.js:508:395
promiseReactionJob@[native code]"
```

My code looks like this, and it works great till 3.3.7.

```

const req = await fetch('https://lic.**********/license-server-fairplay/cert/*****');
      const cert = await req.arrayBuffer();

      player.configure('drm.advanced.com\\.apple\\.fps\\.1_0.serverCertificate',
                       new Uint8Array(cert));


      player.configure('drm.initDataTransform', function(initData) {
            const skdUri = shaka.util.StringUtils.fromBytesAutoDetect(initData);
            const contentId = skdUri;
            const cert = player.drmInfo().serverCertificate;
            return shaka.util.FairPlayUtils.initDataTransform(initData, contentId, cert);
        });
      
      player.getNetworkingEngine().registerResponseFilter((type, response) => {
          if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) {
          return;
        }
          let responseText = shaka.util.StringUtils.fromUTF8(response.data);
          responseText = responseText.trim();
          // Look for <ckc> wrapper and remove it.
          if (responseText.substr(0, 5) === '<ckc>' &&  responseText.substr(-6) === '</ckc>' ) {
            responseText = responseText.slice(5, -6);
          }
          // Decode the base64-encoded data into the format the browser expects.
          response.data = shaka.util.Uint8ArrayUtils.fromBase64(responseText).buffer;
          }
      );
 player.getNetworkingEngine().registerRequestFilter(function(type, request) {
        if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
          request.headers['x-dt-custom-data'] = b64;
        }
      });

```

I've noticed a lack of PatchedMediaKeysApple debug infos in the console, so I guess there is a significant change from 4.1.
With 4.1.1 the browser console looks like this:
![screenshotshaka](https://user-images.githubusercontent.com/12957758/179092716-138bdafb-1000-4a8c-9b4a-31fa7dd3099a.jpg)

What I'm doing wrong?

**Comment by joeyparrish** [comment]
I believe some code that was removed in an earlier release was restored in v4.1.2 by @avelad.  We apologize for the inconvenience.  Can you please try with v4.1.2 (released yesterday)?

**Comment by jakubkrolikowski** [comment]
I tested 4.1.2 immediately early morning, unfortunately, it's not fixed, 6006 error still:

```
{
  "severity": 2,
  "category": 6,
  "code": 6006,
  "data": ["The operation is not supported.", {
    "name": "NotSupportedError",
    "message": "The operation is not supported.",
    "stack": ""
  }, undefined],
  "handled": false,
  "message": "Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (The operation is not supported.,NotSupportedError: The operation is not supported.,)",
  "stack": "@https://cdn.jsdelivr.net/npm/shaka-player@4.1.2/dist/shaka-player.ui.debug.js:181:806
@https://cdn.jsdelivr.net/npm/shaka-player@4.1.2/dist/shaka-player.ui.debug.js:510:395
promiseReactionJob@[native code]"
```

**Comment by joeyparrish** [comment]
I made a mistake.  It looks like that was not cherry-picked to v4.1.  Can you please try with the latest nightly build?

https://nightly-dot-shaka-player-demo.appspot.com/

Or to load into your own app:

https://nightly-dot-shaka-player-demo.appspot.com/dist/shaka-player.compiled.js

**Comment by stuartflanagan** [comment]
Similar issue. FairPlay does not load license server after 3.3. Have updated to 4 to trial some fixes and now not seeing any license requests and result in 7000 error.
Reverting ShakaPlayer version to 3.2 returns FairPlay support.

**Comment by joeyparrish** [comment]
@avelad, can you take a look at this?  I am not very familiar with FairPlay.

**Comment by avelad** [comment]
@joeyparrish I’m on holidays until 9 August… sorry

**Comment by joeyparrish** [comment]
No worries!  Enjoy your holiday.

**Comment by joeyparrish** [comment]
@stuartflanagan, [error code 7000 is LOAD_INTERRUPTED](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:7000).  This should only be possible with conflicting inputs from the application (calling load, unload, detach, or destroy during an in-progress load).  It's possible that some internal timing has changed and some part of your application that happened to work with v3 just happens not to work with v4.  Are you awaiting the result of load() calls, or do you ignore the result?

The changes made to restore some missing FairPlay functionality are in the main branch and nightly demo build, and will be in the upcoming v4.2 release.  Is anyone able to confirm that whether or not they still have issues with the main branch or nightly demo build?

**Comment by stuartflanagan** [comment]
Hi @joeyparrish I will need to build the code to run it in our application.
I will give it a go next week.
I think you are right regarding the 7000 I will look into any un mounting of components while loading is occurring.

**Comment by NoChance777** [comment]
Hello there! We recently faced the same problem with shaka v4.1.2. DRM module fails to make a request and crushes with 6006 error

**Comment by fredrik-telia** [comment]
I had similar issues and ended up setting `useNativeHlsOnSafari: false` in the shaka config object (under `streaming: {` )

as well as changing all instances of `"com.apple.fps.1_0"` to `"com.apple.fps"` for the drm config object.

It might not be an option for you to set `useNativeHlsOnSafari` to false, but if you can, it might work.

**Comment by NoChance777** [comment]
Thank you @fredrik-telia. I will give it a try and let you know if your suggestion helps

**Comment by NoChance777** [comment]
So, unfortunately, the suggested solution doesn't work for me. Here is my config
![image](https://user-images.githubusercontent.com/16236036/182380574-38961c0a-32df-4fd8-9aa5-2bdb25cdc28e.png)

**Comment by fredrik-telia** [comment]
> BTW, what is the difference between "com.apple.fps.1_0" and "com.apple.fps"?

I believe it was from this change: https://github.com/shaka-project/shaka-player/commit/5441f932fd3da20f26da162cc0d49d0470689b41

So make sure you're running that code, I think it will be included in the upcoming 4.2.0 release, I probably should have mentioned that I had to build shaka from master in order to get drm working in Safari, sorry about that.

**Comment by NoChance777** [comment]
Actually, I tried a built from the master branch as well and got another error 6007 (LICENSE_REQUEST_FAILED), but it could be related to out DRM server. Thanks again!

**Comment by loicraux** [comment]
Guys,

FYI I just add the same issue (error 6006) : after shaka-player update from 3.2.9 to 4.1.2, video playback got broken with Fairplay in Safari MacOS v15.5.

I fixed it by using key system `com.apple.fps` instead of `com.apple.fps.1_0` AND by removing our `initDataTransform` function that it apparently not needed anymore.

My DRM provider is EZDRM and our legacy `initDataTransform` was the following :
```ts
function initDataTransform(initData: Uint8Array, initDataType: string, drmInfo: extern.DrmInfo | null): Uint8Array {
    if (drmInfo?.keySystem !== APPLE_FAIRPLAY_KEY_SYSTEM || initDataType !== 'skd') {
        return initData;
    }

    const certificate = drmInfo?.serverCertificate;
    assertIsDefined(certificate);
    const initDataAsString = util.StringUtils.fromBytesAutoDetect(initData);
    const contentId = initDataAsString.split(';').pop();
    assertIsDefined(contentId);
    return util.FairPlayUtils.initDataTransform(initData, contentId, certificate);
}
```

Now everything is working fine w/ version 4.1.2 on Safari MacOS v15.5 and also iOS Safari v15.4

**Comment by joeyparrish** [comment]
We are aware of the modularity problem, and it's a problem in some cases for us at Google, too.  Expect to see some work on that in Q1 or Q2 2023.  We've been building on this structure for [over six years now](https://github.com/shaka-project/shaka-player/commit/5cb3baa602a4cec72daf86d06d5d942243cdfb68), so it's not trivial to undo that.  The results will likely spawn a Shaka v5, since I don't think it's feasible to do it in a backward compatible way.

As for the inclusion of FairPlayUtils vs moving to docs/contrib, we debated that in https://github.com/shaka-project/shaka-player/pull/4309#discussion_r904176052, and this was the conclusion that @avelad, @littlespex and I ended up at.  If you want to exclude them, you may do that at build time in a custom build.  We understand that's not ideal for everyone.  The good news is that the compiled version of FairPlayUtils currently only adds [1998 bytes](https://github.com/shaka-project/shaka-player/files/9273616/fairplayutils.js.txt) to the build.

Thanks @loicraux for the pointers:
 - use key system `com.apple.fps` instead of `com.apple.fps.1_0`
 - remove `initDataTransform`

@jakubkrolikowski, do these tips help?

**Comment by NoChance777** [comment]
Hi @loicraux. Your solution helped me. Thank you very much!

**Comment by NoChance777** [comment]
Hi @joeyparrish! I followed suggested hints, and Shaka's behavior become even stranger. In most cases the player gives 3016 error, but occasionally it plays a live stream. The only working solution for us at the moment is using PatchedMediaKeysApple polyfill.

**Comment by avelad** [comment]
All this, in 4.2 will be solved since it is allowed to use the modern API and the legacy. We have to see if we can speed up 4.2 to avoid these issues. As soon as I get some time, I'll talk to @joeyparrish about this.

**Comment by joeyparrish** [comment]
I'll start preparing for bugfix releases and also v4.2.  Sorry for the delay!

**Comment by avelad** [comment]
@joeyparrish I think it would be good to include https://github.com/shaka-project/shaka-player/pull/4386 as well.

**Comment by joeyparrish** [comment]
I agree, but I'll need to check in with @theodab to see when that will be ready to merge.  Hopefully it will be ready soon and we won't have to delay v4.2 to include it.

**Comment by joeyparrish** [comment]
v4.2.0 is out now.

If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!

**Comment by avelad** [comment]
Please see https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html

**Comment by jakubkrolikowski** [comment]
@joeyparrish I just checked version 4.2.0 and applied these two changes:
- use key system com.apple.fps instead of com.apple.fps.1_0
- remove initDataTransform

and everything works very well, the problem is solved! Thank you!

**Comment by joeyparrish** [comment]
Awesome, I'm so glad to hear it!  Thanks to @avelad for working on this!
