### ISSUE TITLE
IMSC1 subtitles not working in a HLS stream

### ISSUE THREAD

**Issue by duggaraju** [shaka-project/shaka-player#4350]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
4.1.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Windows 11, Microsoft edge/chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://aka.ms/LowLatencyDemo.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

{
streaming: {
  autoLowLatencyMode: true
}
}
setTextTracksVisible(true) or select it from the UI.

**What did you do?**

Just play the stream

**What did you expect to happen?**
the captions should be downloaded and visible.

**What actually happened?**

The fragments of the captions are not getting downloaded and not displayed.

**Comment by joeyparrish** [comment]
The log is full of warnings like `(text:8) cannot find segment lookupTime: 3664.425235271454 presentationTime: 3666.425235271454`.
