### ISSUE TITLE
Can we find out if a device supports a particular codec?

### ISSUE THREAD

**Issue by kiran-dcunha** [shaka-project/shaka-player#4355]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.5

**Please ask your question**
Can we find out what codecs are supported by the platform? Something like shakaPlayer.isCodecSupportedOnDevice("mp4a")

**Comment by joeyparrish** [comment]
You have a few options:

1. Use web APIs directly, such as `MediaSource.isTypeSupported('audio/mp4; codecs="mp4a.40.2"')`
2. Use a method in Shaka meant for debugging: `await shaka.Player.probeSupport()` (pass optional `true` argument to get it to probe DRM, but this may result in prompts on some browsers)
3. If you want to do this to debug, but not in your live application, visit https://shaka-player-demo.appspot.com/support.html which calls `probeSupport(true)` and formats the output for you

Please note that you shouldn't need to probe codec support in a live application.  Shaka Player will negotiate with the platform at runtime to determine which tracks are playable.  There is generally no need to check codec support and load different content based on the results.  Instead, just have a single DASH manifest or HLS playlist containing multiple codecs, and let the player handle it.

Does this help?

**Comment by kiran-dcunha** [comment]
This helps! Thanks!
