### ISSUE TITLE
Multi-period manifest buffering between periods transition

### ISSUE THREAD

**Issue by macoo10** [shaka-project/shaka-player#4356]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. Similar issue: https://github.com/shaka-project/shaka-player/issues/4337

**What version of Shaka Player are you using?**
Latest: v4.1.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App 

**If custom app, can you reproduce the issue using our demo app?**
Yes, we can reproduce with the Shaka demo app. 

**What browser and OS are you using?**
Browser: Latest version of Brave: Version 1.41.96 Chromium: 103.0.5060.114
OS: macOS Monterey

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
We are not using embedded devices

**What are the manifest and license server URIs?**
Sent by email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default configuration since we are using the Shaka Demo App

**What did you do?**

We are in the process of enabling multi-period dash manifests for live content. All the platforms (Android,  Firestick, IOS) we tested work well but it's not the case for **Shaka (web)**.   The transitions are not smooth ->  we see small hiccups and buffering when switching  to a new period. During some periods, Shaka also complains about gaps in our manifest   _Jumping forward 0.0995328426361084 seconds because of gap starting at 1657889395.678565 and ending at 1657889395.744732_ . We have analyzed our manifest and we don't see any gap. 

We tried different Shaka configurations (ex:  _Gap detection threshold_ , _Stall Threshold_, _Safe Skip Distance_) but at the end the results were not good (video glitches, hiccups). 

1. Start the LIVE stream in the Shaka player demo
2. Wait to reach a commercial break (period)

**What did you expect to happen?**
We expect the transition between periods to be smooth 

**What actually happened?**
Buffering and Hiccups between the transitions.

Thanks,

**Comment by dilukd** [comment]
@macoo10  - Do you have a Chromecast receiver implementation on your apps and do you notice the same issue on there which uses Shaka with CAF (Chromecast Application Framework) ? 

We have something similar with Ad insertion that creates multi periods and have noticed similar observations to you.

**Comment by macoo10** [comment]
@dilukd, yes,  we noticed the same observations with Shaka and the CAF

But we think it’s related to shaka since we are able to reproduce the issue on the web as well.

**Comment by dilukd** [comment]
Yes agree.... @macoo10 . Same here

**Comment by jeanalexandre-iragne-deltatre** [comment]
I have the same issue

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!

**Comment by macoo10** [comment]
Hi, yes I confirm that we don't have the issue anymore with the latest version. 
I'm closing the ticket. Thanks for the fix.

**Comment by zuzzurro** [comment]
Would it be possible to know what exactly fixed the issue? For testing purposes and for potentially backward porting?
