### ISSUE TITLE
Wrong caption icon (including demo)

### ISSUE THREAD

**Issue by jakubkrolikowski** [shaka-project/shaka-player#4358]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.3x, 4.1.x

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
yes

**What did you do?**

I think the caption select icon in the overflow menu is set to "OFF" when it should be in "ON" mode.
When any subtitles track is selected the icon should be ON. Currently, icon says "captions are disabled" when they are not.
Look at Angel One demo:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/12957758/179314004-ea25def2-8996-4324-b56d-97af2dd530e1.png">

The bug is in shaka-player/ui/text_selection.js:

```
 onCaptionStateChange_() {
    if (this.player.isTextTrackVisible()) {
      this.icon.textContent =
          shaka.ui.Enums.MaterialDesignIcons.CLOSED_CAPTIONS_OFF; // here should be CLOSED_CAPTIONS
      this.button.ariaPressed = 'true';
    } else {
      this.icon.textContent =
          shaka.ui.Enums.MaterialDesignIcons.CLOSED_CAPTIONS; // here should be CLOSED_CAPTIONS_OFF
      this.button.ariaPressed = 'false';
    }

    this.controls.dispatchEvent(
        new shaka.util.FakeEvent('captionselectionupdated'));
  }
```

**Comment by joeyparrish** [comment]
Yes, I think you're right!  Would you care to make a PR to resolve this?

**Comment by kartikeyshaurya** [comment]
@joeyparrish @jakubkrolikowski   could i work on this

**Comment by jakubkrolikowski** [comment]
@kartikeyshaurya Yes, please, I'm out of office till August 22nd.

**Comment by joeyparrish** [comment]
@kartikeyshaurya, I assigned the issue to you.  You should always feel free to work on PRs without waiting for assignment, though.
