### ISSUE TITLE
4K content not working on Tizen 6.0

### ISSUE THREAD

**Issue by TavenCFC** [shaka-project/shaka-player#4360]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.1.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Tizen 6.0
Chrome 76

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
model: QE43Q65AAUXXH
firmware: T-NKLADEUC-2001.4

**What are the manifest and license server URIs?**

https://cdn.bitmovin.com/content/demos/4k/38e843e0-1998-11e9-8a92-c734cd79b4dc/manifest.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default configuration

**What did you do?**

Play the video. Select 4k variant track.

**What did you expect to happen?**
Video is playing.

**What actually happened?**

I am getting this error:
```
detail: Re
category: 3
code: 3016
data: (3) [3, undefined, ""]
handled: false
severity: 2
```
 I've tried playing other 4k videos (hls and dash) as well and I always get an error. This happens when ABR automatically starts a track, either I select the 4k track with a setSelectTrack method, or I can set restrictions > minHeight to 1600 or higher.

**Comment by TavenCFC** [comment]
Sintel 4k from Shaka Player demo page works fine on TV.
I also sent you an email with additional manifest URI which is not working.

**Comment by joeyparrish** [comment]
It looks like a decoder error from the platform (3016).  If the "Sintel 4k" from the demo works, what about your own content differs?  Profile?  Bitrate?  Framerate?  Some aspect of your content is causing the decoder to fail.

We don't have a Tizen 6 device to test with, so you will have to do the investigation yourself.  We will do our best to provide guidance.
