### ISSUE TITLE
Play HLS video using Shaka player and authorization header

### ISSUE THREAD

**Issue by venomone** [shaka-project/shaka-player#4367]
I just wanted to play a bit with Shaka-player, but I'm not able to get my video manifest to load, it seems. The player always displays error code 7002 as soon as I load the player.

               <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.1.2/shaka-player.compiled.js"></script>
                    <video>
                        <script>
                            var manifestUri = {{ playlist_url | json_string }};

                            function initApp() {
                                // Install built-in polyfills to patch browser incompatibilities.
                                shaka.polyfill.installAll();

                                // Check to see if the browser supports the basic APIs Shaka needs.
                                if (shaka.Player.isBrowserSupported()) {
                                    // Everything looks good!
                                    initPlayer();
                                } else {
                                    // This browser does not have the minimum set of APIs we need.
                                    console.error('Browser not supported!');
                                }
                            }

                            function initPlayer() {
                                // Create a Player instance.
                                var video = document.getElementById('video');
                                shaka.media.ManifestParser.registerParserByExtension("m3u8", shaka.hls.HlsParser);
                                shaka.media.ManifestParser.registerParserByMime("Application/vnd.apple.mpegurl", shaka.hls.HlsParser);
                                shaka.media.ManifestParser.registerParserByMime("application/x-mpegURL", shaka.hls.HlsParser);
                                var player = new shaka.Player(video);

                                // Attach player to the window to make it easy to access in the JS console.
                                window.player = player;

                                player.getNetworkingEngine().registerRequestFilter(function (type, request) {
                                    // This function filters manifest request and add custom headers:
                                    if (type == shaka.net.NetworkingEngine.RequestType.MANIFEST) {
                                        // This are headers to manifest requests:
                                        request.headers['Authorization'] = "{{ access_token }}";
                                    }
                                });

                                // Listen for error events.
                                player.addEventListener('error', onErrorEvent);

                                // Try to load a manifest.
                                // This is an asynchronous process.
                                player.load(manifestUri).then(function () {
                                    // This runs if the asynchronous load is successful.
                                    console.log('The video has now been loaded!');
                                }).catch(onError);  // onError is executed if the asynchronous load fails.
                            }

                            function onErrorEvent(event) {
                                // Extract the shaka.util.Error object from the event.
                                onError(event.detail);
                            }

                            function onError(error) {
                                // Log the error.
                                console.error('Error code', error.code, 'object', error);

                                alert(error.code);
                            }

                            document.addEventListener('DOMContentLoaded', initApp);
                        </script>
                    </video>

It is needed that for every request the player sends to the backend where the video is located, a JWT gets attached as Authorization header.
I already checked on error 7002, it indicates the following:

> The call to Player.load() failed because the Player does not have a
> video element. The video element must either be provided to the
> constructor or to Player.attach() before Player.load() is called.

So my guess here is that I'm simply processing the Authorization header wrong?
Is this the right way to attach a JWT to the request? Is it possible to not just make this for the Manifest request, but for all requests also for the segments?

Thanks in advance

**Comment by joeyparrish** [comment]
You seem to have overlooked the important parts of the documentation for that error code.  Let me highlight that for you:

> The call to Player.load() failed because **the Player does not have a
> video element.** The video element must either be **provided to the
> constructor** or to **Player.attach()** before Player.load() is called.

So if you construct a Player without a video element, you must provide one later in a call like:

```js
await player.attach(videoElement);
```

Or you can provide one when you construct the player:

```js
player = new shaka.Player(videoElement);
```

Since your code does this:

```js
  var video = document.getElementById('video');
  // ...
  var player = new shaka.Player(video);
```

My guess is that you will find `video` is `null`.  Please double-check that the call to `getElementById` is correct.

Does this help?
