### ISSUE TITLE
Does ShakaPlayer support SmoothStreaming with PlayReady

### ISSUE THREAD

**Issue by krackjack234** [shaka-project/shaka-player#4370]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Please ask your question**
We wanted to check if Shaka Player support Microsoft Smooth streaming with PlayReady.
We tried playing a valid MSS Drm stream on LG WebOS with Shaka Player
While the content played with LG's native player, Shaka throws the below error

Code: 4001
Severity: 2
Category:4

Thanks

**Comment by joeyparrish** [comment]
No, Shaka Player does not support Smooth Streaming at all.  It has been discussed many times, but never implemented, and nobody is currently working on it.

Does this answer your question?

**Comment by krackjack234** [comment]
Thanks.
