### ISSUE TITLE
Revert PR #4371 and find a long-term solution

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#4372]
PR #4371 is a temporary solution to make the project compatible with a future compiler version.  We should get access to that compiler internally, work to understand the nature of the errors it produces without these suppressions, and come up with long-term fixes.

Unfortunately, this can't be done with any current version of the open source compiler at this time.

**Comment by avelad** [comment]
Since our plan is to migrate to TypeScript, @joeyparrish, are you okay if we close this issue?

**Comment by joeyparrish** [comment]
Yes, sounds good.
