### ISSUE TITLE
Getting 4012 error code while running playback on Playstation 4 with playready DRM

### ISSUE THREAD

**Issue by Vasanthavanan-Devarajan** [shaka-project/shaka-player#4376]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
On both app error has occured

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
PS4 devkit running `WebMAF 3.0.1-0-g5cad6ac7`
SDK: 9.600.011

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```
"{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 10000,
      "stallTimeout": 30000,
      "connectionTimeout": 30000
    },
    "servers": {
      "com.microsoft.playready": ""
    },
    "clearKeys": {},
    "advanced": {
      "com.microsoft.playready": {
        "distinctiveIdentifierRequired": false,
        "persistentStateRequired": false,
        "videoRobustness": "",
        "audioRobustness": "",
        "sessionType": "",
        "serverCertificate": {},
        "serverCertificateUri": "",
        "individualizationServer": ""
      }
    },
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1,
    "preferredKeySystems": []
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 10000,
      "stallTimeout": 30000,
      "connectionTimeout": 30000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": false,
    "defaultPresentationDelay": 0,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
      }
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "ignoreImageStreamFailures": false,
      "useFullSegmentsForStartTime": false
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 10000,
      "stallTimeout": 30000,
      "connectionTimeout": 30000
    },
    "rebufferingGoal": 5,
    "bufferingGoal": 10,
    "bufferBehind": 5,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.1,
    "smallGapLimit": 0.5,
    "jumpLargeGaps": true,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2,
    "lowLatencyMode": false,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 1
  },
  "offline": {
    "usePersistentLicense": true
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 5,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    }
  },
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferredVideoCodecs": [],
  "preferredAudioCodecs": [],
  "preferForcedSubs": false,
  "preferredDecodingAttributes": [],
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null
}"
```

**What did you do?**
I have tried to play the Dash Manifest with Playready DRM.

**What did you expect to happen?**
Without throwing the `4012` error code. The playback has to start.

**What actually happened?**
When we tried to play the DASH manifest with Playrady DRM, at the time of playback start we are getting the `4012`
 error code from the shaka player. Though an error has occurred, the player can able to start the playback and continue playing.

**Error Details**
```
{"errorCode":4012,"errorMessage":"{"severity":2, "category":4,"code":4012,"data":[{"hasAppRestrictions":false,"missingKeys":["7ceceebf0248434289c2bbf79c0d9237"],"restrictedKeyStatuses":[]}],"handled":false,"message":"Shaka Error MANIFEST.RESTRICTIONS_CANNOT_BE_MET"}
```
Sony's implementation in Playstation 4 (WebMAF 3.0.1) seems to present key IDs as little-endian UUIDs, rather than big-endian (Just like Edge).

```
Standard: 7c ec ee bf - 02 48 - 43 42 - 89 c2 bb f7 9c 0d 92 37
PS4     : bf ee ec 7c - 48 02 - 42 43 - 89 c2 bb f7 9c 0d 92 37
````

**Comment by Vasanthavanan-Devarajan** [comment]
We included a patch to check for `PS4` or `Edge` in [drm_engine.js](https://github.com/shaka-project/shaka-player/blob/main/lib/media/drm_engine.js#L1551) and that fixed the issue for us. We are planning to submit a PR for the same.

**Comment by ArktekniK** [comment]
> We included a patch to check for `PS4` or `Edge` in [drm_engine.js](https://github.com/shaka-project/shaka-player/blob/main/lib/media/drm_engine.js#L1551) and that fixed the issue for us. We are planning to submit a PR for the same.

Hello! I've just been made aware of this issue. Would you mind also reaching out to the WebMAF team via PlayStation's dedicated support tracker so we can discuss the correct approach? The platform framework behaviour you've identified could affect other players beyond Shaka and it'd be worth addressing at the source.

Thanks

**Comment by joeyparrish** [comment]
Ah, the byte-swapped key IDs issue.  That will be hard to fix at a platform level without breaking apps that have already worked around it.  I believe that is why Edge never fixed it in "com.microsoft.playready".  I think it was fixed in "com.microsoft.playready.recommendation", which is more standards-compliant and which Microsoft put under a different ID for backward compatibility reasons.

**Comment by joeyparrish** [comment]
If you send a PR as you described, I would approve it.  If Sony ever puts out a fix, either they will do it under a different ID as Microsoft did, or we will have to detect the platform version from UA or some other means and make the workaround dependent on that.

**Comment by ArktekniK** [comment]
Hi - I've added some comments to the related PR here. Please let me know where's best to discuss
https://github.com/shaka-project/shaka-player/pull/4377#issuecomment-1209122962
