### ISSUE TITLE
Parsing and surfacing `prft` mp4 box information via player events

### ISSUE THREAD

**Issue by dave-nicholas** [shaka-project/shaka-player#4382]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Additional context**

We (SKY) would like to propose a change to the streaming engine in where we would parse and surface `prft` mp4 box information via a player event. We are happy to raise the PR.

**Is your feature request related to a problem? Please describe.**

We have a requirement for seeking to an exact date time within a live event (a goal for example). 
To do this we need to know the program start date (ProducerReferenceTime).
We want to be able to deduce the program start date of a live event using `PRFT` boxes.

**Describe the solution you'd like**

The `PRFT` box contains `ntp_timestamp` (a UTC time in NTP format corresponding to decoding_time) and `media_time` (the same time as ntp_timestamp, but in the time units used for the reference track, and is measured on this media clock as the media is produced.), we can use these values in conjunction with the timescale to calculate the program start date.

```
Program start date = (ConvertToUTC(ntp_timestamp) - (media_time / timescale))
```

- Shaka will surface a new player event `prft`
- The `prft` event will contain
```javascript
{
 wallclocktime, // a utc timestamp representation of the ntp_timestamp
 mediaTime, // media_time
 timescale, // the current timescale 
}
```
- Only the first video PRFT box would need to be surfaced
- To know the timescale we would need to add this value to the segment reference.
- The feature will be subscribe-able via feature flag on the streaming config

[example solution in our own fork](https://gist.github.com/dave-nicholas/6eccac115899e2479e7528d96248858b)

**Describe alternatives you've considered**

N/A

**Comment by joeyparrish** [comment]
That all seems reasonable.  I'm not sure if timescale should be on SegmentReference, but I don't have any other concerns.

Is SegmentReference where you put timescale due to potential timescale differences across periods/discontinuities?  If that's the case, could timescale live in InitSegmentReference, which is shared among all references in a period/discontinuity?  My understanding is that timescale is parsed from the init segment anyway.

**Comment by joeyparrish** [comment]
I'd like to find an agreement with you on timescale, but otherwise I think a PR for this would be great.

**Comment by dave-nicholas** [comment]
The only consideration that I had was timescale differences between bitrate, so `initSegmentReference` would work fine I think. I will get a PR together. Thanks.
