### ISSUE TITLE
Error 3018 when playing an HLS stream with SSAI ads

### ISSUE THREAD

**Issue by mivannikoff** [shaka-project/shaka-player#4392]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.1.2 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Are you using the demo app or your own custom app?**
Demo and custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Google chrome and macOS (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36)

**What are the manifest and license server URIs?**
The URL of stream has been sent to your email.

**What did you do?**
1. Open the demo player link from the email;
2. Start playing this stream;
3. Wait until the player gives error 3018 (Shaka Error MEDIA.TRANSMUXING_FAILED);

**What did you expect to happen?**
Stream playback without error

**What actually happened?**
We have a private HLS stream with SSAI ads, and when exiting the ad, player sometimes throws an error 3018 (Shaka Error MEDIA.TRANSMUXING_FAILED) and stops in Google Chrome browser, while everything works fine in Safari. I tried other players and there the stream plays without errors. Could you check this stream and suggest what could be the problem?

Thank you!

**Comment by joeyparrish** [comment]
If the content is being transmuxed, it must be MPEG2-TS.  Can you use MP4 (CMAF) instead?  (The transmuxer is a third-party library.)
