### ISSUE TITLE
Time between fetching DRM certificate till drmsessionupdate is fired, is much longer on chrome than safari

### ISSUE THREAD

**Issue by arroyoan1214** [shaka-project/shaka-player#4402]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.8

**Please ask your question**
We measured the time it takes in our DRM Flow. We measured from the time we make the certificate call until drmSessionUpdate is fired. This will be referred to as DRM_TIME_TO_INITIALIZE. 

We noticed that on Chrome (Widevine) DRM_TIME_TO_INITIALIZE is around 1.8s while on Safari (FairPlay) DRM_TIME_TO_INITIALIZEis around 0.9s.

On Widevine and FairPlay the Certificate fetch happens in about 0.25s and the license fetch happens in 0.15 seconds.

We are wondering why on Chrome the DRM_TIME_TO_INITIALIZE is much higher than that of Safari? We are looking for ideas on how to bring down the DRM_TIME_TO_INITIALIZE on Chrome?

Something else that we noticed was the time between the drmLicense being retrieved and the drmSessionUpdate event being fired was around 200 milliseconds on Chrome while on Safari it is about 1 millisecond. What processing is happening in shaka player while installing the license or generating a challenge?

We asked a similar question in this Archived [Issue](https://github.com/shaka-project/shaka-player/issues/3872). To answer the follow up question in that issue, yes we are setting a service certificate for Widevine through Shaka’s DRM config.

**Comment by joeyparrish** [comment]
The short answer is that I don't know.  In Safari and Chrome, in FairPlay and Widevine, the same DrmEngine logic is used.  Unless there are filters or other configurations installed by the application, no heavy or async processing should be happening on the license response in JavaScript.

If you see multiple requests to the Widevine license service, I would suspect that your service certificate setting is not working.

If you only see one request, and you don't have request or response filters, then I think any delay in the update must be happening inside the browser.  The EME API `MediaKeySession.update()` is an async method, and we await the result before dispatching the `drmsessionupdate` event.

I don't have visibility into what is happening in the Chrome CDM that might explain the delay, but I would guess it would have to do with inter-process communication, sandboxing, or other security measures applied to the user-land Widveine CDM.  I also assume that Safari has the benefit of OS-level protection for FairPlay, and so may be able to secure the CDM with less processing time.
