### ISSUE TITLE
Resolution disappear if network intermittent

### ISSUE THREAD

**Issue by kocoten1992** [shaka-project/shaka-player#4408]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
v4.1.2

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `main`?**
Probably.

**Are you using the demo app or your own custom app?**
Both.

**If custom app, can you reproduce the issue using our demo app?**
Yes.

**What browser and OS are you using?**
Google Chrome.

**What did you do?**
Go to, https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=uncompiled

Select a resolution (818 maybe), then Press `F12` open chrome dev tool, go to network tab and select `Offline`, wait about 20s, now check resolution on player, it all gone (see image below).

**What did you expect to happen?**
Resolution still there.

**What actually happened?**
Resolution disappear.

![image](https://user-images.githubusercontent.com/7130705/184785663-0f2d96c3-03de-4eb2-ac62-a55c08546bd6.png)

**Comment by joeyparrish** [comment]
Confirmed.  I think this has to do with a feature that was added to restrict tracks when requests start to fail.

**Comment by joeyparrish** [comment]
This issue affects all v4.1 and v4.2 releases.
