### ISSUE TITLE
canplaythrough vs buffering event

### ISSUE THREAD

**Issue by IsaacSNK** [shaka-project/shaka-player#4413]
Hi team. 

In the past we have use player engines that raise the _canplaythrough_ event themselves instead of letting the video element raise it. For Shaka, we don't see any reference to _canplaythrough_ being raised from the engine code. Therefore, we were wondering if we should rely on Shaka's buffering event (false) or the video element _canplaythrough_ event to tell when the video can start playing.

Thanks for any help you can provide.

**Comment by joeyparrish** [comment]
We have generally tried to avoid covering up the video element APIs.  This is why there's no "seek" API on Shaka Player.  You just set video.currentTime instead.

This is also the case for canplaythrough.  We don't cover it up or replace it.

We do generate buffering events, though, and you can rely on those if you want a signal on when the player is has buffered enough.

**Comment by IsaacSNK** [comment]
Thanks @joeyparrish. We have notice scenarios in Shaka where the buffering event (with false value) is triggered but HTMLMediaElement.readyState is not HAVE_ENOUGH_DATA (less than 4). We were considering using a combination of the buffering event false AND HTMLMediaElement.readyState == HAVE_ENOUGH_DATA  to accurately tell that the player is ready. Does it sound like a good idea?

**Comment by joeyparrish** [comment]
It's possible for a live stream to see `readyState` < 4 and buffering false, because we buffer into a certain position in time corresponding to the live edge, **then** seek to that position.  Until we seek, the browser's `readyState` is less than 4 because there's not enough data at `currentTime`.

Does that explain what you're seeing?

**Comment by IsaacSNK** [comment]
Yes. Thank you so much.
