### ISSUE TITLE
keySystemsMapping unrecognized

### ISSUE THREAD

**Issue by sachaelkaim** [shaka-project/shaka-player#4422]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

4.2.0

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `main`?**

yes

**Are you using the demo app or your own custom app?**

custom

**If custom app, can you reproduce the issue using our demo app?**

Have not tried

**What browser and OS are you using?**

macOS chrome
Windows Edge

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

tried to add keySystemsMapping to DRM config
```
player.configure({
  drm: {
    keySystemsMapping: {
      'com.microsoft.playready': 'com.microsoft.playready.recommendation',
    }
  }
});
```

**What did you expect to happen?**

To have the keysystemsmapping not be empty in my player.getconfiguration

**What actually happened?**

Getting a console response
`Invalid config, unrecognized key .drm.keySystemsMapping.com.microsoft.playready`

player.getconfiguration
`preferredKeySystems":[],"keySystemsMapping":{}},`

**Comment by joeyparrish** [comment]
That definitely seems wrong.  We will look into it.  Thanks!

**Comment by joeyparrish** [comment]
An override is missing from the config parser.  Also, there are no tests covering that feature at all.  I'll fix both.

**Comment by joeyparrish** [comment]
This issue affects all v4.1 and v4.2 releases.
