### ISSUE TITLE
HLS Playback issue in shaka Player 3.3.0 version

### ISSUE THREAD

**Issue by siri0099** [shaka-project/shaka-player#4427]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes, we are not seeing any related issues.

**What version of Shaka Player are you using?**
Shaka Player 3.3.0.

**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `main`?**
Not tested. We are using 3.3.0 version only.

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
We have tried in Chrome + Shaka Player, Mac - Safari & Chrome with shaka player, IOS - Safari & Chrome with shaka player. we are seeing issues in all players.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

We have tried in above mentioned combinations and able to reproduce the issue.

**What did you expect to happen?**
Wanted to understand, if this is a player issue (with shaka player 3.3.0 and fixed in latest version) or manifest issue

**What actually happened?**

We have created SSAI enabled manifest and seeing issues playback issues during the switchover to ad content. The stream is playing fine for couple of hours and stopping for couple of hours. Could you please see the below player console logs and suggest where the actual issue is?

[Shaka-3.3.0-Chrome-tsv2-Train&Travel-Player-Log.txt](https://github.com/shaka-project/shaka-player/files/9381197/Shaka-3.3.0-Chrome-tsv2-Train.Travel-Player-Log.txt)

**Comment by Amagi-Achin** [comment]
Hey Team

Please look into the above issue

**Comment by joeyparrish** [comment]
Please try the latest v3.3 release, v3.3.9.  If your issue persists in that release, please try the latest release, v4.2.0.  If the issue persists there, we will investigate.  Thanks!

**Comment by siri0099** [comment]
Hi Team,

The Webapp is built on v3.3.0. Could you please check the attached player
logs and let us know if we are seeing any issues with this release?

If yes and issue is fixed in latest release we will use as suggested by you.

**Comment by Amagi-Achin** [comment]
Hey Team,

We have tested the issue in 3.3.8 and it has same issue

Can someone look into the issue via logs and provide us the fix.

We are near our release date and cannot update to 4.2 because cannot play HLS/Fairplay content on Safari with V4

We found the ticket for it https://github.com/shaka-project/shaka-player/issues/4312

Please check and respond

**Comment by avelad** [comment]
See https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html for FairPlay issues

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
