### ISSUE TITLE
Captions stops renering after it hits the EMPTY Segmented VTT captions file

### ISSUE THREAD

**Issue by sundip111** [shaka-project/shaka-player#4429]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

**Can you reproduce the issue with our latest release version?**

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by sundip111** [comment]
Background: 
I am developing a Chromecast custom receiver and captions are being rendered using segmented VTT. I ran into an issue when at some point one of the segments returned an empty response for a certain time slot. And captions stopped being rendered on the player.

Findings so far:
One of our backend devs found that the error is being thrown from `- mp4_vtt_parser ` and if we add a check `if (!data.length) return [];` here https://github.com/shaka-project/shaka-player/blob/main/lib/text/mp4_vtt_parser.js#L100` can solve the issue.

**Comment by joeyparrish** [comment]
So by "empty", it seems that you mean the segment itself is 0-bytes?  That feels like a content problem.  That segment isn't a valid mp4 file, so of course it is rejected by the mp4 parser.

Is there some reason you won't or can't fix your broken backend?

**Comment by sundip111** [comment]
Thanks, @joeyparrish for the quick response.

Correct, our backend team is looking into this, however, is that possible to handle this scenario by adding the check on the method itself to avoid the missing captions?

**Comment by joeyparrish** [comment]
Sure, that could work.
