### ISSUE TITLE
HLS issues with dynamic -> static manifest

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#4431]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome, macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

Will provide manifest link in separate email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

<details>
<summary> player config </summary>

```
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "servers": {},
    "clearKeys": {},
    "advanced": {},
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": false,
    "defaultPresentationDelay": 0,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
      }
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "useFullSegmentsForStartTime": false
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 10,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.1,
    "smallGapLimit": 0.5,
    "jumpLargeGaps": false,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2,
    "lowLatencyMode": false,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false
  },
  "offline": {
    "usePersistentLicense": true
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    }
  },
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferForcedSubs": false,
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null,
  "useMediaCapabilities": false
}
```
</details>

**What did you do?**

Play a manifest that is dynamic, but will turn static in the future (this is accomplished by using `start` and `stop` query parameters )
I use `setInterval(() => console.log( player.seekRange()), 1000)` to see the values of seekRange().end update

**What did you expect to happen?**
The content should play all the way to the end.
seekRange().end should increment until the content turns static, and then stay at the max value

**What actually happened?**

When the content turns static, seekRange.end() will revert back to what it was when the stream started, this could be observed by using `setInterval(() => console.log( player.seekRange()), 1000)` in the console.

Here's an example scenario:

Program A starts at 10:00 and ends at 11:00
I start the program from the beginning at wall clock time 10:40, the live point in the progress bar is now at 40 minutes, seekRange().end is at 40 minutes.

I'm watching the program, and the live point (`seekRange().end`) increases as expected.

At 11:00 the recording ends, and the manifest goes static, the playhead is at 20 minutes. The live point will now "snap back" to what it was when I started playing, so back to 40 minutes.

When the playhead later on reaches this point, the buffer will drop to 0 and the stream will stall.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/56258400/186111245-e1a16d5e-f0a7-4ebe-96eb-c05183b665f3.png">

In trying to understand this problem, I've changed the `Math.min...` in `getSegmentAvailabilityEnd()` in `presentation_timeline.js` to be a `Math.max...` and that will allow me to play the content all the way through.

Maybe this means that `this.maxSegmentEndTime_` is not updated correctly when HLS manifests go from dynamic to static?

**Comment by joeyparrish** [comment]
Yes, it appears that maxSegmentEndTime_ is the value that's breaking the seek range.  But it doesn't appear to get broken in the transition from dynamic to static.  Instead, it seems it is not being updated at all.

**Comment by joeyparrish** [comment]
It appears that the behavior of maxSegmentEndTime_ changed in releases 3.2.2, 3.1.4, and 3.0.15, in commit 9220c1f87d3ab1b23d0008fc8b0164d2ad26f35f.  Even before that change, the seek range was not "sane", though, so there may be more than one layer to this problem.

**Comment by joeyparrish** [comment]
I think I've found three changes needed to fix this:

1. Update maxSegmentEndTime_ by restoring missing calls to notifySegments
2. Wait to change the presentation type until we have ENDLIST on all playlists, not just the first one, otherwise we miss the last segment of audio, for example
3. Update the MSE duration at exactly the same time we change the presentation type, or else there's a loophole where the UI shows an insane end time until the final segments are buffered for all types

I have this working locally with your test content (thank you for sending that!) but I still need to clean up the change, update tests, and write a few new ones.

**Comment by joeyparrish** [comment]
There's one caveat so far.  The test content you sent us privately does something odd, and this results in an odd UI.  With the parameters I'm giving for start and end times (now - 30s, now + 30s), when the ENDLIST tags are appended to the playlists, there is one more video segment than audio segment.  This results in a weird UI.  For example, the duration may be 1:01 (the max of what was appended), but playback stops at 0:57 (the min of what was appended, the max of what can be played).

The state and the rest of the UI is still correct (ended state, replay button showing).  It also seems like a quirk of the content simulator rather than a realistic issue, so unless someone objects, I'm going to call that good enough.

**Comment by martinstark** [comment]
@joeyparrish thanks for looking into this.

We're aware of this bug and it's being worked on by the provider, we have it on some of our content and it causes the issues you describe. I don't think it should affect the maxSegmentEndTime_ issue, though?

**Comment by joeyparrish** [comment]
With the fixes I'm polishing up right now, there is no stall.  I just wanted to point out that I'm aware of the weird UI, and that I believe it's caused by the off-by-one issue in the content itself, so I'm not putting any extra effort into that.

**Comment by fredrik-telia** [comment]
I'm having issues when testing from `main`
When the ongoing recording ends and I get the EXT-X-ENDLIST, I get this error in the console with debugging turned on:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/56258400/190435846-6b1787db-5ca7-4a5b-906b-7e67b6704330.png">

The buffer drops to zero and playback stalls.

**Comment by fredrik-telia** [comment]
This is also reproducible in the shaka demo app (running locally from `main` using the url provided in a separate email.

Generating a fresh url using `updateUrl(<url from email>)` with the following function:

```javascript
const updateUrl = (url) => {
  const start = Math.floor((Date.now() / 1000) - 120);
  const stop = Math.floor((Date.now() / 1000) + 60);

  return `${url}?start=${start}&stop=${stop}`
}

and playing in Safari with `useNativeHlsOnSafari` set to false, the stream will stall after one minute, instead of playing all the way to the end.
