### ISSUE TITLE
HLS Playback got stuck at transition from content to ad break

### ISSUE THREAD

**Issue by shubhamamagi** [shaka-project/shaka-player#4432]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
https://v3-3-0-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://cdn-apne1.tsv2.amagi.tv/linear/amg01287-rakutentvjapan-trainandtravel-rakutenjp-test/playlist.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v3.3.0-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

**What did you do?**
I played the stream using the link provided, the playback played fine until an ad break occurred. The ad assets got downloaded but the playback got stuck at content to ad transition.

**What did you expect to happen?**
I expected to see a continuous playback without any interruption.

**What actually happened?**
The stream got stuck at content to ad transition and the playback stopped.

![Screenshot from 2022-08-24 16-42-57](https://user-images.githubusercontent.com/83569690/186404833-fd7bf077-66ae-4781-b46d-f8c6fa657624.png)

**Comment by avelad** [comment]
@shubhamamagi Can you test with 4.3.0? Thanks!
