### ISSUE TITLE
crash on webos 5.0 / shaka 2.5.0 docs?

### ISSUE THREAD

**Issue by artstylee** [shaka-project/shaka-player#4433]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.0

**Please ask your question**
hi! i have an old shaka player version on my project.
getting client crash on WEBOS 5.0/ LG  43UN73906LE in 30% while playing dash drm(widevine) 1080p on the first chunk (11mb)
the app just freezes and restart without any errors
at first i want to debug the player, to look what happed inside, but i see no docs for 2.5.0 version and have no idea how to debug it.
we a re using it as a node module ( import {Player} from 'shaka-player/dist/shaka-player.compiled' ). dont rly understand was it compiled before or just pulled from the npm

**Comment by avelad** [comment]
Version 2.5 is not maintained please upgrade to one of the maintained versions, https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md
