### ISSUE TITLE
shaka.Player.getStats() returning mostly null values when playing mp4 Videos

### ISSUE THREAD

**Issue by ahmed4game** [shaka-project/shaka-player#4434]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2

**Please ask your question**
I'm using shaka-player to play HLS, DASH and MP4 format videos and showing the "Stats for nerds" for the same. There is no problem in playback for all formats. But getStats() from shaka.Player is always returning null for most properties when mp4 is getting played. I have attached the stats log for one of mp4 video below
`{
    "width": null,
    "height": null,
    "streamBandwidth": null,
    "decodedFrames": 23,
    "droppedFrames": 0,
    "corruptedFrames": 0,
    "estimatedBandwidth": null,
    "completionPercent": 0,
    "loadLatency": 0.042999982833862305,
    "manifestTimeSeconds": null,
    "drmTimeSeconds": null,
    "playTime": 1.121000051498413,
    "pauseTime": 0,
    "bufferingTime": 0.2630000114440918,
    "licenseTime": null,
    "liveLatency": null,
    "maxSegmentDuration": null,
    "stateHistory": [
        {
            "timestamp": 1661339910.84,
            "state": "buffering",
            "duration": 0.2630000114440918
        },
        {
            "timestamp": 1661339911.103,
            "state": "playing",
            "duration": 1.121000051498413
        }
    ],
    "switchHistory": []
}`

**Comment by avelad** [comment]
Many of these values can only be obtained when using adaptive streaming managed by ShakaPlayer itself. I also see that width and height are not defined and if it would be possible to provide them, I will do a PR for this.

**Comment by ahmed4game** [comment]
@avelad also I can see that `player.getVariantTracks()` also returning [] for mp4. Since Mp4 is single file video, Aren't the player supposed to return single track for this. All I'm trying to get is the **activeTrack, estimatedbandwidth and bufferSize** to show some basic State for Nerds

**Comment by joeyparrish** [comment]
Not at the moment, no.  You would need to add something to Player and possibly StreamUtils to build a Track object based on the data that is available.  PRs are welcome.

> All I'm trying to get is the activeTrack, estimatedbandwidth and bufferSize to show some basic State for Nerds

We have something like this already available in the UI.  Have you seen `ui/statistics_button.js`?  You can add `"statistics"` to the UI config as an overflow button or context menu element.  See also `docs/tutorials/ui-customization.md`.
