### ISSUE TITLE
Playready CBCS support with SL2000

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-player#4436]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest from github

**Please ask your question**
We are trying to use playready DRM with CBCS encryption mode and security level is SL2000. I have tried this in multiple laptops with good configuration and not able to play this content in any laptop.

1. To play CBCS playready with SL2000 is there any additional requirements?
2. In microsoft docs https://docs.microsoft.com/en-us/playready/packaging/content-encryption-modes#limitations
Prior to PlayReady version 4.4 generating a license with a CBC key when the incoming Client Certificate is Windows and SL2000 throws an exception. This is because Windows Clients support CBC only on SL3000 units. **It may be possible to deliver a license with a CBC key to a SL2000 Client, however, if this client is PlayReady version 4.0 minimum and declares support for the CBC mode.**
This means CBC is supported with SL2000 client. But it is not working in any of the laptops

Thanks

**Comment by sridhard** [comment]
I have checked https://github.com/shaka-project/shaka-packager/issues/602 and PR https://github.com/shaka-project/shaka-packager/pull/679 

This discussion is 2 years old. Can you please give current support details.

Thanks

**Comment by joeyparrish** [comment]
It sounds like you have a question about PlayReady, and/or Shaka Packager?  This is Shaka Player's repo.  Did you file this in the wrong project?
