### ISSUE TITLE
Fairplay support with EME

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-player#4437]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest version from git hub

**Please ask your question**
I have seen that now shaka player support Fairplay on safari with EME. I have the below queries:
1. I  think all mac/ios devices does not have this support. Is there any way to detect the support and fallback to native player?
2. In shaka PR and discussions I have found that EME support for fairplay is limited in ipad and not present in IOS. Can we get any data like in which safari versions it is supported in mac and which safari versions in ipad? did apple added any support recently for iphone?

Thanks

**Comment by avelad** [comment]
Fairplay is supported in ShakaPlayer.

- If you want to use MSE you can only use the Modern API and MP4
- If you want to use the video element (apple player) we support all the combinatorics.

The tutorial is available here: https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html

Both iPhone, iPad and Mac are supported, Safari 13+. https://github.com/shaka-project/shaka-player/blob/main/README.md#platform-and-browser-support-matrix

If you want to check if FairPlay is supported you have the `isFairPlaySupported` method at https://shaka-player-demo.appspot.com/docs/api/shaka.util.FairPlayUtils.html

Does this answer your questions?

**Comment by sridhard** [comment]
iPhone and MSE combination is supported?

**Comment by avelad** [comment]
Safari on iPhone does not support MSE yet. You can see it at: https://bugs.webkit.org/show_bug.cgi?id=200147
