### ISSUE TITLE
player.getVariantTracks() return null for Mp4 format. But plays video and audio normally

### ISSUE THREAD

**Issue by ahmed4game** [shaka-project/shaka-player#4440]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.2

**Please ask your question**
I'm able to play mp4 format video and audio using shaka player without a problem. Since the content loaded and played as mentioned in Docs, Should not the getVariantTracks() supposed to return a single track at least as we are playing mp4 format?

**Comment by avelad** [comment]
The getVariantTracks API is only populated when using Shaka Player managed adaptive streaming (HLS or DASH). An mp4 file is managed by the video element itself.
