### ISSUE TITLE
Fairplay with EME

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-player#4442]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2

**Please ask your question**
I am using shaka player to play fairplay content. I have set useNativeHlsOnSafari: false.
If we dont give initDataTransform then our license provider is failing the request saying invalid content ID. 
We are able to get the license from our license provider with useNativeHlsOnSafari:true and with initDataTransform.

If we give initDataTransform with useNativeHlsOnSafari: false then shaka player is not triggering the license request itself.

Can you please tell me whether we need to do anything additional if we want to use initDataTransform. 

I have checked some issues. In that it is mentioned to remove initDataTransform and use com.apple.fps.

Can you please let me know what is the way to solve the issue/

**Comment by avelad** [comment]
What DRM provider do you use? Do you use TS or MP4? Have you read the FairPlay tutorial https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html?

**Comment by sridhard** [comment]
We use MP4. Yes I have done same as tutorial.

**Comment by avelad** [comment]
In that case, open a bug issue and provide all the details so we can look into it.
