### ISSUE TITLE
shaka-ui: Subtitles vertical alignment

### ISSUE THREAD

**Issue by Warry** [shaka-project/shaka-player#4446]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.2.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
I have not tried.

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
not applicable

**What browser and OS are you using?**
Mac firefox & chrome all up to date

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
not applicable

**What are the manifest and license server URIs?**

see below 

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default configuration using shaka-ui, see `player.getConfiguration()` here: https://gist.github.com/Warry/7f8ceced39286fcd6410e4607c4d3695

**What did you do?**

I have created a SSCCE (minimal app) that loads a dash manifest with a video and subtitles, follow the link then play:

https://cdn.githubraw.com/Warry/shaka-bug/main/index.html

source code: https://github.com/Warry/shaka-bug

**What did you expect to happen?**
subtitles with `line:0` or `line:0%` should be at the top, nor is `line:1`, but `line:1%` is working fine.

**What actually happened?**

subtitles lines are not aligned to the top as they should, either with `line:0` or `line:0%` or `line:1`.

![image](https://user-images.githubusercontent.com/197573/186910524-825344bd-88bd-40fa-b3f7-542c27c107ed.png)
![image](https://user-images.githubusercontent.com/197573/186910561-2e5fd1cd-4fc8-4be4-b55d-51831a4b248c.png)
![image](https://user-images.githubusercontent.com/197573/186910594-cc195c5b-4322-4af3-aa85-2b9171dc17e4.png)

`line:1%` does work:
![image](https://user-images.githubusercontent.com/197573/186910633-85739b8d-a9e2-432a-b773-7379fccd43a3.png)

**Comment by avelad** [comment]
The current implementation only takes into account %, when using numbers there are no positioning. I have tried and 0% is positioned at the top, which is correct. Can you try on the main branch and see if it reproduces the same results? Thanks!

**Comment by Warry** [comment]
I have updated my minimal app with 4.3.9, and 0% seems to work now, and `line 0` or `line 1` are still at the bottom.

**Comment by avelad** [comment]
@Warry I'm going to add support to line:0 in https://github.com/shaka-project/shaka-player/pull/5632

**Comment by avelad** [comment]
I don’t know about the CAF implementation, maybe @theodab knows
