### ISSUE TITLE
Shaka + Safari + FairPlay

### ISSUE THREAD

**Issue by boredom2** [shaka-project/shaka-player#4447]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.2.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
didnt check

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Safari 15.6 (macOS)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
Manifest: https://nq-p01.akamaized.net/89d1c111-57c6-4789-adcc-756bbb17fa4b/1702512_src.ism/Manifest(format=m3u8-cmaf,encryption=cbcs-aapl)

License Server: https://nexxplayplus1.keydelivery.westeurope.media.azure.net/FairPlay/

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default with drm.advanced.[com.apple.fps].serverCertificateUri

**What did you do?**
loading the Manifest and start Play, Shaka throws Error Network.BAD_HTTP_STATUS on fetching QualityLevel URLs

**What did you expect to happen?**
Shaka would start DRM Request to License Server or download (FairPlay) Certificate.

**What actually happened?**
I could not see any attempt of Shaka to download the License and/or reach the License Server at all.

I know that there are many Questions around FairPlay and Safari and I also read the "Shaka/FairPlay Configuration Page" - but I hope, my Question is very easy to answer.
I didnt even reach that level, that I have Issues with the DRM Security on FairPlay at all - Shaka just doesnt try to reach any DRM License or anything at all (unlike PlayReady/Widevine, which work perfectly). Maybe I am missing something, but how is this DRM Process with FairPlay initiated at all then, if not automatically?

Thanks a lot!
Christoph

**Comment by boredom2** [comment]
I also compared to #4442 - the Ticket basically mentions also, that License Process is not even triggered under certain Conditions.
This Ticket mentioned, that useNativeHlsOnSafari:true AND initDataTransform finally lead to a License Request.
I tested with useNativeHlsOnSafari:true AND false and with and without initDataTransform. There was no difference, neither initDataTransform Function nor any License Request could be observed.

**Comment by boredom2** [comment]
I also dont even understand, if I should use com.apple.fps OR com.apple.fps.1_0 - you mention both and distinguish between MSE or classic. But is this related to "useNativeHlsOnSafari"? Should this be true in case I use DRM? And if its true, will then com.apple.fps.1_0 work? 
I also ask, as afaik iOS cannot handle EME, so it must be "classic" here then anyway, no? So better use "com.apple.fps.1_0" everywhere and useNativeHlsOnSafari=true in case its DRM-protected (at least thats why I thought after reading all these Issues and descriptions :P).

Nevertheless - whatever I configure, I cannot see any attempt of Shaka to get/load/process anything DRM-related - how can I do that?

**Comment by boredom2** [comment]
I was able to figure out, what the problem was.
Actually the License Request starts, as soon ay Shaka recognizes the Manifest URL correctly. To do that, i just had to attach ".m3u8" after the current URL. Then it works.
Not sure why thatis, but this solves this problem.

**Comment by sridhard** [comment]
@boredom2 I am facing the same issue. Shaka player is not triggering and license request. I am using useNativeHlsOnSafari=true and com.apple.fps.1_0. can you tell me how you solved the issue?
