### ISSUE TITLE
DVB image based subtitle are not rendering using SMPTE-TT in the latest version V4.2.0 and V4.1.3

### ISSUE THREAD

**Issue by balajic7** [shaka-project/shaka-player#4448]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, Linked issues https://github.com/shaka-project/shaka-player/pull/4407, https://github.com/shaka-project/shaka-player/pull/4412 or https://github.com/shaka-project/shaka-player/pull/4273

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.2.0-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

**What did you do?**
Tried to do playback DASH content with DVB image-based subtitle, playback happened for audio/video but the player could not render SMPTE image-based subtitle.

**What did you expect to happen?**
It should render image-based subtitles.

**What actually happened?**

Shaka-player could not render DVB png image-based subtitles on screen whereas it was working in V4.1.2, Sample XML attached in comment.

**Comment by balajic7** [comment]
<?xml version="1.0" encoding="utf-8"?>
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt"
    xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
    xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
    xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt.xsd"
    tts:extent="720px 576px">
  <head>
    <metadata>
      <smpte:image xml:id="3000-0002-01" imageType="PNG" encoding="Base64">
        iVBORw0KGgoAAAANSUhEUgAAAtAAAAAkCAMAAACXFf2IAAAAMFBMVEVNhyQoYwAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAxMTFTU1N1dXWXl5e5ubnb29s0JqdCAAAAEHRSTlMA/3+Uqb/U6f//////////x3AkgwAACUxJREFUeJztXI1y4ygMZmqMjcH2+7/t6Q+MME6z3bbszaCb6ywBf1KsL4okcIz538sHyrxu+3mc+7bOH0O+LL19OcQwoafFx3MP+xn9MvVmxf9YevtyiGFC22WLe/Bh37fF/pCzJwvCf/4hqCQI9vfvvLcvhxiJ0G7dNr/Cn9X9UIQGFeu6uAX+FiomOzvn5jepKRxuQ/2RMaQW9KYXZgRbXqRb7xG+ty+HGMmhLXu09PE3i1182EDHFoovAaImyxu5O6+e21DtK+bm+7H0YaA3bLNxIfhnNEu357K7jTsI/S+IeAzoEbz7lFRflmnZIKFZfYSsJofVefUh7pFUfx5riXawsAnVvqBkYRb48G6gdo/wsaBp+KSE4zzCc8B3+OlZE9QD7iD0PyHiI3Dpvv0koZ3fjxgiakm0AYbG4wQmHUd4i9C8sAXVXo851I14wOewg1pQvHNU/rzH48DQ6O1L3I9B6H9CxElrOH+U0MAajIIYBzNr4GsBXoBI+WeEbkE9aNwzCwsUunoHOTkqv9HjgY/QuSeoNi5Kb18OMb9HaEwYgEShIA0qPYL3mEH8CaEbUC1xyNOaeJxe7GEDtfD1cECofaPHowjdxCXp7cshpiL0NEk/LJf0PBLi2DyYZNXVntCj1sXL6jdfJJ/WkdKVuytNDKUmE7qGympyK49eYBY6zTyL6QUodbODj8UBUdmpHs/tDuBgXgpCl7iVwb19OcRUhHYLCjcAiLfzcnUDpDmAg6lYOE967mIjX8wrptRayEuwtBJCYwOuhaHV5BxaQ102pjaINCVWIl5VvmGAlvIPIjOkzlBYFnhTfQdk7iI0KEm4N4N7+3KIqQi9+A2/i0MI1JGGGCqDZaawGGQw8UIc+nWe1NzFRr4YVgAJqbXAS1KvDF4AQkX49gcsNzUwtJpEaA1V2ihtEGlKYAAGeNW7mSS8UlDFXHwPi8Kr7oDMbVsmtF0y7s3g3r4cYmpCQzobqPOAJT9+F+PgpG4ADPY8uBZGWKjncizki2kFNuhoBTCI0wtqrFCvIVAO3cKo1DChNZSyMeUk3JTYCF5XBhSVw3q1n+GjpPD0HbDSETliQeiMezO4ty+HmJrQWDAdB/oJKiRqZ504gtLNFYOVFsJ/ByyMftFzU2JL5NcQyklrgUdWVBJX9kA0bGMoNYssLKGUjRehkX84ce5RRWhLGYcUk5RfVHj6DvDcgf8XhBbcu8G9fTnENAiNLQDMBcKKlITQSKONBkEGKy081MI8ZzN1TsgnNpxaqBTjFSlA4rc7XeaJhk2MSg0t1FDaRkVoLv+86u1RYyW3VCAdn2yFV92BnYzCkH3l0IJ7N7i3L4eYVoQGumKDOK7oOQyMSM3AxdSyyIu8tcZE9XpuLqiDLYwd5soVV7uAlErgbWJoNfeFzFptYyY0tya4aC0JXSUhGq+6A4S6IHcvswW3YXBvXw4xDUJHzIk5xGGbGIp5iIKQXkYq7aGuj8hC9Lt3xEmgrZrj+MdNZuwCYNkEiS4Wh8ta7VCIUuRpC0OrSRG6hNI2KkLzX7330iK0wqvuAL1XSzs5RR+a0BsG9/blEHMnNNLjo3An7cx5j+6OngTWbOJ3iW96LhOaNzCoKZdOIfkiQiulromh1aQcuoRSNi4NQtdt6JrQk8bTd8Bz8MXTIzdCNwzu7cshpkXoKwmNHOGm2c0Oe7Y7y0ncOtHv5OpQzQkZqXiCmg/i8zyv1FyLuN/cJnQbQ6lJXY4SqrRxfo/QVw5t4SKr8W51ZVxtavZpQjcM7u3LIeY1oZMXJ2sd0TMJc2vBs8lC6HKOHZ+6WnQECBOF/TioffBI6BuG1WpShC6hShvtW4S+uhwfFJw13o3QZMoDoWuDe/tyiPmc0LO0t4qAtMctM62O0DiXiids8FJnLlB9edCJzaeUo4VhtZqry3FBKRvfIDR2kVMfesKNmE3j/RGha4N7+3KI+TzlcHRseaNvX59kTakmE6Sak3SBE1PcpdixbDwon/YvCN3AUGpy9VhAKRtbRaEm9MSpb9op3I4jarxGyjE/phy1wb19OcS8JrQcWHJ0XpJ7YLQXvFEzIKzzNKeisJjjUyC8/cwtLykbF949eSwKawzJobOaonrMUNpG5r801hILp/L8kLQKsfdBvZOzMk3fAdkntw9FYW1wb18OMZ8Qms7xOO5wROzPOfAfnqznfho+2Bcl/l5zQmgP/6YViEKhDheEpxy6gZHadknNFcovKG0j8R+5eWTKOUvJSOreWWlcOygIeYdE490+0miUe2jb1Qb39uUQ85LQC5+0lF0R7KDxQNq11GUOaf/hmnMSCiOvoE9CQtqolTC3CN3AsFpNJnQBpW3koC37IPQmcI/E55BP3xy0tbgKQlwrvGqzEQ+YprmS0FvrTff25RDzktByFp6zYEcsCSHvQmOxhyM88qDm2O/8WEmkqyHXjPTvsNOhiBahWxhWq5GUQ0HdbBSVKYbipknQz31RNRewUUfnNTReXVfy5H6UhBbcu8G9fTnEvCR0euYP/bbyKaCTjp55OZx0cgtj1nPp5I8nNvIpHz7IQw9c5X1ArbSFYbWaq8tRQGkbA80dO/U+6DgfxFLcTMyEnqSdeNBBuU3eV8ar7kCaLLuNGfdmcG9fDjEFofFc2iJPQ2GJBVFnxiPLyI90TpMHeHwU/Y5DmtJzORR6vhhPfiIgzW/F81ZaaQNDq7G8sIKqbMR/g0bcB6fPI54CDeoRLypXufEc+IxsiVfdATFqDwSY3xjh3g3u7cshJhN6wa4X1kn0NBQ1wRZLZ+mpqQEuzgOgFjPN82j6UHOJOPyglDwQwMfwt/J5q1ppA0OrmXhhBaVslDnP5s8LDlY8s78Wu914BRnm6WGaCq+6A24pAAVAcN3N4N6+HGISocGtzs30i0L4GyoT/rIQPXZFPzHkuO0lA3pChY+a8UjPXZJe4wel5N9z8Ws2Wukdo1IjC2uo0sY0R+ZPlidc/QM6coVo0njVHRAMJ/eDPxGCezO4ty+HmEzoR5lAboO041FM6YWtF1vzr5S11bSgKi3T48InTS9Ne3hfDZjevhxiPid0U64HsH9UfknNt0lvXw4xg9DfKb19OcR8mdBv/jjM38kvqfk26e3LIeaLhObfF/hxpv2Smm+T3r4cYr5I6I9Zlf0/Jr+k5rukty//Xv4D/ukf3RJdbjEAAAAASUVORK5CYII=
      </smpte:image>
    </metadata>
    <layout>
      <region xml:id="region_1" tts:origin="0px 514px" tts:extent="720px 36px"/>
    </layout>
  </head>
  <body>
    <div region="region_1" begin="461597:31:12.000" end="461597:31:12.240" smpte:backgroundImage="#3000-0002-01"/>
  </body>
</tt>

**Comment by balajic7** [comment]
Sample XML attached.
[image_based_subtitle.txt](https://github.com/shaka-project/shaka-player/files/9442826/image_based_subtitle.txt)

**Comment by avelad** [comment]
Resolved with https://github.com/shaka-project/shaka-player/commit/4a197e1288c8f20a950cf491041eca9dde7033cb
