### ISSUE TITLE
Tizen TV Captions are sticky to the left. Streaming supports CEA-708 formatting.

### ISSUE THREAD

**Issue by iskewedI** [shaka-project/shaka-player#4455]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Both 2.5.6 and 4.1.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not tried

**Are you using the demo app or your own custom app?**
Own app

**If custom app, can you reproduce the issue using our demo app?**
Not tried

**What browser and OS are you using?**
Samsung Tizen TV

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
2020 

**What are the manifest and license server URIs?**
Sent via email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
`{
  "drm": {
    "retryParameters": {
      "maxAttempts": 3,
      "baseDelay": 2000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "servers": {
      "com.widevine.alpha": "https://content.uplynk.com/wv",
      "com.microsoft.playready": "https://content.uplynk.com/pr"
    },
    "clearKeys": {},
    "advanced": {
      "com.widevine.alpha": {
        "distinctiveIdentifierRequired": false,
        "persistentStateRequired": false,
        "videoRobustness": "",
        "audioRobustness": "",
        "serverCertificate": {},
        "individualizationServer": ""
      }
    },
    "delayLicenseRequestUntilPlayed": false,
    "fairPlayTransform": true
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "xlinkFailGracefully": false,
      "defaultPresentationDelay": 10,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true
    },
    "hls": {
      "ignoreTextStreamFailures": false
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 10,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": true,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "smallGapLimit": 0.5,
    "jumpLargeGaps": false,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true
  },
  "offline": {
    "usePersistentLicense": true
  },
  "abr": {
    "enabled": true,
    "defaultBandwidthEstimate": 9800000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    }
  },
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null
}`

**What did you do?**

Loaded a video, and set on the captions.

**What did you expect to happen?**
The captions should respond to the streaming instructions (centered, top, right side of the screen). Streaming team is telling us that they support CEA-708 type captions, so we should be rendering those. From the front-end, I'm only seeing CEA-608 Text Track mime-types. I know that currently CEA-608 captions don't support positioning, but CEA-708 do. 

**What actually happened?**
The captions are sticky to the left.

I've tried the `.streaming.forceTransmuxTS` setting but didn't work.

<img width="1404" alt="Screen Shot 2022-08-30 at 11 07 50" src="https://user-images.githubusercontent.com/52925249/187458941-085c3c37-84d5-4fbc-9c27-df4b998337f0.png">

**Comment by avelad** [comment]
@iskewedI Do you know if the problem occurs in browsers, or is the problem specific to Tizen? Thanks!

**Comment by jdguser** [comment]
@avelad I'll continue the thread that @iskewedI opened here. Yes, it's only happening for Tizen.

**Comment by jdguser** [comment]
Hi @avelad, I just wanted to follow up on this. Do you know if this is something to be fixed soon? Thank you for your answers in advance.

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
