### ISSUE TITLE
Can shaka player be implemented in Java script in such a way as to support multiple security levels bound to different resolutions?

### ISSUE THREAD

**Issue by meyou69** [shaka-project/shaka-player#4463]
This question concerns the latest version of the shaka player, specifically.

I went through the shaka player tutorial and, while very interesting, the tutorial didn't explain how the shaka player can be configured in Javascript to support multiple security levels (the equivalent of Widevine's L1, L2 and L3 security levels).

Specifically, for example, on Netflix, if you try to access video content using a secure media path covered web browser (i.e. Edge on Microsoft Windows or Safari in Mac OS) then Netflix automatically detects this as maximum security and, consequently, the server picks the highest resolution content to deliver to you (assuming you have the internet bandwidth to support this). However, if you're accessing Netflix from google chrome, for example, this is seen as a lower level security and Netflix only sends up to 1080p video at most. This is all done automatically.

Now, my question is, can this be replicated on my own platform in Javascript using Shaka? I found a tutorial that specifies how I can configure the Shaka player to only allow playing if secure media path is guaranteed in the client browser (I believe this is part of Shaka's advanced configuration options of its player). Which is nice but I want more flexibility than this.

Can I do what Netflix does and write my website to use Shaka in such a way that, if the client has secure media path enabled, I can send them maximum quality of the video (let's say full HD). But if they don't then Shaka should request streaming of up to 480p maximum automatically. Can this be done in Javascript? And is it easy to configure?

**Comment by joeyparrish** [comment]
What you're asking for should not require any special configuration on the client side.  If your manifest has key ID information on each stream (it should), then the player knows what keys are required for what resolutions.  Then the license server decides based on the security level what keys to deliver.  The player will compare the key IDs from the manifest to the key IDs in the license and choose appropriate streams.
