### ISSUE TITLE
Frames from cdm

### ISSUE THREAD

**Issue by Hakai-Shin** [shaka-project/shaka-player#4464]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

**Please ask your question**

Is it possible to get decrypted frames from widevine cdm?

I am following this w3c documentation for eme https://www.w3.org/TR/encrypted-media/
In this document, in section 1- diagram, they have mentioned that "cdm implementation may return decrypted frames or render them directly". So are there any api in shaka player which can help in getting the decrypted frames from cdm.

**Comment by avelad** [comment]
There are not a javascript API to do it.
