### ISSUE TITLE
HLS (MP4 containter) live demo content stops playing after about 10 seconds. 

### ISSUE THREAD

**Issue by Tsuruoka-KORG** [shaka-project/shaka-player#4467]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=ja;textlang=ja;uilang=ja;asset=https://storage.googleapis.com/shaka-live-assets/player-source.m3u8;panel=ALL_CONTENT;panelData=HLS,MP4,LIVE;build=uncompiled

**What version of Shaka Player are you using?**
v4.2.1-uncompiled

**What browser and OS are you using?**
Chrome/ 105.0.5195.102（Official Build）

**What did you do?**

Go to the link and try to play the live HLS MP4 content. 

**What did you expect to happen?**
To play the live content.

**What actually happened?**
The content starts playing, however, after about 10 seconds in, the content stops playing (wheel starts to show) and does not resume. 
Since this happens everytime in a fast internet environment, the problem seems to be the content itself, or shaka player HLS compatibility issue.

**Comment by avelad** [comment]
The problem still occurs in 4.3.0

**Comment by joeyparrish** [comment]
The encoder is currently broken, and the stream is down.  Please try another stream.

**Comment by Tsuruoka-KORG** [comment]
@joeyparrish Please let me know if there's any currently active HLS live streaming samples for Shaka Player. Thank you in advance.
