### ISSUE TITLE
Background transparency is not applied for Teletext subtitle if we disabled the transparency for default transparency available txt subtitle asset

### ISSUE THREAD

**Issue by Suruthi-11** [shaka-project/shaka-player#4468]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=uncompiled

**What version of Shaka Player are you using?**
v4.2.1-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

**What did you do?**

1. Playback one teletext live asset mpd on shaka player
2. enabled the subtitle CC
3. Verify the subtitle decoding and ensure the background transpareny

**What did you expect to happen?**
Background color should not be applied for teletext subtitle if there is no subtitle background applied

**What actually happened?**
In the logs i cannot see any background color attribute but background applied in playback screen

**example subtitle xml:**
```xml
<tt xmlns="http://www.w3.org/ns/ttml"
    xmlns:smpte="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt"
    xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
    xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
    xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt.xsd">
  <head>
    <styling>
         <style xml:id="style_1" tts:color="rgb(255,255,255)"/>
    </styling>
  </head>
  <body>
    <div>
      <p begin="461672:55:46.000" end="461672:55:47.153"><span style="style_1">               She wants her performance</span></p>
      <p begin="461672:55:46.000" end="461672:55:47.153"><span style="style_1">                   to be authentic.     </span></p>
      <p begin="461672:55:47.173" end="461672:55:48.000"><span style="style_1">      Mnh-mnh. I&apos;d rather swallow       </span></p>
      <p begin="461672:55:47.193" end="461672:55:48.000"><span style="style_1">             razor blades.              </span></p>
    </div>
  </body>
</tt>
```

**Comment by joeyparrish** [comment]
The IMSC1 renderer at https://www.sandflow.com/imsc1_1/index.html and the TTML spec both agree with you.  Background should default to transparent.

This will be handled in the TTML parser if at all possible, to avoid changing defaults for other formats.
