### ISSUE TITLE
Problems with 4.2 and Fairplay on iOS native

### ISSUE THREAD

**Issue by multiplexer2** [shaka-project/shaka-player#4470]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.0

**Can you reproduce the issue with our latest release version?**
Have not tried

**Can you reproduce the issue with the latest code from `main`?**
Have not tried

**Are you using the demo app or your own custom app?**
Own build of official 4.2.0 release

**If custom app, can you reproduce the issue using our demo app?**
Have not tried

**What browser and OS are you using?**
Safari on iPhone 8 with iOS 15.6.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Will send link to test page by email.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

4.2.0:
        shaka.polyfill.installAll();
        player.getNetworkingEngine().registerRequestFilter(requestFilter);
        player.getNetworkingEngine().registerResponseFilter(shaka.util.FairPlayUtils.commonFairPlayResponse);

        let playerOptions = {
            drm: {
                advanced: {
                    'com.apple.fps': {
                        serverCertificateUri: fairplayCertUrl
                    }
                },
                servers: {
                   'com.apple.fps': licSrvUrl
                }
            },
        };

The license request is working fine.

3.3.2:
        shaka.polyfill.installAll();
        player.getNetworkingEngine().registerRequestFilter(requestFilter);
        player.getNetworkingEngine().registerResponseFilter(responseFilter);

        let playerOptions = {
            drm: {
                advanced: {
                    'com.apple.fps.1_0': {
                        serverCertificate: new Uint8Array(cert)
                    }
                },
                servers: {
                    // A license server uri is required, but the configured uri is never used. Seems like we can put anything here.
                    'com.apple.fps.1_0': 'https://apple.com/'
                },
                initDataTransform: function (initData) {
                      blahblahblah blah;
                }
            },
        };

**What did you do?**
Play Fairplay protected HLS TS stream which works fine in 3.3.2

**What did you expect to happen?**
Playback to work fine in 4.2.0 as well.

**What actually happened?**
Right after a phone reboot a Fairplay stream will normally play at least once in 4.2.0. But after two or a few more player initializations the player will start to give error #3016: MEDIA.VIDEO_ERROR (3, Media failed to decode) on all playbacks until a new reboot.

Note: These problems do not occur with the same config on Mac Safari (have only tested non-native playback here).

**Comment by multiplexer2** [comment]
@avelad I have already read this document several times without being able to increase my understanding of how to configure Fairplay in 4.2.

**Comment by multiplexer2** [comment]
After having read [this comment](https://github.com/shaka-project/shaka-player/issues/4469#issuecomment-1245084690) in the related issue #4469 I was able to get Fairplay working by using com.apple.fps.1_0 on native, while continuing to use the modern EME for non-native playback. So the problem here seems to be that com.apple.fps does not work (more than once after reboot) with the native player. I guess that this is a Shaka 4 bug? if it's intended behavior, the documentation should probably be updated with info about this.

**Comment by sridhard** [comment]
@multiplexer2 I am also facing same issue #4489 can you please let me know what is the issue with my config?

**Comment by NoChance777** [comment]
Hello there! I notice this problem too. Streams with fairplay DRM work fine on desktop Safari, but not on native Safari.
We configure fairplay DRM similar to the original post, variant with com.apple.fps.1_0, additionally we install polyfill
`shaka.polyfill.PatchedMediaKeysApple?.install();`

**Comment by Benny739** [comment]
We're having the same problem "com.apple.fps" plays exactly once and then starts throwing 3016 errors. After a safari reboot it plays again once.

**Comment by avelad** [comment]
Can you test if in the main branch the problem is still reproducing? Thanks!

FairPlay documentation is available at https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html?
