### ISSUE TITLE
The latency reported by player statistics is always a fixed number and doesn't change

### ISSUE THREAD

**Issue by duggaraju** [shaka-project/shaka-player#4474]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**

4.2.1
**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Windows Chrome/Edge

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Play the following stream URL: https://lldemo-usw22.streaming.media.azure.net/612db94f-b556-4c84-b714-fa18d607320c/edaef292-ea7c-4070-af2c-373964170fc3.ism/manifest(format=m3u8-cmaf).m3u8  (you might have to try multiple times due to another bug)

**What did you expect to happen?**
The player latency reported by player.getStats().liveLatency to reflect the end to end latency.
**What actually happened?**

The latency returned  is a fixed constant number and doesn't reflect the correct latency.

**Comment by duggaraju** [comment]
The issue is in this code in player.js:
      if (this.isLive()) {
        const now = this.getPresentationStartTimeAsDate().valueOf() +
            this.seekRange().end * 1000;
        const latency = (Date.now() - now) / 1000;
        this.stats_.setLiveLatency(latency);
      }

It is using seekRange().end.  Instead it should be video.currentTime to give the correct latency.

**Comment by adgllorente** [comment]
@joeyparrish we have seen this issue too, is it expected to change?
