### ISSUE TITLE
Unhandled exception when playing LL-HLS stream.

### ISSUE THREAD

**Issue by duggaraju** [shaka-project/shaka-player#4475]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Windows  Edge/Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://lldemo-usw22.streaming.media.azure.net/612db94f-b556-4c84-b714-fa18d607320c/edaef292-ea7c-4070-af2c-373964170fc3.ism/manifest(format=m3u8-cmaf).m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default

**What did you do?**

Just play the stream.

**What did you expect to happen?**
The playback starts successfully and plays fine.

**What actually happened?**

Unhandled exception. Doesn't happen always but if you try couple of time you will hit the error.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'endTime')
    at shaka.hls.HlsParser.createSegmentReference_ (hls_parser.js:2096:67)
    at shaka.hls.HlsParser.createSegments_ (hls_parser.js:2267:30)
    at $jscomp.generator.Engine_.program_ (hls_parser.js:1647:27)
    at $jscomp.generator.Engine_.nextStep_ (generator_engine.js:795:43)
    at $jscomp.generator.Engine_.next_ (generator_engine.js:699:15)
    at $jscomp.generator.Generator_.next (generator_engine.js:833:19)
    at b (execute_async_generator.js:52:22)
shaka.hls.HlsParser.createSegmentReference_	@	hls_parser.js:2096
shaka.hls.HlsParser.createSegments_	@	hls_parser.js:2267
(anonymous)	@	hls_parser.js:1647
$jscomp.generator.Engine_.nextStep_	@	generator_engine.js:795
$jscomp.generator.Engine_.next_	@	generator_engine.js:699
next	@	generator_engine.js:833
b	@	execute_async_generator.js:52
await in b (async)		
onclick

**Comment by avelad** [comment]
I can not reproduce the issue with 4.3.0.

**Comment by duggaraju** [comment]
Still able to repro this with 4.3.0 build:  Try again with the stream https://aka.ms/LowLatencyDemo.m3u8. It doesn't consistently happen but happens frequently enough to repro.

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
