### ISSUE TITLE
Support for partial first-segments

### ISSUE THREAD

**Issue by gldraphael** [shaka-project/shaka-player#4477]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes   
**Is your feature request related to a problem? Please describe:** I'm trying to play sections of a longer video with precise start/end times.   

**Describe the solution you'd like:** Support for partial first-segments.   
**Describe alternatives you've considered:** None, still exploring.   

----

The following works:

<details>
<summary>Multi-period DASH without first-partial segments</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated with https://github.com/google/shaka-packager version v2.6.0-5181ea1-release-->
<!-- 
  The following example plays from 2:00 - 3:01 and then from 4:00 to 4:59
  This works as expected, because the first segment of the periods align with the segments' start-point of the.
  (Segment size: 2s)
-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" minBufferTime="PT2S" type="static" 
  mediaPresentationDuration="PT2M">
  <BaseURL>https://galdinstorage.blob.core.windows.net/streams/preview-exp/27022/</BaseURL>
  <Period id="0" start="PT0M" duration="PT1M1S">
    <AdaptationSet id="0" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="15360/512" subsegmentAlignment="true" par="16:9">
      <Representation id="2" bandwidth="739591" codecs="avc1.64001f" mimeType="video/mp4" sar="1:1" width="1280" height="720">
        <BaseURL>f968e9954a3ccd54-720p-4500kbps.mp4</BaseURL>
        <SegmentBase indexRange="867-2110" timescale="15360" presentationTimeOffset="1843200">
          <Initialization range="0-866"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>

  <Period id="1" start="PT1M1S" duration="PT59S">
    <AdaptationSet id="0" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="15360/512" subsegmentAlignment="true" par="16:9">
      <Representation id="2" bandwidth="739591" codecs="avc1.64001f" mimeType="video/mp4" sar="1:1" width="1280" height="720">
        <BaseURL>f968e9954a3ccd54-720p-4500kbps.mp4</BaseURL>
        <SegmentBase indexRange="867-2110" timescale="15360" presentationTimeOffset="3686400">
          <Initialization range="0-866"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

</details>

But the following doesn't:

<details>
<summary>Multi-period DASH; second's period's first segment is a partial segment</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated with https://github.com/google/shaka-packager version v2.6.0-5181ea1-release-->
<!-- 
  The following example plays from 2:00 - 3:01 and then from 4:01 to 5:00

  This drops the first segment (of the 2nd period), and gap-jumps to the next segment at 4:02
  
-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" minBufferTime="PT2S" type="static" 
  mediaPresentationDuration="PT2M">
  <BaseURL>https://galdinstorage.blob.core.windows.net/streams/preview-exp/27022/</BaseURL>
  <Period id="0" start="PT0M" duration="PT1M1S">
    <AdaptationSet id="0" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="15360/512" subsegmentAlignment="true" par="16:9">
      <Representation id="2" bandwidth="739591" codecs="avc1.64001f" mimeType="video/mp4" sar="1:1" width="1280" height="720">
        <BaseURL>f968e9954a3ccd54-720p-4500kbps.mp4</BaseURL>
        <SegmentBase indexRange="867-2110" timescale="15360" presentationTimeOffset="1843200">
          <Initialization range="0-866"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>

  <Period id="1" start="PT1M1S" duration="PT59S">
    <AdaptationSet id="0" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="15360/512" subsegmentAlignment="true" par="16:9">
      <Representation id="2" bandwidth="739591" codecs="avc1.64001f" mimeType="video/mp4" sar="1:1" width="1280" height="720">
        <BaseURL>f968e9954a3ccd54-720p-4500kbps.mp4</BaseURL>
        <SegmentBase indexRange="867-2110" timescale="15360" presentationTimeOffset="3701760">
          <Initialization range="0-866"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>

```

</details>

If I understand correctly, DASH [allows][dash-rep-alignment] period start-times that do not align with segment start-times. However, it does state that it might sometimes be impractical for clients to show partial segments.

According to shaka's [design doc][design-doc]:

> Note that we implement content deleting using the MSE `appendWindowStart`. This has a subtle problem if we have a partial segment at the start of the Period. When the browser drops content at the start of the Period, it will continue to drop frames until the next keyframe.

The media-source [§ 4.5.8 Coded Frame Processing Step #8][media-source-note] says:

> Some implementations MAY choose to collect some of these coded frames with presentation timestamp less than [appendWindowStart](https://w3c.github.io/media-source/#dom-sourcebuffer-appendwindowstart) and use them to generate a splice at the first coded frame that has a [presentation timestamp](https://w3c.github.io/media-source/#presentation-timestamp) greater than or equal to [appendWindowStart](https://w3c.github.io/media-source/#dom-sourcebuffer-appendwindowstart) even if that frame is not a [random access point](https://w3c.github.io/media-source/#random-access-point). Supporting this requires multiple decoders or faster than real-time decoding so for now this behavior will not be a normative requirement.

Would shaka-player consider supporting partial-first-segments in periods?   
Is this even possible?

[design-doc]: https://github.com/shaka-project/shaka-player/blob/c147da7b53e15da6ef44c93bbff26377cc99d90a/docs/design/dash-manifests.md#periods
[media-source-note]: https://w3c.github.io/media-source/#sourcebuffer-coded-frame-processing
[dash-rep-alignment]: https://dashif-documents.azurewebsites.net/Guidelines-TimingModel/master/Guidelines-TimingModel.html#timing-period-representation-alignment

**Comment by joeyparrish** [comment]
> The media-source [§ 4.5.8 Coded Frame Processing Step #8](https://w3c.github.io/media-source/#sourcebuffer-coded-frame-processing) says:
> 
> > Some implementations MAY choose to collect some of these coded frames with presentation timestamp less than [appendWindowStart](https://w3c.github.io/media-source/#dom-sourcebuffer-appendwindowstart) and use them to generate a splice at the first coded frame that has a [presentation timestamp](https://w3c.github.io/media-source/#presentation-timestamp) greater than or equal to [appendWindowStart](https://w3c.github.io/media-source/#dom-sourcebuffer-appendwindowstart) even if that frame is not a [random access point](https://w3c.github.io/media-source/#random-access-point). Supporting this requires multiple decoders or faster than real-time decoding so for now this behavior will not be a normative requirement.
> 
> Would shaka-player consider supporting partial-first-segments in periods? Is this even possible?

The "some implementations" phrase in the MSE spec refers to _browser_ implementations.  We have no control over that in Shaka Player.
