### ISSUE TITLE
Ads in the player

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4481]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
3.2

**Please ask your question**
Can you please give me a quick brief on inserting the ads in the shaka-player?

I have already read this documentation: https://shaka-player-demo.appspot.com/docs/api/tutorial-ad_monetization.html

It says after v3.1+ shaka player will support other ads providers, do we have it as we can see we have 4.2 released?

If yes, how we should integrate that?

**Comment by joeyparrish** [comment]
> It says after v3.1+ shaka player will support other ads providers

Unfortunately, we never implemented that.  I would be happy to discuss the design with you if you want to be part of the solution to extend it.  Currently, this is not on our roadmap.  Unless you are interested in the work, I think we should remove that mention from the docs.

**Comment by hiren3897** [comment]
Okay, thanks for the response
I will talk with my team and let you know :)

**Comment by hiren3897** [comment]
"TypeError: Cannot read properties of null (reading 'isLinear')

When I tried to follow your tutorial, I am getting this error above. 

My questions:

We can request ads anytime during the presentation? 
After the ad gets end does the player switch back to the original video automatically?
Do we have a skip button UI or do I need to work on that to create a button to skip the ads?

**Comment by theodab** [comment]
It's hard to say without the full stack trace, but that `TypeError` looks like we are getting a `CONTENT_PAUSE_REQUESTED` or `STARTED` event from the IMA SDK, but the event has no associated ad.
I don't know why that would happen, admittedly. I'm not an IMA SDK expert or anything.
We should probably have a more useful error for if that happens. I'll put in an assert, maybe.

As to your questions,
1. I believe you can request ads at any time during the presentation, yes.
1. The player should automatically return to the original video after an ad.
1. The UI has a skip ad button. It shows up based on the `getAdSkippableState` method of the IMA `AdsManager`.

**Comment by hiren3897** [comment]
Thanks, @theodab for the response

Can you send me any adsTagURl that is working because I am using the ads URL from this google sample source: 
https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags

None of them are working for me!!

**Comment by theodab** [comment]
The ad tag URIs we are using for demo content are here:

https://github.com/shaka-project/shaka-player/blob/8475214bc46e8321f7b60a6fc7fabee484a40800/demo/common/assets.js#L56-L76

I'm... not sure where they come from, to be honest. I didn't make the ad stuff. I assume they are some kind of sample ads.

It should work when hosted on localhost. I test things over localhost, most of the time.

**Comment by hiren3897** [comment]
![errorADS](https://user-images.githubusercontent.com/59652404/191235083-0f47f0ef-9d0f-4883-bef4-83d23dcf8735.png)
When running on localhost I have this error :'/

**Comment by hiren3897** [comment]
Did the fix made by you resolve the problem of `"TypeError: Cannot read properties of null (reading 'isLinear')` ?

**Comment by joeyparrish** [comment]
@hiren3897, please try again with the latest source from the `main` branch and let us know your results.

**Comment by hiren3897** [comment]
It was an issue of cors but the bug has been resolved!!


I am not able to request multiple ads in the player. 

For example, I want to display 3 ads in the player at any time during the video is played. 

Can you tell me how can I do that with the cue points on the UI? 

I tried to request the ads but the second request doesn't work.
