### ISSUE TITLE
Playready persistent license support

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-player#4482]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. I have checked the issues

**What version of Shaka Player are you using?**
4.2.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom app, In demo app files with only PR are not working

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
windows-10, edge browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What did you do?**
Try to save the file offline (With only playready in manifest)

**What did you expect to happen?**
Offline save and play should be success

**What actually happened?**
Shaka player not supporting offline file for playready

Now shaka player supports com.microsoft.playready.recommendation key system. I have read shaka-player issues and also dash.js issues. Also as per the docs com.microsoft.playready.recommendation supports persistent licenses. but shaka player is not able to support it

**Comment by agajassi** [comment]
I am experiencing a similar problem, but on Play Station 5 device.

**Comment by joeyparrish** [comment]
> **What did you do?**
> Try to save the file offline (With only playready in manifest)

Can you please be more specific?  What steps did you take?  What configuration are you giving to the player?  What content URL are you loading?

We have fields in the issue template for configuration and content URL, which you seem to have deleted.  We ask those questions because that can be important information.  Please use the full template next time to save us both time and effort.  Thanks!

**Comment by sridhard** [comment]
@joeyparrish the usecase is simple. Create a DASH video with only playready support. Then this can be played only in windows edge browser. Now we have to download the content and playready license for offline use. This is not working

**Comment by avelad** [comment]
@sridhard You can change the value of sessionType='persistent-license' in https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.AdvancedDrmConfiguration to use persistent licenses. The change was pushed at https://github.com/shaka-project/shaka-player/pull/3301
