### ISSUE TITLE
DRM MPD video not playing on Safari, error code is 6001

### ISSUE THREAD

**Issue by abhisheksadda247** [shaka-project/shaka-player#4487]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
Sent on mail shaka-player-issues@google.com

**What version of Shaka Player are you using?**
v4.2.1-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

**What did you do?**
In the demo app, have added the mpd manifest, and the licence server, and tried to play the video

**What did you expect to happen?**
Expected for the video to be loaded on Safari

**What actually happened?**

The video loaded on Chrome, but is not loaded on Safari

**Comment by martinstark** [comment]
You need to use HLS+Fairplay to play DRM content on Safari.

**Comment by abhisheksadda247** [comment]
Thanks for the answer, I tried earlier with the m3u8 file and it worked. Closing the ticket.
