### ISSUE TITLE
How do I choose the language track?

### ISSUE THREAD

**Issue by michga1** [shaka-project/shaka-player#4492]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What link can we use to reproduce this?**

https://merucourses.com/wp-content/drm/tut03.html?uri=https://d31te7sw8g9fy1.cloudfront.net/EZDRM-test/SCI1b.mpd&title=SCI%201%20B%20Test&userid=1&contentid=15097

**What version of Shaka Player are you using?**
v4.2.1-compiled

**What browser and OS are you using?**
Google Chrome on Windows 10

**What did you do?**
I set up the Shaka Player according to the tutorial of offline playing:
https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html

**What did you expect to happen?**
I expected to be able to choose the language either (graphically) in the video window or by the player configuration:
player.configure({
  'preferredAudioLanguage': 'en',
  drm: {
    servers: { ........

**What actually happened?**
A random language comes up (french), and I cannot change it.

What do I have to do to choose the language track?
I know that the languages are working because I can play and choose them in this test page:

https://shaka-player-demo.appspot.com/demo/#audiolang=en-EN;textlang=en-US;uilang=en-US;asset=https://d31te7sw8g9fy1.cloudfront.net/EZDRM-test/SCI1b.mpd;license=https://widevine-dash.ezdrm.com/widevine-php/widevine-foreignkey.php?pX=86BEE7&u=1&c=15097;panel=CUSTOM%20CONTENT;build=uncompiled

Thank you for your help!

**Comment by joeyparrish** [comment]
`player.configure('preferredAudioLanguage', 'en');` sets a _preference_.  If you configure it before `load()`, it affects the initial choice of language.  If you don't set a preference, the initial language is whatever is the "main" language of the content (if the content defines that) or the first language in the list.

If you want to change languages during playback, see `player.getAudioLanguages()`, `player.getTextLanguages()`, `player.selectAudioLanguage('en')`, and `player.selectTextLanguage('en')`.

Does this help?
