### ISSUE TITLE
HLS live stream is stalling on webOS with intermittent audio

### ISSUE THREAD

**Issue by kiran-dcunha** [shaka-project/shaka-player#4494]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1
mux.js - 6.2.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Did not check

**Are you using the demo app or your own custom app?**
Reproducible in both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
webOS 4.4
Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.36 WebAppManager

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG webOS 4.4

**What are the manifest and license server URIs?**

NA

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Reproducible with default config

**What did you do?**

Play HLS live stream with custom app and [demo page](https://shaka-player-demo.appspot.com/)

**What did you expect to happen?**
Should play smoothly with audio

**What actually happened?**

Video stalls and starts continuously for a short time. After a while it completely stops.
Audio plays intermittently 

**Logs**
`index.html:70 start
aria.js:32ARIAMixin interface not detected. Installing polyfill.
mediasource.js:24MediaSource.install
mediasource.js:73Using native MSE as-is.
mediasource.js:79Patching vp09 support queries.
random_uuid.js:21randomUUID.install
symbol.js:22Symbol.install
video_play_promise.js:23VideoPlayPromise.install
vttcue.js:24Using native VTTCue.
media_capabilities.js:64MediaCapabilities: install
index.js:52EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
index.js:255McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
player.js:984Starting attach...
player.js:1205Starting load of https://cph-msl.akamaized.net/hls/live/2000341/test/master.m3u8...
hls_parser.js:994Guessing stream type for #EXT-X-STREAM-INF:BANDWIDTH=550172,RESOLUTION="256x106",URI="level_0.m3u8"
hls_parser.js:1024Guessing multiplexed audio+video.
hls_parser.js:994Guessing stream type for #EXT-X-STREAM-INF:BANDWIDTH=1650064,RESOLUTION="640x266",URI="level_1.m3u8"
hls_parser.js:1024Guessing multiplexed audio+video.
hls_parser.js:994Guessing stream type for #EXT-X-STREAM-INF:BANDWIDTH=2749539,RESOLUTION="1280x534",URI="level_2.m3u8"
hls_parser.js:1024Guessing multiplexed audio+video.
hls_parser.js:994Guessing stream type for #EXT-X-STREAM-INF:BANDWIDTH=4947980,RESOLUTION="1920x800",URI="level_3.m3u8"
hls_parser.js:1024Guessing multiplexed audio+video.
hls_parser.js:994Guessing stream type for #EXT-X-STREAM-INF:BANDWIDTH=8247438,RESOLUTION="1920x800",URI="level_4.m3u8"
hls_parser.js:1024Guessing multiplexed audio+video.
player.js:2658 Found variant with audio and video content, so filtering out audio-only content.
stream_utils.js:511 Already got the variants' decodingInfo.
stream_utils.js:259 codecs avc- avg bandwidth 6597709
adaptation_set_criteria.js:127 No exact match for variant role could be found.
streaming_engine.js:190 init: completed initial Stream setup
adaptation_set_criteria.js:127 No exact match for variant role could be found.
player.js:2109 No preferred audio language set.  We have chosen an arbitrary language initially
simple_abr_manager.js:350 Calling switch_(), bandwidth=1771 kbps
player.js:5530 switch_
streaming_engine.js:445 switch: switching to Stream (video:3)
hls_parser.js:2546 Updating manifest...
playhead.js:365 Jumping forward 6.789000082015988 seconds to catch up with the seek range.
streaming_engine.js:690 (video:3) clear: currently updating
streaming_engine.js:640 (video:3) Aborting operation due to seek
streaming_engine.js:874 (video:3) skipping update and clearing the buffer
streaming_engine.js:1890 (video:3) clearing buffer
streaming_engine.js:1908 (video:3) cleared buffer
simple_abr_manager.js:350 Calling switch_(), bandwidth=4992 kbps
player.js:5530 switch_
streaming_engine.js:445 switch: switching to Stream (video:7)
playhead.js:541 Stall detected at 108.875 for 1.0190000534057617 seconds.
playhead.js:547 Pausing and unpausing to break stall.
playhead.js:365 Jumping forward 3.032999980926519 seconds to catch up with the seek range.
streaming_engine.js:657 (all): seeked: buffered seek: presentationTime=112.2829999923706
playhead.js:541 Stall detected at 112.27 for 1.1549999713897705 seconds.
playhead.js:547 Pausing and unpausing to break stall.
hls_parser.js:2546 Updating manifest...
simple_abr_manager.js:350 Calling switch_(), bandwidth=3794 kbps
player.js:5530 switch_
hls_parser.js:2546 Updating manifest...
gap_jumping_controller.js:221 Jumping forward 1.4590609999999913 seconds because of gap before start time of 125.987061
streaming_engine.js:657 (all): seeked: buffered seek: presentationTime=126.1489999294281
playhead.js:541 Stall detected at 125.987061 for 1.2379999160766602 seconds.
playhead.js:547 Pausing and unpausing to break stall.
hls_parser.js:2546 Updating manifest...
streaming_engine.js:1145 (video:7) cannot find segment endTime: 138
playhead.js:365 Jumping forward 3.0499389408721953 seconds to catch up with the seek range.
streaming_engine.js:657 (all): seeked: buffered seek: presentationTime=129.04299998283386
simple_abr_manager.js:350 Calling switch_(), bandwidth=5223 kbps
player.js:5530 switch_
streaming_engine.js:445 switch: switching to Stream (video:5)
gap_jumping_controller.js:221 Jumping forward 1.0840610000000197 seconds because of gap before start time of 131.987061
streaming_engine.js:657 (all): seeked: buffered seek: presentationTime=132.03800010681152
playhead.js:541 Stall detected at 131.987 for 1.003999948501587 seconds.
playhead.js:547 Pausing and unpausing to break stall.
hls_parser.js:2546 Updating manifest...
playhead.js:365 Jumping forward 3.223000038146978 seconds to catch up with the seek range.
streaming_engine.js:657 (all): seeked: buffered seek: presentationTime=135.2220001220703
gap_jumping_controller.js:221 Jumping forward 1.3340610000000197 seconds because of gap before start time of 137.987061
streaming_engine.js:657 (all): seeked: buffered seek: presentationTime=138.13300013542175
playhead.js:541 Stall detected at 137.987 for 1.3529999256134033 seconds.
playhead.js:547 Pausing and unpausing to break stall.`

Issue was observed in our internal streams. I checked an openly available HLS live stream and same issue was seen. Logs are from the open url - https://cph-msl.akamaized.net/hls/live/2000341/test/master.m3u8.

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
