### ISSUE TITLE
HLS stream with TS segments fails playback even when using mux.js (CONTENT_UNSUPPORTED_BY_BROWSER)

### ISSUE THREAD

**Issue by duggaraju** [shaka-project/shaka-player#4505]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Can you reproduce the issue with our latest release version?**

Yes
**Can you reproduce the issue with the latest code from `main`?**

Yes
**Are you using the demo app or your own custom app?**

Both custom and demo app
**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**

Edge/Firefox on Windows 11
**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Try playback with the public HLS demo sample hosted by Apple

**What did you expect to happen?**
playback works with TS streams

**What actually happened?**

Playback fails. Including mux.js to the page doesn't help either.

**Comment by avelad** [comment]
I can not reproduce the issue with 4.3.0.
