### ISSUE TITLE
Cea608 TypeError preventing playback

### ISSUE THREAD

**Issue by mamaddox** [shaka-project/shaka-player#4508]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.2.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom environment

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 105.0.5195.125 on MacOS Catalina 10.15.7

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

Stream Fragment causing the issue:
https://s3.amazonaws.com/playertest.longtailvideo.com/cea608-error/master.mpd
(Can send the full stream as well if needed).

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Attempted to play the above stream and got a TypeError error instead.
In case there is an issue with the stream, if it's a non-fatal issue, I think the player should be able to recover.

**What did you expect to happen?**
Stream should play without error

**What actually happened?**

Get a TypeError about not being able to ('map') of undefined
<img width="815" alt="Screen Shot 2022-09-22 at 10 02 12 AM" src="https://user-images.githubusercontent.com/26205421/191833328-43d263f5-f140-4f31-881b-3c1d4a1cb9a9.png">

**Comment by mamaddox** [comment]
I am working on a PR for this. It looks like `moveRows` is being passed a negative row index for some reason, so it's trying to call `map` on a row that doesn't exist.

**Comment by avelad** [comment]
Thanks @mamaddox , I'll assign to you the issue!
