### ISSUE TITLE
Clear and encrypted periods working shaka 3.x and not 4.x

### ISSUE THREAD

**Issue by jakubvojacek** [shaka-project/shaka-player#4512]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.2.1 and 3.3.10

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
Our license server is too complicated to be used withing the demo app

**What browser and OS are you using?**
Mac 12.4 
- works in FF 104.0.2
- works in exoplayer
- does not work in Chrome 105.0.5195.125

**What did you do?**
Below is the source code for demo app. It has 2 JS included, one commented out. This sample works for both 4.x and 3.x in FF. In chrome it works only with 3.x version. 

The sample includes content as well as widevine URL.

```
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.2.1/shaka-player.compiled.debug.min.js"></script>
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/3.3.10/shaka-player.compiled.debug.min.js" integrity="sha512-uNvwR4nTxy6kLMZb8c2LO573kEjp7KNqtMcS12ZtcjH0ciWSxUdJjCzI2B7TVhmEXyM+CpbrkfQ9/ZLtPAUhPw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>-->
</head>
<body>
<video id="video"controls autoplay></video>
<script type="text/javascript">
    function initApp() {
        shaka.polyfill.installAll();

        var video = document.getElementById('video');
        var player = new shaka.Player(video);

        player.configure({
            drm: {
                servers: {
                    'com.widevine.alpha': 'https://mw.motv.eu/widevine_proxy',
                }
            }
        });

        var devices_type = 'web player';
        var devices_identification = 'mac os, chrome';
        var devices_hash = 'nfihi!knkn1123...unique';
        var customers_token = 'q34rmp2fn99glgpwbx0gf8pkfakigyjizttlewvi';
        var profiles_id = '104565';
        var version = '0.1';
        var timestamp = parseInt(new Date().getTime() / 1000);
        var offset = 0;
        var edges_id = 1;

        player.getNetworkingEngine().registerRequestFilter(function(type, request) {
            var StringUtils = shaka.util.StringUtils;
            var Uint8ArrayUtils = shaka.util.Uint8ArrayUtils;

            if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
                request.headers['Authorization'] = 'Bearer ' + customers_token;
                request.headers['profilesId'] = btoa(profiles_id);
                request.headers['devicesType'] = btoa(devices_type);
                request.headers['version'] = btoa(version);
                request.headers['browserType'] = btoa('chrome');
                var wrapped = {};
                wrapped.timestamp = timestamp;
                wrapped.offset = offset;
                wrapped.edges_id = edges_id;
                wrapped.devices_identification = devices_identification;
                wrapped.devices_hash = devices_hash;
                wrapped.rawLicense =
                    Uint8ArrayUtils.toBase64(new Uint8Array(request.body), false);

                var wrappedJson = JSON.stringify(wrapped);
                request.body = StringUtils.toUTF8(wrappedJson);
            }
        });
        player.getNetworkingEngine().registerResponseFilter(function(type, response) {
            var StringUtils = shaka.util.StringUtils;
            var Uint8ArrayUtils = shaka.util.Uint8ArrayUtils;

            if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
                var wrappedString = StringUtils.fromUTF8(response.data);
                var wrapped = JSON.parse(wrappedString);
                var rawLicense = wrapped.rawLicense;
                response.data = Uint8ArrayUtils.fromBase64(rawLicense);
            }
        });

        player.load('https://edge1.cico.tv/s1/vods/test.mpd');
        video.play();
    }
    document.addEventListener('DOMContentLoaded', initApp);
</script>
</body>
</html>
```

**What did you expect to happen?**
For the playback to work with shaka 4.x in chrome.

**What actually happened?**
It does not play in Chrome with 4.x version. The error I see in JS console is 

```
(video:4) failed fetch and append: code=3014
``` 

with no further information. I think it might be something related to encryption. If I package the same content without encryption, just clear content, it plays in Chrome too. 

Can you please try it out and tell us what might be wrong with he MPD?  Or is it content OK and the issue is in shaka 4.x?

Thanks a lot

**Comment by jakubvojacek** [comment]
I did read few other issues such as https://github.com/shaka-project/shaka-player/issues/2566

- there are no logs in chrome://gpu/
- tried disabling Hardware-accelerated video decode/encode - no change

I have chrome://media-internals/ to capture the log for both shaka 4.2.1 and 3.3.10

[media-internals-failed-4.2.1.txt](https://github.com/shaka-project/shaka-player/files/9652169/media-internals-failed-4.2.1.txt)
[media-internals-works-3.3.10.txt](https://github.com/shaka-project/shaka-player/files/9652170/media-internals-works-3.3.10.txt)

I tried 4.0.0 and it didnt work either. I guess something period-related must have changed in between 3.3.10 and 4.2.1. But when checking changelog of 4.0.0 I didnt find any multiperiod related note

**Comment by jakubvojacek** [comment]
I managed to identify the commit that broke the playback (by checking individual commits in between 3 and 4 and building the player).

Commit 7155ec73bcb6bfcf657882135879bec180d6b564 from Feb 4th works
Next commit https://github.com/shaka-project/shaka-player/commit/6d76a135e5128dfd47653acea025d0a264d121d5 from the next day from @valotvince - **does not work**.

Unfortunately, I am not really familiar with JS to do more thorough checks of the code to identify which block of new code is responsible.

Any help highly appreciated please!

**Comment by dk00** [comment]
It should be related to when `MediaKeys` object is attached to the video.

In 3.x.x, `MediaKeys` when loading a stream, but starting from https://github.com/shaka-project/shaka-player/commit/6d76a135e5128dfd47653acea025d0a264d121d5, `MediaKeys` object is attached when `encrypted` event is fired, and maybe too late for Chrome.

In media-internals log, Chrome said: `Failed to initialize DecryptingVideoDecoder`.

```json
      {
        "time": 28.13099992275238,
        "key": "info",
        "value": "Failed to initialize DecryptingVideoDecoder"
      },
      {
        "time": 34.519999980926514,
        "key": "kIsVideoDecryptingDemuxerStream",
        "value": false
      },
```

@avelad @joeyparrish , is this a Chrome bug? or is it good idea to revert `MediaKeys` object attachment behavior, attach it when initialization instead of first `encrypted` event?

I was able to workaround by adding `window.shakaMediaKeysPolyfill = true` right before player init, @jakubvojacek does this work for you?

```diff
 var video = document.getElementById('video');
+window.shakaMediaKeysPolyfill = true;
 var player = new shaka.Player(video);
```

**Comment by avelad** [comment]
I created a PR https://github.com/shaka-project/shaka-player/pull/4606
