### ISSUE TITLE
HLS VoD fMP4 Choppy Video Start

### ISSUE THREAD

**Issue by JC-OS-dev** [shaka-project/shaka-player#4516]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
v4.2.1-main-9-ge826eb8e AND 3.0.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 105 and Mac OS 12 Monterey

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Sent through email.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Sent Shaka demo through email.

**What did you do?**
I created an HLS VOD constructed from 10 second fragmented MP4 clips originating from a larger video. I played the manifest in Shaka Demo. I repeated this with VLC player and Safari's player, but the bug did not occur there.

**What did you expect to happen?**
I expected that the audio and video at the start of the stream would play together for the first 10 seconds.

**What actually happened?**
During the first 10 seconds, the audio plays successfully, but the video is choppy and mostly displays 2-3 frames. After the new m4s file is loaded upon the 10 seconds finishing, the video syncs to the audio and playback continues as expected.

**Comment by theodab** [comment]
I've noticed something similar with our demo HLS assets.
A little initial testing [on our version index](https://index-dot-shaka-player-demo.appspot.com/) suggests that this started happening somewhere between v3.3.10 and v4.0.5.
One observation is that if you seek, the beginning of the video plays perfectly smoothly. This happens even on a buffered seek, so clearing the buffer isn't what fixes it.

**Comment by nyanmisaka** [comment]
> A little initial testing [on our version index](https://index-dot-shaka-player-demo.appspot.com/) suggests that this started happening somewhere between v3.3.10 and v4.0.5.

I can narrow it down to between v4.0.0 and v4.0.1.
v4.0.0 still works fine on initial without any seeking.
