### ISSUE TITLE
Severity 2 Error 1001 caused by VTT Text Track Load Failure

### ISSUE THREAD

**Issue by stuartflanagan** [shaka-project/shaka-player#4524]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
I do not have a Local build

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
No as the UI ignores the Severity 2 issue

**What browser and OS are you using?**
Chrome 105

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

When initialising the player we load a `VTT` file via `addTextTrackAsync`.
This then adds a track to enable and disable Closed Captions. If the text track fails to load an error `1001` severity 2 is thrown.

```

        const textTrack = await this.player.addTextTrackAsync(
         'captions-track.vtt',
          'en',
          'captions',
          'text/vtt'
        );
        if (textTrack) {
          this.player.selectTextTrack(textTrack);
        }
      
```

**What did you expect to happen?**
I expected a text track failing to load to not cause a severity 2 error which seems related to a playback failure.

**What actually happened?**

Severity 2 error thrown on error of Loading the VTT file if it is a non OK response code.

We can train our app to ignore `1001` errors but not sure if this will result in hangs and non responsiveness if manifest files or segments fail to load.

**Comment by martinstark** [comment]
Could you please fill out the form fully? Information is missing in order to be able to provide help

**Comment by martinstark** [comment]
Could you please fill out the form fully? Information is missing in order to be able to provide help

My assumption is that you have not configured the player to ignore text stream failures, see [docs](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.StreamingConfiguration)

**Comment by stuartflanagan** [comment]
Thank you. I will close, I was not aware of this property.

**Comment by avelad** [comment]
I close it because of the last comment.
