### ISSUE TITLE
shaka-player version 4.X and 3.X VST (Video startup time) is high compare to 2.5.10

### ISSUE THREAD

**Issue by kumarashu123** [shaka-project/shaka-player#4525]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v2.5.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom APP

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Version 105.0.5195.125 (Official Build) (arm64) MACOs Monterey

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Clear content
https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

manifest: {
                    retryParameters: {
                        timeout: 0,
                        maxAttempts: 5,
                        baseDelay: 1000, 
                        backoffFactor: 3,
                        fuzzFactor: 0.5 
                    }
                },
                streaming: {
                    rebufferingGoal: 1,
                    bufferBehind: 6,
                    bufferingGoal: 10,
                    durationBackoff: 1,
                    ignoreTextStreamFailures: true,
                    jumpLargeGaps: true,
                    smallGapLimit: 0.5,
                    startAtSegmentBoundary: false,
                    retryParameters: {
                        timeout: 0, 
                        maxAttempts: 5, 
                        baseDelay: 1000,
                        backoffFactor: 3,
                        fuzzFactor: 0.5
                    }
                }

**What did you do?**

Play content and check VST time

**What did you expect to happen?**
VST time should match same as 2.5.10

**What actually happened?**

I played content https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd
with v4.2.1 and v3.3.10 and v2.5.10. The number of iteration taken is 10 observed avg VST is high for v4.2.1 and v3.3.10 .

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/amukhiya/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/amukhiya/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>
<meta charset=utf-8>

<body link="#0563C1" vlink="#954F72">
<meta charset=utf-8>

v4.2.1 |   | v2.5.10
-- | -- | --
2.765 s |   | 2.034 s
2.690 s |   | 1.848 s
4.020 s |   | 1.739 s
2.555 s |   | 1.619 s
2.583 s |   | 1.595 s
3.252 s |   | 1.773 s
2.891 s |   | 2.850 s
3.470 s |   | 1.381 s
2.913 s |   | 1.525 s
3.117 s |   | 1.828 s
  |   |  
  |   |  
3.0256 |   | 1.8192

</body>

</html>

**Comment by avelad** [comment]
Can you test with v4.3.4 and main branch? Thanks!
