### ISSUE TITLE
Shaka unable to play live HLS stream on a Set Top Box

### ISSUE THREAD

**Issue by kiran-dcunha** [shaka-project/shaka-player#4536]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Please ask your question**
I am trying to play a live hls stream on a set top box. When I tried to run with default config, this error comes up

`onShakaErrorEvent: shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3016,
  "data": [
    4,
    null,
    "Not authorized to access resource."
  ],
  "handled": false,
  "message": "Shaka Error MEDIA.VIDEO_ERROR (4,,Not authorized to access resource.)",
  "stack": "Error@http://192.168.1.98:3000/lib/shaka.js:3326:24\nvideoErrorToShakaError_@http://192.168.1.98:3000/lib/shaka.js:20890:34\nonVideoError_@http://192.168.1.98:3000/lib/shaka.js:20900:44\nhttp://192.168.1.98:3000/lib/shaka.js:18113:33"
}`

I tried to look around the code and simulate a TV environment, and ensured isTizen() returns true. The first frame loads and there is no playback after that. m3u8 and ts files are continuously downloaded. Below log error is thrown in console, and there is no error thrown by player

`Possible encoding problem detected! – "Unexpected buffered range for reference" (7)
SegmentReference {startTime: 24, endTime: 26, trueEndTime: 26, getUrisInner: function, startByte: 0, …}
"from URIs"
["<stream url>"] (1)
"should be"
{start: 24, end: 26}
"but got"
{start: 88650.073066, end: 88650.113066}
error
(anonymous function) — shaka.js:12544
nextStep_ — shaka.js:458
next_ — shaka.js:409
next — shaka.js:474
b — shaka.js:497
promiseReactionJob
shaka.js:15693`

Entire log is here
`[Info] Using native ARIAMixin interface. (shaka-tizen.js, line 35280)
[Log] MediaSource.install (shaka-tizen.js, line 35521)
[Info] Using native MSE as-is. (shaka-tizen.js, line 35539)
[Log] randomUUID.install (shaka-tizen.js, line 36763)
[Log] Symbol.install (shaka-tizen.js, line 36820)
[Log] VideoPlayPromise.install (shaka-tizen.js, line 36840)
[Info] Using native VTTCue. (shaka-tizen.js, line 36893)
[Info] MediaCapabilities: install (shaka-tizen.js, line 35412)
[Debug] EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. (shaka-tizen.js, line 38962)
[Debug] McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. (shaka-tizen.js, line 39083)
[Log] Selecting manifestpref:"mpd" (index.js, line 400)
[Log] playing url: <stream url>(index.js, line 400)
[Log] Selecting audiopref:"ec-3" (index.js, line 400)
[Log] Selecting maxwidthpref:1920 (index.js, line 400)
[Log] Selecting maxheightpref:1080 (index.js, line 400)
[Info] Starting attach... (shaka-tizen.js, line 17983)
[Log] loadstart (index.js, line 400)
[Info] Starting load of <stream url>... (shaka-tizen.js, line 18053)
[Log] Guessing stream type for – "#EXT-X-STREAM-INF:BANDWIDTH=929975,AVERAGE-BANDWIDTH=810470,RESOLUTION=\"640x360\",FRAME-RATE=25.000,CODECS=\"avc1.4D401F,mp4a.40.2\",URI=\"hdntl…" (shaka-tizen.js, line 30087)
[Log] Guessing multiplexed audio+video. (shaka-tizen.js, line 30098)
[Log] Guessing stream type for – "#EXT-X-STREAM-INF:BANDWIDTH=1669175,AVERAGE-BANDWIDTH=1426470,RESOLUTION=\"854x480\",FRAME-RATE=25.000,CODECS=\"avc1.4D401F,mp4a.40.2\",URI=\"hdn…" (shaka-tizen.js, line 30087)
[Log] Guessing multiplexed audio+video. (shaka-tizen.js, line 30098)
[Log] Guessing stream type for – "#EXT-X-STREAM-INF:BANDWIDTH=2489348,AVERAGE-BANDWIDTH=2121687,RESOLUTION=\"1024x576\",FRAME-RATE=25.000,CODECS=\"avc1.4D401F,mp4a.40.2\",URI=\"hd…" (shaka-tizen.js, line 30087)
[Log] Guessing multiplexed audio+video. (shaka-tizen.js, line 30098)
[Log] Guessing stream type for – "#EXT-X-STREAM-INF:BANDWIDTH=3733510,AVERAGE-BANDWIDTH=3181888,RESOLUTION=\"1280x720\",FRAME-RATE=25.000,CODECS=\"avc1.4D401F,mp4a.40.2\",URI=\"hd…" (shaka-tizen.js, line 30087)
[Log] Guessing multiplexed audio+video. (shaka-tizen.js, line 30098)
[Log] Guessing stream type for – "#EXT-X-STREAM-INF:BANDWIDTH=6109510,AVERAGE-BANDWIDTH=5161888,RESOLUTION=\"1920x1080\",FRAME-RATE=25.000,CODECS=\"avc1.640029,mp4a.40.2\",URI=\"h…" (shaka-tizen.js, line 30087)
[Log] Guessing multiplexed audio+video. (shaka-tizen.js, line 30098)
[Log] Syncing HLS streams against base sequence number: – 11534347 (shaka-tizen.js, line 29552)
[Log] Offset – -4 – "applied to" – "hdntl=exp=1664630902~acl=%2f*~data=hdntl~hmac=99981c4fbc6e01cfc4639921c2a0093999d6b19eaaf79694ef20272c435e731a/index-connected_3.m3u8" (shaka-tizen.js, line 29619)
[Log] Offset – -2 – "applied to" – "hdntl=exp=1664630902~acl=%2f*~data=hdntl~hmac=99981c4fbc6e01cfc4639921c2a0093999d6b19eaaf79694ef20272c435e731a/index-connected_7.m3u8" (shaka-tizen.js, line 29619)
[Log] Offset – -0 – "applied to" – "hdntl=exp=1664630902~acl=%2f*~data=hdntl~hmac=99981c4fbc6e01cfc4639921c2a0093999d6b19eaaf79694ef20272c435e731a/index-connected_5.m3u8" (shaka-tizen.js, line 29619)
[Log] Offset – -4 – "applied to" – "hdntl=exp=1664630902~acl=%2f*~data=hdntl~hmac=99981c4fbc6e01cfc4639921c2a0093999d6b19eaaf79694ef20272c435e731a/index-connected_6.m3u8" (shaka-tizen.js, line 29619)
[Log] Offset – -2 – "applied to" – "hdntl=exp=1664630902~acl=%2f*~data=hdntl~hmac=99981c4fbc6e01cfc4639921c2a0093999d6b19eaaf79694ef20272c435e731a/index-connected_4.m3u8" (shaka-tizen.js, line 29619)
[Debug] notifySegments: – "maxSegmentDuration=2" (shaka-tizen.js, line 12975, x5)
[Log] Found variant with audio and video content, so filtering out audio-only content. (shaka-tizen.js, line 19074)
[Debug] EmeEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support. (shaka-tizen.js, line 38991, x5)
[Info] navigator.requestMediaKeySystemAccess failed. (shaka-tizen.js, line 35494, x5)
[Debug] McEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support. (shaka-tizen.js, line 39122, x5)
[Debug] McEncryptionSchemePolyfill: Native encryptionScheme support found. (shaka-tizen.js, line 39115, x5)
[Info] MediaCapabilities.decodingInfo() failed. – "{\"type\":\"media-source\",\"audio\":{\"contentType\":\"audio/mp4; codecs=\\\"mp4a.40.2\\\"\",\"channels\":2,\"bitrate\":810470,\"samplerate\":1,\"spatialRenderi…" – NotSupportedError: The operation is not supported. (shaka-tizen.js, line 5657)
NotSupportedError: The operation is not supported.
[Info] MediaCapabilities.decodingInfo() failed. – "{\"type\":\"media-source\",\"audio\":{\"contentType\":\"audio/mp4; codecs=\\\"mp4a.40.2\\\"\",\"channels\":2,\"bitrate\":1426470,\"samplerate\":1,\"spatialRender…" – NotSupportedError: The operation is not supported. (shaka-tizen.js, line 5657)
NotSupportedError: The operation is not supported.
[Info] MediaCapabilities.decodingInfo() failed. – "{\"type\":\"media-source\",\"audio\":{\"contentType\":\"audio/mp4; codecs=\\\"mp4a.40.2\\\"\",\"channels\":2,\"bitrate\":2121687,\"samplerate\":1,\"spatialRender…" – NotSupportedError: The operation is not supported. (shaka-tizen.js, line 5657)
NotSupportedError: The operation is not supported.
[Info] MediaCapabilities.decodingInfo() failed. – "{\"type\":\"media-source\",\"audio\":{\"contentType\":\"audio/mp4; codecs=\\\"mp4a.40.2\\\"\",\"channels\":2,\"bitrate\":3181888,\"samplerate\":1,\"spatialRender…" – NotSupportedError: The operation is not supported. (shaka-tizen.js, line 5657)
NotSupportedError: The operation is not supported.
[Info] MediaCapabilities.decodingInfo() failed. – "{\"type\":\"media-source\",\"audio\":{\"contentType\":\"audio/mp4; codecs=\\\"mp4a.40.2\\\"\",\"channels\":2,\"bitrate\":5161888,\"samplerate\":1,\"spatialRender…" – NotSupportedError: The operation is not supported. (shaka-tizen.js, line 5657)
NotSupportedError: The operation is not supported.
[Debug] Got MediaKeySystemAccess with configuration – {audioCapabilities: [], distinctiveIdentifier: "not-allowed", initDataTypes: ["cenc"], …} (shaka-tizen.js, line 8552)
{audioCapabilities: [], distinctiveIdentifier: "not-allowed", initDataTypes: ["cenc"], label: "", persistentState: "not-allowed", …}Object
[Info] Created MediaKeys object for key system – "com.widevine.alpha" (shaka-tizen.js, line 8583)
[Log] Already got the variants' decodingInfo. (shaka-tizen.js, line 5642)
[Debug] Player changing buffering state to – true (shaka-tizen.js, line 20607)
[Debug] Changing effective playback rate to – 0 (shaka-tizen.js, line 14255)
[Debug] Changing Player state to – "buffering" (shaka-tizen.js, line 17511)
[Log] codecs – "avc-" – "avg bandwidth" – 5161888 (shaka-tizen.js, line 5485)
[Warning] No exact match for variant role could be found. (shaka-tizen.js, line 6756)
[Debug] Bandwidth ranges: – "0.810" – "0.853" – "Infinity" (shaka-tizen.js, line 6391)
[Debug] (video:1) – "updating in 0 seconds" (shaka-tizen.js, line 15886)
[Log] init: completed initial Stream setup (shaka-tizen.js, line 14670)
[Warning] No exact match for variant role could be found. (shaka-tizen.js, line 6756)
[Warning] No preferred audio language set.  We have chosen an arbitrary language initially (shaka-tizen.js, line 18702)
[Log] Codecs: avc1.4D401F,mp4a.40.2 (index.js, line 400)
[Log] DRM Used :com.widevine.alpha (index.js, line 400)
[Debug] (video:1) – "timeNeeded=24.128000020980835" (shaka-tizen.js, line 15156)
[Debug] (video:1) – "update_:" – "presentationTime=24.128000020980835" – "bufferedAhead=0" (shaka-tizen.js, line 15161)
[Debug] (video:1) – "looking up segment" – "lookupTime:" – 22.128000020980835 – "presentationTime:" – 24.128000020980835 (shaka-tizen.js, line 15235)
[Debug] (video:1) – "fetchAndAppend_:" – "presentationTime=24.128000020980835" – "reference.startTime=22" – "reference.endTime=24" (shaka-tizen.js, line 15284)
[Debug] (video:1) – "setting timestamp offset to 0" (shaka-tizen.js, line 15564)
[Debug] (video:1) – "setting append window start to 0" (shaka-tizen.js, line 15565)
[Debug] (video:1) – "setting append window end to Infinity" (shaka-tizen.js, line 15566)
[Debug] (video:1) – "fetching segment" (shaka-tizen.js, line 15305)
[Debug] fetching: reference= – SegmentReference {startTime: 22, endTime: 24, trueEndTime: 24, …} (shaka-tizen.js, line 15816)
SegmentReference {startTime: 22, endTime: 24, trueEndTime: 24, getUrisInner: function, startByte: 0, …}SegmentReference
[Debug] Segment downloaded: – "deltaTimeMs=74" – "numBytes=219772" – "lastTimeChosenMs=1664544502220" – "enabled=true" (shaka-tizen.js, line 6409)
[Debug] Suggesting Streams... (shaka-tizen.js, line 6451)
[Debug] Bandwidth ranges: – "0.810" – "0.853" – "Infinity" (shaka-tizen.js, line 6391)
[Log] Calling switch_(), bandwidth=23759 kbps (shaka-tizen.js, line 6474)
[Log] switch_ (shaka-tizen.js, line 20745)
[Debug] (video:1) – "checking buffer length" (shaka-tizen.js, line 15740)
[Debug] (video:1) – "buffer behind okay because nothing buffered:" – "presentationTime=24.128000020980835" – "bufferBehind=Infinity" (shaka-tizen.js, line 15748)
[Debug] (video:1) – "appending media segment at" – "unknown" (shaka-tizen.js, line 15669)
[Log] loadedmetadata (index.js, line 400)
[Log] seeking (index.js, line 400)
[Debug] (video:1) – "appended media segment" (shaka-tizen.js, line 15688)
[Debug] (video:1) – "advancing to next segment" – SegmentReference {startTime: 24, endTime: 26, trueEndTime: 26, …} (shaka-tizen.js, line 15369)
SegmentReference {startTime: 24, endTime: 26, trueEndTime: 26, getUrisInner: function, startByte: 0, …}SegmentReference
[Debug] (video:1) – "finished fetch and append" – "[{\"start\":88954.073066,\"end\":88956.073066}]" (shaka-tizen.js, line 15374)
[Debug] Player changing buffering state to – false (shaka-tizen.js, line 20607)
[Debug] Changing effective playback rate to – 1 (shaka-tizen.js, line 14255)
[Debug] Changing Player state to – "paused" (shaka-tizen.js, line 17526)
[Debug] (video:1) – "updating in 0 seconds" (shaka-tizen.js, line 15886)
[Debug] Changing effective playback rate to – 1 (shaka-tizen.js, line 14255)
[Debug] (video:1) – "timeNeeded=24" (shaka-tizen.js, line 15156)
[Debug] (video:1) – "update_:" – "presentationTime=24.128000020980835" – "bufferedAhead=2" (shaka-tizen.js, line 15161)
[Debug] (video:1) – "fetchAndAppend_:" – "presentationTime=24.128000020980835" – "reference.startTime=24" – "reference.endTime=26" (shaka-tizen.js, line 15284)
[Debug] (video:1) – "fetching segment" (shaka-tizen.js, line 15305)
[Debug] fetching: reference= – SegmentReference {startTime: 24, endTime: 26, trueEndTime: 26, …} (shaka-tizen.js, line 15816)
SegmentReference {startTime: 24, endTime: 26, trueEndTime: 26, getUrisInner: function, startByte: 0, …}SegmentReference
[Debug] Segment downloaded: – "deltaTimeMs=65" – "numBytes=202852" – "lastTimeChosenMs=1664544502382" – "enabled=true" (shaka-tizen.js, line 6409)
[Debug] Suggesting Streams... (shaka-tizen.js, line 6451)
[Debug] Still within switch interval... (shaka-tizen.js, line 6466)
[Debug] (video:1) – "checking buffer length" (shaka-tizen.js, line 15740)
[Debug] (video:1) – "buffer behind okay:" – "presentationTime=24.128000020980835" – "bufferedBehind=-88929.94506597902" – "bufferBehind=Infinity" – "underflow=Infinity" (shaka-tizen.js, line 15760)
[Debug] (video:1) – "appending media segment at" – "unknown" (shaka-tizen.js, line 15669)
[Error] Possible encoding problem detected! – "Unexpected buffered range for reference" (7)
SegmentReference {startTime: 24, endTime: 26, trueEndTime: 26, getUrisInner: function, startByte: 0, …}
"from URIs"
[<stream url>] (1)
"should be"
{start: 24, end: 26}
"but got"
{start: 88956.073066, end: 88956.113066}
	error
	(anonymous function) (shaka-tizen.js:12543)
	nextStep_ (shaka-tizen.js:458)
	next_ (shaka-tizen.js:409)
	next (shaka-tizen.js:474)
	b (shaka-tizen.js:497)
	promiseReactionJob
[Debug] (video:1) – "appended media segment" (shaka-tizen.js, line 15688)
[Debug] (video:1) – "advancing to next segment" – null (shaka-tizen.js, line 15369)
[Debug] (video:1) – "finished fetch and append" – "[{\"start\":88954.073066,\"end\":88956.113066}]" (shaka-tizen.js, line 15374)
[Debug] (video:1) – "updating in 0 seconds" (shaka-tizen.js, line 15886)
[Debug] (video:1) – "timeNeeded=26" (shaka-tizen.js, line 15156)
[Debug] (video:1) – "update_:" – "presentationTime=24.128000020980835" – "bufferedAhead=2.040000000008149" (shaka-tizen.js, line 15161)
[Debug] (video:1) – "updating in 1 seconds" (shaka-tizen.js, line 15886)
[Debug] (video:1) – "timeNeeded=26" (shaka-tizen.js, line 15156)
[Debug] (video:1) – "update_:" – "presentationTime=24.128000020980835" – "bufferedAhead=2.040000000008149" (shaka-tizen.js, line 15161)
[Debug] (video:1) – "updating in 1 seconds" (shaka-tizen.js, line 15886)
[Info] Updating manifest... (shaka-tizen.js, line 31204)
[Debug] (video:1) – "timeNeeded=26" (shaka-tizen.js, line 15156)
[Debug] (video:1) – "update_:" – "presentationTime=24.128000020980835" – "bufferedAhead=2.040000000008149" (shaka-tizen.js, line 15161)
[Debug] (video:1) – "fetchAndAppend_:" – "presentationTime=24.128000020980835" – "reference.startTime=26" – "reference.endTime=28" (shaka-tizen.js, line 15284)
[Debug] (video:1) – "fetching segment" (shaka-tizen.js, line 15305)
[Debug] fetching: reference= – SegmentReference {startTime: 26, endTime: 28, trueEndTime: 28, …} (shaka-tizen.js, line 15816)
SegmentReference {startTime: 26, endTime: 28, trueEndTime: 28, getUrisInner: function, startByte: 0, …}SegmentReference
[Debug] Segment downloaded: – "deltaTimeMs=62" – "numBytes=188564" – "lastTimeChosenMs=1664544502382" – "enabled=true" (shaka-tizen.js, line 6409)
[Debug] Suggesting Streams... (shaka-tizen.js, line 6451)
[Debug] Still within switch interval... (shaka-tizen.js, line 6466)
[Debug] (video:1) – "checking buffer length" (shaka-tizen.js, line 15740)
[Debug] (video:1) – "buffer behind okay:" – "presentationTime=24.128000020980835" – "bufferedBehind=-88929.94506597902" – "bufferBehind=Infinity" – "underflow=Infinity" (shaka-tizen.js, line 15760)
[Debug] (video:1) – "appending media segment at" – "unknown" (shaka-tizen.js, line 15669)
[Debug] (video:1) – "appended media segment" (shaka-tizen.js, line 15688)
[Debug] (video:1) – "advancing to next segment" – SegmentReference {startTime: 28, endTime: 30, trueEndTime: 30, …} (shaka-tizen.js, line 15369)
SegmentReference {startTime: 28, endTime: 30, trueEndTime: 30, getUrisInner: function, startByte: 0, …}SegmentReference
[Debug] (video:1) – "finished fetch and append" – "[{\"start\":88954.073066,\"end\":88956.113066}]" (shaka-tizen.js, line 15374)
[Debug] (video:1) – "updating in 0 seconds" (shaka-tizen.js, line 15886)
[Debug] (video:1) – "timeNeeded=28" (shaka-tizen.js, line 15156)
[Debug] (video:1) – "update_:" – "presentationTime=24.128000020980835" – "bufferedAhead=2.040000000008149" (shaka-tizen.js, line 15161)
[Debug] (video:1) – "fetchAndAppend_:" – "presentationTime=24.128000020980835" – "reference.startTime=28" – "reference.endTime=30" (shaka-tizen.js, line 15284)
[Debug] (video:1) – "fetching segment" (shaka-tizen.js, line 15305)`

Any insights on how to proceed here?

**Comment by kiran-dcunha** [comment]
I figured out why the initial problem occurred. User agent of the box is
`Mozilla/5.0 (Macintosh, Intel Mac OS X 10_11_4) AppleWebKit/602.1.28+ (KHTML, like Gecko) Version/9.1 Safari/601.5.17`
and Shaka was trying to play hls natively. I disabled flag useNativeHlsOnSafari and the same issue occurs wih untouched shaka lib.
![image](https://user-images.githubusercontent.com/102036812/193773605-4eafc542-0993-4fb4-8052-7dc836195803.png)

**Comment by theodab** [comment]
Unfortunately it looks like that `userAgent` string doesn't have any distinguishing characteristics that set it apart as not really being Safari on a Mac. So I don't know if we could change anything to handle this problem.

What brand of Set Top Box is this, incidentally? Some device manufacturers have guides on how to identify their device model by `userAgent`, though I wouldn't hold out hope in this case.

**Comment by kiran-dcunha** [comment]
I did some more tests with different configs and versions. Shaka 3.x is to be able to play the stream with the below config, but without audio.
`shakaPlayer.configure({
    streaming: {
      useNativeHlsOnSafari: false,
    },
  });`

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!
