### ISSUE TITLE
HLS: KEYFORMAT in playlist is optional and should default to "identity"

### ISSUE THREAD

**Issue by duggaraju** [shaka-project/shaka-player#4549]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Windows 11, Firefox.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://jopaynm2store.blob.core.windows.net/hlsenctmpl/master.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default configuration.

**What did you do?**

Try playing an encrypted stream.

**What did you expect to happen?**
Playback to work.

**What actually happened?**

Object { severity: 2, category: 4, code: 4023, data: (1) […], handled: false, message: "Shaka Error MANIFEST.HLS_REQUIRED_ATTRIBUTE_MISSING (KEYFORMAT)", stack: "shaka.util.Error@https://shaka-player-demo.appspot.com/dist/shaka-player.ui.debug.js:181:801\nshaka.hls.Tag.prototype.getRequiredAttrValue@https://shaka-player-demo.appspot.com/dist/shaka-player.ui.debug.js:1578:97\nshaka.hls.HlsParser.prototype.convertParsedPlaylistIntoStreamInfo_/<@https://shaka-player-demo.appspot.com/dist/shaka-player.ui.debug.js:1646:106\n$jscomp.generator.Engine_.prototype.nextStep_@https://shaka-player-demo.appspot.com/dist/shaka-player.ui.debug.js:37:105\n$jscomp.generator.Engine_.prototype.next_@https://shaka-player-demo.appspot.com/dist/shaka-player.ui.debug.js:33:234\n$jscomp.generator.Generator_/this.next@https://shaka-player-demo.appspot.com/dist/shaka-player.ui.debug.js:38:73\nb@https://shaka-player-demo.appspot.com/dist/shaka-player.ui.debug.js:39:73\npromise callback*

As per HLS spec: KEYFORMAT Is optional and should default to "identity" if not specified.   https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.4.4

**Comment by theodab** [comment]
Support for the "identity" format was add in [this commit](https://github.com/shaka-project/shaka-player/commit/b1e81a684afe086b7a37ea29bbbfc972575ba332), which was not included in v4.2.1. Could you try the code from the main branch, instead?
