### ISSUE TITLE
Missing "buffering" event when using custom HttpFetchPlugin

### ISSUE THREAD

**Issue by tyrelltle** [shaka-project/shaka-player#4558]
Hi,
I found sometimes the shaka buffering event is missing, and I believe its related to registering custom HttpFetchPlugin as the issue is not reproduceable without it.
However I am not able to find any relationship between buffering event and HttpFetchPlugin, thus would like to get some hint on where to look at to investigate this issue.

**Context:**
I have a custom HttpFetchPlugin which acts as a http interceptor, it checks each individual segment requests and returns privately cached data if the uri matches the one fetched by shaka.
A simplified Pseudocode:

```
class CustomPlugin extends shaka.net.HttpFetchPlugin {
  public static parse(uri: string, ...): shaka.extern.IAbortableOperation<shaka.extern.Response> {
       const cachedData: Promise<shaka.extern.Response> = ..... find cachedData that matches this uri ....
       If(cachedData) {
           return new shaka.util.AbortableOperation(cachedData)
       } else { 
           return super.parse(uri, ....)
       }
  }
}
```
On the other hand, I am listening to `buffering` event from shaka and start to play the video if bufferingEvent.buffering == false and enough audio and video segments have been buffered.

A normal behavior is (This is working as expected most time):
- time1:  at begining shaka sends buffering=true event
- time2: once video segment is buffered, shaka sends buffering=false event
    - we detect video element readystate is 0, thus we know audio semgnet is not buffered
- time3: after audio segment is buffered, shaka sends buffering=false again, this time we get readyState = 4, knowing both A/V data are buffered.
- time3.1: we start play video

**Problem**
**It worked very well in most cases**. **But if one of the segments is delayed by 2~5 seconds**, there is a `random` chance that a buffering=false Event is missing when both audio and video data are buffered, thus we never start to play the video. (we never get to time3 in above example)
- More strange thing is, when this happens (which is when we never get to time3),  if manually query `shaka.getBufferingInfo` we can see both video and audio have enough buffer data. And video element readyState is 4.
- Therefore I believe the issue is not about insufficent data are buffered, but just one buffering=false event is missing.

I can not reproduce this if disable the custom HttpFetchPlugin
I am suspecting if this is because somehow [stateChange is never true at this line](https://github.com/shaka-project/shaka-player/blob/v4.1.x/lib/player.js#L2879).

Question:
- would you give some hint where in the shaka codebase to look at?

Thanks !

**Comment by turbidwater** [comment]
I am also seeing a similar behavior, although my fetch interception is not through a plugin. I'll get multiple events with buffering: true and not get one with a false value, even when playback continues uninterrupted. I'm on 4.3.6, so I'll be looking forward to 4.4!

**Comment by joeyparrish** [comment]
I don't know how this could be related to fetch plugins or interception.  Buffering events are based on observation of what is buffered at the video element, not at the network level.  It could be a bug in BufferingObserver, though.

**Comment by turbidwater** [comment]
@avelad yes, definitely
