### ISSUE TITLE
Question regarding DASH Parsing

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#4559]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.2.2

**Please ask your question**

1. How can I use the Shaka's DASH parser independently? 
2. How do we calculate the segment index of DASH Live Stream. For example: A MPD gives me `startNumber="24149452">` but as I see in network request the start index of A/V isnt the same value but +450 all time.
3. Currently I am using videojs mpd-parser, Does Shaka allow any such implementation to parse a manifest modify some playlists form it and rebuild the manifest?
4. Live Videos in Shaka Player always buffer on the start for a time `minimumUpdatePeriod` mentioned in manifest. For example: `minimumUpdatePeriod="PT30S"` in manifest, The player starts the first playback after 30 seconds and maintaine the buffer until it reaches that duration of live period.

**Comment by theodab** [comment]
1. The interface isn't really designed to be used directly, but if you really wanted to you could do something like this:
```js
const makeAndRunParser = async (uri) => {
  const parser = new shaka.dash.DashParser();
  const playerInterface = {
    networkingEngine: new shaka.net.NetworkingEngine(),
    // TODO: Fill out any of the callbacks below that seem relevant to you.
    modifyManifestRequest: (request, manifestInfo) => {},
    modifySegmentRequest: (request, segmentInfo) => {},
    filter: (manifest) => {},
    makeTextStreamsForClosedCaptions: (manifest) => {},
    onTimelineRegionAdded: (region) => {},
    onEvent: (event) => {},
    onError: (error) => {},
    isLowLatencyMode: () => false,
    isAutoLowLatencyMode: () => false,
    enableLowLatencyMode: () => {},
    updateDuration: () => {},
  };
  const config = shaka.util.PlayerConfiguration.createDefault().manifest;
  // TODO: Change config values as you see fit.
  parser.configure(config)
  const manifest = await parser.start(uri, playerInterface);
  // TODO: If you don't want the parser to keep updating livestreams, you can stop it now.
  return manifest;
}
```
2. We do not directly expose that information in the manifest structure. If each segment has a separate media file I guess you could determine the segment index from the URI of the segment reference? Something like this:
```js
const reference = manifest.variants[0].video.segmentIndex.references[0];
const uri = reference.getUris()[0];
const path = (new URL(uri)).pathname.split('/');
const filename = path[path.length - 1];
// TODO: Then, extract the segment index from the filename.
```
3. Shaka Player does not support turning the parsed manifest back into text. That is outside the scope of this project, as a media player.
4. I'm not sure what the question is?

**Comment by WINOFFRG** [comment]
Hi! Thanks for the response. 

1. WRT 2, The manifest which I tried doesn't have any `segmentIndex` for all the variants (42) of the video. What could this mean?  

 Just to clarify my question again, Whenever I load the manifest. The `startNumber` let's say found in manifest segment is `24219693` but the first segment which is fetched in network is `24220143` and you can see that again the difference is `450`. And this is probably because of `publishTime` and `availabilityStartTime` args defined in manifest. As much as I know after reading [docs](https://github.com/shaka-project/shaka-player/blob/main/docs/tutorials/manifest-parser.md)
Not sure, Can you confirm how is it calculated that which segment needs to be played first?

2. WRT 4, Let me reframe my question. Whenever I load my manifest it keeps on loading and fetching more and more segments until it reaches a specific time X seconds. The playback then starts normally. What if I restart the live playback again by reloading the page lets say, Then again for the same time X seconds it would wait. 

After some careful observation I found that this X time is equal to `minBufferTime` value specified in manifest. For ex: If the value if `PT30S` then the playback will start after 30 seconds. Similarly if some manifest has the value 8 then the playback will start again after 8 Seconds. What could be the possible reason for this?

Is it because the player is trying to maintain the buffer for that time? If yes, Couldn't have that done proactively? While playing and fetching the later segments for buffer.

**Comment by WINOFFRG** [comment]
2nd Solved, Refer https://github.com/shaka-project/shaka-player/issues/4654


> 1. he manifest which I tried doesn't have any `segmentIndex`
Still waiting for response for 1st.
