### ISSUE TITLE
Allow playback of HLS Media Playlist with AAC by default

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#4561]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**Is your feature request related to a problem? Please describe.**

Example Playlist: https://cdn.theoplayer.com/video/indexcom/index.m3u8
Right now the playlist doesn't work without doing extra configuration. The segments are of type AAC so the player should automatically recognize the type.

**Describe the solution you'd like**

Ignore the mediaPlaylistFullMimeType setting when an AAC segment is detected and initialize the player without any specific configuration.

**Describe alternatives you've considered**

Leave it as it currently is.

**Comment by avelad** [comment]
The proposal is to add the following to https://github.com/shaka-project/shaka-player/blob/main/lib/hls/hls_parser.js#L622

Code not fully tested:
```
const firstReference = streamInfo.stream.segmentIndex.get(0);
if (firstReference) {
  const uri = firstReference.getUris()[0];
  if (uri) {
    const extension = shaka.media.ManifestParser.getExtension(uri);
    if (extension == 'aac') {
      type = 'audio';
      streamInfo.stream.codecs = '';
      streamInfo.stream.mimeType = 'audio/aac';
      streamInfo.stream.type = 'audio';
    }
  }
}
```

**Comment by avelad** [comment]
@theodab what do you think?

**Comment by joeyparrish** [comment]
Sounds good to me

**Comment by theodab** [comment]
> @theodab what do you think?

Yeah, that looks good. I'd probably put it after adding the `streamInfo` to `this.uriToStreamInfosMap_ ` so that it can have an empty line and an explanatory comment above it, to set it apart visually, but that's the only change I can think of.
