### ISSUE TITLE
WebVTT line cue setting not following the spec in UITextDisplayer

### ISSUE THREAD

**Issue by Robloche** [shaka-project/shaka-player#4567]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
4.2.2

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `main`?**
Not tried.

**Are you using the demo app or your own custom app?**
My custom app.

**If custom app, can you reproduce the issue using our demo app?**
Not tried.

**What browser and OS are you using?**
Chrome 105.0.5195.127 (Build officiel) (64 bits)
Windows 10 Pro 21H2

**What did you do?**
I'm using `UITextDisplayer` to display WebVTT subtitles.
This particular subtitles file contains lines like:
```
00:04:32.760 --> 00:04:35.160 align:end position:90% line:91%,end
-J'y vais. Tu viens pas avec moi ?
```

**What did you expect to happen?**
The line should be displayed at the bottom of the screen, as per [specification](https://w3c.github.io/webvtt/#webvtt-line-cue-setting):
`For horizontal cues, this is the vertical offset from the top of the video viewport, [...]`

**What actually happened?**
The line appears at the top of the screen.
Inspecting the style shows me:
```<div style="white-space: pre-wrap; direction: ltr; opacity: 1; display: flex; flex-direction: column; align-items: center; justify-content: flex-end; font-weight: 400; font-style: normal; position: absolute; left: 0px; top: 0px; width: 100%; bottom: 91%; text-align: end; writing-mode: horizontal-tb;"><span style="background-color: rgba(0, 0, 0, 0.8);">-J'y vais. Tu viens pas avec moi ?</span></div>```

I guess `bottom: 91%` should be `top: 91%`.
And indeed, doing it in Chrome DevTools actually moves the line to the bottom of the screen, as expected.

**Comment by Robloche** [comment]
OK, my bad!
I'm just starting with WebVTT and I didn't know that the `end` in `line:91%,end` meant that the positionning starts from the bottom of the screen.
Everything works as expected.

**Comment by Robloche** [comment]
After reading the specs [here](https://w3c.github.io/webvtt/#webvtt-line-cue-setting) and [here](https://w3c.github.io/webvtt/#webvtt-cue-line-alignment) again, it appears that `line:91%,end` means that the bottom of the cue box is positionned at 91% of the viewport's height from the top of the viewport.
So, the subtitles should indeed appear at the bottom of the screen, but not by using `top: 91%` (which would be the translation of `line:91%,start`).

To clarify, `line:91%,end` means that the cue box should have a `top` property set to `91% - <height of cue box>`.

So, it's my understanding that the problem is here:
https://github.com/shaka-project/shaka-player/blob/62906bdc9a26456d213a0c5d33f00b4454cdfb5b/lib/text/ui_text_displayer.js#L594

Please feel free to correct me if I misunderstood the specs.

**Comment by koenoe** [comment]
I'm actually having issues with this right now as well, but with absolute values. I've noticed [this TODO in the code](https://github.com/shaka-project/shaka-player/blob/main/lib/text/ui_text_displayer.js#L579), so I'm actually looking if I can implement this in a PR. Could have a look at the problem @Robloche is having as well, or would it be better to keep this separate?

**Comment by Robloche** [comment]
You could have a look but should you able to fix both issues, 2 PRs would be better, I guess.
I also intend to fix this issue myself but don't have enough time right now.

**Comment by Robloche** [comment]
> To clarify, `line:91%,end` means that the cue box should have a `top` property set to `91% - <height of cue box>`.

In fact, a simpler way ot fix it would be to replace:
`style.bottom = cue.line + '%';`
by:
