### ISSUE TITLE
Add configurable logic to decision to ignore duplicate init data

### ISSUE THREAD

**Issue by Wayne-Morgan** [shaka-project/shaka-player#4572]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
`DrmEngine.newInitData()` decides whether to create a new session based on whether the initData has already been seen. We have some advanced DRM features which means sometimes we'd like to change this result to:
- Force session creation regardless of whether we've already seen the initData
- Prevent session creation regardless of whether we've seen the initData
- follow the default behaviour

**Describe the solution you'd like**
We'd like to provide a function in the DRM configuration which will return one of the three options listed above (something like 'FORCE_CREATE', 'FORCE_IGNORE', or 'CHECK_FOR_DUPLICATE')
Parameters for the above function will include the initData for the keySystem, and the keyStatuses:
```
      let initDataAction = 'CHECK_FOR_DUPLICATE';
      if (this.config_.initDataIgnoreOverride) {
        // Need to find the initData for current keySystem
        const systemIds = shaka.media.DrmEngine.defaultSystemIds_;
        const keySystem = this.currentDrmInfo_.keySystem;
        const currentSystemId = systemIds.get(keySystem);
        const pssh = new shaka.util.Pssh(initData);
        if (pssh) {
          const index = pssh.systemIds.indexOf(currentSystemId);
          if (index >= 0) {
            const ksInitData = pssh.data[index];
            const keyStat = this.getKeyStatuses();
            initDataAction = this.config_.initDataIgnoreOverride(ksInitData, keyStat);
          }
        }
      }
      if (initDataAction === 'FORCE_IGNORE') {
        shaka.log.debug('Ignoring init data');
        return;
      }
      if (initDataAction === 'CHECK_FOR_DUPLICATE') {
        const metadatas = this.activeSessions_.values();
        for (const metadata of metadatas) {
          if (shaka.util.BufferUtils.equal(initData, metadata.initData)) {
            shaka.log.debug('Ignoring duplicate init data.');
            return;
          }
        }
      }
      // Either FORCE_CREATE or no duplicate found
      this.createSession(initDataType, initData,
          this.currentDrmInfo_.sessionType);
```

**Describe alternatives you've considered**
I can't think of an alternative, but would welcome any suggestions

**Additional context**

**Comment by Wayne-Morgan** [comment]
Reviewing the requirements once again, the 'FORCE_CREATE' is not necessary. We need the 'FORCE_IGNORE' and the 'CHECK_FOR_DUPLICATE'.

**Comment by avelad** [comment]
@Wayne-Morgan are you interested on send a PR for it? Thanks!
