### ISSUE TITLE
Infinite loading loop on epiphany

### ISSUE THREAD

**Issue by FireMasterK** [shaka-project/shaka-player#4582]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Can reproduce on nightly

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
epiphany 42.4, Arch Linux

**What did you do?**
Go to the demo player, play any content

**What did you expect to happen?**
Content to load and play

**What actually happened?**
There is a loading loop, without any errors.
However, in my custom app, I get a 3016 - try https://piped.kavin.rocks/watch?v=aqz-KE-bpKQ&disableLBRY=1.
I can share the DASH manifest if necessary.

**Comment by friday** [comment]
They define 3016 like this "This error is given to us when the browser can't play the content. This is out of our control and is usually caused by bad content." See https://github.com/shaka-project/shaka-player/blob/1507b1e84401a160c849927941a15dd598c98281/docs/tutorials/faq.md#frequently-asked-questions

Epiphany doesn't support Fairplay/DRM, so that could be why: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1200

**Comment by FireMasterK** [comment]
> Epiphany doesn't support Fairplay/DRM, so that could be why: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1200

But even regular DASH content doesn't work.

**Comment by friday** [comment]
Safari (and hence also Epiphany) supports only HLS. Not DASH.

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!

**Comment by FireMasterK** [comment]
No luck when testing on my custom application, unfortunately.

**Comment by joeyparrish** [comment]
Does it work in our demo app on Epiphany?  https://shaka-player-demo.appspot.com/demo/

Please use the "custom content" tab to enter your manifest information.

If that fails, please send us the demo link with your content pre-filled, and we will take a look.

If it works in our demo and fails in your custom app, then your custom app is the problem.

**Comment by FireMasterK** [comment]
I could reproduce this with the demo player and demo manifest (for the infinite loading), and 3016 for my custom manifest.

**Comment by FireMasterK** [comment]
@shaka-bot reopen

**Comment by joeyparrish** [comment]
Can you be more specific than "the demo manifest"?  Which content, specifically?

> Please use the "custom content" tab to enter your manifest information.
> If that fails, please send us the demo link with your content pre-filled, and we will take a look.

You can also send a pre-filled link from any non-custom content.  The content URI always appears in the URL parameters when you load something, custom or otherwise.

**Comment by FireMasterK** [comment]
The demo I was referring to was [this](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8;panel=HOME;build=compiled). It seems to load now, but after an extremely long time (usually a few minutes).

The custom DASH manifest is available here: https://rentry.co/hre5r

**Comment by avelad** [comment]
Can you try again with the nightly build? We have improved some things about DASH performance that could affect you. Thanks!

**Comment by FireMasterK** [comment]
Thank you for the update! I've tried the nightly build, and it seems to work great now! :)
