### ISSUE TITLE
A/V sync regression after dynamic ad break on HLS stream

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#4589]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
nightly

**Can you reproduce the issue with our latest release version?**
yes, 4.2.2

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome, macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Will send in separate email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default demo app config

**What did you do?**

Add custom content, play, wait until ad break is over (there will be a timestamp on screen when the "real" program is playing)

Observe A/V sync

**What did you expect to happen?**
A/V to be in sync after ad break

**What actually happened?**

Audio and video are out of sync, and will get more out of sync after successive ad breaks.

We were hoping the issues would be solved by https://github.com/shaka-project/shaka-player/issues/4308 but unfortunately this doesn't seem to be the case.

Using an older version ( https://v3-3-11-dot-shaka-player-demo.appspot.com/demo/ ) A/V are still in sync after the ad break.
Using the nightly version ( https://nightly-dot-shaka-player-demo.appspot.com/demo/ ) A/V are out of sync after the ad break.

**Comment by joeyparrish** [comment]
Thanks for the update.  HLS issues are the top priority right now, but we are still short-handed and the list of HLS issues is long.  If you want to investigate and/or send a PR, that would be most welcome.  If not, we appreciate your patience.

**Comment by fredrik-telia** [comment]
Having done some bisecting, these are my findings:

`36d0b5484fad68dc1d640fbddf2fae3e1eb7169b` - [this commit](https://github.com/shaka-project/shaka-player/commit/36d0b5484fad68dc1d640fbddf2fae3e1eb7169b) has audio in sync, but recurring bufferings as shaka will jump to catch up with seek range

`c438e857f2f122eb45899148e067d68ffec3477c` - [this commit](https://github.com/shaka-project/shaka-player/commit/c438e857f2f122eb45899148e067d68ffec3477c) will fix the buffering from the above commit, but audio will be out of sync after the ad break

I'll see if I can find out more, but I'm not really well versed in hls_parser.js

**Comment by joeyparrish** [comment]
Taking over for @theodab.

**Comment by joeyparrish** [comment]
AV sync is definitely off somewhat (audio seems ~0.5s late?) during main content, but it is impossible to tell if it is off or not during ad breaks.  The ads mostly use voiceovers or titles, so there is not much native language spoken content in the ads to judge AV sync.  It could be that AV sync is universally off, not just off after an ad break.

Further, this content has no EXT-X-PROGRAM-DATE-TIME, which is critical for AV sync.  **I strongly recommend using EXT-X-PROGRAM-DATE-TIME.**

I caught one instance of the ads themselves getting badly out of sync.  I'm going to analyze the ad segments, and I expect to find that they are misaligned at at least one point.  There was an ad in English showing interviews about 66% through the break, which was very helpful in this case.

If an ad is not aligned on the right-hand side (audio ends earlier than video or vice-versa), we might need to realign the SourceBuffers after the discontinuity.  I'm seeing "physical" evidence of this, too, in the debugger:

```js
player.mediaSourceEngine_.sourceBuffers_.audio.timestampOffset -
  player.mediaSourceEngine_.sourceBuffers_.video.timestampOffset
2.0372580000000653
```

This number grows over time during ad breaks, and seems like a plausible measurement of desync.  This would also make sense with my theory above (that audio ends earlier than video or vice-versa in certain ads).  In sequence mode, if an application does not touch timestampOffset during playback, it behaves as an accumulator, showing how much data has actually been appended to the buffers.  Here we see different amounts appended to audio and video over time.

Eventually, this number is great enough that we start getting warnings from the player:

```
Possible encoding problem detected! Unexpected buffered range for reference...
```

**Comment by joeyparrish** [comment]
Good news!  I've watched this several times, and my Swedish is improving.  :sweden: 

It appears that desync increases by roughly 50-100 ms per ad.  Joining mid-ad-break results in less desync that joining during the main program and sitting through an entire ad break.

This content appears to be a loop of the same program and ad content each time.  Each ad break seems to add to the desync by a little more than 1 second.

I'm now experimenting with a change that resynchronizes the SourceBuffers across discontinuity bounds, so that we don't accumulate errors in `timestampOffset` over time.  It should be fairly obvious if the fix is working, since 1) the effect is so pronounced and 2) the effect can be measured in the debug console.

**Comment by joeyparrish** [comment]
I've watched the loop several more times testing my fix, and I'm _certain_ I heard Ingvar Kamprad mentioned twice on the antiques show. :teapot: :couch_and_lamp: :shopping_cart: 

My fix appears to work.  The gist is that we track discontinuity sequence numbers for segment references, and resync `timestampOffset` to the theoretical segment start any time the discontinuity sequence number changes.  I initially did this based on init segments changing, but then sync would fail for self-initializing segments.  Using the actual discontinuity sequence number is more robust, IMO.

This resync is only done at these boundaries, though, and not on every segment.  This way, if segment durations in the playlist are somewhat inaccurate, we don't _introduce_ sync issues by slightly moving the segments within discontinuity boundaries.  Sequence mode is allowed to work as it should up until a discontinuity.

**Comment by joeyparrish** [comment]
My fix works, however, after watching several more rounds, there is another source of accumulated error.  This time, in the playlist itself.

I'm syncing with theoretical segment start times, but those are based on summed segment durations only.  What we really need is to resync against `PROGRAM-DATE-TIME`, which this playlist doesn't have.

@fredrik-telia, can `PROGRAM-DATE-TIME` be added?  What I've done so far is an improvement, but it's not perfect.  If I have a sample with `EXT-X-PROGRAM-DATE-TIME` after each `EXT-X-DISCONTINUITY`, or even just after the discontinuity that brings us back into the main program, I can follow up on this change to make it stay in sync better over an arbitrarily long playback session.

**Comment by fredrik-telia** [comment]
Thank you so much for your findings, hopefully we can add `PROGRAM-DATE-TIME` 🙏

**Comment by fredrik-telia** [comment]
I believe the config for the test url has been updated now, might take a few minutes for the change to take effect

**Comment by joeyparrish** [comment]
I'm not seeing PROGRAM-DATE-TIME in the playlists yet.

**Comment by joeyparrish** [comment]
Not present when joining main content, and not added after ad discontinuities, either.

**Comment by joeyparrish** [comment]
I'll go ahead and update the tests affected by the fix I have so far, and get that through review today if I can.  That fix should be in an update this week.

If I still don't have DATE-TIME in the playlists at that point, I'll start working on a change to use that for continuous sync (instead of one-time startup sync as it stands today), but that change will be purely theoretical until I have content to verify it.  This second fix may not make it into this week's updates, and may get pushed out to January while we are on holiday.

**Comment by martinstark** [comment]
Thanks again for all the work @joeyparrish, working on getting the stream looked at

**Comment by joeyparrish** [comment]
No, it's not on my radar.  Thanks!

**Comment by fredrik-telia** [comment]
@joeyparrish adding `&yo.pdt=true` to the url should make the `PROGRAM-DATE-TIME` tags appear

**Comment by joeyparrish** [comment]
Thanks!  I'll try that out.

**Comment by joeyparrish** [comment]
I ran out of time to work on this before the holidays.  I'll be back on this in January.  Thanks!

**Comment by martinstark** [comment]
Happy Holidays! 

We can verify that 4.2.6 solves the issue on our end, presumably with the smaller drift still in place. There are some query params that were left out that may mitigate that.

**Comment by joeyparrish** [comment]
Hi everyone.  I'm back from holidays, but unable to access the content due to a CORS error.  Could you allow cross-origin access to your content again?  Thanks!

**Comment by martinstark** [comment]
@joeyparrish welcome back! Let me know if there's anything else you need.

**Comment by joeyparrish** [comment]
What's in `main` today uses PDT to sync the first segment in each playlist, and then trusts the durations after that. 
 Theoretically, with roughly millisecond-accurate durations, rounding errors could accumulate to a drift of up to 1ms per segment.  In practice, with this content, I see a drift of only about 1ms per 7 or 8 segments (roughly 1ms drift every 30s of content).

I have written new code to sync _each_ segment with its PDT instead, which should correct for duration rounding errors in content where that number is based on an actual wall clock time.

However, whatever is generating this stream on the backend seems to generate the PROGRAM-DATE-TIME values based on the segment durations, so using PDT to sync this content results in the exact same drift as using the declared segment durations.

For example, on startup, PDT is in sync for audio and video, but after ~23 minutes I see a 47ms offset in PDT.  AV sync being off by that much is somewhat noticeable.  After an hours, AV sync drifts past 100ms which is _very_ noticeable.  If I reload the stream and create a new session with the backend, the PDT values change for the same segments.  So they are clearly not real.

So I think I've solved the issue, but I can't verify it with this test stream.

@martinstark, @fredrik-telia, is there a real live stream I can get access to?  I'm not sure if the behavior I'm seeing is because the stream is simulated, or if the same backend will always generate PDT based on segment durations instead of actual wall clock time.

**Comment by joeyparrish** [comment]
If anyone wants to test the latest fix I've made, it's currently available as a draft PR: https://github.com/shaka-project/shaka-player/pull/4870

**Comment by martinstark** [comment]
> is there a real live stream I can get access to
I'll see what I can do. I can quickly get you an account to log in to our sites if you are up for digging out auth tokens and stream URLs yourself, is that good enough? It will take me some more time if I have to sort out long lived tokens and stitched URL sessions. There are a couple of layers or timing-sensitive tokens/sessions for the stitched streams.

**Comment by joeyparrish** [comment]
Yes, I can do that.  I can also VPN to Sweden if necessary, at least on days I come into the Google office in person.

If the content can be accessed from anywhere, though, it will allow me to test on days I work from home.

**Comment by martinstark** [comment]
I'm working on getting a production account whitelisted for the US, VPNs are unfortunately actively blocked. In the meantime, I've emailed a set of new streams that can be used for testing. The subject line includes #4589.

**Comment by joeyparrish** [comment]
Thanks!  My day is just starting, so I'll work on this now.

**Comment by joeyparrish** [comment]
The production stream has the same problem as I observed on the test stream.  After an ad break, the PDT values for the main content are out of sync.  In the break I just watched, the video and audio ad segments differed in length by 5ms.  After the break, the PDT values for the main content differed by 5ms for video and audio.  If I rejoin with a new session, the same segments have synced PDT values again.

The same is true of the updated test stream.  In that case, the first ad break put the main content out of sync by 38ms.

The PDT values in your content are different for the same segments in different sessions, which makes them unreliable for AV sync.  The "align pdt" setting you mentioned in your email does not appear to have any effect on the stream.

This needs to be resolved in the ad stitcher, I believe, before the player can make use of the information.  If we stay in a session with your content long-term, all available information from the manifest (PDT, segment durations) would direct us to play out of sync.  The player can't create the correct information from any source.

**Comment by joeyparrish** [comment]
I just discovered a bug in the fix from PR #4824, which affects v4.3.2 and v4.2.6 only.  The result is some bogus "encoding problem detected" logs and a repeated segment, and I believe it is triggered by ABR changes.

I'm testing a fix and will put up a new PR to fix it ASAP.

**Comment by martinstark** [comment]
Thanks again. I think the original A/V sync issue reported here by us have been fixed, and what remains for us is to fix our bad content. That probably means this issue could be closed, unless you would like to wait for access to production sites to run more tests?

Regarding the 4.2.6 bug, it's not a fatal playback error that kills streams?

**Comment by martinstark** [comment]
> In the break I just watched, the video and audio ad segments differed in length by 5ms. After the break, the PDT values for the main content differed by 5ms for video and audio. 
> If I rejoin with a new session, the same segments have synced PDT values again.

The end of the adbreak also comes with a DISCONTINUITY flag.

https://www.rfc-editor.org/rfc/rfc8216.html#section-6.3.3
  
  > The client MUST be prepared to reset its parser(s) and decoder(s)
  > before playing a Media Segment that has an EXT-X-DISCONTINUITY tag
  > applied to it; otherwise, playback errors can occur.

Would resetting the parser not be the same as rejoining, thus syncing the PDT values?

**Comment by martinstark** [comment]
Thanks for the feedback, we'll be bringing up this accumulating offset with the ad stitching service provider. Should we keep this issue open to continue the discussion once we know more, or would you consider the root issue fixed on the Shaka side?

Regarding the bug in 4.2.6, is it a fatal playback error?

**Comment by joeyparrish** [comment]
I think I found the high-level cause of the bug in my PR, and why my PR triggers it.

There is a periodic "encoding problem detected" log with the new PR, and audio seems to skip/repeat.

The issue always surfaces right after a playlist update, when we merge old and new segment references in HlsParser.  The adjusted times seem to cause an issue with this merge, which throws off the SegmentIterator used by StreamingEngine to decide what to fetch next.  We then fetch the same audio segment we already fetched.

Since we didn't reset anything in MediaSourceEngine (no discontinuity or adaptation), this repeated audio segment gets put at the end of the buffer, which we detect as an "encoding problem" (because the segment isn't where it was supposed to be according to the metadata).

I haven't yet figured out why mergeAndEvict breaks SegmentIterator, but it must relate to the small time adjustments made by the PR.

**Comment by joeyparrish** [comment]
`merge()` left behind a duplicate segment because of a rounding error of about 0.238 microseconds:

```js
    this.references = this.references.filter((r) => {
      return r.startTime < references[0].startTime;
    });
```

That strict less-than is what is broken by the rounding error.

**Comment by joeyparrish** [comment]
Several issues found that could all contribute, all uncovered by doing progressive sync against PDT for all segments.  None of these seem to be an issue before PR #4870, but any of them could have been triggered in other ways.

1. SegmentIndex is vulnerable to tiny rounding errors on merge, leading to duplicate segments in the index and large AV sync issues when iterating through in sequence mode
2. StreamingEngine assumes that the buffered range will align with segment references when a new iterator is needed, but this is not necessarily true
3. The "encoding problem detected" logic in MediaSourceEngine can be fooled by overwriting a buffered range (can be necessary with a new segment iterator in StreamingEngine) or by very tiny segments (as we get from Google DAI sometimes)

**Comment by martinstark** [comment]
Great discoveries! We're working on putting together a summary of issues we're having with playing Fairplay HLS non-natively in Shaka, all of them related to live streams unpredictably being unable to start. Sometimes works, sometimes throws, sometimes stalls in a jump loop at startup trying to catch up to live. Mentioning it in case the changes being made now may affect this case as well.

**Comment by martinstark** [comment]
We've seen a big increase in `MEDIA_SOURCE_OPERATION_THREW` after going from 4.2.4 -> 4.2.6, we're reverting back to 4.2.4 for that reason. The full message is `"message":"Failed to set the 'timestampOffset' property on 'SourceBuffer': The timestamp offset may not be set while the SourceBuffer's append state is 'PARSING_MEDIA_SEGMENT'."`.

**Comment by martinstark** [comment]
@joeyparrish we were informed of the `yo.pdt=sync` parameter, which in our testing seems to solve the misaligned PDTs. If you would like, you can test it with the URLs provided previously.

**Comment by joeyparrish** [comment]
Thanks!  I'll try it out.

I've just started the release process for v4.3.3 and v4.2.7 which will include all the fixes tracked in this issue.

**Comment by joeyparrish** [comment]
Perfectly in sync after 45 minutes with the latest fixes and `yo.pdt=sync`.

**Comment by joeyparrish** [comment]
And I've seen these ad breaks so many times now, I really want to watch "Marko & Irma".

**Comment by martinstark** [comment]
Thanks so much for the great work!

**Comment by martinstark** [comment]
@joeyparrish this issue https://github.com/shaka-project/shaka-player/issues/4431 has returned when using `yo.pdt=sync`. Without the parameter there is no stalling, with the parameter startover streams will regularly stall a short period after going "static".

**Comment by varvaruc** [comment]
@joeyparrish Hi, where is this `yo.pdt=sync` config from ?

**Comment by spvishwas122** [comment]
https://github.com/shaka-project/shaka-player/issues/4589#issuecomment-1382163259
@joeyparrish 
how do we set yo.pdt=sync? 
is it a configuration parameter? 

We are seeing AV sync issues in 4.3.4 as well.

**Comment by fredrik-telia** [comment]
it is a query parameter on the url for this particular type of stream, it has nothing to do with shaka

**Comment by theodab** [comment]
Unfortunately, this fix was found to cause other issues (see issue #5785).
