### ISSUE TITLE
DASH Widevine: read pssh from the manifest before license request

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [shaka-project/shaka-player#4600]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Please ask your question**

In our current implementation we are making a request (outside of shaka) to the MPD and reading the response body to grab the pssh key:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
(...)
<AdaptationSet (...)>
    <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" />
    <ContentProtection schemeIdUri="urn:uuid:(...)" value="Widevine">
        <cenc:pssh>(...)</cenc:pssh>
    </ContentProtection>
(...)
```

We need to do this because we need to do some extra steps to transform the pssh and add a KID query parameter to the license server URI and make a request to get an authorization token to use on the license request.

For this part, I already read the documentation for [Asynchronous Credentials](https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html) and have no questions on how to implement it.

So, how should I go to get the manifest pssh using, maybe, `player.getNetworkingEngine().registerRequestFilter((type, request) => { (...) }`.

Thanks in advance for you help!

**Comment by ricardo-a-alves-alb** [comment]
One approach I figured out:

```js
player.getNetworkingEngine().registerResponseFilter((type, response) => {
  if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST) return
  const manifest = shaka.util.StringUtils.fromBytesAutoDetect(response.data)
})
```

This way, I can read the Manifest loaded by Shaka Player. However, my question lies if there is a way to do this better?

**Comment by ricardo-a-alves-alb** [comment]
Think I found out how to retrieve it, can you please validate?

```js
player.getNetworkingEngine().registerRequestFilter((type, request) => {
  if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) return

  const psshKey = shaka.util.Uint8ArrayUtils.toBase64(request.initData)
}
```

**Comment by riksagar** [comment]
You can also use shaka.net.NetworkingEngine.registerScheme('drm', ...
That allows you to implement your own license handling.

Couldn't find much good documentation in a quick search just now.

**Comment by ricardo-a-alves-alb** [comment]
Thanks for your help, gonna look into it!

**Comment by ricardo-a-alves-alb** [comment]
> Think I found out how to retrieve it, can you please validate?
> 
> ```js
> player.getNetworkingEngine().registerRequestFilter((type, request) => {
>   if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) return
> 
>   const psshKey = shaka.util.Uint8ArrayUtils.toBase64(request.initData)
> }
> ```

Ended up going this route.
