### ISSUE TITLE
Live Dash DRM on webOS buffering

### ISSUE THREAD

**Issue by giladna** [shaka-project/shaka-player#4604]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
ues

**What version of Shaka Player are you using?**
yes

**Please ask your question**

What can be a reason for shaka player to work fine with live dash drm on chrome but same code on webOS will get into buffering / playing state constantly

we tried buffering goal config which did not help
we saw that disabling audio helped for that issue but it is not a solution

please advise.
thanks!

**Comment by avelad** [comment]
Can you test with v4.3.4 and main branch? Thanks!
