### ISSUE TITLE
Shaka-player not rendering CEA-608 Closed Captions

### ISSUE THREAD

**Issue by pravarkulkarnixperi** [shaka-project/shaka-player#4605]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.2.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Google Chrome 106.0.5249.119

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
Manifest URL - https://connect-integration-msp-edge.connectcdn.net/mm/dash/live/7197_DASH_DAI/LIVESERVICE_1234/group=TG_WIFI_HD.mpd

License server URL - https://connect-integration-msp-edge.connectcdn.net/core/v5/drm/widevine/get_license

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
We are using default player configuration at https://shaka-player-demo.appspot.com/

**What did you do?**
1. Load manifest url and license url in demo player(https://shaka-player-demo.appspot.com/)( used goole chrome with web security off to avoid CORS error issues)
2. Start playback and turn on close caption (language is shown as "Unrecognized()"
3.  No closed captions are seen

**What did you expect to happen?**
We are expecting to see closed captions when we turn on closed captions. Similar thing is working on reference dash if player(https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html), we are seeing correct closed captions.

**What actually happened?**

Not able to render closed captions(CEA-608) on Shaka player.

No closed captions of Shaka-player
![Shaka Player](https://user-images.githubusercontent.com/92617844/197185286-0e78daa8-cef6-4143-bf83-ceb6c50cc84f.PNG)

Dash-if player is showing closed captions with same stream.
![dash-if Player](https://user-images.githubusercontent.com/92617844/197185514-909834fe-7bbe-4e82-947a-c357bf5a6dcc.PNG)

**Comment by pravarkulkarnixperi** [comment]
any update on this??

**Comment by joeyparrish** [comment]
No updates at this time.  Nobody has looked into this issue yet.  If you want to start debugging it yourself, you should look into lib/media/, in media_source_engine.js, closed_caption_parser.js, and everything in lib/cea/.

You can also try various older versions of Shaka Player.  If this is a regression, and you can tell us a version that **did** work for your content, it should be much, much easier for us to find the root cause by bisecting and finding a particular revision that broke it.  See https://index-dot-shaka-player-demo.appspot.com/ for an index of older releases.

Sorry we haven't been able to look into your issue yet.

**Comment by joeyparrish** [comment]
Just had a quick chat with @avelad, who started investigating this issue.  It appears that we're missing an offset into the MDAT data, so we begin parsing at the wrong location.

**Comment by pravarkulkarnixperi** [comment]
@joeyparrish thanks for update

**Comment by pravarkulkarnixperi** [comment]
@joeyparrish Is this fix available on https://shaka-player-demo.appspot.com/demo/ ? Because I am still seeing no captions in Shakaplayer demo app above
![shaka-4-3-captions-not-showing](https://user-images.githubusercontent.com/92617844/201251653-90842f71-ce03-4765-9975-1fe9371c034c.PNG)
![dashif-captions-showing](https://user-images.githubusercontent.com/92617844/201251668-b9eaa5ad-d689-4409-8275-265a1d351f44.PNG)

**Comment by joeyparrish** [comment]
Yes, it should be.  The fix was in the v4.3.0 release.

I just tried to check the content URLs from this issue, but I'm denied access to the license server.  I can't disable CORS because I'm on a Chromebook at the moment, and can't control Chrome's command line options in this context.

**Comment by pravarkulkarnixperi** [comment]
I am still able to reproduce the issue. Can you guys please look into it.

**Comment by avelad** [comment]
It’s broken when the stream is encrypted
