### ISSUE TITLE
RESTRICTIONS_CANNOT_BE_MET error for using only one DRM key for both audio and video track

### ISSUE THREAD

**Issue by tmdnk** [shaka-project/shaka-player#4608]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not tried

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Windows 10 Pro
Chrome Version 106.0.5249.119 (Official Build) (64-bit)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

I sent to the mail address.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```
  player.configure({
    preferredTextLanguage: 'el',
    streaming: {
        bufferingGoal: 10
    },
    drm: {
      servers: {
        'com.widevine.alpha': license_server_uri
      }
    }
  });
```

**What did you do?**

Encrypted the video(SD) and audio track using the same key id.
The DRM key is generated by myself.
I know you are suggesting to use different keys for each track.
For some reason we need to use the same one.
I tested license server with Widevine and PlayReady.
Playready works.
Widevine does not work.

**What did you expect to happen?**
The DRM encrypted content can be played when using Widevine license server.

**What actually happened?**

The playback failed with the following error message:
```
shaka.util.Error {severity: 2, category: 4, code: 4012, data: Array(1), handled: false, …}
Shaka Error MANIFEST.RESTRICTIONS_CANNOT_BE_MET ([object Object])
```

**Comment by tmdnk** [comment]
I don't know why, but the playback works now.

**Comment by joeyparrish** [comment]
There may have been a Widevine license server rollout involved in the failure.  I think I heard something about a rollback involving key reuse between video and audio.

For what it's worth, using the same key for video and audio makes it much easier for your content to be compromised.  Audio paths are generally much less protected than video paths in a DRM implementation, and using the same key for both can allow someone (in some cases) to decrypt video using the audio path, without sending it through secure decoders.

Widevine very explicitly warns against using the same key for audio and video.

I hope that helps!
