### ISSUE TITLE
infinite loop when error

### ISSUE THREAD

**Issue by BOUDASS** [shaka-project/shaka-player#4610]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**

2.5.23
**Please ask your question**

I have a problem with shaka player, when I go into hibernate mode then I unlock my pc, I get 403 errors in a loop, the retryParams does not work!

this is my config 
manifest: {
                    dash: {
                        ignoreMinBufferTime: true,
                        ignoreSuggestedPresentationDelay: true,
                        defaultPresentationDelay: 5
                    },
                    retryParameters: {
                        maxAttempts: 5,
                        baseDelay: 1000,
                        backoffFactor: 2,
                        fuzzFactor: 1,
                        timeout: 5000
                    }
                },
                streaming: {
                    bufferingGoal: 6,
                    rebufferingGoal: 2,
                    bufferBehind: 6,
                    smallGapLimit: 2,
                    jumpLargeGaps: true,
                    startAtSegmentBoundary: false,
                    retryParameters: {
                        maxAttempts: 5,
                        baseDelay: 1000,
                        backoffFactor: 2,
                        fuzzFactor: 1,
                        timeout: 5000
                    }
                },

**Comment by joeyparrish** [comment]
> I have a problem with shaka player, when I go into hibernate mode then I unlock my pc, I get 403 errors in a loop, the retryParams does not work!

How would we reproduce the issue?  Does it require certain content?  Can it be reproduced on the Shaka Player Demo app, or only in your own app?

**Comment by sabina4** [comment]
> > I have a problem with shaka player, when I go into hibernate mode then I unlock my pc, I get 403 errors in a loop, the retryParams does not work!
> 
> How would we reproduce the issue? Does it require certain content? Can it be reproduced on the Shaka Player Demo app, or only in your own app?

I have a similar problem.  When the internet connection is lost I get 1002 errors in a loop. We use private servers and I am not able to reproduce on the shaka demo app.

I have the same config params:
manifest: {
dash: {
ignoreMinBufferTime: true,
ignoreSuggestedPresentationDelay: true,
defaultPresentationDelay: 5
},
retryParameters: {
maxAttempts: 5,
baseDelay: 1000,
backoffFactor: 2,
fuzzFactor: 1,
timeout: 5000
}
},
streaming: {
bufferingGoal: 6,
rebufferingGoal: 2,
bufferBehind: 6,
smallGapLimit: 2,
jumpLargeGaps: true,
startAtSegmentBoundary: false,
retryParameters: {
maxAttempts: 5,
baseDelay: 1000,
backoffFactor: 2,
fuzzFactor: 1,
timeout: 5000
}
},
