### ISSUE TITLE
"Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': MediaDrmBridge creation failed"

### ISSUE THREAD

**Issue by dokkuvisweswara** [shaka-project/shaka-player#4611]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes
**What version of Shaka Player are you using?**
yes

**Can you reproduce the issue with our latest release version?**

yes
**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**

my custom app
**If custom app, can you reproduce the issue using our demo app?**
not sure

**What browser and OS are you using?**
android chrome 106

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
after playing multiple times 
it's giving
ERROR Error: Uncaught (in promise): shaka.util.Error {
  "severity": 2,
  "category": 6,
  "code": 6002,
  "data": [
    "Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': MediaDrmBridge creation failed"
  ],
  "handled": false
}

**What did you expect to happen?**

**What actually happened?**

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
