### ISSUE TITLE
Error Code: 6008 "Failed to execute 'update' on 'MediaKeySession': Rejected with system code (13)" when attempting to download DASH file to offline storage

### ISSUE THREAD

**Issue by jookeboxpm** [shaka-project/shaka-player#4618]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Unsure

**Please ask your question**
I am attempting to download a DASH File along with the license from widevine to play the file in offline. But every attempt at download throws the error described in the title. 

Logging the result of "window.storage.store(manifestUri, trackName)" gives the following response.
`Je {promise: Promise, g: false, i: ƒ, then: ƒ}
g: false
i: ƒ ()
promise: Promise
[[Prototype]]: Promise
[[PromiseState]]: "rejected"
[[PromiseResult]]: N
category: 6
code: 6008
data: Array(1)
0: "Failed to execute 'update' on 'MediaKeySession': Rejected with system code (13)"
length: 1
[[Prototype]]: Array(0)
handled: false
severity: 2
[[Prototype]]: Object
then: ƒ (h)
`
Attached below is the function:
![Shaka_6008](https://user-images.githubusercontent.com/63845268/198002833-dc49dc94-01d8-4c0e-bc75-7a3d68669481.PNG)

I request your help in determining why the error is being thrown. I can fetch the license key any time when I simply stream the DASH file. It is only when I attempt to download that the error crops up

**Comment by joeyparrish** [comment]
> Error Code: 6008 "Failed to execute 'update' on 'MediaKeySession'

This means that we passed a license response to the browser's CDM, and the update() method failed.

> Rejected with system code (13)"

This means that the Widevine CDM sees the license response as malformed.  That's a broad category, and there's not much else I can tell you from this error code alone.

Does this help?

**Comment by jookeboxpm** [comment]
Thank you for the suggestions.. It helped me find the fix.

I had to set the storage.configure to the following parameters:
![Shaka_offline_storage_config](https://user-images.githubusercontent.com/63845268/198256562-20297f29-fa98-48d6-8c4b-c86fc41fc3c0.PNG)

The error was reolved and the files began downloading to the local indexDB.
