### ISSUE TITLE
HLS -  Lazy-Load: getIteratorForTime error

### ISSUE THREAD

**Issue by avelad** [shaka-project/shaka-player#4621]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** Main branch

**Are you using the demo app or your own custom app?** Demo app

**What browser and OS are you using?** Chrome - macOS

**What are the manifest and license server URIs?** 
https://1a6165c21d46.us-east-1.playback.live-video.net/api/video/v1/us-east-1.730308843620.channel.w5pCM6EGFwrJ.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default

**What did you do?**
Load the previous stream and switch between resolutions

**What did you expect to happen?**
It works!

**What actually happened?**
![Captura de Pantalla 2022-10-26 a las 9 54 13](https://user-images.githubusercontent.com/8983024/198088703-9165d55a-6dff-404a-9dfa-c8b0b4f7cfbd.png)

https://user-images.githubusercontent.com/8983024/198088723-7fa0b7a4-29af-4a77-ada4-3bf0caf264e7.mp4

**Comment by joeyparrish** [comment]
I found the root cause.  It's this part of hls_parser.js:

```js
    const downloadSegmentIndex = async () => {
      // Un-assign this function, so that if it's called a second time we don't 
      // download twice.
      stream.createSegmentIndex = () => Promise.resolve();
```

It means that if the function is called a second time before the first call completes, it will return a resolved Promise before the segmentIndex has been constructed.

**Comment by joeyparrish** [comment]
To trigger the bug, StreamingEngine needs to try to create a segment index in `makeAbortDecision_()`, then while that is in process, `onUpdate_()` needs to run and try to create a segment index as well.  This second call returns immediately, without waiting for the index to be created.

These things will happen any time the call to switch streams occurs in the middle of a fetch-and-append operation.
