### ISSUE TITLE
ios 16.1 native player is no longer playing DRM protected videos

### ISSUE THREAD

**Issue by jukart** [shaka-project/shaka-player#4626]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.2.2

**Can you reproduce the issue with our latest release version?**
already on latest version

**Can you reproduce the issue with the latest code from `main`?**
not tried

**Are you using the demo app or your own custom app?**
own

**If custom app, can you reproduce the issue using our demo app?**
no, we can not play our DRM protected video using the demo app (independent of this problem)

**What browser and OS are you using?**
Safari on ios 16.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
installed ios 16.1 on iPhone and iPad

**What did you expect to happen?**
video is playing in ios native player as it did with ios 16.0

**What actually happened?**
We installed ios 16.1 on iPhone and iPad and DRM protected videos are no longer playing:
- Player reports buffering and stays in this state.
- All the DRM requests are done as on mac safari (where it plays the videos)
- After 2 minutes shaka player reports error 3016 with 'Media failed to decode'

The issue seems to be related to the native player because we have a Kaltura player working without native player.
We can not switch off useNativeHlsOnSafari because of the file format provided by our backend (Kaltura).

**Comment by joeyparrish** [comment]
You omitted some critical information from the form:

> **What are the manifest and license server URIs?**
> 
> **What configuration are you using? What is the output of `player.getConfiguration()`?**

Without these details, we will not be able to help you with this issue.  You can send private details (URLs, auth tokens, etc) to `shaka-player-issues@google.com`.

Thanks!

**Comment by jukart** [comment]
@joeyparrish  It is still an issue but it would not help if I provide you with the manifest and licence URLs because additional code to transform the licence request body is needed to be able to use it.
I was hoping that someone may have the same issue.

**Comment by joeyparrish** [comment]
> @joeyparrish It is still an issue but it would not help if I provide you with the manifest and licence URLs because additional code to transform the licence request body is needed to be able to use it.

Could you provide that as well, then?  The fact remains:

> Without these details, we will not be able to help you with this issue. You can send private details (URLs, auth tokens, etc) to shaka-player-issues@google.com.

If you decide to provide us with a means to reproduce the issue, you can include `@shaka-bot reopen` in a comment to bring it back to our attention.  Thanks!
