### ISSUE TITLE
EBU subtitles regression in 4.1.3 - duplicate line on screen

### ISSUE THREAD

**Issue by david-hm-morgan** [shaka-project/shaka-player#4631]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://otvplayer.nagra.com/demo/content/bbc/bbc_ebu-tt-d_subtitle_fragmented/dash/ondemand/elephants_dream/1/client_manifest-all-minus-1080p.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.2.2-uncompiled

also seen in 4.2.3, 4.2.1, 4.2.0, 4.1.5, 4.1.4, 4.1.3

Its OK in 4.1.2

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

**What did you do?**

1. Play this stream
2. enable captions
3. monitor the text that is rendered

**What did you expect to happen?**
At around 3 mins we should see the line
`You - I mean we - we could easily die out here`
There are several other examples of duplication in the text during this stream, this is just one example.

**What actually happened?**
The line is repeated.  Two copies.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/37144605/198643506-0c69cf9c-1c12-4ff0-bd05-289eec656286.png">

**Comment by david-hm-morgan** [comment]
@Wayne-Morgan  FYI

**Comment by theodab** [comment]
When I try to load https://otvplayer.nagra.com/vod/dash/clear/bbc/bbc_ebu-tt-d_subtitle_fragmented/dash/ondemand/elephants_dream/1/client_manifest-all-minus-1080p.mpd, I get a 403 forbidden error.

**Comment by david-hm-morgan** [comment]
> When I try to load https://otvplayer.nagra.com/vod/dash/clear/bbc/bbc_ebu-tt-d_subtitle_fragmented/dash/ondemand/elephants_dream/1/client_manifest-all-minus-1080p.mpd, I get a 403 forbidden error.

Apologies @theodab I've corrected the URL in the issue report, please refer to 
https://otvplayer.nagra.com/demo/content/bbc/bbc_ebu-tt-d_subtitle_fragmented/dash/ondemand/elephants_dream/1/client_manifest-all-minus-1080p.mpd

**Comment by david-hm-morgan** [comment]
I've been debugging this a little and comparing to v4.1.2 where you can see in the DOM the subtitle text is actually duplicated, so this is not literally a regressiom with v4.1.3 because the issue was there but it was not visible
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/37144605/200180934-d7bdf29e-a5f1-43fc-8366-c0b6f8680230.png">

However, with 4.1.3 due to perhaps !4412 it becomes visible.
!3018 introduced the checking for duplicates with a view to efficiency, but unfortunately in this case the duplications appear at different places in the cue/nestedCue tree so are not eliminated as duplicates.

**Comment by david-hm-morgan** [comment]
Currently I am looking into adding some code to check for existence of nested duplicates in the `ui_text_displayer`'s `append()` function.  My idea is to check for cues that have been split across segments i.e. where there is an overlap between the cues being added and those already in the list.  Then looking deeper into them to see if the last child of the existing list contents matches the first child of the one being added, if they match, discard the second copy.
I have something working but its not an elegant solution yet.

**Comment by joeyparrish** [comment]
Thank you for working on a fix!
