### ISSUE TITLE
Allow to remove the robustness from the equation instead of defaulting to an empty string

### ISSUE THREAD

**Issue by subhanahmed047** [shaka-project/shaka-player#4659]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

I have been trying to get Shaka player up and running on Panasonic TVs (which isn't currently on the Shaka's [support matrix](https://github.com/shaka-project/shaka-player#platform-and-browser-support-matrix)). I'm currently testing with Shaka `v4.2.1`. 

I've got access to three different `Panasonic TVs`. While one of them worked out of the box, the other models threw the following 6001 (`REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE`) error.

![Shaka 6001 Error](https://i.imgur.com/aVXSzPi.png "Shaka 6001 Error")

Notice the `MediaCapabilities.decodingInfo() failed.` log, with the JSON decodingConfig next to it. 

So I started testing support for each one of the values provided in the above decodingConfig to see if one of them is not supported by the platform and is resulting in the above error which then causes the 6001. 
It turns out the video, and the audio codecs in the above config all work, and so does the Playready DRM.

However, I noticed something weird. As soon as I remove the robustness from the equation, The `MediaCapabilities.decodingInfo` resolves instead of throwing an error. 

![MediaCapabilities.decodingInfo Test](https://i.imgur.com/JFYJe0p.png "MediaCapabilities.decodingInfo")

Looking at the [Microsoft Security levels](https://learn.microsoft.com/en-us/playready/overview/security-level), and [Joey's Comment](https://github.com/shaka-project/shaka-player/issues/818#issuecomment-304105591) I've even tried passing different values of robustness such as `1000, 2000, 3000, SL1000, SL2000, SL3000`, but no luck. 

The problem I have is, as [the docs ](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.AdvancedDrmConfiguration) describe, if you don't set any value for robustness, Shaka defaults the robustness settings to an empty string. 

Which apparently, isn't good enough here. 

**Describe the solution you'd like**
Simply targeting a specific Panasonic platform in the Shaka codebase would be hard and probably not ideal. But I can do that easily in my own codebase. 

I was wondering if we could add a new param to the  `player.configure()` and use that to modify the code such that, it allows us to remove the robustness from the equation altogether instead of defaulting it to an empty string for the scenario such as described above. 

**Additional context**
I can confirm that If I remove the robustness from the equation altogether, the playback works fine for me. But any other value I provide breaks the playback with a 6001 error.

**Comment by joeyparrish** [comment]
I think the root cause is that Panasonic doesn't implement MediaCapabilities correctly, and either doesn't support the robustness field or has some bug in their implementation of it.

[But according to the MediaCapabilities spec](https://www.w3.org/TR/media-capabilities/#dom-keysystemtrackconfiguration-robustness), robustness is an optional parameter that defaults to `""`.  So removing it from the dictionary when it's blank should be safe on all platforms.

@subhanahmed047, would you be willing to send a PR for that?

**Comment by joeyparrish** [comment]
Also, I should clarify that we don't have a Panasonic TV in our lab, and therefore don't and can't do any testing on Panasonic.  That makes it a community-supported platform, so it's up to the community to supply and test PRs for the platform.

Thanks!

**Comment by subhanahmed047** [comment]
Thanks, @joeyparrish, I'll create a PR for this.
