### ISSUE TITLE
Question about HLS playback error( failed fetch and append: code=3018)

### ISSUE THREAD

**Issue by dnxodl1001** [shaka-project/shaka-player#4661]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.1

**Please ask your question**

Hello this is Steve Lee.

I want to play hls video using shaka player. 

However, the following error occurs.

The m3u8 file is also loading normally, but it is not playing and there is an error. 

I would appreciate it if you could reply to this error.

Thank you.

This is my script code.
error.code = 3018
error.message = Shaka Error MEDIA.TRANSMUXING_FAILED ()

![image](https://user-images.githubusercontent.com/117717284/200513875-9fa2ee75-3f6f-418c-ba96-53683c312a26.png)

![image](https://user-images.githubusercontent.com/117717284/200509532-786ae3c3-633b-4fb3-87e5-896449465ec6.png)

And this is my manifest file.

preOutput.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=1328282,AVERAGE-BANDWIDTH=1260984,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=854x480,FRAME-RATE=30.000
output.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2436354,AVERAGE-BANDWIDTH=2286336,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=30.000
output.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5810328,AVERAGE-BANDWIDTH=5360861,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=30.000
output.m3u8

ouput.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:18
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.416667,
output0.ts
#EXTINF:12.666667,
output1.ts
#EXTINF:10.416667,
output2.ts
#EXTINF:10.416667,
output3.ts
#EXTINF:12.208333,
output4.ts
#EXTINF:4.583333,
output5.ts
#EXTINF:10.625000,
output6.ts
#EXTINF:8.666667,
output7.ts
#EXTINF:11.458333,
output8.ts
#EXTINF:12.500000,
output9.ts
#EXTINF:8.750000,
output10.ts
#EXTINF:8.208333,
output11.ts
#EXTINF:16.416667,
output12.ts
#EXTINF:9.083333,
output13.ts
#EXTINF:9.625000,
output14.ts
#EXTINF:4.833333,
output15.ts
#EXTINF:15.291667,
output16.ts
#EXTINF:4.375000,
output17.ts
#EXTINF:11.666667,
output18.ts
#EXTINF:12.000000,
output19.ts
#EXTINF:7.458333,
output20.ts
#EXTINF:8.875000,
output21.ts
#EXTINF:11.958333,
output22.ts
#EXTINF:9.583333,
output23.ts
#EXTINF:8.708333,
output24.ts
#EXTINF:10.416667,
output25.ts
#EXTINF:9.166667,
output26.ts
#EXTINF:11.041667,
output27.ts
#EXTINF:10.833333,
output28.ts
#EXTINF:8.041667,
output29.ts
#EXTINF:12.250000,
output30.ts
#EXTINF:9.666667,
output31.ts
#EXTINF:11.958333,
output32.ts
#EXTINF:16.041667,
output33.ts
#EXTINF:5.166667,
output34.ts
#EXTINF:10.416667,
output35.ts
#EXTINF:5.375000,
output36.ts
#EXTINF:10.041667,
output37.ts
#EXTINF:9.625000,
output38.ts
#EXTINF:13.500000,
output39.ts
#EXTINF:6.125000,
output40.ts
#EXTINF:9.625000,
output41.ts
#EXTINF:10.750000,
output42.ts
#EXTINF:9.791667,
output43.ts
#EXTINF:11.166667,
output44.ts
#EXTINF:9.083333,
output45.ts
#EXTINF:10.500000,
output46.ts
#EXTINF:8.833333,
output47.ts
#EXTINF:9.916667,
output48.ts
#EXTINF:17.791667,
output49.ts
#EXTINF:10.416667,
output50.ts
#EXTINF:10.416667,
output51.ts
#EXTINF:10.416667,
output52.ts
#EXTINF:10.416667,
output53.ts
#EXTINF:10.416667,
output54.ts
#EXTINF:10.416667,
output55.ts
#EXTINF:9.500000,
output56.ts
#EXTINF:1.041667,
output57.ts
#EXTINF:10.416667,
output58.ts
#EXTINF:5.083333,
output59.ts
#EXT-X-ENDLIST

![image](https://user-images.githubusercontent.com/117717284/200511966-6835038f-3761-4ad7-8c18-2ddb3ac767ea.png)

**Comment by joeyparrish** [comment]
You can find information on your error here: https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3018

> TRANSMUXING_FAILED | 3018 | number | Mux.js did not invoke the callback signifying successful transmuxing.
> -- | -- | -- | --

The transmuxing component, [mux.js](https://github.com/videojs/mux.js/), failed for some reason.  You should check your content's validity, and/or report the issue to mux.js.  Thanks!
