### ISSUE TITLE
#EXT-X-PREFETCH is supported by shaka-player for LL-HLS?

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4670]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v4.2.3

**Please ask your question**
I am trying to setup a stream with LL-HLS by using FFmpeg
https://ffmpeg.org/ffmpeg-formats.html#dash-2

In FFmpeg documentation
> lhls lhls

`
Enable Low-latency HLS(LHLS). Adds #EXT-X-PREFETCH tag with the current segment’s URI. hls.js player folks are trying to standardize an open LHLS spec. The draft spec is available at https://github.com/video-dev/hlsjs-rfcs/blob/lhls-spec/proposals/0001-lhls.md This option tries to comply with the above open spec. It enables streaming and hls_playlist options automatically. This is an experimental feature.
`
> Note: This is not Apple’s version of LHLS. See https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis

> ldash ldash

`
Enable Low-latency Dash by constraining the presence and values of some elements.
`

I am trying to create an LL-HLS live stream but the shaka-player doesn't give me a warning of the LL-HLS stream has been configured when I don't set streaming.lowLatencyMode to true

If I try to test another URL having LL-HLS by third party: https://stream.mux.com/v69RSHhFelSm4701snP22dYz2jICy4E4FUyk02rW4gxRM.m3u8
It works.

can you please help me!

**Comment by joeyparrish** [comment]
The community spec for low-latency HLS you referenced is from 2019, and I believe it predated Apple's version.  We implemented Apple's version in Shaka Player, and likely don't recognize tags not in the official spec.

Does this answer your question?

**Comment by hiren3897** [comment]
Yes thanks for the information :)
