### ISSUE TITLE
Is it possible to implement manual quality selection in ios safari? 

### ISSUE THREAD

**Issue by Enflow-io** [shaka-project/shaka-player#4684]
I have prepared m3u8 files: 

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1047200,RESOLUTION=640x360,CODECS="avc1.4d401e,mp4a.40.2"
0.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=1788600,RESOLUTION=842x474,CODECS="avc1.4d401f,mp4a.40.2"
1.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=3436400,RESOLUTION=1280x720,CODECS="avc1.4d401f,mp4a.40.2"
2.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=6096200,RESOLUTION=1920x1080,CODECS="avc1.4d4028,mp4a.40.2"
3.m3u8
```

But in Safari quality switcher does not show any options. Is it possible to show options?

**Comment by theodab** [comment]
All playback on iOS Safari happens through Apple's native player, because Apple doesn't implement the MediaSource API on iOS Safari. And Apple's native player does not surface any list of resolutions or video tracks to us, so sadly we cannot provide resolution options on iOS.
