### ISSUE TITLE
How to play/stop videos if HLS Live Streaming?

### ISSUE THREAD

**Issue by dnxodl1001** [shaka-project/shaka-player#4689]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.1.2

**Please ask your question**
Hello this is Steve.

Currently, I'm trying to play a video for HLS LIVE Streaming.

However, in the case of HLS VIDEO, it works normally when the video is stopped, but in the case of HLS LIVE Streaming, it is confirmed that the video is stopped for 10 minutes and played after 10 minutes.

Even if it's HLS LIVE Streaming, I want the video to be played from the time it stops when it stops playing, so I'd really appreciate it if you could tell me what to do.

Thank you.

**Comment by joeyparrish** [comment]
What you're probably running into is something called the availability window.  A live stream doesn't necessarily leave all segments on the server forever.  It usually has a rolling window of some number of segments.  Only the most recent `N` segments are available.  The length of those `N` segments is the size of the availability window.

If you pause a live stream for hours, but the availability window is only 10 minutes, then when unpause, the content you were in the middle of is no longer available.  There's no way for a player to fetch segments that have been deleted from the server.  So the player is forced to seek to an available time instead.

Does this help?
