### ISSUE TITLE
Black screen when play AES-128 HLS Live Streaming

### ISSUE THREAD

**Issue by JonasBetter** [shaka-project/shaka-player#4700]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yep.

**What version of Shaka Player are you using?**
V4.3.0

**Can you reproduce the issue with our latest release version?**
Yep.

**Can you reproduce the issue with the latest code from `main`?**
Yep.

**Are you using the demo app or your own custom app?**
Own custom app, but just play simple AES-128 m3u8

**What browser and OS are you using?**
Android 6.0.1
Chrome 44.0.2403.133

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
My custom config:
streaming: {
      rebufferingGoal: 0,
      bufferingGoal: 5
}

**What did you do?**

Play a live stream with AES-128 m3u8, which show black screen in Chrome 44.0.2403.133、Android 6.0.1.
(But the m3u8/ts request successfuly that it return http_code 200 in network devtools)

**What did you expect to happen?**
Can be played normally on Android6 Chrome44.xx 

**What actually happened?**
It will black screen.
I have been debugging for a long time, but I have not been able to solve it for the time being, please if you have time, help me to see it, loyal thanks.

**Comment by avelad** [comment]
@JonasBetter can you share your stream to test it? Thanks!
