### ISSUE TITLE
In the case of HLS LIVE, the time is not displayed normally on LIVE, so I want to know what to do.

### ISSUE THREAD

**Issue by dnxodl1001** [shaka-project/shaka-player#4709]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.21.

**Please ask your question**
In the case of HLS LIVE, the time is not normally displayed in LIVE, and the time is displayed in a very large number as shown below.

If I call m3u8 with player.load while the video is playing, player.isLive() returns true normally,

but player.isLive() returns false and sets the time value of the live text when I call updateTime_() from presentation_time.js.

I would appreciate it if you could answer me in this regard.

![image](https://user-images.githubusercontent.com/117717284/201787126-a800deec-0b50-436b-8cee-28c11b5d9f2e.png)

**Comment by joeyparrish** [comment]
If you are not using the Shaka Player UI, this is expected.  The native browser controls for video elements are inappropriate for live streams.  You can either create your own UI or choose to use Shaka Player's optional UI.  See these tutorials for details:

 - https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html
 - https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html

Does this help?

**Comment by joeyparrish** [comment]
Sorry, there are no events emitted for EXT-X-DISCONTINUITY.  If you'd like to add one, feel free to file a feature request to discuss and/or a PR.  Thanks!
