### ISSUE TITLE
Shaka + FairPlay + Microsoft Azure + Browser Reload

### ISSUE THREAD

**Issue by boredom2** [shaka-project/shaka-player#4710]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.2.+ and 4.3.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
i was not able to configure FairPlay DRM in the app, so I could not say.

**What browser and OS are you using?**
latest macOS, latest Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
see below

**What did you do?**
see below

**What did you expect to happen?**
Safari would play the Video, protected by FairPlay

**What actually happened?**
Safari plays the Video exactly one time. After Reload, it immediately fails.

Hi there,
I had a very long talk with Microsoft Azure and their Media Services to finally make FairPlay (provided by them) working with Shaka in Safari. We came very far, but some last step is missing, which nobody could figure out.
Actually, the FairPlay protected Video is working in Shaka, but only one time. After reloading the Page, it fails immediatley without any Error, I could investigate further. Waiting a few minutes helps, it works again then.

We added a very simple Setup for testing - it includes everything needed and the hardcoded Tokens are valid for 24 Hours.
You can find the Shaka Setup here: https://lab-dev-cbr.nexx.cloud/play/drm.html 
Azure Media Services obviously needed various Changes on request and response Filters, but this works.
Playing the Video for a short time and then press F5 or reload the Page though shows immedaitely the Safari Error Image on the Video.

Microsoft also added a "Vanilla JS" Version with FairPlay here (same Assets, same Tokens, all identical);
http://lab-dev-cbr.nexx.cloud/play/drm-azure.html (this is intenitonally not https!)
As this Example works, also after a Reload, we decided, that this must be some Shaka-specific Issue, that we cannot solve without you.

Do you have any Idea, what we can do in order to fix this?

Thank you,
Christoph

**Comment by multiplexer2** [comment]
com.apple.fps has bugs preventing it from working with native playback. If you switch to non-native (MSE) I think your setup should work on Mac Safari.

On iOS native you should try to configure the player with:
- shaka.polyfill.PatchedMediaKeysApple.install();
- com.apple.fps.1_0 with an initDataTransform

**Comment by boredom2** [comment]
Thanks for that - I can confirm already, it indeed works flawlessly on macOS.
For iOS, I need a little more Time testing.
Great hint, thanks!
