### ISSUE TITLE
Unrecognized caption language codes

### ISSUE THREAD

**Issue by FireMasterK** [shaka-project/shaka-player#4713]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not checked

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Brave 1.45.123 Chromium: 107.0.5304.110

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
N/A, I used the player object to add them

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default / nothing changed

**What did you do?**
```
document.querySelector("video").ui.getControls().getPlayer().addTextTrackAsync(
                        "REDACTED", // I think you can put anything here
                        "yue-HK",
                        "CAPTIONS",
                        "application/ttml+xml",
                    );
```

A few unrecognized language codes include: `yue-HK`, `iw`, and `mn`.

**What did you expect to happen?**
To see the proper language code.

`Intl.DisplayNames` can display the correct names for these.

**What actually happened?**
![image](https://user-images.githubusercontent.com/20838718/202174444-adb68d35-4f54-4479-8b55-9882c869d1e7.png)

**Comment by avelad** [comment]
Implemented in https://github.com/shaka-project/shaka-player/commit/35cb193c76a01b0bdea862b423cfc6721f42529a
