### ISSUE TITLE
Widevine(CBCS) Encrypted Dash Stream not working on 2020 & 2021 Samsung(Tizen) TVs

### ISSUE THREAD

**Issue by jparekh-tivo** [shaka-project/shaka-player#4714]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0 & 4.3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
NA

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
2019 TV details: UA58RU7100KXXL, Tizen 5.0 and Browser Version: 2.3.0.0423190
2020 TV details: UT5310, Tizen 5.5 and Browser Version: 3.1.11260

**What are the manifest and license server URIs?**
Manifest url: 'https://storage.googleapis.com/wvmedia/cbcs/h264/tears/tears_aes_cbcs_uhd.mpd',
DrmServers url: 'https://proxy.uat.widevine.com/proxy?provider=widevine_test'

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

None

**What did you do?**
1) Add custom content on shaka demo app with above manifest and drm server URL
2) Try to play it on above mentioned Samsung TV's browser

**What did you expect to happen?**
Playback of encrypted content should happen (similar to 2019 and 2022 Samsung TV models)

**What actually happened?**
Content plays for initial ~9-10 secs(as it is unencrypted) and post that there is no error from player and playback is stuck

**Comment by ashishTivo** [comment]
any update on this issue?

**Comment by joeyparrish** [comment]
Do those devices actually support CBCS encryption?  I know older Widevine CDMs did not.

**Comment by avelad** [comment]
Bitmovin has done an analysis about this: https://bitmovin.com/analysis-drm-ciphers-samsung-tizen-tvs/

It seems that it is only supported in 2022+

**Comment by jparekh-tivo** [comment]
Thanks @avelad for the info and updates on this ticket. We will continue to debug further on various streams to conclude on this further but the test results are inline with what you have shared here about device capability.

**Comment by avelad** [comment]
@jparekh-tivo , can this issue be closed with the above information?

**Comment by jparekh-tivo** [comment]
Sure @avelad. Closing based on above platform capabilities
