### ISSUE TITLE
How to use a track thumbnail (sprite.vtt)

### ISSUE THREAD

**Issue by wearrrrr** [shaka-project/shaka-player#4719]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes I have

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest (4.3.0)

**Please ask your question**
I am wondering how I would go about using a caption file that I have (sprite.vtt) in order to display an image on the timeline as the user scrubs it, I have tried running `addThumbnailsTrack(URL)`, which returns a fulfilled promise, then running `player.getImageTracks()` returns the correct information about said track, with `active: false` being set, manually setting it to true did nothing, and `player.getThumbnails(0, 0)` (presumably the correct statement but honestly I have no idea) returns `Promise {<fulfilled>: null}`

So I am not 100% sure where to go from here, because the track seems to load but not display. I am calling sprite.vtt from a remote url but im not quite sure why that would be an issue, because it uses a relative path of 
```1
00:00:00.000 --> 00:00:10.000
sprite-0.jpg#xywh=0,0,178,100

**Comment by avelad** [comment]
The thumbanils are not yet supported in the UI, see https://github.com/shaka-project/shaka-player/issues/3371

The method getThumbnails returns the raw info in a determined time, but it's responsibility of the developer transforms the data and put in the DOM to saw the thumbnails.

This answer your question?
