### ISSUE TITLE
Way to conditionally hide audio language overflow menu button if there's only one language

### ISSUE THREAD

**Issue by FireMasterK** [shaka-project/shaka-player#4720]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
Yes, when there is only one available audio language, it becomes pointless to show the language option in the overflow menu, since you can't switch it.

**Describe the solution you'd like**
A configuration option or otherwise to hide the audio language option from the overflow menu if there is only one option.

**Describe alternatives you've considered**
Calling the configure method again after loading the manifest, and checking for the audio track count.

**Comment by joeyparrish** [comment]
I think it would be reasonable to hide the menu by default if there is only one item.

**Comment by joeyparrish** [comment]
@FireMasterK, please feel free to send a PR!
