### ISSUE TITLE
Minimum Node version upgrade released as a patch

### ISSUE THREAD

**Issue by alexandercerutti** [shaka-project/shaka-player#4721]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

n/a

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

n/a

**What version of Shaka Player are you using?**

3.3.13

**Please ask your question**

Hey there, we recently upgraded from v3.3.4 to v3.3.13 and we found out that, starting from [this commit](https://github.com/shaka-project/shaka-player/commit/5a44a58b688d9bb338f8d1cf8f03fc08a99fbaf6), Shaka seems to require at least Node v14.

Our project uses Node v12 and `yarn`, which validates `engines.node`. If `node` version does not match, it prevents some dependencies from getting installed. This actually forces us to upgrade to Node v14 (not a bad thing, actually, but it messes up our plans and requirements), hence this seems to be a breaking change that got released as a patch.

```
$ yarn install
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error shaka-player@3.3.13: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.7"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

My first thought was that this property got mistaken as a "project-only" property, just for maintainers.

Is there a specific reason this have been changed and released as a patch?
Thank you very much!

**Comment by joeyparrish** [comment]
Since node is merely a dev dependency, the node version doesn't affect the backward compatibility or API of the library itself.  Therefore it wasn't considered a "breaking" change at the time.

I'm honestly not sure from the commit history why the minimum node version was changed at the same time.  There should have at least been a mention in the commit or the PR, but there wasn't.  So perhaps it was a mistake.

If you revert the minimum node version to 12, can we still npm install all of Shaka Player's dev deps?

**Comment by alexandercerutti** [comment]
Hey @joeyparrish, thanks for your reply. I'm actually not very sure. I mean, I'm experiencing some "stucking" issues with installing `eme-encryption-scheme-polyfill` on both Mac M1 and Mac Intel and I'm not understanding the reason. Could you try too perhaps? Maybe you are luckier than me.

<img width="968" alt="immagine" src="https://user-images.githubusercontent.com/5442545/202668348-f5ef075a-460c-4f86-b6ea-c31b5381a3a1.png">

**Comment by alexandercerutti** [comment]
Hey @joeyparrish, I've asked a colleague of mine to do the same test and these are the results:

- `npm install` without deleting `package-lock.json` -> OK
- `npm install` with deleting `package-lock.json` -> OK
- `yarn install` -> KO.

`yarn` found that `jsdoc` requires `klaw`, which requires `node >= 14`. So perhaps this might be the reason...

**Comment by joeyparrish** [comment]
Well, since nodejs is a dev dependency, and not a runtime dependency, it is not a breaking change to update it IMO.  It was done 4 months ago, and reverting it doesn't work.  So I think we'll have to live with it and update the docs to match.

Sorry for the inconvenience!
