### ISSUE TITLE
CHUNK_DEMUXER_ERROR_APPEND_FAILED: video frame with PTS 1000us has negative DTS -39000us when cast with chromecast

### ISSUE THREAD

**Issue by HAYATO-Kz** [shaka-project/shaka-player#4722]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.1.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Yes ( Basic Shaka player from Tutorial in Shaka document )

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome, MacOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Any .m3u8 playlist (e. g. https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**
 
Click Cast video to Chromecast immediately after video start playing

**What did you expect to happen?**
Video start playing on TV without any problem

**What actually happened?**

Player error with error code 3016 and error message is "CHUNK_DEMUXER_ERROR_APPEND_FAILED: video frame with PTS 1000us has negative DTS -39000us after applying timestampOffset, handling any discontinuity, and filtering against append window"

**Comment by avelad** [comment]
Can you test with v4.3.3? Thanks!
