### ISSUE TITLE
Init Data always uses first key ID in DASH manifest (Widevine)

### ISSUE THREAD

**Issue by nkam12** [shaka-project/shaka-player#4729]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.0

**Please ask your question**
I'm having an issue with how Shaka player is parsing DASH manifests for Widevine-encrypted xHE-AAC content on macOS Google Chrome. I have a manifest that contains four key IDs, corresponding to different qualities of the same content. I'm seeing the Shaka player successfully fetch the manifest, first few audio segments for two different qualities, DRM license, and DRM certificate, successfully buffer the first ~25 seconds of content, and then it just hangs with no meaningful errors. Looking at the media tab, there is a decode error happening:

![image](https://user-images.githubusercontent.com/70608382/202745848-92bd4548-0f49-4c55-acc2-92e23afd7716.png)

I stepped through the unminified code in a debugger and found that Shaka is correctly creating four different variants for the stream, one for each quality/keyID, but the init data of each variant is using the same first key ID from the manifest. Shaka tries to buffer two different qualities and does so successfully, but doesn't seem to be able to decrypt these (likely because the init data is using the wrong key ID for these qualities). 

Looking at the dash/content_protection.js code, I see that this is a purposeful decision: https://github.com/shaka-project/shaka-player/blob/main/lib/dash/content_protection.js#L98

According to the comment, "If we have a default key id, apply it to every initData." Is there a reason for this decision? My understanding is that as per the DASH-IF spec, multiple default key IDs in a single manifest should be supported, and we are providing four different default_KID's in the manifest.

**Comment by joeyparrish** [comment]
I dug through the history a bit, and this code originated here: https://github.com/shaka-project/shaka-player/commit/5707e1603871e6ec8528c2f336ec1ac62d4fb593#diff-3374bcf6cadf40d4db3067eed37d5906bcb62c230ab5526b318a042f0fd327feR176

So we've been doing that since February 2017.  This change was made to close issue #580.

Could you please provide the text of your manifest to compare to the history?  For most issues, we need a manifest URL with actual content, but I think this issue is just a matter of manifest interpretation.  I'd like to compare your manifest structure to the code and the DASH spec to determine if it's the player or packager/encoder that's mistaken.  Thanks!

**Comment by nkam12** [comment]
Got it, thanks for the quick response on this! Just sent the email with the manifest attached to shaka-player-issues@google.com

Please let me know if there's anything else you need for the debugging

**Comment by nkam12** [comment]
Hi Joey, just wondering if there's any update on this issue?

**Comment by joeyparrish** [comment]
Sorry, haven't worked on this yet.  I just tagged it as a bug and gave it a priority.  We will get to it when we can.

**Comment by avelad** [comment]
@nkam12 Can you send your stream to shaka-player-maintainers@googlegroups.com ? In order to work on this it is necessary to have a stream to test with. Thanks!
