### ISSUE TITLE
Safari - DASH with multiple audio tracks doesn't play

### ISSUE THREAD

**Issue by FireMasterK** [shaka-project/shaka-player#4730]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not sure

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
iOS doesn't support MSE, so not sure
iPad OS 15
Safari on OSX 15.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=ALL_CONTENT;panelData=drm:CLEAR,DASH,MP4;build=compiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default

**What did you do?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=ALL_CONTENT;panelData=drm:CLEAR,DASH,MP4;build=compiled

On my custom application, if I don't call `selectAudioLanguage` it works fine.

**What did you expect to happen?**

The video should play.

**What actually happened?**

The video never plays, and a lot of fetch calls are made.

**Comment by avelad** [comment]
I have tested with Safari 17 and it works correctly. The problem with Angel One is that it chooses WebM by default which does not work correctly, if you choose the MP4 version it works correctly.
