### ISSUE TITLE
Query String in `BaseURL` not preserved when combined with `SegmentList` items

### ISSUE THREAD

**Issue by FireMasterK** [shaka-project/shaka-player#4731]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not sure

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Arch, with Brave

**What are the manifest and license server URIs?**
Run: `curl -s -o - "https://pipedapi.kavin.rocks/streams/FG8nTQGJT-Q" | jq -r .dash`

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default

**What did you do?**
Just play a dash manifest with an existing query string in `BaseURL`, with a pre-existing `SegmentList`.

**What did you expect to happen?**

The query string from `BaseURL` to be used.

**What actually happened?**

The paths are being combined, with the query string being completely removed.

**Comment by avelad** [comment]
I've been looking and the test stream you have does not have any queryparam in baseURL

**Comment by FireMasterK** [comment]
Hi, my apologies, there was an error on my part. The manifest should now contain a query string.

**Comment by avelad** [comment]
It seems that now the file is not a valid xml, can you check it? Thanks!

**Comment by FireMasterK** [comment]
@shaka-bot reopen

I've managed to fix the XML issues on my end, hopefully it works this time, thanks for your patience! :)

**Comment by avelad** [comment]
@FireMasterK The error seems to be at https://github.com/shaka-project/shaka-player/blob/main/third_party/closure-uri/uri.js#L214 I haven't found a solution yet.

**Comment by avelad** [comment]
And it seems that this is how Google's closure library works, see https://github.com/google/closure-library/blob/master/closure/goog/uri/uri.js#L251

**Comment by joeyparrish** [comment]
`curl -s -o - "https://pipedapi.kavin.rocks/streams/FG8nTQGJT-Q" | jq -r .dash` gives me null at the moment.

But I'm not sure your expectations are in line with how URLs usually behave.  For example, here's the standard URL resolution in the browser:

```js
base = new URL('https://foo/bar/?baz=blah')
(new URL('relative1/relative2', base)).toString()
// returns 'https://foo/bar/relative1/relative2'
```

URL parameters are not passed to relative URLs.  If you load a web page at `/foo/bar/?baz=blah`, then load an image at relative URL `folder/img.png`, you get `/foo/bar/folder/img.png`, not `/foo/bar/folder/img.png?baz=blah`.

So if I understood the request correctly, I believe the thing you're asking for goes against standards for URLs.
