### ISSUE TITLE
Add Support for setting safeMargin and keeping buffer when selectVariantsByLabel is called

### ISSUE THREAD

**Issue by lindsayrr** [shaka-project/shaka-player#4736]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Our player has the option for the user to select Noise Suppression Track, and we are using `selectVariantsByLabel` function to achieve this. We need an amount of time where we continue to play the original audio track after Noise Suppression Track is selected so that the user will have a seamless experience. Currently, selectVariantsByLabel doesn't support customizing `clearBuffers` and `safeMargin`, 
**Describe the solution you'd like**

we would like to have a PR to change the function signature to pass `clearBuffers` and `safeMargin` to  `selectVariantsByLabel` function

**Describe alternatives you've considered**

**Additional context**

**Comment by avelad** [comment]
Resolved in https://github.com/shaka-project/shaka-player/commit/c7246250323c3c97a2d30f9f66880e914e5c2344
