### ISSUE TITLE
Can't build with latest code because of Java error

### ISSUE THREAD

**Issue by caridley** [shaka-project/shaka-player#4737]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
NA main branch commit c3ff8e5e5f6ad5867ed0650e153627dafcb1bcf7

**Can you reproduce the issue with our latest release version?**

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
NA

**If custom app, can you reproduce the issue using our demo app?**
NA

**What browser and OS are you using?**
NA

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

NA

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

NA

**What did you do?**

Tried to build with the command python build/all.py

**What did you expect to happen?**

**What actually happened?**
Build failed with this error message

P2134253@CHTRMACP4H2J3 shaka-player % python build/all.py  
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Generating Closure dependencies...
[INFO] Linting JavaScript...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Linting CSS...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Linting HTML...
[WARNING] No changes detected, skipping. Use --force to override.
[INFO] Checking that the build files are complete...
[INFO] Checking for common misspellings...
[INFO] Checking correct usage of eslint-disable...
[INFO] Checking the tests for type errors...
[WARNING] No changes detected, skipping. Use --force to override.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
[ERROR] Build failed
P2134253@CHTRMACP4H2J3 shaka-player % java -version
**java version "1.8.0_351"**
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)
P2134253@CHTRMACP4H2J3 shaka-player % node --version
v16.13.1
P2134253@CHTRMACP4H2J3 shaka-player % python --version
Python 3.10.5

**I was able to work around the problem by reverting changes to the closure versions in package.json** 

```
-    "google-closure-compiler-java": "^20220301.0.0",
-    "google-closure-deps": "https://gitpkg.now.sh/google/closure-library/closure-deps?d7736da6",
-    "google-closure-library": "^20220301.0.0",
+    "google-closure-compiler-java": "^20221102.0.0",
+    "google-closure-deps": "^20221102.0.0",
+    "google-closure-library": "^20221102.0.0",

```
**from this commit**

fix(hls): Fix type error in lazy-loading (#4687)

There was a potential type error in an edge case in lib/player.js. It 
would have been caught by the latest compiler, so this upgrades the 
compiler and fixes another type error in one other place, as well.
Commit:
28b73b921d1dbdc6d7e016aa8e0a000e62318ed3 [28b73b92]
Parents:
7af357cf7cd211791c25c69b46745c896fb1c827
Author:
Joey Parrish <joeyparrish@users.noreply.github.com>
Date:
November 11, 2022 at 8:07:58 AM MST
Committer:
GitHub <noreply@github.com>

**This problem was observed on an M1 macbook running MacOS version 12.6**

I am running the latest available Java version for MacOS

**Comment by avelad** [comment]
Please upgrade to Java 11. Thanks!

**Comment by caridley** [comment]
I am using the latest available version of java for Mac OS
<img width="601" alt="Screen Shot 2022-11-21 at 12 57 20 PM" src="https://user-images.githubusercontent.com/8808113/203147060-ef704dea-0855-4667-b1e2-7b01951ab249.png">

**Comment by caridley** [comment]
Ok.. didn't realize that we can no longer use use JRE installed by the OS. Thanks

**Comment by caridley** [comment]
@avelad  We should update the pre-requisites on this page https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html
