### ISSUE TITLE
Processing of SCTE-35 Ad Markers

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#4738]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.0

**Please ask your question**
Hi! In case of SSAI in a HLS Stream consider from AWS Elemental Live https://docs.aws.amazon.com/medialive/latest/ug/scte-35-message-processing.html
Is Shaka Player's Ad Manager able to process SCTE-35 Ad Markers and send events?

As much as I checked the source code of Shaka's Ad Manager, there was no reference for it. However since it works with IMA ADs SDK, I read on google that their SDK supports it. However, I prefer not to use Google's SDK since it creates iFrames and is less customisable. Any idea which OS Library or parser can do this for us? Managing the events and parsing the Live HLS Ad Markers?

**Comment by debjits1** [comment]
@WINOFFRG  did you get any answer to this? I am looking for the same

**Comment by avelad** [comment]
see: https://github.com/shaka-project/shaka-player/issues/4853
