### ISSUE TITLE
0 duration segment handing - Warning '"S" element must have a duration:' - lib/dash/mpd_utils.js - line 157 onwards

### ISSUE THREAD

**Issue by i2iRobert** [shaka-project/shaka-player#4741]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.1

**Can you reproduce the issue with our latest release version?**
Yes - using https://shaka-player-demo.appspot.com/demo/#build=uncompiled

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 107.0.5304.107 - Windows 10 & macOS
Safari and HLS streams not affected

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

URI sent to email address as requested

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Configuration sent to email address as requested

**What did you do?**

Given the above mpd via email, from 3min 20sec issue is visible depending on buffering.

Player stops playing video.

**What did you expect to happen?**
Player to continue playing video.

**What actually happened?**

It appears that our video (as linked to above in the email as requested) has a 0 duration segment as provided by our video server.

The code as below is only expecting greater than 0 durations, and we can see a divide by 0 being avoided by no longer building the "timeline" array.

Warning is logged:
'"S" element must have a duration:' - 

Which can be found here:
lib/dash/mpd_utils.js - line 157 onwards

**Comment by avelad** [comment]
Can you check again against the main branch? Thanks!
