### ISSUE TITLE
Hls video/mp2t live stream won't open

### ISSUE THREAD

**Issue by broscr** [shaka-project/shaka-player#4746]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.0

**Please ask your question**

I'm trying to play a url like http://abc.com/abc/abc/2 inside an m3u file. I actually solved the cors problem by examining the documents and the demo, but I could not play the live broadcast. I will be glad if you can help me where am I going wrong.

```
import { useEffect } from "react";
import shaka from "shaka-player";
import "mux.js/dist/mux";

const Player = () => {
  useEffect(() => {
    console.log("UseEffect");

    // window.muxjs = muxjs;

    const manifestUri = "http://xxxxxx/xxxxx/xxxx/3";

    function initApp() {
      // Install built-in polyfills to patch browser incompatibilities.
      shaka.polyfill.installAll();

      // Check to see if the browser supports the basic APIs Shaka needs.
      if (shaka.Player.isBrowserSupported()) {
        // Everything looks good!
        initPlayer();
      } else {
        // This browser does not have the minimum set of APIs we need.
        console.error("Browser not supported!");
      }
    }

    async function initPlayer() {
      // Create a Player instance.
      const video = document.getElementById("video");
      const player = new shaka.Player(video);

      player
        .getNetworkingEngine()
        .registerRequestFilter(function (type, request) {
          request.method = "GET";
          console.log(type, request);
        });

      // Attach player to the window to make it easy to access in the JS console.
      window.player = player;

      // Listen for error events.
      player.addEventListener("error", onErrorEvent);

      // Try to load a manifest.
      // This is an asynchronous process.
      try {
        player.load(manifestUri);
        // This runs if the asynchronous load is successful.
        console.log("The video has now been loaded!");
      } catch (e) {
        // onError is executed if the asynchronous load fails.
        onError(e);
      }
    }

    function onErrorEvent(event) {
      // Extract the shaka.util.Error object from the event.
      onError(event.detail);
    }

    function onError(error) {
      // Log the error.
      console.error("Error code", error.code, "object", error);
    }
    initApp();
  }, []);

  return (
    <div>
      <video controls id="video" autoPlay />
    </div>
  );
};

export default Player;
```
<a href="https://ibb.co/tX44rTC"><img src="https://i.ibb.co/JQKKJwk/Ekran-g-r-nt-s-2022-11-22-212719.png" alt="Ekran-g-r-nt-s-2022-11-22-212719" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/zJ1G95S/Ekran-g-r-nt-s-2022-11-22-230247.png" alt="Ekran-g-r-nt-s-2022-11-22-230247" border="0"></a>
<a href="https://ibb.co/K6r4Q5T"><img src="https://i.ibb.co/wyzGbd5/Ekran-g-r-nt-s-2022-11-22-224728.png" alt="Ekran-g-r-nt-s-2022-11-22-224728" border="0"></a>
<a href="https://ibb.co/chzyBH4"><img src="https://i.ibb.co/b5p60Zc/Ekran-g-r-nt-s-2022-11-22-224920.png" alt="Ekran-g-r-nt-s-2022-11-22-224920" border="0"></a>

**Comment by WINOFFRG** [comment]
Are you sure that codec is supported by your browser?
Try this in console
```js
const v = document.createElement('video');
console.log(v.canPlayType('video/mp2t'));
```

If the output of above is empty string then your browser is not capable of playing that codec. In case it return a string `maybe` or `probaby` you need to make sure that your MANIFEST is supported by this player.

**Comment by broscr** [comment]
This format is not supported by the browser, but is it not possible to convert it to mp4 format with mux js?

**Comment by WINOFFRG** [comment]
There is nothing that can be done I suppose if your browser doesn't support the codec. Also mux.js is a library for analytics, It can't help you in converting the media into different format. Such tasks are usually done on the server side.

**Comment by broscr** [comment]
> There is nothing that can be done I suppose if your browser doesn't support the codec. Also mux.js is a library for analytics, It can't help you in converting the media into different format. Such tasks are usually done on the server side (pre-processing) like using ffmpeg.

Is it not possible to manipulate an array of type Uint8array?

**Comment by WINOFFRG** [comment]
I don't think that will be possible. However you can always refer SOF for this, as I don't have much idea of this.

**Comment by broscr** [comment]
There is no identifier in the broadcast file, it broadcasts directly. Returns mp2t format. It's an hls release, but it doesn't have a manifest file and it streams directly. Live tv link actually.

**Comment by joeyparrish** [comment]
Transmuxing only changes the container (TS to MP4) but not the codec inside (such as h264, etc).  If we convert TS to MP4, the browser still needs to support the codec, and the player can't change that.

If you're having trouble, I suspect it's because of a combination of two things:

1. For HLS, the player sometimes has to guess what the codec is (we default to h264+AAC)
2. Your content appears to have mpeg 2 audio according to your VLC screenshot

I'm making some assumptions here because you didn't give us enough information to work on this issue.  If these pointers are helpful, you may simply close this issue.  If not, please close this anyway and file a new one using the "bug" template, which will ask for details we will need to work on this issue for you.

Thanks!
