### ISSUE TITLE
missing/null Resolution in Demo Asset in Safari on iPad

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#4747]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Yes, Demo

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Safari v16.2 on iPad (9th Gen)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

Big Buck Bunny: the Dark Truths of a Video Dev Cartoon (HLS)
https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8;panel=ALL_CONTENT;build=uncompiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default

**What did you do?**
Play the demo asset on latest version

**What did you expect to happen?**
Resolutions were missing in resolution menu. Only one track was listed and that too with `nullp` value.

**What actually happened?**

After attaching my debugger, I found that the below statement just returns us 1 track 

https://github.com/shaka-project/shaka-player/blob/a61c08433dab654edd224b2dc930c6d257460ec9/ui/resolution_selection.js#L70

Here below is the track info:

`{"id":5,"active":true,"type":"variant","bandwidth":0,"language":"en","label":"stream_0","kind":"main","width":null,"height":null,"frameRate":null,"pixelAspectRatio":null,"hdr":null,"mimeType":null,"audioMimeType":null,"videoMimeType":null,"codecs":null,"audioCodec":null,"videoCodec":null,"primary":true,"roles":["main"],"forced":false,"audioRoles":["main"],"videoId":null,"audioId":null,"channelsCount":null,"audioSamplingRate":null,"spatialAudio":false,"tilesLayout":null,"audioBandwidth":null,"videoBandwidth":null,"originalVideoId":null,"originalAudioId":"0","originalTextId":null,"originalImageId":null}`

On parsing the above track we see that both `height` and `width` are `null`, Hence causing that one single track to be `nullp`.

![image](https://user-images.githubusercontent.com/61311751/203441969-abe974c5-baac-45b1-aac2-9a8a06a1e3ea.png)

**Comment by avelad** [comment]
On iOS/ipadOS, the preference is to use Safari's native HLS, but it does not return height/width information, so this information is not returned at this point. Thanks!
