### ISSUE TITLE
Add support to <dashif:Laurl>

### ISSUE THREAD

**Issue by bttop83** [shaka-project/shaka-player#4748]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3

**Please ask your question**
I trying to play clear key licensing server using dashif:laurl but shaka-player return 6012 error.
I know Dash-IF lastest security guidelines is `<dashif:laurl>`
https://dashif-documents.azurewebsites.net/Guidelines-Security/master/Guidelines-Security.html#CPS-mpd-drm-config

I wondering, is shaka-player sopport `<dashif:laurl>`? If it is, why I receive 6012 error?

tested `<ContentProtection>` Element like this
```xml
<ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b" value="ClearKey1.0">
        <cenc:pssh>AAAANHBzc2gBAAAAEHfv7MCyTQKs4zweUuL7SwAAAAEbdF33h/WzyyI+2iPFMZsxAAAAAA==</cenc:pssh>
        <dashif:Authzurl>https://some.com/authorize</dashif:Authzurl>
        <dashif:laurl>http://licenseserver.com/AcquireLicense</dashif:laurl>
</ContentProtection>
```
Thanks to read my question.

![2022-11-23 150110](https://user-images.githubusercontent.com/33062001/203485312-cf0e0497-c063-4ac4-a91c-8933ce95c91b.png)

**Comment by joeyparrish** [comment]
No, not yet, but it could be added.  We support the older MS PlayReady variant of that already `ms:laurl`, so there's no reason we couldn't support `dash:laurl` as well.

I'll convert this into a feature request.  PRs are welcome!

**Comment by avelad** [comment]
@bttop83 if you share a manifest(url), I can work in this feature. Thanks!
