### ISSUE TITLE
Font family mapping in UITextDisplayer

### ISSUE THREAD

**Issue by Robloche** [shaka-project/shaka-player#4749]
According to the specifications [tts:fontFamily](https://www.w3.org/TR/ttml1/#style-attribute-fontFamily) and [&#60;genericFamilyName&#62;](https://www.w3.org/TR/ttml1/#style-value-genericFamilyName), I understand that when the font family is a generic name, a mapping should be applied.

What I saw during one of my tests is that `tts:fontFamily="proportionalSansSerif"` is simply converted to `font-family: proportionalSansSerif;`, and since this font doesn't exist (at least to my knowledge), it produces the wrong display.

**Example:**
![image](https://user-images.githubusercontent.com/10497009/203513281-a21d391f-83b2-46c4-907f-d98a73192389.png)

Did I get it right?

**Comment by joeyparrish** [comment]
Sounds right to me.  Please feel free to send a PR.  Thanks!

**Comment by avelad** [comment]
See https://github.com/sandflow/imscJS/blob/master/src/main/js/html.js#L1394

**Comment by Robloche** [comment]
Thanks for the fix @avelad!
