### ISSUE TITLE
styling subtitle

### ISSUE THREAD

**Issue by mahesh-logituit** [shaka-project/shaka-player#4751]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.1.1

**Please ask your question**
I'am trying to set the styles for subtitles cues, using `video::cue{}` not able to set `width`, `padding`, `margin` and `bottom` values to the subtitles. What is the way to set `width`, `padding`, `margin` and `bottom` values to the subtitle cues.

**Comment by friday** [comment]
Cue styling is not for positioning/size: https://developer.mozilla.org/en-US/docs/Web/CSS/::cue#permitted_properties

For positioning/size you should do that in the source (VTT). Ex https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/size and https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/position

But it sounds like what you want to do is to either make a custom text displayer, or use Shaka's UITextDisplayer with custom styling and then style shaka-text-container yourself (see https://github.com/shaka-project/shaka-player/issues/4545#issuecomment-1267619657)

**Comment by joeyparrish** [comment]
@mahesh-logituit, does this answer your question?
