### ISSUE TITLE
audio Data is getting "undetermined"

### ISSUE THREAD

**Issue by sadhashivamp** [shaka-project/shaka-player#4753]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
    "shaka-player": "^4.2.2",
import "shaka-player/dist/controls.css";
const shaka = require("shaka-player/dist/shaka-player.ui.js");

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
i tried both

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

chrome
**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

    const manifestUri = "https://vodemedia-usea.streaming.media.azure.net/75ff8bc0-ebfc-46c0-b808-4ef74790f594/ForBiggerEscapes_New.ism/manifest(format=mpd-time-cmaf,encryption=cenc)";

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

import * as React from "react";
import './App.css'

import {
  Player as ShakaPlayer,
  ui as ShakaUI,
  polyfill as ShakaPolyfill
} from "shaka-player/dist/shaka-player.ui";

import {
  ForwardTenButton,
  RewindTenButton,
} from "shaka-player-ui-controls";

import "shaka-player/dist/controls.css";
const shaka = require("shaka-player/dist/shaka-player.ui.js");

class Shaka2 extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {};

    this.video = React.createRef();
    this.container = React.createRef();
    this.onErrorEvent = this.onErrorEvent.bind(this);
    this.onError = this.onError.bind(this);
  }

  onErrorEvent(event) {
    this.onError(event.detail);
  }

  onError(error) {
    console.error("Error code", error.code, "object", error);
  }

  componentDidMount() {
    const manifestUri = "https://vodemedia-usea.streaming.media.azure.net/75ff8bc0-ebfc-46c0-b808-4ef74790f594/ForBiggerEscapes_New.ism/manifest(format=mpd-time-cmaf,encryption=cenc)";
    const captionUrl = "https://vodemedia-usea.streaming.media.azure.net/bbf73c0d-256e-4ae9-af29-9d1446b4d44d/English 1.vtt";
    var licenseServer = '';
    const videoElement = this.video.current;
    const containerElement = this.container.current;

    console.log("videoElement", videoElement)
    const player = new shaka.Player(videoElement);
    console.log("player", player)
    const ui = new shaka.ui.Overlay(player, containerElement, videoElement);
    ui.getControls();

    player.getConfiguration()
    // var data = player.S.c
    // console.log(data)

    
    
    ShakaUI.Controls.registerElement("forward_10", new ForwardTenButton.Factory());
    ShakaUI.Controls.registerElement("rewind_10", new RewindTenButton.Factory());

    const config = {
      controlPanelElements: [
        'skip',
        'forward_10',
        'play_pause',
        'rewind_10',
        'time_and_duration',
        'spacer',
        'mute',
        'volume',
        'fullscreen',
        'overflow_menu',
      ],
      overflowMenuButtons: [
        'captions',
        'quality',
        'language',
        'picture_in_picture',
        'cast',
        'playback_rate',
      ],
    };
    
    
    ui.configure(config);
    ui.getControls().getLocalization().changeLocale(["el"]); // try to change menu language
    const controls = ui.getControls();
    
    const localization = controls.getLocalization();
    console.log("controls.getLocalization();", controls.getLocalization())

    player.configure({
      abr: {
        enabled: true
      }
    });

    let audioLang =  player.getAudioLanguages();
    let variantTracks =  player.getVariantTracks();

    console.log("audioLang............", audioLang)
    console.log("variantTracks............", variantTracks)

    
    // player.configure({
    //   drm: {
    //     servers: {
    //       'com.widevine.alpha': licenseServer,
    //     },
    //     advanced: {
    //       'com.widevine.alpha': {
    //         'videoRobustness': 'SW_SECURE_CRYPTO',
    //         'audioRobustness': 'SW_SECURE_CRYPTO'
    //       }
    //     }
    //   },
    //   preferredTextLanguage: 'en'
    // });

    // let tracks = player.audioTracks();
    // tracks.addEventListener('change', function () {
    //   for (let i = 0; i < tracks.length; i++) {
    //     let track = tracks[i];
    //     if (track.enabled) {
    //       console.log(track.label);
    //       return;
    //     }
    //   }
    // });

    var url = player.load(manifestUri)
    console.log("manifests", url)

    player.configure('streaming.alwaysStreamText', true)
    player.load(manifestUri).then(function () {
      player.addTextTrack(captionUrl);
      var tracks = player.getTextTracks();
      console.log('tracks_text', tracks)
      if (tracks) {
        for (let i = 0; i < tracks?.length; i++) {
          player.selectTextTrack(tracks[i]);
        }
      }
    });
    player.setTextTrackVisibility(true);

    // player.load(manifestUri).then(function () {
    //   let tracks = player.getAudioLanguages();
    //   tracks.addEventListener('change', function () {
    //     for (let i = 0; i < tracks.length; i++) {
    //       let track = tracks[i];
    //       if (track.enabled) {
    //         console.log(track.label);
    //         return;
    //       }
    //     }
    //   });
    // });

    // const tracks = videoElement.audioTracks;
    // // var new1 = player.selectVariantTrack();
    // console.log("data1", tracks)

    player.addEventListener("error", this.onErrorEvent);

    player.load(manifestUri).then(() => {
      console.log("The video has now been loaded!");
    }).catch(this.onError);

  }

  render() {
    return (
      <div style={{ width: '1040px', height: '600px', margin: 'auto' }} ref={this.container}>
        <video
          data-shaka-player
          width="100%"
          height="100%"
          ref={this.video}
          autoPlay
        />
      </div>

    );
  }
}

export default Shaka2;

**What did you expect to happen?**

**What actually happened?**

Here we can uploaded video with subtitles at azure portals, then we got final streaming urls 
so i used in my shaka player 
all data getting except audio tracks

**Comment by sadhashivamp** [comment]
pls can any one help me on this audioTracks issue

**Comment by WINOFFRG** [comment]
This isn't an issue actually. It all depends on the Manifest format. 

Check this manifest https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd If you observe carefully `AdaptationSet` tag in the manifest for `contentType="audio"` has an attribute `lang="es"` this attribute notifies the player the language of the audio. In your case, Azure Media Services generates the manifest on its own, and if you check your manifest it doesn't have such attributes.

This tool https://videojs.github.io/mpd-parser/? can help you parse a manifest and check its properties.

**Comment by joeyparrish** [comment]
@sadhashivamp, did this answer your question?  May we close the issue?
