### ISSUE TITLE
H264 MPEG-4 AVC (Part 10) Codec

### ISSUE THREAD

**Issue by broscr** [shaka-project/shaka-player#4754]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

There is a broadcast decoded with mpeg-4 avc codec, I cannot play it. [H264-MPEG-4 AVC (Part 10)](https://tr.wikipedia.org/wiki/H.264/MPEG-4_AVC)
[Question Link](https://github.com/shaka-project/shaka-player/issues/4746)
[Test Stream](http://38000.biz:3800/XDENEKUL/XSIFREPASS/2)

**Describe the solution you'd like**

Shaka player codecs I want this codec added.

**Describe alternatives you've considered**

I couldn't find an alternative.

**Additional context**

<img src="https://camo.githubusercontent.com/c669b2485c4e92a2f28f05f1678ee72459f3458ff51564b5b2051a9cedae14b8/68747470733a2f2f692e6962622e636f2f7a4a31473935532f456b72616e2d672d722d6e742d732d323032322d31312d32322d3233303234372e706e67" alt="Ekran-g-r-nt-s-2022-11-22-230247" border="0" data-canonical-src="https://i.ibb.co/zJ1G95S/Ekran-g-r-nt-s-2022-11-22-230247.png" style="max-width: 100%;">

**Comment by WINOFFRG** [comment]
Brining support of any codec cannot be done from Shaka's side, Its from the browser. For example: Chrome has ffmpeg binaries compiled with it and codec enabled.

**Comment by broscr** [comment]
So is there any way to play this file with shaka player?

**Comment by broscr** [comment]
> Brining support of any codec cannot be done from Shaka's side, Its from the browser. For example: Chrome has ffmpeg binaries compiled with it and codec enabled.


So is there any way to play this file with shaka player?

**Comment by joeyparrish** [comment]
Codec support is a browser issue.  We do not implement codecs in JavaScript.  They are always provided by the browser/device/platform, and we have no control over this at the level of the player.  Sorry!

You can file browser bugs here:

Chrome: https://crbug.com/
Firefox: https://bugzilla.mozilla.org/
Safari: https://bugs.webkit.org/

I hope that helps!

**Comment by joeyparrish** [comment]
Looking at this again, I think the audio codec might be the real problem.  Still a browser issue, but you might want to consider transcoding the content.
