### ISSUE TITLE
HLS subtitles lose role information

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#4759]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
own custom app

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Chrome, macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

n/a

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

n/a

**What did you do?**

Play HLS content that has both captions and subtitles, the captions having the EXT-MEDIA-TAG as follows:
```
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="sub1",LANGUAGE="sv",NAME="Swedish [SDH]",AUTOSELECT=YES,CHARACTERISTICS="public.accessibility.describes-music-and-sound",URI="sc-gaFESg/s2_index.m3u8"
```

**What did you expect to happen?**
The subtitle track parsed as having `roles: ["public.accessibility.describes-music-and-sound"]`

**What actually happened?**
There is no information in the shaka track object regarding what `roles` (or `kind`) this track has, so there is no way of distinguishing it as captions.

I have a fix locally that solves the problem, and could make a pull request. It would be good to have someone with more knowledge of `hls_parser.js` to take a look at it.

**Comment by joeyparrish** [comment]
Based on the PR, I think regression was introduced in v4.3.0 with lazy-loading changes.  This bug does not appear to affect any other release.
