### ISSUE TITLE
Shaka player not picking up lower quality / other variants when url of one variant does not respond

### ISSUE THREAD

**Issue by kiran-dcunha** [shaka-project/shaka-player#4764]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.2.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Did not check

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Mac M1 Pro 2021, Chrome 107.0.5304.110

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Originally happening on Smart TVs, but reproducible on Macs as well.

**What are the manifest and license server URIs?**

NA

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

`{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "parseInbandPsshEnabled": false
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
        "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
      },
      "sequenceMode": false
    },
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 10,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.5,
    "durationBackoff": 1,
    "forceTransmux": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2,
    "lowLatencyMode": false,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 1,
    "dispatchAllEmsgBoxes": false,
    "observeQualityChanges": false,
    "maxDisabledTime": 30,
    "parsePrftBox": false
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    },
    "advanced": {
      "minTotalBytes": 128000,
      "minBytes": 16000,
      "fastHalfLife": 2,
      "slowHalfLife": 5
    },
    "restrictToElementSize": false,
    "restrictToScreenSize": false,
    "ignoreDevicePixelRatio": false
  },
  "autoShowText": 3,
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
}`

**What did you do?**

Stop one mp4 chunk of one variant from responding. It is not blocked, but the server does not respond.
**NOTE**: Player works fine if the server is very slow and some part of variant gets downloaded. It switches to lower bitrate and tries to play it. 1003 error is seen in our production environment, and above is a simulation which may be what is occurring in production.

**What did you expect to happen?**
Shaka player should try playing a different variant (preferable lower?)

**What actually happened?**

Shaka player throws 1003 error without trying for another variant. 

![image](https://user-images.githubusercontent.com/102036812/204275661-e8742e86-8e37-4fe6-8436-6f19ec5230da.png)

![image](https://user-images.githubusercontent.com/102036812/204274291-101d062c-71a0-4463-9196-9627568b7245.png)

**Comment by friday** [comment]
There's more information about it here #4728

The case that's causing issues for me is segments that are in the manifest but files are missing, returning 404. This results in a `BAD_HTTP_STATUS` (1001) as demonstrated by that issue ^, but I also mentioned that I thought `TIMEOUT` (1003) should be covered by this.

Then I started making a PR, and the tests intentionally used `TIMEOUT` as the invalid event, which made me hesitate as I'm not sure there might be

**Comment by WINOFFRG** [comment]
I feel this is not an issue, Since the demo version is general and minimalistic, It doesn't handle such cases and allows us to manually handle that. You can add a listener for this event and add your custom logic, for example switching down to a lower resolution playback set!

**Comment by friday** [comment]
> I feel this is not an issue, Since the demo version is general and minimalistic, It doesn't handle such cases and allows us to manually handle that. You can add a listener for this event and add your custom logic, for example switching down to a lower resolution playback set!

The functionality being requested here already exists in Shaka. It's just the condition (one line of code) that's keeping it from being used here.
