### ISSUE TITLE
Live Widevine DRM -  Screen freeze, but audio and subtitles are working 

### ISSUE THREAD

**Issue by giladna** [shaka-project/shaka-player#4776]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.0

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `main`?**

Did not try

**Are you using the demo app or your own custom app?**

Both

**If custom app, can you reproduce the issue using our demo app?**

Yes

**What browser and OS are you using?**

Observed on Mac Chrome 107 and 108 and on Win 10 Chronw

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
sent in slack 
will send agiain to shaka-player-issues@google.com on demand as the token expires

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

`{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "servers": {
      "com.widevine.alpha": "https://udrmv3.kaltura.com/cenc/widevine/license?custom_data=eyJ1ZGlkIjoiNTExNTg2NDA2ODkyMDgyNiIsImZpbGVzIjoiIiwiY2Ffc3lzdGVtIjoiaHR0cHM6Ly8zMjAxLmZycDEub3R0LmthbHR1cmEuY29tL2FwaV92My9zZXJ2aWNlL2Fzc2V0RmlsZS9hY3Rpb24vZ2V0Q29udGV4dD9rcz1kako4TXpJd01YeUlfQ3NyNTdnalFKQUZoZFFPcGZfQWpRQ0hVWko5NEd6dkhnUXgxVUVrZ0Nod180Z2NWS3BTTVg2SnNDSHdCSmRyMU81eVB1TGJta0xJcC1rV0RqTnc5UEhsY1l0dkhzYzhLSmt4WUhnYmFyRmtoWEdrdkoya0xwMFYzWW1uSm1tSjZhWGo3dEI5Z245X2FZT2ZDdmpLVlZPazJ0RnJnU0ZHWXFwUzJuazB5YjFpQ1NheXpHdk55SXRpcDNkRVpYUUgzTzdlYi05SG5tSWJ4SktEaGNoc2drd3RWQlBTRG9pNUtYWlB4TUtLc2NSTnRhRHVlU25iNmc0a2g4aVhYRUJ2WHpPTy10d3dObjZkYk56LVhlTkk1amJXV3FPMGc5TlVxZXFfRUNNVzR3SThvdHZpa0laa0trV3RCTEktLUFLTHN4cHdyUmp2RHV1V0ZmNlduYV9lJmlkPTIxMTkyNzEmY29udGV4dFR5cGU9bm9uZSIsImFjY291bnRfaWQiOiIyNjU3NjYxIiwiY29udGVudF9pZCI6IjExOTEiLCJ1c2VyX3Rva2VuIjoiZGpKOE16SXdNWHlJX0NzcjU3Z2pRSkFGaGRRT3BmX0FqUUNIVVpKOTRHenZIZ1F4MVVFa2dDaHdfNGdjVktwU01YNkpzQ0h3QkpkcjFPNXlQdUxibWtMSXAta1dEak53OVBIbGNZdHZIc2M4S0preFlIZ2JhckZraFhHa3ZKMmtMcDBWM1ltbkptbUo2YVhqN3RCOWduOV9hWU9mQ3ZqS1ZWT2sydEZyZ1NGR1lxcFMybmsweWIxaUNTYXl6R3ZOeUl0aXAzZEVaWFFIM083ZWItOUhubUlieEpLRGhjaHNna3d0VkJQU0RvaTVLWFpQeE1LS3NjUk50YUR1ZVNuYjZnNGtoOGlYWEVCdlh6T08tdHd3Tm42ZGJOei1YZU5JNWpiV1dxTzBnOU5VcWVxX0VDTVc0d0k4b3R2aWtJWmtLa1d0QkxJLS1BS0xzeHB3clJqdkR1dVdGZjZXbmFfZSIsImFkZGl0aW9uYWxfY2FzX3N5c3RlbSI6IjMyMDEifQ%3d%3d&signature=pxZ62SSu7AorlJAK3uhMWv8Y8qk%3d&sessionId=b730f0ac-e827-1821-7fc1-1da815710e93:1691f2ed-8d19-55db-b8be-170a780548f7&clientTag=html5:v3.7.1&referrer=aHR0cHM6Ly8zMjAxLnByZXByb2Qua3V4Lm90dC5rYWx0dXJhLmNvbS9saXZlLzgwOTc1NC9wcm9ncmFt",
      "com.microsoft.playready": "https://udrmv3.kaltura.com/cenc/playready/license?custom_data=eyJ1ZGlkIjoiNTExNTg2NDA2ODkyMDgyNiIsImZpbGVzIjoiIiwiY2Ffc3lzdGVtIjoiaHR0cHM6Ly8zMjAxLmZycDEub3R0LmthbHR1cmEuY29tL2FwaV92My9zZXJ2aWNlL2Fzc2V0RmlsZS9hY3Rpb24vZ2V0Q29udGV4dD9rcz1kako4TXpJd01YeUlfQ3NyNTdnalFKQUZoZFFPcGZfQWpRQ0hVWko5NEd6dkhnUXgxVUVrZ0Nod180Z2NWS3BTTVg2SnNDSHdCSmRyMU81eVB1TGJta0xJcC1rV0RqTnc5UEhsY1l0dkhzYzhLSmt4WUhnYmFyRmtoWEdrdkoya0xwMFYzWW1uSm1tSjZhWGo3dEI5Z245X2FZT2ZDdmpLVlZPazJ0RnJnU0ZHWXFwUzJuazB5YjFpQ1NheXpHdk55SXRpcDNkRVpYUUgzTzdlYi05SG5tSWJ4SktEaGNoc2drd3RWQlBTRG9pNUtYWlB4TUtLc2NSTnRhRHVlU25iNmc0a2g4aVhYRUJ2WHpPTy10d3dObjZkYk56LVhlTkk1amJXV3FPMGc5TlVxZXFfRUNNVzR3SThvdHZpa0laa0trV3RCTEktLUFLTHN4cHdyUmp2RHV1V0ZmNlduYV9lJmlkPTIxMTkyNzEmY29udGV4dFR5cGU9bm9uZSIsImFjY291bnRfaWQiOiIyNjU3NjYxIiwiY29udGVudF9pZCI6IjExOTEiLCJ1c2VyX3Rva2VuIjoiZGpKOE16SXdNWHlJX0NzcjU3Z2pRSkFGaGRRT3BmX0FqUUNIVVpKOTRHenZIZ1F4MVVFa2dDaHdfNGdjVktwU01YNkpzQ0h3QkpkcjFPNXlQdUxibWtMSXAta1dEak53OVBIbGNZdHZIc2M4S0preFlIZ2JhckZraFhHa3ZKMmtMcDBWM1ltbkptbUo2YVhqN3RCOWduOV9hWU9mQ3ZqS1ZWT2sydEZyZ1NGR1lxcFMybmsweWIxaUNTYXl6R3ZOeUl0aXAzZEVaWFFIM083ZWItOUhubUlieEpLRGhjaHNna3d0VkJQU0RvaTVLWFpQeE1LS3NjUk50YUR1ZVNuYjZnNGtoOGlYWEVCdlh6T08tdHd3Tm42ZGJOei1YZU5JNWpiV1dxTzBnOU5VcWVxX0VDTVc0d0k4b3R2aWtJWmtLa1d0QkxJLS1BS0xzeHB3clJqdkR1dVdGZjZXbmFfZSIsImFkZGl0aW9uYWxfY2FzX3N5c3RlbSI6IjMyMDEifQ%3d%3d&signature=pxZ62SSu7AorlJAK3uhMWv8Y8qk%3d&sessionId=b730f0ac-e827-1821-7fc1-1da815710e93:1691f2ed-8d19-55db-b8be-170a780548f7&clientTag=html5:v3.7.1&referrer=aHR0cHM6Ly8zMjAxLnByZXByb2Qua3V4Lm90dC5rYWx0dXJhLmNvbS9saXZlLzgwOTc1NC9wcm9ncmFt"
    },
    "clearKeys": {},
    "advanced": {
      "com.widevine.alpha": {
        "distinctiveIdentifierRequired": false,
        "persistentStateRequired": false,
        "videoRobustness": "SW_SECURE_CRYPTO",
        "audioRobustness": "SW_SECURE_CRYPTO",
        "sessionType": "",
        "serverCertificate": {},
        "serverCertificateUri": "",
        "individualizationServer": ""
      }
    },
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1,
    "preferredKeySystems": [],
    "keySystemsMapping": {}
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": false,
    "defaultPresentationDelay": 0,
    "segmentRelativeVttTiming": false,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
        "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
      }
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "ignoreImageStreamFailures": false,
      "defaultAudioCodec": "mp4a.40.2",
      "defaultVideoCodec": "avc1.42E01E",
      "ignoreManifestProgramDateTime": false,
      "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\""
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 60,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": true,
    "alwaysStreamText": true,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.5,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2,
    "lowLatencyMode": false,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 1,
    "dispatchAllEmsgBoxes": false,
    "observeQualityChanges": false,
    "maxDisabledTime": 30
  },
  "offline": {
    "usePersistentLicense": true,
    "numberOfParallelDownloads": 5
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 500000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    },
    "advanced": {
      "minTotalBytes": 128000,
      "minBytes": 16000,
      "fastHalfLife": 2,
      "slowHalfLife": 5
    },
    "restrictToElementSize": false,
    "ignoreDevicePixelRatio": false
  },
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferredVideoCodecs": [],
  "preferredAudioCodecs": [],
  "preferForcedSubs": false,
  "preferredDecodingAttributes": [],
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null,
  "cmcd": {
    "enabled": false,
    "sessionId": "",
    "contentId": "",
    "useHeaders": false
  }
}`

**What did you do?**
play the media with / without subtitels - wait short time then it is observed

**What did you expect to happen?**

playback does not stall

**What actually happened?**
 player video frame is freeze for some time  (rate 0) audio goes on and also subtitles keep going
then the freeze ends playback rate change to fast playback to reach the gap

https://user-images.githubusercontent.com/16818804/205031872-87212bc3-ecc9-4b3d-b8dc-bca9907f5ff2.mp4

<img width="543" alt="Screen Shot 2022-11-30 at 12 37 23" src="https://user-images.githubusercontent.com/16818804/205031988-5b0344b5-9877-45b1-9d33-8ed2c0f035c7.png">
<img width="1107" alt="Screen Shot 2022-11-28 at 21 52 29" src="https://user-images.githubusercontent.com/16818804/205032217-d9f3802b-6fac-4e23-b8bb-50ff2a24ab24.png">
<img width="772" alt="Screen Shot 2022-11-28 at 21 47 17" src="https://user-images.githubusercontent.com/16818804/205032227-821aaf64-4e87-4d24-b1ed-7d90efffdd1b.png">
<img width="771" alt="Screen Shot 2022-11-28 at 21 42 17" src="https://user-images.githubusercontent.com/16818804/205032234-331a2245-5321-4f93-909a-1a46fede51ff.png">
<img width="811" alt="Screen Shot 2022-11-28 at 21 41 51" src="https://user-images.githubusercontent.com/16818804/205032240-9eb2f6b7-d4a7-4b3b-b027-83f47852a719.png">
<img width="810" alt="Screen Shot 2022-11-28 at 21 32 27" src="https://user-

**Comment by joeyparrish** [comment]
If the playhead is moving, and audio and subtitles are updating, but the video frame is frozen, that sounds like an "under the hood" issue for the browser or the media itself.  If the player fails to append a video segment, playback stalls completely, and the playhead doesn't move.  The weird "catch-up" behavior also is something the player wouldn't be capable of, and may indicate a rendering issue inside the browser.

I would recommend you check chrome:media-internals to see if there are any logs indicating an issue at the level of the browser/demuxer/decoder.

**Comment by joeyparrish** [comment]
I'm marking this as an "external" issue assuming it's something the browser is doing wrong or something in the content encoding that the browser can't handle.  If we find evidence that points back to the player, we can change the labels and take the issue back.

Let us know what else we can do to support you in investigating.

**Comment by giladna** [comment]
@joeyparrish some how we were able to overcome this issue 
we have added `defaultPresentationDelay`  configuration to the player and issue was gone

```
"manifest": {
   "defaultPresentationDelay": 9
  }
```

We suspect it may related to the fact that live edge is being requested too early, do you think this is the case?

attaching the manifest

Thx!

[manifest_defaultPresentationDelay.mpd.zip](https://github.com/shaka-project/shaka-player/files/10202298/manifest_defaultPresentationDelay.mpd.zip)

**Comment by joeyparrish** [comment]
Requesting the live edge too early should result in a hung request or an HTTP 404 error.  Neither of those would explain the frozen video frame with only audio playing, unless there is a bug in the browser or CDM that produces this effect.

**Comment by avelad** [comment]
Since it is an external problem, can you check if the latest versions of Chrome have resolved the problem?
