### ISSUE TITLE
PS5 limitation causing playable variants to be dropped

### ISSUE THREAD

**Issue by littlespex** [shaka-project/shaka-player#4782]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.x

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No, the issue is device specific

**What browser and OS are you using?**
- Device: PS5
- OS: Prospero
- UA: `Mozilla/5.0 (PlayStation; PlayStation 5/4.00) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15`

**What are the manifest and license server URIs?**

Available upon request

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Load a DRM protected stream that produces 20+ variants in the period flattening process.

**What did you expect to happen?**
All playable variants are available via `player.getVariantTracks()`.

**What actually happened?**

Playable variants are dropped.

**Additional notes**
This issue is due to a limitation on PS5 where `navigator.requestMediaKeySystemAccess()` can only   be called 20 times. From Sony MediaSDK team:

> The following are additional adaptations required when porting Shaka to PS5:
> 1. Only one DRM key system can be used per app session. Shaka 4.2.1 will probe each declared key system. This will lead to failure on the second key system access requests. The app needs to filter out the key systems that are not being used for the app session.
> 2. The number of key system access objects is limited to about 20. It looks like your app has 36 variants which result in 36 requestMediaKeySystemAccess calls which exceeds the limit.
>     a. Keeping only the variants with the desired audio codec, e.g., mp4a, will reduce the variants to 24 which is still 4 too many.
>     b. Failed requestMediaKeySystemAccess only results in the exclusion of the variants. The retained variants can function.
>     c. Above actions should yield multiple audio tracks.
> 
> So some general suggestions from our side would be:
> 1. Filter out the undesirable key systems.
> 2. Filter out variants with incompatible codecs.
> 3. If there are still too many variants, reduce audio and/or video representations to keep the > combinations under 20. This could be done, for example, in a 'manifestparsed' event handler.

Here is the dev ticket for those with access:
https://p.siedev.net/support/issue/109330#n1182634

**Comment by littlespex** [comment]
One potential fix that we have tried is to cache the results of each call to `requestMediaKeySystemAccess` in the `decodingInfo` polyfill because there are many codec/drm combinations that repeat. 

Can anyone think of any potential drawbacks to this approach?

**Comment by joeyparrish** [comment]
😭

**Comment by littlespex** [comment]
This issue is addressed by a previous fix: https://github.com/shaka-project/shaka-player/pull/4708
