### ISSUE TITLE
WebM/VP9 DASH steams don't work on Firefox for Android  

### ISSUE THREAD

**Issue by dim** [shaka-project/shaka-player#4786]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.3.0

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Not tried

**Are you using the demo app or your own custom app?**

Demo app

**If custom app, can you reproduce the issue using our demo app?**

N/A

**What browser and OS are you using?**

Firefox for Android 107.2.0

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/sintel-webm-only/dash.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default demo app configuration

**What did you do?**

Open a vp9/webm/dash stream in Firefox for Android, e.g. https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-webm-only/dash.mpd;panel=ALL_CONTENT;build=uncompiled

**What did you expect to happen?**

The video should play. The Shaka Demo URL above also works fine on Chrome/Android and Firefox/Desktop, but not Firefox/Android. Same video asset (just multiplexed) also plays just fine when opened on on its own in the same Firefox/Android browser, which suggests it may be a Shaka Player issue - https://s3.us-east-2.wasabisys.com/photox-us/vp9/vp9.webm.  

**What actually happened?**
Error Code 4032

```
Cannot play media. No decoders for requested formats: application/dash+xml, video/webm; codecs="vp09.00.41.08", video/webm; codecs="vp09.00.41.08", video/webm; codecs="vp09.00.41.08", video/webm; codecs="vp09.00.41.08", video/webm; codecs="vp09.00.41.08", video/webm; codecs="vp09.00.41.08", video/webm; codecs="vp09.00.41.08", video/webm; codecs="vp09.00.41.08", video/webm; codecs="vp09.00.41.08"
```

**Comment by WINOFFRG** [comment]
I suspect that the A/V Codec is supported by browser. The media you are trying to play the codec should be supported by the browser. 

Try this in console

```js
const v = document.createElement('video');
console.log(v.canPlayType('video/webm; codecs="vp09.00.41.08"'));
```

If the output of above is empty string then your browser is not capable of playing that codec. In case it return a string maybe or probaby then it might be an issue.

**Comment by dim** [comment]
Checked via USB Debugging console:

```js
// debugger eval code:2:9
const v = document.createElement('video');
console.log(v.canPlayType('video/webm; codecs="vp09.00.41.08"'));
// => probably
```

**Comment by dim** [comment]
As mentioned, the browser plays that very same asset without any problems if loaded [directly](https://s3.us-east-2.wasabisys.com/photox-us/vp9/vp9.webm) but it fails to play it when loaded by Shaka via Dash manifest.

**Comment by dim** [comment]
Just for reference, I submitted a bug report with the Firefox team as other players also seem affected - https://github.com/mozilla-mobile/fenix/issues/28127

**Comment by joeyparrish** [comment]
We will track this as an "external" bug (on Firefox) for now.

**Comment by avelad** [comment]
Fixed according to Mozilla folks https://bugzilla.mozilla.org/show_bug.cgi?id=1804715
