### ISSUE TITLE
DASH + HLS encrypted 360º streams

### ISSUE THREAD

**Issue by daniel-dias** [shaka-project/shaka-player#4788]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
Not being able to play streams with 360º content

**Describe the solution you'd like**
Have the ability to play DASH and HLS, 360º encrypted streams on Shaka Player. 
Is this feature being considered or in development?

**Comment by joeyparrish** [comment]
This is not currently in development as far as I know, and it is not a priority for the team at Google.  But we are always open to contributions from the community, and we encourage you to make a proposal if this is something you'd like to add.

Here's my rough understanding of the problem:

1. 360 video is encoded into a rectangle, just like normal video
2. After decoding, the video rectangle must be transformed into a rectangular view into the inside of a sphere or cylinder or something
3. There may be multiple encoding/transformation standards, and some metadata from the manifest or application to indicate which transformation should be used
4. The exact viewport of the transformation changes with some user input or accelerometer change

Is that accurate?

I expect the transformations would be done with WebGL, the input would be read from an off-screen video element, and the output would be written to a visible canvas element.  All of that is basically UI work.

_NB: Copying data from a video element would not be possible in some cases if the video used DRM.  That is a deliberate limitation of the browser and/or CDM that the player can do nothing about._

If there is transformation metadata to read from a manifest or playlist, that would involve changes to the DASH and/or HLS parsers, as well as the shaka.extern.Manifest structure, which would get new fields added for this metadata.  If not, the application could configure the player with a specific transformation to use, and that would involve changes to shaka.extern.PlayerConfiguration and its children.

The output canvas could be added to the Shaka Player UI, activated for 360 content, and used to hide the video element.  (We already have a canvas there for LCEVC, and could maybe reuse it if the two features never overlap.)  These new UI features could also listen for keyboard, mouse, or accelerometer events to adjust the viewport.

I hope this is helpful.  I am no expert in 360 video, so I may have made some mistakes here.  Feel free to correct me!  And PRs are very welcome, though we may want to discuss specific designs before we get to the PR phase.

**Comment by avelad** [comment]
WebGL cannot be used with encrypted video due to browser security architecture
