### ISSUE TITLE
SMPTE-TT Teletext subtitles are displaying in the wrong position

### ISSUE THREAD

**Issue by balajic7** [shaka-project/shaka-player#4793]
In the latest Shaka version, 4.3.0 TTML Subtitles are displaying in the wrong position whereas they are displaying correctly in the older version 4.1.2

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=http://192.168.225.199/vod_ttxt14/vxfmt=dash/Manifest.mpd;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.3.0-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

**What did you do?**

Play DASH content with TTML enabled.

**What did you expect to happen?**
Subtitles should be displayed in the correct place.

**What actually happened?**

![image](https://user-images.githubusercontent.com/112380887/205825615-c495e5d3-a6f1-48b9-bbfb-bd996dd0835d.png)

TTML:

[Sample_Subtitle_ttml.txt](https://github.com/shaka-project/shaka-player/files/10162979/Sample_Subtitle_ttml.txt)

**Comment by joeyparrish** [comment]
The link you sent is to a local IP on your network (192.168.x.x), so we can't access the content directly.

I am able to reproduce the issue with the attached subtitle, though, after modifying it and side-loading it in the demo.

**Comment by joeyparrish** [comment]
I modified this to reduce the timestamps to a reasonable range for side-loading onto other content:
[4793.ttml.txt](https://github.com/shaka-project/shaka-player/files/10181116/4793.ttml.txt)

With that in the shaka-player folder, you can side-load the content with:

```js
await player.addTextTrackAsync('../4793.ttml.txt', 'en', 'captions', 'application/ttml+xml', '', '')
```

Next steps are (in no particular order):
 - debug the CSS that is creating this
 - check that the TTML itself is within spec
 - check rendering of the same TTML in https://www.sandflow.com/imsc1_1/

**Comment by joeyparrish** [comment]
I'm not working on this issue this week, so with holidays, it will be _at least_ January before I can give this any attention.  Feel free to debug this yourself in the meantime.  Thanks!

**Comment by balajic7** [comment]
Hi @joeyparrish , Any update on this issue, In the latest version I am seeing subtitle overlapping and showing in different places.
