### ISSUE TITLE
Stream not played until seek  version 4.2.3

### ISSUE THREAD

**Issue by Leena-Sharma-rsys** [shaka-project/shaka-player#4799]
Hi,

This issues is same as https://github.com/shaka-project/shaka-player/issues/600

In my case always the video is not played if I seek a little the video starts playing. Also i tried getting my buffering range to check if there is any gap or not :

Buffered ranges: 3
 0 - 20.033332
 20.099999 - 29.999999
 30.066666 - 50.058666

Please help in fixing the issue

**Comment by joeyparrish** [comment]
@Leena-Sharma-rsys , please fill out the bug issue template.  Without the information in that template, we can't debug your issue.

Thanks!
