### ISSUE TITLE
Crash when switching subtitles on HLS video

### ISSUE THREAD

**Issue by toschlog** [shaka-project/shaka-player#4811]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.3.0

**Can you reproduce the issue with our latest release version?**

I haven't tried.

**Can you reproduce the issue with the latest code from `main`?**

I haven't tried.

**Are you using the demo app or your own custom app?**

Custom app.

**If custom app, can you reproduce the issue using our demo app?**

I haven't tried.

**What browser and OS are you using?**

Electron 20.0.0 on Windows 10.

**What did you do?**

Played Thelma & Louise on Pluto and turned subtitles on and off.

**What did you expect to happen?**

I expected subtitles to turn on and off.

**What actually happened?**

I got a crash in shaka-player.  Here's the stack trace:

```TypeError: Cannot read properties of null (reading 'length')
    at Da.h (shaka-player.compiled.js:754:1)
    at Ga (shaka-player.compiled.js:22:1)
    at Ha.next (shaka-player.compiled.js:23:1)
    at shaka-player.compiled.js:24:1
    at new Promise (<anonymous>)
    at Ia (shaka-player.compiled.js:24:1)
    at G (shaka-player.compiled.js:24:1)
    at xr (shaka-player.compiled.js:754:1)
    at Da.h (shaka-player.compiled.js:739:1)
    at Ga (shaka-player.compiled.js:22:1)
    at Ha.next (shaka-player.compiled.js:23:1)
    at shaka-player.compiled.js:24:1
    at new Promise (<anonymous>)
    at Ia (shaka-player.compiled.js:24:1)
    at G (shaka-player.compiled.js:24:1)
    at br (shaka-player.compiled.js:738:1)
    at Da.h (shaka-player.compiled.js:733:1)
    at Ga (shaka-player.compiled.js:22:1)
    at Ha.next (shaka-player.compiled.js:23:1)
    at b (shaka-player.compiled.js:24:1)
```

I don't have time right now to send over the manifest and other information.  When I can get to it I'll update this item.  But I'm hoping that the stack trace will be enough to see what's going on and fix it.

**Comment by joeyparrish** [comment]
Sorry, the stacktrace is difficult to read from a production build.  Can you use a debug build and send a stack from that?

**Comment by toschlog** [comment]
Yeah, I'll try that soon.  And it's quite possible that I'm screwing something up on my end.

**Comment by toschlog** [comment]
And actually, the subtitles aren't getting displayed at all for this video.  I'll attach the manifest.  And later I can get back to the crash when switching them on and off.

**Comment by toschlog** [comment]
Ok, it has something to do with the ads that Pluto is inserting.  The subtitles work at the beginning of the video, but not after the first ad insert.  The titles do work with hls.js.

**Comment by toschlog** [comment]
I realize that I have listed two bugs in the same ticket, something I hate when my testers do it.  Should I create new item for the inserted ads and leave this one for the on/off crash?

**Comment by joeyparrish** [comment]
Yeah, it's possible we have two separate issues.  Thank you for offering to create a separate one for the missing subs after ads!  That sounds ideal.

**Comment by toschlog** [comment]
Ok, the embedded ads issue is now here: https://github.com/shaka-project/shaka-player/issues/4828

**Comment by joeyparrish** [comment]
v4.3.2 fixed an exception in StreamingEngine teardown.  Can you try again with v4.3.2?

**Comment by toschlog** [comment]
Same error, I'm afraid.
```
TypeError: Cannot read properties of null (reading 'getIteratorForTime')
    at shaka.media.StreamingEngine.getSegmentReferenceNeeded_ (2.e8721bbc.chunk.js:2:1263631)
    at shaka.media.StreamingEngine.update_ (2.e8721bbc.chunk.js:2:1262007)
    at $jscomp.generator.Engine_.program_ (2.e8721bbc.chunk.js:2:1260020)
    at $jscomp.generator.Engine_.nextStep_ (2.e8721bbc.chunk.js:2:909868)
    at $jscomp.generator.Engine_.next_ (2.e8721bbc.chunk.js:2:908832)
    at $jscomp.generator.Generator_.next (2.e8721bbc.chunk.js:2:910313)
    at t (2.e8721bbc.chunk.js:2:910732)
```

"Thema & Louise" is no longer available on Pluto, so I'm testing with "Mean Girls."

I'm seeing a number of other errors, too, on this video.  I've attached a couple images.  Let me know if you would like more information or for me to create a new ticket or whatever.  I haven't looked into these new issues so it's possible that I'm doing something wrong in one of the callbacks or in my processing of the subtitles.

![1](https://user-images.githubusercontent.com/25090868/211095239-62fbf52c-43ce-46b7-bef1-bd3a35c7b993.PNG)

![2](https://user-images.githubusercontent.com/25090868/211095235-4a321c94-2580-46f0-b699-085e4bba29c7.PNG)

**Comment by avelad** [comment]
Can you test with v4.3.4? Thanks!

**Comment by toschlog** [comment]
@avelad I'm getting the same error with 4.3.4.

**Comment by avelad** [comment]
@toschlog can you provide a m3u8 stream to test? Thanks!

**Comment by toschlog** [comment]
I'm never sure what you need, but here are the URLs we loaded.  If there's something else, please let me know.

https://service-stitcher-ipv4.clusters.pluto.tv/stitch/hls/episode/5c6de49d967bb1dada14fba8/master.m3u8?advertisingId=&appName=web&appVersion=5.1.1-11a5dc6accfa4eef774a3bd9df69fe0898ebf50f&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=d9ef6006-5c22-4ad9-90a4-026351c6ba38&deviceLat=42.2324&deviceLon=-83.7017&deviceMake=Chrome&deviceModel=Chrome&deviceType=web&deviceVersion=80.0.3987.149&includeExtendedEvents=false&marketingRegion=US&sid=5741c7ed-5683-4657-8de0-11781c055e14&userId=

https://service-stitcher-ipv4.clusters.pluto.tv/stitch/hls/episode/5c6de49d967bb1dada14fba8/997452/playlist.m3u8?terminate=false&sid=5741c7ed-5683-4657-8de0-11781c055e14&deviceDNT=0&deviceLat=42.2324&deviceLon=-83.7017&deviceModel=Chrome&deviceVersion=80.0.3987.149&includeExtendedEvents=false&appName=web&deviceId=d9ef6006-5c22-4ad9-90a4-026351c6ba38&appVersion=5.1.1-11a5dc6accfa4eef774a3bd9df69fe0898ebf50f&deviceType=web&deviceMake=Chrome

https://service-stitcher-ipv4.clusters.pluto.tv/stitch/hls/episode/5c6de49d967bb1dada14fba8/3063648/playlist.m3u8?terminate=false&sid=5741c7ed-5683-4657-8de0-11781c055e14&deviceDNT=0&deviceLat=42.2324&deviceLon=-83.7017&deviceModel=Chrome&deviceVersion=80.0.3987.149&includeExtendedEvents=false&appName=web&deviceId=d9ef6006-5c22-4ad9-90a4-026351c6ba38&appVersion=5.1.1-11a5dc6accfa4eef774a3bd9df69fe0898ebf50f&deviceType=web&deviceMake=Chrome

https://service-stitcher-ipv4.clusters.pluto.tv/stitch/hls/episode/5c6de49d967bb1dada14fba8/subtitle/en/playlist.m3u8?terminate=false&sid=5741c7ed-5683-4657-8de0-11781c055e14&deviceDNT=0&deviceLat=42.2324&deviceLon=-83.7017&deviceModel=Chrome&deviceVersion=80.0.3987.149&includeExtendedEvents=false&appName=web&deviceId=d9ef6006-5c22-4ad9-90a4-026351c6ba38&appVersion=5.1.1-11a5dc6accfa4eef774a3bd9df69fe0898ebf50f&deviceType=web&deviceMake=Chrome

https://siloh-sp.plutotv.net/597_Warner_Bros/clip/5c6de49c967bb1dada14fba3_Purple_Rain/720pDRM/20230131_121048/hls/0-967843/en/en.m3u8_00001.vtt

**Comment by toschlog** [comment]
I'm never sure what to send, but here are the URLs we loaded for this video.  Please let me know if you need anything else.

https://service-stitcher-ipv4.clusters.pluto.tv/stitch/hls/episode/5c6de49d967bb1dada14fba8/master.m3u8?advertisingId=&appName=web&appVersion=5.1.1-11a5dc6accfa4eef774a3bd9df69fe0898ebf50f&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=d9ef6006-5c22-4ad9-90a4-026351c6ba38&deviceLat=42.2324&deviceLon=-83.7017&deviceMake=Chrome&deviceModel=Chrome&deviceType=web&deviceVersion=80.0.3987.149&includeExtendedEvents=false&marketingRegion=US&sid=5741c7ed-5683-4657-8de0-11781c055e14&userId=

https://service-stitcher-ipv4.clusters.pluto.tv/stitch/hls/episode/5c6de49d967bb1dada14fba8/997452/playlist.m3u8?terminate=false&sid=5741c7ed-5683-4657-8de0-11781c055e14&deviceDNT=0&deviceLat=42.2324&deviceLon=-83.7017&deviceModel=Chrome&deviceVersion=80.0.3987.149&includeExtendedEvents=false&appName=web&deviceId=d9ef6006-5c22-4ad9-90a4-026351c6ba38&appVersion=5.1.1-11a5dc6accfa4eef774a3bd9df69fe0898ebf50f&deviceType=web&deviceMake=Chrome

https://service-stitcher-ipv4.clusters.pluto.tv/stitch/hls/episode/5c6de49d967bb1dada14fba8/subtitle/en/playlist.m3u8?terminate=false&sid=5741c7ed-5683-4657-8de0-11781c055e14&deviceDNT=0&deviceLat=42.2324&deviceLon=-83.7017&deviceModel=Chrome&deviceVersion=80.0.3987.149&includeExtendedEvents=false&appName=web&deviceId=d9ef6006-5c22-4ad9-90a4-026351c6ba38&appVersion=5.1.1-11a5dc6accfa4eef774a3bd9df69fe0898ebf50f&deviceType=web&deviceMake=Chrome

https://service-stitcher-ipv4.clusters.pluto.tv/stitch/hls/episode/5c6de49d967bb1dada14fba8/3063648/playlist.m3u8?terminate=false&sid=5741c7ed-5683-4657-8de0-11781c055e14&deviceDNT=0&deviceLat=42.2324&deviceLon=-83.7017&deviceModel=Chrome&deviceVersion=80.0.3987.149&includeExtendedEvents=false&appName=web&deviceId=d9ef6006-5c22-4ad9-90a4-026351c6ba38&appVersion=5.1.1-11a5dc6accfa4eef774a3bd9df69fe0898ebf50f&deviceType=web&deviceMake=Chrome

https://siloh-sp.plutotv.net/597_Warner_Bros/clip/5c6de49c967bb1dada14fba3_Purple_Rain/720pDRM/20230131_121048/hls/0-967843/en/en.m3u8_00000.vtt

For the last one, there's also en.m3u8_00001.vtt, en.m3u8_00002.vtt, etc.

**Comment by avelad** [comment]
I tested your manifest and I don't see any error. The manifest only has one subtitle (WebVTT). I used the main branch

![Captura de pantalla 2023-02-10 a las 13 59 42](https://user-images.githubusercontent.com/8983024/218098589-d84728e3-1ea4-43f5-9212-5fdeaabb818a.png)

Note: The only bug I see is related to https://github.com/shaka-project/shaka-player/issues/4828.
