### ISSUE TITLE
Stream not played until seek

### ISSUE THREAD

**Issue by Leena-Sharma-rsys** [shaka-project/shaka-player#4815]
Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
YES

**What version of Shaka Player are you using?**
Checked on 4.2.3 and 4.3.1 

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `main`?**
YES

**Are you using the demo app or your own custom app?**
CUSTOM APP with React

**If custom app, can you reproduce the issue using our demo app?**
Played on online player with same url:
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://e2f9de5d62b647428fb652c48267a777.mediatailor.us-west-2.amazonaws.com/v1/dash/9a39c1f787063acfe5de4814e922e22605c1572d/skipAdTest/b9ae3db57338421f986cc028c88d1f40/64c179c9a6b04128ab4105d723012382/c2fa5c88342340349588b8dc8a73f0c4/index.mpd?aws.sessionId=6952a57c-6e0e-4675-ac1c-4f98c84012d0;panel=CUSTOM%20CONTENT;build=uncompiled

SHOWS LOADER , NOT ABLE TO PLAY

**What browser and OS are you using?**
Browser: Chrome,
OS: MAC

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NO embedded devices

**What are the manifest and license server URIs?**
ON MAIL

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
ON MAIL

**What did you do?**
JUST played the manifest Url. No extra configuration

**What did you expect to happen?**
Should Autoplay or atleast play on hitting play button 

**What actually happened?**

This issues is same as [#600](https://github.com/shaka-project/shaka-player/issues/600)

In my case always the video is not played on hitting play button,  if I seek a little the video starts playing. It occurs every time. Also i tried getting my buffering range to check if there is any gap or not :

Buffered ranges: 3
 0.034333 - 9.967666
10.034333 - 19.934333
20 - 39.991999

Also happens with the url having buffered range as :
Buffered ranges: 
0 - 20.033332 
20.099999 - 29.999999  
30.066666 - 50.058666

Please help in fixing the issue.

**Comment by avelad** [comment]
You stream returns a 404
