### ISSUE TITLE
AndroidTV WebView, video freezing while audio continued.

### ISSUE THREAD

**Issue by MASTER-SHAKE** [shaka-project/shaka-player#4818]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
own custom app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
AndroidTV WebView 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
- Mi TV Stick MiTV-AESP0
- Sony Bravia XBR-75X850C

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

Freezing happened on streams and sometimes in VOD. Meanwhile video unfreeze when user call control panel.
Mainly this happens when player try to
`Seeking forward 0.1 seconds to break stall.`
or
`Jumping forward 5.219304457306862 seconds to catch up with the seek range.`

https://user-images.githubusercontent.com/4558166/207054520-7ceb2e67-8c30-4d85-94bb-8730207dbcca.mp4

PC chrome/firefox working perfectly

**Comment by avelad** [comment]
Can you provide all fields of the template? It's necessary to provide support. Thanks!

**Comment by MASTER-SHAKE** [comment]
> Can you provide all fields of the template? It's necessary to provide support. Thanks!

Sent an E-mail to shaka-player-issues@google.com, letter subject "getConfiguration #4818 issue" with all shaka fields config
