### ISSUE TITLE
Question about v4.4 milestone

### ISSUE THREAD

**Issue by tyrelltle** [shaka-project/shaka-player#4820]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v4.2

**Please ask your question**
We have recent PRs got merged and targeted on v4.4 milestone https://github.com/shaka-project/shaka-player/milestone/26.
What is estimated date for releasing v4.4 ?
Is it possible to have beta version or internal version to be published to NPM ?

**Comment by lindsayrr** [comment]
I am on the same team as @tyrelltle, our product really needs the change in this [PR](https://github.com/shaka-project/shaka-player/pull/4770) to roll out further. I am wondering if our PRs can be labeled as v4.3 and released earlier. Really appreciate the help!

**Comment by joeyparrish** [comment]
Cherry-picking features to v4.3 would break semantic versioning.  See https://semver.org/ for more information if you are not familiar with that system.

The next feature release is v4.4.0, and we don't have a schedule for it, but I do not plan to release v4.4 until January, as we are all about to go on holiday until then.  (Some of us are already on holiday.)

So while we won't have a v4.4 release published to NPM in the two weeks remaining in this year, you can always build from source on GitHub or use the pre-compiled nightly builds from main, which are available at https://nightly-dot-shaka-player-demo.appspot.com/dist/ as shaka-player.compiled.js, shaka-player.ui.js, controls.css, etc.  These options may or may not work for your build and deployment infrastructure, and I wouldn't recommend them long-term in any case.

I apologize if the delay of v4.4 is causing a problem for you, and I hope one of these workarounds is suitable.  If not, we'll all be back in January.

**Comment by tyrelltle** [comment]
@joeyparrish thanks so much for clarifying.
 Is there nightly built npm package as well or only the js file ?  I can not see nightly built package  in npm.js but just double checking.

**Comment by joeyparrish** [comment]
No, there isn't a nightly build on npm.

**Comment by tyrelltle** [comment]
Thanks for confirming. Closing this Issue.
