### ISSUE TITLE
Multiple text streams loaded and displayed

### ISSUE THREAD

**Issue by willdharris** [shaka-project/shaka-player#4821]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chrome 108 / macOS Monterey‌‌‌‌ 12.6

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/sintel-many-subs/dash.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default

**What did you do?**

1. Go to the shaka player demo app and load the [Sintel w/ 44 subtitle languages](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-many-subs/dash.mpd;panel=ALL_CONTENT;panelData=SUBTITLES,DASH;build=uncompiled) asset.
2. Start playback and open dev console.
3. Paste the following in console and hit enter, calling both methods at the same time.
```
shakaDemoMain.player_.setTextTrackVisibility('true')
shakaDemoMain.player_.selectTextLanguage('ko')
```
4. Seek to a content time with captions; 2:00 min.
5. Observe the language selected plus English are displayed.

**What did you expect to happen?**
Subtitles to be enabled with only the newly selected language showing.

**What actually happened?**

Subtitles in multiple languages are displayed.

![shaka-double-cc](https://user-images.githubusercontent.com/66787651/207153516-e25fe490-b6b0-42df-a168-c59de2626168.png)

**Comment by willdharris** [comment]
Investigating this further, it appears a `textEngine` has not yet been created when the `player.selectTextLanguage('ko')` call is made. When [mediaSourceEngine.clear](https://github.com/shaka-project/shaka-player/blob/715035cd27e73e123ddf29c9a1b86b1ef4fc5be1/lib/media/media_source_engine.js#L801) is called from [loadNewTextStream_](https://github.com/shaka-project/shaka-player/blob/715035cd27e73e123ddf29c9a1b86b1ef4fc5be1/lib/media/streaming_engine.js#L223), `this.textEngine_` is still `null`. The `clear` function returns without removing the previously loaded text stream, and each text stream is added to the `textEngine` once it is created.

The below screenshot demonstrates that `this.textEngine_` is `null` when a new text stream is loaded from one or more calls to `player.selectTextLanguage()` right after `player.setTextTrackVisibility('true')`.

```
player.setTextTrackVisibility('true')
player.selectTextLanguage('de')
player.selectTextLanguage('ko')
player.selectTextLanguage('lv')
player.selectTextLanguage('ru')
```

![shaka-multi-cc2](https://user-images.githubusercontent.com/66787651/207166419-16eb4453-5a2d-413e-92b3-467ccac8a626.png)

**Comment by azakolbaev** [comment]
I will try that walk-around. Thank you!

**Comment by joeyparrish** [comment]
Thank you for investigating.  Since this appears to be triggered only by some very specific timing, I've set the priority for the team at P2.  PRs are welcome if you want to work on this before we have time!

**Comment by avelad** [comment]
@willdharris are you interested on send a PR for this? Thanks!

**Comment by willdharris** [comment]
@avelad Yes, looking at a fix for this with @littlespex.
