### ISSUE TITLE
How to update FairPlay license server URL depending on the version of the m3u8 manifest parsed ?

### ISSUE THREAD

**Issue by loicraux** [shaka-project/shaka-player#4827]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.2.2

**Please ask your question**

We are using EZDRM as a DRM provider.

The EZDRM Unified Streaming Packager generates 2 manifest files per movie : 
- a `movie_id-cenc/stream.mpd` manifest file for the MPG-DASH protocol
- and a `movie_id-fairplay/stream.m3u8`  manifest file for the HLS protocol.

Now here is our _current_ logic for our player based on Shaka Player : 

```ts
const EZDRM_WIDEVINE_ACCOUNT_PX_NUMBER = '...';
const EZDRM_PLAYREADY_ACCOUNT_PX_NUMBER = '...';
const EZDRM_FAIRPLAY_ACCOUNT_PX_NUMBER = '...';

const BASE_URL = '...';

// Key systems
const GOOGLE_WIDEVINE_KEY_SYSTEM = 'com.widevine.alpha';
const MS_PLAYREADY_KEY_SYSTEM = 'com.microsoft.playready';
const APPLE_FAIRPLAY_KEY_SYSTEM = 'com.apple.fps';

ShakaPolyfill.installAll();

const shakaPlayer = new ShakaPlayer(videoElement);

shakaPlayer.configure({
    drm: {
        preferredKeySystems: [GOOGLE_WIDEVINE_KEY_SYSTEM, MS_PLAYREADY_KEY_SYSTEM, APPLE_FAIRPLAY_KEY_SYSTEM],
        servers: {
            [GOOGLE_WIDEVINE_KEY_SYSTEM]: `https://widevine-dash.ezdrm.com/proxy?pX=${EZDRM_WIDEVINE_ACCOUNT_PX_NUMBER}`,
            [MS_PLAYREADY_KEY_SYSTEM]: `https://playready.ezdrm.com/cency/preauth.aspx?pX=${EZDRM_PLAYREADY_ACCOUNT_PX_NUMBER}`,
            [APPLE_FAIRPLAY_KEY_SYSTEM]: `https://fps.ezdrm.com/api/licenses/{assetId}`
        },
        advanced: {
            [APPLE_FAIRPLAY_KEY_SYSTEM]: {
                serverCertificateUri: 'https://path.to/fairplay.cer'
            }
        }
    }
});

async function updateLicenseRequest(type: net.NetworkingEngine.RequestType, request: extern.Request): Promise<void> {
    // Do update the license request only for Fairplay key system :
    if (type !== net.NetworkingEngine.RequestType.LICENSE || this.shakaPlayer.drmInfo()?.keySystem !== APPLE_FAIRPLAY_KEY_SYSTEM) {
        return;
    }

    // Some async XHR call and logic to get the asset ID ...
    const assetId = await getAssetId();

    const uri = first(request.uris);
    assertIsDefined(uri);
    request.uris = [uri.replace('{assetId}', assetId)];
    request.method = 'POST';
    request.headers['Content-Type'] = 'application/octet-stream';
}

shakaPlayer.getNetworkingEngine()?.registerRequestFilter(updateLicenseRequest);

function getManifestFileURI(protocol: 'dash' | 'hls', movieId: string): string {
    const fileExtension = protocol === 'dash' ? 'mpd' : 'm3u8';
    const ismFolderSuffix = protocol === 'dash' ? 'cenc' : 'fairplay';
    return `${BASE_URL}${movieId}-${ismFolderSuffix}.ism/stream.${fileExtension}`;
};

const movieId = 'some-movie-id';

let manifestFileURI = getManifestFileURI('dash', movieId);
try {
    await shakaPlayer.load(manifestFileURI);
} catch (error: unknown) {
    logWarning(`Failed to load the MPEG-DASH manifest file ${manifestFileURI}, switching to HLS...`);
    manifestFileURI = getManifestFileURI('hls', movieId);
    try {
        await shakaPlayer.load(manifestFileURI);
    } catch (error: unknown) {
        logError(`Also failed to load the HLS manifest file ${manifestFileURI}!`);
        if (error instanceof util.Error) {
            logError(`Received Shaka player error code ${error.code} !`, error);
        } else {
            logError(`Unknown error !`);
        }
    }
}
```

Now our film catalog is being gradually repackaged with a different way of generating the keys **for fairplay**:
- the current way (which will be deprecated at some point) of packaging our movies for fairplay generates 1 key per movie
- the new way (which will be gradually deployed) generates several keys per file (for the different video (and audio) streams)

From the player's point of view, to get the license :
- in the first case (current logic, see current code above), we look for the assetId in a file on our cloud infrastructure (`getAssetId`) then call this license server url: https://fps.ezdrm.com/api/licenses/{assetId}
- in the second case (new packaging / keys), we will simply have to call the url `https://fps.ezdrm.com/api/licenses/auth?pX=${EZDRM_FAIRPLAY_ACCOUNT_PX_NUMBER}`

- In the first case (current packaging for FairPlay) the `#EXT-X-VERSION` tag in the m3u8 file will be < 5
- In the second case (new packaging for FairPlay being rolled out) the `#EXT-X-VERSION` tag in the m3u8 file will be >= 5

I'd like to write the minimum amount of code changes to our player code to implement this logic.

My first problem is that I am not sure I can retrieve the m3u8 version by using Shaka Player API, from its codebase it looks like `#EXT-X-VERSION` is not parsed. I see there is a `manifestparsed` event that looks promising and a `player.getManifest` API, but the later is deprecated... Can you confirm or correct me if I'm wrong please ? Is there at least a way to access to the manifest file raw contents ?

Assuming that I've determined as soon as possible the m3u8 version , where would you add the logic to use the proper license server URL for Apple FairPlay Key System ? I could : 
   -  not call `shakaPlayer.getNetworkingEngine()?.registerRequestFilter(updateLicenseRequest);` (or unregister it ?) and update drm.servers[APPLE_FAIRPLAY_KEY_SYSTEM] URI the if version is >= 5 (not sure if I can still update the drm config after the manifest has been parsed ?)
   - or inside the implementation of `updateLicenseRequest`, check the version number and depending on it, update accordingly the URI
   - or ... (suggestions welcomed) ?

Thanks in advance for you help !

**Comment by joeyparrish** [comment]
> I see there is a manifestparsed event that looks promising and a player.getManifest API, but the later is deprecated... Can you confirm or correct me if I'm wrong please ? Is there at least a way to access to the manifest file raw contents ?

I would suggest you not use either of those, because the "manifest" these refer to is parsed into an internal representation in JavaScript objects.  You won't have access to the M3U8 version with these.

You can get the raw text of the master playlist with a network response filter.  For example (untested, may have mistakes):

```js
player.getNetworkingEngine().registerResponseFilter((type, response) => {
  if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST ||
      response.originalUri != player.getAssetUri()) {
    // Not the master playlist.  Ignore it.
    return;
  }

  const text = shaka.util.StringUtils.fromUTF8(response.data);
  // Do something with the text, and call player.configure() with an appropriate config.
});
```

This will be called before the playlist text has been consumed by the player, so any config changes you make at this point will take effect immediately for the new playback session.

Does this help?

**Comment by loicraux** [comment]
Thanks for the suggestion, but I see that when the .m3u8 master file is loaded in Safari, `src=` is used, meaning that the Hls_Parser is not called, and the request of type RequestType.MANIFEST is not made.

Actually both native and MSE playback are possible, but `useNativeHlsOnSafari` is set to true (by default) in the config, so I end up with `src=` (native) playback being used...

If I set `useNativeHlsOnSafari` to false in my config (which goes a bit against our use case (multiple keys), since I read in the comments : _Warning when disabled: Where single-key DRM streams work fine, multi-keys streams is showing unexpected behaviours (stall, audio playing with video freezes, ...)_), the request of type RequestType.MANIFEST is indeed made for the m3u8 (meaning the hsl_parser is used), but I get a `HLS_MSE_ENCRYPTED_MP2T_NOT_SUPPORTED` error...

I can see [here](https://github.com/shaka-project/shaka-player/issues/4146#issuecomment-1115999801) that encrypted TS does not work with FairPlay on MSE... So I guess I have to leave `useNativeHlsOnSafari` set to true in my config and fetch the manifest by myself...

**Comment by joeyparrish** [comment]
Yes, that seems to be the case.  With src= playback (native HLS on Safari), we are not involved in the fetching or parsing of the playlists.  Sorry we couldn't help you with this in the player, but it seems like fetching the playlist yourself and using RegExp to extract the version is your best bet.
