### ISSUE TITLE
Embedded ads mess up subtitles

### ISSUE THREAD

**Issue by toschlog** [shaka-project/shaka-player#4828]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.3.0

**Can you reproduce the issue with our latest release version?**

Have not tried.

**Can you reproduce the issue with the latest code from `main`?**

Have not tried.

**Are you using the demo app or your own custom app?**

Custom app

**If custom app, can you reproduce the issue using our demo app?**

Have not tried.

**What browser and OS are you using?**

Electron 20.0.0 on Windows 10.

**What are the manifest and license server URIs?**

https://service-stitcher-ipv4.clusters.pluto.tv/stitch/hls/episode/59014205a1041ca52b5ab469/master.m3u8?advertisingId=&appName=web&appVersion=5.1.1-11a5dc6accfa4eef774a3bd9df69fe0898ebf50f&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=d9ef6006-5c22-4ad9-90a4-026351c6ba38&deviceLat=42.2709&deviceLon=-83.7268&deviceMake=Chrome&deviceModel=Chrome&deviceType=web&deviceVersion=80.0.3987.149&includeExtendedEvents=false&marketingRegion=US&sid=5741c7ed-5683-4657-8de0-11781c055e14&userId=

**What did you do?**

Viewed Thelma & Louise from Pluto in Hearo.

**What did you expect to happen?**

I expected subtitles to work.

**What actually happened?**

Subtitles work fine at the beginning of the movie, but after the first inserted ad they stop appearing at all.

Perhaps it has something to do with timestamp mapping?

```
X-TIMESTAMP-MAP=MPEGTS:241290000,LOCAL:00:00:00.000

841
00:07:51.050 --> 00:07:52.427 align:middle
It's our future.
```

**Comment by joeyparrish** [comment]
Acknowledged.  This might be fixed (or improved) by ongoing work for #4589, so I will check back when that is complete.

**Comment by joeyparrish** [comment]
#4589 is fixed now, and the fixes are in v4.2.7 and v4.3.3.  @toschlog, can you please retest with one of those releases?

**Comment by toschlog** [comment]
@joeyparrish I'm still seeing the problem in 4.3.3.  Sorry.

**Comment by joeyparrish** [comment]
Okay.  Thanks for the update.

**Comment by avelad** [comment]
@joeyparrish you can reproduce the issue with the playlist of https://github.com/shaka-project/shaka-player/issues/4811#issuecomment-1424781440 (please, use a CORS extension to allow disable CORS errors)

**Comment by avelad** [comment]
Playlist with the issue: https://playertest.longtailvideo.com/adaptive/elephants_dream_v4/redundant.m3u8
