### ISSUE TITLE
while implementing fairplay on shaka player getting response "spc message can't be null"

### ISSUE THREAD

**Issue by Jatin00555** [shaka-project/shaka-player#4829]
We are trying to play fairplay content on safari over macos using shaka player. We are sendinf spc message as per documentation and tried various ways but still getting response "spc message cant not be null". We tried sending it in header and and body also and tried different encoding. Here are code and response below.

```
if (this.platform.getBrowserPlatform() === Constants.PLATFORMS.SAFARI_WEB) {
            this.shakaPlayer.configure({
                drm: {
                    servers: {
                        'com.apple.fps.1_0': `${this.config.baseUrl}${Constants.DRM_FAIRPLAY_LICENSE}`,
                    },
                    advanced: {
                        'com.apple.fps.1_0': {
                            serverCertificate: cert,
                        },
                    },
                },
            });
            let that = this //,licenseUri;
            this.shakaPlayer.configure('drm.initDataTransform', (initData) => {
                const skdUri = shaka.util.StringUtils.fromBytesAutoDetect(initData);
                var contentId = skdUri.substring(skdUri.indexOf('skd://') + 6);
                // licenseUri = skdUri.replace('skd://', 'https://');
                const url = new URL(contentId);
                const urlParams = new URLSearchParams(url.search);
                const cert = that.shakaPlayer.drmInfo().serverCertificate;
                let id = urlParams.get('contentId');
                that.id = id;
                return shaka.util.FairPlayUtils.initDataTransform(initData, id, cert);
                // let skdUrl = shaka.util.StringUtils.fromBytesAutoDetect(initData);
                // licenseUri = skdUrl.replace('skd://', 'https://');
                // const cert = that.shakaPlayer.drmInfo().serverCertificate;
                // return shaka.util.FairPlayUtils.initDataTransform(initData, licenseUri, cert);
            });

            this.shakaPlayer.getNetworkingEngine().registerRequestFilter((type, request) => {
                if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) {
                    return;
                }
                let token = localStorage.getItem('auth');
                let testToken = JSON.parse(token);


                const originalPayload = new Uint8Array(request.body);
                const base64Payload = shaka.util.Uint8ArrayUtils.toBase64(originalPayload);
                const params = `{ "spc": "${base64Payload}", "assetId":"${that.id}"}`;
                request.body = shaka.util.StringUtils.toUTF8(params);
                request.headers['Content-Type'] = 'application/json';
                request.headers['Authorization'] = `JWT ${testToken.access_token}`
                console.log("request.body", request.body)
            });

            this.shakaPlayer.getNetworkingEngine().registerResponseFilter((type, response) => {
                if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) {
                    return;
                }
                console.log("license passed")
                let responseText = shaka.util.StringUtils.fromUTF8(response.data);
                responseText = responseText.trim();
                if (responseText.substr(0, 5) === '<ckc>' &&
                    responseText.substr(-6) === '</ckc>') {
                    responseText = responseText.slice(5, -6);
                }
                response.data = shaka.util.Uint8ArrayUtils.fromBase64(responseText).buffer;
            });
            this.shakaPlayer.load(this.getProgramUrl(channel, program, restart)).then(() => {
                console.log('1', this.shakaPlayer.isTextTrackVisible());
                console.log('2', this.shakaPlayer.getTextTracks());
                console.log('3', this.shakaPlayer.getTextLanguages());
            }).catch((error) => {
                console.log(error);
            });
```

Response :- 
```

{
    "success": false,
    "message": "spc message cannot be null"
}

```
Request:-

![Screenshot 2022-12-13 at 10 07 43 PM (1)](https://user-images.githubusercontent.com/104584260/207393460-8f407133-fda2-4a3f-8b13-8e5d6a8e199d.png)

**Comment by joeyparrish** [comment]
I don't know what is wrong here.  I don't have any special expertise in FairPlay, though.

Can you debug from the license server where that message is being generated?  Is it expecting some other request format?

If the license server is provided by a third-party service, can you check their documentation to see if you're formatting the request correctly?

**Comment by parthsheth2403** [comment]
const originalPayload = new Uint8Array(request.body);
      var base64Payload = shaka.util.Uint8ArrayUtils.toStandardBase64(originalPayload);
      base64Payload = base64Payload.substring(1, base64Payload.length);
      const params = 'spc:' + base64Payload;
      //console.log(params)
      request.headers['Content-Type'] = 'application/x-www-form-urlencoded';
      request.body = shaka.util.StringUtils.toUTF8(encodeURIComponent(params));

You can pass spc URL in this format

**Comment by Jatin00555** [comment]
@shaka-bot reopen

We have implemented the following code and initially i.e for the first time we are getting our license success and streaming works fine but while assigning url for the second or another time getting error "Unable to parse spc, see inner exception for more information"


```
this.shakaPlayer.getNetworkingEngine().registerRequestFilter((type, request) => {
                if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) {
                    return;
                }
                let token = localStorage.getItem('auth');
                let testToken = JSON.parse(token);
                const originalPayload = new Uint8Array(request.body);
               request.headers['Content-Type'] = 'application/json;api-version=5.1 ';
                var pl = window.btoa(
                    Array(originalPayload.length).fill('').map((_, i) => String.fromCharCode(originalPayload[i])).join('')
                )
               //console.log(pl, "pl")
                const params = `{ "spc": "${pl}", "assetId":"${that.id}"}`;
                request.body = shaka.util.StringUtils.toUTF8(params);
                request.headers['Authorization'] = `JWT ${testToken.access_token}`;
            });
```

For initial time when license getting successful we are getting the following type SPC i.e starting with "AAAAA"

`AAAAAQAAAACK0Ysy9o3kyYvU3C55PH2rczJBYwdx0BCC8QKDkVvpfh5BdmoE8Z4qW9H/+g1KFJn5MA7BNjXqOHhhcc7rwACinHmWulS5zqsR/HSQ4jWsKMiuXv3UrRKkRIR9jYZiCpBoTEguGUI6myFGKatiZQJMQdG2AWeFIlaT1K9iCkxqE9/R2vMHh...`

And the response for the first time :

![Screenshot 2023-01-24 at 7 41 41 PM](https://user-images.githubusercontent.com/104584260/214318254-ae723971-c2a0-408e-9db5-d697a66e72ec.png)


From 1st time onwards we are getting follwing type of SPC that may be reason of the previous error we are getting on license call

`eyAic3BjIjogIkFBQUFBUUFBQUFEQS9vell4aEZqOUh4VHdqL3E2elZPajB0clN3ZHFqZU9sUFY4dGQ3Ui9jQURPWG9PTXUzMm1aWEM5NGoyS1NLQ3hDWm9QaGxZY3ROdUJpSCtvWkl1NVU3dm5qSUF4d2VjVENob0lmMUEzZVoveWV1M0h5TG...`

And for the response while getting error:

![Screenshot 2023-01-24 at 7 27 19 PM](https://user-images.githubusercontent.com/104584260/214318729-8a7ea519-938e-41ab-86f1-8f901dca0b74.png)


@joeyparrish  @parthsheth2403  Do you guys have any suggestion ?

**Comment by joeyparrish** [comment]
@avelad, any advice?

**Comment by avelad** [comment]
I think it has to do with the implementation of FairPlay on the server side, each provider has a different implementation. Some implementations are detailed at: https://github.com/shaka-project/shaka-player/blob/main/lib/util/fairplay_utils.js

What is your DRM provider?

**Comment by Jatin00555** [comment]
For HLS, the flow is - CPIX service (we host) -> Apple fairplay

@avelad
