### ISSUE TITLE
Investigate test speed in lab

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#4832]
~While working on #4831, I found that even with `--filter StreamingEngine`, the test runs on **Chromecast** took 20 minutes each.  For comparison, a complete test run with all tests takes 7 minutes on Linux Chrome on my desktop.~

We should measure the time taken by each test and compare between platforms.  If some test suites are slow, or slower than others when adjusting for general platform speed, we should target those for improvement.

**Comment by joeyparrish** [comment]
Disregard the details above.  I didn't realize I had left `--delay-tests 10` on while debugging.  With that removed, StreamingEngine tests on Chromecast complete in less than 5 minutes.

I still believe we should do the measurements, with a target of speeding up test runs overall.

**Comment by avelad** [comment]
@joeyparrish I think that with the changes that have been made in recent weeks there is now a good speed. Do you think we can close the issue?

**Comment by joeyparrish** [comment]
Sounds good.
