### ISSUE TITLE
CDM Initialization Start Time Event or Statistic Request

### ISSUE THREAD

**Issue by nkam12** [shaka-project/shaka-player#4833]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

I would like to be able to capture metrics around how long it takes the CDM to initialize for QoS metric tracking. Currently, I use the first instance of the drmsessionupdate event to detect when the CDM initialization is complete, but I don't have a good start time for when Shaka begins initializing the CDM.

**Describe the solution you'd like**

I would like for Shaka to either: 
a. Emit an event when CDM initialization first begins. 
or
b. Provide a metric for CDM time to init as part of the Stats provided by Shaka. 

**Describe alternatives you've considered**

Captured above. 

**Additional context**

**Comment by joeyparrish** [comment]
I think you could define some new events in player.js, and dispatch them from DrmEngine.  I believe there is already a callback to dispatch events from there through the Player instance.

PRs are always welcome!

**Comment by avelad** [comment]
@nkam12 are you interested on send a PR to add it? Thanks!
