### ISSUE TITLE
Custom build without lcevc fails

### ISSUE THREAD

**Issue by radiantmediaplayer** [shaka-project/shaka-player#4834]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Y

**What version of Shaka Player are you using?**
4.3.1

**Can you reproduce the issue with our latest release version?**
Y

**Can you reproduce the issue with the latest code from `main`?**
Y

**What did you do?**
I am on Ubuntu 20.04 LTS.
I am trying to build Shaka player 4.3.1 but without the lcvec component. 
The following command fails: 
python build/build.py +@networking +@manifests +@text +./node_modules/eme-encryption-scheme-polyfill/index.js +./lib/polyfill/abort_controller.js +./lib/polyfill/encryption_scheme.js +./lib/polyfill/mediasource.js +./lib/polyfill/media_capabilities.js +./lib/polyfill/patchedmediakeys_nop.js +./lib/polyfill/patchedmediakeys_webkit.js  +./lib/polyfill/random_uuid.js +./lib/polyfill/storage_estimate.js +./lib/polyfill/symbol.js +./lib/polyfill/videoplaybackquality.js +./lib/polyfill/vttcue.js
Error is: 
[INFO] Compiling the library (ui, release)...
/home/arnaud/shaka-player/lib/media/media_source_engine.js:31:0: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "shaka.lcevc.Dil" never defined.
  31| goog.require('shaka.lcevc.Dil');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/arnaud/shaka-player/lib/player.js:59:0: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "shaka.lcevc.Dil" never defined.
  59| goog.require('shaka.lcevc.Dil');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2 error(s), 0 warning(s)
[ERROR] Build failed

The following command works: 
python build/build.py +@networking +@manifests +@text +@lcevc +./node_modules/eme-encryption-scheme-polyfill/index.js +./lib/polyfill/abort_controller.js +./lib/polyfill/encryption_scheme.js +./lib/polyfill/mediasource.js +./lib/polyfill/media_capabilities.js +./lib/polyfill/patchedmediakeys_nop.js +./lib/polyfill/patchedmediakeys_webkit.js  +./lib/polyfill/random_uuid.js +./lib/polyfill/storage_estimate.js +./lib/polyfill/symbol.js +./lib/polyfill/videoplaybackquality.js +./lib/polyfill/vttcue.js

The only difference is the +@lcevc component. 
Can you have a look into it?

**Comment by joeyparrish** [comment]
I don't think you need to do this.  The internal bindings for the LCEVC library don't need to be removed.  Just don't include the external LCEVC library.  All of that code is skipped if the external library isn't loaded.

Of course, it would be somewhat more efficient to completely remove those bindings, but that's not possible with the current system.  I've been discussing a better strategy for modularity with the other maintainers, and we are making plans for a leaner "core" next year.

In the meantime, you can simply not load the external LCEVC library, which contains all the decoder logic.

**Comment by joeyparrish** [comment]
Does this help?

**Comment by radiantmediaplayer** [comment]
Allright, we will just leave the @lcevc module for our builds for the time being.
