### ISSUE TITLE
Seekbar moves when pausing a live stream in Safari

### ISSUE THREAD

**Issue by adgllorente** [shaka-project/shaka-player#4842]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not tested

**Are you using the demo app or your own custom app?**
I am using a clean instance of shaka-player in a custom app to configure fairplay DRM

**If custom app, can you reproduce the issue using our demo app?**
Not tested.

**What browser and OS are you using?**
Safari. The new Internet Explorer 😄 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Gist sent through email.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Almost default configuration, just extended for fairplay configuration.

**What did you do?**

Launch live stream playback and play pause.

**What did you expect to happen?**

Seekbar should stay in the same position.

**What actually happened?**

Seekbar moves back every X seconds. It seems it moves when a new Manifest y requested.

https://user-images.githubusercontent.com/1067480/207869001-9e530243-5329-4368-be52-d20ee21dd7c4.mov

**Comment by joeyparrish** [comment]
This is working as intended.  If you are paused, you are moving progressively further back from the live edge.  (Another way to think of it is that the live edge is moving _away_ from _you_.)

Does this answer your question?

**Comment by adgllorente** [comment]
Yep, I understang how live edge works but this is not happening with DASH.

There is a difference between DASH and HLS when user pauses a live stream.

HLS moves the seek bar backwards, I think this is happening because seek ranges are updated only when another manifest is retrieved.

However, DASH updates seek ranges every second, live edge moves forward but seek ranges too, so the seekbar stays in the same position.

**Comment by adgllorente** [comment]
Just to clarify, this situation is happening because HLS stream does not include EXT-X-PROGRAM-DATE-TIME tags.

Closing it is OK.
