### ISSUE TITLE
Tick timer keeps running after calling destroy

### ISSUE THREAD

**Issue by kiran-dcunha** [shaka-project/shaka-player#4850]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Did not try

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Did not check

**What browser and OS are you using?**
Mac/Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Start the playback. Stop (destroy).

added a snippet to print which timers are running - 
`
window.setTimeoutOriginal = window.setTimeout;
window.setTimeout = (func, delay) => {console.log("setTimeout", func); return window.setTimeoutOriginal(func, delay)}
`

**What did you expect to happen?**
Player should stop executing

**What actually happened?**

There is a tick timer that runs continuously. Screenshot is after destroy.
<img width="479" alt="image" src="https://user-images.githubusercontent.com/102036812/208641328-e8a05c95-b8c1-4d27-b0ef-dd496a695fa1.png">

**Comment by theodab** [comment]
Looks like we aren't releasing `shaka.media.RegionTimeline` when we destroy the player, and that class has a timer in it.
