### ISSUE TITLE
Safari needs to be restarted to get the content to play 

### ISSUE THREAD

**Issue by Cugi** [shaka-project/shaka-player#4852]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://d1sz9kpfvhhqqm.cloudfront.net/6bc94da86c90696cdfb9a29d3c6a5ed35cad8d43cf008798d912ff691a61982d/533c5bcb5dc450a03c0b44f0659ecb84f0318f142f10bf4ca3a15e95bc7053b9/5ce259b1-8144-11ed-a41d-cba3bd8fcc26/asset_video/AV_asset_5ce259b1-8144-11ed-a41d-cba3bd8fcc26.m3u8;license=https://fp.service.expressplay.com/hms/fp/rights/?ExpressPlayToken=BwAqVaU0KckAJDI2NzUwMjgyLTI2M2ItNGRlZi1iZGQzLTZiNzdiNjM4ZDNhZAAAAJBhcrwQWsK3sNMXFVHfC_vOomFlMFRhbovMuGxQTRVUcA4YogCEwftPMNxkyvKtuEU2gYptjNrhsTcgUkvHt8Y1DMJhyQZbps-_Pxt_VahdO4b8JbiB6cQmZLaLUaIdhq6oesabQM5NuJ5w2DjjJVurgMoRmfoE4cu0RTYbuU82gkJmf66Tn9g2MzFmjKMiFTY4b_J44FisHAxGbhAonTwlwYPykg;certificate=https://fpexpressplay.s3.amazonaws.com/fairplay.cer;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.3.2-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

**What did you do?**

**What did you expect to happen?**

The content is supposed to playback every time I press the play button. 

**What actually happened?**

The content plays once, then if I tried to play it again it does not and the error ([Shaka Error MEDIA.VIDEO_ERROR (3,,Media failed to decode)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3016)) is returned.  Once I shut down safari (quit)and restart it, then the content plays again.

**Comment by joeyparrish** [comment]
If you call `player.load()` (or click the "load" button in the demo) a second time instead of clicking the play button, is that an effective workaround?  The answer to that could help point us toward the root cause.
