### ISSUE TITLE
How to update manifest request retry configuration

### ISSUE THREAD

**Issue by lindsayrr** [shaka-project/shaka-player#4855]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**What version of Shaka Player are you using?**
4.3

**Please ask your question**
I tried to update the manifest request retry parameter when encounter a specific error. But since there is no configure method in network_engine.js as in streaming_engine.js, I was not able to do it. I am wondering if there is any function can be used to update manifest request retry parameters, or this is not supported.

**Comment by WINOFFRG** [comment]
You can simply call the `player.configure` method and refer the configuration provided here https://shaka-player-demo.appspot.com/docs/api/tutorial-config.html no need for the full, you can just pass in the new arguments and the config will be updated, to reset you can call `resetConfiguration`
