### ISSUE TITLE
Cannot add subtitle when loading a video without a manifest directly

### ISSUE THREAD

**Issue by FireMasterK** [shaka-project/shaka-player#4856]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not tried

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Brave, Arch Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

https://player.odycdn.com/api/v4/streams/free/redmi-k60-pro-vs-xiaomi-13-pro/982a475604b519260cf28a10e6b84d17c8acbc2b/ec29bb

(no manifest, just a direct `video/mp4`)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default / N/A

**What did you do?**
Load the video in the player, with the mime type `video/mp4`
document.querySelector("video").ui.getControls().getPlayer().addTextTrackAsync("...", "en", "SUBTITLE", "application/ttml+xml")

**What did you expect to happen?**
The subtitle to load, without the 2012 error code

**What actually happened?**
The subtitle doesn't load, and a 2012 error code is thrown

**Comment by WINOFFRG** [comment]
It will be little difficult for me to check without subtitle url being provided, however you can refer https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html for the above issue. If you loading the text tracks correctly and the browser supports it, then it should work.

**Comment by joeyparrish** [comment]
Side-loading TTML subtitles isn't supported with plain MP4 playback.  When we play plain MP4s, we pass that URL down to the browser and don't use internal components like StreamingEngine, MediaSourceEngine, or TextEngine.  This means only natively-supported subtitle formats (WebVTT) can be played in this mode.

Does this answer your question?

**Comment by avelad** [comment]
@joeyparrish the conversion is managed in the code. See: https://github.com/shaka-project/shaka-player/blob/main/lib/player.js#L5087

**Comment by joeyparrish** [comment]
Hrm... and yet [error code 2012](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:2012) is:

CANNOT_ADD_EXTERNAL_TEXT_TO_SRC_EQUALS | 2012 | number | External text tracks cannot be added in src= because native platform doesn't support it.
-- | -- | -- | --

@avelad, can you look into this?  If we support every type converted to VTT internally, why do we have this error code / check?

**Comment by avelad** [comment]
@joeyparrish the secret is in the code comments, https://github.com/shaka-project/shaka-player/blob/main/lib/player.js#L4751 

```
// This should not happen, but there are browser implementations that may
// not support the Track element
```

**Comment by avelad** [comment]
I'll check tomorrow what's going on.

**Comment by avelad** [comment]
@FireMasterK The kind value is erroneous. With `document.querySelector("video").ui.getControls().getPlayer().addTextTrackAsync("https://livesim.dashif.org/dash/vod/testpic_2s/sub_eng_short.xml", "en", "subtitles", "application/ttml+xml")` it works fine!

See the possible values in: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#attr-kind

**Comment by FireMasterK** [comment]
> @FireMasterK The kind value is erroneous. With `document.querySelector("video").ui.getControls().getPlayer().addTextTrackAsync("https://livesim.dashif.org/dash/vod/testpic_2s/sub_eng_short.xml", "en", "subtitles", "application/ttml+xml")` it works fine!
> 
> See the possible values in: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#attr-kind

You're right, that does indeed fix the issue! However, even with this, nothing seems to show up when actually selecting the track in the UI interestingly!

**Comment by avelad** [comment]
see https://github.com/shaka-project/shaka-player/pull/4867
