### ISSUE TITLE
Only one decoding session at a time in Android?

### ISSUE THREAD

**Issue by MarianoFacundoArch** [shaka-project/shaka-player#4860]
Hi,
I was trying to play two videos at the same time using Widevine in an Android device with SW_SECURE_DECODE. However, it seems only one can be played, the rest throw an exception.

The device has L1, max number of sessions: 50

**Comment by joeyparrish** [comment]
I think that will be an issue for Chrome and/or Widevine.  The player in JavaScript has no control over decoder resources or limitations.

**Comment by joeyparrish** [comment]
Try: https://widevine.com/contact
Or: https://bugs.chromium.org/
