### ISSUE TITLE
Shaka Player in GTK built Application

### ISSUE THREAD

**Issue by jbsupport** [shaka-project/shaka-player#4863]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
4.3.2

**Please ask your question**
Can Shaka-Player be integrated in an application built using GTK? I am unable to find any references to this. If it is possible, could you please point me to any resources?

**Comment by joeyparrish** [comment]
Shaka Player is purely web-based.  So you should be able to run Shaka Player inside a web browser context in your GTK application (something like the WebView components available in Android and iOS native apps).  I don't know enough about GTK to recommend a specific component, so your web search is as good as mine.

Does this help?

**Comment by jbsupport** [comment]
Thank you for the reply. My team needs to try a few methods and see what works.
