### ISSUE TITLE
Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp2t; codecs="avc1.42E01E,mp4a.40.2"')

### ISSUE THREAD

**Issue by RyanSacks** [shaka-project/shaka-player#4864]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
We're using 2 files from the cloudflare CDN.

<script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.3.2/shaka-player.ui.min.js" integrity="sha512-My7HWrSUstOQITHXr1qanNoXCEb8aJweepK7Hj+mQegYmzGNKjNa37t6ldDbAXHT4FmLdGV2sq/rgFXuaIdwyQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.3.2/controls.min.css" integrity="sha512-6CAOpe+kF1fCTzRcZlS1iak5PY3M5lT+Ato5R3GJ0GXtoRTY6UOyGUNNG1va+mws+XDs1w3a6+iXQtw6n/Ef+w==" crossorigin="anonymous" referrerpolicy="no-referrer" />    

**Are you using the demo app or your own custom app?**
Our own custom app.

**If custom app, can you reproduce the issue using our demo app?**
No, the stream works on the Demo, but not on our custom app and we're not sure why.

**What browser and OS are you using?**
Chrome Version 108.0.5359.124 (Official Build) (x86_64)
MacOS Mojave Version 10.14.6 (18G9323)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
We're not using this.

**What are the manifest and license server URIs?**

For security reasons, available upon request via email, and since this is during a live streaming, we need to live stream to issue a new URI.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

I'm not sure at the moment.

**What did you do?**

We added the HTML, CSS and Javascript from this page:
https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html
The player works with mp4 and Dash files, but not an HLS .m3u8 file for some strange reason, which is what we use, we use NGINX-RTMP and HLS.

**What did you expect to happen?**
The player should play our video when we Broadcast LIVE using a tool like OBS to create Broadcast Live videos.

**What actually happened?**

The video doesn't play and we get this error in the console.
Error code 9 object DOMException: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp2t; codecs="avc1.42E01E,mp4a.40.2"') is unsupported.

**Comment by danlaquarium** [comment]
We found that it required mux.js to unlock support for MPEG-TS when used by NGINX/RTMP

Link to the specs for Shaka Player mentioning MPEG-TS support required
https://www.npmjs.com/package/shaka-player#:~:text=supported%20in%20HLS-,MPEG%2D2%20TS,find%20and%20parse%20timestamps%20to%20find%20segment%20start%20time%20in%20HLS,-WebVTT

Link to mux.js file
https://github.com/videojs/mux.js/releases

**Comment by joeyparrish** [comment]
Yes, that's right.  mux.js is required for TS content on most browsers/devices.
