### ISSUE TITLE
Google Analytics 4 Integration with Shaka player

### ISSUE THREAD

**Issue by nalin2023** [shaka-project/shaka-player#4865]
I would like to know how to connect and track Shaka player events with google Analytics.

We are currently using the latest version of Shaka player.

Thanks

**Comment by joeyparrish** [comment]
This is more a question about Google Analytics than it is about Shaka Player.  I don't know anything about Google Analytics, but if you need help getting specific events or other data from the player to track, I can help with that.

**Comment by nalin2023** [comment]
Hey @joeyparrish Thanks for the response. Can you suggest me how to track events from the shaka player like Start, pause, End of video playback?

Thanks

**Comment by joeyparrish** [comment]
Those three specifically are events from the HTML video element.

Media events in general: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement#events

Ended event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/ended_event

Pause event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause_event

Play and playing events are subtly different, so read carefully to choose which one you want:
 - https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play_event
 - https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playing_event

**Comment by nalin2023** [comment]
Thanks you so much for answering my queries.
