### ISSUE TITLE
Dynamic Multi Period Dash TimeLine Problem 

### ISSUE THREAD

**Issue by m0hamedessam** [shaka-project/shaka-player#4875]
I  2 questions about Multi Period Dash how to get current period from multi period

For example :- 
```
  <Period duration="PT394.04S" id="2405" start="PT1673258997.04S">
 <Period duration="PT15.0S" id="2405_1073741858_6" start="PT1673259457.56S">
 <Period id="2405_1073741858_7" start="PT1673259472.56S">

```
is it (NOW(time) - Period start) < Period Duration) ? because some times its not working like that formula

Second question how get current segment number from timeline

For example :-
AUDIO: 
```
      <SegmentTemplate initialization="D-$RepresentationID$.dash" media="D-$RepresentationID$-$Time$.dash" presentationTimeOffset="80292708174720" timescale="48000">
        <SegmentTimeline>
          <S d="184320" r="31" t="80292721037311" />
          <S d="178176" />
          </SegmentTimeline>
      </SegmentTemplate> 
```
VIDEO:
```
      <SegmentTemplate initialization="D-$RepresentationID$.dash" media="D-$RepresentationID$-$Time$.dash" presentationTimeOffset="1003658852184" timescale="600">
        <SegmentTimeline>
          <S d="2304" r="32" t="1003659011328" />
          <S d="1560" />
          </SegmentTimeline>

```

You can see **r** on video template is higher than audio so video segments are more than audio if we assume t value is start time always sounds out sync and i cant really match them so how to get right current video and audio number regardless segments index number

**Comment by joeyparrish** [comment]
Shaka Player v3 and v4 do not offer any way to get the current period.  Starting with v3 and up to today, we "flatten" DASH periods so that at the level of our internal structures, there is no period.

I think Shaka Player may not be designed for what you want.  Sorry!

**Comment by m0hamedessam** [comment]
So Shaka player doesn’t support dynamic live multi period streams ?

**Comment by joeyparrish** [comment]
Shaka Player _does_ support dynamic, live, multi-Period streams.  It just doesn't expose the information you seem to be asking for (current period, current segment number).  Those are internal details of the manifest format that are transformed in the loading process, and not preserved for the application's use.

**Comment by m0hamedessam** [comment]
I just want to know calculation formula to get current live period and current live segment number so please explain if you know hows it works.

**Comment by joeyparrish** [comment]
Do you want to know how Periods and timestamps work in DASH in general, or how things work inside Shaka Player?

There isn't a formula for timestamp to segment number, unless your segments are identical in duration.  That is not a requirement of DASH.  So in the general case, you can't do that without a detailed map.

As for Shaka, you can browse the source code if you want to see how things are calculated.  There's a lot of it, but DASH is scoped to lib/dash/.

If you want to get runtime info from the player, you could dig into Shaka's internal manifest structure.  We make no guarantees that we won't change it, and it's not officially part of the stable API.  But you can get into the Stream structures, and from there into the SegmentIndex structures, and from there into SegmentReferences.  You can iterate through, examine start and end timestamps of segments, and use that information to get what you want on segment numbers.  The timestamps in SegmentReference are the same timeline as video.currentTime (the presentation timeline).

You can check for changes in initSegmentReference from one segment to the next.  If the init segment changes, that generally indicates a period transition.  However, if the segments are "self-initializing", initSegmentReference will always be null, and you won't be able to use that to deduce period transitions.

I hope that's helpful.  Enjoy Shaka!
