### ISSUE TITLE
SMPTE-TT Teletext subtitles are overlapping and showing in a different position

### ISSUE THREAD

**Issue by balajic7** [shaka-project/shaka-player#4876]
SMPTE-TT Teletext subtitles are overlapping and showing in a different position.
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What link can we use to reproduce this?**

**What version of Shaka Player are you using?**
v4.3.2-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

**What did you do?**

Play SMPTE-TT Teletext subtitle content.

**What did you expect to happen?**
The text should not overlap.

**What actually happened?**

I suspect the shaka player is unable to handle multiple region with different origin and extent values
[sample_smpte-tt.txt](https://github.com/shaka-project/shaka-player/files/10379622/sample_smpte-tt.txt)

![shaka_text_overlap](https://user-images.githubusercontent.com/112380887/211479038-523f97c8-88e4-4d62-993c-e2d984244199.png)

**Comment by avelad** [comment]
I have tried 4.8.1 and there is no overlap. Can you confirm that the issue is resolved? Thanks!
