### ISSUE TITLE
Shaka Error MEDIA.VIDEO_ERROR (4,,CHUNK_DEMUXER_ERROR_APPEND_FAILED: Initialization segment misses expected aac track.)

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4877]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-IN;textlang=en-IN;uilang=en-IN;asset=https://private7-stream-ovp.vide.io/dl/80cd3989c62aa4ab72b4a8e9e288a38c/63bc2d15/demoovp_3574752/videos/hls/90/43/S569043/V619267/playlist.m3u8?v=2;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.3.2-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

**What did you do?**

Try to play the HLS stream VOD

**What did you expect to happen?**
To play the stream without an audio track

**What actually happened?**

I tried to play the stream but it gave me an error of [Shaka Error MEDIA.VIDEO_ERROR (4,,CHUNK_DEMUXER_ERROR_APPEND_FAILED: Initialization segment misses expected aac track.)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3016)

Maybe the codec is not supported or the player cannot play the stream without an ACC track?

![shaka-error](https://user-images.githubusercontent.com/59652404/211508960-b1f4d205-5ae2-4cd2-aa68-8002c63bd684.png)

**Comment by avelad** [comment]
Can you try the main branch and see if it still happens? Thanks!
