### ISSUE TITLE
Failed to set 'currentTIme' property on 'HTMLMediaElement' on an older Hisense TV

### ISSUE THREAD

**Issue by subhanahmed047** [shaka-project/shaka-player#4888]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 53 (Linux armv7l)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Model: HISENSE MT5658 (2017) 
Firmware: HA43A6501UWT

**What are the manifest and license server URIs?**
It doesn't matter, you can use any manifest.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
You can use any. 

**What did you do?**
Just play a video.

**What did you expect to happen?**
I expected the video to play. 

**What actually happened?**
I get the following error:
`Failed to set 'currentTIme' property on 'HTMLMediaElement'`

I noticed that other libraries such as dash.js also had to see a [similar issue](https://github.com/Dash-Industry-Forum/dash.js/issues/1845) at one point. 

Upon investigation, I found that this Is where the error originates from -> https://github.com/shaka-project/shaka-player/blob/main/lib/media/video_wrapper.js#L145-L148

The `currentTime` in this instance comes up as `NaN`, which means we pass down NaN as current Time and chrome 53 doesn't not like that. 
I was able to fix this by checking for NaN explicitly and then passing startTime instead if it is NaN.
The following code should fix it:
```
const moveToTime = (!this.video_.currentTime || this.video_.currentTime === 0) ? startTime : this.video_.currentTime;
this.mover_.moveTo(moveToTime);
```
 But I'm not sure if this NaN is intentional, and if it would impact other scenarios if we simply change it to startTime (which is 0 in this instance) like this.

**Comment by joeyparrish** [comment]
No, NaN is not intentional.  Does this value turn into NaN on any desktop browsers?  If so, it will be relatively easy to debug.

**Comment by joeyparrish** [comment]
If the issue can't be reproduced on a desktop browser, we will have to rely on you to trace the origin of that value and figure out the fix.  We don't have a Hisense TV in our lab at Google, and we can't debug on the platform, so it is up to the community to support those devices.

**Comment by avelad** [comment]
Today I was able to reproduce the bug on a Hisense TV, but not on WebOS or Tizen. I have also verified that your fix works.
