### ISSUE TITLE
Can not open subtitles on hls

### ISSUE THREAD

**Issue by cuyl** [shaka-project/shaka-player#4889]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
No

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome 109.0.5414.87 macOS 13.1 (22C65)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

1. Open https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/apple-advanced-stream-ts/master.m3u8;panel=ALL_CONTENT;panelData=HLS,MP2TS;build=uncompiled
2. Select a subtitles

**What actually happened?**

<img width="945" alt="Screenshot 2023-01-13 at 2 12 27 AM" src="https://user-images.githubusercontent.com/9765936/212221288-15e6de49-3165-4ffe-addb-7f319d488298.png">
the following error throws, and subtitles not working.

> Cannot read properties of undefined (reading 'push')

**What did you expect to happen?**
not to throw

**Comment by cuyl** [comment]
[v4.3.2](https://github.com/shaka-project/shaka-player/releases/tag/v4.3.2)  ❌ 
[v4.3.1](https://github.com/shaka-project/shaka-player/releases/tag/v4.3.1)  ✅
[v4.2.6](https://github.com/shaka-project/shaka-player/releases/tag/v4.2.6)  ❌ 
[v4.2.5](https://github.com/shaka-project/shaka-player/releases/tag/v4.2.5)  ✅

**Comment by cuyl** [comment]
the bug is introduce by https://github.com/shaka-project/shaka-player/pull/4824

**Comment by avelad** [comment]
@joeyparrish can you review it?

**Comment by avelad** [comment]
It seems that it broken for all HLS content.

https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8;panel=ALL_CONTENT;panelData=HLS,MP4;build=uncompiled

**Comment by joeyparrish** [comment]
Acknowledged.  I'll work on it today, and delay release plans until this is fixed.

**Comment by joeyparrish** [comment]
The fix will be in v4.3.3 and v4.2.7.
