### ISSUE TITLE
Received net::ERR_INSUFFICIENT_RESOURCES for extremely large videos

### ISSUE THREAD

**Issue by benbenmotor** [shaka-project/shaka-player#4898]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Testing with 4.3.0, custom app is on 3.2.1 and shows the same issue.

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Haven't tried due to limited local resources, everything is currently cloud-hosted.

**What browser and OS are you using?**
Chrome 108, Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/a

**What are the manifest and license server URIs?**

Included in email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Included in email

**What did you do?**

Load manifest with large number of periods (2800+) for a 99+ GB video and watched the shaka player make 10,000+ network calls to get all the video/audio files, Chrome fails with net::ERR_INSUFFICIENT_RESOURCES due to the number of requests.

**What did you expect to happen?**
Only a few requests are created to start buffering and play the video.

**What actually happened?**

![image](https://user-images.githubusercontent.com/106129854/212416696-2f06711b-4fd8-465f-beaf-8b40ab04738d.png)

**Comment by joeyparrish** [comment]
The link you sent in your email results in a 404 for me.  Is it a private repo?

Does your manifest use SegmentBase?  SegmentBase requires a `sidx` box be fetched for each stream in each period, in order to parse and extract the map of segments to times.  That's the only reason I can think of that the player would make so many requests upfront.

**Comment by benbenmotor** [comment]
Made the repo public. Sorry about that.

Yes we are using SegmentBase and no we don't have a sidx box. I'll work on
adding that into our manifest and do some testing on it this coming week.
Thanks for the suggestion!



On Fri, Jan 13, 2023 at 4:15 PM Joey Parrish ***@***.***>
wrote:

> The link you sent in your email results in a 404 for me. Is it a private
> repo?
>
> Does your manifest use SegmentBase? SegmentBase requires a sidx box be
> fetched for each stream in each period, in order to parse and extract the
> map of segments to times. That's the only reason I can think of that the
> player would make so many requests upfront.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_shaka-2Dproject_shaka-2Dplayer_issues_4898-23issuecomment-2D1382454257&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_C93KOmcBXCBnhee2v6PYlc&r=cgXd8uaOlrKEWmJRXcSjH_olE3RbyOM34truA6p5Ru8-HfnXx7M-TWM1BmkcR2FM&m=KuUt4ehaUrBzn-mDhk49cQ5vhII6x2Pptq9A2mb7eXuaGZOLta-lXSn0URPB_aXm&s=HmdXCPpc8_M2uGegsum2j-54o2TD4Q81GsYsjPq7hPY&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZJWTPWBK54AG6LZ6QIOIPTWSHHXPANCNFSM6AAAAAAT22BIYY&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_C93KOmcBXCBnhee2v6PYlc&r=cgXd8uaOlrKEWmJRXcSjH_olE3RbyOM34truA6p5Ru8-HfnXx7M-TWM1BmkcR2FM&m=KuUt4ehaUrBzn-mDhk49cQ5vhII6x2Pptq9A2mb7eXuaGZOLta-lXSn0URPB_aXm&s=wB4iMSuzLrwGVGvuYyNwsKd8wJRQ3x5xkB5jR8dARYU&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

-- 


*For more information on how and why we collect your personal 
information, please visit our Privacy Policy 
<https://www.motorolasolutions.com/en_us/about/privacy-policy.html?elqTrackId=8980d888905940e39a2613a7a3dcb0a7&elqaid=2786&elqat=2#privacystatement>.*

**Comment by benbenmotor** [comment]
We follow this structure as shown in Example 3 of 
https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#addressing-indexed

Not sure what we could be missing for this that is not in our manifest file.

**Comment by benbenmotor** [comment]
If I understand correctly what you were saying, we have 2800 periods, each with a representation containing a BaseURL and a SegmentBase. We will have to make 2800 requests up front to create the map of segments to time?

**Comment by joeyparrish** [comment]
That's correct.  Using SegmentBase delegates all index information from the manifest to the actual streams, so we need to make 2800 requests (minimum) to build a segment index of 2800 periods.

If you can generate a DASH manifest with the necessary segment index information, we would not have to make any additional requests.  For example, SegmentTemplate+duration, SegmentTemplate+SegmentTimeline, or SegmentList+SegmentTimeline would all be styles of DASH manifest that include the necessary information upfront.
