### ISSUE TITLE
Safari Fairplay: null is not an object (evaluating 'n.g.initData')

### ISSUE THREAD

**Issue by martinstark** [shaka-project/shaka-player#4902]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.X

**Can you reproduce the issue with our latest release version?**
Presumably, need huge volumes of plays to see issue, and cannot take 4.3.X to prod.

**Can you reproduce the issue with the latest code from `main`?**
n/a

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Safari, Mac OS

**What did you do?**
Check our playback error metrics, and noticed unhandled errors thrown inside of Shaka. The errors are rare, in the magnitude of a handful per thousands of plays.

useNativeHlsOnSafari: true

Play Fairplay DRM streams

**What did you expect to happen?**
Shaka plays the stream, or throws a Shaka Error.

**What actually happened?**

Shaka crashes with a native ReferenceError `null is not an object (evaluating 'n.g.initData')`

Note: The issue is probably in our streams, but Shaka probably shouldn't crash with a ReferenceError when it happens.

**Comment by joeyparrish** [comment]
I don't doubt your data on this, but it's not enough for us to debug the issue. If you have a way to reliably reproduce the issue in the future, please let us know.

**Comment by martinstark** [comment]
I did some quick digging, and the only instance of `\w+\.\w+\.initData[.(/ :;]` being accessed without a guard/null check is here:

https://github.com/shaka-project/shaka-player/blob/eeb647cec5dc4e34ab4e34f917a460f8b8858473/lib/media/drm_engine.js#L483

There are two places where `currentDrmInfo_` is asynchronously assigned `null` in the same file, so in theory I think a race condition could occur where a call to `attach` is queued after `currentDrmInfo_` has been set to null? I didn't do that much digging, but line 483 in drm_engine.js stood out.

**Comment by joeyparrish** [comment]
A PR would be welcome, even without solid repro.  It would be really great if you could come up with a unit test that reproduces the condition, though.  With other components and browser APIs mocked out, it is often feasible to control the timing of things that are normally asynchronous, and to reproduce unlikely race conditions.

**Comment by martinstark** [comment]
This issue just increased by several magnitudes in our error tracking systems, from once or twice every other day to dozens per day. My thought is that it's hiding a deeper DRM/content problem (on our side). I'll be looking more at it and put up a PR for discussion.
