### ISSUE TITLE
Failed to execute 'addSourceBuffer' on 'MediaSource': The MediaSource's readyState is not 'open'.

### ISSUE THREAD

**Issue by martinstark** [shaka-project/shaka-player#4903]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.6

**Can you reproduce the issue with our latest release version?**
Presumably, need huge volumes of plays to see issue, and cannot take 4.3.X to prod.

**Can you reproduce the issue with the latest code from `main`?**
n/a

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Chrome, Edge (notably not on Firefox)

**What did you do?**
Check our playback error metrics, and noticed unhandled errors thrown inside of Shaka. The errors are rare, in the magnitude of a handful per (tens of) thousands of plays.

Play a stream

**What did you expect to happen?**
Shaka plays the stream, or throws a Shaka Error.

**What actually happened?**

Shaka crashes with a native ReferenceError `Failed to execute 'addSourceBuffer' on 'MediaSource': The MediaSource's readyState is not 'open'.`

**Comment by joeyparrish** [comment]
I don't doubt your data on this, but it's not enough for us to debug the issue.  If you have a way to reliably reproduce the issue in the future, please let us know.

**Comment by martinstark** [comment]
There is only a single place where `.addSourceBuffer` is accessed in the Shaka source code:

https://github.com/shaka-project/shaka-player/blob/eeb647cec5dc4e34ab4e34f917a460f8b8858473/lib/media/media_source_engine.js#L380

Given the preceding `await this.mediaSourceOpen_;`, which is hooked directly to the `sourceopen` event, it looks like it should be impossible for the error to occur. However, given that this _must_ be the place where it happens, maybe there is a bug in Chromium where the `readyState` has not (yet) been set properly when the `sourceopen` event triggers.

Would it be worth checking for `readyState === 'open'` as part of the `sourceopen` listener to potentially catch and convert the error, instead of crashing with an native error?

**Comment by joeyparrish** [comment]
I would welcome a PR, even without solid repro.

It's hard for me to suggest the right kind of error to emit, though, because I don't understand the circumstances that would cause readyState to be closed right away after awaiting the promise to open it.

Did playback get cancelled for this to happen?  If so, `this.destroyer_.ensureNotDestroyed();` should handle it correctly AFAICT.  If the root cause is something else, then we may need special handling of it.

**Comment by martinstark** [comment]
>  I don't understand the circumstances that would cause readyState to be closed right away after awaiting the promise to open it

I'll need to look deeper at the code, but in theory that promise could have resolved long before init gets called, it's not necessarily awaiting the opening, unless init is called synchronously after the call to open() the media source.

**Comment by avelad** [comment]
@martinstark Do you think you will be able to send a PR for this?

**Comment by martinstark** [comment]
@avelad a simple one to guard against the erroneous call, yes, but I don't think I'll find time to dig out the root cause. Is that good enough? If not I'm happy to close the ticket until I can spend more time on it.

**Comment by avelad** [comment]
@martinstark I agree to include the guard and see if it doesn't happen in the future. Please send the PR. :)
