### ISSUE TITLE
How to imitate shaka control's show/hide behavior for custom overlay/control elements

### ISSUE THREAD

**Issue by debjits1** [shaka-project/shaka-player#4905]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.0

**Please ask your question**
I have few buttons placed as an overlay on top of player. They are rendered as below
```
<div data-shaka-player-container>
  <button my-custom-react-button></button>
  <div class="shaka-controls-container">
  </div>
</div>
```
I have tried toggling the button using css sibling selectors, but that doesn't seem to work.
I want my button to follow exact behavior to be visible/hidden. Can anyone help me here?

**Comment by joeyparrish** [comment]
I think you might be better served by creating a Shaka UI plugin for your custom button.  Please check out the section titled "Creating custom elements and adding them to the UI" in our ["Customizing the UI" tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html).

That way, when the control panel is hidden, so is your custom button as a child of it.

**Comment by debjits1** [comment]
Thanks for the reply @joeyparrish . The component I am trying add here is a React Component. Can I register React Components in this way as mentioned in ["Customizing the UI" tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html). ?

**Comment by joeyparrish** [comment]
I don't know much about React.  If you can instantiate your react component from within our plugin framework, it should be fine.

The components of a UI plugin are:

1. An element class that extends our base class (this is your plugin)
2. In the class constructor, create DOM elements, listen to events (using React if you want)
3. A factory that creates an instance of the element (here you can inject outside or global data at runtime)
4. Register the plugin with a name and the factory
5. Configure the UI to enable your plugin (`video.ui.configure()`)

Does this help?
