### ISSUE TITLE
MANIFEST.HLS_KEYFORMATS_NOT_SUPPORTED for azure media service

### ISSUE THREAD

**Issue by sudonghan** [shaka-project/shaka-player#4910]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
3.3.2

**Please ask your question**
Hello team,
I am using Azure media service and I want to build Shaka player for Fairplay encryption.
I have the certificate, streaming url(m3u8-cmaf) and token.
For the code I have also added the token before the reqeust is sent and add the server certificate.
But I am getting the error message below:
12:51:49.76 [ERROR] Load Manifest Error: shaka.util.Error { "severity": 2, "category": 4, "code": 4026, "data": [], "handled": false, "message": "Shaka Error MANIFEST.HLS_KEYFORMATS_NOT_SUPPORTED ()", "stack": "Error: Shaka Error MANIFEST.HLS_KEYFORMATS_NOT_SUPPORTED ()\n at new shaka.util.Error (https://cdn.jsdelivr.net/npm/shaka-player@3.3.2/dist/shaka-player.ui.debug.js:181:811)\n at $jscomp.generator.Engine_.program_ (https://cdn.jsdelivr.net/npm/shaka-player@3.3.2/dist/shaka-player.ui.debug.js:1618:333)\n at $jscomp.generator.Engine_.nextStep_ (https://cdn.jsdelivr.net/npm/shaka-player@3.3.2/dist/shaka-player.ui.debug.js:37:105)\n at $jscomp.generator.Engine_.next_ (https://cdn.jsdelivr.net/npm/shaka-player@3.3.2/dist/shaka-player.ui.debug.js:33:234)\n at $jscomp.generator.Generator_.next (https://cdn.jsdelivr.net/npm/shaka-player@3.3.2/dist/shaka-player.ui.debug.js:38:73)\n at b (https://cdn.jsdelivr.net/npm/shaka-player@3.3.2/dist/shaka-player.ui.debug.js:39:73)" }

My code:
https://github.com/Azure-Samples/media-services-3rdparty-player-samples/blob/master/src/shaka/index.js

Could you please help me to further troubleshoot this issue in case I am missing anything? Thanks!

**Comment by avelad** [comment]
This seems a bug, please open a new issue with bug template and provide all fields. Thanks!
