### ISSUE TITLE
shaka.util.XmlUtils should forbid elements from MathML namespace

### ISSUE THREAD

**Issue by tosmolka** [shaka-project/shaka-player#4912]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.3

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome 109.0.5414.75

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
N/A

**What did you do?**
I used shaka.util.XmlUtils.parseXmlString to parse XML with sample XSS payload for MathML namespace and appended the output to DOM. I did this test as part of security review of Trusted Types policy `shaka-player#xml` before allowing it in our app. 

```javascript
document.body.append(shaka.util.XmlUtils.parseXmlString('<math xmlns="http://www.w3.org/1998/Math/MathML"><mi style="position:absolute;z-index:999;background:yellow;height:100px;width:100px;top:0;left:0;" onmousemove="alert(1)" onclick="alert(1)">CLICK ME</mi></math>', 'math'))
```

**What did you expect to happen?**
I expected an error, similar to what happens when attempting to parse elements from HTML or SVG namespace. 

**What actually happened?**
parseXmlString returned parsed elements and XSS payload was functional (on mouse hover or click) after appending to DOM:

![image](https://user-images.githubusercontent.com/37370256/213430262-20434359-5fb3-4fe0-936e-22343a5adb49.png)

**Comment by avelad** [comment]
@tosmolka are you interested on created a PR for it? You can add it in https://github.com/shaka-project/shaka-player/blob/main/lib/util/xml_utils.js#L395

**Comment by joeyparrish** [comment]
Feel free to add an exclusion to XmlUtils, but FYI, nothing parsed by XmlUtils is **ever** added to the DOM by Shaka Player.
