### ISSUE TITLE
VMAP ads won't play in Safari

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#4924]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**

4.3.3

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

Safari, macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Doesn't matter, https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd is good for an example

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

This happens also on custom demo app

**What did you do?**

Created custom demo player. 

Playlist: https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
Ad URL: https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/vmap_ad_samples&sz=640x480&cust_params=sample_ar%3Dpremidpost&ciu_szs=300x250&gdfp_req=1&ad_rule=1&output=vmap&unviewed_position_start=1&env=vp&impl=s&cmsid=496&vid=short_onecue&correlator= (VMAP Pre-, Mid-, and Post-rolls, Single Ads example from https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags )

**What did you expect to happen?**

Ads to play as defined in VMAP response

**What actually happened?**

Video plays without ads

**Comment by avelad** [comment]
@Andekas Can you test if the main branch also has the problem? Thanks!
