### ISSUE TITLE
Uncaught TypeErrors when switching subtitle tracks

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#4929]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
Latest (main)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Chrome, macOS

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
Playing HLS stream with two subtitle tracks, switching tracks causes uncaught TypeError

**What did you expect to happen?**
No errors

**What actually happened?**
Could it be that there's a typo in hls_parser.js https://github.com/shaka-project/shaka-player/blob/7fa40fdb483e155099d0141ee110ac1a791d88ae/lib/hls/hls_parser.js#L3370 ?

Changing this to `text/vtt` makes the TypeErrors go away

**Comment by martinstark** [comment]
There seems to be a deeper issue in `hls_parser.js` that causes one track to be assigned `text/vtt` and the second track to be assigned `text/vtt`, despite both having the same file extension. I haven't debugged it fully, but the PR provided by Fredrik fixes the issue by correcting the bad mime type.

**Comment by joeyparrish** [comment]
> it's confusing me why shaka would choose two different ones for near identical tracks.

We don't know the extension until we load the playlist, and since v4.3.0, we only load the playlists of tracks that we are streaming.

One instance was hard-coded, and the other used a lookup table that contained a typo.  Sorry for the trouble, and thanks for the fix!

**Comment by martinstark** [comment]
Workaround while waiting for a new shaka release:

```typescript
  shaka.text.TextEngine.registerParser(
    "txt/vtt",
    () => new shaka.text.VttTextParser()
  );
```
