### ISSUE TITLE
Shaka Error MANIFEST.RESTRICTIONS_CANNOT_BE_MET ([object Object])  

### ISSUE THREAD

**Issue by tmdnk** [shaka-project/shaka-player#4938]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.3 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Are you using the demo app or your own custom app?**
The Demo app.

**What browser and OS are you using?**
Chrome: Version 109.0.5414.120 (Official Build) (64-bit)
OS: Windows 10 Pro

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default.

**What did you do?**
I updated the dcsl file for my Widevine proxy sdk server. 
The creation time of old and new dcsl files are as bellow:
```
  prev_creation_time_seconds: 1658558280
  new_creation_time_seconds: 1674784397
```

**What did you expect to happen?**
The playback of contents which encrypted with one audio/video shared key could play with the new dcsl file.

**What actually happened?**

After I updated the dcsl file for my Widevine proxy sdk server.
The playback of contents which encrypted with one audio/video shared key failed.
But the playback of contents which encrypted with two separated audio/video keys works well.
The playback works with the old version dcsl file, but not the new one.
The problem is very similar as the issue I submitted before.
https://github.com/shaka-project/shaka-player/issues/4608

**Comment by avelad** [comment]
@tmdnk Please provide a stream to test it. Thanks!

**Comment by tmdnk** [comment]
@avelad Thank you for your reply. I have sent an email to 'shaka-player-issues@google.com' that has links can reproduce this issue just now.

**Comment by joeyparrish** [comment]
@tmdnk wrote:
> The playback of contents which encrypted with one audio/video shared key failed.
> But the playback of contents which encrypted with two separated audio/video keys works well.
> The problem is very similar as the issue I submitted before. https://github.com/shaka-project/shaka-player/issues/4608

In #4608, @joeyparrish wrote:
> For what it's worth, using the same key for video and audio makes it much easier for your content to be compromised. Audio paths are generally much less protected than video paths in a DRM implementation, and using the same key for both can allow someone (in some cases) to decrypt video using the audio path, without sending it through secure decoders.
>
> Widevine very explicitly warns against using the same key for audio and video.

@tmdnk wrote:
> The playback works with the old version dcsl file, but not the new one.

That sounds like a Widevine issue, not a Shaka Player issue.  We are not part of Widevine, and can't give you DCSL or license server support here.

Shaka Player is reacting to the feedback from the CDM, which tells us that we can't play this content with the license you retrieved from the server.  Here are the docs for that error message:

https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:4012

> There exist some streams that could be decoded, but restrictions imposed by the application or the key system prevent us from playing. This may happen under the following conditions:
> - The application has given restrictions to the Player that restrict at least one content type completely (e.g. no playable audio).
> - **The manifest specifies different keys than were given to us from the license server.**
> - **The key system has imposed output restrictions that cannot be met (such as HDCP) and there are no unrestricted alternatives.**

**Comment by joeyparrish** [comment]
I'm sorry that we can't do more for you on this.  I was informed internally that you also reached out to Widevine.  Please continue your support conversation with them.  Thanks!
