### ISSUE TITLE
How to only show the volume bar only on hover the volume icon?

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#4950]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.0.2

**Please ask your question**
This is my UI config:

`const config = {
  controlPanelElements: [
    'play_pause',
    'mute',
    'volume',
    'time_and_duration',
    'spacer',
    'fullscreen',
  ],
};
ui.configure(config)
`

With above config, the volume bar will bed displayed when I hover to video.
Please advise me is there a way to only display the volume bar only on hover the volume icon?
I mean that when I hover the video, only the volume icon displayed. Then when I hover volume icon, the volume bar will be displayed.
The volume bar is the one I circle in red in attached file.
![Screenshot_1](https://user-images.githubusercontent.com/70369658/215666828-a6415b9a-e83e-431b-bdaf-a594e0d5be97.png)

Thank you

**Comment by vanminhquangtri** [comment]
I ended up by manually edit css like below. Still hope that there's will be another way by modifying config instead of this manual way:

```
.shaka-volume-bar-container {
  opacity: 0;
  transition: all 0.5s;
  &:hover {
    opacity: 1;
  }
}

.shaka-mute-button {
  margin-right: 0;
  padding-right: 10px;
}

.shaka-mute-button:hover + .shaka-volume-bar-container {
  opacity: 1 !important;
}
```

**Comment by theodab** [comment]
We have no built-in way of doing this at the moment.

We could probably add a new element to the UI that consists of a mute button and volume bar that are bundled together and expand/contract based on mouse movement. I think that would probably be the best way of implementing this, compared to something like adding a new UI configuration value specifically for this behavior.

Anyway, I'll mark this as an enhancement request.

**Comment by vanminhquangtri** [comment]
@theodab many thanks for your response. So while waiting for your next update, I will edit css manually. Thanks

**Comment by joeyparrish** [comment]
@vanminhquangtri, we would also welcome a contribution of a new element.  Let us know if you want to do this, or if you need any guidance.  Thanks!
