### ISSUE TITLE
Default caption on load

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#4951]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v4.3.0

**Please ask your question**
I add 7 different external subtitles .vtt to the player using
```html
await this.player.addTextTrackAsync(subtitlesTrack.url, subtitlesTrack.language, 'subtitles', subtitlesTrack.mimeType);
```

What I want is for when the player loads it should have a default subtitle activated.

I have to manually go and select the subtitle.

Is there any way to do that?

I already tried the configurations mentioned below.
```html
preferredTextRole: 'en',
preferredTextLanguage: 'en'
```

**Comment by joeyparrish** [comment]
I believe that preferred* configs are applied to choose initial tracks, before you call addTextTrackAsync.  So you will have to select it yourself.  You can use the return value from addTextTrackAsync to call selectTextTrack, though, if I'm not mistaken.

**Comment by joeyparrish** [comment]
"On load", your additional tracks don't exist yet, so we can't use the preferences to choose them on load.

**Comment by hiren3897** [comment]
Okay, thanks for the guidelines,

After the player loads, I can try to `selectTextTrack` from `getTextTracks`? but it still doesn't work :(

**Comment by joeyparrish** [comment]
You also need to call setTextTrackVisibility(true).  Please don't change `track.active`.  That is informational, and active tracks are changed by selectTextTrack() only.

**Comment by hiren3897** [comment]
Thanks @joeyparrish 
the missing piece was `setTextTrackVisibility(true)`

It works.
:tada:
