### ISSUE TITLE
Live streams not working in Edge browser

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#4955]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

Latest

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Can be reproduced in Demo page (using Shaka Player History live stream, both HLS and Dash)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Open live stream in Edge browser

**What did you expect to happen?**

Live stream to play

**What actually happened?**

Live stream plays only first chunk, then stops and keeps loading.

**Comment by avelad** [comment]
See https://github.com/shaka-project/shaka-player/issues/4467#issuecomment-1410739329

**Comment by Andekas** [comment]
@avelad This seems to be unrelated. I tested custom content with livestreams from https://ottverse.com/free-hls-m3u8-test-urls/

For example: 
Live Akamai m3u8
https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8


Works in Chrome, but Edge gives error: "Failed to set the 'timestampOffset' property on 'SourceBuffer': The timestamp offset may not be set while the SourceBuffer's append state is 'PARSING_MEDIA_SEGMENT'."

**Comment by avelad** [comment]
@joeyparrish can you review it? Thanks!

**Comment by joeyparrish** [comment]
I'm unable to reproduce the issue.

I'm using this link:

https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

On Edge 109.0.1518.78 on Linux.

**Comment by joeyparrish** [comment]
@avelad just pointed out to me that this only reproduces on Windows, due to Edge+Windows having native support for TS streams.  On Chrome or Linux, where they are unsupported, they get transmuxed to MP4 first.

Please try enabling the option `mediaSource.forceTransmux` for TS live streams and see if that helps:

```js
player.configure('mediaSource.forceTransmux', true);
```

If so, we could consider changing the default in a future release.

**Comment by Andekas** [comment]
@joeyparrish @avelad I can confirm that enabling forceTransmux resolves the issue. 

In your comment, the key was wrong - it should be streaming.forceTransmux (not mediaSource).
