### ISSUE TITLE
Tags in the webvtt subtitle are not parsed

### ISSUE THREAD

**Issue by Peterdoo** [shaka-project/shaka-player#4956]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v4.3.4-uncompiled

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
Demo app shaka-player-demo.appspot.com

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome Version 109.0.5414.120 (Official Build) (64-bit) on Win11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Demo app shaka-player-demo.appspot.com

**What did you do?**

Played a HLS video with the following cue in the webvtt file:
10:00:00.000 --> 10:00:04.000 line:90%,end position:50% 
First line is &lt;u&gt;underlined &lt;/u&gt;and left positioned.
Second line is &lt;i&gt;italic &lt;/i&gt;&amp;amp; moved right.
Third line is right justified and unjustif.

**What did you expect to happen?**
The tags should have been parsed. The two words inside the spans should be displayed underlined or italic.

**What actually happened?**

Tags stayed unparsed. The tags were displayed as text instead of being parsed and using them for text formatting.

This is how it looks like:
![image](https://user-images.githubusercontent.com/33329671/216404198-d41640e3-558e-4507-836e-bf06610f60e6.png)

**Comment by avelad** [comment]
@Peterdoo I created https://github.com/shaka-project/shaka-player/pull/4960
