### ISSUE TITLE
Spacing between text lines when any styling present in the webvtt cue

### ISSUE THREAD

**Issue by Peterdoo** [shaka-project/shaka-player#4958]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v4.3.4-uncompiled

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
Demo app shaka-player-demo.appspot.com

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome Version 109.0.5414.120 (Official Build) (64-bit) on Win11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Demo app shaka-player-demo.appspot.com

**What did you do?**

Played a HLS video with the following cue in the webvtt file:
10:00:00.000 --> 10:00:04.000 line:90%,end position:10%,line-left align:start
&lt;u&gt;First line is underlined&lt;/u&gt; and left positioned.
&lt;i&gt;Second line is italic&lt;/i&gt; and left positioned.

**What did you expect to happen?**
The vertical line spacing between the two text lines should be the same as when there are no formatting tags present in the cue. There should be no additional transparent space between the text lines when any formatting tags are present.

**What actually happened?**

As soon as there is a formatting tag present in the cue like &lt;i&gt;, &lt;u&gt;, &lt;b&gt;, &lt;c.lime&gt; or similar, there is an additional line spacing between the text lines. There is a transparent space between the lines.

When there are no formatting tags present in the cue, the text lines are displayed without additional line spacing. The box is contiguous without a transparent space between the lines.

Without tags:
![image](https://user-images.githubusercontent.com/33329671/216415697-774fdbd9-ed53-475a-8b83-ba8bd2f24e41.png)

When any tag is present in the cue (additional transparent space between the lines);
![image](https://user-images.githubusercontent.com/33329671/216416241-8dfa0d30-b5cd-4d4c-8527-eca8388f4d18.png)

**Comment by avelad** [comment]
@Peterdoo I created https://github.com/shaka-project/shaka-player/pull/4961
