### ISSUE TITLE
Quality Levels Selection for Non-native HLS Safari

### ISSUE THREAD

**Issue by marcosthejew** [shaka-project/shaka-player#4959]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes
**What version of Shaka Player are you using?**
4.3.3
**Please ask your question**
Hello! I am trying to instantiate Shaka in Safari (MacOS) and have the ability to select between quality levels.

For this, I'm supplying CMAF-encrypted HLS sources, and using: 
`player.configure(
                                drm: {
                                                servers: {
                                                    "com.apple.fps": serverurl,
                                                },
                                                advanced: {
                                                    "com.apple.fps": {
                                                    serverCertificate: cert,
                                                    }
                                                }
                                         },
                              streaming: {
                                              useNativeHlsOnSafari: false,
                                          },`

As well as running:
`shaka.polyfill.PatchedMediaKeysApple.uninstall(); ` on instantiation.

Yet I get this on the player:
<img width="181" alt="image" src="https://user-images.githubusercontent.com/1500967/216428794-f405ace3-5399-4104-92b8-04d95a8d7c1d.png">

Does someone have any advice on which other settings should I tweak to get this working?
Thanks.

**Comment by theodab** [comment]
"nullp"... That suggests that the height of the video stream is `null`. The resolution selector should probably have special text for that case, I suppose.

If you call `player.getManifest().variants[0].video` what do you see? Does the video stream have a width and height?
Does your master playlist have a `RESOLUTION` attribute on the `#EXT-X-STREAM-INF` tags?

As for there only being one track listed... how many variants are in the `player.getManifest().variants` array? It could be that all but one of your variants are getting filtered away, for example; it'd be hard to tell what the exact cause is without examining your content, though.
