### ISSUE TITLE
Offload reducing from main thread for low end/memory constrained devices

### ISSUE THREAD

**Issue by OrenMe** [shaka-project/shaka-player#4965]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

When embedding shaka on smart TVs from 2017-2019 from both LG and Samsung inside a high demanding UX/UI app built with modern frameworks(React) there is a clear pattern of memory usage where shaka and app may use more than the very limited memory.
This often leads to UI issues on the app.
We can see that moving to native player of the platform solves the issue but this is not a good solution as it causes reduced capabilities such as track management, drm and more.
Basically moving to native reduces the load on the JS thread of the app.
There are many potential solutions but one in particular that creates issues is manifest parsing of live stream when manifest is very big - in our case it is live with 1 hour or more of dvr where the encoding of the audio has fluctuations so even though a template is used it still generates a huge manifest that is being loaded and parsed every few seconds which causes high memory peaks cause the manifest is parsed into an xml of thousands of nodes every couple of sec.

**Describe the solution you'd like**

One solution I've been wondering if can help is to move parsing into a worker and passing the serialized manifest to main thread.
This is a big unknown cause the json parsing itself from worker to main thread might cause also a lot of memory allocation but this is here on the table as something to discuss

**Describe alternatives you've considered**

* Shortening the dvr so manifest gets smaller - not always an option 
* fixing the encoding so audio samples are the same - not easy as we don't always have control of origin encoder

**Additional context**

**Comment by avelad** [comment]
@OrenMe are you using DASH or HLS?

**Comment by OrenMe** [comment]
Using dash

**Comment by OrenMe** [comment]
Hi @avelad @joeyparrish any thoughts on this?

**Comment by OrenMe** [comment]
I'll add more context, maybe we will spot another issue.
What we are observing is that memory is retained for long duration and adds up between manifest updates and parsing and eventually both nodes created from parsing big manifests and the heap grow so much that GC cycle is forced and it is a long one and it causes stutters in UI, when u pair this with react that batches and also updates DOM and manages native events it causes the user interaction to be buggy and doesn't allow react to render on time or for system events to not get dispatched on time(think user clicking dpad control and interaction is delayed)

**Comment by OrenMe** [comment]
Hi @avelad any chance to get traction on this? I've been reading a bit on alternative ways to parse XML such as https://github.com/NaturalIntelligence/fast-xml-parser
TBH not sure what will be the impact of passing large serialised strings from worker to main thread and parsing them again to JS object but the removal of impact of the created XML nodes should have an impact.
Can ew maybe consider having this as an option to pass an external serializer and have it run in a worker?

**Comment by avelad** [comment]
@OrenMe In recent months many performance improvements have been made for DASH, can you check if the problem still exists in the main branch? Thanks!

**Comment by OrenMe** [comment]
Hi @avelad would be happy to.
Can you maybe help and specify which changes? Just for curiosity 
In any case I will also update that what we have discovered is that there is a real memory leak in LG on webos4-5, I don't know if it is also in shaka issues but we got confirmation from LG team and there is no fix for that.
Issue will happen with any MSE based player and is due to issue when calling createObjectURL

But in any case having less memory pressure on low memory devices is still good and will reflect on overall performance so we will definitely check

**Comment by avelad** [comment]
For example: https://github.com/shaka-project/shaka-player/pull/5061
And those defined here: https://github.com/shaka-project/shaka-player/pull/5729
