### ISSUE TITLE
Native HLS streaming w/ Fairplay fails in Safari iOS 16+ but works in Safari iOS 15.6.1 at least

### ISSUE THREAD

**Issue by loicraux** [shaka-project/shaka-player#4967]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. The issue #4890 might be related, but I'm not sure since it is about live streams and w/o using native `src=` playback ? ...

**What version of Shaka Player are you using?**
Latest version 4.3.4

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both.

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Safari iOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
[URI in demo app to reproduce](https://shaka-player-demo.appspot.com/demo/#audiolang=fr-fr;textlang=fr-fr;uilang=fr-fr;asset=https://educartestreams.lab.arte.tv/origin/HLS_180773_0-VOF-fairplay.ism/stream.m3u8;license=https://fps.ezdrm.com/api/licenses/70b025b0-a1a0-4623-b834-b2c25d9b0eff?contentId=HLS_180773_0-VOF&deviceId=342d9ab94f766b1c730ae7e7b10cf63a&playerName=artevod-web-player&playerVersion=2.3.0&requestUuid=dbf43cda-ea53-4705-abd6-f1588806ddad&username=eduthequepreprod_openbar;certificate=https://vodstorage.arte.tv/fairplay.cer;panel=CUSTOM%20CONTENT;build=uncompiled)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Nothing special, `useNativeHlsOnSafari` is left at its default value (`true`)
Apple FairPlay key system used is `'com.apple.fps'`;

**What did you do?**
Play the video

**What did you expect to happen?**
Video playback works

**What actually happened?**
Video playback doesn't work in the latest Safari iOS 16.3 but works in Safari iOS 15.6.1 at least.

Notes : 
- Native src= playback is used (`useNativeHlsOnSafari` is set to `true`)
- Everything works ok in MacOS Safari

I guess the problem is on Apple's FairPlay side, but I can't find relevant info on Apple Dev Forums...

**Comment by avelad** [comment]
Can you use 'com.apple.fps.1_0' and see if it works? Also see https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html

**Comment by loicraux** [comment]
> Can you use 'com.apple.fps.1_0' and see if it works? Also see https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html

I can give it a try (2 integrations of EZDRM with legacy Apple Media Keys & Modern EME under a flag...) but I recall that after shaka-player update from 3.2.9 to 4.1.2, video playback got broken with Fairplay in Safari MacOS v15.5.

I fixed it by using key system com.apple.fps instead of com.apple.fps.1_0 ... 🤔 

See https://github.com/shaka-project/shaka-player/issues/4349#issuecomment-1205133118

**Comment by loicraux** [comment]
I managed to make FPS w/ latest shaka player work in iOS 15.x Safari, iOS 16.x Safari & MacOS Safaris, but with com.apple.fps.1_0 key system only.
With modern EME (com.apple.fps), it still doesn't work with iOS 16.x safari. Since it works in iOS 15.x safari, I think there is still an issue on Apple side...

**Comment by Robloche** [comment]
I have a similar issue, here.
Here are the results of my playing Fairplay-encrypted content:
✔️ macOS 12 Safari 15
✔️ iPadOS 15 Safari
❌ iOS 16 Safari

And when it fails, it does not throw any error.

**Comment by sandeep0402** [comment]
Any solution found for this problem? We are also facing this problem

**Comment by Robloche** [comment]
> Any solution found for this problem? We are also facing this problem

It's a technical (and commercial) choice made by Apple. It's bothering everyone but Apple doesn't seem to be inclined to change it.
