### ISSUE TITLE
Surrounding spaces are trimmed from TTML inline text spans

### ISSUE THREAD

**Issue by simontsang** [shaka-project/shaka-player#4974]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.2.2, 4.3.4

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Both

**If custom app, can you reproduce the issue using our demo app?**

Yes

**What browser and OS are you using?**

macOS 12.6.2+ Chrome 109

**What are the manifest and license server URIs?**

Will send via email.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

<details>
  <summary> Default configuration, other than enabling default subtitles via the `preferredTextLanguage` setting. </summary>

  ```javascript
{
    "drm": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "servers": {},
        "clearKeys": {},
        "advanced": {},
        "delayLicenseRequestUntilPlayed": false,
        "logLicenseExchange": false,
        "updateExpirationTime": 1,
        "preferredKeySystems": [],
        "keySystemsMapping": {},
        "parseInbandPsshEnabled": false,
        "minHdcpVersion": ""
    },
    "manifest": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "disableThumbnails": false,
        "defaultPresentationDelay": 0,
        "segmentRelativeVttTiming": false,
        "dash": {
            "clockSyncUri": "",
            "ignoreDrmInfo": false,
            "disableXlinkProcessing": false,
            "xlinkFailGracefully": false,
            "ignoreMinBufferTime": false,
            "autoCorrectDrift": true,
            "initialSegmentLimit": 1000,
            "ignoreSuggestedPresentationDelay": false,
            "ignoreEmptyAdaptationSet": false,
            "ignoreMaxSegmentDuration": false,
            "keySystemsByURI": {
                "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
                "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
                "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
                "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
            },
            "sequenceMode": false
        },
        "hls": {
            "ignoreTextStreamFailures": false,
            "ignoreImageStreamFailures": false,
            "defaultAudioCodec": "mp4a.40.2",
            "defaultVideoCodec": "avc1.42E01E",
            "ignoreManifestProgramDateTime": false,
            "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\"",
            "useSafariBehaviorForLive": true,
            "liveSegmentsDelay": 3,
            "sequenceMode": true
        }
    },
    "streaming": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "rebufferingGoal": 2,
        "bufferingGoal": 10,
        "bufferBehind": 30,
        "ignoreTextStreamFailures": false,
        "alwaysStreamText": false,
        "startAtSegmentBoundary": false,
        "gapDetectionThreshold": 0.5,
        "durationBackoff": 1,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsOnSafari": true,
        "inaccurateManifestTolerance": 2,
        "lowLatencyMode": false,
        "autoLowLatencyMode": false,
        "forceHTTPS": false,
        "preferNativeHls": false,
        "updateIntervalSeconds": 1,
        "dispatchAllEmsgBoxes": false,
        "observeQualityChanges": false,
        "maxDisabledTime": 30,
        "parsePrftBox": false,
        "segmentPrefetchLimit": 0
    },
    "mediaSource": {
        "sourceBufferExtraFeatures": "",
        "forceTransmux": false
    },
    "offline": {
        "usePersistentLicense": true,
        "numberOfParallelDownloads": 5
    },
    "abr": {
        "enabled": true,
        "useNetworkInformation": true,
        "defaultBandwidthEstimate": 1000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
            "minWidth": 0,
            "maxWidth": null,
            "minHeight": 0,
            "maxHeight": null,
            "minPixels": 0,
            "maxPixels": null,
            "minFrameRate": 0,
            "maxFrameRate": null,
            "minBandwidth": 0,
            "maxBandwidth": null
        },
        "advanced": {
            "minTotalBytes": 128000,
            "minBytes": 16000,
            "fastHalfLife": 2,
            "slowHalfLife": 5
        },
        "restrictToElementSize": false,
        "restrictToScreenSize": false,
        "ignoreDevicePixelRatio": false
    },
    "autoShowText": 3,
    "preferredAudioLanguage": "",
    "preferredAudioLabel": "",
    "preferredTextLanguage": "en",
    "preferredVariantRole": "main",
    "preferredTextRole": "subtitle",
    "preferredAudioChannelCount": 2,
    "preferredVideoCodecs": [],
    "preferredAudioCodecs": [],
    "preferForcedSubs": false,
    "preferredDecodingAttributes": [],
    "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null
    },
    "playRangeStart": 0,
    "playRangeEnd": null,
    "cmcd": {
        "enabled": false,
        "sessionId": "",
        "contentId": "",
        "useHeaders": false
    },
    "lcevc": {
        "enabled": false,
        "dynamicPerformanceScaling": true,
        "logLevel": 0,
        "drawLogo": false
    }
}
```
</details>

**What did you do?**
- Load a DASH manifest with TTML subtitle, which contains inline italics, e.g.
  - -`Did...<span tts:fontStyle="italic">he</span> ask for the divorce?`
  - -`<span tts:fontStyle="italic">You</span> did?`
- Play video

**What did you expect to happen?**

A space to be seen after the styled/italicised text

**What actually happened?**

No space is seen after the italicised text

![Screenshot 2023-02-06 at 17 09 12](https://user-images.githubusercontent.com/84047/217037988-d2465ddb-efaf-4562-9149-2bd8c954a54b.png)
![Screenshot 2023-02-06 at 17 09 39](https://user-images.githubusercontent.com/84047/217037983-e0af0f5a-9355-4907-8880-5bed314bb404.png)

The issue happens with both the default `shaka.text.SimpleTextDisplayer` and `shaka.text.UITextDisplayer`.

**Comment by avelad** [comment]
I have been looking at the issue and the problem is that the origin file is  missing the space, if the space is added it works correctly.

**Comment by simontsang** [comment]
> I have been looking at the issue and the problem is that the origin file is missing the space, if the space is added it works correctly.

@avelad Thanks for looking into this, and sorry about the delay in reply.

I don't quite understand what you mean. The origin file has the text:
`Did...<span tts:fontStyle="italic">he</span> ask for the divorce?`.
As far as I can see, there _is_ a space after the closing `span` tag and before the word `ask`.

Likewise, for the markup:
`<span tts:fontStyle="italic">You</span> did?`
There is a space after the closing `span` and before the word `did`.

I've updated the demo to Shaka `v4.7.10`, and it's still showing the same issue.

Can you clarify where there the missing space should be added?

**Comment by avelad** [comment]
I don't know why I posted my previous comment, but it's clearly wrong. Let me keep looking.

**Comment by avelad** [comment]
I have created a very basic file with which to reproduce the problem:

```
<?xml version="1.0" encoding="UTF-8"?>
<tt xml:lang="" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling">
  <body>
    <div>
      <p begin="00:00:00.000" end="00:10:00.000" >Did...<span tts:fontStyle="italic">he</span> ask for the divorce?</p>
    </div>
  </body>
</tt>
```

**Comment by avelad** [comment]
For it to work correctly, we have to use `xml:space` defined in the TTML spec (https://www.w3.org/TR/ttml1/#content-attribute-space), so the file would be:

```
<?xml version="1.0" encoding="UTF-8"?>
<tt xml:lang="" xml:space="preserve" xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling">
  <body>
    <div>
      <p begin="00:00:00.000" end="00:10:00.000" >Did...<span tts:fontStyle="italic">he</span> ask for the divorce?</p>
    </div>
  </body>
</tt>
```

**Comment by simontsang** [comment]
Oh interesting! I'll see what we can do about this in the packager side (Unified).

Interestingly, dash.js seems to render this with a space, without the `xml:space` declared. I'm happy for this to be closed, if you feel that Shaka is behaving to spec, and as intended.

**Comment by simontsang** [comment]
Is this at all related to #665? It does look to be intentional, but i'm not familiar enough with the specs to tell.

**Comment by joeyparrish** [comment]
Thanks for digging up #665.  Very helpful!  Quoting that issue:

> The TTML 1.0 spec Section 7.2.3 says that for xml:space="default", white-space should be treated like
>
> suppress-at-line-break="auto"
> linefeed-treatment="treat-as-space"
> white-space-collapse="true"
> white-space-treatment="ignore-if-surrounding-linefeed"

If you don't specify `xml:space` at all, you get `xml:space="default"` according to the spec, which will collapse whitespace.  So I think Shaka is behaving according to the spec in this case.

**Comment by joeyparrish** [comment]
Test suites have been wrong before... I think the spec text is clear on this point.

You could file an issue with imsc-tests to ask if this was a mistake in the test, a mistake in their reference implementation, or a misunderstanding of the spec on our part.

**Comment by simontsang** [comment]
Clarification requested from imsc-tests (https://github.com/w3c/imsc-tests/issues/110). Closing this issue, but will re-open if necessary. Thanks for looking into this!

**Comment by joeyparrish** [comment]
Our pleasure.  I'll subscribe to the imsc-tests issue.  Thanks for the link!

**Comment by joeyparrish** [comment]
Reopening after clarification.

Quoting w3c/imsc-tests#110: 
> with xml:space="default" runs of one or more "white space" characters are collapsed down to 1 space (0x20) character not zero.
