### ISSUE TITLE
Shaka issues 321 ChromeCast.

### ISSUE THREAD

**Issue by s-t-sa** [shaka-project/shaka-player#4976]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes
**What version of Shaka Player are you using?**

Chromecast version 3.2 i believe
**Please ask your question**

Hi,  

AWS Element encrypted (WideVine) LIVE ChromeCast errors.  

Currently I have this issue where the google cast framework is throwing a 321 error (Shaka is throwing a 1002 HTTP_ERROR) with some part of a stream manifest. It can fail on loading the manifest.mpd, the initialization Mp4 or initialization audio … even some random segment number.  

When I get these errors it can be after a minute or two of playback, other times just not load the manifest. 

The manifests and streams are behind CloudFront. I have harvested jobs that are encrypted that are also behind CloudFront and are casting without problems. It seems to affect just the Elemental encrypted live.  

AWS say these manifests / segments are being served but the client is closing the connection. 

It's odd this only affects AWS Element encrypted live and not the harvested jobs that are also encrypted, apart from the signal source it should be the same? They play back fine with our Shaka web player ( though theres a difference in version numbers )

  Looking for some hints of what might cause these issues with AWS Elemental live and the Shaka player on the ChromeCast  - it would be appreciated !
  
    Thanks.

**Comment by friday** [comment]
Since you are able to reproduce this yourself, maybe try remote debugging and look at the network connections. You can also try to catch and log the original error:

```ts
playerManager.addEventListener(cast.framework.events.EventType.ERROR, (response) => {
  const { detailedErrorCode, error, reason } = response;
  const code = error?.shakaErrorCode;  //  <--- 1002
  const data = error?.shakaErrorData;  // array of extra data likely containing the original error second last.
});
```

The error is likely being thrown from here:
https://github.com/shaka-project/shaka-player/blob/644c93222313369280856e4318299985ccc8cdf6/lib/net/http_fetch_plugin.js#L189-L193

**Comment by s-t-sa** [comment]
Hey Thanks, yes we are logging out the errors - though its not giving us much but heres an example below ( the only thing that changes is the url part, be it mpg init, a segment or audio ), we checked CORS (us and AWS) and seems all good and we do get some playback at times but then these errors will always appear at some time. All other casting works well with AWS elemental ( recorded live encrypted + CDN is great, live encrypted no CDN is great, live no encrypted & CDN is great ) - just Live Encrypted + CDN is the issue :-) 

`[ERROR: {'type""ERROR", detailedErrorCode":321,"error": {"shakaErrorCode":1002,"shakaErrorData": "URL", {}, 0]}}]`

Thanks

**Comment by friday** [comment]
{} is the original error, but you're destroying it by JSON stringifying it (just try to run this in a console `JSON.stringify(new Error())` and you see).

**Comment by s-t-sa** [comment]
Ok Thanks, Ha I misread the cast error docs and saw an object with error info in it. I will take a look at that and see if we get something back.

**Comment by friday** [comment]
The cast error docs only covers how to catch the errors they throw. Not these Shaka-error specific properties or what they are. shakaErrorData doesn't always contain the original error either.

**Comment by s-t-sa** [comment]
Hi thanks for the reply,
Sorry i've been away otherwise I would have commented sooner - sure i can see the error thrown by Shaka and its the same as the cast ( Failed to Fetch ). Heres some output from the logs if you would like to see (attached), in this example manifest_audio_10_0_114583.mp4 is appears a number of times and ultimately the final error was on this with a Failed to fetch, though to me the log shows it was served correctly. Other examples are the same basically, but just stopping at various other points. 

Second column is the bytes received and final column is the size. 

Could a CDN issue look like this pattern ? 

[cast-error-log.txt](https://github.com/shaka-project/shaka-player/files/10872154/cast-error-log.txt)

Thanks
