### ISSUE TITLE
VMAP ads stay muted on muted autoplay

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#4992]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

Latest

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Both

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

Windows, Chrome
**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Standard configuration

**What did you do?**

Video is set to muted and autoplay. Ads are loaded through VMAP (client side ads). 

For testing you can use any VMAP option from https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags

**What did you expect to happen?**

Video starts muted and autoplays. 
User unmutes video. 
Video and ads play with sound. 

**What actually happened?**

After unmuting, video plays with sound, but ads are still muted.

**Comment by Andekas** [comment]
I did a quick fix, that resolves also https://github.com/shaka-project/shaka-player/issues/4800 issue: 

```
adManager.addEventListener(shaka.ads.AdManager.IMA_AD_MANAGER_LOADED, (e) => {
  imaAdManager = e['imaAdManager'];
});

adManager.addEventListener(
  shaka.ads.AdManager.AD_STARTED, () => {
 imaAdManager.setVolume(!video.muted);
});
```

**Comment by avelad** [comment]
@Andekas are you interested on send a PR for it? Thanks!

**Comment by Andekas** [comment]
@avelad I was just about to say that sure, but I guess I was too late for it. Thanks!
