### ISSUE TITLE
DRM 6001 error when trying to load Dash manifest on Chrome 72

### ISSUE THREAD

**Issue by andypixel** [shaka-project/shaka-player#4994]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Issue is only reproduceable on Chrome 72, even when using the demo app.
<img width="840" alt="image" src="https://user-images.githubusercontent.com/444736/218205073-2dbba48a-611c-497e-8050-3d50080d0272.png">

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3625.0 Safari/537.36

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

(Can provide if absolutely necessary, but error is reproduceable using the demo app)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

<details>
  <summary>Configuration settings</summary>

```json
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "servers": {
      "com.widevine.alpha": "https://widevine-license.vudrm.tech/proxy"
    },
    "clearKeys": {},
    "advanced": {},
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1,
    "preferredKeySystems": [],
    "keySystemsMapping": {},
    "parseInbandPsshEnabled": false
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": false,
    "defaultPresentationDelay": 0,
    "segmentRelativeVttTiming": false,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": true,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        (redacted)
      },
      "sequenceMode": false
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "ignoreImageStreamFailures": false,
      "defaultAudioCodec": "mp4a.40.2",
      "defaultVideoCodec": "avc1.42E01E",
      "ignoreManifestProgramDateTime": false,
      "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\"",
      "useSafariBehaviorForLive": true,
      "liveSegmentsDelay": 3
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 0.01,
    "bufferingGoal": 10,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.5,
    "durationBackoff": 1,
    "forceTransmux": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 0,
    "lowLatencyMode": true,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 1,
    "dispatchAllEmsgBoxes": false,
    "observeQualityChanges": false,
    "maxDisabledTime": 30,
    "parsePrftBox": false
  },
  "mediaSource": {
    "sourceBufferExtraFeatures": ""
  },
  "offline": {
    "usePersistentLicense": true,
    "numberOfParallelDownloads": 5
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    },
    "advanced": {
      "minTotalBytes": 128000,
      "minBytes": 16000,
      "fastHalfLife": 2,
      "slowHalfLife": 5
    },
    "restrictToElementSize": true,
    "restrictToScreenSize": false,
    "ignoreDevicePixelRatio": false
  },
  "autoShowText": 3,
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferredVideoCodecs": [],
  "preferredAudioCodecs": [],
  "preferForcedSubs": false,
  "preferredDecodingAttributes": [],
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null,
  "cmcd": {
    "enabled": false,
    "sessionId": "",
    "contentId": "",
    "useHeaders": false
  },
  "lcevc": {
    "enabled": false,
    "dynamicPerformanceScaling": true,
    "logLevel": 0,
    "drawLogo": false
  }
}
```

</details>

**What did you do?**

`player.load()` with described settings.

**What did you expect to happen?**
Expect video to load on all browsers/user agents

**What actually happened?**

Video loads on most all user agents (e.g. desktop Chrome, embedded devices using Chromium) but throws a 6001 error on the affected user agent:

category: 6
code: 6001
data: []
handled: false
message: "Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()"
severity: 2
stack: "Error: Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()\n    at new shaka.util.Error ([http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:48495)\n](http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:48495)/n)    at $jscomp.generator.Engine_.program_ ([http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:14:129361)\n](http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:14:129361)/n)    at $jscomp.generator.Engine_.nextStep_ ([http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:10101)\n](http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:10101)/n)    at $jscomp.generator.Engine_.next_ ([http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:9065)\n](http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:9065)/n)    at $jscomp.generator.Generator_.next ([http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:10546)\n](http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:10546)/n)    at [http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:11119\n](http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:11119/n)    at new Promise (<anonymous>)\n    at Object.$jscomp.asyncExecutePromiseGenerator ([http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:11012)\n](http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:11012)/n)    at Object.$jscomp.asyncExecutePromiseGeneratorProgram ([http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:11308)\n](http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:6:11308)/n)    at shaka.media.DrmEngine.queryMediaKeys_ (http://10.64.17.154:3000/_app/chunks/player-0ab0bfa6.js:14:129104)"

**Comment by avelad** [comment]
Widevine from time to time deprecates the CDMs of old browsers, if I remember correctly now it is necessary to use at least Chrome 95. For more details please contact with Widevine team. Thanks!

**Comment by andypixel** [comment]
> Widevine from time to time deprecates the CDMs of old browsers, if I remember correctly now it is necessary to use at least Chrome 95. For more details please contact with Widevine team. Thanks!

[Álvaro](https://github.com/avelad), would this Widevine compatibility issue only apply to Shaka? I can load and play DRM videos using Widevine and dash.js on Chrome 72 without issue.
