### ISSUE TITLE
Integrate shaka with flutter

### ISSUE THREAD

**Issue by PVR001** [shaka-project/shaka-player#4996]
i have been working with integrating Shaka player with flutter. Though there is no direct implementation ,  i used webview plugin . Is  there any feasible solution to integrate shaka player with fluter?

**Comment by joeyparrish** [comment]
I don't know much about Flutter, but Shaka Player should generally work in WebViews (Android or iOS) or other HTML5 environments that have the necessary APIs.  You can see a detailed support check by loading this page in your Webview in Flutter: https://shaka-player-demo.appspot.com/support.html  Please copy the output of that to GitHub if you need help understanding it.
