### ISSUE TITLE
Playback of multikey content for playready using shaka player

### ISSUE THREAD

**Issue by tshaji** [shaka-project/shaka-player#4997]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
https://shaka-player-demo.appspot.com/demo/
**Please ask your question**
Hi Team,

Regarding the shaka player, I have a few inquiries. We are putting into practice a multikey solution for playready playback(which encrypts the media with different keys for audio and video).
We notice that the player is generating separate license challenge for each of the keys as we attempt to playback the media.
 
1)Is this the intended behavior while using Playready  to play back the content using Shaka player?
2)Is there a way to use a single license challenge or to generate single license challenge for multikeys, which would contain all the encryption keys?
3)Could you  give us some instructions/documentaion on how to use the multikeys with Shaka player for playready?

**Comment by avelad** [comment]
> 1)Is this the intended behavior while using Playready to play back the content using Shaka player?

Yes

> 2)Is there a way to use a single license challenge or to generate single license challenge for multikeys, which would contain all the encryption keys?

It is currently not possible to do this, but we are open to anyone making contributions in this regard.
