### ISSUE TITLE
I am getting "Error code 4032 object" in shaka player . Can some help me?

### ISSUE THREAD

**Issue by zarifRahman** [shaka-project/shaka-player#5003]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

**Please ask your question**

**Comment by martinstark** [comment]
> The content container or codecs are not supported by this browser. For example, this could happen if the content is WebM, but your browser does not support the WebM container, or if the content uses HEVC, but your browser does not support the HEVC codec. This can also occur for multicodec or multicontainer manifests if none of the codecs or containers are supported by the browser. To see what your browser supports, you can check the JSON data dumped by http://support.shaka-player-demo.appspot.com/

See https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#.Code

**Comment by zarifRahman** [comment]
How will i solve it then?

**Comment by martinstark** [comment]
You'll need to provide a lot more information for anyone to be able to answer that question. I suggest updating the ticket with information about your setup, the stream format, codec, etc.

If the browser tells you it doesn't support the format you're trying to play, it's hard to say more without knowing what you're trying to play.

The link provided above will give you information about what the browser you're using supports, your content needs to be in one of the supported formats or it will not work in the browser you're trying to use.

The shaka [README](https://github.com/shaka-project/shaka-player/blob/main/README.md) also contains information on what types of content and where you can expect it to work.

**Comment by zarifRahman** [comment]
I have solved it.
By Adding this two files in the index.html file.

<script src="https://cdn.jsdelivr.net/npm/mux.js@5.5.3/dist/mux.min.js">  </script>



<script src="https://cdn.jsdelivr.net/npm/shaka-player@3.2.2/dist/shaka-player.compiled.js"></script> 

This should be able to transmux MPEG2-TS streams to MP4 so they can be played in browsers that don't support it. And this helps in changing the resolution of the video.
