### ISSUE TITLE
No audio in a channel when changing the language

### ISSUE THREAD

**Issue by SergioFernandez-Mirada** [shaka-project/shaka-player#5005]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.4 / 4.2.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
ONLY reproduced with Mozilla Firefox (in Windows or Mac, this bug is not reproduced with Linux)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
URI from the Demo asset sent to shaka-player-issues@google.com

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
On the sent mail

**What did you do?**
Change the language from Spanish to English. If the default language is English, we first change from English to Spanish and after then back from Spanish to English.

**What did you expect to happen?**
Audio is reproduced okey, no problem is caused by changing the language

**What actually happened?**
No audio is reproduced at all when changing from Spanish to English. It's seems not be a problem with the English channel, because if the default language is English, the audio is reproduced correctly when opening the player.

When changing again to Spanish, the audio is reproduced, the problem is caused in the specific Spanish to English change. The first audio format is Surround and the second is Stereo, we consider this as a possible cause.

**Comment by avelad** [comment]
It seems that Firefox does not support changing the number of channels without resetting the sourcebuffer. I have the same problem on other devices.

Stream with stereo and surround with the same language: https://storage.googleapis.com/shaka-demo-assets/tos-surround/dash.mpd

**Comment by avelad** [comment]
@SergioFernandez-Mirada , does this problem still occur with the latest versions of Firefox?
