### ISSUE TITLE
A/V sync problem on both multi-period DASH and HLS after SSAI ad break

### ISSUE THREAD

**Issue by jolytv2** [shaka-project/shaka-player#5007]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, possible (closed) duplicate [4589](https://github.com/shaka-project/shaka-player/issues/4589)

**What version of Shaka Player are you using?**
Tested with both 4.3.2 (custom build) and 4.3.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both custom and demo app (demo app integrated in a Tizen demo app)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen 3.0 - 7.0 (2017 - 2023)
WebOS 3.x - 8.x (2016 - 2023)

Seemingly all models are equally affected. 

**What are the manifest and license server URIs?**
[DASH](https://csm-e-tv2dk-eb.tls1.yospace.com/csm/extlive/tv2dkdev01,dev_tv2_fyn_audiodesync_staticvast.mpd?yo.ac=true&yo.d.mc=true&yo.pbr=true)

[HLS](https://csm-e-tv2dk-eb.tls1.yospace.com/csm/extlive/tv2dkdev01,dev_hls_audiodesync_staticvast.m3u8?yo.ac=true&yo.d.mc=true&yo.pbr=true&yo.pdt=sync)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default 

**What did you do?**
- Start playback of one of the above streams in an app on a Tizen or WebOS TV with latest Shaka
- Let it run 3-4 ad breaks or more 

**What did you expect to happen?**
Audio / video to remain in sync over extended play across ad breaks

**What actually happened?**
- After 3-4 ad breaks sync is (estimated) 500ms out of sync or more

** Additional information **
We have attempted running the latest Shaka, created an HLS version of the stream and running with the yo.pdt=sync setting as mentioned in [4589](https://github.com/shaka-project/shaka-player/issues/4589) - but we still have the issue.

**Comment by joeyparrish** [comment]
Please confirm that your playlists have EXT-X-PROGRAM-DATE-TIME, and that the timestamps in them are accurate. That is the basis for HLS AV sync, both in Shaka and according to the HLS spec.

Please let us know what you find.

**Comment by jolytv2** [comment]
Hi @joeyparrish 

**HLS**
Regarding your question, on HLS we are running with the yo.pdt parameter from Yospace that inserts the EXT-X-PROGRAM-DATE-TIME - I am not sure how to tell the accuracy of them though. It did seem however that the stream went significantly out of sync with Shaka and yo.pdt=sync, but sometimes went back into sync. Without yo.pdt=sync it didn't seem to recover, at least not as much.  

**DASH**
It should be noted though, that HLS was something we tested, due to the 4589 ticket, but we normally run multiperiod DASH on our SmartTVs. 

Recent observations on DASH is:

a) It seems out timescale is different for content and ads, ads are 12800 and content 180000. This would appear to present problems for SmartTVs, that don't handle changes in timescale well. We haven't the option of aligning the timescale on Yospace and changing our timescale on content isn't trivial either. We have in another player seen that having the player do a remapping of the timescale to match our contents timescale, removes a part of the de-sync issue. 

b) We have also seen that small gaps and overlaps in segments seem to be the second cause of sync problems. When we look at the media internals on web in Chrome, we can sometimes see that the player handles these gaps/overlaps without issue, but on SmartTV this is not the case. In the other player adjustments were made to handle this better on SmartTVs, and combined with regular re-syncs, and the above timescale thing, we can keep the sync down to a few frames, which is within reasonable boundaries.

**Comment by avelad** [comment]
Can you test again with the latest release (4.4.2)? Thanks!

**Comment by jolytv2** [comment]
Hi Avelad, thank you, we will test and get back!
