### ISSUE TITLE
Running Shaka in a Web Worker

### ISSUE THREAD

**Issue by IsaacSNK** [shaka-project/shaka-player#5008]
Hi! Is there any plan on taking advantage of the MSE in Web Workers for Shaka? This could have great performance benefits when the main thread is busy. I see MSE in Web Workers is available for Chrome 108...Any concern, ideas you may have?

**Comment by avelad** [comment]
@joeyparrish can you review it? Thanks!

**Comment by IsaacSNK** [comment]
No, it doesnt

**Comment by avelad** [comment]
Right now this functionality is not supported, nor have I found a issue where nobody asks for it. If you are interested, create an improvement issue so that we can study it. Thank you!
