### ISSUE TITLE
FakeEvent Listener callback function not working when getting Player from UI Controls 

### ISSUE THREAD

**Issue by shmillar** [shaka-project/shaka-player#5009]
I planned on filing this as a question, but I think this may be a bug. From the question template: "If you suspect that your issue might be a bug, but aren't sure, please file the bug template instead."

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes.

**What version of Shaka Player are you using?** 4.3.0

**Can you reproduce the issue with our latest release version?** Yes, using latest version.

**Can you reproduce the issue with the latest code from `main`?** Yes.

**Are you using the demo app or your own custom app?** Custom Response Filter Plugin

**If custom app, can you reproduce the issue using our demo app?** Yes.

**What browser and OS are you using?** Windows, Microsoft Edge and Google Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** Not tested on an embedded device

**What are the manifest and license server URIs?**

I am using Microsoft Azure Media Services generated manifests. The issue I am facing is happening across multiple manifests, and I believe the manifest used will not affect the result.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

I am using the default configuration of Shaka Player. The output of player.getConfiguration() is the same as the output from the Shaka [Tutorials](https://shaka-player-demo.appspot.com/docs/api/tutorial-config.html).

**What did you do?**

Our Response Filter Plugin is using Custom Events (`Shaka.util.FakeEvent`) that are being dispatched through the player (`player.dispatchEvent(myFakeEvent)`). When I add event listener (`player.addEventListener(() => { console.log(event) })`), the event listener callback functions runs when I create a new Shaka Player, but does not run when using the UI Control's Shaka Player

Creating Player and EventListener that is currently working as expected:

```
const video = document.getElementById('video');
const player = new shaka.Player(video);
player.addEventListener('myEvent', (event) => {
  // This callback function is being called, and the event is being printed into the console.
  console.log(event);
}
```

Creating Player and EventListener that is currently **_not_** working as expected:
```
const video = document.getElementById('video');
const ui = video['ui'];
const controls = ui.getControls();
const player = controls.getPlayer();
player.addEventListener('myEvent', (event) => {
  // This callback function is not being called, and the event is not being printed into the console.
  console.log(event);
}
```

My FakeEvent:
`const myEvent = new FakeEvent('myEvent', new Map());`

Dispatching the Event:
`player.dispatchEvent(myEvent);`

**What did you expect to happen?**
I expected my event listener's callback function to print out my event that is being fired. The event is being fired, and is seen in listenToAllEvents. However my event listener's callback function is not being called when using UI Controls to getPlayer().

**What actually happened?**

When stepping through the code, the event listener is being added to listeners_ array. When dispatching the event, the code enters cast_proxy.js, and the event listeners array is being defaulted [FakeEvent.EventName,](https://shaka-player-demo.appspot.com/docs/api/lib_util_fake_event.js.html#line155). Since myEvent is not in this default list, my event listener does not receive any event, but listenToAllEvents receives it. I appreciate any insights on what I might be missing here, or if this is a bug. Thank you!

**Comment by avelad** [comment]
@joeyparrish can you review it? Thanks!
