### ISSUE TITLE
VIZIO SmartCast TV is being incorrectly categorized as a Chromecast, breaking DRM playback

### ISSUE THREAD

**Issue by littlespex** [shaka-project/shaka-player#5010]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.x

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
VIZIO TV

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
`Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36 CrKey/1.0.999999 VIZIO SmartCast(Conjure/SX7A-4.6.419.12 FW/11.0.120.1-1 Model/M65-D0)`

**What are the manifest and license server URIs?**

Available upon request

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Configure a player to play DRM protected content on a VIZIO SmartCast TV.

**What did you expect to happen?**
Video should play.

**What actually happened?**

Player throws an 8000 error. 

<img width="1680" alt="219510466-7ff35810-08de-4f4b-8b4c-f826f1f075c6" src="https://user-images.githubusercontent.com/1508707/219520681-f76124f6-3271-48de-bc30-7ca1fdc7bb29.png">

**Comment by littlespex** [comment]
@joeyparrish I'm not sure which approach is best to take for this fix:
1. Refine the `shaka.util.Platform.isChromecast()` utility to ignore the VIZIO use case
    - I'm not sure if this would break scenarios where the TV was acting specifically as a cast device.
2. Soften the logic in `shaka.polyfill.MediaCapabilities.canCastDisplayType_` to treat the `!(window.cast)` case as a warning instead of an error and fallback to `shaka.media.Capabilities.isTypeSupported`

**Comment by joeyparrish** [comment]
Both?  At least 2.
