### ISSUE TITLE
 Audio and video are out of sync with live HLS streaming when audio and video segments are in separate subdirectories.

### ISSUE THREAD

**Issue by Tsuruoka-569** [shaka-project/shaka-player#5013]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome on macOS Monterey 12.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

n/a

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Unsure.

**What did you do?**

Create a live HLS master manifest, where video and audio segments are in separate subdirectories, with ffmpeg.

Command we use is:
> ffmpeg -re -i input.mp4 -map 0:0 -vcodec copy -map 0:1 -acodec copy -f hls -hls_list_size 10 -g 90 -hls_segment_type fmp4 -movflags +faststart -hls_time 3 -hls_segment_filename stream_%v/data%02d.m4s -master_pl_name master.m3u8 -var_stream_map "v:0,agroup:av a:0,agroup:av" "stream_%v/output.m3u8"

Input video we use is 1080p h264 with aac audio in a mp4 container.

**What did you expect to happen?**
Since having variant streams in subdirectories is allowed in HLS, we expect a smooth playback of the master manifest.

**What actually happened?**

On Chrome, Shaka Player is able to load the content, however, video and audio are out of sync. 

Previsouly, with v4.3.0, we were experiencing an issue where video is frozen for a few second while audio is able to play when loading a content, as well as constant pauses and a/v out of sync issues during playback . 

With v4.3.4, the major problem is that the video and audio are still out of sync.

**Comment by avelad** [comment]
We've recently fixed a lot of issues with HLS, can you check again against the main branch? Thanks!

**Comment by Tsuruoka-569** [comment]
We've tested this again with v4.3.7. The issue is still not solved. 
On Chrome browser, av sync is still off when loading the video. 
Test content example : https://ireplay.tv/test/blender.m3u8

**Comment by Tsuruoka-569** [comment]
We checked again with v4.4.1. The av sync is still off...
