### ISSUE TITLE
How can I insert a jingle / video intro (not strictly speaking an ad) before the main video plays ?

### ISSUE THREAD

**Issue by loicraux** [shaka-project/shaka-player#5015]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
Latest

**Please ask your question**
I have searched the documentation, the open issues and the FAQ, but I could not find an answer to this question (I even asked ChatGPT who made up some configuration options that do not exist :) :

How can I insert a jingle / video intro before the main video plays? I have the URL of the jingle video, (it is not strictly speaking an ad)

- Is it possible to "hijack" the ad management system?
- With a metadata track somehow ?

Any advice is welcome!

Thanks

**Comment by theodab** [comment]
We don't have a built-in way to do this. And I kind of doubt that the IMA SDK provides an API to load random video file URLs as though they were client-side ads, either.

It's not pretty, but if the jingle is something that the browser can play natively in a media element you can kind of hijack parts of the ad API to kind of fake a client-side ad.
Something like...
```js
const playJingle = async (uri, shakaPlayer, shakaVideo, shakaControls) => {
  // Make a video for playing the jingle.
  const jingleVideoContainer = shakaControls.getClientSideAdContainer();
  const jingleVideo = document.createElement('video');
  jingleVideoContainer.appendChild(jingleVideo);
  jingleVideo.style.width = '100%';
  jingleVideo.style.height = '100%';

  // Pause the real video, and start loading the jingle.
  shakaVideo.pause();
  jingleVideo.src = uri;
  jingleVideo.play();
  await new Promise((resolve) => jingleVideo.onplaying = () => {
    resolve();
    jingleVideo.onplaying = null;
  });

  // Create a synthetic ad event that wraps the jingle video.
  const adManager = shakaPlayer.getAdManager();
  adManager.dispatchEvent(new shaka.util.FakeEvent('ad-started', {'ad': {
    isLinear: () => true,
    isPaused: () => jingleVideo.paused,
    pause: () => {
      jingleVideo.pause();
      adManager.dispatchEvent(new shaka.util.FakeEvent('ad-paused'));
    },
    play: () => {
      jingleVideo.play();
      adManager.dispatchEvent(new shaka.util.FakeEvent('ad-resumed'));
    },
    getSequenceLength: () => 1,
    getDuration: () => jingleVideo.duration,
    getRemainingTime: () => jingleVideo.duration - jingleVideo.currentTime,
  }}));

  // Wait for the jingle to end, then resume the video and tear down the jingle.
  await new Promise((resolve) => jingleVideo.onended = resolve);
  adManager.dispatchEvent(new shaka.util.FakeEvent('ad-stopped'));
  shakaVideo.play();
  jingleVideoContainer.removeChild(jingleVideo);
});
```

I guess you'll also want to hide the `shaka-ad-counter-span` element so that it doesn't say that your jingle is an ad.

**Comment by loicraux** [comment]
Thanks for this detailed response... But I feel like it's a bit complicated just for a jingle...  I think I'll go with a simple src= on the video element, and once the playback is finished , load the shaka player with the same video element.
