### ISSUE TITLE
Alternate Audio Language ShakaUI

### ISSUE THREAD

**Issue by stuartflanagan** [shaka-project/shaka-player#5019]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.4

**Please ask your question**
I have a manifest with multiple audio of the same Language.

The Audio is Alternate Audio Described.
The current Shaka UI displays the Language of `English` for both

The markup for the manifest is as follows
```
 <AdaptationSet mimeType="audio/mp4" startWithSAP="1" segmentAlignment="true" lang="en" label="English Audio Description" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="alternate"/>
      <Accessibility schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007" value="1"/>
      <!-- MPEG Common Encryption -->
...
</AdaptationSet>
```
My question is should I expect this to use the label property so that the user can distinguish between the Alternative Audio track?

**Comment by stuartflanagan** [comment]
Could this be a bug?

**Comment by joeyparrish** [comment]
The player API lets you see both languages and roles, and to select by language and role together if you wish.  The UI is configurable to show roles IIRC.  Let me find the config for you.

**Comment by joeyparrish** [comment]
Here it is.  Configure the UI's `trackLabelFormat` field:

 - https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.UIConfiguration
 - https://shaka-player-demo.appspot.com/docs/api/shaka.ui.Overlay.html#.TrackLabelFormat

Quoting the docs:

> field | type | description
> -- | -- | --
> trackLabelFormat | shaka.ui.Overlay.TrackLabelFormat | An enum that determines what is shown in the labels for text track and audio variant selection. LANGUAGE means that only the language of the item is shown. ROLE means that only the role of the item is shown. LANGUAGE_ROLE means both language and role are shown, or just language if there is no role. LABEL means the non-standard DASH "label" attribute or the HLS "NAME" attribute are shown. Defaults to LANGUAGE.

Here's a snippet, assuming `video` is a reference to your video element:

```js
video.ui.configure(
    'trackLabelFormat',
    shaka.ui.Overlay.TrackLabelFormat.LANGUAGE_ROLE);
```

**Comment by stuartflanagan** [comment]
That is great thank you for that information @joeyparrish !

**Comment by absidue** [comment]
@joeyparrish Is there a reason shaka uses the non-standard `label` attribute instead of the `Label` element that is in the DASH specification?
Link to the specification: https://standards.iso.org/ittf/PubliclyAvailableStandards/c083314_ISO_IEC%2023009-1_2022(en).zip

**Comment by avelad** [comment]
Shaka supports both forms. See https://github.com/shaka-project/shaka-player/blob/main/lib/dash/dash_parser.js#L1114-L1125

**Comment by absidue** [comment]
@avelad Would probably be a good idea to update the docs to say that, as they currently only say that it supports the non-standard label attribute.

**Comment by avelad** [comment]
@absidue Can you tell me where you have seen it? I'll try to do a PR to fix it.

**Comment by absidue** [comment]
In the description for the `trackLabelFormat` option in the `UIConfiguration` interface:

> [...] LABEL means the non-standard DASH "label" attribute or the HLS "NAME" attribute are shown. [...]

https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.UIConfiguration
