### ISSUE TITLE
Preloading/Warming Content in Shaka Player's instance

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#5029]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.2

**Please ask your question**
Hi! If we are to create a similar experience like Hulu's Web Player in some content they have a thing called Pre Rolls. Usually these are MA Warning or Production Studio Video and ranges only from 5 - 10 seconds, hence Pre Rolls. Say a Pre Roll `plain,mp4,10s` is loaded before `drm,dash,1hr` video how what I currently will do is on video end event I would just call the load method again and configure the DRM before that. However that could add to some loading time.

Is there some way that I can preload this main content to prevent time taken during manifest and licensing? This would allow us to create a seamless user experience. Both Netflix and Hulu have similar UX ofcoz the stack if different. Spotify on the other hand uses Shaka Player and I felt something similar, however later found that they are fetching and decrypting data on the go and is super fast because of Akamai CDN. If we have something similar in Shaka could really help us.

**Comment by martinstark** [comment]
You have to use two separate Shaka instances with their own video elements to achieve this. When the preroll starts playing you can start loading the main content in the second Shaka instance, then swap out the DOM video element when the preroll ends and start playing.

If the preroll is a simple mp4, and you don't need Shaka's buils in UI, you can play it directly by assigning it as src on the video element, which obviates the need for dual Shaka instances.

**Comment by WINOFFRG** [comment]
Hmm so that's the only method, Also what about warming? For second playback **should I just load it and pause it**? So that shaka loads that content as well and get done with licensing as well? 

I feel there could be some issues with this way of loading and then pause?
