### ISSUE TITLE
Cannot interact with iOS native player when not in fullscreen 

### ISSUE THREAD

**Issue by multiplexer2** [shaka-project/shaka-player#5031]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.3.4

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Have not tried

**Are you using the demo app or your own custom app?**

Demo app

**If custom app, can you reproduce the issue using our demo app?**

Yes

**What browser and OS are you using?**

Safari on IOS 16.3.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A

**What are the manifest and license server URIs?**

The problem can be reproduced with any video on the demo page

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Shaka demo config

**What did you do?**

Navigate to any video on the demo page, with the phone in portrait mode.
Shaka player is loaded and works fine.

Open up the inspector and make a couple changes to the HTML:
 - On the container element: shaka-controls="false"
 - On the video element: Add attribute controls=""

The Shaka controls are now replaced with native controls. 

**What did you expect to happen?**

It should be possible to start and control playback by tapping play and other buttons.

**What actually happened?**

When tapping play or any other control, nothing happens. The player is totally non-responsive.

After going to fullscreen by rotating the phone to landscape mode, the player becomes responsive again, but only while still in fullscreen.

This problem does not occur with Shaka 4.2.0

Note: While the player is non-responsive, it is possible to start playback from the console (after having muted the audio, also from the console).

**Comment by multiplexer2** [comment]
Have tested with various versions, and the problem occurs from version 4.3.0.

Also found a workaround: By setting z-index:1 on the video element, the native controls become tappable again.

**Comment by avelad** [comment]
Can you test if the main branch still has the problem? Thank you!
