### ISSUE TITLE
Can we create a cue points or tags with VTT?

### ISSUE THREAD

**Issue by hiren3897** [shaka-project/shaka-player#5035]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.2

**Please ask your question**
Can we create cue points in the player using webvtt or any other source?

Can you please provide me a doc or example somewhere I can dig around?

Thanks

**Comment by avelad** [comment]
Right now Shaka does not provide this functionality. Sorry...
