### ISSUE TITLE
Unable to play FairPlay protected content through MSE/EME on version 4.3.4

### ISSUE THREAD

**Issue by yvashar** [shaka-project/shaka-player#5038]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.4

**Please ask your question**
We tried setting `streaming.useNativeHlsOnSafari` to false in the shaka configuration, player gives an error as below for the fairplay protected content.
<img width="893" alt="image" src="https://user-images.githubusercontent.com/52818553/221838373-5835ee74-9685-467f-b335-f0e3dd073383.png">

**Comment by martinstark** [comment]
Please have a look at [Fairplay Tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html), the error is expected with the setup you are describing.
