### ISSUE TITLE
Can shaka player auto detect network quality to change resolution automatically?

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#5048]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes. I already read.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. I already read.

**What version of Shaka Player are you using?**
4.0.2

**Please ask your question**
I use shaka player for my webiste, which play stream like channels, football event. Each stream have multi quality: 480p, 720p, 1080p. I can't find any way to make shaka player can auto detect network spped and to auto switch stream quality. For example, if network is good, play the 1080p, if network is weak, play 480p. 
It is like Youtube doing, auto switch video quality based on network speed.
Thank you.

**Comment by loicraux** [comment]
It's all in the documentation.
I guess what you're looking for are the `abr` options in the configuration. Set `abr.enabled` to `true`, and probably also the option `abr.useNetworkInformation`.
See https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.AbrConfiguration

**Comment by friday** [comment]
Also see #4691

**Comment by vanminhquangtri** [comment]
Thank you @friday @loicraux
