### ISSUE TITLE
Fairplay fails with error code 3016

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-player#5059]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. Similar issue reported in #4470 

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
With demo app fairplay content not available

**What browser and OS are you using?**
MacOS, Safari browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
Available in the github repo 

**What did you do?**
We are using fairplay DRM with shaka player. Play is failing randomlt 30%-50% of the times. And for some videos it fails most of the times.

We can reproduce the issue with axinom demo code.
https://github.com/Axinom/drm-quick-start

Download the code and do "npm install" and "npm start". Play the first video.
Wait for 2-3 seconds for play to start and then reload the browser and then play same video again
Play with fail 5-10 times out of 20 times.

Pls check this video which reproduces the issue:
https://learnyst-content-mumbai.s3.ap-south-1.amazonaws.com/fairplayissue/fairplay.mp4

(**Since Fairplay DRM is enabled the video is not captured. When there is white screen it means that video is playing.
When the video fails we can see black video with failed logo. Play failure starts at 40 sec in the video)

When play fails, it fails with error code 3016.
We have tested in 3 different MacBook Pro laptops and all have the same issue.

**What did you expect to happen?**
Fairplay play should be success 100% of the time

**What actually happened?**
Play is failing very frequently (30%-40% of the times)

**Comment by Robloche** [comment]
I have the same issue, and just like you, it randomly fails.
But I don't think Shaka Player is the culprit because before using it, I was using the native HTML video player, and had the same problem.

What I noticed is this happens if I launch a video right after having stopped another one.
But if I wait some time, like one minute, the next play is OK.
So my guess is there is some kind of internal resource that's not freed.

I asked a question on StackOverflow some time ago but that didn't cause much enthusiasm (to say the least):
https://stackoverflow.com/questions/74209455/hlsfairplay-stream-resource-freeing-issue

**Comment by sinewave440hz** [comment]
I am also seeing this issue when upgrading to 4.3.5 from version 3. In fact, any version 4 (I've tried most of them) fails when using the same settings we were using in version 3. Namely: `com.apple.fps.1_0` and an `initDataTransform` and `useNativeHlsOnSafari=true`. Unsure how to proceed... (I've tried with and without the legacy apple polyfill and all combinations of the settings I mention here).

**Comment by dacoten** [comment]
@sinewave440hz
We can't play them on Android devices.
Do you have any suggestions?

**Comment by avelad** [comment]
According to @sinewave440hz the problem was resolved

**Comment by Robloche** [comment]
Well... I tried @sinewave440hz's solution but did not notice any improvement.
