### ISSUE TITLE
CMCD data is not sent on some requests when there is no extension in the URL

### ISSUE THREAD

**Issue by mpollingerQualabs** [shaka-project/shaka-player#5067]
## Context before the actual _issue_

Since CMCD is increasingly starting to get implemented and used across more and more players and CDNs, we started to build a CMCD validator (thanks to Will Law 🙏 ) so that any player could get validation that their implementation of the standard is correct.

To start testing the validator that we've built, we created a demo app using a shaka player and some example assets to test the validator.
At first, as expected, we were getting all valid requests out of the shaka player, but then we tested with a different asset and started getting some invalid results, unexpected for us.

I'll describe what we _think_ is a bug using the template below.

---

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
`shaka-player-react: 1.1.5`

**Can you reproduce the issue with our latest release version?**
Yes, using latest (at the moment of writing this issue).

**Can you reproduce the issue with the latest code from `main`?**
Haven't tried. Using directly from npm when doing `npm install`.

**Are you using the demo app or your own custom app?**
Using own custom application made with react.

**If custom app, can you reproduce the issue using our demo app?**
Haven't tried the shaka demo app.

**What browser and OS are you using?**
> Chrome Version 110.0.5481.177 (Official Build) (64-bit)
> Ubuntu 22.10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

This is the output:

> '{\n  "drm": {\n    "retryParameters": {\n      "maxAttempts": 2,\n      "baseDelay": 1000,\n      "backoffFactor": 2,\n      "fuzzFactor": 0.5,\n      "timeout": 30000,\n      "stallTimeout": 5000,\n      "connectionTimeout": 10000\n    },\n    "servers": {},\n    "clearKeys": {},\n    "advanced": {},\n    "delayLicenseRequestUntilPlayed": false,\n    "logLicenseExchange": false,\n    "updateExpirationTime": 1,\n    "preferredKeySystems": []\n  },\n  "manifest": {\n    "retryParameters": {\n      "maxAttempts": 2,\n      "baseDelay": 1000,\n      "backoffFactor": 2,\n      "fuzzFactor": 0.5,\n      "timeout": 30000,\n      "stallTimeout": 5000,\n      "connectionTimeout": 10000\n    },\n    "availabilityWindowOverride": null,\n    "disableAudio": false,\n    "disableVideo": false,\n    "disableText": false,\n    "disableThumbnails": false,\n    "defaultPresentationDelay": 0,\n    "dash": {\n      "clockSyncUri": "",\n      "ignoreDrmInfo": false,\n      "disableXlinkProcessing": false,\n      "xlinkFailGracefully": false,\n      "ignoreMinBufferTime": false,\n      "autoCorrectDrift": true,\n      "initialSegmentLimit": 1000,\n      "ignoreSuggestedPresentationDelay": false,\n      "ignoreEmptyAdaptationSet": false,\n      "ignoreMaxSegmentDuration": false,\n      "keySystemsByURI": {\n        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",\n        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",\n        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",\n        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",\n        "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"\n      }\n    },\n    "hls": {\n      "ignoreTextStreamFailures": false,\n      "ignoreImageStreamFailures": false,\n      "useFullSegmentsForStartTime": false,\n      "defaultAudioCodec": "mp4a.40.2",\n      "defaultVideoCodec": "avc1.42E01E"\n    }\n  },\n  "streaming": {\n    "retryParameters": {\n      "maxAttempts": 2,\n      "baseDelay": 1000,\n      "backoffFactor": 2,\n      "fuzzFactor": 0.5,\n      "timeout": 30000,\n      "stallTimeout": 5000,\n      "connectionTimeout": 10000\n    },\n    "rebufferingGoal": 2,\n    "bufferingGoal": 10,\n    "bufferBehind": 30,\n    "ignoreTextStreamFailures": false,\n    "alwaysStreamText": false,\n    "startAtSegmentBoundary": false,\n    "gapDetectionThreshold": 0.1,\n    "smallGapLimit": 0.5,\n    "jumpLargeGaps": false,\n    "durationBackoff": 1,\n    "forceTransmuxTS": false,\n    "safeSeekOffset": 5,\n    "stallEnabled": true,\n    "stallThreshold": 1,\n    "stallSkip": 0.1,\n    "useNativeHlsOnSafari": true,\n    "inaccurateManifestTolerance": 2,\n    "lowLatencyMode": false,\n    "autoLowLatencyMode": false,\n    "forceHTTPS": false,\n    "preferNativeHls": false,\n    "updateIntervalSeconds": 1,\n    "dispatchAllEmsgBoxes": false,\n    "observeQualityChanges": false\n  },\n  "offline": {\n    "usePersistentLicense": true\n  },\n  "abr": {\n    "enabled": true,\n    "useNetworkInformation": true,\n    "defaultBandwidthEstimate": 1000000,\n    "switchInterval": 8,\n    "bandwidthUpgradeTarget": 0.85,\n    "bandwidthDowngradeTarget": 0.95,\n    "restrictions": {\n      "minWidth": 0,\n      "maxWidth": null,\n      "minHeight": 0,\n      "maxHeight": null,\n      "minPixels": 0,\n      "maxPixels": null,\n      "minFrameRate": 0,\n      "maxFrameRate": null,\n      "minBandwidth": 0,\n      "maxBandwidth": null\n    },\n    "advanced": {\n      "minTotalBytes": 128000,\n      "minBytes": 16000,\n      "fastHalfLife": 2,\n      "slowHalfLife": 5\n    }\n  },\n  "preferredAudioLanguage": "",\n  "preferredTextLanguage": "",\n  "preferredVariantRole": "",\n  "preferredTextRole": "",\n  "preferredAudioChannelCount": 2,\n  "preferredVideoCodecs": [],\n  "preferredAudioCodecs": [],\n  "preferForcedSubs": false,\n  "preferredDecodingAttributes": [],\n  "restrictions": {\n    "minWidth": 0,\n    "maxWidth": null,\n    "minHeight": 0,\n    "maxHeight": null,\n    "minPixels": 0,\n    "maxPixels": null,\n    "minFrameRate": 0,\n    "maxFrameRate": null,\n    "minBandwidth": 0,\n    "maxBandwidth": null\n  },\n  "playRangeStart": 0,\n  "playRangeEnd": null,\n  "cmcd": {\n    "enabled": true,\n    "sessionId": "testSessionId",\n    "contentId": "testContentId",\n    "useHeaders": false\n  }\n}'

**What did you do?**

Using this asset: [copy this link to try in the validator](https://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl))

Can also try with these two other assets:
* [Asset 1](http://amssamples.streaming.mediaservices.windows.net/91492735-c523-432b-ba01-faba6c2206a2/AzureMediaServicesPromo.ism/manifest(format=m3u8-aapl))
* [Asset 2](http://amssamples.streaming.mediaservices.windows.net/69fbaeba-8e92-4740-aedc-ce09ae945073/AzurePromo.ism/manifest(format=m3u8-aapl))

(got them from: https://ottverse.com/free-hls-m3u8-test-urls/)

Go into: **_https://montevideo-tech.github.io/cmcd-validator/_**

Paste the link and click on _Start Shaka_
![image](https://user-images.githubusercontent.com/70527344/223530713-17dc9777-0cff-4a3b-ac3f-e80ca35d67f6.png)

After the video starts, all the requests made from the player are intercepted and the validator checks for the CMCD data
![image](https://user-images.githubusercontent.com/70527344/223534539-9769c367-e7bc-4070-b6d1-946767a48a4a.png)

In green appear the requests from the player that have correct CMCD data.
In red appear the requests from the player that have incorrect CMCD data.

There are some requests that don't have CMCD data. 
Taking a deeper look at the requests that don't have CMCD data, only the ones that use the HTTP method `HEAD` don't have it.

These was found only when the `content-type` is `video/mp2t`.
When this happens, a `HEAD` request is sent for each quality without CMCD data, after the `HEAD` request, the `GET` request for the same quality is sent. All these `GET` requests **do** have CMCD data.

`HEAD` request
![image](https://user-images.githubusercontent.com/70527344/223532720-0852a0fd-3141-4efe-a0ee-daff9b56b8c5.png)

`GET` request
![image](https://user-images.githubusercontent.com/70527344/223532810-e923e1a8-60e7-45bc-9c0b-c08326346366.png)

This happens for the manifest, audio tracks and video tracks (for all qualities).

**What did you expect to happen?**
For all the requests to the CDN that come out of the player to have CMCD data, even the ones using `HEAD` method.

**What actually happened?**

When a URL with no extension (eg.: no `.m3u8`) is tested, a HEAD request is made to the server, these `HEAD` requests do not contain CMCD data in the URL (as queryparams). This causes the (our validator) app to report an error.

We would like to understand if this behaviour is intended or was missed when implementing CMCD in the player. What i mean is, is this actually a bug or was CMCD data is purposely not being sent in those requests?

We believe that CMCD is useful in these kind of requests, as the CDN could potentially decide whether to server from a different location to the user based on the size of the file requested.

---

### Additional information

This issue (#3142) is related to what i'm trying to report here.

The CMCD validator is an open-source project, proposed by Will Law at the Monte`<video>` Tech meetup and developed by Qualabs (organizer of the meetup). You can find the repository here: https://github.com/montevideo-tech/cmcd-validator/

It would be a good idea to at least send a CMCD sessionID with the `HEAD` requests, if you want to track all the requests made by the player.

**Comment by avelad** [comment]
@littlespex can you review it? Thanks!
