### ISSUE TITLE
Support for frameRate in Resolution Selection UI

### ISSUE THREAD

**Issue by ImVexed** [shaka-project/shaka-player#5068]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
v4.3.5

**Please ask your question**
From what I can see in https://github.com/shaka-project/shaka-player/blob/main/ui/resolution_selection.js there seems to be no consideration of the variant's frameRate when decide what variant's to de-duplicate as well as include in the menu.

Is there any way that I'm missing to include for example `1080p` and `1080p60` in the resolution drop down if I have 2 variants that are both 1080?

**Comment by avelad** [comment]
Right now this is not possible. Please, there will be an improvement type issue, and a priority will be assigned to it. Thanks!
