### ISSUE TITLE
Enabling WebVTT Segmented Subtitles in HLS fails on first try. Works on second intent.

### ISSUE THREAD

**Issue by Peterdoo** [shaka-project/shaka-player#5076]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
v4.3.5 (uncompiled)

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
shaka-player-demo.appspot.com

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Windows 11, Chrome 110.0 x64

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

[HLS with fragmented WebVTT subtitles](https://www.fab-online.com/kgbzkjvhjfvd.m3u8)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

shaka-player-demo.appspot.com

**What did you do?**

Start playing. Enable subtitles (Svenska).

**What did you expect to happen?**
Subtitles should start displaying.
On the second intent enabling the subtitles, the subtitles are displayed, however without the styling information from the WebVTT init segment. STYLE from the WebVTT init segment should be processed in the same way as Shaka-Player does when STYLE is present in the WebVTT text format.

**What actually happened?**

After enabling subtitles (Svenska), the player loads the subtitle playlist (.m3u8), the WebVTT init segment (.mp4) and the first WebVTT subtitle segment (.m4s). Then it reports the error "Shaka Error TEXT.INVALID_TEXT_HEADER ()". No subtitles are displayed.

On the second intent enabling the same subtitles, the subtitles are displayed.
However they are displayed without the styling information from the WebVTT init segment. STYLE from the WebVTT init segment should be processed in the same way as Shaka-Player does when STYLE is present in the WebVTT text format.

**Comment by avelad** [comment]
@Peterdoo I tried your stream in localhost and I get a 403, can you review?
<img width="1508" alt="Captura de pantalla 2023-03-21 a las 11 27 30" src="https://user-images.githubusercontent.com/8983024/226579954-fdfb0d36-1192-4ce6-8d35-947b63a1df06.png">

**Comment by Peterdoo** [comment]
@avelad It seems to be a CORS problem. I have modified it a bit. Please try again.

**Comment by avelad** [comment]
Bug reproduced! I will try to work on solving it in the next few days, thanks for your wait.

**Comment by Peterdoo** [comment]
You might want to try the other HLS stream as well:
[HLS with various subtitle types ](https://www.fab-online.com/kgbzkjvhjfvf.m3u8)

Here it does not help activating it various times. Only the text VTT works. The other two do not work, although they work when they are the only subtitles present without the other two.
