### ISSUE TITLE
"Welcome" tutorial link for Java 14+ links to Java 8

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#5077]
The link to download Java has changed, and Oracle now serves a page recommending the installation of JRE 8 for some reason.  The link needs to be updated.

**Comment by iprasandeep** [comment]
Hi! @joeyparrish, Could I resolve this issue?

**Comment by joeyparrish** [comment]
@iprasandeep, PRs are always welcome.  Thanks!
