### ISSUE TITLE
[DASH] Shaka does not toggle playbackRate back to 1 after loading some manifests

### ISSUE THREAD

**Issue by martinstark** [shaka-project/shaka-player#5092]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Firefox, Linux

**What are the manifest and license server URIs?**
https://f53accc45b7aded64ed8085068f31881.egress.mediapackage-vod.eu-north-1.amazonaws.com/out/v1/6dfccb0406c74fa3ac21d262db7384b1/64651f16da554640930b7ce2cd9f758b/66d211307b7d43d3bd515a3bfb654e1c/manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default

**What did you do?**
To visualise the scenario through the demo app, please follow each step:

1. Open the Shaka Demo Player, create a custom content entry with [the manifest](https://f53accc45b7aded64ed8085068f31881.egress.mediapackage-vod.eu-north-1.amazonaws.com/out/v1/6dfccb0406c74fa3ac21d262db7384b1/64651f16da554640930b7ce2cd9f758b/66d211307b7d43d3bd515a3bfb654e1c/manifest.mpd).
2. press play, so that the video window opens, the video will likely start playing due to `autoplay`
3. inspect the video window and remove the `autoplay=""` parameter from the DOM video element
4. right click and select "use in console" to get the video element saved as `temp0` in the console
5. add an event listener through the console: `temp0.addEventListener("ratechange", () => console.log("ratechange to", temp0.playbackRate))`. This allows us to detect when shaka toggles `playbackRate` when buffering during the initial load
6. optionally clear the console
7. press play on the custom content entry created previously
8. the first frame of the video should appear, it should not autoplay
9. watch only a single `ratechange` log appear in the console. Inspecting `temp0.playbackRate` will return `0`. Shaka never returns `playbackRate` to 1. A manual `play` request is needed before shaka realizes its mistake and recovers the `playbackRate`.

**What did you expect to happen?**
Shaka should toggle playbackRate to 0 while buffering, and toggle it back to 1 after it is done buffering.

It does this with most other manifests, e.g. if you repeat the above steps with [bitmovin dash sample](https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd) there will be two `ratechange` logs in the console, for playbackRate 0 and playbackRate 1.

**What actually happened?**
Shaka does not toggle the `playbackRate` back to 1 until a manual `play` request is made.

**Notes**

This is problematic in scenarios where you want to build external controls on top of Shaka. Shaka will trigger LOADED immediately, but the video element will not yet have triggered `canplaythrough` to indicate that there's any buffer to start playing.

I understand that the Shaka team can't necessarily keep external tools in mind, but this is also problematic in scenarios that may want to avoid using Shaka's event interface to track playback state. [media-event-filter](https://github.com/Eyevinn/media-event-filter) is affected by this issue, a library which relies on detecting when Shaka is done buffering via the MSE `ratechange` event. The event never arriving leaves the filter in "loading" limbo, since shaka never indicates that it has managed to finish buffering.

**Comment by avelad** [comment]
In the latest versions we have stopped using playbackRate to control buffering, can you check if the problem no longer happens in version 4.6.2 or in the main branch? Thanks!
