### ISSUE TITLE
Caption sync issues in HLS manifests with #EXT-X-DISCONTINUITY

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#5096]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
nightly

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
probably

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Edge, macOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Sent in email in regards to question https://github.com/shaka-project/shaka-player/issues/5087

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default

**What did you do?**

Play the manifest url provided in email, in the demo app, select captions -> Svenska
There should be some preroll ads, when the program starts, the captions will be out of sync

**What did you expect to happen?**
Captions should be in sync after ad breaks

**What actually happened?**

Manifest contains #EXT-X-DISCONTINUITY which should signal when sync should be reset, it seems like it's not working properly.

It wasn't an issue before the rewrite to use sequenceMode for HLS, so it works in 3.3.18, the same content also plays fine in other players (hls.js) with no caption sync issues.

**Comment by avelad** [comment]
@fredrik-telia are you interested on send a PR to fix it? Thanks!
