### ISSUE TITLE
Improve AbrManager's `restrictToElementSize` and `restrictToScreenSize` functionality

### ISSUE THREAD

**Issue by fernandoneira** [shaka-project/shaka-player#5101]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**Is your feature request related to a problem? Please describe.**

We have looked into using the `restrictToElementSize` functionality but realised that it deviates from our expectation of how such a feature should work that we can't use it in its current definition. 

I believe this and `restrictToScreenSize` functionality can be improved by redefining how they are calculated and with a slight change in definition - at the cost of a breaking change.

Our problem in short is that the current implementation invariably leads to upscaling, which compromises quality.

For a visual example, given 4 variants with different resolutions, the current solution will filter out any variant strictly bigger in size. This achieves the goal of not wasting bandwidth, but it does penalise quality since the variant chosen is upscaled.

<img width="350" alt="Screenshot 2023-03-17 at 14 52 23" src="https://user-images.githubusercontent.com/9033927/225926509-f1b669f2-71c8-4e4a-ba4a-6a3c5765dfec.png">

**Describe the solution you'd like**

I propose a solution where AbrManager should, if available, choose a variant that is bigger than the dimensions of the video element, but the lowest at that.
This achieves the goal without upscaling, hence not compromising quality.

<img width="350" alt="Screenshot 2023-03-17 at 14 51 53" src="https://user-images.githubusercontent.com/9033927/225928286-7b9a7621-214c-43ba-9a13-7c55062d4d99.png">

I sketched a proposed implementation as follows:

- Add a `selectionCriteria` enum property to AbrConfig with these values:
	- `bandwidth`, `bandwidthAndElementSize`, `bandwidthAndScreenSize`
- Add an `applySelectionCriteria`  function to `StreamUtils` to be used by `SimpleAbrManager` and custom AbrManagers. 
	- This function takes a list of variants (ordered or not) and a `selectionCriteria`, outputs one variant (`selectionCriteria` is read from config).
	- Depending on the value uses one algorithm to select the variant:
		- `bandwidth`: current implementation, picks one according to available bandwidth estimations
		- `bandwidthAndElementSize`: picks one according to available bandwidth estimations and video element size (avoid unnecessarily big resolutions but also upscaling where possible)
		- `bandwidthAndScreenSize`: picks one according to available bandwidth estimations and screen size (avoid unnecessarily big resolutions but also upscaling where possible).
- Modify `ChooseVariant` steps from these:
	([`variants`]) -> `apply restrictions` -> select variant based on bandwidth estimates -> (`variant`)
  to these:
	([`variants`]) -> `apply restrictions` -> `apply selection criteria` -> (`variant`) 

The current `restrictToElementSize` and `restrictToScreenSize` booleans can then be marked as deprecated in favour of the `selectionCriteria` enum, and eventually removed alongside its underlying implementation.

**Describe alternatives you've considered**

Since the `AbrManager` is a point for extension, we can make a custom `AbrManager` that implements this behaviour. I do believe this improvement is useful for other users of shaka, which we would not share with this approach, and it also means duplicating a fair amount of `SimpleAbrManager` functionality in order to make a custom `AbrManager`, given its current structure.

Something that would make it easier to customize `AbrManager` selection criteria without modifying the current `AbrConfig` and with minimal changes on AbrManager would be to make that an extension point in itself, so we can customize that without making an entire custom `AbrManager`.

**Comment by avelad** [comment]
@fernandoneira are you interested on send a PR for it? I agree with your proposal :) thanks!

**Comment by fernandoneira** [comment]
hey @avelad, thanks for the feedback! I don't have a PR currently planned, but I don't discard spending some time on this at some point, provided this makes sense for folks.
