### ISSUE TITLE
Infinity buffering in Chrome on iOS

### ISSUE THREAD

**Issue by NoChance777** [shaka-project/shaka-player#5109]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest master

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Own app

**If custom app, can you reproduce the issue using our demo app?**
I have not tried

**What browser and OS are you using?**
Chrome 111.0.5563.72 on iOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Everything by default, apart 
```javascript
{ 
   useNativeHlsOnSafari?: true;
   preferNativeHls?: true;
}
```

**What did you do?**
I tried to play HLS based video stream with DRM protection, and get `buffering` event only once which indicates that player is in buffering state and never get another event. If I call `play` on videoElement, player starts playback without any issue

**What did you expect to happen?**
Player signals that it has enough buffer to play and changes its state to `buffering=false`

**What actually happened?**
Player never leaves buffering state. I tried to debug the issue and found that in `pollBufferState_` method this.video_.buffered.length is 0 all the time and doesn't change its value.

**Comment by avelad** [comment]
Can you check if it's still happening on the main branch? thanks!
