### ISSUE TITLE
Exiting fullscreen on iOS Safari stops video

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#5111]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

Latest

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Happens on demo also

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

iOS, Safari (iPhone)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Start video in iOS. Enter fullscreen. Exit fullscreen. 

**What did you expect to happen?**

Video resumes playing after exiting fullscreen. 

**What actually happened?**

Video stops; you have to press play to restart it.

**Comment by avelad** [comment]
This is the behavior that Safari applies by default when using the fullscreen element of the video.

**Comment by Andekas** [comment]
Strange, but so it is. Even YouTube works the same way.
