### ISSUE TITLE
Can't find seekRange early enough to use it for updateStartTime

### ISSUE THREAD

**Issue by Wayne-Morgan** [shaka-project/shaka-player#5115]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
YEs

**What browser and OS are you using?**
Chrome Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

The issue isn't specific to a manifest

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

The issue isn't specific to a config

**What did you do?**

Try to use `player.updateStartTime()` to set a start time relative to the seekRange. `updateStartTime()` must be called in the `manifestparsed` listener, but `seekRange()` does not return a valid range until later (until `player.fullyLoaded_`).

I can access the internal manifest representation, but this is not recommended. Alternatively I can `updateStartTime(0)` and allow the player to jump to the start, but it would be good to be able to access the seekRange at this point.

**What did you expect to happen?**
`seekRange()` to return a valid range in the `manifestparsed` event.

**What actually happened?**

`seekrange` returns `{'start': 0, 'end': 0}`

**Comment by avelad** [comment]
The behavior has been changed with https://github.com/shaka-project/shaka-player/pull/4590, @theodab since the PR that changes it is yours, can you review this issue?
