### ISSUE TITLE
Support for <ServiceDescription> in MPD describing Low Latency params

### ISSUE THREAD

**Issue by david-hm-morgan** [shaka-project/shaka-player#5121]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Ywa

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.4

**Please ask your question**
DASH.js has support for ServiceDescription and the Low Latency parameters within it as described in https://dashif.org/docs/CR-Low-Latency-Live-r8.pdf
<img width="558" alt="image" src="https://user-images.githubusercontent.com/37144605/227627364-21aca222-cab8-4e4f-adb8-edef0deea57f.png">

Is there any plan for Shaka Player to introduce support for it?

**Comment by david-hm-morgan** [comment]
FYI @Wayne-Morgan

**Comment by adgllorente** [comment]
Implemented in #5394
