### ISSUE TITLE
Back navigation time increases after several minutes of watching

### ISSUE THREAD

**Issue by lenchis001** [shaka-project/shaka-player#5122]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.2.13

**Can you reproduce the issue with our latest release version?**
Yes. I tried 4.3.5 - the issue can be reproduced there.

**Can you reproduce the issue with the latest code from `main`?**
Yes. I tried version from commit 2b333159c344dcd7c39d65e384435563dad741a8 - the issue can be reproduced there.

**Are you using the demo app or your own custom app?**
I use custom app. Link: https://github.com/lenchis001/shaka-player-flutter-demo.git

**If custom app, can you reproduce the issue using our demo app?**
I cannot use demo app since the issue reproducing requires running from Flutter WEB application.

**What browser and OS are you using?**
Tizen 6.0 (5.0 (SMART-TV; LINUX; Tizen 6.0) AppleWebKit/537.36 (KHTML, like Gecko) 76.0.3809.146/6.0 TV Safari/537.36)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Model: UE43AU7192UXXH
Firmaware: T-KSU2EDEUC-2111.1

**What are the manifest and license server URIs?**
https://storage.googleapis.com/shaka-demo-assets/tos-ttml/dash.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
I use default configuration.
getConfiguration() result:
```
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "servers": {},
    "clearKeys": {},
    "advanced": {},
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1,
    "preferredKeySystems": [],
    "persistentLicenseEnabled": false
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "disableThumbnails": false,
    "defaultPresentationDelay": 0,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "disableXlinkProcessing": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false,
      "ignoreMaxSegmentDuration": false,
      "keySystemsByURI": {
        "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
        "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
        "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
        "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
      }
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "ignoreImageStreamFailures": false,
      "useFullSegmentsForStartTime": false
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 30000,
      "stallTimeout": 5000,
      "connectionTimeout": 10000
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 10,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "gapDetectionThreshold": 0.5,
    "smallGapLimit": 0.5,
    "jumpLargeGaps": false,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2,
    "lowLatencyMode": false,
    "autoLowLatencyMode": false,
    "forceHTTPS": false,
    "preferNativeHls": false,
    "updateIntervalSeconds": 1
  },
  "offline": {
    "usePersistentLicense": true
  },
  "abr": {
    "enabled": true,
    "useNetworkInformation": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    }
  },
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "preferredVideoCodecs": [],
  "preferredAudioCodecs": [],
  "preferForcedSubs": false,
  "preferredDecodingAttributes": [],
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null
}
```

**What did you do?**
I use sample from: https://github.com/lenchis001/shaka-player-flutter-demo.git
I build and installed the app on Tizen TV using "build.sh" script. 

> Case 1.
> 
> 1. Run the sample app on TV device.
> 2. Click on the first tile at "grid page" using remote to start playback of the mentioned stream.<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15190316/227929123-e4bc7ab3-bd34-4761-8135-72174ece47ba.png">
> 3. Wait for 8 seconds.
> 4. Click back button using remote to go back.

> Case 2.
> 
> 1. Run the sample app on TV device.
> 2. Click on the first tile at "grid page" using remote to start playback of the mentioned stream.<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15190316/227929123-e4bc7ab3-bd34-4761-8135-72174ece47ba.png">
> 3. Wait for 8 minutes.
> 4. Click back button using remote to go back.

**What did you expect to happen?**
Back navigation time (from click "back" button on remote to appearing "grid" page) should be the same in both cases. 

**What actually happened?**

In case of 8 sec watching, back navigation takes about 2.54 sec:
| Run 1 | Run 2 | Run 3 | Average |
|-------|-------|-------|----------|
| 2.6   | 2.57  | 2.45  | 2.54     |

In case of 8 min watching, back navigation takes about 3.12 sec:
| Run 1 | Run 2 | Run 3 | Average |
|-------|-------|-------|----------|
| 3.1   | 3.05  | 3.2  | 3.12     |

As you see back navigation time increased. (0.58 sec. longer in seconds case.)

**Comment by avelad** [comment]
Can you check again against the main branch? Thanks!
