### ISSUE TITLE
On DRM failure, re-initiate playback with secondary DRM if available

### ISSUE THREAD

**Issue by kirandcunha-wbd** [shaka-project/shaka-player#5124]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Smart TVs generally support multiple DRMs (Widevine and Playready). Our analysis data throws up multiple DRM related errors on these even though there is a support for a particular DRM. Tests related to manual switching to second DRM on failure have yielded positive results 

**Describe the solution you'd like**

If there is a 6xxx error, and there is another DRM configured, then initiate playback using second DRM. Maybe this can be controlled by a flag
`player.configure({
  drm: {
    allowSecondaryDrmFallback: true
  }
});`

**Describe alternatives you've considered**

Manually catching 6xxx errors and retrying playback

**Additional context**

**Comment by joeyparrish** [comment]
This is not feasible without tearing down the entire playback stack.
