### ISSUE TITLE
How to customize UiConfig with React/NextJs => Unrecognized value happening

### ISSUE THREAD

**Issue by g-silva-oliveira** [shaka-project/shaka-player#5137]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)? Yes**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues? Yes**

**What version of Shaka Player are you using? 4.3.5** 

**Question**
Hi everyone
have been 1 month since I started with Shaka Player. I am not sure if i'm doing something wrong but i cloned the nextjs example and did try to create some custom button to let me skip videos, as the docs shows.

Doesn't work!

So, would be great if someone help me do that using NextJs + React function-components instead class-components. Don't need to be anything complex just that let me better understand how it works.

for VoD I am using this uiConfigs => 
```js
        const uiConfigs = {
            addSeekBar: true,
            controlPanelElements: [
                'play_pause',
                'mute',
                'volume',
                'time_and_duration',
                'spacer',
                'fullscreen',
                'quality',
                'picture_in_picture'
            ],
            volumeBarColors: {
                base: 'rgba(255, 255, 255, 0.3)',
                level: 'rgb(0, 96, 173)'
            },
            doubleClickForFullscreen: true,
            seekBarColors: {
                base: 'rgba(255, 255, 255, 0.3)',
                played: '#e93035',
                adBreaks: 'rgb(255, 204, 0)'
            },
            singleClickForPlayAndPause: true,
        }
```

**Comment by g-silva-oliveira** [comment]
Don't need to be 'skip', could be something easiest like that issue 'rewind 10' that let the user skip 10 seconds of the video.

**Comment by WINOFFRG** [comment]
Hi! 

Please note that all the other framework/library examples mentioned in the docs are unofficial, They have been listed by the users. They could be buggy or outdated! Do take a look at versions before using or try creating issues in their respective repos.

For creating custom elements for Shaka Player, you would need to bind your own logic. Take a look at [Creating custom elements and adding them to the UI
](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html) this should be pretty much same in React!

As a side note, Also take a look at https://github.com/WINOFFRG/limeplay/ This Limeplay UI Library! I have been working on, This is currently in development but you can take a look at implementation to get an idea how this is all done natively in React.

Do ⭐ the library for updates, With upcoming updates you can easily create such custom buttons with just few lines of codes without worrying about underlying player logic! Example: Skip Button, Next Button ...

**Comment by g-silva-oliveira** [comment]
> 
> For creating custom elements for Shaka Player, you would need to bind your own logic. Take a look at [Creating custom elements and adding them to the UI ](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html) this should be pretty much same in React!
> 

I did exactly what the documentation ask to do and still, it doesn't work.
even if I do just an event that will throw a message in the console, the custom element never is created.
So i asked this question here to help me and others who want to understand how to make some element with reactJs

**Comment by WINOFFRG** [comment]
I see, Can you share more details like error message, or code snippets? That would help debug the issue.

**Comment by g-silva-oliveira** [comment]
> I see, Can you share more details like error message, or code snippets? That would help debug the issue.

You can just follow the documentation and you will be able to see a console warning `Unrecognized control panel element requested: your_custom_button` and the button will not appear.
