### ISSUE TITLE
Two CRITICAL errors reported in a row

### ISSUE THREAD

**Issue by cristian-atehortua** [shaka-project/shaka-player#5150]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome Version 112.0.5615.49 (Official Build) (64-bit)
Ubuntu 20.04.6 LTS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A (But should be also replicable)

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default in DEMO app

**What did you do?**

1. Play the content
2. Block all segments request (For the content above, put this url `storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/v-*p-*k-libx264-s*.mp4` to be blocked in Chrome DevTools)
3. Wait for a little

**What did you expect to happen?**
The playback crashes with a SINGLE error after trying to select all variants.

**What actually happened?**

The playback crashes throwing two errors:
4012 - RESTICTIONS_CANNOT_BE_MET
1002 - HTTP_ERROR

This looks like is happening because, on the recovery logic that Shaka has when an error is detected, when there are no more variants to select, the player throws the first error (because there are no selectable variants) but the function that tries to recover returns `false` when no variant is found, causing the original error to be also forwarded to applications.

**Comment by zangue** [comment]
I think this also relates to #5055 and should be fixed in #5057
