### ISSUE TITLE
while playing content, When User Fast Forwards post the Adpods Player screen is freezed and only Audio output is heard (Ad timer runs in background )

### ISSUE THREAD

**Issue by sushmadvg** [shaka-project/shaka-player#5152]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
No as the issue reproducible with ads

**What browser and OS are you using?**
Safari Version 8 and Linux OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
xclass smarttv 
User Agent -Mozilla/5.0 (Linux; x86_64 GNU/Linux) AppleWebKit/601.1 (KHTML, like Gecko) Version/8.0 Safari/601.1 WPE partnerId:comcast

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
Launch application
Play any content
while playing content, When User Fast Forwards post the Adpods Player screen is freezed and only Audio output is heard (Ad timer runs in background )

**What did you expect to happen?**
Ad should play normally without any freeze post FF

**What actually happened?**
while playing content, When User Fast Forwards post the Adpods Player screen is freezed and only Audio output is heard (Ad timer runs in background ) this we are facing in shaka version above 3.0 version

**Comment by avelad** [comment]
Can you test again with the latest release (4.4.2)? Thanks!
