### ISSUE TITLE
Error Unexpected number of arguments for .drm.initDataTransform

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#5163]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.0.2

**Please ask your question**
I got problem with DRM video.
Everything work perfect on Safari browser on Mac Book, Mac Book Pro, Mac Mini. But when play on Safari on Mac OS virtual machine on Vmware Work Station 17 Player, it keeps  warning "**Unexpected number of arguments for .drm.initDataTransform**" and the video is not played. There's also no error thrown so I don't know why.

Version of Mac OS on Vmware: 12.5 Monterey
Version of Safari: 15.6
Already tried to upgrade to Mac OS Ventura, or downgrade to Big Sur, but the same problem occurs.

I guess the code is inside these lines, but can't determine where it is:

          this.player.configure(
            'drm.initDataTransform',
            (initData, initDataType) => {
              if (initDataType !== 'skd') return initData
              const skdUri =
                shaka.util.StringUtils.fromBytesAutoDetect(initData)
              urlSearchParams = new URLSearchParams(new URL(skdUri)?.search)
              const contentId =
                shaka.util.FairPlayUtils.defaultGetContentId(initData)
              const cert = this.player.drmInfo().serverCertificate
              return shaka.util.FairPlayUtils.initDataTransform(
                initData,
                contentId,
                cert
              )
            }
          )

Please advise how I can solve this problem. Thank you.

**Comment by vanminhquangtri** [comment]
I also tested the drm video on Vmware Mac OS on Microsoft Edege, it works. So I think the problem is not from Vmware. Any advice?

**Comment by zangue** [comment]
@vanminhquangtri The `initDataTransform` callback function expects 3 arguments (looks like the tutorial in the doc is outdated). The third argument is `drmInfo` of type [`?shaka.extern.DrmInfo`](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.DrmInfo). Updating your code as follow should fix the issue:
```js
this.player.configure(
  'drm.initDataTransform',
  (initData, initDataType, drmInfo) => {
    if (initDataType !== 'skd') return initData
    const skdUri =
      shaka.util.StringUtils.fromBytesAutoDetect(initData)
    urlSearchParams = new URLSearchParams(new URL(skdUri)?.search)
    const contentId =
      shaka.util.FairPlayUtils.defaultGetContentId(initData)
    // or just drmInfo.serverCertificate
    const cert = this.player.drmInfo().serverCertificate
    return shaka.util.FairPlayUtils.initDataTransform(
      initData,
      contentId,
      cert
    )
  }
)
```

**Comment by vanminhquangtri** [comment]
@zangue thanks for your advice.
after applying your solution, I got error 3016 as attached. 

![Screenshot_2](https://user-images.githubusercontent.com/70369658/233889547-36570568-79db-4a63-a26c-04e669fe32c0.png)

**Comment by zangue** [comment]
@vanminhquangtri From the errors thrown I can only assume that you're not providing the server certificate with your DRM configuration are you? To provide a server certificate for FairPlay you can do the following:
```js
player.configure(
  'drm.advanced.com\\.apple\\.fps.serverCertificateUri', 'https://example.com/cert.der');
```
For more details take a look at the "Server Certificate" section from the [docs/tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html)

**Comment by vanminhquangtri** [comment]
@zangue thanks for your advice. In fact, I already added the cert server. 
My app work perfectly on Safari on real Mac OS. So I think the problem is not from my codes.
The problem only happens when I use Safari on virtual machine VMware. Maybe this is something relate to hardware.

**Comment by joeyparrish** [comment]
Yes, DRM often does not work correctly in VMs.  This is outside of our control at the player level.

The docs for initDataTransform have been corrected.  Thanks!
