### ISSUE TITLE
Video playing error in Firefox

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#5165]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

Latest

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

Windows, Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://router.euddn.net/f79adceedc96855c1c045be3ab05a542/smil:8301/2023/04/19/eveliis_kiiver_cWASjdQx/play_hd.smil/playlist.m3u8?c=8000;panel=CUSTOM%20CONTENT;build=compiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Demo app

**What did you do?**

Tried to play the video. 

**What did you expect to happen?**
Video to play

**What actually happened?**

Video keeps loading. This same video works in player v 4.3.2 , but not in 4.3.5

**Comment by avelad** [comment]
Can you check again against the main branch? Thanks!

**Comment by Andekas** [comment]
Hi! Yes, this works on main, but not on latest release (or Shaka live demo page).

**Comment by avelad** [comment]
Thanks for your info. I’m going to close the issue. Thanks!

**Comment by avelad** [comment]
Yes, we will publish the fix in the 4.4.0 version.
