### ISSUE TITLE
Firefox can't play dash manifest file created by shaka packager

### ISSUE THREAD

**Issue by cli-ish** [shaka-project/shaka-player#5171]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.3.x

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Custom app

**If custom app, can you reproduce the issue using our demo app?**

Not available

**What browser and OS are you using?**

Firefox 112.0.1 (64-Bit)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
MPD Source:
```
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated with https://github.com/google/shaka-packager version v2.6.1-634af65-release-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" minBufferTime="PT2S" type="static" mediaPresentationDuration="PT537.4666748046875S">
  <Period id="0">
    <AdaptationSet id="0" contentType="video" maxWidth="640" maxHeight="480" frameRate="15360/1024" par="39:16">
      <Representation id="0" bandwidth="501265" codecs="avc1.f40016" mimeType="video/mp4" sar="1947:1064" width="640" height="480">
        <BaseURL>file1.mp4</BaseURL>
        <SegmentBase indexRange="895-1334" timescale="15360">
          <Initialization range="0-894"/>
        </SegmentBase>
      </Representation>
      <Representation id="1" bandwidth="297608" codecs="avc1.f40015" mimeType="video/mp4" sar="1947:1064" width="480" height="360">
        <BaseURL>file2.mp4</BaseURL>
        <SegmentBase indexRange="896-1335" timescale="15360">
          <Initialization range="0-895"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="1" contentType="audio" subsegmentAlignment="true">
      <Representation id="2" bandwidth="3101" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="44100">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="1"/>
        <BaseURL>audio.mp4</BaseURL>
        <SegmentBase indexRange="826-1937" timescale="44100">
          <Initialization range="0-825"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```js
<script>
        const manifestUri ='manifest.mpd';

        async function init() {
            const video = document.getElementById('video');
            const ui = video['ui'];
            const controls = ui.getControls();
            const player = controls.getPlayer();
            window.player = player;
            window.ui = ui;

            const config = {
            };
            ui.configure(config);
            player.addEventListener('error', onPlayerErrorEvent);
            controls.addEventListener('error', onUIErrorEvent);

            try {
                await player.load(manifestUri, null, 'application/dash+xml');
                console.log('The video has now been loaded!');
            } catch (error) {
                onPlayerError(error);
            }
        }

        function onPlayerErrorEvent(errorEvent) {
            onPlayerError(event.detail);
        }

        function onPlayerError(error) {
            console.error('Error code', error.code, 'object', error);
        }

        function onUIErrorEvent(errorEvent) {
            onPlayerError(event.detail);
        }

        function initFailed(errorEvent) {
            console.error('Unable to load the UI library!');
        }
        document.addEventListener('shaka-ui-loaded', init);
        document.addEventListener('shaka-ui-load-failed', initFailed);
    </script>
```

**What did you do?**
Embeded the manifest, played unter firefox.

**What did you expect to happen?**
Video to play since its created with the shaka packager.

**What actually happened?**
I get the Javascript error:
```
Error code 4032 object 
Object { severity: 2, category: 4, code: 4032, data: [], handled: false }
```
which refers to `CONTENT_UNSUPPORTED_BY_BROWSER`.
This manifest works in Google Chrome 112.0.5615.138 without any problems.

Firefox:
```
video.canPlayType('video/mp4; codecs="avc1.f40015"');
"" 
```

Chrome:
```
video.canPlayType('video/mp4; codecs="avc1.f40015"');
'maybe'
```

Is there a way to ensure that the shaka packager manifest is created to support all browsers?

**Comment by joeyparrish** [comment]
I think this is working as intended.  The browser is telling you it can't play the container and/or codec of your content.  canPlayType() agrees with the results Shaka Player gets.

Perhaps there is some Firefox config that is set incorrectly?  Try resetting your flags.

You skipped the part of the template that asks for your OS.  Perhaps you're missing some OS-level functionality that Firefox wants to use to demux mp4 or decode H264?  Many years ago, it was the case that Firefox needed some optional deps installed on Linux to play fmp4.  That may still be the case today.

I hope this helps!

**Comment by cli-ish** [comment]
I tested this with `Windows 10 Pro` i did not configure anything different than the default config for firefox aswell. Some manifest work which get generated from shaka packager, but they got different codecs.
A fresh installed version of firefox does have the same error at my side.

**Comment by joeyparrish** [comment]
> Some manifest work which get generated from shaka packager, but they got different codecs.

This indicates that something about the encoding is being rejected by Firefox.  The codec string indicates many details, including the H264 profile and level.  Your content may be encoded with a profile or level not supported by Firefox, and we can't do anything about that in the player.
