### ISSUE TITLE
While jumping forward in Video,segments are downloaded from start ,resulting buffer time.

### ISSUE THREAD

**Issue by vikrant-pratap** [shaka-project/shaka-player#5177]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

After transcoding the Video,the segments are listed in .m3u8 file and mentioned in Manifest file.While playing video,if i try to jump lets say 3.00 min,the video ll buffer and start downloading the segments in Order,till it reaches the media at 3.00.

Is there any way to access the segments randomly rather than in order?.
So that one can skip the video directly to the point he wants to see and does not incur buffer time?  
Is there any configuration on player level that can be done to allow random access of segments?

**Comment by joeyparrish** [comment]
That is not the intended behavior of the player.  That sounds like a bug.  Please file an issue using the bug template and provide all the information requested in the template.  Thanks!
