### ISSUE TITLE
Make CEA parser & decoder as plugins

### ISSUE THREAD

**Issue by tykus160** [shaka-project/shaka-player#5178]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Shaka currently has plugin system, i.e. to decide in individual build shall some text parsers be included. However, it doesn't work like that for closed captions - all of related parsers etc. are attached to the core build. If someone doesn't need TS parser or captions at all, he needs to live with that.

**Describe the solution you'd like**

Prepare plugin registry similar to text parsers plugins:

1. `shaka.cea.ICeaParser/ICeaDecoder`:
 - change to externs

2. `shaka.media.ClosedCaptionParser`:
 - add static exported methods for adding, removing and getting CEA Parser/Decoder plugins
 - get proper parser by a MIME type from plugin registry
 - fallback to `shaka.cea.DummyCeaParser/Decoder` if can not find plugin

3. `shaka.cea.Mp4CeaParser/TsCeaParser/CeaDecoder`:
 - register as a plugin (using static methods mentioned above)
 - exclude from `@core`

**Describe alternatives you've considered**

Forking and removing unneeded dependencies manually.

**Additional context**

I did some experiments already and I'm happy to work on that if Shaka team thinks this idea is valuable for the project.

**Comment by avelad** [comment]
For me it's ok!

**Comment by joeyparrish** [comment]
Sounds good.  Thanks!
