### ISSUE TITLE
Shaka throws the DRM.EXPIRED error playing a channel with server-side advertisement insertion

### ISSUE THREAD

**Issue by FelipeAndresLopez** [shaka-project/shaka-player#5199]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** v4.3.5 (uncompiled)

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `main`?** Yes

**Are you using the demo app or your own custom app?** Demo app and custom app

**If custom app, can you reproduce the issue using our demo app?** Yes

**What browser and OS are you using?** MacOS Ventura 13.3.1 and Chrome/112.0.0.0 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?** N/A

**What are the manifest and license server URIs?** I sent you by email.

**What configuration are you using?  What is the output of `player.getConfiguration()`?** the default configuration

**What did you do?**
1. I set the parameters like manifest, license server URL, and an authorization header (this information was provided by email) for playing a channel in [Shaka Player Demo](https://shaka-player-demo.appspot.com/)
2. I played the channel that contains an advertisement at the beginning.
3. The playback started, and the channel displayed the advertisement and then the content.
This channel has a licensing system that is renewed every 2 minutes. 1 minute after the first license was renewed, Shaka started throwing the error [6014](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6014).
This error was thrown a few times as you can see in the image

![image](https://user-images.githubusercontent.com/53358802/234998951-d5f7359c-1e25-43c8-a4ca-fd51b46101c9.png)

This error didn't stop the content that was playing in Shaka Demo, but It does on the platform where we are using Shaka Player because It's an error and we are handling it.

We think that It's a problem related to Shaka because It's not happening with other players and platforms like iOS or Android. We also performed a test with another player like [dashif](https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html) and the channel works well.

**What did you expect to happen?**
 Shaka should not throw the error [6014](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6014).

**Comment by cristian-atehortua** [comment]
It's interesting that Shaka is sending two requests to the license server for each license request/renewal.

**Comment by avelad** [comment]
Can you check if the error still occurs in version 4.7.4? Thank you!
