### ISSUE TITLE
Make default displayers actual plugins

### ISSUE THREAD

**Issue by tykus160** [shaka-project/shaka-player#5200]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**Is your feature request related to a problem? Please describe.**

Shaka currently has plugin system, i.e. to decide in individual build shall some text parsers be included. However, it doesn't work like that for text diplayers - theoretically they are plugins, but they have strong dependency in core build. In custom build, when someone provides custom displayer there is currently no possibility to exclude default displayers and decrease bundle size.

**Describe the solution you'd like**

API proposal:
1. `shaka.text.TextEngine`:
 - add factory for default HTML-based displayer and default simple displayer
2. `shaka.extern.TextDisplayer`:
 - add method `attachVideo(video: HTMLMediaElement): void`
 - add method `attachContainer(container: HTMLElement): void`
3. `shaka.text.UITextDisplayer/SimpleTextDisplayer`:
 - remove parameters from constructors
 - move constructors' logic to new interface methods
 - exclude displayers from `@core`
4. `shaka.Player`
 - `defaultConfig_()`:
   - adjust default config logic for usage of default factories
   - fallback to dummy displayer implementation if no factories
 - `applyConfig_()`, `onInitializeMediaSourceEngine_()`
   - call new interface methods during displayer initialization
   - if methods are not provided, raise a warning about missing API implementation

**Describe alternatives you've considered**

Forking and removing unneeded dependencies manually.

**Additional context**

I'm happy to work on that if Shaka team thinks this idea is valuable for the project.

**Comment by tykus160** [comment]
EDIT: as text displayers are exported classes, constructor parameters cannot be easily dropped. I'd mark them as optional and call new methods in a constructor if they're provided.

**Comment by avelad** [comment]
For me it doesn't add much value, but I understand the purpose. Is anyone in the community interested in this?
