### ISSUE TITLE
ll-hls supported on shaka player but not chromecast?

### ISSUE THREAD

**Issue by aifeipeng** [shaka-project/shaka-player#5201]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
v3.2 I think

**Please ask your question**
As I have understood it shaka player is what is used by the chromecast receiver. Specifically shaka player v3.2.

From what I can tell when reading the docs and when I have tried shaka player on in my web application it can handle "low latency hls (ll-hls)". I have a "default/styled" chromecast app i.e I have not altered any logic on the the chromecast receiver, but it cannot handle my "low latency hls" stream (my regular hls stream works fine).

When reading in the chromecast documentation I could only find that it supports HLS it doesn't say anything about ll-hls.

I guess my question is what am I missing? Should the default chromecast handle ll-hls or do I need to build a "custom chromecast receiver"?

**Comment by avelad** [comment]
Hi @aifeipeng 

You can use https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.PlaybackConfig#shakaConfig to enable LL-HLS.
