### ISSUE TITLE
Possible to seek beyond live edge. Not corrected

### ISSUE THREAD

**Issue by Wayne-Morgan** [shaka-project/shaka-player#5202]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app, but also reproduced in demo

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Various, but reproduced on Windows Chrome with the demo app

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Reproduced with "Live Sim (2s segments)"

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Reproduced with default config

**What did you do?**
Seek beyond the seekable range, wait half a second, then do it again
```
const vidEl = document.getElementById("video");
vidEl.currentTime = vidEl.currentTime + 3600; 
setTimeout(()=>{vidEl.currentTime = vidEl.currentTime + 3600;}, 500);
```

**What did you expect to happen?**
The video to play from the live edge

**What actually happened?**
The player got stuck waiting.
I also tried seeking a smaller amount into the future (1 minute), and it recovered and started playing after a minute

The problem seems to be in `MediaSourcePlayhead.onSeeking_()` https://github.com/shaka-project/shaka-player/blob/a8e3c9ab310b14ca71610c568cffe108b30d38bf/lib/media/playhead.js#L409

The first seek out of range is corrected, but because the next happens within a second, the correction is simply discarded.

**Comment by CeilingFANC** [comment]
Encountered the same issue. 
I am interested on send a PR.

**Comment by joeyparrish** [comment]
Please do!  I'll assign the issue to you.

**Comment by avelad** [comment]
@CeilingFANC Are you still interested in submitting the PR? Thanks!

**Comment by CeilingFANC** [comment]
Yes. Just updated the test. How can I reopen the PR..

**Comment by avelad** [comment]
What PR?

**Comment by avelad** [comment]
@CeilingFANC I reopened your PR. Thanks!
