### ISSUE TITLE
How to correctly test Shaka with Jest + Enzyme

### ISSUE THREAD

**Issue by giancarlobrusca** [shaka-project/shaka-player#5206]
**What version of Shaka Player are you using?**
v4.3.5

**Please ask your question**
I'm having trouble testing the Shaka player in React using Jest + Enzyme. I've tried several ways to achieve it, but unfortunately, without success. I want to test a custom implementation I did to add trickplay to the player (i.e., show the corresponding thumbnails when hovering over the progress bar).

I want to clarify that this works perfectly in the browser when running the application, I have tested it extensively. The problem is with the unit test.

The error that I'm receiving right now is `TypeError: this.target.addEventListener is not a function`. This error is being thrown by the catch of the `player.load()` function (I logged the manifest, and it's okay). I'm not even able to get the player component to finish its render cycle and start playing the content.

The code of my test is:
```js
const flushPromises = () => new Promise(setImmediate);
const thumbnailSrc = "https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8";
test('Shaka trickplay', async () => {
	const wrapper = mount(<ShakaPlayer sources={{ src: thumbnailSrc, protData: {} }} />);

	wrapper.setProps(); // I added this just to see if it works. I also tried without this line
	wrapper.update(); // Same here
	await flushPromises(); // Same here

	const seekBarContainer = wrapper.find('.shaka-controls-container');
	const seekBar = seekBarContainer.find('.shaka-seek-bar-container');

	console.log(seekBar.html()); // --> This throws an error bc `seekBar` is falsy
})
```
The `flushPromises` function is something I grabbed from [this Stackoverflow answer](https://stackoverflow.com/a/51045733)

---

The code of my component is:
```js
function ShakaPlayer({ sources, playerId }) {
	const videoRef = React.useRef(null);
	const videoContainerRef = React.useRef(null);

	React.useEffect(() => {
		const manifestUri = sources.src;

		const video = videoRef.current;
		const videoContainer = videoContainerRef.current;

		const player = new shaka.Player(video);
		const ui = new shaka.ui.Overlay(player, videoContainer, video);

		const config = {
			overflowMenuButtons: ['quality', 'captions'],
		};

		ui.configure(config);

		player.load(manifestUri).then(async () => {
			// Doing stuff after load
		 }).catch((error) => {
			// Load interrupted
			console.log({ error }) // --> This is throwing the error mentioned above
		});

		return () => {
			if (player) {
				// Destroy player
				player.destroy();
			}
		};
	}, [playerId]);

	return (
		<div ref={videoContainerRef} className="video-container" style={{ position: 'relative' }}>
			<video ref={videoRef} className="shaka-video" style={{ width: '100%', height: '100%' }} autoPlay />
		</div>
	);
}

export default ShakaPlayer;
```

**Comment by joeyparrish** [comment]
> The error that I'm receiving right now is `TypeError: this.target.addEventListener is not a function`. This error is being thrown by the catch of the `player.load()` function (I logged the manifest, and it's okay). I'm not even able to get the player component to finish its render cycle and start playing the content.

I don't see addEventListener in your catch statement.  I would advise you to dig into the stack trace of that error to find the place where that occurs, and what `this.target` and `this` are at that time.  You should also try a debug build of Shaka Player, which is not fully minified.  See [the "Debugging" tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-debugging.html) for details.

Does this help?

**Comment by giancarlobrusca** [comment]
Thank you @joeyparrish for the quick response 😄. I will take a look at that _"Debugging" tutorial_ and see if I can track the cause of the error. I'll post an update here after that (if that's okay).

**Comment by joeyparrish** [comment]
Of course.  No problem.  If the issue goes stale, a robot will ping it, then eventually close, but with instructions on how to reopen if you need to.

**Comment by giancarlobrusca** [comment]
Hi @joeyparrish.

After testing the 'debug build' of Shaka Player, I encountered a new error that caught my attention.

`Shaka Player does not support this browser.`

It sounded like it could be a good lead, so I investigated what [Jest uses to create its 'test environment'](https://github.com/tom-sherman/blog/blob/main/posts/02-running-jest-tests-in-a-browser.md#the-unit-test-footgun). Apparently, Jest uses [JSDOM](https://github.com/jsdom/jsdom), which is not a proper browser. Could this be causing Shaka to not render correctly in the tests? I will investigate a possible solution.

**Comment by theodab** [comment]
The UI fires that error if [shaka.Player.isBrowserSupported](https://github.com/shaka-project/shaka-player/blob/fecb11a230fa4eff94c14986a31ae00021ef5674/lib/player.js#L956) returns false. That would 

I don't know much about JSDOM, but I wouldn't be too surprised if it lacked an API we use. I could imagine that a non-visual fake browser environment might lack something like `window.MediaKeys`, `window.navigator.requestMediaKeySystemAccess`, or `window.MediaSource`.
