### ISSUE TITLE
Shaka Player fails with decoder error

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-player#5212]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App also issue is reproducible

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Android OS, chrome browser
Device: Oppo F12, android 12 OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Shaka player demo widevine videos

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
shaka player hosted demo

**What did you do?**
Just play any widevine video from shaka player hosted demo

**What did you expect to happen?**
Video should play

**What actually happened?**
Video fails with error:
                exceptionTrace = {"severity":2,"category":3,"code":3016,"data":[4,null,"DECODER_ERROR_NOT_SUPPORTED: video decoder initialization failed"],"handled":false}

**Comment by sridhard** [comment]
This happens in few devices like OPPO F12

**Comment by sridhard** [comment]
Hi, how can we resolve this issue? any workaround?

Same issue is happening in other mobiles like moto edge 82.

**Comment by avelad** [comment]
Can you test again with the latest release (4.4.2)? Thanks
