### ISSUE TITLE
Can not Rewind / Seek back beyond 100 min

### ISSUE THREAD

**Issue by mraavi** [shaka-project/shaka-player#5218]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. I don't see any duplicate issue

**What version of Shaka Player are you using?**
v4.3.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome, Mac. But we are able to reproduce this on other OS and browsers too.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
As this is happening with Live recording, Can not provide actual URI as this is dymamic manifest

**What did you do?**

There is issue with Shaka player playing **Live recording (Dynamic manifest)** which is **more than 100 min**. Tested this with Dash players issue is not there.

If the Live recording duration is more than 1 hr 40 min (100 min) and if we try to play that recording before recording end time and after 1 hr 40 min then playback does not start from the beginning, it start from last 100th min (Current Time - 100 min).

For example,

Live Recording during is 2 hrs (120 min) which is started at 1 AM and ends at 3AM

If we try to play recording at 2.30 AM (90 min after recording started) then playback start from beginning of the recording (which is expected)

If we try to play recording at 2.40 AM (100 min after recording started) then playback start from beginning of the recording (which is expected)

But If we try to play recording at 2.50 AM (110 min after recording started) then it begins to play from 10th min instead of 0 min.

If we try to play recording at 1.50 AM (115 min after recording started) then it begins play from 15 mins instead of 0 min.

Also if we try to rewind or seek bar beyond 100 min from the current time, it can go back only till (current time - 100 min)

**What did you expect to happen?**
We should be able to Rewind and seek back beyond 100min

**Comment by avelad** [comment]
Can you change the `manifest.dash.initialSegmentLimit` config to a higher value and see if that works? Thanks!
