### ISSUE TITLE
3016 error on LG & Samsung devices for few HLS contents

### ISSUE THREAD

**Issue by pujantyagi2612** [shaka-project/shaka-player#5227]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
4.3.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome version (38 used by LG 2017 ) 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
   **Samsung 2017**
   Model : UA49MU6470
   Firmware version : T-KTMUABC-1310.1
  **LG 2017**
  Model :  43LJ554T-TA, WebOS : 3.9.2
 Firmware version : 06.10.35

**What are the manifest and license server URIs?**
Manifest URI:  https://hssportsprepack.akamaized.net/videos/cricket/null/1260140426/in/hin/v1/hevc/hls/plain/master_T833ndY7PdhuAlMM_sd.m3u8??hdnea=st=1563797919~exp=1684757919~acl=/*~hmac=b73630d6e7cd1743cade093da2ad5423fa3d3260b81b17a74d8f9cd4380dcaa0

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

1. Play this content on given LG & Samsung Devices
2. Video doesn't play & shaka throws 3016 error 
3. Same content plays in new LG & Samsung models

**What did you expect to happen?**
Playback to play without ay error

**What actually happened?**
Few HLS contents are throwing 3016 error on older devices/browsers.
Same content plays on newer devices .
While playing on chrome older version  , we see 
'Possible encoding problem detected!','Unexpected buffered range for reference'
Video doesn't play  here as well

**Comment by avelad** [comment]
Can you check again against the main branch? Thanks!
