### ISSUE TITLE
Random B/W Lines on LCEVC Playback Canvas

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#5229]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Windows 11, Google Chrome Version 112.0.5615.138 (Official Build) (64-bit)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://dyctis843rxh5.cloudfront.net/vnIAZIaowG1K7qOt/master.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Demo App Default Config

**What did you do?**

Playing the Demo Content
https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://dyctis843rxh5.cloudfront.net/vnIAZIaowG1K7qOt/master.m3u8;panel=HOME;build=uncompiled

**What did you expect to happen?**

**What actually happened?**

Random Oscillating B/W Lines and Boxes appear to be there on the Video. Here below is the video:

https://github.com/shaka-project/shaka-player/assets/61311751/2dbcbc4a-4391-400d-8f19-c54e1463a066

**Comment by avelad** [comment]
@v-nova-vinod can you help here? Thanks!

**Comment by vinod-balakrishnan** [comment]
@WINOFFRG @avelad  The oscillating lines are the debug enhancements which are baked into this stream as a demo to showcase the technology. 

This is in-fact stream specific, and any other valid LCEVC stream won't have debug enhancements but actual enhancements with the exact same version of the player.

We are soon going to raise another PR into shaka player with more demo contents showcasing LCEVC on different streaming and containers formats.

Please let me know if you have any further questions.

**Comment by WINOFFRG** [comment]
Thanks for the confirmation. Makes sense! Just one more thing, As illustrated and explained here https://www.v-nova.com/lcevc-enhanced-video regarding the enhancements that LCEVC brings. I tried comparing the sample playback with the standard one, there didn't appeared to be any difference. Also, from just an M3U8 how does LCEVC infer logic rearding the enhancements that it propose's to bring on? This goes a little in theory, Please drop any references (if any) regarding this which I can possibly refer to get a bit more deeper understanding of MPEG5.

Thanks!

**Comment by vinod-balakrishnan** [comment]
The enhancements are part of the video stream and not the manifest. The `Lcevc` decoder looks for these enhancements and applies them on the base video. It needs to be a stream that was encoded by an `Lcevc` encoder for you to be able to see LCEVC Enhancement on the decoded stream.  If a stream without LCEVC enhancements is given to an LCEVC Decoder, it is backwards compatible and will decode the base video.
For reference on the codec itself : [lcevc.org ](https://www.lcevc.org/)

**Comment by WINOFFRG** [comment]
Understood, Thanks again for your time!
