### ISSUE TITLE
preferredVideoCodecs and preferredAudioCodecs config does not work after the player is loaded

### ISSUE THREAD

**Issue by pedrotari7** [shaka-project/shaka-player#5231]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
No

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome and MacOs

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

- Load a player
- Play some media
- call `player.configure` with either the preferredVideoCodecs or preferredAudioCodecs keys

**What did you expect to happen?**
This sequence of events used to result in the codecs to switch to the selected ones in the preferred codecs array.

**What actually happened?**

When changing the config after the player has been configured and loaded prevents the preferred codecs to be switched. Note that we can still configure the preferred codecs in the initial configuration, but unfortunately not "at runtime".

**Comment by avelad** [comment]
This is the defined behavior because we do not reset the SourceBuffer to make a different codec selection.
