### ISSUE TITLE
Switch from audio+video to audio-only playback without reloading

### ISSUE THREAD

**Issue by AnmolGupta2112** [shaka-project/shaka-player#5237]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**  Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**What version of Shaka Player are you using?** 4.3.5

**Please ask your question** 
Is there a way to extract only audio segment from a mp4 or ismv manifest and play through shaka player? I have a video+audio manifest and want to switch to only audio dynamically if the user selects only audio option from UI. The video fragments should not load in this situation so the bandwidth consuption is low.

**Comment by AnmolGupta2112** [comment]
> Watching! This will be a great addition, to switch a Video to Audio only mode without interrupting the loading. I encountered this use case while designing Youtube Player theme for https://limeplay.me where I want to implement A/V Switching.

Hi Winoffrg, can you please let us know if you have solution for this issue?

**Comment by joeyparrish** [comment]
Currently we do not have any support for switching from video+audio to audio-only.  It's not on our roadmap, and we (at Google) don't have any plan for this.  But if anyone would like to work on it and send a PR, this would involve removing SourceBuffers from MediaSource.  You would want to make some changes in MediaSourceEngine and possibly also StreamingEngine.

**Comment by AnmolGupta2112** [comment]
> Currently we do not have any support for switching from video+audio to audio-only. It's not on our roadmap, and we (at Google) don't have any plan for this. But if anyone would like to work on it and send a PR, this would involve removing SourceBuffers from MediaSource. You would want to make some changes in MediaSourceEngine and possibly also StreamingEngine.

Hi Joey,
I would like to work on it could you please help me by sharing any link or document which have some code information about SourceBuffers,  MediaSource, MediaSourceEngine and StreamingEngine.

**Comment by avelad** [comment]
This can be done and with the latest changes it is easy.
Audio+Video --> audio only --> Removes the media state from the audio and removes the source buffer from the audio. (There are no change for the user, the transition is smooth)
Audio Only --> Audio+Video --> We need to reset MSE (we already have features for this) (the transition is not smooth)

So the change seems reasonable.

**Comment by avelad** [comment]
@AnmolGupta2112 Do you have an HLS stream that has this combination so I can work on it? Thank you!
