### ISSUE TITLE
seekRange().start is going back and forth while start-over (reopen of #3571)

### ISSUE THREAD

**Issue by SivanA-Kaltura** [shaka-project/shaka-player#5244]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.3

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
macOS Monterey 12.5
Google Chrome 113.0.5672.126

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Can provide if necessary

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Load the start-over stream and observe the seekRange().start

**What did you expect to happen?**
seekRange().start is fixed (as the start of the dvr window is fixed)

**What actually happened?**

(note that this is the same issue as ticket #3571 - as the reporting user no longer has access to the ticket, i am reopening it with my name)

seekRange().start is going back and forth between the manifest loadings.

Normally, we expect this value to either be fixed (if the start position of the dvr window is fixed) or to increase (if the start of the dvr window moves forward). In this case, the value is actually fixed, but shaka shows it as cycling back and forth between several values (see below).

On our app:
![image](https://github.com/shaka-project/shaka-player/assets/88330203/c514c347-afab-4a6e-a822-18462f8ba3de)

On Shaka demo page:
![image](https://github.com/shaka-project/shaka-player/assets/88330203/2cd2eb26-fdb2-4fa5-a11b-1787f67a458e)

**Comment by SivanA-Kaltura** [comment]
Hi, did you get to take a look at this issue ?

**Comment by joeyparrish** [comment]
> **What are the manifest and license server URIs?**
>
>Can provide if necessary

Quoting the issue template:

```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.
```
