### ISSUE TITLE
HLS + Fairplay does not try to retrieve certificate or license

### ISSUE THREAD

**Issue by jigfox** [shaka-project/shaka-player#5245]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes

**What version of Shaka Player are you using?**

4.3.6

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**

custom

**If custom app, can you reproduce the issue using our demo app?**

Not available, wasn't able to configure the demo to our settings

**What browser and OS are you using?**

macOS 13.4 with Safari 16.5

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

not applicable

**What are the manifest and license server URIs?**

Will be send via email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```json
{
  "drm": {
    "advanced": {
      "com.apple.fps": {
        "serverCertificateUri": "https://example.com/certificate"
      }
    },
    "servers": {
      "com.apple.fps": "https://example.com/license"
    }
  }
}
```

**What did you do?**

```js
player.configure({
  "drm": {
    "advanced": {
      "com.apple.fps": {
        "serverCertificateUri": "https://example.com/certificate"
      }
    },
    "servers": {
      "com.apple.fps": "https://example.com/license"
    }
  }
});
player.getNetworkingEngine().registerRequestFilter((type, request) => {
  if (type === shaka.net.NetworkingEngine.RequestType.LICENSE) {
    request.headers['custom-token'] = 'some-jwt-token';
  }
});
player.load("https://example.com/manifest.m3u8")
```

**What did you expect to happen?**

Shaka Player should make a call to retrieve the certificate and a license and play the content

**What actually happened?**

No call to fetch certificate or license is made. the request filter isn't called too. Shake emits an error event with code `6010` (`ENCRYPTED_CONTENT_WITHOUT_DRM_INFO`)

**Comment by avelad** [comment]
I tested some EZDRM protected content with Fairplay and it works without problems.
