### ISSUE TITLE
Playback of DASH linear stream with SSAI stops in ad break on Samsung Smart TV 

### ISSUE THREAD

**Issue by sobbe81** [shaka-project/shaka-player#5246]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
4.3.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Samsung Smart TV / Tizen

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
All models

**What are the manifest and license server URIs?**
I will send this separately.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
1. Play linear DASH stream with SSAI
2. Wait for an ad break

**What did you expect to happen?**
Ad break should play without any issues

**What actually happened?**
The player plays one or a couple of adverts and then it stops and shows a spinner. Sometimes is starts playing again after a while. This only happens on Samsung Smart TV. Our desktop web page and chrome cast receiver both using Shaka can play this without any issues.

**Comment by sobbe81** [comment]
Hi,

Any updates on this issue?

Regards,
Martin

**Comment by avelad** [comment]
Can you test if the problem persists on the main branch? Thank you!

**Comment by sobbe81** [comment]
The issue still exists

**Comment by avelad** [comment]
Can you check if the error still occurs in version 4.7.4? Thank you!
