### ISSUE TITLE
When using Shaka Player UI, Seeking multiple times bug the player

### ISSUE THREAD

**Issue by MarianoFacundoArch** [shaka-project/shaka-player#5248]
Using last version of shaka player on a video content, when seeking (by moving the mouse while clicked and then releasing) multiple times get the player ui stucked as if it was playing (pause button is shown, so clicking play doesnt do anything)
It's easy to repeat when scrolling multiple times and ending into the position 0 of the video.

This happens in chrome, it's like the UI is not getting updated in the pause event when it comes from a seeking result sometimes.

With native controls, this does not happen.

I already tried removing all our custom ui code and leaving only the default code to only load the custom shaka player ui library without any customization, and it still happens.

**Comment by MarianoFacundoArch** [comment]
It only happens if you seek in the video by keeping the click held down while dragging the position of the video, and when you release the click, that's where it occurs. If you do simple clicks to seek, it doesn't happen.

**Comment by avelad** [comment]
@MarianoFacundoArch are you interested on send a PR to fix it?
