### ISSUE TITLE
MSS failure in nightly demo with MIME type "mss/video/mp4"

### ISSUE THREAD

**Issue by unext-wendong** [shaka-project/shaka-player#5250]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.3.6-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57

**What did you do?**
1. Goto the shaka-player-demo page above.
2. Create a custom content with the following info:
Manifest URL: https://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest
Name: Smooth Test
3. Click "PLAY".

**What did you expect to happen?**
The stream starts playing.

**What actually happened?**
Playback didn't start and the following error message showed up:
```
[Shaka Error MANIFEST.UNABLE_TO_GUESS_MANIFEST_TYPE (https://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:4000)
```

Logs from the console:
```
Starting load of https://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest...
Could not determine manifest type using MIME type  application/vnd.ms-sstr+xml
Could not find extension for  https://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest
The walker saw an error:
Error Code: 4000
shaka.util.Error {severity: 2, category: 4, code: 4000, data: Array(1), handled: false, …}
```

**Comment by unext-wendong** [comment]
Ah, my bad. I didn't realize it's not in the latest release yet.

With the nightly build, the player is able to recognize the manifest type.

However, now it errors out with the following code.
```
[Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()]
```

Logs in console:
```
MediaCapabilities.decodingInfo() failed. {"type":"media-source","video":{"contentType":"mss/video/mp4; codecs=\"avc1.640028\"","width":1920,"height":1080,"bitrate":5995983,"framerate":1},"audio":{"contentType":"mss/audio/mp4; codecs=\"mp4a.40.2\"","channels":2,"bitrate":125653,"samplerate":44100,"spatialRendering":false}} TypeError: Failed to execute 'decodingInfo' on 'MediaCapabilities': The video configuration dictionary is not valid.
    at MediaCapabilities.probeDecodingInfo_ [as decodingInfo] (index.js:280:64)
    at shaka.util.StreamUtils.getDecodingInfosForVariant_ (stream_utils.js:559:47)
    at shaka.util.StreamUtils.getDecodingInfosForVariants (stream_utils.js:599:38)
    at shaka.media.DrmEngine.init_ (drm_engine.js:392:34)
    at shaka.media.DrmEngine.initForPlayback (drm_engine.js:273:17)
    at shaka.Player.onInitializeDrm_ (player.js:2009:27)
    at player.js:686:22
    at Object.enterNode (player.js:712:16)
    at shaka.routing.Walker.takeNextStep_ (walker.js:340:48)
    at shaka.routing.Walker.doOneThing_ (walker.js:227:19)
```

The browser itself should be fine because the content with the same video/audio sets but in DASH format plays fine:
https://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest(format=mpd-time-csf)

My environment:
Browser: Edge, Version 113.0.1774.57 (Official build) (64-bit)
OS: Windows 11 Pro, 22H2

I can create another issue ticket for this if needed as it's a different issue.

**Comment by joeyparrish** [comment]
Thanks for trying!  I'll just rename/reuse this issue and assign to @avelad.  Are we missing some MIME type transformation for MSS?

**Comment by avelad** [comment]
I’ll try to review it tomorrow

**Comment by avelad** [comment]
I tested with main branch and it works fine! I don't see any problem.

**Comment by unext-wendong** [comment]
@avelad 
I can still reproduce it on the latest nightly build `v4.3.6-main-18-gf0ee16bdb (uncompiled)`.

From the console log I shared, the video/audio content types passed to `MediaCapabilities.decodingInfo` start with `mss/`. Is that expected?

Let me know if you need any other information for further investigation.

**Comment by joeyparrish** [comment]
@avelad has deployed the nightly demo early, so the fix should be live now.  Thanks!

**Comment by unext-wendong** [comment]
Thanks you.
Confirmed that the playback now works on the nightly build.

Wow, Shaka Player is getting more and more powerful. So good to see that. Thank you.
