### ISSUE TITLE
DASH: Getting uncaught (in promise) TypeError when Manifest is dropping during playback

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [shaka-project/shaka-player#5259]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
No, tested only using v4.3.x branch

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
I believe so

**What browser and OS are you using?**
Chrome Windows / MacOS

**What did you do?**

During normal DASH playback, we were trying to simulate Manifest requests dropping and how the player reacts to it. However, sometimes this piece of code throws an exception:

https://github.com/shaka-project/shaka-player/blob/562831bbc65c66e1eb68715afed0c07874aeb81d/lib/player.js#L6096-L6103

<img width="694" alt="image" src="https://github.com/shaka-project/shaka-player/assets/96475496/bea424f3-e453-4c84-b54c-883edb8145c3">

**Comment by avelad** [comment]
Can you check again against the main branch? Thanks!
