### ISSUE TITLE
Support through Managed MSE

### ISSUE THREAD

**Issue by niklaskorz** [shaka-project/shaka-player#5271]
**Is your feature request related to a problem? Please describe.**

shaka-player currently only works on iOS by making use of its native HLS support.

**Describe the solution you'd like**

With iOS 17, Safari will introduce support for "Managed MSE" on all platforms, including the previously unsupported iPhone. It appears to mostly be a drop-in replacement for MSE, except that data ranges inside a ManagedSourceBuffer may be removed by the browser, for example due to memory constraints or to increase battery life.

Resources:

- WWDC 2023: https://developer.apple.com/wwdc23/10122 (starting at 8:00)

Unfortunately, I have yet to find a formal specification for this "Managed MSE" API outside of the WWDC 2023 video.

**Comment by avelad** [comment]
See: https://github.com/w3c/media-source/issues/320

**Comment by niklaskorz** [comment]
Looking at https://github.com/video-dev/hls.js/pull/5542, the required amount of work seems to be manageable.

**Comment by avelad** [comment]
@niklaskorz are you interested on send a PR for it?

**Comment by niklaskorz** [comment]
@avelad I am! I'm on vacation soon (June 23rd to July 14th) but afterwards I'll gladly start working on this.
