### ISSUE TITLE
Unable to play videos on iOS 17

### ISSUE THREAD

**Issue by chejen** [shaka-project/shaka-player#5272]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
- YES

**What version of Shaka Player are you using?**
- v4.3.6 (uncompiled)

**Can you reproduce the issue with our latest release version?**

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
- Browser: Safari
- OS: iOS 17.0

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

1. Navigate to the official demo site: https://shaka-player-demo.appspot.com/
2. Play available videos on the demo site.

**What did you expect to happen?**
- The videos can be played back on all kinds of devices.

**What actually happened?**

- It works with Safari on iOS 15 and 16.
- It doesn't work with Safari on iOS 17.

**Comment by bill42362** [comment]
seems working after iOS17-beta2

**Comment by avelad** [comment]
Fixed in iOS17-beta2!
