### ISSUE TITLE
Unable to playback SSAI HLS stream

### ISSUE THREAD

**Issue by jaskarancodes** [shaka-project/shaka-player#5287]
https://github.com/shaka-project/shaka-player/assets/34194550/2ed62ce1-9112-4b6b-a46e-9ce67dc0b4a6

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://v3-3-19-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://dai-gcp-eu-west-1-1.daiconnect.com/live/hls/usp/scte35-stable/.m3u8?filter=%28type!=%22textstream%22%29;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v3.3.19-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**What did you do?**

1. Run Shaka v3.3.19 demo player
2. Playback sample SSAI stream shared by [provider](https://demo.unified-streaming.com/k8s/live-scte35-aip/#!/HLS) and load the [manifest url](https://dai-gcp-eu-west-1-1.daiconnect.com/live/hls/usp/scte35-stable/.m3u8?filter=%28type!=%22textstream%22%29)

**What did you expect to happen?**
Playback to work smoothly, without stalls.

**What actually happened?**

The playback is stuck and doesn't recover. Check the video attached in the description

**Comment by avelad** [comment]
You can try one of the supported versions and see if the same problem occurs https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md ?

**Comment by jaskarancodes** [comment]
@avelad Shaka 4.x series works on source buffer sequence mode and it might work fine on the web (Chrome) but it breaks when we try to play Shaka 4.x on WebLR (Samsung/LG/Xbox/PS) devices. We face audio loss and video skip issues (tried out multiple variants including the latest one) therefore we went ahead with shaka 3.x

**Comment by avelad** [comment]
You can use  the config `manifest.hls.sequenceMode=false` to enable segments mode in HLS

**Comment by avelad** [comment]
Note: Versions 3.x are no longer maintained.

**Comment by jaskarancodes** [comment]
@avelad We had tried out with the  `manifest.hls.sequenceMode=false `  config as well, but the playback doesn't start in that case and we get the following error. 

![Screenshot 2023-06-12 at 8 16 21 PM](https://github.com/shaka-project/shaka-player/assets/34194550/208e556b-cc96-46d6-9eaa-2b49f20fdcbf)

**Comment by avelad** [comment]
I tested your stream `https://dai-gcp-eu-west-1-1.daiconnect.com/live/hls/usp/scte35-stable/.m3u8?filter=%28type!=%22textstream%22%29` in the main branch and works fine. See https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;uilang=es-ES;asset=https://dai-gcp-eu-west-1-1.daiconnect.com/live/hls/usp/scte35-stable/.m3u8?filter=%28type!=%22textstream%22%29;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by jaskarancodes** [comment]
Thanks @avelad !!! Is there something I can help with ? You can point me in the correct direction, I can also explore and contribute.

**Comment by jaskarancodes** [comment]
Thanks for sharing this info. Since you tagged this as a P2 issue, can we expect a fix in a couple of days?

**Comment by vinodkputta** [comment]
@joeyparrish @theodab Could you please review it once? Thanks

**Comment by WINOFFRG** [comment]
@jaskarancodes Can you please specify on which device/browser does the stream fail for you? Also, Sequence Mode is disabled by default in 4.3.X and is preferably used for containerless formats on HLS. I tested the above stream on my devices

1. Windows 11 / Chrome 144
2. MacOS Catalina / Chrome 144

And the Ad Playaback worked fine (doesn't stall) for me on both the devices. Not sure till the issue is specific to WebLR Devices.  

![image](https://github.com/shaka-project/shaka-player/assets/61311751/f709cf33-6b01-4860-a87d-b30b8dc030b9)

**Comment by avelad** [comment]
We've recently fixed a lot of issues with HLS, can you check again against the main branch? Thanks!

**Comment by jaskarancodes** [comment]
@avelad The issue persists. If we run v4.3.7 with sequence mode we are getting A/V loss on the LR devices (Samsung and WebOS), and if we run with segments mode we are still getting the encoding errors.

**Comment by joeyparrish** [comment]
Then we will be best served by trying to find the cause of the AV sync issues.  Does the content use EXT-X-PROGRAM-DATE-TIME, and if so, is it millisecond-accurate as it is supposed to be?
