### ISSUE TITLE
What is persistentState exactly mean ??

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#5308]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes: I read here https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.DrmSupportType

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.0.2

**Please ask your question**
I use `shaka.Player.probeSupport()` to get list of drm on the browser. Some of them are null, some have object which is {persistentState: boolean}. I see that if it is null, playready is not supported.

I don't understand exactly what is persistentState? I can't find a clear article on the Internet.
And what if it is false, what if it is true?
Whether the device support playready if persistentState = false?
This is very important to me, because the user can only buy some DRM content if their browser suport playready. So I expect to get a clear explanation.
Thank you.

![image](https://github.com/shaka-project/shaka-player/assets/70369658/461badea-5f38-4bc1-9117-b8b8b65569ae)

**Comment by WINOFFRG** [comment]
A DRM License which can be saved in simple language. persistence can help play protected videos even when offline. If a licence is persistsed means it has been saved in a storage and might have some expiration depending upon the configs. In above image `persistentState: boolean` shows if the device supports any DRM Provider also is the browser compatible to persist the license, If yes you may then be able to persists it if the provider allows
. 
https://learn.microsoft.com/en-us/playready/overview/license-persistence

**Comment by vanminhquangtri** [comment]
@WINOFFRG thank you for your useful response and explanation.
