### ISSUE TITLE
Infinite buffering until .play on iOS 

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#5314]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.6

**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `main`?**
No

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
iOS, v16.3, Chrome, Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

Manifest: https://embed-cloudfront.wistia.com/deliveries/4a77e940176149046375a5036dbf2f7f01ce3a59.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default Configuration

**What did you do?**

1. Visit https://limeplay.me [Source](https://github.com/WINOFFRG/limeplay/blob/main/packages/limeplay-core/src/hooks/)
2. Wait for few seconds, Nothing Happens
3. Click on Spinner (Hidden Play Button) the video starts to load.

**What did you expect to happen?**
Instead of `video.readyState` being stuck at 1 it should have loaded the segments. I checked the devtools and only see the request for manifest. Rather the plyaer should have start loading the chunks and update the `readyState` as well as `buffering` state.

**What actually happened?**

I just played the video on limeplay.me and I see it getting loaded. In my developer environement I see `player.isBuffering()` to be always true. As soon as I click on play button in the middle of spinner the hidden play button the video starts to play and `video.readyState` changes from 1 to 4.

![image](https://github.com/shaka-project/shaka-player/assets/61311751/8feaae37-c972-42ef-9c96-4363cad990a9)

Note: Please ignore the other errors like `Unhandled Promise Rejection`  in screenshot as they are from another instance, The video is playing fine until clicked.

**Comment by WINOFFRG** [comment]
The issue can be debugged [here](https://limeplay-git-migration-winoffrg.vercel.app/) on this deployment [Source](https://github.com/WINOFFRG/limeplay/tree/30d4ec046aeb162bea29c496f14593418941854b/packages/limeplay-core/src/hooks)

`window.player` exists to interact with the shaka player object.

**Comment by WINOFFRG** [comment]
Hello @joeyparrish Can you please have a look at this issue when you get time.

**Comment by joeyparrish** [comment]
On iOS, we don't control fetching the media.  We are forced to use native HLS on iOS, where the browser controls fetching media.  So we have no way to directly influence the readyState or when segments are fetched in this environment.

There may be a way to fix the buffering detection for iOS, since we don't actually control buffering.  PRs are welcome!

**Comment by WINOFFRG** [comment]
Understood, Thanks! I tried debugging `player.js` to check if events are being fired properly, However couldn't debug much because of Browserstack limitations in console for iOS Device. 

Can you please confirm one thing, Shouldn't we also listen for [Loading Event](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:LoadingEvent) to show the spinner? What if due to some reason loading is delayed or takes much long, for that.

https://github.com/shaka-project/shaka-player/blob/72e13c4b0629c658be3044df568d5ef0ae988f86/ui/controls.js#L954-L956

**Comment by avelad** [comment]
Maybe, related to https://github.com/shaka-project/shaka-player/issues/5109

**Comment by avelad** [comment]
Can you check if it's still happening on the main branch? thanks!
