### ISSUE TITLE
Unable to Fullscreen from PiP Mode on Mac & iPad

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#5317]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.6

**Please ask your question**
Why don't we exit PiP Mode for iOS Devices, I know iOS can't have custom controls that's we show native one. In case when user is already in PiP Mode and direclty clicks on FullScreen Button it should have also worked. 

https://github.com/shaka-project/shaka-player/blob/main/ui/controls.js#L594-L596

I tried to bring the above condition on top inside try block and that seemed to work fine for me on iOS on my custom app on both Safari and Chrome and iPad Chrome. However, this still fails on MacOS Desktop (Safari) and iPad (Safari). Giving me `webkitfullscreenerror` in an event. If I'm not wrong, on apple device before entering fullscreen they check if the action is from event or programmatic, Right? And only allow in case of events like click.

So, while we do click on fullscreen button -> Logically Exits PiP Mode -> Event Lost -> Logical Request Fullscreen 
Could this be the cause of failure? But again the question comes why didn't this fail in case of mobile and iPad (Chrome) as I did with mine.

https://github.com/shaka-project/shaka-player/assets/61311751/1081f3fe-fab8-4453-8382-1a3fcb82b88b

Also, if the above seems good a patch let me know, I'll raise a PR for the same.

**Comment by avelad** [comment]
@theodab can add you opinion here? Thanks!

**Comment by WINOFFRG** [comment]
@shaka-bot reopen

**Comment by avelad** [comment]
@WINOFFRG Is this question still active or have you resolved the issue?

**Comment by WINOFFRG** [comment]
Hello! Yes the issue is still active, further more I tested it with v4.3.9 it still persists and to add more in above issue, Once we exit PiP we can no longer enter it into again. Error details in screenshot below: 

`NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

![image](https://github.com/shaka-project/shaka-player/assets/61311751/1d58956c-eb8f-4a5b-88e3-7906addbf5e4)

**Comment by avelad** [comment]
I have tested with an iPhone 13 (real) with version 4.5 and the problem no longer occurs.
