### ISSUE TITLE
Attempting to run Shaka on Tizen2 (Samsung 2015, and 2016) causes a `InvalidAccessError: DOM Exception 15` when generating the license request

### ISSUE THREAD

**Issue by subhanahmed047** [shaka-project/shaka-player#5318]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.6

**Please ask your question**
I know quite a few people have tried to attempt this before me. I have been reading about tizen2 being weird in other issues such as [this](https://github.com/shaka-project/shaka-player/issues/813) and [this](https://github.com/shaka-project/shaka-player/pull/2449).

I apologise in advance is I'm being naive as I'm very new to the EME API and still trying to understand the flow of things. I'm getting the `InvalidAccessError: DOM Exception 15` specifically on [this line in the `patchedmediakeys_webkit.js` file ](https://github.com/shaka-project/shaka-player/blob/main/lib/polyfill/patchedmediakeys_webkit.js/#L718) when we are attempting to generate a license request. 

Upon some investigation, I've learnt that in order to generate the license request, the `generateKeyRequest` function needs the `initData`,  which comes from the `encrypted` event which is triggered when the media element detects the encrypted content (In the case of the webkit, we trigger the encrypted event [when the `needkey` event](https://github.com/shaka-project/shaka-player/blob/main/lib/polyfill/patchedmediakeys_webkit.js#L435) is triggered). However in this case I've noticed that the **encrypted event is never triggered**, but we still set `initData` in the [createOrLoad](https://github.com/shaka-project/shaka-player/blob/main/lib/media/drm_engine.js/#L677) function in the `drm_engine.js` file. 

I have a few questions regarding this behaviour:
1. How are we getting the `initDatas` before the `encryped` event is triggered (or without it being triggered at all)?
2. Is it possible that this data is faulty, causing the `generateKeyRequest` method to fail?

> Just before calling this method, I also see a warning `'HTMLMediaElement.webkitGenerateKeyRequest()' is deprecated.  Use 'MediaKeys.createSession()' instead.`,

**Comment by avelad** [comment]
Tizen 2 is supported by the community, we don't directly support it.
