### ISSUE TITLE
Is there a way that we can always display shaka control panel on page

### ISSUE THREAD

**Issue by praveenkumar215** [shaka-project/shaka-player#5321]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**What version of Shaka Player are you using?**

4.3.5
**Please ask your question**
Is there a way that we can always display shaka control panel, 
Currently on mouse out the Player controls get hided and appears once user hover on screen.
I want to show the all controls like seek bar, volume etc should be always visible on UI.

**Comment by WINOFFRG** [comment]
No Shaka Player doesn't have any such option in config to prevent controls from getting hidden. However, you can always fork and modify the UI as you need. There are few hacky ways using which you can prevent them from being hidden until or unless you are not wanting to modify the source.

1. UI Config has an option to set `fadeDelay` this number can be provided to set minimum delay until controls are hidden.
2. Controls are hidden via CSS by checking the `shown` attribute on `div.shaka-controls-container` so after delay `shown` attribute is removed and css sets the opactity to 0. Here this mutation observer will check if that attribute is removed it will force add it back. 

```js
const targetElement = document.querySelector('.shaka-controls-container');

const observer = new MutationObserver(function(mutations) {
  mutations.forEach(function(mutation) {
    if (mutation.type === 'attributes' && mutation.attributeName === 'shown' && !targetElement.hasAttribute('shown')) {
      targetElement.setAttribute('shown', 'true');
    }
  });
});

observer.observe(targetElement, { attributes: true });
```
