### ISSUE TITLE
Getting 3000 error code - MEDIA.BUFFER_READ_OUT_OF_BOUNDS issue with Closed Captions Rendering

### ISSUE THREAD

**Issue by Vasanthavanan-Devarajan** [shaka-project/shaka-player#5323]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**
4.3.4

**Can you reproduce the issue with our latest release version?**
Unable to reproduce with the latest

**Can you reproduce the issue with the latest code from `main`?**
NA

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Chrome and MAC OS 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen  TV 

**What are the manifest and license server URIs?**
NA

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
`'{"drm":{"retryParameters":{"maxAttempts":2,"baseDelay":1000,"backoffFactor":2,"fuzzFactor":0.5,"timeout":30000,"stallTimeout":30000,"connectionTimeout":30000},"servers":{"com.widevine.alpha":"https://widevine-proxy.api.rsm.firstlight.ai/getlicense?service=rsmedia&version=1.0&kid=E059F470-B1B4-470C-BF08-58DFA5620D1B&ptoken=eyJjb250ZW50SWQiOiJFMDU5RjQ3MC1CMUI0LTQ3MEMtQkYwOC01OERGQTU2MjBEMUIiLCJsaWNlbnNlRXhwaXJ5VGltZSI6MTY4Njk2Nzc2NTIyMSwiZW50aXRsZWRDb250ZW50SWRzIjoiUlRBMU9VWTBOekF0UWpGQ05DMDBOekJETFVKR01EZ3ROVGhFUmtFMU5qSXdSREZDIiwibWF4VXNlcyI6MSwic2lnbmF0dXJlIjoiODViY2I5ZTNkYmM0YTdjYzQ0NTdkYzBlMGNhMjI0NmQ4MjQ3YmEyMWY3NzUwYmUwOWMyZTJjYzllODFiZTEwZSIsInVuaXF1ZUlkIjoiZGVmYXVsdC10ZXN0LWRldmljZUlkLTAxIiwiaXNzdWVyIjoiU0lHTktFWV9QVE9LRU5fQ09OU1VNRV9JU1NVRVIiLCJhcGlLZXkiOiJhcGlLZXkiLCJrZXlWZXJzaW9uIjoidmVyczAxIiwiZXhwaXJ5VGltZSI6MTY4NjkyNDYyNTIyMSwiY3JlYXRlZFRpbWUiOjE2ODY5MjQ1NjUyMjEsInRva2VuTW9kZWxWZXJzaW9uIjoiVjMifQ=="},"clearKeys":{},"advanced":{"com.widevine.alpha":{"distinctiveIdentifierRequired":false,"persistentStateRequired":false,"videoRobustness":"","audioRobustness":"","sessionType":"","serverCertificate":{},"serverCertificateUri":"","individualizationServer":""}},"delayLicenseRequestUntilPlayed":false,"logLicenseExchange":false,"updateExpirationTime":1,"preferredKeySystems":[],"keySystemsMapping":{},"parseInbandPsshEnabled":false},"manifest":{"retryParameters":{"maxAttempts":2,"baseDelay":1000,"backoffFactor":2,"fuzzFactor":0.5,"timeout":30000,"stallTimeout":30000,"connectionTimeout":30000},"availabilityWindowOverride":null,"disableAudio":false,"disableVideo":false,"disableText":false,"disableThumbnails":false,"defaultPresentationDelay":0,"segmentRelativeVttTiming":true,"dash":{"clockSyncUri":"","ignoreDrmInfo":false,"disableXlinkProcessing":false,"xlinkFailGracefully":false,"ignoreMinBufferTime":true,"autoCorrectDrift":true,"initialSegmentLimit":1000,"ignoreSuggestedPresentationDelay":false,"ignoreEmptyAdaptationSet":false,"ignoreMaxSegmentDuration":false,"keySystemsByURI":{"urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b":"org.w3.clearkey","urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e":"org.w3.clearkey","urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed":"com.widevine.alpha","urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95":"com.microsoft.playready","urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95":"com.microsoft.playready","urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb":"com.adobe.primetime"},"sequenceMode":false},"hls":{"ignoreTextStreamFailures":false,"ignoreImageStreamFailures":false,"defaultAudioCodec":"mp4a.40.2","defaultVideoCodec":"avc1.42E01E","ignoreManifestProgramDateTime":false,"mediaPlaylistFullMimeType":"video/mp2t; codecs=\\"avc1.42E01E, mp4a.40.2\\"","useSafariBehaviorForLive":true,"liveSegmentsDelay":3}},"streaming":{"retryParameters":{"maxAttempts":2,"baseDelay":1000,"backoffFactor":2,"fuzzFactor":0.5,"timeout":30000,"stallTimeout":30000,"connectionTimeout":30000},"rebufferingGoal":6,"bufferingGoal":30,"bufferBehind":30,"ignoreTextStreamFailures":false,"alwaysStreamText":false,"startAtSegmentBoundary":false,"gapDetectionThreshold":0.5,"durationBackoff":1,"forceTransmux":false,"safeSeekOffset":5,"stallEnabled":true,"stallThreshold":1,"stallSkip":0.1,"useNativeHlsOnSafari":true,"inaccurateManifestTolerance":2,"lowLatencyMode":false,"autoLowLatencyMode":false,"forceHTTPS":false,"preferNativeHls":false,"updateIntervalSeconds":1,"dispatchAllEmsgBoxes":false,"observeQualityChanges":false,"maxDisabledTime":30,"parsePrftBox":false},"mediaSource":{"sourceBufferExtraFeatures":""},"offline":{"usePersistentLicense":true,"numberOfParallelDownloads":5},"abr":{"enabled":true,"useNetworkInformation":true,"defaultBandwidthEstimate":1000000,"switchInterval":8,"bandwidthUpgradeTarget":0.85,"bandwidthDowngradeTarget":0.95,"restrictions":{"minWidth":0,"maxWidth":null,"minHeight":0,"maxHeight":null,"minPixels":0,"maxPixels":null,"minFrameRate":0,"maxFrameRate":null,"minBandwidth":0,"maxBandwidth":null},"advanced":{"minTotalBytes":128000,"minBytes":16000,"fastHalfLife":2,"slowHalfLife":5},"restrictToElementSize":false,"restrictToScreenSize":false,"ignoreDevicePixelRatio":false},"autoShowText":3,"preferredAudioLanguage":"","preferredTextLanguage":"","preferredVariantRole":"","preferredTextRole":"","preferredAudioChannelCount":2,"preferredVideoCodecs":[],"preferredAudioCodecs":[],"preferForcedSubs":false,"preferredDecodingAttributes":[],"restrictions":{"minWidth":0,"maxWidth":null,"minHeight":0,"maxHeight":null,"minPixels":0,"maxPixels":null,"minFrameRate":0,"maxFrameRate":null,"minBandwidth":0,"maxBandwidth":null},"playRangeStart":0,"playRangeEnd":null,"cmcd":{"enabled":false,"sessionId":"","contentId":"","useHeaders":false},"lcevc":{"enabled":false,"dynamicPerformanceScaling":true,"logLevel":0,"drawLogo":false}}'`

**What did you do?**
NA

**What did you expect to happen?**
We assume this error is related to CC rendering, Could not we handle this gracefully without affecting the playback? 

**What actually happened?**
We have observed this on the production with the DAI-enabled live stream, at random intervals the error code 3000 - MEDIA.BUFFER_READ_OUT_OF_BOUNDS has been spiked up.  Sometimes it has affected the 20% of the streams. 
 
We noticed this was happening ever since we moved to shake player 4.3.4.  Since we are unable to reproduce the issue further inputs will be helpful. 

This issue predominantly occurs with Browsers and Tizen TV models only. 

When we check the shaka issues they said this issue has been resolved with shaka player V 4. X
FYI: https://github.com/shaka-project/shaka-player/issues/3659

**Comment by Vasanthavanan-Devarajan** [comment]
@joeyparrish @avelad Can you please look init this

**Comment by avelad** [comment]
Fixed with https://github.com/shaka-project/shaka-player/commit/f0ee16bdb35283e9543006c00ab45bf3ea06f002

**Comment by Vasanthavanan-Devarajan** [comment]
Since it's spiked on Shaka  V 4.3.4, Can we expect the above fix on the patch release for this issue on V 4.3.7?
