### ISSUE TITLE
Not showing sessionID in android browser

### ISSUE THREAD

**Issue by tuanbui53** [shaka-project/shaka-player#5331]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**

4.3.6
**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

Yes
**What browser and OS are you using?**
Chrome on Android 8.1.0

**What did you do?**

Connect my mobile with laptop using USB and turn on USB Debugging mode. Type chrome://inspect/#devices to open inspect - console. I also use EME logger to compare and got the same values.

Here is the code that I use in my player. It works fine to get license, play VOD and log sessionID on Desktop browers. 
 
`player.getNetworkingEngine().registerRequestFilter((type, request) => {
  if (type === shaka.net.NetworkingEngine.RequestType.LICENSE) {
      console.log('This sessionID: '+ request.sessionId);`

**What did you expect to happen?**
A hex sessionID should be shown similar as in Desktop Browsers. For example: 
`This sessionID: AFE19BD1151AF6F2DDE13F835EFEDC98`

**What actually happened?**

I didn't get correct sid value and in Desktop but: 
`This sessionID: sid1` 
or This sessionID: sid2,...., sid10 and so on.

So how do I solve this bug?
<img width="1262" alt="Screen Shot 2023-06-20 at 4 13 33 PM" src="https://github.com/shaka-project/shaka-player/assets/16971753/45079038-9788-4ebb-a030-646958059fe4">

<img width="750" alt="Screen Shot 2023-06-20 at 4 11 13 PM" src="https://github.com/shaka-project/shaka-player/assets/16971753/b7abefb8-9b70-4ef4-9fdb-758b2eaa5f9f">

**Comment by avelad** [comment]
@joeyparrish can you review it? Thanks!

**Comment by avelad** [comment]
For some unknown reason it also happens to me when I use non-persistent licenses. This is information that the CDM returns to the EME, so I consider this an external problem.
