### ISSUE TITLE
HLS: Add support for QUERYPARAM variable type in #EXT-X-DEFINE

### ISSUE THREAD

**Issue by duggaraju** [shaka-project/shaka-player#5333]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YEs

**Is your feature request related to a problem? Please describe.**

This is just the gap with the latest HLS spec.

**Describe the solution you'd like**

Per HLS spec: https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.2.3
QUERYPARAM

      The value is a quoted-string which specifies the Variable Name and
      indicates that its value is the value associated with the query
      parameter of the same name in the URI of the Playlist.  The valid
      character set for the quoted-string is the same as for the NAME
      attribute.  The value associated with the query parameter MUST be
      percent-decoded before performing the variable replacement.  The
      decoded value MUST NOT contain any of the characters disallowed in
      quoted-strings.

      If the QUERYPARAM attribute value does not match any query
      parameter in the URI or the matching parameter has no associated
      value, the parser MUST fail to parse the Playlist.  If more than
      one parameter matches, any of the associated values MAY be used.

      If the URI is redirected, the client MUST look for the query
      parameter in the 30x response URI.

**Describe alternatives you've considered**

Alternative would be writing a network plugin which will not work with native iOS playback.

**Additional context**

Requring a query string with token for authentication when playing HLS .  However for native playback (iOS) you would need to update manifest and either use a variable or rewrite the URLs.  With the queryparam approach you can substitute the variable outside with a query parameter.

**Comment by avelad** [comment]
@duggaraju are you interested in send a PR for it?

**Comment by avelad** [comment]
I'll work on this in a few days
