### ISSUE TITLE
restrictToElementSize and restrictToScreenSize should allow some upscaling

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#5335]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
main

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome stable Linux (currently 114)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```js
player.configure('abr.restrictToElementSize', true);
```

**What did you do?**

It seems that the `abr.restrictToElementSize` and `abr.restrictToScreenSize` configs have a flaw in the implementation.  It caps the stream resolution at the video element size, but there are two wrinkles to this:

1. Loading content can trigger a change in the video element size, once the stream's aspect ratio is known to the browser.  I'm not certain, but there could be an unhandled edge case where the resolution drops after playback begins because of this.  Anecdotally, this has happened to at least one adopter of Shaka within Google, causing them to avoid this feature.
2. The cap on resolution prevents all upscaling, but arguably _some_ upscaling is preferable to downscaling.  For example, if your resolution ladder is 240p, 480p, 720p, and the video element is 479 pixels tall, it would be *much* better to stream 480p than 240p.

I propose we modify the implementation of the restrictToElementSize config to "round up" when considering the element/screen size vs the list of streams.  Since the existing implementation is a simple cap, what I'm proposing would be all-new logic in the default AbrManager:

1. Compute a size limit that is the `min()` of the screen size (if restrictToScreenSize) and the element size (if restrictToElementSize).
2. Compare the size limit against the available streams.
3. Allow up to the smallest stream greater than or equal to the size limit.

I believe this would also resolve any issues with the resize triggered by the application of the stream's aspect ratio.

The current logic lives here:

https://github.com/shaka-project/shaka-player/blob/c1369de55dbd0c3d2f2631a033899e1d196d783e/lib/abr/simple_abr_manager.js#L175-L187

**Comment by avelad** [comment]
@joeyparrish see https://github.com/shaka-project/shaka-player/issues/5101 for me it pretty similar
