### ISSUE TITLE
Is there any way to disable FireFox browser Picture In Picture for Shaka Player

### ISSUE THREAD

**Issue by praveenkumar215** [shaka-project/shaka-player#5340]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**What version of Shaka Player are you using?**

4.3.5
**Please ask your question**
Is there any way to disable FireFox browser Picture In Picture for Shaka Player?
In Firefox the Picture In Picture option is creating problem specially for Semulive, so is there any option to hide PIP programmatically in Shaka.

**Comment by avelad** [comment]
As far as I know, there is currently (as of Firefox 72) no option for website authors to disable the button.

See:
https://support.mozilla.org/en-US/kb/about-picture-picture-firefox
https://support.mozilla.org/en-US/kb/turn-picture-picture-mode
