### ISSUE TITLE
Is video.duration or video.seekable via MSE in player control?

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#5360]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.7

**Please ask your question**
I have observed that for Live Streams, `video.duration` and `video.seekable` aren't correct. For a Live Stream shouldn't a duration mean LL Stream Window size? For example: [Stream 1](https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://livesim.dashif.org/livesim/segtimeline_1/utc_head/testpic_6s/Manifest.mpd;panel=ALL_CONTENT;panelData=LIVE;build=uncompiled;trickplay) Here `video.duration` is always `4294967296` not just for this but all streams. By duration should we either mean the `end` property or the window size. So, represented by either `Infinity` or `4s` example. 

This comes up when I check this https://github.com/shaka-project/shaka-player/blob/5487236668d1d5178dd287af78b47ea0a647ffa1/ui/fast_forward_button.js#L72-L75

Here for such live streams where the window size might be 0, We can still seek? I am aware that we can get `seekRange` via `$('video').ui.player_.seekRange()` but If the original properties are in control why to extend the API? If not then shouldn't the case be same with `duration` ? Since, the `Player` API doesnt expose any such property then either `video.duration` should be correct or we should have a function which returns us the window size which we will be checking on Trickplay.

I'm not sure if these props are under the control [docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/duration) If yes, They should be counted as bug if no then methods to get duration and window size should exist.

**Comment by avelad** [comment]
Those methods for Live do not work correctly, we have yet to implement https://github.com/shaka-project/shaka-player/issues/3153 to make the behavior correct for Live. Thanks!
