### ISSUE TITLE
Fullscreen does not work on iPad chrome.

### ISSUE THREAD

**Issue by papico-inf** [shaka-project/shaka-player#5383]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.3.7

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
IPadOS 16.5.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Click the player fullscreen button on the [demo site](https://shaka-player-demo.appspot.com/demo/#audiolang=ko-KR;textlang=ko-KR;uilang=ko-KR;asset=https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8;panel=HOME;build=uncompiled)

**What did you expect to happen?**
It will be fullscreen.

**What actually happened?**
Type error without going fullscreen
The error occurs only in chrome, it works fine in safari.

https://github.com/shaka-project/shaka-player/assets/109198271/96f7429e-1846-4f33-9c60-db53c6622f15

**Comment by WINOFFRG** [comment]
Tried in iPad 10th Gen, v16.0 Chrome. Couldn't replicate the same issue. Can you share logs from console in uncompiled mode?
