### ISSUE TITLE
Problem After calling Shaka Library we are getting extra text track having label "Shaka Player TextTrack" in textTracks which is read-only

### ISSUE THREAD

**Issue by praveenkumar215** [shaka-project/shaka-player#5389]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**What version of Shaka Player are you using?**

4.3.5
**Please ask your question**
After calling player.load in Video html control we are getting textTracks  with one length having label "Shaka Player TextTrack".
is there any way to remove this track?

**Comment by avelad** [comment]
This track is created automatically for the management of subtitles. There is no way to remove it. If you want there to be a way to eliminate it, please create an improvement issue so that it can be evaluated. Thanks!
