### ISSUE TITLE
PlayReady protected MSS fails in nightly demo on Edge

### ISSUE THREAD

**Issue by unext-wendong** [shaka-project/shaka-player#5390]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What link can we use to reproduce this?**
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.3.7-main-35-g6c71b0ee6-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67

**What did you do?**
1. Goto the shaka-player-demo nightly-built version from here.
https://index-dot-shaka-player-demo.appspot.com
2. Create a custom content with the following info:
Main->Manifest URL: https://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest
DRM->Custom License Server URL: https://playready.directtaps.net/pr/svc/rightsmanager.asmx
Name: Smooth PlayReady Test
3. Click "PLAY".

Content source:
https://github.com/androidx/media/blob/release-1.1.0/demos/main/src/main/assets/media.exolist.json#L264-L270

**What did you expect to happen?**
The stream starts playing.

**What actually happened?**
Playback didn't start and the following error message showed up:
```
Error code 3016
```
(No relevant error logs in the console)

**Additional info**
My environment:
Browser: Edge, Version 114.0.1823.67 (Official build) (64-bit)
OS: Windows 11 Pro, 22H2

The unprotected version of the same content works fine:
https://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest

**Comment by unext-wendong** [comment]
@avelad Ah, I see. But sorry I don't really have time to work on it this week.

If no one takes it, I can take a look later.

**Comment by avelad** [comment]
@unext-wendong I'm not going to be able to work on this in the next few months, I'm assigning the issue to you so you can create a PR.

**Comment by unext-wendong** [comment]
@avelad Will see if I can figure it out.

Btw, have we ever tried the PlayReady protected MSS playback?
It seems odd that the widely used sample content from Microsoft doesn't work.

**Comment by joeyparrish** [comment]
MSS support is very recent and incomplete.  It is possible that @avelad did not fully implement it.

**Comment by unext-wendong** [comment]
@avelad @joeyparrish I think I got it working now.

There were mainly 2 issues:
1. The KID in the WRMHEADER is a GUID structure serialized in little-endian, and we were reading as a normal byte array.
2. The `sepiff` box doesn't exist AFAIK. In PIFF, the sample encryption info could be stored either in a `senc` box or a `uuid` box with user type "A2394F52-5A9B-4F14-A244-6C427C648DF4".

The playback works now with the following changes:
https://github.com/shaka-project/shaka-player/compare/main...unext-wendong:shaka-player:bugfix/protected-mss?expand=1

However, I left a TODO here, where I couldn't get `isoFile.fetchAll()` compile. Not sure where I got it wrong.
https://github.com/unext-wendong/shaka-player/blob/bugfix/protected-mss/lib/transmuxer/mss_transmuxer.js#L275-L276

Could you guys take over from here? I don't have CLA signed so couldn't merge it anyway.

You can use my above change as you want. I have little experience writing JS code, so you might want to rewrite it.

**Comment by joeyparrish** [comment]
The CLA is a copyright assignment.  According to Google's policy, if you haven't signed a CLA, I couldn't just take your code and merge it as if it were my own.  (I am not a lawyer, and I am only speaking about company policy and not open source licensing under the law.)

**Comment by unext-wendong** [comment]
One update:
- Removed the creation of the `saio` and `saiz` boxes, which to my understanding is only an alternative to the presence of the `senc` box.
- The code got much simpler and is able to handle `moof` boxes with multiple `uuid` boxes.

btw: My CLA process is still on pending.
