### ISSUE TITLE
How to implement widevine on shaka player

### ISSUE THREAD

**Issue by TREER00T** [shaka-project/shaka-player#5393]
I want to use drm widevinve to prevent the screen record of the user in Shaka player using hls, but I am confused.

1. Where can I find a license url?

**Comment by WINOFFRG** [comment]
Kindly go through the Docs https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html
Note that user is responsible for protecting their videos with DRM, If you are protecting them with any of your DRM providers they should provide you the URL. This is Player where you provide those values for playback.

**Comment by TREER00T** [comment]
Thanks, can I implement my license server to support widevine?

**Comment by avelad** [comment]
To get Widevine support contact with the Widevine team in https://www.widevine.com/contact Thanks!
