### ISSUE TITLE
Playready MSS failed due to 412 (Precondition Failed) segments multiple errors

### ISSUE THREAD

**Issue by jakubjereczek** [shaka-project/shaka-player#5395]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Sure.

**What version of Shaka Player are you using?**
3.2.11.

**Can you reproduce the issue with our latest release version?**
I have not checked, I used built-in Chromecast ShakaPlayer.

**Can you reproduce the issue with the latest code from `main`?**
I have not checked, I used built-in Chromecast ShakaPlayer.

**Are you using the demo app or your own custom app?**
We have Custom Web Receiver with built-in ShakaPlayer.

**If custom app, can you reproduce the issue using our demo app?**
I have not checked.

**What browser and OS are you using?**
Is not related to browser/OS.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast 3,

**What are the manifest and license server URIs?**

I will send details on haka-player-issues@google.com.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

The default what is provided in built-in Chromcast.

**What did you do?**

While playing MSS provided by VSPP platform usually after few seconds of playing, we are facing with multiple failed segment request with 412 error code. 
I will add that steam works normally, but after reaching the limit of max segment retries error throws.

**What did you expect to happen?**
Segments that are not available - 412 should be filtered out somehow.

**What actually happened?**

The issue arises when playing MSS (Microsoft Smooth Streaming) on the VSPP streaming platform. It has been observed on numerous streams that after a few segments are successfully downloaded, the subsequent fragment requests fail with a response of 412 (Precondition Failed).

It is worth mentioning that despite the segment failures, the stream itself continues without hanging. Once the maximum segment retry limit is reached, an error is thrown. 

As a clarification: In the case of live TV, encountering the 412 error is normal when requesting future segments that are not yet available (meaning the client is too close to the live moment). There seems to be a problem where a significant portion of them fail due to the 412 error, indicating that ShakaPlayer attempts to fetch a segment that is not yet accessible.

![image](https://github.com/shaka-project/shaka-player/assets/58139870/bf0e7f39-e877-48d3-84b0-acb8d4400240)

**Comment by avelad** [comment]
Shaka Player does not have MSS support in an official version, so you have to write to the chromecast team about this bug. https://developers.google.com/cast/support. Sorry!
