### ISSUE TITLE
Changing m3u8 content after downloaded

### ISSUE THREAD

**Issue by TREER00T** [shaka-project/shaka-player#5396]
I have the contents of my m3u8 files encrypted, I want to display the side of the player that I implemented using shaka player
 However, after m3u8 is downloaded, I want it to decrypt the contents in shaka player

**Comment by avelad** [comment]
Here https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html you can find the documentation on how to configure your DRM in Shaka Player.

**Comment by TREER00T** [comment]
@avelad I want to change the contents of m3u8 files. I can do this in hls.js using the [ploader](https://github.com/video-dev/hls.js/blob/master/docs/API.md#ploader) object, but in shaka player, I don't know how this construction process is.

**Comment by avelad** [comment]
You can register a response filter to manipulate the server response (https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.ResponseFilter)
