### ISSUE TITLE
Live stream audio and video out of sync

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#5397]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest. 

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome and Edge, both Mac and Windows.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://router.euddn.net/95b879fc5407bb2fc4ae3a1c74d69466/smil:live1.smil/playlist.m3u8?c=8000

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Open live stream, let it play about 5 minutes

**What did you expect to happen?**
Live stream to play with audio and video in sync

**What actually happened?**

After about 5 minutes audio and video get out of sync. 
The problem occurs in latest release and also on main, but in 4.3.2 everything works as expected (audio and video are in sync).

**Comment by avelad** [comment]
@joeyparrish can you review it?
