### ISSUE TITLE
Autorelease broken

### ISSUE THREAD

**Issue by f1multiviewer** [shaka-project/shaka-player#5401]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
n/a

**Please ask your question**
It seems that https://github.com/shaka-project/shaka-player/pull/4692 has been open for a while but is being blocked by a CLA issue. There's a few important improvements for us that we'd like to use but since there's no release we're left waiting. Is there any way to unblock this release?

**Comment by joeyparrish** [comment]
The release automation is not broken.  We just haven't triggered it for v4.4.0 yet.  We are not quite ready to release that version.

The robot proposes a release PR as soon as there is a single change in the main branch (or any stable release branches, such as v4.3.x).  The release does not happen until a human maintainer chooses to merge that PR.

Sorry for any confusion.
