### ISSUE TITLE
Audio/Video Sync Issue 

### ISSUE THREAD

**Issue by isararod** [shaka-project/shaka-player#5402]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled

**What version of Shaka Player are you using?**
v4.3.7-uncompiled

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**What did you do?**
When playing out a stream on ShakaPlayer with DRM, the stream becomes out of sync where the audio is delayed

**What did you expect to happen?**
Audio and video should be in sync 

**What actually happened?**
Audio and video became out of sync.

**Comment by joeyparrish** [comment]
Unable to reproduce.  Please use the template here and provide all requested information (most critically, the content and license server URLs): https://github.com/shaka-project/shaka-player/issues/new?assignees=&labels=type%3A+bug&projects=&template=bug_report.md&title=
