### ISSUE TITLE
High VST for Multi Audio content on Shaka Player

### ISSUE THREAD

**Issue by samcurran22** [shaka-project/shaka-player#5403]
Am trying to play Media package VOD asset packaged in MPEG DASH.I have observed the there is high VST and rebuffering seen when player is trying to change from one audio to another audio.

Seg duration is 4 sec.

Any reason why is that so ?

Please find mpd manifest file FYR.
[multi-audio.txt](https://github.com/shaka-project/shaka-player/files/12005977/multi-audio.txt)

**Comment by joeyparrish** [comment]
What does VST stand for?

**Comment by samcurran22** [comment]
Yes.Video Start time

**Comment by avelad** [comment]
Can you test with the main branch? Thanks!
