### ISSUE TITLE
Dolby Atmos content fails to chromecast from a Chrome browser (but reloading the content resolves the issue)

### ISSUE THREAD

**Issue by Tsuruoka-569** [shaka-project/shaka-player#5404]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
We use both. (With our android custom app, it works fine.)
The issue occurs on Chrome with shaka based players.

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
We've tried 
- Chrome (114.0.5735.199) on Windows 10
- Chrome (114.0.5735.198) on Mac (Big Sur 11.6)
- Chrome (114.0.5735.196) on Android (version 13)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
We used Chromecast ultra and Chromecast with Google TV connected to an AV receiver.

**What are the manifest and license server URIs?**

n/a

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

n/a

**What did you do?**

Create a MPEG-DASH stream (via [shaka packager](https://github.com/shaka-project/shaka-packager)) in dolby atmos format. We use Dolby Digital Plus JOC format (aka. Enhanced AC-3 JOC).
Upload the dash stream to a server and play the content using [shaka player demo](https://shaka-player-demo.appspot.com/demo/#audiolang=ja;textlang=ja;uilang=ja;panel=CUSTOM%20CONTENT;build=uncompiled) on Chrome. 

**What did you expect to happen?**
Since the Dolby Atmos format is not supported on Chrome, the playback shouldn't start.
However, using Chromecast with Dolby Atmos compatible devices like Chromecast ultra and Chromecast with Google TV, we expect to be able to cast the content.

**What actually happened?**

Upon casting, the playback does not start, and clicking the play button doesn't do anything. 
Only upon reloading the content, the content is casted properly without issue.

**Comment by avelad** [comment]
@Tsuruoka-569  Please provide a manifest. If not, we can't help you. Thanks!
