### ISSUE TITLE
RetryParameters for Manifest not work in Safari

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#5405]
Hello,

I am using Shaka player version 4.0.2. Safari version 16.5.1. 

My config for retryParameters in MANIFEST not working on Safari while it works on on Chrome and Edge. Please advise do I need to add any additional config for Safari.

I config to 5000ms, but it often take up to about 20000ms in Safari:

![Screen Shot 2023-07-11 at 10 20 00](https://github.com/shaka-project/shaka-player/assets/70369658/290627c2-bd74-4c6a-9004-2c98a671d0bf)

My config is:

```
{
 streaming: {
    bufferingGoal: 10,
    // bufferingGoal is the amount of content we try to buffer.
    // For example, if this is set to 30, we fetch segments until we have at least 30 seconds buffered.
    bufferBehind: 60,
    lowLatencyMode: true,
    inaccurateManifestTolerance: 0,
    rebufferingGoal: 0.01,
    retryParameters: {
      connectionTimeout: 5000, // connection timeout in ms, after which we abort
      timeout: 5000,
      maxAttempts: 1,
      baseDelay: 2000,
      backoffFactor: 2,
      fuzzFactor: 0.5,
    },
  },
  manifest: {
    retryParameters: {
      timeout: 5000, // timeout in ms, after which we abort
      maxAttempts: 1, // the maximum number of requests before we fail
      baseDelay: 1000, // the base delay in ms between retries
      backoffFactor: 2, // the multiplicative backoff factor between retries
      fuzzFactor: 0.5, // the fuzz factor to apply to each retry delay
    },
  },
  abr: {
    enabled: true,
  },
 drm: {...}
}

```
I expect to set timeout 5000ms (5 seconds) for each request of the manifest.
Thank you.

**Comment by vanminhquangtri** [comment]
I update version of Shaka to latest 4.3.7, but problem still happen. Any advice??

![Screen Shot 2023-07-11 at 17 28 10](https://github.com/shaka-project/shaka-player/assets/70369658/71b1538b-7d11-4722-ac82-1ae16c710dd9)

**Comment by joeyparrish** [comment]
With Apple's native HLS implementation, we don't control those requests.  You may want to set the player configuration `streaming.useNativeHlsOnSafari` to `false`:

```js
player.configure('streaming.useNativeHlsOnSafari', false);
```

Note, however, that this won't have any effect on iOS, where native HLS is the only option available to us.

Does this help?

**Comment by vanminhquangtri** [comment]
@joeyparrish thanks for your advice. if I set useNativeHlsOnSafari to false, the player is failed with error **4026**.
As I see in Safari, you only support DRM fairplay, correct?

Is it possible to set useNativeHlsOnSafari to false if DRM is fairplay?

![Screen Shot 2023-07-12 at 07 10 49](https://github.com/shaka-project/shaka-player/assets/70369658/4d176fc4-2801-4f93-b5c4-20ecb140cad9)

**Comment by vanminhquangtri** [comment]
@joeyparrish error **4026** mean **The HLS parser has encountered encrypted content with unsupported KEYFORMAT attributes.**
Does this mean we have to make change at our video encoder?

**Comment by vanminhquangtri** [comment]
@joeyparrish can you please help?

**Comment by vanminhquangtri** [comment]
I ended this issue by using Bitmovin Player, it support Fairplay on Macos for Tauri. Thanks.

**Comment by joeyparrish** [comment]
> Is it possible to set useNativeHlsOnSafari to false if DRM is fairplay?

Yes.  Fairplay support is independent of that flag.

>  4026 mean The HLS parser has encountered encrypted content with unsupported KEYFORMAT attributes.
Does this mean we have to make change at our video encoder?

Not necessarily.  But it means that this aspect of your content is not supported by the version of the player you are using.  Either you can change the content or change the player.

I recommend you start by upgrading the player.  v4.0.2 is no longer supported.  The latest release is v4.3.7, and we currently support the v4.2 and v4.3 branches.  See [https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md](maintained-branches.md) for details.

Does this help?  If you're still having a KEYFORMAT error with the latest release, please use the bug report template and fill out all the requested information so that we can diagnose your problem: https://github.com/shaka-project/shaka-player/issues/new/choose

Thanks!

**Comment by vanminhquangtri** [comment]
@joeyparrish if I change to version 4.2 or 4.3, the player play fail.
Do you have migration guide for change from 4.02.2 to 4.2/4.3


https://github.com/shaka-project/shaka-player/assets/70369658/d943e449-94d4-4a34-99e5-b71ad0e55bfd

**Comment by avelad** [comment]
@vanminhquangtri Can you test if the main branch still has the problem? Thanks!

**Comment by vanminhquangtri** [comment]
@avelad please advise what you mean main branch?

**Comment by avelad** [comment]
> @avelad please advise what you mean main branch?

https://github.com/shaka-project/shaka-player/tree/main

**Comment by vanminhquangtri** [comment]
@avelad can you instruct me how to test this?

**Comment by avelad** [comment]
@vanminhquangtri You can use the following link: https://nightly-dot-shaka-player-demo.appspot.com/dist/shaka-player.ui.js
