### ISSUE TITLE
Include error stack on compiled mode.

### ISSUE THREAD

**Issue by cristian-atehortua** [shaka-project/shaka-player#5406]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

We are facing some strange issues on production that are hard to replicate locally. Those errors are causing peaks in specific timeframes and since we don't have stack traces is hard to know what is causing them.

**Describe the solution you'd like**

Include the `Error.stack` field in compiled mode, not only in uncompiled.

**Describe alternatives you've considered**

Using uncompiled mode in production (not feasible because of degraded performance)

**Additional context**

I don't know what is the reason for not including the stack. The only reason I see is, since the compiled mode is obfuscated the stack may not add information. However, since developers can use a source map loader when compiling applications it will give back the ability of understanding the stack.

**Comment by cristian-atehortua** [comment]
@avelad @joeyparrish @theodab Do you have any comments?

**Comment by joeyparrish** [comment]
> I don't know what is the reason for not including the stack. The only reason I see is, since the compiled mode is obfuscated the stack may not add information.

This is exactly the reason.

> However, since developers can use a source map loader when compiling applications it will give back the ability of understanding the stack.

This is a great point!  We had not considered that when we wrote the logic.  (The exclusion of stacks in production goes all the way back to when we originally added the stack trace, in 6d57a9181b7c47392fc0fc261aef3e62c96767bf from 2016.)
