### ISSUE TITLE
Shaka support for DASH manifest with both CMAF & non-CMAF content

### ISSUE THREAD

**Issue by va2401** [shaka-project/shaka-player#5413]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest at the time - v4.3.7 (uncompiled)

**Please ask your question**
I know that Shaka supports both CMAF and non-CMAF content for DASH manifest (MPD).
However, the question is can Shaka support multi-period DASH manifest for Simulcast stream having few periods (<Period>) in CMAF format and few in non-CMAF format together?
- I have verified for VOD and it works just fine
- I wasn't able to get it working for Simulcast stream

**Comment by avelad** [comment]
>  However, the question is can Shaka support multi-period DASH manifest for Simulcast stream having few periods () in CMAF format and few in non-CMAF format together?

At the moment, we need the same codec and container across the multi-period
