### ISSUE TITLE
Controls issues 

### ISSUE THREAD

**Issue by Leena-Sharma-rsys** [shaka-project/shaka-player#5415]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
4.2.7

**Please ask your question**
hi, i am facing issues with control.css, 
i have attached the image  and code for your reffernce;

const video = videoRef.current;
const container = videoContainer.current;
var player = new shaka.Player(video);
 const controls = new shaka.ui.Overlay(player, container, video);
 controls.getControls();

    <div className="video-container" ref={videoContainer}>
      <video
        className="shaka-video"
        ref={videoRef}
        // controls
        poster="//shaka-player-demo.appspot.com/assets/poster.jpg"
      />
    </div>

<img width="643" alt="Screenshot 2023-07-14 at 10 11 05 PM" src="https://github.com/shaka-project/shaka-player/assets/96762905/3ce08890-ba41-479f-a737-f8dc583b7748">

Thanks

**Comment by WINOFFRG** [comment]
You are importing just the player, To use the default UI with styles you would need to import CSS Separately. 
You can it here from the CDN https://cdnjs.com/libraries/shaka-player
