### ISSUE TITLE
Fetching Persistent License from EZDRM for offline storage in Electron

### ISSUE THREAD

**Issue by jookeboxpm** [shaka-project/shaka-player#5418]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.2.2

**Please ask your question**
I need to request a Persistent License from EZDRM widevine servers and store it for offline playback. I have gone through the documentation and have attempted to configure my player using [https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html](https://shaka-player-demo.appspot.com/docs/api/tutorial-offline.html). I am requesting any help you can provide.

**Comment by joeyparrish** [comment]
What issue are you having?  What isn't working?  What is unclear from the offline tutorial?  Are there things in the EZDRM docs that you don't know how to configure in Shaka Player?
