### ISSUE TITLE
Playback fails when some but not all representations require unsupported DRM security level

### ISSUE THREAD

**Issue by caridley** [shaka-project/shaka-player#5421]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Have not tried

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 114 on Mac OS 13.4.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
I will e-mail manifest and license urls to <shaka-player-issues@google.com>
Contents of the manifest are attached 
[track_keys_manifest.txt](https://github.com/shaka-project/shaka-player/files/12095891/track_keys_manifest.txt)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
See attached file 
[shaka-config.txt](https://github.com/shaka-project/shaka-player/files/12095753/shaka-config.txt)

**What did you do?**
We are trying to play a VOD DASH stream that use a different DRM key for higher resolution video representations. That key requires a higher widevine security level that is not supported by the Chrome desktop browser. 

We expect shaka to play one of the lower resolution representations that do not require the higher widevine security level, but playback fails on failure of the license request for the key associated with the higher resolution streams. We see this error

Shaka Error DRM.LICENSE_REQUEST_FAILED (shaka.util.Error { "severity": 2, "category": 1, "code": 1001, "data": [ "https://licenseurlremoved", 403, "{\"code\":130001,\"message\":\"License denied. Failed to find a policy for the requested security level SW_SECURE_DECODE.\"}", { "content-length": "118", "content-type": "application/json; charset=UTF-8" }, 2 ], "handled": false, "message": "Shaka Error NETWORK.BAD_HTTP_STATUS 

We are able to play this stream if we set restriction.maxWidth to 1024.

**Comment by caridley** [comment]
Is there anybody out there? Any suggestions on how we can fix this?

**Comment by caridley** [comment]
Hi, we could really use some help with this one.

**Comment by avelad** [comment]
@caridley can you send the manifest and license urls to shaka-player-maintainers@googlegroups.com ? Thanks!

**Comment by caridley** [comment]
Just sent e-mail with new test stream manifest and licence urls.

**Comment by avelad** [comment]
Same issue as https://github.com/shaka-project/shaka-player/issues/3051. So I'm going to close it as a duplicate.
