### ISSUE TITLE
Error 3015, 3016  MPEG DASH Low Latency on TV Samsung 2017 Tizen 3.0

### ISSUE THREAD

**Issue by vuhieutrung279** [shaka-project/shaka-player#5425]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.3.1

**Please ask your question**
I was trying to play a low-latency MPEG-DASH stream on a Samsung TV from 2017 running Tizen 3.0. I received errors 3015 and 3016, but the stream plays fine on newer Samsung TVs released after 2017. Are there any particular manifest or configuration options in Shaka Player that would help enable low-latency playback on this model or an older Samsung TV model?

**Comment by avelad** [comment]
@vuhieutrung279 The version you are using is no longer maintained, please try to upgrade to a maintained version. See: https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md

**Comment by vuhieutrung279** [comment]
I upgraded to version 4.3.8, but it's still not working. Do you have any solutions?

**Comment by avelad** [comment]
@vuhieutrung279 Can you test if the main branch still has the problem? Thanks!
