### ISSUE TITLE
Issues with ABR with bandwidth variations

### ISSUE THREAD

**Issue by kumarashu123** [shaka-project/shaka-player#5426]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Own

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome Version 115.0.5790.98 (Official Build) (arm64) and MACOS Ventura 13.4.1 (c)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
No

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths/dash.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

streaming: {
                    rebufferingGoal: 1,
                    bufferBehind: 6,
                    bufferingGoal: 10,
                    durationBackoff: 1,
                    ignoreTextStreamFailures: true,
                    jumpLargeGaps: true,
                    smallGapLimit: 0.5,
                    startAtSegmentBoundary: false,
                    retryParameters: {
                        timeout: 0,
                        maxAttempts: 5,
                        baseDelay: 1000,
                        backoffFactor: 3, 
                        fuzzFactor: 0.5
                    }
                }
                
**What did you do?**

1.  Play asset having Multiple resolution, select high resolution from the resolution list.
2. Throttled network using Charles Proxy/ Chrome network throttling or when network bandwidth fluctuates. 
3. Video and audio segments of selected resolution is getting downloaded and buffering is seen.

**What did you expect to happen?**
Video and audio segments of lower profile should be downloaded and playback should be smooth.

**What actually happened?**

* If high resolution is selected from the resolution list, when bandwidth fluctuates Video and audio segments of lower profile is not getting downloaded. High profile is getting downloaded and a lot of buffering is seen.

https://github.com/shaka-project/shaka-player/assets/10974291/82a45e55-ea8b-478d-a2a1-9484424b1e1e

**Comment by WINOFFRG** [comment]
For Adaptive Bitrate Streaming to Work you must select **Auto** in quality panel, When you select any other value, it is enforced and ABR is turned off and any change in network speed wont affect the resolution variant. Refer [ABR Configuration](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.AbrConfiguration)

`player.configure({abr: {enabled: true}})`;

**Comment by kumarashu123** [comment]
@WINOFFRG  It is not same for other's player like AVPlayer (iOS), ExoPlayer and so on.

If you manually select a specific quality level (e.g., 720p or 1080p) from the quality panel, ABR is not turned off or disabled. The media player will continue to adapt the video quality within the selected resolution variant based on the available network speed. If the network conditions change, the player will still adjust the bitrate within the chosen resolution to maintain a stable playback experience.

**Comment by WINOFFRG** [comment]
Hey! Kindly note that [Demo UI](https://shaka-player-demo.appspot.com/) is a player implementation. You can use it the way you want, Also Shaka Player allows you to select any variant without disabling the ABR. You can directly select a variant and you will just get a warning `Changing tracks while abr manager is enabled will likely result in the selected track being overriden. Consider disabling abr before calling selectVariantTrack().` Which you can ignore. And based on the network it will auto switch to some other variant just as you asked.

**Comment by kumarashu123** [comment]
@WINOFFRG In the Shaka Player version 2.5.10 I tried setting below config when I select quality level as 720

  shakaPlayer.configure({
      abr: {
          enabled: true,
          restrictions: {
              maxHeight: 720
          }
      }
  });
  
  
  I see only resolution variant 720 is picked in both case stable network and change in network speed.
  
  Is there any issue with Shaka version 2.5.10 ?
  From which version for Shaka Player abr works fine when I choose quality level as high (eg 720) and there is change in network speed?

**Comment by kumarashu123** [comment]
> @WINOFFRG In the Shaka Player version **2.5.10** I tried setting below config when I select quality level as 720
> 
> shakaPlayer.configure({ abr: { enabled: true, restrictions: { maxHeight: 720 } } });
> 
> I see only resolution variant 720 is picked in both case stable network and change in network speed.
> 
> Is there any issue with Shaka version 2.5.10 ? **From which version for Shaka Player abr works fine when I choose quality level as high (eg 720) and there is change in network speed?**
> 
> In the latest Shaka version 4.3.8 I see useNetworkInformation: true in the configuration with this abr is working fine when I choose quality level as high (eg 720) and there is change in network speed.
> 
> I see related PR #2663

@WINOFFRG any comment

**Comment by WINOFFRG** [comment]
I'm not exxactly able to understand the issue here, Can you share some recording or explain in detail?

> I see only resolution variant 720 is picked in both case stable network and change in network speed.

For me ABR seems to work fine, When you restrict height or width means any variant above that wont be selected or shown in `getVariantTracks` You may disable ABR when calling `selectVariantTrack` to prevent ABR from auto switching to any other track based on bandwidth if you dont do so depending upon network conditions it will switch automatically.

**Comment by kumarashu123** [comment]
@WINOFFRG I have enabled abr and set restrictions maxHeight: 720. what i expect is if network bandwidth is good it should pick track with bandwidth 720 , if network bandwidth is low it should pick track with less than 720.

In shaka-player version 2.5.10 it's not working as expected, it's only picking track with bandwidth 720 .

In latest shaka player it's working as expected. I wanted to know is there any limitations in v2.5.10?

**Comment by WINOFFRG** [comment]
Sorry I haven't worked with v2.5.10 have no idea about it. However it is an outdated version I guess no support for that. Other members might be able to help.

**Comment by avelad** [comment]
See [maintained-branches.md](https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md) for the up-to-date list of maintained branches of Shaka Player.

**Comment by kumarashu123** [comment]
Thanks!
