### ISSUE TITLE
Having problem with import

### ISSUE THREAD

**Issue by TDUser91** [shaka-project/shaka-player#5430]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.7

**Please ask your question**
Trying to use shaka-player in my React app (typescript) but I'm dealing with this issue while trying to import the */shaka-player/dist/shaka-player.ui.ts'*. See screenshot
![Screenshot from 2023-07-21 09-35-00](https://github.com/shaka-project/shaka-player/assets/139954955/e4eb6c18-fd3e-4b04-b74f-ae8002f91654)

the file is there, while importing it even suggest that file to me. Not quite sure how to fix this as I'm new to React and Typescript

**Comment by WINOFFRG** [comment]
Hey @TDUser91 I faced the same issue while I was setting this up for https://github.com/WINOFFRG/limeplay
I spent many days in various communities like Typescript Community, Video Dev Slack, etc and got the solution for this.

First I would recommend you to use [Typescript Path](https://www.typescriptlang.org/tsconfig#paths) Feature to get rid of `shaka-player/dist/shaka-player.ui` so as to directly use `shaka-player`. 

Then refer this, 

1. Declare `shaka-player` as module and export the Shaka type namespace globally. [Link](https://github.com/WINOFFRG/limeplay/blob/main/%40types/shaka-player.d.ts#L1-L3)
2. Include those types in your `tsconfig` [Link](https://github.com/WINOFFRG/limeplay/blob/main/packages/limeplay-core/tsconfig.json#L5)
3. Consume them directly [Link](https://github.com/WINOFFRG/limeplay/blob/main/packages/limeplay-shaka/src/use-shaka-player.ts#L1)

![image](https://github.com/shaka-project/shaka-player/assets/61311751/9c3218cb-3fb8-45cd-9b68-effb317d124d)

This could initially be a lot to understand if you are beginner, Here are the thread links to Typescript Community Discussions (Discord) I had with them to get this issue solved:
1. https://discord.com/channels/508357248330760243/1071292445331030076
2. https://discord.com/channels/508357248330760243/1080459419474726932

**Comment by TDUser91** [comment]
Hi @WINOFFRG, thank you! for the taking the time and the replies, I will try your approach as well. From my end I've managed to fix the export bug and the warning errors [like so](https://gist.github.com/Security2431/2b28f17e11870bb4b0e347673e16d5ba#gistcomment-4636610) if you want to take a look
