### ISSUE TITLE
How can I get details of the current ad? preroll or midroll

### ISSUE THREAD

**Issue by mrshulk** [shaka-project/shaka-player#5431]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
Latest

**Please ask your question**
How can I get details of the current ad? I need to know if it is a preroll or midroll, I tried to search using e.getStreamData().adProgressData without success.

```js
function listenEvents(adManager) {
    const eventsAdManager = [
      shaka.ads.AdManager.ADS_LOADED,
      shaka.ads.AdManager.AD_STARTED,
      shaka.ads.AdManager.AD_FIRST_QUARTILE,
      shaka.ads.AdManager.AD_MIDPOINT,
      shaka.ads.AdManager.AD_THIRD_QUARTILE,
      shaka.ads.AdManager.AD_COMPLETE,
      shaka.ads.AdManager.ALL_ADS_COMPLETED,

      shaka.ads.AdManager.AD_PROGRESS,
      shaka.ads.AdManager.AD_BREAK_READY,
      shaka.ads.AdManager.AD_DURATION_CHANGED,
      shaka.ads.AdManager.AD_LINEAR_CHANGED,
      shaka.ads.AdManager.AD_LOADED,
      shaka.ads.AdManager.CUEPOINTS_CHANGED,
      shaka.ads.AdManager.IMA_AD_MANAGER_LOADED,
      shaka.ads.AdManager.IMA_STREAM_MANAGER_LOADED,
    ];

    eventsAdManager.forEach(events => {
      adManager.addEventListener(events, (e) => {

        console.log(`EVENT: ${e.type}`, e);
      }, false);
    });
  }
```

**Comment by WINOFFRG** [comment]
`$('video').ui.player_.adManager_.csAdManager_.imaAdsManager_.getCurrentAd()`

This might be what you are looking for.

**Comment by theodab** [comment]
The `AD_STARTED` event has an attached `sdkAdObject` object that contains all of the data the SDK knows for the ad that started.
To find the information on the ad pod itself, which would include the position, check `event.sdkAdObject.data.adPodInfo`. Specifically, you should look at the pod index in that. See the IMA SDK docs [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdPodInfo#getPodIndex). The pod index is 0 for a preroll, -1 for a post-roll, and 1+ for a midroll.

**Comment by mrshulk** [comment]
Hello guys, thanks for your help.

Actually, I've been using the IMA SDK and the IMA DAI SDK as well. Do you have any hints?

**Comment by avelad** [comment]
I created https://github.com/shaka-project/shaka-player/pull/5524 to add this information to the public API
