### ISSUE TITLE
Video casted to chromecast feezes for few seconds, while audio plays.

### ISSUE THREAD

**Issue by tomasz-rekawek** [shaka-project/shaka-player#5436]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
No, seems like the demo app is using reciver v2

**What browser and OS are you using?**
MacOS Ventura 13, Chrome Version 114.0.5735.198 (Official Build) (arm64)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast 1.61.3299090

**What are the manifest and license server URIs?**
https://media-production.nebula.app/unauthenticated/nebula_trailers/originals/lindsay_ellis/avc.d8bb45cff28e.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default chromecast v3 reciver config.

**What did you do?**

1. open cacTool https://casttool.appspot.com/cactool/
2. set app id to: 0BBC55A6
3. connect to chromecast
4. go to load media
5. set content url to: https://media-production.nebula.app/unauthenticated/nebula_trailers/originals/lindsay_ellis/avc.d8bb45cff28e.m3u8
6. send request

**What did you expect to happen?**
Video to play in sync with audio on a casted device.

**What actually happened?**
Audio plays, while video is freezed for 1-2 seconds, then it plays normally.

Bug exists only when shakaVersions on the reciver side are set to 4.x.x i.e 4.3.4, 4.3.8.
downgrading to 3.3.19 seems to fix the problem.

**Comment by avelad** [comment]
Can you test if the problem still exists in version 4.5.0 or in the main branch? Thanks!

**Comment by tomasz-rekawek** [comment]
Hi, seems like chromecast reciver apps are pulling automatically the newer version, if i set manually version to 4.3.4 i can observe the issue. If i remove the field or set it to 4.5.0 it seems to be gone. 
Seems like it is resolved. 
Thank you, much appriciated.
