### ISSUE TITLE
Image Track parsing Support

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#5438]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.8

**Please ask your question**

Want to confirm if Shaka Player is currently capable of parsing all types of Thumbnail Tracks? After going through https://developer.bitmovin.com/playback/docs/thumbnail-preview-support#compatibility 

1. Is player able to parse HLS/DASH Thumbnail Tracks in WebVTT format? I couldn't check as I wasn't able to get any samples for both HLS and DASH. 
2. What about HLS Image Media Playlist? For this as well I wasn't able to get a valid working sample.
3. Not sure about BIF but I do have an implementation, However is there any plan for supoprting BIF as well even though it is Roku specific. If yes, In what ways, As much as I'm aware it can only be added via external source none of DASH/HLS supports direct implementation. Kindly confirm.

**Comment by avelad** [comment]
Shaka currently supports:
  - Internal DASH thumbnails. Using DASH-IF IOP Image Adaptation Set
  - Internal HLS thumbnails. Using HLS Image Media Playlist
  - External WebVTT with images/sprites (only for VoD)

**Comment by WINOFFRG** [comment]
Hello @avelad Can you confirm one thing, Are there any plans to bring support for BIF Image Track format? 
Ref: https://developer.roku.com/docs/developer-program/media-playback/trick-mode/bif-file-creation.md

If not I'll continue completing my custom implementation for BIF support for https://github.com/WINOFFRG/limeplay
otherwise integrate in shaka before.

**Comment by avelad** [comment]
There are not plans from us. But we are open to review PRs
