### ISSUE TITLE
CMAF HLS stream with edit list results in audio video sync

### ISSUE THREAD

**Issue by duggaraju** [shaka-project/shaka-player#5445]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
 4.3.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome On windows 11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://amsencodermsitest.z22.web.core.windows.net/live/asset-4846ed58-14ac-464e-a4d9-11dc51f7a803/9ec21739-768f-49ac-a54c-47aee0ffae4b.m3u8
https://amsencodermsitest.z22.web.core.windows.net/live/asset-4846ed58-14ac-464e-a4d9-11dc51f7a803/9ec21739-768f-49ac-a54c-47aee0ffae4b.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Just try and play the HLS and DASH urls. HLS url has A/V sync while DASH one works fine.

**What did you expect to happen?**
No A/V sync since there is an edit list in the CMAF initialization segment.

**What actually happened?**

**Comment by avelad** [comment]
Both urls returns a 404, can you share a new urls? Thanks!

**Comment by duggaraju** [comment]
Try https://amsencodermsitest.z22.web.core.windows.net/live/rtmpencc%20-rtmpencc-1ha/9ec21739-768f-49ac-a54c-47aee0ffae4b.m3u8 and
https://amsencodermsitest.z22.web.core.windows.net/live/rtmpencc%20-rtmpencc-1ha/9ec21739-768f-49ac-a54c-47aee0ffae4b_3.mp4
DASH works fine but HLS lip sync is off. Packaged using shaka packager and the underlying CMAF is same.

**Comment by duggaraju** [comment]
@shaka-bot  reopen the issue.

**Comment by avelad** [comment]
@duggaraju  can you try with the main branch? Yesterday I fixed some AV sync issues.

**Comment by duggaraju** [comment]
Try with latest of main branch built locally as well as the nightly demo page https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://amsencodermsitest.z22.web.core.windows.net/live/rtmpencc%20-rtmpencc-1ha/9ec21739-768f-49ac-a54c-47aee0ffae4b.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled  Stil can see that DASH is in sync but HLS is out of sync

**Comment by avelad** [comment]
Looks like this issue is being mitigated setting `manifest.hls.sequenceMode` to false and `manifest.hls. ignoreManifestTimestampsInSegmentsMode` to true the video and audio are in sync. 

But we still have to fix because it doesn't work in sequence mode.

**Comment by avelad** [comment]
@duggaraju The stream returns a 404, can you check it? Thanks!

**Comment by duggaraju** [comment]
@avelad for security reasons traffic is blocked. If you have specific
 ip address or range I can allow list the same to access the content. or if you need, I can share the content somewhere

**Comment by avelad** [comment]
> @avelad for security reasons traffic is blocked. If you have specific ip address or range I can allow list the same to access the content. or if you need, I can share the content somewhere

You can send the uris to shaka-player-maintainers@googlegroups.com And there we can talk about sharing our IPs, thank you!
