### ISSUE TITLE
The player doesn't load the initial video chunks randomly on Safari + DRM

### ISSUE THREAD

**Issue by hmishinev** [shaka-project/shaka-player#5446]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**
4.3.8, 4.3.7, 4.3.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Own custom app

**What browser and OS are you using?**
Safari 16.5.2

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Just the drm servers with the default configuration. No changes.

```
  drm: {
    servers: {
      'com.widevine.alpha': videoConfig.drmLicenseServerWidevine,
      'com.microsoft.playready': videoConfig.drmLicenseServerPlayready,
      'com.apple.fps': videoConfig.drmLicenseServerFairplay,
    },
    advanced: {
      'com.apple.fps': {
        'serverCertificateUri': videoConfig.drmLicenseServerFairplayCertificate,
      },
    },
  },
```

Hello,

I've encountered a recurring issue with the Shaka Player when playing DRM-enabled videos on Safari. More often than not, we're seeing a 3016 MEDIA.VIDEO_ERROR (3,,Media failed to decode).

My analysis suggests that there seems to be a race condition at loading. It appears the player begins to decode the video before the certificate has fully loaded, which then prevents further chunks from loading. After several refresh attempts, the video does eventually start to play.

This issue isn't present when there's a 10-second clear lead and the certificate has time to load. However, a separate problem arises specifically on Safari, where the audio cuts out for a few seconds after the clear lead.

I've documented the issue in the video linked below for further clarification. It is clearly visible how the first time the page loads the initial video chunks are not loaded, i.e. canceled due to the error.

https://drive.google.com/file/d/1CkiOd3IOZmKoKcZwl96eKI0mv-tHsCga/view?usp=sharing

![image](https://github.com/shaka-project/shaka-player/assets/4200656/1a2c7a69-3fd3-498c-a5bc-4241fd68f115)

**Comment by hmishinev** [comment]
I finally got it working using:
```
com.apple.fps.1_0
polyfill.PatchedMediaKeysApple.install();
```

**Comment by avelad** [comment]
Thanks for finding your problem!
