### ISSUE TITLE
HLS Subtitles with external VTT out of sync

### ISSUE THREAD

**Issue by WINOFFRG** [shaka-project/shaka-player#5458]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome, Windows 11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Manifest: https://stream.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU.m3u8
WebVTT: https://www.vidstack.io/media/sprite-fight.vtt

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default Config

**What did you do?**

```
$('video').ui.player_.load('https://stream.mux.com/VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU.m3u8')
await $('video').ui.player_.addTextTrackAsync('https://www.vidstack.io/media/sprite-fight.vtt', 'en')
```

1. Select English Track
2. Seek to a time, Found captions out of sync

**What did you expect to happen?**
Captions should have been in sync, I have checked the timestamps in VTT they are correct. 

**What actually happened?**

Captions are out of sync on both native video element as well as on UITextDisplayer

**Comment by avelad** [comment]
I'm working on a fix for it!
