### ISSUE TITLE
Issue with Shaka Player on TizenTV - HLS Multi Audio Playback Problem

### ISSUE THREAD

**Issue by J-NAVEEN-KUMAR** [shaka-project/shaka-player#5475]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Certainly?

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.8

**Please ask your question**
Dear Community,

 I am writing to seek assistance with a specific issue I am facing while using the Shaka Player on TizenTV (SamsungTV) with HLS video URLs. I have implemented the player to handle both single audio and multi audio streams, but unfortunately, I am encountering playback problems when using the multi audio HLS URLs.

The error message I am receiving is as follows:

_Skipping unsupported HLS stream audio/aac audio/aac/tur/test.m3u8
Raw formats are not yet supported. Skipping audio/aac
"CHUNK_DEMUXER_ERROR_APPEND_FAILED: audio object type 0x40 does not match what is specified in the mimetype_

For reference:
1. Shaka Player CDN URL: https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.3.8/shaka-player.compiled.js
2. Relevant code snippet:

```
var MediaPlayer = (function () {
  var video; // Declare the video variable to make it accessible throughout the module.

  var _loadUrl = function () {
    // Use the correct 'window.player.load' method to load the HLS stream.
    window.player.load('https://testencoding.s3.eu-central-1.amazonaws.com/output_videos/videos/2666d83b-2ccf-4a7f-a533-0104b10a24c3/hls/playlist.m3u8', null, 'application/x-mpegURL')
      .then(function () {
        video.play();
      })
      .catch(function (e) {
        console.log('--', e.code);
      });
  };

  var _initPlayer = function () {
    video = document.getElementById("video");
    var player = new shaka.Player(video);
    player.configure({
      streaming: {
        bufferingGoal: 180,
        rebufferingGoal: 5,
      },
    });
    window.player = player;
    // Configure Shaka Player with preferred audio language
    const config = {
      preferredAudioLanguage: 'es', // Set the preferred audio language code (e.g., 'en' for English)
    };

    // Load HLS content and start playback
    player.configure(config);
    _loadUrl(); // Move the _loadUrl() call inside the _initPlayer function.
  };

  var init = function () {
    shaka.polyfill.installAll();
    if (shaka.Player.isBrowserSupported()) {
      _initPlayer();
    }
  };

  return { init };
})();

document.addEventListener("DOMContentLoaded", MediaPlayer.init, false);
```

Video URLs:

- Single Audio: https://testencoding.s3.eu-central-1.amazonaws.com/output_videos/videos/videos/7a8d35b8-fddb-4109-bd05-3be32bf3f1bb/hls/playlist.m3u8
- Multi Audio: https://testencoding.s3.eu-central-1.amazonaws.com/output_videos/videos/2666d83b-2ccf-4a7f-a533-0104b10a24c3/hls/playlist.m3u8

The multi audio urls causing this issue, while the mpd multi audio urls are working fine.
I would highly appreciate it if someone could shed some light on why this problem is occurring and provide guidance on how to resolve it. If you need any additional information or clarifications from my end, please do not hesitate to ask. PFA
[shakaPlayer_samplecode.zip](https://github.com/shaka-project/shaka-player/files/12309657/shakaPlayer_samplecode.zip)

Thank you for your time and assistance in advance.

**Comment by avelad** [comment]
Can you test with the main branch? We fixed a lot of HLS issues in the main branch. Thanks!
