### ISSUE TITLE
Error when click on Ads 

### ISSUE THREAD

**Issue by mrshulk** [shaka-project/shaka-player#5476]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Please ask your question**
I have 2 issues involving Ads.

**Version**
I have tested with 4.3.7 and 4.3.8

1 - Ads appear as they should, but when I click on the ads, the attached error appears.
2 - The ads are running out of link.

Any suggestions what it could be?
I already tried to raise the div above the video.

in initPlayer() I'm starting the ui with the container: 
`const ui = new shaka.ui.Overlay(player, container, videoContent);`

After
   `const adContainerClientSide = controls_.getClientSideAdContainer();
   adManager.initClientSide(adContainerClientSide, videoContent);`
(ps. in this part initClientSide I already tried to set the container instead of adContainerClientSide, without success).

for midrolls, 
`adManager.initServerSide(controls_.getClientSideAdContainer(), videoContent); 
     adManager.requestClientSideAds(adRequest);`

![2023-08-10_16-38](https://github.com/shaka-project/shaka-player/assets/134942986/588758ce-1d94-4997-8c50-305e95d41bb6)

**Comment by avelad** [comment]
I have tried to reproduce the error but I have not been able to, could you share the stream and ad with which it occurs?. Thanks!
