### ISSUE TITLE
Azure Media Livestream getting Continuous Buffering in HLS

### ISSUE THREAD

**Issue by Ravi-79** [shaka-project/shaka-player#5488]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I couldn't find any duplicate issues

**What version of Shaka Player are you using?**
v4.3.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom application

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
OS: Windows 11
Browser :Microsoft Edge
Version 115.0.1901.200 (Official build) (64-bit)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Manifest:
https://amscdn-mpslive1-uswe.streaming.media.azure.net/367a8478-b0dc-44ea-9a8f-2576dfff5a32/bc63b6a1-fe8e-4c0c-9069-a7e09f30c41f.ism/manifest(format=m3u8-aapl)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

{
    "drm": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "servers": {},
        "clearKeys": {},
        "advanced": {},
        "delayLicenseRequestUntilPlayed": false,
        "logLicenseExchange": false,
        "updateExpirationTime": 1,
        "preferredKeySystems": [],
        "keySystemsMapping": {},
        "parseInbandPsshEnabled": false
    },
    "manifest": {
        "retryParameters": {
            "maxAttempts": 3,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "disableThumbnails": false,
        "defaultPresentationDelay": 0,
        "segmentRelativeVttTiming": false,
        "dash": {
            "clockSyncUri": "",
            "ignoreDrmInfo": false,
            "disableXlinkProcessing": false,
            "xlinkFailGracefully": false,
            "ignoreMinBufferTime": false,
            "autoCorrectDrift": true,
            "initialSegmentLimit": 1000,
            "ignoreSuggestedPresentationDelay": false,
            "ignoreEmptyAdaptationSet": false,
            "ignoreMaxSegmentDuration": false,
            "keySystemsByURI": {
                "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
                "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
                "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
                "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
            },
            "sequenceMode": false
        },
        "hls": {
            "ignoreTextStreamFailures": false,
            "ignoreImageStreamFailures": false,
            "defaultAudioCodec": "mp4a.40.2",
            "defaultVideoCodec": "avc1.42E01E",
            "ignoreManifestProgramDateTime": false,
            "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\"",
            **"useSafariBehaviorForLive": false,**
            "liveSegmentsDelay": 3
        }
    },
    "streaming": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "rebufferingGoal": 6,
        "bufferingGoal": 30,
        "bufferBehind": 30,
        "ignoreTextStreamFailures": false,
        "alwaysStreamText": true,
        "startAtSegmentBoundary": false,
        "gapDetectionThreshold": 0.5,
        "durationBackoff": 1,
        "forceTransmux": true,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsOnSafari": true,
        "inaccurateManifestTolerance": 2,
        "lowLatencyMode": false,
        "autoLowLatencyMode": false,
        "forceHTTPS": false,
        "preferNativeHls": false,
        "updateIntervalSeconds": 1,
        "dispatchAllEmsgBoxes": false,
        "observeQualityChanges": false,
        "maxDisabledTime": 30,
        "parsePrftBox": false
    },
    "mediaSource": {
        "sourceBufferExtraFeatures": ""
    },
    "offline": {
        "usePersistentLicense": true,
        "numberOfParallelDownloads": 5
    },
    "abr": {
        "enabled": false,
        "useNetworkInformation": true,
        "defaultBandwidthEstimate": 1000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
            "minWidth": 0,
            "maxWidth": null,
            "minHeight": 0,
            "maxHeight": null,
            "minPixels": 0,
            "maxPixels": null,
            "minFrameRate": 0,
            "maxFrameRate": null,
            "minBandwidth": 0,
            "maxBandwidth": null
        },
        "advanced": {
            "minTotalBytes": 128000,
            "minBytes": 16000,
            "fastHalfLife": 2,
            "slowHalfLife": 5
        },
        "restrictToElementSize": false,
        "restrictToScreenSize": false,
        "ignoreDevicePixelRatio": false
    },
    "autoShowText": 3,
    "preferredAudioLanguage": "",
    "preferredTextLanguage": "eng",
    "preferredVariantRole": "",
    "preferredTextRole": "",
    "preferredAudioChannelCount": 2,
    "preferredVideoCodecs": [],
    "preferredAudioCodecs": [],
    "preferForcedSubs": false,
    "preferredDecodingAttributes": [],
    "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null
    },
    "playRangeStart": 0,
    "playRangeEnd": null,
    "cmcd": {
        "enabled": false,
        "sessionId": "",
        "contentId": "",
        "useHeaders": false
    },
    "lcevc": {
        "enabled": false,
        "dynamicPerformanceScaling": true,
        "logLevel": 0,
        "drawLogo": false
    }
}

**What did you do?**

Run the player with HLS liveStream. 
Make sure the hls.useSafariBehaviorForLive is set to false so that player can show the seek bar
while playing the video at some points the video getting continuous buffering and not playing afterwards.
It can be mostly reproable when opening the player tab while the player is muted and running in background.

**What did you expect to happen?**
The player shouldn't be buffering continuously while watching Livestream continuously for several hours even switching the player between background and foreground.

**What actually happened?**

When I tried to play the Azure media HLS stream in my custom application which is using Shaka version -v4.3.8, I came to notice that the Livestream getting to buffer continuously at some point in the live. 
As I want to Seek slider and forward and Rewind options, the player won't be always in Live Edge. I set this  hls.useSafariBehaviorForLive configuration value as "False".
I tested in Shaka Demo page also using the Custom Content option with our HLS LiveStream manifest. And I can able to reproduce the issue.
I did some debugging in Shaka demo site itself, it looks like sometimes when the Video Stream is waiting for Audio stream to catch up the Presentation timeline the Segment request is not triggered. Only the Manifest request for video and audio are only continuously getting triggered. So the Audio Stream never getting cached up with the Video Stream and the player is continuously buffering.

Can you help me to know why the Segment request is not getting triggered and setting the player to buffer continuously?

Screenshot of continuous manifest request without Segment request:
![image](https://github.com/shaka-project/shaka-player/assets/131441182/447d1b64-1cbf-4635-ac49-a51dc7ecff7d)

Screenshot of Log information of video stream waiting for Audio and getting any Segement
![image](https://github.com/shaka-project/shaka-player/assets/131441182/0ec9068c-4a9b-4cde-a623-4658248865d0)

**Quick Fix I tried**
Whenever video buffering continuously, skipping forward or backward few seconds fixing the issue.

**Comment by avelad** [comment]
Please attach a manifest URL to the bug template, thanks!

**Comment by Ravi-79** [comment]
@avelad updated the manifest URL in description. please check

**Comment by avelad** [comment]
Using the config `manifest.hls.sequenceMode = true`, I don't see any problem.

**Comment by Ravi-79** [comment]
Hi @avelad , Is that a default value for manifest.hls.sequenceMode = true or do we need to explicitly configure that?
I can't able to get this property in getConfiguration() method.

**Comment by avelad** [comment]
Hi @Ravi-79, I used the config that you post here. By default should be true, but in your config the field is missing.

**Comment by Ravi-79** [comment]
Hi @avelad , I can able to see the sequencemode under DASH only but not under HLS.
Even I can't able to set the Property by using configure() method.
![image](https://github.com/shaka-project/shaka-player/assets/131441182/8ad08f4d-f59d-41fd-9b2f-6813d011aa8f)

**Comment by joeyparrish** [comment]
`manifest.hls.sequenceMode` isn't in the v4.3.x branch.  It was first introduced in 2b50b88030d44c841daea8f67a3c51eb9b2284a4, which hasn't been put into a release.  As far as I can tell, that is unrelated to anything in the original report.  Let's please disregard that as debugging advice.

**Comment by Ravi-79** [comment]
Hi @joeyparrish , any update?

**Comment by avelad** [comment]
@Ravi-79 can you try with the main branch? Yesterday I fixed some HLS issues.

**Comment by Ravi-79** [comment]
Hi @avelad , I will test with the latest code and let you know.

**Comment by avelad** [comment]
@Ravi-79 do you have any news? Thanks!

**Comment by Ravi-79** [comment]
@avelad , we tested with fewer audience and can't get any buffering issue. We are currently testing with larger audience. 
I'll update the observation ASAP.
Thanks for the patience!
