### ISSUE TITLE
Stream freezes on Firefox after a seek.

### ISSUE THREAD

**Issue by matvp91** [shaka-project/shaka-player#5520]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not related to FairPlay.

**What version of Shaka Player are you using?**

v4.3.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Firefox 116.0.3 (latest) on macOS Monterey

**What are the manifest and license server URIs?**

See email, sorry for not being able to post publicly. The manifest is static.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default configuration

**What did you do?**

Most minimal implementation in order to reproduce the bug is here.
```javascript
<html>
  <head>
    <style>
      #videoElement {
        width: 340px;
      }
    </style>
  </head>
  <body>
    <video id="videoElement" controls></video>
  </body>
  <!-- 4.3.9 isn't available on CDN yet thus running the previous version but checked with the latest version and the bug remains. -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.3.8/shaka-player.compiled.debug.min.js"></script>
  <script>
    (async () => {
      const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

      const videoElement = document.getElementById("videoElement");

      videoElement.muted = true;

      const manifestUri =
        "__MANIFEST_URI__"; // Paste the manifest URI from the mail in here.

      const player = new shaka.Player(videoElement);

      await player.load(manifestUri);

      videoElement.play();

      await sleep(1000);

      videoElement.currentTime = 20;

      await sleep(1000);

      videoElement.currentTime = 5;
    })();
  </script>
</html>
```

I suspect a malformed manifest, fiddling with `streaming.inaccurateManifestTolerance` makes it play through but not consistently. Ran the same asset with dash.js and the same bug could not be reproduced there.

**What actually happened?**

```
(audio:6) cannot find segment endTime: 27.45 [shaka-player.compiled.debug.min.js:1:55081](https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.3.8/shaka-player.compiled.debug.min.js)
(audio:6) cannot find segment endTime: 27.45
```

A reference for the given time in the audio stream is not found, player is therefor endlessly buffering.

https://github.com/shaka-project/shaka-player/blob/cdf60aa20788bb3ffd63a02b69ccc40be4d0f343/lib/media/streaming_engine.js#L1124-L1132

Makes me wonder why Chrome runs this fine though.

**Comment by matvp91** [comment]
The difference with Chrome is that in Chrome, `this.sourceBuffers_[contentType].buffered` becomes empty after a seek while in Firefox it does not.

`bufferEnd` provided in `getSegmentReferenceNeeded_` is therefor always provided and the logic in that function takes a different code path.

**Comment by avelad** [comment]
Can you send the manifest to shaka-player-maintainers@googlegroups.com so we can investigate the issue? Thank you!
