### ISSUE TITLE
More Delay/Buffering in Shaka library compared to dash library. Why?

### ISSUE THREAD

**Issue by joyson-madtha0** [shaka-project/shaka-player#5526]
We are currently using Shaka Player on the website. Master manifest of one multi audio video is given below.
https://ef1d3defcf6fa0e21ac378f5ac916b69.egress.mediapackage-vod.ap-south-1.amazonaws.com/out/v1/0c446e1f92b54d108ce86c7c9b645e91/a67d66abbd1e4e4fbba6d2f68f7165e7/b8837af05884442b968cbd111a91d186/master.mpd
**Observation:**
This stream works seamlessly with less buffering on change of audio in [dash-if-reference-player](https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html). But same content will take more buffering time in Shaka Player ([shaka-player-demo](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://ef1d3defcf6fa0e21ac378f5ac916b69.egress.mediapackage-vod.ap-south-1.amazonaws.com/out/v1/0c446e1f92b54d108ce86c7c9b645e91/a67d66abbd1e4e4fbba6d2f68f7165e7/b8837af05884442b968cbd111a91d186/master.mpd;panel=CUSTOM%20CONTENT;build=uncompiled)) while switching to different audio. It took me around 6-30 seconds of delay to switch to different language in Shaka Player demo.
Same delay is observed with delay between master.mpd load to the first play of the video.

dash will start playback right after the first chunk load. Where as Shaka will load 6 to 7 chuncks to start playing for the stream. Is it possible to minimise this duration? Tried `streaming.retryParameters.stallTimeout` set to 0. But it doesnot seem to work.

**Platform:** Chrome-Mac(Incognito)

**Shaka Player version:** ^4.3.3

**Comment by avelad** [comment]
@theodab can you help here? Thanks

**Comment by avelad** [comment]
I have noticed that in your manifest you have this: `minBufferTime="PT30S"`.
This produces that we have to download 15 audio segments and 15 video segments before starting playback.

Two options:
- Modify your manifest to include a reasonable time, such as 3-4 seconds.
- Use `manifest.dash.ignoreMinBufferTime` config to ignore that value

**Comment by joyson-madtha0** [comment]
@avelad Thank you for the info. I do see the `minBufferTime` set to 2 seconds in other stream contents.
