### ISSUE TITLE
Absence of Offline Ads Management Support in Shaka Player for Primarily Offline Solutions

### ISSUE THREAD

**Issue by renatosalopes** [shaka-project/shaka-player#5535]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** 
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** 
Yes

**What version of Shaka Player are you using?**  
3

**Please ask your question**
The Shaka Player has solidified its reputation as a versatile media player that excels across various platforms. However, a critical functionality appears to be missing from its feature set, particularly for solutions that primarily operate offline: the capacity to manage and display advertisements (ads) in an offline environment.

In contexts where offline content consumption takes precedence, such as applications intended for low-connectivity environments or scenarios where users prefer downloaded content, offline ad support is crucial. Integrating this capability within Shaka Player could open new avenues for content monetization and improve user engagement for primarily offline solutions.

1. While waiting for an official implementation, would it be possible to explore workarounds or unconventional methods to manually integrate offline advertisement management into my codebase using Shaka Player? Are there any potential resources or insights you can provide to assist in this endeavor?

Thank you for your commitment to the Shaka Player project. We eagerly anticipate your guidance and input on the possibility of incorporating offline advertisement management capabilities into primarily offline solutions and any interim measures that could be explored.

**Comment by avelad** [comment]
Currently no one is working on this part and Shaka's maintainer team is not focused on providing this functionality. If anyone in the community is interested in working on it, we will be happy to review the designs and PR.

None of us have had the need for this scenario, so I can't guide you in a correct way to solve it, I'm sorry.

**Comment by renatosalopes** [comment]
Ok, thanks.
