### ISSUE TITLE
[Paramount] - Video Start Failure on Orange Set Top Box

### ISSUE THREAD

**Issue by willdharris** [shaka-project/shaka-player#5544]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

4.3.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
WebKit based environment
UserAgent:
```
"Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15 WPE/2.40.0 SOPOpenBrowser/2.40.0 Model/WHD95 Firmware/01.10.03
```

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Orange STB6 Model/WHD95 Firmware/01.10.03

**What are the manifest and license server URIs?**

`https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd`

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Load a test page with Shaka player onto the Orange device. 
Call play.

**What did you expect to happen?**
Playback to start without issue.

**What actually happened?**

Playback never starts.

Because the device gets categorized as Apple, the player defaults to using `src=` over `MediaSource`, and the manifest does not load. MSE is supported and should be used on this device.
https://github.com/shaka-project/shaka-player/blob/92edb7b1efe34acfca9b6df999688a5eec3e30c8/lib/player.js#L1414-L1422

**Comment by avelad** [comment]
Have you tried to configure `streaming.useNativeHlsOnSafari = false` and see if it works correctly MSE?

**Comment by avelad** [comment]
The possible bug is at https://github.com/shaka-project/shaka-player/blob/main/lib/util/platform.js#L212, are you interested in submitting a PR to fix this?

**Comment by avelad** [comment]
@willdharris Please send the PR and I'll review it asap.
