### ISSUE TITLE
Not able to manually switch to stream

### ISSUE THREAD

**Issue by bidisha15hotstar** [shaka-project/shaka-player#5551]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**What version of Shaka Player are you using?**

**Please ask your question**
1. On trying to forcefully switch to a given stream on 3016 , it does not switch rather it just pauses the player
Why does this happen?

Code:
```
onVariantUpdate: (variant, shouldBlackList) => {
  variant['allowedByBrowser'] = !shouldBlackList;
  // const currentPeriod =
  //     this.getPresentationPeriod_() || this.manifest_.periods[0];
  shaka.log.info('Ihrr', this.abrManager_.getVariants());
  let fil = this.abrManager_.getVariants();
  if (fil !== null) {
    let filteredVariants = fil.filter((abrVar)=> abrVar.id !== variant.id
      && abrVar.id !== 23);
    this.abrManager_.setVariants(filteredVariants);
    let chosenVariant = this.abrManager_.chooseVariant();
    shaka.log.info('Chosen variant from here', chosenVariant);
    let bandwidthEstimate = this.abrManager_.config_.
    bandwidthEstimator.getBandwidthEstimate(
      this.abrManager_.config_.defaultBandwidthEstimate);
    shaka.log.info('Bandwidth estimate', bandwidthEstimate);
    let currentBandwidthKbps = Math.round(bandwidthEstimate / 1000.0);
    shaka.log.info('current bandwidth kbps', currentBandwidthKbps);
    shaka.log.info(
      'Calling switch_(), bandwidth=' + currentBandwidthKbps + ' kbps');
    shaka.log.debug(
      'Calling switch_(), bandwidth=' + currentBandwidthKbps + ' kbps');
    // eslint-disable-next-line max-len
    // If any of these chosen streams are already chosen, Player will filter them
    // out before passing the choices on to StreamingEngine.
    this.abrManager_.switch_(chosenVariant);
    shaka.log.info('Perfect switch');
  }
  
```

this is called during error recovery controller whenever onerror is thrown
called like 
`this.playerInterface_.onVariantUpdate(activeVariant, true);`

```
const activeVariant = blacklistedVariant ||
    this.playerInterface_.getActiveVariant();
```
@joeyparrish  - please help resolving.

**Comment by joeyparrish** [comment]
Error 3016 is unrecoverable.  You can check the severity of the error object and see that `error.severity == shaka.util.Error.Severity.CRITICAL`.


See the definition of Severity from the docs at https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#.Severity :


Name | Value | Type | Description
-- | -- | -- | --
RECOVERABLE | 1 | number | An error occurred, but the Player is attempting to recover from the error. If the Player cannot ultimately recover, it still may not throw a CRITICAL error. For example, retrying for a media segment will never result in a CRITICAL error (the Player will just retry forever).
CRITICAL | 2 | number | A critical error that the library cannot recover from. These usually cause the Player to stop loading or updating. A new manifest must be loaded to reset the library.

**Comment by bidisha15hotstar** [comment]
But we are changing the recoverability from to RECOVERABLE - when we are throwing the error.
Why is it still not possible then?

@joeyparrish

**Comment by bidisha15hotstar** [comment]
@joeyparrish , any update on this?
Please let me know.

**Comment by joeyparrish** [comment]
The reason we label that error as critical is because the playback stack has to be torn down, all the way to the browser.  Changing the enum value doesn't change that fact.

The enum value is a description of what is wrong.  The enum value is not the thing that keeps it from working.

The only thing you can do after a decoder or demuxer error from the browser is call load() to restart the entire stack.

Does this help?

**Comment by bidisha15hotstar** [comment]
Absolutely. We are trying to give a seamless experience on 3016, from our end. 
Will raise a PR if we are able to do this. 

Thanks a lot for your clarification @joeyparrish !
Cheers. 👍

**Comment by bidisha15hotstar** [comment]
Resolved.
