### ISSUE TITLE
"After seek, playback takes 3 to 4 seconds to resume"

### ISSUE THREAD

**Issue by kumarashu123** [shaka-project/shaka-player#5556]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

4.3.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom and tried in demo also

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 116.0.5845.111 (Official Build) (64-bit) and Windows 11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

"streaming": {
                rebufferingGoal: 1,
                bufferBehind: 6,
                bufferingGoal: 10,
                inaccurateManifestTolerance: 0
}

**What did you do?**

1. Play vod or linear restart content 
2. Try to seek to some position like currentTime + 100
3. It takes 3 to 4 sec to start playback to the seek positioned

**What did you expect to happen?**
Playback should resume immediately after first audio and video segments download.

**What actually happened?**

When user try to seek to the specified position it should immediately resume playback to the seek position.
Only one video and audio segments should download and start playback.
Observed multiple audio and video segments getting downloaded and then playback resumed.

**Comment by avelad** [comment]
Please fill in the questions that are empty, specifically we need the manifest URI to be able to see what is happening.

**Comment by kumarashu123** [comment]
It's happen with all manifest like demo asset
https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths/dash.mpd

**Comment by joeyparrish** [comment]
I'm unable to reproduce the issue with that content.  I'm using ChromeOS stable 116.

**Comment by kumarashu123** [comment]
Is my streaming configuration creating this issue?

"streaming": {
rebufferingGoal: 1,
bufferBehind: 6,
bufferingGoal: 10,
inaccurateManifestTolerance: 0
}

can you please suggest what streaming configuration i need to put for smooth seek and playback ?

**Comment by avelad** [comment]
I tried your configuration and the playback is smooth for me.
