### ISSUE TITLE
Not all MPD Segments in live mode available/seekable.

### ISSUE THREAD

**Issue by whplh** [shaka-project/shaka-player#5560]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes, mostly.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Trying to upgrade from  "shaka-player": "3.1.0" to "shaka-player": "^4.3.9" (or any other of the more recent versions)

**Please ask your question**

I need some advice how to handle updates to the manfifest when a server is writing to a mpd file.
In this case `manifest?.presentationTimeline?.isLive() ` is true.
My problem is that  `const maxTime = videoController.getPlayer().seekRange().end;` is not the "true" maximum range to play and lags behind until the server process is finished creating the mpd file.
`seekRange` updates/increases continuously but always lags behind what is truly availbale in the manifest.
If I force reload of the whole player `player.load(...` then all the segments currently available are loaded.

In version 3.2 an interval with something like:
```
const segments = getSegments(manifest);
manifest.presentationTimeline.notifySegments(segments);
manifest.presentationTimeline.notifyMaxSegmentDuration(getLastSegment(manifest).getEndTime())
```
works for me and I always can play all the segments available.

But it breaks in every of the more recent versions. What do I miss? 
All availbale segments are present in the segment reference (via: `manifest?.variants?.[0]?.video?.segmentIndex?.get(i)` But the player cannot seek to these ranges unless I reload.
 
I'm using this player configuration
```
  player.configure('streaming.durationBackoff', 0);
  player.configure('abr.enabled', false);
  player.configure('manifest.dash.ignoreMinBufferTime', true);
```
and I'm aware that  `player.configure('streaming.updateIntervalSeconds', 1);` is the default. And I see the mpd requests, (but no segment requests, which is the same in 3.1.0)

Is a custom ManifestParser the way to try to fix this or am I missing something like `player.refreshFromManifest()`

Any suggestions very much appreciated.

**Comment by joeyparrish** [comment]
> My problem is that `const maxTime = videoController.getPlayer().seekRange().end;` is not the "true" maximum range to play and lags behind until the server process is finished creating the mpd file.

If the manifest describes segments individually, the player can't know about them until the server finishes creating the MPD.

If the manifest uses `SegmentTemplate` with a fixed `duration`, then it doesn't have to describe segments individually and the player doesn't have to update the manifest to know about them.  The internal timer is enough.

Does this help?
