### ISSUE TITLE
Playout fails: CHUNK_DEMUXER_ERROR_APPEND_FAILED

### ISSUE THREAD

**Issue by Peterdoo** [shaka-project/shaka-player#5572]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

v4.4.0

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
shaka-player-demo.appspot.com

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Latest Chrome under Windows 11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://ztnr.rtve.es/ztnr/1694255.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

shaka-player-demo.appspot.com

**What did you do?**

Started playing the HLS stream.

**What did you expect to happen?**
The stream should play as it does on other players and earlier versions of Shaka player.

**What actually happened?**

Shaka Error MEDIA.VIDEO_ERROR (4,,CHUNK_DEMUXER_ERROR_APPEND_FAILED: RunSegmentParserLoop: stream parsing failed. append_window_start=0 append_window_end=inf)

**Comment by avelad** [comment]
The stream is working in 4.3.x so it's a regression in the new transmuxer
