### ISSUE TITLE
Memory Optimization with Shaka Player

### ISSUE THREAD

**Issue by Akash4231** [shaka-project/shaka-player#5573]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YEs

**What version of Shaka Player are you using?**
4.2.13

**Please ask your question**
As we are working on very low end devices and are very considerate on even a single KB rise of memory. We wanted to understand what would be the best configuration so that runtime memory usage is at the lowest?

We have to play HLS, mp3 content along with DASH+Widevine. All the content is audio-only.

**Comment by avelad** [comment]
We currently have an open issue that DASH consumes more resources than HLS, so I recommend that you use HLS while we resolve the issue. See: https://github.com/shaka-project/shaka-player/issues/5668 Thanks!
