### ISSUE TITLE
Previous segment before load startTime is downloaded 

### ISSUE THREAD

**Issue by ethan-canva** [shaka-project/shaka-player#5574]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
N/A

**What version of Shaka Player are you using?**
4.4.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Sample Code on JSFiddle

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://dash.akamaized.net/dash264/TestCasesIOP33/adapatationSetSwitching/5/manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default

**What did you do?**

Set a `startTime` with `Player.load()`
eg: `player.load(manifestUri, 5, 'application/dash+xml')`;

**What did you expect to happen?**
I expect only the segment that covers the `startTime` specified in `Player.load` to be downloaded

**What actually happened?**
The previous segment which does not cover the `startTime` is downloaded.

For example:
With 2 seconds segments,
0 --- 2 --- 4 --- 6
When startTime is set to 5, It will download segment 2 and segment 3 instead of just segment 3. Is this an expected behaviour?

sample: https://jsfiddle.net/4ocdqnrv/1/

**Comment by joeyparrish** [comment]
Yes, this is expected.  It is a way to compensate for DASH's vague requirement that timestamps only be "approximately" accurate, which they define elsewhere to be +/- 50% of a segment duration.  If we pick one segment early, playback will still work.  If we pick one segment late, playback will stall.  So we play it safe by going one early.

If you know your content is accurate, you can override this behavior with the config `streaming.inaccurateManifestTolerance`, which is in seconds:

```js
player.configure('streaming.inaccurateManifestTolerance', 0);
```

**Comment by ethan-canva** [comment]
thanks for your explanation, it makes sense.
