### ISSUE TITLE
Shaka Player TextTrack - console.log since 4.4.0

### ISSUE THREAD

**Issue by francoism90** [shaka-project/shaka-player#5581]
**What version of Shaka Player are you using?**
4.4.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
No, the demos seem to be running fine.

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Firefox, Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
N/A

**What did you do?**
I'm using this in Laravel (Vite):
```
import shaka from 'shaka-player/dist/shaka-player.ui'

shaka.polyfill.installAll()

window.shaka = shaka
```

**What did you expect to happen?**
No logging

**What actually happened?**
It happens after upgrading to 4.4.0, something seems to be logging, but I cannot find the `console.log` in the Shaka code?
Downgrading to the previous release, fixes the issue.

The following messages are being logged in console:
```
TextTrack { kind: "subtitles", label: "Shaka Player TextTrack", language: "", id: "" ...
```
This is a part of the compiled source using Vite:
```
(Array.from(e.textTracks)),n=t.next();!n.done;n=t.next())n=n.value,n.mode="disabled",n.label=="Shaka Player TextTrack"&&(this.g=n);this.g||(this.g=e.addTextTrack("subtitles","Shaka Player TextTrack"),console.log(this.g)),this.g.mode="hidden"}
```

Thanks

**Comment by francoism90** [comment]
@avelad It seems the package on NPM hasn't been updated/bump.

Sorry to tag you, I can open an issue if you want.

**Comment by avelad** [comment]
Please, open a new issue!
