### ISSUE TITLE
How to modify the seek range end value to use a custom value ?

### ISSUE THREAD

**Issue by jdguser** [shaka-project/shaka-player#5583]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
4.3.8

**Please ask your question**
Currently, we are facing an issue while fast forwarding to the last segment of the content after an ad pod (DASH with DRM), the issue is being caused because of the seek range limitations that the content has.

We are using the same player to playback the main content along with its ads, so it seems it is causing the issue since the duration of the content without ads is lower than with ads, and the player is just allowing us to seek until that limit because it is what is being returned in the manifest file.

For example, the seek range limit is 1249 seconds (The duration of the content without ads) but the ads are causing the player to have a higher timeline, for example, 1700 seconds.

So the player gets frozen if we try to seek 1250.

Is there a way to modify programatically the seek range end value to the total duration with ads for the DASH/DRM content ?

Thanks a lot for your help.

**Comment by avelad** [comment]
You can use `manifest.availabilityWindowOverride` (https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.ManifestConfiguration)  to change the length value, does it help?
