### ISSUE TITLE
video and audio slip out of sync

### ISSUE THREAD

**Issue by jesscalvert** [shaka-project/shaka-player#5584]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What link can we use to reproduce this?**
https://v4-3-2-dot-shaka-player-demo.appspot.com/demo/#audiolang=ja;textlang=ja;uilang=ja;asset=https://7a5aa5b9.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlbkpQLXdlYl9UcmF2ZWxYUF9DTUFG/playlist.m3u8;panel=CUSTOM%20CONTENT;build=compiled

**What version of Shaka Player are you using?**
v4.3.2

**What browser and OS are you using?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**What did you do?**

This stream is restricted to Japan, please use a VPN to access it. 
Watch the stream and usually within about 15 minutes, a video segment is repeated while the audio for the segment is not repeated. Because the .ts segments for this particular stream are 6 seconds in length, the audio sync issue is such that the audio is 6 seconds ahead of the video. When the stream goes into an ad break, the issue is resolved for a bit, but then it will eventually slip again. It's not a gradual slip of sync, rather, there will be a very jarring moment when the .ts video repeats and the audio is instantly out of sync. This happens on multiple streams, but we are only able to share this one stream. 

**What did you expect to happen?**
The audio and video should remain in sync during playout. 

**What actually happened?**

**Comment by Peterdoo** [comment]
I have seen this problem yesterday with the demo player v4.4.1 with the following stream:
https://ztnr.rtve.es/ztnr/1694255.m3u8

Video was few seconds behind the audio after some time. Probably as mentioned above, video from previous chunk was played together with the audio from the current chunk (video and audio are multiplexed in the same .ts here).

I have seen it only once after having the Chrome playing in background for some time and activating it again. I couldn't reproduce it again yet.

**Comment by dacoten** [comment]
@avelad @joeyparrish 
I'm sorry, but I tried playing the video with the new version 4.4.3, and the issue still persists. The audio loop happens multiple times. Could you please check it?
Thanks.

https://v4-4-3-dot-shaka-player-demo.appspot.com/demo/#audiolang=ja;textlang=ja;uilang=ja;asset=https://7a5aa5b9.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlbkpQLXdlYl9UcmF2ZWxYUF9DTUFG/playlist.m3u8;panel=CUSTOM%20CONTENT;build=compiled

**Comment by jesscalvert** [comment]
@avelad I have the same issue still as well, can you let me know how to try with the main branch?

**Comment by dacoten** [comment]
@avelad-san
Please help us resolve this issue.
Thanks!
