### ISSUE TITLE
Blocking Playlist Reload Support

### ISSUE THREAD

**Issue by diogoazevedos** [shaka-project/shaka-player#5594]
**Is your feature request related to a problem? Please describe.**
The player is not issuing blocking playlist requests when the manifest has the following:
```m3u8
#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES
```

**Describe the solution you'd like**
When the manifest includes the data above, the playlist must be reloaded immediately, not delayed by: https://github.com/shaka-project/shaka-player/blob/17e4ef25c0f069002c6777e77569cbf90d538449/lib/hls/hls_parser.js#L3698-L3705

**Additional context**
[6.2.5.2](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-6.2.5.2) Blocking Playlist Reload

⚠️ The bandwidth estimation may be affected by the blocking requests.

**Comment by avelad** [comment]
HLS blocking playlist reload is already supported, see: https://github.com/shaka-project/shaka-player/blob/main/lib/hls/hls_parser.js#L2357 and https://github.com/shaka-project/shaka-player/blob/main/lib/hls/hls_parser.js#L352

I'm going to close this issue, if you have any issue with this funcionality, please open a new issue with bug template. Thanks!
