### ISSUE TITLE
4.4.1 not published on NPM

### ISSUE THREAD

**Issue by francoism90** [shaka-project/shaka-player#5599]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.4.0

**Please ask your question**
I cannot find 4.4.1 on NPM, why? :)

**Comment by joeyparrish** [comment]
In the workflow logs, I see that the npm publish workflow failed:
https://github.com/shaka-project/shaka-player/actions/runs/6070157677/job/16465708155

```
Run npm publish
  npm publish
  shell: /usr/bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: ***

> shaka-player@4.4.1 prepublishOnly
> python build/checkversion.py && python build/all.py --force

Error:  Player version does not match git version.
git version: v4.4.1
npm version: 4.4.1
player version: v4.4.0-uncompiled
changelog version: 4.4.1
npm ERR! code 1
npm ERR! path /home/runner/work/shaka-player/shaka-player
npm ERR! command failed
npm ERR! command sh -c -- python build/checkversion.py && python build/all.py --force

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-09-04T07_00_27_651Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by joeyparrish** [comment]
The release PR did not update the version in `player.js`: https://github.com/shaka-project/shaka-player/pull/5591/files

The release PR for 4.3.11 has the same problem: https://github.com/shaka-project/shaka-player/pull/5592/files

I did not notice that the player.js change was missing.

Compare to v4.3.10, which worked correctly: https://github.com/shaka-project/shaka-player/pull/5563/files

The most likely culprit is a workflow change I made recently: https://github.com/shaka-project/shaka-player/pull/5585 and the follow-up https://github.com/shaka-project/shaka-player/pull/5588

**Comment by joeyparrish** [comment]
Both missing versions patched and published manually

**Comment by absidue** [comment]
Thanks for fixing this, unfortuntately it looks one more thing needs to be done, the latest tag on npm should point to `4.1.1`  instead `4.3.11`, which it currently points to.

**Comment by joeyparrish** [comment]
That's what I get for doing it manually and doing 4.3 last.  I'll fix it.

In general, this could still happen from the automated workflows, though.  They don't differentiate between branches, so `latest` == most recent.  Ideally, the workflow would be explicit about only updating `latest` when we release from the most recent release branch.  The appspot parts of the workflow do something similar, so it shouldn't be hard to adapt if I can figure out the `npm` commands.

**Comment by joeyparrish** [comment]
Fixed manually for now.

```
$ npm dist-tag ls
latest: 4.4.1
```

**Comment by francoism90** [comment]
Many thanks for the quick fix. 👍

**Comment by absidue** [comment]
Thank you for the quick fixes. Please don't be too harsh on yourself, I don't think it's possible to make GitHub actions workflows or changes to them that work the first time, at least nobody I've talked to has managed it.

**Comment by joeyparrish** [comment]
Yes, it's tough, even when you test workflows on a fork first, you can't _fully_ test releasing without doing a release.

I think the permanent fix for "latest" will be up for review soon.  Thanks to you both for the feedback!
