### ISSUE TITLE
Can I make Shaka only load and parse the manifest, but defer loading any media segments?

### ISSUE THREAD

**Issue by turbidwater** [shaka-project/shaka-player#5609]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.7

**Please ask your question**
I have an interesting use case where I'd like to have Shaka load the manifests for a live stream and poll them and report the duration, but not load any media segments. Preferably, later on I could then turn the media loading on to start playback, though this is not required. Is this possible with Shaka?

**Comment by avelad** [comment]
This functionality is not supported in Shaka Player. Sorry!

**Comment by turbidwater** [comment]
Ok, thanks for the response!
