### ISSUE TITLE
Add Picture-in-Picture functions to shaka.ui.Controls like the full screen ones

### ISSUE THREAD

**Issue by absidue** [shaka-project/shaka-player#5617]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Since version 4.4.0 shaka-player supports both the normal Picture-in-Picture API and the document Picture-in-Picture API. The document Picture-in-Picture API requires a much more elaborate setup and tear-down process than the normal Picture-in-Picture API, unfortunately in shaka that code is buried inside the Picture-in-Picture button. Due to that code being buried inside the Picture-in-Picture button, it means that to toggle Picture-in-Picture programatically (e.g. for hotkeys), you either need to programatically click the button or reimplement shaka's document Picture-in-Picture API in your own code.

**Describe the solution you'd like**
It would be nice to have functions on shaka.ui.Controls to control and query Picture-in-Picture, similar to the existing ones for full screen. To avoid duplicate code across the project, the Picture-in-Picture button could then rely on those functions on the Controls class, just like the full screen button does.

- [`isFullScreenEnabled()`](https://shaka-player-demo.appspot.com/docs/api/shaka.ui.Controls.html#isFullScreenEnabled)
- [`isFullScreenSupported()`](https://shaka-player-demo.appspot.com/docs/api/shaka.ui.Controls.html#isFullScreenSupported)
- [`toggleFullScreen()`](https://shaka-player-demo.appspot.com/docs/api/shaka.ui.Controls.html#toggleFullScreen)

**Describe alternatives you've considered**
Programatically clicking the Picture-in-Picture button e.g.

```javascript
const pipButton = document.querySelector('.shaka-pip-button')

 if (pipButton && !pipButton.classList.contains('shaka-hidden')) {
  pipButton.click()
}
```

**Comment by joeyparrish** [comment]
That makes perfect sense.  I'm very much open to a PR that factors PiP methods out of the button and into Controls.

**Comment by avelad** [comment]
I created a PR with this: https://github.com/shaka-project/shaka-player/pull/5629
