### ISSUE TITLE
Is it possible to set only subtitles without credentials?

### ISSUE THREAD

**Issue by asnaeal** [shaka-project/shaka-player#5626]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.0.0

**Please ask your question**
I'm getting videos and subtitles from other servers
The video needs credential setting, so I set 'use-credentials' in the crossorigin of the video
However, I don't want to set the credentials because I want the subtitle file to be imported from the common file server
As a result, there is a problem as below
~has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'.
Is there any solution to resolve this problem?

**Comment by avelad** [comment]
Hi! In the new versions you can get the stream from [RequestContext](https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.RequestContext), na dinside the steram you can get the type.

**Comment by asnaeal** [comment]
Are you telling me to check if the type of stream is text in the RequestFilter and set the credentials?

**Comment by avelad** [comment]
> Are you telling me to check if the type of stream is text in the RequestFilter and set the credentials?

Yes

> i added track inside the video tag and changed the crossorigin of the video tag to 'anonymous' to proceed without any problems.

Ok, I'm going to close the issue. Thanks!
