### ISSUE TITLE
[docs] Response to a question in FAQ.md is wrong

### ISSUE THREAD

**Issue by loicraux** [shaka-project/shaka-player#5634]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes, the issue lies precisely in the FAQ itself :)

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

N/A

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `main`?**

yes

**Are you using the demo app or your own custom app?**

N/A

**If custom app, can you reproduce the issue using our demo app?**

N/A

**What browser and OS are you using?**

N/A

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A

**What are the manifest and license server URIs?**

N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

N/A

**What did you do?**

On the [FAQ page](https://shaka-player-demo.appspot.com/docs/api/tutorial-faq.html), the answer to the question `Q: I am getting UNSUPPORTED_SCHEME or error code 1000 when loading from file://.` is the following :

```
A: In a browser environment, trying to load a file from file:// is inappropriate. Therefore, we do not provide a default network plugin for such requests.

In other environments, for example Electron, it is appropriate. In those cases, before Shaka Player loads a manifest, you can register the existing http plugin for file:// requests:

shaka.net.NetworkingEngine.registerScheme('file', shaka.net.HttpXHRPlugin);
```

**What did you expect to happen?**
**What actually happened?**

The correct answer is the following :

```js
shaka.net.NetworkingEngine.registerScheme('file', shaka.net.HttpXHRPlugin.parse); // <-- note the .parse
```

**Comment by joeyparrish** [comment]
PRs are always welcome!

**Comment by loicraux** [comment]
OK I'll create a PR for this one :)
