### ISSUE TITLE
Play org.w3.clearkey cross-plat (including Safari)

### ISSUE THREAD

**Issue by Chokoabigail** [shaka-project/shaka-player#5640]
I want to be able to play `ClearKey` encryption in Safari as well as in Chrome, is it possible? if so, is there a guide with an example of how it can be implemented?

**Comment by avelad** [comment]
Currently not possible due to a bug in Safari, see https://bugs.webkit.org/show_bug.cgi?id=231006 . Sorry...

**Comment by Chokoabigail** [comment]
@avelad Thanks for the quick response, Does this bug affect all variants of ClearKey (Sample-aes/AES-128 on fmp4/ts)? or does it affect only the fmp4 sample-aes version?

**Comment by avelad** [comment]
this affect to ClearKey DRM

**Comment by Chokoabigail** [comment]
As far as I understood (and please correct me if I'm rung) ClearKey can be implemented in different ways.
HLS-128 HLS is a clear key (no DRM needed like Fairplay etc.) but it seems to work only on .ts files.
Sample-aes HLS is a clear key as well and it supports both fmp4 and.ts files

Is it true? or do I mix up staff here?

**Comment by joeyparrish** [comment]
HLS AES-128 delivers a key in the clear, but this is distinct from ClearKey DRM, which is an implementation of a Common Encryption (CENC) DRM scheme that also happens to deliver keys in the clear.

Every other aspect of these two things is different, and they are mutually incompatible.

HLS-AES-128 involves encryption of the entire segment, with no complicated scheme applied.  With the key, we can decrypt this from JavaScript with the WebCrypto API.

ClearKey DRM, on the other hand, has to be implemented by the browser/CDM, which understands how to apply decryption to specific parts of the media segment.  Even with the key, it would be very difficult to directly decrypt it in JavaScript.  So we supply a license and other details to the CDM using the MediaKeys API (part of EME).

You can't use a ClearKey CDM implementation to decrypt HLS-AES-128, and you can't use WebCrypto to naively decrypt HLS-AES-128 content.  They are incompatible, even though both deliver keys in the clear.

**Comment by Chokoabigail** [comment]
@joeyparrish Thanks so much for the well-explained answer.
If I understood you then what I'm actually looking for is probably HLS AES-128 and not ClearKey (since Apple has a bug in it, and we do have support cross-plat on AES-128).
Do Shaka players support HLS-AES-128? If so, is there a guide with an example of how it can be implemented?
