### ISSUE TITLE
How to configure shaka-player to stream AES-128 

### ISSUE THREAD

**Issue by Chokoabigail** [shaka-project/shaka-player#5648]
After a question in a different closed thread, I tried to make Shaka play an AES-128 HLS file.

I created the HLS AES-128 using the following `ffmpeg` command:
```
/usr/local/lib/python3.9/dist-packages/streamer_binaries/ffmpeg-linux-x64 -i ../a.mp4 -hls_time 9 -hls_key_info_file ../keyfile -hls_playlist_type vod -hls_segment_filename fileSequence%d.ts hls.m3u8
```

This is the content of the `keyfile`:
```
https://www.httpstest.com:600/key.key
key.key
00000000000000000000000000000000
```

and this is the content of `key.key`:
```
aaaaaaaaaaaaaaaa
```

When tried to play it in `hls.js` this worked fine, but I couldn't make it work in Shaka-player.

Is Shaka-player support playing `HLS AES-128`? if so, can you help me please understand how to configure 
Shaka player to play it or direct me to a guide with an example of how it can be implemented?

**Comment by avelad** [comment]
HLS AES-128 is supported and working, can you share a test URL so we can see what happens?

**Comment by joeyparrish** [comment]
Yes, this feature does not generally require any configuration.  A test stream URL would be very helpful.

**Comment by Chokoabigail** [comment]
Sorry for the late response, we are in a different time zone.
Here are the files:
[ffmpeg_ts_encrypted.zip](https://github.com/shaka-project/shaka-player/files/12605385/ffmpeg_ts_encrypted.zip)

This is the command I used to create them:
`/usr/local/lib/python3.9/dist-packages/streamer_binaries/ffmpeg-linux-x64 -i ../a.mp4 -hls_time 9 -hls_key_info_file ../keyfile -hls_playlist_type vod -hls_segment_filename fileSequence%d.ts ffmpeg_ts_encrypted.m3u8`

as I mentioned, `hls.js` plays them fine, and `shaka` prints this error:
```
{
    "severity": 2,
    "category": 4,
    "code": 4022,
    "data": [],
    "handled": false
}
```

Looks like he has some issues with the `m3u8` file (based on the error code + the fact he doesn't try to download any file except the main `m3u8` file)

**Comment by TREER00T** [comment]
To solve this problem, you must have a master.m3u8 file so that shak can parse the main m3u8 file through this file.


To solve this problem, create your hls file like this by adding this parameter


`-master_pl_name master.m3u8`


Full command:




`/usr/local/lib/python3.9/dist-packages/streamer_binaries/ffmpeg-linux-x64 -i ../a.mp4 -hls_time 9 -hls_key_info_file ../keyfile -hls_playlist_type vod -hls_segment_filename fileSequence%d.ts ffmpeg_ts_encrypted.m3u8 -master_pl_name master.m3u8
`

**Comment by TREER00T** [comment]
I'm guessing you haven't uploaded your key on the server side that's why you're getting this problem

Please make sure that the key can be downloaded successfully through this address

https://www.httpstest.com:771/key.key

**Comment by Chokoabigail** [comment]
I doubled check, it's working and downloadable (the password is `aaaaaaaaaaaaaaaa`).
I checked the Networking f12 page, and it looks like `shaka` didn't attempt to download it.

**Comment by Chokoabigail** [comment]
`packager-linux-x64 'in=/tmp/shaka-live-jduc48fw/00ff9d24-dc59-412a-a23f-4d0de9098c45,stream=video,init_segment=output_files/video_360p_400k_h264_init.mp4,segment_template=output_files/video_360p_400k_h264_$Number$.mp4' 'in=/tmp/shaka-live-jduc48fw/1ba91628-ccb6-4191-b2cf-40ccee818f6c,stream=audio,language=eng,init_segment=output_files/audio_eng_2c_128k_aac_init.mp4,segment_template=output_files/audio_eng_2c_128k_aac_$Number$.mp4' --segment_duration 10 --hls_playlist_type VOD --hls_master_playlist_output output_files/hls.m3u8`

This creates the HLS, then I manually encrypt the results to `aes-128`

**Comment by TREER00T** [comment]
Finally i found this [issue](https://github.com/shaka-project/shaka-player/issues/850) which describe Why AES-128 doesnt support on shaka packager

**Comment by TREER00T** [comment]
If the issue of security is important for your content, I suggest you not to use this method to keep your content safe. In this method, due to the availability of the encryption key in the user's browser, the content can be downloaded and viewed, and this content is only for It is used to prevent mitm attack, but this method is no longer used. You can use new methods such as Clearkey or using famous DRMs such as widevine, playready, or Fireplay to protect your content.

**Comment by Chokoabigail** [comment]
@joeyparrish @avelad Here is a link you can test: https://testenc.eshetmag.com/hls.m3u8

This link works on `HLS.js` and doesn't work in `shaka-player`.
The way we can test them is:
`HLS.js`: https://hlsjs.video-dev.org/demo/?src=https%3A%2F%2Ftestenc.eshetmag.com%2Fhls.m3u8&demoConfig=eyJlbmFibGVTdHJlYW1pbmciOnRydWUsImF1dG9SZWNvdmVyRXJyb3IiOnRydWUsInN0b3BPblN0YWxsIjpmYWxzZSwiZHVtcGZNUDQiOmZhbHNlLCJsZXZlbENhcHBpbmciOi0xLCJsaW1pdE1ldHJpY3MiOi0xfQ==

`Shaka` using the demo website custom content: https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by Chokoabigail** [comment]
Any update on this? if there is a need to add code I'm willing to do that, just point me to what needs to be changed and I will code this.

**Comment by avelad** [comment]
@Chokoabigail I tried to use your URL, but it doesn't work. can you review? Thanks!
