### ISSUE TITLE
DASH live stream doesn't play when SegmentTimeline has a duration 0 "S" element

### ISSUE THREAD

**Issue by dk00** [shaka-project/shaka-player#5649]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes, there's no related thing.

**If the problem is related to FairPlay, have you read the tutorial?**

Not related(clear content).

**What version of Shaka Player are you using?**

4.2.2 and 4.4.1 (latest 2023-09-12)

**Can you reproduce the issue with our latest release version?**

Yes(4.4.1)

**Can you reproduce the issue with the latest code from `main`?**

I'll try it later.

**Are you using the demo app or your own custom app?**

Custom app

**If custom app, can you reproduce the issue using our demo app?**

Yes, with a AWS MediaPackage live stream, start-over enabled.

**What browser and OS are you using?**

Chrome 116.0.5845.179

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

Not for embedded devices

**What are the manifest and license server URIs?**

A live DASH manifest(start-over enabled) of a AWS MediaPackage live stream, and it is gone.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```js
{
  manifest: {
    retryParameters: defaultRetryParameters,
    availabilityWindowOverride: null,
    disableAudio: false,
    disableVideo: false,
    disableText: false,
    disableThumbnails: false,
    defaultPresentationDelay: 0,
    segmentRelativeVttTiming: false,
    dash: {
      clockSyncUri: '',
      ignoreDrmInfo: false,
      disableXlinkProcessing: false,
      xlinkFailGracefully: false,
      ignoreMinBufferTime: false,
      autoCorrectDrift: true,
      initialSegmentLimit: 1000,
      ignoreSuggestedPresentationDelay: true,
      ignoreEmptyAdaptationSet: false,
      ignoreMaxSegmentDuration: false,
    },
    hls: {
      ignoreTextStreamFailures: false,
      ignoreImageStreamFailures: false,
      defaultAudioCodec: 'mp4a.40.2',
      defaultVideoCodec: 'avc1.42E01E',
      ignoreManifestProgramDateTime: false,
    },
  },
  streaming: {
    retryParameters: defaultRetryParameters,
    rebufferingGoal: 0,
    bufferingGoal: 10,
    bufferBehind: 30,
    ignoreTextStreamFailures: false,
    alwaysStreamText: false,
    startAtSegmentBoundary: false,
    gapDetectionThreshold: 0.5,
    durationBackoff: 1,
    forceTransmuxTS: false,
    safeSeekOffset: 0,
    stallEnabled: true,
    stallThreshold: 1,
    stallSkip: 0.1,
    useNativeHlsOnSafari: true,
    inaccurateManifestTolerance: 2,
    lowLatencyMode: false,
    autoLowLatencyMode: false,
    forceHTTPS: false,
    preferNativeHls: false,
    updateIntervalSeconds: 1,
    dispatchAllEmsgBoxes: false,
    observeQualityChanges: false,
    maxDisabledTime: 30,
  },
  abr: defaultAbrOptions,
  preferredAudioLanguage: '',
  preferredTextLanguage: '',
  preferredVariantRole: '',
  preferredTextRole: '',
  preferredAudioChannelCount: 2,
  preferredVideoCodecs: [],
  preferredAudioCodecs: [],
  preferForcedSubs: false,
  preferredDecodingAttributes: [],
  restrictions: defaultRestrictions,
  playRangeStart: 0,
  playRangeEnd: null,
  cmcd: {enabled: false, sessionId: '', contentId: '', useHeaders: false},
}
```

**What did you do?**

There should be various ways to make `<S d=0 />` elements happen, here's the situation I encountered:

- Create an AWS MediaPackage live stream
- Start ingestion
- Play the DASH live stream with Shaka player in my custom app
- Stop ingestion
- The player displays loading indicator after a few seconds, as expected
- Wait for 3 minutes
- Start ingestion again
- The player keep displaying loading indicator without loading & playing new segments
- The player keep saying `"S" element must have a duration: ignoring the remaining "S" elements.` in console

I was able to workaround it by rewriting `d="0"` to `d="1"`, these `d="0"` "S" elements are generated after resume of ingestion.

Actually the "S" element do have a duration, its duration is `0`.

The message comes from [lib/dash/mpd_utils.js](https://github.com/shaka-project/shaka-player/blob/main/lib/dash/mpd_utils.js#L163):

```js
if (!d) {
  shaka.log.warning(
    '"S" element must have a duration:',
    'ignoring the remaining "S" elements.', timePoint);
  return timeline;
}
```
Does it work if we check it with `d != unll`?

**What did you expect to happen?**

It should keep playing available segments(skip through missing segments?).

One of another commercial DASH player plays well.

**What actually happened?**

It just keep updating the manifest, but no new segments are loaded.

**Comment by avelad** [comment]
@joeyparrish can you review it?

**Comment by joeyparrish** [comment]
@dk00, how is a duration of 0 meant to be interpreted?  Do they occupy space in the timeline?  Should they occupy a slot in our internal reference list?  Should those segments be fetched?  If they have `$Time$` in a segment template, and the timeline doesn't advance, should we assign the same URL to the d=0 segments and the one that follows with d!=0?

**Comment by dk00** [comment]
$Number$ variable is used to identify the specific segment, `d="0"` means a segment is not available and should not be fetched.

For example:

- segment 1037 d = 95232
- segment 1038 d = 0
- segment 1039 d = 95256

If I rewrite it to `d="1"`, the player retries for a few times and recovers.

Here's log:
```
GET https://xxxxxx.cloudfront.net/out/v1/…/index_audio_6_0_1038.mp4?m=1694743477 net::ERR_FAILED 404 (Not Found)
(audio:7) failed fetch and append: code=1002
Updating manifest...
notifySegments: maxSegmentDuration=2.0479999999997744
...
notifyNewSegmentDuration: maxSegmentDuration=2.0479999999997744
Already got the variants' decodingInfo.
Recoverable NETWORK HTTP_ERROR, trying to recover...
switch: Stream (video:4) already active
switch: switching to Stream (audio:5)
(audio:5) clearing buffer
(audio:5) cleared buffer
(audio:5) looking up segment from new stream endTime: 2076.362666
(audio:5) fetchAndAppend_: presentationTime=2075.888101 reference.startTime=2074.3786666666665 reference.endTime=2076.368
(audio:5) fetching init segment
(audio:5) appending init segment
(audio:5) buffer behind too large: presentationTime=2075.888101 bufferedBehind=41.08810100000005 bufferBehind=30 overflow=11.088101000000051
(audio:5) evicted 11.088101000000051 seconds
(audio:5) appending media segment at unknown
(audio:5) finished fetch and append [{"start":2045.893333,"end":2076.362666}]
...
(resumed playback)
```

Recovery works with audio, but not video, if `d="0"` occurs with video segments, the player doesn't not recover.

MediaPackage claims to support `$Time$`, I'll figure out how to configure it.

**Comment by avelad** [comment]
@joeyparrish can you review it?
