### ISSUE TITLE
How to decrypt m3u8 file before load on shaka

### ISSUE THREAD

**Issue by TREER00T** [shaka-project/shaka-player#5652]
Hello, I have encrypted the content of the m3u8 file on the server side and I want to decrypt it on the front side using the algorithms I have written, but I don't know how I can do this. In Hls.js, it can be done easily using objects. I do [pLoader](https://github.com/video-dev/hls.js/blob/master/docs/API.md#ploader)

Is there also a possibility implemented in shaka or not?

**Comment by avelad** [comment]
Yes, you can use a response filter to process data coming from the server.

**Comment by TREER00T** [comment]
Excellent, can you provide me with an example of a documentation for this section?

**Comment by TREER00T** [comment]
Finally I researched the documentation again and got the implementation how I want to share this process


```js
player.getNetworkingEngine().registerResponseFilter(function(type, response, context) {
     const StringUtils = shaka.util.StringUtils;

     if (type == shaka.net.NetworkingEngine.RequestType.MANIFEST) {
        const wrappedString = StringUtils.fromUTF8(response.data);
        // implement your logic to decrypt m3u8
        response.data = StringUtils.toUTF8(wrappedString)
    }

})
```
