### ISSUE TITLE
Seeking not working as expected on certain multi period DASH streams in 4.4.x

### ISSUE THREAD

**Issue by littlespex** [shaka-project/shaka-player#5664]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

`4.4.2`. This issue does not occur in `4.3.12`.

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome 117.0.5938.62, Safari 16.6 (18615.3.12.11.2), MacOS Ventura 13.5.2 (22G91)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

Sent via email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

1. Load the stream
2. Once playback begins, seek somewhere in the middle of the stream (most noticeable when seeking to a different period)

**What did you expect to happen?**
The player jumps to the new playhead time, starts loading segments starting at the new playhead time and begins playback.

**What actually happened?**

The player loads all segments between the original playhead time and the seek time resulting in a long "buffering" period before playback resumes.

https://github.com/shaka-project/shaka-player/assets/1508707/e296d758-fad5-470c-ae70-8592594effd4

**Comment by avelad** [comment]
@littlespex are you interested on send a PR to fix it?

**Comment by littlespex** [comment]
Update: The issue was introduced in commit f1c5a1c19126832184f43b0d08e9503a34b0dac0

**Comment by littlespex** [comment]
The segment iterator is not returning the correct initial value, and the `update_` function has to tick through all the interim values before finding the correct segment. Adding the following code at the end of `StreamingEngine`'s `getSegmentReferenceNeeded_` function fixes the issue, but seems dangerous:

```ts
      while (mediaState.segmentIterator && presentationTime > ref.endTime) {
        ref = mediaState.segmentIterator.next().value;
      }
```

**Comment by koenoe** [comment]
This issue is still happening for us, we don't have it in 4.3.x, but we do in 4.4.x and 4.5.x
