### ISSUE TITLE
Bug - shaka-player don't play AES-128 HLS according the RFC

### ISSUE THREAD

**Issue by Chokoabigail** [shaka-project/shaka-player#5667]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

It's not related to Fairplay, this is AES-128

**What version of Shaka Player are you using?**

The latest release (4.4.2), the DEMO site, and the latest version in Github (download and compile myself)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Tested on both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Edge, Chrome, Windows 10, Windows 11

**What are the manifest and license server URIs?**

Here are manifest examples:
`HLS.m3u8`
```
#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.6.1-634af65-release

#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_0.m3u8",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"

#EXT-X-STREAM-INF:BANDWIDTH=325411,AVERAGE-BANDWIDTH=325411,CODECS="avc1.4d401e,mp4a.40.2",RESOLUTION=654x360,FRAME-RATE=29.970,VIDEO-RANGE=SDR,AUDIO="default-audio-group",CLOSED-CAPTIONS=NONE
stream_1.m3u8
```

`stream_1.m3u8`
```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version v2.6.1-634af65-release
#EXT-X-TARGETDURATION:2
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://www.httpstest.com:771/key.key",IV=0x00000000000000000000000000000000
#EXT-X-MAP:URI="video_360p_400k_h264_init.mp4"
#EXTINF:0.934,
video_360p_400k_h264_1.mp4
#EXT-X-ENDLIST

```

`stream_0.m3u8`
```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version v2.6.1-634af65-release
#EXT-X-TARGETDURATION:2
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://www.httpstest.com:771/key.key",IV=0x00000000000000000000000000000000
#EXT-X-MAP:URI="audio_eng_2c_128k_aac_init.mp4"
#EXTINF:1.022,
audio_eng_2c_128k_aac_1.mp4
#EXT-X-ENDLIST
```

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

No special configuration, just a vanilla player.

**What did you do?**

I created an `fmp4` HLS (using `shaka-packager`) and then encrypted `AES-128` all the `.mp4` files (please note, AES-128 is different from the Clear-key even do the key is also sent in clear, I saw the term `envelop-encryption` for it).

The RFC of HLS states that the `init` files should also be encrypted by `AES-128` (and Apple devices follow this), here is a similar bug that `HLS.js` had: https://github.com/video-dev/hls.js/issues/2259 and here is the RFC:  https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-06
```
The EXT-X-KEY tag specifies how to
   decrypt them.  It applies to every Media Segment and to every Media
   Initialization Section declared by an EXT-X-MAP tag that appears
   between it and the next EXT-X-KEY tag in the Playlist file with the
   same KEYFORMAT attribute (or the end of the Playlist file).
```

**What did you expect to happen?**
As the RFC (and Safari, and the rest of the Apple products do) states, the player should decrypt all `.mp4` including the ones appearing in the `EXT-X-MAP` (i.e. the `init` files) using the `AES-128` keys.

**What actually happened?**

Instead of decrypting all the files including the `init` files that appear in the `EXT-X-MAP` (as the RFC stats), the player treats
the  `init` file as if they are non-encrypted and only tries to decrypt the rest of the `.mp4` files which lead to error.

**Comment by avelad** [comment]
@Chokoabigail  Can you share a url? I'll try to resolve the problem this week. Thanks!

**Comment by avelad** [comment]
Test stream: https://d12zt1n3pd4xhr.cloudfront.net/dev/fmp4-aes-en-nif.m3u8
