### ISSUE TITLE
Why live streaming in Dash manifest takes more Memory than Streaming in HLS?

### ISSUE THREAD

**Issue by Ravi-79** [shaka-project/shaka-player#5668]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes checked, No duplicate open issues

**What version of Shaka Player are you using?**
v4.4.2

**Please ask your question**
Why live streaming in Dash manifest takes more Memory than Streaming in HLS?
I tested with Shaka demo player as well as in Basic player which is in documentation also. Is it a bug or any reason why it's happening only for Dash?
![Screenshot 2023-09-19 214103](https://github.com/shaka-project/shaka-player/assets/131441182/b79f55c1-6d9e-4ae6-8395-8bc901aeed61)

**Comment by joeyparrish** [comment]
There's no good reason that it **must** be so.  We'll consider it a performance defect.

**Comment by Akash4231** [comment]
Hi @Ravi-79 
couple of questions:
1. Which browser did you test shaka player on?
2. How are you measuring the memory?

**Comment by Ravi-79** [comment]
Hi @Akash4231 , I tested on Edge as well as Chrome.
You can use the Task manager from browser to test the memory.
![image](https://github.com/shaka-project/shaka-player/assets/131441182/88ed2e42-4261-4af5-a629-be2869d931b6)

**Comment by Akash4231** [comment]
Hi @Ravi-79 
I tested Shaka on Samsung TV 2023 (Tizen)
& there is no much memory increase observed in DASH from HLS.

At peak:
for HLS: 33 MB
for DASH: 34.3 MB

Maybe you are using quite different manifests with different songs & DASH one being of higher quality?
Can you pls check if we are comparing apples to apples.

**Comment by Ravi-79** [comment]
Hi @Akash4231 , Are you using the live stream or VOD? Because it is only happening on Live only.
I was using same manifest created in Azure media Services with the available streaming format options of HLS, DASH and Smooth Streaming.
