### ISSUE TITLE
Restricting resolutions

### ISSUE THREAD

**Issue by psp95** [shaka-project/shaka-player#5670]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.4.2

**Please ask your question**
I don't know if I'm not capable, but I need to block the quality of a mpd link at 720p, mpd link goes up to 1080p, but I'm interested in 720p, but I can't do it in any of the ways, this is my code in html

```js
async function init() { 
const video = document.getElementById('video'); 
const ui = video['ui']; 

const controls = ui.getControls(); 
const player = controls.getPlayer(); 
player.configure({
  drm: {
    clearKeys: {
      // 'key-id-in-hex': 'key-in-hex',
      'KID': 'KEY'
    }
  }
});
//player.configure({drm:{servers:{'com.widevine.alpha':'xxxx'}}}); 
window.player = player; 
window.ui = ui; 
player.addEventListener('error', onPlayerErrorEvent); 
controls.addEventListener('error', onUIErrorEvent); 
try{await player.load('URLMPD'); 
console.log('The video has now been loaded!');} catch (error) {onPlayerError(error);}} 
function onPlayerErrorEvent(errorEvent) {onPlayerError(event.detail);} 
function onPlayerError(error) {console.error('Error code', error.code, 'object', error);} 
function onUIErrorEvent(errorEvent) {onPlayerError(event.detail);} 
function initFailed(errorEvent) {console.error('Unable to load the UI library!');} 
document.addEventListener('shaka-ui-loaded', init); 
document.addEventListener('shaka-ui-load-failed', initFailed); 
    player.configure({
  	abr: {
		restrictions: {
  			maxWidth: 1280,
                        maxHeight: 720
  		}
  	}
  });
```

**Comment by theodab** [comment]
Restrictions set via `abr.restrictions` are "soft" restrictions (see the [documentation on configuration](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.PlayerConfiguration)); the track still shows up, but it shouldn't be switched to automatically. You could set a "hard" restriction via `restrictions` to make it not show up at all.
E.g.:
```js
player.configure({ restrictions: {maxWidth: 1280, maxHeight: 720} });
```
