### ISSUE TITLE
How do i add a custom button to the top left corner of shaka player ui 

### ISSUE THREAD

**Issue by dextermapalya** [shaka-project/shaka-player#5680]
Hi,
I followed directions provded at this link and was able to sucessfully add a custom button to shaka ui controls
My question is how do I add the button outside of the controls at the top left corner of player screen or for that matter any other location on the screen ?

Thanks and look forward to a response
Dexter
https://github.com/shaka-project/shaka-player/issues/3177

**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**What version of Shaka Player are you using?**

**Please ask your question**

**Comment by joeyparrish** [comment]
You can use CSS to position your custom buttons.
