### ISSUE TITLE
Spec interpretation clarification requested re currentTime during seek to start of live stream on some Samsung Tizen models

### ISSUE THREAD

**Issue by dhmmNagra** [shaka-project/shaka-player#5682]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
4.3.8

**Please ask your question**
We have observed an issue on certain Samsung Tizen TVs where playback of a Live stream suffers from a double seek ahead of initial playback.
This can manifest itself in a short seek backwards i.e. an unpleasant visual jump after an initial freeze frame.

This has been traced to be a consequence of failure of the Samsung middleware to give anything other than `0` for the `currentTime` during the seek to the `startTime`.  See below for details.

Is it possible for the Shaka Player community to offer a clarifying position on the interpretation of the spec?  Please clarify Shaka Player's dependency on `currentTime` in particular state of the video tag is based on which exact spec/section.

Is Shaka Player expecting the `currentTime` to be the last one set *even if* the video element state is `HAVE_METADATA` (`1`) or `HAVE_CURRENT_DATA` (`2`)?

> This is in reference to the spec links
> - [`currentTime`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime)
>   >  _If the media is not yet playing, the value of currentTime indicates the time position within the media at which playback will begin once the play() method is called._
> - [`readyState`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/readyState)
> - [`play`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play)

## Detailed explanation

Consider an example of live DASH where we have audio and video segments two seconds in duration. The segments have the start-times of 09:59:58, 10:00:00, 10:00:02 etc (the timestamps include dates too, but let’s just use the times for simplicity).

### How it should work:

1. Shaka player reads the manifest. After applying some logic including the presentation delay, it establishes that playback should start with the presentation time of 10:00:00.
    * Shaka player will set the `currentTime` on the video element to 10:00:00, but not yet. It will wait until the `readyState` of the video element is at least 1 (after the `loadedmetadata` event)

1. Shaka player will set the playback rate to 0 while it is buffering content

1. Shaka player will acquire the initialisation segments for audio and video, and append them to the media buffers. At this point the video element emits the `loadedmetadata` event, so shaka player sets the `currentTime` to 10:00:00.
    * From this point on, shaka player will periodically poll the `currentTime` to ensure it’s not behind the earliest buffered content

1. The default behaviour of shaka player is to start acquiring segments 2 seconds before the presentation time in order to avoid issues caused by the segment times being misaligned from the manifest. It will therefore start acquiring segments from those timestamped 09:59:58.

1. When shaka player has buffered at least 2 seconds beyond the presentation time (i.e. 10:00:02), it will set the playback rate to 1.

1. Playback starts
 

### What we see:

* Steps 1-5 are as above
* From step 3, shaka player is periodically reading the `currentTime` and the video element is erroneously returning the value 0
* Due to a combination of conditions, shaka player doesn’t try to correct this false gap until the playback rate is set to 1 in step 5.
* After step 5, the erroneous `currentTime` value results in shaka player’s gap jumping logic to setting the `currentTime` to the earliest time for which audio and video segments have been buffered (i.e. 09:59:58)

**Comment by dhmmNagra** [comment]
@Wayne-Morgan FYI

**Comment by avelad** [comment]
@dhmmNagra In the latest versions we removed the playback rate change for the buffering control. Can you try it again with 4.6.X? Thank you!
