### ISSUE TITLE
Need a better way to detect whether mux.js has finished transcoding or not

### ISSUE THREAD

**Issue by neerajgulati-airtel** [shaka-project/shaka-player#5684]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not related to Fairplay

**What version of Shaka Player are you using?**
4.4.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
MacOs, chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Using for web

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

https://github.com/shaka-project/shaka-player/commit/260e3f9f90ae47866351af6462b2ae86b7ff964a added error reporting until muxjs fixes the issue on its side as mentioned in https://github.com/shaka-project/shaka-player/issues/1449

It was found that the error reporting so done is  hampering playback of files that are working fine otherwise when we comment the code in https://github.com/shaka-project/shaka-player/commit/260e3f9f90ae47866351af6462b2ae86b7ff964a . 

Run the urls sent in mail using standard demo available on production

For 1st url, you will find the playback hangs somehere between 18-19 mins
For 2nd url, you will find playback hanging right at the end 4-5secs before end of content

But if we comment the code present in the fix, then the playback goes on smoothly. Request you to come up for a more improved method of error detection so that playback of ok content doesn't get hampered
Steps for verifying playback runs ok after commenting

1) Ran shaka custom demo on local 
Commented code added in 
2) https://github.com/shaka-project/shaka-player/commit/260e3f9f90ae47866351af6462b2ae86b7ff964a

**What did you expect to happen?**
Playback to run seamlessly

**What actually happened?**
Playback failed

https://github.com/shaka-project/shaka-player/commit/260e3f9f90ae47866351af6462b2ae86b7ff964a added error reporting until muxjs fixes the issue on its side as mentioned in https://github.com/shaka-project/shaka-player/issues/1449

It was found that the error reporting so done is  hampering playback of files that are working fine otherwise when we comment the code in https://github.com/shaka-project/shaka-player/commit/260e3f9f90ae47866351af6462b2ae86b7ff964a . 

Run the urls sent in mail using standard demo available on production

For 1st url, you will find the playback hangs somehere between 18-19 mins
For 2nd url, you will find playback hanging right at the end 4-5secs before end of content

But if we comment the code present in the fix, then the playback goes on smoothly. Request you to come up for a more improved method of error detection so that playback of ok content doesn't get hampered
Steps for verifying playback runs ok after commenting

1) Ran shaka custom demo on local 
Commented code added in 
2) https://github.com/shaka-project/shaka-player/commit/260e3f9f90ae47866351af6462b2ae86b7ff964a

<img width="737" alt="Screenshot 2023-09-26 at 9 59 51 PM" src="https://github.com/shaka-project/shaka-player/assets/120081455/6d9f1f15-6bed-4c7e-8202-54d4e8b30e58">

**Comment by joeyparrish** [comment]
Please try the latest code in `main` or at https://nightly-dot-shaka-player-demo.appspot.com/, where we no longer depend on mux.js for transmuxing.  If it's working there, this will be solved in the upcoming v4.5 release.

**Comment by neerajgulati-airtel** [comment]
Thanks @joeyparrish for prompt reply but I am still getting a transmuxing error on nightly build.

**Comment by joeyparrish** [comment]
May I share your content URLs with @avelad, who is a trusted maintainer outside of Google?  (We will soon be changing the issue template to update to a sharing address that is explicitly accessible by all maintainers.)

**Comment by neerajgulati-airtel** [comment]
Sure

**Comment by avelad** [comment]
@joeyparrish please share me the stream! Thanks!

**Comment by joeyparrish** [comment]
@avelad, send me a chat if you haven't received it by email

**Comment by avelad** [comment]
@joeyparrish I got it, it was in the spam folder, sorry...

**Comment by avelad** [comment]
@neerajgulati-airtel I fixed the issue with the second URL in https://github.com/shaka-project/shaka-player/pull/5686
I don't have access to the first URL, the url resturns a 403.

**Comment by neerajgulati-airtel** [comment]
I have just now sent a mail with new urls. What's the expected live date for v4.5

**Comment by avelad** [comment]
@neerajgulati-airtel I have tested both streams at 10x from start to finish with the changes of the PR and the error was fixed for both URLs :) .

**Comment by neerajgulati-airtel** [comment]
Any expected date when v4.5 will be made live and can you update nightly url to reflect the fixed changes so that I can also check it once

**Comment by avelad** [comment]
We want to include https://github.com/shaka-project/shaka-player/pull/5470 in 4.5, once it has been merged we should be ready to release a 4.5. I hope 4.5 occurs in 2023 Q4.

I ran the nightly demo job, you should be able to see the changes in about 15 minutes.
