### ISSUE TITLE
How to switch between Document Picture-In-Picture and Picture-In-Picture mode?

### ISSUE THREAD

**Issue by Ravi-79** [shaka-project/shaka-player#5689]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I checked. There is nothing

**What version of Shaka Player are you using?**
v4.4.2

**Please ask your question**
After the latest update the browsers are using the Document Picture-In-Picture. Is there any way to switch back the old Picture-In-Picture mode?

**Comment by avelad** [comment]
Currently it’s not possible

**Comment by Ravi-79** [comment]
We are facing some accessibility issues inside the Document Picture-In-Picture window. I thought it would be better if we can switch between these options.

Having the controls inside the pip-window is very useful, but the focus-visible is not set on those controls. So, the controls are hard to access via keyboard due to the focus is not visible.

**Comment by avelad** [comment]
@beaufortfrancois is it possible resolve this issue?

**Comment by beaufortfrancois** [comment]
> Having the controls inside the pip-window is very useful, but the focus-visible is not set on those controls. So, the controls are hard to access via keyboard due to the focus is not visible.

@Ravi-79 I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=1487494 so that the Chrome team can investigate this issue. Can you share which platform you use (Windows, macOS, ChromeOS, or Linux) and a screen record maybe so that we can see the difference you experience between PiP Video and Document PiP?

**Comment by Ravi-79** [comment]
Hi @beaufortfrancois , I am using the Windows OS and tested in Shaka demo player.
Player URL:
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8;panel=HOME;build=uncompiled

Video Recording
https://github.com/shaka-project/shaka-player/assets/131441182/f90d43d8-8419-4f9e-a256-207fac09c1c7

**Comment by fkoemep** [comment]
There should be a straightforward setting that allows devs to choose the behaviour of the PiP button.

I for one do not want to use PiP in Document mode, right now I have no choice but to create a custom button...

**Comment by Ravi-79** [comment]
Hi @beaufortfrancois , @avelad ,  is there any way of using the new document picture in picture inside an iframe?
I am getting this error
**Error code: 0 object DOMException: Failed to execute 'requestWindow' on 'DocumentPictureInPicture': Opening a PiP window is only allowed from a top-level browsing context**

**Comment by beaufortfrancois** [comment]
> Hi @beaufortfrancois , @avelad , is there any way of using the new document picture in picture inside an iframe? I am getting this error **Error code: 0 object DOMException: Failed to execute 'requestWindow' on 'DocumentPictureInPicture': Opening a PiP window is only allowed from a top-level browsing context**

None. It is not possible **yet** to open a PiP window from an iframe. You can follow along at https://github.com/WICG/document-picture-in-picture/issues/97
