### ISSUE TITLE
Switching resolutions on a live DASH stream causes issues

### ISSUE THREAD

**Issue by Tsuruoka-569** [shaka-project/shaka-player#5693]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

n/a

**What version of Shaka Player are you using?**
`v4.4.2-uncompiled`

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
The demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Windows10 and Chrome 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
No asset

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Play a live streamed DASH content (with multiple resolutions, for example, 480p/720p/1080p).
Swtich the resolution from auto to 1080p.

**What did you expect to happen?**
Smooth transission between the resolutions.

**What actually happened?**

The playback is stopped, or paused for a long time and then resume.
The following error messages appear. 
>Possible encoding problem detected! Unexpected buffered range for reference.

Switching between resolutions sometimes completely stops the playback.

This seems to be a new issue since this did not happen on v4.3.12.

**Comment by Tsuruoka-569** [comment]
Same issue happens on Mac (big sur) and Chrome as well.

**Comment by avelad** [comment]
Please provide a URL of the stream, without this we can solve this problem. Thank you!

**Comment by Tsuruoka-569** [comment]
This issue occurs on this content as well as our own live content : https://shaka-player-demo.appspot.com/demo/#audiolang=ja;textlang=ja;uilang=ja;asset=https://storage.googleapis.com/shaka-live-assets/player-source.mpd;panel=ALL_CONTENT;panelData=DASH,LIVE;build=uncompiled

Thanks!

**Comment by avelad** [comment]
That stream is broken because it is not updated even if it is live, wouldn't you have a better example?

**Comment by Tsuruoka-569** [comment]
After investigation, this seems to be an encoder-side issue. My apologies.. Thanks!
