### ISSUE TITLE
mux.js in debug mode is not working

### ISSUE THREAD

**Issue by siarheipashkevich** [shaka-project/shaka-player#5697]
Regarding this PR I've found that this implementation doesn't work for `debug`.

https://github.com/shaka-project/shaka-player/pull/2683

Only `window.muxjs = muxjs;` works correctly for both modes.

fyi @NoChance777

**Comment by avelad** [comment]
We are removed mux.js in the main branch. And the next 4.5 doesn't include mux.js. So we are not going to fix this error. I'm sorry

**Comment by siarheipashkevich** [comment]
@avelad you will use another transmuxer?

**Comment by avelad** [comment]
Yes a internal transmuxer.
