### ISSUE TITLE
On player loads multiple video segments are getting cancelled

### ISSUE THREAD

**Issue by gatoenano** [shaka-project/shaka-player#5698]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

n/a

**What version of Shaka Player are you using?**

4.4.2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
no

**If custom app, can you reproduce the issue using our demo app?**
custom

**What browser and OS are you using?**
OS: windows and mac. Browser: firefox, chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

We are using the default configuration except for few parameters in streaming: 
`      streaming: {
        bufferBehind: 480,
        bufferingGoal: 480,
        retryParameters: {
          timeout: 0,
        },
      }`

**What did you do?**

playback a content which has multiple text segment

**What did you expect to happen?**
I expected the chunks to be loaded accordingly instead of getting several chunks cancelled.

**What actually happened?**
The first few chunks always get cancelled. After that, starts to load the chunks properly.
It started to happen after upgrading to the latest version of Shaka Player (4.4.2).

![image](https://github.com/shaka-project/shaka-player/assets/2183987/6deb7093-979e-4a82-a820-11bf827205bf)

**Comment by avelad** [comment]
Provide the manifest URL, without it we will not be able to help you. Thanks!

**Comment by gatoenano** [comment]
Hi @avelad! Thanks for answering me. How can I send you the URL privately?

**Comment by WINOFFRG** [comment]
@gatoenano You can share the resource here shaka-player-issues@google.com however only certain people have access to it, not all contributors

**Comment by avelad** [comment]
Please share a stream to shaka-player-maintainers@googlegroups.com so we can investigate what is happening. Thank you!
