### ISSUE TITLE
Error 6002 observed on Chrome Browser (Mobile & Web) on September 26th from 00:00 Hours to 23:59 Hours.

### ISSUE THREAD

**Issue by jasujakaran** [shaka-project/shaka-player#5700]
Hello,

One of my client observed the below error on September 26th from 00:00 Hours to 23:59 Hours on Shaka Player.

FAILED_TO_CREATE_CDM_6002_Fatalerror

Could you plesae confirm on -

1. Possible causes behind this error.
2. Was there any known issues going with Shaka Player on Septmeber 26th?
3. What could be done to prevent these types of errors?

Please Help

Karan Jasuja

**Comment by joeyparrish** [comment]
"Failed to create CDM" for 24 hours may indicate an issue that Widevine or Chrome was experiencing.  I don't know anything about that, but you can contact Widevine to ask.  https://widevine.com/
