### ISSUE TITLE
Unable to play videos on Tizen tv error: 3016

### ISSUE THREAD

**Issue by GolluAjay** [shaka-project/shaka-player#5701]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
2.5.7

**Please ask your question**

I followed the official sample provided by Samsung Forums at https://github.com/SamsungDForum/SampleWebApps-PlayerHTMLShaka. Can anyone help me resolve the issue? Thank you in advance.

![Screenshot from 2023-09-30 11-07-23](https://github.com/shaka-project/shaka-player/assets/72682071/3aaa33f8-b2ec-44d8-889b-e20f4be6c5f9)

**Comment by arturparkhisenko** [comment]
@GolluAjay please provide the manifest URL you're trying to play?

**Comment by GolluAjay** [comment]
@arturparkhisenko  please check with this
URL:https://1410669422.rsc.cdn77.org/Ac9Eqa_Bk_iAyreTTXgpFw==,1696932866/649565da9779a2001b538f4f/videos/1b8b649e-9e76-4612-8e00-968d6901a248/master.m3u8

**Comment by avelad** [comment]
Hi @GolluAjay, I see you are using an unmaintained version https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md, please use a more modern version. I have tested on the main branch and your content works without problems.

**Comment by GolluAjay** [comment]
Thank you
