### ISSUE TITLE
Immediate Configuration of bufferingGoal and rebufferingGoal and Event Triggering on Buffer Level Threshold

### ISSUE THREAD

**Issue by cenkutsal** [shaka-project/shaka-player#5720]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
v4.4.2-main-7-g96ae7f2fe

**Please ask your question**
How can I configure the bufferingGoal and rebufferingGoal immediately upon video playback initiation? What is the recommended procedure?

Is there a specific event triggered when the buffer size attains a particular level?

Thanks in advance.

**Comment by subhanahmed047** [comment]
you can look at Shaka's Network and Buffering Configuration [here](https://shaka-player-demo.appspot.com/docs/api/tutorial-network-and-buffering-config.html). 

To determine how much a video is buffered, you can look at the [HTMLMediaElement.buffered](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/buffered) property.

**Comment by cenkutsal** [comment]
Thank you for your quick response  @subhanahmed047.These docs are helpful. But not quite what I'm looking for. Let me try to elaborate on my situation here.

In my SmartTV application, initiating a forward skip or rewind causes the video to pause and display thumbnails, akin to the functionality observed in Netflix. 

![image](https://github.com/shaka-project/shaka-player/assets/72452399/c4684ac6-02c9-439d-8a36-84572b3416b9)

During this operation, how can I ensure that the Shaka Player does not engage in any data transfer or buffering? What is the correct approach to achieve this?

**Comment by subhanahmed047** [comment]
From my experience, you can pause the video by calling the pause function and then resume the video at the time associated with the selected thumbnail.

**Comment by cenkutsal** [comment]
Even if I pause, the video keeps buffering and data transfer continues. I am looking for a best practice or an example use. (If possible.)

**Comment by avelad** [comment]
> How can I configure the bufferingGoal and rebufferingGoal immediately upon video playback initiation? What is the recommended procedure?

The bufferingGoal parameter can only be set before playback.
The rebufferingGoal parameter can be set at any time.

> Is there a specific event triggered when the buffer size attains a particular level?

There is no event for that.
