### ISSUE TITLE
Player hangs for Multi period dash

### ISSUE THREAD

**Issue by neerajgulati-airtel** [shaka-project/shaka-player#5723]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**
4.4.2: Does not work
2.5.3: Works
Also checked on nightly, it fails on nightly too

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
MacOS version: 13.5.2 (22G91)
Chip: Apple M1 Pro
Chrome Version: 117.0.5938.132

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

Sent in mail

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

In mail

**What did you do?**

Provided the manifest and license urls. Video hangs at end of first period

**What did you expect to happen?**
video to play smoothly

**What actually happened?**
Multiperiod content is not working on shaka latest verion. I am only able to run such content on very old version ie 2.5.3.
The player hangs after completion of first period.
<img width="1506" alt="image" src="https://github.com/shaka-project/shaka-player/assets/120081455/c5266d2a-9d47-4b08-b9aa-b584dc235701">

**Comment by avelad** [comment]
@neerajgulati-airtel, your manifest returns a 403

**Comment by neerajgulati-airtel** [comment]
Have sent new ones just now

**Comment by avelad** [comment]
I'm getting the same error with the new stream (403), is it geoblocked?

**Comment by neerajgulati-airtel** [comment]
Yes
