### ISSUE TITLE
time_and_duration documentation

### ISSUE THREAD

**Issue by fkoemep** [shaka-project/shaka-player#5733]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.5.0

**Please ask your question**
Today I was developing a custom button that calls the goToLive() function, but just found out that the ui's 'time_and_duration' button (which by the way just found out it's a button) does this natively. 

This is not mentioned at any point in the tutorial (https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html) so I think it would be a good idea to mention that feature.

I also wanted to suggest adding buttons that seeks a user-defined amount of seconds forward and backwards, this is very useful for live videos and it's implemented in many live video players.

**Comment by avelad** [comment]
I don't know if you're wrong, because the goToLive method is not used anywhere in the UI. Is your question correct?

**Comment by fkoemep** [comment]
> I don't know if you're wrong, because the goToLive method is not used anywhere in the UI. Is your question correct?

So if it's not calling the goToLive method, what method does this button call? It is not mentioned anywhere in the documentation
