### ISSUE TITLE
Trying to play mpd file but player is trying to download full files before starting playback

### ISSUE THREAD

**Issue by abhidev54** [shaka-project/shaka-player#5735]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
I have my own app and I am using s3/cloudfront to serve mpd/related mp4 files.

**If custom app, can you reproduce the issue using our demo app?**
No

**What browser and OS are you using?**
Unix

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
 drm: {
                    servers: {
                        'com.widevine.alpha': WIDEVINE_URL
                    }
                }

**What did you do?**
I am trying to play normally but in network player try to download full files untilmately getting timedout. It should be play normally once small chunk lets say 5 seconds is ready to play.

**What did you expect to happen?**
 It should be play normally once small chunk lets say 5 seconds is ready to play. Also it should not timeout while downloading related mp4 files, no matter what timeout setting i do, it is getting timeout. so Main problem is why it tried to download full, is there any config to force it to stop downloading full files? I tried streamingGoals: 2 but that didn't helped too

**What actually happened?**
I am trying to play normally but in network tab player try to download full files and ultimately getting timed out because those are large files like 400 MB or 1 GB. It should play normally once small chunk lets say 5 seconds is ready to play.
so Main problem is why it tried to download full file, is there any config to force it to stop downloading full files?

Also Why Shaka player not sending Range header in the request headers when downloading mp4 files of mpd file, resulting into performance degrade, is there a way to force Shaka player to send Request header.
In Shaka player, i don't see 206 status code instead i see 200 status code while downloading mp4 files.
Please suggest if there is a way to force Shaka player to use Range headers.

below is my mpd file structure:

`<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" type="static" minBufferTime="PT30S" profiles="urn:mpeg:dash:profile:isoff-main:2011" mediaPresentationDuration="PT1H11M45.134S">
  <Period start="PT0S" duration="PT1H11M45.134S" id="1">
    <AdaptationSet xmlns:cenc="urn:mpeg:cenc:2013" mimeType="video/mp4" frameRate="24000/1001" segmentAlignment="true" subsegmentAlignment="true" startWithSAP="1" subsegmentStartsWithSAP="1" bitstreamSwitching="false">
      <ContentProtection cenc:default_KID="xxxx" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh>xxxxx</cenc:pssh>
      </ContentProtection>
      <Representation id="1" width="1920" height="1080" bandwidth="10000000" codecs="avc1.640029">
        <BaseURL>GOT_DRM_NORMALIZED.mp4</BaseURL>
        <SegmentBase indexRange="905-26756">
          <Initialization range="0-904"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
    <AdaptationSet xmlns:cenc="urn:mpeg:cenc:2013" mimeType="audio/mp4" lang="und" segmentAlignment="0">
      <ContentProtection cenc:default_KID="7269074e-e6b8-47b4-a5f7-617d092ec1b7" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh>xxxxx</cenc:pssh>
      </ContentProtection>
      <Representation id="2" bandwidth="448000" audioSamplingRate="48000" codecs="mp4a.40.2">
        <BaseURL>GOT_DRM_NORMALIZED_5_1_en_1.mp4</BaseURL>
        <SegmentBase indexRange="825-26676">
          <Initialization range="0-824"/>
        </SegmentBase>
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="6"/>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>`

**Comment by avelad** [comment]
Please share a stream to [shaka-player-maintainers@googlegroups.com](mailto:shaka-player-maintainers@googlegroups.com) so we can investigate what is happening. Thank you!
