### ISSUE TITLE
Offline storage : why are .dash chunks not downloaded in parallel ?

### ISSUE THREAD

**Issue by loicraux** [shaka-project/shaka-player#5737]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

version 4.4.2

**Please ask your question**

When downloading a `.mpd` asset for offline playback using shaka player's `storage` API, `.dash` chunks are downloaded, but they are downloaded one after the other, in other words there is no parallelisation of chunk downloads, and the download is quite slow consequently imho :

![image](https://github.com/shaka-project/shaka-player/assets/3329077/fc141d6d-5f95-4c80-969b-34696689b2d0)

With some other .mpd manifests (e.g. https://bitmovin-a.akamaihd.net/content/playhouse-vr/mpds/105560.mpd), `.m4s` chunks (also DASH segments, right ?) for example are downloaded in parallel (5 downloads in parallel in this case, which corresponds to the default value of `numberOfParallelDownloads`) and the download is therefore much faster...

![image](https://github.com/shaka-project/shaka-player/assets/3329077/182de545-0a7b-4283-92dc-3cd205cf4571)

I've searched the Shaka Player documentation and tickets without success to find an explanation for this...

(I haven't set any value for `numberOfParallelDownloads`, so I should also get 5 downloads in parallel...)

- Is it due to the MPEG-DASH protocol itself?
- Or is it adjustable via shaka player settings? offline storage?
- Or is it due to the metadatas returned by our CDN (response headers?)?

Thanks in advance for your help!

**Comment by avelad** [comment]
This looks like a bug, please open a bug issue and fill out all fields. Thanks!

**Comment by loicraux** [comment]
Related bug opened : #5755

**Comment by avelad** [comment]
Thanks @loicraux !
