### ISSUE TITLE
Release 4.4.2 freezes on some live streams

### ISSUE THREAD

**Issue by adgllorente** [shaka-project/shaka-player#5738]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

Latest

**Please ask your question**

After upgrading from 4.3.2 to 4.4.2 our QA team has seen that shaka-player suddenly freezes and stays in an infinite loading on live streams.

We have seen this assertion message in the console `Assertion error: Request without URIs!`, it is produced in the `network_engine.js` file but after a few days debugging we have not found anything more conclusive.

It happens with any of our live channels, mostly in the first 5 playback minutes and we haven't seen this behavior in shaka-player 4.3.2.

Player does not emit an error, it just shows that assertion message and shows an spinner and keeps requesting Manifests.

We have also tried with stall configuration but it does not fix the situation.

Do you have any idea about what could be happening? Could you think in any change between 4.3.2 and 4.4.2 that could produce this situation? Could you please give us more information to continue our debugging?

Thanks.

**Comment by avelad** [comment]
Can you test with 4.4.3? Thanks!

**Comment by adgllorente** [comment]
We have just tested with 4.5.0 and we have the same issues.

**Comment by avelad** [comment]
Well it seems like a bug, please open a bug type issue with all the fields filled out. Thanks!
