### ISSUE TITLE
Plugin tutorial is outdated, missing various text and manifest parsers

### ISSUE THREAD

**Issue by absidue** [shaka-project/shaka-player#5741]
Both the latest release and nightly plugin tutorial docs are missing various text (LRC, SBV, SRT, SSA) and manifest (MSS) parsers. I'm guessing the page just hasn't been updated in a while.

Latest Release docs: https://shaka-player-demo.appspot.com/docs/api/tutorial-plugins.html
Nightly: https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-plugins.html

I'm sorry that I removed the template, it didn't seem relevant to this docs issue.

**Comment by shivam200446** [comment]
hey, I want to work on it. assign me!

**Comment by joeyparrish** [comment]
@shivam200446, thanks!
