### ISSUE TITLE
The first video chunk fails 1-3 times and is processed successfully on some video streams

### ISSUE THREAD

**Issue by siarheipashkevich** [shaka-project/shaka-player#5754]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

this problem not related the FairPlay

**What version of Shaka Player are you using?**

4.5.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
demo app and custom app also

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
iOS 16, 17. Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://d28xag2clsabew.cloudfront.net/8pod/test/test_4_60fps/hls/FPS_test_1080p60_L4.2.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default configuration except:
`streaming.useNativeHlsOnSafari: false`
also we try use only default configuration

**What did you do?**

want to play hls stream in mobile safari without any declined requests for chunks (for avoiding additional latency)

**What did you expect to happen?**
hls stream in mobile safari starts without any declined requests of chunks

**What actually happened?**

![MicrosoftTeams-image](https://github.com/shaka-project/shaka-player/assets/7753600/919ede51-6b00-485a-8623-c79642d18093)

Full description of the problem:
The first video chunk fails 1-3 times and is processed successfully on some video streams. 

The flag `useNativeHlsOnSafari: false` fixes the issue on desktop Safari but does not affect the mobile one. 

The issue is captured with the test video from Apple documentation and with videos after Amazon SimpleConvert. : https://developer.apple.com/documentation/http-live-streaming/deploying-a-basic-http-live-streaming-hls-stream

https://d28xag2clsabew.cloudfront.net/8pod/test/test_4_60fps/hls/FPS_test_1080p60_L4.2.m3u8

**Comment by siarheipashkevich** [comment]
@avelad are there any commits that could fix this?

**Comment by avelad** [comment]
Yes, we use ManagedMediaSource for iOS 17.1+

**Comment by siarheipashkevich** [comment]
@avelad for checking my issue on `main` branch I should clone repository, switch to `main` branch and compile a new build?

**Comment by avelad** [comment]
You can use the nightly demo: https://nightly-dot-shaka-player-demo.appspot.com/demo/

**Comment by siarheipashkevich** [comment]
@shaka-bot reopen

**Comment by siarheipashkevich** [comment]
It's still a valid issue on iOS 17.1+

**Comment by avelad** [comment]
I tested in 4.7.3 and now it works fine!
