### ISSUE TITLE
why shaka player not sending Range header in the request headers when downloading mp4 files of mpd file

### ISSUE THREAD

**Issue by abhidev54** [shaka-project/shaka-player#5758]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.5

**Please ask your question**
Why Shaka player not sending Range header in the request headers when downloading mp4 files of mpd file, resulting into performance degrade, is there a way to force Shaka player to send Request header.
In Shaka player, i don't see 206 status code instead i see 200 status code while downloading mp4 files.
Please suggest if there is a way to force Shaka player to use Range headers.

**Comment by joeyparrish** [comment]
It should send range headers.  Please open a new issue with the "bug" template and send us relevant details to reproduce your issue.  It may be a bug in the player or something wrong with your content.  Thanks!

**Comment by abhidev54** [comment]
Hi @joeyparrish ,

I already have one issue with "bug" template https://github.com/shaka-project/shaka-player/issues/5735 , still waiting for reply.
can you please take a look, see if you came across such issue earlier?
