### ISSUE TITLE
Instagram in-app browser and fairplay DRM content

### ISSUE THREAD

**Issue by saradha-kannan** [shaka-project/shaka-player#5759]
Hi, should fairplay DRM content (hls stream) be supported on instagram in-app browser on iOS device?  How does Shaka player determine and playback DRM streams on insta/FB app-browser?

**Comment by avelad** [comment]
You can check it by accessing the following link: https://nightly-dot-shaka-player-demo.appspot.com/support.html

If the fairplay part is different from null it is supported
