### ISSUE TITLE
Release 4.4.2 freezes on some live streams

### ISSUE THREAD

**Issue by adgllorente** [shaka-project/shaka-player#5760]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

Latest

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**

Chrome browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A

**What are the manifest and license server URIs?**

I can provide Manifest and License if needed but we haven't found steps to reproduce the situation. It may happen during the first 5-10 minutes or it may work fine.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default configuration from demo website.

**What did you do?**

1. Launch playback
2. Wait for 5-10 minutes

**What did you expect to happen?**

Playback should continue.

**What actually happened?**

Player shows an infinite loading spinner and playback does not continue.

Console reports an error log `Assertion error: Request without URIs!` because `network_engine.js > request()` method is called without URIs.

Player does not emit any proper error code and it continues downloading Manifest.

Stall configuration does not fix it either.

Release 4.3.2 shows a loading spinner but playback continues.

Related with #5738

**Comment by adgllorente** [comment]
We haven't reproduced this issue on 3.4.13 or 4.4.0.

It may be some change introduced between 4.4.1 and 4.4.2

**Comment by avelad** [comment]
@adgllorente Since you are investigating the issue, would you like to fix it and make a PR?

**Comment by adgllorente** [comment]
If I have a fix, I will open a PR but I would let the issue unassigned since I am not confident with finding a solution yet
