### ISSUE TITLE
Reported video time is incorrect and video ending never occurs

### ISSUE THREAD

**Issue by ivaniclixx** [shaka-project/shaka-player#5765]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Only happens in any Safari (macOs or iOs)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
iPhone 11, iPhone 14, ...

**What are the manifest and license server URIs?**
http://tenmasters.b-cdn.net/BUGSHAKASAFARI/master.m3u8
This is NOT the complete video (only the first 4 .ts files are there), as it is copyrighted by the company, but it is enough to show and reproduce the bug.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Does not matter

**What did you do?**
Load the video in any shaka player running under Safari.

**What did you expect to happen?**
Video playing with the correct timing.

**What actually happened?**
The video plays and shows the correct duration, but after a second or so, the duration shown is incorrect. Instead of 16:20 it changes to 23:16, which is incorrect. The video element has a duration of 1396 (matching the 23:16) which is incorrect. The timeline, though, seems correct, as going to the end of the scroll it approaches the time of 16 min.
Also, the video never finishes, as it just stops a few seconds before the end, and keeps buffering.

Screenshot showing the timeline and not matching time attached
![bug_shaka_crop](https://github.com/shaka-project/shaka-player/assets/16993298/a8801924-9ee4-411d-ad8b-f703d79bca4a)
.

EDIT - FORGOT TO ADD INFO:
The bug *only* happens using Shaka. Opening the m3u8 directly by the browser works perfectly. Using another web browser, no issues. Shaka + Safari = BUG happens.

**Comment by avelad** [comment]
The UI is using the duration of the video element to show the time duration, I have doubts that for vod we should not show `seekRange.end - seekRange.start`. @theodab @littlespex, what do you think?

**Comment by avelad** [comment]
Shaka does the same for all stream types, the difference is that in `src=` it returns this which is the strange thing:
```
document.getElementById('video').duration
1396.08
shakaDemoMain.player_.seekRange()
{start: 0, end: 980.92}
```

I'm going to create a PR to use seekRange in the UI.
