### ISSUE TITLE
How to build own shaka-player excluding some plugins?

### ISSUE THREAD

**Issue by siarheipashkevich** [shaka-project/shaka-player#5770]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes.

https://github.com/shaka-project/shaka-player/blob/main/docs/tutorials/plugins.md#excluding-default-plugins

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes

**What version of Shaka Player are you using?**

4.5.0

**Please ask your question**

I want to build my own instance of the shaka-player without some plugins for decreasing the bundle size.

![image](https://github.com/shaka-project/shaka-player/assets/7753600/f4a9bec6-ae72-4d43-ae92-e61cdf4486b2)

But when I ran command for build shaka-player I'm getting only some files and I can't found for example `shaka-player.compiled.js'.

Where I'm wrong?

**Comment by siarheipashkevich** [comment]
https://github.com/shaka-project/shaka-player/issues/4740

**Comment by cuyl** [comment]
You can use the name arg `--name custom`
`python3 build/build.py --name compiled +@complete -@text`

**Comment by absidue** [comment]
@siarheipashkevich The reason you are missing files, is that you are only doing a UI build, whereas the npm package contains 4 different builds (UI debug, UI release, non-UI debug, non-UI release), see all.py for more details.
https://github.com/shaka-project/shaka-player/blob/main/build/all.py#L117-L129
