### ISSUE TITLE
Support addThumbnailsTrack in SRC_EQUALS

### ISSUE THREAD

**Issue by absidue** [shaka-project/shaka-player#5778]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Since version 4.4.0 (https://github.com/shaka-project/shaka-player/pull/5502) the UI will display thumbnails when hovering over the seek bar when they are provided. Unfortunately this is currently only usable when the load mode is `MEDIA_SOURCE`, as `Player.addThumbnailsTrack()` throws `CANNOT_ADD_EXTERNAL_THUMBNAILS_TO_SRC_EQUALS` when you call it when the load mode is `SRC_EQUALS`. While that error is correct, it also makes it impossible to use the thumbnail display feature with `SRC_EQUALS`.

**Describe the solution you'd like**

A way to pass thumbnail tracks to the UI even when the load mode is `SRC_EQUALS`. As shaka-player can handle them completely fine when the load mode is `MEDIA_SOURCE`, it means that most of the necessary infrastructure already exists, it just has to be adapted for use with the load mode being `SRC_EQUALS`.

**Describe alternatives you've considered**

Building a custom seek bar component with custom thumbnail handling and registering that with the UI.

**Comment by theodab** [comment]
Sure, that'd be possible. The thumbnails feature as it works today relies on the existence of a manifest, but there's no reason we couldn't add some alternate container for storing user-added image tracks that we could use while loaded in src-equals mode.

**Comment by avelad** [comment]
I'll work on it in a few weeks.

**Comment by avelad** [comment]
I'll work on this after it's merged https://github.com/shaka-project/shaka-player/pull/5752

**Comment by avelad** [comment]
@absidue I created https://github.com/shaka-project/shaka-player/issues/5778
