### ISSUE TITLE
Thumbnails support for live stream

### ISSUE THREAD

**Issue by burugupalli** [shaka-project/shaka-player#5781]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

When the user wants to skipp on the seek range for live stream, I wanted to show all the thumb nails for the live stream and I want to scroll through those thumbnails and select appropriate thumb nail to seek.

**Describe the solution you'd like**

An API which returns all the thumbnails along with seek positions.

**Describe alternatives you've considered**

Trying to iterative through all the image streams and manually get the thumbnails.

**Additional context**

**Comment by theodab** [comment]
I believe this is technically possible without a dedicated API call, but it'd be an unreasonable amount of work for a developer. So I agree that adding a new method makes sense.
