### ISSUE TITLE
How to include custom compiled build to own project?

### ISSUE THREAD

**Issue by siarheipashkevich** [shaka-project/shaka-player#5784]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.5.0

**Please ask your question**

I've created custom build without some plugins regarding this documentation:
https://github.com/shaka-project/shaka-player/blob/main/docs/tutorials/plugins.md#excluding-default-plugins

```
docker run -v ./:/usr/src --user $(id -u):$(id -g) shaka-player-build python build/build.py --name compiled +@polyfill +@transmuxer +@networking +@hls +@dash -lib/polyfill/vttcue.js
```

Then I copy the files to my project but I'm getting an error when open in browser.
Where am I wrong?

![image](https://github.com/shaka-project/shaka-player/assets/7753600/e59c5c70-8124-4b4c-b0c3-f77097d616c5)

![image](https://github.com/shaka-project/shaka-player/assets/7753600/c9122e0e-63a5-42ea-b313-6f26efce2428)

**Comment by siarheipashkevich** [comment]
https://github.com/shaka-project/shaka-player/issues/5770

**Comment by theodab** [comment]
This isn't a problem unique to a custom build; you'll see the same error if you import from the default build.
It happens because the compiler Shaka Player uses is kind of out of date, and still does exports in the ES2015 style.
If you want to import stuff module-style, try this syntax instead:

```js
import * as shaka from './lib/shaka-player.compiled'
```

That should capture all of the ES2015-style exports into a constant called "shaka", which should allow you to use the player as normal.

**Comment by siarheipashkevich** [comment]
@theodab but in that case I'll lost d.ts suggestions and my TS will catch errors

**Comment by absidue** [comment]
@siarheipashkevich Did you add `export default shaka` to the bottom of the .d.ts file? by default shaka-player doesn't export the types.

**Comment by siarheipashkevich** [comment]
@absidue yes

![image](https://github.com/shaka-project/shaka-player/assets/7753600/3d54b458-00af-45da-9aaa-81b160492d99)
