### ISSUE TITLE
Subtitles not in sync with video when video playes

### ISSUE THREAD

**Issue by neerajgulati-airtel** [shaka-project/shaka-player#5792]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

NA

**What version of Shaka Player are you using?**

4.3.6

**Can you reproduce the issue with our latest release version?**
Not able to do on shaka custom demo as can't find any field to provide subtitles url

**Can you reproduce the issue with the latest code from `main`?**
Not able to do on shaka custom demo as can't find any field to provide subtitles url

**Are you using the demo app or your own custom app?**
own app

**If custom app, can you reproduce the issue using our demo app?**
Not able to do on shaka custom demo as can't find any field to provide subtitles url

**What browser and OS are you using?**
MacOS version: 13.5.2 (22G91)
Chip: Apple M1 Pro
Chrome Version: 117.0.5938.132

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

NA

**What did you do?**

Played the content, also providing the urls. The subtitles come approx. 2s earlier than where they are supposed to come according to srt file.

**What did you expect to happen?**
Video and subtitles to play in sync

**What actually happened?**

According to srt file the subtitles are supposed to come at exact duration as stated in the file
Ex
<img width="441" alt="image" src="https://github.com/shaka-project/shaka-player/assets/120081455/aec6b471-f525-4cd8-b8e2-404334a74433">
The subtitle is supposed to come at 00:06:13,109  but it comes at 00:06:11.

**Comment by neerajgulati-airtel** [comment]
Shared just now via mail

**Comment by avelad** [comment]
This is already fixed in 4.4 or above. See https://github.com/shaka-project/shaka-player/pull/5491
