### ISSUE TITLE
Is VTTRegion used again in v4?

### ISSUE THREAD

**Issue by cristian-atehortua** [shaka-project/shaka-player#5799]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.5.0

**Please ask your question**
Hi, Shaka's team. I'm seeing a problem with the subtitles rendering. The problem is that there is a black square surrounding the subtitles and there's no way to remove it.

I found this issue https://github.com/shaka-project/shaka-player/issues/1907. It says that this was caused because Shaka is using VTT Regions to display subtitles and there's a bug in Chrome and Firefox that doesn't allow to change styling. In that issue, it says Shaka will stop using VTTRegion to avoid that behavior.

My question is, does Shaka is using it again? There's a particular reason to do it?

Thanks in advance.

**Comment by avelad** [comment]
Actualmente no usamos VTT regions, ¿estas usando UITextDisplayer o SimpleTextDisplayer? ¿Que formato de subtitulos usas (TTML, WebVTT, etc...)?

**Comment by cristian-atehortua** [comment]
Hi @avelad. We're using SimpleTextDisplayer. The browser injects that black square I think. It is not a DOM element but a pseudo-element that doesn't have a way to be selected through CSS.

I will check if I can use UITextDisplayer.

**Comment by absidue** [comment]
@cristian-atehortua It's definitely selectable through CSS with the `::cue` pseudo-selector.

WebVTT spec: https://w3c.github.io/webvtt/#the-cue-pseudo-element
MDN page: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video#styling_the_displayed_subtitles

e.g.
```css
::cue {
    background-color: transparent;
}
```

**Comment by absidue** [comment]
If you are removing the background, please make sure that the text alone has a strong enough contrast against your video content, that it is still readable by your users. (The higher the contrast the better, hence why browsers default to white text on a black background, unless you have configured it differently in your browser or operating system).

**Comment by cristian-atehortua** [comment]
Nope @absidue it is not the background I'm referring to. That background is for the cue itself but the background Chrome is adding is for the cue-region. And that selector (::cue-region) doesn't work.

**Comment by absidue** [comment]
I'd recommend trying some of the other pseudo selectors, e.g. `::-webkit-media-text-track-container`, I know setting that `display: none` on that hides the entire native text display (I use that to replace it with a UITextDisplayer instance)

**Comment by cristian-atehortua** [comment]
`display: none` will also hide the text. I just want to remove the background keeping the text. But nevermind, I think using UITextDisplayer will be a better option for me. Thanks.

**Comment by absidue** [comment]
I wasn't saying you should hide the text, just showing you that there are more pseudo selectors available and that one definitely works.

**Comment by cristian-atehortua** [comment]
Not for removing the background. That background it's impossible to remove. That was the point of the issue I referenced in the question.

**Comment by absidue** [comment]
Have you tried all possible pseudo selectors (there are a bunch more webkit ones)?

I'm just surprised that you are seeing it, because I've not seen that region background that you are talking about before. Do you have a screenshot of the background in question?
