### ISSUE TITLE
Supporting Cobalt

### ISSUE THREAD

**Issue by kaidokert** [shaka-project/shaka-player#5804]
**Is your feature request related to a problem? Please describe.**

Cobalt ( https://cobalt.dev ) currently doesn't work with Shaka out of the box, due to a few minor missing APIs that currently throw JavaScript exceptions. 

**Describe the solution you'd like**

I have a small patch that stubs out the usage of `video.textTracks` and `document.createNodeIterator` that would disable textTracks and some XSS security guards in Shaka.

**Describe alternatives you've considered**

We could also try and add stub implementations of those web APIs in Cobalt quite easily, and we likely will. However, that wouldn't let all the deployed versions of Cobalt to run with Shaka.

**Additional context**

Preview of quick 15-minute changes here ( i would remove the lint suppressions, of course ): 
https://github.com/kaidokert/shaka-player/commit/f5167033cccded38dc27e12b863aac7d9e0b993d

**Comment by avelad** [comment]
I have reviewed the link, I agree with including the changes in lib/util/xml_utils.js, but I think the changes in lib/text/simple_text_displayer.js should be to make a new text displayer that does nothing, what do you think?

**Comment by kaidokert** [comment]
Yep, i think there was only one call site for the textDisplayer so that change would be cleaner and would throw less surprises.

**Comment by avelad** [comment]
I have created https://github.com/shaka-project/shaka-player/pull/5805 to solve the problem of `lib/util/xml_utils.js`

For the other change I am willing to review your PR if you are interested in sending it, I think the new class should be called `StubTextDisplayer` (`lib/text/stub_text_displayer.js`), then the change would only be to add a new if in https://github.com/shaka-project/shaka-player/blob/main/lib/player.js#L5441

**Comment by kaidokert** [comment]
Thanks much for such a quick response - i'll put a PR together and send it.
