### ISSUE TITLE
Is there a way to check whether polyfills have been installed?

### ISSUE THREAD

**Issue by vanyaxk** [shaka-project/shaka-player#5808]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**Please ask your question**
Is there a way to check whether polyfills have been installed instead of trying to install them every time? Some of the polyfills have relevant logs, but not all of them, and I was wondering whether there is a way to check if `installAll` or a relevant polyfill callback was run before.

**Comment by avelad** [comment]
Currently this information is not available. But we are open to reviewing PR that adds this information. Thanks!

**Comment by vanyaxk** [comment]
ok, Will try to come up with something 🙂
