### ISSUE TITLE
Question/Future request: ShakaPlayer audio and subtitle track detection (audioDescription, original, sdh)

### ISSUE THREAD

**Issue by jakubjereczek** [shaka-project/shaka-player#5810]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I did.

**Is your feature request related to a problem? Please describe.**

At the beginning, I would like to point out that I am using ShakaPlayer in Chromecast CAF.
I would like to inquire about the technical capabilities of ShakaPlayer for detecting the following audio/subtitle tracks roles in a manifest.
* **Audio description** (audio description for the visually impaired),
* Audio **Original Version**, (source audio version)
* Subtitle **Hearing impaired** (sdh: subtitling for the deaf and hard of hearing)

**Describe the solution you'd like**

To extend the audio/subtitle ShakaPlayer API in order to obtain information about the above values.

I don't know what it looks like in DASH, but in HLS everything is available in the CHARACTERISTICS attribute in the manifest.
audio description: `CHARACTERISTICS="public.accessibility.describes-video"`
hearing impaired: `CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog,public.accessibility.describes-music-and-sound"`
original language: `CHARACTERISTICS="public.original-content"`

**Describe alternatives you've considered**

No alternatives.

**Additional context**

In our application, we need to add a detailed description and specify the mentioned types above and I would like to know if it is technically possible using ShakaPlayer.

**Comment by jilles-sg** [comment]
It looks like the idea is that `shaka.extern.Track` contains the necessary information:

- "Audio description": `roles` or `audioRoles` (?) contains `caption` or `commentary` (?)
- Audio "Original Version": `primary` is true
- Subtitle "Hearing impaired": `kind` is `caption` (not `subtitle`)

**Comment by jakubjereczek** [comment]
Probably it is, sorry if my question wasn't clear. I'm using CAF that have their unusual implementation of ShakaPlayer API. To sum up i'm asking whether shaka player technically detects the above roles (HLS was just an example).

**Comment by avelad** [comment]
I created https://github.com/shaka-project/shaka-player/pull/5819 for "Subtitle "Hearing impaired""

I have not been able to find the public.original-content in the HLS spec (https://developer.apple.com/streaming/HLS-draft-pantos.pdf) so we cannot accept this change. Regarding the change of "Audio description" I would like to know @theodab's opinion

**Comment by avelad** [comment]
@littlespex do you have any opinion about that?

**Comment by avelad** [comment]
@littlespex Thanks for your response, I will do the same in the HLS implementation
