### ISSUE TITLE
Export essential modules for custom player API implementations

### ISSUE THREAD

**Issue by zangue** [shaka-project/shaka-player#5814]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

I have been looking into implementing custom player API (without having to build an adapter on top of the current one) using the Shaka libraries. However, in my investigation, I noticed that certain key components such as the Streaming/Media source/DRM engine, playhead and couple more, are not currently exported to the consumer. I believe it would be beneficial to make these components accessible to enable the aforementioned use case (or e.g. standalone use of the Streaming engine for embedded use cases).

**Describe the solution you'd like**

Export all key components needed to build a custom player API from scratch.

**Describe alternatives you've considered**

I've considered manually exporting needed component or implement a different player API from within the shaka code base. But either way I will end up with custom shaka library build which I want to avoid.

**Additional context**

A lot of components are actually already exported e.g. manifest parsers, networking engine, text related modules, utilities.

**Comment by avelad** [comment]
Is anyone interested in seeing this implemented (other than the issue reporter)? Otherwise the issue will be closed in 7 days.

**Comment by zangue** [comment]
@avelad I'm interested in this. Other topics I've kept me busy in the meantime but I will probably have capacity to do this around mid of May if that's ok.
