### ISSUE TITLE
Does shaka support srt subtitles

### ISSUE THREAD

**Issue by neerajgulati-airtel** [shaka-project/shaka-player#5818]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
shaka 4.5.0

**Please ask your question**
Does shaka support srt subtitles

**Comment by avelad** [comment]
Yes, you can see the subtitle support in https://github.com/shaka-project/shaka-player#media-container-and-subtitle-support
