### ISSUE TITLE
Shaka tends to crash while playing HLS AES 128 streams on Firefox

### ISSUE THREAD

**Issue by multiplexer2** [shaka-project/shaka-player#5824]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.5.0

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Both

**If custom app, can you reproduce the issue using our demo app?**

Yes

**What browser and OS are you using?**

Firefox, Windows + Ubuntu

**What are the manifest and license server URIs?**

Link to shaka demo asset:
https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-ts-aes-key-rotation/master.m3u8;panel=ALL_CONTENT;panelData=drm:AES128;build=uncompiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Using the config set by the demo site

**What did you do?**

Navigate to the Shaka demo site and play "Sintel (HLS, TS, AES-128 key rotation)"
Switch quickly between different Resolutions

**What did you expect to happen?**

Playback should work fine

**What actually happened?**

After some resolution switches the player crashes. (Other HLS AES streams may crash immediately.) The following error messages are written to the console:

Starting load of https://storage.googleapis.com/shaka-demo-assets/sintel-ts-aes-key-rotation/master.m3u8... [log.js:142:50](https://nightly-dot-shaka-player-demo.appspot.com/lib/debug/log.js)
Updating manifest... [log.js:142:50](https://nightly-dot-shaka-player-demo.appspot.com/lib/debug/log.js)
**Assertion failed:** mediaState.segmentIterator should exist [streaming_engine.js:2213:20](https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js)
**Assertion failed:** Should only receive a Shaka error [streaming_engine.js:1473:20](https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js)
(video:8) failed fetch and append: code=undefined [log.js:140:51](https://nightly-dot-shaka-player-demo.appspot.com/lib/debug/log.js)
**Assertion failed:** Wrong error type! [player.js:6457:18](https://nightly-dot-shaka-player-demo.appspot.com/lib/player.js)
**TypeError: iter is null**
    aes128Decrypt_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1525
    fetch_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2214
    fetchAndAppend_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1419
    update_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1177
    onUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:992
    updateTimer https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2339
    onTick https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:56
    setTimeout handler*tickAfter https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:60
    scheduleUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2345
    fetchAndAppend_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1467
    update_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1177
    onUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:992
    updateTimer https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2339
    onTick https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:56
    setTimeout handler*tickAfter https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:60
    scheduleUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2345
    fetchAndAppend_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1467
    update_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1177
    onUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:992
    updateTimer https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2339
    onTick https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:56
    setTimeout handler*tickAfter https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:60
    scheduleUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2345
    clearBuffer_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2309
    switchInternal_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:513
    switchVariant https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:364
    switchVariant_ https://nightly-dot-shaka-player-demo.appspot.com/lib/player.js:6081
    selectVariantTrack https://nightly-dot-shaka-player-demo.appspot.com/lib/player.js:4245
    onTrackSelected_ https://nightly-dot-shaka-player-demo.appspot.com/ui/resolution_selection.js:218
[main.js:1728:13](https://nightly-dot-shaka-player-demo.appspot.com/demo/main.js)
    onError_ https://nightly-dot-shaka-player-demo.appspot.com/demo/main.js:1728
    onErrorEvent_ https://nightly-dot-shaka-player-demo.appspot.com/demo/main.js:1706
    onErrorEvent https://nightly-dot-shaka-player-demo.appspot.com/demo/main.js:424
    dispatchEvent https://nightly-dot-shaka-player-demo.appspot.com/lib/util/fake_event_target.js:126
    playerProxyLocalEvent_ https://nightly-dot-shaka-player-demo.appspot.com/lib/cast/cast_proxy.js:740
    init_ https://nightly-dot-shaka-player-demo.appspot.com/lib/cast/cast_proxy.js:284
    dispatchEvent https://nightly-dot-shaka-player-demo.appspot.com/lib/util/fake_event_target.js:126
    onError_ https://nightly-dot-shaka-player-demo.appspot.com/lib/player.js:6472
    onError https://nightly-dot-shaka-player-demo.appspot.com/lib/player.js:3205
    handleStreamingError_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2407
    fetchAndAppend_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1502
    update_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1177
    onUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:992
    updateTimer https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2339
    onTick https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:56
    (Async: setTimeout handler)
    tickAfter https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:60
    scheduleUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2345
    fetchAndAppend_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1467
    update_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1177
    onUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:992
    updateTimer https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2339
    onTick https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:56
    (Async: setTimeout handler)
    tickAfter https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:60
    scheduleUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2345
    fetchAndAppend_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1467
    update_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:1177
    onUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:992
    updateTimer https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2339
    onTick https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:56
    (Async: setTimeout handler)
    tickAfter https://nightly-dot-shaka-player-demo.appspot.com/lib/util/delayed_tick.js:60
    scheduleUpdate_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2345
    clearBuffer_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:2309
    switchInternal_ https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:513
    switchVariant https://nightly-dot-shaka-player-demo.appspot.com/lib/media/streaming_engine.js:364
    switchVariant_ https://nightly-dot-shaka-player-demo.appspot.com/lib/player.js:6081
    selectVariantTrack https://nightly-dot-shaka-player-demo.appspot.com/lib/player.js:4245
    onTrackSelected_ https://nightly-dot-shaka-player-demo.appspot.com/ui/resolution_selection.js:218

​

​

**Comment by avelad** [comment]
@multiplexer2 Are you interested on send a PR to fix it? Thanks!

**Comment by multiplexer2** [comment]
@avelad I'm sorry but I won't be able to do that ...
