### ISSUE TITLE
[Paramount] Player Fails To Successfully Transition From Content To Ad Period

### ISSUE THREAD

**Issue by agajassi** [shaka-project/shaka-player#5826]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, I have and so far couldn't find any duplicate or similar issues.

**If the problem is related to FairPlay, have you read the tutorial?**

Not related to DRM

**What version of Shaka Player are you using?**

Shaka v. 4.5.0

**Can you reproduce the issue with our latest release version?**
Yes with Shaka v. 4.5.0, but not with 4.4.x versions.

**Can you reproduce the issue with the latest code from `main`?**
I tried with `main` branch, but I couldn't even get the playback going. Maybe because there is some other incomplete dev work in the main branch. 

**Are you using the demo app or your own custom app?**
Using custom but also reproducible on demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
MacOS/Chrome Version 118.0.5993.117

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

Content is DRM protected. I can provide it via email.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

I am using default configuration. The only config I am setting is drm server.
```
 const config = player.getConfiguration();
 config.drm.servers['com.widevine.alpha'] = "license_acquisition_url"
 player.configure(config);
 ```

**What did you do?**

1. Setup a simple test page with Shaka v4.5.0.
2. Play multi-period VOD asset with DAI midroll ads in it. 
3. Once playback starts turn on CC
`player.setTextTrackVisibility(true);`
4. Seek to the midroll ad break (or couple seconds before midroll break start time)
5. Once midroll ad starts playing, notice the errors in the console

**NOTE:** Most of the time playback will freeze during ads, or play all the ads and freeze immediately after it transitions back to the content. 

**What did you expect to happen?**
I expect player to successfully transition from content period to the ad break period despite CC being on.  

**What actually happened?**

Playback gets stuck immediately after playing first ad in the ad break with errors in the console. This behavior does not happen with previous version of Shaka 4.4.3. Please see the screenshots included below. Based on the errors, it looks like player fails to fetch and append text segments for ad break period.

![Screen Shot 2023-10-27 at 12 49 15 PM](https://github.com/shaka-project/shaka-player/assets/12893220/4b64b475-ec8e-4552-85dd-1a1bc7edcfe7)

![Screen Shot 2023-10-27 at 12 28 23 PM](https://github.com/shaka-project/shaka-player/assets/12893220/f0d3db55-bd70-42d4-81ff-56e4f7ff4d43)

![Screen Shot 2023-10-27 at 12 28 44 PM](https://github.com/shaka-project/shaka-player/assets/12893220/3777c9a5-fdc2-4bda-90e2-ea7145a57add)

![Screen Shot 2023-10-27 at 12 29 06 PM](https://github.com/shaka-project/shaka-player/assets/12893220/9fade804-85a5-454a-b351-fdbc26f991ec)

![Screen Shot 2023-10-27 at 12 29 48 PM](https://github.com/shaka-project/shaka-player/assets/12893220/cf94265e-3b49-4ff4-b196-efc9c8be5c9c)

**Comment by littlespex** [comment]
This issue is resolved in `main` and `4.5.x` branches and will be available in `v4.5.1`.
