### ISSUE TITLE
Can we cherry pick LTS change into a 4.4.4 release

### ISSUE THREAD

**Issue by dsparacio** [shaka-project/shaka-player#5832]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.4.3 after finding regression in 4.5.0 and testing main for fix.

**Please ask your question**
Can we cherry pick this commit into a point release based on 4.4.3 (E.g. 4.4.4)
https://github.com/shaka-project/shaka-player/pull/5602/files

Reason why:
We found and filed an issue after we upgraded to 4.5 (to pick up our [fix for LTS Event](https://github.com/shaka-project/shaka-player/pull/5602/files)).  We are unable to update to this version until we PR a fix for this [issue](https://github.com/shaka-project/shaka-player/issues/5826) 

This may take a couple weeks and we are in need of this change asap. We can do the work to PR this cherry pick if you all think you could do the point release?

**Comment by avelad** [comment]
Shaka is following a semserver versioning, this change is of type feat. So it should not be migrated to 4.4. But he left the final decision to @theodab or @joeyparrish . Sorry!

**Comment by absidue** [comment]
@dsparacio If you want to mix and match releases, may I suggest creating a custom build for the time being. That lets you do the custom stuff you need, without shaka-player having to break versioning standards. Seems like a win-win to me.

The instructions and scripts to do so are here: https://github.com/shaka-project/shaka-player/tree/main/build
