### ISSUE TITLE
Fix Transmuxer tests on Edge Windows

### ISSUE THREAD

**Issue by theodab** [shaka-project/shaka-player#5834]
A recent large PR (#5752) has caused the tests within `test/transmuxer/transmuxer_integration.js` to stop working in the Shaka Player lab machines, when running Edge on Windows. Specifically, after this PR, the calls to `shaka.media.ManifestParser.getFactory` within the loading process throw `UNABLE_TO_GUESS_MANIFEST_TYPE` errors, even for mimeTypes that should have a manifest parser factory associated with them.

Manual test runs on other Windows machines have been unable to reproduce these errors, so this might be a problem with the lab machine rather than the code itself. Because the failures do not seem to be a result of the problem within the player itself, I have decided to temporarily filter those tests for lab runs until this problem can be fixed.

**Comment by avelad** [comment]
Same issue in https://github.com/shaka-project/shaka-player/pull/6002 (HLS-AES-256)

**Comment by joeyparrish** [comment]
I'm on it

**Comment by joeyparrish** [comment]
Removing the check worked for me with `--filter '(HlsParser|Transmuxer)' --browsers Edge`, just running the affected suites.  I'll try one more time with a full test pass on Edge to be sure.

If it works with `--filter` and fails without, there may be pollution from another test suite causing the issue.  That or timing.  (Please don't be timing...)

**Comment by joeyparrish** [comment]
Whatever caused this issue seems to be fixed already in `main`.  I'll have a PR up soon to restore those suite.

**Comment by joeyparrish** [comment]
This needs to be reverted.  The OP says:

> A recent large PR (https://github.com/shaka-project/shaka-player/pull/5752) has caused the tests within test/transmuxer/transmuxer_integration.js to stop working in the **Shaka Player lab machines**, when running Edge on Windows.

I re-enabled them when they passed in the lab, but now I see them failing in GitHub CI.  Had I realized that the environment was wrong, I would have done more testing.

**Comment by joeyparrish** [comment]
This started in #5752.  I'm guessing that we broke the ability to look up parsers by extension somehow, and that Karma (the test runner) has a web server that doesn't return the correct MIME type for m3u8 files.

I'm going to try to fix it instead of reverting the restored tests.

**Comment by joeyparrish** [comment]
The tests don't fail when I filter for just those.  So I believe there may be some test suite polluting the global state in a way that breaks this test.  It may be timing dependent, or there may be an Edge-specific code path.  Not sure.

With extra debug logging, I see that the extension is parsed, the MIME type looked up correctly, but that it still fails to find the right parser with that MIME type:

```
LOG LOG: 'guessMimeType_ pre', Object{assetUri: '/base/test/test/assets/hls-ts-muxed-aac-h264/playlist.m3u8'}
LOG LOG: 'getMimeType pre', Object{uri: '/base/test/test/assets/hls-ts-muxed-aac-h264/playlist.m3u8', extension: 'm3u8'}
LOG LOG: 'getMimeType mid', Object{mimeType: 'application/x-mpegurl'}
LOG LOG: 'guessMimeType_ mid', Object{mimeType: 'application/x-mpegurl'}
LOG LOG: 'guessMimeType_ post', Object{mimeType: 'application/x-mpegurl'}
LOG LOG: 'preloadInner_ pre', Object{mimeType: 'application/x-mpegurl'}
LOG LOG: 'preloadInner_ post', Object{mimeType: 'application/x-mpegurl'}
WARN LOG: 'Could not determine manifest type using MIME type ', 'application/x-mpegurl'
```

**Comment by joeyparrish** [comment]
In `test/player_unit.js`, in the suite `when config.streaming.preferNativeHls is set to true`, we register a fake HLS parser for testing, then unregister it afterward without putting the original back.  That's the culprit.

If that test runs before the other one, it fails.  The order is not deterministic AFAICT, but may be based on load order.  This could explain why it only happens on one device and not another, because the timing of requests to load JS files could have an impact.

**Comment by joeyparrish** [comment]
I found this by looking at `shaka.media.ManifestParser.parsersByMime`, which answers the failing query, and which is not referenced in any other file.  That means only calls to registerParserByMime and unregisterParserByMime can explain the behavior.  Then I searched all tests for those methods and reviewed each call.  There were only 17, and only one pair of calls involved the HLS MIME type.
