### ISSUE TITLE
Optimize Loading of Players using same Manifest

### ISSUE THREAD

**Issue by benbenmotor** [shaka-project/shaka-player#5839]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.7

**Please ask your question**
Is there a way to optimize loading time of manifests when 3 players need to load the same manifest?

Currently, we use 1 player for the video playback, and 2 additional players as still frames (for start and end images to show the user where the video will be trimmed). We have to load the same manifest on each of these players and some of the manifest files we have can be quite large and we can't reduce the sizes (legacy issues).

We looked into preload but that is tied to a player instance and once the player consumes the loader, it can't be re-used later.
Can we load the manifest into a variable and supply that to all 3 players through some other means?

**Comment by avelad** [comment]
>  Is there a way to optimize loading time of manifests when 3 players need to load the same manifest?

You can play a bit with the buffer config and disable* features to consume less resources.


>  Can we load the manifest into a variable and supply that to all 3 players through some other means?

Currently that is not possible.

**Comment by benbenmotor** [comment]
Which features would you suggest disabling? 
We set our buffer/rebuffer goals to 1 second.

**Comment by avelad** [comment]
> Which features would you suggest disabling? 

manifest.disableAudio = true
manifest.disableText = true
manifest.disableThumbnails = true
