### ISSUE TITLE
Stream deteriorates to lowest quality on chromecast when turning liveSync on, using ll-hls

### ISSUE THREAD

**Issue by aifeipeng** [shaka-project/shaka-player#5843]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not Applicable

**What version of Shaka Player are you using?**

4.5.0

**Can you reproduce the issue with our latest release version?**
Don't know if it's possible

**Can you reproduce the issue with the latest code from `main`?**
Don't know if it's possible

**Are you using the demo app or your own custom app?**
My own

**If custom app, can you reproduce the issue using our demo app?**
I cannot reproduce the issue on computer

**What browser and OS are you using?**
Android TV 9.1.1
chromecast built in: 1.68.374976

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
nvidia shield
version 11 (I think)

**What are the manifest and license server URIs?**

Manifest uri: https://kanal75-live.akamaized.net/live/Data/atg-kanal-17-02/HLS-LL-Ateme/atg-kanal-17-02.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

`shakaConfig = { streaming: { autoLowLatencyMode: true, liveSync: true, liveSyncMaxLatency: 8 } };`

**What did you do?**

created a custom web receiver chromecast app.
Set
```
castReceiverOptions.useShakaForHls = true;
castReceiverOptions.shakaVersion = "4.5.0";
```
Then casted https://kanal75-live.akamaized.net/live/Data/atg-kanal-17-02/HLS-LL-Ateme/atg-kanal-17-02.m3u8 to the application.

**What did you expect to happen?**
Initially I expected to not get drift on the stream. When realizing I had drift from live edge I added `liveSync: true`. When liveSync was added I expected to have the same behaviour but when falling behind live edge more than 8 seconds it would speed up to be on live edge again.

**What actually happened?**

The quality goes steadily down to lowest quality, then more or less stays there.

My own theory is that the chromecast (nvidia shield in this case) is to weak to do all the requests in a high enough pace to handle low latency. Shaka then prioritizes being live edge rather than quality. Which means I get stuck with a low quality stream.

Could this be the case? In that case it's not possible to actually have low latency (with good quality) on chromecasts.

**Comment by avelad** [comment]
In the main branch this problem has been resolved through several changes, but version 4.5.1 has not yet been released
