### ISSUE TITLE
Variant synchronization in HLS after selectVariantTrack does not work

### ISSUE THREAD

**Issue by Able1991** [shaka-project/shaka-player#5849]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
`v4.5.0-uncompiled`

**Can you reproduce the issue with our latest release version?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36`

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```
{
    "manifest": {
        "hls": {
            "sequenceMode": false
        }
    }
}
```

**What did you do?**

Call selectVariantTrack(track) or selectVariantsByLabel(track) on HLS stream with EXT-X-PROGRAM-DATE-TIME tags 

**What did you expect to happen?**
Switching qualities with track synchronization by #EXT-X-PROGRAM-DATE-TIME tags

**What actually happened?**
Due to a slight desynchronization (less than 0.1 seconds), the player does not synchronize the quality and I see the image and sound twitching

https://github.com/shaka-project/shaka-player/blob/v4.5.x/lib/media/media_source_engine.js#L821

```
if (timestampOffsetDifference >= 0.1 || seeked || adaptation) {
  timestampOffset = calculatedTimestampOffset;
  if (this.attemptTimestampOffsetCalculation_) {
    this.enqueueOperation_(
        contentType,
        () => this.abort_(contentType));
    this.enqueueOperation_(
        contentType,
        () => this.setTimestampOffset_(contentType, timestampOffset));
  }
}
```

Checking the behavior on the demo page, I displayed debugging information in the console:

<img width="778" alt="image" src="https://github.com/shaka-project/shaka-player/assets/3898046/25f99947-e768-4204-b539-c15e8db026ad">

After that, I started to call switching qualities in the console using the following method: `shakaDemoMain.player_.selectVariantsByLabel("audio_360p", false)`

Result:
![telegram-cloud-photo-size-2-5343688809948237531-y](https://github.com/shaka-project/shaka-player/assets/3898046/e04806a4-423c-4929-bfef-c298e601bcc2)

In some cases, immediately after switching quality, the MediaSourceEngine.appendBuffer method is called for segments of the current quality with the adaptation=true flag, after which the mediaState.adaptation flag is set to false. Next when the MediaSourceEngine.appendBuffer method is called for new segments of the new selected quality, time synchronization does not occur because timestampOffsetDifference < 0.1 and the adaptation flag = false

It turns out that the player sometimes synchronizes the segments currently loaded for the previous variant, and does not synchronize the following segments of the new variant

**Comment by avelad** [comment]
Please provide a url with the stream. Thanks!

**Comment by Able1991** [comment]
> Please provide a url with the stream. Thanks!

Hi. I sent it to shaka-player-maintainers@googlegroups.com with issue number in the subject line
