### ISSUE TITLE
shaka.ads.AdManager.AD_STARTED fires before ad starts with AWS Media Tailor

### ISSUE THREAD

**Issue by radiantmediaplayer** [shaka-project/shaka-player#5854]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Y

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**
4.5.0

**Can you reproduce the issue with our latest release version?**
Y

**Can you reproduce the issue with the latest code from `main`?**
Y

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Y

**What browser and OS are you using?**
Windows 11 Chrome 119

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
See below

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
We are trying to implement our own UI on top of Shaka player when used with AWS Media Tailor. We rely on ad events to set our ad UI but we are having an issue with the shaka.ads.AdManager.AD_STARTED event that fires before player has been interacted with (case with no autoplay). Below is the code we are using that reproduces the issue.
```
<!DOCTYPE html>
<html>

<head>
  <!-- Shaka Player ui compiled library: -->
  <script src="https://ajax.googleapis.com/ajax/libs/shaka-player/4.5.0/shaka-player.ui.js"></script>
  <!-- Shaka Player ui compiled library default CSS: -->
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/shaka-player/4.5.0/controls.css">
</head>

<body>
  <!-- The data-shaka-player-container tag will make the UI library place the controls in this div.
         The data-shaka-player-cast-receiver-id tag allows you to provide a Cast Application ID that
           the cast button will cast to; the value provided here is the sample cast receiver. -->
  <div data-shaka-player-container style="max-width:40em" data-shaka-player-cast-receiver-id="07AEE832">
    <!-- The data-shaka-player tag will make the UI library use this video element.
            If no video is provided, the UI will automatically make one inside the container div. -->
    <video data-shaka-player id="video" style="width:100%;height:100%"></video>
  </div>
  <script>
    async function init() {
      // When using the UI, the player is made automatically by the UI object.
      const video = document.getElementById('video');
      const ui = video['ui'];
      const controls = ui.getControls();

      const container = controls.getServerSideAdContainer();
      const player = controls.getPlayer();
      const netEngine = player.getNetworkingEngine();
      const adManager = player.getAdManager();
      adManager.initMediaTailor(container, netEngine, video);

      adManager.addEventListener(shaka.ads.AdManager.AD_STARTED, () => {
        console.log('AWS Media Tailor: AD_STARTED');
      });

      adManager.addEventListener(shaka.ads.AdManager.AD_PAUSED, () => {
        console.log('AWS Media Tailor: AD_PAUSED');
      });

      adManager.addEventListener(shaka.ads.AdManager.AD_RESUMED, () => {
        console.log('AWS Media Tailor: AD_RESUMED');
      });

      adManager.addEventListener(shaka.ads.AdManager.AD_STOPPED, () => {
        console.log('AWS Media Tailor: AD_STOPPED');
      });

      const mediaTailorUrl = 'https://ad391cc0d55b44c6a86d232548adc225.mediatailor.us-east-1.amazonaws.com/v1/session/d02fedbbc5a68596164208dd24e9b48aa60dadc7/singssai/master.m3u8';
      const uri = await adManager.requestMediaTailorStream(mediaTailorUrl);
      player.load(uri);
    }

    document.addEventListener('shaka-ui-loaded', init);
  </script>
</body>

</html>
```

**What did you do?**
Load player on page and wait for shaka.ads.AdManager.AD_STARTED. This event fires when the player has not been interacted with.

**What did you expect to happen?**
shaka.ads.AdManager.AD_STARTED should fire only when ad start, no on page/player load.

**What actually happened?**
shaka.ads.AdManager.AD_STARTED fires on page load. Please reload page if you cannot reproduce the issue on the first try. Thanks

**Comment by avelad** [comment]
@radiantmediaplayer PR to fix it: https://github.com/shaka-project/shaka-player/pull/5855

**Comment by radiantmediaplayer** [comment]
Thanks I have verified that the fix works for us. I have already merged this in our local branch so we can move on with our work. We will update our player with the official release once the fix is publicly available.
