### ISSUE TITLE
 Inquiry about Identifying Differences between Downloaded Persistence License and Current Widevine Version

### ISSUE THREAD

**Issue by ranjithrr** [shaka-project/shaka-player#5860]
Shaka Player Version : 2.0.0

Question :
I have a specific query related to the identification of differences between the version of Widevine for which a persistence license was downloaded and the current Widevine version. Is there a method or mechanism that allows us to determine whether there is a difference between the two versions? This information is crucial as it will enable us to inform our users about any potential compatibility issues.

**Comment by avelad** [comment]
Currently that information is not provided, sorry.
