### ISSUE TITLE
Are there any events that can detect buffer wall errors?

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#5867]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.5.0

**Please ask your question**
Are there any events that can detect buffer wall errors?

When BUFFER_STALLED_ERROR, BUFFER_NUDGE_ON_STALL error of hls.js occurs, I would like to forward the log and perform recovery like the code below.

```
                case Hls.ErrorDetails.BUFFER_STALLED_ERROR:
                    this._dispatchEvent(StreamConstant.STREAM_EVENT.BUFFER, {detail : data.details});
                    break;
                case Hls.ErrorDetails.BUFFER_NUDGE_ON_STALL:
                    this.media.currentTime = this.media.buffered.end(this.media.buffered.length - 1) - 2;
                    break;
```

Is there an error event sample code related to buffer stuck in shaka player?

**Comment by avelad** [comment]
Right now, we have two related events `stalldetected` and `gapjumped`. Are enough for you? Thanks!
