### ISSUE TITLE
HLS V4 live stream from Azure media services taking more time to load than Live Akamai m3u8

### ISSUE THREAD

**Issue by Ravi-79** [shaka-project/shaka-player#5870]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I checked, no duplicate issues

**If the problem is related to FairPlay, have you read the tutorial?**

No it's not

**What version of Shaka Player are you using?**

V4.5.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
OS:
Edition Windows 11 Enterprise
Version 22H2

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**Azure HLS v4 :**https://amscdn-mpslive1-uswe.streaming.media.azure.net/17291d28-dc35-4dcc-b87a-287686416f84/d5516941-3d02-47b3-a067-b2bb30466f62.ism/manifest(format=m3u8-aapl)
**Akami Live:** https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8 

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

{
"drm": {
"retryParameters": {
"maxAttempts": 2,
"baseDelay": 1000,
"backoffFactor": 2,
"fuzzFactor": 0.5,
"timeout": 30000,
"stallTimeout": 5000,
"connectionTimeout": 10000
},
"servers": {},
"clearKeys": {},
"advanced": {},
"delayLicenseRequestUntilPlayed": false,
"persistentSessionOnlinePlayback": false,
"persistentSessionsMetadata": [],
"logLicenseExchange": false,
"updateExpirationTime": 1,
"preferredKeySystems": [],
"keySystemsMapping": {},
"parseInbandPsshEnabled": false,
"minHdcpVersion": ""
},
"manifest": {
"retryParameters": {
"maxAttempts": 2,
"baseDelay": 1000,
"backoffFactor": 2,
"fuzzFactor": 0.5,
"timeout": 30000,
"stallTimeout": 5000,
"connectionTimeout": 10000
},
"availabilityWindowOverride": null,
"disableAudio": false,
"disableVideo": false,
"disableText": false,
"disableThumbnails": false,
"defaultPresentationDelay": 0,
"segmentRelativeVttTiming": false,
"raiseFatalErrorOnManifestUpdateRequestFailure": false,
"dash": {
"clockSyncUri": "",
"ignoreDrmInfo": false,
"disableXlinkProcessing": false,
"xlinkFailGracefully": false,
"ignoreMinBufferTime": false,
"autoCorrectDrift": true,
"initialSegmentLimit": 1000,
"ignoreSuggestedPresentationDelay": false,
"ignoreEmptyAdaptationSet": false,
"ignoreMaxSegmentDuration": false,
"keySystemsByURI": {
"urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
"urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
"urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
"urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
"urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
"urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
},
"sequenceMode": false,
"enableAudioGroups": false
},
"hls": {
"ignoreTextStreamFailures": false,
"ignoreImageStreamFailures": false,
"defaultAudioCodec": "mp4a.40.2",
"defaultVideoCodec": "avc1.42E01E",
"ignoreManifestProgramDateTime": false,
"mediaPlaylistFullMimeType": "video/mp2t; codecs="avc1.42E01E, mp4a.40.2"",
"useSafariBehaviorForLive": false,
"liveSegmentsDelay": 3,
"sequenceMode": true,
"ignoreManifestTimestampsInSegmentsMode": false
},
"mss": {
"sequenceMode": false,
"keySystemsBySystemId": {
"9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
"79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
}
}
},
"streaming": {
"retryParameters": {
"maxAttempts": 2,
"baseDelay": 1000,
"backoffFactor": 2,
"fuzzFactor": 0.5,
"timeout": 30000,
"stallTimeout": 5000,
"connectionTimeout": 10000
},
"rebufferingGoal": 2,
"bufferingGoal": 10,
"bufferBehind": 30,
"ignoreTextStreamFailures": false,
"alwaysStreamText": false,
"startAtSegmentBoundary": false,
"gapDetectionThreshold": 0.5,
"gapJumpTimerTime": 0.25,
"durationBackoff": 1,
"safeSeekOffset": 5,
"stallEnabled": true,
"stallThreshold": 1,
"stallSkip": 0.1,
"useNativeHlsOnSafari": true,
"inaccurateManifestTolerance": 2,
"lowLatencyMode": false,
"autoLowLatencyMode": false,
"forceHTTPS": false,
"preferNativeHls": false,
"updateIntervalSeconds": 1,
"dispatchAllEmsgBoxes": false,
"observeQualityChanges": false,
"maxDisabledTime": 30,
"parsePrftBox": false,
"segmentPrefetchLimit": 0,
"liveSync": false,
"liveSyncMaxLatency": 1,
"liveSyncPlaybackRate": 1.1
},
"mediaSource": {
"codecSwitchingStrategy": "smooth",
"sourceBufferExtraFeatures": "",
"forceTransmux": false,
"insertFakeEncryptionInInit": true
},
"offline": {
"usePersistentLicense": true,
"numberOfParallelDownloads": 5
},
"abr": {
"enabled": true,
"useNetworkInformation": true,
"defaultBandwidthEstimate": 1000000,
"switchInterval": 8,
"bandwidthUpgradeTarget": 0.85,
"bandwidthDowngradeTarget": 0.95,
"restrictions": {
"minWidth": 0,
"maxWidth": null,
"minHeight": 0,
"maxHeight": null,
"minPixels": 0,
"maxPixels": null,
"minFrameRate": 0,
"maxFrameRate": null,
"minBandwidth": 0,
"maxBandwidth": null
},
"advanced": {
"minTotalBytes": 128000,
"minBytes": 16000,
"fastHalfLife": 2,
"slowHalfLife": 5
},
"restrictToElementSize": false,
"restrictToScreenSize": false,
"ignoreDevicePixelRatio": false,
"clearBufferSwitch": false,
"safeMarginSwitch": 0
},
"autoShowText": 3,
"preferredAudioLanguage": "",
"preferredAudioLabel": "",
"preferredTextLanguage": "",
"preferredVariantRole": "",
"preferredTextRole": "",
"preferredAudioChannelCount": 2,
"preferredVideoHdrLevel": "AUTO",
"preferredVideoCodecs": [],
"preferredAudioCodecs": [],
"preferForcedSubs": false,
"preferredDecodingAttributes": [],
"restrictions": {
"minWidth": 0,
"maxWidth": null,
"minHeight": 0,
"maxHeight": null,
"minPixels": 0,
"maxPixels": null,
"minFrameRate": 0,
"maxFrameRate": null,
"minBandwidth": 0,
"maxBandwidth": null
},
"playRangeStart": 0,
"playRangeEnd": null,
"cmcd": {
"enabled": false,
"sessionId": "",
"contentId": "",
"useHeaders": false
},
"lcevc": {
"enabled": false,
"dynamicPerformanceScaling": true,
"logLevel": 0,
"drawLogo": false
},
"ads": {
"customPlayheadTracker": false
}
}

**What did you do?**

Step 1: Create a basic player page using Shaka UI libraries.
Step 2: Configure the player to show the progress bar with this code 
player.configure('manifest.hls.useSafariBehaviorForLive',false);
player.configure('manifest.hls.sequenceMode',false);
Step 3:open the player URL and observe the time difference between the two deferent HLS stream.

**What did you expect to happen?**
The akami HLS is loading the video within 4 to 5 seconds, where as the Azure HLS is taking more than 9 to 10 seconds to load.
Please help us to optimize the initial loading time for Azure HLS live stream.

**What actually happened?**

I don't know what happening. Please find below mentioned screenshots for the time difference in each manifest.

Code snippet:
![image](https://github.com/shaka-project/shaka-player/assets/131441182/6fdcf09f-2ebd-4eda-b878-f9edb620003a)

Azure HLS v4: Taking 10 seconds before the player loaded fully.
![image](https://github.com/shaka-project/shaka-player/assets/131441182/3dfff5ab-73b1-459c-8a5c-6fafb6d74b5b)

Akamai Live HLS: Taking only 2 seconds before the player loaded fully.
![image](https://github.com/shaka-project/shaka-player/assets/131441182/bac209be-8b36-4b16-907d-e236d2e2a8e9)

**Note :** We have did many test samples, mostly the akamai is loaded within 5 seconds

**Comment by avelad** [comment]
I see several reasons why it takes time to load.
- The playlists are totally different
- Akamai playlist has content muxed with TS container.
- The Azure playlist uses MP4 with initial segments, also the content is not muxed.
- The Azure playlist does not have an extension so to detect the mimetype, if it is not passed in the load call, it causes an extra request to detect the mimetype.

--> 3 requests are necessary to load the Akamai stream
--> 8 requests are necessary to load the Azure stream

This is not a bug because the playlists are totally different, and the times of each CDN are also different.

**Comment by Ravi-79** [comment]
> I see several reasons why it takes time to load.
> 
> * The playlists are totally different
> * Akamai playlist has content muxed with TS container.
> * The Azure playlist uses MP4 with initial segments, also the content is not muxed.
> * The Azure playlist does not have an extension so to detect the mimetype, if it is not passed in the load call, it causes an extra request to detect the mimetype.
> 
> --> 3 requests are necessary to load the Akamai stream --> 8 requests are necessary to load the Azure stream
> 
> This is not a bug because the playlists are totally different, and the times of each CDN are also different.

Thanks for the information @avelad .
