### ISSUE TITLE
Hls playback is not recover after internet connection is restored

### ISSUE THREAD

**Issue by Able1991** [shaka-project/shaka-player#5873]
**What version of Shaka Player are you using?**
`v4.5.0-uncompiled`

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
[The demo](https://shaka-player-demo.appspot.com/demo/#audiolang=ru;textlang=ru;manifest.hls.sequenceMode=false;uilang=ru;asset=https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8;panel=HOME;build=uncompiled)

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

uri= `https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8`

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```
{
    "manifest": {
        "hls": {
            "sequenceMode": false
        }
    }
}
```

**What did you do?**

Set throttling to offline in Chrome dev tools for 15 seconds, and then disable it 

**What did you expect to happen?**
Restore playback

**What actually happened?**
Nothing, the player spins the loader

<img width="754" alt="image" src="https://github.com/shaka-project/shaka-player/assets/3898046/922b9700-f8ce-4fe6-847b-861ae0852413">

**Comment by avelad** [comment]
@theodab can you review it? Thanks!

**Comment by avelad** [comment]
I can reproduce the error

**Comment by avelad** [comment]
Only occurs with live HLS streams
