### ISSUE TITLE
when i upgraded to next.js from version 12 to 13, player error code 4004.

### ISSUE THREAD

**Issue by JockGo** [shaka-project/shaka-player#5874]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
latest

**Please ask your question**

After updating Next.js from version 12 to 13, 
I'm experiencing a persistent 4004 error when playing DRM-protected videos, which worked fine in version 12. 
I've confirmed that reverting to version 12 resolves the issue. 
Is there a way to address this problem?

**Comment by theodab** [comment]
I do not believe any of the common Shaka Player maintainers have any Next.js development experience.
Perhaps you could ask the person who made [that third-party next.js integration tutorial](https://github.com/amit08255/shaka-player-react-with-ui-config/tree/master/nextjs-shaka-player)? @amit08255. I don't know how active they are though.

**Comment by amit08255** [comment]
https://github.com/amit08255/shaka-player-react-with-ui-config/tree/master/nextjs-shaka-player

This repository contains example for shaka player integration with NextJS 13. Feel free to let me know if this doesn't work for you.

**Comment by JockGo** [comment]
Firstly, I appreciate to @theodab and @amit08255.
and I don't know why on next 13 doesn't work with it. But, when i update Next version 13 to 14.
it works properly.

**Comment by JockGo** [comment]
Firstly, I appreciate to @theodab and @amit08255.
and I don't know why on next 13 doesn't work with it. But, when i update Next version 13 to 14.
it works properly.

**Comment by JockGo** [comment]
Firstly, I appreciate to @theodab and @amit08255.
and I don't know why on next 13 doesn't work with it. But, when i update Next version 13 to 14.
it works properly.

if anyone who doesn't work shaka player with drm on next 13, try update to 14. it working very well.
