### ISSUE TITLE
BUFFER_READ_OUT_OF_BOUNDS encountered in linear stream

### ISSUE THREAD

**Issue by nrcrast** [shaka-project/shaka-player#5891]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**

3.3.10

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome Mac

**What did you do?**

Play back a linear stream. After some random period of time, it will error out with BUFFER_READ_OUT_OF_BOUNDS.

**What did you expect to happen?**
Playback for _eternity_

**What actually happened?**

**Comment by avelad** [comment]
Please share a stream to test it and please you must to check if it happens in the Demo app. Thanks!
