### ISSUE TITLE
In `addTextTrackAsync` in `SRC_EQUALS` mode the unmodified input language gets compared to the normalised one

### ISSUE THREAD

**Issue by absidue** [shaka-project/shaka-player#5901]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not applicable

**What version of Shaka Player are you using?**

4.6.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
In the demo player

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Firefox on Windows 10

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not applicable

**What are the manifest and license server URIs?**

Call `Player.load()` with any MP4 file, so that the player uses the `SRC_EQUALS` load mode.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

_Load an MP4 asset or an HLS stream on iOS_

`await document.getElementById('player').ui.getControls().getPlayer().addTextTrackAsync('data:text/vtt,WEBVTT', 'zh-Hans', 'captions', 'text/vtt')`

**What did you expect to happen?**
No error to be thrown

**What actually happened?**

A `CANNOT_ADD_EXTERNAL_TEXT_TO_SRC_EQUALS` error is thrown, but the text track is added to the DOM and appears in the text track selector.

By the looks of it, shaka-player compares the input language `zh-Hans` against the `language` on the track, which contains the normalised language `zh-HANS` and then throws an error because they don't match.

**Comment by avelad** [comment]
@absidue are you interested on send a PR to fix it? Thanks!

**Comment by absidue** [comment]
If shaka-player didn't have a CLA, I would consider it opening pull requests, but I don't particularly fancy doxxing myself and signing my life away to Google, just to do a one line change. Especially as shaka-player is just used in a project I work on in my free time, nothing corporate.

Also with shaka-player's non-standard build system, it would probably take me multiple hours to setup a shaka-player development environment, which seems overkill for a one line change. I would be willing to do that if the CLA didn't exist.
