### ISSUE TITLE
WebVTT rendering - shaka.text.Cue

### ISSUE THREAD

**Issue by eowino** [shaka-project/shaka-player#5902]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.4.0

**Please ask your question**

**WHAT**

- How does the compiler/minifier determine which properties to uglify/minify and which to leave as is?
- Is it possible to extend `shaka.text.Cue`?
   - The problem I am facing is that `shaka.text.Cue` doesn't seem to support [VTTCue.line](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/line) or [VTTCue.snapToLines](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/snapToLines)
in the minified version at runtime.

![image (1)](https://github.com/shaka-project/shaka-player/assets/9787512/bcad0fd0-6fa3-4c59-8f1e-00d16188cfb9)
The screenshot above shows an instance of [shaka.text.Cue](https://github.com/shaka-project/shaka-player/blob/main/lib/text/cue.js) with some uglified and some readable properties. To my humble eye, its unclear what the compiler latches onto as the determining factor.

**WHY**

I am trying to take control of the rendering of VTTCues because I am not getting quite the same behaviour as [getCueAsHTML](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/getCueAsHTML). The solution I have arrived at is to extend `shaka.text.VttTextParser` and register a parser using the `shaka.text.TextEngine.registerParser` API for the `text/vtt` mimeType.

**Comment by absidue** [comment]
Upgrade to a newer version of shaka-player, that was fixed a while ago.
