### ISSUE TITLE
HLS Shaka Error MEDIA.TRANSMUXING_FAILED with ts playlist

### ISSUE THREAD

**Issue by Able1991** [shaka-project/shaka-player#5907]
**What version of Shaka Player are you using?**
`v4.6.0-uncompiled`

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
The demo

**What browser and OS are you using?**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`

**What are the manifest and license server URIs?**
VOD HLS, I sent it by email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default

**What did you do?**
tried to play the video

**What did you expect to happen?**
Play

**What actually happened?**
Shaka Error MEDIA.TRANSMUXING_FAILED

**Comment by avelad** [comment]
Your manifest does not include codec information, so Shaka uses a codec by default. If you include the CODECS in the master playlist it will work correctly, alternatively you can use the setting `manifest.hls.disableCodecGuessing = true` to make your stream work correctly.

Thanks!
