### ISSUE TITLE
adding muxjs dependency on shaka 4.6.0 causing error?

### ISSUE THREAD

**Issue by fredrik-telia** [shaka-project/shaka-player#5912]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.6.0

**Please ask your question**
Tried bumping shaka-player from 4.4.2 to version 4.6.0 in our repo and noticed a new error when trying to play something, the error was:
`undefined is not supported`

I tracked it down to where we add a dependency to muxjs:
`shaka.dependencies.add(shaka.dependencies.Allowed.muxjs, muxjs);`

I couldn't find anything in the release notes regarding this, is it a bug, or should we avoid using muxjs?

**Comment by avelad** [comment]
Since version 4.5 mux.js is not necessary, please do not try to use it. Thank you!
