### ISSUE TITLE
The CEA subtitles can not be recognised with latest version (4.6.0)

### ISSUE THREAD

**Issue by Wenjie-Shao** [shaka-project/shaka-player#5915]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. It's not mentioned recently.

**If the problem is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**

It can be reproduced in both 4.3.4 and latest version (which is 4.6.0 currently)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not try

**Are you using the demo app or your own custom app?**

Both.

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome and Chromecast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
https://lnc-bloomberg-originals.tubi.video/tubi-bloomberg-quicktake-ZdKlqOiMOCbub2GE.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Just use default config

**What did you do?**
Just open demo page and play the content https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://lnc-bloomberg-originals.tubi.video/tubi-bloomberg-quicktake-ZdKlqOiMOCbub2GE.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

**What did you expect to happen?**
The subtitle could appear or the text tracks could be obtained by calling `player.getTextTracks()` or `player.video_.textTracks`

**What actually happened?**
```
player = video.ui.getControls().getLocalPlayer()
player.getTextTracks()
 > []
player.video_.textTracks
> TextTrackList {length: 0, onchange: null, onaddtrack: null, onremovetrack: null}
```

I also tried with the `hls.js` demo https://hlsjs.video-dev.org/demo/. The text tracks could be obtained from video element like this
<img width="747" alt="image" src="https://github.com/shaka-project/shaka-player/assets/39085271/8c14fb4d-ec99-4845-8dce-c649e2f06a41">

**Comment by avelad** [comment]
Your master playlist:

```
#EXTM3U
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="cc",LANGUAGE="en",NAME="English",AUTOSELECT=YES,INSTREAM-ID="CC1"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="master_broadcast",LANGUAGE="eng",NAME="Master Audio",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=3158000,RESOLUTION=1280x720,CODECS="mp4a.40.2, avc1.640020",AUDIO="master_broadcast"
origin/contribution-m1-bloomberg-quicktake/3128k/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=958000,RESOLUTION=640x360,CODECS="mp4a.40.2, avc1.640016",AUDIO="master_broadcast"
origin/contribution-m1-bloomberg-quicktake/928k/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=558000,RESOLUTION=428x240,CODECS="mp4a.40.2, avc1.640015",AUDIO="master_broadcast"
origin/contribution-m1-bloomberg-quicktake/528k/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2158000,RESOLUTION=960x540,CODECS="mp4a.40.2, avc1.64001f",AUDIO="master_broadcast"
origin/contribution-m1-bloomberg-quicktake/2128k/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6158000,RESOLUTION=1920x1080,CODECS="mp4a.40.2, avc1.640028",AUDIO="master_broadcast"
origin/contribution-m1-bloomberg-quicktake/6128k/index.m3u8
```
The attribute `CLOSED-CAPTIONS` is missing in `#EXT-X-STREAM-INF`. We need this attribute in order to get the correct closed captions tag.

The right master playlist should be:

```
#EXTM3U
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="cc",LANGUAGE="en",NAME="English",AUTOSELECT=YES,INSTREAM-ID="CC1"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="master_broadcast",LANGUAGE="eng",NAME="Master Audio",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=3158000,RESOLUTION=1280x720,CODECS="mp4a.40.2, avc1.640020",AUDIO="master_broadcast",CLOSED-CAPTIONS="cc"
origin/contribution-m1-bloomberg-quicktake/3128k/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=958000,RESOLUTION=640x360,CODECS="mp4a.40.2, avc1.640016",AUDIO="master_broadcast",CLOSED-CAPTIONS="cc"
origin/contribution-m1-bloomberg-quicktake/928k/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=558000,RESOLUTION=428x240,CODECS="mp4a.40.2, avc1.640015",AUDIO="master_broadcast",CLOSED-CAPTIONS="cc"
origin/contribution-m1-bloomberg-quicktake/528k/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2158000,RESOLUTION=960x540,CODECS="mp4a.40.2, avc1.64001f",AUDIO="master_broadcast",CLOSED-CAPTIONS="cc"
origin/contribution-m1-bloomberg-quicktake/2128k/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6158000,RESOLUTION=1920x1080,CODECS="mp4a.40.2, avc1.640028",AUDIO="master_broadcast",CLOSED-CAPTIONS="cc"
origin/contribution-m1-bloomberg-quicktake/6128k/index.m3u8
```

**Comment by avelad** [comment]
hm... Accoring to https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.6.1

```
TYPE

      The value is an enumerated-string; valid strings are AUDIO, VIDEO,
      SUBTITLES, and CLOSED-CAPTIONS.  This attribute is REQUIRED.

      Typically, closed-caption [[CEA608](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#ref-CEA608)] media is carried in the video
      stream.  Therefore, an EXT-X-MEDIA tag with TYPE of CLOSED-
      CAPTIONS does not specify a Rendition; the closed-caption media is
      present in the Media Segments of every video Rendition.
```

**Comment by avelad** [comment]
The spec is a bit ambiguous, after talk with @theodab, we are going to support this case.

**Comment by Wenjie-Shao** [comment]
Thank you for your fast response! It would be a great help.

**Comment by siarheipashkevich** [comment]
@avelad @Wenjie-Shao how to HIDE this captions and subtitles from Shaka Player ???

My manifest file does not have any text tracks but in the player controls I have options to select subtitles, I've hided it using
```
textDisplayFactory: () => new StubTextDisplayer(),
```

but it's working only on Android, but on iOS I have this "damn" subtitles, how to hide them??? 

![image](https://github.com/shaka-project/shaka-player/assets/7753600/8eadf936-99bc-4451-8763-f3eab325127a)

Please help me
