### ISSUE TITLE
Demo: Add field for chapters URL when adding custom content

### ISSUE THREAD

**Issue by absidue** [shaka-project/shaka-player#5932]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

When using the demo player to check if bugs are reproducible there instead of just the custom app, you can't currently add chapters unless they are in the manifest.

**Describe the solution you'd like**

It would be nice to have a text field for a chapters URL, next to the existing one for a thumbnails URL.

**Describe alternatives you've considered**

Asking shaka-player contributors to add the chapters through the browser's dev tools console.

**Additional context**

I wanted to report two UI bugs but noticed that the demo doesn't make it easy to add custom characters.

The first one is that when both chapters and thumbnails are used that the same time (currently no demo assets available with both), the chapter text is displayed below the thumbnail on the z-axis, so you can't see it.

The other is that because the chapter labels are limited to the width of the segment, long ones on short chapters get aggressively wrapped and overflow below the bottom of the player.

**Comment by avelad** [comment]
I have a working PR with this, so it will be available in v5.0 and in the nightly soon
