### ISSUE TITLE
getPlayheadTimeAsDate() differs from program time (X-EXT-PROGRAM-DATE-TIME)

### ISSUE THREAD

**Issue by bbert** [shaka-project/shaka-player#5939]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**

4.6.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome/Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Sent by email

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

1.  Load the live manifest
2. Pause afters some time after playback has started
3. Open the console and call the `getPlayheadTimeAsDate()` API method

`document.querySelector('video').ui.player_.getPlayheadTimeAsDate()
`

**What did you expect to happen?**

The playlist contains the `X-EXT-PROGRAM-DATE-TIME` tag, and the live content's video displays a timecode synchronized with the `X-EXT-PROGRAM-DATE-TIME` tag.

The `getPlayheadTimeAsDate()` should return the same time value as the one displayed on the video.

**What actually happened?**

The `getPlayheadTimeAsDate()` returns a value that differs by a few seconds from the real time value displayed on the video, 13 seconds in the following snapshot.

![image](https://github.com/shaka-project/shaka-player/assets/5312520/68060d85-d68b-41f5-8bc8-2fe23fae757c)

As a comparison, here is a snaphost of hls.js (Windows/Chrome):

![image](https://github.com/shaka-project/shaka-player/assets/5312520/5e2e5e24-608c-43ca-b125-f90f1f787b67)

![image](https://github.com/shaka-project/shaka-player/assets/5312520/63f2aa2a-300e-4f10-ba85-6300b14be112)

And a snapshot of AVPlayer on iOS:

![Screenshot 2023-11-27 at 16 03 01](https://github.com/shaka-project/shaka-player/assets/5312520/6da8ba9d-137e-41c5-95f5-b1d0b0deeb3e)

Maybe the problem is related to the issue #4330

**Comment by avelad** [comment]
@bbert are you interested on send a PR to fix it? Thanks! (see: https://github.com/shaka-project/shaka-player/blob/main/lib/player.js#L4417)

**Comment by bbert** [comment]
@avelad I'm not aware enough of source code to try to fix it without introducing any regression.

I had a look but don't understand this part of code: https://github.com/shaka-project/shaka-player/blob/610206002838157658bdadb608588c4430cf075d/lib/media/presentation_timeline.js#L303

`#X-EXT-PROGRAM-DATE-TIME` seems not be considered to compute timeline presentationStartTime_ used by `getPlayheadTimeAsDate()`.

**Comment by avelad** [comment]
@bbert Can you check if https://github.com/shaka-project/shaka-player/pull/6059 resolves your issue? Thanks!

**Comment by bbert** [comment]
Hi @avelad, I confirm PR #6059 resolves the issue.
Thanks!

**Comment by joeyparrish** [comment]
We are reverting the fix, which caused additional issues.
