### ISSUE TITLE
trickPlay doesn't auto-cancel as specified

### ISSUE THREAD

**Issue by Wayne-Morgan** [shaka-project/shaka-player#5944]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**
4.4.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Reproducible on demo

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Windows Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Live DASH, e.g.
https://storage.googleapis.com/shaka-live-assets/player-source.mpd
https://livesim2.dashif.org/livesim2/utc_head/testpic_2s/Manifest.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default on demo

**What did you do?**
Play live dash
pause or seek back a little from live edge
set a trickPlay > 1
wait for playback to catch up to live

Seek back near the start of the seekable range
set a trickPlay < 0
wait for playback to get to start of seekable range

**What did you expect to happen?**
When trickplay gets to live edge, cancel the trickplay
When trickplay gets to start of seekable range, cancel the trickplay
as specified [here](https://github.com/shaka-project/shaka-player/blob/0deb25b57f0612a802ad8fbc8e3e379dff54a57c/lib/player.js#L3552)

**What actually happened?**
Upon getting close to the live edge, the player would buffer for a while then continue playing at the faster rate
Upon getting close to the start of the seekable range, the player would seek forward, and then continue with the backward trickPlay
`Jumping forward 5.05700046767015 seconds to catch up with the seek range.`

**Comment by avelad** [comment]
@Wayne-Morgan are you interested on send a PR to fix it? Thanks!
