### ISSUE TITLE
Allow no-cors on fetch request

### ISSUE THREAD

**Issue by Robloche** [shaka-project/shaka-player#5959]
I was looking for a solution to my problem and found the following issue:
https://github.com/shaka-project/shaka-player/issues/1286

I think I have indeed found a use case for such a request.
I have an HLS manifest in which segments don't have any extension.
Then, as shown in code below, the parser does a `HEAD` request to retrieve the mime type:

https://github.com/shaka-project/shaka-player/blob/678bf2524dae237ca6ec08db35e50e26598d4e63/lib/hls/hls_parser.js#L3754-L3761

And in my case, a CORS error happens.
Since I don't have any control on the manifest and I don't care about the anwser (only the response headers matter), a `no-cors` fetch request would certainly solves my issue.

What do you think?

**Comment by avelad** [comment]
So what you propose is to use no-cors for HEAD requests? If you can share the manifest with me so I can investigate the issue and provide an appropriate solution. Thanks!

**Comment by avelad** [comment]
I have been looking and it is not possible, in no-cors mode we do not have access to the headers, so we can not detect the mimetype correctly.

**Comment by Robloche** [comment]
Oh, you're totally right.
I knew I wouldn't be able to access the response's body, but I thought the headers would be OK.

Thanks for the quick answer.

**Comment by Robloche** [comment]
In fact, @avelad, I'd like a little help here, if you can.
When I load my manifest in your demo player, a `GET` request is done, as you can see below:

![image](https://github.com/shaka-project/shaka-player/assets/10497009/d8a09136-1781-4e19-8926-4cffeab2bf94)

https://shaka-player-demo.appspot.com/demo/#audiolang=fr-FR;textlang=fr-FR;uilang=fr-FR;asset=https://amg01074-fueltv-netgem.amagi.tv/playlist/amg01074-fueltv-netgem/ad15140a-8f80-11ee-89ab-3a7f5f935650/27/1920x1080_6503200/index.m3u8;license=https://dev-vodapi.videofutur.fr/apirest/drm/licenseApplication?token=GCmkQphA8QAMeDKT3f1Qw76ewof2Ggu8KZSXriCTQJWt9oMY%2FV3yIQ%3D%3D&drm=widevine;panel=HOME;build=uncompiled;vv

But in my own app, it's a `HEAD` request:

![image](https://github.com/shaka-project/shaka-player/assets/10497009/1d695340-2ddc-49be-a81f-60e0cc4f4b3e)

What's the explanation?

**Comment by Robloche** [comment]
Thanks.
I'm using the latest version of the player (v4.6.3).

**Comment by avelad** [comment]
The difference is that when you provide the master playlist, since we have all the information, we only need to make a HEAD to obtain the contentType, but when you provide a half playlist we have to obtain all the information, so we download the entire segment.

**Comment by Robloche** [comment]
OK, I understand the "why", but now, I need to make it work. 😄 

I also found this issue which is very similar to mine:
https://github.com/shaka-project/shaka-player/issues/3142

And from what I read, it led to a PR that was merged 2 years ago.
But the code has changed a bit since that day.
And now, when the `HEAD` request fails, it seems like the execution simply stops instead of going through `guessMimeTypeFallback_()` and fallback-ing to `mp4`.

Shouldn't `const response = await this.makeNetworkRequest_(headRequest, requestType, {type});` be inside a try/catch?

**Comment by avelad** [comment]
@Robloche I created https://github.com/shaka-project/shaka-player/pull/5964 to fix it

**Comment by Robloche** [comment]
Wow, that was fast!
Thanks a lot.

**Comment by Robloche** [comment]
Sorry to re-open this issue but it seems like the same behavior is needed here as well:
https://github.com/shaka-project/shaka-player/blob/7fd99b7c2663903f3fa3991acfbab3782ddb0e07/lib/net/networking_utils.js#L23-L41

I indeed have another case where the playlist itself doesn't have any extension, and redirects to a a `.m3u8` file.
In this case, a `HEAD` request is made, which fails.

**Comment by avelad** [comment]
@Robloche I created https://github.com/shaka-project/shaka-player/pull/5986 to fix it

**Comment by Robloche** [comment]
Thank you so much.
