### ISSUE TITLE
TTML Displaying ok with alignments and position but no colors.

### ISSUE THREAD

**Issue by erwan-guy-brossier-wiztivi** [shaka-project/shaka-player#5968]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.6

**Please ask your question**
Hello,

I'm trying to display Hearing Impaired subtitles in the TTML format.
The subtitles are correctly position with left, center, right alignment and move to the middle of the screen when credits are displayed at the end of the episode.
However some HI Cues ("Someone knocking at the door") should be displayed in red but they are not.
I tested the TTML with oonatools and they are displayed correctly in red.

I'm using Shaka 4.3.6 without the UI, i'm using player.addTextTrack() to add the subtitles.
Do I need to add some pluggins to display colors ?
Maybe i'm not using the correct parameters for addTextTrack() ?

**Comment by erwan-guy-brossier-wiztivi** [comment]
Hi thanks for the quick answer.

Loading shaka like the basic usage in the demo 

```
const video = document.createElement("video");
const player = new shaka.Player(video)
await player.load(manifestUri)
```
Not using the setVideoContainer, i assumed using the video element in the constructor served the same purpose.

Here is a sample of the TTML we're using, it's copy paste from the network request made by shaka we don't have the source files.
[sample_ttml.txt](https://github.com/shaka-project/shaka-player/files/13524698/sample_ttml.txt)

**Comment by avelad** [comment]
I saw that we had some problems mapping some colors that are used in TTML, I created https://github.com/shaka-project/shaka-player/pull/5970 to solve it.

I have also seen that in Chrome when we use VTTCue with colors, the browser ignores the color information. So I recommend using `UITextDisplayer`, to use it you have to call `player.setVideoContainer` before `player.load`.
