### ISSUE TITLE
Can I Use One DRM Session for Multiple Streams in Shaka Player?

### ISSUE THREAD

**Issue by JoakimCarlsson** [shaka-project/shaka-player#5993]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.6.1

**Please ask your question**

I'm working on a project where I use multiple Shaka Players to play different streams simultaneously. My aim is to minimize DRM lookups by reusing DRM session metadata across these players and streams.

Currently, I've implemented a system where the DRM session metadata is stored and successfully reused for the same stream on player reload. This avoids additional DRM lookups effectively. However, when I load a different stream in a new player instance, the player initiates a new DRM lookup. Here's a snippet of my implementation:

```JS
if (storedSessionsString){
    var storedSessions = JSON.parse(storedSessionsString);
    storedSessions.forEach(session => {
        if (session.initData) {
            session.initData = this.fromBase64(session.initData);
        }
    });
    
    this.player.configure({
        drm: {
            persistentSessionOnlinePlayback: true,
            persistentSessionsMetadata: storedSessions ? storedSessions : null
        }
    });
}

private fromBase64(base64) {
    let binary_string = window.atob(base64);
    let len = binary_string.length;
    let bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
}
```

I am wondering if it's possible to extend this functionality to reuse the same DRM session metadata for different streams across multiple Shaka Player instances? If so, how can this be achieved?

**Comment by avelad** [comment]
It can be done if all the streams have the same pssh, but this would add a security gap in your project, because if someone capture a key, that key is valid for all your streams.

Does this solve your question?

**Comment by avelad** [comment]
Please send two streams and the license server to `shaka-player-maintainers@googlegroups.com` so we can see what is happening. However, I must mention that starting tomorrow I'm taking vacation and won't be back until January, so it's possible that I won't be able to test it today.

**Comment by JoakimCarlsson** [comment]
@avelad I'm sorry, but I can't share the streams.
Do you have anything in mind that I could possibly try?

**Comment by avelad** [comment]
I would have to investigate and put traces in https://github.com/shaka-project/shaka-player/blob/main/lib/media/drm_engine.js but I'm not sure where.

Without being able to provide some test streams I can't help you more.

Sorry...
