### ISSUE TITLE
How I can get version browsers limit of Shaka Player ( v4.6.3 )

### ISSUE THREAD

**Issue by nhutuan99** [shaka-project/shaka-player#5999]
I just can get infomation of version IOS and Safari with this link : https://shaka-player-demo.appspot.com/docs/api/tutorial-upgrade.html

![image_2023_12_07T03_03_50_232Z](https://github.com/shaka-project/shaka-player/assets/66738885/8a50d91a-039b-43da-a5dd-aa4e1eddd48e)

Thank you

@shaka-bot

**Comment by avelad** [comment]
We currently do not have this information and we do not know it for sure, but here is what should be supported:

- WebOS 3.0+
- Tizen 2.4+
- All Xbox One and Xbox Series S|X
- Chrome 38+
- Edge Chromium all versions.
- Edge legacy all versions.
- Safari 9+
- PlayStation 4 and 5
- Chromecast all versions
- Firefox 42+
