### ISSUE TITLE
CastReceiver VTT Subtitles relative vertical alignment

### ISSUE THREAD

**Issue by denys-pavlenko-deltatre** [shaka-project/shaka-player#6006]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**

shaka-player 4.3.4

**Can you reproduce the issue with our latest release version?**
yes, with the latest CAF

**Can you reproduce the issue with the latest code from `main`?**
not applicable

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
not applicable

**What browser and OS are you using?**
CAST SDK CAF Version: 3.0.0111 which has shaka-player 4.3.4 under the hood. CC 3rd gen

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast 3rd gen

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Trying to play a video with all possible styles of VTT subtitles 

**What did you expect to happen?**
Subtitles with relative position should be displayed according to the percentages. subtitles with line:50% should be at the center of the screen, 75% on 3/4 of the screen, etc

**What actually happened?**

I'm experiencing the issue with vertical alignment in % on Chromecast Receiver(CAST SDK CAF Version: 3.0.0111 which has shaka-player 4.3.4 under the hood). So 0% working fine, but then every percent moving the position too much lower which end up 14% being at the very bottom of the screen. Do you have any idea if it's fixable and/or on your radars? TIA
![2023-11-10 09 16 51](https://github.com/shaka-project/shaka-player/assets/103035700/55e9a4c3-d619-4baf-8276-dc48f10f61a4)
![2023-11-10 09 17 00](https://github.com/shaka-project/shaka-player/assets/103035700/db0dcdad-e110-4420-b154-fc378b922f93)
![2023-11-10 09 16 38](https://github.com/shaka-project/shaka-player/assets/103035700/20eeaf7a-efd1-4ff9-96aa-5386f68a9438)
![2023-11-10 09 16 56](https://github.com/shaka-project/shaka-player/assets/103035700/29c21a7f-6e18-48e2-9f6d-0ba26fe62dbe)
![2023-11-10 09 16 41](https://github.com/shaka-project/shaka-player/assets/103035700/61c1adb8-1244-40bc-8369-d30f2753d42e)
![2023-11-10 09 16 47](https://github.com/shaka-project/shaka-player/assets/103035700/b0c6e038-4f96-428d-b486-aedbcebb409a)
![2023-11-10 09 16 44](https://github.com/shaka-project/shaka-player/assets/103035700/6233078e-17f9-4e57-ae2f-f30e7c14e71d)

**Comment by avelad** [comment]
Since the problem is in the CAF framework, I recommend that you use their support: https://developers.google.com/cast/support

Sorry
