### ISSUE TITLE
Subtitle appearing twice

### ISSUE THREAD

**Issue by davidmagine** [shaka-project/shaka-player#6007]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

not related

**What version of Shaka Player are you using?**

4.7.0

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
not applicable

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
not applicable

**What browser and OS are you using?**
LG WebOS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG model 55UK6400PLF, webOS 4.4.2-11 and a few other LG model tv and webOS versions

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Play a video with subtitle

**What did you expect to happen?**
Only one line of subtitle to appear

**What actually happened?**

Occasionally the subtitle will appear twice at different position
Video
https://github.com/shaka-project/shaka-player/assets/119855296/b8038fcb-dacb-45ea-a6c3-333fe59537f1
Image
![image](https://github.com/shaka-project/shaka-player/assets/119855296/f5dd4f30-7f03-4f4f-817a-029fbe4ac4de)
VTT subtitle files (segments 37 and 38)
[vtt.zip](https://github.com/shaka-project/shaka-player/files/13633543/vtt.zip)

**Comment by avelad** [comment]
@davidmagine are you using `UITextDisplayer` or `SimpleTextDisplayer`? in the player, are you calling to `setVideoContainer`?
