### ISSUE TITLE
Insufficient error test

### ISSUE THREAD

**Issue by Robloche** [shaka-project/shaka-player#6016]
Following PR https://github.com/shaka-project/shaka-player/pull/5986, I found a new edge case.

When the `HEAD` method is not authorized, the server returns a `404`  status code, ending up as the following error:
![image](https://github.com/shaka-project/shaka-player/assets/10497009/76960c11-b7ed-4657-acd9-85b006ee8ba7)

The error code is `1001`, whereas `shaka.util.Error.Code.HTTP_ERROR` is `1002`.
Hence, the `GET` request is never done.

I think the test should be:
```js
    if (error && (error.code == shaka.util.Error.Code.HTTP_ERROR || error.code == shaka.util.Error.Code.BAD_HTTP_STATUS)) {
      request.method = 'GET';
      const response = await netEngine.request(type, request).promise;
      mimeType = response.headers['content-type'];
    }
```

And the same change should be done in `lib/hls/hls_parser.js` as well.

What do you think, @avelad?

**Comment by avelad** [comment]
@Robloche Is it normal behavior that if the HEAD method is not supported it returns a 404?

**Comment by Robloche** [comment]
No, you're right. Unsupported method should cause a `405` status.
But one cannot expect all servers to be properly configured, don't you think so?

**Comment by avelad** [comment]
You have convinced me, I will be happy to approve your PR to change it.

**Comment by Robloche** [comment]
Glad to read it! 😄

**Comment by Robloche** [comment]
PR https://github.com/shaka-project/shaka-player/pull/6044
