### ISSUE TITLE
Player stalls when changing audio language (Windows Edge + DASH + PlayReady)

### ISSUE THREAD

**Issue by reece-white** [shaka-project/shaka-player#6025]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.7.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Windows Edge (Chromium)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
Demo player test asset `https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest.mpd`

`https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest.mpd;panel=ALL_CONTENT;panelData=drm:PLAYREADY;build=uncompiled`

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default demo player config

**What did you do?**

1. Navigate to `https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest.mpd;panel=ALL_CONTENT;panelData=drm:PLAYREADY;build=uncompiled` on Windows Edge
2. Play asset
3. Change audio language

**What did you expect to happen?**
Audio language transitions smoothly

**What actually happened?**
Audio language changes but the player framerate drops and stutters.

**Comment by avelad** [comment]
Can you test if the problem persists with the main branch? Thanks!
