### ISSUE TITLE
UI interactivity is using the wrong event listeners - really bad experience for mobile

### ISSUE THREAD

**Issue by MarianoFacundoArch** [shaka-project/shaka-player#6027]
With customUI, I noticed the following problems:

When controls were hidden, and I am on iOS or Android, I try to scroll down (player is on an iframe), but instead, the event is cancelled and the UI controls are shown. That is not intended, the intended behavior in that case is to respond to the scroll event. I imagine the wrong event listener is being used.

The other problem is with the tapToSeek, when it is enabled, the scrolling when scrolling from the laterals is blocked, so had to disable the entire feature.

I guess the UI is using the wrong event listeners.

**Comment by avelad** [comment]
@MarianoFacundoArch partial fix https://github.com/shaka-project/shaka-player/pull/6050

**Comment by avelad** [comment]
Can you share a minimal code to reproduce the issue? Thanks!
