### ISSUE TITLE
"Undetermined" text track in safari - hls ?

### ISSUE THREAD

**Issue by MarianoFacundoArch** [shaka-project/shaka-player#6028]
![image](https://github.com/shaka-project/shaka-player/assets/19694461/1032f21f-1ce9-475d-b070-7ae1795c986c)
I see an "undetermined" text track in the ui, even there is only one text track I add with addtexttrackasync.

**Comment by avelad** [comment]
It seems that Apple analyzes the video segments and detects some available CC and automatically put the "bad" track. You can see more information here: https://developer.apple.com/library/archive/qa/qa1801/_index.html

I recommend declaring the absence of subtitle content in the playlist by specifying CLOSED-CAPTIONS=NONE in the EXT-X-STREAM-INF tag.

Info from https://github.com/shaka-project/shaka-player/issues/5782
