### ISSUE TITLE
6010: ENCRYPTED_CONTENT_WITHOUT_DRM_INFO on Comcast X1 Due to Safari Blocklist on Shaka 4.6.5

### ISSUE THREAD

**Issue by Vasanthavanan-Devarajan** [shaka-project/shaka-player#6029]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?** 
 No it's not related to Fairplay DRM

**What version of Shaka Player are you using?**  
4.6.5

**Can you reproduce the issue with our latest release version?** 
Yes it's even reproduced with 4.7.0

**Can you reproduce the issue with the latest code from `main`?** 
Yes

**Are you using the demo app or your own custom app?** 
Yes

**If custom app, can you reproduce the issue using our demo app?** 
NA

**What browser and OS are you using?**
Device has Safari Version 8

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Comcast X1 infinity Setup Box 

**What are the manifest and license server URIs?**
NA

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default

**What did you do?**

Started (DASH+Widevine) Stream on the Comcast device, getting  6010 - ENCRYPTED_CONTENT_WITHOUT_DRM_INFO	

**What did you expect to happen?**
Playback has to work without any issues. 

**What actually happened?**

In our production environment, we're currently utilizing Shaka Player version 4.3.7 and are in the process of upgrading to version 4.6.5. However, we've encountered a playback issue specific to the `Comcast X1 Infinity set-top box`.

Upon investigating, we discovered that the media source support in Shaka Player is unexpectedly marked as `null`. This issue seems to stem from a recent change in Shaka Player's handling of Safari browser versions 
(refer to PR: https://github.com/shaka-project/shaka-player/pull/5752). 

Shaka Player now blocklists Safari versions below 10. The User Agent for Comcast's setup, which is 
`Mozilla/5.0 (Linux; x86_64 GNU/Linux) AppleWebKit/601.1 (KHTML, like Gecko) Version/8.0 Safari/601.1 WPE`, is being identified as an older Safari version (Safari 8), leading to the media source being set to null. This, in turn, triggers the player to incorrectly handle `srcEquals`, resulting in the `ENCRYPTED_CONTENT_WITHOUT_DRM_INFO` error.

The relevant code references are:

Media Source Polyfill: [Shaka Player Media Source Polyfill](https://github.com/shaka-project/shaka-player/blob/8649e7ebbdb173d70741ec5e7400bbcbf2019710/lib/polyfill/mediasource.js#L43)
Platform Utilities: [Shaka Player Platform Utilities](https://github.com/shaka-project/shaka-player/blob/8649e7ebbdb173d70741ec5e7400bbcbf2019710/lib/util/platform.js#L233)
For further context, here are older PRs related to this issue:

[PR #2798](https://github.com/shaka-project/shaka-player/pull/2798)
[PR #2801](https://github.com/shaka-project/shaka-player/pull/2801)
We have developed a fix for this issue on our end, confirming successful playback. We plan to submit a PR with our solution.

**Comment by Vasanthavanan-Devarajan** [comment]
PR has been raised for the above: https://github.com/shaka-project/shaka-player/pull/6034. 
CC: @avelad

**Comment by avelad** [comment]
Fixed with https://github.com/shaka-project/shaka-player/pull/6034
