### ISSUE TITLE
Player gets reinitialised on error 

### ISSUE THREAD

**Issue by neerajgulati-airtel** [shaka-project/shaka-player#6030]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
No

**What version of Shaka Player are you using?**
4.7.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo 

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
MacOS version: 13.5.2 (22G91)
Chip: Apple M1 Pro
Chrome Version: 117.0.5938.132

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
Sharing in mail

**What did you do?**
Once we encounter an error in playback, the player reinitialises itself automatically. This has occurred in 4.7.1 release only and is not reproducible in older version

Steps:
1) Using the manifest url shared in mail, start the playback.
2) Add an event listener to check when play init happens. I used the below code in dev tools
   2.a) Selected video tag in dev tools
   2.b) Add $0.addEventListener('loadstart', (e) => {debugger; console.log("===>started")}); in console and press enter.
            $0 represents the currently selected element in dev tools
3) Seek to 35:05. At 35:10 the playback fails in shaka player for which already a ticket is open vide ticket https://github.com/shaka-project/shaka-player/issues/5692
What has started happening now is that at 35:10 when an error is encountered player gets reinitialised and loadstart is fired again. Though the playback doesn't work

We create  a new play session on every loadstart and this additional loadstart event in case of error  is causing issues in tracking
**What did you expect to happen?**
Even in case of error. The loadstart flow shouldn't have been triggerd

**What actually happened?**
The player gets reinitialised

<img width="1509" alt="image" src="https://github.com/shaka-project/shaka-player/assets/120081455/27fa7a31-59a4-4ea6-912d-da44484b2976">

**Comment by avelad** [comment]
This is configurable, you can set it to: `streaming.allowMediaSourceRecoveries`. See: https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.StreamingConfiguration
