### ISSUE TITLE
Filter track variants by resolution

### ISSUE THREAD

**Issue by kwinso** [shaka-project/shaka-player#6031]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
`4.7.1`

**Please ask your question**
How can I filter out track variants? I only need "good" resolutions like `1080`, `720` and other popular resolutions, but I don't need resolutions like `432`. How can I filter out tracks by this criteria given that I cannot control manifest, so this must be done on clientside. On top of that, I also need ABR manager to filter out those "bad" resolutions. How can I achieve such behaviour?

**Comment by avelad** [comment]
To do this you can configure restrictions, see https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.PlayerConfiguration
You can configure them at the ABR level to be soft if you wish.

**Comment by kwinso** [comment]
I think it's what I need. But the configuration suggests setting min and max height (so I can tell this to be from 144 to 1080, but I can't filter out something like `432` since it matches height range), but how can I list the exact values I want to be shown?

**Comment by avelad** [comment]
You can filter by a maximum and minimum value, you cannot filter specific qualities. If you need filter specific qualities, I recommend you create a custom ABR manager.

**Comment by kwinso** [comment]
Ok, maybe that's the only way. Anyway, thanks for the help!
