### ISSUE TITLE
Is there any way to make subtitle's background color to transparant?

### ISSUE THREAD

**Issue by baobao-jane** [shaka-project/shaka-player#6033]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.7.1

**Please ask your question**
I am using Shaka Player in a Next.js environment. 
I'm currently trying to remove the background color of the subtitles, but the following CSS style doesn't seem to apply the background color

```
video::-webkit-media-text-track-display {
  position: absolute;
  background-color: transparent !important;
  overflow: hidden;
  white-space: pre-wrap;
  flex: 0 0 auto;
  border-radius: 8px !important;
  top: 85% !important;
}
```

Could you please help me understand why the background color is not being applied? Any assistance would be greatly appreciated.

**Comment by avelad** [comment]
In which browser do you want to make the changes? What type of stream do you use (HLS, DASH, MSS)? What subtitle format?

Thanks!

**Comment by avelad** [comment]
The best you can do is use SimpleTextDisplayer which is used by not calling `setVideoContainer`. This means that the subtitle is always rendered by the browser, so it can be customized with CSS.

On how to change the CSS style there are multiple open questions on stackoverflow, for example: https://stackoverflow.com/questions/32252337/how-to-style-text-tracks-in-html5-video-via-css

My recommendation is that if you have access to the subtitle files, change the style in the WebVTT file itself.
