### ISSUE TITLE
how to add a thumbnail feature for custom seek bar in React js

### ISSUE THREAD

**Issue by pluvd7j** [shaka-project/shaka-player#6038]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?*Yes*

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?*Yes*

**What version of Shaka Player are you using?*4.5.0*

**Please ask your question**
How to add a seek bar thumbnail feature for the custom seek bar. Any sample code is there?

**Comment by pluvd7j** [comment]
@avelad can you please share the sample code if you have

**Comment by absidue** [comment]
@pluvd7j Just look at how shaka-player's UI does it, the code is in this repository.

**Comment by pluvd7j** [comment]
@absidue Can you mention the file name please

**Comment by avelad** [comment]
The code is in https://github.com/shaka-project/shaka-player/blob/main/ui/seek_bar.js

**Comment by pluvd7j** [comment]
In my case while doing forward or rewind with the custom button I want to show thumbnails. How can I achieve that in React js

I'm using this code for Forward

`const handleForward = () => {
    const videoElement = document.getElementById('shakaPlayer')
    videoElement.currentTime = videoElement?.currentTime + 10;
  }`
