### ISSUE TITLE
UI: Audio track selector and quality selector should use the same logic to group variants into audio tracks

### ISSUE THREAD

**Issue by absidue** [shaka-project/shaka-player#6039]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

The quality selector doesn't currently respect the `trackLabelFormat` (it only filters by language) or the `showAudioChannelCountVariants` (it always filters by channel count) UI settings. This means that disabling `showAudioChannelCountVariants` hides the audio track selector, but doesn't add those variants to the quality selector. It also means that if you have multiple audio tracks in the same language, but with different roles and labels (e.g. audio descriptions), they will all show up in the quality selector, despite the audio track selector treating them as different tracks.

**Describe the solution you'd like**

The logic to group variants into audio tracks should be unified across the audio track selector and quality selector, that way they can properly work side by side.

**Describe alternatives you've considered**

Building my own audio track selector and quality selector components.

**Additional context**

n/a

**Comment by avelad** [comment]
@absidue I don't understand your problem very well, could you give an example with a playlist and what you would expect to be shown in each case? Thanks!

**Comment by absidue** [comment]
I'll try explaining it better in text, until I get round to modifying some of the demo files so that they can act as test cases for this.

The behaviours are most noticable with audio only manifests (it happpens with audio + video ones too, but you can't see the issue as obviously in the UI)

## `showAudioChannelCountVariants`
When you have a manifest with both stereo and surround audio tracks and have `showAudioChannelCountVariants` set to `true`, the audio track selector shows up, allowing you to switch between stereo and surround, the quality selector only shows varients with the same channel count as the currently active varient.

However when `showAudioChannelCountVariants` is set to `false` the audio track selector disappears, because it now sees the variants as the same audio track, the quality selector however still only shows variants with the same channel count as the currently active variant. This results in some variants being completely inaccessible in the UI.

## `trackLabelFormat`
For this case assume we have a manifest with multiple audio tracks in the same language but different roles (e.g. `main` and `description`). When `trackLabelFormat` is set to `ROLE`, `LANGUAGE_ROLE` (or `LABEL` if you have labels), the audio track selector shows up, allowing you to switch between the `main` and `description`. The quality selector however doesn't respect the `trackLabelFormat` setting and only ever filters by language, so in this case it sees both variants as belonging to the same audio track and lists them as different qualities.

Hopefully this clears stuff up a bit.

**Comment by avelad** [comment]
@absidue I created https://github.com/shaka-project/shaka-player/pull/6069, can you review it? Thanks!

**Comment by absidue** [comment]
That you, that solves the `showAudioChannelCountVariants` issue.
