### ISSUE TITLE
Impact of disabling autoCorrectDrift for DASH manifest

### ISSUE THREAD

**Issue by PradeepK17** [shaka-project/shaka-player#6058]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.11

**Please ask your question**
ShakaPlayer calculates presentationStartTime based on explicit segment endTime to account drift caused by encoders which is causing computed presentationStartTime to fall few seconds behind or ahead of actual availabiltyStartTime present in the manifest. Disabling autoCorrectDrift gives presentationStartTime equal to availabiltyStartTime. Does disabling autoCorrectDrift have any impact in playback?

**Comment by joeyparrish** [comment]
According to [the docs for that option](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.DashManifestConfiguration):

> If `true`, ignore the `availabilityStartTime` in the manifest and instead use the segments to determine the live edge. This allows us to play streams that have a lot of drift.
> **If `false`, we can't play content where the manifest specifies segments in the future.**

Does this answer your question?
