### ISSUE TITLE
Muting/unmuting ads won't affect video and vice versa

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#6071]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not related

**What version of Shaka Player are you using?**

4.7.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Doesn't seem to matter. WIndows, Chrome for example, but seems to be browser independent. 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not related

**What are the manifest and license server URIs?**

Demo app is good, VMAP ad tags from https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Play video with ads

**What did you expect to happen?**
When ads/video start muted and I unmute ad/video, I expect video/ad to be unmuted also. 
When ads/video start with sound and I mute ad/video, I expect video/ad to be muted also. 

**What actually happened?**

Muting / unmuting applies only to currently playing media. Next elements (video, other ads) are not affected. 

For example: 
- when video starts muted and I have midroll with three ads and I unmute the first ad, other two ads and proceeding video will remain muted. 
- when I have preroll, starting with sound and I mute the preroll, video will still continue with sound
- etc

**Comment by avelad** [comment]
@Andekas PR to fix it: https://github.com/shaka-project/shaka-player/pull/6073
