### ISSUE TITLE
preload is not a function

### ISSUE THREAD

**Issue by shigristudy** [shaka-project/shaka-player#6077]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Not Related to fairplay

**What version of Shaka Player are you using?**
v4.7 (latest)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
No

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome Linux

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

I'm using shaka player to create a website like tiktok.

so far everything is good.
I want to preload next video but from shaka player documentation is see preload function in new API.

but when i try to load next video source with preload function i get 

`Video.vue:113 Uncaught (in promise) TypeError: player.value.preload is not a function
    at shakaPlayerInit (Video.vue:113:16)
`

`const shakaPlayerInit = async () => {
  player.value = new shaka.Player();
  player.value.attach(video.value) 

  player.value.preload(nextFeed.value.src_m3u8)

  player.value.configure({
    streaming: {
      segmentPrefetchLimit: 5,
    },
    abr: {
      restrictions: {
        minWidth: 481
      },
      defaultBandwidthEstimate: 4000000
    }
  });

  console.log(player.value.getConfiguration())
  player.value
    .load(post.value.src_m3u8)
    .then(() => {})
    .catch(onError);
}`

**Comment by avelad** [comment]
It's not implemented yet: https://github.com/shaka-project/shaka-player/pull/5897

**Comment by shigristudy** [comment]
when this feature will be available?

**Comment by avelad** [comment]
You can track the issue at https://github.com/shaka-project/shaka-player/issues/880
