### ISSUE TITLE
sourceURL overriding BaseURL even after init ranges are initialized

### ISSUE THREAD

**Issue by chadacious** [shaka-project/shaka-player#6091]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

4.7.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**
Yes 

**What browser and OS are you using?**
Chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

https://pastebin.com/raw/0YSvSgUG

Here is the relevant section of the manifest:
```
      <Representation aspectRatio="37:20" bandwidth="1"
        codecs="avc1.4D401F" frameRate="24000/1001" height="520" id="video=1500000" sar="481:480"
        scanType="progressive" trackName="avc1.4D401F_1500000" width="960">
        <BaseURL>/interstitial/2/5691511/video_9.mp4</BaseURL>
        <SegmentBase timescale="96000" indexRange="7512-7735">
          <Initialization range="7736-8451" sourceURL="video_init.mp4" />
          <RepresentationIndex range="7512-7735" sourceURL="video_init.mp4" />
        </SegmentBase>
      </Representation>
```
Notice the BaseURL contains the fmp4 video file, and the Initialization and RepresentationIndex have the init file.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

https://pastebin.com/raw/LMExcnPB

**What did you do?**

Loading the mainfest and fails to play

**What did you expect to happen?**
I expected that once the init range was read from the video_init.mp4 specified in the sourceURL, that it would then load segments from the video_9.mp4 specified in the BaseURL.

**What actually happened?**

The init segment ranges are read, but then shaka continues trying to read the video segments from the init file and not switch back to the one specified in the BaseURL.

I would expect that if the sourceURL is provided for Initiatialization and RepresentationIndex, that once the init ranges are read, it would no longer use the sourceURL to read fpm4 data from and instead revert back to the BaseURL

**Comment by avelad** [comment]
Can you put the spec where indicates that this should in that way? Thanks!

**Comment by chadacious** [comment]
Yes of course, a necessary and appropriate question. You can refer to the following sections of the MPEG-DASH standard (ISO/IEC 23009-1):

- Section 5.3.9.2 "BaseURL": This section explains the role of the BaseURL element. It defines the BaseURL as a location that provides the base URL for resolving other relative URLs within the DASH manifest. It's intended for segment downloads.
- Section 5.3.9.4 "Initialization" and Section 5.3.9.6 "RepresentationIndex": These sections detail the Initialization and RepresentationIndex elements, which may include a sourceURL attribute. The sourceURL is specifically for the initialization segment and the index segment, not for the media segments.
- Section 5.3.9 "SegmentBase": This section provides an overview of the SegmentBase element, which indicates that a Representation consists of a single segment and defines how to access this segment. The SegmentBase element itself doesn't specify the media content's location but defines how to access it, particularly for the initialization and index segments.

In the DASH specification, the distinct roles of the BaseURL and sourceURL are clear: the BaseURL is used for accessing the media segments, while the sourceURL within Initialization and RepresentationIndex elements is used for accessing specific metadata and index information for setting up the stream. The Shaka Player is using the sourceURL for segment downloads instead of the BaseURL, and is a deviation from these specifications from my interpretation of the DASH spec.

**Comment by avelad** [comment]
Ok, then in that case, do you want to send a PR to fix this?. The problem should be fixable at: https://github.com/shaka-project/shaka-player/blob/main/lib/dash/segment_base.js#L243

I will be happy to review your PR and the tests you have added.

One question, is your stream working correctly with [dash.if](https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html)?

**Comment by chadacious** [comment]
It works correctly with video.js. Yeah, I've been meaning to get to a PR. Hoping to start on it soon.

**Comment by avelad** [comment]
@chadacious are you planning send the PR? Thanks!

**Comment by chadacious** [comment]
Yes, we have a working fork for our purposes. Of course, as startups typically go, we are struggling to find time to prepare the PR. But thanks for the reminder. Will try to get to that soon.

**Comment by avelad** [comment]
@chadacious any update? Thanks!
