### ISSUE TITLE
How can I always show controls and seek bars and make them updated even when mouse pointer is not hovering over them?

### ISSUE THREAD

**Issue by lechatthecat** [shaka-project/shaka-player#6098]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.7.4

**Please ask your question**
I want to show controls always aside the video (and always show seek bar on the video). So I googled and checked this question:
https://github.com/shaka-project/shaka-player/issues/2550
So I started using shaka-player.ui.js and changed css to always show the controls. (Controls are moved to outside the video by css because it was hard to read depending on the background color. Only seek bar is on the video.)

But the problem is that the current "time and duration" and the current point of seek bar are not updated when mouse cursor is not hovering on the video element. How can I make them always shown and updated?

**Comment by absidue** [comment]
Instead of messing with the CSS, you can probably just set the UI `fadeDelay` setting to a really big number.

**Comment by lechatthecat** [comment]
Thank you, it worked.

**Comment by lechatthecat** [comment]
Although I guess it would be helpful if there is an option to prevent the fading out, thank you very much for your help.
