### ISSUE TITLE
How to start the ABR mode at lowest resolution

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#6099]
Hello,

I am using Shaka version 4.6.3, my stream has resolution 360, 480, 720, 1080p.

My player is now alway start playing at the highest resolution (1080p) when I set abr.enabled = true.
What is want to alway start playing at the lowest (360). I already tried to set abr.defaultBandwidthEstimate = 400000 but this does not works.

Is there a way on Shaka to handle this?
Thank you.

**Comment by vanminhquangtri** [comment]
Thanks @avelad , it seem useNetworkInformation make shaka alway play the lowest resolution. It not automatically switch to higher resolution when my network stronger.

**Comment by avelad** [comment]
I have tried the demo with the Sintel stream and in my case it works correctly with this configuration, does this case work well for you?

**Comment by vanminhquangtri** [comment]
Can you please send me the demo of Sintel that you tried @avelad ?

**Comment by avelad** [comment]
https://shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;useNetworkInformation=false;uilang=es-ES;asset=https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd;panel=ALL_CONTENT;build=uncompiled
