### ISSUE TITLE
Live2Vod contents playback issue

### ISSUE THREAD

**Issue by zangi-dev** [shaka-project/shaka-player#6101]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.3.5

**Please ask your question**

we are encountering issues with Live2Vod contents stuttering/flashing while streaming at content playback launch. 
if you skip a few frames forward or restart the event the issue looks to resolve itself.

This problem has been observed on the following devices:
Device Google Chromecast 4K with Android TV
Player Shaka v 4.3.5
OS - Android 13
This issue is mainly observable on GoogleTV Chromecast 4K, but please take in count that it can be also replicate in a less evident way also on other platforms (e.g. Chromecast casting from ios or android application, LG smarttv application)

about the contents generation workflow.

We have a cluster of elemental encoder, but for a single profile, we use one single encoder to publish the content on two different Publishing Endpoint on two different Live Origins.
Then no sync issue on source side because the encoder is the same.
Live Origins (1 and 2) have the same configuration and the same live archive (4days).
Live Origin 1 is used for live streaming.
Live Origin 2 is used to generate capture using Unified tools installed on RMP and triggered by external WF manager.

the issue seems to be related to the frame_accurate options used during the l2v capturing process. When the --frame_accurate option is used, Unified Capture transcodes the first and last fragments of a clip to allow for sample accurate timing.

we identified differences between the streams generated using frame accurate.
Following two contents generated using capture unified tool with and without frameccurate option.
We analyze them using ffmprobe tool and what can be observed is that the stream structure for the two cases is different.
FRAME ACCURATE OFF
https://vod.rte.ie/vod-d/RTE_Test_-_Integration/937/280/IH10002380-24-0001/IH10002380-24-0001-1704193591844_nodrm.ism/.mpd
ffprobe -i "https://vod.rte.ie/vod-d/RTE_Test_-_Integration/937/280/IH10002380-24-0001/IH10002380-24-0001-1704193591844_nodrm.ism/.mpd" -show_frames -select_streams v:5 | grep "pict_type" >> /tmp/struct_frame_accurate_off.txt
all GOPs have IBBPBBP scructure
[FRAME]
key_frame=1
pkt_pts=24
pkt_pts_time=0.040000
pkt_dts=24
pkt_dts_time=0.040000
pict_type=I
coded_picture_number=0
[/FRAME]
[FRAME]
key_frame=0
pkt_pts=48
pkt_pts_time=0.080000
pkt_dts=48
pkt_dts_time=0.080000
pict_type=B
coded_picture_number=2
[/FRAME]
[FRAME]
key_frame=0
pkt_pts=72
pkt_pts_time=0.120000
pkt_dts=72
pkt_dts_time=0.120000
pict_type=B
coded_picture_number=3
[/FRAME]
[FRAME]
key_frame=0
pkt_pts=96
pkt_pts_time=0.160000
pkt_dts=96
pkt_dts_time=0.160000
pict_type=P
coded_picture_number=1
[/FRAME]
FRAME ACCURATE ON
https://vod.rte.ie/vod-d/RTE_Test_-_Integration/655/424/IP10000879-01-0014/IP10000879-01-0014-1686931010344_nodrm.ism/.mpd
ffprobe -i "https://vod.rte.ie/vod-d/RTE_Test_-_Integration/655/424/IP10000879-01-0014/IP10000879-01-0014-1686931010344_nodrm.ism/.mpd" -show_frames -select_streams v:5 | grep "pict_type" >> /tmp/struct_fram_accurate_on.txt
(only) the first GOP is composed by only from I and P frames with different dts and pts
the others have IBBP scructure as expected
[FRAME]
key_frame=1
pkt_pts=24
pkt_pts_time=0.040000
pkt_dts=0
pkt_dts_time=0.000000
pict_type=I
coded_picture_number=0
[/FRAME]
[FRAME]
key_frame=0
pkt_pts=48
pkt_pts_time=0.080000
pkt_dts=24
pkt_dts_time=0.040000
pict_type=P
coded_picture_number=1
[/FRAME]
[FRAME]
key_frame=0
pkt_pts=72
pkt_pts_time=0.120000
pkt_dts=48
pkt_dts_time=0.080000
pict_type=P
coded_picture_number=2
[/FRAME]
[FRAME]
key_frame=0
pkt_pts=96
pkt_pts_time=0.160000
pkt_dts=72
pkt_dts_time=0.120000
pict_type=P
coded_picture_number=3
[/FRAME]

summarizing, it seems that, when the frame_accurate option is used, the structure of the first GOP is slight different and it could cause the stuttering issue reported. do you have any suggestions how we can solve or mitigate this issue on client side? following the current shakaplayer configuration used on client side. 

these are the configurations passed by us:
AD_MIME_TYPES: ['dash', 'hls', 'mp4'],
SHAKA_DRM_TYPES: ['com.widevine.alpha'],
SHAKA_CONFIG_STREAMING: {
    bufferingGoal: 15,
    rebufferingGoal: 5,
    retryParameters: { baseDelay: 2000, maxAttempts: 1, backoffFactor: 1, timeout: 40000, fuzzFactor: 0 },
  },
SHAKA_RETRY_CONFIG_MANIFEST: {
    maxAttempts: 3,
    baseDelay: 2000,
    backoffFactor: 1,
    fuzzFactor: 0
  },

frameaccurate ON content:
https://vod.rte.ie/vod-d/RTE_Test_-_Integration/655/424/IP10000879-01-0014/IP10000879-01-0014-1686931010344.ism/.mpd

frameaccurate OFF content:
https://vod.rte.ie/vod-d/RTE_Test_-_Integration/937/280/IH10002380-24-0001/IH10002380-24-0001-1704193591844_nodrm.ism/.mpd

**Comment by avelad** [comment]
From what you say, it seems that the problem is in the decoding, which in this case is handled by the browser and not by us. Since it is not a problem with the generated manifest but with the segment itself, I cannot be of more help to you... sorry

**Comment by zangi-dev** [comment]
Any way to process and manage the first GOP frames prior to send them to the decoder?

Thanks!
