### ISSUE TITLE
DRM videos fail to play on Firefox for Android

### ISSUE THREAD

**Issue by wjywbs** [shaka-project/shaka-player#6111]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
N/A

**What version of Shaka Player are you using?**
4.7.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not Tested

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Firefox 121.1.0
Android 11
Pixel 2

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
Sintel on https://shaka-player-demo.appspot.com/

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
Open https://shaka-player-demo.appspot.com/ on Firefox for Android, and play Sintel on the home page.

**What did you expect to happen?**
The video plays.

**What actually happened?**
The video fails to play.

```
MediaCapabilities: Native mediaCapabilities support found. [log.js:142:50](https://shaka-player-demo.appspot.com/lib/debug/log.js)
EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. [index.js:52:13](https://shaka-player-demo.appspot.com/node_modules/eme-encryption-scheme-polyfill/index.js)
McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. [index.js:255:13](https://shaka-player-demo.appspot.com/node_modules/eme-encryption-scheme-polyfill/index.js)
EmeEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support. [index.js:96:13](https://shaka-player-demo.appspot.com/node_modules/eme-encryption-scheme-polyfill/index.js)

Object { severity: 2, category: 7, code: 7003, handled: false, message: "Shaka Error PLAYER.OBJECT_DESTROYED ()"
```

Note that video.js can play this video.

**Comment by avelad** [comment]
@wjywbs are you interested on send a PR to fix it?

**Comment by avelad** [comment]
I can reproduce the error

**Comment by avelad** [comment]
@wjywbs Can you try to disable `streaming.allowMediaSourceRecoveries`? Could you tell me the new result after that change.

**Comment by wjywbs** [comment]
The new error is `Object { severity: 2, category: 3, code: 3016, message: "Shaka Error MEDIA.VIDEO_ERROR (3,,NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - Error creating decoder for audio/opus)"`.

video.js plays h264 and aac.

**Comment by avelad** [comment]
Sintel works in the unencrypted version. So it seems that Firefox Android does not support Opus+Widevine correctly.
