### ISSUE TITLE
Best methods to implement Multi Audio + Multi Subtitle for DASH stream

### ISSUE THREAD

**Issue by whatever1211** [shaka-project/shaka-player#6129]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes, we have.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, we have.

**What version of Shaka Player are you using?**
Version 3.3.19.

**What browser and OS are you using?**
Windows - Chrome OS.

**Please ask your question**
What is the best methods to implement Multi Audio + Multi Subtitle for DASH stream?

Here is our current try:
1. Update Audio track + Subtitle track list by listen to trackschanged event.
2. Select Audio track + Subtitle track
Audio track: selectAudioLanguage()
Subtitle track: selectTextLanguage()
3. Update Audio track + Subtitle track value by listen to variantchanged event.

Can Shaka team help us review our events and methods use. Does this implementation cable to cover all stream cases?

If able, what is Shaka team recommend events and methods used to implement Multi Audio + Multi Subtitle streams?

Thanks,

**Comment by avelad** [comment]
The best is listen `trackschanged`, `textchanged`, `texttrackvisibility` and `variantchanged` to check the active variant or texttrack and get all tracks updated. To select the audio you can use selectAudioLanguage and to select the subtitle you can use selectTextLanguage-

**Comment by whatever1211** [comment]
Thank you @avelad,
Can you help us more specific of 4 events `trackschanged`, `textchanged`, `texttrackvisibility` and `variantchanged`.
What events trigger when track lists (resolution/audio/subtitle) updated?
What events trigger when active variant (resolution/audio/subtitle) updated?
Regards,

**Comment by avelad** [comment]
> What events trigger when track lists (resolution/audio/subtitle) updated?

`trackschanged` 

>  What events trigger when active variant (resolution/audio/subtitle) updated?

`variantchanged`, `adaptation`, `textchanged`, `texttrackvisibility`

**Comment by whatever1211** [comment]
Pefect! That is exactly what we needed. Thank you @avelad for your kind support.
