### ISSUE TITLE
Client side ads not playing in iOS fullscreen

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#6133]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not related

**What version of Shaka Player are you using?**

Latest, 4.7.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
iOS - Chrome, Safari, Firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

For content, any (demo) URL is good. 

For ads I used Google IMA VMAP sample tags ( https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags ) 

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Try to play video with ads

**What did you expect to happen?**
Ads and video to play

**What actually happened?**

Ads work great when player is not in fullscreen. 

On fullscreen, no ads are displayed. When going to fullscreen during an ad (rotating the device to landscape), the ad sound keeps playing but main video is visible (paused). If ad(s) end, video starts playing.

**Comment by avelad** [comment]
Are you interested in finding and create a PR to fix the error? Thanks!

**Comment by Andekas** [comment]
@avelad I'm afraid that I'm not that familiar with Apple devices. As I use Win/Android, it would be really difficult to debug also...

**Comment by avelad** [comment]
The fullscreen API is not available on iOS (https://caniuse.com/fullscreen) so we use the fullscreen API of the video element itself and it produces this behavior.
I see two solutions:
- Disable the full screen button in browsers that do not support the fullscreen API and are using IMA CS.
- When an ad is going to be played, exit fullscreen, and disable the fullscreen button during the ad, the problem is that we cannot return to fullscreen afterwards because a user action is necessary.

Which solution do you like best? (You probably won't like any...)

**Comment by Andekas** [comment]
@avelad Thanks for looking it up! 

I guess that the best solution would be to disable the fullscreen button / rotation during the ads, if fullscreen API is not supported. 

In this case user is forces to see at least preroll. And if he goes to fullscreen after preroll and doesn't get any midrolls, it's acceptable. Exiting fullscreen to display ads is a really bad user experience, I would say.

**Comment by avelad** [comment]
@theodab What do you think?

**Comment by PradeepK17** [comment]
@Andekas @avelad Please look this [blog - IMA iOS10+ customPlayback](https://ads-developers.googleblog.com/2017/06/new-custom-playback-apis-for-ima-html5.html). It may provide insights on how to address the problem.
