### ISSUE TITLE
Client side ads not visible on iPad Chrome

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#6134]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not related

**What version of Shaka Player are you using?**

Latest, 4.7.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
iPad OS Chrome (everything works on iPad OS Safari)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

For content, any (demo) URL is good. 

For ads I used Google IMA VMAP sample tags ( https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags ) 

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Try to play video with ads

**What did you expect to happen?**
Ads and video to play

**What actually happened?**

Ads won't play, video plays good.

**Comment by avelad** [comment]
Are you interested in finding and create a PR to fix the error? Thanks!

**Comment by Andekas** [comment]
@avelad I'm afraid that I'm not that familiar with Apple devices. As I use Win/Android, it would be really difficult to debug also...

**Comment by Andekas** [comment]
@avelad It wasn't related, because ads weren't displaying at all (even when video wasn't on fullscreen). 

I tested it again with two iPads (iPadAir iPadOS 17.1.1 and iPad mini 2 OS 12.5.7) and now everything works (both fullscreen and not). So maybe it was Chrome bug and fixed in some new version. 

I close the issue and re-open it if I am able to reproduce it again.
