### ISSUE TITLE
Issue with FairPlay DRM and PatchedMediaKeysApple Installation

### ISSUE THREAD

**Issue by baobao-jane** [shaka-project/shaka-player#6140]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** yes

**If the problem is related to FairPlay, have you read the tutorial?**
yes

**What version of Shaka Player are you using?**
4.7.6

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
own custom app

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
macOS 14.1.1 / safari

When playing HLS files using FairPlay DRM and installing PatchedMediaKeysApple with shaka.polyfill.PatchedMediaKeysApple.install();, the issue arises when executing shaka.util.FairPlayUtils.defaultGetContentId. When the initDataTypes is "skd" and the value contains "/", it is interpreted as a path. Consequently, only the portion before "/" is used as contentId, leading to authentication failure.

```
initDataTransform: function (
  h: ArrayBuffer | ArrayBufferView,
  k: ArrayBuffer | ArrayBufferView | string,
  l: ArrayBuffer | ArrayBufferView | null,
) {
  if ('skd' == k && l) {
    //@ts-ignore
    const k = l.serverCertificate;
    const url = shaka.util.StringUtils.fromBytesAutoDetect(h);
    const contentId = url.substring(url.indexOf('skd://') + 6);
    h = shaka.util.FairPlayUtils.initDataTransform(h, contentId, k);
  }
  return h;
},
```

Configuring to execute the above function within player.configure resolves the issue, enabling proper license authentication and file playback. However, it seems that the problem of recognizing "/" as a path needs to be addressed.

**Comment by avelad** [comment]
Are you interested in submitting a PR to fix this? Thanks!

**Comment by avelad** [comment]
The implementation of this function depends on your DRM provider, by default we have the one provided by Apple in its SDK, if a provider changes it (there are many that change it), you have to customize the function as you have done. This is really not a bug.
