### ISSUE TITLE
Issue on Shaka-Player Demo

### ISSUE THREAD

**Issue by mrshulk** [shaka-project/shaka-player#6158]
**If the problem is related to FairPlay, have you read the tutorial?**
I don't think so

**What version of Shaka Player are you using?**
latest version online

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
-

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**
-

**What browser and OS are you using?**
linux ubuntu

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
web

**What are the manifest and license server URIs?**
-

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
NONE

**What did you do?**
Just added assetKey "c-rArva4ShKVIAkNfy6HUQ" from Google DAI

**What did you expect to happen?**

**What actually happened?**
After few minutes when video running on shaka-player test website show up this error PLAYER OBJECT DESTROYED,
I've been using the Big Buck Bunny assetkey from Google DAI (c-rArva4ShKVIAkNfy6HUQ), usually show ups after 01:45min

![image](https://github.com/shaka-project/shaka-player/assets/134942986/87f470b0-1a06-47db-af73-6bc1d45c52ff)

**Comment by mrshulk** [comment]
I've been testing the version "4.7.6" so I can see this error as well.

![2024-01-24_14-58](https://github.com/shaka-project/shaka-player/assets/134942986/e2cd54b0-ae82-471f-9d4d-8a02e13dff0d)

**Comment by avelad** [comment]
With 4.7.7 (released a few hours ago), the issue is fixed or i cannot reproduce the issue with that version.
