### ISSUE TITLE
Wrong aspect ratio on some videos on Win Chrome

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#6168]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not related

**What version of Shaka Player are you using?**

Tested with 4.7.7, 4.7.5, nightly.  

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Windows, Chrome and Edge

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

This doesn't happen to all videos, but one with the problem is: 

https://router.euddn.net/f79adceedc96855c1c045be3ab05a542/smil:8301/2023/12/29/y2mate.com_OLLIE_My_Friend_Eesti_Laul_2024_1440p_cmiaBpcG/play_hd.smil/playlist.m3u8?c=8000 

Demo URL: https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://router.euddn.net/f79adceedc96855c1c045be3ab05a542/smil:8301/2023/12/29/y2mate.com_OLLIE_My_Friend_Eesti_Laul_2024_1440p_cmiaBpcG/play_hd.smil/playlist.m3u8?c=8000;panel=CUSTOM%20CONTENT;build=debug_compiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Play the video

**What did you expect to happen?**
Video to play with correct aspect ratio

**What actually happened?**

Video plays, but is streched to 16:9 AR. 

This problem occurs with Windows Chrome and Edge. Aspect ratio is correct with Windows FireFox and Android Chrome. Haven't tested with other browsers/devices. 

When using 4.3.3, aspect ratio is correct in Win Chrome also.

**Comment by avelad** [comment]
Info from Chrome debugger

![Captura de pantalla 2024-01-26 a las 11 18 48](https://github.com/shaka-project/shaka-player/assets/8983024/7390233e-3fc0-47aa-9ce1-eeb15cc320e3)

**Comment by Andekas** [comment]
And both of these aspect ratios are wrong; should be 2594x1080

Player 4.3.x shows correct info: https://v4-3-13-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://router.euddn.net/f79adceedc96855c1c045be3ab05a542/smil:8301/2023/12/29/y2mate.com_OLLIE_My_Friend_Eesti_Laul_2024_1440p_cmiaBpcG/play_hd.smil/playlist.m3u8?c=8000;panel=CUSTOM%20CONTENT;build=uncompiled 

![image](https://github.com/shaka-project/shaka-player/assets/885095/3648fde6-c85d-470a-92cb-a1f79ec3da3c)

**Comment by avelad** [comment]
In the new transmuxer it seems that we are not implementing the box pasp, I am still doing a little research.

**Comment by avelad** [comment]
PR to fix it: https://github.com/shaka-project/shaka-player/pull/6170

**Comment by Andekas** [comment]
@avelad Thanks, seems to work perfectly!
