### ISSUE TITLE
Dash Live stream not updating and playback stop

### ISSUE THREAD

**Issue by Iragne** [shaka-project/shaka-player#6185]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

we tested it on 4.6.11 4.7.7 and the bug is here, it's working on 4.5.0 and previous version

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes
**Are you using the demo app or your own custom app?**
Yes the demo app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Chrome and FF

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Standard configuration 

**What did you do?**

Play a linear stream with minimumUpdatePeriod="PT0S" 

**What did you expect to happen?**
Linear stream to play

**What actually happened?**

the playback start and stop to be updated, no manifest get fetch/updated

**Comment by Iragne** [comment]
We investigate in the issue and it appear to be that PR who cause the issue https://github.com/shaka-project/shaka-player/pull/5823
By reverting it back to this
if (this.updatePeriod_ < 0) {
Everything work as expected 

I can confirm that my manifest get minimumUpdatePeriod="PT0S"

**Comment by Iragne** [comment]
The issue maybe introduce by that thread here https://github.com/Dash-Industry-Forum/Guidelines-TimingModel/issues/48
But reading it, it's not meaning that we should stop updating the manifest, it's saying that the manifest is no more valid when it get fetch and a future update is needed later on

**Comment by Iragne** [comment]
[avelad](https://github.com/avelad) let me know your thoughts ?

**Comment by avelad** [comment]
I would be happy to review your PR
