### ISSUE TITLE
Cannot build v4.7.8 (can build v4.7.7)

### ISSUE THREAD

**Issue by radiantmediaplayer** [shaka-project/shaka-player#6195]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Y

**If the problem is related to FairPlay, have you read the tutorial?**
N

**What version of Shaka Player are you using?**
4.7.8

**Can you reproduce the issue with our latest release version?**
Y

**Can you reproduce the issue with the latest code from `main`?**
N/A

**Are you using the demo app or your own custom app?**
N/A

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
N/A

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
N/A

**What did you do?**
I am trying to build v4.7.8 of shaka player but I am getting an error at build time:
[ERROR] Unable to find file: C:\wamp64\www\shaka-player\lib\polcd
I am using the command for building 
python build/build.py +@ads +@cea +@core +@dash +@hls +@networking  +@offline +@text +@transmuxer +./node_modules/eme-encryption-scheme-polyfill/index.js +./lib/polyfill/abort_controller.js +./lib/polyfill/encryption_scheme.js +./lib/polyfill/mediasource.js +./lib/polyfill/media_capabilities.js +./lib/polyfill/patchedmediakeys_nop.js +./lib/polyfill/patchedmediakeys_webkit.js  +./lib/polyfill/random_uuid.js +./lib/polcd shyfill/storage_estimate.js +./lib/polyfill/symbol.js +./lib/polyfill/videoplaybackquality.js +./lib/polyfill/vttcue.js

If I switch to v4.7.7 I can build with the same command without issue. I can reproduce the issue on Windows 11 and Linux Ubuntu 18.04 systems.

**What did you expect to happen?**
Shaka player to build successfully 

**What actually happened?**
An error is preventing build 
[ERROR] Unable to find file: C:\wamp64\www\shaka-player\lib\polcd

**Comment by avelad** [comment]
Hi @radiantmediaplayer, you have a typo in you command:
python build/build.py +@ads +@CEA +@core +@Dash +@hls +@networking +@offline +@text +@transmuxer +./node_modules/eme-encryption-scheme-polyfill/index.js +./lib/polyfill/abort_controller.js +./lib/polyfill/encryption_scheme.js +./lib/polyfill/mediasource.js +./lib/polyfill/media_capabilities.js +./lib/polyfill/patchedmediakeys_nop.js +./lib/polyfill/patchedmediakeys_webkit.js +./lib/polyfill/random_uuid.js +./lib/polcd shyfill/storage_estimate.js +./lib/polyfill/symbol.js +./lib/polyfill/videoplaybackquality.js +./lib/polyfill/vttcue.js

Should be:
python build/build.py +@ads +@CEA +@core +@Dash +@hls +@networking +@offline +@text +@transmuxer +./node_modules/eme-encryption-scheme-polyfill/index.js +./lib/polyfill/abort_controller.js +./lib/polyfill/encryption_scheme.js +./lib/polyfill/mediasource.js +./lib/polyfill/media_capabilities.js +./lib/polyfill/patchedmediakeys_nop.js +./lib/polyfill/patchedmediakeys_webkit.js +./lib/polyfill/random_uuid.js +./lib/**polyfill**/storage_estimate.js +./lib/polyfill/symbol.js +./lib/polyfill/videoplaybackquality.js +./lib/polyfill/vttcue.js

**Comment by radiantmediaplayer** [comment]
Yes this is a typo indeed on our side. I apologise, this one is on me. Thanks for taking the time to look into it.
