### ISSUE TITLE
ADD mpegts support 

### ISSUE THREAD

**Issue by iptvsmartws** [shaka-project/shaka-player#6196]
Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
YES

Is your feature request related to a problem? Please describe.
Yes, it is related to a problem. I am currently trying to play an MPEG-TS live stream, but it seems that Shaka Player supports only HLS and DASH formats. This limitation restricts the usage of Shaka Player in environments where MPEG-TS streams are prevalent.

Describe the solution you'd like
I would like Shaka Player to include support for MPEG-TS streams. This would involve enabling the player to handle MPEG-TS container formats and potentially adapt to the different streaming protocols and codecs used in MPEG-TS compared to HLS and DASH. The ideal solution would allow seamless playback of MPEG-TS live streams, just as it currently does with HLS and DASH streams.

Describe alternatives you've considered
One alternative solution I have considered is using a different media player that supports MPEG-TS. However, this is not ideal as it requires integrating and maintaining multiple media players for different formats. Another alternative is transcoding MPEG-TS streams to HLS or DASH on the server side, but this adds additional complexity and resource requirements to the streaming process.

Additional context
The addition of MPEG-TS support in Shaka Player would significantly enhance its utility in various streaming scenarios, particularly for live broadcasting. Many broadcast systems and cameras natively output MPEG-TS streams, and having direct support in Shaka Player would simplify the workflow and reduce the need for format conversion. This feature would be highly beneficial for developers and content providers who work with a mix of HLS, DASH, and MPEG-TS streams.

**Comment by avelad** [comment]
Currently I don't think we can support this functionality. There is not enough community demand to support this.

If you want a player that fully supports this I recommend: https://github.com/xqq/mpegts.js

Sorry!

**Comment by iptvsmartws** [comment]
> Currently I don't think we can support this functionality. There is not enough community demand to support this.
> 
> If you want a player that fully supports this I recommend: https://github.com/xqq/mpegts.js
> 
> Sorry!

Already using this, no support for ac3 Audio

**Comment by avelad** [comment]
Looking at the project code, it seems that they do support AC-3 (https://github.com/xqq/mpegts.js/blob/master/src/demux/ac3.ts)
