### ISSUE TITLE
Delay to show the image (Black Screen) + DRM

### ISSUE THREAD

**Issue by mrshulk** [shaka-project/shaka-player#6200]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**
Yes

**What version of Shaka Player are you using?**
4.7.7

**What browser and OS are you using?**
Linux + Uuntu

**Please ask your question**
Hi guys, I have an issue here, when I start the video using DRM with FairPlay it takes a few seconds to show the image, in the Shaka Player demo this doesn't happen. Has anyone ever experienced this? If yes, how to resolve it?

https://drive.google.com/file/d/1p3yPXPVD1f6KszBRPJyx5m2tK9WFQvvJ/view?usp=drive_link

**Comment by avelad** [comment]
I leave the question open to see if anyone in the community also experiences this.
