### ISSUE TITLE
I have random issues with HLS + Fairplay in Safari

### ISSUE THREAD

**Issue by adgllorente** [shaka-project/shaka-player#6215]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**If the question is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**

4.3.13

**What browser and OS are you using?**

Safari 17.3 in MacOS Sonoma 14.3 (M1) but it fails with Intel and M2 processors too.

**Please ask your question**

I have a weird situation with HLS + Fairplay in Safari and I do not know what else can I do to find a solution.

The situation happens randomly while playing HLS + Fairplay streams. I launch one stream, then close the player, then launch another one and at some point, playback crashes with a 6010 error (ENCRYPTED_CONTENT_WITHOUT_DRM_INFO).

I also see these logs in the console:

> [Log] PatchedMediaKeysApple.requestMediaKeySystemAccess
> [Log] PatchedMediaKeysApple.MediaKeySystemAccess
> [Log] PatchedMediaKeysApple.requestMediaKeySystemAccess
> [Log] PatchedMediaKeysApple.MediaKeySystemAccess
> [Log] PatchedMediaKeysApple.requestMediaKeySystemAccess
> [Log] PatchedMediaKeysApple.MediaKeySystemAccess
> [Log] PatchedMediaKeysApple.requestMediaKeySystemAccess
> [Log] PatchedMediaKeysApple.MediaKeySystemAccess
> [Log] PatchedMediaKeysApple.requestMediaKeySystemAccess
> [Log] PatchedMediaKeysApple.MediaKeySystemAccess
> [Log] PatchedMediaKeysApple.requestMediaKeySystemAccess
> [Log] PatchedMediaKeysApple.MediaKeySystemAccess
> [Log] PatchedMediaKeysApple.requestMediaKeySystemAccess
> [Log] PatchedMediaKeysApple.MediaKeySystemAccess
> [Log] PatchedMediaKeysApple.requestMediaKeySystemAccess
> [Log] PatchedMediaKeysApple.MediaKeySystemAccess
> [Info] navigator.requestMediaKeySystemAccess failed. (x8)

What is weird is that if I launch the playback again on the same stream, it works perfectly.

I have thought, the CDM is getting blocked at some point and it fails, but if I give enough time to be released, it works again.

Do you have any idea to find a solution? Do you know any extension or log level to debug the problem?

As you can see, I am just looking for some light with this problem 😊

Thanks!

**Comment by joeyparrish** [comment]
I don't know much about Fairplay.  @avelad does, but he is on leave.  I'll assign the question to him for when he returns.  If anyone else reading this has any insights, all comments are welcome!

**Comment by avelad** [comment]
I haven't seen this problem recently, in the past I did see it. I see that you are using a slightly old branch, could you try with 4.7.10 and the main branch and see if the same thing happens? Could you use Modern EME instead of the legacy version? Thanks!
