### ISSUE TITLE
Playback with shaka player gets stuck on QuotaExceededError

### ISSUE THREAD

**Issue by vtarasov-goog** [shaka-project/shaka-player#6217]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes. There is a related https://github.com/shaka-project/shaka-player/issues/1352, but that doesn't cover the playback being broken in case of QuotaExceededError.

**If the problem is related to FairPlay, have you read the tutorial?**
N/A

**What version of Shaka Player are you using?**
v4.7.9 (uncompiled)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
Demo player at https://shaka-player-demo.appspot.com

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
* Pixel 6a, Android 14, UQ1A.240205.00
* Chrome 121.0.6167.143

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
* https://storage.googleapis.com/wvmedia/clear/vp9/tears/tears_uhd.mpd
* The content is unencrypted, no license server needed.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
* Use Android device with 6GB RAM or less
* Open https://shaka-player-demo.appspot.com in Chrome
* Create "custom content" with https://storage.googleapis.com/wvmedia/clear/vp9/tears/tears_uhd.mpd as manifest URL.

**What did you expect to happen?**
* Entire video plays OK.

**What actually happened?**
* Video playback gets stuck after about 10 seconds.
* Console contains the following error messages:
```
(video:2) MediaSource threw QuotaExceededError: reducing buffering goals by 20%
...
(video:2) MediaSource threw QuotaExceededError: reducing buffering goals by 96%
No alternate stream found for active video stream. Will ignore request to disable stream...
(video:2) MediaSource threw QuotaExceededError too many times
```

**Comment by joeyparrish** [comment]
The segments are just fundamentally too large.  There is only one stream, with 4k content only.  I think your issue is that the content is unrealistic.  With realistic content, you would be able to choose a lower resolution and play something that fits the screen and the device memory better.
