### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by slushpuppy** [shaka-project/shaka-player#6218]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.7.9

**What browser and OS are you using?**
firefox, windows 11

**Please ask your question**
Hi, I am wondering if there is first in class support for typescript for this project

**Comment by theodab** [comment]
Not currently. See #1030

**Comment by slushpuppy** [comment]
thanks
