### ISSUE TITLE
HD Video Freeze after SD License Load with DRM - Fairplay

### ISSUE THREAD

**Issue by mrshulk** [shaka-project/shaka-player#6229]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Yes

**What version of Shaka Player are you using?**
4.7.7

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo App + Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Linux + ubuntu

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
None

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
I configured Fairplay, in my manifest it starts with the video in SD and after a few seconds, depending on the quality of the internet, it switches to the HD video version. The SD video starts normally. I didn't use any extra options in player_.configure (just DRM for fairplay)

```
player.getNetworkingEngine().registerRequestFilter((type, request, context) => {
  if (type != shaka.net.NetworkingEngine.RequestType.LICENSE) {
    return;
  }

  const originalPayload = new Uint8Array(request.body);
  const base64Payload =
      shaka.util.Uint8ArrayUtils.toStandardBase64(originalPayload);
  const params = 'spc=' + encodeURIComponent(base64Payload);
  request.headers['Content-Type'] = 'application/x-www-form-urlencoded';
  request.body = shaka.util.StringUtils.toUTF8(params);
});
```

**What did you expect to happen?**
Shaka Player update itself the license between SD and HD automatically when is requested HD video and no stall.

**What actually happened?**
Fairplay - I request the SD video first to load quickly with DRM settings, and it works well. However, a few seconds later, when Shaka Player attempts to request the HD video, image stalls (audio keep running) because the license from the SD version is different from the HD version and won't update. I've tried using 'player.getNetworkingEngine().registerRequestFilter' to force an update of the license auto, but it didn't work.

**Comment by mrshulk** [comment]
other thing I tried as well was to send a new player.configure() without success

I taken this piece of code from this reply of @joeyparrish (https://github.com/shaka-project/shaka-player/issues/4827#issuecomment-1370249386)

```
player_.getNetworkingEngine().registerResponseFilter((type, response) => {

if (type != shaka.net.NetworkingEngine.RequestType.MANIFEST ||
response.originalUri != player_.getAssetUri()) {
// Not the master playlist.  Ignore it.
return;
}

const text = shaka.util.StringUtils.fromUTF8(response.data);
// Do something with the text, and call player.configure() with an appropriate config.
});
```

**Comment by mrshulk** [comment]
[Update 1] - On the Shaka Player demo, I observed the same behavior: if it starts with an SD video and switches to an HD video after a few seconds, the video stalls (this change happens automatically). If it doesn't switch and remains in SD quality, it keeps running.

[Update 2] - It seems to me that after a few minutes, Shaka Player automatically reverts to the SD version, making it work again because the main key provided was for SD

**Comment by avelad** [comment]
@mrshulk In order to help you, we need you to share the stream with the license server and the FairPlay certificate so we can test and see what is happening. Thank you!
