### ISSUE TITLE
Using buffer visualizer

### ISSUE THREAD

**Issue by Andekas** [shaka-project/shaka-player#6230]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Not related

**What version of Shaka Player are you using?**
Latest

**What browser and OS are you using?**
Win, Chrome

**Please ask your question**
In Shaka demo page, there is a really nice buffer visualizer. Is there any tutorial, how to implement it in own Shaka player instance also?

**Comment by theodab** [comment]
It's not built into Shaka Player, no. It's part of the demo app, and the button that opens it is a custom button (see the [UI customization tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html) for how to make custom buttons). You could try copying the code for the visualizer into your test app, I guess.

The visualizer code: https://github.com/shaka-project/shaka-player/blob/main/demo/visualizer.js
You'll probably want to replace the demo's `BoolInput` class with just an html input, if you still want that auto-screenshot toggle field. And removing the `goog.provide` and `goog.require` file management stuff at the top, probably.
It is meant to be associated with these DOM elements: https://github.com/shaka-project/shaka-player/blob/36b7367ebd3efafd6e46d8ef74758cd834aff224/demo/index.html#L134-L138

**Comment by Andekas** [comment]
Thanks! I think it would be a good debug info to add in our backend. I'll try it out if I have some spare time.
