### ISSUE TITLE
Small `MediaSource.remove()` intervals causing crashes on Cast platforms.

### ISSUE THREAD

**Issue by JulianDomingo** [shaka-project/shaka-player#6240]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

v4.7.x

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app (PlutoTV)

**If custom app, can you reproduce the issue using our demo app?**
N/A (cast-related)

**What browser and OS are you using?**
Chrome / Cast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Chromecast Ultra

**What are the manifest and license server URIs?**

N/A (Load any VOD or live stream on the PlutoTV production app).

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default shaka config.

**What did you do?**

1. Open PlutoTV app, cast any live or VOD stream.

**What did you expect to happen?**
1. Open PlutoTV app, cast any live or VOD stream.
2. Shaka should continue to play the media.

**What actually happened?**

1. Open PlutoTV app, cast any live or VOD stream.
2. Observe an app crash after 20-40 minutes of playback.

The issue is very similar to https://github.com/shaka-project/shaka-player/issues/2982. However, the eviction goal is still very small, as Shaka will attempt evictions for intervals as small as `0.01`:
https://github.com/shaka-project/shaka-player/blob/83c02b8a5cfe48e2c028efb3aca6d3fd9026b062/lib/media/streaming_engine.js#L2348-L2358

We've observed this is problematic for Cast platforms, as overflow durations like `0.01084400000002006` are failing downstream checks in the cast MSE implementation:
```
[FATAL:source_buffer_stream.cc] Check failed: IsRangeListSorted(ranges_).
```

It seems reasonable to make the `StreamingEngine`'s eviction goal configurable, and also to set a higher default minimum interval; it doesn't make sense to spend the effort to remove durations of approx. `0.01` seconds. 

The crashes stopped even by increasing this minimum from `0.01` => `0.10`, so the PR will provide a default value of `0.10`.

**Comment by joeyparrish** [comment]
I say increase it to 1.0.  There's not much point in evicting 100ms of content.
