### ISSUE TITLE
Shaka 4.7.0 used in Chromecast throws a codec related error

### ISSUE THREAD

**Issue by TommiRautanen** [shaka-project/shaka-player#6245]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
-

**What version of Shaka Player are you using?**
4.7.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
-

**Are you using the demo app or your own custom app?**
-

**If custom app, can you reproduce the issue using our demo app?**
-

**What browser and OS are you using?**
Chromecast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
-

**What are the manifest and license server URIs?**
-

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
default config

**What did you do?**
Start play dash content

**What did you expect to happen?**
Content should start to play

**What actually happened?**
Content does not start to play, instead following error message is thrown to the console of Chromecast receiver:
<img width="1452" alt="Screenshot 2024-02-13 at 13 27 12" src="https://github.com/shaka-project/shaka-player/assets/99327481/67eb0582-33ad-4d3f-a98b-83ccbfc9202d">

Note that this issue does not happen if I use Shaka 4.3.4 in Chromecast.

**Comment by joeyparrish** [comment]
v4.7.0 is out of date.  Please try v4.7.9, the latest release from that branch.

**Comment by TommiRautanen** [comment]
<img width="1461" alt="Screenshot 2024-02-13 at 21 46 32" src="https://github.com/shaka-project/shaka-player/assets/99327481/b526ce77-f713-4e16-ace8-c65ce607c439">

Unfortunately v4.7.9 gives an error, although a different one..

**Comment by TommiRautanen** [comment]
@avelad unfortunately this is DRM protected stream so you probably won't be able to test it. I'm attaching DASH manifest instead in case you can work around it.
[dash.txt](https://github.com/shaka-project/shaka-player/files/14478004/dash.txt)

**Comment by avelad** [comment]
@theodab can you review if your changed of https://github.com/shaka-project/shaka-player/pull/6348 resolves it? Thanks!

**Comment by TommiRautanen** [comment]
Shaka 4.7.11 gives still same MANIFEST.PERIOD_FLATTENING_FAILED error.

**Comment by avelad** [comment]
@TommiRautanen are you interested on send a PR to fix it? Thanks!

**Comment by avelad** [comment]
`manifest.dash.useStreamOnceInPeriodFlattening = true` is a workaround that allows reproduction without problems

**Comment by TommiRautanen** [comment]
@avelad Shaka 4.7.11 says that it cannot recognize config key you are referring to above?

**Comment by avelad** [comment]
Sorry, `useStreamOnceInPeriodFlattening` is only available in the main branch...

**Comment by avelad** [comment]
Yes because that config will be available in 5.0.0 not earlier, sorry!

**Comment by TommiRautanen** [comment]
But with 4.7.12 I'm not getting `PERIOD_FLATTENING_FAILED` error anymore, has something changed compared to 4.7.11 where error did exist?

**Comment by avelad** [comment]
Since the problem is solved in the main branch, I consider the problem closed.

**Comment by TommiRautanen** [comment]
@avelad I tested Shaka 4.8.1 with HLS TS stream and it does not work. It throws `UNABLE_TO_GUESS_MANIFEST_TYPE` error. Is this perhaps related?
