### ISSUE TITLE
allowCrossSiteCredentials not working in Safari

### ISSUE THREAD

**Issue by sonjoydatta** [shaka-project/shaka-player#6247]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Yes

**What version of Shaka Player are you using?**
4.7.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**
Can't find an option in your demo app.

**What browser and OS are you using?**
Google Chrome, Microsoft Edge, Firefox, Safari, Chrome iOS, Safari iOS / Mac, iPhone

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
'{"abr":{"enabled":true},"manifest":{"dash":{"ignoreMinBufferTime":true}},"streaming":{"useNativeHlsOnSafari":true},"drm":{}}'

**What did you do?**
1. My demo player is on, example.com and used ReactJS
2. Manifest url is from cdn.example.com (it needs a cookie)
3. Enable player cross-side cookie sharing property
```
player.getNetworkingEngine()?.registerRequestFilter((_, request) => {
// optional: check the request type (MANIFEST, SEGMENT, LICENSE)
request.allowCrossSiteCredentials = true;
});
```
5. Cookie is going when player making fetch request for that manifest file from Chrome, Edge and Firefox and video is playing perfectly but, not working for Safari/Mac, Safari/iOS, Chrome/iOS
6. On Safari I found that player making fetch request with **credentials: 'omit'** but use **credentials: 'include'** for Chrome, Edge and Firefox

_Note: I am not using any extensions or anything for the browsers its working. Also, cross-site cookie sharing headers are enabled from server_

**What did you expect to happen?**
I expect **credentials: 'include'** for Safari/Mac, Safari/iOS, Chrome/iOS when `request.allowCrossSiteCredentials = true`

**Comment by joeyparrish** [comment]
@sonjoydatta, can you share what the solution was?  It might help someone in the future to know what you discovered that led you to close the issue right after filing.

**Comment by sonjoydatta** [comment]
> @sonjoydatta, can you share what the solution was? It might help someone in the future to know what you discovered that led you to close the issue right after filing.

@joeyparrish I had a predefined attribute `crossorigin="anonymous"` in code for **HTMLVideoElement**. It was preventing to send back cross-site cookie even with `request.allowCrossSiteCredentials = true`. Safari sets a priority for the cookie based on what user passes in the video element and for Chrome/iOS I find it follows the same set of rules as Safari
