### ISSUE TITLE
[Offline] Expiration time not updated despite Playback_Duration < License_Duration

### ISSUE THREAD

**Issue by loicraux** [shaka-project/shaka-player#6255]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
N/A

**What version of Shaka Player are you using?**
Latest version 4.7.9

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Own custom app.

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**

Chrome in VMP-signed Electron

```json
{
  "electronVersion": "28.1.3",
  "nodeVersion": "18.18.2",
  "chromeVersion": "120.0.6099.199",
  "shakaPlayerVersion": "4.7.7",
  "widevineCDMVersion": "4.10.2710.0",
  "operatingSystem": "Windows_NT x64 10.0.22631"
}
```

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What did you do?**

Our Widevine licenses server proxy is setup to return the following license durations for offline playback (persistent licences) :
- `License_Duration` is set to 30 days (2,592,000 seconds) (License duration starts as soon as the license is acquired as per my understanding)
- `Rental_Duration` is also set to 30 days also (From what I've read on CWIP discussion group, `Rental_Duration` was deprecated in 2016.  Please confirm that it is still deprecated or not).
- `Playback_Duration` is set to 2 days (172,800 seconds) (Playback Duration starts with the first content decryption as per my understanding.  When Playback Duration expires, the license expires, even if the license duration is not yet reached.)

What we eventually want is the user to be able to keep the downloaded content for up to 30 days once it's downloaded but only up to 2 days once it has been played at least once.

Once the content is downloaded thanks to Shaka Player Storage API, the `expiration` field of the `StoredContent` gives a correct time stamp, that is 30 days after the current download date. (this is stored at download time in the `manifest-v5` table of `shaka_offline_db`
indexedDB.)

**What did you expect to happen?**

Now right after the content is played for the first time I would expect this expiration date to be updated so that it expires in 2 days (the Playback Duration).

If I understand well, the DRM engine keeps on polling the EME API to compute an expiration date that might have been updated, since EME does not expose an event for such updates. The update of the expiration time in the stored manifest is already done in Shaka Player code (See [this feature request](https://github.com/shaka-project/shaka-player/issues/727) & [the corresponding commit for implementation](https://github.com/shaka-project/shaka-player/commit/b4d0fa4901bba0dffe43dcd5742f5b331dad7aa7), please correct me if I'm wrong.

**What actually happened?**

If I subscribe to `'expirationupdated'` events sent by the Player, I do get called, but only when the expiration goes from Infinity (uninitialized) to 30 days, I never get called when the expiration should be updated from 30 days to 2 days.

The `expiration` field of the StoredContent (or stored manifest) never gets updated.

**Additional observations**

I don't know if this OK or not, but I have observed that the `session-ids` table of the `shaka_offline_db` database is always empty, no matter what I download.... Is this normal ?

**Comment by loicraux** [comment]
I managed to correct the problem on my side, no problem in Shaka Player's code, which anyway only uses the EME APIs to retrieve and update the license expiration date.

The confusion arose from the fact that our DRM provider (EZDRM) uses the following parameters for license durations (according to https://hs.ezdrm.com/hubfs/Documentation/EZDRM-Universal-License-Delivery-v1.2-1.pdf?hsLang=en):

- `Rental_Duration`
- `License_Duration`
- `Playback_Duration_Seconds`

Note the `_seconds` suffix only for playback duration, whereas the other 2 parameters do not have this suffix.

Widevine servers accept all 3 parameters (https://developers.google.com/widevine/drm/feature/policy):

- `rental_duration_seconds`
- `playback_duration_seconds`
- `license_duration_seconds`

Furthermore, the documentation / slides I received when I took the CWIP training course were not clear and not up to date....

So that it's clear to everyone (because the Widevine docs aren't very clear on this subject I find...), here's my current understanding of these durations :

- `rental_duration_seconds` indicates the rental window. It starts as soon as the license is **acquired.** This duration **runs according to absolute time** (the time on your watch).
- `playback_duration_seconds` indicates the viewing window, once playback has begun. It **starts when you first decrypt,** once playback begins. When playback duration expires, the license expires, even if the rental duration is not yet reached. **I'm not sure whether this duration is based on the time spent viewing the video or on absolute time (on your watch)**.
- `license_duration_seconds` is **DEPRECATED**; It should not be used.

It is not clear to me whether or not Rental Duration can overwrite Playback Duration if earlier.

It would be great if someone from Shaka Player / Widevine could confirm my understanding of these durations ! Thanks !

**Comment by joeyparrish** [comment]
@loicraux, thank you for leaving your detailed findings.  That is very helpful for the community!

As for the questions:

> * `playback_duration_seconds` ...  **I'm not sure whether this duration is based on the time spent viewing the video or on absolute time (on your watch).**
>
> ...
>
> **It is not clear to me whether or not Rental Duration can overwrite Playback Duration if earlier.**

You would have to ask someone at Widevine.  Shaka Player is no longer run by the Widevine team, and my expertise is more with the EME API and less with Widevine policy configuration.

@kqyang, do you know the answer, or can you tag someone who does?  Thanks!

**Comment by joeyparrish** [comment]
> I managed to correct the problem on my side, no problem in Shaka Player's code, which anyway only uses the EME APIs to retrieve and update the license expiration date.

Since there is no problem in Shaka Player, and this isn't the best place for Widevine support, I'm going to go ahead and close this issue.  For your Widevine policy questions, please reach out to Widevine support at https://widevine.com/

Thanks!
