### ISSUE TITLE
Url radio doesn't work on shaka player

### ISSUE THREAD

**Issue by alevator** [shaka-project/shaka-player#6257]
Hi all,

I need support because I have problems to earn my favorite radio

The url is this  https://4c4b867c89244861ac216426883d1ad0.msvdn.net/radiodeejay/radiodeejay/master_ma.m3u8

But doesn't work with Shaka player.
I can play with others players

I have another url of this radio that is working but is not present in tune-in (they using shaka player also) for example 

https://4c4b867c89244861ac216426883d1ad0.msvdn.net/radiodeejay/radiodeejay/master.m3u8

Can you help me to understand why?

I tried a tool demo on shakaplayer website

I am using Chrome

Thank you so much

**Comment by loicraux** [comment]
This manifest (live audio stream) works perfectly in the demo app, in FF and Chrome at least, see https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://4c4b867c89244861ac216426883d1ad0.msvdn.net/radiodeejay/radiodeejay/master_ma.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

**Comment by alevator** [comment]
Hello,

Thank you for your help.

I tried here (https://philcluff.co.uk/players/shaka-player.html) but I think is an old version of the player [Shaka Player v3.3.2
But I don't understand if the issue is related to the version of the player or to the url (and manifest then).

:(

**Comment by loicraux** [comment]
> Hello,
> 
> Thank you for your help.
> 
> I tried here (https://philcluff.co.uk/players/shaka-player.html) but I think is an old version of the player [Shaka Player v3.3.2 But I don't understand if the issue is related to the version of the player or to the url (and manifest then).
> 
> :(

The manifest is perfectly fine, so I guess version 3.3.2 of Shaka Player either had a bug or did not yet support this type of manifest/stream.

**Comment by joeyparrish** [comment]
I'll send Phil a PR to update his site.  But the latest, canonical demo maintained by this community is https://shaka-player-demo.appspot.com/

Since there doesn't seem to be an issue in the latest Shaka Player, I'm going to close this issue.  If you need to reopen this issue, just put `@shaka-bot reopen` in a comment.  Thanks!
