### ISSUE TITLE
In case of Fairplay playback in shaka, how to achieve shaka to make subsequent fairplay license call based in LEASE limited duration

### ISSUE THREAD

**Issue by anandhakarthick** [shaka-project/shaka-player#6280]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)? Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues? Yes

**If the question is related to FairPlay, have you read the tutorial?**. Yes

**What version of Shaka Player are you using?** Latest Shaka

**What browser and OS are you using?** Safari, MAC

**In case of Widevine playback using shaka, if the WV license service backend set the RenewalIntervalSeconds in policy, based on this time, player makes a subsequent renewal call to license server which is working fine & i have validated it. 

Similarly in case of Fairplay, in backend license server , i'm trying to set the contentkey duration as LEASE_ONLY(0x1a4bde7e) or LIMITED(0x18f06048), with a duration of some 60sec..  with this change in backend, the license delivered to shaka is valid only upto 60sec & expected to make subsequent license call to fairplay license service by shaka player , which didn't happened but content continue to play even after 60sec.. 

To achieve this case , if any special tweaks to be done at shaka client end ? kindly suggest. **

**Comment by joeyparrish** [comment]
@avelad, can you answer this one when you are back to work?

**Comment by anandhakarthick** [comment]
Hi @avelad - could you please suggest on this

**Comment by avelad** [comment]
I have no experience with the FairPlay backend and its policies, I know how to implement it on the player side only. I'm sorry! I leave the question open to see if anyone in the community can help.

**Comment by anandhakarthick** [comment]
thank a lot @tykus160  - Will try out with your suggestions
