### ISSUE TITLE
Remove cast button video pause

### ISSUE THREAD

**Issue by fkoemep** [shaka-project/shaka-player#6293]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Whenever I press the cast button, the video always pauses. This does not happen in websites such as YouTube (which is the cast behaviour I'm seeking)

**Describe the solution you'd like**

I would like to have a flag or any other way of avoiding pausing the video when I click the cast button.

**Describe alternatives you've considered**

I though about monkey patching the library locally but it'd be much better to have a native option for this.

**Additional context**

The method `getInitState_()` inside `cast_proxy.js` should be modified so that the video resumes playing after `this.localVideo_.pause();`, or removing that line so the video never pauses.

**Comment by joeyparrish** [comment]
You are welcome to submit a PR for this, but the shaka.cast APIs are slated for removal in v5.0.0.  We will be moving away from custom messaging between sender and receiver and moving cast functionality out of shaka.cast and into the UI.

**Comment by fkoemep** [comment]
Since the API is going to be removed I just ended up creating a monkey-patch that resumes the video after the cast button is pressed, I'm going to leave it here in case anyone needs it.
 ```javascript
//resume video after pausing for casting

const originalCastFunction = shaka.cast.CastProxy.prototype.cast;
const modifiedCastFunction = async function () {
    originalCastFunction.bind(this)();
    ui.getControls().getLocalVideo().play();
};
shaka.cast.CastProxy.prototype.cast = modifiedCastFunction;
 ```
I call it after `player.load();`
