### ISSUE TITLE
"cannot find segment" with HLS and subtitles in a livestream

### ISSUE THREAD

**Issue by mthie** [shaka-project/shaka-player#6299]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**If the problem is related to FairPlay, have you read the tutorial?**
n/a

**What version of Shaka Player are you using?**
4.7.4 and newer

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `main`?**
Yes.

**Are you using the demo app or your own custom app?**
Both.

**If custom app, can you reproduce the issue using our demo app?**
Yes.

**What browser and OS are you using?**
Windows, Linux, Android

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a

**What are the manifest and license server URIs?**
https://watch.contentflow.tv/1d3da1cb-4acd-4baa-b804-28e42e62462c/corporations/E35UT53DI5pzEhDgDLRg/workspaces/h7wpnlhZfMpmGfcJrb2d/outputs/AUTw3INEg9X2CvdD5W6I/index.m3u8

[Demo-Link](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://watch.contentflow.tv/1d3da1cb-4acd-4baa-b804-28e42e62462c/corporations/E35UT53DI5pzEhDgDLRg/workspaces/h7wpnlhZfMpmGfcJrb2d/outputs/AUTw3INEg9X2CvdD5W6I/index.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
No specific configuration.

**What did you do?**
Use an HLS manifest with subtitles with Shaka player.

**What did you expect to happen?**
See a video with subtitles.

**What actually happened?**
The player reports errors (see ![Debug Output Screenshot](https://github.com/shaka-project/shaka-player/assets/167062/d43c4d4f-0fc8-4f6b-9204-3ed4434bb0b0)). It doesn't happen with 4.7.3 and earlier, and is produced by the code from this [Commit](https://github.com/shaka-project/shaka-player/commit/cc1f3dfed75e16ac89f59c3f0e2799262477ac73).

Everything works fine with the same video material without this line in the m3u8 playlist:
`#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="de",DEFAULT=NO,AUTOSELECT=NO,LANGUAGE="de",FORCED="NO",CHARACTERISTICS="public.accessibility.transcribes-spoken-dialog",URI="captions_playlist.m3u8"`

It doesn't matter, whether the `lookupTime` and `presentationTime` are the same values or not (I've tried to sync them). The player doesn't fetch the subtitle playlist, so it can't be an async error between subtitles and the video.

Everything works fine with VODs or with `manifest.hls.ignoreManifestProgramDateTime: true`, but this option is only a workaround. The playlist even works perfectly with hls.js.

**Comment by joeyparrish** [comment]
@avelad, the commit that introduced the regression appears to be one of your fixes from January: https://github.com/shaka-project/shaka-player/pull/6059 to fix https://github.com/shaka-project/shaka-player/issues/5939.  Could you take a look when you have time?

**Comment by avelad** [comment]
@mthie your content is geoblocked

**Comment by mthie** [comment]
No, the stream is offline since yesterday. Give me a few minutes, I start it again.

**Comment by mthie** [comment]
@avelad please have a look again...

**Comment by avelad** [comment]
still not working… sorry

**Comment by mthie** [comment]
Oh, you're right. I removed the Geo-Blocking. Sorry.
