### ISSUE TITLE
"VSF:SHAKA_ERROR__DRM6007.MAIN_CONTENT" Now TV on Linux

### ISSUE THREAD

**Issue by Fiddoodle** [shaka-project/shaka-player#6303]
Apologies if this is not the correct place to ask about this. I am using Firefox on Fedora 39 and when trying to watch content on NOW TV I am getting this error - VSF:SHAKA_ERROR__DRM6007.MAIN_CONTENT. I have the openh264 codec plugin and widevine plugin installed. The video will attempt to load and then throw up this error. I also have playback of DRM content enabled in Firefox. Any help would be appreciated. Thanks!

**Comment by tykus160** [comment]
This is not the best place for this, as NOW TV is not maintained by shaka team.
However, as I have something in common with NOW, I feel like I have an obligation to at least suggest something ;)
AFAIK Firefox installs Widevine CDM by itself if you allow for it, so I'm not sure is any other plugin needed. Try to update Firefox to the latest version first.
If it still doesn't work, maybe try to install Firefox from other source than RPM (like official website).
Unfortunately I don't use Fedora so I'm not able to quickly verify it.

**Comment by joeyparrish** [comment]
You can also check https://shaka-player-demo.appspot.com/support.html in your browser to see if you have Widevine support.  If not, that might explain the problem.

If you see this toward the bottom of the page:

```
    "com.widevine.alpha": {
      "persistentState": true
    }
```

(or presistentState: false), you have Widevine.

If you see this:

```
    "com.widevine.alpha": null
```

then you do not.

If you need any further help, please contact NOW TV.

Thanks!
