### ISSUE TITLE
doesn't work well on Safari with useNativeHlsOnSafari = false

### ISSUE THREAD

**Issue by kuroishi** [shaka-project/shaka-player#6315]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**

4.7.11

**Can you reproduce the issue with our latest release version?**
yes (4.7.11)

**Can you reproduce the issue with the latest code from `main`?**
I don't know.

**Are you using the demo app or your own custom app?**
yes. I use the demo app.
ref.
https://shaka-player-demo.appspot.com/

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Safari 17.1 (19616.2.9.11.7)
macOS Sonoma 14.1.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

e.g.
https://live-par-2-cdn-alt.livepush.io/live/bigbuckbunnyclip/index.m3u8　

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

When useNativeHlsOnSafari is true, it works well but it dosen't with false.

**What did you do?**

Using the manifest above, you can play it on the demo app on Safari. (https://shaka-player-demo.appspot.com/)
The playback will be choppy.

**What did you expect to happen?**
The playback works well.

**What actually happened?**

We hava a custom app too. We found that setting useNativeHlsOnSafari to true the playback works well.
But we can't get the manifest with such setting. It's inconvinient for us to do things we want. We hope that when useNativeHlsOnSafari is false the playback works well on Safari.

**Comment by dostrowski-udemy** [comment]
We are also seeing issues with Safari playback when using useNativeHlsOnSafari: false. The video and audio stutter or stall on playback with non-DRM content on Safari with 4.7.9-4.7.11.

**Comment by avelad** [comment]
> It looks like the same issue is with https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8. It plays as a slideshow in Safari only with useNativeHlsOnSafari = false

Using manifest.hls.useSafariBehaviorForLive = false your manifest works well. I'll investigate why...

**Comment by avelad** [comment]
@kuroishi I can reproduce the same error in Chrome with the main branch

**Comment by avelad** [comment]
It seems that your segments are no independent segments, our transmuxer does not support this case.

**Comment by kuroishi** [comment]
Thanks for your reply.

I believe taht all the segments I give you above as an example are independent segments that don't refer the frames in other segments.

If you confirm no independent segments in my example above, please let me know.

What exactly should I generate as proper segments in terms of such as GOP, I, B, P frame and IDR.

**Comment by MarianoFacundoArch** [comment]
This might be closely related to 
https://github.com/shaka-project/shaka-player/issues/6446
