### ISSUE TITLE
Content Playback Issue with Shaka Player 2.4.0 - Offline Content Playback Error (DOMException: Failed to execute 'load' on 'MediaKeySession': Rejected with system code (72))

### ISSUE THREAD

**Issue by rranjithk** [shaka-project/shaka-player#6316]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
No

**What version of Shaka Player are you using?**
2.4.0

**Are you using the demo app or your own custom app?**
Custom app

**What browser and OS are you using?**
windows 7, 10, 11  and chrome - 108 and 111, electron 27

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
No

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
player.configure({
    drm: {
      servers: { 'com.widevine.alpha': 'https://127.0.0.1:5556/nextdrm/nextdrm/persistentlicense?domain=https://ifp.nexterp.in' },
      advanced: {
        'com.widevine.alpha': {
          'persistentStateRequired': true,
        }
      }
    },
    preferredTextLanguage: 'eng',
    streaming: {
      alwaysStreamText: true,
      ignoreTextStreamFailures: true
    }

  });

Why are we using an old version of Shaka? 
We understand that Shaka Player 2.4.0 is an older version, but our customisation code is intricately tied to it, making an immediate update challenging, Customisation is available while downloading offline licences. Shaka downloads content along with the licence. Since content is available in our discs, we don't want to download the license to resolve download time license and number of request's  

Context:
Our application relies heavily on the ability to save offline licenses to support offline content playback. This functionality was working flawlessly until recently.

Request for Assistance:
Given the critical nature of this issue for our product, we are seeking your expertise to understand if there have been any breaking changes in the Widevine DRM system or Shaka Player that could be causing this problem.

Steps to Reproduce:
Download an offline license.
Attempt to play the content offline with the newly acquired license.
Encounter the "DOMException: Failed to execute 'load' on 'MediaKeySession': Rejected with system code (72)" error.
Additional Information:
We have ruled out any issues with CastLab Electron, as the problem persists with the latest version.
Previously downloaded licenses are still functioning correctly; the issue seems to be isolated to newly acquired licenses.

How Can You Help?
We kindly request your guidance on resolving this issue or any insights into potential changes in the Widevine DRM system that might be affecting Shaka Player 2.4.0's offline license loading.

Please let us know if there are specific logs, details, or steps we can provide to assist in diagnosing and resolving this issue.

**Comment by joeyparrish** [comment]
## Supported Versions

> **Why are we using an old version of Shaka?**
> We understand that Shaka Player 2.4.0 is an older version, but our customisation code is intricately tied to it, making an immediate update challenging

I understand from personal experience over many years how difficult and complex it is to maintain a long-term fork.  I was once employed to maintain a fork of Chromium for exotic platforms that had no business running such a memory-hungry browser.  Every time we had to update to a newer branch of Chromium, every customization had to be redone, at great expense.  It made us never want to update or rebase.

So I definitely get where you're coming from.

However, we can't support a version that is almost 6 years old (2018-05-24), with 2 breaking-change major-version releases in between (v3.0.0 and v4.0.0).  We're even on the threshold of a v5.0.0 some time this year.  We stopped maintaining the v2.4 branch fully 5 years ago (2019-02-19 with v2.4.7).

Our official statement on supported branches is here: https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md

Our branch maintenance policy is here: https://shaka-project.github.io/maintenance/shaka-player.html#branch-maintenance-policy

Each of these docs links to the other.

Again, I know first-hand the difficult place you are in.  We apologize for any inconvenience.  But my team just doesn't have the resources to help you with this.  Perhaps someone from the broader Shaka Player community might have a suggestion for you.

## Widevine Compatibility

To address the other part of your question:

> Given the critical nature of this issue for our product, we are seeking your expertise to understand if there have been any breaking changes in the Widevine DRM system or Shaka Player that could be causing this problem.

Widevine makes periodic changes to the underlying CDM to address content security and other issues.  You could ask Widevine for support on this.

## Widevine System Codes

> Encounter the "DOMException: Failed to execute 'load' on 'MediaKeySession': Rejected with system code (72)" error.

These system codes are the key to understanding Widevine's errors.  If you have access to Widevine's devsite, you can find a list of system codes and their meanings.  (This list is not fully publicly available.)  If you don't have access, please contact Widevine at [widevine.com](https://widevine.com/) and **get** access.  You **need** this info to maintain a Widevine-based product.

From what I can tell with my access to that list, this system code has something to do with the service certificate.  If you aren't setting a service certificate in your application, you should.  **Does this help?**

## Further Support

If you need further support on this issue, I strongly recommend you reach out to Widevine.  At this point, there's nothing more I can do for you on the Shaka Player side of things for three reasons:
  1. You are on a very old version we no longer support
  2. You are on a fork that we are not responsible for at all
  3. Your issue appears to be with Widevine CDM changes, not the player at all (and this project is no longer owned or maintained by Widevine)

I hope this helps.  If you need help making contact with Widevine, I can help you do that.  Just reach out to me via email at my GitHub username at google.com.

Thanks!
