### ISSUE TITLE
How to implement quality change function during IOS native playback

### ISSUE THREAD

**Issue by sorimpower** [shaka-project/shaka-player#6326]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
ok

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
ok

**If the question is related to FairPlay, have you read the tutorial?**

ok

**What version of Shaka Player are you using?**
4.7.9

**What browser and OS are you using?**
 safari on v15.7.9 IOS

**Please ask your question**

Hi~
I'm developing a vod player using shaka
There's a problem with developing the quality change function

If I play m3u8 as native in the IOS Browser,
Shaka didn't drop the track information to getVariants(), so I parsed the m3u8 directly using the m3u8-parser library and extracted the m3u8 url for each quality
And when the user changed it to a specific quality, I put the corresponding m3u8 directly into the src of the video

The first question is, is it best to do it this way to provide quality in native? Is there a way to do it with a little more shaka?

The second question is, in the case above, there's a problem that I can't bring up my audio, which is good at changing the quality
If you look at below master.m3u8, AUDIO URI exists separately from video, but only video URLs of specific quality are loaded on src and there is no way to load audio
But do you think it's a good idea to use the audio element separately? I don't think it's the right way

Tell me a good way plz

ex)
m3u8 url : https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8

```
#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.3.0-5bf8ad5-release

#EXT-X-MEDIA:TYPE=AUDIO,URI="playlist_a-eng-0128k-aac-2c.mp4.m3u8",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"

#EXT-X-STREAM-INF:BANDWIDTH=255636,AVERAGE-BANDWIDTH=212901,CODECS="avc1.42c01e,mp4a.40.2",RESOLUTION=250x144,AUDIO="default-audio-group"
playlist_v-0144p-0100k-libx264.mp4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=543932,AVERAGE-BANDWIDTH=467745,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=418x240,AUDIO="default-audio-group"
playlist_v-0240p-0400k-libx264.mp4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1599186,AVERAGE-BANDWIDTH=1347573,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1002x576,AUDIO="default-audio-group"
playlist_v-0576p-1400k-libx264.mp4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2778640,AVERAGE-BANDWIDTH=2324339,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1252x720,AUDIO="default-audio-group"
playlist_v-0720p-2500k-libx264.mp4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1184460,AVERAGE-BANDWIDTH=992577,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=834x480,AUDIO="default-audio-group"
playlist_v-0480p-1000k-libx264.mp4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=909696,AVERAGE-BANDWIDTH=770778,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=626x360,AUDIO="default-audio-group"
playlist_v-0360p-0750k-libx264.mp4.m3u8

```

And I have additional questions.
When playing m3u8 through Shaka on iOS, is there a way to know whether it is played natively or Shaka?
My current thinking is below. Is this appropriate?

![image](https://github.com/shaka-project/shaka-player/assets/9003751/5cba3d54-a9fe-4cc3-848e-5466ab910fb9)

**Comment by kuroishi** [comment]
As far as I know, there is no way to control quality using the native playback. Sorry if I'm wrong.

**Comment by joeyparrish** [comment]
I believe you are right.  With native HLS on Safari, we do not get to select anything other than language.  Quality changes are hidden from us and done entirely inside the browser.
