### ISSUE TITLE
Can I use the registerScheme API on iOS 17.1 and below?

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6327]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.5.0

**What browser and OS are you using?**
Chrome, Safari, Firefox, Opera, Edge

**Please ask your question**

I heard from shaka player that iOS 17.1 and below will play as a native player.
Is the `registerScheme `API in the code below not available on iOS 17.1 or lower? If so, are there any other clients that don't support that API?

```
    function customNetEngine(scheme, request) {
        const targetData = getFile(downloadFiles, request.uris[0]);
        let response = {
            uri: targetData.url,
            data: targetData.data,
            headers: {'content-type': 'application/octet-stream'},
        };
        return Promise.resolve(response);
    }
    
    function getFile(downloadedFiles, url) {
        return downloadedFiles.find(each => url.indexOf(each.name) > -1);
    }
    shaka.net.NetworkingEngine.registerScheme('https', customNetEngine);
```

**Comment by joeyparrish** [comment]
iOS 17.1 introduced support for ManagedMediaSource, which is the only way Shaka Player can be in control of iOS playback.  On older devices, we don't get to make network requests at all, except for the FairPlay license request.

`registerScheme()` impacts how Shaka makes network requests, so you will only see that affect playlist and segment requests if you use iOS 17.1+.

`registerScheme()` is also how our offline support works, by connecting a special `offline:` URI syntax to a local database in the browser.  So offline would also not work before iOS 17.1.

Does this answer your question?

**Comment by brodiddev** [comment]
100% understood. Thank you for your help.
