### ISSUE TITLE
Widevine failure with HEVC

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#6333]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

nightly

**Can you reproduce the issue with the latest code from `main`?**
**Can you reproduce the issue with our latest release version?**
Will try later, just recording the info now

**Are you using the demo app or your own custom app?**
demo

**What browser and OS are you using?**
Chrome or Edge on a platform without Widevine L1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

 * CBCS mode: https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;lowLatencyMode=true;uilang=en-US;asset=https://ll-ateme-nam.akamaized.net/live/media0/appledemo/hls-ll-ctr/appledemo.m3u8;license=https://entitlements.ezdrm.com/widevine/proxy.aspx?px=8DB0CE;panel=CUSTOM%20CONTENT;build=uncompiled
 * CTR mode: https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;lowLatencyMode=true;uilang=en-US;asset=https://ll-ateme-nam.akamaized.net/live/media0/appledemo-cbcs/hls-ll-cbcs/appledemo-cbcs.m3u8;license=https://entitlements.ezdrm.com/widevine/proxy.aspx?px=8DB0CE;panel=CUSTOM%20CONTENT;build=uncompiled

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

See demo links above

**What did you do?**

Load content

**What did you expect to happen?**
Content rejected with error 4032

**What actually happened?**

Shaka Error DRM.FAILED_TO_GENERATE_LICENSE_REQUEST (Failed to execute 'generateRequest' on 'MediaKeySession': No supported PSSH box found.,NotSupportedError: Failed to execute 'generateRequest' on 'MediaKeySession': No supported PSSH box found.,)

But since it is a stream with HEVC+Widevine and that combination is not supported, Shaka should return a 4032 error, but instead what it does is try to load the stream.

Reported to me via chat from @avelad

Have yet to confirm

**Comment by joeyparrish** [comment]
> **What browser and OS are you using?**
> Chrome or Edge on a platform without Widevine L1

Works correctly in Chrome 121 on Linux.  (No L1.)  I get `MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER` (4032).

Works correctly in ChromeOS 121 as well.  (**Does** have L1.)

@avelad, can you provide any more details on the necessary environment to repro this?

**Comment by avelad** [comment]
@joeyparrish more info:

Chrome 120 - macOS Sonoma 14.3
Useragent:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`

https://github.com/shaka-project/shaka-player/assets/8983024/38effcc3-5989-4f64-8d8f-a2df9e024c1e

Edge 122 - macOS Sonoma 14.3
Useragent:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`

https://github.com/shaka-project/shaka-player/assets/8983024/f7e64b67-380b-497b-9dec-79a961b364a5

**Comment by avelad** [comment]
@theodab can you reproduce it? Thanks!

**Comment by joeyparrish** [comment]
> Chrome or Edge on a platform without Widevine L1

> But since it is a stream with HEVC+Widevine and that combination is not supported, Shaka should return a 4032 error, but instead what it does is try to load the stream.

Perhaps the issue isn't Widevine L1 vs L3, but HEVC support.  Does your Mac support HEVC?  If so, maybe we are detecting HEVC support and proceeding based on that.

EME & MCap should allow us to see that the combination of HEVC+Widevine is not supported, even though perhaps plain HEVC is.

Can you check HEVC support in https://shaka-player-demo.appspot.com/support.html ?

**Comment by avelad** [comment]
HEVC is supported in clear, but HEVC is not supported in EME. Same results with Mcap (clear supported, encrypted is not supported)

**Comment by avelad** [comment]
It’s a problem with the population of drmInfo in the streams (lazy download issue, I think)

**Comment by avelad** [comment]
If the manifest uses EXT-X-SESSION-KEY the problem doesn’t occur.

**Comment by avelad** [comment]
The streams are down, I will reopen the issue when I get the correct streams.
