### ISSUE TITLE
(HLS, TS, AES-128 key rotation) occur 3014, 3016 error in Android Chrome.

### ISSUE THREAD

**Issue by papico-inf** [shaka-project/shaka-player#6334]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**

v4.7.11

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
demo app

**What browser and OS are you using?**
browser: Chrome (122.0.6261.91)
OS: Android 13

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/sintel-ts-aes-key-rotation/master.m3u8

Demo site url : https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-ts-aes-key-rotation/master.m3u8;panel=ALL_CONTENT;panelData=drm:AES128,HLS,MP2TS;build=compiled

**What did you do?**

Enter the [link](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-ts-aes-key-rotation/master.m3u8;panel=ALL_CONTENT;panelData=drm:AES128,HLS,MP2TS;build=compiled) on Android device Chrome

**What actually happened?**

Error 3016, 3014 when playing with AES-128 key rotation on Android Chrome browser.

![CleanShot 2024-03-07 at 17 17 02@2x](https://github.com/shaka-project/shaka-player/assets/109198271/df735fbb-fc01-409e-baf6-93f01247b549)
![Screenshot_20240304_145542_Chrome](https://github.com/shaka-project/shaka-player/assets/109198271/b8174357-badb-4aae-b5fc-5d737a69fd86)

**Comment by joeyparrish** [comment]
Confirmed.  It works in ChromeOS and Chrome on Linux, but not Chrome on Android.

We need to check if there is a difference in TS support (is Android transmuxing like Linux and ChromeOS?), and we need to check if webCrypto is operating correctly on Android (unlikely to be the issue, but you never know)

**Comment by joeyparrish** [comment]
My phone appears to support TS natively, which means we are skipping transmuxing.  I didn't realize that was the case.

**Comment by avelad** [comment]
@joeyparrish I think TS has problems in all browsers, I think we should always do transmuxing in any browser

**Comment by joeyparrish** [comment]
Agreed.  It comes up on TVs, on Android, on Cast... it's a bad format and it's badly-supported.  Transmuxing should be better.

**Comment by papico-inf** [comment]
@joeyparrish 
Any idea when this error might be fixed?
I'm currently playing with rotation aes-128 key encryption and that error is preventing me from updating the version. 
Thank you for your attention.

**Comment by joeyparrish** [comment]
To fix this, we need to force transmuxing on all TS content on all platforms.  That will require a new release.

But you can change this behavior with a config today:

```js
// v4.4 through v4.7 (current)
player.configure('mediaSource.forceTransmux', true);

// v4.3
player.configure('streaming.forceTransmux', true);

// v3.0 through v4.2
player.configure('streaming.forceTransmuxTS', true);
```

Based on this workaround, the priority for the change is set at P2.  Apologies for not explaining this workaround explicitly before.  @papico-inf, can you please confirm that this workaround works for you?

**Comment by framework20** [comment]
Same errors - 3014 & 3016 on android (samsung s10+) with chrome (122.0.6261.105). But error 3014 does not always appear and has data[0]=0. Error 3016 has the following data [3,null, "PIPELINE_ERROR_DECODE"]. Logs from chrome://media-internals attached as a file. Shaka player v4.7.11.
[media-internals.txt](https://github.com/shaka-project/shaka-player/files/14591891/media-internals.txt)

**Comment by papico-inf** [comment]
@joeyparrish 
I tried setting the options you mentioned, but it doesn't work. 😢
