### ISSUE TITLE
When I create a blobUrl and play it, error 4016 occurs

### ISSUE THREAD

**Issue by sorimpower** [shaka-project/shaka-player#6336]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Y

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Y

**If the question is related to FairPlay, have you read the tutorial?**

Y

**What version of Shaka Player are you using?**
4.7.9

**What browser and OS are you using?**
window chrome

**Please ask your question**

Hi
Assuming I knew the response of master.m3u8, I created the response string object as a blobUrl and tried to load player.
But I'm getting error 4016. Why is that? Below is the code I wrote

```
 const getBlobUrl = () => {
    const manifestResponse = `#EXTM3U
    #EXT-X-MEDIA:TYPE=AUDIO,URI="playlist_a-eng-0128k-aac-2c.mp4.m3u8",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_0",AUTOSELECT=YES,CHANNELS="2"
    #EXT-X-STREAM-INF:BANDWIDTH=255636,AVERAGE-BANDWIDTH=212901,CODECS="avc1.42c01e,mp4a.40.2",RESOLUTION=250x144,AUDIO="default-audio-group"
    playlist_v-0144p-0100k-libx264.mp4.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=543932,AVERAGE-BANDWIDTH=467745,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=418x240,AUDIO="default-audio-group"
    playlist_v-0240p-0400k-libx264.mp4.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=1599186,AVERAGE-BANDWIDTH=1347573,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1002x576,AUDIO="default-audio-group"
    playlist_v-0576p-1400k-libx264.mp4.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=2778640,AVERAGE-BANDWIDTH=2324339,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1252x720,AUDIO="default-audio-group"
    playlist_v-0720p-2500k-libx264.mp4.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=1184460,AVERAGE-BANDWIDTH=992577,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=834x480,AUDIO="default-audio-group"
    playlist_v-0480p-1000k-libx264.mp4.m3u8
    #EXT-X-STREAM-INF:BANDWIDTH=909696,AVERAGE-BANDWIDTH=770778,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=626x360,AUDIO="default-audio-group"
    playlist_v-0360p-0750k-libx264.mp4.m3u8`;

    const blob = new Blob([manifestResponse], { type: 'application/vnd.apple.mpegurl' });
    const blobUrl = URL.createObjectURL(blob);

    return blobUrl;
  };
  const loadMedia = () => {
     const BlobUrl = getBlobUrl(manifestUrl);
     player.load(BlobUrl, 0, 'application/vnd.apple.mpegurl');
 }
```

Below is the 4016 error code

`{
    "severity": 2,
    "category": 4,
    "code": 4016,
    "data": [
        "    #EXT-X-MEDIA:TYPE=AUDIO,URI=\"playlist_a-eng-0128k-aac-2c.mp4.m3u8\",GROUP-ID=\"default-audio-group\",LANGUAGE=\"en\",NAME=\"stream_0\",AUTOSELECT=YES,CHANNELS=\"2\""
    ],
    "handled": false,
    "message": "Shaka Error MANIFEST.INVALID_HLS_TAG (    #EXT-X-MEDIA:TYPE=AUDIO,URI=\"playlist_a-eng-0128k-aac-2c.mp4.m3u8\",GROUP-ID=\"default-audio-group\",LANGUAGE=\"en\",NAME=\"stream_0\",AUTOSELECT=YES,CHANNELS=\"2\")",
    "stack": "Error: Shaka Error MANIFEST.INVALID_HLS_TAG (    #EXT-X-MEDIA:TYPE=AUDIO,URI=\"playlist_a-eng-0128k-aac-2c.mp4.m3u8\",GROUP-ID=\"default-audio-group\",LANGUAGE=\"en\",NAME=\"stream_0\",AUTOSELECT=YES,CHANNELS=\"2\")\n    at new shaka.util.Error (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:201:727)\n    at shaka.hls.ManifestTextParser.parseTag (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:1888:106)\n    at shaka.hls.ManifestTextParser.parseTag_ (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:1887:252)\n    at shaka.hls.ManifestTextParser.parsePlaylist (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:1884:122)\n    at $jscomp.generator.Engine_.eval [as program_] (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:1919:374)\n    at $jscomp.generator.Engine_.nextStep_ (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:37:105)\n    at $jscomp.generator.Engine_.next_ (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:33:234)\n    at $jscomp.generator.Generator_.next (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:38:73)\n    at eval (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:39:227)\n    at new Promise (<anonymous>)\n    at $jscomp.asyncExecutePromiseGenerator (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:39:120)\n    at $jscomp.asyncExecutePromiseGeneratorProgram (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:39:416)\n    at shaka.hls.HlsParser.parseManifest_ (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:1919:148)\n    at $jscomp.generator.Engine_.eval [as program_] (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:1902:464)\n    at $jscomp.generator.Engine_.nextStep_ (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:37:105)\n    at $jscomp.generator.Engine_.next_ (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:33:234)\n    at $jscomp.generator.Generator_.next (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:38:73)\n    at b (webpack-internal:///(app-pages-browser)/./node_modules/shaka-player/dist/shaka-player.compiled.debug.js:39:73)"
}`

And what I ultimately want to do is take master.m3u8, delete the information about a specific image quality, and then play the player with the processed master.m3u8.
To do that, I want to use blobUrl. Can I do it this way?

**Comment by joeyparrish** [comment]
`MANIFEST.INVALID_HLS_TAG` indicates that you have an invalid HLS tag in your blob.  Your edits are probably the root of that problem.

**Comment by sorimpower** [comment]
Thanks for commenting
However, the m3u8 I attached is the m3u8 on the shakea demo page. I don't think there is anything wrong here https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/hls.m3u8

Wouldn't it be a different problem?

**Comment by joeyparrish** [comment]
It looks like you dropped the final newline.  Our parser may be that strict.  If that's it, it's possible it's too strict, and I would be happy to accept a PR to address it.

But please double-check that your blob is correct.  The error code is pretty clear.

**Comment by sorimpower** [comment]
Thanks for commenting !

I know the cause As you said, it was because there was a space in the manifest string.
So I removed the spaces and succeeded in loading the blob url.
But another problem arose.

After loading master.m3u8, when loading video and audio m3u8 for each quality/language in Shaka Player, the baseUrl is set to be the same as the baseUrl of master.m3u8, 
`Fetch API cannot load blob:http%3a//localhost%3a3000/playlist_a-eng- 0128k-aac-2c.mp4.m3u8. URL scheme "blob" is not supported.
`

So, I have a question. Can I add the base URL as a setting value to Shaka? Is baseUrl unconditionally extracted from master.m3u8?

**Comment by sorimpower** [comment]
Oh, I guess I'm a fool

All I have to do is create a new master.m3u8 by adding the baseUrl to each video/audio URL, right?!!
Like below

```
const manifestResponse = `#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.3.0-5bf8ad5-release

#EXT-X-MEDIA:TYPE=AUDIO,URI="https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_a-eng-0128k-aac-2c.mp4.m3u8",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_5",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_a-deu-0128k-aac-2c.mp4.m3u8",GROUP-ID="default-audio-group",LANGUAGE="de",NAME="stream_4",AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_a-ita-0128k-aac-2c.mp4.m3u8",GROUP-ID="default-audio-group",LANGUAGE="it",NAME="stream_8",AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_a-fra-0128k-aac-2c.mp4.m3u8",GROUP-ID="default-audio-group",LANGUAGE="fr",NAME="stream_7",AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_a-spa-0128k-aac-2c.mp4.m3u8",GROUP-ID="default-audio-group",LANGUAGE="es",NAME="stream_9",AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_a-eng-0384k-aac-6c.mp4.m3u8",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_6",CHANNELS="6"

#EXT-X-MEDIA:TYPE=SUBTITLES,URI="playlist_s-en.webvtt.m3u8",GROUP-ID="default-text-group",LANGUAGE="en",NAME="stream_0",DEFAULT=YES,AUTOSELECT=YES
#EXT-X-MEDIA:TYPE=SUBTITLES,URI="playlist_s-el.webvtt.m3u8",GROUP-ID="default-text-group",LANGUAGE="el",NAME="stream_1",AUTOSELECT=YES
#EXT-X-MEDIA:TYPE=SUBTITLES,URI="playlist_s-fr.webvtt.m3u8",GROUP-ID="default-text-group",LANGUAGE="fr",NAME="stream_2",AUTOSELECT=YES
#EXT-X-MEDIA:TYPE=SUBTITLES,URI="playlist_s-pt-BR.webvtt.m3u8",GROUP-ID="default-text-group",LANGUAGE="pt-BR",NAME="stream_3",AUTOSELECT=YES

#EXT-X-STREAM-INF:BANDWIDTH=8062646,AVERAGE-BANDWIDTH=1824731,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=768x576,AUDIO="default-audio-group",SUBTITLES="default-text-group"
https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_v-0576p-1400k-libx264.mp4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6096050,AVERAGE-BANDWIDTH=1410993,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=640x480,AUDIO="default-audio-group",SUBTITLES="default-text-group"
https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_v-0480p-1000k-libx264.mp4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4005148,AVERAGE-BANDWIDTH=1146764,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=480x360,AUDIO="default-audio-group",SUBTITLES="default-text-group"
https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_v-0360p-0750k-libx264.mp4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2190444,AVERAGE-BANDWIDTH=784019,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=320x240,AUDIO="default-audio-group",SUBTITLES="default-text-group"
https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_v-0240p-0400k-libx264.mp4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=827972,AVERAGE-BANDWIDTH=482170,CODECS="avc1.42c01e,mp4a.40.2",RESOLUTION=192x144,AUDIO="default-audio-group",SUBTITLES="default-text-group"
https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths-hls/playlist_v-0144p-0100k-libx264.mp4.m3u8

`;
```

**Comment by joeyparrish** [comment]
Yes, that's right.  If the URLs in a playlist are relative URLs, they will be resolved relative to the playlist URL.  If they are absolute URLs, they do not need to be interpreted.
