### ISSUE TITLE
Stuck on initial buffer gap (dash)

### ISSUE THREAD

**Issue by vlazh** [shaka-project/shaka-player#6339]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

4.7.11

**What are the manifest and license server URIs?**

[master_mpd.zip](https://github.com/shaka-project/shaka-player/files/14557775/master_mpd.zip)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default

**What did you do?**

Just load a manifest.

**What did you expect to happen?**
Player ready for playback and video event 'loadeddata' is fired.

**What actually happened?**

Video event 'loadeddata' is not fired. Dash.js implementation handles this situation.

The problem I found out is that when the buffer has initial gap then the player can't to get a complete ready state.
GapJumpingController could handle this situation but it works only after play.

**Comment by joeyparrish** [comment]
@vlazh, thank you for sending a PR!
