### ISSUE TITLE
HLS IN-STREAM CEA-608 captions not working on Chromecast Receiver

### ISSUE THREAD

**Issue by CHaNGeTe** [shaka-project/shaka-player#6350]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**If the problem is related to FairPlay, have you read the tutorial?** N/A

**What version of Shaka Player are you using?** v4.7.11

**Can you reproduce the issue with our latest release version?** Yes

**Can you reproduce the issue with the latest code from `main`?** N/A receiver can be setup to use latest main?

**Are you using the demo app or your own custom app?** Both, demo works ok (no chromecast)

**If custom app, can you reproduce the issue using our demo app?** No

**What browser and OS are you using?** Demo: Chrome Mac - Chromecast: bundled

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**  Google TV (Chromecast)

**What are the manifest and license server URIs?** send via shaka-player-maintainers@googlegroups.com

```#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="CC",LANGUAGE="eng",NAME="english",INSTREAM-ID="CC1"
#EXT-X-STREAM-INF:BANDWIDTH=3572008,AVERAGE-BANDWIDTH=3440800,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=29.970,CLOSED-CAPTIONS="CC"
index2400.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2199524,AVERAGE-BANDWIDTH=2120800,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=848x480,FRAME-RATE=29.970,CLOSED-CAPTIONS="CC"
index750.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4715744,AVERAGE-BANDWIDTH=4540800,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=29.970,CLOSED-CAPTIONS="CC"
index5000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=356334,AVERAGE-BANDWIDTH=345400,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=462x240,FRAME-RATE=29.970,CLOSED-CAPTIONS="CC"
index375.m3u8
```

**What configuration are you using?  What is the output of `player.getConfiguration()`?** Chromecast Receiver defaults. Tried also: 
`{
preferredTextLanguage: 'en',
            streaming: {
                alwaysStreamText: true,
                ignoreTextStreamFailures: true,
}`

**What did you do?**

Open sender app, connect to Custom Receiver, start casting.
Select CC track (CEA-608)

**What did you expect to happen?**
Subtitles to be rendered

**What actually happened?**

Subtitles are not shown even the player reports the track as active when enabling CC

**Comment by CHaNGeTe** [comment]
The CEA-608 stream works on Shaka Demo, but not with the bundled options on a Chromecast Receiver

**Comment by CHaNGeTe** [comment]
This CEA-608 track works with MPL, but no showing when using shaka for HLS (will become mandatory on H" 2024)

**Comment by joeyparrish** [comment]
Are you using `useShakaForHls: true` and `shakaVersion: "4.7.11"` on your receiver for these tests?

**Comment by CHaNGeTe** [comment]
I am using useShakaForHls true
will try the shakaVersion override and come back with results

**Comment by CHaNGeTe** [comment]
Using shakaVersion: "4.7.11" override it works! Thank you @joeyparrish
