### ISSUE TITLE
Chromecast AWS Mediatailor documentation

### ISSUE THREAD

**Issue by CHaNGeTe** [shaka-project/shaka-player#6352]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**If the question is related to FairPlay, have you read the tutorial?** No FP issue

**What version of Shaka Player are you using?** 4.7.11

**What browser and OS are you using?** Chrome Mac OSX / iOS native app / Google TV

**Please ask your question**

- Is there any tutorial or materials that explain how to use AWS Mediatailor on a Chromecast Custom Receiver?
- Is there any doc for CastProxy and CastReceiver usage?
- Is somehow documented how to use custom builds of shaka? We have shakaVersion config parameter, but anyway to load custom builds? (to test PRs, etc)

From what I have seen there is no documented way to access the adManager from the receiver context, so any help is more than welcome

**Comment by joeyparrish** [comment]
Ad breaks work differently in the Cast Application Framework.  At the moment, there is no direct access to Shaka Player from CAF.
