### ISSUE TITLE
Edge - Error while playing content which having multiple audio eng with codecs="ac-3"' and codecs="mp4a.40.29"

### ISSUE THREAD

**Issue by kumarashu123** [shaka-project/shaka-player#6353]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

4.7.11

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
custom 

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Microsoft Edge Version 122.0.2365.92 (Official build) (64-bit) 
Windows 11

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

drm: {
      servers: {
          'com.microsoft.playready': LicenseServer,
      },
  },
  streaming: {
      stallThreshold: 2,
      stallSkip: 2,
  },
  abr: {
      enabled: true,
  },

**What did you do?**

1. Play any PlayReady DRM content in edge browser.
2. content plays from 30 secs and black screen seen

**What did you expect to happen?**
content should play smoothly

**What actually happened?**

<img width="689" alt="Screenshot 2024-03-21 152736" src="https://github.com/shaka-project/shaka-player/assets/10974291/5e21646b-6162-4514-9349-aad48453a7bb">

**Comment by avelad** [comment]
Please share the url of the content so we can review what is happening. Thanks!

**Comment by kumarashu123** [comment]
This is part of mpd
`<AdaptationSet lang="hin" mimeType="audio/mp4" id="1" segmentAlignment="true" startWithSAP="1"> <ContentProtection schemeIdUri="urn:uu###f95" value="MSPR 2.0" cenc:default_KID="d03bd###"> <mspr:pro>... </mspr:pro> </ContentProtection> <Representation bandwidth="104000" codecs="mp4a.40.29" id="###-0_audioidx~audio_frag_482_64000~extrAud_0_2" audioSamplingRate="24000" scanType="progressive" /> </AdaptationSet> 
<AdaptationSet lang="hin" mimeType="audio/mp4" id="2" segmentAlignment="true" startWithSAP="1"> <ContentProtection schemeIdUri="urn:uuid:###" value="MSPR 2.0" cenc:default_KID="d###910"> <mspr:pro>..  </mspr:pro> </ContentProtection> <ContentProtection schemeIdUri="urn:###2011" value="cenc" cenc:default_KID="d03b###0" /> <SegmentTemplate duration="540000" media="$RepresentationID$_184201/segment_$Number$.m4a" startNumber="0" timescale="90000" initialization="$RepresentationID$/audio/init.mp4" presentationTimeOffset="7200" /> <Representation bandwidth="541600" codecs="ac-3" id="###-0_audio_frag_483_384000.idx~audio_frag_483_384000" audioSamplingRate="48000" scanType="progressive" /> </AdaptationSet>`

what i have observed shakaPlayer.getAudioLanguages() gives only one language.
when i select language as 'hi' shakaPlayer.selectAudioLanguage('hi')
after a minute playback stops and i get an error.

Currently i do not have any clear content which i can share.

**Comment by joeyparrish** [comment]
Quoting the issue template you filled out:

```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.
```

If you can't share something that enables us to reproduce and debug your issue, we can't work on your issue.

**Comment by kumarashu123** [comment]
I am trying to get clear content, will try to share clear content once it is available.

**Comment by avelad** [comment]
It seems that changeType does not work when using MediaFoundation in chromium. You can try to use:

`player.configure('mediaSource.codecSwitchingStrategy', shaka.config.CodecSwitchingStrategy.RELOAD);`

**Comment by kumarashu123** [comment]
@avelad with config player.configure('mediaSource.codecSwitchingStrategy', shaka.config.CodecSwitchingStrategy.RELOAD);
playback is working without any error.
Thanks! for the support

**Comment by avelad** [comment]
@kumarashu123 Do you need this workaround for playready only or also for clear content?

**Comment by kumarashu123** [comment]
@avelad Needed for both.

**Comment by avelad** [comment]
I'll add it to the default config in Shaka. Thanks!
