### ISSUE TITLE
Add callback configuration to modify `addSourceBuffer()` call

### ISSUE THREAD

**Issue by tykus160** [shaka-project/shaka-player#6358]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**Is your feature request related to a problem? Please describe.**

Shaka supports appending extra features to `addSourceBuffer()` call via `mediaSource.sourceBufferExtraFeatures` configuration. Unfortunately it is very limited:
- we cannot pass different features to video than to audio
- it's not easy to pass features based on codecs used
- we cannot easily change features required when we switch codecs

**Describe the solution you'd like**

- add new configuration field, i.e.
```js
mediaSource.addExtraFeaturesToSourceBuffer: function(mimeType: string): string
```
defaults to
```js
mediaSource.addExtraFeaturesToSourceBuffer = (mimeType) => mediaSource.sourceBufferExtraFeatures ?? ''
```
- new callback should be called on every `SourceBuffer` creation (initial & codec switch in reload mode)
- probably also on call to `SourceBuffer.changeType`
- deprecate current configuration field

**Describe alternatives you've considered**

Adding polyfill to `MediaSource.prototype.addSourceBuffer()`.

**Additional context**

**Comment by avelad** [comment]
@tykus160 For me the idea is perfect, would you be interested in sending a PR to implement this? Thanks!

**Comment by tykus160** [comment]
Sure, please assign this to me.
