### ISSUE TITLE
Shaka 4.3.4 is loading chunks which not exist

### ISSUE THREAD

**Issue by TommiRautanen** [shaka-project/shaka-player#6368]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, no duplicates.

**If the problem is related to FairPlay, have you read the tutorial?**

Not related.

**What version of Shaka Player are you using?**

4.3.4 (the ones that comes with CAF by default)

**Can you reproduce the issue with our latest release version?**
Cannot reproduce myself even with 4.3.4, but seeing some users getting this error.

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
Chromecast

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chromecast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://vod.streaming.a2d.tv/fc50ce0d-3dfe-4a3e-97df-79e42851b8a2/5ff2ed40-eb49-11ee-89b7-89033642e7fd_20796968.ism/.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default configuration with following values overwritten:
```
abr: {
      bandwidthDowngradeTarget: 0.85,
      bandwidthUpgradeTarget: 0.75,
      switchInterval: 3,
  },
  streaming: {
    bufferingGoal: 40,
    retryParameters: {
      timeout: 40000,
      maxAttempts: 6,
      baseDelay: 1500,
      backoffFactor: 2.5,
      fuzzFactor: 0.4
    }
  }
```

**What did you do?**

No clear steps, we are only seeing these kinds of errors reported from the users automatically to our bug tracker.

**What did you expect to happen?**
Stream should play without issues.

**What actually happened?**

This is what we are seeing in the logs reported by Shaka player:
```
"error":{"shakaErrorCode":1001,"shakaErrorData":["https://vod.streaming.a2d.tv/fc50ce0d-3dfe-4a3e-97df-79e42851b8a2/5ff2ed40-eb49-11ee-89b7-89033642e7fd_20796968.ism/dash/5ff2ed40-eb49-11ee-89b7-89033642e7fd_20796968-video=3500000-59400.dash",404,"",{"akamai-mon-iucid-del":"1371244","cache-control":"max-age=0, no-cache, no-store","content-length":"0","expires":"Tue, 26 Mar 2024 08:24:13 GMT","last-modified":"Tue, 26 Mar 2024 08:18:27 GMT","pragma":"no-cache","server":"Apache/2.4.54 (Unix)"},1]}
```

When I'm trying to play same content I do not see "-video=3500000-59400.dash" being loaded but instead player loads "-video=3500000-57600.dash" and after that "-video=3500000-61200.dash" so what could make Shaka try to load something which doesn't exist?

**Comment by avelad** [comment]
Can you reproduce the issue with the latest code from main? Thanks!

**Comment by TommiRautanen** [comment]
I haven't managed to reproduce this issue myself. We are only seeing this error being reported when used by customers.

**Comment by avelad** [comment]
I tried to reproduce the bug on the main branch and it doesn't happen. So I think the bug is resolved at some point.
