### ISSUE TITLE
Tizen / Webos SmartTv not listing dolby track when stereo track with same audio language exists at mpd

### ISSUE THREAD

**Issue by kumarashu123** [shaka-project/shaka-player#6369]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.7.11

**What browser and OS are you using?**
WebOs 8.3.0 
<img width="346" alt="Screenshot 2024-03-26 173913" src="https://github.com/shaka-project/shaka-player/assets/10974291/e1c5c293-6301-4056-9729-f97d64481b35">

**Please ask your question**
I have same mpd
`<AdaptationSet lang="hin" mimeType="audio/mp4" id="1" segmentAlignment="true" startWithSAP="1">
  <ContentProtection schemeIdUri="urn:uu###f95" value="MSPR 2.0" cenc:default_KID="d03bd###">
    <mspr:pro>... </mspr:pro>
  </ContentProtection>
  <Representation bandwidth="104000" codecs="mp4a.40.29" id="###-0_audioidx~audio_frag_482_64000~extrAud_0_2" audioSamplingRate="24000" scanType="progressive" />
</AdaptationSet>
<AdaptationSet lang="hin" mimeType="audio/mp4" id="2" segmentAlignment="true" startWithSAP="1">
  <ContentProtection schemeIdUri="urn:uuid:###" value="MSPR 2.0" cenc:default_KID="d###910">
    <mspr:pro>..  </mspr:pro>
  </ContentProtection>
  <ContentProtection schemeIdUri="urn:###2011" value="cenc" cenc:default_KID="d03b###0" />
  <SegmentTemplate duration="540000" media="$RepresentationID$_184201/segment_$Number$.m4a" startNumber="0" timescale="90000" initialization="$RepresentationID$/audio/init.mp4" presentationTimeOffset="7200" />
  <Representation bandwidth="541600" codecs="ac-3" id="###-0_audio_frag_483_384000.idx~audio_frag_483_384000" audioSamplingRate="48000" scanType="progressive" />
</AdaptationSet>`

shakaPlayer.getAudioLanguages()
gives only one audio language
<img width="214" alt="Screenshot 2024-03-26 175136" src="https://github.com/shaka-project/shaka-player/assets/10974291/cd2f653c-1383-464b-9f06-2b59b99aa855">

shakaPlayer.getAudioLanguagesAndRoles()
<img width="292" alt="Screenshot 2024-03-26 175334" src="https://github.com/shaka-project/shaka-player/assets/10974291/7914562e-2c03-4c52-a256-0bde47717260">

**Is there any API which returns both audio tracks with different codecs ?
and how to select audio track based on codecs ?**

I checked in the dash.js 
this.dashPlayer.getTracksFor('audio') gives audio tracks with both codecs "audio/mp4;codecs="mp4a.40.29"" and "audio/mp4;codecs="ac-3"" of language "ms"
<img width="599" alt="image" src="https://github.com/shaka-project/shaka-player/assets/10974291/370d489e-5b78-4a53-8ab0-8e7b3301ced2">

**Comment by kumarashu123** [comment]
shakaPlayer.getVariantTracks() gives only list of video tracks , I do not see any function which gives both audio/video tracks or only audio tracks.

**Comment by joeyparrish** [comment]
Variant tracks are combinations of audio and video tracks.  If you have 3 languages and 4 resolutions, you would expect to see 12 variants (4 x 3).

**Comment by kumarashu123** [comment]
@joeyparrish shakaPlayer.getAudioLanguages() give me only one language then how can i select audio language for  type codecs="ac-3"  or codecs="mp4a.40.29" for the lang="hin" ?

**Comment by joeyparrish** [comment]
Try using getVariantTracks() / selectVariantTrack() instead of getAudioLanguages() / selectAudioLanguage().

**Comment by kumarashu123** [comment]
I was thinking to use  getVariantTracks() / selectVariantTrack() but going through selectVariantTrack function code found need to disable abr when i use selectVariantTrack(). 

My requirement is abr should be enabled, if i use selectVariantTrack () abr will not work right?
 ```
if (this.config_.abr.enabled) {
    shaka.log.alwaysWarn('Changing tracks while abr manager is enabled ' +
                         'will likely result in the selected track ' +
                         'being overriden. Consider disabling abr before ' +
                         'calling selectVariantTrack().');
  }

```

**Comment by kumarashu123** [comment]
@avelad Do you have any idea on this?

**Comment by avelad** [comment]
Our logic filters out duplicate qualities, see https://github.com/shaka-project/shaka-player/blob/main/lib/util/stream_utils.js#L88-L118

A possible solution you have is for ac-3 and mp4a.40.29 to use different roles.

**Comment by kumarashu123** [comment]
@avelad I was looking into dash document but not able to find different roles is mandatory.

**Comment by avelad** [comment]
Yes, the roles are not mandatory, but our implementation to support the two codecs with the same number of channels requires it, it is a limitation of Shaka Player.

**Comment by kumarashu123** [comment]
@avelad Thank you so much for your support.
