### ISSUE TITLE
Multiline colored VTT subtitles displayed on one line

### ISSUE THREAD

**Issue by Robloche** [shaka-project/shaka-player#6374]
**What version of Shaka Player are you using?**
`v4.7.11-main-27-gb51e6615e-uncompiled`

**Can you reproduce the issue with our latest release version?**
No.

**Can you reproduce the issue with the latest code from `main`?**
Yes.

**Are you using the demo app or your own custom app?**
The demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
uri= `https://vod.stream.vno.videofutur.fr/15ddedc0-6bc2-433d-9b35-6a78eb36b434/0565544-HORACE_62_HD_BOX-HD-FI.ism/Manifest(format=mpd-time-cmaf,encryption=cenc).mpd`
license server= `https://apitest-vod.azureedge.net/rest/v1/license/widevine?token=%2FO5MzhB9czOwDCshhWnt%2BnRNS8U3kysD4NLNlqqKpRiElyOtkxaFvw%3D%3D`

**What did you do?**
I play a movie with subtitles, some of them being displayed over two lines.

**What did you expect to happen?**
In previous version, including 4.7.11, multiline subtitles are correctly displayed, as below:
![image](https://github.com/shaka-project/shaka-player/assets/10497009/e2552062-6317-49a3-896a-819547740d9a)

**What actually happened?**
With the nightly version, subtitles are displayed on one line:
![image](https://github.com/shaka-project/shaka-player/assets/10497009/b973ecc6-9290-4b8b-bef7-e5c3ff22e4a4)

If I look at the DOM, I see this in v4.7.11:
![image](https://github.com/shaka-project/shaka-player/assets/10497009/4aa150fa-cae2-4216-8544-821114ecb8fb)

And this in the nightly version:
![image](https://github.com/shaka-project/shaka-player/assets/10497009/75040a2b-b890-4a4c-98db-17e330870068)

The `<br>` tag is missing in the faulty version.

And here's the part of the VTT file that matches:
```
00:02:45.640 --> 00:02:48.280 align:center line:91%,end
<c.cyan>Voilà Antoine,</c>
<c.cyan>mon frère aîné.</c>
```

It seems to me that the VTT parser treats these 2 lines as 2 cues instead of 1 with 2 nested cues, and thus misses the insertion of the line break cue.

**Comment by avelad** [comment]
It seems that the regression was introduced by tXml, I'm looking it now.

**Comment by avelad** [comment]
@Robloche PR: https://github.com/shaka-project/shaka-player/pull/6394
