### ISSUE TITLE
The refresh rate for the seekbar is TOO slow

### ISSUE THREAD

**Issue by MarianoFacundoArch** [shaka-project/shaka-player#6376]
The seekbar, when playing content, looks so unnatural, with small jumps.
How can I force you to update quickly? I thought of setting a timer with interval 50, but I don't see what method to call.
Thanks.

**Comment by avelad** [comment]
It is currently not configurable, the default value is 0.125 seconds. See: https://github.com/shaka-project/shaka-player/blob/main/ui/controls.js#L190

**Comment by MarianoFacundoArch** [comment]
Can we make this configurable? It does really look bad, no player has this delay, I've tried youtube, bitmovin, jwplayer.
We look like from the 90s with that refresh rate

**Comment by MarianoFacundoArch** [comment]
Yes, I can do it! Let me try, this is my first commit to shaka, will keep you psoted!

**Comment by MarianoFacundoArch** [comment]
Done!
https://github.com/shaka-project/shaka-player/pull/6386

**Comment by MarianoFacundoArch** [comment]
I got this error?

```
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

View this [failed invocation](https://github.com/shaka-project/shaka-player/pull/6386/checks?check_run_id=23307303530) of the CLA check for more information.

For the most up to date status, view the checks section at the bottom of the pull request.
```

**Comment by MarianoFacundoArch** [comment]
I signed the contract, how can we proceed to get this merged for next release?

**Comment by avelad** [comment]
> I signed the contract, how can we proceed to get this merged for next release?

I fixed some issues on your PR, you need add your name and email to https://github.com/shaka-project/shaka-player/blob/main/AUTHORS and https://github.com/shaka-project/shaka-player/blob/main/CONTRIBUTORS
