### ISSUE TITLE
How to display the start/end time in my custom web receiver for live streams?

### ISSUE THREAD

**Issue by lalit-tudip** [shaka-project/shaka-player#6379]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
- Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
- Yes

**If the question is related to FairPlay, have you read the tutorial?**

- Yes

**What version of Shaka Player are you using?**
- 4.7.10

**What browser and OS are you using?**
- Custom Web Receiver(Chromecast)

**Please ask your question**

Player handling is different for live compared to non-live streams when I use my custom web receiver. 
- The start and end times are eliminated.
- The seek bar is reset to a reddish color.
- The seekbar's left side displays the current time, while its right side displays live text.

**Need/Requirement**:
- The program start time should be shown on the left side of the seek bar, and the program end time should be shown on the right.
- The seek bar color should be green(in our case) even when live content is played(working as expected on non-live streams).
- Is there any way to replace the current/default seek bar with a custom seek bar as when we display the start and end time around the seek bar we would also need to update the position of the current time in seek bar
- **Example**: As seen in the attachment,  the program timing is 12:30 to 3:30 and the current live time is around 3. So the seekbar current time is adjusted as per the current time.
- I have added an image in the attachment where we have handled the live program seek bar and start/end time. The same functionality is required in the custom web receiver.

**Attachement**:
<img width="742" alt="image" src="https://github.com/shaka-project/shaka-player/assets/119930630/af97e5c2-85ed-404f-90a8-c26ecea34b75">

**CDN:**
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.7.10/shaka-player.compiled.js"></script>
```

**Load request**:
```
playerManager.setMessageInterceptor(
  cast.framework.messages.MessageType.LOAD, loadRequestData => {
    return new Promise(async (resolve, _reject) => {
      try {
        let url = getDashUrl(loadRequestData.media?.contentUrl);
        let mediaInfo = new cast.framework.messages.MediaInformation();
        let metadata = new cast.framework.messages.GenericMediaMetadata();
        let token = loadRequestData?.media?.metadata?.token;

        // Customize mediaInfo properties based on customData
        metadata.title = loadRequestData.media?.metadata?.title;
        metadata.subtitle = loadRequestData.media?.metadata?.subtitle;
        metadata.posterUrl = loadRequestData?.media?.metadata?.bgimage;
        metadata.images = [{
          url: loadRequestData?.media?.metadata?.image,
        }, ];
        mediaInfo.contentUrl = url;
        mediaInfo.contentId = url;
        mediaInfo.duration = loadRequestData.media?.duration || 2626;
        mediaInfo.contentType = ContentType.DASH;
        mediaInfo.streamType = "NONE";
        mediaInfo.metadata = metadata;

        // For Widevine DASH streams
        playbackConfig.licenseUrl = "";
        playbackConfig.protectionSystem = cast.framework.ContentProtection.WIDEVINE;

        playbackConfig.licenseRequestHandler = (requestInfo) => {
          requestInfo.withCredentials = false;
          requestInfo.headers["Content-Type"] = "application/octet-stream";
          requestInfo.headers["Authorization"] = token;
          console.log("requestInfo token", token);
        };

        // Set the modified mediaInfo in the load request
        loadRequestData.media = mediaInfo;
        resolve(loadRequestData);
      } catch (error) {
        console.log("Error", errorData);
      }
    });
  }
);
```

#### **Note**: I know it handles the live stream differently than the non-live but we want to display consistent UI in the receiver same as in our app. So how can I achieve the same, Do we need to create a custom seek bar for it, and if yes then how @joeyparrish?

**Comment by joeyparrish** [comment]
This doesn't appear to be a Shaka Player issue, and this isn't the right forum for Chromecast SDK support.

**Comment by joeyparrish** [comment]
Also, to be completely clear, I don't know the answer.  This is outside my experience with the Cast SDK to date.  If I did know the answer, I would never refuse to say it just because we're in the wrong forum.  😄   But you may have better luck elsewhere.

**Comment by lalit-tudip** [comment]
Sorry for the confusion, as Shaka is being used behind the scenes in the receiver, So I thought I could ask the doubts here.
