### ISSUE TITLE
ABR try to move to 720p and 1080p when the internet can carry only 360p on Android Galaxy A12

### ISSUE THREAD

**Issue by Chokoabigail** [shaka-project/shaka-player#6381]
**What version of Shaka Player are you using?**
Latest

**What browser and OS are you using?**
Android 13; Galaxy A12 (SM-A127F), kiwi browser 124.0.6327.2
Tried in Kiwi to be able to see the dev tools, but the initial problem was spotted on the default Galaxy browser on the device as well

**Please ask your question**
When I play a video on the latest version on an A12 phone, it seems the ABR miscalculates the phone's ability and tries to upgrade the video to 720p and 1080p again and again, which causes buffering since the phone capability is on 360p.
(I checked that several times, downloaded Kiwi, and browsed through it to make sure that this was indeed the problem).

How can I fix that?

**Comment by Chokoabigail** [comment]
Example of a video that gets stack: https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8;panel=ALL_CONTENT;panelData=HLS,ULTRA_HIGH_DEFINITION;build=uncompiled



After researching this, I think there is an issue with those low-power devices that sometimes they get the BW from the "Use Network Information API" and it's not aligned with the actual BW speed the device has.
On the other hand, when there is a fast change in the BW speed the "Use Network Information API" is the more accurate.

I think if we have another option in the ABR setting of "choose the lower BW (min) based on Network Information API and the bandwidth estimation" this will get us the best of both worlds.

**Comment by Chokoabigail** [comment]
In addition, I think it also makes sense to allow the user to configure `shaka.abr.Ewma`, since it affects how fast shaka will react to bandwidth changes.

**Comment by avelad** [comment]
Our ABR implementation can be extended and customized by any user, using abrFactory in the configuration.

There are advanced configurations to configure EWMA, see https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.AdvancedAbrConfiguration

Also, we will review https://github.com/shaka-project/shaka-player/pull/6396 as soon as the person on the team has time to review it.

**Comment by avelad** [comment]
And I mean those, because they can be updated by configuration.

See: https://github.com/shaka-project/shaka-player/blob/1da5da9790b8ba2e3e7b3d548b2e47f08e474379/lib/abr/ewma_bandwidth_estimator.js#L77-L78

**Comment by Chokoabigail** [comment]
> And I mean those, because they can be updated by configuration.
> 
> See:
> 
> https://github.com/shaka-project/shaka-player/blob/1da5da9790b8ba2e3e7b3d548b2e47f08e474379/lib/abr/ewma_bandwidth_estimator.js#L77-L78

My bad, I missed that, thanks.
What about the PR?

**Comment by avelad** [comment]
It must be reviewed by assigned reviewers

**Comment by Chokoabigail** [comment]
@avelad The PR still hasn't been reviewed, is there anything I should do from my side to make it happen?

**Comment by avelad** [comment]
You have to wait until they are free to review. Sorry!

**Comment by joeyparrish** [comment]
I don't believe your PR is the right direction.

I recommend you use the existing configuration `abr.useNetworkInformation` and set it to `false` to disable the NetworkInformation API from being used.  Then you can set the `abr.defaultBandwidthEstimate` to whatever you want (bits/sec).

Thanks!
