### ISSUE TITLE
Video continuously getting refreshed after reaches the end of the Timeline when the manifest filter is added in Azure HLS m3u8.

### ISSUE THREAD

**Issue by Ravi-79** [shaka-project/shaka-player#6393]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I read it. There is no duplicate that I can find.

**If the problem is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**

4.7.11 

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
OS:
Edition Windows 11 Enterprise
Version 22H2
Browser:
Microsoft Edge for Business
Version 123.0.2420.65 (Official build) (64-bit)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

Without Manifest Filter(No issue - for reference):
https://amscdn-mpslive1-uswe.streaming.media.azure.net/05a51219-f1e4-4319-a313-c8849bf99e91/62d2fe92-e5a7-4719-85f8-0cefa98a28be.ism/manifest(format=m3u8-aapl,)
With Manifest Filter (Issue reproable):
https://amscdn-mpslive1-uswe.streaming.media.azure.net/05a51219-f1e4-4319-a313-c8849bf99e91/62d2fe92-e5a7-4719-85f8-0cefa98a28be.ism/manifest(format=m3u8-aapl,filter=Newscenter2)
**What configuration are you using?  What is the output of `player.getConfiguration()`?**

{
    "drm": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "servers": {},
        "clearKeys": {},
        "advanced": {},
        "delayLicenseRequestUntilPlayed": false,
        "persistentSessionOnlinePlayback": false,
        "persistentSessionsMetadata": [],
        "logLicenseExchange": false,
        "updateExpirationTime": 1,
        "preferredKeySystems": [],
        "keySystemsMapping": {},
        "parseInbandPsshEnabled": false,
        "minHdcpVersion": "",
        "ignoreDuplicateInitData": true
    },
    "manifest": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "disableThumbnails": false,
        "defaultPresentationDelay": 0,
        "segmentRelativeVttTiming": false,
        "raiseFatalErrorOnManifestUpdateRequestFailure": false,
        "dash": {
            "clockSyncUri": "",
            "ignoreDrmInfo": false,
            "disableXlinkProcessing": false,
            "xlinkFailGracefully": false,
            "ignoreMinBufferTime": false,
            "autoCorrectDrift": true,
            "initialSegmentLimit": 1000,
            "ignoreSuggestedPresentationDelay": false,
            "ignoreEmptyAdaptationSet": false,
            "ignoreMaxSegmentDuration": false,
            "keySystemsByURI": {
                "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
                "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
                "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
                "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:f239e769-efa3-4850-9c16-a903c6932efb": "com.adobe.primetime"
            },
            "sequenceMode": false,
            "enableAudioGroups": false,
            "multiTypeVariantsAllowed": true
        },
        "hls": {
            "ignoreTextStreamFailures": false,
            "ignoreImageStreamFailures": false,
            "defaultAudioCodec": "mp4a.40.2",
            "defaultVideoCodec": "avc1.42E01E",
            "ignoreManifestProgramDateTime": false,
            "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\"",
            "useSafariBehaviorForLive": true,
            "liveSegmentsDelay": 3,
            "sequenceMode": true,
            "ignoreManifestTimestampsInSegmentsMode": false,
            "disableCodecGuessing": false,
            "allowLowLatencyByteRangeOptimization": true
        },
        "mss": {
            "sequenceMode": false,
            "keySystemsBySystemId": {
                "9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
            }
        }
    },
    "streaming": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "rebufferingGoal": 2,
        "bufferingGoal": 10,
        "bufferBehind": 30,
        "ignoreTextStreamFailures": false,
        "alwaysStreamText": false,
        "startAtSegmentBoundary": false,
        "gapDetectionThreshold": 0.5,
        "gapJumpTimerTime": 0.25,
        "durationBackoff": 1,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsOnSafari": true,
        "inaccurateManifestTolerance": 2,
        "lowLatencyMode": false,
        "autoLowLatencyMode": false,
        "forceHTTPS": false,
        "preferNativeHls": false,
        "updateIntervalSeconds": 1,
        "dispatchAllEmsgBoxes": false,
        "observeQualityChanges": false,
        "maxDisabledTime": 30,
        "parsePrftBox": false,
        "segmentPrefetchLimit": 0,
        "liveSync": false,
        "liveSyncMaxLatency": 1,
        "liveSyncPlaybackRate": 1.1,
        "liveSyncMinLatency": 0,
        "liveSyncMinPlaybackRate": 1,
        "allowMediaSourceRecoveries": true,
        "minTimeBetweenRecoveries": 5
    },
    "mediaSource": {
        "codecSwitchingStrategy": "smooth",
        "sourceBufferExtraFeatures": "",
        "forceTransmux": false,
        "insertFakeEncryptionInInit": true
    },
    "offline": {
        "usePersistentLicense": true,
        "numberOfParallelDownloads": 5
    },
    "abr": {
        "enabled": true,
        "useNetworkInformation": true,
        "defaultBandwidthEstimate": 1000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
            "minWidth": 0,
            "maxWidth": null,
            "minHeight": 0,
            "maxHeight": null,
            "minPixels": 0,
            "maxPixels": null,
            "minFrameRate": 0,
            "maxFrameRate": null,
            "minBandwidth": 0,
            "maxBandwidth": null
        },
        "advanced": {
            "minTotalBytes": 128000,
            "minBytes": 16000,
            "fastHalfLife": 2,
            "slowHalfLife": 5
        },
        "restrictToElementSize": false,
        "restrictToScreenSize": false,
        "ignoreDevicePixelRatio": false,
        "clearBufferSwitch": false,
        "safeMarginSwitch": 0
    },
    "autoShowText": 3,
    "preferredAudioLanguage": "en-US",
    "preferredAudioLabel": "",
    "preferredTextLanguage": "en-US",
    "preferredVariantRole": "",
    "preferredTextRole": "",
    "preferredAudioChannelCount": 2,
    "preferredVideoHdrLevel": "AUTO",
    "preferredVideoLayout": "",
    "preferredVideoLabel": "",
    "preferredVideoCodecs": [],
    "preferredAudioCodecs": [],
    "preferForcedSubs": false,
    "preferSpatialAudio": false,
    "preferredDecodingAttributes": [],
    "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null
    },
    "playRangeStart": 0,
    "playRangeEnd": null,
    "cmcd": {
        "enabled": false,
        "sessionId": "",
        "contentId": "",
        "useHeaders": false
    },
    "cmsd": {
        "enabled": true,
        "applyMaximumSuggestedBitrate": true,
        "estimatedThroughputWeightRatio": 0.5
    },
    "lcevc": {
        "enabled": false,
        "dynamicPerformanceScaling": true,
        "logLevel": 0,
        "drawLogo": false
    },
    "ads": {
        "customPlayheadTracker": false
    }
}

**What did you do?**

1. Open the following player URL which is having the HLS Azure video with manifest filter Added.
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://amscdn-mpslive1-uswe.streaming.media.azure.net/05a51219-f1e4-4319-a313-c8849bf99e91/62d2fe92-e5a7-4719-85f8-0cefa98a28be.ism/manifest(format=m3u8-aapl,filter=Newscenter2);panel=CUSTOM%20CONTENT;build=uncompiled
2. Once the video reaches to the end of the timeline you can observe that the player is still loading instead of showing the replay icon.
![image](https://github.com/shaka-project/shaka-player/assets/131441182/3eca8bf0-2a2d-4a5d-9423-7b41b8393649)

**What did you expect to happen?**
The player should stops the loading and show the replay icon.

**Note: Same manifest without Manifest filter doesn't create any issue**
Reference player URL without Manifest filter
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://amscdn-mpslive1-uswe.streaming.media.azure.net/05a51219-f1e4-4319-a313-c8849bf99e91/62d2fe92-e5a7-4719-85f8-0cefa98a28be.ism/manifest(format=m3u8-aapl,);panel=CUSTOM%20CONTENT;build=uncompiled

Expected result Screenshot:
![image](https://github.com/shaka-project/shaka-player/assets/131441182/1c3c4c97-fd45-4164-ab4d-aff0f55e5967)

**What actually happened?**

I am not sure about the exact root cause, but I believe the player is trying to fetch the segment which is not available due the the manifest filter added. 
The **Possible encoding problem detected! Unexpected buffered range for reference ** error is triggered.
![image](https://github.com/shaka-project/shaka-player/assets/131441182/78bf8e59-7e1d-48dc-8e1a-e14c2413ff6b)

**Comment by avelad** [comment]
I can reproduce the error. If I disable the audio or video, the behaviour is correct (strange...)

**Comment by avelad** [comment]
> Without Manifest Filter(No issue - for reference):
> https://amscdn-mpslive1-uswe.streaming.media.azure.net/05a51219-f1e4-4319-a313-c8849bf99e91/62d2fe92-e5a7-4719-85f8-0cefa98a28be.ism/manifest(format=m3u8-aapl,)

Result of media stream validator: 
[non-issue.html.zip](https://github.com/user-attachments/files/16233460/non-issue.html.zip)

> With Manifest Filter (Issue reproable):
> https://amscdn-mpslive1-uswe.streaming.media.azure.net/05a51219-f1e4-4319-a313-c8849bf99e91/62d2fe92-e5a7-4719-85f8-0cefa98a28be.ism/manifest(format=m3u8-aapl,filter=Newscenter2)

Result of media stream validator: 
[issue.html.zip](https://github.com/user-attachments/files/16233461/issue.html.zip)

**Comment by avelad** [comment]
The stream returns a 410...
