### ISSUE TITLE
Even if I play the Shaka Player sample URL, I can't find the segment lookupTime.

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6400]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.7.11

**What browser and OS are you using?**
yes

**Please ask your question**
Even if I play the Shaka Player sample URL, I can't find the segment lookupTime.
https://storage.googleapis.com/shaka-live-assets/player-source.m3u8

I configured configure as below:
```
player.configure({
    streaming: {
      useNativeHlsOnSafari: false, // iOS 17.1이상일 때 샤카 플레이어로 재생
      bufferingGoal: 0.5, // 최소 0.5초 분량의 미디어를 버퍼에 유지
      rebufferingGoal: 0.5, // 버퍼링을 시작하기 전에 가지고 있어야 하는 미디어의 최소 길이를 결정
      lowLatencyMode: true, // 저지연 모드 기본 설정 적용 (configure 설정이 최우선으로 적용됨)
      inaccurateManifestTolerance: 0, // manifest 정확성에 대한 허용 오차를 0으로 설정해 세그먼트와의 시간 불일치를 최소화 함
      segmentPrefetchLimit: 2, // 두 개의 세그먼트를 미리 가져옴
      retryParameters: {
        baseDelay: 100, // 재시도 delay 100ms 설정
      },
    },
    manifest: {
      retryParameters: {
        baseDelay: 100,
      },
    },
  });
```

However, even if configure is not set, the same cannot find segment lookupTime warning below occurs.

How can I solve this?

This happens frequently and cannot be played with Shaka Player.
When I play the same content on the hls.js demo page, it works fine.

![image](https://github.com/shaka-project/shaka-player/assets/136538250/124f7641-6489-4f48-a79a-a9cf21b894b9)

**Comment by avelad** [comment]
HLS Live from Shaka is broken (https://storage.googleapis.com/shaka-live-assets/player-source.m3u8) because the media playlist are not updated. Sorry!

**Comment by brodiddev** [comment]
Even with other live streams, the cannot find warning message often appears.  What is the reason?
