### ISSUE TITLE
useSafariBehaviorForLive=false not giving full DVR length for HLS live stream when used with Chromecast

### ISSUE THREAD

**Issue by TommiRautanen** [shaka-project/shaka-player#6401]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not FairPlay related

**What version of Shaka Player are you using?**
4.3.4 (the one that comes with CAF)

**Can you reproduce the issue with our latest release version?**
Tried on Shaka's demo page with 4.7.11 and when setting useSafariBehaviorForLive to false in config, timeline is drawn and full window is presented. Same version used in Chromecast with same config override makes CAF's PlayerManager to return only 15s of DVR window back.

**Can you reproduce the issue with the latest code from `main`?**
-

**Are you using the demo app or your own custom app?**
Custom CAF receiver using Shaka.

**If custom app, can you reproduce the issue using our demo app?**
Plain Shaka player works with this stream correctly, but not when Shaka is used in Chromecast.

**What browser and OS are you using?**
Chromecast

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
-

**What are the manifest and license server URIs?**
https://live.streaming.a2d.tv/asset/20315823.isml/.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default, but overriding manifest.hls.useSafariBehaviorForLive and setting it to false.

**What did you do?**
Start to play stream in Chromecast. Stream is not seekable as liveSeekableRange reported by CAF's PlayerManager is only 15s long.

**What did you expect to happen?**
Stream should be seekable also when used in Chromecast with 30 minutes of DVR length.

**What actually happened?**

Stream plays but DVR window is only 15s long so cannot be seeked.

**Comment by avelad** [comment]
From what you mention, it is an error in the integration of Shaka Player in CAST, so this site is not the appropriate one to report this error, I recommend that you use: https://developers.google.com/cast/support Thanks!

**Comment by TommiRautanen** [comment]
@avelad actually this may have been Shaka related issue after all as I also needed to override `manifest.availabilityWindowOverride` value in order to get CAF give me full DVR window length.

**Comment by avelad** [comment]
@theodab can you review it? Thanks!

**Comment by joeyparrish** [comment]
CAF may have its own default configs for Shaka Player.  It is reasonable for you to override them with your own if you need to.
