### ISSUE TITLE
Getting the availabilityStartTime from the manifest

### ISSUE THREAD

**Issue by samueleastdev** [shaka-project/shaka-player#6410]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**What actually happened?**

I am trying to get the availabilityStartTime fromt the manifest
![Screenshot 2024-04-05 at 10 28 55](https://github.com/shaka-project/shaka-player/assets/1894778/bf97105a-bb50-46bc-a998-90bc46e9ad2f)

We currently parse the manifest ourselves due to our setup, and this seems redundant since Shaka also parses the manifest. I was hoping to utilize the Shaka Player API to obtain this value.

I noted that this has been discussed here:
https://github.com/shaka-project/shaka-player/issues/957

I have tried the following methods:

``` javascript
this.player.getPresentationStartTimeAsDate();

//Outputs: Thu Jan 01 1970 01:00:11 GMT+0100

// And

const manifest = this.player.getManifest();
const timeline = manifest.presentationTimeline;
const startTime = timeline.getPresentationStartTime();

// Outputs: 16.771488666534424
```

This method has been mentioned here:
https://github.com/shaka-project/shaka-player/blob/ea740ba2468f3b035d463ea9933aa7eeccf5c748/lib/player.js#L4749

I also see this in the console:

```
[Thu Jan 01 1970 01:00:11 GMT+0100 (Greenwich Mean Time)] Warning: Shaka Player's internal Manifest structure is NOT covered by semantic versioning compatibility guarantees. It may change at any time! Please consider filing a feature request for whatever you are using getManifest() for.
```

Therefore, I am submitting a feature request. Is there a way to obtain the availabilityStartTime from the manifest without having to parse it ourselves, before we even load Shaka?

I want to get the value availabilityStartTime="1970-01-01T00:00:00Z"

Here is what we currently do.
```js
protected parseManifest = (manifestXML: string) => {
    const DOMTree = new window.DOMParser().parseFromString(manifestXML, 'text/xml');
    const MPD = DOMTree.getElementsByTagName('MPD').item(0);

    if (!MPD) {
        console.warn('WARNING: manifest parsing error');
        return;
    }

    const availabilityStartTime = MPD.getAttribute('availabilityStartTime');

    // availabilityStartTime="1970-01-01T00:00:00Z"
    console.log('availabilityStartTime', availabilityStartTime);

};
```

Can the above be done by Shaka?

**Comment by avelad** [comment]
@samueleastdev are you interested on send a PR for this? Thanks!

**Comment by samueleastdev** [comment]
@avelad, I was wondering if it's possible with the current setup; perhaps I'm missing an API of which I am not aware. If it's not available, then having the ability to get values like availabilityStartTime from the MPD would be helpful. Thanks.

**Comment by avelad** [comment]
@samueleastdev I have seen that this can be easily obtained in the main branch and in the future version 5.0.0

With the config `manifest.dash.manifestPreprocessor`, in your function you receive a parameter that includes the following

![Captura de pantalla 2024-04-10 a las 11 16 34](https://github.com/shaka-project/shaka-player/assets/8983024/0140158c-bb7e-4ea4-96c8-4c4c062074a6)

Using: https://storage.googleapis.com/shaka-live-assets/player-source.mpd

You have the original attribute without needing to parse anything.

Is this enough for you?

**Comment by samueleastdev** [comment]
This is perfect thank you.

~~~ js
this.shaka.configure({
    manifest: {
        dash: {
            manifestPreprocessor: (manifest) => {
                console.log('[Debug][dash]', manifest);
            },
        },
    },
});
~~~
