### ISSUE TITLE
Get customer actual video data downloaded per sec

### ISSUE THREAD

**Issue by AdityaSinghShekhawat** [shaka-project/shaka-player#6411]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.2.0

**What browser and OS are you using?**
Chrome (123.0.6312.106), Mac (14.3.1)

**Please ask your question**
Is there a way to get downloaded video data? I want to know actual video data downloaded per sec. For e.g., A customer watch 10 sec of video and in that duration a total of 100Mb is data is loaded/downloaded then actual customer bitrate would be 10Mbps. In Exo player there is a method [totalBandwidthBytes](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/PlaybackStats.html#totalBandwidthBytes) which tells total bytes transferred. Do Shaka have anything similar?

**Comment by avelad** [comment]
At Shaka we have none of this. Sorry!

**Comment by AdityaSinghShekhawat** [comment]
Got it. Thanks for quick reply! Have opened a feature request.
