### ISSUE TITLE
Lag/Idle Time when playing video in Shaka Player

### ISSUE THREAD

**Issue by smriti0302** [shaka-project/shaka-player#6412]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**
Yes

**What version of Shaka Player are you using?**
4.7.11

**What browser and OS are you using?**
Microsoft Edge, Windows 10

**Please ask your question**
My requirement is to enable seamless playing (close to 0 lag) of videos. I am using the Shaka Player, but in a Stack manner. So, there's an active shaka player, and a hidden shaka player, where the next video is pre-loaded. So, for both players, the drm license request call, the init function, fetching of mpd and first 2 segments occurs. Once the video finishes in the active player, it is removed and the second player becomes active. However, when the videos are of large sizes, after the first player goes out, there's a black screen that appears in the second player and only after that does the video start playing. This lag is about 1 second in duration. I have checked the performance and network and could not attribute this black screen to anything in particular, except "Idle Time" where nothing is happening except the periodic Shaka UI functions. 

Shaka Controls : 

const shakaUIConfig = {
  enableTooltips: true,
  doubleClickForFullscreen: true,
  seekOnTaps: true,
  tapSeekDistance: 5,
  enableKeyboardPlaybackControls: true,
  enableFullscreenOnRotation: true,
  keyboardSeekDistance: 5,
  controlPanelElements: [
    "prev",
    "prev_marker",
    "seek_backward",
    "play_pause",
    "seek_forward",
    "next_marker",
    "next",
    "spacer",
    "mute",
    "volume",
    "time_and_duration",
    "toggle_mode",
    "custom_fullscreen",
  ],
  seekBarColors: {
    base: "#FFFFFF",
    buffered: "#DDDDDD",
    played: "#FFBF00",
  },
  fastForwardRates: [2, 4, 8, 1],
  rewindRates: [-1, -2, -4, -8],
};

const shakaStreamConfig = {
  streaming: {
    maxDisabledTime: 0,
    inaccurateManifestTolerance: 0,
    lowLatencyMode: true,
    bufferingGoal: 10,
    bufferBehind: 20,
    rebufferingGoal: 4,
    ignoreTextStreamFailures: true,
    stallThreshold: 3,
    segmentPrefetchLimit: 3,
    retryParameters: {
      maxAttempts: 3,
      timeout: 30000,
      connectionTimeout: 30000,
      stallTimeout: 15000,
    },
  },
};

export {
  ShakaPlayerFullscreen,
  ShakaPlayerGoNext,
  ShakaPlayerGoPrev,
  ShakaPlayerGoSeekBackward,
  ShakaPlayerGoSeekForward,
  ShakaPlayerNextMarker,
  ShakaPlayerPrevMarker,
  ShakaPlayerToggleMode,
  shakaPlayerToggleModeInstance,
  shakaStreamConfig,
  shakaUIConfig,
};

I wish to remove the idle time and that black screen that appears and produce seamlessness while playing videos. How do i do it?

**Comment by avelad** [comment]
It is not released yet, but with https://github.com/shaka-project/shaka-player/issues/880 you can do what you want. You have to wait for us to release 5.0.0 to be able to use this functionality. Sorry!
