### ISSUE TITLE
Get customer actual video data downloaded per sec

### ISSUE THREAD

**Issue by AdityaSinghShekhawat** [shaka-project/shaka-player#6413]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
We have integrated advance codecs like VP9, x265 on top of x264. Need to have a metric which could tell customer data saved due to advance codecs. We need actual customer video data download per sec. For e.g., A customer watch 10 sec of video and in that duration a total of 100Mb data is loaded/downloaded then actual customer bitrate would be 10Mbps.

**Describe the solution you'd like**
It would be super helpful if we get the above data in utility like [Stats](http://v1-6-5.shaka-player-demo.appspot.com/docs/shaka.player.Stats.html).

**Describe alternatives you've considered**
If not the actual bitrate then total bytes loaded during a playback can also, be helpful.

**Additional context**
In Exo player there is a method [totalBandwidthBytes](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/PlaybackStats.html#totalBandwidthBytes) which tells total bytes transferred. Need similar method in Shaka player.

**Comment by avelad** [comment]
@AdityaSinghShekhawat are you interested on send a PR to add it? Thanks!
