### ISSUE TITLE
Greenish lines observed when initialized the encrypted channel playback on Shaka player

### ISSUE THREAD

**Issue by Ramajayadevi174** [shaka-project/shaka-player#6420]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**
>

**What version of Shaka Player are you using?**
`v4.7.11-uncompiled`

**Can you reproduce the issue with our latest release version?**
Using latest version v4.7.11

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
The demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Mozilla firefox

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
No asset

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**
Configure the Manifest url, license server url and header values to play the encrypted playback.

**What did you expect to happen?**
There should be a playback without any macroblocks/Greenish lines over a playback.

**What actually happened?**
Observed greenish lines while initiate a playback and its recovered when we enabled/disabled the Low latency Mode and Auto Low latency mode options on the Settings menu on the player.
![greenish_lines_encrypted_pb_shaka](https://github.com/shaka-project/shaka-player/assets/166511522/f095aabb-ab42-4eaf-8272-b18650dfc486)

**Comment by avelad** [comment]
Please provide a sample stream to test it! Thanks!

**Comment by joeyparrish** [comment]
@Ramajayadevi174, please follow these instructions from the issue template:

```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```

If you need to send us additional instructions for authorization, include that in the email.

Without a way to reproduce and debug your issue, we **can't** work on it.

If you want to work on your own PR to resolve the issue, we can assign it back to you.

**Comment by Ramajayadevi174** [comment]
Hi Team,

Please find the required details,

Manifest url : https://live.pl10d.vdochne2e.com/ull_62m_drm1/vxfmt=dp/manifest.mpd?device_profile=ull_enabled_d<http://live.pl10d.vdochne2e.com/ull_62m_drm1/vxfmt=dp/manifest.mpd?device_profile=ull_enabled_d>

License server url : https://multidrm.core.verimatrixcloud.net/widevine

Shaka demo URI after loaded the required details : https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://live.pl10d.vdochne2e.com/ull_62m_drm1/vxfmt=dp/manifest.mpd?device_profile=ull_enabled_d;license=https://multidrm.core.verimatrixcloud.net/widevine;panel=CUSTOM%20CONTENT;build=uncompiled

On the settings icon on the player, if we enabled/disabled the Low Latency Mode and Auto Low Latency mode under STREAMING option, greenish lines were recovered.

Regards,
Ramajayadevi.
________________________________

**Comment by joeyparrish** [comment]
I'm unable to access your content.  Your hostname doesn't resolve: https://www.nslookup.io/domains/live.pl10d.vdochne2e.com/dns-records/

**Comment by Ramajayadevi174** [comment]
Hi Team,

Could you please provide your IP details of the machine where you tried to play the content. So that we can request our IT team to whitelist your IP to resolve dns.

Regards,
Ramajayadevi.
________________________________

**Comment by joeyparrish** [comment]
It's not a matter of my IP, unless your name servers need to allow-list me to resolve the domain name.  Please check the link above.  Your domain has no public A or AAAA records at all.
