### ISSUE TITLE
Shaka 4.7.12 cannot be loaded - URL returns 404

### ISSUE THREAD

**Issue by TommiRautanen** [shaka-project/shaka-player#6424]
https://ajax.googleapis.com/ajax/libs/shaka-player/4.7.12/shaka-player.compiled.js says 404.

**Comment by avelad** [comment]
@theodab can you review it? Thanks!

**Comment by theodab** [comment]
v4.7.12 has been approved to be uploaded to ajax.googleapis.com, but it usually takes Ajax a few hours to update.

**Comment by theodab** [comment]
I'll add something to the FAQ about this, people keep asking about it.

**Comment by theodab** [comment]
It is now online.
