### ISSUE TITLE
onEnded Event Fails to Trigger on Specific LG Devices and Set Top Boxes

### ISSUE THREAD

**Issue by samueleastdev** [shaka-project/shaka-player#6427]
**What version of Shaka Player are you using?**

Shaka: 4.7.12

**Can you reproduce the issue with our latest release version?**

Yes

**What browser and OS are you using?**

We are seeing the issue on LG 43UR78003LK - 2023 and also on our STB running.
~~~
Mozilla/5.0, AppleWebKit/537.36, Chrome/92.0.4515.159, Safari/537.36, OPR/46.0.2207.0, OMI/4.22.1, VODAFONE_STB/7.2.A002.99aa.huad BCM72604/7.2.A002.99aa.huad/DCI362/MEDIUM (Sagemcom_Broadband_SAS, DCI362_UHD_VF_HU, Wired)
~~~

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

All the information i have so far: LG 43UR78003LK - 2023 will try to get more if needed

**What did you do?**

I have both a basic setup and a Shaka setup. Upon testing Shaka on LG devices and our STB, the onEnded event does not fire.
I have created a demo link here.

https://58boel1q56.execute-api.eu-central-1.amazonaws.com/dev/

Additionally, here is a video demonstrating the issue, first tested on the STB and then on the browser for reference. You won't see the video in the STB inspector — that's normal, but it is playing on the STB.

The basic setup uses an MP4 file, while the Shaka setup utilizes a DASH stream. You can see everything in the source of the demo link.

https://github.com/shaka-project/shaka-player/assets/1894778/f7cac127-3ed4-4b83-a970-694350372465

**What did you expect to happen?**

onEnded event to fire

**What actually happened?**

onEnded event does not fire

**Comment by avelad** [comment]
These devices are supported by the community, we do not have these devices in the laboratory to test it. Are you interested in finding the bug and submitting a PR? Thanks!

**Comment by samueleastdev** [comment]
Thanks for the response. We may have some time to look into this. We are first seeing if this may be an issue with the actual stream.

Have you seen issues like this in the past that have been caused by streaming problems?

We are on a tight schedule for a release at the moment, so we have a workaround in place.

```
onTimeupdate = () => {
    if (isStb()) {
        const duration = PlaybackController.getDuration();
        const timePlayed = PlaybackController.getPlayedTime();
        if (duration > 0 && timePlayed + 0.5 >= duration) {
            // do something 
        }
    }
}
```

But this is not ideal, hopefully we can find a fix.

**Comment by joeyparrish** [comment]
We do something very similar to that in `timeupdate` events to work around issues like this in our tests.

**Comment by avelad** [comment]
@samueleastdev Do you want do a PR to fix it?

**Comment by samueleastdev** [comment]
@avelad we are just using the workaround for now but as soon as I get some free time I will looking into creating a PR for this.
