### ISSUE TITLE
Fairplay tutorial / documentation clarification

### ISSUE THREAD

**Issue by alexandercerutti** [shaka-project/shaka-player#6428]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**If the question is related to FairPlay, have you read the tutorial?** Yes

**What version of Shaka Player are you using?** latest v4

**What browser and OS are you using?** -

**Please ask your question**

We are migrating from Shaka v3 to v4. Along all the changes, several difficulties and unknown things that makes us say "why does this work?" or "why doesn't this work?", while integrating (again) the support to Fairplay on Safari HLS (through `src=`), we noticed we had to convert (as documentation says) the key system from the legacy to the EME.

Then we had to install the polyfill (and we don't understand why) as per the [Fairplay Tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html). Then we saw in there this phrase:

> By default Shaka Player supports Modern EME, if your provider doesn't support Modern EME yet, you can use legacy Apple Media Keys with:

That "if you provider doesn't support Modern EME" is what we don't exactly understand.

What is intended as "provider"? The "project side" (backend) that generates the M3U8 file, the browser or what? How do we understand if the provider supports Modern EME?

Thank you.

**Comment by avelad** [comment]
> > By default Shaka Player supports Modern EME, if your provider doesn't support Modern EME yet, you can use legacy Apple Media Keys with:
> 
> That "if you provider doesn't support Modern EME" is what we don't exactly understand.
> 
> What is intended as "provider"? The "project side" (backend) that generates the M3U8 file, the browser or what? How do we understand if the provider supports Modern EME?

By provider we mean DRM provider, for example EZDRM, Verimatrix, ExpressPlay, etc.

DRM provider is responsible for managing FairPlay keys.

**Comment by alexandercerutti** [comment]
@avelad okay thanks. So, is there a way to understand, by the manifest perhaps, if the served content supports Modern EME?

**Comment by avelad** [comment]
> @avelad okay thanks. So, is there a way to understand, by the manifest perhaps, if the served content supports Modern EME?

No, you always need to know if the DRM provider supports it or not, with the manifest it is impossible to know.

**Comment by alexandercerutti** [comment]
I'm asking you because I see the manifest owns something like this, especially the `KeyFormat`, so I was thinking this was related.

```
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://hls-fairplay",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
```

**Comment by avelad** [comment]
> I'm asking you because I see the manifest owns something like this, especially the `KeyFormat`, so I was thinking this was related.
> 
> ```
> #EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://hls-fairplay",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
> ```

It is impossible to know, because that is generic to the protocol used for fairplay.

**Comment by alexandercerutti** [comment]
Okay thank you very much for the answers!
