### ISSUE TITLE
Help with Google Cast Receiver configuration

### ISSUE THREAD

**Issue by mrp1no** [shaka-project/shaka-player#6439]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
v4.7.12

**What browser and OS are you using?**
Google Chrome 123.0.6312.105 on Ubuntu 22.04 LTS
Google Chrome 123.0.6312.100 on Android 14

**Please ask your question**
Hello,
I've correctly configured Shaka Player on my website and it works like a charm, but now I'm stuck at CAF receiver configuration... I can't figure out how to configure the receiver so it can detect the video/audio stream with external WebVTT subtitles from the player in my website. I have a PHP website which loads the content dinamically, with the MPD link for each content being stored in a MySQL database (same for .vtt subs) and the player loading the content every time I click a link from the same page, using "attach" method. Is there a way for the receiver app to automatically "detect" the stream which is currently being played by Shaka along with the subtitles? Can someone help me understand what I should do or maybe send me a link to a working Shaka-CAF receiver integration? I tried with the one in the demo folder but it didn't work, and there isn't that much documentation about Shaka Player CAF integration - or at least I wasn't able to find it, otherwise I wouldn't be here writing this question.
Thank you in advance!!

**Comment by avelad** [comment]
To ask about CAF integration problems you have to use: https://developers.google.com/cast/support. Sorry!

**Comment by mrp1no** [comment]
> To ask about CAF integration problems you have to use: https://developers.google.com/cast/support. Sorry!

Tried with CastReceiver GitHub sample, doesn't work. Shaka Player cannot send videos to v3 receiver
