### ISSUE TITLE
Weird behavior on iOS Safari

### ISSUE THREAD

**Issue by MarianoFacundoArch** [shaka-project/shaka-player#6440]
I read several posts on this and no one with a solution.
On iOS Safari, when we load a manifest, such as an m3u8, it shows an infinite loading.

I found a kind of workaround after calling load, it is doing:

```
      if (
        this._clientDetails?.device?.model === "iPhone" &&
        this._videoPlayerElement.readyState === 1
      ) {
        this._videoPlayerElement.load();
      }
```
(The ===1 in the readyState is completely necessary, as if not, offline playback stops working)
Is there any other solution more reliable?
Thanks.

**Comment by avelad** [comment]
Please, use the [template](https://github.com/shaka-project/shaka-player/issues/new?assignees=&labels=type%3A+bug&projects=&template=bug_report.md&title=) to open the bugs! Thanks!
