### ISSUE TITLE
Using web workers to run shaka

### ISSUE THREAD

**Issue by StormFury2701** [shaka-project/shaka-player#6441]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.7.11

**What browser and OS are you using?**
Chrome + Windows

**Please ask your question**
I am interested in trying to measure potential benefits of using MSE in Web Worker for Shaka. I have found similar question https://github.com/shaka-project/shaka-player/issues/5008 and was wondering if there have been any changes in plans for supporting this functionality.
Additionally, as an alternative, I was looking into achieving this without changing shaka code by overriding a component that is responsible for handling MSE. I believe that would be MediaSourceEngine, I am not sure if this is possible at all since it is not a plugin. Is there any option for me to create an extension class for MediaSourceEngine or some other way to change the core logic of the MediaSourceEngine without changing shaka code?
Thank you!

**Comment by joeyparrish** [comment]
One of the major things preventing Shaka from running in a worker context was our use of DOMParser, which isn't available there.  However, this was recently changed.  In v4.8.0, Shaka should be able to run without DOMParser.

I don't know much, but I expect it would be best to have some division within Shaka to allow some subset of components to be optionally hosted in a worker, with messages exchanged between the main player and those worker components.  I'm sure MediaSourceEngine would be part of that, but I'm not sure what else.  StreamingEngine?  A copy of NetworkingEngine?  I also wonder if we'll have trouble with any configuration shared between these two halves.

If you're interested in pursuing this, please make a proposal!  I'm open to changes to the structure of the project to enable use in workers.

**Comment by StormFury2701** [comment]
Thank you for getting back to me so quickly with this! I am gonna look into v4.8.0 without the DOM parser, try to estimate locally what changes would be required for that and get back to you with a more detailed proposal.
