### ISSUE TITLE
when useNativeHlsOnSafari is  false - DRM protected content playback is... impossible

### ISSUE THREAD

**Issue by MarianoFacundoArch** [shaka-project/shaka-player#6445]
When using fairplay and trying to use         useNativeHlsOnSafari: false , video completely freezes, stalls, weird behaviour.

**Comment by avelad** [comment]
Please, use the [template](https://github.com/shaka-project/shaka-player/issues/new?assignees=&labels=type%3A+bug&projects=&template=bug_report.md&title=) to open the bugs! Thanks!
