### ISSUE TITLE
when useNativeHlsOnSafari is false - DRM protected content playback is... impossible

### ISSUE THREAD

**Issue by MarianoFacundoArch** [shaka-project/shaka-player#6446]
Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
Yes

If the problem is related to FairPlay, have you read the tutorial?
Yes

What version of Shaka Player are you using?
Latest - Master

Can you reproduce the issue with our latest release version?
Yes

Can you reproduce the issue with the latest code from main?
Yes

Are you using the demo app or your own custom app?
Custom app, as it has fairplay

If custom app, can you reproduce the issue using our demo app?
It needs fairplay.

What browser and OS are you using?
Apple Sonoma 14.0

For embedded devices (smart TVs, etc.), what model and firmware version are you using?
Does not apply

What are the manifest and license server URIs?
Custom, it is a working Fairplay server

What configuration are you using? What is the output of player.getConfiguration()?
Default values, with apple fairplay and useNativeHlsOnSafari in false

What did you do?
Turn to false useNativeHlsOnSafari

What did you expect to happen?
Video to play normally

What actually happened?
Video plays shortly when it starts, than completely stuck, not even seeking.

**Comment by avelad** [comment]
> **What are the manifest and license server URIs?**
>
> Custom, it is a working Fairplay server

Quoting the issue template:

```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.
```

**Comment by MarianoFacundoArch** [comment]
Hi Avelad, unfortunately, I cannot provide a URL because it is locally running!
And it is not related to the issue, everything works perfectly until we turn on useNativeHlsOnSafari

**Comment by MarianoFacundoArch** [comment]
Hi Avelad!
I can do a tunnel to the local DRM service if that helps. 
Also, I think this demo is not using useNativeHlsOnSafari as the X-Playback-Session-Id is being added. Maybe I am missing something in the configuration itself to force it not to use native Hls?
X-Playback-Session-Id: 27EFA8FB-62CB-4F6B-9C02-221264F4C2DC

**Comment by avelad** [comment]
Since you cannot provide a test stream, we cannot help you further. If you want to debug the issue yourself and create a PR, we will be happy to review it.

**Comment by MarianoFacundoArch** [comment]
I can upload a test myself without any issues! Do you want a demo player using a demo stream with that feature turned on?

**Comment by avelad** [comment]
For me is working with: https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=es-ES;textlang=es-ES;uilang=es-ES;asset=https://na-fps.ezdrm.com/demo/ezdrm/master.m3u8;panel=ALL_CONTENT;panelData=drm:FAIRPLAY;build=uncompiled 
I'm using Safari 13.1 with macOS 14.3

**Comment by MarianoFacundoArch** [comment]
Yes, bu tit is not with useNativeHlsOnSafari to false.
The problem is when useNativeHlsOnSafari is false

**Comment by MarianoFacundoArch** [comment]
With the release done yesterday and changing useNativeHlsOnSafari to use 

        useNativeHlsForFairPlay: false,
        preferNativeHls: false,


Apparently works with no problem. My doubt here is why the quality selector is not being shown, if this is no longer native hls?
