### ISSUE TITLE
Issue: 6399 Avoid duplicate AES requests 4.x Releases?

### ISSUE THREAD

**Issue by stuartflanagan** [shaka-project/shaka-player#6451]
**Please ask your question**
At present we are trying to work around this issue by increasing buffer size to give more tolerance for slower license requests.
I did see that the issue: https://github.com/shaka-project/shaka-player/pull/6399 had been merged and was hoping it would make it into latest 4.7 releases as well as 5.0.
I do not see it listed in the release notes though. If it has not been included would it be possible to have in backwards compatible releases?

**Comment by avelad** [comment]
We plan to release version 4.8 soon, which will include this change.
