### ISSUE TITLE
Support for getAllThumbnails API with multi period manifest

### ISSUE THREAD

**Issue by burugupalli** [shaka-project/shaka-player#6461]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Yes, current implementation of getAllThumbnails API is returning thumb nails for manifest with only one period. If the manifest has multiple periods, API doesn't return anything.

**Describe the solution you'd like**

getAllThumbnails API should work and return the thumbnails for any type of manifest

**Describe alternatives you've considered**

**Additional context**

**Comment by avelad** [comment]
@burugupalli  Please provide a sample stream in order to implement this. Thanks!

**Comment by avelad** [comment]
I can work on it soon if the stream is provided

**Comment by burugupalli** [comment]
@avelad  Do you still need a stream?

**Comment by avelad** [comment]
> @avelad Do you still need a stream?

I have tried another, if you give me yours I will verify that the fix works well with yours.

**Comment by burugupalli** [comment]
@avelad Below is the stream.

https://content.uplynk.com/preplay/ext/5a83ec1bb4db4b739b568ec951b4327c/NBCU2653964000110015-1708398186.json?v=2&expand=qlv&ad=qlv_vod&ad.ua=Dalvik%2F2.1.0+%28Linux%3B+U%3B+Android+11%3B+Stream+TV+Build%2FRTT4.230821.001%29&ad.cid=NBCU2653964000110017&ad.dev=SETTOP&ad.hhid=da4e96642268a854c6a55557f7da0a794cb13e671d048d2e53fcaa88f62cf045&ad.ifa=ac24f7f2-bdcc-4750-855f-321e1b4200e7&ad.ifatype=adid&ad.ip=47.203.131.0&ad.lmt=False&ad.prov=bravotv.com&ad.sess=1&ad.devid=856a2aca871237971130c407f6d15886b2f1d1839ba8e067458e206ee0a19ae1&ad.ts=1713449497&ad.tz=-5&ad.vip=47.203.131.0&ad.zc=10452&rmt=pr&pr.require_hdcp_type_1=False&pr.license_begin_seconds=0&pr.digital_video_protection_level=250&pr.securitylevel=2000&pr.version=2&resolutions=0-2160&tc=1&rn=2626868520&ct=a&oid=5a83ec1bb4db4b739b568ec951b4327c&eid=NBCU2653964000110015-1708398186&vcodec=avc&pp2ip=0&manifest=mpd&exp=1718634569&euid=856a2aca871237971130c407f6d15886b2f1d1839ba8e067458e206ee0a19ae1&sig=baefd8a4fb7c58aa3132fa7a6f483fed5b99174d203ff3c73022d5193f92d8a2
