### ISSUE TITLE
This is a seekRange() question.

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6467]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**
4.5.11

**What browser and OS are you using?**
chrome Window

**Please ask your question**

I previously asked the above [question ](https://github.com/shaka-project/shaka-player/issues/6423)regarding CMAF HLS live stream time difference reduction.
I've seen the potential to shorten the lag by adjusting the `liveSegmentsDelay` option, but the buffer runs out quickly. The buffer was checked with the code below.
```

logBufferedInfo() {
const position = this.videoElement.currentTime;
let bufferedInfo = { total: 0, played: 0, left: 0 };

for (let i = 0; i < this.videoElement.buffered.length; i++) {
	const start = this.videoElement.buffered.start(i);
	const end = this.videoElement.buffered.end(i);
	const duration = end - start;

	if (start <= position && end > position) {
		bufferedInfo.played += Math.max(0, position - start);
		bufferedInfo.left += Math.max(0, end - position);
	} else if (start > position) {
		bufferedInfo.left += duration;
	} else {
		bufferedInfo.played += duration;
	}

	bufferedInfo.total += duration;
}
const leftFormatted = bufferedInfo.left.toFixed(3);

document.getElementById(
	'logBufferedInfoLabel'
).innerHTML = `Buffer (left/played/total): ${leftFormatted}/${bufferedInfo.played.toFixed(
	3
)}/${bufferedInfo.total.toFixed(3)}`;
}

```

I have a question here.

1. Will playing the last segment when loading using the `player.seekRange().end()` API help reduce time lag?

2. When `liveSegmentsDelay` is set to less than 1.5, leftBuffer becomes 0.00 when playing for 2 to 3 minutes, resulting in buffering. Are the configure settings below the optimal settings?
3. Will Shaka Player help reduce lag when #EXT-X-TARGETDURATION:3 is reduced to 2? I would like to know the relationship between the player and the corresponding tag to shorten the time difference.
```

this.player.configure({
    streaming: {
        bufferingGoal: 30,
        rebufferingGoal: 5,
        lowLatencyMode: true, 
        startAtSegmentBoundary: true,
        retryParameters: {
	        baseDelay: 1000,
	        timeout: 5000, 
	        maxAttempts: 2,
        },
    },
    manifest: {
        hls: {
	        liveSegmentsDelay: 1.5,
        },
        retryParameters: {
	        baseDelay: 1000, 
	        timeout: 5000,
	        maxAttempts: 2, 
        },
    },

```

**Comment by brodiddev** [comment]
May I know why you recommended that option to me?
Why disable Safari's way of finding Live Edge?

**Comment by avelad** [comment]
The way Sfari works is different, it doesn't let you search on a Live stream. In Shaka we have that functionality enabled by default. But if it is disabled we allow seek on a live stream.
