### ISSUE TITLE
AddSeekBar not working

### ISSUE THREAD

**Issue by enricovittorini** [shaka-project/shaka-player#6481]
Live streaming use case:
I am trying to add the seek bar o scroll in the DVR window
using the folllowing shaka
`		<script src="https://ajax.googleapis.com/ajax/libs/shaka-player/4.7.13/shaka-player.ui.js"></script>
		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/shaka-player/4.7.13/controls.css">`

`  const video = document.getElementById('video');
  const ui = video['ui'];
  
  const config = {
  addSeekBar: true,
   seekBarColors: {
   base: 'rgba(255, 255, 255, 0.3)',
   buffered: 'rgba(255, 255, 255, 0.54)',
   played: 'rgb(255, 255, 255)',
 },
  'controlPanelElements': ['play_pause','time_and_duration','mute','volume','language','captions','quality']
};
ui.configure(config);`

The seekbar is not shown

**Comment by avelad** [comment]
Are you using DASH or HLS?

**Comment by enricovittorini** [comment]
@avelad I am using HLS. There must be something to enable for the seekbar for HLS I guess but did not find it in the docs nor I'm the past issues

**Comment by avelad** [comment]
Please use: `player.configure('manifest.hls.useSafariBehaviorForLive', false);`

**Comment by avelad** [comment]
@enricovittorini  Can you confirm that it works for you?

**Comment by enricovittorini** [comment]
@avelad yes it worked. thanks!
