### ISSUE TITLE
Logging : Shaka UI should be in debug?

### ISSUE THREAD

**Issue by xavierlaffargue** [shaka-project/shaka-player#6520]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
lastest

**What browser and OS are you using?**
Chrome

**Please ask your question**
It seems that if we use the Shaka UI library, it must also be debugged for the logs but this is not indicated in the documentation.
Can you confirm that we need the UI library in debug for the logs?

**Comment by joeyparrish** [comment]
Most logging is disabled at compile-time in production builds.  This is true for both UI and non-UI builds.

Debug builds have logging enabled and configurable at runtime.  The debugging strings make these builds larger.

Does this help?
