### ISSUE TITLE
Failed to execute 'createElement' on 'Document'

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#6524]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

4.8.1

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
ChromeOS stable 123

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/tos-ttml/dash.mpd;panel=ALL_CONTENT;panelData=LIVE

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
N/A

**What did you do?**

Load the content

**What did you expect to happen?**
Content plays

**What actually happened?**

Content fails with error `Failed to execute 'createElement' on 'Document': The tag name provided ('?xml') is not a valid name.`  This appears to be caused by a backward-compatibility feature we added for 4.8.0 to make tXml compatible with DOMParser.

**Comment by avelad** [comment]
I can't reproduce the error on macOS. @joeyparrish, is this a ChromeOS specific problem?
