### ISSUE TITLE
Support time shifting in live streams using IndexedDB to store media segment

### ISSUE THREAD

**Issue by caridley** [shaka-project/shaka-player#6528]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

We would like to be able timeshift in a live stream within a rolling window that extends up to 90 minutes behind the current time. 

**Describe alternatives you've considered**

Store media segments in IndexedDB as they are for downloaded VOD content. 

**Additional context**

**Comment by joeyparrish** [comment]
Could you make 90 minutes of content available in the live stream by expanding the availability window?
