### ISSUE TITLE
How to run shaka player at custom domain for testing

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#6529]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.6.3

**What browser and OS are you using?**
- Browser: Chrome  124.0.6367.119
- OS: Window 11 Pro, 64 bit

**Please ask your question**
I am developing my app for testing stream url using framework nuxt v2.
Due to security reason, localhost is not allowed to run stream.
In dev mode, stream link can be only played at http://abc.mycompany.com. In which abc.mycompany.com is our custom hostname for localhost, configured in host file:
127.0.0.1 abc.mycompany.com.

I know shaka player require https or localhost to run. But is there any way in this case?
I already tried to run https but no luck: https://abc.mycompany.com.

Hope to here from you soon

**Comment by joeyparrish** [comment]
Sorry, the requirement to use https or localhost ("secure contexts") comes from the web platform and the browser, not the player.

For specific browsers, you can work around this with command-line flags.  For example, in Chrome, you can use [this](https://peter.sh/experiments/chromium-command-line-switches/#unsafely-treat-insecure-origin-as-secure):

> `--unsafely-treat-insecure-origin-as-secure`
>
> Treat given (insecure) origins as secure origins. Multiple origins can be supplied as a comma-separated list. 
> Example: `--unsafely-treat-insecure-origin-as-secure=http://a.test,http://b.test`

There are probably flags available for Firefox testing as well.  Edge and Safari tend not to have flags for these sorts of things.

Does this help?

**Comment by joeyparrish** [comment]
Oh, I forgot to add, when you run Chrome with command-line flags, if you already have Chrome running, it will ignore your flags and open your URL in your existing browsing session.  To create a new session, use something like `--user-data-dir=/path/to/blank-user-data-dir` in addition to your other testing flags.

**Comment by vanminhquangtri** [comment]
thanks @joeyparrish , it works.
just a small wonder, when i use videojs, this issue not happen. I can play at my custom domain without having to setup --unsafely-treat-insecure-origin-as-secure.
anyway now it works.
