### ISSUE TITLE
Handle token expiration for API requests

### ISSUE THREAD

**Issue by falk-stefan** [shaka-project/shaka-player#6530]
Any media played in my application requires an access token from the server. However, this access token may expire at some point which is why I need some logic in place in order to refresh the token.

I have found a tutorial for [error handling](https://shaka-player-demo.appspot.com/docs/api/tutorial-errors.html) but it's not really clear to me how I can refresh the token and retry the previous request.

Also, it seems as if the `retry` event is never fired:

```typescript
player.getNetworkingEngine()?.addEventListener('retry', /* .. */);
```

Is it even the right one to use? 

https://shaka-player-demo.appspot.com/docs/api/tutorial-errors.html

**Comment by avelad** [comment]
You can use something like:
```

player.getNetworkingEngine().registerRequestFilter(function(type, request, context) {
  // Only manipulate license responses for example
  if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
    // Do something
  }
});
```

As such there is no retry event.

**Comment by falk-stefan** [comment]
Thanks @avelad for the response.

Not sure if that'll do in my case, however. I am sending a `Bearer <token>` with the `Authorization` header. The server will respond with HTTP 401 and a code `auth/token-expired` - only then I know that the request failed and that I have to refresh the token.

**Comment by joeyparrish** [comment]
You can register a response filter to intercept the HTTP 401.  If you make the filter async, it can refresh the token, then replicate the original request with the new token, and finally insert the new response in place of the first one.

**Comment by joeyparrish** [comment]
This seems common enough, so if you want to propose an API to simplify this process for users, I'd be happy to review it.

**Comment by falk-stefan** [comment]
@joeyparrish thank you! :)

If I get that right then I should be able to do somethign like this:

```typescript
player.getNetworkingEngine()?.registerResponseFilter(async (req, res) => {
  if (res.status === 401) {
    const error = JSON.parse(String(res.data)) as HTTPError;
    if (error.code === 'auth/token-expired') {
      // 1. Refresh token
      // 2. fetch(res.uri)
      // 3. return new response object
    }
  }
  return res;
});
```

**Comment by joeyparrish** [comment]
Roughly, yes.  But you will have to overwrite the fields of `res` in your snippet, rather than return a different object.

You want some of the details from this tutorial (overwriting part of the response):

https://shaka-player-demo.appspot.com/docs/api/tutorial-license-wrapping.html

And some of the details from this tutorial (sending a new async request from a filter):

https://shaka-player-demo.appspot.com/docs/api/tutorial-license-server-auth.html

This could probably use a new tutorial entry if we don't add an explicit API of some kind.

**Comment by absidue** [comment]
The application level redirects tutorial covers both the making of new requests and overwriting the response data, so the code snippet there is probably a good starting point for you: https://shaka-player-demo.appspot.com/docs/api/tutorial-application-level-redirects.html

**Comment by falk-stefan** [comment]
Thanks a lot guys! With that I should be able to fix the issue! :)
