### ISSUE TITLE
Cant use player.attach for playing the next video while creating the functionality for playing the next video

### ISSUE THREAD

**Issue by shubhankarMitra** [shaka-project/shaka-player#6550]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**
4.7.12

**What browser and OS are you using?**
Ubuntu - Chrome and Firefox

**Please ask your question**

`function Shaka({ videoData, getNextEpisodeId = () => {} }) {
    const videRef = useRef(null);
    const [player, setPlayer] = useState(null);

    async function init(videoData) {
        const player = new Shaka.player();
        await player.attach(videoRef.current); //Stops execution here in the second initialization for the next episode
        setPlayer(player);
        //await player.load(videoData.src)
    }

    useEffect(() => {
        //Player initialization code
        init(videoData);
    }, []);

    const handleNext = () => {
        if (player) {
            player.destroy();
        }

        getNextEpisodeId().then((data) => init(data));
    };
    return (
        <div>
            <video ref={videoRef} autoplay />
            <button onClick={handleNext}>Skip Next</button>
        </div>
    );
}`

I have written the code for playing next episode.
The player. attach method does not work the second time i am loading it for the get next episode ,it reachs till there and it stops execution when I am trying to load the second time

**Comment by avelad** [comment]
player.destroy() is a method that returns a promise, you have to wait with await before creating a new player and calling attach.

**Comment by shubhankarMitra** [comment]
okay , i somewhat solved it using await.
but i want to know is this the right way to play the mext episode or there is a better way?

**Comment by avelad** [comment]
Your solution is optimal.
