### ISSUE TITLE
Documented Code Sample for Preload API seems to be incorrect

### ISSUE THREAD

**Issue by SivanA-Kaltura** [shaka-project/shaka-player#6551]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**If the problem is related to FairPlay, have you read the tutorial?**

Not related to Fairplay.

**What version of Shaka Player are you using?**
4.8.2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not sure how to test that.

**Are you using the demo app or your own custom app?**
Custom app:
https://codepen.io/sivana-kaltura/pen/VwOZmmq

**If custom app, can you reproduce the issue using our demo app?**
No (not sure if it contains preload yet).

**What browser and OS are you using?**
MacOs Monterey 12.6.7

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/bbb-dark-truths/dash.mpd
https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd
https://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default configuration.

**What did you do?**

I wanted to test the new preload API.
I searched for documentation and found the following link:
https://github.com/shaka-project/shaka-player/blob/3d1c5467e6c936c4620ae930332c62eeabe54841/docs/design/preload.md

With the following sample usage code:
```
  const player = new shaka.Player();
  
  const loader1 = player.preload('foo1.mpd');
  const loader2 = player.preload('foo2.mpd');
  
  player.attach(video);
  
  player.load(loader1); // The buffered data in loader1 is transferred to
                        // the Player and the MediaSource. loader1 is
                        // invalidated.
  loader2.destroy();    // loader2 is invalidated
```

I set up a test page to preload a media and connect the loader to the player:
https://codepen.io/sivana-kaltura/pen/VwOZmmq

**What did you expect to happen?**
The player should be loading the media via the loader.

**What actually happened?**

The player doesn't load the media.
When passing the resolved value of the promise to the player, it does work.
So either the docs aren't up-to-date or I was looking at the wrong docs for the feature.

**Are you planning send a PR to fix it?**
No.

**Comment by theodab** [comment]
That design doc is an out-of-date candidate that we ended up not using. We should probably just get rid of it, to avoid confusion.
The final API is mostly similar, but the `preload` method is asynchronous. As you noticed in your codepen, you need to wait for the preload manager to be returned.

I'll write a short tutorial on how to use the preload system, for the docs.
