### ISSUE TITLE
3 Line 608 caption displays as 1 line on Safari

### ISSUE THREAD

**Issue by jcekstrom** [shaka-project/shaka-player#6552]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.  There are other caption issues, but not exactly this one.

**If the problem is related to FairPlay, have you read the tutorial?**
608 

**What version of Shaka Player are you using?**

v4.7.13 
nightly

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
I can on the nightly demo page.

**Are you using the demo app or your own custom app?**
Demo app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Mac/Safari displays incorrectly.

Mac / Firefox, Chrome, Edge -> GOOD
Win / Firefox, Chrome, Edge -> Good

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**
https://storage.ekstech.net/video/long_caption_test/master.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

1. Added the URL to the test video
2. Turned on English Captions
3. Rewind / play entire video

**What did you expect to happen?**
A 3 line caption to display.
<img width="480" alt="Screenshot-Good" src="https://github.com/shaka-project/shaka-player/assets/275902/be0a28fa-2e72-4ad6-9459-d9eca5dc246b">

**What actually happened?**
On Mac/Safari all 3 lines appeared to display on the same line.
<img width="645" alt="screenshot-Mac-safari" src="https://github.com/shaka-project/shaka-player/assets/275902/a9e27d72-3152-444f-a194-0f69722a7b5f">

**Are you planning send a PR to fix it?**
Not yet.

**Comment by jcekstrom** [comment]
A couple of more notes:

1. If played in Safari, without the Shaka Player, it has the same issue.  I'm not sure how HLS playout is implemented for Safari, but it appears to use the same pathway whether Shaka is used or not.
2. Quicktime/Mac displays captions correctly.

**Comment by avelad** [comment]
From what you say in your last comment, it is a Safari issue that we cannot fix, sorry.
