### ISSUE TITLE
Unexpected buffer range for reference on old device

### ISSUE THREAD

**Issue by Wyyyned** [shaka-project/shaka-player#6564]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.8.3

**Can you reproduce the issue with our latest release version?**
No

**Can you reproduce the issue with the latest code from `main`?**
Haven't tried

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Haven't tried

**What browser and OS are you using?**
Chrome 124.0.6367.119 works fine with the same server
VEWD Safari 5.1 (old tv) works fine without seeking

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Hisense - not sure

**What are the manifest and license server URIs?**
Stremio server url (Hard to get long lasting url)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
Default

**What did you do?**
Playing a stream and seeking forward on the TV.

**What did you expect to happen?**
Behave the same as it does on the PC.

**What actually happened?**
I can play the same stream on my PC and seek as many times as i want with no issues, but when seeking on the TV i get 'Possible encoding problem detected, Unexpected buffered range for reference', and the difference is quite big (220 - 224 but got 436 - 439), playing it normally works just fine but i read on another issue about the segment behaviour without seeking

TV:
![Inked20240509_023949_LI](https://github.com/shaka-project/shaka-player/assets/29341606/e45386e4-19cf-43cd-ba79-3db9bb9cb813)
PC:
![Screenshot_2](https://github.com/shaka-project/shaka-player/assets/29341606/c3ef90d5-7df4-45cb-84bd-a0cac13e58ce)

**Are you planning send a PR to fix it?**

**Comment by avelad** [comment]
VEWD is not a device that we have on the supported list, so we cannot know what the problem is. If you want to send a PR to fix what's wrong, we'll be happy to review it. Thank you!

**Comment by Wyyyned** [comment]
Copy that, any advice on how i could debug this issue?,  is something that I might be able to address or find a workaround? Or such old tvs are a no go. Thanks for your response!

**Comment by Wyyyned** [comment]
I know what it is, im not sure why it only happens on VEWD. It was caused by hls sequenceMode.

```javascript
//hls/hls_parser.js:767
this.manifest_ = {
  presentationTimeline: this.presentationTimeline_,
  variants,
  textStreams,
  imageStreams,
  offlineSessionIds: [],
  minBufferTime: 0,
> sequenceMode: true,
};
```
Setting sequenceMode to false works perfectly, also `player.configure('manifest.hls.sequenceMode', false)` does not work.

**Comment by Wyyyned** [comment]
I modified the source code, thats the snipped i posted `hls/hls_parser.js:767`
