### ISSUE TITLE
How can i add eventlistener like click doubleclick to player

### ISSUE THREAD

**Issue by Samta1997** [shaka-project/shaka-player#6566]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes
**If the question is related to FairPlay, have you read the tutorial?**

not related to fair play

**What version of Shaka Player are you using?**
4.8.2

**What browser and OS are you using?**
chrome and window11

**Please ask your question**
I have been trying to add gesture based feature like single tap, double tap on video player. But i am not able to add event listener to it. When i am single clicking it play or pause. How can i add my custom event listener to it?

const initPlayer = async () => {
      const player = new shaka.Player();
      const video=document.getElementById('video')
      await player.attach(video)
      window.player=player
      player.load(manifest)
      player.addEventListener('click',handleclick)
    };

**Comment by joeyparrish** [comment]
Click events hit DOM elements like the video tag, but not the player.  The player isn't a DOM element.  I hope this helps!

**Comment by Samta1997** [comment]
Thanks for replying. It worked. 
Thanks for great player.
