### ISSUE TITLE
There is a 6 second buffer and then suddenly disappears.

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6574]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**
4.7.11

**What browser and OS are you using?**
window

**Please ask your question**
Why does the current Buffer go from 6.1234 to 2.9455 in 503ms?
![image](https://github.com/shaka-project/shaka-player/assets/136538250/045e3829-c460-4b59-a7dc-e3da4e0a6b99)

I am making the settings below.
```

streaming: {
    useNativeHlsOnSafari: true,
    bufferingGoal: 5,
    bufferBehind: 5,
    rebufferingGoal: 4,
    lowLatencyMode: true,
    startAtSegmentBoundary: true,
    liveSync: true,
    liveSyncMaxLatency: 5,
    liveSyncMinLatency: 4,
    liveSyncPlaybackRate: 1.1,
    updateIntervalSeconds: 0.5,
    retryParameters: { baseDelay: 1000, timeout: 5000, maxAttempts: 2 },
  },
  manifest: {
    hls: {
      liveSegmentsDelay: 1.2,
    },
    retryParameters: { baseDelay: 1000, timeout: 5000, maxAttempts: 2 },
  },
```

**Comment by joeyparrish** [comment]
I don't know.  Please use the bug template and give us the information we need to reproduce the issue.  Please do not skip or delete any fields of the template.  Thanks!
