### ISSUE TITLE
Summary of known compiler issues

### ISSUE THREAD

**Issue by seanbecker15** [shaka-project/shaka-player#6578]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**
3.2.1

**What browser and OS are you using?**
Too many to list :)

**Please ask your question**
We are currently using the debug version of Shaka in production because we have noticed issues with the compiled version of 3.2.1. Upgrading versions is on our roadmap, but I recall reading a few thread that related to compiler issues. I also recall reading about a large change to the compiler near the time of 3.x or 4.x. Any way we could get some more information about what was changed and how the compiler behaves differently? Links to relevant issues, PRs, and commits would all be greatly appreciated. Anything would help.

For reference, I searched through the issues and PRs but it seems like this might be something that spans over quite a few issues and quite a few years, so figured it might be best to just ask for a summary.

**Comment by joeyparrish** [comment]
Sorry, we don't have any such list here.  You can look at the changelog of the compiler: https://github.com/google/closure-compiler and compare that to the history of package.json where we made compiler changes.

Our last update to the compiler was 28b73b921d1dbdc6d7e016aa8e0a000e62318ed3 in Nov 2022, and before that it was 6f274cbc972233b2653a4f34f24edf0950a84944 in March 2022, and before that it was c482e81ad975c4eef654e26cf4b273541a2abcd0 in February 2022, and before that it was 87797157af7083e020c29ba84a0a806d2ab1f07b in May 2021.

I found these by `git log -p package.json` and then searching for `^-.*compiler-java`.

We don't plan to upgrade the Closure Compiler again, as we hope to move to TypeScript later this year.

I hope that helps!

**Comment by seanbecker15** [comment]
@joeyparrish that helps a lot, thanks! Looking forward to the TypeScript upgrade. We've currently got a shim that interfaces with Shaka but with TS support we could probably remove that shim.

Feel free to close this issue at your convenience.
