### ISSUE TITLE
Selecting of default audio track on loading for MPD manifests

### ISSUE THREAD

**Issue by SergeiBel** [shaka-project/shaka-player#6599]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
~4.3.4

**What browser and OS are you using?**
Chrome, Ubuntu 20.04

**Please ask your question**
I have multiple audio tracks in my player already implemented, but i was faced the problem that i need to select a default audio  track from the mpd manifest. I used getVariantTracks method from Shaka-player, but after investigation of our codebase i found that method which used [there](https://shaka-player-demo.appspot.com/docs/api/lib_util_stream_utils.js.html#line1193) does not return any data from asset file, which related to the default audio track. I did not find any way how to get this data from the variant using your lib. 

Maybe you can give me some advice how to get this option or how can i manage audio tracks in order to select the default one on player initialization?

**Comment by Robloche** [comment]
Are you looking for the default audio track from the MDP manifest or are you trying to select a specific audio track at startup?

If it's the latter, you can use `preferredAudioLanguage` when configuring the player:
```
shaka.configure({preferredAudioLanguage: 'en'});
```

**Comment by joeyparrish** [comment]
Preferred language and role should be your first try.  If that isn't detailed enough, you can use the player's `streaming` event to make track selections between manifest parsing and ABR selections.
