### ISSUE TITLE
Shaka Player is not playing the complete content duration

### ISSUE THREAD

**Issue by burugupalli** [shaka-project/shaka-player#6612]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Problem not related to FairPlay

**What version of Shaka Player are you using?**

4.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Chrome on Mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

Shaka Player Demo Link with custom content: https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://content-ause1-uu-fios1.uplynk.com/preplay2/7b8fe4f3ea644312912b01a41c50d3d8/527714cb231e6d33e14c57546fe082aa/7OheISeaXrmVhTLanBcB9L3a8Z8fKOuMgvJkkutPnAwp.mpd?pbs=4226b21719884eb484e031baef621d11;panel=CUSTOM%20CONTENT;build=uncompiled

Manifest URI: https://content-ause1-uu-fios1.uplynk.com/preplay2/7b8fe4f3ea644312912b01a41c50d3d8/527714cb231e6d33e14c57546fe082aa/7OheISeaXrmVhTLanBcB9L3a8Z8fKOuMgvJkkutPnAwp.mpd?pbs=4226b21719884eb484e031baef621d11

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

Playing a custom asset in the demo app, content duration is ~44 Minutes, Shaka player play only for approximately 19 minutes and then stops

**What did you expect to happen?**
Content should be played for complete duration

**What actually happened?**

**Are you planning send a PR to fix it?**
No

**Comment by avelad** [comment]
Your manifest returns 403

**Comment by avelad** [comment]
It looks like your manifest has 10 periods, 4 periods use segmentList and 6 periods use segmentTemplate. The parser is not prepared for this mixture and gives incorrect behavior. I'm going to let @joeyparrish tell you what the best way to proceed is.

**Comment by joeyparrish** [comment]
@burugupalli, what encoder/packager are you using?  How much control do you have over the packaging side?

**Comment by burugupalli** [comment]
@joeyparrish  We get the manifest from 3rd party and currently don't have any control over it. The same manifest is working and playing fine with other players.

**Comment by avelad** [comment]
@burugupalli It appears that its content has been updated and is now working correctly.
