### ISSUE TITLE
I want to keep the remaining buffer constant.

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6622]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**
4.8.4

**What browser and OS are you using?**
window chrome

**Please ask your question**
I want to keep the remaining buffer constant.
leftFormatted in the code below is currently staying at 5-6 seconds.

I want to keep it at 3-4 seconds, so how about adjusting liveSegmentsDelay to 2 if the remaining buffer (leftFormatted) is more than 5, and 4 if it is less than 2?

Is there a better way?

### leftBuffer
```
	calculateBufferedInfo(videoElement) {
		const position = videoElement.currentTime;
		let bufferedInfo = { total: 0, played: 0, left: 0 };

		for (let i = 0; i < videoElement.buffered.length; i++) {
			const start = videoElement.buffered.start(i);
			const end = videoElement.buffered.end(i);
			const duration = end - start;

			if (start <= position && end > position) {
				bufferedInfo.played += Math.max(0, position - start);
				bufferedInfo.left += Math.max(0, end - position);
			} else if (start > position) {
				bufferedInfo.left += duration;
			} else {
				bufferedInfo.played += duration;
			}

			bufferedInfo.total += duration;
		}
		const leftFormatted = bufferedInfo.left.toFixed(3);
		const playedFormatted = bufferedInfo.played.toFixed(3);
		const totalFormatted = bufferedInfo.total.toFixed(3);

		return { leftFormatted, playedFormatted, totalFormatted };
	}
```

### config
```
		abr: { enabled: false },
		streaming: {
			rebufferingGoal: 2,
			bufferingGoal: 10,
			bufferBehind: 30,
            }
```

**Comment by joeyparrish** [comment]
> I want to keep the remaining buffer constant.

How strictly do you expect "constant" to be?  Shaka downloads whole segments by default, so you can be at your target +/- (segment length + network delay).

**Comment by brodiddev** [comment]
Can I use liveSyncMinLatency and liveSyncMaxLatency to set the settings below to keep the remaining buffer between 2 and 2.5 seconds?

```
streaming: {
rebufferingGoal: 2;
bufferingGoal: 5,
useNativeHlsOnSafari: true;
lowLatencyMode: true,
liveSync: true;
liveSyncMaxLatency: 2.5,
liveSyncMinLatency: 2,
},
manifest: {
hls: {
liveSegmentsDelay: 1.5,
},
},
```

**Comment by joeyparrish** [comment]
Seems reasonable

**Comment by brodiddev** [comment]
many thanks :)
