### ISSUE TITLE
Segement downloaded in 5 ms, wrong information 

### ISSUE THREAD

**Issue by Iragne** [shaka-project/shaka-player#6623]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**If the question is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**
Latest

**What browser and OS are you using?**
Firefox

**Please ask your question**
When i looked to how the player is behaving against bandwidth changed i found that the network engine was sending wired information to the ABR manager 

Segment downloaded: contentType=video deltaTimeMs=5 numBytes=132328 lastTimeChosenMs=1715701213390 enabled=true

Segment downloaded: contentType=video deltaTimeMs=153 numBytes=71224 lastTimeChosenMs=1715701213390 enabled=true

Segment downloaded: contentType=video deltaTimeMs=604 

**deltaTimeMs=5**  so much data in so short time is quite wired to me. is that something possible can it be linked to wrong information.
have you experience it  ?

Should we put some filter to avoid to count that value inside the ABR manager 
![Screenshot 2024-05-14 at 17 40 20](https://github.com/shaka-project/shaka-player/assets/1516807/d2684ea0-276f-4f9c-adfd-56d67c62c285)

**Comment by Iragne** [comment]
additionally  we are only passing information of the bandwidth during the on-progress and never at the end of the download of the segment. I'm wondering if we should also add it when the download is ended. event if it's kind of duplicate

**Comment by joeyparrish** [comment]
> **deltaTimeMs=5** so much data in so short time is quite wired to me. is that something possible can it be linked to wrong information.

Browser caching could explain bad data being fed to ABR manager.  Can you try again with caching disabled/cleared in your browser?

**Comment by Iragne** [comment]
@joeyparrish  sorry i should mention this but the test had been done with cache disable on FF

**Comment by avelad** [comment]
We should use something like https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/models/ThroughputModel.js#L250

Since I want to make improvements to the ABR, I assign it to myself and move to improvement.

**Comment by jeanalexandre-iragne-deltatre** [comment]
@avelad  that is lovely i was pushing the same PR you were too fast !!!! thanks

**Comment by Iragne** [comment]
@avelad  that is lovely i was pushing the same PR you were too fast !!!! thanks
