### ISSUE TITLE
HLSParser: MEDIA_SEGMENT request in getMediaPlaylistBasicInfo_ causes load latency

### ISSUE THREAD

**Issue by yyamaguchi93** [shaka-project/shaka-player#6627]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**If the question is related to FairPlay, have you read the tutorial?**
 N/A

**What version of Shaka Player are you using?** v4.8.4

**What browser and OS are you using?** MacOS Sonoma 14.4.1 Google Chrome

**Please ask your question**
When loading a DRM HLS content to the Shaka Player, the second MEDIA_SEGMENT request made in getMediaPlaylistBasicInfo_ in HLS Parser causes significant delay when loading manifest by fetching the entire media segment.

In the screenshot, the second request with the size of 157MB is fetched. Is this necessary? Is there a way to workaround this? 
![Screenshot 2024-05-16 at 3 50 12 PM](https://github.com/shaka-project/shaka-player/assets/132605593/b471269b-903d-4677-b31a-1615afa52aaa)

Code Snippet:
```
player.configure(
drm: { 'com.widevine.alpha': <licenseServerURL> },
manifest: {
   hls: { mediaPlaylistFullMimeType: 'audio/mp4; codecs="mp4a.40.2"' }
}
}
player.load("https://test.com/v1/manifest-translator/manifests/hls/com.widevine.alpha/236a494a9b504d7f226234827468b62ac82f52a5/audio/10/master.m3u8");
...
```
Example manifest file:
[master.m3u8.txt](https://github.com/shaka-project/shaka-player/files/15341741/master.m3u8.txt)

**Comment by avelad** [comment]
There is a bug when load a Media Playlist that uses byterange.
