### ISSUE TITLE
abr is false, but master.m3u8 plays the highest quality.

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6628]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**
4.8.4

**What browser and OS are you using?**
window chrome

**Please ask your question**
abr is false, but master.m3u8 plays the highest quality.
After player.load, I selected the lowest quality, but in the network tab it calls the highest quality and plays the low quality.

At this time, an adaptation event is triggered. Why does that event occur even when abr false?

Is there a way to play back the lower quality I selected from the beginning?

**Comment by avelad** [comment]
You can use the following configuration to achieve the behavior you want:

```
{
  abr: {
    enabled: false,
    useNetworkInformation: false,
    defaultBandwidthEstimate: 1e5, // 100kbps 
  }
}
```

**Comment by brodiddev** [comment]
thanks!

**Comment by brodiddev** [comment]
@avelad 
There is a problem calling 1080p quality playlist, mp4v, and mp4a when watching 360p quality.
In order to always call only the playlist with the quality you want to watch, we set the minHeight and maxHeight of restrictions to 360.
When playing, the 1080p quality playlist is no longer called, but only the 360p playlist, but when abr is applied, the picture quality does not increase beyond 360p.
Is there a good way to solve this?

**Comment by joeyparrish** [comment]
If you restrict the player from accessing 1080p content (`restrictions`), it will not be able to access 1080p content.  If you want ABR to function, it must be enabled (the default) and you must remove the restriction `maxHeight: 360`.

**Comment by brodiddev** [comment]
understand thanks
