### ISSUE TITLE
Unable to change between Eng audio tracks on Angel One

### ISSUE THREAD

**Issue by david-hm-morgan** [shaka-project/shaka-player#6645]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**
`v4.8.5-uncompiled`

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
The demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
`Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
uri= `https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd`

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

- Select the `Angel One` stream from the demo.
- Pull up the menu for languages and see there are two `English` tracks
- Attempt to change from the default `English` to the other one.
- Attempt to change back to the previous

**What did you expect to happen?**
Other track would be shown as selected in the menu - in response to the selection.
Segments would be downloaded for the different one:
`audio_en_2c_128k_aac.mp4` <-> `audio_en_2c_64k_opus.webm`

**What actually happened?**

First change accepted, but from second onwards there is no apparent change of selection.
Segments downloaded from the other track, but fall back to downloading the first.

![image](https://github.com/shaka-project/shaka-player/assets/37144605/1f4a4e7d-1d02-4b2b-95d9-c1fb0de65861)

**Comment by avelad** [comment]
The behavior is correct. Because there are two tracks with different roles. AAC has no role and OPUS uses the main role.
