### ISSUE TITLE
"Changing tracks while abr manager is enabled" warning clarification.  

### ISSUE THREAD

**Issue by Kerryliu** [shaka-project/shaka-player#6665]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes 

**What version of Shaka Player are you using?**
`4.8.5`

**What browser and OS are you using?**
Chrome `125.0.6422.61`.  Windows 11.  

**Please ask your question**
I'm getting the following warning when calling `player.selectAudioLanguage`. E.g.: `player.selectAudioLanguage("en", "public.accessibility.describes-video");`.  Other than the warning, the audio track changes, as expected. 

```
Changing tracks while abr manager is enabled will likely result in the selected track being overriden. Consider disabling abr before calling selectVariantTrack().
```

If this is the incorrect method to use for changing audio tracks, please let me know.  However, this warning seems to also occur on the Shaka Player Demo site when changing audio tracks, so I'm not sure if this is a harmless warning or something that I should investigate further.

**Comment by avelad** [comment]
This shouldn't happen, I'm going to work on fixing it.
