### ISSUE TITLE
Let ABR manager know about prefetched streams

### ISSUE THREAD

**Issue by gkatsev** [shaka-project/shaka-player#6673]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

This is partly related to an issue we saw when enabling multiple audio track prefetches. If a lot of streams are prefetched, this could potentially impact the ABR algorithm. If the ABR manager knows about which streams are prefetched, it might be able to make a more intelligent decision.

**Describe the solution you'd like**

This involves letting the ABR manager know which streams got enabled for prefetching in the streaming engine.

- Add `setPrefetchStreams` to ABR Manager. This will receive a list of all the streams that are being prefetched.
- Add `setPrefetchStreams` to the streaming engine's player interface. This would allow the streaming engine to collate all the streams that are prefetched. Then the Player can shuttle it across to the ABR manager.
- The Simple ABR Manager could implement this as a noop.

While the ABR manager deals with variants and the streaming engine deals with streams, the ABR manager has access to the individual streams via the properties on the variants, which is why for simplicity, we directly push the list of streams from the streaming engine to the ABR manager.

This is a bit of a speculative addition. We don't currently have any ideas on how to use it immediately but thought it would be helpful to have, particularly when we circle back around to this.

**Describe alternatives you've considered**

The main alternative is to do nothing and either hard-code values into a custom abr manager or tweak the number of segments being prefetched.

**Additional context**

**Are you planning to send a PR to add it?**
I can make a PR for this if there's consensus around this addition.

**Comment by avelad** [comment]
I agree to add this if we also add it to the SimpleAbrManager
