### ISSUE TITLE
Previously registered requestFilters are not used in the NetworkingEngine for a PreloadManager.

### ISSUE THREAD

**Issue by jason-s13r** [shaka-project/shaka-player#6698]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, though this #6616 closed issue is similar and I left a comment there.

**If the problem is related to FairPlay, have you read the tutorial?**
No.

**What version of Shaka Player are you using?**
4.8.7.

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `main`?**
Yes.

**Are you using the demo app or your own custom app?**
Custom.

**If custom app, can you reproduce the issue using our demo app?**
Yes.

**What browser and OS are you using?**
Chrome, Safari; Windows, MacOS.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
From demo.

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
With default from demo.

**What did you do?**

We've been having trouble with `shaka.media.PreloadManager` not sending cookies with preload requests despite the _player_'s networking engine having a request filter to set `request.allowCrossSiteCredentials = true`.

I believe that this is due to the `shaka.Player.makePreloadManager_` creating a networking engine for the preload manager in [/lib/player.js#L2109](https://github.com/shaka-project/shaka-player/blob/c541515995f630573fa545f8478e65fb15585019/lib/player.js#L2109).
`const networkingEngine = this.createNetworkingEngine(getPreloadManager);`

This new networking engine has empty sets for `requestFilters_` and `responseFilters_` for the preload manager.

I think a PreloadManager should expose a getNetworkingEngine(), and/or copy the sets from the player's networking engine, or use the same networking engine.

Using the Shaka demo website with uncompiled v4.8.7, I can use in the JS console:

```javascript
const player = new shaka.Player();
await player.attach(document.getElementById('video'));

player.getNetworkingEngine().registerRequestFilter(function (_type, request) {
  request.uris = request.uris.map(uri => uri + (uri.includes('?') ? '&' : '?') + '__viaRequestFilter=true');
});

const manager = await player.preload(shakaAssets.testAssets[1].manifestUri);
manager.networkingEngine_.registerRequestFilter(function (_type, request) {
  request.uris = request.uris.map(uri => uri + (uri.includes('?') ? '&' : '?') + '__preload=true');
});


const manager2 = await player.preload(shakaAssets.testAssets[1].manifestUri);
```

**What did you expect to happen?**
I expected requests made from a PreloadManager to have the adjustments made by the registered request filter from the player's networking engine (ie, contains `?__viaRequestFilter=true`).
In our custom app, this would be to set `request.allowCrossSiteCredentials = true`. 

**What actually happened?**
Manifest requests are preloaded as-expected, using the request filters previously registered with `player.getNetworkingEngine().registerRequestFilter()`.
But the preloaded segment requests, and perhaps other requests types, do not appear to use the same filters.
In our custom app, the failure to set `request.allowCrossSiteCredentials = true` causes 403 on the preloaded requests.

![image](https://github.com/shaka-project/shaka-player/assets/284461/e1ca3d05-b831-409c-b3e2-9e7382d67b5a)

**Are you planning send a PR to fix it?**
Perhaps, at least to add `getNetworkingEngine()` to `shaka.media.PreloadManager`.

**Comment by jason-s13r** [comment]
Here's a suggested fix.

https://github.com/jason-s13r/shaka-player/commit/044bae7ad2835f0e8bbdcf12e4d62200f84d05fc

**Comment by theodab** [comment]
That solution could work, but I don't want to offload too much of the work in getting the preload system to work onto the developer. It should ideally be as painless as possible to adopt.

For various technical reasons (stuff like tracking stats) we make a new networking engine for each preload manager.
Changing that might be possible, but I fear it'd be complicated. Instead, it might be easier to just have the new networking engine copy over any filter present in the player's networking engine, at the time the preload manager was made. Unless someone makes a habit of changing networking filters mid-playback, that should be a fairly simple-to-implement change that solves this issue. I'll give it a try.

**Comment by jason-s13r** [comment]
Yep, agree on making it easy for the application developer.

The [commit](https://github.com/jason-s13r/shaka-player/commit/044bae7ad2835f0e8bbdcf12e4d62200f84d05fc) I made used that approach to copy each of the requestFilters_ from the Player's networking engine to the PreloadManager's networking engine. As well as the responseFilters_.

I'll be happy to open a PR with that commit.

**Comment by avelad** [comment]
@jason-s13r see: https://github.com/shaka-project/shaka-player/pull/6709

**Comment by theodab** [comment]
Whoops, I totally did not notice the commit you linked.
Oh well. I guess I'll take it as a vote of confidence that the PR we just merged is a solution that will work for you.
