### ISSUE TITLE
 Issue Playing MPEG-4 part 2 Video with MP3 Audio Using Shaka Player

### ISSUE THREAD

**Issue by iptvsmartws** [shaka-project/shaka-player#6733]
Hello Shaka Player Team,

I'm having trouble playing a specific video file using Shaka Player, and I would appreciate your assistance.

Details:

Video File Info:
Title: testvid
Container Extension: MKV
Video Codec: MPEG-4 part 2 (codec_name: mpeg4, codec_long_name: MPEG-4 part 2, profile: Advanced Simple Profile)
Audio Codec: MP3 (codec_name: mp3, codec_long_name: MP3 (MPEG audio layer 3))
Resolution: 720x404
Frame Rate: 25 fps
Duration: 00:43:26
JSON Info:

json
Copy code
{
 
   "container_extension": "mkv",
    "info": {
        "movie_image": "",
        "plot": "",
        "rating": "",
        "releasedate": "",
        "duration_secs": 2606,
        "duration": "00:43:26",
        "video": {
            "index": 0,
            "codec_name": "mpeg4",
            "codec_long_name": "MPEG-4 part 2",
            "profile": "Advanced Simple Profile",
            "codec_type": "video",
            "codec_time_base": "1/25",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 720,
            "height": 404,
            "coded_width": 720,
            "coded_height": 404,
            "has_b_frames": 1,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "180:101",
            "pix_fmt": "yuv420p",
            "level": 5,
            "chroma_location": "left",
            "refs": 1,
            "quarter_sample": "false",
            "divx_packed": "false",
            "r_frame_rate": "25/1",
            "avg_frame_rate": "25/1",
            "time_base": "1/1000",
            "start_pts": 40,
            "start_time": "0.040000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "DURATION": "00:43:26.800000000"
            }
        },
        "audio": {
            "index": 1,
            "codec_name": "mp3",
            "codec_long_name": "MP3 (MPEG audio layer 3)",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "s16p",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bit_rate": "128000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "DURATION": "00:43:26.808000000"
            }
        },
        "bitrate": 1122
    },
    "custom_sid": "",
    "added": "1521197459",
    "season": 1,
    "direct_source": ""
}
Issue:
I have tried loading the video using Shaka Player 4.9.1, but I receive an error message indicating that the media could not be loaded. The error code is 4, with a message stating, "The media could not be loaded, either because the server or network failed or because the format is not supported."

Additional Notes:

I have confirmed that the video plays correctly in VLC.
The video and audio codecs (MPEG-4 part 2 and MP3) should be supported based on the documentation.
Could you please assist me in identifying the issue and provide guidance on how to successfully play this video using Shaka Player?

Thank you for your support!

**Comment by absidue** [comment]
Single file playback is handled by the web browser itself, so that error is coming from your web browser saying it doesn't support the file.

As mentioned by other people in all of your previous issues, you should switch to using DASH or HLS, instead of continuing do try to do things that web browsers don't support.

**Comment by avelad** [comment]
@absidue  answer is correct.
