### ISSUE TITLE
changing textdisplayfactory creates bogus subtitle track with native webm video.

### ISSUE THREAD

**Issue by mrx1983** [shaka-project/shaka-player#6747]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**

4.8.5

**Are you using the demo app or your own custom app?**
own website

**What browser and OS are you using?**
windows 10, chrome

**What did you do?**
i configured the player with:
`.configure('textDisplayFactory', () => new shaka.text.SimpleTextDisplayer(video));`

**What did you expect to happen?**
that i can play the subtitles on the native video element (not on the ui).
i want that for consistency, regardless if i play an mpd file or webm, it should use the native video element to display the sub.

**What actually happened?**
it plays the subtitles on the native video element, but if i load a native webm, it seems to produce an additional bogus track with the name "undetermined". this at least was not the case with version 4.4.3 that i had used at the end of 2023.
i probably could work around it by setting the display factory only when i load an mpd (not tested that yet).

**Are you planning send a PR to fix it?**
again, maybe the professionals here can do that.

**Comment by avelad** [comment]
This issue has a priority 4, so no one on the maintainer team will resolve it in the short/middle term.

**Comment by mrx1983** [comment]
want so share an finding that i made, when i change the code line to this:
`.configure('textDisplayFactory', () => new shaka.text.SimpleTextDisplayer(video,"Shaka Player TextTrack"));`
it apparently not creates the bogus track and works as expected (for me at least). maybe it also helps tracking the possible bug down.

**Comment by avelad** [comment]
It's not a bug. There is no API available to remove a TextTrack from a video element. If you don't want to have this behavior you can use: StubTextDisplayer or UITextDisplayer, neither of these two displayers creates a texttrack. Sorry!

**Comment by mrx1983** [comment]
no, i think you not understand what i ment. i just wanted to use the SimpleTextDisplayer instead of the UI Displayer for mpd files. Basically using the native Sub Display of the HTML Video Element. In older Versions that worked without a Problem, but in the newer Version it shows me an extra Track with the Name undetermined in the Video UI. It basically switches to the native HTML Video Element to display the Subtitle (which is what i want), but it leaves some bogus track. I only load one Subtitle but it shows me some bogus track in addition. i will probably create an example html file to show the Problem. give me a day or two.

**Comment by mrx1983** [comment]
so i built a html to show the problem better (hopefully).
http://s421666117.online.de/shakatest/

you can see it works great with the mpd file, but as soon as i then load a native webm (click on the button), it shows the track "undetermined" listed in the UI. so if i use simpletextdisplayer its not possible to switch back and forth between an mpd and an
native webm without having the bogus track listed in the ui. is this really intended? in that case you can't really use simpletextdisplayer when one has native and dash files (or one can try to ignore the strange track in the tracklist).

code of the html file: http://s421666117.online.de/shakatest/index.txt

![CwkEOYhJCW](https://github.com/shaka-project/shaka-player/assets/47363681/279acab2-6579-41a0-a02e-099a08a750e5)
