### ISSUE TITLE
AudioContext gets incorrect values upon switching tracks with different channels count. 

### ISSUE THREAD

**Issue by pstyrna** [shaka-project/shaka-player#6764]
Hello, Im doing audio channels visualization for video player using AudioContext. I have notice that when switching tracks in shaka player from 2ch to 6ch, audioContext still is getting only 2ch. Only when we pause video for some time (~30sec) it starts getting 6ch. Seeking to unbuffered section of video after track switch doesn't help either.  

**What version of Shaka Player are you using?**
4.9.2

**What browser and OS are you using?**
Chrome 125.0.6422.76

**What are the manifest and license server URIs?**
uri= 'https://storage.googleapis.com/shaka-demo-assets/tos-surround/dash.mpd'

Working snipped:
https://stackblitz.com/edit/stackblitz-starters-baocxl?file=src%2Fapp%2Fshaka-player%2Fshaka-player.component.ts

**What did you do?**
1. start the video (notice 2 channels playing)
2. press surround button (it will change track to the one with 6 channels) 
3. notice still only 2 channels outputting values
4. try to seek to unbuffered part (notice still 2 channels outputting values)
5. pause video for ~1min
6. unpause, notice 6 channels outputting values

**What did you expect to happen?**
AudioContext should get 6 channels audio on switch without having to pause and w8.

**Comment by joeyparrish** [comment]
Maybe you need to reset your AudioContext or pipeline somehow when the channel configuration changes?

In any case, when you do this:

```js
    const audioContext = new AudioContext();
    const sourceNode = audioContext.createMediaElementSource(
      this.videoElement!
    );
```

Shaka Player has zero involvement in the connection between your video element and your audio context.  All of that happens inside the browser.

You could probably build a small app with MediaSource directly (painful) that appends a series of 2-channel audio segments, then a series of 6-channel audio segments, and you would find the same behavior from the browser.  I strongly suspect that this is a browser bug.

What behavior do you get in Firefox or Safari?  These implementations are independent of Chrome, and so they may behave differently.

**Comment by pstyrna** [comment]
Thx for you replay. 
We are strictly chrome so i didn't check before, but you are right it is a browser bug. On firefox it works fine.
