### ISSUE TITLE
Provide hard coded manifest to shaka

### ISSUE THREAD

**Issue by bidisha15hotstar** [shaka-project/shaka-player#6768]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

**What browser and OS are you using?**

**Please ask your question**
1. How can I provide hardcoded manifest to shaka?
I am seeing missed cue events in shaka, I want to debug it, using hls parser. for ssai. 
Can someone please help. Bit urgent.

**Comment by bidisha15hotstar** [comment]
Bumping this up
cc: @joeyparrish

**Comment by avelad** [comment]
You can modify Shaka's code so that it returns the manifest you want in the manifest parser itself or if you use MSE you can use a blob type url.
