### ISSUE TITLE
Multi Period Drm in DASH

### ISSUE THREAD

**Issue by dkehl** [shaka-project/shaka-player#6772]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Custom version based on version 4.7.11

**What browser and OS are you using?**
Chrome, Windows 10

**Please ask your question**
I'm looking into playing streams with multi period drm in DASH in shaka player, specifically around a use case where different periods have differing license urls(and can change over time via a dynamic manifest).

For a trimmed down example(widevine) of a manifest update where this is relevant:
```
<MPD>
	<Period>
		<AdaptationSet id="0" contentType="video" mimeType="video/mp4">
			<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
				<dashif:Laurl>license1</dashif:Laurl>
			</ContentProtection>
		</AdaptationSet>
	</Period>
	<Period>
		<AdaptationSet id="0" contentType="video" mimeType="video/mp4">
			<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
				<dashif:Laurl>license2</dashif:Laurl>
			</ContentProtection>
		</AdaptationSet>
	</Period>
</MPD>
```
The expectation would be that shaka player would retrieve license1 for the first period and license2 for the second period(you can use a request filter to do any custom context wrapping for security, but the uri in the filter should be the relevant license from the period). In practice, it seems to always request license1.

Investigation of source indicates the following:
The drm_engine maintains it's own instance of drmInfo(currentDrmInfo_), which is what gets used when the drm engine requests a new license via drm_engine.newInitData(initDataType, initData) evaluating that initData requires a new drm session. currentDrmInfo_ is not updated when encountering a new period in the manifest with different drm, and will contain the licenseServerUri of the first period. 
Further digging indicates that when periods are combined via periods.combinePeriods, drm from multiple periods is flattened via getCommonDrmInfos. This process combines the initData and keyIds from both periods(into entries in an array / set for each), but the licenseServerUri is flattened to either the license from the first or second source.

I managed to hack something together locally to request the license I expected - I added a custom array to drmInfo that preserved the licenseUris from each drm when merging via getCommonDrmInfos, tweaked player.processDrmInfos to pass in the equivalent license server url to drm_engine.newInitData, tweaked drm_engine.createSession to add the license information to the metadata of the session, and finally tweaked drm_engine.sendLicenseRequest to use the license on the sessions metadata if present over the currentDrmInfo.

While it works in my narrow case, I don't think this would be a sound approach in general because it ends up mirroring data and is in essence working around some things that the code is based around, namely that there are optimizations that flatten out drm information in varying parts of the manifest and supplied configuration, and the drm engine seems designed to work with a single drmInfo(currentDrmInfo_) object that is being contextually overridden.

My limited perspective on it would be that it might be better to either have more license request information on the session metadata and use that rather than currentDrmInfo_ when sending licenses(basically a cleaner version of what I hacked together, but maybe using the full drmInfo), or to somehow have the drmEngines currentDrmInfo object track the association of licenseUrls for different periods.

Either approach seems like a decent amount of work and may have implications not readily apparent to me, so I figured I would reach out get the devs thoughts on this(and whether multi period drm is something on the radar in general).

**Comment by avelad** [comment]
This is currently not supported in Shaka, please create an feature request issue so we can study it. Thanks!

**Comment by dkehl** [comment]
I thought this might be simpler than it evidently is, so I'll spend some more time to collecting things to do a proper feature request. Thanks for your time.
