### ISSUE TITLE
Shaka player offline api, when abort clears IndexDB

### ISSUE THREAD

**Issue by rezaan6** [shaka-project/shaka-player#6779]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
V4.9.3

**What browser and OS are you using?**
Mac OS 14.5 (23F79)

**Please ask your question**
I need some query in the shaka player offline api, i saw a ticket where resume and pause apparently is not supported natively, if so is there any alternative lib that does support? The other question is when I use this 
"(method) globalThis.shaka.extern.IAbortableOperation<any>.abort(): Promise<any> (+1 overload)"
the segement in IndexedDB->shaka_offline_db->segment-v5 gets cleared. Don't know why it deleting all the downloaded segment. The only way its doesn't clear is if I have downloaded the entire file. If there is a sample for custom resume and pause download for api that would be great.

**Comment by avelad** [comment]
The functionality is not supported because we do not yet support play/pause for offline, see: https://github.com/shaka-project/shaka-player/issues/1301, I recommend that we follow up on this in that issue. thank you!
