### ISSUE TITLE
Add `manifestPeriodCount` to player stats

### ISSUE THREAD

**Issue by tykus160** [shaka-project/shaka-player#6788]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**Is your feature request related to a problem? Please describe.**

For the sake of telemetry, we are trying to monitor how many periods are in our streams. It often help during investigation of production issues.

**Describe the solution you'd like**

Add `manifestPeriodCount` to `shaka.extern.Stats`. For DASH, it should represent number of periods. For other manifests types, it should be probably set explicitly to 1.
When src= mode is used, it should be set to `NaN` as we are not able to determine it.

**Describe alternatives you've considered**

Register manifest preprocessor to count it on application side.

**Additional context**

**Are you planning send a PR to add it?**
Yes if there's an agreement.

**Comment by avelad** [comment]
@theodab Can you give your opinion here?

**Comment by theodab** [comment]
This one also sounds reasonable to me.
