### ISSUE TITLE
Add `manifestGapCount` to player stats

### ISSUE THREAD

**Issue by tykus160** [shaka-project/shaka-player#6789]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**Is your feature request related to a problem? Please describe.**

For the sake of telemetry, we are trying to track how many gaps we were able to detect on a manifest level.

**Describe the solution you'd like**

Add `manifestGapCount` to `shaka.extern.Stats` object.
Add `gapCount` to `shaka.extern.Manifest`, so we can pass this value from `Manifest` to `Stats` once manifest is parsed.
In DASH, it should count how many times there is a non-zero distance between periods.
In HLS, it should represent number of occurrences of `EXT-X-GAP`.
In MSS, set it to 0 (?).
In src= mode it should be set to `NaN` as we are not able to determine it.

**Describe alternatives you've considered**

**Additional context**

**Are you planning send a PR to add it?**
Yes if there's an agreeement.

**Comment by avelad** [comment]
@theodab Can you give your opinion here?

**Comment by theodab** [comment]
I don't see any reason not to.

**Comment by theodab** [comment]
To be clear, I am giving my permission to implement this statistic, as well as the one detailed in #6788.
I would also like to review the PRs when they are ready, to make sure the statistics are properly documented and such.
