### ISSUE TITLE
Customize UI and change the position of buttons

### ISSUE THREAD

**Issue by Leena-Sharma-rsys** [shaka-project/shaka-player#6796]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.5.0

**What browser and OS are you using?**
Chrome

**Please ask your question**
I am using media tailor in my code and my Ui looks like the attached screenshot:
<img width="814" alt="Screenshot 2024-06-11 at 4 26 59 PM" src="https://github.com/shaka-project/shaka-player/assets/96762905/40ec90e5-a82a-4a27-bf7a-173c8ba4f927">

But i want different Ui where seek bar is above the play button and duration is placed at exterme right end.
but the functionality remain the same.
How can it be achieved, Please help?

**Comment by avelad** [comment]
You can make those changes through CSS in your own application, but there is no way to change it via config or similar.

**Comment by Leena-Sharma-rsys** [comment]
Thanks for your response,
I have changed it using the following:
.shaka-bottom-controls {
  display: flex;
  flex-direction: column-reverse;
}

Its working fine.
I also wanted to know if i can change "triple dot icon" of "overflow menu", functionality would remain the same. Only need to change icon. how can it be done ?

**Comment by avelad** [comment]
The icon is a font ("Material Icons Round"), it is not trivial to change it.

**Comment by Leena-Sharma-rsys** [comment]
My project Ui demand for different Icon.
In case we can t change it, how can we add functionality of overflow menu to new icon that i have added in config

I have created the following icon in
<img width="239" alt="Screenshot 2024-06-12 at 12 01 50 PM" src="https://github.com/shaka-project/shaka-player/assets/96762905/3453db33-68d0-4f31-96bf-f362fdfbf299">
 added to ui.config as well:

Please help!!

Thanks

**Comment by Leena-Sharma-rsys** [comment]
i have resolved this using a classname and changed the icon Name. 
but i am facing one issue with bottom bar it is repecating twice , the older controls and new controls. Please refer the attached image.

<img width="887" alt="Screenshot 2024-06-12 at 12 57 08 PM" src="https://github.com/shaka-project/shaka-player/assets/96762905/395738ba-1170-4989-88e4-aaea430ebb66">


Code :

    const video = document.getElementById("video");
    const videoContainerElement = document.getElementById("container");
    const localPlayer = new shaka.Player();
    const ui = new shaka.ui.Overlay(localPlayer, videoContainerElement, video);

    await localPlayer.attach(video);
    var config = {};
    config["controlPanelElements"] = [
      "play_pause",
      "spacer",
      "overflow_menu",
      "spacer",
      "time_and_duration",
      "fullscreen",
    ];
    ui.configure(config);
    const controls = ui.getControls();



I am missing something here ??

**Comment by Leena-Sharma-rsys** [comment]
It was due to spacer in react js, i have added the linear gradient to the background, to resolve the above issue.
Closing the issue
