### ISSUE TITLE
How to pause player when the seek bar is pressed

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#6812]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.6.3

**What browser and OS are you using?**
Window 11 Pro
Chrome 125
Edge 125

**Please ask your question**
For example this demo https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://storage.googleapis.com/shaka-demo-assets/apple-advanced-stream-fmp4/master.m3u8;panel=ALL_CONTENT;panelData=HLS,VOD;build=uncompiled

When you press down the mouse, seek to time 05:00, but still press the the mouse, not release. You can see that player still fetch stream of time 05:00. 

What I want is to totally pause player, pause video, not fetch any stream and not playe video ONLY UNTIL releasing the mouse (or event mouseup). I can't find any configuration for this function.

I hope to get advice from you team. Thanks.

**Comment by avelad** [comment]
This functionality does not exist in the UI, sorry!
