### ISSUE TITLE
UI: In iOS devices the Current time is not updating properly for live stream

### ISSUE THREAD

**Issue by Ravi-79** [shaka-project/shaka-player#6816]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
I read it. There is no duplicate that I can find. 

**If the problem is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**

4.9.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom App

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
iPhone 12 Pro
iOS version 17.5.1 - Safari browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://d305rncpy6ne2q.cloudfront.net/v1/session/94063eadf7d8c56e9e2edd84fdf897826a70d0df/SFP-MediaTailor-Live-HLS-DASH/channel/sfp-channel1/hls.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

{
    "drm": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "servers": {},
        "clearKeys": {},
        "advanced": {},
        "delayLicenseRequestUntilPlayed": false,
        "persistentSessionOnlinePlayback": false,
        "persistentSessionsMetadata": [],
        "logLicenseExchange": false,
        "updateExpirationTime": 1,
        "preferredKeySystems": [],
        "keySystemsMapping": {},
        "parseInbandPsshEnabled": false,
        "minHdcpVersion": "",
        "ignoreDuplicateInitData": true
    },
    "manifest": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "disableThumbnails": false,
        "defaultPresentationDelay": 0,
        "segmentRelativeVttTiming": false,
        "raiseFatalErrorOnManifestUpdateRequestFailure": false,
        "dash": {
            "clockSyncUri": "",
            "ignoreDrmInfo": false,
            "disableXlinkProcessing": false,
            "xlinkFailGracefully": false,
            "ignoreMinBufferTime": false,
            "autoCorrectDrift": true,
            "initialSegmentLimit": 1000,
            "ignoreSuggestedPresentationDelay": false,
            "ignoreEmptyAdaptationSet": false,
            "ignoreMaxSegmentDuration": false,
            "keySystemsByURI": {
                "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
                "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
                "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
                "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
            },
            "sequenceMode": false,
            "enableAudioGroups": false,
            "multiTypeVariantsAllowed": true,
            "useStreamOnceInPeriodFlattening": false,
            "updatePeriod": -1,
            "enableFastSwitching": true
        },
        "hls": {
            "ignoreTextStreamFailures": false,
            "ignoreImageStreamFailures": false,
            "defaultAudioCodec": "mp4a.40.2",
            "defaultVideoCodec": "avc1.42E01E",
            "ignoreManifestProgramDateTime": false,
            "ignoreManifestProgramDateTimeForTypes": [],
            "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\"",
            "useSafariBehaviorForLive": false,
            "liveSegmentsDelay": 3,
            "sequenceMode": true,
            "ignoreManifestTimestampsInSegmentsMode": false,
            "disableCodecGuessing": false,
            "disableClosedCaptionsDetection": false,
            "allowLowLatencyByteRangeOptimization": true
        },
        "mss": {
            "sequenceMode": false,
            "keySystemsBySystemId": {
                "9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
            }
        }
    },
    "streaming": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "rebufferingGoal": 2,
        "bufferingGoal": 10,
        "bufferBehind": 30,
        "evictionGoal": 1,
        "ignoreTextStreamFailures": false,
        "alwaysStreamText": false,
        "startAtSegmentBoundary": false,
        "gapDetectionThreshold": 0.5,
        "gapJumpTimerTime": 0.25,
        "durationBackoff": 1,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsOnSafari": true,
        "useNativeHlsForFairPlay": true,
        "inaccurateManifestTolerance": 2,
        "lowLatencyMode": false,
        "autoLowLatencyMode": false,
        "forceHTTP": false,
        "forceHTTPS": false,
        "preferNativeHls": false,
        "updateIntervalSeconds": 1,
        "dispatchAllEmsgBoxes": false,
        "observeQualityChanges": false,
        "maxDisabledTime": 30,
        "parsePrftBox": false,
        "segmentPrefetchLimit": 0,
        "prefetchAudioLanguages": [],
        "disableAudioPrefetch": false,
        "disableTextPrefetch": false,
        "disableVideoPrefetch": false,
        "liveSync": false,
        "liveSyncTargetLatencyTolerance": 0.5,
        "liveSyncMaxLatency": 1,
        "liveSyncPlaybackRate": 1.1,
        "liveSyncMinLatency": 0,
        "liveSyncMinPlaybackRate": 0.95,
        "liveSyncPanicMode": false,
        "liveSyncPanicThreshold": 60,
        "allowMediaSourceRecoveries": true,
        "minTimeBetweenRecoveries": 5,
        "vodDynamicPlaybackRate": false,
        "vodDynamicPlaybackRateLowBufferRate": 0.95,
        "vodDynamicPlaybackRateBufferRatio": 0.5,
        "infiniteLiveStreamDuration": false,
        "preloadNextUrlWindow": 30,
        "loadTimeout": 30,
        "clearDecodingCache": false
    },
    "mediaSource": {
        "codecSwitchingStrategy": "smooth",
        "forceTransmux": false,
        "insertFakeEncryptionInInit": true
    },
    "offline": {
        "usePersistentLicense": true,
        "numberOfParallelDownloads": 5
    },
    "abr": {
        "enabled": true,
        "useNetworkInformation": true,
        "defaultBandwidthEstimate": 1000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
            "minWidth": 0,
            "maxWidth": null,
            "minHeight": 0,
            "maxHeight": null,
            "minPixels": 0,
            "maxPixels": null,
            "minFrameRate": 0,
            "maxFrameRate": null,
            "minBandwidth": 0,
            "maxBandwidth": null,
            "minChannelsCount": 0,
            "maxChannelsCount": null
        },
        "advanced": {
            "minTotalBytes": 128000,
            "minBytes": 16000,
            "fastHalfLife": 2,
            "slowHalfLife": 5
        },
        "restrictToElementSize": false,
        "restrictToScreenSize": false,
        "ignoreDevicePixelRatio": false,
        "clearBufferSwitch": false,
        "safeMarginSwitch": 0,
        "cacheLoadThreshold": 20
    },
    "autoShowText": 3,
    "preferredAudioLanguage": "en-US",
    "preferredAudioLabel": "",
    "preferredTextLanguage": "en-US",
    "preferredVariantRole": "",
    "preferredTextRole": "",
    "preferredAudioChannelCount": 2,
    "preferredVideoHdrLevel": "AUTO",
    "preferredVideoLayout": "",
    "preferredVideoLabel": "",
    "preferredVideoCodecs": [],
    "preferredAudioCodecs": [],
    "preferForcedSubs": false,
    "preferSpatialAudio": false,
    "preferredDecodingAttributes": [],
    "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null,
        "minChannelsCount": 0,
        "maxChannelsCount": null
    },
    "playRangeStart": 0,
    "playRangeEnd": null,
    "textDisplayer": {
        "captionsUpdatePeriod": 0.25
    },
    "cmcd": {
        "enabled": false,
        "sessionId": "",
        "contentId": "",
        "rtpSafetyFactor": 5,
        "useHeaders": false,
        "includeKeys": []
    },
    "cmsd": {
        "enabled": true,
        "applyMaximumSuggestedBitrate": true,
        "estimatedThroughputWeightRatio": 0.5
    },
    "lcevc": {
        "enabled": false,
        "dynamicPerformanceScaling": true,
        "logLevel": 0,
        "drawLogo": false
    },
    "ads": {
        "customPlayheadTracker": false,
        "skipPlayDetection": false,
        "supportsMultipleMediaElements": true
    }
}

**What did you do?**

Play the following player in iOS device or any live stream with Latest Shaka player in iOS device.
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;useSafariBehaviorForLive=false;uilang=en-US;asset=https://d305rncpy6ne2q.cloudfront.net/v1/session/94063eadf7d8c56e9e2edd84fdf897826a70d0df/SFP-MediaTailor-Live-HLS-DASH/channel/sfp-channel1/hls.m3u8;panel=ALL_CONTENT;panelData=LIVE,HLS;build=uncompiled

While pausing the video the current time value is not increasing continuously, instead it takes 6 seconds delay and updating the new value.
This issue is not reproable in other Operating Systems.
I have shared the video recording for reference.

https://github.com/shaka-project/shaka-player/assets/131441182/199c146a-bd43-4fec-980a-dba244952a7d

**What did you expect to happen?**
The Current time has to be updated properly when it's not on live edge.
**What actually happened?**

I am not sure about the root cause of this issue. But it seems to happen only on iOS devices.

**Are you planning send a PR to fix it?**
No.

**Comment by avelad** [comment]
This issue cannot be fixed and only occurs when src= is used. The problem is how the video element itself reports the times.

**Comment by Ravi-79** [comment]
Thanks for the update @avelad .
