### ISSUE TITLE
Having trouble with forwarding Authorization headers with Fairplay + Safari

### ISSUE THREAD

**Issue by brewsterbhg** [shaka-project/shaka-player#6834]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**
Yes

**What version of Shaka Player are you using?**
4.9.4

**What browser and OS are you using?**
Safari macOS Sonoma 14.5

**Please ask your question**
This feels like a ridiculous question, but I've got a fairly straightforward configuration for loading audio streams with DRM:

```js
initPlayer = () => {
    shaka.polyfill.installAll()
    this.player = new shaka.Player(this.node)
    const src = isSafari ? "path/to/manifest.m3u8" : "path/to/manifest.mpd"

    this.player.configure({
      drm: {
        servers: {
          [GOOGLE_WIDEVINE_KEY_SYSTEM]: licenseServers.widevine,
          [APPLE_FAIRPLAY_KEY_SYSTEM]: licenseServers.fairplay,
        },
        advanced: {
          [APPLE_FAIRPLAY_KEY_SYSTEM]: {
            serverCertificateUri: `${licenseServers.fairplay}cert/[merchant_id]`,
          },
        },
      },
    })

    this.player.getNetworkingEngine().registerRequestFilter((type, request) => {
      if (type === shaka.net.NetworkingEngine.RequestType.LICENSE) {
        // license-specific headers
      } else {
        request.headers["Authorization"] = token
      }
    })

    this.player.addEventListener("error", this.onErrorEvent)

    try {
      await this.player.load(src)
    } catch (e) {
      this.onError(e)
    }
  }
```
Our audio streaming URL uses basic JWT authorization. The Widevine integration works great, and the Fairplay integration seems to load the configuration + server certificate fine, but the problem I'm running into is the Authorization header isn't sent out with the request to our audio URL (specifically on Safari). The HEAD request includes the correct Authorization header, but the GET request doesn't. I don't know if this is a Safari problem, or if there's something wrong with my configuration. Any help would be appreciated!

**Comment by brewsterbhg** [comment]
Digging into it further, the request filter catches the request to get the server certificate, but doesn't seem to trigger again for the request to our audio streaming endpoint

**Comment by avelad** [comment]
By default for FairPlay we delegate to the video element. Therefore, Shaka Player does not make any request other than a License/Certificate. If you want to change the behavior you can do it with the configuration, but keep in mind that not all FairPlay providers support MSE, see: https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html

**Comment by brewsterbhg** [comment]
Hi @avelad, thanks for the context. Apologies, I'm a little new to the library (started this week), and I'm having trouble figuring out exactly how I'd update Fairplay to stream with authentication headers. Do I need to update `useNativeHlsForFairPlay` to false?

**Comment by tykus160** [comment]
@brewsterbhg yes, by setting this option to false you will enable MSE mode in Safari.

**Comment by brewsterbhg** [comment]
Great @tykus160, that worked for me. Thank you!
