### ISSUE TITLE
I want to do some conversion on the URL before requesting the thumbnail

### ISSUE THREAD

**Issue by vaseala** [shaka-project/shaka-player#6836]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes!

**Is your feature request related to a problem? Please describe.**

This is the thumbnail.vtt
```
WEBVTT

00:00.000 --> 00:05.000
image1.png?range=1024,10240#xywh=0,0,128,72

00:05.000 --> 00:10.000
image1.png?range=10241,20480#xywh=128,0,128,72

00:10.000 --> 00:15.000
image2.png?range=1024,20480#xywh=256,0,128,72
```

Before show thumbnail，I want to change the `range` param to the request Header Range

**Describe the solution you'd like**

In the seek_bar.js, I found `this.thumbnailImage_.src = uri;` Maybe It should replace with something like `this.thumbnailImage_.src = await somefunc(uri);`

**Describe alternatives you've considered**

I have no idea.

**Additional context**

nothing

**Are you planning send a PR to add it?**
I'm afraid not

**Comment by avelad** [comment]
Thumbnails are fetched on the application side, so this could be done in-app. Although it is true that the UI also handles them, I am going to create a new type in the filters for this case.

**Comment by vaseala** [comment]
> 再次回顾一下，在我们的例子中，我们将 URL 传递给 img 标签，因此我们不直接管理 URL。因此，这必须始终在应用程序端完成。抱歉！



> 再次回顾一下，在我们的例子中，我们将 URL 传递给 img 标签，因此我们不直接管理 URL。因此，这必须始终在应用程序端完成。抱歉！

I want to transform the url to a blob url

**Comment by vaseala** [comment]
> Reviewing it again, in our case we pass the URL to the img tag, so we do not directly manage the url. So this has to be done on the application side always. Sorry!

In my actual usage scenario, the address of the thumbnail image is dynamic, and there is an expiration time parameter in the image url parameter. I hope that when the thumbnail is displayed, I can first determine whether the expiration time in the image link is valid. If it has exceeded the expiration time, I hope to replace it.

**Comment by avelad** [comment]
> > Reviewing it again, in our case we pass the URL to the img tag, so we do not directly manage the url. So this has to be done on the application side always. Sorry!
> 
> In my actual usage scenario, the address of the thumbnail image is dynamic, and there is an expiration time parameter in the image url parameter. I hope that when the thumbnail is displayed, I can first determine whether the expiration time in the image link is valid. If it has exceeded the expiration time, I hope to replace it.

All of this can be done on the side of the application that is responsible for displaying the image.

**Comment by vaseala** [comment]
> am going to create a new type in the filters for this case.



> Reviewing it again, in our case we pass the URL to the img tag, so we do not directly manage the url. So this has to be done on the application side always. Sorry!

In most cases, it is feasible to use the URL in webvtt directly.
However, my image address has a validity period, which may be short. If the video is very long, then when the thumbnail address is requested at the end, the address in webvtt is expired.
Moreover, the thumbnail addresses in webvtt are different, so the cache will not take effect.
So I hope to provide a hook function for URL conversion (preferably supporting asynchronous conversion) or a public function that can handle it

**Comment by avelad** [comment]
You can do it in the app in a simple way:
```
const thumbnail = await player.getThumbnails(trackId, time);
const url = thumbnail.url.replace(....);
```

**Comment by vaseala** [comment]
> You can do it in the app in a simple way:
> 
> ```
> const thumbnail = await player.getThumbnails(trackId, time);
> const url = thumbnail.url.replace(....);
> ```

@avelad Thank you for your recommended solution. Yes, I can use your method to replace the URL of the image in webvtt regularly.
Then I have a higher encryption requirement for thumbnails. For example, if the thumbnail is encrypted, I don’t want to use it directly as the URL of the image. Instead, I want to get the binary data through asynchronous request, decrypt it, and then generate the blob URL as the real image address.

**Comment by vaseala** [comment]
or the image url 


> > You can do it in the app in a simple way:
> > ```
> > const thumbnail = await player.getThumbnails(trackId, time);
> > const url = thumbnail.url.replace(....);
> > ```
> 
> @avelad Thank you for your recommended solution. Yes, I can use your method to replace the URL of the image in webvtt regularly. Then I have a higher encryption requirement for thumbnails. For example, if the thumbnail image is encrypted, I don’t want to use it directly as the URL of the image. Instead, I want to get the binary data through asynchronous request, decrypt it, and then generate the blob URL as the real image address.

Or my thumbnail is in a file,
such as imageContainerFile?start=range1&end=range2?range=1024,10240#xywh=0,0,128,72
This means I need to take the data from range1 to range2 bytes from imageContainerFile as the address of the image

**Comment by vaseala** [comment]
> Reviewing it again, in our case we pass the URL to the img tag, so we do not directly manage the url. So this has to be done on the application side always. Sorry!

@avelad  I sorted out my needs again：

I combined the thumbnail and subtitles of a video into a file allinone.bin (also with media track, which is not list here)
There is also a manifest file: manifest.json
```js
{
  subtitles: {
    en: {
      file: 'allinone.bin',
      byte_start: 0,
      byte_end: 10239,
      lang: 'en',
      type: 'srt',
    }
  }
  thumbnails: {
    image1: {
      file: 'allinone.bin',
      width: 200,
      height: 200,
      left: 200,
      top: 0,
      byte_start: 10240,
      byte_end: 20480,
      time_start: '00:00.00',
      time_end: '00:05.000'
    },
    // ...
  }
}

```

When used in the player of browser, first I build a vtt text
```
WEBVTT

00:00.000 --> 00:05.000
image1?file=allinone.bin&bytes=10240,20480#xywh=200,0,200,200

// 00:05.000 --> 00:10.000
//...

```
then I transform the text content with `URL.createObjectURL` , then get a blob url, eg: `blob:http://xxx.xx/xx`

when request the thumbnail image url, it may be (blob:http://xxx.xx/image1?file=allinone.bin&bytes=10240,20480#xywh=200,0,200,200),

I want to first get the image raw data with http request, then generate a new image blob uri, then placed to the player thumbnail container.

This may be possible through the http interface to do a transfer, but I think it is more convenient to convert the thumbnail directly
