### ISSUE TITLE
Status 400 when play fairplay content 

### ISSUE THREAD

**Issue by zhangxuno1** [shaka-project/shaka-player#6840]
Hi I am using the v4.9.5 version shaka player demo, I am trying to play fairplay content, it need set "Custom Licenses Certificate URL", I put certificate.der file on Amazon S3 bucket, so I use the URL on S3 for certificate file.
After I try to play the content with available header value, the status 400 pops up, could you please give me some suggestions about this error? Thanks.
![error_400](https://github.com/shaka-project/shaka-player/assets/51395934/09c133d7-cbbd-42b2-b588-ca23c1b20352)

**Comment by avelad** [comment]
I see you are using Verimatrix. Please note that the default Demo does not support Verimatrix, but some changes need to be included, please see: https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html

**Comment by zhangxuno1** [comment]
Thanks for your reply. If I use the verimatrix, I need modify the patchedmediakeys_apple_unit.js file under \test\polyfill, like below screenshot? do I need modify other part? do I need compile the library again? 
![code](https://github.com/shaka-project/shaka-player/assets/51395934/266c02f1-124f-47fb-a8a1-30068f8470df)

**Comment by avelad** [comment]
That would be the only thing. There is no need to compile the player again.

**Comment by zhangxuno1** [comment]
OK, thanks. But  the result is same. the status 400 pops up, do you know which JS file mention the location of certificate.der?

**Comment by avelad** [comment]
I recommend that you talk to your DRM provider so they can tell you what the error is due to.
