### ISSUE TITLE
Shaka Player Resolution labels.

### ISSUE THREAD

**Issue by shubhankarMitra** [shaka-project/shaka-player#6859]
![Screenshot from 2024-06-19 11-26-38](https://github.com/shaka-project/shaka-player/assets/144677376/dd882a20-e9a0-4120-a47b-ae0e3d21110c)

I want to change the resolution labels,for example  for 720p I want to keep it "High". Is it possible with shaka-ui?

Please tell me a way how to do it if its possible!

**Comment by avelad** [comment]
There is no way to customize it, but you can modify it at https://github.com/shaka-project/shaka-player/blob/main/ui/resolution_selection.js#L236 Sorry!
