### ISSUE TITLE
The blob uri can not play on safari

### ISSUE THREAD

**Issue by vaseala** [shaka-project/shaka-player#6860]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**

4.9.6

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Twice

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Macos safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
No

**What are the manifest and license server URIs?**

can find in the demo

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

default configuration

**What did you do?**

I create  very simple page to show the bug:
the code page: https://github.com/issuebox/player/blob/main/shaka-blob.html
the visite page: https://issuebox.github.io/player/shaka-blob.html

It is the same media source with  https://github.com/issuebox/player/blob/main/shaka-http.html , which visite with  https://issuebox.github.io/player/shaka-http.html ,if I use http media source, it works ok in both chrome and safari!

open in the chrome, it works good!
bug can not play in the safari browser.

**What did you expect to happen?**
I hope it can play in the safari browser.

**What actually happened?**

<img width="1152" alt="image" src="https://github.com/shaka-project/shaka-player/assets/12792057/72f4e4f9-a4fa-4039-8a5a-d4a3ceea2537">
<img width="1897" alt="image" src="https://github.com/shaka-project/shaka-player/assets/12792057/7cecf0ae-f2f2-44d0-a80c-5ed73f8314b6">

**Are you planning send a PR to fix it?**
Probably not

**Comment by avelad** [comment]
Blob only works for standalone files or if we use MSE for any type of file. Since you are using HLS in Safari, it by default plays with the native player which does not support blobs for HLS.

**Comment by vaseala** [comment]
But with [hls.js](https://github.com/video-dev/hls.js), I can play with blob uri in safari browser.

**Comment by avelad** [comment]
hls.js always uses MSE :)

**Comment by vaseala** [comment]
> How should I improve my code if using shaka-player?

So can I config to use shaka player with mse?

**Comment by vaseala** [comment]
> hls.js always uses MSE :)

So can I config to use shaka player with mse?

**Comment by avelad** [comment]
`streaming.useNativeHlsOnSafari = false`

**Comment by vaseala** [comment]
> `streaming.useNativeHlsOnSafari = false`

Can you be more specific? Where does the streaming come from? Where do I set it up? Any thoughts on documentation or demos?
Thank you!

**Comment by vaseala** [comment]
> `streaming.useNativeHlsOnSafari = false`

OK！ Thanks!
