### ISSUE TITLE
Load Latency Stats When Using PreloadManager

### ISSUE THREAD

**Issue by yyamaguchi93** [shaka-project/shaka-player#6871]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**
v4.9.3

**What browser and OS are you using?**
MacOS Sonoma 14.5 Chromium

**Please ask your question**
It seems that the load latency statistics are misleading when the `PreloadManager` is used to load the player. Specifically, if there is a delay between when the preload is initiated and when the PreloadManager is actually loaded into the player, the load latency is significantly increased. This behavior does not align with the comment in `stats.js`.
```javascript
  /**
   * Record the time it took between the user signalling "I want to play this"
   * to "I am now seeing this".
   *
   * @param {number} seconds
   */
  setLoadLatency(seconds) {
    this.loadLatencySeconds_ = seconds;
  }
  ```

Is this discrepancy intentional? I rely on the load latency from `player.getStats()` to monitor the player's performance and expected to see improved load latency when using preload.

Here is a pseudo code example demonstrating the issue:
```javascript
await player.load(...);
preloadMgr = await player.preload(...);
await sleep(5); // Simulating a delay
await player.load(preloadMgr);
await waitForEvent("loadedmetadata");
player.getStats().loadLatency; // preload start time - loadedmetadata event time
```

Could you clarify how load latency should be interpreted when using the PreloadManager and whether there are any plans to adjust this metric to better reflect the intended timing?

**Comment by avelad** [comment]
@theodab can you review it? Thanks!

**Comment by theodab** [comment]
That's a good point. It probably makes more sense to start measuring the load latency from when the preload manager is used by `load`, rather than from when it is made.
I'll make a PR for it.
