### ISSUE TITLE
When requesting the thumbnail image URL, I want to make some modifications

### ISSUE THREAD

**Issue by vaseala** [shaka-project/shaka-player#6872]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
latest

**What browser and OS are you using?**
chrome MacOS 

**Please ask your question**

I combined the thumbnail images and subtitles  of a video file into a file allinone.bin，and all the position info is saved into a manifest file.
The manifest file is just like:

```
{
  subtitles: {
    en: {
      file: 'allinone.bin',
      byte_start: 0,
      byte_end: 10239,
      lang: 'en',
      type: 'srt',
    }
  }
  thumbnails: {
    image1: {
      file: 'allinone.bin',
      width: 200,
      height: 200,
      left: 200,
      top: 0,
      byte_start: 10240,
      byte_end: 20480,
      time_start: '00:00.00',
      time_end: '00:05.000'
    },
    image2: {
      file: 'allinone.bin',
      width: 200,
      height: 200,
      left: 400,
      top: 0,
      byte_start: 20481,
      byte_end: 30720,
      time_start: '00:05.00',
      time_end: '00:10.000'
    },
    // ...
  },
  // ....
}

```

When used in the player of browser, first I can calculate thumbnail vtt text
```
WEBVTT

00:00.000 --> 00:05.000
image1?file=allinone.bin&bytes=10240,20480#xywh=200,0,200,200

// 00:05.000 --> 00:10.000
//...

```
then I transform the vtt text with `URL.createObjectURL` , then get a blob url, eg: `blob:http://foo/bar`

When request the thumbnail image url, it may be (blob:http://foo/image1?file=allinone.bin&bytes=10240,20480#xywh=200,0,200,200)

When show the thumbnail in the player, it will requirest the above url, it is not a correct url address.

So before requesting the image URL, I hope to do some conversion on the URL, just like as following:
```
// url1: blob:http://foo/image1?file=allinone.bin&bytes=10240,20480#xywh=200,0,200,200
async function convertThumbnailImageUrl(url1: string) {

    const {byte_start, byte_end} = parseUrl(url1)
    const rawData = await axios.request('https://xxx/allinone.bin', {
        headers: {
            range: `bytes=${byte_start}-${byte_end}`
        }
    }).then(res => res.data)
    const url2 = URL.createObjectURL(rawData);
    return url2;
}
```

This may be possible through the http interface to do a transfer, but I think it is more convenient to convert the thumbnail directly

**Comment by vaseala** [comment]
@joeyparrish Is it necessary to set the thumbnail address to support asynchronous functions?

**Comment by avelad** [comment]
You can use absolute URLs in your WebVTT file to avoid having to do blob transformations. 

Your conversion code to use headers is correct for me. And since this code is executed on the application side I don't see any problem.

**Comment by vaseala** [comment]
> You can use absolute URLs in your WebVTT file to avoid having to do blob transformations.
> 
> Your conversion code to use headers is correct for me. And since this code is executed on the application side I don't see any problem.

My question is, where does convertThumbnailImageUrl get called?

**Comment by vaseala** [comment]
> You can use absolute URLs in your WebVTT file to avoid having to do blob transformations.
> 
> Your conversion code to use headers is correct for me. And since this code is executed on the application side I don't see any problem.

I want to change the header['range'] in an async function,  but there is no hook to run my async function

**Comment by avelad** [comment]
> > You can use absolute URLs in your WebVTT file to avoid having to do blob transformations.
> > Your conversion code to use headers is correct for me. And since this code is executed on the application side I don't see any problem.
> 
> I want to change the header['range'] in an async function, but there is no hook to run my async function

In your code you use `await axios.request`, you will have to see in the axios library how to do that, that library is not part of Shaka Player.

**Comment by vaseala** [comment]
>You can use absolute URLs in your WebVTT file to avoid having to do blob transformations.

I put the compressed file on the CDN, https://cdn.xx.com/allinone.bin

If I directly set the thumbnail address to https://server.xxx.com/allinone.bin?range=10240,20480, I need to get the corresponding byte data of allinone.bin from the CDN on the server side first, and then return it, which reduces the image access speed and increases unnecessary traffic.

So I hope to process this address before setting the thumbnail address to 'https://server.xxx.com/allinone.bin?range=10240,20480':
I can first get 10240-20480 bytes of data from https://cdn.xx.com/allinone.bin through axios or fetch, then generate a blob url with this data and assign it to the thumbnail address

**Comment by vaseala** [comment]
> > > You can use absolute URLs in your WebVTT file to avoid having to do blob transformations.
> > > Your conversion code to use headers is correct for me. And since this code is executed on the application side I don't see any problem.
> > 
> > 
> > I want to change the header['range'] in an async function, but there is no hook to run my async function
> 
> In your code you use `await axios.request`, you will have to see in the axios library how to do that, that library is not part of Shaka Player.

Maybe I didn't express it clearly. My focus is not on how to set the headers of axios

**Comment by avelad** [comment]
You can use something like:
```
const thumbnail = player.getThumbnails(...)
const yourUrl = convertThumbnailImageUrl(thumbnail.uris[0])
```

**Comment by avelad** [comment]
Ok, I think there is some information missing here. Are you using the Shaka UI? Or are you using your own?

**Comment by vaseala** [comment]
> Ok, I think there is some information missing here. Are you using the Shaka UI? Or are you using your own?

I modify the seek-bar.js
https://github.com/shaka-project/shaka-player/blob/main/ui/seek_bar.js#L630

I add the following lines after line 630:
```
if (this.player.thumbnailImageUriParser) {
  uri = await this.player.thumbnailImageUriParser(uri);
}
```
Then I built my own shaka-player, temporarily called shaka-player2.


---------------------------------------------------------------------------------

On the player page， I use it as following：

```
import * as shaka2 from 'shaka-player2'
const player = new shaka2.Player(video);

player.thumbnailImageUriParser = async (uri) => {
  const arr = uri.split('/').slice(-3)
  const file = arr[0]
  const byte_start= Number(arr[1])
  const byte_end= Number(arr[2])

  const arrayBuffer = await axios.request('https://xxx/'+file, {
        headers: {
            range: `bytes=${byte_start}-${byte_end}`
        }
    }).then(res => res.data)

  const blobUri = this.arrayBufferToUri(arrayBuffer)
  return blobUri
}
```

**Comment by avelad** [comment]
Ok, then you have found the solution.

**Comment by vaseala** [comment]
> Ok, then you have found the solution.

But I still hope that the official can add a hook here to set the thumbnail address.

**Comment by avelad** [comment]
> > Ok, then you have found the solution.
> 
> But I still hope that the official can add a hook here to set the thumbnail address.

No one from the maintainer team is going to work on it, if you want to open a PR, we will be happy to review it (see: https://github.com/shaka-project/shaka-player/blob/main/CONTRIBUTING.md)

**Comment by vaseala** [comment]
> > > Ok, then you have found the solution.
> > 
> > 
> > But I still hope that the official can add a hook here to set the thumbnail address.
> 
> No one from the maintainer team is going to work on it, if you want to open a PR, we will be happy to review it (see: https://github.com/shaka-project/shaka-player/blob/main/CONTRIBUTING.md)

OK, thanks!
