### ISSUE TITLE
Memory leaked while using player.preload() feature

### ISSUE THREAD

**Issue by obozhe** [shaka-project/shaka-player#6883]
**What version of Shaka Player are you using?**
4.9.8

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
I created a demo app to test and address the issue
https://codesandbox.io/p/sandbox/shaka-sequential-preload-demo-44r3y7

**If custom app, can you reproduce the issue using our demo app?**
Didn't find suitable demo apps

**What browser and OS are you using?**
Chrome, MacOS/Linux

**What are the manifest and license server URIs?**
Don't know, just a pack of some random test/demo videos (.m3u8)

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
```
{
  "drm": {},
  "manifest": {
    "availabilityWindowOverride": null
  },
  "streaming": {},
  "mediaSource": {},
  "offline": {}
}
```

**What did you do?**
Trying to sequentially preload videos one after another
Open attached codesandbox demo app, take memory snapshot, let the app run for some amount of time, take another snapshot, observe memory usage increase

**What did you expect to happen?**
Expected constant memory usage, proper resources cleaning

**What actually happened?**
Memory usage increase, with every new preload it goes up
We have Shaka player implemented in some sort of gallery with ability to turn on slideshow mode (running all videos in loop one by one). There is a requirement to preload the start of the next video now. I implemented the code, it seemed working, and I left the device (TV, but doesn't matter since I reproduced it locally on laptop) running for a night and got 'Memory exceeded' errors. After investigation, I found that `system / JSArrayBufferData` in memory snapshots has gone from 20mb up to >400mb overnight.

<img width="1496" alt="image" src="https://github.com/shaka-project/shaka-player/assets/15518970/6b499111-f3b7-4d9a-b4bf-d99b9738220f">

**Are you planning send a PR to fix it?**
Not sure if I know how to fix this, if someone guides me would be happy to help

If this is not an issue and I just implemented this wrong, then I'm sorry and would appreciate help in resolving this issue.

**Comment by theodab** [comment]
It looks like the segment prefetches that the preload manager makes aren't being properly disposed of, but only if the preload manager is actually used; they are disposed of if the preload manager is just destroyed without being used.
I'll make a PR to fix this.
