### ISSUE TITLE
Firefox DRM issue when using Web Audio API

### ISSUE THREAD

**Issue by XoDima** [shaka-project/shaka-player#6888]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
latest

**Can you reproduce the issue with our latest release version?**
Yes

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
firefox macOS

**What are the manifest and license server URIs?**
hls manifest and widevine drm

**What did you do?**
Connect AudioContext to audio/video element and try to play hls content protected by widevine

**What did you expect to happen?**
If this is a player bug, I want you to know about it and fix it.  
If this is a browser bug, I don't know.  
Please tell me how to handle this error. player.addEventListener('error') doesn't handle it.  

**What actually happened?**
When using web audio context api, an error occurred when creating a DRM session.  
<img width="1176" alt="Снимок экрана 2024-06-22 в 10 42 07" src="https://github.com/shaka-project/shaka-player/assets/47698517/fdd69563-a263-4b45-9955-3632d09913df">  
  
I also made a screen recording reproducing the error  
https://drive.google.com/file/d/1yJv_RXTAzc2X6_hluRm4owJUQkKCRHym/view?usp=drive_link  

**Are you planning send a PR to fix it?**
No

**Comment by avelad** [comment]
This seems more like a browser problem than Shaka Player itself, see https://bugzilla.mozilla.org/show_bug.cgi?id=1331763

**Comment by XoDima** [comment]
Thanks for the quick response! Is it possible to catch this error on the player?
