### ISSUE TITLE
Dash and HLS live stream (with 3hours DVR mode) lags in shaka player player

### ISSUE THREAD

**Issue by Balakumaran-Sunweb** [shaka-project/shaka-player#6889]
What version of Shaka Player are you using?
4.9.7

Can you reproduce the issue with our latest release version?
Yes

Are you using the demo app or your own custom app?
Own Custom app

What browser and OS are you using?
Chrome and WebOS

For embedded devices (smart TVs, etc.), what model and firmware version are you using?
OLED48CXPTA, 43UP7750PTZ

What are the manifest and license server URIs?**
confidential, own manifest and license 

What configuration are you using?  What is the output of `player.getConfiguration()`?
Default Shaka config

What did you expect to happen?
Playback should not stop. It should play after the stream started.

What actually happened?
While Live streaming getting stopped and Started due to technical issue or network disruption in Streaming side then the playback stopped and after that playback not continue till the DVR duration it downloading the segments and playback starting.

**Comment by Balakumaran-Sunweb** [comment]
Hi @avelad , kindly help us for this issue.

**Comment by avelad** [comment]
From what you say, it also happens in Chrome, but we need the content to see what happens:

```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```

**Comment by Balakumaran-Sunweb** [comment]
Hi @avelad thanks for your reply. I have shared the URL information in that mail(shaka-player-maintainers@googlegroups.com). 

  Note: The issue occurred only on when the live stream encoder stopped and restart. Like Player downloading happen till DVR time after that it will playing normally.

**Comment by avelad** [comment]
@Balakumaran-Sunweb it's the same issue as https://github.com/shaka-project/shaka-player/issues/5649 (it closed due to inactivity, I'm going to try the proposed fix with your stream)

**Comment by Balakumaran-Sunweb** [comment]
@avelad  Thanks for your reply. The issue will be there upto 3 hours of encoder stopped and restart. Please let me know once the playback started. We will recreate this issue again. Then you can able to continue the debugging.

**Comment by avelad** [comment]
@Balakumaran-Sunweb PR to fix it: https://github.com/shaka-project/shaka-player/pull/6896

**Comment by Balakumaran-Sunweb** [comment]
Thank you @avelad , will check from our end and will let you know the update.
