### ISSUE TITLE
Skip button with Media Tailor remains disabled

### ISSUE THREAD

**Issue by Leena-Sharma-rsys** [shaka-project/shaka-player#6909]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
YES

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**If the question is related to FairPlay, have you read the tutorial?**

YES

**What version of Shaka Player are you using?**
4.9.0

**What browser and OS are you using?**
Chrome browser on MAC OS

**question**
hi, I Have been working on Media Tailor with shaka player, the skip functionality which is said to be added in version 4.9.0 is not working. Skip button is visble, but it disabled even if the skipOffset mark is passed.
In the VAST , skipOffset is of 5 seconds which is mentioned in string Format "00:00:05".
What i find in Shaka player Code , in media_tailor_ad.js  is:
getRemainingTime() {
    const endTime = this.ad_.startTimeInSeconds + this.ad_.durationInSeconds;
    return endTime - this.video_.currentTime;
  }

this.getRemainingTime() - this.ad_.skipOffset;
That a no. is being subtracted with string which will result in NaN, hence the skip Button is not enabled. For reffernce please check the screenshot.

<img width="234" alt="Screenshot 2024-06-25 at 2 46 24 PM" src="https://github.com/shaka-project/shaka-player/assets/96762905/53de162c-d50e-4ed2-96b7-afe644623098">
<img width="954" alt="Screenshot 2024-06-25 at 3 13 55 PM" src="https://github.com/shaka-project/shaka-player/assets/96762905/9a800fc4-88d0-464b-b369-990948f49ffe">

Please correct if i missed something.

REQUIRED.
Skip button Should be enabled. 
Please provide solution to this. I have been using React js as library.

**Comment by avelad** [comment]
This sounds like a bug, can you send us a url so we can fix it?

**Comment by avelad** [comment]
```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```

**Comment by Leena-Sharma-rsys** [comment]
hi,
thanks for your response ,
test url  -- > https://10368c5f41df4fb4b0689d2b90e2c7f2.mediatailor.us-west-2.amazonaws.com/v1/session/9a39c1f787063acfe5de4814e922e22605c1572d/single_ad/6fd21c05275845e2bb67f2a3ccac3605/3222cd28d72744cf86b09f568fa77418/dfadea49cd1647be8c684e1002969cad/index.mpd

**Comment by avelad** [comment]
@Leena-Sharma-rsys I found the bug! I'm working on a fix
