### ISSUE TITLE
How to  display two audio track's NAME of a m3u8 manifest file?

### ISSUE THREAD

**Issue by vaseala** [shaka-project/shaka-player#6914]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**

The latest

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
simple code

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
chrome latest

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

I a m3u8 file, it have two audio tracks, they are the same language, but different audio quality
```
#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,URI="audio_0_adapt.m3u8",GROUP-ID="adapt-audio-group",LANGUAGE="und",NAME="stream_adapt_1",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="audio_0_high.m3u8",GROUP-ID="high-audio-group",LANGUAGE="und",NAME="stream_high_1",AUTOSELECT=YES,CHANNELS="6"

#EXT-X-STREAM-INF:BANDWIDTH=11119790,AVERAGE-BANDWIDTH=9406259,CODECS="avc1.6e0033,mp4a.40.2",RESOLUTION=3840x2160,AUDIO="adapt-audio-group"
video_2160_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=11338466,AVERAGE-BANDWIDTH=9616340,CODECS="avc1.6e0033,mp4a.40.2",RESOLUTION=3840x2160,AUDIO="high-audio-group"
video_2160_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4501180,AVERAGE-BANDWIDTH=3797603,CODECS="avc1.6e0032,mp4a.40.2",RESOLUTION=2560x1440,AUDIO="adapt-audio-group"
video_1440_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4719856,AVERAGE-BANDWIDTH=4007684,CODECS="avc1.6e0032,mp4a.40.2",RESOLUTION=2560x1440,AUDIO="high-audio-group"
video_1440_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2522770,AVERAGE-BANDWIDTH=2046771,CODECS="avc1.6e0028,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="adapt-audio-group"
video_1080_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2741446,AVERAGE-BANDWIDTH=2256852,CODECS="avc1.6e0028,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="high-audio-group"
video_1080_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1239638,AVERAGE-BANDWIDTH=985040,CODECS="avc1.6e001f,mp4a.40.2",RESOLUTION=1280x720,AUDIO="adapt-audio-group"
video_720_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1458314,AVERAGE-BANDWIDTH=1195121,CODECS="avc1.6e001f,mp4a.40.2",RESOLUTION=1280x720,AUDIO="high-audio-group"
video_720_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=739263,AVERAGE-BANDWIDTH=606994,CODECS="avc1.6e001f,mp4a.40.2",RESOLUTION=960x540,AUDIO="adapt-audio-group"
video_540_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=957939,AVERAGE-BANDWIDTH=817075,CODECS="avc1.6e001f,mp4a.40.2",RESOLUTION=960x540,AUDIO="high-audio-group"
video_540_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=451479,AVERAGE-BANDWIDTH=361370,CODECS="avc1.6e001e,mp4a.40.2",RESOLUTION=640x360,AUDIO="adapt-audio-group"
video_360_manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=670155,AVERAGE-BANDWIDTH=571451,CODECS="avc1.6e001e,mp4a.40.2",RESOLUTION=640x360,AUDIO="high-audio-group"
video_360_manifest.m3u8

```
<img width="214" alt="image" src="https://github.com/shaka-project/shaka-player/assets/12792057/fe78223e-0dcb-405d-bc35-fa44114c1fb4">
<img width="218" alt="image" src="https://github.com/shaka-project/shaka-player/assets/12792057/f414b0a9-1820-4849-9a1a-0cd9eec0ec9c">

in the player, I want to show the audio track name, not the language name like the  images

**What did you expect to happen?**
I want to know how to config the player to show the audio track's name in the player ui, not show the language name.

**What actually happened?**

**Are you planning send a PR to fix it?**

**Comment by vaseala** [comment]
Sorry, I make a mistake, I tag it as a bug, it should be a question.

**Comment by avelad** [comment]
Try to use UI config:  https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.UIConfiguration --> `trackLabelFormat` ( with the format: LABEL)

**Comment by vaseala** [comment]
> Try to use UI config: https://nightly-dot-shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.UIConfiguration --> `trackLabelFormat` ( with the format: LABEL)

@avelad Thanks, I changed to label with the following code: 
```
ui.configure({
    trackLabelFormat: shaka.ui.Overlay.TrackLabelFormat.LABEL
 })
```

Then I want to custome the icon and the title(language ) ，as shown in the picture below, I circled the part:
![image](https://github.com/shaka-project/shaka-player/assets/12792057/d007746a-c0a2-4eb7-8ed3-9208232e7df5)
Can I do it directly through configuration?

**Comment by avelad** [comment]
The translations are within the library itself and cannot be changed.
About the icon: https://github.com/shaka-project/shaka-player/issues/6796

**Comment by vaseala** [comment]
> The translations are within the library itself and cannot be changed. About the icon: #6796

OK, Thanks very much !
