### ISSUE TITLE
Live content switching to VOD

### ISSUE THREAD

**Issue by zubcoco** [shaka-project/shaka-player#6918]
Hello,

We are a TV provider and we have LIVE content that can be transformed into VOD content.

In this case, the isLive method continues to return true even if the asset is transformed into VOD.

And in this case too, we don't receive the end event. We only receive a buffering event.

I've done the tests on the last shaka player version (4.9.10).

Have you an idea how to fix the bug and if it will be fixed in a future release ?

Thanks,
Corentin

**Comment by avelad** [comment]
Please fill out the bug template so we can help you! https://github.com/shaka-project/shaka-player/issues/new/choose

The conversion of Live to Vod works, but not all providers do it in the same way, so we have to look at the specific case.

Thanks!

**Comment by avelad** [comment]
@zubcoco Can you review if the change of https://github.com/shaka-project/shaka-player/pull/7029 resolves your issue? Thanks!

**Comment by zubcoco** [comment]
My problem is not fixed in the latest release (v4.10.6) who contains the change of #7029 ...

**Comment by avelad** [comment]
@zubcoco Can you send new assets so we can investigate the problem? Thanks!

**Comment by Iragne** [comment]
Happy to test this use case too

**Comment by avelad** [comment]
@Iragne this feature is not working for you?

**Comment by zubcoco** [comment]
@avelad I've sent some stream sample to reproduce the issue.
Thanks

**Comment by avelad** [comment]
@zubcoco I can reproduce the issue with version 4.10.10, but not with the main branch. So some commit will have fixed this (I don't know which one). and the fix will appear in version 4.11

**Comment by Iragne** [comment]
@avelad i'm still seeing the issue in my main branch updated. 
The issue for me is at the end of the live 2 events are trigger quite in the same time but the stat of the video element is already set to paused = true and ended = true.
So when updateStateHistory_ is trigger it's only switching to pause and never to ended

**Comment by avelad** [comment]
I tested with the streams provided by @zubcoco and the ended event is fired and isLive returns false. I used: https://nightly-dot-shaka-player-demo.appspot.com

@Iragne I think what you report is another problem, please make an issue with your problem, and with streams to reproduce it and I will look at it.

**Comment by avelad** [comment]
@Iragne Contact me via Slack (https://video-dev.slack.com/team/U05DB2BTVRU) and I will try to help you faster

**Comment by Iragne** [comment]
@avelad  It looks like there isn’t an account on video-dev tied to this email address.

**Comment by avelad** [comment]
@Iragne https://github.com/shaka-project/shaka-player/pull/7189 :)
