### ISSUE TITLE
Why the subtitles track added to Shaka player which is playing a video in mp4 format is using the native subtitle track display rather using shaka-text-container? 

### ISSUE THREAD

**Issue by Ravi-79** [shaka-project/shaka-player#6924]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes, sorry I couldn't find any.

**If the question is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**
4.9.10

**What browser and OS are you using?**
Windows 11
Microsoft Edge for Business
Version 126.0.2592.68 (Official build) (64-bit)

**Please ask your question**
Why the subtitles track added to Shaka player which is playing a video in mp4 format is using the native subtitle track display rather using shaka-text-container? 
![image](https://github.com/shaka-project/shaka-player/assets/131441182/a58e65f1-a158-4d30-ad62-c6faf3e60dcb)

Is there any config available to load the added external subtitle track in shaka-text-container?

**Comment by avelad** [comment]
Because we always create the track when we use src=, maybe we could improve it, are you interested in doing it?

**Comment by Ravi-79** [comment]
Thanks for the update @avelad , Let me try to add this feature. If I need any help, I'll let you know.
