### ISSUE TITLE
Chromecast: Apple HSL stream with .m4s fragments not working

### ISSUE THREAD

**Issue by BeeMeeMan** [shaka-project/shaka-player#6934]
Hey everyone! 
Iam trying to cast livestream from my iphone. Here is  how m3u8 file looks like:
EXTM3U
#EXT-X-TARGETDURATION:1.0
#EXT-X-VERSION:7
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-MAP:URI="video/header.mp4"
#EXTINF:0.9500,	
video/segment1.m4s
#EXTINF:1.0000,	
video/segment2.m4s
#EXTINF:1.0000,	
video/segment3.m4s

It works well with any HSL player(installed as chrome extension)
I can't test it on shaka-player-demo cause it is local stream.
what Iam doing wrong, or this format is not supported?

when I try to cast it, player opens, few seconds and it just closes.

here is my config for custom Media reciver:
const castReceiverOptions = new cast.framework.CastReceiverOptions();
const playbackConfig = new cast.framework.PlaybackConfig();
playbackConfig.autoResumeDuration = 5;
castReceiverOptions.playbackConfig = playbackConfig;
castReceiverOptions.supportedCommands = cast.framework.messages.Command.ALL_BASIC_MEDIA;
castReceiverOptions.useShakaForHls = true;
castReceiverOptions.skipMplLoad = true;
castReceiverOptions.shakaVersion = "4.7.11"; //(tested with different versions)

**Comment by avelad** [comment]
@BeeMeeMan Can you provide the url of your manifest? Thanks!

**Comment by BeeMeeMan** [comment]
> @BeeMeeMan Can you provide the url of your manifest? Thanks!
Yes sure, here is it:
https://6683f73eec19ad575048862f--gleaming-phoenix-e0a275.netlify.app/index.m3u8

**Comment by avelad** [comment]
Tested with 4.10.0 and works well

**Comment by BeeMeeMan** [comment]
Ok thanks, will search what is wrong.
