### ISSUE TITLE
If the order of the video sequence numbers in m3u8 is different, the sync will be out of sync.

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6942]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**

4.8.4

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
yes

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
window chrome

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

A detailed log was printed

**What did you expect to happen?**

Below is a log image saved in m3u8 with the sequence numbers out of order (down to up order)
It was delivered to the player in the following order: 3812 > 3813 > 3814 > 3816 > 3815, and the player replayed the video fragment that had been played, and from then on, the sync started to go out of sync.

Question: Is there a way to prevent the sync from going out even if the segment order is not consistent in the player, or to reset the sync even if it goes out of sync?

PROGRAM_DATE_TIME is constant between video and audio m3u8, but if they come in a different order, previous chunks are played again and the sync is out of sync.

m3u8, mp4a, and mp4v logs were recorded using the request and response Filter API.

Each column is timestamp, type, currentTime, responseTime, m3u8 first/last sequenceNum, leftBuffer.
### request

3812 > 3813 > 3814 > 3816 > 3817 > 3815 > 3817 > 3818 > 3820

18:37:48.988 - video_3812.mp4v - 439.731705
18:37:49.981 - audio_3886.mp4a - 440.72507
18:37:49.986 - video_3813.mp4v - 440.729769
18:37:49.989 - audio.m3u8 - 440.732939
18:37:49.991 - video_2.m3u8 - 440.732939
18:37:50.898 - audio_3887.mp4a - 441.641754
18:37:50.977 - audio.m3u8 - 441.720802
18:37:50.979 - video_2.m3u8 - 441.720802
18:37:51.006 - video_3814.mp4v - 441.749787 
18:37:51.902 - audio_3888.mp4a - 442.645198
18:37:51.979 - audio.m3u8 - 442.722428
18:37:51.981 - video_2.m3u8 - 442.722428
18:37:52.947 - audio.m3u8 - 443.690655
18:37:52.949 - video_2.m3u8 - 443.690655
18:37:52.962 - audio_3889.mp4a - 443.705485
18:37:53.944 - audio_3890.mp4a - 444.688187
18:37:54.017 - audio.m3u8 - 444.760535
18:37:54.019 - video_2.m3u8 - 444.760535
18:37:54.049 - video_3816.mp4v - 444.793155 
18:37:54.052 - video_3817.mp4v - 444.793155 
18:37:54.056 - video_3815.mp4v - 444.799777
18:37:54.854 - audio_3891.mp4a - 445.597757
18:37:55.028 - audio.m3u8 - 445.772452
18:37:55.032 - video_2.m3u8 - 445.772452
18:37:55.043 - video_3817.mp4v - 445.787233 
18:37:55.067 - video_3818.mp4v - 445.810654
18:37:55.862 - audio_3892.mp4a - 446.605634
18:37:55.968 - video_3820.mp4v - 446.711295

### response

3812 > 3813 > 3814 > 3816 > 3815 > 3817 > 3817 > 3818 > 3820

18:37:49.091 - video_3812.mp4v - 439.849992 - 103ms -  - 4.15
18:37:49.113 - audio_3885.mp4a - 439.85679 - 128ms -  - 4.243
18:37:49.894 - audio.m3u8 - 440.637108 - 915ms - [3882, 3886] - 4.363
18:37:49.902 - video_2.m3u8 - 440.645071 - 921ms - [3809, 3813] - 4.355
18:37:50.007 - audio_3886.mp4a - 440.751054 - 26ms -  - 4.249
18:37:50.114 - video_3813.mp4v - 440.871592 - 128ms -  - 4.128
18:37:50.889 - audio.m3u8 - 441.632867 - 900ms - [3883, 3887] - 4.367
18:37:50.903 - video_2.m3u8 - 441.646502 - 912ms - [3810, 3814] - 4.353
18:37:51.009 - audio_3887.mp4a - 441.753026 - 111ms -  - 4.247
18:37:51.118 - video_3814.mp4v - 441.877008 - 112ms -  - 4.123
18:37:51.874 - audio.m3u8 - 442.618078 - 897ms - [3884, 3888] - 4.382
18:37:51.907 - video_2.m3u8 - 442.650733 - 928ms - [3810, 3814] - 4.349
18:37:51.990 - audio_3888.mp4a - 442.733328 - 88ms -  - 4.267
18:37:52.418 - video_2.m3u8 - 443.161573 - 437ms - [3810, 3814] - 3.838
18:37:52.864 - audio.m3u8 - 443.607341 - 885ms - [3885, 3889] - 3.393
18:37:52.980 - audio_3889.mp4a - 443.724134 - 18ms -  - 3.276
18:37:53.848 - audio.m3u8 - 444.591225 - 901ms - [3886, 3890] - 2.409
18:37:53.950 - video_2.m3u8 - 444.693347 - 1001ms - [3813, 3817] - 2.307
18:37:53.961 - audio_3890.mp4a - 444.704504 - 17ms -  - 2.295
18:37:54.062 - video_3816.mp4v - 444.824419 - 13ms -  - 2.176
18:37:54.090 - video_3815.mp4v - 444.843704 - 34ms -  - 2.156
18:37:54.187 - video_3817.mp4v - 444.937137 - 135ms -  - 4.063
18:37:54.848 - audio.m3u8 - 445.591407 - 831ms - [3887, 3891] - 4.409
18:37:54.957 - video_2.m3u8 - 445.70041 - 938ms - [3814, 3818] - 4.3
18:37:54.966 - audio_3891.mp4a - 445.70982 - 112ms -  - 4.29
18:37:55.047 - video_3817.mp4v - 445.805695 - 4ms -  - 4.194
18:37:55.194 - video_3818.mp4v - 445.946978 - 127ms -  - 5.053
18:37:55.831 - audio.m3u8 - 446.574842 - 803ms - [3888, 3892] - 4.774
18:37:55.946 - audio_3892.mp4a - 446.689759 - 84ms -  - 4.66
18:37:55.961 - video_2.m3u8 - 446.70481 - 929ms - [3816, 3820] - 5.295
18:37:56.290 - video_3820.mp4v - 447.042772 - 322ms -  - 4.957

**What actually happened?**

The same chunk is played again and then out of sync.

**Are you planning send a PR to fix it?**

**Comment by avelad** [comment]
If the order is wrong, this is a problem with the content. Sorry!
