### ISSUE TITLE
Player freezes when seeking multiple times on safari

### ISSUE THREAD

**Issue by jasonjeffrey11** [shaka-project/shaka-player#6955]
**What version of Shaka Player are you using?**
4.9.10

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom app

**If custom app, can you reproduce the issue using our demo app?**
yes - see below for a link to demo link

**What browser and OS are you using?**
safari 17.5 (19618.2.12.11.6) - MacOS 14.5 (23F79)
iPadOS  17.5.1 - iPad Pro (4th Hen

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
n/a - not tested

**What are the manifest and license server URIs?**
https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://media.staging.cvr-dev.sohonettesting.com/2024-06-27_13-59-25.361210_sol-levante-hdr-3-cut/assets/sollevante-hdr10-r2020-st2084-uhd-24fps-1000nit.mov/hls/master.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled;visualizer

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
{
  "drm": {},
  "manifest": {
    "availabilityWindowOverride": null
  },
  "streaming": {
    "useNativeHlsOnSafari": false
  },
  "mediaSource": {},
  "offline": {},
  "abr": {
    "enabled": false
  }
}

**What did you do?**
seek the video a few times

**What did you expect to happen?**
the video will seek and continue to play from the selected location

**What actually happened?**
after multiple seeks the video will freeze and no longer continue to play. this only appears to affect Safari as this works as expected in Chrome.

**Are you planning send a PR to fix it?**
I am happy to help - I am currently unable to identify the issue

**Comment by avelad** [comment]
From slack:

```
Marcus Pennington
This turned out to be a GOP issue since libx265 has open GOP by default whereas libx264 had closed. We've now resolved the issue on the encode end with open-gop=0.
Thanks for your help and insight still. I will have my colleague close the github issue in the morning! 
```
