### ISSUE TITLE
How to fix a downloaded DRM video to use offline returns a 9012 error 

### ISSUE THREAD

**Issue by Jtrom314** [shaka-project/shaka-player#6964]
**What version of Shaka Player are you using?**
Latest

**What browser and OS are you using?**
Chrome / Windows

**Please ask your question**

I am trying to use shaka player to download and play a video that has DRM attached to it offline. Currently I am able to download the video and put it into IndexedDB however whenever I try to play the video, I get a 9012 error message in my console. According to the documentation, this is a `KEY_NOT_FOUND` error. My questions are: Has anyone else encountered this before? How can I set up the configuration so that I can view the videos offline even though they still have DRM?

Attached is what I currently have. I am doing this in Vue 2. 

```js
    async initShaka() {
      shaka.polyfill.installAll()

      if (shaka.Player.isBrowserSupported()) {
        this.player = new shaka.Player(this.$refs.video)
        this.storage = new shaka.offline.Storage(this.player)

        // Listen for error events.
        this.player.addEventListener('error', this.onErrorEvent)

        this.player.configure({
          drm: {
            servers: {
              'com.widevine.alpha': 'https://content.uplynk.com/wv',
              'com.microsoft.playready': 'https://content.uplynk.com/pr'
            }
          },
          offline: {
            usePersistentLicense: true,
            progressCallback: this.setDownloadProgress,
            trackSelectionCallback: this.selectTracks
          },
          manifest: {
            availabilityWindowOverride: 60 * 60 * 4 // 4 hours
          }
        })

        try {
          await this.refreshContentList()
        } catch (error) {
          console.error('Failed to refresh content list: ', error)
        }
      } else {
        console.error('Browser not supported!')
      }
    },

```

**Comment by avelad** [comment]
Could you share the content so we can test and see what is happening? thanks!

**Comment by Jtrom314** [comment]
@avelad mind if I send you the content privately?

**Comment by avelad** [comment]
From bug template:

```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```

You can use: shaka-player-maintainers@googlegroups.com

**Comment by Jtrom314** [comment]
Sweet! Thank you

**Comment by avelad** [comment]
The Widevine server returns a 403 when try to fetch a persistent license:
<html><body>The Widevine server denied the license request</body></html>

I think you have to enable the use of persistent licenses for your content
