### ISSUE TITLE
If Video playback URL changes during session setup, DRM module is going into infinite loop

### ISSUE THREAD

**Issue by mmsreedhar** [shaka-project/shaka-player#6965]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

NA

**What version of Shaka Player are you using?**
4.9.12

**What browser and OS are you using?**
"Mozilla/5.0 (Linux mips) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.176.Bravo.51 Model/ARRIS-VMS1100, Verizon_STB_Bcm/KA93.12.08.13 (Verizon, VMS1100, wired)[0000152767232056/32.874]"

**Please ask your question**
**Platform**: SetTopBox

Usecase: 
1. Start a video playback, once the playback starts video starts playing

2. Change video source and while the session is being setup change the video source again. (Do channel changes multiple times)

**3. SuccessScenario: MediaKeys looks like this**
Map {MediaKeySession {sessionId: "Arristotle3", expiration: NaN, closed: Promise, keyStatuses: MediaKeyStatusMap} => Object {initData: Uint8Array[1746], initDataType: "cenc", loaded: true, oldExpiration: Infinity, updatePromise: null…}, MediaKeySession {sessionId: "Arristotle4", expiration: NaN, closed: Promise, keyStatuses: MediaKeyStatusMap} => Object {initData: Uint8Array[1746], initDataType: "cenc", loaded: true, oldExpiration: Infinity, updatePromise: null…}}

**4. FailureScneario: MedaiKeys looks like this**
Map {MediaKeySession {sessionId: "", expiration: NaN, closed: Promise, keyStatuses: MediaKeyStatusMap} => Object {initData: Uint8Array[1730], initDataType: "cenc", loaded: false, oldExpiration: Infinity, updatePromise: null…}, MediaKeySession {sessionId: "", expiration: NaN, closed: Promise, keyStatuses: MediaKeyStatusMap} => Object {initData: Uint8Array[1730], initDataType: "cenc", loaded: false, oldExpiration: Infinity, updatePromise: null…}, MediaKeySession {sessionId: "", expiration: NaN, closed: Promise, keyStatuses: MediaKeyStatusMap} => Object {initData: Uint8Array[1730], initDataType: "cenc", loaded: false, oldExpiration: Infinity, updatePromise: null…}}

**Browser instance stays in the same until we reboot the browser.**

**Comment by avelad** [comment]
Does this only happen on your STB or does it also happen on the Shaka player demo in browsers? If this is only on your STB, I don't think I can help you solve the problem.

**Comment by mmsreedhar** [comment]
It happens only on that model of STB. Is there any way for us to wait until the previous session successfully closed

**Comment by avelad** [comment]
You would have to modify Shaka's code, there is currently a race, see: https://github.com/shaka-project/shaka-player/blob/main/lib/media/drm_engine.js#L2021

**Comment by mmsreedhar** [comment]
Thank you for the suggestion.
Looks like the change is not helping as we are having an issue with the opening session only.

Here is the flow right now.
1. Create a Media key session
2. Before attaching session ID change the channel.

Attached the active sessions query. Since session ID is not there we were unable to close it.
![MediaSessionsEmpty](https://github.com/shaka-project/shaka-player/assets/5544716/98a75585-b2a1-43b6-9af7-4dd13aa1dd05)

Please let me know if we can make it synchronous from the creation of mediaKeySession to populating valid session id.

**Comment by mmsreedhar** [comment]
I will try to wait on the current session setup to be completed before tuning to next channel. Thank you for the help.
