### ISSUE TITLE
Choosing an audio track with fewer channels than `preferredAudioChannelCount` results in no audio on Firefox.

### ISSUE THREAD

**Issue by oscnord** [shaka-project/shaka-player#6980]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

Latest version (as of today) v4.10.1

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app 

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Browser: Firefox v127.0.2 
OS: macOS 14.5 (23F79)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Example setup: <https://www.oscarnord.com/shaka-test/>
Stream that is used in above example: <https://storage.googleapis.com/shaka-demo-assets/tos-surround/dash.mpd>

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Default with the inclusion of:
```json
{
  "preferredAudioChannelCount": 6
}
```
**What did you do?**

Start the player and choose a 2 channel audio track. In Chrome and Safari it works as expected but in Firefox audio segments are fetched but no audio is playing.

**What did you expect to happen?**
Audio-tracks with channels < `preferredAudioChannelCount` should still be playable. 

**What actually happened?**

No sound when selecting a 2 channel audio track. Switching back to the surround track however works and then audio playing.

**Are you planning send a PR to fix it?**
Don't know if this is related to Shaka Player och if it's a bug in Firefox.

**Comment by avelad** [comment]
If you start with 6 channels, then change 2, the browser does not play the sound, if you then change to 6, the 6 channel does play. If you start with 2 channels, all other channel transitions work fine.
This is a Firefox bug. Sorry!

**Comment by oscnord** [comment]
Ticket created: https://bugzilla.mozilla.org/show_bug.cgi?id=1906273

**Comment by oscnord** [comment]
Still an issue on Firefox. @shaka-bot reopen

**Comment by avelad** [comment]
Yes, but it is a Firefox bug, not Shaka itself, which is why the issue has been closed. Tracking must be done on the page https://bugzilla.mozilla.org/show_bug.cgi?id=1906273 we can't do anything else, sorry!
