### ISSUE TITLE
Buffering occurs if EXT-X-MEDIA-SEQUENCE is discontinuous.

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#6994]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**
4.8.4

**What browser and OS are you using?**
window chrome

**Please ask your question**
If the 'EXT-X-MEDIA-SEQUENCE' value in m3u8 is missing as shown below, Shaka Player has a problem of calling video files repeatedly.
I understand that buffering occurs at this time, 

1. What problems will Shaka players experience if one of the SEQUENCE numbers on the server is missing or is not consecutive?

2. Why is 2129.mp4v called again after 2130.mp4v and not 2131.mp4v?

I would really appreciate it if you could answer the above questions.

![image](https://github.com/shaka-project/shaka-player/assets/136538250/75a9a046-713d-4096-9c7c-2b09c4cf5a3f)

### configure
streaming: {
    bufferingGoal: 5,
    bufferBehind: 30,
    rebufferingGoal: 2,
    lowLatencyMode: true,
  },
  manifest: {
    hls: {
      liveSegmentsDelay: 1.5,
    },
  },

### rfc docs
https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.3.2

**Comment by avelad** [comment]
This sounds like a bug in the player, can you fill out the bug template and share the stream with us so we can investigate? Thanks!
