### ISSUE TITLE
Why shaka not detect all resolutions of manifest

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#7005]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Not related to Fairplay

**What version of Shaka Player are you using?**
4.6.3

**What browser and OS are you using?**
OS: Window 11 Pro (64-bit)
Browser: Chrome Version 126.0.6478.127 (Official Build) (64-bit)

**Please ask your question**
How to configure player so that it can detect all resolutions defined in manifest? 

My manifest is: 
https://vod03-cdn.fptplay.net/POVOD/encoded/2024/06/03/deomo_9ladder/master.m3u8

The video resolutions list is below, please note we have 2 options 1080p, but they have different BandWidth and different video link. This is similar to 720 and 432
# Video
#EXT-X-STREAM-INF:AUDIO="audio",AVERAGE-BANDWIDTH=653215,BANDWIDTH=1338331,VIDEO-RANGE=SDR,CODECS="avc1.640015,mp4a.40.2",RESOLUTION=416x324,FRAME-RATE=24.000
video/avc1/1/media.m3u8
#EXT-X-STREAM-INF:AUDIO="audio",AVERAGE-BANDWIDTH=771269,BANDWIDTH=1543601,VIDEO-RANGE=SDR,CODECS="avc1.64001E,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=24.000
video/avc1/2/media.m3u8
#EXT-X-STREAM-INF:AUDIO="audio",AVERAGE-BANDWIDTH=868390,BANDWIDTH=**1781749**,VIDEO-RANGE=SDR,CODECS="avc1.64001E,mp4a.40.2",RESOLUTION=**768x432**,FRAME-RATE=24.000
**video/avc1/3/media.m3u8**
#EXT-X-STREAM-INF:AUDIO="audio",AVERAGE-BANDWIDTH=966911,BANDWIDTH=**2009283**,VIDEO-RANGE=SDR,CODECS="avc1.64001E,mp4a.40.2",RESOLUTION=**768x432**,FRAME-RATE=24.000
**video/avc1/4/media.m3u8**
#EXT-X-STREAM-INF:AUDIO="audio",AVERAGE-BANDWIDTH=1080721,BANDWIDTH=2232815,VIDEO-RANGE=SDR,CODECS="avc1.64001F,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=24.000
video/avc1/5/media.m3u8
#EXT-X-STREAM-INF:AUDIO="audio",AVERAGE-BANDWIDTH=1165521,BANDWIDTH=**2337351**,VIDEO-RANGE=SDR,CODECS="avc1.64001F,mp4a.40.2",RESOLUTION=**1280x720**,FRAME-RATE=24.000
**video/avc1/6/media.m3u8**
#EXT-X-STREAM-INF:AUDIO="audio",AVERAGE-BANDWIDTH=1256395,BANDWIDTH=**2526301**,VIDEO-RANGE=SDR,CODECS="avc1.64001F,mp4a.40.2",RESOLUTION=**1280x720**,FRAME-RATE=24.000
**video/avc1/7/media.m3u8**
#EXT-X-STREAM-INF:AUDIO="audio",AVERAGE-BANDWIDTH=1443177,BANDWIDTH=**2924653**,VIDEO-RANGE=SDR,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=**1920x1080**,FRAME-RATE=24.000
**video/avc1/8/media.m3u8**
#EXT-X-STREAM-INF:AUDIO="audio",AVERAGE-BANDWIDTH=1443354,BANDWIDTH=**2908635**,VIDEO-RANGE=SDR,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=**1920x1080**,FRAME-RATE=24.000
**video/avc1/9/media.m3u8** 

I already directly tested on Demo Shaka Page, you can see shaka can only detect one 1080 and one 720 while in fact it has two 1080 and two 720.
https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://vod03-cdn.fptplay.net/POVOD/encoded/2024/06/03/deomo_9ladder/master.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled
![image](https://github.com/shaka-project/shaka-player/assets/70369658/6b64735b-2a7c-4068-8dce-e0075a98aefc)

When check player.getVariantTracks(), the same problem happen.

BUT, when test with Chrome extension, it detect all resolutions as expected
https://chromewebstore.google.com/detail/native-mpeg-dash-+-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn
![image](https://github.com/shaka-project/shaka-player/assets/70369658/fbfda4b9-cfee-4865-ab1b-7bd50d4dfefa)

Thank you.

**Comment by avelad** [comment]
The change was added in versions 4.9.x https://github.com/shaka-project/shaka-player/commit/a9d5dc399168cb8f9ab5ab0abdbef41e31e2942d please update to a more modern version. Thanks!

**Comment by vanminhquangtri** [comment]
Hi @avelad it seem update to version 4.9.x not working. I event also upgraded to version 4.10.x latest but no luck.
It still only get 1 resolution if 2 resolution has the same width/height.

**Comment by avelad** [comment]
Ok, in that case please open a bug (have more questions to help us solve the problem), since it could be a bug in the player, it wouldn't be a question. Thank you!

**Comment by avelad** [comment]
I found a problem in the player, but to verify it, I would need you to fill out the template, to know your configuration for example...

**Comment by vanminhquangtri** [comment]
hi @avelad yes I already open a bug here:
