### ISSUE TITLE
Issue with Resolution Select Quality Setting Menu Not Closing When Selecting "Auto" Option in Shaka Player UI

### ISSUE THREAD

**Issue by MSAJAL07** [shaka-project/shaka-player#7009]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** 
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** 
Yes

**What version of Shaka Player are you using?**
4.9.7

**What browser and OS are you using?**
macOS sonoma

**I am using Shaka Player with the UI. I changed the resolution from 720p to "auto" in the resolution menu, but no "adaptation" or "variantchanged" event was triggered because the video continues to play at 720p, and I am  closing the resolution menu upon these events. How can I achieve this?**

 ```
player.addEventListener("variantchanged", () => {
                uiRef.current?.getControls().hideSettingsMenus();
            });
 player.addEventListener("ratechange", () => {
                uiRef.current?.getControls().hideSettingsMenus();
            });
```

**Comment by avelad** [comment]
If auto detects that it is not necessary to change the resolution, it will not change it immediately, which is why it is not launched any event in that case.

**Comment by MSAJAL07** [comment]
yes @avelad. I just want to close resolution menu. currently I am closing it on event  of "variantchanged" but in case of "auto" event is not triggered and menu remains open. is there any other event that is getting triggered so i can close the settings menu

**Comment by MSAJAL07** [comment]
I solved this by adding a click event on `querySelector(".shaka-resolutions")`, but is there an API available for this? Ideally, selecting an option from the menu should close it by default.

```
 const resolutionMenu = document.querySelector(".shaka-resolutions");
            if (resolutionMenu) {
                resolutionMenu.addEventListener("click", () => {
                    uiRef.current?.getControls().hideSettingsMenus();
                });
            }
```

**Comment by avelad** [comment]
There is no other method currently. Sorry!
