### ISSUE TITLE
Shaka Ad not clickable

### ISSUE THREAD

**Issue by neerajgulati-airtel** [shaka-project/shaka-player#7016]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Yes

**What version of Shaka Player are you using?**
4.10.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
. Issue not reporoducible in demo app

**What browser and OS are you using?**
MacOS version: 13.5.2 (22G91)
Chip: Apple M1 Pro
Chrome Version: 117.0.5938.132

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**

Ad Tag URL: https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_preroll_skippable&sz=640x480&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=

Manifest URL: "https://hoichoihls-airtel.akamaized.net/vhoichoiindia2/Renditions/20240612/1718176016284_trial_jamai_video/hls/master.m3u8?hdnts=st=1720611286~exp=1720625686~acl=/*~hmac=dccd6ba8d68d058a38dcdf6303236ee452dde37eddd801d28d6b86ecb8678a30"
You can use any manifest url  however in case above one expires

**What did you do?**

Play any content
Ad will play but however neither ad is clickable nor the skip ad button or skip timer is showing

**What did you expect to happen?**
Ad should be clickable. Skip Ad button and timer should be visible
**What actually happened?**
Ad was not clickable not skip ad timer is showing

While debugging I can see that in my ad container the ad video tag and ad iframe gets rendered which shows the ad. The responsibility of ad click is on iframe but I can see that somehow the ad video tag is getting a z-index of 99. But the iframe is not getting any z-index. Due to which the ad video comes before ad 

Please note that I am not using shaka UI Build. I am nowhere adding z-index: 99 to iframe or video.

Please see attached screen shot

<img width="1504" alt="image" src="https://github.com/shaka-project/shaka-player/assets/120081455/cc987ecc-571f-42f9-b047-dde2c1315c01">
<img width="1512" alt="image" src="https://github.com/shaka-project/shaka-player/assets/120081455/387e63a3-15d6-4159-910c-4a3b6d50c55e">

<img width="968" alt="image" src="https://github.com/shaka-project/shaka-player/assets/120081455/fa5bb0fd-f916-4952-bcd6-8c47647f50ee">

**Are you planning send a PR to fix it?**

**Comment by avelad** [comment]
I can't reproduce it in the demo, please include a minimal example of how you are building everything so I can help you. Thanks!

**Comment by neerajgulati-airtel** [comment]
Understood the cause. Please ignore
