### ISSUE TITLE
Can shakea player parse X-Cache?

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#7020]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**
4.8.11

**What browser and OS are you using?**
window chrome

**Please ask your question**
Can shakea player parse X-Cache?

In register Response Filter
m4v, m4a are being responded to. 
However, only the content-type is displayed in the header content as shown below. 

Is there a way to print the X-Cache of the fragment being played?
```

data
: 
ArrayBuffer(993705)
headers
: 
content-type
: 
"video/mp4"
[[Prototype]]
: 
Object
timeMs
: 
23
uri
: 
"https://127.0.0.0:49151/frag_3_main_31494/?params=eyJwYWNrZXRUeXBlI"
```

**Comment by avelad** [comment]
You need include `Access-Control-Expose-Headers: X-Cache` in the response Headers

**Comment by brodiddev** [comment]
My edits didn't take effect. Thank you :)
