### ISSUE TITLE
Add config to not use patch locations

### ISSUE THREAD

**Issue by domenico-montalbano-deltatre** [shaka-project/shaka-player#7025]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
Our stream provider is not delivering low latency stream compatible and using patch locations is preventing us to play. It keeps freezing every few seconds

**Describe the solution you'd like**
A config like "manifest.dash.disablepatchlocations" to just return an empty array in dash-parser.js https://github.com/shaka-project/shaka-player/blob/87bf738ece4081e4ed4ea2fa52467e6d09cb542d/lib/dash/dash_parser.js#L2929C5-L2930C45
 

**Describe alternatives you've considered**
---

**Additional context**
---

**Are you planning send a PR to add it?**
Not at the moment

**Comment by avelad** [comment]
If I understand correctly, the problem is that manifest appears PatchLocation but the URL is incorrect or returns incorrect data, is that correct?

**Comment by Iragne** [comment]
Look like yes. i seen some issue with provider and patch manifest. i'm surprise that this new feature is automatically activated

**Comment by domenico-montalbano-deltatre** [comment]
> If I understand correctly, the problem is that manifest appears PatchLocation but the URL is incorrect or returns incorrect data, is that correct?

Correct

**Comment by avelad** [comment]
Really then the problem is that your stream provider does not follow the DASH standard.

Our goal (in the medium term) is to simplify the configuration, so we do not want to add configurations for each functionality.

**Comment by Iragne** [comment]
For me we should to the check here 
https://github.com/shaka-project/shaka-player/blob/87bf738ece4081e4ed4ea2fa52467e6d09cb542d/lib/dash/dash_parser.js#L365

`
const patchLocationUris = manifest.dash.disablePatchLocation ? "" : this.getPatchLocationUris_();


`

**Comment by Iragne** [comment]
@avelad  before not doing it let's review the implementation. can we have a stream to test ?

**Comment by avelad** [comment]
In the Demo there are some test streams: https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;panel=ALL_CONTENT;panelData=MPD_PATCH;build=uncompiled

**Comment by Iragne** [comment]
@domenico-montalbano-deltatre  can you check if we have any issue in the stream and if not can you share to us a stream exemple

**Comment by domenico-montalbano-deltatre** [comment]
I can check if I can provide one I can share

**Comment by Iragne** [comment]
Will check your stream @domenico-montalbano-deltatre
