### ISSUE TITLE
Live HLS stream playback giving 1001 Error: Shaka Error NETWORK.BAD_HTTP_STATUS

### ISSUE THREAD

**Issue by spatel799** [shaka-project/shaka-player#7034]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
`v4.10.4-uncompiled`

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
The demo

**If custom app, can you reproduce the issue using our demo app?**
N/A
Yes

**What browser and OS are you using?**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`
Version 126.0.6478.127 (Official Build) (arm64)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A
Right now, I am trying to run it on the Shaka demo player using custom option https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://hls.xumo.com/channel-hls/v3/4d1c1fd3e3684d33/99992293/master.m3u8;panel=HOME;build=uncompiled

**What are the manifest and license server URIs?**

uri= `https://content-*****.uplynk.com/channel/*********************/d.m3u8`

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

{
    "drm": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "servers": {},
        "clearKeys": {},
        "advanced": {},
        "delayLicenseRequestUntilPlayed": false,
        "persistentSessionOnlinePlayback": false,
        "persistentSessionsMetadata": [],
        "logLicenseExchange": false,
        "updateExpirationTime": 1,
        "preferredKeySystems": [],
        "keySystemsMapping": {},
        "parseInbandPsshEnabled": false,
        "minHdcpVersion": "",
        "ignoreDuplicateInitData": true
    },
    "manifest": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "availabilityWindowOverride": null,
        "disableAudio": false,
        "disableVideo": false,
        "disableText": false,
        "disableThumbnails": false,
        "defaultPresentationDelay": 0,
        "segmentRelativeVttTiming": false,
        "raiseFatalErrorOnManifestUpdateRequestFailure": false,
        "continueLoadingWhenPaused": true,
        "dash": {
            "clockSyncUri": "",
            "ignoreDrmInfo": false,
            "disableXlinkProcessing": false,
            "xlinkFailGracefully": false,
            "ignoreMinBufferTime": false,
            "autoCorrectDrift": true,
            "initialSegmentLimit": 1000,
            "ignoreSuggestedPresentationDelay": false,
            "ignoreEmptyAdaptationSet": false,
            "ignoreMaxSegmentDuration": false,
            "keySystemsByURI": {
                "urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b": "org.w3.clearkey",
                "urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e": "org.w3.clearkey",
                "urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed": "com.widevine.alpha",
                "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "urn:uuid:79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
            },
            "sequenceMode": false,
            "enableAudioGroups": false,
            "multiTypeVariantsAllowed": true,
            "useStreamOnceInPeriodFlattening": false,
            "updatePeriod": -1,
            "enableFastSwitching": true
        },
        "hls": {
            "ignoreTextStreamFailures": true,
            "ignoreImageStreamFailures": false,
            "defaultAudioCodec": "mp4a.40.2",
            "defaultVideoCodec": "avc1.42E01E",
            "ignoreManifestProgramDateTime": false,
            "ignoreManifestProgramDateTimeForTypes": [],
            "mediaPlaylistFullMimeType": "video/mp2t; codecs=\"avc1.42E01E, mp4a.40.2\"",
            "useSafariBehaviorForLive": true,
            "liveSegmentsDelay": 3,
            "sequenceMode": false,
            "ignoreManifestTimestampsInSegmentsMode": false,
            "disableCodecGuessing": false,
            "disableClosedCaptionsDetection": false,
            "allowLowLatencyByteRangeOptimization": true
        },
        "mss": {
            "sequenceMode": false,
            "keySystemsBySystemId": {
                "9a04f079-9840-4286-ab92-e65be0885f95": "com.microsoft.playready",
                "79f0049a-4098-8642-ab92-e65be0885f95": "com.microsoft.playready"
            }
        }
    },
    "streaming": {
        "retryParameters": {
            "maxAttempts": 2,
            "baseDelay": 1000,
            "backoffFactor": 2,
            "fuzzFactor": 0.5,
            "timeout": 30000,
            "stallTimeout": 5000,
            "connectionTimeout": 10000
        },
        "rebufferingGoal": 2,
        "bufferingGoal": 10,
        "bufferBehind": 30,
        "evictionGoal": 1,
        "ignoreTextStreamFailures": true,
        "alwaysStreamText": false,
        "startAtSegmentBoundary": false,
        "gapDetectionThreshold": 0.5,
        "gapJumpTimerTime": 0.25,
        "durationBackoff": 1,
        "safeSeekOffset": 5,
        "stallEnabled": true,
        "stallThreshold": 1,
        "stallSkip": 0.1,
        "useNativeHlsForFairPlay": true,
        "inaccurateManifestTolerance": 2,
        "lowLatencyMode": false,
        "autoLowLatencyMode": false,
        "forceHTTP": false,
        "forceHTTPS": false,
        "preferNativeHls": false,
        "updateIntervalSeconds": 1,
        "dispatchAllEmsgBoxes": false,
        "observeQualityChanges": false,
        "maxDisabledTime": 30,
        "parsePrftBox": false,
        "segmentPrefetchLimit": 0,
        "prefetchAudioLanguages": [],
        "disableAudioPrefetch": false,
        "disableTextPrefetch": false,
        "disableVideoPrefetch": false,
        "liveSync": {
            "enabled": false,
            "targetLatency": 0.5,
            "targetLatencyTolerance": 0.5,
            "maxPlaybackRate": 1.1,
            "minPlaybackRate": 0.95,
            "panicMode": false,
            "panicThreshold": 60,
            "dynamicTargetLatency": {
                "enabled": false,
                "stabilityThreshold": 60,
                "rebufferIncrement": 0.5,
                "maxAttempts": 10,
                "maxLatency": 4,
                "minLatency": 1
            }
        },
        "allowMediaSourceRecoveries": true,
        "minTimeBetweenRecoveries": 5,
        "vodDynamicPlaybackRate": false,
        "vodDynamicPlaybackRateLowBufferRate": 0.95,
        "vodDynamicPlaybackRateBufferRatio": 0.5,
        "infiniteLiveStreamDuration": false,
        "preloadNextUrlWindow": 30,
        "loadTimeout": 30,
        "clearDecodingCache": false,
        "dontChooseCodecs": false,
        "shouldFixTimestampOffset": false
    },
    "mediaSource": {
        "codecSwitchingStrategy": "smooth",
        "forceTransmux": false,
        "insertFakeEncryptionInInit": true
    },
    "offline": {
        "usePersistentLicense": true,
        "numberOfParallelDownloads": 5
    },
    "abr": {
        "enabled": true,
        "useNetworkInformation": true,
        "defaultBandwidthEstimate": 1000000,
        "switchInterval": 8,
        "bandwidthUpgradeTarget": 0.85,
        "bandwidthDowngradeTarget": 0.95,
        "restrictions": {
            "minWidth": 0,
            "maxWidth": null,
            "minHeight": 0,
            "maxHeight": null,
            "minPixels": 0,
            "maxPixels": null,
            "minFrameRate": 0,
            "maxFrameRate": null,
            "minBandwidth": 0,
            "maxBandwidth": null,
            "minChannelsCount": 0,
            "maxChannelsCount": null
        },
        "advanced": {
            "minTotalBytes": 128000,
            "minBytes": 16000,
            "fastHalfLife": 2,
            "slowHalfLife": 5
        },
        "restrictToElementSize": false,
        "restrictToScreenSize": false,
        "ignoreDevicePixelRatio": false,
        "clearBufferSwitch": false,
        "safeMarginSwitch": 0,
        "cacheLoadThreshold": 20,
        "minTimeToSwitch": 0
    },
    "autoShowText": 3,
    "preferredAudioLanguage": "",
    "preferredAudioLabel": "",
    "preferredTextLanguage": "",
    "preferredVariantRole": "",
    "preferredTextRole": "",
    "preferredAudioChannelCount": 2,
    "preferredVideoHdrLevel": "AUTO",
    "preferredVideoLayout": "",
    "preferredVideoLabel": "",
    "preferredVideoCodecs": [],
    "preferredAudioCodecs": [],
    "preferForcedSubs": false,
    "preferSpatialAudio": false,
    "preferredDecodingAttributes": [],
    "restrictions": {
        "minWidth": 0,
        "maxWidth": null,
        "minHeight": 0,
        "maxHeight": null,
        "minPixels": 0,
        "maxPixels": null,
        "minFrameRate": 0,
        "maxFrameRate": null,
        "minBandwidth": 0,
        "maxBandwidth": null,
        "minChannelsCount": 0,
        "maxChannelsCount": null
    },
    "playRangeStart": 0,
    "playRangeEnd": null,
    "textDisplayer": {
        "captionsUpdatePeriod": 0.25
    },
    "cmcd": {
        "enabled": false,
        "sessionId": "",
        "contentId": "",
        "rtpSafetyFactor": 5,
        "useHeaders": false,
        "includeKeys": []
    },
    "cmsd": {
        "enabled": true,
        "applyMaximumSuggestedBitrate": true,
        "estimatedThroughputWeightRatio": 0.5
    },
    "lcevc": {
        "enabled": false,
        "dynamicPerformanceScaling": true,
        "logLevel": 0,
        "drawLogo": false
    },
    "ads": {
        "customPlayheadTracker": false,
        "skipPlayDetection": false,
        "supportsMultipleMediaElements": true
    }
}

**What did you do?**

Just tried to load the m3u8 HLS stream URL

**What did you expect to happen?**
the player to start playing the content. The same URL works on Bitmovin, HLS, and VideoJS but fails on Shaka.

**What actually happened?**

We are observing shaka.util.Error {severity: 2, category: 1, code: 1001, data: Array(6), handled: false, …}
403
2
: 
""
3
: 
content-length
: 
"0"
content-type
: 
"text/html"
[[Prototype]]

![image](https://github.com/user-attachments/assets/2c17db62-251b-4dc8-b752-9f0fe5ef6280)

**Comment by avelad** [comment]
In order for us to fix this bug, you have to send us the url to shaka-player-maintainers@googlegroups.com Thanks!

**Comment by spatel799** [comment]
Sorry, I couldn't share the URL, but the stream seems to be working with the new release, v4.10.7. Thank you very much!
