### ISSUE TITLE
Grouping by codec in the audio track selector should not occur when the trackLabelFormat is LABEL

### ISSUE THREAD

**Issue by absidue** [shaka-project/shaka-player#7035]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

https://github.com/shaka-project/shaka-player/pull/6723 introduced the feature to treat different codecs as separate audio tracks in the UI, which works great if the `trackLabelFormat` is set to `LANGUAGE`, however it doesn't work well if it is set to `LABEL`. In that case it correctly shows the original labels, however in the background it still treats them as separate audio tracks, so you end up with the labels getting duplicated in the audio track selector, once for each codec.

**Describe the solution you'd like**
When the `trackLabelFormat` is set to `LABEL` is would be nice if shaka-player grouped the audio streams by label regardless of their codec, like it did before that pull request.

**Describe alternatives you've considered**
An option to opt-out of the codec based grouping.

**Additional context**
n/a

**Are you planning send a PR to add it?**
No, unfortunately this project still has the CLA :(.

**Comment by avelad** [comment]
Can you provide a stream to implement it? Thanks!
