### ISSUE TITLE
Problem with displaying items

### ISSUE THREAD

**Issue by FiberOnePL** [shaka-project/shaka-player#7036]
Hello, while shaka works well on computers, it often doesn't work correctly on TV. I mean, for example, the lack of controls or the cursor not disappearing. I found the biggest bug on the Samsung QLED QE65Q7FAM TV.

<a href="https://ibb.co/37r8LY7"><img src="https://i.ibb.co/37r8LY7/20240713-224858.png" alt="20240713-224858" border="0"></a>

https://ibb.co/37r8LY7

As you can see in the attachment half of the elements are missing. The software is up to date, the browser too. Other sites like yt (Browser) vimeoo and others display correctly.

**Comment by avelad** [comment]
Our UI is not designed to work on SmartTVs, sorry! For SmartTVs you should create your own interface or fix ours so that it works well in your case.
