### ISSUE TITLE
Live french content with accented characters in closed captions using TTML not properly displayed anymore on `v4.8.0`

### ISSUE THREAD

**Issue by Boubalou** [shaka-project/shaka-player#7044]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

Yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes.

**If the question is related to FairPlay, have you read the tutorial?**

Not related.

**What version of Shaka Player are you using?**

4.7.18 and 4.8.0 in that particular case.

**What browser and OS are you using?**

Latest Chrome. Not reproducible on Safari due to the rendering of Closed Captions being handled by the device directly.

**Please ask your question**

We’ve got a little problem with closed captions for live contents since we picked up the new Shaka Player 4.8.0. Our TTML text track did not change, but it seems like Shaka is now using the encoding value of the XML (UTF-8 in our case) to determine the display on screen. Was it a desired change?

After a bit of research, we believe it could have been caused by the change to the DOM Parser (https://github.com/shaka-project/shaka-player/pull/6063). What was the previous behavior regarding the language field `xml:lang="fre"` found in the TTML XML?

| Before | After |
| ------ | ------ |
| <img width="637" alt="Shaka 4 7 x - TTML Rendering" src="https://github.com/user-attachments/assets/f3d43b0f-8cbf-43a1-87f9-266cdcef0882"> | <img width="611" alt="Shaka 4 8 0 - TTML Rendering" src="https://github.com/user-attachments/assets/36f30171-a621-4603-843e-2389911fda8f"> |

Content of our TTML file: 
[Shaka 4.7.x - TTML content.txt](https://github.com/user-attachments/files/16236094/Shaka.4.7.x.-.TTML.content.txt)

**Comment by avelad** [comment]
@Boubalou Can you share a full stream with this to test it better? You can share it privately to shaka-player-maintainers@googlegroups.com

**Comment by avelad** [comment]
I put the following TTML in the player, and it renders fine (using the main branch):

```
<?xml version="1.0" encoding="UTF-8"?>
<tt ttp:cellResolution="40 19" xml:lang="fre" xmlns="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling">
  <head>
    <styling>
      <style tts:fontFamily="monospaceSansSerif" tts:fontSize="80%" xml:id="ttmlStyle"/>
      <style tts:backgroundColor="rgba(0,0,0,0)" tts:displayAlign="center" tts:extent="100% 33%" tts:fontFamily="proportionalSansSerif" tts:fontSize="18px" tts:origin="0% 66%" tts:textAlign="center" xml:id="backgroundStyle"/>
      <style style="backgroundStyle" tts:backgroundColor="transparent" tts:color="white" tts:textOutline="black 1px" xml:id="speakerStyle"/>
      <style style="speakerStyle" tts:backgroundColor="black" tts:color="white" tts:textOutline="none" xml:id="textStyle"/>
    </styling>
    <layout>
      <region tts:extent="100% 100%" tts:origin="0% 0%" tts:zIndex="1" xml:id="full"/>
      <region style="speakerStyle" tts:zIndex="1" xml:id="speaker"/>
      <region style="backgroundStyle" tts:zIndex="0" xml:id="background"/>
      <region tts:extent="17.50% 5.33%" tts:origin="42.50% 84.66%" xml:id="region-446"/>
      <region tts:extent="75% 10.67%" tts:origin="12.50% 79.33%" xml:id="region-94"/>
    </layout>
  </head>
  <body style="ttmlStyle">
    <div>
      <!-- text-based TTML -->
      <p begin="00:00:00.000" end="1514:31:08.000" region="region-94" tts:textAlign="center">
        <span tts:backgroundColor="#000000" tts:color="#FFFFFF">j'ai l'impression qu'une vanne
          <br/>
          a enfin été ouverte.</span>
      </p>
    </div>
  </body>
</tt>
```

**Comment by Boubalou** [comment]
Interesting! I've sent an email with a link to the demo app including our manifest and our license server. Thanks for the quick response.

**Comment by Boubalou** [comment]
@avelad Looking at your test above using your XML hardcoded, the data is different: 

```
        <span tts:backgroundColor="#000000" tts:color="#FFFFFF">j'ai l'impression qu'une vanne
          <br/>
          a enfin été ouverte.</span>
```

vs the data in the text file attached:

```
<span tts:color="#FFFFFF" tts:backgroundColor="#000000">j'ai l'impression qu'une vanne<br/>a enfin &#xE9;t&#xE9; ouverte.</span></p></div></body></tt>
```

**Comment by Boubalou** [comment]
Holy moly, thanks @theodab & @avelad for the quick turnaround and effort! Much appreciated.
