### ISSUE TITLE
Exposing DASH or HLS manifest to Player API

### ISSUE THREAD

**Issue by hugohlln** [shaka-project/shaka-player#7051]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

Not really a problem, just a feature request. Since Player.manifest has been flatten, we don't have access anymore to specific DASH or HLS manifest.

**Describe the solution you'd like**

Being able to get HLS and DASH manifests objects from Player class just to have access to manifests specificities. And also what would be great is being able to trigger an event when there is a dash period transition ..

**Describe alternatives you've considered**

For the moment I've managed to get the manifest once downloaded by the player by registering a response filter on player's network engine :
`this._shakaPlayer.getNetworkingEngine()?.registerResponseFilter((type, response) => {
            if (type == shaka.net.NetworkingEngine.RequestType.MANIFEST) {
                const decoder = new TextDecoder('utf-8');
                const manifestText = decoder.decode(response.data);
                console.log(manifestText)
            }
        });`
But I think that's not a very clean way to do that.

**Additional context**

In my case, my CDN is doing some specific tricks with DASH periods and specifies distinct ids on each period to identify them. Then on client side, we can do specific actions according to the period which is currently playing.

**Are you planning send a PR to add it?**
No, not enough knowledge on ShakaPlayer

**Comment by theodab** [comment]
This doesn't sound very necessary to me. We already have a way to get the manifest text: a response filter, as you are doing here. Making an event that gives you the manifest text would just be making the process one or two lines of code shorter, and would add more complexity and (potentially) more memory usage to Shaka Player.
