### ISSUE TITLE
Is there a method to get the total loaded chunks size?

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#7053]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**
4.10.4

**What browser and OS are you using?**
Both Window and MacOs

**Please ask your question**
I need to get the total size of chunks that **player already loaded**, start from when we load the stream manifest. If possible, this should include the size of video, audio, subtitle. If not, only video chunks is ok.
For exampl my below chunks, I need to get the total size of all .m4s files
![image](https://github.com/user-attachments/assets/654b2171-4a59-431f-8c89-68b0df2832f1)

I think this could be done manually by Javascript but it will be very complicated and have to handle different way for Safari. So I hope shaka already define some function to do this.

Thank you.

**Comment by vanminhquangtri** [comment]
I know there is networkingEngine.registerResponseFilter, but this only show the size of individual chunks

**Comment by avelad** [comment]
In `getStats` you have the total of everything downloaded, if you only want video you can do it with responseFilter and maintaining a local counter of yours stats.

**Comment by vanminhquangtri** [comment]
Thank @avelad
