### ISSUE TITLE
Error with Shaka Player on Firefox: DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE

### ISSUE THREAD

**Issue by AliSeydnezhad** [shaka-project/shaka-player#7057]
**Issue Description:**

When using Shaka Player to play encrypted content with ClearKey DRM in Firefox, an error occurs with the message "Error code 6001 object" and "Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()". This issue does not occur in Chrome or Edge browsers, where the player functions correctly without errors.

**Steps to Reproduce:**

1. Load the provided HTML page containing Shaka Player setup and ClearKey DRM configuration.
2. Attempt to play encrypted content from the specified manifest URI (https://mysite.com/Player/shaka/output.mpd) using Firefox.
3 .Observe the error message in the browser console: "Error code 6001 object" and "Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()".

**Expected Behavior:**

The Shaka Player should successfully load and play encrypted content using ClearKey DRM on all major browsers including Firefox, without encountering DRM configuration errors.

**Actual Behavior:**

Encountered "Error code 6001 object" with "Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()" specifically on Firefox, indicating a failure to retrieve or configure the DRM system correctly.
Environment:

- Browser: Firefox (Version 128.0)
- Shaka Player Version: 4.10.6
- Operating System: Windows 10 / macOS / Linux (Specify if relevant)

**Additional Information:**

- Verified that CORS headers are correctly configured to allow access to the MPD manifest.
- MIME type for .mpd files (application/dash+xml) is properly set.
- ClearKey DRM configuration (clearKeys) is correctly defined in the Shaka Player setup.
- No issues observed on Chrome and Edge browsers, suggesting Firefox-specific DRM configuration or compatibility issue.

**Screenshots:**

Attach any relevant screenshots showing the error message in Firefox's console.

![error](https://github.com/user-attachments/assets/621c6dc9-b908-4d79-a1f8-6ebe388737a6)

**Notes:**

This issue is critical for project success as Firefox compatibility is necessary for wider audience reach. Seeking guidance on resolving the DRM configuration error specifically in Firefox while using Shaka Player with ClearKey DRM.

**Next Steps:**

1. Investigate further into Firefox-specific DRM configuration requirements or limitations with Shaka Player.
2. Test alternative configurations or updates to Shaka Player settings.
3. Seek community or developer insights into similar issues and potential solutions.
4. Continuously monitor Firefox updates or Shaka Player releases for compatibility fixes.

This structured issue report aims to provide clarity on the encountered problem and seeks guidance for resolution to ensure seamless playback across all supported browsers.

**Comment by avelad** [comment]
It seems like some bug related to `encryptionScheme`

**Comment by avelad** [comment]
It seems that Firefox enabled `encryptionScheme` by default and they don't support `encryptionScheme = ""`, so I need fix the player.
