### ISSUE TITLE
Can Fairplay Work 

### ISSUE THREAD

**Issue by brewsterbhg** [shaka-project/shaka-player#7068]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**
Yes

**What version of Shaka Player are you using?**
4.10.7

**What browser and OS are you using?**
Safari 17.5 MacOS Sonoma

**Please ask your question**
We are using Shaka Player for audio streaming. Since our audio server requires authorization, I disabled native HLS in order to forward our authorization headers. This works great for non-DRM content, however, when trying to configure Fairplay with our DRM vendor, I've run into a roadblock (Widevine works great). When making the request to the license server, it doesn't appear to be successfully parsing the key from our manifest for fetching the appropriate asset. Our DRM provider (DRMToday) provides a Fairplay integration guide with Shaka (which I've successfully ran), however, it's using native HLS, and I believe that's what's preventing us from successfully validating with the DRM server.

**Comment by avelad** [comment]
So I understand that you want to use MSE, to do this you have to indicate that for FairPlay you want to use MSE, `streaming.useNativeHlsForFairPlay = false`
