### ISSUE TITLE
How to exactly disable the functionality auto-retry of shaka when error happen?

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#7069]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**
4.6.3
https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.6.3/shaka-player.ui.min.js

**What browser and OS are you using?**
Both Window and macOs

**Please ask your question**
I would like to know how to exactly disable the functionality auto-retry of shaka when streaming has error or manifest has error. What I need is whenever these errors happen, player only need to throw the error and NOT auto retry.
I see there's `streaming.retryParameters.maxAttempts` and `manifest.retryParameters.maxAttempts`. But when set to zero (0), it throws error **Cannot read properties of null (reading 'code')** after call function `player.load(manifestUrl)`

![image](https://github.com/user-attachments/assets/c861dd35-7be2-49a9-bc0f-e9c797fe95f3)

Can you please let me know the exact configuration to do this?
Thank you

**Comment by theodab** [comment]
The number of attempts described by `streaming.retryParameters.maxAttempts` includes the initial attempt, before any retries. Setting it to 0 would mean that we wouldn't try to download anything at all, which doesn't really make sense.

Just set it to 1 instead, if you want to disable retrying.

**Comment by vanminhquangtri** [comment]
Thanks @avelad
