### ISSUE TITLE
Every HLS Content on iOS thriows Error 4032 if preferNativeHls is enabled

### ISSUE THREAD

**Issue by boredom2** [shaka-project/shaka-player#7070]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes

**If the problem is related to FairPlay, have you read the tutorial?**

not related

**What version of Shaka Player are you using?**

4.10.7

**Can you reproduce the issue with our latest release version?**

yes

**Can you reproduce the issue with the latest code from `main`?**

yes

**Are you using the demo app or your own custom app?**

both

**If custom app, can you reproduce the issue using our demo app?**

yes

**What browser and OS are you using?**

iOS 17.2 - 17.4

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

n/a

**What are the manifest and license server URIs?**

any HLS Content, also from the Shaka Demo Page

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

i only configured: streaming.preferNativeHls=false;

**What did you do?**

followed the basic example, installed all Polyfills, added the config.streaming.preferNativeHls=false and started on iOS 17.2 and iOS 17.4.

**What did you expect to happen?**

Video would be able to play

**What actually happened?**

#

Error 4032 is emitted. This also happens on you official Demo Page, if I select any HLS Content.
If I use preferNativeHls=true, then Playback works absolutely fine.

Maybe I make a mistake and misunderstand something, but it feels very wrong, that a simple HLS Manifest cant be loaded when we use ManagedMediaSource (at least thats what I think is happening, when preferNativeHls is disabled).

**Are you planning send a PR to fix it?**

**Comment by theodab** [comment]
I'm not seeing any issues on my iPhone, playing HLS assets on the demo.

I'm using iOS 17.5.1, so it's possible there was a bug in the MediaSource implementation that was fixed sometime after 17.4.

**Comment by boredom2** [comment]
I agree.
I tested it on iOS Simulators, and there, indeed nothing is working on any iOS Version (at least on my mac).
On real devices, uits working indeed.
That will make Development more complicated, but i guess, thats not really an issue then.
Thanks!

**Comment by theodab** [comment]
Oh yeah, more "obscure" APIs like MediaSource don't always work the same way in the iOS simulator as in an actual device. It's annoying, but there's not much you can do about it.
