### ISSUE TITLE
The video subelement track is deleted

### ISSUE THREAD

**Issue by dsyscms** [shaka-project/shaka-player#7080]
`
   <video id="video" width="640" height="360" controls autoplay>
      <track default="" kind="metadata" src="">
    </video>
`

The track element will not be deleted when the video is played for the first time

When switching video streams(manifestUri address is different), the track element is deleted.

`
await player.load(manifestUri);
`

**Comment by avelad** [comment]
It’s the expected behavior, why do you need it?

**Comment by dsyscms** [comment]
Subtitles rely on track elements,The track element is deleted, which causes the element to be not found, thus affecting the loading of subtitles
`<track default="" kind="metadata" src="blob:http://localhost:3000/1daf4b3a-2f94-4065-b22a-bd164347fc6f">`

**Comment by avelad** [comment]
We have an API to add external subtitles: `addTextTrackAsync` , you need use it.

**Comment by dsyscms** [comment]
The project must use the track element because the subtitle function has been implemented.
Since deletion is the expected behavior, why is it not deleted the first time it is called?

**Comment by avelad** [comment]
Because the player doesn’t support mix internal text tracks and video tracks

**Comment by dsyscms** [comment]
If possible, please keep it and don't delete it.
Many people use shaka-player mainly to replace dash.js
Generally, only shaka-player is needed to provide dash format video playback function
