### ISSUE TITLE
Preload next episode

### ISSUE THREAD

**Issue by shubhankarMitra** [shaka-project/shaka-player#7085]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

**What browser and OS are you using?**

**Please ask your question**

I am using shaka player "4.7.12" and i want to know whats the optimal way preload the next episode in the series,i want the player to preload the next manifest and play it after the user clicks "play next episode"

**Comment by avelad** [comment]
You can use something like:

```
const player = new shaka.Player();

await player.load('CURRENT_EPISODE');

const preloadManager = await player.preload('NEXT_EPISODE');

element.addEventListener('click', () => {
  if (preloadManager) {
    player.load(preloadManager);
  } else {
    player.load('NEXT_EPISODE')
  }
});
```

**Comment by shubhankarMitra** [comment]
is there any way for shaka to fetch the manifest because EPISODE_URL s are a part of the manifest,which is being fetched from server.

**Comment by shubhankarMitra** [comment]
Fixed it,thanks a lot for help
