### ISSUE TITLE
Time syncing issue in external texttracks (WebVtt) when there are ad markers in manifest files (HLS, DASH)

### ISSUE THREAD

**Issue by pankaj4may** [shaka-project/shaka-player#7088]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Not thoroughly

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**If the question is related to FairPlay, have you read the tutorial?**

NO

**What version of Shaka Player are you using?**
4.10

**What browser and OS are you using?**
Chrome, Windows 10

**Please ask your question**
When I load a player with manifest having Ad markers and external webvtt file(s), It is not time synced. I believe there must exists a configuration which do auto syncing of the external vtt files.

**Comment by avelad** [comment]
We can't help you with the information you provide...

Do subtitles take ads into account? What type of ads do you use? IMA, MediaTailor?

**Comment by pankaj4may** [comment]
Hi Avelad,
Subtitles don't take ad into account. Ad markers are coming in as VMAP response to AWS MediaTailor service. For the same video on demand content I can have ad markers at different times based on 2 AWS EMT configurations.
EMT EndPoint 1 --- Ad markers at say 1 & 3 minutes
EMT EndPoint 2 --- Ad markers at say 2 & 4 minutes.
External WebVTT file has subtitles for the VOD content only (lets say 5 minute video)

I hope the above info gives enough information to suggest the possible solutions

**Comment by avelad** [comment]
Are you using our Ad Manager to manage AWS MediaTailor?

**Comment by pankaj4may** [comment]
> Are you using our Ad Manager to manage AWS MediaTailor?
Yes

**Comment by avelad** [comment]
I don't see anything obvious about what's wrong, because the code takes ads into account (see https://github.com/shaka-project/shaka-player/blob/main/lib/player.js#L5702) please fill out the bug template and so we can have more details to know what is happening.

**Comment by pankaj4may** [comment]
Thanks for the prompt reply. I'll check and revert.
I am calling addTextTrackAsync after player.load(), I believe need to add TextTracks in -
adManager.addEventListener(shaka.ads.Utils.ADS_LOADED,(e) => {
		  console.log('ADS_LOADED');
});
