### ISSUE TITLE
If the first segment of an hls stream does not have CEA-x08 tracks embedded, Tracks are never added when subsequent segments contain them

### ISSUE THREAD

**Issue by jonp-iversoft** [shaka-project/shaka-player#7094]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

4.10.8

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
Custom

**If custom app, can you reproduce the issue using our demo app?**
Cannot get the stream to play using custom app

**What browser and OS are you using?**
Chrome/macos

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Tizen 8

**What are the manifest and license server URIs?**

n/a, but the manifest looks like this:
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:6.006,
#EXT-X-PROGRAM-DATE-TIME:2024-07-23T14:24:39.000Z
/stream/segw.ts?yjt9foUpb41acsxRoA7oDQ
#EXTINF:6.006,
#EXT-X-PROGRAM-DATE-TIME:2024-07-23T14:24:45.006Z
/stream/segw.ts?poZFQMmYm9h2k9R1R4Gp1A
#EXTINF:6.006,
#EXT-X-PROGRAM-DATE-TIME:2024-07-23T14:24:51.012Z
/stream/segw.ts?WVikdqzUtYGMKuyFeazaqg
```

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```
const shakaConfig = {
            streaming: {
                preferNativeHls: false, 
                lowLatencyMode: true, 
                bufferingGoal:  60,
                rebufferingGoal:  30,
                bufferBehind:  60,
                stallEnabled: true, 
                stallThreshold: 2, 
                stallSkip: 1, 
                updateIntervalSeconds: 1, 
                alwaysStreamText: true, 
                retryParameters: {
                    timeout: 10000, 
                    stallTimeout: 5000, 
                    connectionTimeout: 10000, 
                    maxAttempts: 2, 
                    baseDelay: 1000, 
                    backoffFactor: 2, 
                    fuzzFactor: 0.5 
                }
            },
            manifest: {
                availabilityWindowOverride: Infinity,
                retryParameters: {
                    timeout: 10000, 
                    stallTimeout: 5000, 
                    connectionTimeout: 10000, 
                    maxAttempts: 2, 
                    baseDelay: 1000, 
                    backoffFactor: 2, 
                    fuzzFactor: 0.5 
                },
                hls: {
                    ignoreTextStreamFailures: false
                }
            },
            mediaSource: {
                forceTransmux: true
            },

            preferredAudioLanguage: "en"
        }
```

**What did you do?**

Start a live hls/ts (mp4) OTT stream where the first segment does NOT have CEA-x08 tracks (say, a commercial)

**What did you expect to happen?**
Text tracks should be added when additional segments video includes text tracks

**What actually happened?**

Start a live hls/ts (mp4) OTT stream where the first segment does NOT have CEA-x08 tracks (say, a commercial) - then when an airing continues after a commercial where there are tracks, Shaka does not add them to the track list.  

This is being checked via `player.getTextTracks()` on a time tick.  

If the first segment of the hls stream is the airing that does have text tracks, shaka performs as expected.

**Are you planning send a PR to fix it?**
Not at this time

**Comment by avelad** [comment]
Does your master playlist not include CEA information?

**Comment by jonp-iversoft** [comment]
It does not, but even if I add it manually via 
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="CC",LANGUAGE="CC1",NAME="English",DEFAULT=YES,AUTOSELECT=YES,INSTREAM-ID="CC1"
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:6.006,
#EXT-X-PROGRAM-DATE-TIME:2024-07-23T14:24:39.000Z
/stream/segw.ts?yjt9foUpb41acsxRoA7oDQ
#EXTINF:6.006,
#EXT-X-PROGRAM-DATE-TIME:2024-07-23T14:24:45.006Z
```
It does the same thing :\

**Comment by avelad** [comment]
Media tags are only allowed in the Multivariant Playlist. You can verify this using the `mediastreamvalidator`.

Our current behaviour when there are not a master playlist (you only provide the media playlist) is only check the first segment for VoD.

**Comment by jonp-iversoft** [comment]
Is there any way to check the current segments of a VoD for embedded cc tracks?

**Comment by avelad** [comment]
> Is there any way to check the current segment of a VoD for embedded cc tracks?

No

**Comment by jonp-iversoft** [comment]
I was able to get the master playlist and inject the `#EXT-X-MEDIA` tag into it, and it looks like it might solve the issue. Thanks for your input!

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-STREAM-INF:BANDWIDTH=10000000
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="CC",LANGUAGE="CC1",NAME="English",DEFAULT=YES,AUTOSELECT=YES,INSTREAM-ID="CC1"
/stream/pls.m3u8?iDxKsllfxF144EDlLywvew&fmt=v4
```
