### ISSUE TITLE
Emsg and Metadata events

### ISSUE THREAD

**Issue by dloftus** [shaka-project/shaka-player#7097]
Pertains to  any Shaka version 4.3  -  latest 

Using Chrome on MacOS 

Stream :   DASH with Emsg

**Background**
When playing a DASH stream, upon encountering an Emsg box, Shaka Player releases two events: an _Emsg_ event, and a _Metadata_ event.   The _Metadata_ event presumably provides a more convenient means of consuming the metadata payload, by conveying text rather than raw data.

However, there is a disparity between _Emsg_ and _Metadata_ with respect to the PTS conveyed.

- The _Emsg_ event conveys the PTS value read from the Emsg box.
- The _Metadata_ event conveys the start time of the segment that contained the metadata.
- Additionally,  a _Metadata_ event with a `cueTime` of 0 will not be dispatched, because the relevant code requires `cueTime` to be 'truthy'.

The relevant code can be found in `streaming_engine.js/parseEMSG_`, where the Metadata event is composed, and in `player.js/processTimedMetadataMediaSrc_`, where the Metadata event is dispatched.

**Questions**
1) Is there a reason that the metadata event conveying an Emsg/ID3 payload carries the SegmentReference start time rather than the PTS of the Emsg?

2) Is there a reason events with cue time of 0 are ignored?

**Comment by avelad** [comment]
Fix for the metadata event: https://github.com/shaka-project/shaka-player/pull/7098

**Comment by avelad** [comment]
Do you have a sample stream for the EMSG part? Thanks!

**Comment by dloftus** [comment]
> Do you have a sample stream for the EMSG part? Thanks!

Yeah, the hard part!   working on it...

**Comment by avelad** [comment]
Both PR merged!
