### ISSUE TITLE
Ability to change/override icons

### ISSUE THREAD

**Issue by i2iRobert** [shaka-project/shaka-player#7103]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently it appears Shaka doesn't allow for CSS overrides of icons.

In our case we want to change the "Closed Caption" icon from the CC in a box to a more generic YouTube style pictogram with the lines at the bottom of a square.

This is because in our geographical region "CC" doesn't mean anything, the convention is to use "Subtitle".

**Describe alternatives you've considered**
We've attempted replicating the code for "Closed Caption" in order to re-add it to the player, but it was becoming a rabbit hole of code duplication and the knock on of code maintenance on any updates.

We researched CSS overrides and other tricks but nothing was possible 

**Additional context**
Shaka Player
![image](https://github.com/user-attachments/assets/2fe99adf-b3b5-4c66-8b26-7b5979f71bdc)

YouTube
![image](https://github.com/user-attachments/assets/06777d81-2a1a-4bd9-b6e4-9f5960cd91fe)

**Are you planning send a PR to add it?**
No

**Comment by avelad** [comment]
We have already created an issue to migrate to SVG that will make this much easier: https://github.com/shaka-project/shaka-player/issues/2467
