### ISSUE TITLE
How to change the possition of current time and duration of control bar?

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#7106]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**
4.10.6
https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.10.6/shaka-player.ui.min.js

**What browser and OS are you using?**
Window and macOS

**Please ask your question**
This is demo link:
https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://vod02-cdn.fptplay.net/POVOD/encoded/2024/03/05/desperado-1995-us-1709599664/master.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

What I want is to show the current time, seek bar, and duration in one line.
I think about using set interval or event like timeupdate to manipulate the dom, append dom, etc, but I think these way can cause player not work properly.
So I wonder if shaka provider any configuration for this? Thank you so much.
![Screenshot_2](https://github.com/user-attachments/assets/15ad9444-739f-43d1-b939-0e94e3290324)

**Comment by avelad** [comment]
There is currently no config for this, and given the construction of the elements, I don't think it can be easily modified by CSS. Sorry!

**Comment by vanminhquangtri** [comment]
Thanks @avelad
