### ISSUE TITLE
Video playack interrupts

### ISSUE THREAD

**Issue by shubhankarMitra** [shaka-project/shaka-player#7112]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

yes

**What version of Shaka Player are you using?**

4.7.12

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
custom

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
os : windows,ubuntu , browser chrome,firefox 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Are you planning send a PR to fix it?**

Scenario:

![Screenshot from 2024-07-26 14-21-09](https://github.com/user-attachments/assets/7783d364-cd89-46d9-ab3e-3be0bc28f5a6)

Shaka player is loading the init audio chunk and then restarts loading the video chunks from beginning,you can see that in network tab and it fails and the video is interrupted.
Please tell me a possible fix for this

**Comment by avelad** [comment]
Please fill out this information, otherwise we will not be able to help you.

```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```
