### ISSUE TITLE
How to get AWS ID3 Marker in shaka player?

### ISSUE THREAD

**Issue by fakeDev9** [shaka-project/shaka-player#7120]
Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?
Yes

Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
Yes

If the question is related to FairPlay, have you read the tutorial?

No

What version of Shaka Player are you using?
4.10.9

What browser and OS are you using?
Chrome on iOS

Please ask your question
how to get id3 marker in player

**Comment by f1multiviewer** [comment]
You can listen for ID3 markers like so:

```ts
player.addEventListener("metadata", (event) => {
  console.log(event)
});
```

[See the documentation](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:MetadataEvent)

**Comment by avelad** [comment]
@f1multiviewer 's answer is correct, if that doesn't work please there will be a bug issue so we can investigate the problem
