### ISSUE TITLE
How to make player run smoothly when gap jumping happen

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#7130]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**
4.10.6

**What browser and OS are you using?**
Window and macOS

**Please ask your question**
**This is demo link:**
https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://vips-livecdn.fptplay.net/MTA4NDUxNDB8Y25iY19obHMuc21pbHxmcHR8MTcyMjg1MTE0MXwxMDAuOTEuMTI1LjgxfGEwNDc3MTViOWM3MjE4MDA4NjRhZWQwNzZmMDkwYzZm/fnxhd2/cnbc_hls.smil/playlist.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled

**The manifest is:**
https://vips-livecdn.fptplay.net/MTA4NDUxNDB8Y25iY19obHMuc21pbHxmcHR8MTcyMjgyNjE2NHwxLjU0Ljg5LjE1NHw5NDcwY2Y2M2U0M2FhMDNkY2MwZWY2YWE3MDdlNTI4Mw/fnxhd2/cnbc_hls.smil/playlist.m3u8

You can see that the player is frequently stop for a while then continue. I see the error is due to time range not proper and have to transcode again. 
But is there configure way to make the player play smoothly without changing the transcode or change the manifest?

Thank you.

**Comment by vanminhquangtri** [comment]
Hi as checked with videojs with same maniffest URL: the player is running smoothly so I think we can make some configuration to make shaka player run smoothly too.
https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&fluid=false&minified=false&sync-workers=false&liveui=true&llhls=true&url=https%3A%2F%2Fvips-livecdn.fptplay.net%2FMTA4NDUxNDB8Y25iY19obHMuc21pbHxmcHR8MTcyMjgyNjE2NHwxLjU0Ljg5LjE1NHw5NDcwY2Y2M2U0M2FhMDNkY2MwZWY2YWE3MDdlNTI4Mw%2Ffnxhd2%2Fcnbc_hls.smil%2Fplaylist.m3u8&type=application%2Fx-mpegURL&keysystems=&buffer-water=false&exact-manifest-timings=false&pixel-diff-selector=false&network-info=false&dts-offset=false&override-native=true&preload=auto&mirror-source=true&forced-subtitles=false

**Comment by vanminhquangtri** [comment]
Hi @avelad @theodab can you please take a look this issue? It is happening on my production version so I hope to solve this as soon as possible. Thank you.

**Comment by vanminhquangtri** [comment]
Can anyone please take a look at this? Thank you.

**Comment by joeyparrish** [comment]
Looks like this question is superceded by bug #7138, so I'll close this and respond there.  Thanks!
