### ISSUE TITLE
Buffering in Multi Period MPD File - Shaka Player

### ISSUE THREAD

**Issue by smriti0302** [shaka-project/shaka-player#7134]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes

**If the question is related to FairPlay, have you read the tutorial?** N/A

**What version of Shaka Player are you using?** 4.9

**What browser and OS are you using?** Windows OS

**Please ask your question**

I use Shaka Player in my React website to play yoga videos in yoga classes. The different yoga videos are packages using Shaka Packager (with and without PlayReady DRM) and playlists (sequence of yoga videos) are made. These playlists have a combined manifest which has multiple periods, each period denoting one yoga video in the playlist. I'm attaching a sample MPD file.

[
[sample_mpd.txt](https://github.com/user-attachments/files/16501232/sample_mpd.txt)
](url)

My issue right now is that when i play this in the player, it starts buffering in the middle of certain videos. My scenario requires me to play these videos seamlessly with no buffering. I'd packaged the videos with a segment duration of 10 seconds, and have used CMAF. Running out of ideas as to how I can prevent this behaviour. Request guidance on this issue.

Edit : I have transcoded videos at CRF 15, 19, 23. I noticed that the segment size is extremely huge for a video of 1.7GB. I thus changed the CRFs to 24, 27, 30. When throttling, buffering usually happens when switches are made between the CRFs. Is there one particular CRF value I can use such that the video would play under any network conditions, and the quality wouldnt be compromised too much?

Is there a way to instruct the shaka parser to always use, say, CRF 30 encoded videos irrespective of network?

**Comment by avelad** [comment]
Maybe related to https://github.com/shaka-project/shaka-player/issues/7174 ?
