### ISSUE TITLE
Maintain the aspect ratio and remove top bar in PiP (Picture-in-Picture)

### ISSUE THREAD

**Issue by hijuuijj** [shaka-project/shaka-player#7137]
I would like to maintain the aspect ratio and remove the top bar when I'm in PiP mode, as it was before version 4.4.0. Is there a way to do this with the new version?

**Comment by avelad** [comment]
You can use the old way by setting the ui with preferDocumentPictureInPicture = false

Tutorial for UI config
https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html
