### ISSUE TITLE
How to switch captions and audio tracks using the keyboard?

### ISSUE THREAD

**Issue by hijuuijj** [shaka-project/shaka-player#7142]
How to switch captions and audio tracks using the keyboard? I would like to switch with A and C.
Is there a way to load all those default keyboard shortcuts?

This is my code:

			document.addEventListener('keydown', (event) => {
				switch (event.key) {
					case ' ':
						videoElement.paused ? videoElement.play() : videoElement.pause();
						break;
					case 'ArrowLeft':
						videoElement.currentTime -= 10;
						break;
					case 'ArrowRight':
						videoElement.currentTime += 10;
						break;
					case 'ArrowUp':
						videoElement.volume = Math.min(1, videoElement.volume + 0.1);
						break;
					case 'ArrowDown':
						videoElement.volume = Math.max(0, videoElement.volume - 0.1);
						break;
					case 'm':
						videoElement.muted = !videoElement.muted;
						break;
					case 'f':
						document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen();
						break;
				}
				event.preventDefault();
			});
		}

		document.addEventListener('shaka-ui-loaded', init);

**Comment by joeyparrish** [comment]
You could add 'a' and 'c' to your switch statement and use those keys to call some combination of methods like:

 - [player.getAudioLanguagesAndRoles()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#getAudioLanguagesAndRoles)
 - [player.getTextLanguagesAndRoles()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#getTextLanguagesAndRoles)
 - [player.selectAudioLanguage()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#selectAudioLanguage)
 - [player.selectTextLanguage()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#selectTextLanguage)

If your tracks don't change mid-playback, you could call the `get` functions above right after `load()` completes, then arrange the languages/roles into an array that you cycle through when 'a' and 'c' are pressed.  Increment an index, then call the `select` method.  Something like:

```js
await player.load(url);
audio = player.getAudioLanguagesAndRoles();
audioIndex = 0;  // Assuming this is the default... may want something else here
```

```js
case 'a': {
  audioIndex++;
  const newAudio = audio[audioIndex % audio.length];
  player.selectAudioLanguage(newAudio.language, newAudio.role);
}
```

Does this help?

**Comment by hijuuijj** [comment]
The audio track works with the 'A' key, but the captions/subtitles don’t work with the 'C' key.

Do you know where the problem might be?

Thank you.

`<script>
		const manifestUri = '<?=$url?>';
		let audio = [], audioIndex = 0, text = [], textIndex = 0;

		async function init() {
			const player = document.getElementById('video')['ui'].getControls().getPlayer();
			await player.load(manifestUri);
			document.querySelector('[data-shaka-player-container]').focus();
			audio = player.getAudioLanguagesAndRoles();
			text = player.getTextLanguagesAndRoles();
		}

		document.addEventListener('keydown', event => {
			const video = document.getElementById('video');
			const player = video['ui'].getControls().getPlayer();
			const volumeStep = 0.1;

			switch (event.key) {
				case ' ': video.paused ? video.play() : video.pause(); break;
				case 'ArrowLeft': video.currentTime -= 10; break;
				case 'ArrowRight': video.currentTime += 10; break;
				case 'ArrowUp': video.volume = Math.min(video.volume + volumeStep, 1); break;
				case 'ArrowDown': video.volume = Math.max(video.volume - volumeStep, 0); break;
				case 'KeyP': video.paused ? video.play() : video.pause(); break;
				case 'KeyF': document.fullscreenElement ? document.exitFullscreen() : video.requestFullscreen(); break;
				case 'a':
					if (audio.length) {
						audioIndex = (audioIndex + 1) % audio.length;
						const { language, role } = audio[audioIndex];
						player.selectAudioLanguage(language, role);
					}
					break;
				case 'c':
					if (text.length) {
						textIndex = (textIndex + 1) % text.length;
						const { language, role } = text[textIndex];
						player.selectTextLanguage(language, role);
					}
					break;
			}
			event.preventDefault();
		});

		document.addEventListener('shaka-ui-loaded', init);
	</script>`

**Comment by hijuuijj** [comment]
> You could add 'a' and 'c' to your switch statement and use those keys to call some combination of methods like:
> 
> * [player.getAudioLanguagesAndRoles()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#getAudioLanguagesAndRoles)
> * [player.getTextLanguagesAndRoles()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#getTextLanguagesAndRoles)
> * [player.selectAudioLanguage()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#selectAudioLanguage)
> * [player.selectTextLanguage()](https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#selectTextLanguage)
> 
> If your tracks don't change mid-playback, you could call the `get` functions above right after `load()` completes, then arrange the languages/roles into an array that you cycle through when 'a' and 'c' are pressed. Increment an index, then call the `select` method. Something like:
> 
> ```js
> await player.load(url);
> audio = player.getAudioLanguagesAndRoles();
> audioIndex = 0;  // Assuming this is the default... may want something else here
> ```
> 
> ```js
> case 'a': {
>   audioIndex++;
>   const newAudio = audio[audioIndex % audio.length];
>   player.selectAudioLanguage(newAudio.language, newAudio.role);
> }
> ```
> 
> Does this help?

In addition to the issue with the 'C' key, I've observed another problem. The SPACE, F, and M keys are enabled by default, but they only work if I click on the progress bar first. Otherwise, they don't respond. What could be the cause of this?

`<html>
<head>
	<script src="//ajax.googleapis.com/ajax/libs/shaka-player/4.10.9/shaka-player.ui.js"></script>
	<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/shaka-player/4.10.9/controls.css">
	<style>
		body, html {width: 100%; height: 100%; margin: 0; background: #000;}
		video {width: 100%; height: 100%; display: block; user-select: none;}
	</style>
</head>
<body>
	<div data-shaka-player-container style="width:100%; height:100vh;">
		<video data-shaka-player id="video"></video>
	</div>
	<script>
		const manifestUri = '<?=$url?>';
		async function init() {
			const videoElement = document.getElementById('video');
			const ui = videoElement['ui'];
			const controls = ui.getControls();
			const player = controls.getPlayer();
			await player.load(manifestUri);
		}
		document.addEventListener('shaka-ui-loaded', init);
	</script>
</body>
</html>`

**Comment by hijuuijj** [comment]
> You could add 'a' and 'c' to your switch statement and use those keys to call some combination of methods like:

In addition to the issue with the 'C' key, I've observed another problem. The SPACE, F, and M keys are enabled by default, but they only work if I click on the progress bar first. Otherwise, they don't respond. What could be the cause of this?

`<html>
<head>
	<script src="//ajax.googleapis.com/ajax/libs/shaka-player/4.10.9/shaka-player.ui.js"></script>
	<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/shaka-player/4.10.9/controls.css">
	<style>
		body, html {width: 100%; height: 100%; margin: 0; background: #000;}
		video {width: 100%; height: 100%; display: block; user-select: none;}
	</style>
</head>
<body>
	<div data-shaka-player-container style="width:100%; height:100vh;">
		<video data-shaka-player id="video"></video>
	</div>
	<script>
		const manifestUri = '<?=$url?>';
		async function init() {
			const videoElement = document.getElementById('video');
			const ui = videoElement['ui'];
			const controls = ui.getControls();
			const player = controls.getPlayer();
			await player.load(manifestUri);
		}
		document.addEventListener('shaka-ui-loaded', init);
	</script>
</body>
</html>`

**Comment by avelad** [comment]
For the subtitles the problem is that you are not activating their visibility, for this you should call `setTextTrackVisibility`

The problem with `f` and `m` is that we only listen to the event when the videoContainer is focused, if the focus is somewhere else, those keys will not work. If you want to disable the default behavior of these keys, you can configure it in the UI with enableKeyboardPlaybackControls
