### ISSUE TITLE
When calling master m3u8 in shaka player, it always calls the highest playlist.

### ISSUE THREAD

**Issue by brodiddev** [shaka-project/shaka-player#7145]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes 

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
4.8.4

**What browser and OS are you using?**
window chrome 

**Please ask your question**
This phenomenon is the same even when selecting a 360p track to play, it requests a 1080p playlist and requests 360p. Is it possible to fix this phenomenon without setting restriction in abr option?

**Comment by avelad** [comment]
This depends on the ABR, I recommend you change useNetworkInformation to false and set defaultBandwidthEstimate to the value you want.

**Comment by brodiddev** [comment]
Even if abr is disabled and playback starts at 360p, which is manual quality, the 1080p playlist is called. Is it possible to solve it?
