### ISSUE TITLE
Playback speed on webOS

### ISSUE THREAD

**Issue by Pokakoli** [shaka-project/shaka-player#7154]
Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?
Yes

Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
Yes

If the question is related to FairPlay, have you read the tutorial?
Not related

What version of Shaka Player are you using?
4.10.9

What browser and OS are you using?
WebOS, chrome

Please ask your question
I tried displaying DRM content on WebOS and using a custom controller. Everything works fine in the browser, but when on TV, the playback speed is not working. I've tried using video.playbackRate and video.trickPlay, but everything doesn't work. Is there any other way I can try?

**Comment by joeyparrish** [comment]
video.playbackRate and player.trickPlay (which sets video.playbackRate) are the only ways I'm aware of.  Does playbackRate work on WebOS outside of Shaka Player, in a simple HTML `<video>` element?

**Comment by Pokakoli** [comment]
I haven't tried it, but webOS said that they don't support playback speed for native players. So I guess playback speed won't work on webOS
