### ISSUE TITLE
Unable to play one video segment of the video on WPE WebKit 2.22.1 browser

### ISSUE THREAD

**Issue by ubaidashraf** [shaka-project/shaka-player#7159]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**

4.10.9  

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app
**If custom app, can you reproduce the issue using our demo app?**

No, but can see error warning in console of demo app at exact video segment. 

**What browser and OS are you using?**
 WPE WebKit 2.22.1 
 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Horizon from liberty media 

**What are the manifest and license server URIs?**

https://699f4b4fd221407ead714c33183bba51.mediatailor.eu-west-1.amazonaws.com/v1/manifest/774d979dd66704abea7c5b62cb34c6815fda0d35/virgin-vod/9ff7ec6f-4576-401c-a3e0-4643c3f2b5d1/4.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

 Object = $2
abr: {enabled: true, useNetworkInformation: true, defaultBandwidthEstimate: 1000000, switchInterval: 8, bandwidthUpgradeTarget: 0.85, …}
abrFactory: function()
ads: {customPlayheadTracker: true, skipPlayDetection: true, supportsMultipleMediaElements: false}
autoShowText: 3
cmcd: {enabled: false, sessionId: "", contentId: "", rtpSafetyFactor: 5, useHeaders: false, …}
cmsd: {enabled: true, applyMaximumSuggestedBitrate: true, estimatedThroughputWeightRatio: 0.5}
drm: {retryParameters: Object, servers: {}, clearKeys: {}, advanced: {}, delayLicenseRequestUntilPlayed: false, …}
lcevc: {enabled: false, dynamicPerformanceScaling: true, logLevel: 0, drawLogo: false}
manifest: {retryParameters: Object, availabilityWindowOverride: NaN, disableAudio: false, disableVideo: false, disableText: false, …}
mediaSource: {codecSwitchingStrategy: "smooth", addExtraFeaturesToSourceBuffer: function, forceTransmux: false, insertFakeEncryptionInInit: true, modifyCueCallback: function}
offline: {trackSelectionCallback: function, downloadSizeCallback: function, progressCallback: function, usePersistentLicense: true, numberOfParallelDownloads: 5}
playRangeEnd: Infinity
playRangeStart: 0
preferForcedSubs: false
preferSpatialAudio: false
preferredAudioChannelCount: 2
preferredAudioCodecs: [] (0)
preferredAudioLabel: ""
preferredAudioLanguage: ""
preferredDecodingAttributes: [] (0)
preferredTextLanguage: ""
preferredTextRole: ""
preferredVariantRole: ""
preferredVideoCodecs: [] (0)
preferredVideoHdrLevel: "AUTO"
preferredVideoLabel: ""
preferredVideoLayout: ""
restrictions: {minWidth: 0, maxWidth: Infinity, minHeight: 0, maxHeight: Infinity, minPixels: 0, …}
streaming: {retryParameters: Object, failureCallback: function, rebufferingGoal: 2, bufferingGoal: 10, bufferBehind: 30, …}
textDisplayFactory: function()
textDisplayer: {captionsUpdatePeriod: 0.25}

**What did you do?**

Video stops playing at exact 2 minutes 12 seconds on device.  

**What did you expect to happen?**
If there is issue with video chunk, it could be skipped. But shaka player doesn't recover

**What actually happened?**

Video plays fine upto 2 minutes and 12 seconds. Then it stops playing and never recovers. First 2 minutes and 20 seconds are the ads in video. If ads are not there, rest of the video plays without an issue.  
Logs from player when video stops: 
[Log] (audio:47) – "clear: handling right now" (shaka-player.compiled.debug.js, line 144)
[Log] (audio:47) – "clearing buffer" (shaka-player.compiled.debug.js, line 144)
[Log] (audio:47) – "cleared buffer" (shaka-player.compiled.debug.js, line 144)
[Log] Find 0 (shaka-player.compiled.debug.js, line 144)
[Log] Using full mime type – "audio/mp4; codecs=\"mp4a.40.2\"" (shaka-player.compiled.debug.js, line 144)
[Log] Using full mime type – "video/mp4; codecs=\"avc1.640028\"" (shaka-player.compiled.debug.js, line 144)
[Log] Calling switch_(), bandwidth=25919 kbps (shaka-player.compiled.debug.js, line 144)

Exact ts video chunk which fails as can be seen in manifest: 
https://segments.mediatailor.eu-west-1.amazonaws.com/tm/774d979dd66704abea7c5b62cb34c6815fda0d35/o227vnkjsre4tb5kv4t5puqvzdei76jc/asset_1080_5_4_00001.ts
 
 If I use demo app here :  https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://699f4b4fd221407ead714c33183bba51.mediatailor.eu-west-1.amazonaws.com/v1/manifest/774d979dd66704abea7c5b62cb34c6815fda0d35/virgin-vod/9ff7ec6f-4576-401c-a3e0-4643c3f2b5d1/4.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled;visualizer
 
 Above logs warning at exact same place where it breaks on the box but plays still: **Unrecognized ID3 frame type: COMM**  
 
 
 Standalone test case: https://hybridtv.ss7.tv/tests/playback/shaka/for-shaka-issue-7159.html 
**Are you planning send a PR to fix it?**
No

**Comment by ubaidashraf** [comment]
**Manifest:** https://hybridtv.ss7.tv/whitelabel/app/release/1.127.0/default-horizon-default.html?env=prd&platform=hzn&cid=vmtv&platformenv=prd&service=horizon&httpforced=1&skipsplash=1&shakadebug=1 

**player.getConfiguration() output :** 
Object = $2
abr: {enabled: true, useNetworkInformation: true, defaultBandwidthEstimate: 1000000, switchInterval: 8, bandwidthUpgradeTarget: 0.85, …}
abrFactory: function()
ads: {customPlayheadTracker: true, skipPlayDetection: true, supportsMultipleMediaElements: false}
autoShowText: 3
cmcd: {enabled: false, sessionId: "", contentId: "", rtpSafetyFactor: 5, useHeaders: false, …}
cmsd: {enabled: true, applyMaximumSuggestedBitrate: true, estimatedThroughputWeightRatio: 0.5}
drm: {retryParameters: Object, servers: {}, clearKeys: {}, advanced: {}, delayLicenseRequestUntilPlayed: false, …}
lcevc: {enabled: false, dynamicPerformanceScaling: true, logLevel: 0, drawLogo: false}
manifest: {retryParameters: Object, availabilityWindowOverride: NaN, disableAudio: false, disableVideo: false, disableText: false, …}
mediaSource: {codecSwitchingStrategy: "smooth", addExtraFeaturesToSourceBuffer: function, forceTransmux: false, insertFakeEncryptionInInit: true, modifyCueCallback: function}
offline: {trackSelectionCallback: function, downloadSizeCallback: function, progressCallback: function, usePersistentLicense: true, numberOfParallelDownloads: 5}
playRangeEnd: Infinity
playRangeStart: 0
preferForcedSubs: false
preferSpatialAudio: false
preferredAudioChannelCount: 2
preferredAudioCodecs: [] (0)
preferredAudioLabel: ""
preferredAudioLanguage: ""
preferredDecodingAttributes: [] (0)
preferredTextLanguage: ""
preferredTextRole: ""
preferredVariantRole: ""
preferredVideoCodecs: [] (0)
preferredVideoHdrLevel: "AUTO"
preferredVideoLabel: ""
preferredVideoLayout: ""
restrictions: {minWidth: 0, maxWidth: Infinity, minHeight: 0, maxHeight: Infinity, minPixels: 0, …}
streaming: {retryParameters: Object, failureCallback: function, rebufferingGoal: 2, bufferingGoal: 10, bufferBehind: 30, …}
textDisplayFactory: function()
textDisplayer: {captionsUpdatePeriod: 0.25}
Object Prototype

**Comment by spikything** [comment]
The Set Top Box in question is the 'Apollo' box, on the Horizon 4 platform, from Liberty Global https://www.libertyglobal.com/the-mini-tv-box-our-smallest-greenest-set-top-box/

**Comment by spikything** [comment]
I created a standalone testcase for this https://hybridtv.ss7.tv/tests/playback/shaka/for-shaka-issue-7159.html

You can also test the same content via the demo player, which simply gives up playback at the same stall point https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://699f4b4fd221407ead714c33183bba51.mediatailor.eu-west-1.amazonaws.com/v1/manifest/774d979dd66704abea7c5b62cb34c6815fda0d35/virgin-vod/9ff7ec6f-4576-401c-a3e0-4643c3f2b5d1/4.m3u8;panel=CUSTOM%20CONTENT;build=uncompiled;debug

On the Liberty Global Horizon 4 'Apollo' box (which runs WPE 2.22.1) it stalls at the end of the first pre-roll advert with the debug output:

`Stall detected at 31.994666333 for 1.003000020980835 seconds.`

Whether or not using the recommended `stallSkip` setting of 0 for TV, the pause/unpause (or skip ahead) fails to break the stall and generates no further errors.

Note that the `useNativeHlsOnSafari:false` setting is recommended by Liberty Global for the platform, since it detects as Safari 9 but is actually WPE 2.22.1 but makes no difference here.

Different versions of Shaka and MUX.js made no difference. Larger values or `stallSkip` (or the other settings commented in the testcase, such as `rebufferingGoal` and `inaccurateManifestTolerance`) also appeared to make no difference.

If it's useful, the userAgent of this device type is:

`Mozilla/5.0 (Linux armv7l) AppleWebKit/602.1.28+ (KHTML, like Gecko) Version/9.1 Safari/601.5.17 WPE/2.22.1, VirginMedia_STB_/VIP5002W-mon-web-03.02-190-ai-AL-20240613151908-na001 (Arris_liberty,VIP5002W-PRD,Wireless) HZN/5.11 (MN=VIP5002W-PRD;PC=APLSTB;FV=VIP5002W-mon-web-03.02-190-ai-AL-20240613151908-na001;)`

**Comment by spikything** [comment]
Trying `ignoreManifestProgramDateTime:true` also didn't help

**Comment by avelad** [comment]
Your stream returns `{"message":"Invalid sessionId [9ff7ec6f-4576-401c-a3e0-4643c3f2b5d1]"}` Can you review it? Thanks!

**Comment by spikything** [comment]
@avelad the content in question appears to have been deleted. We'll find another stream and provide for you. @ubaidashraf the majority of previous catchup and been deleted and re-generated apparently. Let's find other examples.
