### ISSUE TITLE
IMA SDK, getCompanionAds for audio ads with images

### ISSUE THREAD

**Issue by vangn** [shaka-project/shaka-player#7163]
Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?
Yes

If the problem is related to FairPlay, have you read the tutorial?

Not related

What version of Shaka Player are you using?

Latest, 4.7.6

Can you reproduce the issue with our latest release version?
Yes

Can you reproduce the issue with the latest code from main?
Yes

Are you using the demo app or your own custom app?
No

If custom app, can you reproduce the issue using our demo app?
Yes

What browser and OS are you using?
Windows Chrome, Firefox, Opera

Hello everyone, I have a question about the Ads implementation with IMA SDK.

Is there any way to make use of the google.ima.CompanionAd interface? I ask this question because in my project, the Ads is varied in types of formats, ie. video ads and audio ads with images. As for video ads I have no problem, but when the ads is audio with images, only the audio is played and omits the image advertising.

Investigating in the Google documentation, it is possible to modify and show the images using the CompanionAd interface.

A sample code for this:

![image](https://github.com/user-attachments/assets/0abf3fe9-8d31-400a-b709-2ca3390761ea)

Is there any way to use that interface or in case of shaka player, is it possible to display images with audio?

I attach documentation from Google:

[](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.CompanionAd)

[](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/companions)

Thanks for your kind attention

Regards!

**Comment by avelad** [comment]
You can get the original IMA SDK ad event with this:

```
shakaAdManager.addEventListener('ad-started', (event) => {
  const adEvent = event.originalEvent;
  ...
});
```
