### ISSUE TITLE
Shaka player not working only on android emulator and android app

### ISSUE THREAD

**Issue by swarna9999** [shaka-project/shaka-player#7178]
Shaka player with mpd dash not working on android app but its working on android chrome browser.

The media player issue like that
resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
cleanDrmObj: mDrmObj=null mDrmSessionId=null

![image](https://github.com/user-attachments/assets/f3aa86fd-8c46-419c-b850-af1ade28ce94)

**Comment by avelad** [comment]
Here is an article that explains how to use DRM in a webview within an app: https://amokranechentir.hashnode.dev/android-play-drm-protected-content-inside-a-webview
