### ISSUE TITLE
Can the shaka player stream HLS media from a VAST file rather than the IMA SDK pass it to the native player?

### ISSUE THREAD

**Issue by geethu-rajasekharan** [shaka-project/shaka-player#7220]
**Test Build Versions**: I've tested on the demo Shaka player and our local version - V4.3.0.

**Tested Environments**:
Chrome on Windows
Firefox on Windows
Safari on Mac
Chrome on Mac
Chromium on Tizen
Chromium on WebOS

I went through the shaka player internal code relating to ads management. It looks like the shaka player has a wrapper around the IMA SDK, but the actual selection of media file and playback of ad is handled by the IMA SDK itself. 

**Question**: Can shaka player play an HLS stream ad from the VAST response. In my testing I have found that if there is only an HLS stream entry under MediaFiles, then Chrome on Windows is unable to play it, whereas environments like Safari on iOS and chromium on WebOS are able to play it. This could be because of 2 reasons:
1. The IMA SDK performs validation of whether the video element can directly play the stream or not. If this validation fails, playback is not attempted.
2. The playback is done directly by the video element. (I believe this is the case since I see on the demo shaka player that it is assigning the video element with src=<media_url_retrieved_from_vast_xml>) 
If the element cannot play it, we get the error from IMA SDK that the player does not have the capability to play linear assets.

We're basically trying to figure out if shaka player can take care of adaptive streaming of ads on all browsers.

**Comment by avelad** [comment]
Shaka on the main branch (the change is not in any release yet, but is scheduled for 4.11), supports VAST and VMAP playback without IMA intervention and uses by default DASH or HLS, the only limitation of this implementation is that there is no event tracking.

**Comment by geethu-rajasekharan** [comment]
Okay so you are confirming that dash or HLS playback would work only on environments that natively support them right? And this is because the Ad playback is handled by the native player and not shaka player in the current versions.

**Comment by avelad** [comment]
No, I'm saying that what IMA does is not up to us. But in 4.11 there will be a non-IMA mode that will support this. But the way the two modes work is different.

**Comment by geethu-rajasekharan** [comment]
So today, would the IMA select a MediaFile from VAST response and pass it on to the shaka player for ad playback?
In simpler words, the question is whether the shaka player would play the ad or the native player?

**Comment by avelad** [comment]
IMA always use the native player.

**Comment by geethu-rajasekharan** [comment]
Perfect! Thanks for clarifying. 👍
