### ISSUE TITLE
Get new strings translated by Google's internal translation system

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#7231]
While https://github.com/shaka-project/shaka-player/issues/3752 covers pushing manual changes from GitHub back into Google's internal translation system, we also need to submit new strings for translation that have been added to Shaka since the last round of translations, then pull the translations into GitHub.

Internal tracking in b/361830865

**Comment by joeyparrish** [comment]
Initial sync in https://github.com/shaka-project/shaka-player/pull/7261, still need to resolve conflicts between the two systems.

**Comment by joeyparrish** [comment]
Conflicts resolved.  Still need to pull in missing translations for zh-HK.

**Comment by joeyparrish** [comment]
SJN translations updated in https://github.com/shaka-project/shaka-player/pull/7324

**Comment by avelad** [comment]
@joeyparrish , now is it complete?

**Comment by joeyparrish** [comment]
Waiting on zh-HK translations.  The rest are done.

**Comment by joeyparrish** [comment]
It turns out that the zh-HK translations were temporarily blocked by an internal bug in the translation system, but someone worked around it and they should be available in a few days.

**Comment by joeyparrish** [comment]
I misread!  They are available now!
