### ISSUE TITLE
Seeking guidance & solutions for implementing chromecast-like dual-window offline playback with Shaka Player (facing DRM issues)

### ISSUE THREAD

**Issue by loicraux** [shaka-project/shaka-player#7253]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**
N/A

**What version of Shaka Player are you using?**
latest 4.11.0

**What browser and OS are you using?**
Chrome 122.0.6261.139 in VMP-signed Electron 29.1.6
(widevine CDM Version is 4.10.2710.0)

**Please ask your question**
I've written an offline video player based on Electron (VMP-signed, from CastLabs), shaka-player and shaka-player storage API for offline downloading and playback.

One of the features I need to implement in this application is the ability to play a video simultaneously in an additional separate window called a "mirror window", in addition to the main player window. The main window contains a player with all controls, seek bar, etc., while the additional "mirror" window displays only the video and subtitles, with no controls (apart from a button to switch to full screen).

This "mirror/projection" window is intended to be used for projecting the video on a second screen or projector, while the main window is used for controlling the playback. The goal is to have the video playing in both windows simultaneously, with the ability for the projectionist to control the playback from the main window, and no controls shown on the screen during the projection of the movie.

Here is a screenshot of the main (on the left) window & additional "projector/mirror" window (on the right) :
![Screenshot from 2024-09-04 10-41-57](https://github.com/user-attachments/assets/7a033524-5bd7-4fba-a564-7407e584f57c)

As you can see, it is very very similar to how Chromecasting works, where you can control the playback from your the "sender" device, while the video is playing on the "receiver" device.

Except that... Chromecasting a downloaded video is not supported by shaka-player :(
See https://github.com/shaka-project/shaka-player/blob/f78f09dbaa55ec77da6919f9570bbc303ab817a8/lib/offline/indexeddb/storage_mechanism.js#L397

So I thought of implementing this feature by creating two instances of shaka-player, one in the main window and one in the mirror window, and keeping them in sync using the Electron IPC (inter-process communication) mechanism. The main window sends events to the mirror window to control the playback (load, play, pause, seek, etc.), and the mirror window makes subsequent calls to the shaka-player API to perform the requested actions (loading a video, playing, pausing, seeking, etc.).

It works as a charm on Linux (where persistent licenses are indeed not supported), but I'm facing a problem on Windows and MacOS, where the mirror window is not able to play the downloaded video because of this error :

```
[RENDERER] [ERROR] [MirroredVideoPlayerImpl] A shaka player error occurred during playback:
Severity=CRITICAL(2) Category=DRM(6) Code=FAILED_TO_CREATE_SESSION(6005)
Data=["Failed to execute 'load' on 'MediaKeySession': Rejected with system code (70)"]
```

From Widevine developer documentation (https://developers.google.com/widevine/drm/feature/browser-error-codes?hl=en#70_-_ksessionalreadyinuse), system code 70 means `"kSessionAlreadyInUse"`, which is quite self-explanatory... : I cannot have two instances of shaka-player playing the same downloaded video at the same time.

And I guess there must be the same problem while chromecasting, where the video is indeed played on the Chromecast device, and the sender device --- showing a black screen but with all the controls --- is only sending commands to the receiver device...

I'd like to still benefit from shaka-player UI & Controls in the main "sender" window, so that I don't have to re-implement all the controls, seek bar, etc. in the main window. And have the mirror "receiver" window only displaying the video, with no controls...

So I'm looking for a way to implement this feature, and I'm open to any suggestions, ideas, or workarounds that could help me achieve this goal. Is there a way to implement something similar to chromecasting, but for offline downloaded videos ? Are there any internal shaka-player interfaces that could help me and that I could implement ?

Thank you very much in advance for your ideas & suggestions!

**Comment by avelad** [comment]
I have an idea, although it may not be the best, since since you store the videos, the idea would be to have two different keys for the video (for example one for SD and another for HD). Download both qualities and select one for the main window and another for the projection. To solve the audio problem (since there is only one key), the best thing to do is to disable the audio for one of the videos with disableAudio config.

Does this help?

**Comment by loicraux** [comment]
> I have an idea, although it may not be the best, since since you store the videos, the idea would be to have two different keys for the video (for example one for SD and another for HD). Download both qualities and select one for the main window and another for the projection. To solve the audio problem (since there is only one key), the best thing to do is to disable the audio for one of the videos with disableAudio config.
> 
> Does this help?

Thanks, that's an interesting idea.

But I finally implemented a kind of remote control that sends messages between Electron windows, for a result similar to Chromecasting.
