### ISSUE TITLE
How to get list of audio having the same "language"

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#7256]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**
4.10.6

**What browser and OS are you using?**
Window 11, Chrome 128.x

**Please ask your question**
My manifest have 4 audios, they have same property "lang" but they have different codec. We want to switch to the codec that is best suitable for browser. But currently, function player.getAudioLanguages() only return 1 audio, so we can not switch. 
Does shaka player support to detect multi audi codec have same "lang" ? or for each "lang", it always return 1 item only?
https://vips-livecdn.fptplay.net/MTA4NDUxNDB8dnR2MS1oZC1tYXVkaW8tc3RhZ2luZ3xmcHR8MTcyNTQ0NDA4OXwxMDAuOTEuMTI1LjEzNHw4NjE5Y2ZjZjRiODg2NTJhMjBhZWRlZGRkN2VmYjdkNA/channel/vtv1-hd-maudio-staging/master.mpd

**Comment by tykus160** [comment]
As name suggests, `getAudioLanguages()` returns only an array of languages possible to select. To get all unique audio tracks, you need to rely on `getVariantTracks()` method. Below I posted code that should help you to get all unique audio tracks based on this API:

```js
const getUniqueAudioTracks = () => {
  const allAudioTracks = player.getVariantTracks().filter((track) => track.audioId !== null);
  const asMap = new Map(allAudioTracks.map((track) => [track.audioId, track]));
  const uniqueTracks = Array.from(asMap.values());
  return uniqueTracks;
};
```

Shaka supports multi codec manifests, but to have an option to switch between different codecs, you may need to pass following value to the config:
```js
{
  streaming: {
    dontChooseCodecs: true
  }
}
```

**Comment by vanminhquangtri** [comment]
Thanks @tykus160 , let me explain again.
This is manifest:
https://vips-livecdn.fptplay.net/MTA4NDUxNDB8dnR2MS1oZC1tYXVkaW8tc3RhZ2luZ3xmcHR8MTcyNTUwNjQ2MXwxMDAuOTEuMTI1LjEzNHxhMTgyZDYzZmQ0YjVhOWRlOTllZjdiM2Q4M2Q0N2ZmZA/channel/vtv1-hd-maudio-staging/master.mpd
When you inspect this manifest you can see that, the lang=**vi** have 4 option with different codecs:
codecs="**mp4a.40.2**"
codecs="*ac-3**" (channel=2)
codecs="**ac-3**" (channel=6)
codecs="**ec-3**"

The function player.getVariantTracks() or option dontChooseCodecs seems can not detect all of these 4 audio options. While what I want is some way to switch between these options. I mean the language is still **vi**, but the codec is different.

I use yor function `getUniqueAudioTracks `but it also only return one option.

![image](https://github.com/user-attachments/assets/951df9d1-f361-4ddd-8ce2-d22718282c6c)

**Comment by vanminhquangtri** [comment]
@tykus160 in short words, we want to show a dropdown for user to choose the codec they want for the same language: for example:
- Vie (AAC)
- Vie (EC-3)
- Vie (AC-3)

**Comment by tykus160** [comment]
@vanminhquangtri Chrome does not support AC-3 for now. Can you recheck my suggestions on device that supports this codec?

**Comment by vanminhquangtri** [comment]
hello @tykus160 , my list is just an example. Before show the list of codec drop for user to choose, we will check if user browser support codec or not. So it will have the case that dropdown will have at least 2 option.

**Comment by vanminhquangtri** [comment]
@tykus160 for example in Safari, it support AAC, AC-3, EC-3, so our dropdown will have these options:
- Vie (AAC)
- Vie (EC-3)
- Vie (AC-3) - 2 Channel
- Vie (AC-3) - 6 Channel

**Comment by tykus160** [comment]
@vanminhquangtri links you've provided don't work for me due to invalid token, so I'm not able to debug your issue. Can you share proper URLs?

**Comment by vanminhquangtri** [comment]
@tykus160 I would like to resend manifest link:
**dash**: 
https://vips-livecdn.fptplay.net/MTA4NDUxNDB8dnR2MS1oZC1tYXVkaW8tc3RhZ2luZ3xmcHR8MTcyNTUzMDUwNnwxMDAuOTEuMTI1LjEzNHwxM2Q3ZjkyNTBmMDVmMDhmN2U4YjhmNDJjN2IyYzQwYw/channel/vtv1-hd-maudio-staging/master.mpd

**hls**: https://vips-livecdn.fptplay.net/MTA4NDUxNDB8dnR2MS1oZC1tYXVkaW8tc3RhZ2luZ3xmcHR8MTcyNTUzMDAzMnwyMS42NC44LjIxOXw0OGQ4ODg0YTkyNmMyOThiMzEyNWE4ZGJlNWFlMWE0Mw/channel/vtv1-hd-maudio-staging/master.m3u8

I also have just test your function suggested in safari, it return many items but all items have the same audioCodec value while infact the audio codec not the same:
![image](https://github.com/user-attachments/assets/79439aac-68ab-4c58-ad43-2506eeec8c68)

I also test function player.getVariantTracks and also, all item have same audioCodec as well:
![image](https://github.com/user-attachments/assets/0760f58a-33d3-492d-afd2-530b698da733)

**Comment by tykus160** [comment]
Both URLs give me `{"error": "INVALID_TOKEN"}`

**Comment by avelad** [comment]
Same for me, Are the URLs geolocated?

**Comment by vanminhquangtri** [comment]
@tykus160  @avelad I add link the demo, can you please check this
https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;assetBase64=eyJuYW1lIjoiREFTSCBBVURJTyBDT0RFQyIsInNob3J0TmFtZSI6IiIsImljb25VcmkiOiIiLCJtYW5pZmVzdFVyaSI6Imh0dHBzOi8vdmlwcy1saXZlY2RuLmZwdHBsYXkubmV0L01UQTRORFV4TkRCOGRuUjJNUzFvWkMxdFlYVmthVzh0YzNSaFoybHVaM3htY0hSOE1UY3lOVFV6TURVd05ud3hNREF1T1RFdU1USTFMakV6Tkh3eE0yUTNaamt5TlRCbU1EVm1NRGhtTjJVNFlqaG1OREpqTjJJeVl6UXdZdy9jaGFubmVsL3Z0djEtaGQtbWF1ZGlvLXN0YWdpbmcvbWFzdGVyLm1wZCIsInNvdXJjZSI6IkN1c3RvbSIsImZvY3VzIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJleHRyYVRleHQiOltdLCJleHRyYVRodW1ibmFpbCI6W10sImV4dHJhQ2hhcHRlciI6W10sImNlcnRpZmljYXRlVXJpIjpudWxsLCJkZXNjcmlwdGlvbiI6bnVsbCwiaXNGZWF0dXJlZCI6ZmFsc2UsImRybSI6WyJObyBEUk0gcHJvdGVjdGlvbiJdLCJmZWF0dXJlcyI6WyJWT0QiXSwibGljZW5zZVNlcnZlcnMiOnsiX190eXBlX18iOiJtYXAifSwibGljZW5zZVJlcXVlc3RIZWFkZXJzIjp7Il9fdHlwZV9fIjoibWFwIn0sInJlcXVlc3RGaWx0ZXIiOm51bGwsInJlc3BvbnNlRmlsdGVyIjpudWxsLCJjbGVhcktleXMiOnsiX190eXBlX18iOiJtYXAifSwiZXh0cmFDb25maWciOnsic3RyZWFtaW5nIjp7InJldHJ5UGFyYW1ldGVycyI6eyJ0aW1lb3V0IjozMDAwLCJtYXhBdHRlbXB0cyI6MSwiYmFzZURlbGF5IjozMDAwLCJiYWNrb2ZmRmFjdG9yIjoyLCJmdXp6RmFjdG9yIjowLjV9fX0sImV4dHJhVWlDb25maWciOm51bGwsImFkVGFnVXJpIjpudWxsLCJpbWFWaWRlb0lkIjpudWxsLCJpbWFBc3NldEtleSI6bnVsbCwiaW1hQ29udGVudFNyY0lkIjpudWxsLCJpbWFNYW5pZmVzdFR5cGUiOm51bGwsIm1lZGlhVGFpbG9yVXJsIjpudWxsLCJtZWRpYVRhaWxvckFkc1BhcmFtcyI6bnVsbCwidXNlSU1BIjp0cnVlLCJtaW1lVHlwZSI6bnVsbH0=;panel=CUSTOM%20CONTENT;build=uncompiled

In case still not able to access, please check the attached is the manifest content:
[dash.txt](https://github.com/user-attachments/files/16887873/dash.txt)
[hls.txt](https://github.com/user-attachments/files/16887874/hls.txt)

Thank you so much for spending your time

**Comment by avelad** [comment]
Please use the next config:

```
{
  streaming: {
    dontChooseCodecs: true
  }
}
```

With this config we will not choose codecs and we will show you all the codecs that work on your platform.
