### ISSUE TITLE
Safari on iOS: HLS livestream with MPEG-TS segments does not play

### ISSUE THREAD

**Issue by mthie** [shaka-project/shaka-player#7263]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

tested on 4.7.3, 4.10.x, and 4.11.0

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `main`?**

Yes

**Are you using the demo app or your own custom app?**

Both.

**If custom app, can you reproduce the issue using our demo app?**

Yes

**What browser and OS are you using?**

Latest Safari 17.5 on iOS 17.6.1 (iPhone 14 Pro)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A

**What are the manifest and license server URIs?**

https://rtc.mthie.dev/index.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Doesn't matter, doesn't even work with no-settings on the demo page.

**What did you do?**

Use Manifest URI and try to play it with Shaka player.

Livestream is created with ffmpeg:

```
ffmpeg -threads 2 -re -fflags +genpts -stream_loop -1 -i ../big_buck_bunny_1080p_h264.mov -vsync 2 -filter_complex "[0:v]scale=w=1920:h=1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,format=pix_fmts=yuv420p,setsar=sar=1/1,split=6[v0][v1][v2][v3][v4][v5];[v1]scale=w=1280:h=720[v1];[v2]scale=w=854:h=480[v2];[v3]scale=w=640:h=360[v3];[v4]scale=w=428:h=240[v4];[v5]scale=w=256:h=144[v5];[0:a]aformat=sample_rates=48000:channel_layouts=stereo,asplit=6[a0][a1][a2][a3][a4][a5]" -map "[v0]" -profile:v:0 high -level:v:0 5.0 -tune:v:0 film -preset:v:0 superfast -c:v:0 libx264 -b:v:0 5000000 -minrate:v:0 5000000 -maxrate:v:0 5000000 -bufsize:v:0 10000000 -x264-params:v:0 nal-hrd=cbr -g:v:0 30 -keyint_min:v:0 30 -bf:v:0 2 -map "[a0]" -ar:a:0 48000 -c:a:0 aac -b:a:0 256000 -map "[v1]" -profile:v:1 high -level:v:1 5.0 -tune:v:1 film -preset:v:1 superfast -c:v:1 libx264 -b:v:1 4500000 -minrate:v:1 4500000 -maxrate:v:1 4500000 -bufsize:v:1 9000000 -x264-params:v:1 nal-hrd=cbr -g:v:1 30 -keyint_min:v:1 30 -bf:v:1 2 -map "[a1]" -ar:a:1 48000 -c:a:1 aac -b:a:1 256000 -map "[v2]" -profile:v:2 high -level:v:2 5.0 -tune:v:2 film -preset:v:2 superfast -c:v:2 libx264 -b:v:2 3500000 -minrate:v:2 3500000 -maxrate:v:2 3500000 -bufsize:v:2 7000000 -x264-params:v:2 nal-hrd=cbr -g:v:2 30 -keyint_min:v:2 30 -bf:v:2 2 -map "[a2]" -ar:a:2 48000 -c:a:2 aac -b:a:2 160000 -map "[v3]" -profile:v:3 high -level:v:3 5.0 -tune:v:3 film -preset:v:3 superfast -c:v:3 libx264 -b:v:3 2000000 -minrate:v:3 2000000 -maxrate:v:3 2000000 -bufsize:v:3 4000000 -x264-params:v:3 nal-hrd=cbr -g:v:3 30 -keyint_min:v:3 30 -bf:v:3 2 -map "[a3]" -ar:a:3 48000 -c:a:3 aac -b:a:3 160000 -map "[v4]" -profile:v:4 high -level:v:4 5.0 -tune:v:4 film -preset:v:4 superfast -c:v:4 libx264 -b:v:4 1500000 -minrate:v:4 1500000 -maxrate:v:4 1500000 -bufsize:v:4 3000000 -x264-params:v:4 nal-hrd=cbr -g:v:4 30 -keyint_min:v:4 30 -bf:v:4 2 -map "[a4]" -ar:a:4 48000 -c:a:4 aac -b:a:4 128000 -map "[v5]" -profile:v:5 high -level:v:5 5.0 -tune:v:5 film -preset:v:5 superfast -c:v:5 libx264 -b:v:5 1000000 -minrate:v:5 1000000 -maxrate:v:5 1000000 -bufsize:v:5 2000000 -x264-params:v:5 nal-hrd=cbr -g:v:5 30 -keyint_min:v:5 30 -bf:v:5 2 -map "[a5]" -ar:a:5 48000 -c:a:5 aac -b:a:5 128000 -f hls -hls_time 6 -hls_flags "independent_segments+program_date_time+append_list" -hls_segment_type mpegts -hls_segment_filename "%v/%02d.ts" -master_pl_name index.m3u8 -var_stream_map "v:0,a:0,name:hd1080 v:1,a:1,name:hd720 v:2,a:2,name:normal v:3,a:3,name:low v:4,a:4,name:small v:5,a:5,name:preview" "%v/index.m3u8"
```

**What did you expect to happen?**

Seeing a live stream.

**What actually happened?**

The player does not play.

Interesting facts:
- it works,  when `-hls_segment_type fmp4` instead of `-hls_segment_type mpegts` is set, but it's no option for us
- the same manifest works with HLS.js on the same device
- generating a VOD with the same HLS options works fine
- since I don't own an iPhone nor a Mac to access a developer console, I can't send more debug information
- it works fine on all the other devices (Windows, Linux, Android)

**Are you planning send a PR to fix it?**

No.

**Comment by mthie** [comment]
@avelad Sorry, ran out of disk space. Just restarted the stream on the test server.

**Comment by avelad** [comment]
I have reproduced the problem, it is a webkit issue, but it has been fixed, but I don't know when it will be released! (https://github.com/WebKit/WebKit/pull/32938)
