### ISSUE TITLE
Can Safari on MacOS play H.265 DRM VOD stream?

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#7300]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Yes, but not find the information I need

**What version of Shaka Player are you using?**
4.10.6

**What browser and OS are you using?**
Safari 17.6 on macOS Monterey

**Please ask your question**
Everytime player load VOD stream DRM H.265, it throws error 3016. Do we need any other configuration or Safari MacOS does not support DRM H.265.

Manifest link: 
https://vod06-cdn.fptplay.net/POVOD/encoded/2024/08/29/SolLevante_netflix_h265_drm_v2/hls_drm/master.m3u8

Attached is the manifest content.
[h265.txt](https://github.com/user-attachments/files/16987318/h265.txt)

Thank you

**Comment by avelad** [comment]
Are you using src= or MSE?

**Comment by vanminhquangtri** [comment]
Hello @avelad we use MSE

**Comment by avelad** [comment]
In my case I have always used src= for HEVC (due to my DRM provider). I leave the question open in case someone in the community knows how to answer it.

**Comment by vanminhquangtri** [comment]
@avelad can you please provide the sample code of used src= for HEVC, I believe this can help me. Currently my player always return error 3015. I use player.load() to player HEVC like other codecs.

**Comment by avelad** [comment]
With `useNativeHlsForFairPlay` = true you will use src=
With `useNativeHlsForFairPlay` = false you will use MSE

**Comment by vanminhquangtri** [comment]
ak if so, yes, I am using src= like you. because my useNativeHlsForFairPlay is true

**Comment by avelad** [comment]
Since you use src=, only the Apple player is involved except to request the content license. In my case, HEVC works, I use fmp4 and there are also other qualities with AVC.

I don't know how to help you much more, I recommend that you open an issue at https://bugs.webkit.org/ so they can help you better. Sorry!

**Comment by vanminhquangtri** [comment]
Hello @avelad , on my Safari we can play H.265 but it is non-DRM. As I check on Apple they say Fairplay only support H.264.
So can you please let me know your HEVC is non-DRM or DRM? 

https://developer.apple.com/streaming/fps/FairPlayStreamingOverview.pdf

**Comment by joeyparrish** [comment]
@vanminhquangtri, a quick Google search turned up this quote from https://developer.apple.com/forums/thread/94080?answerId=316209022#316209022 :

> Advances in HTTP Live Streaming
> 
> https://developer.apple.com/videos/play/wwdc2017/504/
> 
> HEVC is supported in hardware on A9 or better devices, and falls back to software on earlier hardware with iOS 11.

**Comment by joeyparrish** [comment]
Your PDF is copyright 2016, and the WWDC presentation that talks about HEVC support is from 2017.

**Comment by vanminhquangtri** [comment]
Thank @joeyparrish
