### ISSUE TITLE
About the cause of playback errors in Windows 10

### ISSUE THREAD

**Issue by ogawa-ma** [shaka-project/shaka-player#7327]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
3.0.6

**What browser and OS are you using?**
Electron Windows10

**Please ask your question**
Please forgive the machine translation.
When some users try to stream and play videos protected by Widevine DRM, the following error occurs and the video cannot be played.
The error occurs before a license is issued.
```
player.load error: shaka.util.Error {
    "severity": 2,
    "category": 6,
    "code": 6002,
    "data": [
        "Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': CreateCdmFunc not available."
    ],
    "handled": false
}
```

I [looked](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html) at the list of errors, but I couldn't find the specific cause.
What exactly causes this error?

**Comment by joeyparrish** [comment]
This looks like something specific to both Chrome and Windows.  I'm not familiar with the implementation, but I believe there's a Windows-specific CDM in Chrome.

@xhwang-chromium, can you help out here?  What would cause this error?  How can it be resolved?

**Comment by xhwang-chromium** [comment]
We are not seeing this error in Chrome. Which version of Chromium is this based on? Any difference in how it's using the CDM?

**Comment by ogawa-ma** [comment]
> We are not seeing this error in Chrome. Which version of Chromium is this based on?

We are using [downstream_electron v0.4.0](https://github.com/castlabs/downstream_electron/tree/v0.4.0).
If you check the package.json, the electron version is v6.0.0, so the Chromium version is probably M76.
https://www.electronjs.org/ja/docs/latest/tutorial/electron-timelines


> Any difference in how it's using the CDM?

I don't think there is any difference.
This page was used as a reference when implementing it.
- https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html
- https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html

### Excerpt of code
```
// HTML
<video id="video" ref="video" data-shaka-player :poster="content.image_url.package" style="width: 100%; height: 100%;">
</video>

// Vue JS
created() {
    require('shaka-player/dist/controls.css')
    this.shakaUi = require('shaka-player/dist/shaka-player.ui')
    document.addEventListener('shaka-ui-loaded', this.initApp)
},
methods: {
    initApp: async function() {
        this.video = this.$refs.video
        const ui = this.video['ui']
        const controls = ui.getControls()
        this.player = controls.getPlayer()
    },
    playVideo(manifestUrl, customData, currentTime) {
        const licenseServerUrl = 'https://◯◯◯.com/?custom_data=' + customData
        this.player.configure({
            drm: {
                servers: {
                    'com.widevine.alpha': licenseServerUrl
                }
            }
        })
        this.manifestUrl = manifestUrl // mpd file url
        this.player.load(manifestUrl).then(() => {
            this.video.play()
        }).catch((error) => {
            onPlayerError('player.load error: ' + error)
        })
    },
}
```

**Comment by tykus160** [comment]
@ogawa-ma DOWNstream Electron version you're using is outdated, can you try the most recent one?
@mackode do you have any other suggestions?

**Comment by ogawa-ma** [comment]
Please allow some time for a response.
