### ISSUE TITLE
Aborting In-Progress Video Segment Downloads

### ISSUE THREAD

**Issue by aadharjain1** [shaka-project/shaka-player#7337]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Not related

**What version of Shaka Player are you using?**
4.11.0

**What browser and OS are you using?**
Android Webview & Chrome

**Please ask your question**
I have an infinite video feed (m3u8 videos) and I start loading a video once it comes into focus. If user scrolls through videos really fast, then 1st video segment of all the videos start downloading parallely and choke the network bandwidth, resulting in delay in playing current focused video. As a possible solution, I would like to know if there's a way to abort the download of in progress video segments, if user moves to next video. As of now, I'm able to stop download of any new segments, but couldn't cancel the ones which are already being downloaded.

**Comment by theodab** [comment]
Are you referring to the preload API? A preload manager should abort downloads when you call `destroy` on it, if it hasn't been loaded by a player yet. If it's not doing so, that's a bug.

**Comment by aadharjain1** [comment]
Hi @theodab, question is actually valid for both `load` and `preload` APIs. Calling `destroy` on preload manager currently is making fully downloaded segments unusable for future.

**Scenario (Given Segment Size ~ 500kb)**
User is watching Video 1 (2 segments are completely downloaded and 3rd is in progress)
User moves to Video 2 (1st segment starts downloading)

I'm looking for a way to be able to cancel download for Video 1 - Segment 3, so that user's bandwidth can be dedicated in loading Video 2. But in case user comes back to Video 1, we should be able to play already downloaded segments of Video 1 instantly.

**Comment by joeyparrish** [comment]
You can:

 1. pause() the video - the player will stop fetching when it reaches the buffering goal
 2. unload() the player - the player will stop immediately, and you have to call load() again to resume the content

Does this help?
