### ISSUE TITLE
Preload 1st segment and store for offline playback

### ISSUE THREAD

**Issue by aadharjain1** [shaka-project/shaka-player#7338]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Not related

**What version of Shaka Player are you using?**
4.11.0

**What browser and OS are you using?**
Android Webview & Chrome

**Please ask your question**
I have an infinite video feed (m3u8 videos) and I start loading a video once it comes into focus. But I would like to know if there's a way to preload just the 1st segment of the next video and store it in IndexedDB for offline playback. Once user comes on this video, then it should start download from 2nd segment onwards.

I tried to achieve this by using shaka.offline.Storage class, but it was downloading the entire video. So, I made some changes in the shaka player code and was able to download only 1st segment. But is there a way to load the video from 2nd segment onwards using player.load()?

**Comment by avelad** [comment]
What you are looking for is the preload API https://shaka-player-demo.appspot.com/docs/api/tutorial-preload.html :)

**Comment by aadharjain1** [comment]
But can we store this segment as well in IndexedDB for offline playback using preload API? Basically what I'm looking for is like a combination of both preload and offline APIs.

**Comment by avelad** [comment]
Right now that's not possible and no one on the maintenance team will be working on this in the future. Sorry...
