### ISSUE TITLE
Need safer playback for hls content in safari with buffer issue in content

### ISSUE THREAD

**Issue by akash-kush9** [shaka-project/shaka-player#7371]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Yes

**What version of Shaka Player are you using?**
4.7.13

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Safari on MacOS Sonoma 14.6.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
https://vod-jitp.narmada.ivpdth.in/hls-ts/vodc/Beans/default.m3u8.

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**
Have same issue on shaka player provided on https://shaka-player-demo.appspot.com.

**What did you do?**
Pass the url to playback, and let it play.

**What did you expect to happen?**
On safari have a complete playback (same as chrome) instead of stopping in between, Or a extremely well explanation why this is not a client issue & cannot be fix.

**What actually happened?**
There is this one asset we have which was having issue in safari during playback. On investigation we saw that the error is related to buffering, "**Possible encoding problem detected! Unexpected buffered range for reference , ... ,should be {start: 12.012, end: 14.014} but got {start: 12.045366, end: 14.013999}, same with other fragments too**". While chrome shows the same error it is able to have a playback but safari is only able to have few seconds of playback and then fails completely. On shaka player demo the content ends up with buffer for the same point where my apps playback stops too.

**Are you planning send a PR to fix it?**
Nope

**Comment by akash-kush9** [comment]
Hi @joeyparrish , any suggestion/comment will be helpful.

**Comment by joeyparrish** [comment]
Are you setting the config `streaming.useNativeHlsOnSafari`?  Alternately, what is `videoElement.src` in your app on Safari?

Can you try setting `streaming.useNativeHlsOnSafari` explicitly to `false`?
