### ISSUE TITLE
Closed Captions stopped working after commit on 07/11/2024

### ISSUE THREAD

**Issue by ambihuru** [shaka-project/shaka-player#7386]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

It is related to TextTracks / Closed Captions

**What version of Shaka Player are you using?**

4.11.6

**Can you reproduce the issue with our latest release version?**
Yes
But code working fine on code checked in until 7/11/2024 2:28AM CST

**Can you reproduce the issue with the latest code from `main`?**
NA

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
I do not have supported streams

**What browser and OS are you using?**
Blink based browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

**What did you do?**

Closed captions are embedded into the our video stream
When enabled closed captions using API 
Middleware.Ipplayer.instance.setTextTrackVisibility('true');
Middleware.Ipplayer.instance.selectTextLanguage('en');

closed captions are parsed by Shaka and I was able to see CC until the code dated
87bf738e Álvaro Velad Galván <ladvan91@hotmail.com> on 7/11/2024 at 2:28 AM

Below commit broke the CC rendering.
11a2cc5d Álvaro Velad Galván <ladvan91@hotmail.com> on 7/12/2024 at 1:46 AM

**What did you expect to happen?**

**What actually happened?**

**Are you planning send a PR to fix it?**

**Comment by ambihuru** [comment]
@avelad Can you please check this

**Comment by tykus160** [comment]
@ambihuru what's the behavior now? Captions are not displayed, rendered unproperly, or maybe player throws some error?
Can you share a test stream for validation?

**Comment by ambihuru** [comment]
@tykus160 Before the checkin I have mentioned CC was extracted and rendered perfectly from the video stream.

But after the mentioned commit, CC extraction itself is not succesful.
When used the API shaka.Player.getTextTracks() does not return any value.

**Comment by tykus160** [comment]
@ambihuru Please share a manifest, either here or to shaka-player-maintainers@googlegroups.com
