### ISSUE TITLE
ShakaPlayer minimalist code?

### ISSUE THREAD

**Issue by hijuuijj** [shaka-project/shaka-player#7390]
Where can I find minimalist code for ShakaPlayer? I need a solution that can play videos and supports basic keyboard controls, while also being as lightweight as possible.

Thanks in advance.

**Comment by joeyparrish** [comment]
> Where can I find minimalist code for ShakaPlayer? I need a solution that can play videos and supports basic keyboard controls, while also being as lightweight as possible.

If you mean a minimal library, you can get the compiled, optimized, and minified version of our latest release here:

 - https://ajax.googleapis.com/ajax/libs/shaka-player/4.11.7/shaka-player.compiled.js

You can always find the latest releases hosted on Google's CDN here:

 - https://developers.google.com/speed/libraries#shaka-player

You can also build and/or host them yourself.

-----

If you mean a minimal app demonstrating playback, see our tutorial here:

 - https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html

-----

Does this help?
