### ISSUE TITLE
Mouse cursor only hidden when placed at the center of the video player

### ISSUE THREAD

**Issue by FiberOnePL** [shaka-project/shaka-player#7394]
When playing a video, the cursor remains visible when being placed on the left or the right side of the video player, it is hidden when being place in the center of the video player. These positions seem to be related to the div.shake-rewind-container and div.shaka-fast-forward-container seen in the (edited) screenshot (the green area is the one where the cursor is hidden).
![337990817-874fa1af-40d9-4b98-ab6a-48948e506a1f](https://github.com/user-attachments/assets/aacbda46-8a38-4c63-8c71-82e6eb7e000b)

**Comment by OothecaPickle** [comment]
If the play button is shown, the cursor will not be hidden with the rest of the UI no matter where it is on the screen.

**Comment by FiberOnePL** [comment]
@joeyparrish 

After commenting out the cursor tracking everything works fine. So you're right.

**Comment by OothecaPickle** [comment]
@FiberOnePL what lines did you comment out?

**Comment by joeyparrish** [comment]
Would you please consider sending a PR?

**Comment by OothecaPickle** [comment]
The cursor is also not hidden along with the rest of the UI if it's placed on other elements such as the center play button, if enabled, or the progress bar area.

**Comment by OothecaPickle** [comment]
When the cursor is placed over the big play button, the DevTools debugger does break if the breakpoint is set to [the line](https://github.com/shaka-project/shaka-player/blob/1749315d33b099c7f061b5ffbed543a0460f974a/ui/controls.js#L1519) that sets the cursor style to 'none' , but the cursor does not disappear.

**Comment by avelad** [comment]
> @joeyparrish
> 
> After commenting out the cursor tracking everything works fine. So you're right.

Can you create a PR with your change? Thanks!

**Comment by FiberOnePL** [comment]
@joeyparrish @avelad 

I hid the elements that overlap in css, this is only a temporary solution but not a permanent solution.

**Comment by OothecaPickle** [comment]
@avelad #7458 doesn't resolve the issue, the cursor is still not hidden if it's placed over other UI elements such as the center play button or the video controls.

**Comment by joeyparrish** [comment]
Recursively changing the cursor feels hacky.  Shouldn't elements below the container inherit the cursor style instead?

**Comment by OothecaPickle** [comment]
> Recursively changing the cursor feels hacky. Shouldn't elements below the container inherit the cursor style instead?

cursor styles with more specificity (that take precedence) are defined in CSS for many of those elements
<img width="214" alt="cursor-styles" src="https://github.com/user-attachments/assets/b25f019d-d56d-4dc5-aa2e-36c1504abe60">

**Comment by OothecaPickle** [comment]
in the case of the big play button, the user agent stylesheet overrides its cursor style
<img width="1226" alt="bigplaybutton-cursor" src="https://github.com/user-attachments/assets/e7ca1f01-8480-4ec0-bf45-a7bde58a9418">

**Comment by joeyparrish** [comment]
Hrm... then maybe we should adjust those as well.  Maybe some of them are not needed?
