### ISSUE TITLE
Audio switch is not working on Safari

### ISSUE THREAD

**Issue by vanminhquangtri** [shaka-project/shaka-player#7396]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Yes

**What version of Shaka Player are you using?**

4.11.2
https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.11.2/shaka-player.ui.min.js

**Can you reproduce the issue with our latest release version?**
[Link ](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;assetBase64=eyJuYW1lIjoiREFTSCBPTiBTQUZBUkkiLCJzaG9ydE5hbWUiOiIiLCJpY29uVXJpIjoiIiwibWFuaWZlc3RVcmkiOiJodHRwczovL3ZpcHMtbGl2ZWNkbi5mcHRwbGF5Lm5ldC9NVEE0TkRVeE5EQjhkblIyTVMxb1pDMXRZWFZrYVc4dGMzUmhaMmx1WjN4bWNIUjhNVGN5T0RBeE16VXhOM3d4TURBdU9URXVNVEkxTGpFNU1Yd3hZekZpWkRVell6SmtNell5TURabU9USTNPREkxTURoaU1ETmxZbUZpTkEvY2hhbm5lbC92dHYxLWhkLW1hdWRpby1zdGFnaW5nL21hc3Rlci5tcGQiLCJzb3VyY2UiOiJDdXN0b20iLCJmb2N1cyI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwiZXh0cmFUZXh0IjpbXSwiZXh0cmFUaHVtYm5haWwiOltdLCJleHRyYUNoYXB0ZXIiOltdLCJjZXJ0aWZpY2F0ZVVyaSI6bnVsbCwiZGVzY3JpcHRpb24iOm51bGwsImlzRmVhdHVyZWQiOmZhbHNlLCJkcm0iOlsiTm8gRFJNIHByb3RlY3Rpb24iXSwiZmVhdHVyZXMiOlsiVk9EIl0sImxpY2Vuc2VTZXJ2ZXJzIjp7Il9fdHlwZV9fIjoibWFwIn0sImxpY2Vuc2VSZXF1ZXN0SGVhZGVycyI6eyJfX3R5cGVfXyI6Im1hcCJ9LCJyZXF1ZXN0RmlsdGVyIjpudWxsLCJyZXNwb25zZUZpbHRlciI6bnVsbCwiY2xlYXJLZXlzIjp7Il9fdHlwZV9fIjoibWFwIn0sImV4dHJhQ29uZmlnIjpudWxsLCJleHRyYVVpQ29uZmlnIjpudWxsLCJhZFRhZ1VyaSI6bnVsbCwiaW1hVmlkZW9JZCI6bnVsbCwiaW1hQXNzZXRLZXkiOm51bGwsImltYUNvbnRlbnRTcmNJZCI6bnVsbCwiaW1hTWFuaWZlc3RUeXBlIjpudWxsLCJtZWRpYVRhaWxvclVybCI6bnVsbCwibWVkaWFUYWlsb3JBZHNQYXJhbXMiOm51bGwsInVzZUlNQSI6dHJ1ZSwibWltZVR5cGUiOm51bGx9;panel=CUSTOM%20CONTENT;build=uncompiled)

**Can you reproduce the issue with the latest code from `main`?**
[Link ](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;assetBase64=eyJuYW1lIjoiREFTSCBPTiBTQUZBUkkiLCJzaG9ydE5hbWUiOiIiLCJpY29uVXJpIjoiIiwibWFuaWZlc3RVcmkiOiJodHRwczovL3ZpcHMtbGl2ZWNkbi5mcHRwbGF5Lm5ldC9NVEE0TkRVeE5EQjhkblIyTVMxb1pDMXRZWFZrYVc4dGMzUmhaMmx1WjN4bWNIUjhNVGN5T0RBeE16VXhOM3d4TURBdU9URXVNVEkxTGpFNU1Yd3hZekZpWkRVell6SmtNell5TURabU9USTNPREkxTURoaU1ETmxZbUZpTkEvY2hhbm5lbC92dHYxLWhkLW1hdWRpby1zdGFnaW5nL21hc3Rlci5tcGQiLCJzb3VyY2UiOiJDdXN0b20iLCJmb2N1cyI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwiZXh0cmFUZXh0IjpbXSwiZXh0cmFUaHVtYm5haWwiOltdLCJleHRyYUNoYXB0ZXIiOltdLCJjZXJ0aWZpY2F0ZVVyaSI6bnVsbCwiZGVzY3JpcHRpb24iOm51bGwsImlzRmVhdHVyZWQiOmZhbHNlLCJkcm0iOlsiTm8gRFJNIHByb3RlY3Rpb24iXSwiZmVhdHVyZXMiOlsiVk9EIl0sImxpY2Vuc2VTZXJ2ZXJzIjp7Il9fdHlwZV9fIjoibWFwIn0sImxpY2Vuc2VSZXF1ZXN0SGVhZGVycyI6eyJfX3R5cGVfXyI6Im1hcCJ9LCJyZXF1ZXN0RmlsdGVyIjpudWxsLCJyZXNwb25zZUZpbHRlciI6bnVsbCwiY2xlYXJLZXlzIjp7Il9fdHlwZV9fIjoibWFwIn0sImV4dHJhQ29uZmlnIjpudWxsLCJleHRyYVVpQ29uZmlnIjpudWxsLCJhZFRhZ1VyaSI6bnVsbCwiaW1hVmlkZW9JZCI6bnVsbCwiaW1hQXNzZXRLZXkiOm51bGwsImltYUNvbnRlbnRTcmNJZCI6bnVsbCwiaW1hTWFuaWZlc3RUeXBlIjpudWxsLCJtZWRpYVRhaWxvclVybCI6bnVsbCwibWVkaWFUYWlsb3JBZHNQYXJhbXMiOm51bGwsInVzZUlNQSI6dHJ1ZSwibWltZVR5cGUiOm51bGx9;panel=CUSTOM%20CONTENT;build=uncompiled)

**Are you using the demo app or your own custom app?**
Both
- Demo: [Link ](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;assetBase64=eyJuYW1lIjoiREFTSCBPTiBTQUZBUkkiLCJzaG9ydE5hbWUiOiIiLCJpY29uVXJpIjoiIiwibWFuaWZlc3RVcmkiOiJodHRwczovL3ZpcHMtbGl2ZWNkbi5mcHRwbGF5Lm5ldC9NVEE0TkRVeE5EQjhkblIyTVMxb1pDMXRZWFZrYVc4dGMzUmhaMmx1WjN4bWNIUjhNVGN5T0RBeE16VXhOM3d4TURBdU9URXVNVEkxTGpFNU1Yd3hZekZpWkRVell6SmtNell5TURabU9USTNPREkxTURoaU1ETmxZbUZpTkEvY2hhbm5lbC92dHYxLWhkLW1hdWRpby1zdGFnaW5nL21hc3Rlci5tcGQiLCJzb3VyY2UiOiJDdXN0b20iLCJmb2N1cyI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwiZXh0cmFUZXh0IjpbXSwiZXh0cmFUaHVtYm5haWwiOltdLCJleHRyYUNoYXB0ZXIiOltdLCJjZXJ0aWZpY2F0ZVVyaSI6bnVsbCwiZGVzY3JpcHRpb24iOm51bGwsImlzRmVhdHVyZWQiOmZhbHNlLCJkcm0iOlsiTm8gRFJNIHByb3RlY3Rpb24iXSwiZmVhdHVyZXMiOlsiVk9EIl0sImxpY2Vuc2VTZXJ2ZXJzIjp7Il9fdHlwZV9fIjoibWFwIn0sImxpY2Vuc2VSZXF1ZXN0SGVhZGVycyI6eyJfX3R5cGVfXyI6Im1hcCJ9LCJyZXF1ZXN0RmlsdGVyIjpudWxsLCJyZXNwb25zZUZpbHRlciI6bnVsbCwiY2xlYXJLZXlzIjp7Il9fdHlwZV9fIjoibWFwIn0sImV4dHJhQ29uZmlnIjpudWxsLCJleHRyYVVpQ29uZmlnIjpudWxsLCJhZFRhZ1VyaSI6bnVsbCwiaW1hVmlkZW9JZCI6bnVsbCwiaW1hQXNzZXRLZXkiOm51bGwsImltYUNvbnRlbnRTcmNJZCI6bnVsbCwiaW1hTWFuaWZlc3RUeXBlIjpudWxsLCJtZWRpYVRhaWxvclVybCI6bnVsbCwibWVkaWFUYWlsb3JBZHNQYXJhbXMiOm51bGwsInVzZUlNQSI6dHJ1ZSwibWltZVR5cGUiOm51bGx9;panel=CUSTOM%20CONTENT;build=uncompiled)
- Custom: https://codesandbox.io/p/sandbox/9p35qt?file=%2Findex.html%3A11%2C18-11%2C99

**If custom app, can you reproduce the issue using our demo app?**
https://codesandbox.io/p/sandbox/9p35qt?file=%2Findex.html%3A11%2C18-11%2C99

**What browser and OS are you using?**
Safari 17.6 on macOS Monterey 12.7.6, Safari Iphone 12 Promax, Macbook Pro M1
So I think all Safari will have same issue.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
We not use embedded device.

**What are the manifest and license server URIs?**

This is non-DRM stream
https://vips-livecdn.fptplay.net/MTA4NDUxNDB8dnR2MS1oZC1tYXVkaW8tc3RhZ2luZ3xmcHR8MTcyODAxMzUxN3wxMDAuOTEuMTI1LjE5MXwxYzFiZDUzYzJkMzYyMDZmOTI3ODI1MDhiMDNlYmFiNA/channel/vtv1-hd-maudio-staging/master.mpd

Attached is manifest content in case you can not access the link
[codecs.txt](https://github.com/user-attachments/files/17253451/codecs.txt)

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

Default configuration of shaka.

**What did you do?**

Init player as normal. My stream have 4 audio options, all have same language but different codecs: AAC, AC3, AC351, EAC3. All are supported by Safari.

Please check the demo link.
Click on setting of control bar (3 dots at the right).

**What did you expect to happen?**
Show audio selection for user to choose codec.
Example from videojs: https://3cvkd4.csb.app/

**What actually happened?**

There's no audio selection

ONE THING I NOTED is that, the control show a selection for language with 4 options. When you click at any option, it seems shaka does nothing at all.
I think this is a confuse from shaka because all 4 audios have same language (in this case is Vietnamese). So should be NO selection for language. It should be codecs audio selection instead.

**Are you planning send a PR to fix it?**
Yes I will try If I can

**Comment by vanminhquangtri** [comment]
hello @joeyparrish can you please take a look on this, thank you

**Comment by avelad** [comment]
@tykus160 Can you review it? You added the codec in the UI in https://github.com/shaka-project/shaka-player/pull/6723

**Comment by tykus160** [comment]
@vanminhquangtri Can you try setting `streaming.dontChooseCodecs` to `true` in configuration?
