### ISSUE TITLE
Can the Volume Bar with Mute/unmute button be added to the overflow Menu ? 

### ISSUE THREAD

**Issue by hafeez432** [shaka-project/shaka-player#7407]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.3.4

**What browser and OS are you using?**
On all Web browsers 

I am looking to move the volume button to the overflow menu. Just trying to check if that's possible with config changes or does it require custom changes.

**Comment by avelad** [comment]
Right now it can't be done, the volume bar is not something we can easily put in the overflow menu. I will make the mute/unmute icon work overflow menu.
