### ISSUE TITLE
Full screen mode does not work on most TVs.

### ISSUE THREAD

**Issue by FiberOnePL** [shaka-project/shaka-player#7419]
It doesn't work on TV in full screen mode. I checked it on a 2018 Sony and a 2019 Samsung. While it worked correctly on previous versions, now I have a black screen and cursor and nothing happens, in normal mode it works correctly.

**Comment by FiberOnePL** [comment]
The last version that works correctly is v2.5.23, newer versions won't load on TV.

https://index-dot-shaka-player-demo.appspot.com/

The latest shaka demo also loads only a white page on TV.

**Comment by avelad** [comment]
Our UI and Demo are not prepared to work on any SmartTV, and we will not support this functionality.

**Comment by FiberOnePL** [comment]
@avelad  I wrote that I also checked if it works there, but it doesn't work on either the production version or the demo version, and I checked which latest version works, so you closed this bug without checking.

**Comment by FiberOnePL** [comment]
Currently I checked on 11 tv full screen does not work properly. We just get a black screen and nothing happens.

**Comment by avelad** [comment]
Version 2.5.X is no longer supported, see our policy at: https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md

**Comment by FiberOnePL** [comment]
@avelad 

But it doesn't work on the latest version, and I wrote that the last version on which full screen worked was version 2x. So there is a bug there because on 11 TVs from 2018 to 2022 on various models the full screen does not work.

**Comment by FiberOnePL** [comment]
![20241018_172558](https://github.com/user-attachments/assets/1f5ac68d-54fa-41b5-bd9c-99e0a5ac8f53)

**Comment by FiberOnePL** [comment]
As you can see there are no controls and a black screen. In normal mode everything works fine only in full screen mode it stops working and this does not apply to 1 tv I think most older tvs if a 2 year old tv can be considered old

**Comment by joeyparrish** [comment]
I would bet that this could be fixed in CSS, assuming those TVs support the fullscreen API in general.  @FiberOnePL, can you get access to dev tools or a debugger on those devices and experiment with the fullscreen styles to help figure out what's wrong?

**Comment by FiberOnePL** [comment]
Not really because I haven't had time for anything lately. I'll try to help but as I wrote to you earlier I won't be able to join the team until after the new year.

**Comment by FiberOnePL** [comment]
@joeyparrish @avelad  

Unfortunately, I have no way of connecting to this TV, but I asked other people and about 50 percent reported this error. If you have the ability to verify this problem on your own, that would be great. Unfortunately, I do not have another TV available on which I could diagnose the problem myself.

**Comment by joeyparrish** [comment]
I don't have a 2018 Sony or a 2019 Samsung.  Sorry!

**Comment by avelad** [comment]
It seems that WebOS for example does not recommend using the Fullscreen API, see https://webostv.developer.lge.com/faq/2024-04-09-how-can-i-set-my-app-to-play-video-in-full-screen 😮
