### ISSUE TITLE
Audio volume normalization

### ISSUE THREAD

**Issue by FiberOnePL** [shaka-project/shaka-player#7420]
Hello, as we know, each video file has a different sound volume, audio normalization in ffmpeg does not always work correctly and often causes sound defects. Is there a possibility in shaka player to normalize audio like in yt player ? 

Thanks for any answers

**Comment by joeyparrish** [comment]
It would have to be through something like the WebAudio API.  You can attach arbitrary filter graphs to the audio of a video and manipulate it in various ways, including adjusting volume.  This might not work with DRM in some cases (I can't verify this), and it might not be available on all devices.

We're unlikely to adopt something like that into Shaka Player unless we know it is robust.

If there's such a feature in YouTube, YouTube has the advantage of encoding and hosting every video they play.  It's conceivable that they have detailed information about audio amplitude ahead of playback.  They also don't do a ton of DRM content.  So I imagine YouTube can do many things that would be impractical for Shaka Player.

**Comment by FiberOnePL** [comment]
@joeyparrish Thank you for your answer. Since I have another question not related to Shaka, I took the liberty of sending you an email with a question.
