### ISSUE TITLE
Abnormal video playback(distorted) in LG and Samsung TV when abr enabled as true

### ISSUE THREAD

**Issue by kumarashu123** [shaka-project/shaka-player#7422]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

v4.11.2

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
not tried

**What browser and OS are you using?**

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG 2023  firmware 03.31.82

**What are the manifest and license server URIs?**

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

drm: {
                servers: {
                    'com.microsoft.playready': XXX,
                },
            },
            streaming: {
                stallThreshold: 2,
                stallSkip: 2,
                observeQualityChanges: true,
            },
            abr: {
                enabled: true,
            },
            mediaSource: {
                codecSwitchingStrategy: 'RELOAD', // workaround for playready fix available in shaka 5.0.0
            },

**What did you do?**

play any VOD content and perform seek or subtitle change

**What did you expect to happen?**
Playback should be smooth

**What actually happened?**

distorted video is seen. 

https://github.com/user-attachments/assets/5f2d0c25-38b0-4de3-9ca3-a43379edffc8

**Are you planning send a PR to fix it?**

**Comment by avelad** [comment]
Does this error only happen on TVs?

**Comment by kumarashu123** [comment]
@avelad In my mpd video track video7 scanType is interlaced and others are progressive does shaka player can switch from interlaced to processive and vice and versa playback smoothly?

**Comment by avelad** [comment]
In my experience using interlaced causes problems on many platforms and that does not depend on Shaka but on the decoder and the MSE implementation, I recommend you switch to using progressive always. Sorry!
