### ISSUE TITLE
[Safari][Live] Player Freeze When Tabbing Out During Live

### ISSUE THREAD

**Issue by sachaelkaim** [shaka-project/shaka-player#7425]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes, I have checked the FAQ and did not find any duplicate open issues that match this problem.

**What version of Shaka Player are you using?**

Version 4.10.12

**Can you reproduce the issue with our latest release version?**

Yes, the issue can be reproduced with the latest release version.

**Can you reproduce the issue with the latest code from `main`?**

This has not been tested with the latest code from main.

**Are you using the demo app or your own custom app?**

The issue was observed using a custom app.

**If custom app, can you reproduce the issue using our demo app?**

Yes, the issue can be reproduced using the Shaka Player Demo.

**What browser and OS are you using?**

Safari Version 17.3.1 (19617.2.4.11.12) on macOS.

**What are the manifest and license server URIs?**

Legacy apple media keys src=TS setup.

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

default except retry parameters.

**What did you do?**

- Play a live stream and mute the player.
- Tab out and do something else on your computer for 5-10 minutes.
- Return to the tab with the player.

**What did you expect to happen?**

Expected the video to resume playing smoothly upon returning to the tab.

**What actually happened?**

The player freezes with no errors and sometimes skips frames but never resumes playing smoothly. Occasionally, if not tabbed out for too long, the player may resume but after a long delay.

This seems to not happen often on low latency streams, but regular live streams this is reproducible 100% of the time.

**Are you planning send a PR to fix it?**

**Comment by avelad** [comment]
Please provide the following information, otherwise we will not be able to help you.

```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  Avoid geo-blocked content if at all possible, as the contributors who diagnose
  Shaka Player issues may not be able to access it.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```
