### ISSUE TITLE
Unable to Access storage.list in CastLabs Electron 28 with Chromium 120 After Offline License Download

### ISSUE THREAD

**Issue by ranjithrr** [shaka-project/shaka-player#7426]
Description:

We are experiencing an issue after updating to CastLabs Electron version 28 (Chromium version 120). Previously, using CastLabs Electron version 27, we could access storage.list data across multiple domains without any problems. However, after the update, this functionality is no longer working as expected.

Steps to Reproduce:

We use Shaka Player version 2.0.0 for offline license download.
We open multiple Electron windows with different domains (e.g., localhost1, localhost2, localhost3) to speed up the offline download license process.
We randomly allocate the files to download the offline license.
After downloading, when playing the content, we open the player on the respective domain to access the relevant IndexedDB data.
We try to access the offline downloaded license through storage.list but receive an empty array.
If we open the console, navigate to the Application tab, and check IndexedDB, we can see the offline downloaded data.
Expected Behavior:

The storage.list should return the data of the offline downloaded licenses, just like it did with CastLabs Electron version 27.
Actual Behavior:

storage.list returns an empty array, even though the data is visible in IndexedDB when manually checked.
Additional Information:

Shaka Player Version: 2.0.0
CastLabs Electron Version: 28
Chromium Version: 120
The same setup worked as expected in CastLabs Electron version 27.
Could there be any recent security changes or restrictions introduced in Electron 28 or Chromium 120 that might be causing this issue?

**Comment by ranjithrr** [comment]
Would you please help me?

**Comment by avelad** [comment]
Version 2.0.0 is no longer supported, see our policy at: https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md

Please test it with a newer version of Shaka, sorry!

**Comment by ranjithrr** [comment]
Used v4.10 as per your recommendation, still same issue , is there any cross domain related changes happed in chromium recent released versions, we are download the offline license in localhost1 stored with same domain in indexedDB, while accessing offline license parent application is launching with localhost and player is loading in ifram with localhost1but storage.list() giving empty array ,please give the solution   , is anything related to "StoragePartitioning"

**Comment by avelad** [comment]
@joeyparrish can you help here? Thanks!

**Comment by joeyparrish** [comment]
I assume it has to do with the different domains used by your application.  You should be able to investigate in the dev console, in the "Application" tab, which lets you see what's stored in IndexedDB.
