### ISSUE TITLE
Using Safari with HLS getVariantTracks() doesn't return expected tracks from Manifest

### ISSUE THREAD

**Issue by daniel-dias** [shaka-project/shaka-player#7434]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.9.5

**What browser and OS are you using?**
Safari 17.1 / 17.4 / 17.5 / 18.0 with MacOS

**Please ask your question**
Using Safari with HLS getVariantTracks() doesn't return expected tracks from Manifest
We have this Manifest below:
![Shaka - Index m3u8 - edited](https://github.com/user-attachments/assets/e902c007-8886-4331-af38-9a46d883bee9)

And this is what we get, after calling .getVariantTracks(), only 1 object in Array, and we expected it to return 6 objects (as the entries on the manifest show).
![Shaka - getVariantTracks Player Object](https://github.com/user-attachments/assets/8ac9dc2c-c6aa-41ef-86d2-2e57ae63be69)

Note: I have seen in the issue https://github.com/shaka-project/shaka-player/issues/2802 that is closed, someone commenting about the "useNativeHlsForFairPlay: false" that could be a solution, but that way the video doesn't even starts.

Using DASH, this method works as expected. So, are we doing something wrong?

Regards,
Daniel

**Comment by avelad** [comment]
When using src= mode the native Apple player is used, in this case the information we provide is all that is provided by the Apple player. If you use MSE you can access all the information.

If your stream is not encrypted, by default we use MSE if the platform has it available.
If your stream is encrypted with FairPlay by default we use src=, if you want to use MSE you have to use `useNativeHlsForFairPlay: false`

**Comment by daniel-dias** [comment]
Hi @avelad 

In fact we are using HLS with FairPlay and having the default (useNativeHlsForFairPlay: true).

So, according to you, the Shaka Player provides all the information that is provided by Apple Player correct? 
Given the screenshots above, (Manifest + .getVariantTracks()), we don't have have access to all the tracks, so there is nothing that Shaka Player can do as this is because the native Apple Player is not passing this informations?

Thanks,
Daniel

**Comment by avelad** [comment]
Yes, that's correct, I'm sorry, but we can't do anything else :(
