### ISSUE TITLE
Widevine/Shaka player doesn't play video

### ISSUE THREAD

**Issue by jonasbu11** [shaka-project/shaka-player#7443]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
There are a few (old) similar issues, except this doesn't result in an error message that I can see.

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

Version: 4.10.2830.0

**Can you reproduce the issue with our latest release version?**
As far as I can tell this is the latest

**Can you reproduce the issue with the latest code from `main`?**

Yeah not my job buddy

**Are you using the demo app or your own custom app?**

No

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
MacOS Sequoia 15.0.1
Brave v1.71.114
Chrome (older)
Safari 18.0.1 

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Beats me.  I'm on Amazon prime, Netflix, then also tried https://shaka-player-demo.appspot.com/

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

What?  No, I'm not building this damn thing, I just want to watch netflix.  And chill, potentially.

**What did you do?**

1. Go to anyplace that would use widevine to play DRM video.  
2. Attempt to play video.  
3. Get no video.  Only sound.
4. Be very frustrated because it was working a few days ago.

**What did you expect to happen?**
Not be frustrated by video not playing.

**What actually happened?**

Became very frustrated by video not playing.
Only sound.

**Are you planning send a PR to fix it?**
Do I look like a developer?

**Comment by avelad** [comment]
In order to help solve your problem you must provide the following information:

```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```
