### ISSUE TITLE
HLS live stream looping issue

### ISSUE THREAD

**Issue by Frederiks96** [shaka-project/shaka-player#7445]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Not related

**What version of Shaka Player are you using?**
`v4.11.7-uncompiled`

**Can you reproduce the issue with our latest release version?**
I can't see the demo app website updated to 4.11.8? But from the release notes in 4.11.8 I don't see this issue specifically addressed.

**Can you reproduce the issue with the latest code from `main`?**
N/A

**Are you using the demo app or your own custom app?**
The demo app and Chromecast devices

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`
Also able to reproduce on
- Chromecast devices
- Safari on an iOS device running 18.0.1

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**
~Unable to disclose the URL publicly, is there a way to send it somewhere else?~
**Update:** I sent an e-mail to `shaka-player-maintainers@googlegroups.com` with the URL

**What configuration are you using? What is the output of `player.getConfiguration()`?**

N/A

**What did you do?**

Played the stream - the error happens consistently.

**What did you expect to happen?**
The stream plays flawlessly (the player continues to the next segment (and the next after that))

**What actually happened?**

After playing for approximately 18 seconds (3 segment durations), the player starts looping a segment over and over. It may jump to a later segment after a few minutes, but will then keep looping that segment. This behaviour repeats over and over.

The same HLS stream plays without issues in AVPlayer, HLS.js, Safari (natively) and ExoPlayer (v2 and Media3).

I see the following output to the console (repeating over and over):
```
Updating manifest...
Possible encoding problem detected! Unexpected buffered range for reference 
should be {
    "start": 1786.4169645309448,
    "end": 1792.4116345309449
}
but got {
    "start": 1792.406319,
    "end": 1798.400985
}
```

**Comment by avelad** [comment]
It seems that your manifest has an incorrect value of #EXT-X-PROGRAM-DATE-TIME on updates.
Your segments are 5.99467 long, but EXT-X-PROGRAM-DATE-TIME is always incremented by 6. That rounding problem causes this issue.

You can use the config `manifest.hls.ignoreManifestProgramDateTime = true` and your stream works correctly with that.

**Comment by Frederiks96** [comment]
Thanks, that seems to do the trick! I'll let the manifest authors know :+1:
