### ISSUE TITLE
Subtitles in HLS are shown too early

### ISSUE THREAD

**Issue by mthie** [shaka-project/shaka-player#7447]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes.

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

4.11.8 / latest

**Can you reproduce the issue with our latest release version?**

Yes.

**Can you reproduce the issue with the latest code from `main`?**

Yes.

**Are you using the demo app or your own custom app?**

Both.

**If custom app, can you reproduce the issue using our demo app?**

Yes.

**What browser and OS are you using?**

Windows 11, Chrome stable and beta.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

N/A

**What are the manifest and license server URIs?**

https://cdn.contentflow.net/corporations/cSR2UwvAfK8yti4pErXo/workspaces/HavgCUYVXa6kAea0IkTK/media/44672e62-8555-4728-b131-794c00b2a6a6/index.m3u8

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

Plain default of the Demo Player.

**What did you do?**

Enable the subtitles and press play.

**What did you expect to happen?**

Show subtitles at the correct timestamp that is defined in the webvtt file.

**What actually happened?**

There's a subtitle starting within the first second of the video, but is not shown. The second subtitle, starting with second 00:02.880 is shown at the beginning of the 2nd second. The result is that subtitles are asynchronous to the spoken text and will be shown before the speaker speaks the first word of the current subtitle line.

It works fine with HLS.js.

**Are you planning send a PR to fix it?**

No.

**Comment by avelad** [comment]
With `manifest.hls.sequenceMode = false` your stream plays fine

**Comment by mthie** [comment]
Sure, thank you for the workaround. :)
