### ISSUE TITLE
Tizen 5.5: when playing DASH, video stuck after changing playback rate

### ISSUE THREAD

**Issue by dk00** [shaka-project/shaka-player#7451]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes.

**If the problem is related to FairPlay, have you read the tutorial?**

Not related, the video doesn't protection.

**What version of Shaka Player are you using?**

4.11.0

**Can you reproduce the issue with our latest release version?**

I'm not in the lab with Tizen 5.5 TV, will try it when I can.

**Can you reproduce the issue with the latest code from `main`?**

Same as above.

**Are you using the demo app or your own custom app?**

[Custom app](https://playcraft-simple.kksweb.vercel.app/simple-video?dash=https%3A%2F%2Fd3gnsg2u8khc44.cloudfront.net%2F85b9cfad-35cc-4424-9615-cefb7e3e76c2%2Fvod%2F343a2360-d3a4-4d2f-be4c-6656da0f564d%2Fvod%2Fdash.mpd)

**If custom app, can you reproduce the issue using our demo app?**

Will try it when I can.

**What browser and OS are you using?**

Tizen 5.5

It work as expected on another Tizen 6 TV.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

Model: TU6900 Crystal UHD 4K Smart TV 2020

**What are the manifest and license server URIs?**

[manifest URL](https://d3gnsg2u8khc44.cloudfront.net/85b9cfad-35cc-4424-9615-cefb7e3e76c2/vod/343a2360-d3a4-4d2f-be4c-6656da0f564d/vod/dash.mpd)
license server is not needed.

This happens only with DASH, when playing HLS, it works as expected.

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

```json
{
  "manifest": {
    "retryParameters": {
      "maxAttempts": 6
    },
    "dash": {
      "ignoreSuggestedPresentationDelay": true
    }
  },
  "streaming": {
    "safeSeekOffset": 0,
    "autoLowLatencyMode": true,
    "preferNativeHls": true
  }
}
```

**What did you do?**

- Open the custom app link in the TV(Tizen 5.5) browser
- (autoplay)
- Change playback rate with the 1.5x button

It sets playback rate with `videoElement.playbackRate = 1.5`.

**What did you expect to happen?**

The video should play with 1.5x playback rate.

**What actually happened?**

Video stuck, play / pause also doesn't work 

**Are you planning send a PR to fix it?**

I have no idea for the cause, but I an willing to send a PR if we can confirm this is a Shaka player bug. 

--

Hi @joeyparrish and Shaka Player Team,

The issue preconditions are:

- Tizen 5.5 (TU6900 Crystal UHD 4K Smart TV 2020), other devices / Tizen versions works as expected
- DASH (not HLS)
- Change playback rate

Some of our video content provides DASH only, so we can't go with HLS only solution.

**Comment by avelad** [comment]
Normally changing the playback rate on TVs doesn't work well, in fact it's not even supported on WebOS. To change the playbackRate try using player.trickPlay(1.5) for example, tell us if this helps, otherwise it's a bug that you'll have to report to Samsung.

**Comment by dk00** [comment]
Hi avelad, thanks for the info.

I'll check if UX of `trickPlay` satisfies customers.
