### ISSUE TITLE
Desync .m3u8 for Shakaplayer

### ISSUE THREAD

**Issue by ValerioCarmineIenco** [shaka-project/shaka-player#7460]
**What version of Shaka Player are you using?**
I am using version 4.6.18

**Can you reproduce the issue with the latest code from `main`?**
**Can you reproduce the issue with our latest release version?**
I can also reproduce the issue in the latest version

**What are the manifest and license server URIs?**
I will send the url of the manifest in private

**What did you do?**
Trying to play a .m3u8 video stream

**What did you expect to happen?**
Video is played back without problems

**What actually happened?**
If I try to play a playlist with multi audio I will see a desynchronisation between audio and video

If I try to play a playlist without multi audio I will see correctly

**Comment by avelad** [comment]
```
**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  Avoid geo-blocked content if at all possible, as the contributors who diagnose
  Shaka Player issues may not be able to access it.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```

Your content requires a VPN to Italy so we can't access it, we'd be happy to review your PR in case you'd like to fix this issue.
