### ISSUE TITLE
Two quite similar manifests containing both HDR and SDR streams causes different streams to be selected

### ISSUE THREAD

**Issue by olapeter** [shaka-project/shaka-player#7468]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
4.9.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Not tried

**Are you using the demo app or your own custom app?**
Both

**If custom app, can you reproduce the issue using our demo app?**
Partially

**What browser and OS are you using?**
WebOS 23 / WebOS 24 / MacOS(Safari)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
LG C3 smart tv (2023)

**What are the manifest and license server URIs?**
https://static.nrk.no/dev/streamtests/shaka-hlg/nrktv9/cmaf.m3u8
https://static.nrk.no/dev/streamtests/shaka-hlg/byliv/cmaf.m3u8
https://static.nrk.no/dev/streamtests/shaka-hlg/byliv/dash.mpd

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

**What did you do?**
Play each of the manifests.

Background: we have some HDR/HLG content that has been working fine on AVPlayer/ExoPlayer and the platform player on LG WebOS (models 2020 and later). However, when using Shaka Player on the same TV, the SDR variant is chosen. A stripped down example can be found here: https://static.nrk.no/dev/streamtests/shaka-hlg/byliv/cmaf.m3u8 and https://static.nrk.no/dev/streamtests/shaka-hlg/byliv/dash.mpd

However, we also have an experimental live HDR-channel where the HDR-variant IS chosen on the same TV with Shaka Player. A static example is provided here https://static.nrk.no/dev/streamtests/shaka-hlg/nrktv9/cmaf.m3u8

So basically, why is one working and not the other?

Similar behavior can be seen on demo player on Safari Mac with HDR-capable screen, with one difference - HLS6-manifest triggers HDR, DASH-manifest does not - so could be different cause with same symptom.

**What did you expect to happen?**
https://static.nrk.no/dev/streamtests/shaka-hlg/nrktv9/cmaf.m3u8 - use the h265-variant and trigger HDR mode on TV
https://static.nrk.no/dev/streamtests/shaka-hlg/byliv/cmaf.m3u8 - use the h265-variant and trigger HDR mode on TV
https://static.nrk.no/dev/streamtests/shaka-hlg/byliv/dash.mpd - use the h265-variant and trigger HDR mode on TV

**What actually happened?**
https://static.nrk.no/dev/streamtests/shaka-hlg/nrktv9/cmaf.m3u8 - works as expected, HDR mode is triggered on HDR-capable screens
https://static.nrk.no/dev/streamtests/shaka-hlg/byliv/cmaf.m3u8 - uses SDR-variant always
https://static.nrk.no/dev/streamtests/shaka-hlg/byliv/dash.mpd - uses SDR-variant always

**Are you planning send a PR to fix it?**
Unsure if it is actually a bug or some stream/content difference we're not aware of.

**Comment by avelad** [comment]
@olapeter PR to fix Shaka issue https://github.com/shaka-project/shaka-player/pull/7470

**Comment by olapeter** [comment]
@avelad Thanks for the swift response.

Regarding Dash and transferCharacteristics - that is probably a good clue. I was under the impression that if not specified it would imply SDR (e.g for HLS it says "VIDEO-RANGE... This attribute is OPTIONAL.  Its absence implies a value of SDR." from https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis ) , however upon further thought that may only hold true if ALL variants are SDR. Couldn't find specific mentions of the combination in the DASH Interop guide.

Was also thrown off by ExoPlayer seemingly handling all variants.
