### ISSUE TITLE
Preload waitforFinish  API issues

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-player#7520]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
NA

**What version of Shaka Player are you using?**
Latest from master

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Mac OS. Chrome browser

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
NA

**What are the manifest and license server URIs?**
It happens with any manifest

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**
Using preload sample code

**What did you do?**
Preload the asset

**What did you expect to happen?**
When we use preload ro load the asset there are 2 issues:
1. If any error happens during preload like license acquire failed or seqment fetch failed then no exception is given to the application. Errors should be given to the application to handle failures. Now the exception is just logged by shaka player
2. When we use preload.waitforfinish(), the api is not waiting for the preload to complete. Preload is complete when the license and the segments are loaded. But this api is not waiting for license and segments to fetch. It returns before that. So application does not know when the preload is completed

**What actually happened?**
Errors are not given to application during preload and also application does not have a way to wait for preload to complete

**Are you planning send a PR to fix it?**
No

**Comment by theodab** [comment]
1. Yes, we probably should be catching those particular errors.
2. The original design was that the preload was considered finished once the manifest et all were downloaded, and the segment prefetch was just an extension of our normal segment prefetch system and thus not counted as part of the preload. However, counting the segment prefetch as part of the preload sounds like a reasonable change in behavior to me.

I'll make a PR for this.
