### ISSUE TITLE
Xone Support

### ISSUE THREAD

**Issue by Iragne** [shaka-project/shaka-player#7522]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes
**If the question is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**
MAin

**What browser and OS are you using?**
> navigator.platform
< "Linux aarch64"

> navigator.userAgent
< "Mozilla/5.0 (Linux; x86_64 GNU/Linux) AppleWebKit/601.1 (KHTML, like Gecko) Version/8.0 Safari/601.1 WPE"

> navigator.vendor
< "Apple Computer, Inc."

**Please ask your question**

Stream used 
https://d24rwxnt7vw9qb.cloudfront.net/v1/dash/e6d234965645b411ad572802b6c9d5a10799c9c1/All_Reference_Streams/ee565ea510cb4b4d8df5f48918c3d6dc/index.mpd

I'm playing a stream multi period live manifest.
I'm bock the playback to only 1 quality to reduce to complexity of the investigation
During the playback i have a lot of GAP that are 4 to 15 second long. it's not making any sense.
Also i compare it to a chrome of an FF playback, i not so much GAP and at that size.
[Info] Jumping forward – 6.088022217154503 – "seconds because of gap starting at" – 113149184.372666 – "and ending at" – .....

I'm a bit lost in the investigation
I did a support with 
shaka.polyfill.MediaSource.stubAbort_();
and shaka.polyfill.MediaSource.patchRemovalRange_();
Also set the canUseNativeMCap to false

But i have a lot of GAP apearing and at the end i reach the edge of the playback
Any guidance ?

**Comment by Iragne** [comment]
Yes i was thinking about this too.
Thanks for the lead.

During my test i figure out that when we are jumping Gap we just going close to the edge.
At the end, we are so close to the edge that when we are jumping a gap we enter in the following condition of the playhead repostion_ function

`if (currentTime > end) {
      shaka.log.v1('Playhead past end.');
      return endl;
    }`

end is the seakable duration but we are kind of looping to this value all the time.
should we not do more something like that


`if (currentTime > end) {
      shaka.log.v1('Playhead past end.');
      return end - this.config_.bufferingGoal;
    }
`

**Comment by Iragne** [comment]
@joeyparrish  you refer to that https://github.com/shaka-project/shaka-player/commit/6ae1474e65cfaf6e7ef0b08a150a1773f768d5ae

**Comment by joeyparrish** [comment]
No, but that may also be relevant.  I was referring to the polyfills.  I dug up this commit, for example:

https://github.com/shaka-project/shaka-player/commit/8c7c74e950791001bdebc5fa57bb9991f5418b9f#diff-7f8f8933c7e0846befae7dec87bf7548d4569126806688c6ff2c0f2619260c9bR54

**Comment by Iragne** [comment]
Thanks a refactor all my code and result look really good now
