### ISSUE TITLE
Player throws error in the Google search console

### ISSUE THREAD

**Issue by almoloo** [shaka-project/shaka-player#7547]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**

4.11.7

**Can you reproduce the issue with our latest release version?**
I have not yet tried the latest release version.

**Can you reproduce the issue with the latest code from `main`?**
I have not yet tried the latest code from main.

**Are you using the demo app or your own custom app?**
I’m using my own custom app.

**If custom app, can you reproduce the issue using our demo app?**
I can not test this issue on the demo app.

**What browser and OS are you using?**
Observed in Google Search Console’s rendering tool.

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

If necessary, I can provide these privately.

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

I can provide this configuration if needed.

**What did you do?**

Integrated Shaka Player (version 4.11.7) on my website to play MPEG-DASH videos, which functions correctly on my site but encounters an error in Google Search Console.

**What did you expect to happen?**
I expected Google Search Console to render my page without error as it is doing now with jwplayer.

**What actually happened?**

In Google Search Console’s rendered view, the following error appears:
```
Shaka Error MANIFEST.CONTENT_UNSUPPORTED_BY_BROWSER ()
    at new shaka.util.Error ([hidden_url]:1:73707)
    at shaka.media.ManifestFilterer.checkPlayableVariants_ ([hidden_url]:1:293598)
    at $jscomp.generator.Engine_.program_ ([hidden_url]:1:292796)
    at $jscomp.generator.Engine_.nextStep_ ([hidden_url]:1:11407)
    at $jscomp.generator.Engine_.next_ ([hidden_url]:1:10371)
    at $jscomp.generator.Generator_.next ([hidden_url]:1:11852)
    at t ([hidden_url]:1:12271)
```

**Are you planning send a PR to fix it?**
Not at this time.

**Comment by avelad** [comment]
The error you get is that there is some format that is not supported. In order to help you we need more information:
```

**What are the manifest and license server URIs?**
<!-- NOTE:
  You can send the URIs to <shaka-player-maintainers@googlegroups.com> instead,
  but please use GitHub and the template for the rest.
  A copy of the manifest text or an attached manifest will **not** be
  enough to reproduce your issue, and we **will** ask you to send a
  URI instead.  You can copy the URI of the demo app to send us the
  exact asset, licence server, and settings you have selected there.
  Avoid geo-blocked content if at all possible, as the contributors who diagnose
  Shaka Player issues may not be able to access it.
  If you send the URIs to email, the response time and resolution
  will be much higher.
-->
```

**Comment by almoloo** [comment]
> The error you get is that there is some format that is not supported. In order to help you we need more information:
> 
> ```
> 
> **What are the manifest and license server URIs?**
> 
> ```

Here is a sample manifest, and there's no license server:
[https://s24.namasha.com/dash/7319859993/Manifest.mpd](https://s24.namasha.com/dash/7319859993/Manifest.mpd)

```
<?xml version="1.0"?>
<!-- MPD file Generated with GPAC version 0.7.0-rev0-gbd5c9af-master  at 2021-08-24T06:24:10.216Z-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500S" type="static" mediaPresentationDuration="PT0H3M3.228S" maxSegmentDuration="PT0H0M10.000S" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011">
 <ProgramInformation moreInformationURL="http://www.namasha.com">
  <Title>generated by namasha</Title>
 </ProgramInformation>

 <Period duration="PT0H3M3.228S">
  <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9" lang="und" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
   <ContentComponent id="1" contentType="video" />
   <ContentComponent id="2" contentType="audio" />
   <Representation id="1" mimeType="video/mp4" codecs="avc1.640028,mp4a.40.2" width="1280" height="720" frameRate="24" sar="1:1" audioSamplingRate="44100" startWithSAP="1" bandwidth="959746">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>720p_dashinit</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1457-1716">
      <Initialization range="0-1456"/>
    </SegmentBase>
   </Representation>
   <Representation id="2" mimeType="video/mp4" codecs="avc1.42C01E,mp4a.40.2" width="852" height="480" frameRate="24" sar="640:639" audioSamplingRate="44100" startWithSAP="1" bandwidth="685347">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>480p_dashinit</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1455-1714">
      <Initialization range="0-1454"/>
    </SegmentBase>
   </Representation>
   <Representation id="3" mimeType="video/mp4" codecs="avc1.42C01E,mp4a.40.2" width="640" height="360" frameRate="24" sar="1:1" audioSamplingRate="44100" startWithSAP="1" bandwidth="461037">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>360p_dashinit</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1451-1710">
      <Initialization range="0-1450"/>
    </SegmentBase>
   </Representation>
   <Representation id="4" mimeType="video/mp4" codecs="avc1.42C01E,mp4a.40.2" width="426" height="238" frameRate="24" sar="1904:1917" audioSamplingRate="44100" startWithSAP="1" bandwidth="277647">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>240p_dashinit</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1455-1714">
      <Initialization range="0-1454"/>
    </SegmentBase>
   </Representation>
   <Representation id="5" mimeType="video/mp4" codecs="avc1.42C01E,mp4a.40.2" width="256" height="144" frameRate="24" sar="1:1" audioSamplingRate="44100" startWithSAP="1" bandwidth="159402">
    <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
    <BaseURL>144p_dashinit</BaseURL>
    <SegmentBase indexRangeExact="true" indexRange="1450-1709">
      <Initialization range="0-1449"/>
    </SegmentBase>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
```

**Comment by avelad** [comment]
@joeyparrish do you have any idea?

**Comment by joeyparrish** [comment]
I do not know what would cause this, but I assume that the search console is embedding your page in an iframe, and it may not have the necessary rights to play media, or there may be modifications in the environment of that frame that break the player or its polyfills in some way.

I have no experience with the Google Search Console, and I assume I won't be able to access your dashboard to debug it myself.

If you can use a debug build of Shaka Player, and enable verbose logging in your app, you may be able to give us logs of the failure in context of Google Search Console.  That might help us figure out what is causing the incompatibility.

But since this isn't affecting actual visitors to your site, only the rendering of your page for your eyes only in Google Search Console, I'm marking this at a low priority (P3).

**Comment by almoloo** [comment]
I've tested the issue with the demo app. when You try a dash manifest like [the one here](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;assetBase64=eyJuYW1lIjoiQW5nZWwgT25lIChtdWx0aWNvZGVjLCBtdWx0aWxpbmd1YWwpIiwic2hvcnROYW1lIjoiQW5nZWwgT25lIiwiaWNvblVyaSI6Imh0dHBzOi8vc3RvcmFnZS5nb29nbGVhcGlzLmNvbS9zaGFrYS1hc3NldC1pY29ucy9hbmdlbF9vbmUucG5nIiwibWFuaWZlc3RVcmkiOiJodHRwczovL3N0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vc2hha2EtZGVtby1hc3NldHMvYW5nZWwtb25lL2Rhc2gubXBkIiwic291cmNlIjoiU2hha2EiLCJmb2N1cyI6ZmFsc2UsImRpc2FibGVkIjpmYWxzZSwiZXh0cmFUZXh0IjpbXSwiZXh0cmFUaHVtYm5haWwiOltdLCJleHRyYUNoYXB0ZXIiOltdLCJjZXJ0aWZpY2F0ZVVyaSI6bnVsbCwiZGVzY3JpcHRpb24iOiJBIGNsaXAgZnJvbSBhIGNsYXNzaWMgU3RhciBUcmVrIFRORyBlcGlzb2RlLCBwcmVzZW50ZWQgaW4gTVBFRy1EQVNILiIsImlzRmVhdHVyZWQiOnRydWUsImRybSI6WyJObyBEUk0gcHJvdGVjdGlvbiJdLCJmZWF0dXJlcyI6WyJEQVNIIiwiRG93bmxvYWRhYmxlIiwiTVA0IiwiTXVsdGlwbGUgbGFuZ3VhZ2VzIiwiU3VidGl0bGVzIiwiVk9EIiwiV2ViTSJdLCJsaWNlbnNlU2VydmVycyI6eyJfX3R5cGVfXyI6Im1hcCJ9LCJsaWNlbnNlUmVxdWVzdEhlYWRlcnMiOnsiX190eXBlX18iOiJtYXAifSwicmVxdWVzdEZpbHRlciI6bnVsbCwicmVzcG9uc2VGaWx0ZXIiOm51bGwsImNsZWFyS2V5cyI6eyJfX3R5cGVfXyI6Im1hcCJ9LCJleHRyYUNvbmZpZyI6bnVsbCwiZXh0cmFVaUNvbmZpZyI6bnVsbCwiYWRUYWdVcmkiOm51bGwsImltYVZpZGVvSWQiOm51bGwsImltYUFzc2V0S2V5IjpudWxsLCJpbWFDb250ZW50U3JjSWQiOm51bGwsImltYU1hbmlmZXN0VHlwZSI6bnVsbCwibWVkaWFUYWlsb3JVcmwiOm51bGwsIm1lZGlhVGFpbG9yQWRzUGFyYW1zIjpudWxsLCJ1c2VJTUEiOnRydWUsIm1pbWVUeXBlIjpudWxsfQ==;panel=ALL_CONTENT;panelData=DASH;build=uncompiled) and feed it to the [Google PageSpeed Insights](https://pagespeed.web.dev) you get the same error.
![Screenshot](https://github.com/user-attachments/assets/3a3550ad-22b9-4215-a668-5ab266b8b9e4)

**Comment by joeyparrish** [comment]
[Google PageSpeed Insights](https://pagespeed.web.dev/) does not render the page in your browser.  If you start watching network traffic in the browser's dev console, then hit the analyze button in PageSpeed Insights, you will never see a request for the demo page or any version of the Shaka Player library.

It is rendered server-side as far as I can tell, presumably in an environment that does not have the necessary codecs.  There's nothing we can do about that, no further information we can gather from it, and it's not a problem with Shaka Player itself AFAICT.  If the browser runtime can't play the content, then error message is legitimate in this case.
