### ISSUE TITLE
Some HLS streams video/audio are out of sync

### ISSUE THREAD

**Issue by avicarpio** [shaka-project/shaka-player#7551]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the problem is related to FairPlay, have you read the tutorial?**

-

**What version of Shaka Player are you using?**

4.11.11

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
both

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Chromium

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
-

**What are the manifest and license server URIs?**

https://directes3-tv-cat.3catdirectes.cat/live-content/tv3-hls/master.m3u8

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

{}

**What did you do?**

play the hls that I provided or some 24/7 content

**What did you expect to happen?**
Audio/video play on sync. hls.js and video.js play the content well.

**What actually happened?**

Audio/Video not on sync

**Are you planning send a PR to fix it?**
Not enough knowledge to do a PR

**Comment by avelad** [comment]
The problem is that your stream doesn't use #EXTINF precision, it rounds the value instead, and this is something Shaka doesn't support and we don't plan to support, since this happens to more people, I think it's worth mentioning in the documentation. 

HLS Spec: https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-15#section-4.4.4.1

```
The EXTINF tag specifies the duration of a Media Segment.  It applies
   only to the next Media Segment.  This tag is REQUIRED for each Media
   Segment.  Its format is:
   #EXTINF:<duration>,[<title>]
   where duration is a decimal-floating-point or decimal-integer number
   (as described in Section 4.2) that specifies the duration of the
   Media Segment in seconds and title is the remainder of the line
   following the comma.  Durations SHOULD be decimal-floating-point,
   with enough accuracy to avoid perceptible error when segment
   durations are accumulated.  However, if the compatibility version
   number is less than 3, durations MUST be integers.  Durations that
   are reported as integers SHOULD be rounded to the nearest integer.
```
