### ISSUE TITLE
VTT italic subtitles badly displayed

### ISSUE THREAD

**Issue by Robloche** [shaka-project/shaka-player#7553]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
Issue reproduced on the demo page:
https://shaka-player-demo.appspot.com/demo

**Can you reproduce the issue with our latest release version?**
Yes.

**Can you reproduce the issue with the latest code from `main`?**
Not tried.

**Are you using the demo app or your own custom app?**
Demo app.

**What browser and OS are you using?**
Chrome 130.0.6723.92 (Build officiel) (64 bits)

In the VTT file, we can see:
```
00:03:33.600 --> 00:03:38.000 align:end position:90% line:91%,end
Je viendrai à cheval, en gants blancs
chercher <i>Le Gaulois.</i>
```

But on screen, the two elements `chercher` and `Le Gaulois.` are swapped:
![image](https://github.com/user-attachments/assets/1c945e75-cc8c-4335-ad2b-c00df4026061)

**Comment by avelad** [comment]
@Robloche do you want send a PR to fix it?

**Comment by Robloche** [comment]
I'd like to, but I'm pretty deep into my workload these days...

**Comment by avelad** [comment]
@joeyparrish do you have idea about how fix it?

**Comment by avelad** [comment]
I have been able to reproduce the issue. It only happens with UITextDisplayer, with SimpleTextDisplayer it does not happen.

**Comment by avelad** [comment]
@Robloche I created a PR to fix it https://github.com/shaka-project/shaka-player/pull/7559 , Can you tell me if it looks fixed? (for me yes, but I want your confirmation) Thanks!

**Comment by joeyparrish** [comment]
It won't be in the nightly build until after the PR is merged.  But the PR is waiting for your confirmation.  You could cherry-pick or check out the PR change and use a local build, or we can go ahead and merge it so you can try the next nightly.

**Comment by Robloche** [comment]
Merging and testing the nightly build tomorrow morning would be good to me, thanks.

**Comment by Robloche** [comment]
I confirm that it's fixed for me as well.

Thank you for the quick fix!
