### ISSUE TITLE
Video Source Buffer Params Lost During Audio Codec Switch Reload

### ISSUE THREAD

**Issue by dpfister2** [shaka-project/shaka-player#7555]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not related

**What version of Shaka Player are you using?**

4.11.11

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome Browser, Mac OS

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd (Angel One from Demo page)

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

```
{
    "mediaSource": {
        "codecSwitchingStrategy": "reload"
    }
}
```

**What did you do?**

Swap from English AAC to English Opus. Set a breakpoint in media_source_engine to inspect the source buffers. 

**What did you expect to happen?**
That the video source buffer params (timestamp/appendWindowStart/appendWindowEnd) are added during the reload

**What actually happened?**

Verify that while audio source buffer params are correctly added, video source buffer is missing them. Google Chrome is able to silently handle this, but I have seen a Gen 3 Chromecast fail to load when the params are missing.

<img width="289" alt="Screenshot 2024-11-06 at 11 47 11 AM" src="https://github.com/user-attachments/assets/f4c5c799-3e49-4d8e-a772-7c28b246f60c">

**Are you planning send a PR to fix it?**
Yes, but I wanted to get feedback on the suggested fix.
Two possibilities are

- Surface the `media_source_engine` reset call to `streaming_engine` so the `mediastates` can be cleaned (which will call `setStreamProperties` for both audio and video).
- Save source buffer params on reset and restore them at end of the reset
Would like to hear which route I should take (or an alternative option)

**Comment by tykus160** [comment]
Hi @dpfister2. Stream properties values theoretically should be set by StreamingEngine during reset operation. As it doesn't happen, it looks like some nasty race condition.
As a quick fix / workaround I think the option suggested (Save source buffer params on reset and restore them at end of the reset) is enough, if it solves the described issue on Chromecast.
However, I'd love to see proper synchronization of actions during reload in StreamingEngine / MediaSourceEngine to avoid potential race conditions in the future (as we see some race conditions occasionally in integration tests).
@joeyparrish what do you think?

**Comment by joeyparrish** [comment]
I would prefer it if we could understand the race and resolve it if possible.

I would also love suggestions on how we could redesign StreamingEngine/MediaSourceEngine/etc to avoid races and complexity in general, if anyone has thoughts on that.
