### ISSUE TITLE
What's the current LTS branch as of November 2024?

### ISSUE THREAD

**Issue by seanbecker15** [shaka-project/shaka-player#7562]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
N/A

**What browser and OS are you using?**
N/A

**Please ask your question**
In an issue opened recently there's a [comment](https://github.com/shaka-project/shaka-player/issues/7399#issuecomment-2428192448) stating that v4.9 is LTS. However, [maintained-branches.md](https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md) states that there is not an active LTS. Hoping to clarify whether 4.9 is indeed LTS, and for how long that will be the case if it is known.

**Comment by joeyparrish** [comment]
Sorry for the confusion.  We have LTS for 1 year on the branch right before we make a breaking change.  We don't have one of those right now.

v4.9 is in use by the Cast SDK right now, and we (Google / Cast) will maintain that branch for as long as the Cast SDK uses it.  So it's very similar to the LTS status we give before a breaking change, but it ends as soon as the Cast SDK moves on from that branch.  I should have chosen my words more carefully, and I'll edit the comment you linked to clarify.

**Comment by seanbecker15** [comment]
Just to make sure I'm fully understanding the LTS strategy, hypothetically speaking once the team rolls out 5.x there will be an LTS (likely one of the 4.x branches) for one year. Is that correct?

Thanks for the quick response and updating the comment, and no worries. I'm guessing you didn't expect for someone to take a comment so deep in the weeds so literally.

**Comment by seanbecker15** [comment]
Understood. It does sound like a lot of overhead to port fixes between two languages for an extended period of time. Will keep an eye out for that decision.
