### ISSUE TITLE
No captions in fullscreen mode on iPhone (iOS) in Shaka demo

### ISSUE THREAD

**Issue by jakubkrolikowski** [shaka-project/shaka-player#7568]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

yes

**If the problem is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**

4.11.12

**Can you reproduce the issue with our latest release version?**
yes

**Can you reproduce the issue with the latest code from `main`?**
yes

**Are you using the demo app or your own custom app?**
demo and custom

**If custom app, can you reproduce the issue using our demo app?**
yes

**What browser and OS are you using?**
Safari on iOS 17.5.1 (iPhone 12)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

Default demo Angel One from:
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=uncompiled

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

Demo default configuration.

**What did you do?**

Play demo Angel One on iPhone, turn on captions, turn on full screen mode.

**What did you expect to happen?**
Captions / subtitles will be visible.

**What actually happened?**

No caption in fullscreen mode.

**Are you planning send a PR to fix it?**
No. 
Looks like in normal mode caption are rendered by Shaka text displayer. They disapear on fullscreen mode.
I think subtitles should be rendered in this case by native IOS player.

**Comment by avelad** [comment]
This only happens with `UITextDisplayer`, with `SimpleTextDisplayer` this does not happen.

**Comment by jakubkrolikowski** [comment]
> This only happens with `UITextDisplayer`, with `SimpleTextDisplayer` this does not happen.

I guess Shaka demo player uses defualt SimpleTextDisplayer, right?

**Comment by avelad** [comment]
> > This only happens with `UITextDisplayer`, with `SimpleTextDisplayer` this does not happen.
> 
> I guess Shaka demo player uses defualt SimpleTextDisplayer, right?

Yes

**Comment by jakubkrolikowski** [comment]
> > > This only happens with `UITextDisplayer`, with `SimpleTextDisplayer` this does not happen.
> > 
> > 
> > I guess Shaka demo player uses defualt SimpleTextDisplayer, right?
> 
> Yes

So I can reproduce this bug on my iPhone playing demo Angel One, which uses a SimpleTextDisplayer.

**Comment by avelad** [comment]
> > > > This only happens with `UITextDisplayer`, with `SimpleTextDisplayer` this does not happen.
> > > 
> > > 
> > > I guess Shaka demo player uses defualt SimpleTextDisplayer, right?
> > 
> > 
> > Yes
> 
> No, I believe the default for the demo is UITextDisplayer, since we are using the full UI.

Oh yeah, it depends on whether you use Shaka UI or not.
