### ISSUE TITLE
How to force player to use only native caption on iOS iPhone?

### ISSUE THREAD

**Issue by jakubkrolikowski** [shaka-project/shaka-player#7570]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**What version of Shaka Player are you using?**
4.10.26

**What browser and OS are you using?**
Safari on iOS 17.5.1 (iPhone 12)

**Please ask your question**
I noticed that Shaka Player in fullscreen mode on iPhone displays captions in two modes simultaneously - natively and rendered by Shaka's text displayer. Just before the native caption is displayed, I can see the shaka-rendered subtitle flash for a moment.
More over, shaka-rendered subtitles are displayed only when I exit the fullscreen mode (native are hidden then).

Turning off shaka controls with
`controls.setEnabledShakaControls(false);`
does not help, the subtitles are rendered twice anyway.

How can I force the player to use only native captions rendering, or only rendering by Shaka TextDisplayer (not both in the same time)?

I use UITextDisplayer (configuration below), however with default SimpleTextDisplayer problem is the same.
```
player.configure({
        textDisplayFactory: function() {  
            return new shaka.text.UITextDisplayer (video, document.getElementById('shaka-content')):
         }
});

```

**Comment by joeyparrish** [comment]
If the text is rendered natively, we might have fed text tracks to the platform somehow.  UITextDisplayer should only be active when we are in control of text tracks at the player level, and they are not fed to the platform (through src= or TextTrack/VTTCue APIs).

**Comment by youcheng-yc** [comment]
I have the same issue, when in fullscreen mode on my iOS 17.5.1, there are two(three, sometimes) duplicated subtitles rendered. When leaving fullscreen mode, there is only one subtitle rendered as expected.
Here is my code:

```js
    const tag = document.querySelector('video');
    shaka.polyfill.installAll();
    const shakaPlayer = new shaka.Player();
    const shakaConfig = {
      drm: {/** some FairPlay Setting **/}
    };
    // some network filters are skipped
    shakaPlayer.configure(shakaConfig);
    shakaPlayer.attach(tag);
    shakaPlayer.load('https://contents.pallycon.com/test-contents/tearsofsteel/cmaf/master.m3u8');
```
Could you please provide some advice about this?
(shaka version: v4.12.4)

**Comment by youcheng-yc** [comment]
@shaka-bot reopen
