### ISSUE TITLE
Tizen 6.5: when playing HLS, video stuck while switch between stereo and surround audio

### ISSUE THREAD

**Issue by Itsysho** [shaka-project/shaka-player#7595]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**If the problem is related to FairPlay, have you read the tutorial?**

Not related, the video doesn't protection.

**What version of Shaka Player are you using?**

4.11.4

**Can you reproduce the issue with our latest release version?**
I'm not in the lab with Tizen 6.5 TV, will try it when I can.

**Can you reproduce the issue with the latest code from `main`?**
Same as above.

**Are you using the demo app or your own custom app?**
My custom app

**If custom app, can you reproduce the issue using our demo app?**
Also reproduced in my custom app, I tried to fix by
```
player.selectAudioLanguage(
      activeTrack.language,
      undefined,
      activeTrack.channelsCount,
    )
```
or
```
player.selectVariantsByLabel(activeTrack.label)
```

It could be fix with workaround 
```
player.selectAudioLanguage(activeTrack.language)
player.configure("preferredAudioChannelCount", targetLanguage.channelsCount)
player.reload()
```

**What browser and OS are you using?**
Tizen 8.0 / Chromium 108
It also happen Tizen 6.5 / Chromium 85 and Tizen 7.0 / Chromium.

`userAgent: Mozilla/5.0 (SMART-TV; Linux; Tizen 8.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/7.0 Chrome/108.0.5359.1 TV Safari/537.36`

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

**What are the manifest and license server URIs?**

```
#EXT-X-MEDIA:TYPE=AUDIO,URI="",GROUP-ID="audio-AACL-127",LANGUAGE="ja",NAME="Japanese",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2"
#EXT-X-MEDIA:TYPE=AUDIO,URI="",GROUP-ID="audio-AC-3-384",LANGUAGE="und",NAME="Undetermined",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="6"

```

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

```
{
  "manifest": {
    "retryParameters": {
      "maxAttempts": 6
    },
    "dash": {
      "ignoreSuggestedPresentationDelay": true
    }
  },
  "streaming": {
    "safeSeekOffset": 0,
    "autoLowLatencyMode": true,
    "preferNativeHls": true
  }
}
```

**What did you do?**
On a device that supports surround sound:

- Load a stream that contains both stereo and surround audio renditions.
- Switch between stereo and surround audio.
- Player stuck.

**What did you expect to happen?**
- Play normally.

**What actually happened?**

- Player stuck.

**Are you planning send a PR to fix it?**
Yes, let's find the cause.

**Comment by tykus160** [comment]
@avelad on Tizen 6 shaka uses reload by default.
This is probably caused by #7555

**Comment by avelad** [comment]
Duplicated of https://github.com/shaka-project/shaka-player/issues/7555

**Comment by Itsysho** [comment]
We could reproduce the issue in [shaka 4.11.14](https://github.com/shaka-project/shaka-player/pull/7634) which [#7555](https://github.com/shaka-project/shaka-player/issues/7555) check in version and shaka  4.12.2 demo page.

**Comment by avelad** [comment]
@tykus160 can you review it? Thanks!

**Comment by Iragne** [comment]
Hello can it be link to PS5 issue to ?

**Comment by tykus160** [comment]
@Iragne it's very likable. There's a draft PR of mine, I'm testing it mainly on Tizen & Chromecast now, but if you have a capability to make a draft run with this on PS5, that would be great!

**Comment by Iragne** [comment]
I will share to the team yes we will do

**Comment by Iragne** [comment]
FYI we are testing it this week and next week with long playback our testing will be on ps5 and we will force a lot of quality change and seek back and forward out of the buffer.
the current testing phase with this + this https://github.com/shaka-project/shaka-player/pull/7723 is really promissing

**Comment by Iragne** [comment]
@avelad  and @tykus160 this fix is making a huge improvement on cc devices. We will run it in production shortly.
