### ISSUE TITLE
Setting up Shaka Player for DASH Streaming on Meta Quest Browser

### ISSUE THREAD

**Issue by user1233445** [shaka-project/shaka-player#7599]
**What version of Shaka Player are you using?**
Latest (current version)

**What browser and OS are you using?**
Meta Quest Browser on Meta Quest build 71.0 

**Please ask your question**
I’d like to know if it’s possible to use the Shaka Player plugin embedded in an HTML file to play a DASH stream in the Meta Quest Browser. If this is possible, what are the specific requirements for the DASH stream in terms of compatibility with Shaka Player and the Meta Quest Browser? Are there any particular codecs, formats, or configurations (e.g., fMP4 segments, CORS headers) that need to be in place for smooth playback?

Thank you!

**Comment by joeyparrish** [comment]
I don't know anything about the Meta Quest browser, and it's not an officially-supported platform.  If it works, great!  If it doesn't, PRs are welcome.

Someone else in the community may have direct experience with it, and we welcome all comments.

You can load https://shaka-player-demo.appspot.com/support.html in any browser to get a dump of what it does or doesn't support through Shaka Player.  If you would like help interpreting it, please feel free to paste the results from the Meta Quest browser here.

**Comment by avelad** [comment]
Do you want this for a website, or to run inside a game with Unreal or Unity?

**Comment by joeyparrish** [comment]
Did you install polyfills in your application with `shaka.polyfill.installAll()`?

**Comment by user1233445** [comment]
That was the fix. It now works seamlessly on all browsers. Thanks so much for your help!
