### ISSUE TITLE
Understand Shaka Player documentation

### ISSUE THREAD

**Issue by ycharbi** [shaka-project/shaka-player#7601]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

**What version of Shaka Player are you using?**
v4.11.7

**What browser and OS are you using?**
Firefox on Debian 12

**Please ask your question**
I don't understand how the parameters in your documentation are reflected in the configuration of Shaka Player.

For example, I'm trying (but this is not the only case I've encountered) to correct the `streaming.liveSync has been deprecated and will be removed in v5.0 . We are currently at version v4.11 . Additional information: Please Use streaming.liveSync.enabled instead.` warning message linked to the `liveSync: true` parameter. I've found the [documentation page](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.LiveSyncConfiguration) on the subject, but I can't integrate it into my configuration (copied from the Internet):
```
player.configure({
        preferredTextLanguage: 'fr',
        streaming: {
            lowLatencyMode: true,
            liveSync: true,
            inaccurateManifestTolerance: 0,
            rebufferingGoal: 0.01,
            segmentPrefetchLimit: 2,
            updateIntervalSeconds: 0.1,
            maxDisabledTime: 1,
            retryParameters: {
              baseDelay: 100,
            },  
        },
...
```

How do you get from your table to a Json structure understood by the software? All my attempts have failed. I don't understand how we're supposed to interpret your documentation to configure the software.

Parameters seem to be able to be passed as `player.configure('streaming.liveSync.enabled', true);` but this is not practical with many parameters. I'd like to pass everything as a Json tree.

If you can tell me how to convert the documentation into a usable configuration, that would be great.

Thank you.

**Comment by tykus160** [comment]
Hi! [Here](https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.StreamingConfiguration) you can find that one of properties is `liveSync` which should be `LiveSyncConfiguration` object you've linked before.
So, in your example, you should call `configure()` method like that (replace `liveSync` from boolean to object):

```js
player.configure({
  preferredTextLanguage: 'fr',
  streaming: {
    lowLatencyMode: true,
    liveSync: {
      enabled: true,
    },
    inaccurateManifestTolerance: 0,
    rebufferingGoal: 0.01,
    segmentPrefetchLimit: 2,
    updateIntervalSeconds: 0.1,
    maxDisabledTime: 1,
    retryParameters: {
      baseDelay: 100,
    },  
  },
});
```

You can find more info how shaka configuration works [here](https://shaka-player-demo.appspot.com/docs/api/tutorial-config.html).

**Comment by joeyparrish** [comment]
In general, the string syntax is just a path through the object syntax.  So, for example:

```js
player.configure('streaming.liveSync.enabled', true);
```

Is equivalent to:

```js
player.configure({
  streaming: {
    liveSync: {
      enabled: true,
    },
  },
});
```

Does this help?

I would appreciate a docs PR if you want to suggest a better way to explain it in the docs.  Whatever would have helped you understand the first time is a welcome improvement!

**Comment by ycharbi** [comment]
Hello,

Thank you both for your answers, it was helpful!
I'll see if I understand the logic when I get back on this subject.

> I would appreciate a docs PR if you want to suggest a better way to explain it in the docs. Whatever would have helped you understand the first time is a welcome improvement!

I'm not promising anything, but I'll see what I can do, because it's not easy to understand, and I'd be happy to help make it more accessible.

Documentation is no mean feat...

Best regards.
