### ISSUE TITLE
feat: Add 'downloadcompleted' event

### ISSUE THREAD

**Issue by vlazh** [shaka-project/shaka-player#7608]
**Is your feature request related to a problem? Please describe.**

NetworkEngine can notify about download failed but there is no way to know when the download is completed (before filters applied). It needs for custom Abr managers, at least, to correct track start and end body downloads.

**Describe the solution you'd like**

I suggest to add event 'downloadcompleted' and modify NetworkEngine for that.

**Are you planning send a PR to add it?**
Yes.

**Comment by tykus160** [comment]
@vlazh if you're interested, I have a working solution for this already but couldn't find time before to pushing it back.
