### ISSUE TITLE
 Shaka freezes when there are many players on the page (video decode error)

### ISSUE THREAD

**Issue by Kalynov** [shaka-project/shaka-player#7612]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**
Not related

**What version of Shaka Player are you using?**
4.12.0

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
No

**Are you using the demo app or your own custom app?**
use custom app

**If custom app, can you reproduce the issue using our demo app?**
no

**What browser and OS are you using?**
google chrome 130.0.6723.117
windows server 2019 standart

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not related

**What are the manifest and license server URIs?**
https://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live-periods/mp4-live-periods-mpd.mpd

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**
I use default config 
`{}`

**What did you do?**
I added 10 identical players to the page with the same link (and different) to the DASH manifest, “Hardware graphics acceleration” was enabled in the browser. 

**What did you expect to happen?**
players work stably all the time, video plays, no errors, RAM consumption does not increase

**What actually happened?**
within 1-2 minutes after turning on the video, the browser consumes more than 6GB of RAM and the tab crashes. no errors appear in the console.

If you turn off “hardware graphics acceleration” in the browser, memory consumption does not increase, but after ~15 minutes the players freeze, video playback stops in all players. there are no errors in the console.

One day the error "video decode error" appeared in the console
![image](https://github.com/user-attachments/assets/9e17a7c3-57d6-404f-ada0-1443c7c429ed)

**Are you planning send a PR to fix it?**
Uncertain at this moment

**Comment by avelad** [comment]
This doesn't seem like a Shaka error but rather a bug from the browser itself when managing multiple MSEs... I think you should open the issue at https://issues.chromium.org/

**Comment by Kalynov** [comment]
in Firefox the behavior is similar

**Comment by joeyparrish** [comment]
For Chrome, see https://crbug.com/, for Firefox, see https://bugzilla.mozilla.org/
