### ISSUE TITLE
com.widevine.alpha.experiment key system setup

### ISSUE THREAD

**Issue by Jason239** [shaka-project/shaka-player#7613]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
yes

**If the question is related to FairPlay, have you read the tutorial?**

not related

**What version of Shaka Player are you using?**
4.6.2

**What browser and OS are you using?**
Windows 11 / Chrome

**Please ask your question**

I'm trying to do a Widevine L1 playback test, but when I set the key system as below in Shaka player, I get a 6012 error. If set it to the `com.widevine.alpha` key system, it work fine.
Internally, the `com.widevine.alpha.experiment` key system doesn't seem to be working, is it because it's an experimental key system and is prevented from being used? 

```
playerConfig = {
                drm: {
                    servers: {
                        'com.widevine.alpha.experiment': licenseUri
                        
                    },
                    advanced: {
                        'com.widevine.alpha.experiment': {
                            'distinctiveIdentifierRequired': false,
                            'persistentStateRequired': true,
                            videoRobustness: 'HW_SECURE_ALL',
                            audioRobustness: 'HW_SECURE_CRYPTO'
                        }
                    }
                },
                streaming: {
                    autoLowLatencyMode: true,
                },
            };
```

**Comment by avelad** [comment]
I think that you need use `distinctiveIdentifierRequired = true` to used Widevine L1 (https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding?tab=readme-ov-file#requestmediakeysystemaccess)

**Comment by aykut-33** [comment]
I am getting the same error. Any updates?

**Comment by avelad** [comment]
I found a error in the code... I'll create a PR to fix it very soon!

**Comment by bora-bora-bora** [comment]
> @MarianoFacundoArch Widevine L1 license is delivered as a wrapped PlayReady license. @tykus160 Yes, I tested it and the key system is now working fine. Thanks for the quick fix :)

Hi Jason239,

We are also facing with same issue but now it is okay with latest build. However, now it is not clear for us to handle this widevine license which wrapped PlayReady license. Could you please help us if you have any clue?
