### ISSUE TITLE
MPEG-H support in Shaka-player

### ISSUE THREAD

**Issue by cecosme** [shaka-project/shaka-player#7655]
Dear GStreamer team,

The Brazilian SBTVD Forum has finished the draft standards for Brazil's second-generation Digital Terrestrial Television system called TV 3.0 (more details here: https://forumsbtvd.org.br/tv3_0/#panel-phase3). The current TV 3.0 roadmap expects prototypes to be deployed in 2025/Q2-Q4 and commercial products in 2026/Q1-Q2.

The MPEG-H Audio system which is already adopted by ATSC (ATSC 3.0 TV), DVB, TTA (Korean TV) and now is adopted by Brazilian SBTVD as the sole audio codec for Brazil's TV 3.0.

I would like to open this issue to request the MPEG-H support in GStreamer. More information related to MPEG-H Audio can be found here:

Information: https://mpegh.com/news/brazil/
GitHub Decoder: https://github.com/Fraunhofer-IIS/mpeghdec
GitHub IEC Encapsulation: https://github.com/Fraunhofer-IIS/iec61937-13
Test Material: https://mpegh.com/academy/testing-and-qa/
ExoPlayer Integration: https://github.com/androidx/media/tree/main/libraries/decoder_mpegh
MediaInfo support: https://mediaarea.net/MediaInfo/ChangeLog

BR, Carlos Cosme

**Comment by joeyparrish** [comment]
> I would like to open this issue to request the MPEG-H support in GStreamer. 

This isn't GStreamer, this is Shaka Player.  Please see https://gstreamer.freedesktop.org/
