### ISSUE TITLE
HLS no longer works on v4

### ISSUE THREAD

**Issue by ProtoScott** [shaka-project/shaka-player#7664]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
https://github.com/shaka-project/shaka-player/issues/4852 - this issue was opened with the same bug but was never resolved.

**What version of Shaka Player are you using?**
3.3.1 - Working
4.12.2 - Not working (I have tried a few version)

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Yes

**If custom app, can you reproduce the issue using our demo app?**
TBD

**What browser and OS are you using?**
Mac OS (latest/any) Safari (latest/any)

**What are the manifest and license server URIs?**
Staging Site / Credentials sent to: shaka-player-maintainers@googlegroups.com

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**
Will confirm on device shortly.

**What did you do?**
Play content back on safari.

**What did you expect to happen?**
Playback

**What actually happened?**
3016 error. It seems to download the first two chunks then throws the 3016.
The chunk sizes on the 3.x and 4.x builds are the same, so it doesn't seem to be an issue from that.

**Are you planning send a PR to fix it?**
No

**Comment by avelad** [comment]
Maybe similar to https://github.com/shaka-project/shaka-player/issues/7629 ?

**Comment by ProtoScott** [comment]
> Maybe similar to #7629 ?

Yeah possibly a duplicate, though they at least get a few playback before breakage.
