### ISSUE TITLE
Extract first frame from Shaka player

### ISSUE THREAD

**Issue by AdityaSinghShekhawat** [shaka-project/shaka-player#7670]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Not related to FairPlay.

**What version of Shaka Player are you using?**
4.11.11

**What browser and OS are you using?**
All mobile, desktop browsers and system browser for webview.

**Please ask your question**
We are creating a reels (verticle videos) kind of platform using single player. The first frame info is present with player. So, while swipping the next/previous page is blank as there is only single player instance. I have following questions:

1. Does shaka player can extract first frame while preloading?
2. Does shaka player can extract first frame from MPD file?

**Comment by AdityaSinghShekhawat** [comment]
Any update?

**Comment by avelad** [comment]
Shaka delegates the decoding of any video to the browser, so Shaka cannot extract any frames. If the video is not encrypted you could use a canvas to extract a frame and turn it into a png image for example...
