### ISSUE TITLE
Help setting correct TTML Parser for inband Live captions

### ISSUE THREAD

**Issue by stuartflanagan** [shaka-project/shaka-player#7691]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
Latest

**What browser and OS are you using?**
Various TV webOS/Tizen

**Please ask your question**
I am trying to ensure the correct text parser is used for our in-band live captions.
Mp4TtmlParser.
I see captions displayed but no TTML styling Information is used in the display.
Does this need a custom text parser?

**Comment by avelad** [comment]
I think the problem might be with the Text Displayer you are using... See: https://shaka-player-demo.appspot.com/docs/api/tutorial-text-displayer.html

`To configure type 2, you have to call setVideoContainer function before making attach call in the player.`

Does this help you?

**Comment by stuartflanagan** [comment]
Thank you @avelad 
Will try this on Monday and let you know.

Thanks for your help
