### ISSUE TITLE
Playready License Renewal not triggered

### ISSUE THREAD

**Issue by daniel-dias** [shaka-project/shaka-player#7725]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v4.9.5

**What browser and OS are you using?**
Windows 11 and Microsoft Edge 131

**Please ask your question**
I have an app with Shaka Player that plays DASH Streams using DRM Widevine and Playready.
The Licenses have a limited duration and must be renewed every 5 minutes.

With Widevine, all works correctly, the player requests both the Initial License as well as all the Renewal Licenses, and the streams are playing without problems.

But when using Playready (Browser Edge and also Xbox UWP), what is happening is that the Initial License is requested correctly, but after that, the player never requests a Renewal License, resulting with the player throwing an error 6014 - Expired.

Is this behaviour expected with Playready? As far as i know, these Limited Duration Licenses (LDL) whould work with Playready.
I have searched the github issues but didn't find anyone with this particular issue, which seems strange.

As i know the time that the license will expire, is it possible for me to manually trigger a license renewal to the license server?

Regards,
Daniel

**Comment by tykus160** [comment]
@daniel-dias can you try to pass following config on Edge Desktop?

```js
player.configure({
  drm: {
    keySystemsMapping: {
      'com.microsoft.playready': 'com.microsoft.playready.recommendation',
    },
  },
});
```
I'm not sure about recommendation key system, but `com.microsoft.playready` one does not send `license-renewal` events. For this use case we would have to add new config (`timeToRenew` or something like that) and trigger license renewal manually.

There is similar problem on FairPlay btw, see #6280.

**Comment by daniel-dias** [comment]
Hello @tykus160 

I have added the keySystemsMapping config but there is no change on the behaviour.

On the ticket you provided, you have the sugestion: 
```
let renew = Uint8Array.from('renew', c => c.charCodeAt(0));
mediaKeySession.update(renew);
```

Is anything like that possible using DASH with Playready? Triggering a license request whenever i wanted?

Regards,
Daniel

**Comment by tykus160** [comment]
@daniel-dias 
> Is anything like that possible using DASH with Playready? Triggering a license request whenever i wanted?

Yes, but for PlayReady it won't be as straightforward as for FairPlay. You'd probably have to call `MediaKeySession.generateRequest()` manually with lastly seen init data or maybe even create a new session and close the old one.
I can't find any documentation from PlayReady about it unfortunately.
As with ticket I mentioned - unfortunately I don't have capacity and proper DRM environment to develop it on my own, but I'm happy to help in the process.
