### ISSUE TITLE
Shaka player integration with bubble.io's plugin builder

### ISSUE THREAD

**Issue by charTechAccountant** [shaka-project/shaka-player#7727]
I tried to integrate shaka player in bubble.io's plugin builder following shaka player's guide
https://shaka-player-demo.appspot.com/docs/api/tutorial-errors.html

I am getting 6001 error code everytime I load the page

The code is:

function(instance, context) {

const rootElement=instance.canvas[0];
const videoPlayerDiv=document.createElement('div');
rootElement.appendChild(videoPlayerDiv);
let videoPlayer=document.createElement("video");
videoPlayerDiv.appendChild(videoPlayer);
videoPlayer.setAttribute('controls','true');
videoPlayer.muted=true;
videoPlayer.style.padding='3px';
videoPlayer.style.background='#000000';
videoPlayer.style.borderRadius='5px';
let player=new shaka.Player(videoPlayer);

shaka.polyfill.installAll();

player.configure({
	drm: {
		servers: {	'com.widevine.alpha':'https://drm-widevine-licensing.axprod.net/AcquireLicense'}
			}
				});

	player.getNetworkingEngine().registerRequestFilter(function (type,request,context) {
	if (type == shaka.net.NetworkingEngine.RequestType.LICENSE) {
        console.log("request", request);
		request.headers['X-AxDRM-Message'] =				'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjogMSwiY29tX2tleV9pZCI6ICI0N2RlNzMxNC01ZDc5LTRhY2YtYTllMy1iMjBiMDA3OGVlYzEiLCJtZXNzYWdlIjogeyAgInR5cGUiOiAiZW50aXRsZW1lbnRfbWVzc2FnZSIsICAidmVyc2lvbiI6IDIsICAiY29udGVudF9rZXlzX3NvdXJjZSI6IHsgICAgImlubGluZSI6IFsgICAgICB7ICAgICAgICAiaWQiOiAiMzdlZDQ0ZTQtYmUxZS00MjZhLWFkNDQtM2Y5MWZkZmVkNjFmIiAgICAgIH0gICAgXSAgfX19.am39c948yoErhjmaovNjNXmpFR86w3Dv6XJC59b6XjI'
			}
            	});

	player.load('https://s3.ap-southeast-1.wasabisys.com/learnscreenoutput/1234@123.com/Arts/Arts%20And%20Craft/cmaf/manifest.mpd');

**Comment by avelad** [comment]
can you put the result of ` await shaka.Player.probeSupport()`? Thanks!
