### ISSUE TITLE
Temporarily ban layers when a child manifest layer returns 404 in live streaming

### ISSUE THREAD

**Issue by YanpengZhang-HS** [shaka-project/shaka-player#7733]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**Is your feature request related to a problem? Please describe.**

We are facing an issue when streaming live content with Shaka Player. In our setup, we disable high-resolution streams when network conditions degrade (e.g., when bandwidth is limited). When users request the child manifest for a disabled high-res layer, the server returns a 404 error.

The current behavior is that once a 404 is returned for a particular layer (e.g., high-resolution video), Shaka Player does not handle this well and may throw the error. This is problematic because other video layers (e.g., lower-resolution streams) are still available and playable. 

**Describe the solution you'd like**

The player should be able to:
1. Switch to a different available layer when a specific layer returns a 404 error.
2. Continue playing the stream from the available layer, without interruption.
3. After some time, retry the 404 layer to check if it becomes available again (e.g., once bandwidth improves).

**Describe alternatives you've considered**

I found a similar issue, but this is for stream, not for manifest, I think we can make use of this 
https://github.com/shaka-project/shaka-player/issues/1542

**Additional context**

Similar issue before
https://github.com/shaka-project/shaka-player/issues/1542

**Are you planning send a PR to add it?**
Yes, I can help make the changes,  but I'm not sure if there is a more suitable way to implement this modification.

**Comment by avelad** [comment]
For me this is working fine(main branch), I used DASH and HLS, what version are you using?

**Comment by YanpengZhang-HS** [comment]
@avelad I'm using v4.3.7, for segments, if a 404 error occurs, it will indeed switch to another track. However, for the manifest in live stream, if a child manifest returns a 404 error, it does not automatically switch to another layer and request the corresponding manifest
For example, if the manifest request `https://xxx/master_apmf_480_2.m3u8` returns a 404 error, and there is another available layer with the manifest `https://xxx/master_apmf_720_2.m3u8`, it will throw the `NM_1001_404` error instead of switching to the latter one

**Comment by avelad** [comment]
This has been fixed in a higher version, I can't remember which one right now, I recommend you upgrade to a more modern version, see our policy: https://github.com/shaka-project/shaka-player/blob/main/maintained-branches.md
