### ISSUE TITLE
4K + FairPlay + T2 Secure Chip

### ISSUE THREAD

**Issue by hcodes** [shaka-project/shaka-player#7739]
Hello everyone, is it possible to directly or indirectly detect on macOS in Safari the ability to play 4K videos with DRM FairPlay without starting the video? Most likely, it's the T2 Secure Chip, [I haven't found](https://checkdevice.online/en/video/) the exact way to detect it yet, I hope that the Shaka community will help.

Users need to give an answer to the question, "Can I watch 4K video on online services?".

I want there to be more online services in the world that would allow you to watch 4K movies on a desktop. So far, there is only Netflix.

**Comment by joeyparrish** [comment]
You should look into the MediaCapabilities API.  You can query the browser to say "Can you play something that looks like this?" and specify the resolution, framerate, codecs, and key system (DRM).

**Comment by hcodes** [comment]
> You should look into the MediaCapabilities API. You can query the browser to say "Can you play something that looks like this?" and specify the resolution, framerate, codecs, and key system (DRM).

Thanks! I'll look into this API.

**Comment by hcodes** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaCapabilities/decodingInfo#browser_compatibility

configuration.keySystemConfiguration parameter is not supported for Safari. 

Are there any other ways?

@joeyparrish
