### ISSUE TITLE
4.12.2 introduces switching HLS stream to muxed audio track makes player/buffering hang

### ISSUE THREAD

**Issue by markuswolters** [shaka-project/shaka-player#7744]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

N/A

**What version of Shaka Player are you using?**
`v4.12.4`

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
No - Seems to work with v4.12.4-main-22-geff0aef8f

**Are you using the demo app or your own custom app?**
The demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36`

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

uri= `https://sdn-global-streaming-cache.3qsdn.com/7861/files/24/11/26/10859093/7861-Mmc8xvn2T6RVhXH-drm-aes.ism/manifest.m3u8`

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

Using demo site with custom url: [Demo Custom Content](https://shaka-player-demo.appspot.com/demo/#audiolang=de-DE;textlang=de-DE;uilang=de-DE;assetBase64=eyJuYW1lIjoiM3EtVGVzdCIsInNob3J0TmFtZSI6IiIsImljb25VcmkiOiIiLCJtYW5pZmVzdFVyaSI6Imh0dHBzOi8vc2RuLWdsb2JhbC1zdHJlYW1pbmctY2FjaGUuM3FzZG4uY29tLzc4NjEvZmlsZXMvMjQvMTEvMjYvMTA4NTkwOTMvNzg2MS1NbWM4eHZuMlQ2UlZoWEgtZHJtLWFlcy5pc20vbWFuaWZlc3QubTN1OCIsInNvdXJjZSI6IkN1c3RvbSIsImZvY3VzIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJleHRyYVRleHQiOltdLCJleHRyYVRodW1ibmFpbCI6W10sImV4dHJhQ2hhcHRlciI6W10sImNlcnRpZmljYXRlVXJpIjpudWxsLCJkZXNjcmlwdGlvbiI6bnVsbCwiaXNGZWF0dXJlZCI6ZmFsc2UsImRybSI6WyJObyBEUk0gcHJvdGVjdGlvbiJdLCJmZWF0dXJlcyI6WyJWT0QiXSwibGljZW5zZVNlcnZlcnMiOnsiX190eXBlX18iOiJtYXAifSwibGljZW5zZVJlcXVlc3RIZWFkZXJzIjp7Il9fdHlwZV9fIjoibWFwIn0sInJlcXVlc3RGaWx0ZXIiOm51bGwsInJlc3BvbnNlRmlsdGVyIjpudWxsLCJjbGVhcktleXMiOnsiX190eXBlX18iOiJtYXAifSwiZXh0cmFDb25maWciOm51bGwsImV4dHJhVWlDb25maWciOm51bGwsImFkVGFnVXJpIjpudWxsLCJpbWFWaWRlb0lkIjpudWxsLCJpbWFBc3NldEtleSI6bnVsbCwiaW1hQ29udGVudFNyY0lkIjpudWxsLCJpbWFNYW5pZmVzdFR5cGUiOm51bGwsIm1lZGlhVGFpbG9yVXJsIjpudWxsLCJtZWRpYVRhaWxvckFkc1BhcmFtcyI6bnVsbCwidXNlSU1BIjp0cnVlLCJtaW1lVHlwZSI6bnVsbH0=;panel=CUSTOM%20CONTENT;build=compiled)

**What did you do?**

- Updated from Shaka 4.12.1 to 4.12.2 and noticed bug.
- Tried to replicate with demo site (Custom content)
- Selected play
- Switched from preselected German track (separate audio track) to English audio track (muxed audio track)

**What did you expect to happen?**
Audio track should switch to English and playback should continue

**What actually happened?**

Audio track switches to English but after about 20 seconds player stops playing and stays in buffering.

The issue does not happen, if the muxed audio track is preselected before start of first playback. It only happens when switching from a separate audio track to the muxed audio track. Using the trackbar and skipping to another time seems to restart the buffering.

EDIT: Firefox is even more dramatic, it completly stops playback the moment I switch to muxed audio.

EDIT#2: Seems to work with v4.12.4-main-22-geff0aef8f (Tested with [Nightly Demo](https://nightly-dot-shaka-player-demo.appspot.com/demo/#audiolang=de-DE;textlang=de-DE;uilang=de-DE;assetBase64=eyJuYW1lIjoiM1EgdGVzdCIsInNob3J0TmFtZSI6IiIsImljb25VcmkiOiIiLCJtYW5pZmVzdFVyaSI6Imh0dHBzOi8vc2RuLWdsb2JhbC1zdHJlYW1pbmctY2FjaGUuM3FzZG4uY29tLzc4NjEvZmlsZXMvMjQvMTEvMjYvMTA4NTkwOTMvNzg2MS1NbWM4eHZuMlQ2UlZoWEgtZHJtLWFlcy5pc20vbWFuaWZlc3QubTN1OCIsInNvdXJjZSI6IkN1c3RvbSIsImZvY3VzIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJleHRyYVRleHQiOltdLCJleHRyYVRodW1ibmFpbCI6W10sImV4dHJhQ2hhcHRlciI6W10sImNlcnRpZmljYXRlVXJpIjpudWxsLCJkZXNjcmlwdGlvbiI6bnVsbCwiaXNGZWF0dXJlZCI6ZmFsc2UsImRybSI6WyJObyBEUk0gcHJvdGVjdGlvbiJdLCJmZWF0dXJlcyI6WyJWT0QiXSwibGljZW5zZVNlcnZlcnMiOnsiX190eXBlX18iOiJtYXAifSwibGljZW5zZVJlcXVlc3RIZWFkZXJzIjp7Il9fdHlwZV9fIjoibWFwIn0sInJlcXVlc3RGaWx0ZXIiOm51bGwsInJlc3BvbnNlRmlsdGVyIjpudWxsLCJjbGVhcktleXMiOnsiX190eXBlX18iOiJtYXAifSwiZXh0cmFDb25maWciOm51bGwsImV4dHJhVWlDb25maWciOm51bGwsImFkVGFnVXJpIjpudWxsLCJpbWFWaWRlb0lkIjpudWxsLCJpbWFBc3NldEtleSI6bnVsbCwiaW1hQ29udGVudFNyY0lkIjpudWxsLCJpbWFNYW5pZmVzdFR5cGUiOm51bGwsIm1lZGlhVGFpbG9yVXJsIjpudWxsLCJtZWRpYVRhaWxvckFkc1BhcmFtcyI6bnVsbCwidXNlSU1BIjp0cnVlLCJtaW1lVHlwZSI6bnVsbH0=;panel=CUSTOM%20CONTENT;build=compiled)

![image](https://github.com/user-attachments/assets/ea53c743-0ae2-4980-82d3-12cfa26182f3)

Actually we're now trapped, as we need the latest update to support all Apple devices due to bug https://github.com/shaka-project/shaka-player/issues/7666 and also all of our videos use muxed audio, so we rely on at least 4.12.0 due to fixed bug https://github.com/shaka-project/shaka-player/issues/5836 

**Are you planning send a PR to fix it?**
No

**Comment by markuswolters** [comment]
Seems to work with nightly main build (v4.12.4-main-22-geff0aef8f) Was there anything fixed with that?

**Comment by tykus160** [comment]
@markuswolters it's possible it has been already fixed in https://github.com/shaka-project/shaka-player/pull/7700

**Comment by joeyparrish** [comment]
I'll prep a new 4.12 release and we can see if cherry-picking #7700 resolves it.

**Comment by joeyparrish** [comment]
See https://github.com/shaka-project/shaka-player/pull/7754 and the upcoming 4.12.5 release.

**Comment by joeyparrish** [comment]
4.12.5 is out, and includes #7700.  Please let us know it helps.
