### ISSUE TITLE
Airplay just working with Apple TV Box

### ISSUE THREAD

**Issue by markuswolters** [shaka-project/shaka-player#7746]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**

4.11.9, 4.12.4

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
Safari tested on different iPhone, iPad and Mac with a number of AirPlay devices (Apple, LG, Samsung)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

HLS content on demo

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

Demo

**What did you do?**

- Selected HLS content on the Demo site
- Hit play
- Selected AirPlay from sub menu
- Selected AirPlay device

**What did you expect to happen?**
- After selecting AirPlay device, player should connect to remote device and start play back 

**What actually happened?**

Most of the time, only the Music-play icon is displayed on the device. After some playing around with turning off AirPlay and turning on again it may work. Then a switch of sub titles or audio tracks will stop playback or connection lost completly.

It works fine when HLS link is entered directly into Safari. It also works well with other players, like those based on video.js.

Using a Apple TV Box, content plays well, however, the tracks and subtitles are only switchable via native TV UI.

Any hints or tips what we can try?

**Are you planning send a PR to fix it?**
No

**Comment by avelad** [comment]
This is a Safari and AirPlay issue... :(
I already reported it to the webkit repo: https://bugs.webkit.org/show_bug.cgi?id=281853
Why does it work on other players? Because by default we use MSE for HLS-Clear, and the AirPlay implementation for MSE is buggy on Safari. If you change to use src= to play the HLS content, everything works fine... (streaming.preferNativeHls config)

**Comment by markuswolters** [comment]
@avelad I see two parameters in streaming config,  preferNativeHls and useNativeHlsOnSafari. Can you quickly describe, what they do and what I should set them to?

**Comment by avelad** [comment]
useNativeHlsOnSafari is deprecated, so you should use preferNativeHls

preferNativeHls -->` If true, prefer native HLS playback when possible, regardless of platform.`

**Comment by markuswolters** [comment]
@avelad Thanks, setting preferNativeHls fixed all of our issues on iOS!! But it turned out - That setting breaks Android! We don't get any audio and the language and subtitle buttons are missed. When I set preferNativeHls to false, it runs on Android. Is that something which needs to be added as a bug? Is there a quick fix so we can turn on native HLS only for iOS devices?

**Comment by markuswolters** [comment]
Does anybody have a reliable browser detection snippet at hand to conditionally set preferNativeHls  only on iOS?
