### ISSUE TITLE
Chromecast Ultra h265 DRM support question

### ISSUE THREAD

**Issue by murrumbidgee63** [shaka-project/shaka-player#7759]
Hi, Just wondering if Shaka player on Chromecast Ultra should support h265 with DRM fully using BuyDRM we are testing with a video that is failing when cast to a custom chromecast receiver! The error I receiver is Shaka error 6001 on the remote console connected to my custom chromecast receiver! 
Test video 1080/h265/drm https://iview-vod.akamaized.net/stage/new/NEWS2024104705682/20241211095126/mpegdash-h265/1080.mpd
Any advice on this would be appreciated,

Marc Howard
marc.howard@abc.net.au

**Comment by joeyparrish** [comment]
It depends entirely on device support.  Shaka Player uses standard web APIs to negotiate with the device on codec, container, and DRM support (and all three in combination).

If a Chromecast Ultra supports H265, and you're using Widevine, it should work.  (All Chromecast devices support Widevine DRM.)  If it doesn't work, check device support for the codec, specifically in combination with the codec profile, resolution, etc.  Product documentation may help with that.  (I hope.)

Does this help?
