### ISSUE TITLE
Can headers be added to the fetched media file when adding a custom interstitial?

### ISSUE THREAD

**Issue by salvdev** [shaka-project/shaka-player#7763]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

Not related to FairPlay

**What version of Shaka Player are you using?**
4.12.3

**What browser and OS are you using?**
Chrome, windows 10

**Please ask your question**
I've been following the documentation located here: https://shaka-player-demo.appspot.com/docs/api/tutorial-ad_monetization.html
on how to add custom interstitials.

```
adManager.addCustomInterstitial({
  id: '1',
  startTime: 0,
  endTime: null,
  uri: 'example.com/ad.mp4',
  mimeType: null,
  isSkippable: true,
  skipOffset: 10,
  canJump: false,
  resumeOffset: null,
  playoutLimit: null,
  once: true,
  pre: true,
  post: false,
  timelineRange: false,
});
```

So far everything has been working well. Ads play when they are supposed. What I am trying to figure out is how to add headers to the media file request in the `uri`  property. 

I have tried using the network engine as followed:

```
  this.player.getNetworkingEngine()?.registerRequestFilter(function (type, request) {
	  if (
		  type === shaka.net.NetworkingEngine.RequestType.MANIFEST ||
		  type === shaka.net.NetworkingEngine.RequestType.LICENSE
	  ) {
		  return
	  }
	  request.headers['Authorization'] = `Bearer test`
  })

```
The Authorization header is added to all requests except the request for the ad file in the `uri` property. I console.logged all requests and I can see all requests appearing in the network engine except the request related to this uri file. It doesn't seem to appear at all.

Is it possible to add headers to this file request?

**Comment by avelad** [comment]
This is not currently possible, but I'm going to work on exposing the player in some way so you can add any headers you want.
