### ISSUE TITLE
Can this player directly play an H.264 video stream that is not encapsulated in an MP4 container, with the video stream being pushed in real-time via WebSocket?

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [shaka-project/shaka-player#7764]
**Can this player directly play an H.264 video stream that is not encapsulated in an MP4 container, with the video stream being pushed in real-time via WebSocket?**

**Comment by joeyparrish** [comment]
No, sorry.  It's long, but you'll find that the README has details on what we support.  It's primarily for DASH & HLS, which are at a higher level than the MP4 container.

To deal directly with H.264 and no container, check out the WebCodecs API.
