### ISSUE TITLE
Setting preferNativeHls breaks Android. Bug or on purpose?

### ISSUE THREAD

**Issue by markuswolters** [shaka-project/shaka-player#7771]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**
4.12.4

**What browser and OS are you using?**
Chrome on Android and Android webview

**Please ask your question**
To get AirPlay working, it's required for us to activate preferNativeHls in the shaka streaming config. However, we discovered, that this breaks Android: no audio playback, language and subtitle buttons are missing and playback stops after a while. When I set preferNativeHls to false, it runs on Android.

Is that something which needs to be added as a bug? The only only quick fix I have in mind currently is activating preferNativeHls only for iOS devices via a browser detection. Does anybody have a reliable browser detection of iOS at hand?

**Comment by markuswolters** [comment]
This seems to work now:

`		var preferNativeHls = false;

		if (window.WebKitPlaybackTargetAvailabilityEvent)
			preferNativeHls = true;`

**Comment by tykus160** [comment]
@markuswolters native HLS playback is still under development in Chrome: https://issues.chromium.org/issues/40057824
I guess Chrome Android already claims it can play it, by support is limited. I'll tryo to confirm it later.

**Comment by avelad** [comment]
```
 * @property {boolean} preferNativeHls
 *   If true, prefer native HLS playback when possible, regardless of platform.
 *   <br>
 *   Defaults to <code>false</code>.
```

The configuration is for any platform, if you want it to only apply to iOS for example, you can use something like this.

```
function isIOS() {
  if (/(?:iPhone|iPad|iPod)/.test(navigator.userAgent)) {
    return true;
  }
  return false;
}

player.configure('streaming.preferNativeHls', isIOS());
```
