### ISSUE TITLE
Can we add custom style to captions rendered shaka.text.UITextDisplayer?

### ISSUE THREAD

**Issue by rabinmahato** [shaka-project/shaka-player#7796]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes. I have tried to add plugin for shaka.text.UITextDisplayer. It didn't work. After I added the plugin the subtitles are not rendering nat all.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the question is related to FairPlay, have you read the tutorial?**

No

**What version of Shaka Player are you using?**
4.3.6

**What browser and OS are you using?**
Chrome Version 131.0.6778.205

**Please ask your question**
Can we add custom style to captions rendered shaka.text.UITextDisplayer? 
Please help me to create a plugin for shaka.text.UITextDisplayer so that I can my custom styles to the subtitle dom wrappers.

**Comment by avelad** [comment]
Currently not possible, sorry!

**Comment by rabinmahato** [comment]
@avelad ,
Can you please help me to create a custom plugin for shaka.text.UITextDisplayer so that I can my custom styles to the subtitle DOM wrappers?

**Comment by avelad** [comment]
Documentation: https://nightly-dot-shaka-player-demo.appspot.com/docs/api/tutorial-plugins.html (section `Subtitle/caption displayers`)

You can use the code from https://github.com/shaka-project/shaka-player/blob/main/lib/text/ui_text_displayer.js and change it with your styles, but we don't have a tutorial as such to do your customization.
