### ISSUE TITLE
Deprecation Warning and Subtitle Error on Updating to v4.12.5

### ISSUE THREAD

**Issue by sertacars** [shaka-project/shaka-player#7803]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**If the problem is related to FairPlay, have you read the tutorial?**

Not related to FairPlay.

**What version of Shaka Player are you using?**

4.12.5

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Custom app

**If custom app, can you reproduce the issue using our demo app?**
No, there is no warning or error in shaka player demo app.

**What browser and OS are you using?**
Chrome - macOS Sonoma

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
Not using

**What are the manifest and license server URIs?**

Manifest: https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8
No need license server URI.

**What configuration are you using?  What is the output of `player.getNonDefaultConfiguration()`?**

{
    "streaming": {
        "rebufferingGoal": 10,
        "bufferingGoal": 25
    },
    "abr": {
        "restrictions": {
            "maxHeight": 720
        }}
}

**What did you do?**

- Updated Shaka Player from v4.7.3 to v4.12.5.
- Using a UITextDisplayer in the player configuration.
- Attempted to change subtitles during playback.

**What did you expect to happen?**
- No deprecation warnings in the console.
- Subtitles should switch without any errors.

**What actually happened?**

- Warning appears regarding UITextDisplayer.
<img width="469" alt="Screenshot 2024-12-24 at 11 05 13" src="https://github.com/user-attachments/assets/ab2a7a0a-88ff-4b7a-943d-5293a41b08a3" />

I understand the warning is about the deprecation, but clear documentation or examples for the migration process would be helpful.

- Subtitle changes sometimes fail, causing a TypeError.
<img width="445" alt="Screenshot 2024-12-24 at 11 05 56" src="https://github.com/user-attachments/assets/4216c783-d0ef-49e4-8931-851f40fedfff" />

This error does not occur consistently. Sometimes subtitles change successfully without error when attempting to change subtitles.

**Are you planning to send a PR to fix it?**
No

**Comment by avelad** [comment]
I've been thinking about it and the warning is not really necessary, because we configure it later, so I'm going to remove it. I haven't been able to reproduce the SimpleTextDisplayer error, but I'll put some guards so that it doesn't happen.

**Comment by sertacars** [comment]
> I've been thinking about it and the warning is not really necessary, because we configure it later, so I'm going to remove it. I haven't been able to reproduce the SimpleTextDisplayer error, but I'll put some guards so that it doesn't happen.

Thank you for addressing the warning and adding guards for the SimpleTextDisplayer issue. Should I update anything in my integration to avoid potential errors?

Thanks again for your support!

**Comment by avelad** [comment]
With my change it would not be necessary for you to change anything :)

**Comment by sertacars** [comment]
Got it, thank you for the clarification and the quick fix! :)
