### ISSUE TITLE
How to find which chunk (url) are playing?

### ISSUE THREAD

**Issue by theifish** [shaka-project/shaka-player#857]
Hi.

I need to check which chunk are playing and get event when it changed. 
I couldn't find such functionality in Docs.
Could you help me, are there in Shaka any methods/events for this?

**Comment by ismena** [comment]
Hi @theifish,
Let me make sure I understand you correctly: you would like to know when a new segment is being played even if just a different segment of the same media stream (meaning, nothing changed in terms of bit rate, language, frame rate etc.) Is that right?

**Comment by theifish** [comment]
Yes, I want to know which segment are now actually playing in video stream (depends on its timing, bitrate and other params).

**Comment by joeyparrish** [comment]
We don't have an API for this currently.  Could you help us understand the reason for this functionality?  Why is it useful to know that in your application?

**Comment by theifish** [comment]
We use P2P for chunks (lib replaces global XHR object), and we need to know if current playing chunk loaded over P2P or from CDN to gather statistics.

**Comment by joeyparrish** [comment]
Instead of replacing global XHR, I would strongly recommend replacing Shaka Player's HTTP implementation instead.  Our HTTP implementation is just a default plugin.  You can register your own HTTP plugin and replace ours.  See [lib/net/http_plugin.js](https://github.com/google/shaka-player/blob/b5cbc010/lib/net/http_plugin.js).  You simply have to provide a method which takes a URI and a `Request` object and returns a Promise to a `Response` object.  Then register it as you see at the bottom of our default plugin:

```js
shaka.net.NetworkingEngine.registerScheme('http', P2PHttpPlugin);
shaka.net.NetworkingEngine.registerScheme('https', P2PHttpPlugin);
```

Would this more direct integration help at all with your stats gathering?

**Comment by theifish** [comment]
Of course it's a good idea to use HTTP plugin replacement instead of global XHR replacing, however we use third-party company solution and it takes a time to develop this replacement for them.
Anyway, it doesn't resolve our needs, the statistic based on current playing chunk state (not loading).

**Comment by joeyparrish** [comment]
We don't have anything like this today.  I've marked it as an enhancement and added it to the backlog.  If you would like to submit a PR, I would be happy to talk design.

**Comment by maxbaluev** [comment]
@theifish Do not worry about it. We will provide the ready plug-in next week.

**Comment by theifish** [comment]
Hi @maxbaluev.

Did you publish new plug-in? More than one week passed yet :)

**Comment by joeyparrish** [comment]
I just came across this again after a long time, and I thought it might be useful to give an update.

I don't know what @maxbaluev was referring to, but there is currently no support in Shaka Player for determining the currently-displayed segment.  This would require us to track which segments correspond to which buffer positions, which we currently do not do.

This is still an open feature request in our backlog.  I'll post an update here when the work is scheduled.  In the mean time, we're always open to suggestions on how to design/implement this.

**Comment by gzlock** [comment]
I know the VOD video can use videoElemnt.currentTime get the length of time that has been played
But I want to know what time to display subtitles in the live video
For example:
A live show and use websocket to push subtitles to users
Two visitors named A and B, and they start watching the live show at different time
A's network ver fast, just watch the live video in just a few seconds of buffer time
But B need to waited a few minutes of buffer time to watch the live show
Now, A and B at the same time watching the different video content
So I want to has a event to listen which video segment is playing to display subtitle
Look like this:
```js
player.on('FRAG_CHANGED', (fragment)=>{
   // use fragment.id to get the subtitle content and display it
})
```

**Comment by joeyparrish** [comment]
If your subtitles have timing information, you don't need to know what segment is displayed.  You just need to know what time to display the subtitle, and the current time for the video.  As you point out, you can get the current video time from `video.currentTime`.

I don't see any reason the currently-displayed segment URL or segment number is necessary for subtitle display.

**Comment by gzlock** [comment]
My "subtitle" it mean the danmaku (Japanese, it flow up on the video like
subtitle), it post from other visitors of the live show, so the danmaku
not contain the video time data

Joey Parrish <notifications@github.com> 于 2019年9月12日周四 上午6:08写道：

**Comment by joeyparrish** [comment]
If someone sends a message during the show, couldn't you attach the timestamp of that user's video element when you send it to the other users?  So that they see it at the same point in the presentation where the original user was when they sent it?

**Comment by avelad** [comment]
Is anyone interested in seeing this supported?
