### ISSUE TITLE
Support multiple trick-play tracks

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#872]
DASH manifests can supply multiple trick-play tracks.  We currently only use one.

With multiple tracks, we could choose one based on framerate vs playbackRate, max playout rate vs playbackRate, or resolution & bandwidth.  More research is needed to learn how trick play tracks differ when there are multiple, and to decide what the decision making process will be for Shaka when we choose between them.  We also need to design changes to our internal structures to accommodate this extra information.

**Comment by avelad** [comment]
Is anyone interested in this functionality?
