### ISSUE TITLE
No key status on 2017 Tizen TVs

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#891]
There seems to be no key status information on 2017 Tizen TVs.  This causes a timeout in one of our DRM integration tests, but more concerning is that we may not be able to make the right decisions for some content without this information.

We need to:

1. File a bug against Samsung
2. Work around the test failure
3. Work around any content issues that arise from this

This is related to #884 for 2016 TVs, in which the EME polyfill sends out a fake key status event, but without any valid key IDs in it.  We must solve #884 in order to work without key status information.  The difference with 2017 TVs is that there is no polyfill and no key status event at all.

**Comment by chrisfillmore** [comment]
Fyi I have both a 2016 and 2017 TV now if I can assist with troubleshooting.

**Comment by joeyparrish** [comment]
Work-arounds are in place now, but we still have not been able to file bugs against Samsung/Tizen.  Having trouble getting an account on their JIRA instance.

**Comment by chrisfillmore** [comment]
Yes I tried that too and also couldn't get an account. I'll talk to Samsung and get in touch with you.

**Comment by joeyparrish** [comment]
Work-arounds have been cherry-picked and will be released in v2.1.5.

**Comment by EloB** [comment]
Did you managed to run any drm on Tizen 2017/2016 and have a stable playback?

**Comment by chrisfillmore** [comment]
@EloB in general protected playback with Shaka works on Tizen 2017 TV's and newer. The implementation of EME on 2016 model TV's is extremely buggy, and I would caution you against trying to support that platform.

**Comment by joeyparrish** [comment]
Samsung will never fix this, so there's no need for us to continue tracking it.  I'm closing it now.
