### ISSUE TITLE
Predict next segment in DASH SegmentTimeline

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#898]
It has come up many times that `<SegmentTimeline>` requires the manifest to be refreshed for the player to know about new segments.  (See [this issue comment](https://github.com/google/shaka-player/issues/578#issuecomment-260515320) or [this list post](https://groups.google.com/d/msg/shaka-player-users/YV5wk1nZJrE/R8cf65wpAgAJ).)

I don't recall who gave me this idea, and I can't find the conversation on github or in the mailing list, so it may have come up during a [CWIP class](http://www.widevine.com/cwip/).  It should be feasible for us to predict what the next segment would look like in a way that is likely to be accurate enough to keep the user from buffering.

For example, if the last segment described in `<SegmentTimeline>` has a duration of 4096, we could simply assume the next one would be as well.  Or we could be more conservative and assume that if the last N segments had the same duration, the next one would as well.

This would allow us to survive better with DASH content whose `suggestedPresentationDelay` and `minimumUpdatePeriod` parameters are not well-tuned.

**Comment by avelad** [comment]
There is no comment on this since the issue was created 7 years ago, is anyone still interested in this? Otherwise in 7 days the issue will be closed.
