### ISSUE TITLE
HLS: Add support for EXT-X-SESSION-KEY tag

### ISSUE THREAD

**Issue by ismena** [shaka-project/shaka-player#917]
The EXT-X-SESSION-KEY tag tag allows encryption keys from Media Playlists to be specified in a Master Playlist.  This allows the client to preload these keys without having to read the Media Playlist(s) first.

https://tools.ietf.org/html/draft-pantos-http-live-streaming-20#section-4.3.4.5

**Comment by ismena** [comment]
Prompted by #914

**Comment by mlevkov** [comment]
Has this, by any chance, been implemented yet?

**Comment by michellezhuogg** [comment]
@mlevkov , this is not implemented yet. We welcome contributions from the community!

**Comment by tdevittcarol** [comment]
FYI - https://github.com/shaka-project/shaka-player/pull/4568
