### ISSUE TITLE
Ability to specify startTime for "load" as Date

### ISSUE THREAD

**Issue by ondrejpar** [shaka-project/shaka-player#936]
Hi, this is closely related to #356 . I need to start live playback from a certain point in time. However, I don't know in advance what seek range will Shaka use after loading the stream, thus I don't know what value should I use for startTime parameter. It would be great if I could just specify Date here, and Shaka would calculate the correct position, using manifest information. Does this seem possible?

**Comment by joeyparrish** [comment]
It seems reasonable.  I think we have enough information for this, but a `Date` object would only be translatable into a presentation time for live content.  It would be meaningless for VOD, as the presentation timeline for VOD is not anchored in any way to date & time.

**Comment by ondrejpar** [comment]
In the meantime: can we use onStreamLoaded event handler,  perform the calculation described in #356 (which is a temporary hack itself, I know) and set the position from inside the handler? Or is there any race condition to be aware of?
I understand that this workaround is suboptimal, as it will start playing on the live edge and immediately seek to the desired position, but it's better than nothing.

**Comment by joeyparrish** [comment]
For live streams, with no start time specified in `player.load()`, the playback start time is calculated by `Playhead`.  `Playhead` is created in the middle of the Promise chain in `load()`, and it won't listen to `'seeking'` events until `'loadedmetadata'` fires.  So any seek you perform before `'loadedmetadata'` will essentially be overridden by `Playhead` during startup.

`player.seekRange()` should start working as soon as the manifest is parsed, which is earlier than the creation of `Playhead`.  So by the time `Playhead` would permit you to seek, you can use `seekRange()` to decide where to go.  You can also use `getPlayheadTimeAsDate()` as soon as the manifest is parsed.

I suggest waiting either until `load()` is resolved, or until after `'loadedmetadata'` is fired.  (Note that I haven't tried any of these suggestions myself, so YMMV.)

```js
function seekToDate(targetDate) {
  var playheadDate = player.getPlayheadTimeAsDate();
  var offsetMilliseconds = targetDate.getTime() - playheadDate.getTime();
  video.currentTime += offsetMilliseconds / 1000;
}

// Option 1, wait for load() to complete
player.load(manifestUri).then(function() {
  seekToDate(targetDate);
});

// Option 2, wait for 'loadedmetadata'
function onLoadedMetadata() {
  video.removeEventListener('loadedmetadata', onLoadedMetadata);
}
video.addEventListener('loadedmetadata', onLoadedMetadata);
```

Does this help?

**Comment by ondrejpar** [comment]
Turns out that the dates reported in stream are bogus (randomly shifted by few seconds), so we decided to go with another approach.We use `shakaPlayer.manifest_.presentationTimeline.getEarliestStart()` to determine the lowest accessible timestamp and go from there. (We don't have getPlayheadTimeAsDate on Shaka 2.0)
I can confirm that this information is available when `loaddata` is called. We don't use `loadmetadata`.

**Comment by perqa** [comment]
With the introduction of ShakaPlayer 3, the method `updateStartTime` was introduced:

**updateStartTime(startTime)**
Provides a way to update the stream start position during the media loading process. Can for example be called from the manifestparsed event handler to update the start position based on information in the manifest.

Although it's not exactly what this ticket requests, it seems like it could be used in the same way.
